### ISSUE TITLE
[BUDI-6744] Uncaught TypeError: Cannot read properties of undefined (reading 'ROWS')

### ISSUE THREAD

**Issue by BellBoy68** [Budibase/budibase#10021]
Hello, I ran into a problem:
When I try to create a template in the budibase cloud, I got the following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'ROWS')
```
Filename: budibase-client.js?v=2.4.25
![image](https://user-images.githubusercontent.com/127862266/225022610-6d72aca0-e903-46ea-b511-bd7e4ed5efae.png)

How to solve??

<sub>[BUDI-6744](https://linear.app/budibase/issue/BUDI-6744/uncaught-typeerror-cannot-read-properties-of-undefined-reading-rows)</sub>

**Comment by shogunpurple** [comment]
Hi @BellBoy68 - this should now be resolved.

**Comment by BellBoy68** [comment]
Thank you wery much. It's working now.
