### ISSUE TITLE
[BUDI-6748] Relationship postgres

### ISSUE THREAD

**Issue by holgerbermeo** [Budibase/budibase#10030]
hello.  I am using the version as of today 03/14/2023, I have a question since I have made two relations in a table and while in one the data appears in text (automatically because I do not see where to configure that) in the other just gives me the code.  what could that be due to?

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/9d899cb5-1fc3-4738-9880-e69ac1309f9f/d34451f5-78ab-4bd3-b22a-fd87c73d3803)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/181198ab-ed62-4347-ac62-55143b884882/4449e617-8f8d-4159-bce0-88f2669b7b98)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/0f55e1e1-76fc-416e-8fb3-ff4be5d4006e/e48c4271-f2dd-4143-9c1f-f4c918dcdbd1)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/1de16e96-a108-4d3c-a096-d7882d65e0e4/6541c6fa-d586-425d-a22f-8d7d56d4570d)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f6788630-2b17-4fdb-bebe-716d1be31aaf/43b05842-9776-4bcf-ba39-d6555f815aba)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ec62173d-8dd2-456e-bee9-459bb916bd4a/aeea061b-c9c4-4314-a187-234cf95f1d5b)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6748](https://linear.app/budibase/issue/BUDI-6748/relationship-postgres)</sub>

**Comment by mike12345567** [comment]
Hi @holgerbermeo this is due to the "Display" column for the related table. You can go into the Data UI for the table which is displaying numbers instead of text and edit the column you would like to be displayed for that relationship, setting it as as display column. https://docs.budibase.com/docs/budibasedb#selecting-the-display-column
