### ISSUE TITLE
"List View" autogenerated screen does not remove relations when unselected in the relationship picker

### ISSUE THREAD

**Issue by dominikjannis** [Budibase/budibase#10041]
Hi everyone,
today i discovered that the autogenerated screens with the side panels do not delete existing many to many relations in my attached PostgreSQL db. Adding new ones with the relationship picker works fine and the present ones are displayed correctly, but unselecting them in the drop down does not remove them after clicking save. Is there anything that i may be missing, or is this a bug?
Thanks!

**Comment by dominikjannis** [comment]
I just found [this](https://github.com/Budibase/budibase/discussions/5870) old discussion where a similar / the same error was already described, but never resolved as it seems

**Comment by melohagan** [comment]
Hey @dominikjannis 

Could you please follow the bug template, providing screenshots and reproduction steps.

Closing for now, thanks!
