### ISSUE TITLE
[BUDI-6766] Table Component: 'On Row Click' shows as undefined in conditional

### ISSUE THREAD

**Issue by mp-strachan** [Budibase/budibase#10045]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Self hosted business
  - Budibase Version: 2.4.4
  - App Version: 2.4.4

**Describe the bug**
"On Row Click" shows as undefined in the update setting drop down

**To Reproduce**
1. Create a table
2. Edit conditional settings
3. Create a condition
4. Set to "Update Setting"
5. Setting type has a "Undefined" in dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/26296076/225548876-271b0c7b-3085-4881-a50a-a61c436f5273.png)
![image](https://user-images.githubusercontent.com/26296076/225548931-524993c4-d702-446b-9782-a2d9f51b854f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome

<sub>[BUDI-6766](https://linear.app/budibase/issue/BUDI-6766/table-component-on-row-click-shows-as-undefined-in-conditional)</sub>

**Comment by aptkingston** [comment]
Thanks for reporting @mp-strachan! I've got a PR up to fix this :+1:
