### ISSUE TITLE
Forgot/Reset Password Flow

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1005]
https://discord.com/channels/733030666647765003/735083509202419778/801058091784339496

- Admins should be able to reset their users passwords
- Forgot password flow for end users
- SMTP configuration in budibase applications

**Comment by timconsidine** [comment]
Looking forward to this.
Essential functionality for any user-based app.
Worked out how to do it manually in an emergency.
Would love to have it as integrated functionality.
