### ISSUE TITLE
[BUDI-6769] I can't delete a row in Users database if I deleted this user in budibase administration 

### ISSUE THREAD

**Issue by Flashpok** [Budibase/budibase#10069]
**Checklist**
- [ x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version:2.4.8
  - App Version: 2.4.8

**Describe the bug**

I can't delete a row in Users budybase database (In my application)  if I delete User in budibase administration 

**To Reproduce**
1. to create a user in main administration portal.
2. Assign an application to this user.
1. To delete this user in main administration portal.

**Expected behavior**
If I delete in the main portal, the user row in my application must be deleted. But the user row remain visible and can't be deleted.

I hope it can be resolved.
Thank you for Budibase. It's a fantastic app ! Love openSource

<sub>[BUDI-6769](https://linear.app/budibase/issue/BUDI-6769/i-cant-delete-a-row-in-users-database-if-i-deleted-this-user-in)</sub>

**Comment by Flashpok** [comment]
up

**Comment by shamoon** [comment]
I just ran into this yesterday, can I ask why it was closed as not planned? 

For me the users were created in an automation which seems easy enough but then they can’t be deleted. I had to create a dummy screen in my app to do this…

**Comment by melohagan** [comment]
@aptkingston That comment was never synced to GitHub FYI

The issue is closed anyway, although someone was recently complaining about it again.

**Comment by Flashpok** [comment]
No help about this. ?It seems so important to me.

**Comment by mike12345567** [comment]
Hi @Flashpok and @shamoon - I'm currently working on a re-write of the user sync to apps which can be followed here: https://github.com/Budibase/budibase/issues/10216

Sorry for this being closed without message - we have another platform we track issues on and it must not have sync'd our comment. I'll keep it closed as we have an issue to track the implementation of the new system for this.

For now, if you're working in self host, you can delete user documents directly from your app database, by going to `<local URL>/db/_utils/#` and logging in with your CouchDB credentials.

You can then find the app databases which need fixed, they will start with `app_` and `app_dev` - like so:
![image](https://user-images.githubusercontent.com/4407001/230336909-3cef4267-c194-4853-931a-ce77dd25aa26.png)

You can go into these databases, and find the `ro_ta_users_us_....` documents, you can look into these to work out which ones need to be removed.
![image](https://user-images.githubusercontent.com/4407001/230337080-b485aebb-294d-4911-8d78-035491f43551.png)

The new system will take better care of the synchronisation of the global users with their metadata in apps, based on the roles and groups they have access to, but is quite a large re-write so may take some time to finish.

**Comment by shamoon** [comment]
Thanks for the instructions and for clarifying!
