### ISSUE TITLE
[BUDI-6770] Configuration of environment variable TEMPLATES_BUCKET_NAME is missing in Helm Chart

### ISSUE THREAD

**Issue by rgelsi** [Budibase/budibase#10065]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: k8s
  - Budibase Version: 2.4.31
  - App Version: 2.4.31

**Describe the bug**
It is not possible to configure the environment variable TEMPLATES_BUCKET_NAME with the Helm chart.
In the chart templates app-service-deployment.yaml and worker-service-deployment.yaml the following two lines are missing:

```yaml
        - name: TEMPLATES_BUCKET_NAME
          value: {{ .Values.services.objectStore.templatesBucketName | quote }}
```

**Expected behavior**
Deployment through the Helm Chart should set the environment variable TEMPLATES_BUCKET_NAME with a custom value

**Desktop (please complete the following information):**
 - OS: RHEL Linux
 - Browser Chrome

<sub>[BUDI-6770](https://linear.app/budibase/issue/BUDI-6770/configuration-of-environment-variable-templates-bucket-name-is-missing)</sub>

**Comment by melohagan** [comment]
Will be solved in this PR: https://github.com/Budibase/budibase/pull/12650
