### ISSUE TITLE
The automation trigger is missing a placeholder

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1007]
**Describe the bug**
There is no placeholder in the box which makes it hard to know what to type in, or if it's even possible to type anything.

![Screenshot 2021-01-21 at 16 02 22](https://user-images.githubusercontent.com/49767913/105376948-32637180-5c02-11eb-8a13-dad06c32279f.png)

**Comment by yashank09** [comment]
Hi @joebudi ! If I could get some more context as to where the placeholder is supposed to be etc., I would like to see if I can fix this :)

**Comment by mjashanks** [comment]
Hey @yashank09 

The placeholder should be here:

![image](https://user-images.githubusercontent.com/3524181/106240546-59bacf80-61fc-11eb-895f-5a29d6750c41.png)

The red outline is an input, that should say "Enter field name".

Would be great if you could do that one :)

**Comment by shogunpurple** [comment]
Solved in https://github.com/Budibase/budibase/pull/1047. Thanks again @yashank09
