### ISSUE TITLE
[BUDI-6778] Rest API Connector POST and PATCH Issues

### ISSUE THREAD

**Issue by reedwi** [Budibase/budibase#10098]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: obogroup

**Describe the bug**
I am using the Rest API connector to connect to the HubSpot API. I imported the endpoints through the OpenAPI specs and am very well versed in the HubSpot API in general and the required formats. I have gotten GET requests to work, but I am now trying to run a PATCH and POST request. Both are failing. I have ensured the format of the body in the builder is correct by using Postman and running the exact same request. Everything in the general query builder setup seems to be correct. Are there any known issues potentially on the conversion of JSON > string? This seems to be the only possible thing I am running into. Are there any workarounds to this

**Expected behavior**
Expecting there to be a successful request, but I am getting a 400 error and the request isn't even making it to the API.

**Screenshots**
<img width="1127" alt="Screenshot 2023-03-22 at 12 40 30 PM" src="https://user-images.githubusercontent.com/65463278/226976257-d40a9916-9ab1-4381-9dc4-12cdaf96bf32.png">

**Desktop (please complete the following information):**
 - OS: Mac Ventura
 - Browser: Chrome
 - Version: 111.0.5563.64

<sub>[BUDI-6778](https://linear.app/budibase/issue/BUDI-6778/rest-api-connector-post-and-patch-issues)</sub>

**Comment by shogunpurple** [comment]
Need to test if PATCH and POST work for other API specs or if this is specific to hubspot.

**Comment by mike12345567** [comment]
Hi @reedwi I replicated this exactly with the Hubspot OpenAPI (https://api.hubspot.com/api-catalog-public/v1/apis/crm/v3/objects/contacts) and tried in a few different environments, I was unable to recreate the scenario above:
![image](https://user-images.githubusercontent.com/4407001/228295428-8a470b5c-3910-4cc1-923e-077777bed12c.png)
