### ISSUE TITLE
[BUDI-6779] Google sheets: Sheet has a space in the name, Budibase cant show the data

### ISSUE THREAD

**Issue by virus2016** [Budibase/budibase#10097]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker single image 
  - Budibase Version: 2.4.14
  - App Version:  2.4.14
**Describe the bug**
 If a sheet has a space in the name, Budibase goes to Users in data tab. You can not view the data in Budibase if this happens

**To Reproduce**
1. Go to Google sheets and create a sheet with a space in the name of the sheet.
2. Add some headers and dummy data
3. Add it to your Budibase
4. Fetch tables
5. Click on the table on the left bar

**Expected behavior**
See the data in Budibase
 
**Desktop (please complete the following information):**
 - Browser Chrome
 - Version Latest

<sub>[BUDI-6779](https://linear.app/budibase/issue/BUDI-6779/google-sheets-sheet-has-a-space-in-the-name-budibase-cant-show-the)</sub>

**Comment by mike12345567** [comment]
This issue is resolved in the latest release.
