### ISSUE TITLE
[BUDI-6776] A relationship between two tables should be able to exist in multiple contexts

### ISSUE THREAD

**Issue by dnk8n** [Budibase/budibase#10096]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose

**Describe the bug**
One should be able to define multiple relationships (between different junction tables) for different use cases.

**To Reproduce**
1. Define relationships as in screenshots.
1. An idea of the relationship I want to model:
```
CREATE TABLE IF NOT EXISTS employees (
    employee_id bigserial primary key,
    user_id text unique not null,
    email text unique not null,
    name text,
    position text
);

CREATE TABLE IF NOT EXISTS projects (
    project_id bigserial primary key,
    name text unique not null,
    start_date date,
    end_date date,
    description text
);

CREATE TABLE IF NOT EXISTS dashboard_projects (
    employee_id bigint,
    dashboard_project_id bigint,
    primary key (employee_id, dashboard_project_id),
    foreign key (employee_id) references employees(employee_id) on delete cascade on update cascade,
    foreign key (dashboard_project_id) references projects(project_id) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS project_members (
    project_id bigint not null,
    employee_id bigint not null,
    primary key (project_id, employee_id),
    foreign key (project_id) references projects(project_id) on delete restrict on update cascade,
    foreign key (employee_id) references employees(employee_id) on delete restrict on update cascade,
    is_manager boolean not null
);
```

**Expected behavior**
Both scenarios involve projects and employees (but for different use cases, and through different junction tables):
1. A list of projects each employee is entitled to view on their dashboard (only available to managers)
2. A list of projects each employee is a member of

**Screenshots**
![Screenshot from 2023-03-21 20-49-51](https://user-images.githubusercontent.com/3307753/226714947-b5a0134e-fdf2-45f0-8132-21c729db0ba5.png)

![Screenshot from 2023-03-21 20-50-36](https://user-images.githubusercontent.com/3307753/226714928-b240b117-d33f-41dc-b11b-77769df81952.png)
  
**App Export**
Not possible

<sub>[BUDI-6776](https://linear.app/budibase/issue/BUDI-6776/a-relationship-between-two-tables-should-be-able-to-exist-in-multiple)</sub>

**Comment by mike12345567** [comment]
Closing this issue as it has been discussed before - a decision was made no to pursue this, discussion can be continued on old issue: https://github.com/Budibase/budibase/issues/9401
