### ISSUE TITLE
Request export data in Budibase in nosql. 

### ISSUE THREAD

**Issue by SalehMohammadMusa** [Budibase/budibase#10116]
**Describe the feature request**
Although there is row selection in sql there is no support of row selection in nosql (dynamodb) therefore we can not use it to export CSV file

**Screenshots**
![image](https://user-images.githubusercontent.com/50841672/227863448-a06e8b0a-783b-43dc-aa66-8f1edb3a326d.png)

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/7348
