### ISSUE TITLE
[BUDI-6781] Dynamic Filtering on 0 for external sources e.g. mysql, postgres

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#10118]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.4.27-alpha.5.
  * App Version: 2.4.27-alpha.5.

**Describe the bug**
You aren't able to interact with 0 with the dynamic filter within the Data or design view when using an external data source like MySQL or Postgres. When trying to do this it doesn't filter the results at all, they just remain unchanged. A side note the filter will work with 0.1 instead of 0, leading to the next point.

This does work with the Budibase datasource. The reason it doesn't work with the other sources is likely due to a falsey check where 0 is being treated as false. (There is likely a bad falsey check somewhere in the plus datasources which isn't accounting for 0)

**To Reproduce**

1. Setup a table
2. Setup up a number based column
3. Add some values
4. Add a filter for the column created for greater or less than with the value set to 0

**Expected behavior**
Filtering should occur on the data set, to show the numbers which match the filter. Nothing occurs and it remains unchanged when trying to use the filter.

**Screenshots**

Filter being used

![filter being used.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/933d6196-331e-44e7-a147-4a43941b98d0/b6592b11-c9f7-4a93-90e3-8cc101b0a664)

Budibase data source

![budibase source and what should happen.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f6997e60-dbe1-401c-9847-d81d4fb8cabb/859f5702-1f63-41a8-a90c-6501df05082c)

External datasource - unchanged using the same filter

![external source, nothing changes.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/03d2b286-59db-4db6-821a-9edc4ec11c64/b79a0187-c81a-41f8-bdca-25fc777dc6de)

**App Export**

[d-filtering-0.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/afb38e85-399c-4ec3-88df-db210742d6a2/f7d40700-12d8-4ed7-9a30-b06021aec78f)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6781](https://linear.app/budibase/issue/BUDI-6781/dynamic-filtering-on-0-for-external-sources-eg-mysql-postgres)</sub>

**Comment by ars3nicum** [comment]
The same behaviour will be only with dynamic filters, but if you :
1. create number form filed 
2. assign datasource filter for some column to be greater/less than that field.
3. put 0 to that field
Maybe this issue related to [BUDI-6819](https://github.com/Budibase/budibase/issues/10182)

**Comment by AlejandroFNadal** [comment]
If it is related to [https://github.com/Budibase/budibase/issues/10182](BUDI-6819), this should not be low priority, essentially every time you have a 0 in a numerical field it will not be shown.

**Comment by AlejandroFNadal** [comment]
I have also seen that if you have a "return 0" in a paragraph component for the text field, it also does not work. For now, for paragraphs, I am using:
return `${0}`

This is useful when you show a number using a paragraph and the number comes from somewhere as 0.

**Comment by ars3nicum** [comment]
Hey. Any progress on this?

**Comment by ars3nicum** [comment]
please, somebody fix this

**Comment by ars3nicum** [comment]
@ConorWebb96
Can you please tell me if this bug will be fixed someday? Looks quite a big problem for me.

**Comment by ConorWebb96** [comment]
Hey @ars3nicum,

This is in progress, there should be a fix for this within this iteration.

**Comment by ars3nicum** [comment]
Great. Thank you!

**Comment by ars3nicum** [comment]
Sorry, @ConorWebb96, but what what does it mean 'this iteration''? Since then several releases was out and this bug not fixed there.

**Comment by ConorWebb96** [comment]
Hey @ars3nicum,

This was set to be done this release, but doesn't seem likely now as there were more urgent bugs/enhancements that needed to be focused on this iteration (This months worth of work.) One of the engineers should hopefully get a look at this over the next iteration. (Next months work) I've bumped the priority and will mention this to the dev team which should hopefully get this sorted sooner.

I hope this makes sense.

**Comment by ars3nicum** [comment]
Thank you very much!

**Comment by ars3nicum** [comment]
heeeey, once again i am pinging about this issue. it is almost half a year fixing this :(

**Comment by ars3nicum** [comment]
@ConorWebb96 👀

**Comment by ConorWebb96** [comment]
@ars3nicum pr linked above 🙌

**Comment by ars3nicum** [comment]
Great! ThanksOn 12 Sep 2023, at 16:11, Conor Webb ***@***.***> wrote:﻿
@ars3nicum pr linked above 🙌

**Comment by ars3nicum** [comment]
🙏

**Comment by ars3nicum** [comment]
I installed 2.10.8 which is just released and nothing changed for me - 0 still doesn't work in filters. @ConorWebb96

**Comment by mike12345567** [comment]
Hi @ars3nicum - how have you configured this - on 2.10.8 it is working for me as such:
Filters:
![image](https://github.com/Budibase/budibase/assets/4407001/e1ea8e95-3b1a-4db2-b604-a05e36a9fb9c)
Data:
![image](https://github.com/Budibase/budibase/assets/4407001/32d5f319-a3c5-4544-80b4-2b0238b32fa3)

**Comment by ars3nicum** [comment]
@mike12345567 add some entries with negative age and then add filter "more then or equal to 0"

**Comment by mike12345567** [comment]
Hi @ars3nicum - I see it, appears to be an independent issue from the "0" - i'll look into it.

**Comment by mike12345567** [comment]
@ars3nicum - got a fix - coming shortly.
![image](https://github.com/Budibase/budibase/assets/4407001/ea6f4e49-6981-4f1c-aebd-014126d4edaa)

**Comment by ars3nicum** [comment]
@mike12345567 thank you!

**Comment by ars3nicum** [comment]
@mike12345567 Hi. I see that it is fixed now, thank you! But still the operation is slightly different for external datasource and internal. 
Example:
1. Create input form field with number
2. Add filter to datasource so that it greater then/lower that this field
3. If you have entries with empty param1 and input field is empty internal source will show entries with empty param1, which in my opinion is correct. But for external datasource it will not show them.

<img width="769" alt="Screenshot 2023-09-17 at 10 32 58" src="https://github.com/Budibase/budibase/assets/90869728/bb265d93-d0de-452d-a10c-1dfa063977cd">

**Comment by ConorWebb96** [comment]
Hey @ars3nicum,

This is a different issue, its not related to the above. Can you create a new issue following the bug template? If you could provide as much information as possible including: app exports and your db schema etc. so we can easily test.

Thanks in advance.
