### ISSUE TITLE
[BUDI-6800] Automations only work sporadic

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#10117]
**Checklist**
- [x] I have searched Budibase discussions and GitHub issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.4.31
  - App Version: 2.4.31

**Describe the bug**
We have 2 apps with automations and they don't work 70% of the time.
We don't know the reason, there's no error in Budibase and when restarting the docker/updating Budibase (when update available), the E-Mails get sent out.

**To Reproduce**
?

**Expected behavior**
We expect the Automations to work without having to restart the docker every single time.

**Additional context**
Automations are really important for our users and we are just helpless.

<sub>[BUDI-6800](https://linear.app/budibase/issue/BUDI-6800/automations-only-work-sporadic)</sub>

**Comment by shogunpurple** [comment]
Without reproduction steps or some kind of insight into your self hosted installation it's almost impossible for us to debug this. closing

**Comment by dewdeded** [comment]
Can be closed, the issues was (by you) resolved earlier this week in our call. 
Thank you again. :)

We now monitor the redis queue via our monitoring system and get alerts, when jobs are delayed way to long.

**We found another one.** Maybe it would be a good idea, to write in the docs that eh redis queue is always "First In, First Out", so automations with very, long delays causes these problems.
