### ISSUE TITLE
[BUDI-6798] minio 403 problem after upgrading from 2.2.22 to 4.3.31

### ISSUE THREAD

**Issue by reichert** [Budibase/budibase#10126]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: upgrade from 2.2.22 TO 2.4.31
  - MINIO IMAGE VERSION in docker-compose.yml: minio/minio:RELEASE.2022-10-24T18-35-07Z
  - I'm running the entire setup behind a traefik reverse proxy:
![image](https://user-images.githubusercontent.com/1287032/228025977-3a7293b8-fb5b-475a-9245-cb5ad00d5860.png)

**Describe the bug**
- After upgrading the system from 2.2.22 to any other newer version (example: v:2.4.31 ) the minio throws an 403 error when serving my files previously uploaded and possibly the static budibase original files. One of them is the budibase-client.js. This prevents from editing the app. Full URL: `https://budibase.internal.XXXXXX/files/signed/prod-budi-app-assets/app_default_84bd366cf6XXXXXXXX9cd6f61/budibase-client.js?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=budibase%2F20230327%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230327T174226Z&X-Amz-Expires=3600&X-Amz-Signature=edf9b66fc0XXXXXXXXXXXXXXXX43a9f545f120&X-Amz-SignedHeaders=host`

- The other file is my logo that was previously uploaded during the instalation and loads successfully with previous version.

**To Reproduce**
1. Have my setup in v 2.2.22
2. Upgrade it to v 2.4.31
3. Enter in any app and the file budibase-client.js will not be loaded (you only need to look to browser inspector)
4. Enter in the main portal and my logo which is inside minio also doesnt load
5. If I install again the version 2.2.22 it starts to work again.

**Expected behavior**
The apps should run and the JS file should be served correctly

**Screenshots**
- before upgrading:
![image](https://user-images.githubusercontent.com/1287032/228022908-23e2b320-c8b3-4559-a135-b8dc22880f2f.png)
- after upgrading budibase AND the app to the latest version:
![image](https://user-images.githubusercontent.com/1287032/228024289-c45fdf39-6b61-4553-86c0-16dd6d1c1c8f.png)
- even the other assets uploaded previously to minio does not open like my logo:
![image](https://user-images.githubusercontent.com/1287032/228024794-de9a29d8-046e-4bf0-8bff-f7c688d10adb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: chrome (tested also in others)
 - Version: 111 64 bits

**Additional context**
- I'm building the images from https://hub.docker.com/r/budibase/apps/tags?page=1
- The only image I have to manipulate was the proxy because we had to change the nginx.conf - but this works fine and I believe this is not the source of the problem.

I'd appreciate any help!
Thanks.

<sub>[BUDI-6798](https://linear.app/budibase/issue/BUDI-6798/minio-403-problem-after-upgrading-from-2222-to-4331)</sub>

**Comment by shogunpurple** [comment]
Hi @reichert - there's a possibility that updates to the way that we store and authenticate attachments have caused issues with your traefik setup here. We've also updated our `nginx.conf` to provide support for these changes, so it's possible yours is behind.

We aren't sure if it's actually a problem with budibase here or something that needs to be configured on your side given you are using a fairly custom setup. Closing for now, but if you can reproduce this with a default budibase NGINX config and without traefik please raise another one with the reproduction. Thanks.
