### ISSUE TITLE
[BUDI-6808] Since yesterday it's  impossible to create new rows (but we can delete and update)

### ISSUE THREAD

**Issue by cnrodrig** [Budibase/budibase#10142]
- [X ] I have searched budibase discussions and github issues to check if my issue already exists

- Cloud
  - Tenant ID:  unoafp
  
**Describe the bug**
Can't create new rows since yesterday. Everything was working fine but today we realized it's not possible to create new rows in any table. We try to press the Save button and nothing happens. We even created a new autogenerated screen for a table and nothing. 
The strange thing is that we could delete and update rows, but not create rows.
---- UPDATE ----
Testing alternatives we've arrived to the "culprit". We don't know why but the problem is with the primary keys in postgres.
We where using a SERIAL id column but now it doesn't work. We've tried using identity also. If we use a integer primary key column it works in Budibase only if we enter the id value by hand (no autoincrement).

So... how can we define a id column in postgres that works with Budibase?!!!!! The SERIAL id column was working fine until yesterday :(

**To Reproduce**
1. Go to https://unoafp.budibase.app/app/cpa
2. Click on Tribunal-2
3. Click on Create Row (Up Right)
4. Click on Save
5.  Nothings happen

**Expected behavior**
The blank row (or with any value) should be saved

**App Export**
Export Attached

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - Version 111.0.5563.111

[cpa-export-1680036080644.tar.gz](https://github.com/Budibase/budibase/files/11093985/cpa-export-1680036080644.tar.gz)

<sub>[BUDI-6808](https://linear.app/budibase/issue/BUDI-6808/since-yesterday-its-impossible-to-create-new-rows-but-we-can-delete)</sub>

**Comment by oscargws** [comment]
This is now happening to my organisation as well, we're completely offline due to this. We haven't changed anything in our budibase configuration, or our database, and as of the same time as you, this is now broken. This is the error that the API returns whenever I try to insert a new row. 

<img width="486" alt="Screen Shot 2023-03-29 at 1 12 59 pm" src="https://user-images.githubusercontent.com/40099755/228424959-0f107573-f6ae-487e-a41b-a5b3ede4335d.png">

**Comment by NBolmer** [comment]
I have the same issue also with auto_increment fields in MariaDB

**Comment by NBolmer** [comment]
I use the latest selfhosted version (2.4.32) and yes it is still happening 
![SCR-20230329-ndxi](https://user-images.githubusercontent.com/92300746/228540866-ee0fbbde-1eb0-49c4-9dfa-a10d939d5faf.png)

**Comment by cnrodrig** [comment]
It’s working!! We are going to do some tests. I’ll comment later

**Comment by shogunpurple** [comment]
@NBolmer the latest should be 2.4.40 - https://github.com/Budibase/budibase/releases/tag/v2.4.40

**Comment by NBolmer** [comment]
Thanks @shogunpurple 
But it seems the docker image on docker.com is not updated yet.

**Comment by shogunpurple** [comment]
@NBolmer if you are using the single image that should be updated now.

**Comment by NBolmer** [comment]
@shogunpurple I use the docker image budibase/budibase. Sorry, but this image is still not updated.

**Comment by NBolmer** [comment]
@shogunpurple I now saw the updated image and installed it. Now it works also for me!! Great job. Thanks!!!

**Comment by kekonn** [comment]
Can confirm this issue was also present when using a MySQL data source, and this update fixed it.
