### ISSUE TITLE
[BUDI-6817] Unable to proceed past the login screen since updating to v2.4.32 and beyond

### ISSUE THREAD

**Issue by galenvssysadmin** [Budibase/budibase#10175]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 2.4.32

**Describe the bug**
After updating to v2.4.32, I am unable to proceed past the login screen. I click 'login' to authenticate, get the 'Logged in successfully' confirmation, then get redirected back to the login page, in an endless loop.

I have tried to update to v2.4.42 released yesterday, however I encounter the same problem. The last working docker image for me is v2.4.14.

**To Reproduce**

1. At the Budibase authentication screen, click login (either with username/pw, Google SSO, or OIDC).

After the 'Logged in successfully' confirmation, I get a brief flash of the developer portal, then screen redirects me back to the authentication screen:

![gif](https://user-images.githubusercontent.com/102808173/229081235-41de33a8-5014-48a8-a150-359d91a50eea.gif)

The Chrome console shows the error:

`[Builder] HTTP 403 on GET:https://apps.<domain>.com/api/global/self`
`          Unauthorized`

<sub>[BUDI-6817](https://linear.app/budibase/issue/BUDI-6817/unable-to-proceed-past-the-login-screen-since-updating-to-v2432-and)</sub>

**Comment by mike12345567** [comment]
Hi @galenvssysadmin - I'm not able to recreate this issue on v2.4.43 - I've used a fresh install - could you confirm if you still experience this issue in a fresh docker image with no existing users/configuration?

**Comment by mike12345567** [comment]
Hi @samkline - the failed `/api/global/self` check is expected on the login screen - this is by design, we use this to determine if the user is logged in already or not and need re-directed away from the login page.

I'm going to call this issue resolved as it appears to have only affected previous versions, thank you for confirming this @samkline.
