### ISSUE TITLE
Development deployment cluster - self hosted

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#1018]
Quick task to setup a deployment cluster which updates to match master at all times so that during development we have somewhere we can easily deploy to. A few parts to this:

- [x] 1. Setting up a `staging` docker image which is released every time master is updated.
- [x] 2. Run an EC2 instance from which we can run a self hosted cluster
- [x] 3. Setup a periodic script to check for updates to the `staging` docker image, when found reload the cluster with the new image
- [x] 4. Setup a Budibase subdomain/path to direct to for development purposes
- [x] 5. Configure HTTPS for the cluster with an NGINX reverse proxy and certbot
- [x] 6. Distribute the development key and development URL to the team

**Comment by shogunpurple** [comment]
Few bits of this are done:
- Instance brought up
- Periodic updates
- URL to team

Just need to set up the CI stuff for staging images now and we are good to go :)
