### ISSUE TITLE
[BUDI-6821] Send email with Office365 Microsoft Exchange

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10196]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Describe the bug**
This user on Discord highlighted an issue connecting to an Office 365 email server: [https://ptb.discord.com/channels/733030666647765003/1091593229918552156](https://ptb.discord.com/channels/733030666647765003/1091593229918552156)

Further digging brought up what I believe to be the solution: [https://stackoverflow.com/questions/29812132/error-sending-email-using-nodemailer-via-office365-smtp-meanjs-scaffold](https://stackoverflow.com/questions/29812132/error-sending-email-using-nodemailer-via-office365-smtp-meanjs-scaffold)

**Screenshots**

According to SO, we need to either replace *secure* with *secureConnection*, or add *service* = "Outlook365", although I saw the *secureConnection* appear twice - it may be the standard fix.

![Screenshot 2023-04-03 at 13.54.00.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/84ff96f5-efdc-4a83-b155-79c882d8b582/5e7037e9-5413-49ca-a0e0-5690fa04a85d)

**Expected behavior**
As a user I should be able to use Office365 Microsoft Exchange as an SMTP provider

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6821](https://linear.app/budibase/issue/BUDI-6821/send-email-with-office365-microsoft-exchange)</sub>

**Comment by dewdeded** [comment]
SMTP Mail via Office 365 still works BB with:

- via Port 587, 
- Security Type: None/StartTLS, 
- Require sign in,
- From EMail = Username

Account must be allowed to send SMTP mail @ Office 365.
And 2FA should be disabled for the Office365 login.

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/13985

**Comment by andz-bb** [comment]
I think this one's still valid
