### ISSUE TITLE
[BUDI-6833] Change made by budibase badge to be a footer

### ISSUE THREAD

**Issue by FloMiLe** [Budibase/budibase#10191]
**Describe the feature request**
Currently, the little branding screen in the bottom-right corner sits on top of side panels and may hide content, see scr eenshot attached. With the newly introduced side panels, could the branding maybe moved somewhere else, e.g. the bottom-left corner?

**Screenshots**

<img width="406" alt="Branding on top of side panel" src="https://user-images.githubusercontent.com/13892710/229429277-eb773d4c-92fd-481b-85a0-933587d42a5a.png">

<sub>[BUDI-6833](https://linear.app/budibase/issue/BUDI-6833/do-not-place-branding-above-side-panel)</sub>

**Comment by dewdeded** [comment]
![bb_unbranded](https://user-images.githubusercontent.com/7132234/230708818-66b85056-9911-4e4d-8438-49184a102826.png)
I un-branded and now my login page looks like this. (2.5.0, multiple images deployment).
