### ISSUE TITLE
The data source prop has disappeared for the form component

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1019]
**Describe the bug**
The data source prop has disappeared for the form component. This means there is no way to bind a form to a table.
![Screenshot 2021-01-26 at 12 35 19](https://user-images.githubusercontent.com/49767913/105845678-14678980-5fd3-11eb-8993-36d6bc563300.png)

**Comment by mjashanks** [comment]
This was removed on purpose, a while ago. 

I'm sure that this will all change with the new form builder stuff anyway. However, the way it currently works is that a form should always be contained inside a "New Row" or a "Row Detail" component. The auto-screens have one of these by default as their root component.
