### ISSUE TITLE
[BUDI-6845] From one moment to another no row will be added to the PostgreSQL database

### ISSUE THREAD

**Issue by Mando540** [Budibase/budibase#10221]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

Somehow identical to this issue but updating to a current version of Budibase doesn't fix the problem: https://github.com/Budibase/budibase/issues/10142

**Hosting**
- Cloud
  - Tenant ID: blackscreenrecords

**Describe the bug**

We are not able to write a row in one of our tables which are connected to Budibase via PostgreSQL. I didn’t make any changes in the app since it was working. But every time we try to save a new row nothing is happening. If I toggle on the „Require confirmation“ button the confirmation is shown but nothing else.

I checked the dev tools and noticed an error notification (attached below).

**To Reproduce**
1. Go to https://blackscreenrecords.budibase.app/app/fulfillment-portal#/job/new
3. Add all relevant required data, add a line item and choose options
4. Click "Save Job" 
5. See error / nothing is happening in the app

**Expected behavior**
A new row is added in the database.

**Screenshots**
![Bildschirm­foto 2023-04-05 um 12 48 21](https://user-images.githubusercontent.com/64315462/230085159-8be50661-0493-4638-8002-89e2bccd2a09.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version:  111.0.5563.146

<sub>[BUDI-6845](https://linear.app/budibase/issue/BUDI-6845/from-one-moment-to-another-no-row-will-be-added-to-the-postgresql)</sub>

**Comment by mike12345567** [comment]
Hi @Mando540 - could you provide an example of the SQL schema used to generate the specific table you're having problems with? A simplistic example of the table would make it easier for us to debug this.

**Comment by Mando540** [comment]
Hi Mike, thank you for the swift reply! And I think I finally found the problem. Some columns have default values. So if I add a new row and the payload doesn't include values for those columns the default value should be used instead. But for some reason I now have to add information for those columns to the payload as well. I don't know why I have to to do that now but it works if I adjust the payload.

You may have a clue for me why this has changed but the most important thing is that the app is finally working again.
