### ISSUE TITLE
[BUDI-6837] Enable component nesting validation for new apps

### ISSUE THREAD

**Issue by TheFunkyBiskit** [Budibase/budibase#10229]
We should enable component nesting validation again, but only for new apps.

To account for this, we'll need to add some new arbitrary flag inside a "features" flag on new app docs which we can check for the existence of inside the design section.

Then we can conditionally apply nesting validation if this flag is set.

Original issue below:

**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Docker Compose
  * Budibase Version: 2.5.0
  * App Version: 2.5.0

**Describe the bug**
I mis-clicked and nested a side panel element within another. This breaks the page and makes it unresponsive. Side panel nesting likely shouldn't be allowed. ~~The page is now in an unrecoverable state as the tab locks up and eventually crashed whenever that page is visited in the editor.~~ See my comment below.

**To Reproduce**

1. Create a side panel element
2. Create another
3. Nest one side panel within another

**Expected behavior**
I would expect that this cannot happen since it doesn't really have any use case as anything but a top-level element.

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Chrome
* Version: 111.0.5563.147 (Official Build) (64-bit)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6837](https://linear.app/budibase/issue/BUDI-6837/enable-component-nesting-validation-for-new-apps)</sub>

**Comment by TheFunkyBiskit** [comment]
Update:
Just realized that the lock-up only occurs when the side panel element is rendered. So if you're in this situation, you can fix it by deleting the nested panel with the "..." menu, but without selecting it, that way it stays hidden. Though the potential still exists.

**Comment by shogunpurple** [comment]
@aptkingston to turn on `illegalChildren` for new apps only.
