### ISSUE TITLE
Created By, Updated By, Created At, Updated At Fields

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1022]
- Allow the user to optionally include these at table creation time
- Keep them updated

**Comment by medouederni** [comment]
Using Budibase  0.9.73 Docker deployment on Windows
I added a new internal table (Files) with all auto columns and the related screens.
When I add a new row, the **Created By** column is empty.
I expected that the **Created By** column will be set with the current user.

Am I missing something?
