### ISSUE TITLE
[BUDI-6842] Many to many relationship - Postgresql - does not remove relationships when edited

### ISSUE THREAD

**Issue by kpturner** [Budibase/budibase#10236]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: monito

**Describe the bug**
I have two postgreSQL tables:

**country**
id_country (autoincrement PK)
label_country (selected as display field for table)

**currency**
id_currency (autoincrement PK)
label_currency (selected as display field for table)

There is a many to many relationship between the files (a country can have many one or more currencies) through a table called **currency_country**. This table simply contains:
id_currency
id_country
**_and it has a primary key constraint containing both columns_**

If I create this relationship, the **out of the box** edit facility in the **Data** section of Budibase allows me to select the currencies for a country via a multiselect relationship select component.  This works well when adding currencies. I can select one or more currencies and click "save" and the modal gets dismissed and data appears in the **currency_country** table.
However, if I then remove one or more of the relationships, then click 'Save":
a) The modal edit dialog does not get dismissed
b) The data in the **currency_country** remains unchanged
No errors are seen in the UI.  However I can see that the HTTP request is failing with 
**HTTP 400 error: duplicate key value violates unique constraint "currency_country_pkey"**

If I remove the constraint (which is not a good idea) then I no longer get the 400 error, but the data is still not updated on the **currency_country** table. I actually end up with duplicate keys.

If, however, I edit the countries on the currency record (effectively doing the same thing in reverse) then the **currency_country** table gets updated correctly. It is as if the update via country is getting the keys the wrong way around or something.  

To Reproduce
I defined a relationship thus:
Type: Many to many
From table: currency
To table: country
Through: currency_country
Foreign key (currency): id_currency
Foreign key (country): id_country
From table column name: currencies
To table column name: countries

Expected behavior
This should be possible but it is not obvious how to do it without getting errors.

Desktop (please complete the following information):

OS: iOS
Browser: Chrome
Version: 111

<sub>[BUDI-6842](https://linear.app/budibase/issue/BUDI-6842/many-to-many-relationship-postgresql-does-not-remove-relationships)</sub>

**Comment by kpturner** [comment]
By way of an update, if I reverse the logic on my relationship thus:
Type: Many to many
From table: country
To table: currency
Through: currency_country
Foreign key (country): id_country
Foreign key (currency): id_currency
From table column name: countries
To table column name: currencies

then the problem occurs in reverse.  If I edit currencies on a country it works.  If I edit countries on a currency it fails.

**Comment by melohagan** [comment]
Possible related scenario: https://github.com/Budibase/budibase/discussions/10398

**Comment by melohagan** [comment]
Hey @kpturner 

Sorry for the late response, I have dug into this a bit more and could see the error you described. This was because of the schema of the joining table:

```sql
CREATE TABLE main_data.country_currency (
    country_iso character varying(2) NOT NULL,
    currency_iso character varying(3) NOT NULL
);
```

This is not a valid joining table, it worked with the schema shown in the docs which I have updated here: https://docs.budibase.com/docs/sql-datasource#many-to-many
