### ISSUE TITLE
[BUDI-6834] Rename published app - button disabled with no explanation

### ISSUE THREAD

**Issue by andz-bb** [Budibase/budibase#10230]
**Checklist**

* [X] I have searched Budibase discussions and GitHub issues to check if my issue already exists

**Hosting**

* Self
  * Method: dev stack
  * Budibase Version: 2.5.1

**Describe the bug**
When trying to update the name of a published app, you are correctly prevented from doing so. The button contains a help icon and tooltip that explains that this can't be done while the app is published, but because the button is disabled the tooltip won't display.

![Screenshot 2023-04-06 at 10.22.50.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/937ffbf9-b06c-4e3a-b3e7-d1242b82dcb5/b70a5edd-75c9-4533-acf1-0b4e2c857d44)

**To Reproduce**
Steps to reproduce the behaviour:

1. Create app and publish it
2. Click manage and go to the Name and URL tab
3. Try to rename the app

**Expected behaviour**
Button is disabled but there is an explanation available. Bonus would be a link to unpublish the app right there.

When I remove the disabled prop from the button in devtools the tooltip shows as expected.

![Screenshot 2023-04-06 at 10.16.32.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/9143830e-e1d0-4dcb-ba21-177ca23358d5/4070ef2b-2710-4c85-a2fa-3af47f49cf62)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6834](https://linear.app/budibase/issue/BUDI-6834/rename-published-app-button-disabled-with-no-explanation)</sub>

**Comment by melohagan** [comment]
![Screenshot 2023-11-10 at 16 04 10](https://github.com/Budibase/budibase/assets/101575380/79031839-f649-4180-85fc-12035d102794)
