### ISSUE TITLE
[BUDI-6840] Delete multiple Rows = Conversion Failed

### ISSUE THREAD

**Issue by BRM-SMS** [Budibase/budibase#10256]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose 
  - Budibase Version: 2.4.43 

**Describe the bug**
I cannot select multiple rows and delete them. Im getting error:

![image](https://user-images.githubusercontent.com/119508535/231097462-ca31edea-8e9c-47c8-b400-00c086dda968.png)

**To Reproduce**
1. Create datasource.
2. Create Form and Table for Datasource.
3. Create Button for Action > Delete Row > Selected Rows

**Expected behavior**
Selected Rows getting deleted

**Screenshots**
![image](https://user-images.githubusercontent.com/119508535/231097937-8f8b2039-9713-4814-9e20-9055c1fce6c0.png)

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chrome
 - Version latest

<sub>[BUDI-6840](https://linear.app/budibase/issue/BUDI-6840/delete-multiple-rows-=-conversion-failed)</sub>

**Comment by shogunpurple** [comment]
Dupe [https://github.com/Budibase/budibase/issues/8715](https://github.com/Budibase/budibase/issues/8715)
