### ISSUE TITLE
Airtable connector not returning full schema

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1027]
**Describe the bug**
When I create a new Airtable query, and "Run Query", the JSON returned by Airtable does not include all my columns. So, these columns aren't available in my query.

I believe that the missing columns are ones that have no value in row number 1 of the table.

**To Reproduce**
1. Find an Airtable table that has some rows, 
2. Add a new number column (works with other types too)
3. Create a new query to that table

RESULT: the JSON returned in the builder does not have your new column

**Expected behavior**
My new column should exist in the JSON

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: FF
 - Version: commit d937d62

**Comment by yashank09** [comment]
Hello! I'd like to pick this issue if no one else is working on it :)

**Comment by shogunpurple** [comment]
Thanks @yashank09!

**Comment by yashank09** [comment]
Hi @shogunpurple ! 
I'm not able to run a query and get response from my Airtable.., will you be able to give me a reference/example? 

I've created a simple table with a field called `Score`, which has it's first row as empty. I have also created a `boolean` named `Accepted` that contains a value for each row. I used my Airtable's API key when asked by Budibase, and seem to have the right names for all my tables/views. On running a query to read all records, I get an empty response back.
Thanks!

**Comment by shogunpurple** [comment]
Hey @yashank09, to set up an airtable query:

- Set up your airtable datasource using your API key and base ID. You can find your API key in your airtable settings, and your base ID at https://airtable.com/api
- You then need to configure your table and view names. Bear in mind these are case sensitive. I've been caught a few times by using "Grid View" instead of "Grid view"
- Run your query and you should get results back.

Here's a loom showing how to set it up:

https://www.loom.com/share/be230a92cda44914bc7dbec6a5ed19ac

**Comment by yashank09** [comment]
Hey @shogunpurple , 
I have cross checked several times and all my settings look fine.., so there must be something silly I'm missing? I should be able to figure it out, but just to give you an update, here's my table and source settings-
![airtable_query](https://user-images.githubusercontent.com/37672190/107139138-ba699c80-68cd-11eb-8f3a-602471d6a31e.png)

![air_table](https://user-images.githubusercontent.com/37672190/107139143-c2c1d780-68cd-11eb-99c5-850de83cccee.png)

Maybe something in the parameters itself? I'm assuming I should get my whole table without any parameters?

**Comment by shogunpurple** [comment]
@yashank09 that's very strange. When you run that query, does it just say there are no results, or do you get an error?

**Comment by yashank09** [comment]
It returns a query with no results. I have recreated the source multiple times, not sure what I'm missing...

I also seem to have this UI bug on Vivaldi browser(chrome 88.0). If anyone can confirm, I will file a separate thread for this.
https://imgur.com/a/5ala3yG

**Comment by shogunpurple** [comment]
Ah - @mjashanks @yashank I know why this happens now. It's because the schema is derived from the first row in the response. It doesn't parse every single row to get all the columns available. For certain data sources, they will return the key of the object, but for airtable it omits the key entirely for empty columns. 

I will add code to parse all of the response and return the schema, which should account for this if at least one column has the field defined.

**Comment by Caterina1994** [comment]
Hi! 
I run my query putting the table name and "Grid view" but it wont work.

**Comment by shogunpurple** [comment]
@Caterina1994 ok, do you get an error when you run your query? What does your configuration look like?

**Comment by Caterina1994** [comment]
@shogunpurple , yes I get an error in blue that says: "Query results empty. Please execute query with results to create your  schema".

What do you mean my configuration? My table is just a Grid View

**Comment by shogunpurple** [comment]
> Query results empty. Please execute query with results to create your schema

Do you have any records in your table?

**Comment by Caterina1994** [comment]
Yes I do! @shogunpurple

**Comment by shogunpurple** [comment]
@Caterina1994 This could happen if the first row in your table is empty? Airtable omits fields if they are empty - that's the issue @yashank09 had above. We have fixed this and it will be released tomorrow.

I'm unable to recreate this on the latest released version of the builder with a table that has every row defined.

**Comment by Caterina1994** [comment]
Hello @shogunpurple  my first row is not empty . Can there be another problem?

**Comment by yashank09** [comment]
> Hello @shogunpurple my first row is not empty . Can there be another problem?

any chance you could post a screenshot of the table with the view name etc. ?

**Comment by Caterina1994** [comment]
<img width="1383" alt="Captura de Pantalla 2021-02-24 a la(s) 20 15 48" src="https://user-images.githubusercontent.com/61291910/109053554-1f4e3080-76dd-11eb-8669-1c80c94450cd.png">
<img width="1409" alt="Captura de Pantalla 2021-02-24 a la(s) 20 14 59" src="https://user-images.githubusercontent.com/61291910/109053560-21b08a80-76dd-11eb-9ef9-9ab295383b2b.png">

**Comment by yashank09** [comment]
@Caterina1994 Ah, I see a slight typo in your view names. Try changing the Budibase view name to 'Grid view'(lowercase v) instead and hopefully it will do the trick :)

**Comment by shogunpurple** [comment]
That would do it! I've done that myself actually. Great catch @yashank09

**Comment by Caterina1994** [comment]
Hey!  Still nothing 

<img width="1414" alt="Captura de Pantalla 2021-02-25 a la(s) 18 49 45" src="https://user-images.githubusercontent.com/61291910/109194979-4585d600-779a-11eb-9f31-7d63e3aacf3c.png">

**Comment by shogunpurple** [comment]
Hi @Caterina1994 - you will be pleased to know we have performed significant updates to the builder and the latest version of budibase is now available. 

Please try and see if your issue still persists on the latest version, and if it does we will debug.

**Comment by Caterina1994** [comment]
Great @shogunpurple  how do i get the last version?

**Comment by Caterina1994** [comment]
I have the new version. but still cant connect with airtable
![Uploading Captura de Pantalla 2021-02-25 a la(s) 20.06.45.png…]()

**Comment by shogunpurple** [comment]
Hi @Caterina1994 - it seems like your screenshot is not working.

I have tried many times to recreate this and cannot, with any airtable base.

Could you please screenshot your airtable query on the current version of budibase, and show me that that your configuration is **exactly** like the following (according to the airtable base screenshot you sent earlier):

![Screenshot 2021-02-25 at 20 12 25](https://user-images.githubusercontent.com/11256663/109211179-c9918b00-77a5-11eb-8e00-9c18280edbbe.png)

**Comment by Caterina1994** [comment]
Hey! Yes here is a screenshot
<img width="1365" alt="Captura de Pantalla 2021-02-25 a la(s) 21 20 21" src="https://user-images.githubusercontent.com/61291910/109212060-5bea5c80-77af-11eb-8186-0e9d13fb94a7.png">
<img width="1337" alt="Captura de Pantalla 2021-02-25 a la(s) 21 20 27" src="https://user-images.githubusercontent.com/61291910/109212072-5e4cb680-77af-11eb-8779-e144bf2dc407.png">

**Comment by shogunpurple** [comment]
@Caterina1994 - looking at your screenshot above, your base is called fac_horarios, not your table. Your table is called “Imported table”. Please update your config to look identical to mine above.

**Comment by Caterina1994** [comment]
It WORKED!!!!!! :D:D:DD:D:D
thanksss @shogunpurple

**Comment by Caterina1994** [comment]
The Only problem now is that it doesnt bring the data to design :(

<img width="1427" alt="Captura de Pantalla 2021-02-25 a la(s) 22 41 54" src="https://user-images.githubusercontent.com/61291910/109223323-bd63f880-77ba-11eb-8476-b65ed81d2890.png">
<img width="998" alt="Captura de Pantalla 2021-02-25 a la(s) 22 36 58" src="https://user-images.githubusercontent.com/61291910/109223330-be952580-77ba-11eb-9970-039d87b267be.png">

**Comment by shogunpurple** [comment]
Que bien! Veo que de Airtable tu hables Español. Aprendo desde hace algunos meses - pero necisito practicar mas 😆

Por favor dígame si tiene alguna pregunta!

**Comment by Caterina1994** [comment]
jajaj si hablo español. La pregunta es : ¿Porque no me trae la información a la tabla?
Its not reading my query

**Comment by shogunpurple** [comment]
Hmmm, lo probé y no puedo verlo.

Your configuration in the design panel looks good.

Is there anything in your developer console? It looks like an error may have occurred when you rendered your grid component. Also make sure that you save your query in the data sources section before using it in design.

**Comment by Caterina1994** [comment]
Hey @shogunpurple I have my query already done correctly. But my budibase wotn read my database. I also had a problem with a csv i put .. My data wont show in the design panel .. ANd when i look at my web app this error appears:

<img width="737" alt="Captura de Pantalla 2021-03-01 a la(s) 8 53 26" src="https://user-images.githubusercontent.com/61291910/109467549-9ed85880-7a6b-11eb-99b2-e344cb4db89b.png">

So i think it is an error comingo from the budibase itself and not airtable or csv input.

**Comment by shogunpurple** [comment]
@Caterina1994 did you update your self hosted installation of budibase before that happened?
