### ISSUE TITLE
[BUDI-6848] Ignore Time zone with existing date/time field on MS SQL Server

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10278]
### Discussed in https://github.com/Budibase/budibase/discussions/10259

<div type='discussions-op-text'>

<sup>Originally posted by **lanedsmu** April 11, 2023</sup>
Hi all,

I believe I understand that the "ignore time zone" option is available for some DB platforms but not others (and possibly [not always available for those we'd expect](https://github.com/Budibase/budibase/discussions/10060)?).

We have a lot of MSSQL tables with existing date/time data without timezone offset, and it appears Budibase always treats these as UTC.  Is there a short-term way for us to handle this without utilizing queries to add the offset?

Thanks much!  -Lane
![image](https://user-images.githubusercontent.com/80843079/231170933-7e6b7dba-4395-4e90-a7d0-31bb8b957f7c.png)
</div>

<sub>[BUDI-6848](https://linear.app/budibase/issue/BUDI-6848/ignore-time-zone-with-existing-datetime-field-on-ms-sql-server)</sub>

**Comment by melohagan** [comment]
Hey @lanedsmu

Going to close this one because there's a limitation with Knex (our SQL connector library) that prevents us adding the *Ignore timezone* option for MS SQL Server (and Oracle).

You can read more here: https://github.com/Budibase/budibase/pull/6206
Look for the **Details around limitations** section.

What you may be able to do to work around this is ensure that the docker container has the same timezone set as your SQL Server.

There is a `TZ` environment variable that can be set to accomplish this: https://www.howtogeek.com/devops/how-to-handle-timezones-in-docker-containers/

**Comment by melohagan** [comment]
@lanedsmu Argh timezone stuff is always tricky. 

Those dates that have already been saved will remain as they are. You may need to update them manually with a query.

With the TZ variable set, it should save future data records in UTC with the correct offset. If my understanding is correct.

**Comment by lanedsmu** [comment]
Ah, we may be discussing different problems: I'm not doing data entry with this, but rather displaying existing data that doesn't have a TZ offset. Is there a way for me to get Budibase not to assume that's utc (without putting a query on front of it)?

Thanks again.

**Comment by melohagan** [comment]
Hey @lanedsmu When it comes to displaying data, then it may be dependent on the TZ of the web-browser as well. 

Instead of using a query to offset the time, you could also add a Formula column for display purposes that does the offsetting if that helps? https://docs.budibase.com/docs/formula

**Comment by lanedsmu** [comment]
Thanks again @melohagan.  I'll have to do some more digging and get better at using this interface; we'll see what we can come up with.

I'm left with a nagging concern, though, that I'll never be able to create an app reasonably trivially that'll just handle dates as they exist in the database.  

I think I see what you're talking about with the problem presented by the connection library.  If I do a simple select query in Budibase and manually change the schema to specify text as the datatype for a datetime field, the data is returned somewhat altered from what's in the database:
<img width="120" alt="image" src="https://user-images.githubusercontent.com/80843079/233647396-387df1c2-caf1-4a2d-b76e-fbee70c06213.png">

That Z timezone designator isn't a part of the data (and the DB server isn't in UTC).  Though it's noteworthy that the concrete date itself is correct, excluding the UTC designator.  

I've been imagining lots of ways we could use Budibase to monitor and delegate control over technical processes throughout our org, but all of that involves displaying dates from a variety of sources, none of which we'd have control over, in terms of formatting.  I don't yet know how to handle that, apart from utilizing SQL queries for everything (which might be fine...?).  

Is utilizing queries the right way to go, in terms of least friction for implementation?  Given the use-case:  querying date data that is historical and not under our control in terms of formatting (read: no TZ offset), what would you recommend as the easiest method to work around this problem?  

-Lane

**Comment by lanedsmu** [comment]
Thanks @melohagan; that was fast!  Can you point me to where that is?  I'd like to experiment some more with possibilities on this front.

**Comment by melohagan** [comment]
Certainly 😄  @lanedsmu 

Here is the connector: https://github.com/Budibase/budibase/blob/develop/packages/server/src/integrations/microsoftSqlServer.ts

I had tried simply adding the *useUTC* flag to false in the *options* object of the config.

The contributing readme is here: https://github.com/Budibase/budibase/blob/HEAD/docs/CONTRIBUTING.md

**Comment by lanedsmu** [comment]
hi @melohagan.  I've made progress, though I (like you) tried modifying microsoftSqlServer.ts, and I didn't get anywhere.  

Instead, I modified the useUTC setting in `/app/node_modules/tedious/lib/connection.js` from the default (true) to false.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/80843079/234935784-c90435b5-4c4f-4cbd-bf9c-a6726d88f01b.png">

and that worked marvelously.  

Before that was updated:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/80843079/234937466-7520363c-96be-44a3-9294-f59f23397070.png">


After the useUTC change hard-coded in connection.js
<img width="289" alt="image" src="https://user-images.githubusercontent.com/80843079/234937839-db70746c-2c4b-4524-9289-bafae8b7e53c.png">
Which is the actual set of values stored in the database.

and this appears to work with queries as well as with direct-to-table connections.

We obviously generally don't want to hard code values like that (though `true` /is/ hard-coded in connection.js, and hard-coding it as `false` is exactly a correct outcome for our use cases here).  I'm not familiar enough yet with these libraries or Budibase UI configuration yet to suss out exactly how best to address the problem as a product offering.

**Comment by melohagan** [comment]
Hey @lanedsmu Thank you very much for digging into this. I have also found this issue, so there may be a bug with the MS SQL library we are using: https://github.com/tediousjs/node-mssql/issues/1478

**Comment by lanedsmu** [comment]
Absolutely. It does seem as though we should be able to pass this config value on through the connection as a config object (see [Tedious readme](https://github.com/tediousjs/node-mssql/blob/7248e58ff223b2369cb1570005d54e9196c904bf/README.md)), but I'm clearly doing something incorrectly in my modifications of microsoftSqlServer.ts...  I'll keep hammering at that.

Reading that issue does make it sound like there's some data consistency concerns that they're working on, doesn't it?  In any event (assuming that gets fixed), do you expect the "right" solution here is to surface that setting through the data connection configuration in Budibase?

**Comment by melohagan** [comment]
I may be understanding the issue incorrectly, but from what I can the setting is being ignored when it shouldn't in the tediousjs node-mssql library that we use.
Therefore we need to wait for a fix in the library, then we can update the version in Budibase and simply pass the setting through in the config of `microsoftSqlServer.ts`.
