### ISSUE TITLE
Adding a User with a valid email returns "Unavailable" error

### ISSUE THREAD

**Issue by caseyatMission** [Budibase/budibase#10293]
Hi, I've run into this issue several times by trying to add this user in various ways. If I try to invite them to Budibase rather than at the app level, I get "There was a problem creating some users" with the reason listed as "Unavailable" for their email.

If I try adding them in the app, I just get an "Error inviting user" alert. Trying to autogenerate their password or just send an email invite doesn't make a difference.

I'm not sure what the issue is, as this is my colleague's email address, no typos, and I've had no trouble adding other individuals from my organization.

![Screenshot 2023-04-13 at 5 02 01 PM](https://user-images.githubusercontent.com/124637427/231909157-e78c57ab-054c-4c4e-bc50-89efe4c37edb.png)

**Comment by mike12345567** [comment]
Hi @caseyatMission - can you confirm if this is from the Budibase Cloud or a self hosted installation?

**Comment by caseyatMission** [comment]
We are paying for Budibase Cloud.

After investigating more on our end, it appears she made her own account, so then I could not add her as a user anymore. After she deleted her account I was able to re-add her and get her account working.

I'm going to mark this resolved because it's not an issue anymore, but also note that a clearer error message like "This email already exists for a Budibase user and cannot be added to your organization" or something of the kind would be useful in this case.
