### ISSUE TITLE
[BUDI-6850] Pushing query response JSON to App State requires parsing

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10290]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.5
  * App Version: 2.5

**Describe the bug**
When I push the response of a query in an action chain to App State, it gets saved as a string, and I have to parse it to access the props.

**To Reproduce**

1. Create a button with **Execute Query** action for REST datasource
2. Add a second action **Update State** and push the query result
3. Try to access a prop of the app state - it doesn't work
4. Try to access a prop of the app state after doing `JSON.parse($("State.Response")).prop` → now it works

**Expected behavior**
If I push a JSON object to app state, it should not be saved as a string.

**Screenshots**

![Screenshot 2023-04-13 at 13.19.51.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/2ec0362e-a933-4dfa-8400-ee224f97960c/cd245595-cc31-4747-8a52-34d8b17da150)

**This doesn't work**

![Screenshot 2023-04-13 at 13.20.27.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e1fa8680-111b-4819-9824-5a72d81a0a99/2201ac65-3ba5-439b-b95c-430459364fd7)

**But this does work**

![Screenshot 2023-04-13 at 13.22.20.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/380d2f4b-071e-49eb-9f64-96918b1150a3/800a1567-65fc-48bb-ac2a-cd3062585ec8)

**App Export**

[My app-export-1681388559206.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/c3deecf2-91cd-4146-9350-2dd8a3cbe5cd/90757eeb-4fc2-4c09-8ea3-568f7c33b119)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6850](https://linear.app/budibase/issue/BUDI-6850/pushing-query-response-json-to-app-state-requires-parsing)</sub>

**Comment by PClmnt** [comment]
Ran into this as well and had a quick look - this is because if you pass a handlebars expression in the Update State button action then it resolves to a string and `updateStateHandler` stores said string. 

Maybe we should parse the object in `updateStateHandler` before storing it?

**Comment by aptkingston** [comment]
Yep as Peter said it's just because HBS resolves everything to a string.

2 potential solutions if you want to store an object rather than a string:
- Use the `literal` HBS helper: this will prevent it treating everything as a string. e.g. `{{ literal (Action 1.Query result) }}` (I'm inserting brackets because I'm not sure how it will react to the spaces, but you can tinker with that)
- Use JS which allows you to return any type

**Comment by PClmnt** [comment]
I actually think the `literal` handlebars helper is pretty important - we should maybe document it in the bindings section in the docs.
