### ISSUE TITLE
Why is the default not to use a persistent volume?

### ISSUE THREAD

**Issue by Rambatino** [Budibase/budibase#10306]
Given the fact it was in a statefulset I made the unwitting assumption that it would have a pvc, stupid now I know.

https://github.com/Budibase/budibase/blob/develop/charts/budibase/values.yaml#L242

I think this should be changed to true, lost 6 months worth of data when we removed some k8s nodes.

**Comment by jonnymccullagh** [comment]
Sorry @Rambatino that you had a bad experience. There are many defaults in the example config files that should be assessed before running in production, but we can't class those as bugs.

**Comment by Rambatino** [comment]
I'm not classing it as a bug, only that it seems like an incorrect default that may (and has) caught people out.
