### ISSUE TITLE
Self Host - Dependency decoupled deployment

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#10333]
Maintain an official docker compose for a self host decoupled installation, where BB can be installed and easily updated without all its dependencies in cases where people want to use their existing couchDB/mimio/redis installations.

**Comment by shogunpurple** [comment]
Hi @poirazis - are you using the budibase CLI? If you have a pretty custom setup, you are probably at the point now where it would be a lot easier for you to manage the `docker-compose.yaml` yourself

**Comment by poirazis** [comment]
hey @shogunpurple ,
i guess you are right ! :)
