### ISSUE TITLE
[BUDI-6888] Unable to save form if date field is empty

### ISSUE THREAD

**Issue by megatron757** [Budibase/budibase#10341]
**Checklist**
- [ x ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: ankr

**Describe the bug**
We are unable to save a form to update a row if a date field is empty. Data validation is not configured on the field, and the field is not set to be required. 
I think this may be related to https://github.com/Budibase/budibase/issues/10131, but that issue relates to importing data into a date field. 

**To Reproduce**
1. Go to form
2. Click the birthdate field, and empty out the field
3. Click Save on the form 
4. See error "birthdate must be a valid date"

**Expected behavior**
I expect to be able to click Save on the form and the row be saved, regardless of if the date field is empty or populated.

**Screenshots**
![Screenshot 2023-04-18 at 12 25 55 PM](https://user-images.githubusercontent.com/106602832/232857420-4bae1c29-b3d2-4ab0-8fc8-876f8bc5e9fa.png)
![Screenshot 2023-04-18 at 12 26 04 PM](https://user-images.githubusercontent.com/106602832/232857429-87fd1c75-e96d-4849-be3b-34648bc688e2.png)
![Screenshot 2023-04-18 at 12 26 22 PM](https://user-images.githubusercontent.com/106602832/232857443-6a8c0c7d-93ec-415f-8ba6-b84b4d8483ec.png)
![Screenshot 2023-04-18 at 12 28 41 PM](https://user-images.githubusercontent.com/106602832/232857461-5d09ffde-2abe-4c3c-a3f9-b73c909e17cd.png)
![Screenshot 2023-04-18 at 12 29 06 PM](https://user-images.githubusercontent.com/106602832/232857480-62f53df3-c891-432d-93c9-e4f8a6d38d09.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Version 112.0.5615.121 (Official Build) (arm64)

**Additional context**
Backed DB is postgreSQL

<sub>[BUDI-6888](https://linear.app/budibase/issue/BUDI-6888/unable-to-save-form-if-date-field-is-empty)</sub>

**Comment by shogunpurple** [comment]
We can't seem to recreate this one - could you share an app export if possible to help us debug?

**Comment by megatron757** [comment]
> We can't seem to recreate this one - could you share an app export if possible to help us debug?

Yes, is there a way to send it securely to you?
