### ISSUE TITLE
PSQL Query: Binding not parsed

### ISSUE THREAD

**Issue by MaxBernstetter** [Budibase/budibase#10390]
Self hosted Budibase (v. 2.5.2.)

Query:
![image](https://user-images.githubusercontent.com/77627676/233918023-fb973d9e-7499-4788-b817-f1acaf2fdfeb.png)

SQL from payload: ""SELECT * FROM projectservice.projects\nWHERE\n\n\t\tNOT exists \n\t\t\t(SELECT FROM projectservice.relation_projects_applications\n\t\t\tWHERE projectservice.projects.id = projectsid)\n\t\t\t\n\t\tAND  projectservice.projects.fk_projectmanager = {{user}}\n"
"
--> User binding is not parsed but just read as part of the query string

**Comment by shogunpurple** [comment]
You need to wrap `'{{ user }}'` in quotes.
