### ISSUE TITLE
Use without sign-up?

### ISSUE THREAD

**Issue by brasilikum** [Budibase/budibase#1040]
Hey, as this is promoted as open source and the definitions of open source vary, I was wondering if there is a way to use budibase without sign-up. 

It's ok if this it's not, I am just wondering if it's the kind of open source I could continue to use if you guys go out of business, or it's the kind of open source where the code is open for trust’s sake but in the end it's a commercial project.

Please point me to the docs in case I missed that part.

**Comment by mjashanks** [comment]
Hey @brasilikum - welcome!

You are correct in flagging this as a bug! Currently, you cannot progress past the first screen, without entering an API key (which you get on signup). 

Previous to yesterday's self-hosting release, users could only deploy to our cloud platform - therefore, they needed an API key from our deployment.

We will fix this. Once we do fix this, you will be able to download the Builder from the releases section, and self-host the rest.

You will absolutely be able to use Budibase if we go out of business. Building a community around Budibase will be key for us. The codebase will be open-source forever - a strong community will be able to continue development, should Budibase the company disappear.

All that said, this is indeed a commercial open-source project. We see our commercial success to be dependant on the health of our community, and vice-versa. it is important for us that these two things are aligned.

**Comment by shogunpurple** [comment]
Hi @brasilikum - the above issue has been addressed with https://github.com/Budibase/budibase/issues/1040. It will be available in the next release, along with a smoother and simpler self-hosting process. Thank you again for your feedback and taking the time to raise this issue. I'll close this one out if you are satisfied :)

**Comment by brasilikum** [comment]
Very nice!
