### ISSUE TITLE
[BUDI-6922] The Number 0 cannot be displayed on input number fields, when being pulled in from a data provider.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#10412]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Docker compose
  * Budibase Version: 2.5.6
  * App Version: 2.5.6

**Describe the bug**
Whenever saving a number input with the value of 0 to a table within the db. Whenever, it comes to displaying the input again in order to edit it, the value doesn't appear. Likely a result of how 0 interacts with istruethy isfalsey.

**To Reproduce**

1. Go to a table, create a number based column.
2. Create a CRUD page.
3. Create a record with the number column being set to zero.
4. Click on the row of the table for the newly created record.
5. See the number input missing the 0 which was added to the record.

**Expected behavior**
Show 0 instead of removing it from the input.

**Screenshots**

![Ui 0 display bug.gif](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ff820873-beba-49bc-907a-b35de736fc25/cd5403fe-2a08-49c7-98ba-17fcb28f5934)

**App Export**

[Number test-export-1682419625471.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f70221ee-820a-4b9c-9d63-216d418ce915/19e13788-1495-4e5d-b599-4df18e8b94b6)

**Desktop (please complete the following information):**

* OS: Ventura 13.3.1 - 22E261
* Browser Brave
* Version [Version 1.50.121 Chromium: 112.0.5615.138 (Official Build) (arm64)](https://brave.com/latest/)

**Additional notes**

This may be related to: [https://github.com/Budibase/budibase/issues/10118](https://github.com/Budibase/budibase/issues/10118). However, thats based around filtering.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6922](https://linear.app/budibase/issue/BUDI-6922/the-number-0-cannot-be-displayed-on-input-number-fields-when-being)</sub>

**Comment by AlejandroFNadal** [comment]
I filed this bug here: [#10182](https://github.com/Budibase/budibase/issues/10182) and it was closed based on it being related to #10118 . Perhaps the name of 10118 should be changed so that it reflects the fact that 0 cannot be displayed. It will also not work if you just do return 0 in a javascript function, without a data provider.

**Comment by sebastian-jansson** [comment]
Related to this I guess, when editing a row where 0 is stored, the value is not displayed and need to be re-entered before saving:

![image](https://github.com/Budibase/budibase/assets/54795430/4c658a00-dce3-4fb7-919f-2f4718c6a4bb)

**Comment by ConorWebb96** [comment]
This issue seems to have popped up again, heres the discord thread of were it came [about](https://discord.com/channels/733030666647765003/1022503693867823104/1192387738633261086).
