### ISSUE TITLE
[BUDI-6958] Allow Automation Triggers to store and use the output after running.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#10445]
When running an automation trigger allow the output to be available to be used in other actions. For example showing some of its contents within a notification popup.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6958](https://linear.app/budibase/issue/BUDI-6958/allow-automation-triggers-to-store-and-use-the-output-after-running)</sub>

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/9890
