### ISSUE TITLE
[BUDI-6962] POSTGRES - Defining existing relationship loses table, requires Fetch.

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#10458]
Self Hosting - 2.5.8
Chrome : latest

When you go through the process of defining an existing relationship, the relationship gets defined, but you need to refetch the tables list.

Reproduce  

https://user-images.githubusercontent.com/80512170/235464435-99885d93-6e5b-4e3d-9ad8-999a1e4be231.mov

<sub>[BUDI-6962](https://linear.app/budibase/issue/BUDI-6962/postgres-defining-existing-relationship-loses-table-requires-fetch)</sub>

**Comment by melohagan** [comment]
Hey @poirazis 

I wasn't able to recreate this on develop branch. Hopefully it will be fixed for you in the next release.

With that said, it appears your invoice table has no rows? It may be a good idea to try and add some data to your tables before defining the relationships.
