### ISSUE TITLE
[BUDI-7050] MySQL foreign key getting overwritten in a relation

### ISSUE THREAD

**Issue by Jhaddad-galenvs** [Budibase/budibase#10453]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Budibase Version: 2.5.9 
  - App Version: 2.5.9 
  
**Bug Description**
When creating a relation between two MySQL tables, if you update the row , the foreign key gets overwritten with the id.

**To Reproduce**
1. in your MYSQL source, go to relations and define a relationship , likr the following :
![Screenshot 2023-04-28 142141](https://user-images.githubusercontent.com/122468788/235224302-cf19c15a-8b4a-4a77-86da-dbd1d0c3c2ef.png)

now we have the following creation created and a formula column that takes img data from the first table :
![Screenshot 2023-04-28 142325](https://user-images.githubusercontent.com/122468788/235224813-5cf2aac1-d41c-4e78-9656-dda4437cec5e.png)
![Screenshot 2023-04-28 142351](https://user-images.githubusercontent.com/122468788/235224816-d75830c6-665f-4cf7-9596-da8f2c48c1d7.png)

3. Now update a row using a side panel (that has a form of type Update) :
This is row we gonna test the foreign key highlighted : <br>
![1234](https://user-images.githubusercontent.com/122468788/235226511-f105f362-777c-4d49-9674-9bdd1b283373.png)

we update one random field and then click save:<br>
![Screenshot 2023-04-28 142838](https://user-images.githubusercontent.com/122468788/235226990-6129657f-ad43-45e9-aab5-311f0ef603c2.png)

![Screenshot 2023-04-28 143101](https://user-images.githubusercontent.com/122468788/235227028-23d269b6-931d-4670-8d53-d62bac6c3bd2.png)

4. now click save 
the is what the save button do : <br>
![Screenshot 2023-04-28 142948](https://user-images.githubusercontent.com/122468788/235227497-4431bc07-e2e6-465d-b3d8-843cc6689791.png)

5. See error as the foreign key gets over written with the id of in this case (the kits table item) (CF has id :17 ) :
   
![4321](https://user-images.githubusercontent.com/122468788/235228016-9915db1e-7a4b-4d78-a6da-2b24aec15166.png)

**Expected behavior**
the value should stay as is and not be overwritten when updated .

<sub>[BUDI-7050](https://linear.app/budibase/issue/BUDI-7050/mysql-foreign-key-getting-overwritten-in-a-relation)</sub>

**Comment by shogunpurple** [comment]
This one is user error given the allocation of the primary key column
