### ISSUE TITLE
[BUDI-7262] Invalid characters in query names

### ISSUE THREAD

**Issue by diogenesbrussels** [Budibase/budibase#10466]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.5.9

**Describe the bug**
When a query name contains a parenthesis, the js objects are no longer usable.

**To Reproduce**
1. Create and save a read query with parenthesis in the name
2. Use this query in a data provider
3. Try to manipulate the results in js
4. The value is undefined

**Expected behavior**
Prohibit characters in query names or escape them in the name of js objects

<sub>[BUDI-7262](https://linear.app/budibase/issue/BUDI-7262/invalid-characters-in-query-names)</sub>

**Comment by melohagan** [comment]
Hi @diogenesbrussels 

Could you provide some more information please. I wasn't able to determine any immediate issue.

 - What does the data look like that's being returned from the query?
 - What does your component tree look like?
 - What does your JavaScript look like? Where is the binding?

**Comment by diogenesbrussels** [comment]
Hey @melohagan 

The request itself does not seem to be the problem.
Here is an example:
Query
SELECT * FROM cities LIMIT 0,5
Query output:
![image](https://user-images.githubusercontent.com/91942877/236814206-0777b68b-1e18-45fa-b002-561d18dcbfa3.png)

My test page:
![image](https://user-images.githubusercontent.com/91942877/236814604-9985b444-451f-42bf-8d34-45d7c1adca83.png)

The JS binding:
![image](https://user-images.githubusercontent.com/91942877/236814762-fa63ebd0-5192-42da-965f-c3721f35ac41.png)

This var is undefined.
Quick note: if you create your component with binding that works then duplicate it and change the query to one with parenthesis, it will work. If you open the JS binding and then hit Save: the binding is now invalid.

Let me know if you have enough information :)

**Comment by AlejandroFNadal** [comment]
This also is blocking the duplicate query command
