### ISSUE TITLE
Customizing themes does not change button color

### ISSUE THREAD

**Issue by caseyatMission** [Budibase/budibase#10489]
I've noticed that on my current application, I can't change button coloring by changing the theme. Changing these accent colors seems to have no effect on button styling throughout the app.

<img width="457" alt="Screenshot 2023-05-04 at 4 59 22 PM" src="https://user-images.githubusercontent.com/124637427/236354465-fdd22d2b-cca8-4200-925f-f53b32437c98.png">

**Comment by aptkingston** [comment]
Hey @caseyatMission. It depends what type of button you're using (which you can choose in the button settings) - only the "Action" variant has a solid background color, and that will use your accent color.
