### ISSUE TITLE
Builder - Make "icon" property of core Icon component bindable

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#10484]
Make the "Icon" property bindable so it can be set dynamically from a value coming from the db ( querry )

Scenario
Data Provide -> Repeater -> Icon ( show conditionally different icon per row )

Currently this can be achieved via Conditional UI, but i propose the above way would be better.

<img width="531" alt="Screenshot 2023-05-04 at 4 02 29 PM" src="https://user-images.githubusercontent.com/80512170/236212814-cef2a08a-3771-4cd9-ad29-ecc098886a07.png">

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/12406
