### ISSUE TITLE
Invisible Ink Form Fields: Update form saves responses, but does not display them as default values

### ISSUE THREAD

**Issue by rose111data** [Budibase/budibase#10499]
**Checklist**
- [V] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: DigitalOcean 
  - Budibase Version: 2.6.2 (has been occurring for past two updates)
  - App Version: 2.6.2 (has been occurring for past two updates) 

**Describe the bug**
I have a table, with each row containing an individual's responses to a form, and columns for related interview questions. In an Update form, the fields for the responses prefill appropriately into the form, and fields corresponding to the interview questions for the interviewer to fill out. They submit just fine, and appear in the data source as it should. Once interview questions are saved and the form is opened again, however, whatever text in the text fields is invisible until you click on the form field. 

![budibase](https://user-images.githubusercontent.com/116825158/236569245-245468a9-b5e8-4a89-8e5c-4a7581b0ad55.gif)

I've tried everything I know to try, including painstakingly going through each form field and setting their default as the repeater value. I was hoping this recent update might magically fix it, but alas. 

**To Reproduce**
1. Make an update form from table from Postgres Data Source
2. Submit update form, successfully saves
3. Reopen completed form for the same individual
4. Filled form fields = invisible ink

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1 Vera
 - Browser: Firefox (Happens on Chrome too)
 - Version 112.0.2

**Additional context**
I can't find any other open (or closed) issues on this, though I'm about 80% sure I'm just doing something wrong.

**Comment by melohagan** [comment]
Hi @rose111data 

I'm not able to recreate any particular issue here. Could you please provide some additional screenshots of your component tree, and any relevant actions or bindings that you have setup.

An app export would be very useful if you are able to provide it. You're welcome to post that here if it's not sensitive, or email a link through to support@budibase.com

**Comment by rose111data** [comment]
> Hi @rose111data
> 
> I'm not able to recreate any particular issue here. Could you please provide some additional screenshots of your component tree, and any relevant actions or bindings that you have setup.
> 
> An app export would be very useful if you are able to provide it. You're welcome to post that here if it's not sensitive, or email a link through to [support@budibase.com](mailto:support@budibase.com)

Great, thank you! I've just emailed my app export, but I'll try to explain the layout a bit. I've modified a Row Explorer block, where clicking on a person's name brings up the form on the right panel  - the page /test has just the panel that appears after clicking the name:

![WHOLE](https://github.com/Budibase/budibase/assets/116825158/e88c802c-852b-4545-b247-0c6a3f88b9f9)

Could it be an issue with a show/hide action somewhere with the modified Row Explorer?

**Comment by melohagan** [comment]
Hey @rose111data 

Thank you for the app export, I've had a quick look, but I think I need more information.

Would you be able to share detailed steps to recreate the issue including the name of the screen involved, and the steps taken in your app.
A screen recording would be very helpful as well!

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/11619

There may be some issues when ejecting a row explorer block.
