### ISSUE TITLE
Can't edit write access

### ISSUE THREAD

**Issue by ben-biber** [Budibase/budibase#10490]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: <method> docker compose
  - Budibase Version: <version> 2.6.1
  - App Version: <version> 2.6.2
 
**Describe the bug**
Can't edit write access to a data table

**To Reproduce**
1. Go to 'Data'
2. Click on 'Add Source'
3. Create an 'BudiBase DB' table
4. Click on 'Access'
5. You can only edit read access

**Expected behavior**

I earlier versions it was possible to edit the write access
  
**App Export**
[Sommerfreizeit 2023-export-1683272448680.tar.gz](https://github.com/Budibase/budibase/files/11404166/Sommerfreizeit.2023-export-1683272448680.tar.gz)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: safari
 - Version 16.4

**Comment by shogunpurple** [comment]
Hi @ben-biber - we are currently looking into this one and will have a fix out ASAP.
