### ISSUE TITLE
Deployed app does not trigger Zapier webhook

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1050]
**Describe the bug**
If I set up an automation to run a Zapier webhook, it runs on Localhost, but not when deployed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create automation, and setup Zapier action
2. Test automation in preview (works)
3. Deploy
4. Test automation in the deployed app

**Expected behaviour**
Zap should run

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Additional context**
I waited a few minutes for zap to run, and it did not.

Reported by @DaveGeorge via discord

**Comment by rr559** [comment]
- - [ ] [@](
