### ISSUE TITLE
[BUDI-7394] Sending single quote or double quote via data in REST API fails

### ISSUE THREAD

**Issue by clixsoftware** [Budibase/budibase#10504]
**Checklist**
- [ *] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 

**Describe the bug**

**To Reproduce**
1. Go to 'Attempt to send data with single or double quotes via REST api, even if escaped does not work. Also the handlebars "escape" command does not work.'
4. See error - Invalid JSON Request Body

**Expected behavior**

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [chrome]

**Additional context**
Please see : 
`{
    "allow_comments": true,
    "allow_likes": false,
    "allow_ratings": true,
    "title": "King Charles III and Queen Camilla are crowned",
    "summary": "Anti-monarchy protest group Republic said its members are still being held at a London police station.",
    "category": "memorandum",
    "content_source": "ceo-office",
    "must_read": false,
    "collection_id": "30",
    "video_url": "",
    "video_source": " ",
    "cover_image_url": " ",
    "cover_image_json": "[]",
    "attachments_json": "[{\"size\":524270,\"name\":\"SRDPaper_Digital-Signage-in-Healthcare.pdf\",\"url\":\"/files/signed/prod-budi-app-assets/app_89314a149e9d44758495332d04db48c6/attachments/276cb232-8f62-45e9-b138-c32c19af17fd.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=e4bbeb5b-04f8-4247-9528-bdb72cdf8265%2F20230506%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230506T190742Z&X-Amz-Expires=3600&X-Amz-Signature=21d57d54ac1cd262098bad44dc23367877f8bac1029b116199959901ed60fda9&X-Amz-SignedHeaders=host\",\"extension\":\"pdf\",\"key\":\"app_89314a149e9d44758495332d04db48c6/attachments/276cb232-8f62-45e9-b138-c32c19af17fd.pdf\"}]",
    "start_publishing_at": "2023-05-06 02:07 PM",
    "tags": "buy,procurement,",
    "pinned": true,
    "pinned_globally": false,
    "pinned_until": "2023-05-24T17:00:00.000Z",
    "body": "Earlier Saturday, Republic told CNN that London police arrested the organizers of Saturday’s anti-monarchy protest without providing any reason. \n\nAt around 7 a.m. local time, police stopped six Republic organizers and told them they were detaining and searching, Republic Director Harry Stratton told a CNN producer at the protest.\n\nAccording to London's Metropolitan Police Service, more than 50 arrests have been made on Saturday.",
    "cover_image_file_id": "0",
    "stop_publishing_at": ""
}`

<sub>[BUDI-7394](https://linear.app/budibase/issue/BUDI-7394/sending-single-quote-or-double-quote-via-data-in-rest-api-fails)</sub>

**Comment by Simoon-F** [comment]
same，I am the backslash appears. `\`


```json
{
message: "Invalid JSON for request body",
status: 400
}
```

**Comment by shogunpurple** [comment]
Just tested this with the JSON that you provided - the problems are the `attachment_json` and `body` fields. You must double escape (`//`) the characters, or they can't be parsed by `JSON.parse` - you will need to edit your JSON appropriately so it can be parsed.
