### ISSUE TITLE
Apps will not load after upgrading Budibase version

### ISSUE THREAD

**Issue by DylanLiang1** [Budibase/budibase#10519]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.6.8
  - App Version: 1.0.46 and 2.6.8

**Describe the bug**
We upgraded Budibase from version 1.0.46 to version 2.6.8. Found the follow issues:
1. The Design page won't load when editing the apps.
2. When viewing the published apps, they show error message "There was an error loading your app. The Budibase client library could not be loaded. Try republishing your app." We have tried updating the app version, republishing the apps, and creating new apps from templates. The error message stays the same.

**To Reproduce**
1. Update Budibase to latest version in docker
2. View pushlished apps

**Expected behavior**
The design page and the apps should run 

**Screenshots**
See attached
  
![Screenshot 2023-05-08 135859](https://user-images.githubusercontent.com/126724025/236897240-252b86a5-36ec-45ba-9332-deb9e6d2d106.png)
![Screenshot 2023-05-08 140057](https://user-images.githubusercontent.com/126724025/236897241-8754864e-69c1-4893-ac99-546492f81ed1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 2.6.8

**Comment by rgelsi** [comment]
I have a similar issue with an app after updating to 2.6.8 (but from 2.6.2).

I tried to delete components until it worked again. The component that is causing the issue is a date picker in a side panel that has the "Time only" checkbox enabled. I need to update a Postgres time column and have not found a way around this.

**Comment by rgelsi** [comment]
PR #10631 included in v2.6.20 solved my issue
