### ISSUE TITLE
fix: README.md assert

### ISSUE THREAD

**Issue by shikharvashistha** [Budibase/budibase#10516]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Screenshots**
![image](https://user-images.githubusercontent.com/51105234/236823926-a8b733f7-12a1-4343-bd6c-ff3128938a72.png)

**Issue**

Fix the assert path/image 

**suggested labels** : good-first-issue && documentation

**Comment by jaysoni-ash42** [comment]
@melohagan  i want to work on this issue what is the correct image path that would be used here and  what about suugest labels should it go under the docs  general documentation and interactive api documentation?

**Comment by shikharvashistha** [comment]
> @melohagan i want to work on this issue can you provide me a correct image path that would be used here and what about suggested labels should it go under the docs general documentation and interactive api documentation?

cc: @melohagan @adrinr
