### ISSUE TITLE
Automation panel does not scroll

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#10535]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.6.8
  - App Version: 2.6.8

**Describe the bug**
You cannot scroll in the automation side panel

**To Reproduce**
1. Create an app
2. Create at least 5 automatons
3. Resize the screen so some of the automatons aren't visible
4. You cannot scroll down to see them

**Expected behavior**
I am able to scroll

**Screenshots**
![panel](https://github.com/Budibase/budibase/assets/97764630/a7acfec9-77f6-4f69-b44f-da5ad2ce594a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 113.0.1774.35

**Comment by jaysoni-ash42** [comment]
@melohagan  i want ot work on this issue just some few questions only the automation list should scroll or the whole panel becasue same probelm arise in data list as well.

**Comment by melohagan** [comment]
Hey @jaysoni-ash42 

It would just be the automation list that needs to scroll. It is already working for the datasource list as you can see here:

![scroll](https://github.com/Budibase/budibase/assets/101575380/63939108-ac94-44d1-824f-7b91c09521fd)

For automations there is no scrollbar:
<img width="262" alt="Screenshot 2023-05-17 at 10 54 07" src="https://github.com/Budibase/budibase/assets/101575380/70e4cfa4-c7ed-4890-98c9-7aed17366561">

**Comment by jaysoni-ash42** [comment]
> Hey @jaysoni-ash42
> 
> It would just be the automation list that needs to scroll. It is already working for the datasource list as you can see here:
> 
> ![scroll](https://user-images.githubusercontent.com/101575380/238907121-63939108-ac94-44d1-824f-7b91c09521fd.gif)
> 
> For automations there is no scrollbar: <img alt="Screenshot 2023-05-17 at 10 54 07" width="262" src="https://user-images.githubusercontent.com/101575380/238907429-70e4cfa4-c7ed-4890-98c9-7aed17366561.png">

@melohagan  thanks for the clarification i'll start working on this issue
