### ISSUE TITLE
[Grid System] - Allow column rearrangement with DND list

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#10537]
it would be most useful if we could rearrange the order of the columns in the grid, from the show / hide columns dropdown by allowing to drag and drop the columns to set their order.
<img width="388" alt="Screenshot 2023-05-10 at 2 27 05 PM" src="https://github.com/Budibase/budibase/assets/80512170/d2caf7d9-7b5b-4973-beca-4c29b5b51dad">

**Comment by aptkingston** [comment]
Valid suggestion!

Just also making sure you know that you can drag and drop them to reorder in the actual grid itself - just in case you didn't know! But this is still a valid suggestion 👍

**Comment by poirazis** [comment]
I actually didn't know i could drag drop in the grid ! I just thought that being able to rearrange there would centralize column management more. Amazing work overall @aptkingston !
