### ISSUE TITLE
[BUDI-7070] Helm chart uses wrong image tags

### ISSUE THREAD

**Issue by mauriziobrilli** [Budibase/budibase#10543]
**Checklist**
- [*] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: k8s
  - Budibase Version: 2.6.9

**Describe the bug**
Image tags in helm chart lack the initial 'v'. E.g. budibase/budibase:2.6.9 instead of budibase/budibase:v2.6.9. I also checked version 2.6.8, same situation

**To Reproduce**
1. helm install --create-namespace --namespace budibase budibase budibase/budibase
2. kubectl get pods -n budibase
3. 

>     Output:
    NAME                              READY   STATUS             RESTARTS   AGE
    minio-service-785c7bf9f8-9bzw5    1/1     Running            0          2m22s
    redis-service-5dcbf4db55-cb2tv    1/1     Running            0          2m22s
    buditest-couchdb-0                2/2     Running            0          2m22s
    buditest-couchdb-1                2/2     Running            0          2m22s
    buditest-couchdb-2                2/2     Running            0          2m22s
    worker-service-5f7f9cc457-4bhvl   0/1     ImagePullBackOff   0          2m22s
    app-service-75f55fb46-9mdqb       0/1     ImagePullBackOff   0          2m22s
    proxy-service-7796b4644b-svwck    0/1     ImagePullBackOff   0          2m22s

4. describe pods --namespace budibase - for each budibase container Events report failure to pull image (e.g. Pulling image "budibase/proxy:2.6.9")

**Expected behavior**
All services running

<sub>[BUDI-7070](https://linear.app/budibase/issue/BUDI-7070/helm-chart-uses-wrong-image-tags)</sub>

**Comment by ecarlotti** [comment]
I can confirm that bug, I had the same issue. The helm chart is using images names missing the "v" before the version number, e.g. "budibase/proxy:2.6.9" instead of the correct "budibase/proxy:v2.6.9" - That happens on the three services mentioned by @mauriziobrilli

**Comment by jamesread** [comment]
Can confirm also - the helm release is currently broken, and I had to manually patch the deployments to add the "v" in the "image: " spec. 

I was going to PR this as a quick fix, but it seems  that the image version is populated from the chart version (annoyingly), so I'm uncertain if the original authors want to add the "v" to the chart version too, or the "v" just to the image version. Adding the "v" to the chart version too may break some helm things / auto-upgrades etc.

**Comment by shogunpurple** [comment]
Hi folks, we are currently looking into this one and potentially planning on getting rid of the `v*` concept altogether since there's not much point.

For now you can work around this by setting the following in your `values.yaml`:
```yaml
globals:
  appVersion: "" # Use as an override to .Chart.AppVersion
```

Or when you install with the `helm` command directly.
```
helm install budibase-helm budibase/budibase --set globals.appVersion=v2.0.0
```
