### ISSUE TITLE
Issue when there's an error during data source import at app creation

### ISSUE THREAD

**Issue by doingandlearning** [Budibase/budibase#10549]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker compose
  - Budibase Version: 2.6.9

**Describe the bug**
When adding the data source during app creation, I got an error. When I tried to fix the login details, the error I get the second time is that an app with that name already exists.

**To Reproduce**
https://www.loom.com/share/55dce2e3a69e43c0aea03585ae328051

- Add a new app
- Add a postgres database but get the details wrong
- Try to add the postgres database with correct credentials a second time

**Expected behavior**
- The error would relate to the database connection
- The onscreen error would give more context 

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser: Chrome

**Comment by aptkingston** [comment]
Fixed and deployed 👍
