### ISSUE TITLE
Duplicate protected columns in users table

### ISSUE THREAD

**Issue by PEP4711** [Budibase/budibase#10547]
**Checklist**
- [x ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: <tenantId>  pepdev

**Describe the bug**
After updating the user table in my app with help of a form block I recognizes duplicate columns for email, firstname, lastname etc in the data section of the designer. These columns are protected and cannot be removed by me any more. 

**To Reproduce**
1. Add a column "language" to the users table 
2. Update the users table in an app using a form block in preview mode. Eventually try to change the name field and or the added language field.
3. Click on save.  
4. Go to the data section of thedesigner Scroll down to '....'
5. See error in the attachend screenshots --> All default columns have got duplicates with uppercase column names. 
![image](https://github.com/Budibase/budibase/assets/133233425/634e707b-06ba-4b27-8090-fef756e3b79b)
![hc_3718](https://github.com/Budibase/budibase/assets/133233425/3b3deb5b-1e0a-429a-9e6b-053ce071b77c)

**Expected behavior**
No fields are created.

**Screenshots**
  ![image](https://github.com/Budibase/budibase/assets/133233425/634e707b-06ba-4b27-8090-fef756e3b79b)
![hc_3718](https://github.com/Budibase/budibase/assets/133233425/3b3deb5b-1e0a-429a-9e6b-053ce071b77c)
![hc_3719](https://github.com/Budibase/budibase/assets/133233425/51383c91-0c94-4817-a61b-b58a371e5110)

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.
[TrainDoc-export-1683814147326.tar.gz](https://github.com/Budibase/budibase/files/11453036/TrainDoc-export-1683814147326.tar.gz)
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22]  Version 112.0.1722.58 (Offizielles Build) (64-Bit)

**Additional context**
It would be great if someone could help me to remove the duplicate columns.

**Comment by shawnweeks** [comment]
I ran into this issue today and in testing I discovered that it only happens if you've hidden columns on the user table before adding the new column. If you don't have any columns hidden it works fine but once it's broken deleting the column doesn't fix it.

**Comment by PEP4711** [comment]
Unfortuantely I am not able to edit or delete the duplicate columns. I assume that budibase checks the names but not case sensitive. Hence a columns email and also EMail is protected.

**Comment by aptkingston** [comment]
Thanks for reporting @PEP4711. I've been able to reproduce this myself, and I'm working on fix.

**Comment by aptkingston** [comment]
I'll update here once the above PR has been merged and deployed. Once deployed, you'll be able to delete the duplicated user columns and won't appear again.

**Comment by DAVNRW** [comment]
Big thanks!
