### ISSUE TITLE
[BUDI-6986] Update Airtable connection to support OAuth (and PAT?)

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10557]
The API Key will be deprecated as of February 2024: [https://support.airtable.com/docs/airtable-api-key-deprecation-notice](https://support.airtable.com/docs/airtable-api-key-deprecation-notice)

We need a generic strategy for handling OAuth refreshing, as this will affect Airtable, Googlesheets, eventually REST APIs etc.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6986](https://linear.app/budibase/issue/BUDI-6986/update-airtable-connection-to-support-oauth-and-pat)</sub>

**Comment by helena-pa** [comment]
Hi,
There's less than a month and a half to go before the Airtable API key becomes deprecated.
I'd like to launch a new Budibase project based on Airtable, but I need to be confident that I won't have a service interruption on February 1.
Will this issue be resolved in time, or should I give up using Budibase?

**Comment by ash-development** [comment]
bumping this as it is currently not possible to connect airtable to budibase

**Comment by mikec5** [comment]
Hi, new to Budibase, I'm use Airtable token and baseid. Keep getting the following error. Please let me know how to fix this. Thanks

![image](https://github.com/Budibase/budibase/assets/49621855/d33cba3b-e517-472e-9b45-41fad1bafdf5)

**Comment by melohagan** [comment]
Hey @ash-development @mikec5 @InesRefra 

Addressing this is not on our roadmap. We're going to hide the Airtable connector from the datasources list going forward.
