### ISSUE TITLE
Running Budibase on 1vCPU and 1 GB Ram on DigitalOcean is no longer possible.

### ISSUE THREAD

**Issue by smad-bro** [Budibase/budibase#10564]
After running the recent update of Budibase, the app has been crashing always. When I checked 'htop' I found that memory and CPU are at peak usage while running Budibase, and did not had any issues with previous versions.  It was giving me 502 Bad Gateway Errors all the time. I just upgraded the ram to 2 GB and it's working fine now.

**Comment by melohagan** [comment]
Hey @smad-bro 

We do recommend 2GB of RAM: https://docs.budibase.com/docs/docker#recommended-resources

Glad it is working fine for you now.

I'm going to change this issue from a bug as you were able to resolve the issue, however I'll keep the ticket open as a reference.

**Comment by shogunpurple** [comment]
Closing as we recommend that setup
