### ISSUE TITLE
image display from local budibase db table of attachments

### ISSUE THREAD

**Issue by vereng** [Budibase/budibase#10570]
**Checklist**
- [ 1] I have searched budibase discussions and github issues to check if my issue already exists
there is display images budibase help document which i followed but still not able to display image
**Hosting**

- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
1 created successfuly a table of image attachments (column names:  image_name,**image_file**)
2 under home screen under header added component data_provider named **images**
   pointing to the images_table
3  added repeater component 
4 added component like "image1"  which is already exists as one of the attachments 
  uploaded to the image_file attachment column
5 inserted the  binding field text pointing to the image file within the table 
according to instructions eamples
 as follows:
 {{url.images Repeater.images_table.image_file}} not work
{{images Repeater.images_table.image_file.0}}   not work
{{url.images Repeater.images.image_file}} not work
{{images Repeater.images.image_file}} not work
{{images_table Repeater.images.image_file}} not work
{{images Repeater.images_table.image_file[0].0}}   not work

6 expected behaviour
 when previewing the screen created the file name "image1"  may appear but not the already  uploaded image from table

7 screenshot 

![image](https://github.com/Budibase/budibase/assets/20261976/cc49b2c8-8391-42fd-b04b-826af0da7c2e)

8 OS: [e.g. iOS]
 -Firefox on Windows10

**Comment by aptkingston** [comment]
Hey @vereng. The correct syntax is `{{ Repeater.Users.Pictures.0.url }}`, for example. The important parts to note are that:
- Attachment data types are always arrays, so you need to use `.0` (or another index) to access a specific attachment
- Attachments have a schema of `{ name, url }`, so in this case I'm adding `.url` to get the URL and pass it to the image component

This is mentioned in the docs:
https://docs.budibase.com/docs/image#single-or-fixed-number-of-image-attachments

If you want to loop over all attachments and show an image for every one (assuming you're storing more than one attachment in each field) then you can use a data provider and repeater (or repeater block), and set the source to be the attachment field. Then you'll get explicit bindings for "Name" and "URL" as shown:
<img width="881" alt="image" src="https://github.com/Budibase/budibase/assets/9075550/f1a386eb-80e2-4c6f-91e5-ac8265dbd637">

This is also mentioned in the docs:
https://docs.budibase.com/docs/image#design

**Comment by vereng** [comment]
thanks so much - it worked using your syntax style by using " {{ Repeater.images_table.image_file.0.url}} "
f.y.i 
now seems that conditions to show or hide one specific image - using the condition configure for component 
like {{ Repeater.Row index }} or  {{ Repeater.images_table.image_name}} 
 is not really working  for repeater component 
but
is not the big deal - can hide or show it using the css
