### ISSUE TITLE
table bug only for 1 data table

### ISSUE THREAD

**Issue by aribyusronha** [Budibase/budibase#10581]
**Checklist**
- [ y] I have searched budibase discussions and github issues to check if my issue already exists

**Describe the bug**
The style of table is not like table. for example, i put the screenshoot in below. This bug only 1 data table, employee. when i change the dataprovider, the table back to normal.

**Screenshots**
![bug table](https://github.com/Budibase/budibase/assets/83322770/7f888d2f-c520-4285-96a9-27b63e6ab9a3)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Brave
 - Version : 2.3.5

**Comment by aptkingston** [comment]
@aribyusronha could you please use the rest of the bug template. Are you using cloud or self host, and if self host - what version are you on? Is your app also updated to the latest version?

**Comment by aribyusronha** [comment]
Nvm, Its was solved. i think its because wasn not updated yet, thanks
