### ISSUE TITLE
[BUDI-6999] [BUDI-7000] Auto ID not incrementing any more

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10599]
### Discussed in [https://github.com/Budibase/budibase/discussions/10585](https://github.com/Budibase/budibase/discussions/10585)

<div type='discussions-op-text'>

<sup>Originally posted by **JohannesM007** May 15, 2023</sup>

Since today 15-05-2023 the Auto ID of the Budibase DB tables are not incrementing any more.

We use Couch DB and a local hosted version 2.6.9 and also tried the latest version 2.6.11

If i add a new row in any of my tables the ID will not increment.

We tried to delete the last data record but this also will not help.

We tried Google Chrome and Firefox as well.

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/c4a89067-b388-44d6-be05-391bf54325d9/486d86fa-fd69-4b07-a887-d7f5fdde28bd)

Whats going wrong?  Is there a known issue in the moment?
Regards
Johannes
</div>

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6999](https://linear.app/budibase/issue/BUDI-6999/[budi-7000]-auto-id-not-incrementing-any-more)</sub>

**Comment by aptkingston** [comment]
PR here https://github.com/Budibase/budibase/pull/10593

**Comment by aptkingston** [comment]
Closing as the fix is now live 👍
