### ISSUE TITLE
feat: add `autofocus` to builder inputs and BBUI

### ISSUE THREAD

**Issue by yashank09** [Budibase/budibase#1059]
Supporting a discussion with @shogunpurple @joebudi , it would be nice to add an `autofocus` prop to `Input` elements in BBUI to enable a better experience for the user. 
The same prop will be added in the newer implementation of the component builder, that will be available to build Budibase apps.

**Comment by NicolasFabre81** [comment]
Hello @melohagan , just having the same need as @diogenesbrussels right now : I'm building my first mobile app, and on entering a new form, we currently need to tap on the first text field to be able to input something in it.
It would be nice to be able to force the focus of a certain on field onload of the screen.

**Comment by kzkondo** [comment]
I am always grateful for your help.
Has this issue been resolved?

**Comment by smart-account** [comment]
for what reason was this closed? An autofocus prop to input elements would help us a lot. We are building an app where barcodes are scanned with a barcode hand scanner, here it is very cumbersome because each time the text field must be selected manually. We have used other low-code solutions in the past where this autofocus was possible and the workflow was much easier.

**Comment by melohagan** [comment]
Hey @smart-account you could try using the **Scroll To Field** action. It will auto-focus the component, and if it's already in view then it wont scroll obviously.

**Comment by smart-account** [comment]
great thanks, the **Scroll To Field** action works for us!

**Comment by ecmonsen** [comment]
I just found this old issue as well. Scroll To Field does not work for us - I'd like to autofocus on a form field when the page loads in a browser, but when I navigate to Screen -> On screen load -> Add Action -> Scroll to Field, my form is not listed.

![Screenshot 2024-01-22 at 10 22 28 AM](https://github.com/Budibase/budibase/assets/851923/c368bf1f-fa42-4e39-a92a-b6c7a29650be)
