### ISSUE TITLE
[BUDI-7005] Error: cannot update identity column

### ISSUE THREAD

**Issue by danielbolt** [Budibase/budibase#10605]
**Checklist**
- [x ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Self hosted
  - Method: docker compose
  - Budibase Version: 2.6.11
  - App Version: 2.6.11

**Describe the bug**
When updating a record i get the folowwing MSSQL error:

'Cannot upodate identity column'

![image](https://github.com/Budibase/budibase/assets/60649319/69ebac5a-b717-4cdf-95c6-7ee973e7edb5)

The strange part is that this particular field isn't an identity column.

Table: team_persoon_positie_indeling
- Columns: 
tppi_id (PK) (Identity),
fk_team_tppi (relationship with table team.team_id)
fk_persoon_tppi (relationship with table persoon.persoon_id)
fk_positie_tppi (relationship with table positie.positie_id)
alert (bit)

Table: positie
- Columns
positie_id (PK) (Identity = yes)
positie (varchar)

`
CREATE TABLE [dbo].[team_persoon_positie_indeling](
	[tppi_id] [int] IDENTITY(1,1) NOT NULL,
	[fk_team_tppi] [int] NULL,
	[fk_persoon_tppi] [int] NULL,
	[fk_positie_tppi] [int] NULL,
	[alert] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[tppi_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]`

`CREATE TABLE [dbo].[positie](
	[positie_id] [int] IDENTITY(1,1) NOT NULL,
	[positie] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_positie] PRIMARY KEY CLUSTERED 
(
	[positie_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]`

I have set the following joins in Budibase configuration:

![image](https://github.com/Budibase/budibase/assets/60649319/7faa36c2-c973-44df-ac10-c0c67e99277c)

What's wrong?

**Desktop (please complete the following information):**
 - OS: Windows 11 (Docker = Ubuntu)
 - Browser: Windows Edge or Brave (no diffrences)
 - Version: Brave (1.51.114) Edge 

**Additional context**

<sub>[BUDI-7005](https://linear.app/budibase/issue/BUDI-7005/error-cannot-update-identity-column)</sub>

**Comment by mike12345567** [comment]
Hi @danielbolt - looking at your relationship configuration I believe that your primary key and foreign key entries need to be flipped. According to your table definitions the primary key of the "positie" table is "positie_id" - however you've set the foreign key as this. This is likely what is causing the error as it is attempting to update the primary key field which is not allowed.

If you flip the from and to tables, then you should be able to correct the columns as required.
