### ISSUE TITLE
tutorial step 5 not working

### ISSUE THREAD

**Issue by mikelty** [Budibase/budibase#1060]
i'm running the latest x64 distribution of budiasbebuilder on windows 10. 
i tried this twice and made sure i did everything correctly up to the UI design. but when i try to click into the detailed view for any individual row of sales rep it brings me back to the home page, even though the deals' detail page shows up just fine.
hope this can be resolved. thansk>

**Comment by shogunpurple** [comment]
Has since been resolved - this was a routing issue that we have fixed. Thanks for taking the time to raise an issue.
