### ISSUE TITLE
[BUDI-7014] Unexpected Query Rows Behavior When Filter is Empty and In List

### ISSUE THREAD

**Issue by shawnweeks** [Budibase/budibase#10632]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.6.11
  - App Version: <version> 2.6.11

**Describe the bug**
When using the `Query Rows` automation and an `Is In` filter the behavior of `When filter empty` is unexpected. If the binding is empty `Return all table rows` actually returns no rows and `Return no rows` throws an error on the action.

**To Reproduce**
1. Create an automation, i used a cron trigger
2. Create a `Query Rows` action pointed at the `Users` table
3. Define a filter on `email` is in using a binding and just leave it blank
4. Test automation with `When Filter Empty` set to both options and notice the output behavior

**Expected behavior**
I would expect `Return all table rows` to return all rows when the binding is empty and `Return no rows` to return no rows when the binding is empty like it does when you use the equals filter.

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome and Firefox Latest

**Additional context**
I've read over the documentation for Query Rows and Filters and don't see anything mentioned about the `is in` behavior but if the current behavior is expected then a small note in the documentation would be helpful.

<sub>[BUDI-7014](https://linear.app/budibase/issue/BUDI-7014/unexpected-query-rows-behavior-when-filter-is-empty-and-in-list)</sub>

**Comment by melohagan** [comment]
Fixed in **v2.7.11**
