### ISSUE TITLE
[BUDI-7022] Support segregated (exact) roles

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10645]
Currently roles act within a hierarchy which is useful, however some use-cases require roles that are specific to one table.

For example users from different departments: Librarians, Technicians, etc. Their access to data and screens should be siloed.

This affects:

* Navigation links
* Conditional UI
* Data access

On the flip side, is it better to have separate apps when you need this type of segregation?

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7022](https://linear.app/budibase/issue/BUDI-7022/support-segregated-exact-roles)</sub>

**Comment by yogeshvachhani** [comment]
Currently what we do is define 4 types of access right per page.

And then create a user and assign those rights that to a user on per page basis.

Here is a sample screenshot that my help give you some idea.
![image](https://github.com/Budibase/budibase/assets/109499572/f01bf8a1-0fa8-4a3b-b481-be3da32bac3c)
The application in the screenshot is built in PHP.

**Comment by melohagan** [comment]
Closing as you can technically accomplish this by having custom roles that inherit basic.
