### ISSUE TITLE
[BUDI-7042] Automation does not launch on app actions or cron trigger

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#10669]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.6.20
  - App Version: 2.6.20

**Describe the bug**
Automations do not trigger when using an app action or cron timer trigger.

**To Reproduce**
1. Create a new automation with the Cron Trigger
2. Select the preset Every Minute
3. Create a new step to do something (e.g. send an email)
4. Publish app
5. The step action will not execute

**Expected behavior**
The automation action does the steps requested of it.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 113.0.1774.50

**Additional context**
Clicking the Run Test button will run the automation as expected.
Possibly related to #10641
Reverting to 2.5.8 fixes this issue

<sub>[BUDI-7042](https://linear.app/budibase/issue/BUDI-7042/automation-does-not-launch-on-app-actions-or-cron-trigger)</sub>

**Comment by shawnweeks** [comment]
@FlaminWrap Did you publish your app after creating the automation?

**Comment by FlaminWrap** [comment]
Yes, these apps are published.

**Comment by FlaminWrap** [comment]
Reverting to 2.5.8 has fixed the issue for now.

**Comment by andz-bb** [comment]
I was unable to replicate this in my testing locally.

I initially created an app on my local dev instance running 2.6.20 with two automations: one triggered by a cron job every minute and the other triggered by an app action. After publishing the app both automations worked as expected when triggered.

I then switched to a single-image installation running 2.5.9 and created another app with the same automations. In that case also, all worked as expected.

I updated the single image version and ran a new container on the same volume. The automations in the app that I created in 2.5.9 also worked when upgraded to 2.6.21.

**Comment by FlaminWrap** [comment]
It was the Create Deceleration automation that wasn't working. There are other automations in other apps that also didn't run

**Comment by FlaminWrap** [comment]
Just an update, I think I might have found the issue. There were two automations in an app that both ran at the same time and updated the same record. Will play around with things tonight and let you know.

**Comment by andz-bb** [comment]
FlaminWrap response:

| Just an update, I think I might have found the issue. There were two automations in an app that both ran at the same time and updated the same record. Will play around with things tonight and let you know. |

![@FlaminWrap](https://avatars.githubusercontent.com/u/97764630?s=80&u=ddc799c07e26834388028ed82d241bb53caa6c41&v=4)

| After clearing out most automations and republishing the apps everything seems to work as expected now. |
