### ISSUE TITLE
[BUDI-7036] Timeout error when calling Chat GPT API

### ISSUE THREAD

**Issue by cnrodrig** [Budibase/budibase#10660]
- [ x] I have searched budibase discussions and github issues to check if my issue already exists

- Cloud
  - Tenant ID: unoafp

**Describe the bug**
We are trying to integrate chat gpt with Budibase using chatgpt api.
When we use short prompts it works but for larger prompts sometimes we get a timeout (10000 ms)
EDIT: We have checked and sometimes with short prompts (that in Postman the response time is almost 0) we got the same error.

![WhatsApp Image 2023-05-20 at 12 50 16](https://github.com/Budibase/budibase/assets/6564749/396063d5-749d-41cf-a1de-19d34d768134)

I understand that there is a QUERY_THREAD_TIMEOUT variable on self hosted deployments, but we don't know what to do in the cloud

**To Reproduce**
1. Go to Data -> GPT-API source --> Test Prompt con texto completo Endpint
2. Click on Send
3. "Sometimes" we get the error (depends on the response time)

 - OS: Windows 11
 - Browser Chrome 
 - Version 113.0.5672.127

<sub>[BUDI-7036](https://linear.app/budibase/issue/BUDI-7036/timeout-error-when-calling-chat-gpt-api)</sub>

**Comment by mike12345567** [comment]
Hi @cnrodrig - our Cloud platform has a max timeout of 10 seconds in the Cloud - this is not configurable. If you wish to have a longer timeout then self hosting can be utilised, with the `QUERY_THREAD_TIMEOUT` environment variable set.
