### ISSUE TITLE
[BUDI-7056] Data Table with column field type number when value  set to 0 shows nothing 

### ISSUE THREAD

**Issue by jaysoni-ash42** [Budibase/budibase#10673]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.6.20
  - App Version: 2.6.20

**Describe the bug**
In Data table when we add column with type number and then add the new row when setting the value to nothing shows up

**To Reproduce**
1. Create a  table in budibase  DB (default db) and add a column with type number  and save it 
3. Add a row with value to be 0 and save it 
5. check the value in the filed it shows nothing 

**Expected behavior**
column filed with type number to show the value 0

**Screenshots**

https://github.com/Budibase/budibase/assets/68722497/2028623c-4ffb-430c-a6f0-c07bd10d28dd

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome safari
 - Version latest

**Additional context**
but it shows the value in the formula column where it shows the value of number column field

<sub>[BUDI-7056](https://linear.app/budibase/issue/BUDI-7056/data-table-with-column-field-type-number-when-value-set-to-0-shows)</sub>

**Comment by jaysoni-ash42** [comment]
@melohagan  i am ready to create a pr to resolve this issue.

**Comment by shogunpurple** [comment]
@aptkingston has this one been resolved and just not closed? Just from looking at the PR raised here: [https://github.com/Budibase/budibase/pull/10672](https://github.com/Budibase/budibase/pull/10672)
