### ISSUE TITLE
[BUDI-7105] Builder Option for Read Only Form Fields

### ISSUE THREAD

**Issue by shawnweeks** [Budibase/budibase#10676]
**Describe the feature request**
Add an option in the builder to set form fields to read only by setting the html input tag property `readonly`, this would be similar in nature to the existing `disabled` option and should also be included in the component conditional options. Primary difference is setting read only option would not dim the field but would still prevent normal user modification. This is purely cosmetic but would allow some flexibility to how form fields are presented especially when used in non-traditional ways.

**Screenshots**

<sub>[BUDI-7105](https://linear.app/budibase/issue/BUDI-7105/builder-option-for-read-only-form-fields)</sub>

**Comment by shawnweeks** [comment]
I'm interested in contributing to this if this seems like something appropriate to the project.

**Comment by melohagan** [comment]
Hey @shawnweeks 

This is possible through global styling! https://docs.budibase.com/docs/custom-css#global-styling

Add your embed component with the following content:

```html
<style>
.is-disabled > input:disabled {
  background-color: dimgrey !important;
  color: linen !important;
  opacity: 1 !important;
}
</style>
```

![Screenshot 2023-06-08 at 17 07 35](https://github.com/Budibase/budibase/assets/101575380/2cfae08c-a202-48a8-9ea1-7bbd043c1359)

You can change the style in anyway you like!

**Comment by shawnweeks** [comment]
@melohagan Wouldn't this apply to all disabled form inputs? I'm wanting to set the `readonly` property on the actual input component. CSS doesn't exactly support canceling out an existing setting.

**Comment by melohagan** [comment]
Hey @shawnweeks 

Thanks for the docs link. I gave the readonly setting a go and I wasn't able to notice much of a difference, for example I could copy and paste the content from both a disabled and readonly field - at least on Google Chrome, MacOS.

One difference was the focus, I was able to tab through read-only fields but not disabled fields.

I think @aptkingston would have a better opinion on this, and it may be worth adding.

**Comment by shawnweeks** [comment]
I've spent some time messing with the global styles but I've never gotten it to make a disabled field look like a non disabled one. The behavior for selecting the contents of disabled fields seems to behave different in firefox.
[Fields Example-export-1686312355097.tar.gz](https://github.com/Budibase/budibase/files/11706092/Fields.Example-export-1686312355097.tar.gz)

**Comment by aptkingston** [comment]
Yea this is a totally valid feature request. The components themselves already support a `readonly` flag (well at least some of them do) so we'd just need to expose this as a setting.

To me the biggest difference is that `readonly` only makes sense for certain fields (like text inputs), but not others like a select. So I would probably not expose this as a top level form setting, but just expose it on whatever fields it makes sense to do so.

**Comment by shawnweeks** [comment]
@aptkingston That sounds good, what I've been playing with is read only record views or some sort of crud form inside of a repeater where only certain fields can be changed. If it was implemented like the other options you could also use conditionals to mark certain fields read only based on other fields. If the underlying form component already supports a readonly option I'd like to have it exposed.
