### ISSUE TITLE
[BUDI-7212] Unable to drag and drop component into new Side Panel

### ISSUE THREAD

**Issue by spmvoss** [Budibase/budibase#10679]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.6.16

**Describe the bug**
After adding a new side panel, I am unable to drag and drop any components into it. 

**To Reproduce**
1. Create a new screen
2. Add a side panel component
3. Click 'Add component' and try to drag and drop it into the new side panel

**Workaround**
1. Select the side panel in the Components tree on the left
2. Click 'Add component'
3. Click on the component you want to add (not drag and drop)
4. It will be added to the side panel
5. You can now drag and drop new components into the side panel

**Expected behavior**
Component added to side panel when dropped into Side Panel frame

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox & Chrome

**Extra information**
I even created a fresh cloud instance with a new app and observed the same behaviour. I found the same behaviour.

<sub>[BUDI-7212](https://linear.app/budibase/issue/BUDI-7212/unable-to-drag-and-drop-component-into-new-side-panel)</sub>

**Comment by timneill** [comment]
@spmvoss are you using a REST API data source by any chance? I've seen/noticed that very very few components are supporting the REST API source and instead of notifying the user that it's invalid, it just ignores the drag-and-drop. So the interface is quite tricky to get working.

If you're using a DB datasource, then I have no ideas...

**Comment by aptkingston** [comment]
> @spmvoss are you using a REST API data source by any chance? I've seen/noticed that very very few components are supporting the REST API source and instead of notifying the user that it's invalid, it just ignores the drag-and-drop. So the interface is quite tricky to get working.
> 
> If you're using a DB datasource, then I have no ideas...
> 
> Edit: To try experiment with this, i created a new blank screen, added a Form block by itself, and then checked the "data source" dropdown. I only have my sample DB data there - the REST API queries are not valid options.

Hey @timneill. The form block very clearly states, right at the top, that it's only compatible with internal or SQL tables:

![image](https://github.com/Budibase/budibase/assets/9075550/2402ef8b-5da4-4e02-b6bd-60657a04c5c3)

REST APIs are much more unique and dynamic in their implementation and design than something like a SQL table (which we have much more control over) so we can't automatically do things like create or update records for you, that we can do with other data sources.

If you use a normal form component, and build it out yourself with whatever fields you want to pass to your REST API call, then you can add a button and link it up to trigger one of your REST API endpoints. There's no issue using a REST API with forms or pretty much any other component, just sometimes you'll have to do a bit more work manually.

**Comment by aptkingston** [comment]
@spmvoss thanks for raising this issue! In the meantime, you can drag and drop components inside the component list on the left side - that will let you put things inside a side panel without any issue.

![image](https://github.com/Budibase/budibase/assets/9075550/b68c2ca4-94ba-484f-9b10-29b729ee2838)

**Comment by timneill** [comment]
@aptkingston not complaining at all! thanks for the feedback, and ill resume fiddling with the REST API implementation 👍

**Comment by spmvoss** [comment]
Just to add, I was not using any REST API data sources, using the built-in data source and a postgresql one. When I created a fresh instance on the cloud, I only had the built-in default data source with no other data than users in it.

**Comment by mike12345567** [comment]
At the moment this would be quite challenging to implement - going to close for now.
