### ISSUE TITLE
[BUDI-7213] Relationships wrong after docker update. (“Cannot read property 'primary' of undefined”, and “Empty update()“ errors)

### ISSUE THREAD

**Issue by pierreboudes** [Budibase/budibase#10688]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: <version> 2.6.20

**Describe the bug**
After updating to "latest" docker container of the docker compose installation, the app I was designing is failing to insert or update rows of a Postgresql table (lets say organisation) in a many to one relation with another table (lets say person).  I am not able to reproduce the bug in a newly created app but I can recreate another one #10387 which may be related, and expose a situation where the relationship is no longer represented inside Postgresql by a foreign key mecanism, see below.

After the update I also noticed that I wasn't able to us a [Table.person.id](http://Table.person.id) in a filter and I had to replace it with a Table.person.\_id (not an integer, but an url encoded array of one integer). At the moment the problem seems more general.

**To Reproduce**
I have a hard time with my main app at the moment, I can surely provide it.  However I can reproduce #10387 easily :

1. Start with the lastest [docker compose](https://docs.budibase.com/docs/docker-compose) create a new app from scratch
2. Use budibase to add a table `organisation (id, name)` and a table `person (id, name)` in an external Postgresql database
3. Use budibase to create a relationship “one organisation to many persons”
4. Note that even if **the relationship appears in budibase, there is none at the Postgresql level** (no foreign key) in the tables.
5. Create a “List view” screen for organisation
6. Try to insert or update an organisation with at least one person, and get the error message (`Empty update()`)

**Expected behavior**
I expect the insertion or update to succeed so the next actions are fired. I also expect to be able to inspect and populate relationships directly in Postgresql as it was the case before.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/6ff6cc6d-04bc-4dad-840a-bc65ace6d0dd/9e26418b-97ff-4f95-8eed-ba574d761d8d)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/6025c2ed-f810-4139-9781-760e0115923c/0357cc6f-5474-467d-b07d-42d854326c61)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/68520d37-1b1a-472d-874b-9a97c078b260/b7ed7590-6fc8-4a91-8145-700303d436e4)

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

[Debug-export-1684942467895.tar.gz](https://github.com/Budibase/budibase/files/11556429/Debug-export-1684942467895.tar.gz)

**Desktop (please complete the following information):**

* OS: Linux Debian
* Browser Firefox ESR
* Version 102.11.0

**Additional context**
I can provide my main app archive via a private communication.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7213](https://linear.app/budibase/issue/BUDI-7213/relationships-wrong-after-docker-update-cannot-read-property-primary)</sub>

**Comment by HVStechnik** [comment]
Can confirm this bug. In my case all new one-to-many relationships produce this error. It seems that budibase treats them as a many-to-many relationship and tries to write a foreign key into the FROM / ONE table.

**Comment by sklaffa** [comment]
I have similar issues with MariaDB. See discussion #10935. It looks like the issue is not related to a specific database backend.
