### ISSUE TITLE
[BUDI-7117] Issues with Onchange update record events

### ISSUE THREAD

**Issue by adamkingsbury** [Budibase/budibase#10693]
**Checklist**

* \[x \] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: <method> docker compose
  * Budibase Version: <version> tested in 2.5.5 (works as expected), 2.6.22 (issues occur)
* Cloud
  * Tenant ID: <tenantId> logikloud.budibase.app

**Describe the bug**
I have designed a number of screens to simulate a basic editable data grid or table utilising a pattern of
dataprovider -> repeater -> form -> text, date and other fields

each field is set up with an onchange event to save the record

In prior versions (v2.5.5 tested) this worked as expected. When a user moved away from an edited cell, the record would save the update and display the updated values. It appears some time soon after version 2.5.5 this no longer works depending on the way a user moves from an edited cell, the save update process may now be triggered either once or twice, and may result in a failed save (without error)

**To Reproduce**

1. Create a new blank app with sample data.
2. Create a new screen with the following layout:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/cc6bc40e-fdc6-48c5-b7ac-c652172a0772/a359b5a3-92eb-439a-8eac-04dce9eff757)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/eab43005-4a18-41b0-ab48-e52747ce63df/170e9193-caf1-4131-8f2d-e057d47ec043)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/bb5c6fc7-6e33-4341-aaee-29eb90db60b6/8c4de5f0-dc62-409a-b88b-8c90292cdb80)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/23aef88f-6928-4277-a513-4034540ebc89/ca46de9e-bf4d-4539-94d6-1ba79e9251d8)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5f2e0bc9-ebd3-4747-8322-49373d7c23c6/1931d3be-f121-4201-80c0-5c17a36d1ac7)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/90ebd516-7e21-4f70-bac0-ce7bde5c4b41/3cd67549-b2ab-4e5b-ac44-d232770bcb30)

All of the fields have the same action set:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/9b5bc3f1-f371-4d89-b45f-29cb8f5c7f05/1a04ddac-b33a-44e1-ac5b-da7c7d7979c3)

1. The following tests can be performed to identify the varying behaviour of the on change event:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/20f3de56-4191-4bc7-8e9e-3eaf3d5eec68/5d52850a-bacb-4594-8aeb-2aa5129e85dc)

**Expected behavior**
In all cases when a users has modified a value in a field, then moves away, either by clicking another field, clicking outside, or by tabbing to the next field, the on change event should be triggered only once and should result in the record being saved successfully.

**App Export**
Can provide an export of my test app if required....

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f03fe717-47e1-4e1b-a028-50844708384d/e42e91d5-13b1-4981-8104-991a9553a83c)

**Desktop (please complete the following information):**

* OS: Windows
* Browser Microsoft Edge
* Version 113.0.1774.50 (Official build) (64-bit)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7117](https://linear.app/budibase/issue/BUDI-7117/issues-with-onchange-update-record-events)</sub>

**Comment by adamkingsbury** [comment]
Hi I can see that there hasn't been a lot of movement on this in the last couple of weeks. Is there anything else I can do/provide to support this issue?

**Comment by melohagan** [comment]
Hey @adamkingsbury Thank you very much for the detailed bug report. I was able to reproduce the issue.

It may be worth simply having a save button for your form in the meantime,

What may be occurring in this instance is that because you are performing a **Save Row** action within the **On Change**, it may be refreshing the Data provider, which in turn is then triggering another on change.

It could be something to do with the timing of actions, but I'm not sure.
