### ISSUE TITLE
[BUDI-7214] MySQL filter by BigInt field

### ISSUE THREAD

**Issue by andr-04** [Budibase/budibase#10703]
**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 2.5.6

**Describe the bug**
After solving #8781 the bug with filtering data remains.

**To Reproduce**
1. Create MySQL database.
2. Create 2 tables for the MySQL database: first one with BigInt as primary key and the second one with BigInt as a foreign key to the first table, and some data fields.
3. Create some records with BigInt primary key, like `12345678901234567890`, and records on the second table with the same foreign key.
5. Create Budibase application.
6. Attach MySQL database as a datasource to the Budibase application.
7. Create 2 screens with routes `/` and `/:id`. Each screen has a Table component connected to the appropriate MySQL table.
8. Add row click action for the first screen Navigate to second screen `route /{{ Clicked row.[id] }}`.
9. Add filter for the datasource on second screen foreign_key equals binding `{{ URL.id }}`.
10. Run the application, click the row on first screen and see nothing records on second screen.

**Expected behavior**
The table on the second screen should not be empty.

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 112.0.5615.137 (Official Build) (arm64)

**Additional context**
On preview I caught search URL https://***/api/datasource_plus_4ec8a16d53924ecca5cc000da8812859__second/search with the following payload:
```
{
  "query": {
    "string": {},
    "fuzzy": {},
    "range": {},
    "equal": {
      "1:foreign_id": 12345678901234567890
    },
    "notEqual": {},
    "empty": {},
    "notEmpty": {},
    "contains": {},
    "notContains": {},
    "oneOf": {},
    "containsAny": {},
    "allOr": true
  },
  "bookmark": null,
  "limit": 10,
  "sort": "foreign_id",
  "sortOrder": "descending",
  "sortType": "number",
  "paginate": false
}
```

Here's `1:foreign_id` has not string, but **integer** value which is too big. When I replaced it to string and gather it through cURL, it became work!

<sub>[BUDI-7214](https://linear.app/budibase/issue/BUDI-7214/mysql-filter-by-bigint-field)</sub>

**Comment by andr-04** [comment]
@melohagan, just a hypothesis, probably here the wrong condition, but I don't know how to fix it for sure: https://github.com/Budibase/budibase/blob/30c966dde54d532d6204f31fc3fd23e349188ade/packages/backend-core/src/db/lucene.ts#L253

**Comment by melohagan** [comment]
Closing as this scenario appears to be working fine. Tested on **2.8.9** with the new *BigInt* field type:

![working](https://github.com/Budibase/budibase/assets/101575380/f43f2a29-166c-4509-a9b4-3ae6f92fdaf0)
