### ISSUE TITLE
No connection to database when port added

### ISSUE THREAD

**Issue by sysoppl** [Budibase/budibase#1072]
**Describe the bug**
When I enter IP:PORT into database it never works. DB is working with other services, so it's not db problem.

**To Reproduce**
1. Go to data sources
2. Add new database
3. Try to query

**Expected behavior**
It should connect to DB. 

**Screenshots**
![obraz](https://user-images.githubusercontent.com/30871217/106657174-fdf59b00-659b-11eb-802b-f83b9c95e1bb.png)
![obraz](https://user-images.githubusercontent.com/30871217/106657222-106fd480-659c-11eb-9fc8-da3b058981c0.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [firefox,]
 - Version [85]

**Comment by shogunpurple** [comment]
Should be resolved in latest release.
