### ISSUE TITLE
[BUDI-7215] Automation QUERY ROWS does not fetch latest data from internal tabel

### ISSUE THREAD

**Issue by lisa-neoom** [Budibase/budibase#10733]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Budibase Version: <2.3.16> 
  - App Version: <version> <2.3.16>

**Describe the bug**
Within an automation, during the `QUERY ROWS` step, 
where an internal budibase table is called with the following parameters:
  Table: <table_name>
  Filtering: no filters
  Sort Column: `Created At`
  Sort Order: `Descending`
  Limit: `336`
  When Filter Empty: `Return no rows`
the latest rows from the table are not fetched, but some older ones, assumingly form the last time the app was published.

During TEST AUTOMATION, everything works fine an the latest row(s) from the internal table are fetched and used for all further steps (JS SCRIPTING etc)

JS SCRIPT
`// Access rows from the second step
const rows = steps[1].rows;

// Extract date of last entry
const createdAt = rows.map(row => row.createdAt);

// Initialize an empty array to hold output messages
const output = [];

// Send slack message with latest timestamp
output.push(`[TEST2 - ENERGY_FLOWS] Using Auto ID as sort criterium. Latest timestamp checked: ${createdAt[0]} `);

// Check if there are any messages in the output array
if (output.length > 0) {
  // Join the messages with newline characters and return the resulting string
  return output.join("\n\n");
} else {
  // If there are no messages, return "null"
  return "null";
}`

However when the cron job is running in production, the same old data is fetched and used for all further steps over and over again. So if the last TEST and APP PUBLICATION was run on 15 May for example, the automation would continue to query rows only until that date, although newer rows for any day after 15 May already exist.

**To Reproduce**
1. Go to 'Add Automation' and update CRON TRIGGER to 15 * * * *
2. Click on '+' to Add QUERY ROWS.
3. Add parameters (see above)
4. Click on '+' to add JS SCRIPTING and write script (see above)
5. Click on '+' to add SLACK MESSAGE and add webhook URL, as well as message `{{ steps.2.value }}`
6. Publish App

**Expected behavior**
I expect a Slack Notification that returns the latest Created At date from my internal budibase table. 

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

<sub>[BUDI-7215](https://linear.app/budibase/issue/BUDI-7215/automation-query-rows-does-not-fetch-latest-data-from-internal-tabel)</sub>

**Comment by ConorWebb96** [comment]
Hey @lisa-neoom,

I ran through your reproduction and everything seems to work fine. I did however have to fix your JS code as there were stray Grave symbols throughout as well and some missing grave symbols where needed as well. Below is the fixed code;

```
const rows = steps[1].rows;
const createdAt = rows.map(row => row.createdAt);
const output = [];
output.push(`[TEST2 - ENERGY_FLOWS] Using Auto ID as sort criterium. Latest timestamp checked: ${createdAt[0]}`);

if (output.length > 0) {
   return output.join("\n\n");
} else {
   return "null";
}
```

I've attached some screenshots of the automation, I changed it to run every minute for testing purposes and it seemed to pull the correct createdAt time.
<img width="400" alt="Screenshot 2023-07-11 at 15 15 21" src="https://github.com/Budibase/budibase/assets/126772285/c2e07e50-e2f1-4bd5-96b0-c9e2c3947a57">
<img width="393" alt="Screenshot 2023-07-11 at 15 15 28" src="https://github.com/Budibase/budibase/assets/126772285/72a96f32-6b44-4819-92d4-91999f362f9a">

Below are results which were sent to slack.
<img width="855" alt="Screenshot 2023-07-11 at 15 09 50" src="https://github.com/Budibase/budibase/assets/126772285/999d6ea5-b7cd-47be-9aec-d77155b0cc70">

I did make a few records in between each automation run to see if it would still get the newly created record's createdAt.

**Comment by lisa-neoom** [comment]
Dear Conor,
Thanks for checking and for updating the JS code.

I have meanwhile found the error that caused my data in the budibase tables to not show up in graphs and  and other automations built on these budibase tables.
I fixed the problem and confirmed the fix during our latest release.

The API call, that was fetching data from our internal database,  was writing data to the budibase _dev_ table instead of the table in production.
As a result all the automation tests looked fine, however the data was never available in production until the app was PUBLISHED again and therefore newest data did not show in graphs or was fetched by other automations calling the budibase (production) table.

Best regards,
Lisa
________________________________
Von: Conor Webb ***@***.***>
Gesendet: Dienstag, 11. Juli 2023 16:28
An: Budibase/budibase ***@***.***>
Cc: Lisa Lang ***@***.***>; Mention ***@***.***>
Betreff: Re: [Budibase/budibase] [BUDI-7215] Automation QUERY ROWS does not fetch latest data from internal tabel (Issue #10733)


Hey @lisa-neoom<https://github.com/lisa-neoom>,

I ran through your reproduction and everything seems to work fine. I did however have to fix your JS code as there were stray Grave symbols throughout as well and some missing grave symbols where needed as well. Below is the fixed code;

const rows = steps[1].rows;
const createdAt = rows.map(row => row.createdAt);
const output = [];
output.push(`[TEST2 - ENERGY_FLOWS] Using Auto ID as sort criterium. Latest timestamp checked: ${createdAt[0]}`);

if (output.length > 0) {
   return output.join("\n\n");
} else {
   return "null";
}


I've attached some screenshots of the automation, I changed it to run every minute for testing purposes and it seemed to pull the correct createdAt time.
[Screenshot 2023-07-11 at 15 15 21]<https://user-images.githubusercontent.com/126772285/252692662-c2e07e50-e2f1-4bd5-96b0-c9e2c3947a57.png>
[Screenshot 2023-07-11 at 15 15 28]<https://user-images.githubusercontent.com/126772285/252692668-72a96f32-6b44-4819-92d4-91999f362f9a.png>

Below are results which were sent to slack.
[Screenshot 2023-07-11 at 15 09 50]<https://user-images.githubusercontent.com/126772285/252692766-999d6ea5-b7cd-47be-9aec-d77155b0cc70.png>

I did make a few records in between each automation run to see if it would still get the newly created record's createdAt.
