### ISSUE TITLE
Default value can't be reset to none

### ISSUE THREAD

**Issue by diogenesbrussels** [Budibase/budibase#10760]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.5.9
  - App Version: 2.5.9

**Describe the bug**
There is no way to distinguish between a default value equivalent to "" and a non-existent value (no default value).

**To Reproduce**
1. Create an option column in a MySQL table, add a few options, not required
2. Create a form with this field as options (select or radio buttons) with db schema
3. Don't touch the default value of this field, the form is valid.
4. Now set a default value to the field. The form is valid if the value is in the list.
5. Now empty the default value field. The form isn't valid as the default value "" isn't in the list.

**Expected behavior**
There should be a way to distinguish between an undefined default value and a "" value. There should also be a button to delete this value if necessary.

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Firefox
 - Version 113

**Comment by melohagan** [comment]
Hey @diogenesbrussels 

Could you please upgrade to the latest version (**2.6.20**). If the problem persists I'll look into it.

**Comment by melohagan** [comment]
Great thanks @diogenesbrussels - we are also doing a release today, so ideally could you update when that rolls out. It'll be version **2.7**
