### ISSUE TITLE
[BUDI-7078] Side Panel UX issue: releasing a click off-panel closes the panel

### ISSUE THREAD

**Issue by agmcnabb** [Budibase/budibase#10762]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Docker
  - Budibase Version: 2.5.2
  - App Version: 2.5.2

**Describe the bug**
A couple of users have noticed an irritating behaviour with the side panel: when clicking and dragging to highlight text in a text field, if the mouse is hovering off the side panel when the click is released, the app closes the side panel - recording attached.

**To Reproduce**
1. Have a side panel with text field.
2. Click and drag to highlight the text in the text field.
3. Release the click while the mouse is not hovering over the side panel.
4. The click release is interpreted as a click, and the side panel closes.

**Expected behavior**
Releasing a click that started on the side panel should not close the panel.

**Screenshots**

https://github.com/Budibase/budibase/assets/125557661/a4e72b4b-035c-4e74-b45b-00fce7f9c0f6

  
**App Export**

[test app-export-1685626054269.tar.gz](https://github.com/Budibase/budibase/files/11625803/test.app-export-1685626054269.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge

<sub>[BUDI-7078](https://linear.app/budibase/issue/BUDI-7078/side-panel-ux-issue-releasing-a-click-off-panel-closes-the-panel)</sub>

**Comment by melohagan** [comment]
To add to this one, if you close an error toast it also closes the side panel which is a little frustrating:


https://github.com/Budibase/budibase/assets/101575380/ed858d17-eb74-4185-9df3-835978b2916e

**Comment by bjornclauw** [comment]
would it be possible to add an option under the sidebar so the sidebar can only be closed with the dedicated button? (=clicking outside of the sidebar does nothing)
