### ISSUE TITLE
[BUDI-7089] OIDC Custom Icons don't appear when added.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#10812]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.6.20
  * App Version: 2.6.20

**Describe the bug**
Custom OIDC icons don't appear whenever added returns a blank/missing image. Previous issue fixed the default icons here; [https://github.com/Budibase/budibase/pull/9826](https://github.com/Budibase/budibase/pull/9826)

**To Reproduce**

1. Go to settings
2. Click on auth
3. Scroll down to OpenID Connect
4. Fill in all relevant information
5. Upload a custom icon 
6. See issue

**Expected behavior**
Uploaded icon should be displayed after upload.

**Screenshots**

![242895318-124532c3-faac-4978-8130-4e79ea8c9cd3.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/955f14d1-3acd-4bf3-a91d-8998705e7e41/c7b816a0-c8ee-4cd1-9354-8285f59ce42d)

**Desktop (please complete the following information):**

* OS: IOS
* Browser Brave
* Version **v1.52.122**

**Additional context**
Related discussion; [https://github.com/Budibase/budibase/discussions/10771](https://github.com/Budibase/budibase/discussions/10771)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7089](https://linear.app/budibase/issue/BUDI-7089/oidc-custom-icons-dont-appear-when-added)</sub>

**Comment by gmentzik** [comment]
Confirming this issue. I have opened discussion for it here: https://github.com/Budibase/budibase/discussions/10771
I think this was working fine before version 2.

**Comment by koneubauer** [comment]
Can replicate this issue in 2.13.20
