### ISSUE TITLE
loop problem in sending email automation 

### ISSUE THREAD

**Issue by JEQ7** [Budibase/budibase#10820]
Hello everyone!
need some help heroes!

I'm currently facing a problem related to automation

I have two emails I want to send through the automation

and for each one, I use a loop

the first loop run fine and send the email 

but the second failed 

I tried to add another email with the third loop but it face the same issue 

I think automation doesn't handle more than one loop in single automation!

Correct me if I'm wrong or miss something, kind regards!

**Comment by melohagan** [comment]
Hi @JEQ7 

Please follow the bug template - screenshots, reproduction steps, environment, version, etc.
