### ISSUE TITLE
[BUDI-7100] Changing the Table Block Data Source to Relationship Removes the Underlying Click Events

### ISSUE THREAD

**Issue by MarleTangible** [Budibase/budibase#10833]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: v2.7.7 but also repeatable on v2.6.11 (v2.6.20+ not published on Docker Hub.)
  - App Version: v2.7.7

**Describe the bug**
When the data source of a Table Block is updated as a relationship, events such as on row click and button click are removed from the underlying table component. After which clicking on the add row button and selecting a row doesn't do anything. Changing the data source back to a table, restores the events. However, if the table block is ejected while its data source is still a table, and then the underlying data provider's source is updated to a relationship, then everything works as expected.

I don't know if this is the expected behavior but seemed like a bug to me and I wasn't able to locate any reference to this in the documentation. 

As an alternative, I tried filtering the `_id` column with `Current User` relation column but that resulted no items to be shown.

**To Reproduce**
1. Create a brand new app with Budibase DB.
2. Create a new table and add some columns. Also add a relationship column to the users table. (one user to many rows).
3. On the design tab, add a new screen with the list view.
4. Preview the app and add some sample rows. Everything works as expected, and clicking on rows shows the details pane as well.
5. Switch back to design view and change the data source to a relationship. e.g. updated by current user etc.
6. Preview the app again. Create row button and clicking on rows fails to open the side panel.
7. Restore the table block data source to the original table. Click events work again.
8. Eject the table block while its data source is still connected to a table. And then change the data provider source to a relationship and preview the app. Everything works as expected with rows being limited to current user.
9. Repeating the above step while the table block is configured for a relationship source shows that the underlying table and button components are missing their on click events.

**Expected behavior**
Either a documentation update stating that this is the expected behavior or users being able to see rows related to them and being able to click on a row to open the side panel to make updates and use the create row button to add records.

**Screenshots**
N/A
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Chrome
 - Version: 114

**Additional context**
The main goal of this app is to create something akin to a ticket management solution where users can view tickets assigned to them and provide status updates. I initially tried filtering the table block with `_id` is in current user's relationship column but it yielded a table with no rows.

<sub>[BUDI-7100](https://linear.app/budibase/issue/BUDI-7100/changing-the-table-block-data-source-to-relationship-removes-the)</sub>

**Comment by shogunpurple** [comment]
The problem here is that you have switched the data source for your block to a source other than the internal table or SQL - this will cause some problems with the automatic side panel functionality. We mention this in the help text present in the settings panel on the right.

**Comment by MarleTangible** [comment]
@shogunpurple Thank you for the clarification. My assumption was that as long as I select a relationship that is directly tied to the internal database then it would work.
