### ISSUE TITLE
Failed to run yarn build:docker:single

### ISSUE THREAD

**Issue by phankhanhhung** [Budibase/budibase#10840]
**Hosting**

- Self
  - Method:  docker single image
  - Budibase Version: 2.7.9
  - App Version: 2.7.9

**Describe the bug**
The error log displays: error Couldn't find any versions for "@budibase/backend-core" that matches "0.0.0"

**To Reproduce**
As exactly README in the single folder

**Additional context**
Compile on Debian arm64, Paralells Mac OS M1
Compile on Mac OS M1 native

**Comment by mike12345567** [comment]
Hi @phankhanhhung - we've updated our docker build sequence, in time we will try to make this more cohesive - but for now the sequence to build the single image is:
```
yarn build
./scripts/updateVersions.sh
yarn docker:build:single:image
./scripts/resetVersions.sh
```

Versions have been removed as part of a general update to our infrastructure, but going forward we will be removing the need for versioning of mono-repo packages altogether - going to close this issue as we have internal issues to track our progress towards this.

**Comment by phankhanhhung** [comment]
Thanks, and please share me the sequence for building multiple images like provided docker-compose installation method.

**Comment by mike12345567** [comment]
Hi @phankhanhhung - that should be a similar process, but using the `build:docker` command instead of `yarn docker:build:single:image` - although you may need to remove the end of this as it will attempt to release to docker hub and unless you're logged in this will fail.
