### ISSUE TITLE
[BUDI-7107] The Cancel and Save butttons at the top of the new formula dialog do not work when editing a formula column.

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#10849]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
  - Method: Docker compose
  - Budibase Version: 2.7.9
  - App Version: 2.7.9

**Describe the bug**
The Cancel and Save butttons at the top of the new formula dialog do not work when editing a formula column.

**To Reproduce**
1. Edit a formula column
2. Click the lightning icon at the side of the formula field.
3. Press Cancel or Save at the top bar
4. Nothing happens and the error appears in the browser console

**Expected behavior**
For an action to happen

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/97764630/87d5f2e1-bf40-43b0-9d80-386918d2169b)
![image](https://github.com/Budibase/budibase/assets/97764630/81c624bc-28a9-4bd7-890c-dc253221cbd7)
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser MS Edge
 - Version 114.0.1823.41

**Additional context**
The cancel and confirm buttons at the bottom work, so this isn't a huge priority. 

<sub>[BUDI-7107](https://linear.app/budibase/issue/BUDI-7107/the-cancel-and-save-butttons-at-the-top-of-the-new-formula-dialog-do)</sub>

**Comment by melohagan** [comment]
Will be fixed as part of this PR: https://github.com/Budibase/budibase/pull/10805
