### ISSUE TITLE
REST Data source double-request bug

### ISSUE THREAD

**Issue by zigenis** [Budibase/budibase#10856]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker Compose 
  - Budibase Version: 2.5.6 
  - App Version: 2.5.6 

**Describe the bug**
When querying a REST endpoint using the REST data source, it appears that requests from Budibase get sent twice if the endpoint returns a non-200 status code.

**To Reproduce**
1. Set up a web server of some sort. In my case, I'm using Node-Red to make a few API endpoints.
2. Ensure that you have a route that returns a 200 status code.
3. Configure a REST query in Budibase and remain on the query creation page so that you can see the 'Test' button at the top right.
4. Monitor server logs for the API endpoint web server from step 1, then click on the test button from step 3 to initiate a request to the server.
5. The server logs should show just one request at this point (given that it responded with a 200 status code to Budibase).
6. Modify the web server from step 1 to return an error status code of some sort (403, 503, etc.)
7. Click the test button (from step 3) in Budibase again, and review the API server logs. At this point, you should see that Budibase re-sent the initial request after having received the error status code from the first response.

If you add a significant delay between request and response on the API server end, the behavior becomes very apparent. The initial request will hit the endpoint, then as soon as the API server responds with an error code, Budibase will request again.

**NOTE: This behavior is not exclusive to the test button, the issue exists wherever the query is triggered from. I can reproduce it from a button action on an app page as well.**

**Expected behavior**
I would expect that Budibase would only send one request per query, regardless of status code on the response. Sending double the requests, especially when an error is returned, seems like a bad practice to me.

**Screenshots**
In the screenshot below, you can see two requests come in to the server from just one click of the test button. I added a 2 second delay between request and response on the API server, which is shown in the request timestamp:
![err](https://github.com/Budibase/budibase/assets/132610996/35be319a-c4af-48a4-a85e-3aaffb51ce32)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 114.0.5735.110 (Official Build) (64-bit)

**Additional context**
I looked through budibase/packages/server/src/integrations/rest.ts and found that fetch() is only called once and there doesn't seem to be any logic checking for non-200 status codes, so I'm at a loss. I'm not too familiar with the structure of Budibase, so I may just be in the completely wrong place to look.

**Comment by mslourens** [comment]
This is the intended behavior. If you look at the file `packages/server/src/threads/query.ts` on [line 125](https://github.com/Budibase/budibase/blob/a3fc5e46c82f338f77d485c6c7cc09e2ad255a0c/packages/server/src/threads/query.ts#L125), you'll see that the request will be retried once on failure.

**Comment by mslourens** [comment]
I don't know the rationale behind it, the only thing I can find in Github is this commit message: "Adding query invalidation, when a query fails that has dynamic variables it will invalidate the cache value for all dynamic variable values.". Maybe @mike12345567 can tell you why this has been implemented, because he is the author of this piece of code.

**Comment by mike12345567** [comment]
Hi @mslourens and @zigenis - the idea behind this is that the dynamic variables are really designed for fetching authentication tokens - the extra request is incase a token has expired for example and we need to re-fetch the authentication token to continue requesting. Originally this was only on a 403 response, but we had to expand it due to some of the usages that were discovered after it went out into the wild!

**Comment by zigenis** [comment]
@mike12345567 Ahhh, that makes a lot more sense. Thanks for the clarification. It doesn't seem to be a real consequential issue, I just thought it was odd and I couldn't find any documentation on why it behaved this way. Hopefully this thread can serve as that documentation to anyone who comes across it in the future. Thank you!
