### ISSUE TITLE
Clicking Bind on Data Provider Filter Deletes Filter

### ISSUE THREAD

**Issue by shawnweeks** [Budibase/budibase#10851]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.7.11
  - App Version: 2.7.11

**Describe the bug**
Clicking the bind lightning bolt in a data provider filter sometimes deletes the filter instead of opening the bind dialog box. 2.6.20 did not do this.

**To Reproduce**
1. Add a data provider and table component to a page.
2. Try and add an is in bind filter.
3. Sometimes clicking the bind button makes the filter disappear.

**Expected behavior**
Clicking the bind button in a filter shouldn't delete the filter.

**Screenshots**
<img width="1285" alt="Screenshot 2023-06-09 at 9 49 38 AM" src="https://github.com/Budibase/budibase/assets/9768773/c4a6b7e8-46bd-42c5-8589-5599629c827f">
  
<img width="1336" alt="Screenshot 2023-06-09 at 9 51 58 AM" src="https://github.com/Budibase/budibase/assets/9768773/d1dc7b29-7c0f-4f22-b0cd-0f78c447a9cb">

<img width="1277" alt="Screenshot 2023-06-09 at 9 52 23 AM" src="https://github.com/Budibase/budibase/assets/9768773/1af058cf-8e37-4f64-af76-43f176ef3bf2">

**App Export**
This app export was created brand new after the upgrade to 2.7.11, it was not upgrade from 2.6.20. All apps on 2.7.11 that I've tested do this.

[Table Filter Bug-export-1686322561105.tar.gz](https://github.com/Budibase/budibase/files/11707492/Table.Filter.Bug-export-1686322561105.tar.gz)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version Latest

**Additional context**
When this happens I don't see any errors in the browser console and it only happens some of the time but it's at least 75% of the time.

**Comment by itopaloglu83** [comment]
Related.
https://github.com/Budibase/budibase/issues/10838

**Comment by shogunpurple** [comment]
Should now be fixed as in https://github.com/Budibase/budibase/issues/10838
