### ISSUE TITLE
column formula fields loose formulas on Save

### ISSUE THREAD

**Issue by lukuser** [Budibase/budibase#10873]
### Discussed in https://github.com/Budibase/budibase/discussions/10857

<div type='discussions-op-text'>

<sup>Originally posted by **lukuser** June  9, 2023</sup>
I notice that recently, when I save a column with a formula, the formulas disappear. I have to hit refresh for them to be accessible again:
![image](https://github.com/Budibase/budibase/assets/81827963/39ae289b-70fa-4bde-9cc5-15471929cc27)
The formula box shows the result of the formula instead of {javascript function} (in this case my formula had an error, so I see the error message). 
On  top of that when I deleted one of the formula-based columns, all the other columns, which are also based on formulas, loose their formulas permanently (they don't return after refresh - I must retrieve them from a backup).

Other issues I noticed. When restoring a formula on one columns, it works. When creating (pasting in from outside) a formula for a second formula-based column, the first column that just worked, now gets cleared, so there's no way to set multiple formula columns. 

The formula fields used to work fine in older versions.
</div>

**Comment by melohagan** [comment]
Hey @lukuser 

Could you please fill out the bug template including reproduction steps, and the actual formula code being used here!
https://github.com/Budibase/budibase/issues/new/choose
