### ISSUE TITLE
[BUDI-7116] Importing custom datasource plugin -  JS invalid: require is not defined

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10878]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.7
  * App Version: 2.7

**Describe the bug**
When attempting to import a custom datasource plugin the following message is displayed: `Failed to add plugin: Failed to import plugin: JS invalid: require is not defined`

First noted in Discord: [https://ptb.discord.com/channels/733030666647765003/1117551989027524698](https://ptb.discord.com/channels/733030666647765003/1117551989027524698)

**Expected behavior**
As a user, I should be able to import a custom datasource plugin without any errors.

### Works fine in v 2.6.11, broken in v2.7.7

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7116](https://linear.app/budibase/issue/BUDI-7116/importing-custom-datasource-plugin-js-invalid-require-is-not-defined)</sub>

**Comment by stevenjwright** [comment]
@melohagan this looks to have been patched. Updated to `V2.7.21` and was able to install without issue 🎉

**Comment by melohagan** [comment]
Thanks for letting me know! @stevenjwright 

I've done a quick test and confirmed it to be fixed.
