### ISSUE TITLE
Unable to fetch date from PostgreSQL

### ISSUE THREAD

**Issue by Mando540** [Budibase/budibase#10871]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: blackscreenrecords

**Describe the bug**
There seems to be an issue with our PostgreSQL connection. The data won't get fetched.

**To Reproduce**
1. Start the Budibase app
2. See error ("Thread timeout exceeded 10000ms timeout.")

**Expected behavior**
The data get fetched. No error warning.

**Screenshots**
![Bildschirmfoto 2023-06-12 um 15 39 17](https://github.com/Budibase/budibase/assets/64315462/5d928e99-d9f0-4de7-b466-fe760ee18fd4)
![Bildschirmfoto 2023-06-12 um 15 39 30](https://github.com/Budibase/budibase/assets/64315462/f58b86a0-22da-4fb5-93ca-8de06903484c)
![Bildschirmfoto 2023-06-12 um 15 44 02](https://github.com/Budibase/budibase/assets/64315462/a797c637-33bc-4d2e-bfdd-ee612194e253)

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome
- Version: 111.0.5563.146

**Additional context**
I did clear my cache and the issue still occurs. I haven't changed anything in the credentials and even if I try to enter the password again an error appears.

**Comment by Mando540** [comment]
My bad. I didn't whitelist the necessary IPs. Now it's working again.

**Comment by Mando540** [comment]
I have to reopen the issue as the error occurs again. For a few days everything worked as before when I whitelisted the additional IPs but now even with those IPs whitelisted I have timeouts. Other apps using the PostgreSQL database are working.

Are there some changes made in the last few days that I missed?

**Comment by jonnymccullagh** [comment]
Yes there is an email going out shortly to explain we had an unplanned maintenance change that resulted in new IP addresses. The updated IP whitelist is on the docs page:
[https://docs.budibase.com/docs/whitelisting](https://docs.budibase.com/docs/whitelisting)
We have reserved IPs to try to minimise this happening again.
