### ISSUE TITLE
[BUDI-7209] Relationship fields (foreign keys) aren't saved when using relational databases

### ISSUE THREAD

**Issue by zedascouves** [Budibase/budibase#10949]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: valis

**Describe the bug**

(I've initially reported the issue in [https://github.com/Budibase/budibase/discussions/10937](https://github.com/Budibase/budibase/discussions/10937), and I believe this one also relates to the same problem: [https://github.com/Budibase/budibase/discussions/10935.)](https://github.com/Budibase/budibase/discussions/10935.))

When a form contains a dropdown picker of type "Relationship", the field value contains unparsed characters. This prevents the row from being saved, as the foreign key is invalid.

**To Reproduce**

1. Create two tables in a MySQL/MariaDB database, with a relationship of 1 to many.
2. Import these tables in Budibase
3. Create 1-N relationship
4. Autogenerate a listing page for the table with the foreign key column, with save/update actions
5. Edit a row, changing the option related to the foreign key.
6. The selected option will **NOT** be saved.

**Expected behavior**
The row should be saved with the updated values.

**Desktop (please complete the following information):**

* OS: Windows 11
* Browser: Firefox
* Version 114.0.1

**Additional context**
I was able to workaround the issue by changing the "Save row" action and cleaning up the form field value.

`{{ toInt (remove (remove (remove (remove (stringify Details Form.Fields.VIPS_Country) '%5B') '%5D') '["') '"]') }}`

So, my action looks like:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/dc71df5f-b8ec-4146-97a9-95d692aa1352/0e0d6455-6ad5-471b-8b32-48fcd66a8a32)

This way I can select my "foreign key" element on the picker, and it'll save the correct ID on the row. Nevertheless, it doesn't fix the underlying problem.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7209](https://linear.app/budibase/issue/BUDI-7209/relationship-fields-foreign-keys-arent-saved-when-using-relational)</sub>

**Comment by sklaffa** [comment]
Hi, I'm the author of report #10935. I would like to highlight that at least the issues I experienced are reproducible also in other database backends. I tried with PostgreSQL and got the very same behaviour, so I suspect the bug is not really backend-dependent.

**Comment by mike12345567** [comment]
Hi @zedascouves - the relationship picker is not designed to be used with a foreign key field. Within Budibase you must [defined your relationships](https://docs.budibase.com/docs/sql-datasource#defining-relationships) and then you can use the relationship picker to set relationships on the relationship column. The foreign key will the automatically be updated in the background based on the rows that were picked.

We could add a helper to HBS/JS which would automatically convert our built in `_id` format, which is what the relationship picker returns (the extra characters are there by design to help Budibase manage composite keys) - a helper like say `getPrimaryKey` could be used then if you do not want to use the built in Budibase relationship management system.

**Comment by mike12345567** [comment]
Hi @zedascouves - when you define your relationship within Budibase you have two options:
1. You can create a new column within Budibase that will setup the foreign key by itself and the constraints as required
2. You can define an existing relationship and specify the foreign key that should be used to manage it

I believe in your case the better option would be the second, if you have an existing foreign key then you should use this when defining an existing relationship in Budibase, as [shown in these docs](https://docs.budibase.com/docs/sql-datasource#defining-relationships). Budibase will not create any new columns etc in your SQL database, there will be a "virtual" relationship column which is used to manage the related rows in the response, but the SQL table will be unaffected by this definition, it is purely to make Budibase aware of this relationship.

One you have this virtual relationship column, you use the relationship picker to update the list of related rows (many side) or the single row (one side) and then internally Budibase will work out the primary of the related row and update the foreign key field. We actually plan to hide the foreign key field as an "auto-generated" field soon once the user has defined it is used in a relationship, as you shouldn't update the foreign key field directly, you should always update the virtual relationship column.

In the future we hope to auto-detect these ourselves, but it is quite difficult to manage auto detection of many to many relationships through junction tables so we haven't found a great solution for this just yet!

**Comment by zedascouves** [comment]
Hi @mike12345567,

Thank you for all the info. The thing is, I am going with option 2, and I believe I've read the correct doc.

For example, with this relationship...
![imagem](https://github.com/Budibase/budibase/assets/594831/b51a4a6f-b1bf-480a-892f-913328dd23ba)

... we have a Client with one or more Projects.

When I create a new project for a client, I get this message:
![imagem](https://github.com/Budibase/budibase/assets/594831/cff3e28a-dc00-4610-ae95-66965bd1c5e8)

This is the foreign key field, that I didn't edit in the form. I only selected an option on the relationship field:
![imagem](https://github.com/Budibase/budibase/assets/594831/1b40487f-81a1-4e54-a3d3-d20d29064956)

If I understood correctly, this column/field (idClient in table VIPS_Project) should be automatically filled by Budibase, without any user input, but it just isn't.

What am I doing wrong?

Thank you for all the help!

**Comment by mike12345567** [comment]
Hi @zedascouves - that does look like an issue, would it be possible for you to provide the schema of the tables experiencing this problem? If I can replicate it within my development environment I will be able to see what is going on.

**Comment by zedascouves** [comment]
Sure, here it is: https://0.0g.gg/?5324d0a39070b7e1#9Ae2xehbNRdAPoxCr1ihvbAtzoFNtsDUDW3XCcJwAUfF

Thanks!

**Comment by mike12345567** [comment]
Hi @zedascouves - this link appears to have expired/be invalid.

**Comment by zedascouves** [comment]
For the sake of simplification, here's a simpler one, with only the two tables: https://pb.duarte.vg/?b62769b58eabfb02#BPFogUsGF6xDLsYuJK3mZKp6iFAsJ4xyPiscqGM2Fuhu

**Comment by mike12345567** [comment]
Hi @zedascouves - just to get back to you, I've been looking through your export (thank you very much for it!) and I believe I've found the issue. I'll get a fix out hopefully soon once I work out all the implications, once you update you will need to remove the relationships you've setup between your tables and then re-add them (sorry for the pain, but I believe they may have been mis-configured).

In future we hope to auto-detect these relationships and remove any kind of opportunity for mal-configuration, but this is still a little ways off, its a big project.

**Comment by zedascouves** [comment]
Hi @mike12345567,

Thank you for looking into it! Do you have any estimation of when will this be corrected? I'm using this for a client and, as you saw, there are quite a few relationships, so the sooner I map them out, the better.

Cheers!

**Comment by zedascouves** [comment]
On another note, and maybe it's related: should it be possible to select more than one option in the relationship picker?
![imagem](https://github.com/Budibase/budibase/assets/594831/729f5899-4087-4135-9738-078d587c8fcd)

**Comment by mike12345567** [comment]
> On another note, and maybe it's related: should it be possible to select more than one option in the relationship picker? ![imagem](https://user-images.githubusercontent.com/594831/247916352-729f5899-4087-4135-9738-078d587c8fcd.png)

This is a symptom of the issue - the fix I am putting together will mean this does not happen going forward.

**Comment by zedascouves** [comment]
Hi @mike12345567,

I see this has been merged and I've updated my app to the latest version, but I think the issue remains. Yes, I've recreated the relationships.

I've also deleted and re-added the datasource, but to no avail. Curiously, when I recreated the datasource, I didn't see the option to fetch only some tables, so all the tables showed up.

Any help is welcome!

Cheers!

**Comment by mike12345567** [comment]
Hi @zedascouves - can you confirm that your app has been updated to at least `2.7.30`? From the schema export you provided I was definitely able to get it working, at least for the VIP_Clients and VIP_Projects example you demonstrated.

**Comment by zedascouves** [comment]
I can confirm that that is the version I'm at. I tested with other tables, so let me try the clients->projects one.

About the table fetching: ok.

**Comment by zedascouves** [comment]
- I'm using the latest version:
![imagem](https://github.com/Budibase/budibase/assets/594831/76c2013b-0073-46df-b5cc-4d376700da1b)

- Redefined the relationship:
![imagem](https://github.com/Budibase/budibase/assets/594831/60066af6-8327-4e8e-9469-f69ed54904f0)

I've autogenerated a new screen from scratch, and I get:

- I can select more than one option from the relationship field menu:
![imagem](https://github.com/Budibase/budibase/assets/594831/f1bbd688-0fdb-496c-9a08-bcc55966b884)
- When I click "Save", I get:
![imagem](https://github.com/Budibase/budibase/assets/594831/d2ba3eae-9ac0-4551-b6ed-e591e7c4a45e)


I haven't created a new app from scratch, but I'll try that too, just in case.

**Comment by mike12345567** [comment]
@zedascouves - can you confirm for me whether or not you can create rows from the data view rather than through a screen? It could be a separate issue with foreign keys in the screen that I need to look into as well.

**Comment by zedascouves** [comment]
With a new app from scratch, and with no changes to the add/update form:

- Click "create row"
- Select a client from the drop-down relationship field (I can also select more than one option)
- This message shows up in the primary key field (that wasn't changed in any way):
![imagem](https://github.com/Budibase/budibase/assets/594831/a9e5ff8a-def6-45a7-bef3-cb0dd758c0f9)

**Comment by zedascouves** [comment]
> @zedascouves - can you confirm for me whether or not you can create rows from the data view rather than through a screen? It could be a separate issue with foreign keys in the screen that I need to look into as well.

I **_cannot_** create new rows from the data view just by filling the relationship field.
I **_can_** create new rows if I fill manually the foreign key field.

**Comment by mike12345567** [comment]
Just to add to the fetch table information as well - for now you can still reduce the list of tables you fetch by re-fetching the tables and toggling the fetch listed tables only - as seen here:
![image](https://github.com/Budibase/budibase/assets/4407001/9a651ea2-4ad5-4b50-9176-b317fecb2d44)

**Comment by zedascouves** [comment]
That also didn't work ;-)

**Comment by mike12345567** [comment]
Hi @zedascouves - I've had another look at this - so I've just created the single relationship between projects and clients, then the rest of the foreign keys I've just hardcoded, but left the `idClient` blank when creating a project.

seen below:
![image](https://github.com/Budibase/budibase/assets/4407001/1f5f480e-a803-49e0-8c40-e1fa24287c87)

This creates as expected, setting the `idClient` to the correct foreign key.

Would it be possible for you confirm that this works in a more limited scenario with just the single relationship?
![image](https://github.com/Budibase/budibase/assets/4407001/bba1981b-3759-4cb9-a4c5-ebe1066b2001)

**Comment by zedascouves** [comment]
It didn't work on my side :-\

https://github.com/Budibase/budibase/assets/594831/8cb83bc2-1ae3-47b6-9dee-8285c1665dc8

**Comment by mike12345567** [comment]
it seems to me like the relationship is still mis-configured - as it is still a multi-select for the relationship picker. Can you define the relationship from the MySQL datasource, as below:
![image](https://github.com/Budibase/budibase/assets/4407001/0e466930-9729-42cd-a8a9-6db493ecbae0)
![image](https://github.com/Budibase/budibase/assets/4407001/104ec000-c6b1-4b3e-b940-c74c929687eb)

I believe that the relationship is still getting configured as both sides being the many - although I am not sure how.

**Comment by zedascouves** [comment]
Ok, that way it worked (in the data view)!

**Comment by mike12345567** [comment]
Excellent! What way were you configuring the relationship before? I'll get a fix out as well for the screens not allowing the forms to send.

**Comment by zedascouves** [comment]
I think the to and from tables were switched.

Sent from a calculator.

A sexta, 23/06/2023, 14:27, Michael Drury ***@***.***>
escreveu:

**Comment by zedascouves** [comment]
Hi @mike12345567,

Is this in the latest version (2.7.33)?

Cheers

**Comment by mike12345567** [comment]
@zedascouves no not yet - some delays in testing.
