### ISSUE TITLE
Select a color for each option - option/multi-option field

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#10952]
**Describe the feature request**
Within the data section, when adding an option/multi-option field, I would like the ability to select a color for each option - this way I can color coordinate the options.

**Comment by poirazis** [comment]
hey @joebudi i would suggest the same feature be reflected to the options picker component too.
when either using the schema option or the custom options defined via the Options property editor
<img width="1134" alt="Screenshot 2023-06-20 at 7 10 00 PM" src="https://github.com/Budibase/budibase/assets/80512170/1108ed29-cc14-43a4-9701-77f56de86a63">


if I were to take this a bit further , i would suggest that color and icon properties be added to options / multiptions
This would make it super easy for no-code users to color / icon code their apps, and color/icon coding is like a must these days!

just my 2 cents !
