### ISSUE TITLE
Layouts panel does not open when binding drawer is active

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1095]
**Describe the bug**
After using the binding drawer I wanted to change the layout. I was unable to.

**To Reproduce**
1. open bindings drawer
2. Click on layouts

![Screenshot 2021-02-05 at 12 30 35](https://user-images.githubusercontent.com/49767913/107035013-708a9480-67af-11eb-81ff-936e4c7d2ef9.png)

**Comment by aptkingston** [comment]
As discussed in discord, this is caused by `svelte-portal` (used by the drawer) preventing a component unmounting when it's supposed to. @kevmodrome 's upcoming change to close the drawer when clicking outside should hopefully fix this by ensure the drawer is closed before navigating away.
