### ISSUE TITLE
[BUDI-7168] Custom user fields get wiped when user resets password

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10969]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.7.19
  * App Version: 2.7.19

**Describe the bug**
Whenever a user resets their password, any custom field values are wiped from the Users table.

**To Reproduce**

1. Give a user access to a newly created app
2. Add a boolean column to the users table of the app.
3. Tick the checkbox for the user and publish the app
4. Reset the password of that user
5. The checkbox is now wiped

**Expected behavior**
Resetting a users password should not wipe the custom user fields.

**Screenshots**

A user with checkboxes ticked:

![Screenshot 2023-06-20 at 10.01.59.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/57b4fa12-ce83-426a-8180-7bca2eb45443/d4de5133-ed38-4277-9cf2-69e774b9ef40)

Force reset their password:

![Screenshot 2023-06-20 at 10.02.34.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e11aa031-3fd5-4d86-9598-a3f224ba8562/f15e991e-fd63-48e8-9a56-1981d2a59008)

Custom field values are now wiped:

![Screenshot 2023-06-20 at 10.03.51.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/081abc9f-8033-476c-9a48-16f5f7fb67bd/3f14a68a-1292-4fc6-94d0-117bc8f5312e)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7168](https://linear.app/budibase/issue/BUDI-7168/custom-user-fields-get-wiped-when-user-resets-password)</sub>

![bug](https://github.com/Budibase/budibase/assets/101575380/52be681c-afb6-4e99-a711-f41e4b62e7a4)

**Comment by melohagan** [comment]
When the `save` user function is called, the custom fields are not present. Possibly because the custom fields are saved against the apps?

https://github.com/Budibase/budibase/blob/develop/packages/worker/src/api/controllers/global/users.ts#L39

**Comment by manwithpowers** [comment]
Sorry if this isn't kosher to comment here, but could their be a relation to this bug I filed last month? [Logging in via SSO or as new user deletes custom column data in Users table](https://github.com/Budibase/budibase/issues/10471)

**Comment by melohagan** [comment]
Hey @manwithpowers I believe this is the same bug. I'm sorry that it slipped past me, because your issue was well written up - I appreciate that!

I've just tested this in **2.7.26** and it appears to be resolved now. Let me know if you have any further issues after updating!

**Comment by melohagan** [comment]
Hey @manwithpowers I believe this is the same bug. I'm sorry that it slipped past me, because your issue was well written up - I appreciate that!

I've just tested this in **2.7.26** and it appears to be resolved now. Let me know if you have any further issues after updating!

**Comment by manwithpowers** [comment]
No problem, thanks for getting back to me! I'll give 2.7.26 a try as soon as I can and report back if there are any other issues.
