### ISSUE TITLE
[BUDI-7166] The date is not being saved correctly

### ISSUE THREAD

**Issue by alx25** [Budibase/budibase#10963]
**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.7.21
  * App Version: 2.7.21

**Describe the bug**
When I enter a date using the Date Picker control, for example 30-06-2023, when saving it in my data base(PostgreSQL), it is saved as the date 29-06-2023.

It is always saved with a one-day difference from the date I entered.

I have already checked the regional settings of my server, and they are correct.

**To Reproduce**

1. Add a date picker.
2. Enter a date.
3. Save.

**Expected behavior**
If I select 30-06-2023 in my application, the date should be saved as such.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/c7729d21-2ba4-4b68-902d-bfa56bc52b76/45d26895-18e6-4a2f-8c87-d2c8f3e06399)

When I save

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/aba424cd-95df-47a3-8e37-5b8200ee2766/8790a082-5796-4598-928d-12266d0a601f)

**App Export**
[Feriados-export-1687201800376.tar.gz](https://github.com/Budibase/budibase/files/11791420/Feriados-export-1687201800376.tar.gz)

**Desktop (please complete the following information):**

* OS: Ubuntu 22.04
* Browser chrome

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7166](https://linear.app/budibase/issue/BUDI-7166/the-date-is-not-being-saved-correctly)</sub>

**Comment by mike12345567** [comment]
Hi @alx25 - if you set the timezone of your app/worker services, through the environment variable `TZ` within your `docker-compose.yaml` this will rectify the issue.

The timezone you set should be the same as the timezone in which your database is hosted - by default we will assume UTC, but this may not be consistent with the timezone the database is hosted within.

Timezone list can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones e.g. `Europe/London` or `America/Costa_Rica`
