### ISSUE TITLE
[BUDI-7206] Budibase tries to connect from an IP address not in the docs

### ISSUE THREAD

**Issue by TimVee** [Budibase/budibase#10971]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: strobbo

**Describe the bug**
Budibase tries to connect to our database from 54.220.176.165, which isn't in the list of IP addresses budibase uses according to [https://docs.budibase.com/docs/whitelisting#budibase-cloud](https://docs.budibase.com/docs/whitelisting#budibase-cloud).

**To Reproduce**

1. Open a page that needs a database connection.

**Expected behavior**
Budibase should only use the documented IP addresses.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/251ad9a8-4746-4c34-be3c-0ced33559efc/b475c9d3-8191-4512-a2d9-abb04071734c)

**Desktop:**

* OS: Windows
* Browser: Edge
* Version: 114

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7206](https://linear.app/budibase/issue/BUDI-7206/budibase-tries-to-connect-from-an-ip-address-not-in-the-docs)</sub>

**Comment by jonnymccullagh** [comment]
@TimVee I apologise for the disruption. We had an unplanned intervention on AWS replacing our worker nodes and thus IP addresses. I have updated the [docs page here](https://docs.budibase.com/docs/whitelisting) with the new IP addresses for whitelisting.

**Comment by palsivertsen** [comment]
@jonnymccullagh Thanks!

Is the email(?) notifications working? Last time this happened I did not get notified.

**Comment by jonnymccullagh** [comment]
I don't believe there would be any impact on email sending.

**Comment by melohagan** [comment]
Resolved. Docs updated.
