### ISSUE TITLE
Better Log Messages for CouchDB setup script with docker-compose

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1097]
- The error messages can be a red herring - we should have a more friendly output to show the status of the couch setup script
- Potentially an overall more sophisticated bootstrap script for the docker containers to ensure that they are all configured properly

**Comment by mike12345567** [comment]
Had a discussion around this - we currently have a ultra-lightweight container that is part of the self hosted setup which simply curls the couchDB container to see if it is working correctly, this is the `couch-init` service in the `docker-compose.yaml`. Thinking we can expand on this to become the large bootstrap script which checks the app, worker and minio services as well for health and once all of these are confirmed healthy or unhealthy prints something like:

### Healthy
```
  ___         _ _ _                  
 | _ )_  _ __| (_) |__  __ _ ___ ___ 
 | _ \ || / _` | | '_ \/ _` (_-</ -_)
 |___/\_,_\__,_|_|_.__/\__,_/__/\___|
  Go to http://localhost:10000 for 
            next steps!
```
### Unhealthy
```
ERR! Failed to start Budibase services
ERR! ERR-CODE-1
ERR! Please visit https://github.com/Budibase/budibase/issues and
ERR! raise this issue with us, providing your bb-error.log and code
```

Error stuff just a suggestion, wouldn't need all of this initially but building around being able to do something like this might be a good idea.
