### ISSUE TITLE
[BUDI-7172] Define relationships button is visible for Google Sheets even though it does not support relationships

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10970]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Describe the bug**
> I am trying out a self-hosted budibase installation  with google sheets integration. I am trying to create a simple relationship > between two tables. After fetching the tables successfully and on trying to establish the relationship, I am getting this error: > "Error saving column: Column type: link not allowed for GSheets integration."

> Now, I am somewhat confused because feedback I am getting from the UI is a bit thin. Is the relationship not possible? > Looking at https://budibase.com/blog/data/google-sheets-dashboard/ it seems like it should, but the post is also slightly > outdated and everything looks different. I tried Googling for help but to no avail.

From this discussion: https://ptb.discord.com/channels/733030666647765003/1120666969826394163

**To Reproduce**
1. Add a Google Sheets datasource
2. Fetch some sheets
3. Click on a table -> See that the `Define relationships` button is visible.

**Expected behavior**
Define relationships should be hidden or disabled if the Integration has `relationships: false`

<sub>[BUDI-7172](https://linear.app/budibase/issue/BUDI-7172/define-relationships-button-is-visible-for-google-sheets-even-though)</sub>

**Comment by jochenstu** [comment]
Cool, thanks for the responsiveness and creating the issue right away! (I was the one who brought this thing up)

To add a little onto this: To me, having Google Sheets as a backend in budibase was a super big deal, given that it brings super user friendly backup, rollback and "managed everything". It gels really well with the whole low tech approach, so I want to encourage you to actually include/bring back this option if at all feasible in the future.

**Comment by mike12345567** [comment]
Hi @jochenstu - sadly having relationships in googlesheets is very unlikely to be supported - as there is no concept of relational data within Googlesheets itself it is very difficult for us to provide this.
