### ISSUE TITLE
'Send Analytics to Budibase' setting not saved

### ISSUE THREAD

**Issue by Canard164An207** [Budibase/budibase#1098]
**Describe the bug**
The Analytics setting is always reset to 'Yes'. It is impossible to deactivate it.

**To Reproduce**
1. Go to the settings
2. Click on Send Analytics to Budibase to deactivate it.
3. Click on Save.
4. Message 'Settings saved' is displayed correctly.
5. Re-open the settings.

**Comment by shogunpurple** [comment]
@Canard164An207 thanks for raising - I see the issue. It actually does disable analytics when you click that toggle but there's a UI bug which always shows it as on. Will get that fixed asap and push a release. Thanks again 👍

**Comment by shogunpurple** [comment]
Should be fixed on the latest release
