### ISSUE TITLE
[BUDI-7208] Exporting data from a table with relational columns

### ISSUE THREAD

**Issue by cproudlock** [Budibase/budibase#10988]
**Hosting**
- Self
  - Method: Docker
  - Budibase Version: 2.7.21
  - App Version: 2.7.21

**Describe the bug**
I'm attempting to create an export table button. The table has a relationship column that isn't being included in the exported CSV file.

**To Reproduce**
1. Create a relationship column in a database table.
2. Create a table in design that will display the data.
3. Create a button that will export data from the table into a CSV.
4. CSV will not have the column nore the data from the relationship entries.

**Expected behavior**
I expect all of the data in the table to export.
  
**App Export**
https://data.proudlock.tech/sharing/BvVYGjepD

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 114.0.1823.51

<sub>[BUDI-7208](https://linear.app/budibase/issue/BUDI-7208/exporting-data-from-a-table-with-relational-columns)</sub>

**Comment by melohagan** [comment]
This is by design. We cannot guarantee that the IDs would be the same when re-importing elsewhere, so we don't export them.
