### ISSUE TITLE
Export Data: Add "Separator" selector

### ISSUE THREAD

**Issue by cnrodrig** [Budibase/budibase#10996]
I would love to, when using the Action Export Data, have the option to choose the separator (in South America we use ; instead of , )

![image](https://github.com/Budibase/budibase/assets/6564749/2a918175-5a19-4300-b6a9-4dda2c89e6eb)

**Comment by melohagan** [comment]
Hey @cnrodrig 

Thanks for raising, good idea! However I am going to close this as a duplicate of: https://github.com/Budibase/budibase/issues/8799
