### ISSUE TITLE
[BUDI-7177] Vertical scrollbars on binding inputs aren't working

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#10990]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.7.21
  * App Version: 2.7.21

**Describe the bug**
Whenever doing large functions or providing large amounts of text to the bindings area, you aren't able to scroll up and down. This becomes more of an issue if you are on a smaller screen sized device.

**To Reproduce**

1. Go to any app's design view.
2. Add a component.
3. Click on the lighting bolt beside e.g. title, text etc.
4. Type out a large function or a large amount of text.
5. See issue.

**Expected behavior**
You should be able to scroll up and down within this area and edit all text/code contain within.

**Screenshots**

![Screenshot 2023-06-22 at 08.38.33.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/685cb983-5ecc-43a7-bf53-0a68d6f44658/eda7a183-5de4-4844-bbfe-562d4335c974)

**App Export**

[vertical scroll bug-export-1687419267817.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ce9e6363-f02c-4dbb-9927-31fd64394c4c/750e11d7-f18a-42ad-ab4e-7f7f6d065a2a)

**Desktop (please complete the following information):**

* OS: macOS Ventura
* Browser Brave
* Version **v1.52.126**

**Additional context**
Related discussion can be found here; [https://github.com/Budibase/budibase/discussions/10972](https://github.com/Budibase/budibase/discussions/10972)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7177](https://linear.app/budibase/issue/BUDI-7177/vertical-scrollbars-on-binding-inputs-arent-working)</sub>

**Comment by aptkingston** [comment]
Fixed in develop, will be released this coming week.
