### ISSUE TITLE
[BUDI-7203] used custom query while saving a form

### ISSUE THREAD

**Issue by harman-bluebash** [Budibase/budibase#11016]
I am using postgres datasource in my app and have fetched users table from  budibase table and have another table in postgres named duplicate_reports i want that when i create a new duplicate_report current user id should be saved in duplicate_reports table, but value is not stored.
although i have created a custom query to fetch the id of current user, but getting the same isue.

<sub>[BUDI-7203](https://linear.app/budibase/issue/BUDI-7203/used-custom-query-while-saving-a-form)</sub>

**Comment by melohagan** [comment]
Please use the issue template. Closing.
