### ISSUE TITLE
[BUDI-7200] Dataprovider Filters / 'match any' vs. 'match all'

### ISSUE THREAD

**Issue by tglynx** [Budibase/budibase#11018]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

This issue may be related to #9473

**Hosting**

- Self
  - Method: docker compose 
  - Budibase Version: 2.6.20.
  - App Version: 2.6.20.

**Describe the bug**
When using 'Define Filters' on a dataprovider i would assume that the behaviour 'macht all filters' would combine the defined filters using 'AND' whilst the behaviour 'match any filter' would combine the defined filters using 'OR'. Is that right? 
This does not work for me. 

**To Reproduce**
1. Go to 'Define Filters' of a Data Provider. 
2. Define 2 Filters where you want any of the criterias beeing matched (behaviour 'match any filter')
4. Dataprovider only returns rows where all criterias are beeing matched -> 'match all filters'

**Expected behavior**
Lets assume the following table: 
I want to retrieve records with Status1 = True or Status2 = True. 
```
Status1;Status2
True;True
True;False
False;True
```

I would assume that with 'match any filter' all three rows should be returned. That is not the case. 
Only Row 1 is returned (same as with 'match all filters').

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 114.0.5735.133 

<sub>[BUDI-7200](https://linear.app/budibase/issue/BUDI-7200/dataprovider-filters-match-any-vs-match-all)</sub>

**Comment by melohagan** [comment]
Hey @tglynx 

Could you please provide screenshots of your filters.

Also please provide the datasource you are using and the data types of the columns being filtered. Thanks!

**Comment by tglynx** [comment]
Hi @melohagan

i am using the bb internal db.

These are my filters: 
![Bildschirm­foto 2023-06-28 um 15 43 58](https://github.com/Budibase/budibase/assets/30650435/c5e9a0ae-e5b0-4742-a82a-e5675290b959)

The datatypes are: 
Text for LiceneNumber and InsuranceNumber and Boolean for StatusClearance, RulesAccepted, DataPolicyAccepted

I want to select records where any of those filters is matched, but i only get records where all filters match (for both: 'Match any filter' (or?) and 'Match all filters' (and?))

Thanks,
Michael

**Comment by melohagan** [comment]
Appears to be specific to the boolean fields. The Match any works as expected when only checking *Is empty*

**Comment by tglynx** [comment]
I can confirm that it works as expected with just 'text' fields checking _Is empty_ in the filter.

**Comment by melohagan** [comment]
Fixed in **2.8.6**
