### ISSUE TITLE
Ability to revoke invitations

### ISSUE THREAD

**Issue by diogenesbrussels** [Budibase/budibase#11044]
**Describe the feature request**
I would like to be able to manage invitations to new users:
- Be able to revoke them
- See the remaining validity period
- Extend the validity period?

Discord discussion for ref.;
https://discord.com/channels/733030666647765003/1121369030343786639

**Comment by aptkingston** [comment]
Thanks for raising this @diogenesbrussels 👍

**Comment by diogenesbrussels** [comment]
@aptkingston Is it still planned or considered? Thanks!

**Comment by diogenesbrussels** [comment]
Duplicate #12342  ?

**Comment by OriginalLimited** [comment]
Hello,

When you invite a user and they are sat in "Pending Invites" there are no options to make changes. 
For example:
- Cancel Invite
- Re-send Invite

I found this out when the email settings were not setup correctly - the email did not send and I cannot add the same email addresses again.

Thanks!
