### ISSUE TITLE
[BUDI-7225] Table column widths corrupted on imported postgreSQL table

### ISSUE THREAD

**Issue by kpturner** [Budibase/budibase#11051]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: monito

**Describe the bug**
See [https://github.com/Budibase/budibase/discussions/11017](https://github.com/Budibase/budibase/discussions/11017)

**To Reproduce**
I can only reproduce this on one imported table.  Since it is not possible to delete and re-import a table I cannot work out why it has gone wrong.  The CSS generated for the table columns is invalid:

![image](https://github.com/Budibase/budibase/assets/308646/d0ddeacb-4255-4271-bf36-18ed10ae7edd)

when I believe it should be

![image](https://github.com/Budibase/budibase/assets/308646/f291270f-d02f-4844-86cc-c2e5ce2e9224)

Change the column widths to 200px then back to Auto seems to fix it, but then I still do not get the `minmax` values, I get

![image](https://github.com/Budibase/budibase/assets/308646/048a3b89-0e71-4027-83b2-7ff50f53669c)

The only way I can achieve `minmax` CSS is to explicitly set the column widths to `minmax(auto 1fr)` rather than `Auto`

**Expected behavior**
Default column widths should be correct

**Screenshots**
See [https://github.com/Budibase/budibase/discussions/11017](https://github.com/Budibase/budibase/discussions/11017)

**App Export**
Do I really need to do this?  The problem is that the datasource is secure and contains the password.  I cannot really provide that.  It begs the question, if you have the tenant id can you access it or do you have to be added as a user?

**Desktop (please complete the following information):**

* OS: Mac iOS
* Browser Chrome
* Version 114.0.5735.133 (Official Build) (x86_64)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7225](https://linear.app/budibase/issue/BUDI-7225/table-column-widths-corrupted-on-imported-postgresql-table)</sub>

**Comment by kpturner** [comment]
Where have the screenshots gone?

**Comment by kpturner** [comment]
As you have the cloud tenant id (`monito`) you should be able to replicate this using the `country` table from the imported schema labelled `Staging - Main DB` 

What would be good would be to be able to completely remove and imported table then re-import it.  Something internal to the BB database is wrong with this table, and simply re-importing it does not fix it.  Either that or there is something (that I cannot spot) about this table that is unusual.

**Comment by kpturner** [comment]
I have also emailed the schema to support

**Comment by kpturner** [comment]
I have just had this happen again with another table. This time the table was all fine (screens deigned and save - all OK).
I then wanted to check the type of one particular field. So I went to visit the grid in the Data section (as opposed to Design) edited one of the columns to ensure it was Number, clicked save and the returned to the design. This was the result for the table page:

![image](https://github.com/Budibase/budibase/assets/308646/3c47405d-6b8a-4540-a0fe-eb8f935a43ae)

**Comment by kpturner** [comment]
In addition to the column widths in the table going awry, so does the formatting of a dynamic filter component.  It looks like this
![image](https://github.com/Budibase/budibase/assets/308646/4b712a1f-d880-4bf0-a87a-0f3c9bfd07f3)
However, unlike the table columns where one can override the CSS for the columns, you cannot do anything with the CSS for the filter

**Comment by mike12345567** [comment]
Hi @kpturner - just to confirm, have you updated your Budibase app version? https://docs.budibase.com/docs/update-app-version

**Comment by kpturner** [comment]
No I hadn't done that.  Is this a known issue that has since been fixed?

I have updated now and it appears to be OK - although I had to edit all the columns to remove the width

**Comment by kpturner** [comment]
May I ask what is meant by "....with the installation"?

**Comment by mike12345567** [comment]
@kpturner - when I say this I mean the version of the the overall services, this more applies to the self hosted version of Budibase, but we upgrade the backend services of Budibase periodically in the Cloud as well - so there are two versions that need updated:
1. The installation - the backend services and the frontend bundles
2. The app library - per app, this can be updated to the latest version provided by the installation

In future we might make both of these updates one in the same, if the installation is updated then all apps within will also be updated as it avoids scenarios like this.
