### ISSUE TITLE
Drawers stack on top of each other when you click several bindable fields

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1113]
In the design panel, when you click several fields that bring up the binding drawer, the drawers get stacked. Destroy the first drawer when the second bindable input is clicked

**Comment by aptkingston** [comment]
I agree this is a bug when considering clicking on different component settings causing multiple drawers to open, but I also think there are times when we want multiple drawers open, so we shouldn't prevent multiple drawers being open entirely.

For example when adding bindable URL params, I had to update the "navigate to" button action. These actions are already displayed in a drawer, so the bindable input that appears to enter the URL now opens a second drawer on top of that to configure bindings. Personally I think this feels much better than using the popover on top of the drawer, which is currently done when entering bindable values into some of the other actions (execute query I think) - and I think we should actually refactor that to open a second drawer for bindings as well. I've made a new `DrawerBindableInput` component which makes that super easy. 2 layers of drawers (with different purposes) make sense in this case, but definitely not in the case of having multiple binding drawers open for different components.

What do you reckon?

**Comment by shogunpurple** [comment]
@aptkingston I half-jokingly said before that the current behaviour is actually a nice experience if you are updating a few different bindings in the builder, so I'm inclined to agree. If we are to go down that path, I think we should have a title in each drawer, so you know exactly what you are configuring/binding to. Even just a title saying something like `ComponentName -> <Design Prop>` or something would make it super clear as to what you were working on, and allow the nesting of dependent drawers.

Should we:
- Refactor the popovers to stack drawers on top of each other using `DrawerBindableInput`
- Give every Drawer an explicit title so the user doesn't get lost in a sea of drawers

?

**Comment by aptkingston** [comment]
@shogunpurple titles is a great idea yea. I honestly think that will be a much nicer experience for the user (and more consistent) if we always use drawers for bindings rather than having a popover inside a drawer, even if that means multiple drawers. That sounds like a plan.

**Comment by shogunpurple** [comment]
Nice one - looks like we are in agreement. The popovers can be a little gnarly on certain screen sizes and browsers too, so I think removing that concept from binding in general will be much nicer UX wise.
