### ISSUE TITLE
[BUDI-7257] Allow app Name and URL to be edited inline

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#11150]
**Describe the feature request**
When changing the Name and URL, you have to click `Edit` which opens a modal that is just a replica of the settings anyway.
It would be nice if the edit button made the existing fields type-able.

I also noticed a minor UI bug:

1. Click edit and change the URL - save.
2. Click edit again.
3. Do not change the name, simply click off the name field.
4. See that the custom URL has now been set to the name of the app. (Animation below)

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/8146b442-ff20-4197-8ac8-239ffd34a42a/fade7867-61e4-49ef-9d9a-6e6c3085be01)

[Source image](https://github.com/Budibase/budibase/assets/101575380/555d23e9-2d1a-46c9-bba0-527ecf7b61f6)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5059cfe8-80ee-468d-803a-4691c457fc22/3aa4e948-9068-42d2-b9bc-70f38e259809)

[Source image](https://github.com/Budibase/budibase/assets/101575380/6859b53a-98f7-4fd7-ab87-3c18352bf35b)
*Why open this modal when you could inline edit the fields?*

**Bug**

[https://github.com/Budibase/budibase/assets/101575380/5e0476e9-03b7-4d15-a0f3-fa30ea917362](https://github.com/Budibase/budibase/assets/101575380/5e0476e9-03b7-4d15-a0f3-fa30ea917362)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7257](https://linear.app/budibase/issue/BUDI-7257/allow-app-name-and-url-to-be-edited-inline)</sub>

**Comment by joebudi** [comment]
To add to this, it would be great if we could inform the user they have to unpublish their app (if published) before they can make any changes to the name, icon, url.

<img width="1222" alt="CleanShot 2023-08-21 at 09 06 51@2x" src="https://github.com/Budibase/budibase/assets/49767913/64fb196b-9a6a-41b0-878d-4d111084c49c">

**Comment by aptkingston** [comment]
> To add to this, it would be great if we could inform the user they have to unpublish their app (if published) before they can make any changes to the name, icon, url.
> 
> <img alt="CleanShot 2023-08-21 at 09 06 51@2x" width="1222" src="https://user-images.githubusercontent.com/49767913/261960296-64fb196b-9a6a-41b0-878d-4d111084c49c.png">

It does already if you hover over the edit button 👌 

![image](https://github.com/Budibase/budibase/assets/9075550/0c23f106-260d-4c26-81a3-1e0b2242276d)

**Comment by joebudi** [comment]
Ah ok. I missed that. I suppose it's still relevant if we decide to remove the button (Mel's point).

**Comment by melohagan** [comment]
I didn't even know it did that 😁 In my mind I wouldn't think to interact with a disabled button.

**Comment by melohagan** [comment]
![Screenshot 2024-08-15 at 10 18 38](https://github.com/user-attachments/assets/94217aac-0131-4f35-b17b-694f69f1aa8f)

Done!
