### ISSUE TITLE
[BUDI-7348] No SCIM documentation

### ISSUE THREAD

**Issue by devSparkle** [Budibase/budibase#11157]
**Checklist**
- [x] I have searched Budibase discussions and GitHub issues to check if my issue already exists

**Describe the bug**
I recently found, through the product features page, a paragraph indicating Budibase had added support for AD/SCIM sync. However, unlike OpenID Connect and related features; there is no documentation regarding this feature.

It's also worth noting that the [features page](https://budibase.com/product/) describes it as a Business tier feature, whereas the [pricing page](https://budibase.com/pricing/) says its only available in the Enterprise plan.

**Expected behavior**
Documentation on how to setup, expected SCIM attributes, and a list of features and limitations.

<sub>[BUDI-7348](https://linear.app/budibase/issue/BUDI-7348/no-scim-documentation)</sub>

**Comment by melohagan** [comment]
Documentation added: https://docs.budibase.com/docs/scim-provisioning
