### ISSUE TITLE
[BUDI-7260] [Builder] Bindings drawer HBS {{ /if }} syntax highlight issue

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#11158]
Self hosted 2.8.1

The HBS expression works, but is not correctly highlighted.

First Screenshot is from editing the HBS on a Formula Column

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e79df6b5-9d77-43ce-ad98-8b4b8cb13200/99a72d09-82a0-4f05-8c17-9e8ebbb09423?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lNzlkZjZiNS05ZDc3LTQzY2UtYWQ5OC04YjRiOGNiMTMyMDAvOTlhNzJkMDktODJhMC00ZjA1LThjMTctOWU4ZWJiYjA5NDIzIiwiaWF0IjoxNjg5Njc0MzA3LCJleHAiOjE2ODk3NjA3MDd9.RskJ5M2gnOLyxYO2WoV0K08r0lSk4Iqk4528z0D_32Q)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/a47f657a-4ac9-40e0-b41a-af8d0404e93c/810caffe-aaf8-4db7-beaa-4556d8b3c522?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hNDdmNjU3YS00YWM5LTQwZTAtYjQxYS1hZjhkMDQwNGU5M2MvODEwY2FmZmUtYWFmOC00ZGI3LWJlYWEtNDU1NmQ4YjNjNTIyIiwiaWF0IjoxNjg5Njc0MzA3LCJleHAiOjE2ODk3NjA3MDd9.mDtvo37RMysKrtHlzjRuyxwy6fKk8d0Oj8GTq0HfjPs)

[Source image](https://github.com/Budibase/budibase/assets/80512170/fae85dcf-558e-43ad-a377-f01469c96d5c)

Second Screenshot by @melohagan from autogenerated screen bindings

[Source image](https://github.com/Budibase/budibase/assets/80512170/19140eb7-c779-4683-8d15-418a745f290e)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7260](https://linear.app/budibase/issue/BUDI-7260/[builder]-bindings-drawer-hbs-if-syntax-highlight-issue)</sub>

**Comment by diogenesbrussels** [comment]
I've noticed other similar problems:
- With a date to display 
![image](https://github.com/Budibase/budibase/assets/91942877/9285fd53-3deb-4fa8-80c7-759a220c2808)
![image](https://github.com/Budibase/budibase/assets/91942877/d824bd71-de06-4d96-95d4-b850edae00b1)
![image](https://github.com/Budibase/budibase/assets/91942877/2ca7c58b-c839-4d9e-b1e7-e8f996e80a5c)

- With parseJSON or JSONparse? The syntax is invalid
![image](https://github.com/Budibase/budibase/assets/91942877/02bedc20-5350-44e7-9c74-224d5a0bb56e)


Tell me if I need to create another issue with these cases.

**Comment by diogenesbrussels** [comment]
The addition of parentheses also seems to have an impact.
![image](https://github.com/Budibase/budibase/assets/91942877/e5be86f2-a053-44ed-af09-3d8b3b979946)
![image](https://github.com/Budibase/budibase/assets/91942877/9ae96767-2f62-4d3e-9052-ec3dd97b9222)
