### ISSUE TITLE
[Grid Block] Allow Grid Block to be controlled via Actions

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#11165]
I would suggest that Grid Block should be able to be controlled via Actions.

Like Insert Row , Delete Row , Save Row so you can drive it with other buttons and/or automate behaviour.
Also possibly add a Refresh Action ?

**Comment by melohagan** [comment]
This is now possible with Grid block buttons 👍 

![Screenshot 2023-11-27 at 12 51 58](https://github.com/Budibase/budibase/assets/101575380/770a792c-6fbd-47f8-984d-7825abb2b170)
