### ISSUE TITLE
Failed to connect to postgres database "Unable to connect - connect ECONNREFUSED 127.0.0.1:5432 "

### ISSUE THREAD

**Issue by zhaowenbooo** [Budibase/budibase#11163]
Hello!

Since the default database of budibase is redis, I want to connect to a relational database, and after going through online training videos, I still can't connect to postgres, my postgres is in docker.

What can i do to connect to postgresSQL, Thanks a lot!

<img width="483" alt="Capture2" src="https://github.com/Budibase/budibase/assets/111510081/10726dee-f72d-4d1e-aac6-914dac587d7a">
 
<img width="322" alt="Capture1" src="https://github.com/Budibase/budibase/assets/111510081/f70e6d75-e663-4aa4-9a9b-0ba73a2f9366">

**Comment by mike12345567** [comment]
Hi @zhaowenbooo - it looks like you're hosting via Docker compose. In this environment, `127.0.0.1` will point to your app service containers localhost, this is not where your Postgres database is. You'll need to point to the postgres service via the Docker network, for example `my-postgres` might be a valid URL depending on how your docker-compose network is configured.

This is documented as part of the Postgres datasource setup https://docs.budibase.com/docs/postgresql#datasource-setup
