### ISSUE TITLE
[BUDI-7264] Number of filters set is different between Match Any and Match All

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#11175]
**8Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.8.2
  * App Version: 2.8.2

**Describe the bug**
When adding filters to a Budibase DB table in the Design section, I noticed that in the settings panel the number of "filters set" changed depending on whether *Match any* or *Match all* was selected.

Related issue: [https://github.com/Budibase/budibase/issues/11018](https://github.com/Budibase/budibase/issues/11018)

**To Reproduce**

1. Add filters to a table block for a Budibase DB (see gif)
2. Switch between *Match all* and *Match any*, and save
3. Notice that *Match all* has the correct number, whereas *Match any* has +1 filter count.

**Expected behavior**
The number of filters set should not change when the *Match All/Any* setting is changed.

**Screenshots**

![Linear-hosted image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/c178506e-1aa9-4476-8fb1-0b551e482458/247ce88d-73f3-4a42-bd6d-a083411aedca)

[Source image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/c178506e-1aa9-4476-8fb1-0b551e482458/247ce88d-73f3-4a42-bd6d-a083411aedca)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7264](https://linear.app/budibase/issue/BUDI-7264/number-of-filters-set-is-different-between-match-any-and-match-all)</sub>

**Comment by aptkingston** [comment]
Just to speed you up on this, the reason is that we append a filter to indicated that we want "match any".

```js
.concat(matchAny ? [{ operator: "allOr" }] : [])
```

So in the button where we're counting the filters, we just need to filter out that one before counting them. I'm sure you've probably found this out already, but thought that might help!

**Comment by melohagan** [comment]
Cheers @aptkingston 

Yeah that's what I did, just filtered to make sure a *field* property existed when counting. Working on the related Match all/any bug here: https://github.com/Budibase/budibase/issues/11018 before pushing up
