### ISSUE TITLE
Add Preview URL link to newest version v2.8.1

### ISSUE THREAD

**Issue by miguelou7** [Budibase/budibase#11177]
Include a link to a Preview URL along with the Preview Button.

Why:
Up to now, to see a preview of your changes, you jumped to a unique URL that has the changes that are not in production. This is exactly the pattern that is used in basically the majority of editing software and it worked like a charm. This new release, has the preview inside the Editor, and generates a LOT of problems with testing things fast. As a User, I really NEED to see the preview as a standalone website, so I can better understand de final look and feel, try stuff with the chrome inspector, etc.

![Screen Shot 2023-07-10 at 13 17 26](https://github.com/Budibase/budibase/assets/1044367/b931e16d-bd6c-4460-a774-b9852e8a29bc)

Just a Preview Button, and no link!

**Comment by zigenis** [comment]
I see that @aptkingston's additions have been merged, but has this made it into a release yet? I'm running version 2.8.14 and I don't see the "Fullscreen" option, which would be very helpful as it seems that the in-editor preview totally breaks when using URL variables.

**Comment by aptkingston** [comment]
@zigenis they'll be going out in the July release this coming week 👍 

> the in-editor preview totally breaks when using URL variables

The in-editor preview performs exactly the same as the "old" preview, the only difference being you can't manually edit the URL, which I doubt is how you would normally use your app. Navigating to a page with URL variables set will work as normal. 

If you were editing a page that expects URL variables and you preview it, then you won't have any URL variables set so it will redirect you back to another valid route. You can then use the app as a normal user would and navigate to a screen with the URL variables set properly by your application.

Have you had an issue with using URL variables? I appreciate it might be nice to offer an option when previewing which would let you enter URL variables to preview the page with, but that would be a nice feature in general and not specific to this in-editor preview.

**Comment by zigenis** [comment]
@aptkingston 

I tried what you mentioned and that did the trick. I misunderstood how the preview worked, thank you for the clarification.
I updated my instance this week and I see the original functionality is available again as well. All is right in the world again!

It seems like this issue can be closed now.
