### ISSUE TITLE
Can't select relationship option value in row menu

### ISSUE THREAD

**Issue by Hiroip** [Budibase/budibase#1119]
Hi,

**Describe the bug**
After creating a relationship between two table, when creating a new row, scroll down menu doesn't appear when clicking on the relationship field.

**To Reproduce**
Create 2 tables with a relationship column.
Create a new row.
Click on the "Choose some options" on the relationship column

**Expected behavior**
Scroll down menu appears and you can choose the appropriate row in the other table.

**Screenshots**
![image](https://user-images.githubusercontent.com/5566269/107839548-9afbd380-6de7-11eb-9096-4fddda9ddc53.png)
![image](https://user-images.githubusercontent.com/5566269/107839555-a51dd200-6de7-11eb-906e-933a48be9acf.png)
![image](https://user-images.githubusercontent.com/5566269/107839544-96371f80-6de7-11eb-9b61-0f76ccf56c86.png)
![image](https://user-images.githubusercontent.com/5566269/107839559-ad760d00-6de7-11eb-96a2-35b3ded65064.png)

![image](https://user-images.githubusercontent.com/5566269/107839570-ba92fc00-6de7-11eb-8b6f-ada5b39eeeb6.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - App version 0.7.6

Best regards,

**Comment by yashank09** [comment]
Seems to be linked to this issue: #1101 
I can have a MR by tonight if it's only about setting z-index, but will have to replicate on Linux first.

**Comment by shogunpurple** [comment]
Should be resolved in the latest release
