### ISSUE TITLE
[BUDI-7268] Relationship picker doesn't show all rows in dropdown selection

### ISSUE THREAD

**Issue by miguelou7** [Budibase/budibase#11214]
**Hosting**
Budibase Cloud hosting, business account.

**Describe the bug**
Relationship picker doesn't show all rows in dropdown selection (therefore specific items don't show up in the autocomplete search).
In other words: within a form, when trying to select an item from a dropdown field (a relationship), many items are missing.

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/4f6f3940-b84f-47a1-9147-b299b5a6148e/fb57951d-9c0a-4e59-803d-c762ab0b6577)

[Source image](https://github.com/Budibase/budibase/assets/1044367/6578f29f-8d4d-4483-b244-8bcba731e67d)

Relevant: source data is a Postgres DB, and the table with the targeted relationship has 8k items. (6 columns).

**To Reproduce**

1. Go to screen
2. Click on dropdown
3. Search a specific item.
4. Doesn't appear.

Notes:
There seems to be no logic as to which items are shown, and which aren't.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7268](https://linear.app/budibase/issue/BUDI-7268/relationship-picker-doesnt-show-all-rows-in-dropdown-selection)</sub>

**Comment by shogunpurple** [comment]
Due to 5000 row limit in SQL db:

https://docs.budibase.com/docs/query-rows#table
