### ISSUE TITLE
Correct scanning of the barcode should not require confirmation

### ISSUE THREAD

**Issue by KevMyst** [Budibase/budibase#11216]
Correct scanning of the barcode should not require confirmation.

1. Add an option to the control settings - "If code validation is correct, close the window"
2. Add to the control the option to clear the value in the scan window - marked in green on the screenshot.
3. Transfer the validation to the scan window - marked in red on the screenshot.
4. If the validation is not correct, change the color of the dot to red? - marked in blue on the screenshot

New functionality / question - I didn't find any action that could value the code, e.g.: ABCD|123|DEF - save the values to the context of the form in the appropriate fields:
field1: ABCD
field2: 123
field3:DEF

it is best to do it before saving, immediately after reading the code correctly, and then use the form validation action.

![image](https://github.com/Budibase/budibase/assets/6716949/6a4aa469-17a3-421e-8fe1-57a54c9482a3)

**Comment by melohagan** [comment]
Docs: https://docs.budibase.com/docs/barcodeqr-field
