### ISSUE TITLE
[BUDI-7274] Stopping the execution of the action on the button after the Update Field Value action

### ISSUE THREAD

**Issue by KevMyst** [Budibase/budibase#11217]
* Budibase version: 2.8.10

On the button, after adding 2 actions that copy the value from the barcode field, the "Save Row" action is not performed. Clicking the button again performs all actions.

![Linear-hosted image](https://github.com/Budibase/budibase/assets/6716949/6cfede88-2c10-4778-aa00-68390c52dbc2)
[Image source](https://github.com/Budibase/budibase/assets/6716949/6cfede88-2c10-4778-aa00-68390c52dbc2)

[https://github.com/Budibase/budibase/assets/6716949/3c11e552-8c5d-4748-9d39-56b02c7f387d](https://github.com/Budibase/budibase/assets/6716949/3c11e552-8c5d-4748-9d39-56b02c7f387d)

[My app-export-1689198884320.tar.gz](https://github.com/Budibase/budibase/files/12033108/My.app-export-1689198884320.tar.gz)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7274](https://linear.app/budibase/issue/BUDI-7274/stopping-the-execution-of-the-action-on-the-button-after-the-update)</sub>

**Comment by melohagan** [comment]
Hey @KevMyst 

I think this is because of the order of operations - the validate form action might be firing before the UI has updated the field values.

How about instead of updating the field values on click of the save button, you do it *On Change* of the Barcode field?

**Comment by KevMyst** [comment]
I'm all for it, but the codescanner control doesn't have an action property to do anything after changing the value.

![image](https://github.com/Budibase/budibase/assets/6716949/76a55ae9-66c8-4180-80f1-2733156de4df)

**Comment by melohagan** [comment]
The *On Change* setting has since been added to the Barcode/QR Scanner

![Screenshot 2023-11-10 at 16 28 06](https://github.com/Budibase/budibase/assets/101575380/17d9f6ec-6cbe-4369-82c4-967cbec468c4)
