### ISSUE TITLE
[BUDI-7270] Can't export apps with the encrypted option turned on.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11227]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: cloudbudi

**Describe the bug**
When using the encrypted app export option whilst using cloud it doesn't work and fires a 502 error. (A screenshot of the console and network tabs can be seen below;)

Self-host doesn't seem to be affected by this, I was able to export an encrypted app through the CLI just fine. (On the newest version 2.8.10)

**To Reproduce**

1. Go to a cloud account
2. Click on an
3. Go to settings
4. Go to export
5. Click export latest app
6. Make sure the encrypted toggle is on
7. Click export

**Expected behavior**
You should be allowed you export the app with a password and then import it elsewhere.

**Screenshots**

![Linear-hosted image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/23aff196-b586-47d3-bdeb-1714a348cfbe/94295e42-b059-43f6-8af6-22a9d4e2d794)
[Image source](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/23aff196-b586-47d3-bdeb-1714a348cfbe/94295e42-b059-43f6-8af6-22a9d4e2d794)

![Linear-hosted image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e3781d7f-2db2-4567-8d26-ff40254146b4/921a1386-0f0e-42f0-a51e-ea1d374f0339)
[Image source](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e3781d7f-2db2-4567-8d26-ff40254146b4/921a1386-0f0e-42f0-a51e-ea1d374f0339)

![Linear-hosted image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/2b95c23d-5a30-4b81-b794-09fa6ed7199f/490b1686-c036-48ca-a12a-97ede5bf7cbd)
[Image source](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/2b95c23d-5a30-4b81-b794-09fa6ed7199f/490b1686-c036-48ca-a12a-97ede5bf7cbd)

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Brave
* Version **v1.52.130**

**Additional Notes**

[https://github.com/Budibase/budibase/discussions/11224](https://github.com/Budibase/budibase/discussions/11224)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7270](https://linear.app/budibase/issue/BUDI-7270/cant-export-apps-with-the-encrypted-option-turned-on)</sub>

**Comment by mike12345567** [comment]
Doesn't appear to still be happening.
