### ISSUE TITLE
[BUDI-7271] Public API should throw 405: Method not allowed when appropriate

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#11228]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.8.10
  * App Version: 2.8.10

**Describe the bug**
I was using the `/search` endpoint for rows using the public API, and I was getting a **404** error with the cryptic message '*missing'*. 

After a bit I did realise I should have selected POST instead of GET. The correct error code **405** with the message *'Method not allowed*' would have alerted me to the root cause sooner.

**To Reproduce**

1. Make a GET request to the `/search` endpoint with otherwise valid credentials, table IDs, etc. [https://docs.budibase.com/reference/post_tables-tableid-rows-search](https://docs.budibase.com/reference/post_tables-tableid-rows-search)
2. See the cryptic message *'missing'*
3. Change the method to POST → now works fine.

**Expected behavior**
I would expect the public API to throw a `405: Method not allowed` when appropriate.

 

**Screenshots**

GET method cryptic error:

![Linear-hosted image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/16e8f3a7-5f7e-4fc6-a1e3-acd074364483/43f7731d-dff0-4357-a8d9-6cd0df0fa0f5)
[Image source](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/16e8f3a7-5f7e-4fc6-a1e3-acd074364483/43f7731d-dff0-4357-a8d9-6cd0df0fa0f5)
POST is fine as expected:

![Linear-hosted image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5e9df7f8-6d25-4e7c-a223-d5aa5fac236b/e9a50bcc-2013-43a7-b4a9-d55d5e56f385)
[Image source](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5e9df7f8-6d25-4e7c-a223-d5aa5fac236b/e9a50bcc-2013-43a7-b4a9-d55d5e56f385)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7271](https://linear.app/budibase/issue/BUDI-7271/public-api-should-throw-405-method-not-allowed-when-appropriate)</sub>

**Comment by shogunpurple** [comment]
More info here around allowedMethods in koa that may help us achieve this [https://github.com/ZijianHe/koa-router/tree/071b26489cb5c1886b2f89894a4633b18e9822de#routerallowedmethodsoptions--function](https://github.com/ZijianHe/koa-router/tree/071b26489cb5c1886b2f89894a4633b18e9822de#routerallowedmethodsoptions--function)
