### ISSUE TITLE
Stringfield - On Change Event broken

### ISSUE THREAD

**Issue by Den4ik1992** [Budibase/budibase#11234]
- **Budibase-Cloud:  ver. 2.8.10**

Hallo budibase community!

I would like to submit a form without clicking a button. Instead, I use the Enter key or Tab key on the keyboard 
after inputting data, which triggers the onchange event. 
Unfortunately, the current value is not being written to the database, but rather the previous value that was in the string field.

https://github.com/Budibase/budibase/assets/82113641/12c438b4-b7ef-4e4b-a9c3-ea61097abd7e

**simple on change action**

![image](https://github.com/Budibase/budibase/assets/82113641/44672c1d-0aa2-4281-8f37-51dbc780b4ae)

**validation rule to Save Row only if Stringfield = 6 digit number**

![image](https://github.com/Budibase/budibase/assets/82113641/9f6d1d41-ccef-4acd-9996-515267f048e2)
****

**Comment by melohagan** [comment]
Hey @Den4ik1992 

Can I see what your **Save Row** action looks like please?

I think you are making a common mistake of not using the `{{ Field Value }}` binding. There's more here: https://docs.budibase.com/docs/text-inputs#on-change

**Comment by Den4ik1992** [comment]
Thank you are the best!

I followed your tip and it works, i could have come up with it myself. 😒

![image](https://github.com/Budibase/budibase/assets/82113641/97f1587e-a9cc-4b0a-8223-2ce393e336bb)




Thread can be closed

**Comment by melohagan** [comment]
No problem, glad to help @Den4ik1992 I always prefer the easy fixes anyway! 😁
