### ISSUE TITLE
[BUDI-7278] Relationships no longer load in list for MySql database and updating record columns with relationships clear related records

### ISSUE THREAD

**Issue by sonisoft-cnanda** [Budibase/budibase#11233]
**Checklist**

* \[ X\] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Docker initiated via Budi CLI
  * Budibase Version: 2.8.1
  * App Version: 2.8.1

**Describe the bug**
I believe it was after creating another relationship (I am not sure if it was a many to many or a one to many) the relationships starting showing up oddly and errors starting arising when editing data.  The relationship list on the MySql database view will lock up the application for the browser, so I need to refresh the browser.

When I edit a record with a relationship (not the relationship id column or relationship column) it will clear the relationships on that record.  (See screenshot) It will also present with an error (see screenshot).

The error in the JS console looks like something is wrong with the tableName on one (or more) of the records for the relationships.

I am traveling right now and can't get the couchdb password/username so I can't see what the relationship data is at the moment.

**Expected behavior**

**Screenshots**

<img width="1648" alt="image" src="https://github.com/Budibase/budibase/assets/67545636/92052ac1-4148-44dd-bea4-165bb4187241">

<img width="1654" alt="image" src="https://github.com/Budibase/budibase/assets/67545636/71dceed7-f7d9-4022-bce2-98798939022e">

<img width="1659" alt="image" src="https://github.com/Budibase/budibase/assets/67545636/61155d6b-ed09-4708-8952-42190aeabae8">

<img width="1639" alt="image" src="https://github.com/Budibase/budibase/assets/67545636/0f260c86-f2ae-48fb-9fcd-c1c74d9b8a6f">

<img width="1920" alt="image" src="https://github.com/Budibase/budibase/assets/67545636/e651fc9d-16ee-4017-ae91-0ac28b824f57">

<img width="1920" alt="image" src="https://github.com/Budibase/budibase/assets/67545636/971c6909-1b09-409e-a1c1-649153b35368">

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7278](https://linear.app/budibase/issue/BUDI-7278/relationships-no-longer-load-in-list-for-mysql-database-and-updating)</sub>

**Comment by melohagan** [comment]
Related discussion: https://github.com/Budibase/budibase/discussions/11203#discussioncomment-6450088

**Comment by melohagan** [comment]
Hey @sonisoft-cnanda 

Your issue specifies **2.8.1**. Just in case could you update to **2.8.10** please

**Comment by sonisoft-cnanda** [comment]
> Hey @sonisoft-cnanda
> 
> Your issue specifies **2.8.1**. Just in case could you update to **2.8.10** please

Updated but I can’t login to the VM to restart the budibase app atm. Will update later today when I can restart BB..

thanks!

**Comment by sonisoft-cnanda** [comment]
> Hey @sonisoft-cnanda
> 
> Your issue specifies **2.8.1**. Just in case could you update to **2.8.10** please

Looks like the issue is persisting in 2.8.10, confirmed upgrade and checked relationships and still getting the same error and freezing.

**Comment by melohagan** [comment]
Thanks @sonisoft-cnanda 

Sorry to ask, but would you be able to upload those screenshots again? I have accidentally wiped them when I triggered one of our webhooks 😬

**Comment by sonisoft-cnanda** [comment]
> Thanks @sonisoft-cnanda
> 
> Sorry to ask, but would you be able to upload those screenshots again? I have accidentally wiped them when I triggered one of our webhooks 😬

No problem. I’ll have to do that in a couple hours tho due to meetings.  Thanks for your help!

**Comment by sonisoft-cnanda** [comment]
> Thanks @sonisoft-cnanda
> 
> Sorry to ask, but would you be able to upload those screenshots again? I have accidentally wiped them when I triggered one of our webhooks 😬

Re-added all those screenshots.  I have been looking through the code trying to find where that code is generated, but I am guessing it is outside the main codebase since I haven't been able to find where that code that is erroring is created.

**Comment by ab-cvg** [comment]
Same for me, at the same time as https://github.com/Budibase/budibase/issues/11398

**Comment by melohagan** [comment]
Going to close this one for the following reasons:

- "I am not sure if it was a many to many or a one to many"
- no app export
- likely an edge case bug that occurred when upgrading from 2.7 -> 2.8, but is now resolved
