### ISSUE TITLE
[BUDI-7350] Filter "equal" for numbers not working in data providers

### ISSUE THREAD

**Issue by SufiSR** [Budibase/budibase#11264]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image> 
  - Budibase Version: 2.8.10
  - App Version: 2.8.10

**Describe the bug**
Filter "EQUAL" on data providers does not work for numbers anymore after System Update to 2.8.10
The app version is irrelevant - it doesn't work on either on the old nor the updated.

**To Reproduce**
I created a datasource that picks up data from mysql with a query.
The schema is properly set (eg. text columns as text, number columns as numbers)
I created a data provider and a table. 
I choose my query as a data provider --> Result: Full table is shown, upon inspection of the response the data source returns the following json:

"data": [
        {
            "firstname": "bla",
            "lastname": "bla2",
            "my_date": "2021",
            "Paid": "154.02",
            "Unpaid": "179.20",
            "percentage_paid": "46.22"
        },
       etc.
]
When now applying the filter my_date equals value 2023 no results are returned.

**Expected behavior**
The Equal to Filter should work again

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 114.0.5735.199

**Additional context**
One can see that the response returns a list of json objects with all numbers in double quotes.
The filters properly identify the field as either text or number (they will provide different comparison options based on the type of field).

**Evil Workaround**: I changed the schema of the column from number to text and then created a new filter based on the text value. Works for now but not cool.

**What I tried to solve the issue**
Query: I explicitly casted the my_date as an integer.
Filter: I changed the filter to equal or more/less --> Results are properly shown
Filter: I changed the filter lastname equals value "bla2" --> Results are properly shown
Filter: I changed the filter Paid equals value 154.02 --> No Data
Filter I changed the filter my_date equals "2023" --> No Data
New Page: I created an entirely new page with my components and the error persists

<sub>[BUDI-7350](https://linear.app/budibase/issue/BUDI-7350/filter-equal-for-numbers-not-working-in-data-providers)</sub>

**Comment by melohagan** [comment]
Hey @SufiSR 

> I created a datasource that picks up data from mysql with a query.

Would you be able to provide the query that you are using in addition to the SQL schema (which you can grab within Budibase: [Troubleshooting SQL](https://docs.budibase.com/docs/troubleshooting-sql).

Also screenshots are very helpful!

**Comment by melohagan** [comment]
Thanks @SufiSR 

> One note that may be important for testing:
When playing around and changing the schema for the query (e.g. from text to number and vice versa) one must make sure to fully delete the filter and recreate it so that it picks up on the changed schema.

Probably related to this bug I raised the other day: https://github.com/Budibase/budibase/issues/11420
