### ISSUE TITLE
[BUDI-7298] Can't see Views attached to internal users table.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11271]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.8.10 
  * App Version: 2.8.10 

**Describe the bug**
When adding a view to the user table, there is no UI to delete it when compared to other Budibase internal tables.

The view does become available to select within a data provider in the design view. However you can't interact with the view once it has been created on the users table.

**To Reproduce**

1. Go to any app.
2. Click on the users table.
3. Add a view to the users table.
4. See that no views appear within the users table after adding.

**Expected behavior**
Similar UI for other Budibase internal tables were you are able to see views attached. From here you can then select the view to edit or delete them.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7298](https://linear.app/budibase/issue/BUDI-7298/cant-see-views-attached-to-internal-users-table)</sub>

**Comment by melohagan** [comment]
It is no longer possible to create views from the users table.
