### ISSUE TITLE
[BUDI-7304] REST queries using dynamic variables returning 400 "Connection is closed"

### ISSUE THREAD

**Issue by andz-bb** [Budibase/budibase#11285]
**Checklist**

* [X] I have searched Budibase discussions and GitHub issues to check if my issue already exists

**Hosting**

* Self
  * Method: dev stack
  * Budibase Version: 2.8.10
  * App Version: 2.8.10

**Describe the bug**
When running a query that uses a dynamic variable from another query, the response is always a 400. The message is "Connection is closed" - I guess this might be trying and failing to get the data from Redis.

**To Reproduce**
Steps to reproduce the behaviour:

1. create a REST query
2. run it and create a dynamic variable from the output
3. create a second REST query
4. use the dynamic variable from the first as a param/header/body
5. test the second query and see that it fails

**Expected behaviour**
The second query should run with data from the dynamic variable, or if that variable is not available it should give a better error.

**Screenshots**

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/78071f9e-5323-4b29-8b07-3125fd75b230/416874df-5944-4401-815d-9325930f14a6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC83ODA3MWY5ZS01MzIzLTRiMjktOGIwNy0zMTI1ZmQ3NWIyMzAvNDE2ODc0ZGYtNTk0NC00NDAxLTgxNWQtOTMyNTkzMGYxNGE2IiwiaWF0IjoxNjg5ODM3NDA4LCJleHAiOjE2ODk5MjM4MDh9.kD-dQLAa9a67G_h6SaYXAyIgrqMtE9ujVBaqb9jZmPg)

![Screenshot 2023-07-20 at 09.03.32.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ed2ade08-0a0f-4677-86cb-a64748d5bd2c/bf9167b0-b390-4530-98bf-e5d9a907b3cb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lZDJhZGUwOC0wYTBmLTQ2NzctODZjYi1hNjQ3NDhkNWJkMmMvYmY5MTY3YjAtYjM5MC00NTMwLTk4YmYtZTVkOWE5MDdiM2NiIiwiaWF0IjoxNjg5ODM3NDA4LCJleHAiOjE2ODk5MjM4MDh9.CnlFrGM19T3aPkjYktmIqfLG_xDQkpSv0ujNbUCrcDU)

**App Export**

[REST TEST-export-1689836520961.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5e71731b-7c80-435d-b48e-88d74ec4ff98/5e66b4a9-66a5-49bd-ac91-1f36abec8588?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC81ZTcxNzMxYi03YzgwLTQzNWQtYjQ4ZS04OGQ3NGVjNGZmOTgvNWU2NmI0YTktNjZhNS00OWJkLWFjOTEtMWYzNmFiZWM4NTg4IiwiaWF0IjoxNjg5ODM3NDA4LCJleHAiOjE2ODk5MjM4MDh9.NIJkUn6nwwE030fcupWXJ43a7t0l9cQK6EV5m7Uwavg)

**Context**

raised in this discussion, appears to be a recent regression: [https://github.com/Budibase/budibase/discussions/11261](https://github.com/Budibase/budibase/discussions/11261)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7304](https://linear.app/budibase/issue/BUDI-7304/rest-queries-using-dynamic-variables-returning-400-connection-is)</sub>

**Comment by buanet** [comment]
Hi, looks like this is still/ again an issue. See #11261 
Thx.

Regards,
André

**Comment by TheDreamFactoryNZ** [comment]
> Hi, looks like this is still/ again an issue. See #11261 Thx.
> 
> Regards, André

Looks like this is. It's been a very long evening debugging things only to realise the old bug is probably why my queries are failing.

![image](https://github.com/user-attachments/assets/04b2d23a-29c5-468f-a749-493c5c630894)

![image](https://github.com/user-attachments/assets/fd619e55-3789-4959-8c48-7cbd27e15b57)

![image](https://github.com/user-attachments/assets/7295935a-d63b-432b-a6d9-15863952d21e)
