### ISSUE TITLE
Preview button opens up the wrong app

### ISSUE THREAD

**Issue by arladmin** [Budibase/budibase#1129]
**Describe the bug**
From within an app in the builder, clicking on the preview opens up the wrong app. 

**To Reproduce**
1. In the builder, start editing an app, say App 2.
2. Click on Preview button.
3. App opens up in the browser. But the opened app is not App 2. It's another app.

**Expected behavior**
The app from within which the Preview button is being clicked should open up in the Browser.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] 0.7.8

**Additional context**

**Comment by mike12345567** [comment]
There has been a lot of changes in the latest release around this, I am currently unable to re-produce this behaviour (with the new release), if it shows up again in the latest release please re-open this issue.
