### ISSUE TITLE
[BUDI-7313] Self host - caching of assets isn't being done were cloud is

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11307]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.8.10
  * App Version: 2.8.10

**Describe the bug**
When pages are opened, forms are clicked it reloads the same assets constantly. (Slowing down load times a little.) However, whenever using Budibase cloud, it pulls in cache versions of these assets.

**To Reproduce**

1. Go to any app within a self-host setup
2. Use one of the templates or create a form
3. Inspect element.
4. Go to the network tab and see assets being pulled in constantly on form load or page loads.

**Expected behavior**
Cache versions of these assets to be used instead, similar to the approach used for cloud.

**Screenshots**
Cloud

![cloud-network.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/49f622d2-79e0-489d-81cc-ab38794854b7/6570f7a3-9e7e-4d5b-a829-c457eef8e7f1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC80OWY2MjJkMi03OWUwLTQ4OWQtODFjYy1hYjM4Nzk0ODU0YjcvNjU3MGY3YTMtOWU3ZS00ZDViLWE4MjktYzQ1N2VlZjhlN2YxIiwiaWF0IjoxNjg5OTI2MzYxLCJleHAiOjE2OTAwMTI3NjF9.eHe4-gqtaVQ8inbXEZg82AYugGHDCMsdVCmvzExe\_-c)

Self-host

![self-host-netwrok.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/a075ce1f-96f7-4bd4-9e8c-6f517411df43/6e56dbea-4054-41e9-9e9d-c851f5b1b083?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hMDc1Y2UxZi05NmY3LTRiZDQtOWU4Yy02ZjUxNzQxMWRmNDMvNmU1NmRiZWEtNDA1NC00MWU5LTllOWQtYzg1MWY1YjFiMDgzIiwiaWF0IjoxNjg5OTI2MzYxLCJleHAiOjE2OTAwMTI3NjF9.SCUnvAjQ_JDTljFVKQRlQGbOQjkFEr383nQf2rcWWEY)

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Brave
* Version **v1.56.9**

Related Discussion:

[https://github.com/Budibase/budibase/discussions/11270](https://github.com/Budibase/budibase/discussions/11270)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7313](https://linear.app/budibase/issue/BUDI-7313/self-host-caching-of-assets-isnt-being-done-were-cloud-is)</sub>

**Comment by aptkingston** [comment]
Just to point out that the only difference between those 2 screenshots appears to be the fronts (source sans pro), which are cached in the first one and not in the second.

Caching is a heavily browser dependent feature, and I'm not sure there's any work for us to do here. Checking myself in a local dev environment, everything is cached (including CSS stylesheets which are not cached in either of the screenshots above):
![image](https://github.com/Budibase/budibase/assets/9075550/b76af19e-30c6-45b7-9035-d5d0b8f6969b)

In cloud, Cloudflare is in control of what's cached, but for self host we don't explicitly disable caching for anything via headers, so it should be entirely up to the users browser and their settings.

**Comment by tmdoit** [comment]
I've checked it in Brave, Edge and Firefox - same issue, each time assets are downloaded, also why HTTP/2 is not used?
It impacts UX.
