### ISSUE TITLE
[BUDI-7343] Issue with latest version number

### ISSUE THREAD

**Issue by hawkinsjon** [Budibase/budibase#11353]
**Hosting**

- Self
  - Method: Digital Ocean
  - Budibase Version: 2.8.22

**Describe the bug**
When updating to version 2.8.22 I noticed the new version was shown as .8.22 (missing the 2)

**Screenshots**
Before updating:
<img width="459" alt="Screenshot 2023-07-25 at 10 11 10 AM" src="https://github.com/Budibase/budibase/assets/3512179/44c16172-e171-4e47-8b49-23d84fcbdf08">

After updating:
<img width="891" alt="Screenshot 2023-07-25 at 10 13 42 AM" src="https://github.com/Budibase/budibase/assets/3512179/af4e9b71-7822-48d0-bd06-c2837fda9337">

<sub>[BUDI-7343](https://linear.app/budibase/issue/BUDI-7343/issue-with-latest-version-number)</sub>

**Comment by aptkingston** [comment]
Thanks @hawkinsjon! We removed the `v` prefix from our release versions on GitHub and obviously didn't update the code which slices off the first character. Thanks for letting us know.
