### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:5432

### ISSUE THREAD

**Issue by shaikhashraf709** [Budibase/budibase#1136]
### Error that occurred when using the budibase builder:
```
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```
### Operating System Information:
---

Budibase Builder 0.7.8
Electron 10.1.3
win32 6.1.7601
Locale: en-US

**Comment by shogunpurple** [comment]
Will be resolved in this weeks release
