### ISSUE TITLE
[BUDI-7344] Invitation Emails are being sent blank without the Template

### ISSUE THREAD

**Issue by alican92** [Budibase/budibase#11375]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Docker Self Hosted
  * Budibase Version: 2.8.14
  * App Version: <version> 
* Cloud
  * Tenant ID: <tenantId> 

**Describe the bug**
Emails and Invitations worked perfect for a long time while I self hosted Budibase, then a few days ago I noticed that when we send an Invitation email it sends to the user blank. When checking the Email Templates I noticed that the Preview doesn't work at all

**To Reproduce**

1. Go to 'Settings, Email'
2. Click on 'Invitation Email'
3. Scroll down to 'Preview Panel'

**Expected behavior**
The Preview panel should show a basic empty template for the Email Template, instead it's showing "{\[ contents }}'

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/a5a3dee8-3639-4854-ab3f-f5185b4ddc9c/c85eb376-4984-4808-af92-c91f5ac99a8e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hNWEzZGVlOC0zNjM5LTQ4NTQtYWIzZi1mNTE4NWI0ZGRjOWMvYzg1ZWIzNzYtNDk4NC00ODA4LWFmOTItYzkxZjVhYzk5YThlIiwiaWF0IjoxNjkwODk2ODkwLCJleHAiOjE2OTA5ODMyOTB9.eoJN4GEVMLDQzp5bh5SulchMVzuc4n_EShYlgd2dcgw)

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

* OS: Windows 11
* Browser \[e.g. chrome, safari\]: Chrome, Edge
* Version \[e.g. 22\]

**Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7344](https://linear.app/budibase/issue/BUDI-7344/invitation-emails-are-being-sent-blank-without-the-template)</sub>

**Comment by andz-bb** [comment]
hi @alican92, is this still happening for you on Budibase 2.9? If so, could you please send through the HTML for your `Base format` and `User invitation` templates? I haven't been able to recreate the issue on my end so any details you can provide will be very helpful. Thanks!
