### ISSUE TITLE
Table blocks always returns "no rows found" even data already exist

### ISSUE THREAD

**Issue by thanhpd56** [Budibase/budibase#11374]
### Discussed in https://github.com/Budibase/budibase/discussions/11344

<div type='discussions-op-text'>

<sup>Originally posted by **thanhpd56** July 23, 2023</sup>
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: k8s
  - Budibase v2.8.10
  - App Version: v2.8.10
  - Tenant ID: self hosted

**Describe the bug**
Try to display data of mysql table by table block component, but it always shows "no rows found"

**To Reproduce**
1. In the data connect 1 table of mysql
2. Click create new screen with list view (table block default)
3. Watch the data

**Expected behavior**
The table always show "no rows found". I have tried to connect several tables but the results are the same.
**Screenshots**
Banner table:
<img width="901" alt="image" src="https://github.com/Budibase/budibase/assets/3794898/208e8109-e29f-4d5a-a577-9791bcd307e0">
Banner screen:
<img width="1398" alt="image" src="https://github.com/Budibase/budibase/assets/3794898/0f29128b-92c0-4062-8f75-e7ef24bcd842">

  
**App Export**

**Desktop (please complete the following information):**

**Additional context**
If I change to grid view component, then data is show up as nornal.
</div>

**Comment by aptkingston** [comment]
@thanhpd56 I have already converted this into a discussion in our help forum. Please do not create duplicates.

This looks like an issue with your hosting setup, not a bug with the platform. Please be patient - we don't have the capacity to quickly investigate complicated hosting issues for all free-tier customers, as I'm sure you can appreciate.
