### ISSUE TITLE
Problems with one-to-many relationship

### ISSUE THREAD

**Issue by udsonassis** [Budibase/budibase#11386]
I'm having the following problem with one to many relationship

![image](https://github.com/Budibase/budibase/assets/4209678/d80cd328-3ba2-4546-8bff-2d37e90fdfc6)

I have a User table with the following fields:
id, name, phone

Another Menu table with the following fields:
id, user_id, description

1 - When I make the relationship one to many from User to Menu, the Users page, lists only one user if the order is ASC.

![image](https://github.com/Budibase/budibase/assets/4209678/38478375-ed2b-434d-8fc0-b975d11300f5)

![image](https://github.com/Budibase/budibase/assets/4209678/a4f9de07-b596-4ca4-ae6a-62909e8045d6)

2 - On the Menus page, the relationship lists only one record.
![image](https://github.com/Budibase/budibase/assets/4209678/8ff1eb77-49b9-4567-8a0b-6439bf4bcd07)

SelfHosted via docker
V 2.8.14

**Comment by melohagan** [comment]
Hey @udsonassis 

 - How many rows are in your Users table? 
 - How many rows are in your Menus table?

**Comment by udsonassis** [comment]
@melohagan
A table menu has 99 lines, user has 4 lines.

If you want I can share the project along with the database.

**Comment by udsonassis** [comment]
@melohagan

Where do I share it with you? Discord, email?

**Comment by melohagan** [comment]
You can send a download link for the app export to: support@budibase.com
