### ISSUE TITLE
[BUDI-7345] External table doesn't load all rows

### ISSUE THREAD

**Issue by giacomouberti** [Budibase/budibase#11398]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists
- [x] I have checked for errors in console, bbworker, bbapps and couchdb-service logs
- [x] I have checked the external data source and the table is working fine
- [x] If I fetch the whole table with an SQL Query all rows are available

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.8.14
  - App Version: 2.8.14

**Describe the bug**
I have an external PostgreSql database as data source with 11 tables but just one doesn't load all rows when accessed from the backend and the issue is replicated also when the table is used as a relationship. In the UI, fox example, it's not possible to see al rows and therefore select the desired one.

The table has only 26 rows so it doesn't appear to be an issue and the number of rows displayed varies, sometimes are just 5 sometimes up to 16. When loaded none of the container logs shows any sign of what might be the problem neither I get en error in console.

I have tried to change the primary column, refetch tables from database but it nothing has successed not even restarting docker 

**Expected behavior**
I expect all table's rows to load

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 114.0.5735.248

<sub>[BUDI-7345](https://linear.app/budibase/issue/BUDI-7345/external-table-doesnt-load-all-rows)</sub>

**Comment by melohagan** [comment]
Hey @giacomouberti 

Would you be able to share the SQL schema (CREATE script) for the problematic table please?

Also just to rule out any problems with the particular app instance, could you create a new app and add the datasource to see if the problem still exists in the new app?

**Comment by mikey0000** [comment]
I've also got this problem of a max 5000 limit on data providers regardless of the limit I set, so using stat cards with a row.length doesn't work as expected

**Comment by semanticdreamer** [comment]
@melohagan exact same problem for me, also on PostgreSQL.

One additional observation: the amount of rows returned slightly differs when changing the sort criteria (e.g. from default to another column). But also then, not all rows are returned—for both, bb backend and when used in components.

**Comment by melohagan** [comment]
> Maybe related with #5753 ?
> 
> I have also this problem, after adding multiple one to many relations in Budibase, on a MySQL DB.
> 
> Table has 59 entries, only 10 are displayed after adding a 4th o2m relation, and clicking on the table takes now about 5 seconds to display the (cut) content. Delete the relation restores complete view and speed.

Adding a lot of relationships to one table is currently an issue because it loads the rows from the linked tables, which could hit the 5000 limit pretty easily if multiple relationships are involved.

More context here: https://github.com/Budibase/budibase/issues/8558
