### ISSUE TITLE
[BUDI-7338] Add custom roles to the preview options in the selectable dropdown.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11402]
When a custom role is created, this should be added to the preview selectable dropdown options, so that you can easily view by the newly create roles permissions.

![256738524-4896830b-b2f4-470e-9aeb-09374a998483.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/d0cc5701-bdfc-4307-bc2b-d654ba4d277f/d707b641-ab6d-4659-9419-b8e0697e41db?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9kMGNjNTcwMS1iZGZjLTQzMDctYmMyYi1kNjU0YmE0ZDI3N2YvZDcwN2I2NDEtYWI2ZC00NjU5LTk0MTktYjhlMDY5N2U0MWRiIiwiaWF0IjoxNjkwNzk4NTk2LCJleHAiOjE2OTA4ODQ5OTZ9.n8JnoVvR8Zw9GjD5dC3nTeexMj4SE3BN6IlFXyo_B14)

Currently this only takes in the default roles and doesn't account for custom created roles. Meaning the only way to test, is to publish and login with an account that has the assigned custom role.

Related discussion; [https://github.com/Budibase/budibase/discussions/11389](https://github.com/Budibase/budibase/discussions/11389)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7338](https://linear.app/budibase/issue/BUDI-7338/add-custom-roles-to-the-preview-options-in-the-selectable-dropdown)</sub>

**Comment by melohagan** [comment]
![Screenshot 2023-10-13 at 10 28 51](https://github.com/Budibase/budibase/assets/101575380/6af62c96-2e76-46b8-9196-648738a07fb9)

This one has been fixed!
