### ISSUE TITLE
[BUDI-7362] Expose global Binding which Theme is in use

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#11409]
a global binding , possibly under Device, which will tell us which theme is in use to adjust coloring with conditionals

<sub>[BUDI-7362](https://linear.app/budibase/issue/BUDI-7362/expose-global-binding-which-theme-is-in-use)</sub>

**Comment by deanhannigan** [comment]
PR [https://github.com/Budibase/budibase/pull/11617](https://github.com/Budibase/budibase/pull/11617)

**Comment by melohagan** [comment]
There is a whole section for bindings, so a page could be created in there for the global bindings
