### ISSUE TITLE
[BUDI-7339] Automation fails to run when loop text input list has a single value

### ISSUE THREAD

**Issue by zedascouves** [Budibase/budibase#11405]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: valis

**Describe the bug**
In an automation, when looping through a text string, if there's only one element in the list, the automation doesn't run, showing the error: `[object Object]`. In the browser console, we can see the following error:

```
[Builder] HTTP 500 on POST:https://[tenant].budibase.app/api/automations/au_e1af84228cf54a55856b5debf5b76c39/test
value.split is not a function
```

**To Reproduce**
1. Create an automation with a text input
2. Add an action with a loop of input type "string"
3. Set the "Binding / Value" to `{{ trigger.fields.[text_input_field] }}`
4. Test the automation with a single value in the text input
5. See error

**Expected behavior**
While the expected input list should be separated by commas, if the list has a single value and no commas, the loop should still iterate that single time..

<sub>[BUDI-7339](https://linear.app/budibase/issue/BUDI-7339/automation-fails-to-run-when-loop-text-input-list-has-a-single-value)</sub>

**Comment by melohagan** [comment]
Could not reproduce!
