### ISSUE TITLE
Cancel Button doesn't work 

### ISSUE THREAD

**Issue by shynes** [Budibase/budibase#1141]
**Describe the bug**
https://share.getcloudapp.com/X6u98Exp

**To Reproduce**
1. Go to Deploy > Add Webhook, the popup has a cancel button, but it does not work.

**Comment by RichardGrant-93** [comment]
Unable to reproduce. Please provide more information.

Could not find "Add Webhook" but i did find "View Webhook". Please provide more information if this bug is still active. See below for my testing. https://screencast-o-matic.com/watch/crnr1ASWOD
