### ISSUE TITLE
[BUDI-7346] Not able to connect to Postgres schema with a hyphen

### ISSUE THREAD

**Issue by samirotiv** [Budibase/budibase#11410]
**Checklist**

* \[ X\] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Docker Compose
  * Budibase Version: 2.8.10
  * App Version: N/A

**Describe the bug**
I have a Postgres database with a public schema and multiple other schemas. The other schemas have a hyphen in their name.

* If I try writing the name in the schema name, it gives me a syntax error
* If I try escaping with double quotes, it returns an empty list of tables (same result as a bogus schema name)
* If I try escaping with single quotes, it returns a 502 error
* Escaping hyphens with backslashes doesn't work either

The tables from the public schema are working fine. I have triple checked the name of the other schema.

**To Reproduce**
Create a Postgres database with a schema called `tenant_895d98b9-8b75-4021-be05-94124b742a53` and a few dummy tables in it. Connect to Budibase and try clicking on "Fetch Tables".

**Expected behavior**
I expect that the tables

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/55b86cea-3a66-4c4f-9dc1-85ec02f05e6f/5d5a67b7-64d4-41e5-9c13-eed263a25762?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC81NWI4NmNlYS0zYTY2LTRjNGYtOWRjMS04NWVjMDJmMDVlNmYvNWQ1YTY3YjctNjRkNC00MWU1LTljMTMtZWVkMjYzYTI1NzYyIiwiaWF0IjoxNjkwODk2ODk0LCJleHAiOjE2OTA5ODMyOTR9.YDcWe8wtqVYwHMdZ6icsczqWsZHbv3G8QpIHyVGlYuY)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/01e7d8e3-ad19-41e2-996e-040736ceeedc/8af49d01-c6bf-4b9d-af37-662f5d1f94b5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8wMWU3ZDhlMy1hZDE5LTQxZTItOTk2ZS0wNDA3MzZjZWVlZGMvOGFmNDlkMDEtYzZiZi00YjlkLWFmMzctNjYyZjVkMWY5NGI1IiwiaWF0IjoxNjkwODk2ODk0LCJleHAiOjE2OTA5ODMyOTR9.ikgjYwzZauebrrFrWcYzMWzH0phvhvSetx0Z8E9MHXA)

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Chrome
* Version 115

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7346](https://linear.app/budibase/issue/BUDI-7346/not-able-to-connect-to-postgres-schema-with-a-hyphen)</sub>

**Comment by samirotiv** [comment]
Hi @mike12345567 I really appreciate the quick MR and fix. 

This is a make-or-break reason for us to use Budibase or move to another platform. 

When can we expect a release that we can atleast use to test with? That will help me take a decision for my organization.

**Comment by mike12345567** [comment]
This should be released now @samirotiv.
