### ISSUE TITLE
Feature request: Ability to set user status (active/inactive/pending)

### ISSUE THREAD

**Issue by arladmin** [Budibase/budibase#1143]
Currently, the only way to remove a user is to delete it from the Users table.
This is a highly undesirable action and is almost never followed in practice.

Usually, when removing a user, the desired outcome is to:
1. Disable login access for the user
2. Mark User as disabled, so that appropriate Screens in the app can maintain their filtered data (e.g. only Active Users)
3. A user's activity within an app is rarely required to be deleted. All the records (rows) created/edited by the user and linked to them should not lose any information just because the user's active status has changed.

**Comment by mike12345567** [comment]
Hi @arladmin - this is a great point, having the ability to decide between deletion and de-activation is a useful feature, I've implemented this [here](https://github.com/Budibase/budibase/pull/1152) - it will be available in the next release.

**Comment by mike12345567** [comment]
Hi @arladmin - going to close this issue as this feature has been implemented in the release occurring today - can be seen as such:
![image](https://user-images.githubusercontent.com/4407001/109139637-a1793c00-7753-11eb-97eb-a1c98fb91422.png)

This is currently a dropdown of active or inactive, to allow for further options in the future when they make sense.
