### ISSUE TITLE
[BUDI-7360] pulling with podman

### ISSUE THREAD

**Issue by avnav88** [Budibase/budibase#11442]
**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: latest

**Describe the bug**
```Error: choosing an image from manifest list docker://budibase/budibase:latest: no image found in image index for architecture amd64, variant "", OS linux
```
can't pull on an x86_64 server (debian 11) in ec2

<sub>[BUDI-7360](https://linear.app/budibase/issue/BUDI-7360/pulling-with-podman)</sub>

**Comment by KamillaPup** [comment]
I am having this same issue too:
```docker pull budibase/budibase
Using default tag: latest
latest: Pulling from budibase/budibase
no matching manifest for linux/amd64 in the manifest list entries```

**Comment by jkirkpatrick** [comment]
v2.9.5 did not fix podman issue

```bash
$ podman pull registry.hub.docker.com/budibase/budibase:latest

Trying to pull registry.hub.docker.com/budibase/budibase:latest...
Error: choosing an image from manifest list docker://registry.hub.docker.com/budibase/budibase:latest: no image found in image index for architecture amd64, variant "", OS linux
```

**Comment by tavrez** [comment]
looks like amd64 versions are removed, they were there 4 hours after they
pushed the new version

**Comment by mike12345567** [comment]
Hi all, we are actively looking into this - hopefully have a solution soon.

**Comment by mike12345567** [comment]
Hi all - `2.9.18` has been released with both ARM and AMD images attached.

https://hub.docker.com/layers/budibase/budibase/2.9.18/images/sha256-2ec6142e6eabc33a8ccf473eded79875459d21f6fa7bca8f89113def29a757ec?context=explore
