### ISSUE TITLE
Connect Airtable when API being depreciated

### ISSUE THREAD

**Issue by ajkjajkj** [Budibase/budibase#11443]
Excuse me if I am jumping the gun, but I am trying to test out Budibase to build an internal front end for Airtable. Im running into an issue right away trying to natively connect Airtable. Budibase is wanting to use the Airtable API, but this is being depreciated and will stop working in January of 24  (and I'm not sure you can even get a new key) .  It needs OAuth or a Personal Access Token to connect. Is this possible? How?

**Comment by melohagan** [comment]
Hey @ajkjajkj 

Thanks for raising - we are aware! https://github.com/Budibase/budibase/issues/10557
