### ISSUE TITLE
Add preferred camera to QR scanner configuration

### ISSUE THREAD

**Issue by zedascouves** [Budibase/budibase#11459]
**Describe the feature request**

Currently, the default camera for the QR code scanner component is the "environment". While this usually works without any issues on desk machines, it would be convenient to allow some kind of configuration, so that mobile devices can use both back and front cameras.

I propose a setting in the component configuration, where the developer can choose the preferred camera. If the preferred option is not available, it should default back to the "environment" option.

This would also be changeable in the component's "conditions" tab, so the camera could be switched at runtime.

**Reference**
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**More info**
I've identified 3 possible files where the change should be made:

- packages/client/manifest.json
```
       ...{ "label": "Custom", "value": "custom" }
        ]
      },
{"type": "select",
        "label": "Prefered camera",
        "key": "preferedCamera",
        "defaultValue": "",
        "options": [
          {
            "label": "Front",
            "value": "user"
          },
          {
            "label": "Back",
            "value": "environment"
          }
        ]},
      {
        "type": "number",
        "label": "Sound frequency (Hz)",
        "key": "customFrequency",...
```
- packages/client/src/components/app/forms/CodeScanner.svelte
```
export let preferedCamera = "environment"
let cameraSetting = { facingMode: preferedCamera }
```
- packages/client/src/components/app/forms/CodeScannerField.svelte

```
export let preferedCamera 
{#if fieldState}
    <CodeScanner
      value={fieldState.value}
      on:change={handleUpdate}
      disabled={fieldState.disabled}
      {allowManualEntry}
      scanButtonText={scanText}
      {beepOnScan}
      {beepFrequency}
      {customFrequency}
      {preferedCamera}
    />
  {/if}
```

**Comment by melohagan** [comment]
Thanks for the contribution @zedascouves ❤️
