### ISSUE TITLE
[BUDI-7372] Problem in creating the Dev Environment according to the document

### ISSUE THREAD

**Issue by liem-td** [Budibase/budibase#11464]
**Checklist**
- [*] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - 
  - Budibase Version: 2.8.10
  - App Version: 2.8.10

**Describe the bug**
when i run the "**yarn setup**" command,no docker is running.
also after that, i run "**yarn run dev:docker**" and run the dockers, but when the "**worker**" and "**server**" run, both issue the following error:
build-bbworker          | yarn run v1.22.19
build-bbworker          | $ node dist/index.js
build-bbworker          | internal/modules/cjs/loader.js:934
build-bbworker          |   throw err;
build-bbworker          |   ^
build-bbworker          | 
build-bbworker          | Error: Cannot find module './types'
build-bbworker          | Require stack:
build-bbworker          | - /app/node_modules/@budibase/pro/dist/index.js
build-bbworker          | - /app/dist/index.js
build-bbworker          |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
build-bbworker          |     at Function.Module._load (internal/modules/cjs/loader.js:774:27)
build-bbworker          |     at Module.require (internal/modules/cjs/loader.js:1003:19)
build-bbworker          |     at require (internal/modules/cjs/helpers.js:107:18)
build-bbworker          |     at Object.<anonymous> (/app/node_modules/@budibase/pro/dist/index.js:1:193)
build-bbworker          |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
build-bbworker          |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
build-bbworker          |     at Module.load (internal/modules/cjs/loader.js:979:32)
build-bbworker          |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
build-bbworker          |     at Module.require (internal/modules/cjs/loader.js:1003:19)
build-bbworker          |     at require (internal/modules/cjs/helpers.js:107:18)
build-bbworker          |     at Object.<anonymous> (/app/dist/index.js:108466:19)
build-bbworker          |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
build-bbworker          |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
build-bbworker          |     at Module.load (internal/modules/cjs/loader.js:979:32)
build-bbworker          |     at Function.Module._load (internal/modules/cjs/loader.js:819:12) {
build-bbworker          |   code: 'MODULE_NOT_FOUND',
build-bbworker          |   requireStack: [
build-bbworker          |     '/app/node_modules/@budibase/pro/dist/index.js',
build-bbworker          |     '/app/dist/index.js'
build-bbworker          |   ]
build-bbworker          | }
build-bbworker          | error Command failed with exit code 1.
build-bbworker          | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
build-bbworker exited with code 1
build-bbapps            | internal/modules/cjs/loader.js:934
build-bbapps            |   throw err;
build-bbapps            |   ^
build-bbapps            | 
build-bbapps            | Error: Cannot find module './types'
build-bbapps            | Require stack:
build-bbapps            | - /app/node_modules/@budibase/pro/dist/index.js
build-bbapps            | - /app/dist/index.js
build-bbapps            |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
build-bbapps            |     at Function.Module._load (internal/modules/cjs/loader.js:774:27)
build-bbapps            |     at Module.require (internal/modules/cjs/loader.js:1003:19)
build-bbapps            |     at require (internal/modules/cjs/helpers.js:107:18)
build-bbapps            |     at Object.<anonymous> (/app/node_modules/@budibase/pro/dist/index.js:1:193)
build-bbapps            |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
build-bbapps            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
build-bbapps            |     at Module.load (internal/modules/cjs/loader.js:979:32)
build-bbapps            |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
build-bbapps            |     at Module.require (internal/modules/cjs/loader.js:1003:19)
build-bbapps            |     at require (internal/modules/cjs/helpers.js:107:18)
build-bbapps            |     at src/utilities/global.ts (/app/dist/index.js:133371:18)
build-bbapps            |     at __init (/app/dist/index.js:9:59)
build-bbapps            |     at src/middleware/currentapp.ts (/app/dist/index.js:133397:5)
build-bbapps            |     at __init (/app/dist/index.js:9:59)
build-bbapps            |     at src/api/index.ts (/app/dist/index.js:169351:5) {
build-bbapps            |   code: 'MODULE_NOT_FOUND',
build-bbapps            |   requireStack: [
build-bbapps            |     '/app/node_modules/@budibase/pro/dist/index.js',
build-bbapps            |     '/app/dist/index.js'
build-bbapps            |   ]
build-bbapps            | }
build-bbapps            | error Command failed with exit code 1.
build-bbapps            | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser chrome
 - node v14
 - alpine sysroot
 - yarn 1.22.19

<sub>[BUDI-7372](https://linear.app/budibase/issue/BUDI-7372/problem-in-creating-the-dev-environment-according-to-the-document)</sub>

**Comment by diogenesbrussels** [comment]
I have similar issues, unsuccessful on my Win11 with WSL2 (which runs well my regular docker compose and plugins versions) and also buggy on a fresh Debian 12 install.

Which node version to use?
Dev setup docs
![image](https://github.com/Budibase/budibase/assets/91942877/adaf15a7-6b69-4ded-a88a-8eda0803239d)
package.json
![image](https://github.com/Budibase/budibase/assets/91942877/ef779103-b351-4541-8ea8-438e70efd63b)
