### ISSUE TITLE
The Save Row action in On CHange of a field works every other time saving previous value of the field.

### ISSUE THREAD

**Issue by lukuser** [Budibase/budibase#11475]
Version 2.9.8 (and 2.7.33)
Self Hosted: Azure ACI
Database: SQL Server

Issue:
The Save Row action in On Change of a field works every other time saving previous value of the field.

To Reproduce
I have a form where I want each field to save to db as soon as it's updated. So in "On change" of each field I add action "Save Row". When I preview and modify value (let's say from "A" to "B") and tab out., I see the confirmation msg "Row saved" but the db doesn't get updated (stays as "A"). At this time in the field visible on the form I still see "B". I try again and change value from "B" to "C" and tab out again. I see the "Row Saved" again, but this time the whole form flashes (reloads) and the value in the box changes back to "B". The database also gets updated to "B". So I get to save only every second change and only to the value of the previous change.
The Save Row data source is the form, not the repeater above the form (if I try to set the ds to repeater, the db doesn't get updated at all - no matter how many times I change the value).

**Comment by avivkri** [comment]
Hello @lukuser,

As answered in the Discussions:
You might want to use the special binding `{{ Field Value }}` to refer to the current value of the field inside "On change" actions, as explained in the documentation here.
https://docs.budibase.com/docs/text-inputs#on-change

**Comment by melohagan** [comment]
Thanks @avivkri ! That is correct.

Regardless, I'm going to close this issue as it has not followed the bug template.
