### ISSUE TITLE
[BUDI-7375] Relationship picker incorrectly renders selections, and not all records show in the dropdown

### ISSUE THREAD

**Issue by kpturner** [Budibase/budibase#11478]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: monito

**Describe the bug**
A relationship picker does not render selections properly, and does not provide all the available rows for selection

**To Reproduce**
Created a relationship between two simple tables - `country` and `currency`.  A `country` can have multiple `currency` records associated with it. The data is held in a `country_currency` table that just contains the primary key of `country` and the primary key of `currency`.  The data is correctly rendered in the grid in the "data" section of the designer - for example:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/25437d62-e8f8-42f6-bc9a-996ab9bb7d40/5d16af49-d7b5-41c8-992b-a5f38b738dae?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8yNTQzN2Q2Mi1lOGY4LTQyZjYtYmM5YS05OTZhYjliYjdkNDAvNWQxNmFmNDktZDdiNS00MWM4LTk5MmItYTVmMzhiNzM4ZGFlIiwiaWF0IjoxNjkxNTcyMTU5LCJleHAiOjE2OTE2NTg1NTl9.VGqQDQqK3M9uCBtx2XnVSVFdeWZ1cLBatM7kYADMdnA)

But within the application where a relationship picker is used, `USD` shows as `%5B'USD'%5D`

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ffeed756-9659-4f79-b624-32020b7f1d84/3713941c-b7b2-4306-9e36-d8a14d4ddb95?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9mZmVlZDc1Ni05NjU5LTRmNzktYjYyNC0zMjAyMGI3ZjFkODQvMzcxMzk0MWMtYjdiMi00MzA2LTllMzYtZDhhMTRkNGRkYjk1IiwiaWF0IjoxNjkxNTcyMTU5LCJleHAiOjE2OTE2NTg1NTl9.lXyx79JmZiY0VOtI1Crbr1ZCtMr_NvPuO7qiJmHayX8)

Furthermore when you use the picker to choose other currencies, only a handful of the total records appear in the dropdown.

**Expected behavior**
All selections should be rendered properly and all available records should appear in the relationship picker.

**Screenshots**
See above

**App Export**
I don't think I can, because the export would contain the secure credentials to the data source, and without the data source, there would be no data to test with.  I am more concerned about what it is about the data that could cause this, as it looks completely normal in the DB and is handled correctly by the "data" section of the designer.

What I can do is simply send the entire postgres schema via email if need be.  If it is data related that would help diagnosis.  

**Desktop (please complete the following information):**

* OS: iOS (mac)
* Browser Chrome
* Version 115.0.5790.114 (Official Build) (x86_64)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7375](https://linear.app/budibase/issue/BUDI-7375/relationship-picker-incorrectly-renders-selections-and-not-all-records)</sub>

**Comment by melohagan** [comment]
Hey @kpturner 

The relationship picker currently has a hard-coded max limit of 100 records. Are you expecting more than 100 rows to be available for selection?

You can filter the relationship picker, which may help if that reduces the number of dropdown options to below 100, if that's the problem.

**Comment by kpturner** [comment]
But why does the limit cause the data to be rendered incorrectly?  Surely that cannot be right?

An application level filter would be no use here. A filter that can be applied by the user might work.

A 100 row limit makes the relationship picker pretty useless in this case.  Are there out of the box alternatives?

**Comment by melohagan** [comment]
Hey @kpturner 

I may have mis-understood the issue. Are you talking about the Relationship Picker component in the **Design** section, or is this issue about selecting relationships in the **Data** section?

**Comment by kpturner** [comment]
I'm talking about the relationship picker you'd add as a component to your application(s).  That's the one that renders badly. The one that you get by default in the "data" section on a grid seems fine (in terms of what it renders).  The issue I am seeing is on a picker that selects currency codes so naturally there will be a lot more than 100, and the one that looks wrong is USD (which will obviously be way down the list past 100)

**Comment by melohagan** [comment]
Thanks for the clarification @kpturner 

Is it possible for you to add a filter to the relationship picker? Something like:

<img width="1102" alt="Screenshot 2023-08-13 at 19 53 08" src="https://github.com/Budibase/budibase/assets/101575380/a36a7027-be33-4dc3-a37d-286c15341918">

So in this case it is assuming you have selected a country already in a form, and are returning only the currencies that are available in that country. Would that ever be more than 100? 

Also if you cannot share the app export, you can share the SQL schema (only metadata about the tables are shared, i.e. column names and types): https://docs.budibase.com/docs/troubleshooting-sql

**Comment by kpturner** [comment]
The problem is with creating a new country - when you need to select its currencies from an unfiltered list. Admittedly we do not create new countries very often 😂

**Comment by kpturner** [comment]
Even when editing a country you need to be able to select from the entire list of currencies. The only time I can think of a filter being useful is for display only - but then it's not really a "picker".

**Comment by kpturner** [comment]
I have emailed the schema dump to team@budibase.com

**Comment by kpturner** [comment]
> Hey @kpturner Have you tried using an options picker with a data provider source instead? https://docs.budibase.com/docs/option-picker#using-a-data-provider

It would have to be a multi-select picker to be useful - but then that does not like the data type for the field.

**Comment by melohagan** [comment]
> 



> > Hey @kpturner Have you tried using an options picker with a data provider source instead? https://docs.budibase.com/docs/option-picker#using-a-data-provider
> 
> It would have to be a multi-select picker to be useful - but then that does not like the data type for the field.

The multi-select picker has the same ability to use a data provider as its source. You can also always manually enter a field name.
Then when you do your **Save Row** action you would also `Add Column` to ensure you save the extra info that was not a part of the schema.

**Comment by kpturner** [comment]
Of course this is a pretty horrific work around as the data comes from (and has to be updated to) a relationship table that just has the keys of the two files.  It is not just a column in a table that can be sorted out on the save event. Nightmare to fix something that should work anyway.

**Comment by kpturner** [comment]
That bit is the easy bit.  When editing an existing country I still have to:
a) Preload the picker with the currencies already selected previously (from the country_currency relationship table)
b) Rewrite the data in that table when the country row is saved

**Comment by melohagan** [comment]
Shouldn't be too bad. For part a assuming you have the value column set to **_id** then you should be able to bind the relationship field to the default value of the multi-select without any transformations required.

Part b, in your **Save Row** action you will `Add Column`, select the relationship field, and set the value to your multi-select binding.

**Comment by kpturner** [comment]
Assume I have a country_currency relationship table and a currency table
I am updating a country table
and I also need to rewrite the country_currency table upon save
Which table loads the picker?  Presumably the currency table?  So I do not get how it knows which ones to pre-pick?
Or, how it would use that on a save to repopulate the country_currency table.  

Would it be possible to document an example with based on the schema I sent?

**Comment by melohagan** [comment]
Had a look at this, and the Many-Many joining table definitely makes this more difficult.

What's needed is the search functionality that can be found in the relationship picker of the data section. That way even if the options are limited to 100, the search could still be used to scan the whole table.

**Comment by kpturner** [comment]
Given that the relationship field raw value seems to be something like this:
`[{"primaryDisplay":"AWG", "_id":"%5B'AWG'%5D"}, {"primaryDisplay":"EUR", "_id":"%5B'EUR'%5D"}, {"primaryDisplay":"USD", "_id":"%5B'USD'%5D"}]`
presumably that is what I have to reset it to on the save to get BB to do its own thing with the relationship table?

**Comment by kpturner** [comment]
I got this working by creating a `worker` multi-select field that I initialise (default value) with JavaScript
```
return $("Repeater.country.additional_currencies") ? $("Repeater.country.additional_currencies").map((ac)=>ac.primaryDisplay).join(',') : ''
```
Then on the `Save Row` I update the relationship column `additional_currencies` with Javascript also (because that way it is an array and not a string)
![image](https://github.com/Budibase/budibase/assets/308646/0741b9c3-57d4-4979-982a-861715d1837e)

```
return $("Form - Update.Fields.additional_currencies_worker")
```

**Comment by melohagan** [comment]
As discussed, this does affect the default value for the relationship pickers. This is an auto-generated table block:

![Screenshot 2023-08-31 at 09 05 26](https://github.com/Budibase/budibase/assets/101575380/c7df36e1-a800-4f9a-92bb-c3527d4e053e)

You can see that customers are present. Now click on a row:

![Screenshot 2023-08-31 at 09 06 00](https://github.com/Budibase/budibase/assets/101575380/1abfd131-96e5-4af4-b571-35652ca07d1c)

Customers is **null** instead of 'Debra' because only 100 rows are selected:
![Screenshot 2023-08-31 at 09 06 40](https://github.com/Budibase/budibase/assets/101575380/8cf5e675-0c1f-4a3e-b390-00e629021c94)

**Comment by melohagan** [comment]
Having a look now at adding the search, and I do have it selecting an initial value by doing an initial search of the field value. Just working through a few other edge cases for the search as well

**Comment by andyburgessmd** [comment]
Is there likely to be any new work on this?
I have the issue where in an update form the value shown in Relationship Picker component shows as null as the value its matching is not in the first 100 results from the relationship table.

**Comment by melohagan** [comment]
Hey @andyburgessmd 

Thanks for bringing our attention to this one, I can confirm it to be a regression:

![Screenshot 2023-11-10 at 15 01 20](https://github.com/Budibase/budibase/assets/101575380/b344e889-77d7-4331-ba39-6ce388e27580)
*Initial value*

![Screenshot 2023-11-10 at 15 01 54](https://github.com/Budibase/budibase/assets/101575380/040481ca-d89c-43fa-b72a-3b0445bd383e)
*After scroll pagination loads the value*

**Comment by rmeekers** [comment]
What's the status on this? With me there are only 20 records showing in the picker and a search only searches in those 20. In order to select the right value, I have to scroll down in the picker in order to load all the records in the picker, and only then I can search for the one I need. This is quite useless off course.

**Comment by melohagan** [comment]
Try version **2.21.2**
