### ISSUE TITLE
[BUDI-7390] Zapier Payload Bindings Not Working

### ISSUE THREAD

**Issue by kerbersystems** [Budibase/budibase#11486]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Azure Docker Compose
  * Budibase Version: 2.8.30
  * App Version: 2.8.30

**Describe the bug**
When attempting to pass bindings to the payload, the bindings are not transformed into their values.

**To Reproduce**

1. Create Zapier automation.
2. Create bindings.
3. Test automation with binding values in payload to Zapier.

**Expected behavior**
Bindings in the payload are transformed into their underlying values.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/1acd36ad-dd10-497c-90e6-bf27a37b75ef/9f54a470-fa42-4b7e-9f04-9d26b1a88b70?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8xYWNkMzZhZC1kZDEwLTQ5N2MtOTBlNi1iZjI3YTM3Yjc1ZWYvOWY1NGE0NzAtZmE0Mi00YjdlLTlmMDQtOWQyNmIxYTg4YjcwIiwiaWF0IjoxNjkyMDg2NDg4LCJleHAiOjE2OTIxNzI4ODh9.g2cW424dB1G1urdSL-e6qtDoy2dFB7uKLXq-Q-o2HrE)

**Additional context**
Followed this Doc: [https://docs.budibase.com/docs/zapier](https://docs.budibase.com/docs/zapier)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7390](https://linear.app/budibase/issue/BUDI-7390/zapier-payload-bindings-not-working)</sub>

**Comment by melohagan** [comment]
Hey @kerbersystems 

You are missing a comma in your payload. It should be:

```json
{
  "number": "{{ trigger.fields.phonenumber }}",
  "message": ...
}
```

Note the ',' after "{{ trigger.fields.phonenumber }}`

**Comment by kerbersystems** [comment]
Yes I am! Thank you very much. Not sure how I didn't catch that.

**Comment by melohagan** [comment]
> Yes I am! Thank you very much. Not sure how I didn't catch that.

No worries, thanks for getting back! 😄
