### ISSUE TITLE
Bug - validation on update forms

### ISSUE THREAD

**Issue by benaunt** [Budibase/budibase#11513]
### Discussed in https://github.com/Budibase/budibase/discussions/11512

<div type='discussions-op-text'>

<sup>Originally posted by **benaunt** August 14, 2023</sup>
Hi,

I believe i have encountered a bug when applying conditional validation to an update form.

We have a requirement for a user to optionally fill in a mobile number. If the field has a value i want to apply a regex function to ensure its formatted correctly, if there is no value the field is not mandatory.

To do this I am using the condition menu on the field so that it applies a must match regex, if the field is not empty:

![image](https://github.com/Budibase/budibase/assets/83434591/2f14ec10-8b86-405f-83c8-29fd97a8c630)

When doing this, and viewing an existing record. whenever i delete the data in the field it repopulates with the saved value as i click out of the field, so I cannot empty an existing record.

The form was created with a form block, then ejected but has no specific changes to how it loads data.

When I apply this conditional validation on the field in a create form, it works as expected.

See demo:
https://github.com/Budibase/budibase/assets/83434591/2e6c8505-3fed-4ac4-9f0e-ac1d9336e528

</div>

**Comment by ConorWebb96** [comment]
Hey @benaunt,

@melohagan has provided a solution for you in that discussion as well as not being able to reproduce https://github.com/Budibase/budibase/discussions/11512#discussioncomment-6718849. Going to close this for now as it doesn't seem to be an issue. 

I've also tested myself and wasn't able to reproduce.
