### ISSUE TITLE
[BUDI-7398] Automation history filtering not working

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#11539]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud

**Describe the bug**
Automation history filtering is not showing **Stopped** automations.

**To Reproduce**

1. Go the automation history tab of an automation that has an automation that has stopped in the past
2. Filter on Status = 'stopped'
3. No rows are returned

**Expected behavior**
Automation history filter should show stopped automations.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/92de0aa8-dc6b-4714-826b-41ecc374d91b/fc1cf2aa-e56e-48ec-a2fd-0f0b4764c48b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC85MmRlMGFhOC1kYzZiLTQ3MTQtODI2Yi00MWVjYzM3NGQ5MWIvZmMxY2YyYWEtZTU2ZS00OGVjLWEyZmQtMGYwYjQ3NjRjNDhiIiwiaWF0IjoxNjkyMTkzODE3LCJleHAiOjE2OTIyODAyMTd9.VQJowiaEyxEALOKOhGNpyDB230dCz-t85aBI_ib5A-E)

**Filter on stopped**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/187b2964-6313-4465-812f-e7ea24f36e2d/08a4a3ae-ae34-48fb-9971-355585a9afcc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8xODdiMjk2NC02MzEzLTQ0NjUtODEyZi1lN2VhMjRmMzZlMmQvMDhhNGEzYWUtYWUzNC00OGZiLTk5NzEtMzU1NTg1YTlhZmNjIiwiaWF0IjoxNjkyMTkzODE3LCJleHAiOjE2OTIyODAyMTd9.bE1CmqOV_zUwUHLrfgOBAp-4XZMLat46vXWBhF4T86Y)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7398](https://linear.app/budibase/issue/BUDI-7398/automation-history-filtering-not-working)</sub>

**Comment by mike12345567** [comment]
Fixed in develop, this is specific to the new CRON stopped mechanism.
