### ISSUE TITLE
[BUDI-7409] Unable to delete a row with numeric key on postgresql table

### ISSUE THREAD

**Issue by kpturner** [Budibase/budibase#11538]
@aptkingston notes:

This looks something to do with the new "delete rows" action that accepts a whole bunch of input types. It looks like it maybe fails when provided with a single numeric value.

**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: monito

**Describe the bug**
We have a repeater containing a form and the form has a delete button.
The repeater/form shows records from a postgresql table that has an auto-generated numeric key (id).
The form correctly shows the numeric id
The delete button deletes the row providing the repeater row id
The delete fails with an error of "An error occurred while executing the query"
Debugging the BB JavaScript reveals this error to be misleading as it never gets to the point of executing any query. The JavaScript is actually failing before it gets there:

```
VM4368 budibase-client.js:47 TypeError: Cannot read properties of undefined (reading 'length')
    at Delete Row (VM4368 budibase-client.js:47:561138)
    at l (VM4368 budibase-client.js:47:565406)
    at Object.onConfirm (VM4368 budibase-client.js:47:565646)
    at confirm (VM4368 budibase-client.js:22:319217)
    at ha.<anonymous> (VM4368 budibase-client.js:1:611192)
    at VM4368 budibase-client.js:1:9543
    at Array.forEach (<anonymous>)
    at VM4368 budibase-client.js:1:9528
    at HTMLButtonElement.<anonymous> (VM4368 budibase-client.js:1:451438)
    at HTMLButtonElement.<anonymous> (VM4368 budibase-client.js:1:4577)
```

Because the key is an number (stored in a variable called `i` in the bb function, this line of code will result in `e` being `undefined`
`if ("object" == typeof i && i.constructor === Object ? e = [i] : Array.isArray(i) && (e = i)`

**To Reproduce**
See above

**Expected behavior**
Should be able to delete rows with numeric key

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7409](https://linear.app/budibase/issue/BUDI-7409/unable-to-delete-a-row-with-numeric-key-on-postgresql-table)</sub>

**Comment by kpturner** [comment]
I managed to work around this by adding a comma to the key

![image](https://github.com/Budibase/budibase/assets/308646/b94e8cee-159f-4629-8d40-9cc304575c37)

**Comment by AlejandroFNadal** [comment]
We have it too in MySQL. This breaks soo many things :(

**Comment by alican92** [comment]
So do we it hasn't been working, neither has Postgresql been able to pull new tables or fields

**Comment by zigenis** [comment]
Adding to this as I'm running into issues with it on MySQL. It seems that the change to the Delete Row action that allows for multiple row deletions at once introduced this bug. Here's the [PR](https://github.com/Budibase/budibase/pull/11236). This functionality is also not reflected in the docs.

**Comment by deanhannigan** [comment]
The endpoint for deleting rows expects 1 or more string `_id` properties to be specified. 
For SQL tables we provide a parsed `id` as the `_id` property. For example, a row with the numerical `id` 229 will have a url encoded value of `%5B229%5D`(\[229\])

You just need to specify 1 or more `_id` values when configuring the delete rows behaviour.

We could possibly add some additional help text to underline this and update the error text to reiterate.

**Comment by melohagan** [comment]
Perhaps we could also add some validation to throw a more useful error toast message. Something like:

> Cannot delete row: invalid row _id provided

**Comment by aptkingston** [comment]
The problem is that we don't really know if it's valid or not - we basically hand it off to the external DB and it will run the query. It probably depends on the DB type, but I imagine most would not return an error if you just run a query to delete rows that matches nothing.

**Comment by aptkingston** [comment]
In this case the error is due to a type mismatch, which it will error on, but if its just an ID that doesn't exist then we can't error.

**Comment by kpturner** [comment]
What was certainly unclear to me was the fact that you are supposed to use `_id`.   It seems counter-intuitive that this would even capable of working given that one knows the actual key is numeric and `_id` is not (and the contents only vaguely look like the key value with some encoding around it).

**Comment by deanhannigan** [comment]
I verified that this behaviour used to be supported on an old 1.x install so I'm just going to enable it again

**Comment by deanhannigan** [comment]
PR [https://github.com/Budibase/budibase/pull/12186](https://github.com/Budibase/budibase/pull/12186)
