### ISSUE TITLE
Cannot create query for external datasource

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1154]
**Describe the bug**
I am working off master, using a postgres data source. When I create a query, with a parameter and no default value, the query fails to save

**To Reproduce**
1. Create postgres data source (the only one I've tried)
2. Create a query
3. Add a parameter, with no default value
4. Setup the rest of the query
5. Save

RESULT: Fails to save, with error on `POST api/queries`

"Invalid body - "parameters[0].default" is not allowed to be empty"

**Screenshots**
https://www.loom.com/share/fdb32b1c709240f7b7a6c6d0b6352bfb

**Desktop**
 - OS: Windows (yarn dev on WSL)
 - Browser: Builder in chrome
 - Version: master

**Comment by shogunpurple** [comment]
Are you working off `develop` @mjashanks ?

Looks like it breaks when you don't set a value for a default param. Good catch - Will fix that one up!

**Comment by mjashanks** [comment]
I was working off `master`

**Comment by shogunpurple** [comment]
Ah, best to test off develop since we are merging that into master for the release
