### ISSUE TITLE
[BUDI-7408] Grid block buttons cover option values

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#11557]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Budimaster

**Describe the bug**
When adding a new row, and selecting an options field, the options are hidden behind the save button.

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/cd650fe0-28de-4eaf-aa8e-7948182bc2d3/0bede737-e6e6-4413-b5e8-b2ba235c8566?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9jZDY1MGZlMC0yOGRlLTRlYWYtYWE4ZS03OTQ4MTgyYmMyZDMvMGJlZGU3MzctZTZlNi00NDEzLWI1ZTgtYjJiYTIzNWM4NTY2IiwiaWF0IjoxNjkyMzcxOTk1LCJleHAiOjE2OTI0NTgzOTV9.rJFkFz6fs6atkQkJ6vv6euDhajGIOrAr4l2yh3QDWqw)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7408](https://linear.app/budibase/issue/BUDI-7408/grid-block-buttons-cover-option-values)</sub>

**Comment by aptkingston** [comment]
Unfortunately we can't avoid this - the buttons have to sit on top. I would recommend adding a display column to your table (which is typically not a select) as this bumps over your other columns and fixes the issue. All tables by default should have a display column.

**Comment by melohagan** [comment]
Just to add to this one, the options values can also dropdown behind the horizontal scroll in some circumstances.

<img width="152" alt="Screenshot 2023-10-08 at 23 04 11" src="https://github.com/Budibase/budibase/assets/101575380/a284ab40-9592-4f57-95b5-4dd5148de726">

**Comment by aptkingston** [comment]
With my recent rewrite of how table popovers work, this is no longer an issue. Dropdowns will be on top of the buttons, and overflow the table itself as needed.
