### ISSUE TITLE
Automations External Data Connector doesn't save

### ISSUE THREAD

**Issue by Kitinun** [Budibase/budibase#11552]
Now I'm facing a problem in Budibase system. I want to add firstname and lastname values to External Data Connector after I finish adding data and save data successfully. When I reload the web page The edited one is not saved, but other automation steps other than the External Data Connector can be saved normally. I would like to know how this problem can be solved or can budibase check the problem?

<img width="468" alt="Screenshot 2566-08-18 at 18 48 55" src="https://github.com/Budibase/budibase/assets/106437540/aa00e3bf-9b10-4089-b03e-743faa281317">

**Comment by melohagan** [comment]
Hey @Kitinun 

Please fill out the bug template including the reproduction steps.
