### ISSUE TITLE
[BUDI-7407] Selecting "None" as a data provider's sort column should keep rows in their original order

### ISSUE THREAD

**Issue by andz-bb** [Budibase/budibase#11554]
**Checklist**

* [X] I have searched Budibase discussions and GitHub issues to check if my issue already exists

**Hosting**

* Self
  * Method: cloud
  * Budibase Version: 2.9.23
  * App Version: 2.9.23

**Describe the bug**
When you choose `None` as the sort column for a data provider, it should leave the data from the server in its original order rather than choosing the first column behind the scenes and sorting by that.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a REST API query with multiple items on the response
2. Use that query in a data provider and ensure that `None` is selected for the sort column
3. See that the data provider is sorting the results by the first column rather than leaving them in the original order from the api response.

**Expected behaviour**
`Default` should be added to the picker with the current functionality where the data is sorted by the first column

`None` should also be an available option for the Sort Column, and when selected, would mean that the rows in the data provider are presented in their original order from the server.

**Screenshots**

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/4448249e-c591-4fde-b3ae-091aefd7b869/2f4a056d-217f-43c0-95c7-abb39eb42402?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC80NDQ4MjQ5ZS1jNTkxLTRmZGUtYjNhZS0wOTFhZWZkN2I4NjkvMmY0YTA1NmQtMjE3Zi00M2MwLTk1YzctYWJiMzllYjQyNDAyIiwiaWF0IjoxNjkyMzY2NzU3LCJleHAiOjE2OTI0NTMxNTd9.i9Xde9lMFAP-Y_YGfGmN7_hOXH2do8eoS4Q0Kc_ZPhk)

**Context**

Raised in [this GitHub discussion](https://github.com/Budibase/budibase/discussions/11543)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7407](https://linear.app/budibase/issue/BUDI-7407/selecting-none-as-a-data-providers-sort-column-should-keep-rows-in)</sub>

**Comment by aptkingston** [comment]
This will be fixed as part of the views V2 PR (it's already fixed on that branch).

If you leave "sort column" at "default" then it will either do no sorting at all (e.g. most datasources) or use the built in sorting (view V2s).

"sort order" will also not appear as a setting unless "sort column" is defined.
