### ISSUE TITLE
[BUDI-7410] Drag and drop not working:  multi-select option config

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#11569]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Budimaster - Cloud

**Describe the bug**
I added a multi-select field to my schema. I then added 6 options. I want to rearrange the options but DnD is not working.

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/d1ebf9bf-b628-4455-bc31-2bd67e2ae382/0fb2d080-c73a-445b-949a-3d53592751cf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9kMWViZjliZi1iNjI4LTQ0NTUtYmMzMS0yYmQ2N2UyYWUzODIvMGZiMmQwODAtYzczYS00NDViLTk0OWEtM2Q1MzU5Mjc1MWNmIiwiaWF0IjoxNjkyNjE2NjQ3LCJleHAiOjE2OTI3MDMwNDd9.hhP6T-ggBsWWN5H-3EHjP-IkDkBV1syQEVrEbozBcgs)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7410](https://linear.app/budibase/issue/BUDI-7410/drag-and-drop-not-working-multi-select-option-config)</sub>

**Comment by melohagan** [comment]
Same also applies to a newly added options field.

**Comment by aptkingston** [comment]
What browser or OS is this? What happens when you drag?

This is working fine for me in Chrome, although in Firefox when you release drag it closes the popover.

**Comment by melohagan** [comment]
This is so strange, I was sure that I couldn't drag the options, and now I can. I was using Google Chrome.

The last time I tried, the grab hand was definitely displaying, but I couldn't drag.

**Comment by melohagan** [comment]
Ah I've figured out the reproduction steps:

1. Add three options
2. Rename the third option, and without clicking off the text input, try to drag.
3. Now the drag is broken

Page refresh will fix

**Comment by aptkingston** [comment]
> Ah I've figured out the reproduction steps:
> 
> 1. Add three options
> 2. Rename the third option, and without clicking off the text input, try to drag.
> 3. Now the drag is broken
> 
> Page refresh will fix ![change id](https://user-images.githubusercontent.com/101575380/262045640-b2de85c4-07ba-4430-9fe4-fd476b04fc63.gif)

Nice catch. Minimal steps are:
- Rename an option, but do not click off the text field
- Try to drag

This throws an error.
