### ISSUE TITLE
[Docker] [Fresh Install] 502 Bad Gateway behind Reverse Proxy

### ISSUE THREAD

**Issue by Gamechiefx** [Budibase/budibase#11562]
After installing a fresh and latest leantime docker installation I am unable to navigate to /dashboard/home it reports a 502 Bad Gateway. On top of it /Dashboard reports a 404 Not found.

Please help

**Comment by aptkingston** [comment]
Hi @Gamechiefx. I'm not sure where you got your information from, but we don't have any routes for `/dashboard` or `/dashboard/home` in Budibase. `/builder/portal/apps` is the closest thing to a "home page" that we have.

You can of course build an app with those routes, if that's what you mean.

Please follow the issue template next time as well.
