### ISSUE TITLE
I am not able to deselect the Field in form Which i have created from budibase's internal tables

### ISSUE THREAD

**Issue by shaikhashraf709** [Budibase/budibase#1157]
Description:
When i Create a form using an internal budibase table, the whole table columns appear on the form and i can't remove some of the fields that i don't want in my form.

**Comment by shogunpurple** [comment]
Hi @shaikhashraf709, this will no longer be an issue when we release the new form builder feature this week. The form builder allows you to have total control over the columns you put into your forms, solving your problem! Closing this for now.
