### ISSUE TITLE
[BUDI-7422] Composite keys cause issues whenever trying to bulk delete records.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11588]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Docker compose
  * Budibase Version: 2.9.30
  * App Version: 2.9.30

**Describe the bug**
External data sources e.g. MySQL, Postgres. When using a composite key for the primary id e.g. `name,age,date`. The delete row action won't work; the error message thrown says `cannot read property '_id' of undefined`. Weirdly enough updating or creating rows work.

**To Reproduce**

1. Create a database in MySQL with a composite primary key made up of other fields within the table. **See below for the SQL query used to create the table**
2. Import the above database into Budibase
3. Add a table block component within a screen
4. Turn on row selection within the table block component
5. Configure a button to delete rows on click
6. Bind the selected rows to the delete rows action.
7. Select some rows, try and delete then see the error.

**Expected behavior**
Rows when selected are passed to the delete rows action it and should successfully delete the selected rows.

**Screenshots**

![Screenshot 2023-08-24 at 12.30.36.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/371f137c-6729-4785-9a68-c6138a13a658/16cbb3ff-9638-4882-a60d-cf15aa71d014?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8zNzFmMTM3Yy02NzI5LTQ3ODUtOWE2OC1jNjEzOGExM2E2NTgvMTZjYmIzZmYtOTYzOC00ODgyLWE2MGQtY2YxNWFhNzFkMDE0IiwiaWF0IjoxNjkzMjkxODc1LCJleHAiOjE2OTMzNzgyNzV9.sxPqHI8G2Ivoxli1jWhtjjzbocHSFCyU_VZrNOb_npA)

![Screenshot 2023-08-24 at 12.30.27.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/a175a4fe-7212-4c65-9dd4-95268b59bfd3/63ccbe94-4e63-4df9-8511-22e97db5525a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hMTc1YTRmZS03MjEyLTRjNjUtOWRkNC05NTI2OGI1OWJmZDMvNjNjY2JlOTQtNGU2My00ZGY5LTg1MTEtMjJlOTdkYjU1MjVhIiwiaWF0IjoxNjkzMjkxODc1LCJleHAiOjE2OTMzNzgyNzV9.SQULS_25YgpIxuqx7F8xbdD_eBf8jBCc6BqEEDOs8UU)

**Table create query - that causes the issues**

```
CREATE TABLE `new_table` (
  `name` varchar(20) NOT NULL,
  `age` int(11) NOT NULL,
  `date` datetime NOT NULL,
  PRIMARY KEY (`name`,`age`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

```
CREATE TABLE `odometer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(20) DEFAULT NULL,
  `mileage` int(11) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=796 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

It won't work with the above code either. This outputs normal looking ids e.g. `%5B2%5D,%5B1%5D`

The above's error is different from the previous; `Truncated incorrect DOUBLE value: '%5B2%5D,%5B1%5D'`. This version will allow you to also delete one if one is selected. This error is only through if more than 1 is selected for deleting.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7422](https://linear.app/budibase/issue/BUDI-7422/composite-keys-cause-issues-whenever-trying-to-bulk-delete-records)</sub>

**Comment by jacobmaussocc** [comment]
Any updates on this issue? I am sorry to rush anything, though the need for this functionality is a lot more pressing than we had initially thought. Would really like to have it be possible.

**Comment by ConorWebb96** [comment]
Hey @ConorWebb96,

This is set to be done in the next iteration (next month). The engineering team have a lot of fixes/enhancements that require their attention this iteration.

**Comment by mike12345567** [comment]
Fixed in latest release.
