### ISSUE TITLE
Table not being fetched when using "Select All"

### ISSUE THREAD

**Issue by EndoRay** [Budibase/budibase#11595]
**Checklist**
- [x ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: ASPnix 
  - Budibase Version: 2.9.30
  - App Version: N/A
- Cloud
  - Tenant ID: hexfold

**Describe the bug**
I am trying to add all tables from my SQL database into budibase, and when I open the Fetch Tables tool it lists all of my tables, but one is unchecked. When I check it at click "Fetch Tables" it add all of the tables except for the one that started as unchecked. That table has no primary key, but the data within wouldn't need a primary key for my purposes but that's the only reason I can think for why it wasn't fetched. When I click "Select All" and then "Fetch Tables," I get the same issue.

UPDATE: Added a primary key to the problem table, table added successfully.

**To Reproduce**
1. Go to Data
2. Click on MySql
3. Scroll down to Fetch Tables button
4. Click on Fetch Tables button
5. Click on Select All button
6. Click on Fetch Tables button

**Expected behavior**
I expected all of my tables to be put into budibase, not just the ones with a primary key (if that's the issue)

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/11151070/68e70bf8-4722-4813-998b-5741071dde5f)
![image](https://github.com/Budibase/budibase/assets/11151070/600e0aca-a146-493e-b5c2-a36c63fe11ae)

  
**App Export**
No

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 116.0.3

**Comment by melohagan** [comment]
Hey @EndoRay 

Most likely this is because the `alt_inks` table is incompatible with Budibase. As you stated in your own update, it's because of the missing primary key.

Going to close this one in favour of: https://github.com/Budibase/budibase/issues/6216
