### ISSUE TITLE
[BUDI-7431] Let users decide where they put a save button on forms.

### ISSUE THREAD

**Issue by EndoRay** [Budibase/budibase#11598]
**Describe the feature request**
As of this moment I am unable to change where the save button appears on a Form Component in my budibase app. I have a somewhat longer form that I fill out and it'd be nice if I was able to place the save button at the bottom of the form rather than have to scroll to the top. Not super important but it'd be nice for QoL purposes

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/7a9532bc-dce7-49a2-82fa-3b1f03b129c2/d8ed0832-ec82-407a-898c-4f10c7a308b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC83YTk1MzJiYy1kY2U3LTQ5YTItODJmYS0zYjFmMDNiMTI5YzIvZDhlZDA4MzItZWM4Mi00MDdhLTg5OGMtNGYxMGM3YTMwOGIyIiwiaWF0IjoxNjkzMzExMTk5LCJleHAiOjE2OTMzOTc1OTl9.KO-h_gKVgXHrvcQ1cdMDjg4HwQ6uScr6SLf4oBAQ4t4)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7431](https://linear.app/budibase/issue/BUDI-7431/let-users-decide-where-they-put-a-save-button-on-forms)</sub>

**Comment by mslourens** [comment]
it is possible to position the save button of a form wherever you like (top or bottom of the form) just by moving the save button to a different position in the component tree:
### At the bottom
![image](https://github.com/Budibase/budibase/assets/1907152/fe06fda9-4380-4e4f-91ec-b82ba940ffde)

### At the top
![image](https://github.com/Budibase/budibase/assets/1907152/380749a9-55f7-4016-9747-c24362be8fbf)
