### ISSUE TITLE
Repeater gives different output for "Default value" and "Placeholder" 

### ISSUE THREAD

**Issue by teigentler** [Budibase/budibase#11601]
I have a table that contains a reimbursement for defined services. This table is to be displayed using text fields.
If this is relealized with a repeater, which should output the text as "Default value", the number of rows is displayed correctly, but textually always only the first row.
If the same reference is given as "Placeholder", the row is displayed correctly.

Right with Placeholder
![image](https://github.com/Budibase/budibase/assets/18628021/849c239b-aaa1-4ba1-bd0b-3b2a32629b7d)

Wrong with "Default"
![image](https://github.com/Budibase/budibase/assets/18628021/d30d0667-f3a0-4bc2-ad35-22050dd8b2af)

 - OS: Windows
 - Browser Edge
 - Version 115

**Comment by melohagan** [comment]
Hey @teigentler 

This is not technically a bug because you are repeating form fields that have the same name, thus the default value will be the same for all.

Closing in favour of this enhancement: https://github.com/Budibase/budibase/issues/5658
