### ISSUE TITLE
[BUDI-7426] Relationship picker searching enhancement

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11607]
**Describe the feature request**
Add the ability to search relationships with the relationship picker component, currently the autocomplete option is capped to 100 items. (Optionally allow this to be increased depending on the users needs.)

**Related Discussions**

* [https://github.com/Budibase/budibase/discussions/11558](https://github.com/Budibase/budibase/discussions/11558)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7426](https://linear.app/budibase/issue/BUDI-7426/relationship-picker-searching-enhancement)</sub>

**Comment by aptkingston** [comment]
I assume you mean searching from inside the component itself? Since we did recently add relationship picker filtering as a builder setting.

**Comment by JCV67** [comment]
Thank you @ConorWebb96
