### ISSUE TITLE
[BUDI-7437] Allowing naming of automation steps

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#11621]
I would like to be able to give each automation step a name.

When there are more than 2 steps, it starts to become confusing which step is which, when using bindings...

`{{ step 3.response.id }}` - what is step 3 again?

It would be nice to see `{{ create customer.response.id }}`, both in existing bindings, and in the binding selection drawer / autocomplete.

<sub>[BUDI-7437](https://linear.app/budibase/issue/BUDI-7437/allowing-naming-of-automation-steps)</sub>

**Comment by mike12345567** [comment]
@AndrewBastin.whann - one concern raised is what the error state should look like for the automation step name input, e.g. it is not unique or contains letters that are not allowed.

**Comment by turbohz** [comment]
Even if the name is not used for bindings, a name and description that will be just displayed would be very helpful.
