### ISSUE TITLE
[BUDI-7445] Zappier automation triggering but not completing

### ISSUE THREAD

**Issue by kerbersystems** [Budibase/budibase#11638]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Docker Compose
  * Budibase Version: 2.9.34 (also on 2.8.0 and 2.9.30)
  * App Version: 2.9.34 (also on 2.8.0 and 2.9.30)

**Describe the bug**
Running an automation by clicking a button does not trigger the automation even though the response say it had triggered (it also does not show up in automation history). I am able to test an automation and it run successfully with the exact same data. I do not see the Zap coming through in Zappier in the production app but it does in the test automation.

**Expected behavior**
The automation triggers successfully.

**Screenshots**
Automation from inside of app (200 response)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/8d410128-7e7d-484b-8ff4-9d34d0606096/b7488c86-3fb1-4ecd-94e3-9d33e00d5887?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC84ZDQxMDEyOC03ZTdkLTQ4NGItOGZmNC05ZDM0ZDA2MDYwOTYvYjc0ODhjODYtM2ZiMS00ZWNkLTk0ZTMtOWQzM2UwMGQ1ODg3IiwiaWF0IjoxNjkzNTExOTM3LCJleHAiOjE2OTM1OTgzMzd9.3T1lH8cVzn6EklnaOcooYrJrRCsngSo_JdXMiBOEvdE)

Automation history showing no runs

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b8c1e823-678a-490d-8bff-269220db39c4/af4fa724-d855-4d63-b242-8fccb3755370?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9iOGMxZTgyMy02NzhhLTQ5MGQtOGJmZi0yNjkyMjBkYjM5YzQvYWY0ZmE3MjQtZDg1NS00ZDYzLWIyNDItOGZjY2IzNzU1MzcwIiwiaWF0IjoxNjkzNTExOTM3LCJleHAiOjE2OTM1OTgzMzd9.JHZNqLZQHXe0oVtGUqnqUY5b11jAl7RHnG0cJm0Oz_Y)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7445](https://linear.app/budibase/issue/BUDI-7445/zappier-automation-triggering-but-not-completing)</sub>

**Comment by melohagan** [comment]
Hey @kerbersystems 

This may be related to a broader issue relating to automations: https://status.budibase.com/

**Comment by kerbersystems** [comment]
@melohagan Thank you for the update! I'm assuming the automation health monitor is for cloud environments? If so, will there be a release to fix the self hosted deployments?

**Comment by melohagan** [comment]
Hey @kerbersystems 

This issue should be resolved in version **2.9.36**

**Comment by kerbersystems** [comment]
I can confirm that it is fixed. Thank you to all the devs!
