### ISSUE TITLE
Preview throws error when adding a new component

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1165]
**Describe the bug**
I am working from `develop`, using a brand new app. When I create a new component, it does not appear in the preview, and an error is thrown in console:

```
index.mjs:1652 Uncaught (in promise) Error: 'target' is a required option
    at new SvelteComponentDev (VM215 budibase-client.js:1048)
    at new Provider (VM215 budibase-client.js:5019)
    at Os (VM215 budibase-client.js:1523)
    at init (VM215 budibase-client.js:958)
    at new _s (VM215 budibase-client.js:1523)
    at create_key_block$2 (VM215 budibase-client.js:6304)
    at create_if_block$1 (VM215 budibase-client.js:6028)
    at Object.update [as p] (VM215 budibase-client.js:6406)
    at update (VM215 budibase-client.js:510)
    at flush (VM215 budibase-client.js:478)
```

**To Reproduce**

1. Create a new app
2. Go to design
3. Add a repeater component
4. repeater does not display on screen
5. Error thrown in console

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chroms
 - Version: `develop`

**Comment by aptkingston** [comment]
This is usually due to the client package not being built and used in the builder when pulling down significant updates. Try doing a manual build first.

**Comment by mjashanks** [comment]
Ah of course.

I did actually to a `yarn build`, which didn't fix it.

Just realised that `yarn bootstrap` throws an error, so I'm sure it's to do with that. Maybe the symlinks are not getting setup.

![image](https://user-images.githubusercontent.com/3524181/108903240-fbbfb300-7614-11eb-99b9-b9a4d315c616.png)

I'm using WSL, but I get the same error when using Powershell.

Not to worry for now, but looks like dev on windows is broken.

**Comment by shogunpurple** [comment]
@mjashanks looks like an issue with yarn:

https://github.com/yarnpkg/yarn/issues/660

Some people on that issue report that ‘yarn cache clean’ fixes it 👍
