### ISSUE TITLE
[BUDI-7466] Invalid default global-db name (cloud)

### ISSUE THREAD

**Issue by diogenesbrussels** [Budibase/budibase#11707]
**Hosting**
- Cloud
  - Tenant ID: ?

**Describe the bug**
I already have a self-hosted version but I wanted to try one of the templates (https://budibase.com/templates/).
I clicked the "Try Template" button, then was asked to login. After using the "Log in with Google" option, I got this message:
`{"message":"Name: 'xxx@xxx.com_global-db'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.","status":400}`
I hope this helps you to have a better first experience for new users/customers.

**To Reproduce**
1. Go to https://budibase.com/templates/
2. Click on 'Try template'
3. Use 'Log in with Google' (no sign up before)
4. See error : `{"message":"Name: 'xxx@xxx.com_global-db'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.","status":400}`

**Expected behavior**
Have an intermediate form that asks me for the db name (and that corresponds to the criteria) or have the db name generated without special characters

<sub>[BUDI-7466](https://linear.app/budibase/issue/BUDI-7466/invalid-default-global-db-name-cloud)</sub>

**Comment by shogunpurple** [comment]
Hi, have you already onboarded previously when you signed up for a self hosted account using the same email address?

**Comment by diogenesbrussels** [comment]
Hi, do you mean on the self-hosted instance or on the cloud solution?
On the self-hosted instance: Yes
Via cloud: I don't remember so

I'm not sure I understand what onboarding refers to because I just clicked on 'Try template' and then the google login button oauth.

**Comment by shogunpurple** [comment]
@diogenesbrussels this is happening because you are trying to use https://budibase.com/templates/ which is mainly for cloud accounts.

The full list of available templates should be displayed inside your self hosted instance when you click "Create an app". Would this not suffice?
