### ISSUE TITLE
[BUDI-7471] Prevent the key "user" being used as a binding in REST queries

### ISSUE THREAD

**Issue by tkowalski29** [Budibase/budibase#11722]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Budibase Version: <version> 2.10.0

**Describe the bug**
When we have user in parameters in query we got error:
```
{
    "message": "Invalid JSON for request body",
    "status": 400
}
```

But when we change user to another name for example users. Everyfing is working well.

More information about solutions. 
Discord -> community-help -> thread ID: 1149361595076591727
https://discord.com/channels/733030666647765003/1149361595076591727/1149361595076591727

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/3847457/5fbdcd0e-b15a-4432-a990-6b5c23b1bcc7)
![image](https://github.com/Budibase/budibase/assets/3847457/35670c60-b356-4b2e-823a-e701a95a04aa)

<sub>[BUDI-7471](https://linear.app/budibase/issue/BUDI-7471/binding-variable-user-in-query)</sub>

**Comment by melohagan** [comment]
And I believe `auth` would also be a reserved keyword - worth test it as well
