### ISSUE TITLE
[BUDI-7472] Cant make a local generated docker image work - but the published one works

### ISSUE THREAD

**Issue by reichert** [Budibase/budibase#11721]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image (building my own image)
  - OS: both Ubuntu 20.04 and 22.04 (inside a multipass container)
  - Budibase Version: 2.9.36

**Describe the bug**
I'm trying to build my own image (single image) and after searching a lot I used the following reference to build my script:
- https://github.com/Budibase/budibase/tree/develop/hosting/single
- https://github.com/Budibase/budibase/issues/10840

Inside a multipass container of the Ubuntu 22.04 or 20.04 I can successfully run the container published in dockerhub through `docker run -d -t --name=budibase -p 80:80 -v ./budidata:/data --restart unless-stopped budibase/budibase:latest`
If I use the local image I just burn `docker run -d -t --name=budibase -p 80:80 -v ./budidata:/data --restart unless-stopped budibase:latest` I cannot access the system and the docker logs only show 502 errors

**To Reproduce**
I'll put my script here used to build the image
```
sudo apt-get update

# Install the NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Install npm 14
nvm install 14
npm install -g yarn jest lerna

# Install other requirements
sudo apt install -y cmake g++

# Install docker
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$UBUNTU_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update -y
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo usermod -aG docker ubuntu
newgrp docker

# Clone budibase
BUDI_VERSION=2.9.36
git clone -b $BUDI_VERSION https://github.com/Budibase/budibase.git --depth 1

# BUild the image
cd budibase
npm install -g yarn jest lerna
node ./hosting/scripts/setup.js 
yarn
yarn build
./scripts/updateVersions.sh
yarn build:docker:single
./scripts/resetVersions.sh

#docker run -d -t --name=budibase -p 80:80 -v ./budidata:/data --restart unless-stopped budibase:lates
```
**Assumptions**
1. Everything should be done with node 14 (package.json requires node between 14 and 15 besides the documentation tell us that the version 16 should be used)
2. When installing lerna (under node 14) an error occurs but all the process continues besides the error. Under node 16 the error does not occur

**Expected behavior**
1. build the docker single image and the migrations should be applied in the first run (they are not)

**Additional context**
If I'm doing anything wrong I'd love to hear!

<sub>[BUDI-7472](https://linear.app/budibase/issue/BUDI-7472/cant-make-a-local-generated-docker-image-work-but-the-published-one)</sub>

**Comment by shogunpurple** [comment]
Hi @reichert - this is a totally custom setup, using NVM etc with your own build script. Unfortunately this would be beyond the scope of community support and would require some time to debug.

You can use the CI job we use to build the budibase single image for reference here, which may help - https://github.com/Budibase/budibase/actions/runs/6158492194/workflow

**Comment by jcostasilva** [comment]
Hi @shogunpurple ,

I'm experiencing exactly the same problem, also running my own copy of https://github.com/Budibase/budibase/actions/runs/6158492194/workflow

Thanks,
Jorge

**Comment by shogunpurple** [comment]
@jcostasilva do you have a custom script to build the image?

**Comment by jcostasilva** [comment]
@shogunpurple No. I just copied the file 100% and only changed to my docker credentials.

**Comment by shogunpurple** [comment]
@jcostasilva then why build your own image? Could you not just use ours?

**Comment by jcostasilva** [comment]
@shogunpurple I was just testing to see if I could make it work. If that was case, I could afterwards try to make custom builds, like installing new libraries, etc. I started trying to do local builds with build:docker:single:image. When that didn't work, I trying to mirror your exact workflow, but that didn't work either.

**Comment by reichert** [comment]
Hello @shogunpurple and @melohagan 

I apologize for the "custom setup" - it was not the intention to make anything different than you do and I just realized that the docker images are generated through the github actions, so I decided to build an image by myself with near zero custom code. The same error persists.
If you can point if I'm doing anything wrong it would be great.

**Reason for generating an image by myself:**
- We need to proof the concept to publish budibase if we decide to make any customization on it;
- We will publish it on single image in this case;
- The [documentation](https://github.com/Budibase/budibase/blob/develop/hosting/single/README.md#build-the-image) of building images does not work or it is not up to date;

**how we build the single docker image (and the reasons)**
1. we cloned the budibase repository to our own github account
2. we configured the secrets for github and dockerhub: DOCKER_API_KEY, DOCKER_USERNAME, PERSONAL_ACCESS_TOKEN
3. we make the following changes in /.github/workflows/release-singleimage.yml
- replaced the target of budibase image from budibase/budibase to myaccount/budibase
- changed in the checkout section the submodules to false because it makes reference to the budibase-pro - and we dont have access to this repository (and we assumed it is not 
5. we commited the changes, released a new tag on the master and we put this tag on the environment RELEASE_VERSION of github.

**Trying to run the image**
- we used docker run -p 8000:80 --name budibase -v ./budibase_data:/data --restart unless-stopped myaccount/budibase
- trying to access the browser it result in an 502. We noticed through the logs that couchdb didn't started
- logs attached below

How would you suggest me to go forward?

Errors that I thing are useful (full logs attached)

**couchdb does not create the database and keeps throwing errors....**
[error] 2023-09-27T12:02:33.949554Z couchdb@127.0.0.1 emulator -------- Error in process <0.397.0> on node 'couchdb@127.0.0.1' with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,400}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,375}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,404}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,97}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}

**Every request returns an 502**
[notice] 2023-09-27T12:03:49.255093Z couchdb@127.0.0.1 <0.1207.0> 8d7f2252c9 localhost:5984 127.0.0.1 undefined GET / 200 ok 0
127.0.0.1 - - [27/Sep/2023:12:04:04 +0000] "GET / HTTP/1.1" 502 150 "-" "curl/7.74.0" "-"

full docker logfile
[docker.log](https://github.com/Budibase/budibase/files/12741104/docker.log)

full github action build log
[logs_action_single_13.zip](https://github.com/Budibase/budibase/files/12741120/logs_action_single_13.zip)
