### ISSUE TITLE
[BUDI-7477] Add the ability to revoke pending user invites.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11745]
When I invite someone the invite goes into a pending state and can't be interacted with unless, it either expires or the user joins. Add a button attached to the invite that will revoke the ability to join an app before the expiration date.

**Conditions of Satisfaction (COS)**

* Add the ability to somehow revoke a pending user invite. This could be a button attached to the invite, or some form of dropdown menu which has options to cancel invite or re-send invite again.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7477](https://linear.app/budibase/issue/BUDI-7477/add-the-ability-to-revoke-pending-user-invites)</sub>

**Comment by diogenesbrussels** [comment]
Duplicate #11044 ?

**Comment by ConorWebb96** [comment]
@diogenesbrussels,

I missed this, closing as you are right.
