### ISSUE TITLE
[BUDI-7482] Users can no longer log in

### ISSUE THREAD

**Issue by kpturner** [Budibase/budibase#11752]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: monito

**Describe the bug**
Our users can no longer log in

**To Reproduce**
We have 4 admin users and one power user.  The user cannot log in. No error messages are displayed but we can see that the login request responds with a 403.  If they use an incorrect password then they are correctly told the credentials are wrong - so that is not the issue.  This is a big showstopper at the moment. 

**Expected behavior**
Users should be able to log in - or at least be told why not

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/308646/79802cc3-0dc6-4922-9516-ad13f4c09115)

![image](https://github.com/Budibase/budibase/assets/308646/9d14b8d6-6832-4f94-b4f8-c5592fe9d158)

  

<sub>[BUDI-7482](https://linear.app/budibase/issue/BUDI-7482/users-can-no-longer-log-in)</sub>

**Comment by kpturner** [comment]
@melohagan any ideas?   Not sure what is going on without any meaningful errors

**Comment by kpturner** [comment]
It seems now that only `Admin` users can log in.   Those invited as `Members` cannot.

**Comment by melohagan** [comment]
Hey @kpturner I believe there is a PR out for the fix. Will be deployed tomorrow most likely.

**Comment by shogunpurple** [comment]
Hi @kpturner - this should now be resolved. Can you now log in as normal?

**Comment by kpturner** [comment]
Yep - works now
