### ISSUE TITLE
[BUDI-7484] Dataprovider filter return no rows must not save if no filter criteria is set

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#11761]
**Checklist**
- [ X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Version: 2.10.0

**Describe the bug**
If someone sets in a DP to add filter, clicks on "Return no Rows: when filter empty, and then selecting no filters and saving, the DP shows no filters, but it will return no rows. 
I guess the goal of this feature is to be able to select what happens if no rows match the filter, to return all or to return none. But in this case, if you save with no filter selected, it will show nothing. 

**To Reproduce**
1. Create a DP
2. Add filter button
3. Set "When empty", "Return no rows"
4. Save without adding any filter
5. No rows will be returned and no filters will be shown as active in the DP

**Expected behavior**
I would expect to not be able to save in such an invalid state, or, otherwise, that if I go to the filters, this is shown, so that I can realize that I am in this invalid state and revert it.

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser Firefox
 - Version 102

<sub>[BUDI-7484](https://linear.app/budibase/issue/BUDI-7484/dataprovider-filter-return-no-rows-must-not-save-if-no-filter-criteria)</sub>

**Comment by shogunpurple** [comment]
This is expected behaviour - generally when filters are passed to a DP it will be done so in a dynamic fashion, which is why we have the option to show all vs no rows when an empty filter is passed.

We are happy to accept a PR for something like this if it's a big issue for your use case - but closing for now.
