### ISSUE TITLE
[BUDI-7518] [Builder] - Make Section of Component Properies Panel optionally collapsible

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#11777]
Add the conditional ability to the Section to be collapsible like an accordion and have an Order ( the position amongst sibling Sections ) so we dont have to move things around in the schema to position them and we can keep all Sections nicely together and rearrange them by changing the Order.

<sub>[BUDI-7518](https://linear.app/budibase/issue/BUDI-7518/[builder]-make-section-of-component-properies-panel-optionally)</sub>

**Comment by mike12345567** [comment]
Hi @poirazis - interesting idea, we've been discussing it, could you perhaps give us a bit more information about what you mean by "position amongst sibling sections" and "changing the order" of the sections? If they were collapsible that would not affect where the properties are in the panel, you can control the order of your settings using the manifest today.

**Comment by poirazis** [comment]
Hey @mike12345567 .
you are correct, you can change the order by moving them in the manifest, that part of the idea wanst the finest :)
