### ISSUE TITLE
[BUDI-7490] Delete button does not show for table block until after you focus the input

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#11774]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method:  docker compose
  - Budibase Version: 2.10.6

**Describe the bug**
When you add an auto-generated screen for list view, no delete button is added even though it is shown in the settings. If you click on the 'Delete' input text, then the delete button will be added.

**To Reproduce**
1. Add sample data
2. Create list view screen for the 'Employees' table
3. Preview app - click on a row to see there is no delete button
4. Click on the 'Delete' text in the settings panel of the table block
5. Preview app - click on a row to see the delete button has now been added

**Expected behavior**
When adding an auto-generated list view screen, the delete button should be included in the side panel, as reflected in the settings panel.

**Screenshots**
![Screenshot 2023-09-14 at 15 38 02](https://github.com/Budibase/budibase/assets/101575380/a08ad049-4bf8-419b-b2bd-b15f79c68c87)

![Screenshot 2023-09-14 at 15 38 21](https://github.com/Budibase/budibase/assets/101575380/ce1c2b0e-bd8b-4039-8ddb-3fd1243b815b)
*No delete button*

![Screenshot 2023-09-14 at 15 38 41](https://github.com/Budibase/budibase/assets/101575380/e7e9ab1c-60f9-4b85-a0de-12e9789d5bfd)
*Focus the delete text input*

![Screenshot 2023-09-14 at 15 39 08](https://github.com/Budibase/budibase/assets/101575380/13ba5df5-ff2b-432c-8273-8b5ab5bea7f9)
*Delete button now appears*

<sub>[BUDI-7490](https://linear.app/budibase/issue/BUDI-7490/delete-button-does-not-show-for-table-block-until-after-you-focus-the)</sub>

**Comment by deanhannigan** [comment]
PR [https://github.com/Budibase/budibase/pull/11875](https://github.com/Budibase/budibase/pull/11875)
