### ISSUE TITLE
[BUDI-7488] Make DateTime Picker follow selected Theme

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#11772]
Currently the DateTime Picker when opened always uses a White background.
It would be nice if we were to inject some CSS to make the underlying picker follow the Budibase selected Theme.

<sub>[BUDI-7488](https://linear.app/budibase/issue/BUDI-7488/make-datetime-picker-follow-selected-theme)</sub>

**Comment by mike12345567** [comment]
Hi @poirazis - we have created this issue to fix our date-picker component, we have a number of issues with it, wanted to create somewhere we could track the multitude of reasons it needs replaced.
https://github.com/Budibase/budibase/issues/11894
