### ISSUE TITLE
Columns in screen do not match with data columns

### ISSUE THREAD

**Issue by Ph1com** [Budibase/budibase#11787]
Hi, I joined Budibase yesterday and I've just created my first Budibase app and screen using the Budibase database. I've managed to create an inventory app, which scans in barcodes and allows me to take and store photos. All looks good, except that when I try to rearrange the columns within the data table, it does not reflect these changes on the screen within the design tab. I have republished, but it is still the same. I can change the position of the fields in the side panel, but not the row view.

Any pointers would be gratefully received!

Best regards
Paul

**Comment by melohagan** [comment]
Hey @Ph1com 

Could you please follow the bug template, including reproduction steps and screenshots. 

Closing for now
