### ISSUE TITLE
[BUDI-7837] Table with two many-to-many relationships.  Only one of the "through" tables is editable

### ISSUE THREAD

**Issue by kpturner** [Budibase/budibase#11825]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud
  - Tenant ID: monito

**Describe the bug**
We have a simple table that has two many-to-many relationships defined for it - therefore there are two "through" tables for the relationship data.  When we import the tables to Budibase the "through" tables are there in the "Data" section as expected BUT you cannot edit them - i.e. you cannot manually add records to the "through" table through the Budibase data facility.

However, if you go to the relationship definition and click "Save" then the "through" table does become editable - but only the one you  clicked "save" for.  If you then "save" the other relationship, the "through" table for that becomes editable but the first one is no longer.  It seems to toggle between them - but there is no way to make them both editable at the same time.  If they are not editable, you cannot manually enter data or import a CSV.   

**To Reproduce**
Described above

**Expected behavior**
Imported "through" tables should be editable regardless

**Screenshots**
  
**App Export**
I can send it to support if need be

<sub>[BUDI-7837](https://linear.app/budibase/issue/BUDI-7837/table-with-two-many-to-many-relationships-only-one-of-the-through)</sub>

**Comment by kpturner** [comment]
Sure – please find attached

 

From: Michael Drury ***@***.***>
Reply to: Budibase/budibase ***@***.***>
Date: Wednesday, 20 September 2023 at 10:33
To: Budibase/budibase ***@***.***>
Cc: Kevin Turner ***@***.***>, Mention ***@***.***>
Subject: Re: [Budibase/budibase] Table with two many-to-many relationships. Only one of the "through" tables is editable (Issue #11825)

 

Hi @kpturner - would it be possible for you to provide a basic replication of this, using the schema export:
https://docs.budibase.com/docs/troubleshooting-sql
would make debugging this quite a bit easier!

**Comment by kpturner** [comment]
I am not going to attach the schema to GitHub so I just replied to your email.  Please give me a specific address so that I can bypass GitHub completely.

 

From: Michael Drury ***@***.***>
Reply to: Budibase/budibase ***@***.***>
Date: Wednesday, 20 September 2023 at 11:33
To: Budibase/budibase ***@***.***>
Cc: Kevin Turner ***@***.***>, Mention ***@***.***>
Subject: Re: [Budibase/budibase] Table with two many-to-many relationships. Only one of the "through" tables is editable (Issue #11825)

 

Hi @kpturner - Github strips attachments from email responses before putting them out as comments - so I am unable to see any attachments!

**Comment by mike12345567** [comment]
Hi @kpturner - if you can send it to support@budibase.com that would be great.

**Comment by danieleangeli** [comment]
A similar behaviour happens when having two or more one-to-many relationships between two tables. My example is:

TABLE "**databaseName**"
id
name

TABLE "**licenses**"
id
sourceNameId
targetNameId

**databaseName** has a one-to-many with **licenses** on sourceNameId _and_ another one on targetNameId. This is leading budibase on breaking the relationship builder (you cannot create the second relationship from within the data source) but _you can_ from the **databaseName** table even though it breaks the previous constrait making it unusable

**Comment by danieleangeli** [comment]
Still getting weird errors like:

- Error saving relationship info: CouchDB error: Document update conflict. 
- identity column conflicts

I am basically unable to use two or more relationships in a table that points to another one, is there anyway taking an eye on that?

**Comment by mike12345567** [comment]
This should be resolved in V3 - we've made some updates around this which will be released next week.
