### ISSUE TITLE
Auto ID not incremeting

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1182]
**Describe the bug**
I am creating new rows via the builder. They all have `Auto ID = 1`

**To Reproduce**
Steps to reproduce the behaviour:
Create new rows in the build, on a table that has an AutoID Column

**Expected behavior**
Rows' auto id should increment, 1,2,3,4

**Screenshots**
![image](https://user-images.githubusercontent.com/3524181/109037326-827e9980-76c2-11eb-8c61-36982b5cfbe5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version `develop`

**Comment by rschnell** [comment]
Windows Edge Version 2.3.19

Budibase internal database

Bug remains eaxactly as described here, but it6 says it was fixed in 2021
