### ISSUE TITLE
[BUDI-7525] When fetching external tables - display errors for why certain tables cannot be fetched (e.g. no primary keys)

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11843]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase 2.10.10
  - App Version: 2.10.10

**Describe the bug**
Whenever fetching tables that don't have primary keys set, a success notification appears stating that the tables have been successfully fetched. The tables aren't synced across, I believe this is related to no primary keys being set.

**To Reproduce**
1. Your a Budibase app
2. Add a MySQL data source
3. Create a new table in it using the schema provided below
4. Try to fetch the table
5. See issue.

**Expected behavior**
Instead of a success notification, an error notification should be thrown explaining why a table failed to be fetched and synced into Budibase.

**Screenshots**
![Screen Recording 2023-09-21 at 10 59 42](https://github.com/Budibase/budibase/assets/126772285/b1080a79-d8cc-4d9c-b2b6-731ffe310462)
  
**Table create SQL**
```
CREATE TABLE noPrimaryKey (
    column1 INT,
    column2 VARCHAR(50),
    column3 DATE
);
```
**Additional context**
No console errors or network errors are thrown when this happens.

<sub>[BUDI-7525](https://linear.app/budibase/issue/BUDI-7525/when-a-mysql-table-doesnt-have-primary-keys-set-budibase-cannot-fetch)</sub>

**Related discussions**
- https://github.com/Budibase/budibase/discussions/11504
- https://github.com/Budibase/budibase/discussions/11836

**Comment by jbueter** [comment]
@ConorWebb96 Thank you for creating this issue! I just wanted to add that this issue probably exists for all types of SQL databases. At least in our case, we had the issue with PostgreSQL as well.
