### ISSUE TITLE
[BUDI-7527] Natural-sort client side svelte table

### ISSUE THREAD

**Issue by aricooperdavis** [Budibase/budibase#11840]
**Describe the feature request**
It would be nice if we could have [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order) on the client-side table element. This is only really relevant for string-type columns, such as for the first line of addresses which are often either strings (e.g. house names) or digits (e.g. house numbers).

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/8947634/2f6b869f-b624-47d9-9c79-98a805b86c30)

<sub>[BUDI-7527](https://linear.app/budibase/issue/BUDI-7527/natural-sort-client-side-svelte-table)</sub>

**Comment by mike12345567** [comment]
This would be nice, but we're concerned how this would link up with all of our backend sorting strategies, most databases will not be able to utilise natural sorting and so therefore this would never pair up well paginated data.

We could implement this just for client-side, but there are very limited places that this would actually be utilised, realistically only query results could use this - for now we're going to close this as the complexity this might introduce would out-weigh the usefulness.

If you wished to do something like this then it could make for a good custom plugin! https://docs.budibase.com/docs/custom-component
