### ISSUE TITLE
Allow plugins to contribute DatasourcePlus integrations

### ISSUE THREAD

**Issue by Samuel-Martineau** [Budibase/budibase#11867]
**Describe the feature request**
Plugins can't currently contribute `DatasourcePlus` integrations, which prevents them from having feature-parity with native data sources. _(I ran into this issue whilst trying to fully integrate [Xata.io](xata.io) into Budibase, https://github.com/Budibase/budibase/discussions/11863#discussion-5660411)_

Fixing this should only require a change to the schema validation for plugins, as they seem to behave the same as native integrations after that step.

**Comment by Samuel-Martineau** [comment]
I have prepared a pull request with what I believe to be the minimal changes required to bring feature-parity to plugins.

**Comment by Samuel-Martineau** [comment]
@mike12345567 I understand your reasons for closing the above pull request. However, even through the lack of documentation, it is quite possible to build a DatasourcePlus plugin based on the Google Sheet and Postgres examples. I am almost done building a FOSS Xata.io integration for my organization and it's quite saddening to know that we will need to run our own fork for now, just because of some schema validation rule, with all the functionality behind working.

Do you think it would be possible to unofficially / experimentally support this? Perhaps throw a warning when a "plus" plugin is detected, whilst still allowing it to function.

**Comment by mike12345567** [comment]
Hi @Samuel-Martineau - I would be interested to see the approach used to build a Xata.io integration - if it is infact possible to do this then we might consider opening up the possibility but yes we would need to add some sort of logic to warn the user that not everything will work.

Again, I should warn you that building DS+ plugins might seem possible initially, but the level to which they integrate makes them very hard to make and keep them stable - it is possible but quite a bit harder to achieve right now. There isn't any guarantee that the plugin will work with future versions of Budibase as the structure and approach used for DS+ could change, which might require a re-write of the plugin.

**Comment by mike12345567** [comment]
That would be fantastic, just to get an idea of the approach you've used, would help to support the possibility of exposing it!

**Comment by Samuel-Martineau** [comment]
@mike12345567 Sorry for the delay, the last few days have been quite busy. Here is a repo containing the code for my Xata.io DatasourcePlus integration. https://github.com/Samuel-Martineau/budibase-datasource-xata

Do you think that we could consider reopening #11868 to make this possible without having to fork the project?

**Comment by mike12345567** [comment]
Hi @Samuel-Martineau - this looks very interesting, thank you for showing us how you've approached this!

We've had a discussion about this and decided that we will merge the PR allowing DS+ plugins to be utilised. Just adding this here again though for anyone else looking into this - this is not documented, is extremely experimental and we can't really offer much support for it. If there are issues/odd bugs with DS+ plugins, we can't offer much support for this today as they are extremely complex to implement fully.
