### ISSUE TITLE
[BUDI-7548] Automation Step numbers output incorrect when using JS Scripting

### ISSUE THREAD

**Issue by JClarke90** [Budibase/budibase#11866]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image 
  - Budibase Version: 2.10.11 

**Describe the bug**
The automation steps are incorreect when testing, it doesn't seem to affect anything except the JS Scripting output from my testing.

**To Reproduce**

The helper suggests to use steps.4.value, which produces a blank output when called.

![image](https://github.com/Budibase/budibase/assets/12259768/16e4bc41-06ad-4ab7-a159-c66f0dfdea07)
![image](https://github.com/Budibase/budibase/assets/12259768/52b6bbdb-c599-4c19-8aa6-98985d536539)

When changing the input to the correct steps 5 it works correctly

![image](https://github.com/Budibase/budibase/assets/12259768/4a482aa8-624c-4303-b6fa-07866c054750)

This took me a while to figure out as it only seems to affect JS scripting, although I haven't tested every automation task. 
When using something like query rows then you need to use the step number shown on the right column.

![image](https://github.com/Budibase/budibase/assets/12259768/7fc255a7-aaa6-48a1-8c56-2af63f4d649a)
![image](https://github.com/Budibase/budibase/assets/12259768/af596906-fc1d-4d51-94a7-a28af4f8b636)

This just makes things super confusing as step 4 output just doesn't exist at all now.

The main issue with fixing this is that it would likely break a lot of automation tasks, but it should be corrected.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox/Edge
 - Version latest

<sub>[BUDI-7548](https://linear.app/budibase/issue/BUDI-7548/automation-step-numbers-output-incorrect-when-using-js-scripting)</sub>

**Comment by mike12345567** [comment]
dupe: [BUDI-7341](https://linear.app/budibase/issue/BUDI-7341/multiple-loops-in-actions-cause-the-steps-to-become-out-of-sync)

**Comment by mike12345567** [comment]
As of the latest release it is possible to use the automation name in bindings - the bindings are now unique to each step and cannot get into an inconsistent state.
