### ISSUE TITLE
Public page does not seem to be working

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1187]
**Describe the bug**
I created a new page, with access = Public. When I access the page, I get the login screen

**To Reproduce**
1. Create a public page
2. Preview and browse to it

**Screenshots**
https://www.loom.com/share/d4291505a40b42e190d0c867063e698f

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version `develop`

**Comment by shogunpurple** [comment]
This happens because that URL is not valid for a client side route, the svelte SPA router handles the navigation underneath.

If you put `http://localhost:4001/<appId>/#/stats` into the address bar, or you created a link in the builder to point to `/stats`, your page should work.

**Comment by mjashanks** [comment]
Oops, sorry. Thanks.

**Comment by azlantechnologies** [comment]
@shogunpurple Hi, what is the correct url format for client side route? My current url is this http://159.65.8.152:10000/app_dev_7a9d011ee1f8491a9498355da6073188#/asd

**Comment by Rory-Powell** [comment]
@azlantechnologies This is because the app is in development, there is a restriction on viewing development pages publicly for security purposes. If you publish your application and visit the public url you should not be redirected to login.
