### ISSUE TITLE
[BUDI-7560] Cannot duplicate query

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#11888]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.10.10

**Describe the bug**
When attempting to duplicate a query, I get an error: `Error duplicating query`

**To Reproduce**
1. Add and save a SQL query
2. Duplicate the query
3. See error

**Expected behavior**
I should be able to duplicate a query

**Screenshots**
![Screenshot 2023-09-26 at 10 45 08](https://github.com/Budibase/budibase/assets/101575380/0704857b-1c48-4e5e-8a63-5baa7eaaab62)

![Screenshot 2023-09-26 at 10 44 42](https://github.com/Budibase/budibase/assets/101575380/767375fb-bd92-444c-b92b-df0d9bb76ab6)

**Additional context**
It may be because the duplicate name would have parentheses:

![Screenshot 2023-09-26 at 10 46 21](https://github.com/Budibase/budibase/assets/101575380/60c8be3c-16eb-4ae9-aaa9-4955883734fd)

<sub>[BUDI-7560](https://linear.app/budibase/issue/BUDI-7560/cannot-duplicate-query)</sub>

**Comment by deanhannigan** [comment]
PR [https://github.com/Budibase/budibase/pull/11896](https://github.com/Budibase/budibase/pull/11896)

**Comment by offbase-solutions** [comment]
This is issue is still existing in version 2.11.16. Would love to see this issue resolved, taking too much time to create similar queries. All my queries are Rest APIs.

\

**Comment by melohagan** [comment]
![Screenshot 2023-10-12 at 16 09 48](https://github.com/Budibase/budibase/assets/101575380/5f7da563-9c3f-4eb6-a101-f440be673235)

@deanhannigan Still a minor issue with this one, then name of the query doesn't reflect the name in the list

**Comment by melohagan** [comment]
![Screenshot 2023-10-12 at 16 11 47](https://github.com/Budibase/budibase/assets/101575380/2aeaf175-7d91-47a9-9236-7559393bb0eb)

It's only for REST queries, other custom queries appear to be grand.
