### ISSUE TITLE
[BUDI-7561] Replace flatpickr

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#11894]
We have had a multitude of issues with Flatpickr (our date-picker) we want to replace it with something we have more control over (e.g. theming).

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7561](https://linear.app/budibase/issue/BUDI-7561/replace-flatpickr)</sub>

**Comment by ConorWebb96** [comment]
Closing as this is now done
