### ISSUE TITLE
Can't Install Plugins

### ISSUE THREAD

**Issue by ethanfox** [Budibase/budibase#11914]
How do you install plugins?

Whenever I paste in the URL from a GitHub repo I get an error: 
Failed to add plugin: Failed to import plugin: Only component plugins are supported outside of self-host.

**Comment by mike12345567** [comment]
Hi @ethanfox - the error message means that you are trying to import a datasource or automation plugin into the cloud platform - these are currently not allowed in the cloud for security reasons.

If you wish to use these you can self-host Budibase: https://docs.budibase.com/docs/docker
