### ISSUE TITLE
building docker single image - as default as possible - image does not work

### ISSUE THREAD

**Issue by reichert** [Budibase/budibase#11923]
Hello @shogunpurple and @melohagan

This is related to issue #11721 which is already closed (I posted there too).

I'm trying to gerenate an image for docker in a process as similar you do as possible.

I apologize for the "custom setup" (last issue created) - it was not the intention to make anything different than you do and I just realized that the docker images are generated through the github actions, so I decided to build an image by myself with near zero custom code, but apparently the same error persists.

I'll try to explain the reason, the process and the result below:

**Reason for generating an image by myself:**
- We need to proof the concept to publish budibase docker image in case we decide to make any customization on it;
- We will publish it on single image in this case;
- The [documentation](https://github.com/Budibase/budibase/blob/develop/hosting/single/README.md#build-the-image) of building docker single image does not work or it is not up to date (and does not mention about github actions);

**how we build the single docker image**
1. we forked the budibase repository to our own github account
2. we configured the secrets for github and dockerhub: DOCKER_API_KEY, DOCKER_USERNAME, PERSONAL_ACCESS_TOKEN
3. we make the following changes in /.github/workflows/release-singleimage.yml
- replaced the target of budibase image from budibase/budibase to myaccount/budibase (4 occurrences);
- changed in the checkout section of the file the submodules to false because (as we understood) if it is true we need to have access to the budibase-pro - and we just want to generate the image with open-source code;
4. we commited the changes, released a new tag on the master and we put this tag on the environment RELEASE_VERSION of github.
5. we run the action "Deploy Budibase Single Container Image to DockerHub" on actions tab of github
6. after estabilishing the process, the image was build and pushed to dockerhub

**Trying to run the image**
- we used docker run -p 8000:80 --name budibase -v ./budibase_data:/data --restart unless-stopped myaccount/budibase
- trying to access the browser pointing to container it result in an 502. We noticed through the logs that couchdb throwed some errors.
- logs attached below

How would you suggest me to go forward?

Errors that I thing are useful (full logs attached)

**couchdb does not create the database and keeps throwing errors....**
[error] 2023-09-27T12:02:33.949554Z couchdb@127.0.0.1 emulator -------- Error in process <0.397.0> on node 'couchdb@127.0.0.1' with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,400}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,375}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,404}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,97}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}

**Every request returns an 502**
[notice] 2023-09-27T12:03:49.255093Z couchdb@127.0.0.1 <0.1207.0> 8d7f2252c9 localhost:5984 127.0.0.1 undefined GET / 200 ok 0
127.0.0.1 - - [27/Sep/2023:12:04:04 +0000] "GET / HTTP/1.1" 502 150 "-" "curl/7.74.0" "-"

full docker logfile
[docker.log](https://github.com/Budibase/budibase/files/12741104/docker.log)

full github action build log
[logs_action_single_13.zip](https://github.com/Budibase/budibase/files/12741120/logs_action_single_13.zip)

_Originally posted by @reichert in https://github.com/Budibase/budibase/issues/11721#issuecomment-1737744836_

**Comment by melohagan** [comment]
> we forked the budibase repository to our own github account

We don't support project forks - sorry!
