### ISSUE TITLE
[BUDI-7571] Refetching tables deletes pre-existing views

### ISSUE THREAD

**Issue by kalinbb** [Budibase/budibase#11922]
**Checklist**

- [x] I have searched budibase discussions and github issues to check if my issue already exists
- Cloud
  - Tenant ID: genmomentum

**Describe the bug**
In the Data view, when connecting a Postgres data source and creating a view, it gets deleted after re-fetching the tables. 

**To Reproduce**
1. Go to "Create view" on any Postgres data source and save it.
2. Click on "Fetch tables" under that same data source
3. Chose tables and click "fetch tables"
4. See error - the previously created views have been deleted

**Expected behavior**
Whenever refetching the table the views should remain, unless the tables are unchecked and removed.

**Screenshots**
https://drive.google.com/file/d/1SgXabp7OGPFcs9zlEnqRtPJx1keS3vG8/view
  
**App Export**
NA

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version 116.0.5845.187 

**Additional context**
NA

<sub>[BUDI-7571](https://linear.app/budibase/issue/BUDI-7571/refetching-tables-deletes-pre-existing-views)</sub>

**Comment by ConorWebb96** [comment]
Is and issue on self-host 2.10.10 as well.

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/12470
