### ISSUE TITLE
[BUDI-7583] Filtering data provider with a `user column` does not work, the type of filter does not show and only blank. 

### ISSUE THREAD

**Issue by MikeYates** [Budibase/budibase#11958]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Docker Compose
  - Budibase Version: 2.11.0

**Describe the bug**
Filtering data provider with a `user column` does not work, the type of filter does not show and only blank. 

**To Reproduce**
1. Insert a `data provider` in a screen
2. Add a `filter column` in the `data provider`
3. Select a `User column`
4. Cannot select the type of filter for a `User Column` , but its still possible to add binding.

**Expected behavior**
Any data that is needs to be filtered according to the user will not show.

**Screenshots**
https://imgur.com/rKEBqK9

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.7.8
 - Browser: Chrome Version 117.0.5938.132 (Official Build) (x86_64)

<sub>[BUDI-7583](https://linear.app/budibase/issue/BUDI-7583/filtering-data-provider-with-a-user-column-does-not-work-the-type-of)</sub>

**Comment by mike12345567** [comment]
Hi @MikeYates - this should be resolved as of 2.11.8.

**Comment by MikeYates** [comment]
@mike12345567 Thank you 🙏 awesome work to the bb team.

**Comment by MikeYates** [comment]
@mike12345567 Hi Mike, can this be double checked. Even though the filter options shows up, but the filtering does not actually work when using a `User Column`

I tried to filter a data provider that has a `user column` with the current user email binding, data will not show. If I just use a regular text column and manually enter the user email it will work fine.

**Comment by aptkingston** [comment]
Hi @MikeYates. You'll need to filter using a user ID (`_id` column) rather than an email address. We'd like to improve this in future, but for now only the ID will work. That's also available as a current user binding.

**Comment by MikeYates** [comment]
@aptkingston Thanks for confirming it, I thought there was an issue on my app.
