### ISSUE TITLE
Relationship columns do not show contents in Preview

### ISSUE THREAD

**Issue by FloMiLe** [Budibase/budibase#1195]
**Describe the bug**
In the Budibase Builder, relationship columns in tables show the entry in the table display column of a linked row. 

a) In the preview, however, it only reads "1 related row(s)", "2 related row(s)" etc. These entries are also not clickable, so it is hard to find out which rows are related.

b) In the preview, furthermore, the details view of a row shows a too narrow grey area for a relationship column, see screenshot attached.

**To Reproduce**
1. Create the "Simple CRM" following the tutorial under [3. Getting started with Budibase and creating your first app](https://docs.budibase.com/tutorial/tutorial--setup)
2. Click on 'Preview'
3. Log in and navigate to the 'Deals List'.
4. See error.

**Expected behavior**
a) Instead of "1 related row(s)" the display name(s) of related rows should be shown, and should ideally link to the details of that row.

b) The grey area for relationship columns should be of the same height as all other fields, and show content.

**Screenshots**
<img width="650" alt="Screen Shot 2021-02-25 at 19 30 10" src="https://user-images.githubusercontent.com/13892710/109199752-1a05ea00-77a0-11eb-8bad-7707fe7a1400.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Safari
 - Budibase Builder v0.8.3

**Comment by mike12345567** [comment]
Hi @FloMiLe - I was wondering if you could send through some screenshots of your grid as well? Would it be possible to check that your app is correctly updated as well (perhaps un-install and re-install from the latest release on Github). 

This is how the Deals grid currently looks in v0.8.3
![image](https://user-images.githubusercontent.com/4407001/109384805-45472100-78e7-11eb-9a96-7aecdb6a5c1c.png)

And the row details page:
![image](https://user-images.githubusercontent.com/4407001/109384831-627bef80-78e7-11eb-8e02-635fba716675.png)

With v0.8.3 the look and feel of apps has changed quite a bit with the introduction of the form builder - just wondering, was the app you're working on started before the v0.8.3 update?
If I've gotten anything wrong here please let me know, want to get you sorted asap! :)

**Comment by FloMiLe** [comment]
Hello @mike12345567 

Thanks for your reply.

Indeed, the column "Sales Reps" does show up in the builder and the preview:

<img width="1254" alt="Screen Shot 2021-02-28 at 09 27 56" src="https://user-images.githubusercontent.com/13892710/109502933-ebd32380-7a99-11eb-90f0-89ddb7cbe340.png">

But the respective field does not occur in the details form:

<img width="1059" alt="Screen Shot 2021-03-01 at 14 21 19" src="https://user-images.githubusercontent.com/13892710/109503121-263cc080-7a9a-11eb-9078-e8543635dba1.png">

The "Simple CRM" that I had created with v0.7.8 still has the same problem. So I guess was not properly updated by the updated builder:

<img width="1246" alt="Screen Shot 2021-02-28 at 09 26 37" src="https://user-images.githubusercontent.com/13892710/109503255-52584180-7a9a-11eb-8a9d-1299b176e838.png">

Are these the screenshots you were asking for? Or can I provide anything else?

By the way, deleting and re-installing BB builder did not have any effect.

**Comment by teamkarmix** [comment]
I said stop fucking messaging me

**Comment by FloMiLe** [comment]
> I said stop fucking messaging me
> […](#)

Hello @teamkarmix 

I did not consciously message you. Have you maybe somehow subscribed to this issue? Have you tried to "Unsubscribe" on the right-hand side?

**Comment by teamkarmix** [comment]
I keep unsubscribeing and I keep getting messages

**Comment by mike12345567** [comment]
Hi @teamkarmix - I think you may have "watched" the repo, if you do not wish to receive emails about it then you might want to unwatch it. If you do not wish to receive emails from Github at all I recommend you look into disabling communication from Github.

@FloMiLe - yes this looks accurate, theres two issues here so I'll split the response in two:
1. Not showing up in the details form in the new app - this is a feature of the new forms, they don't automatically populate with new fields as they are added, if you look through your components you'll see there is a `Field Group`, when clicked into this you'll see a `Reset Fields` option in the settings, clicking this will update the form with all the current attributes from the table. The reason we have had to do this is that forms are now a lot more dynamic, you can add and remove properties of a row from being editable/displayed as you see fit. If you always updated the forms automatically when the table was altered this would likely lead to forms being changed/broken. You can see the field group and reset fields button in the below images.
![image](https://user-images.githubusercontent.com/4407001/109504779-d65afb00-7a93-11eb-8ab2-6d39545f0fc0.png)
There is still some discussion in the team around this as to how we can make this more obvious, we may be making changes here (for example the ability to update all forms linked to a specific table).

2. The old app not being updated, right now there isn't a great way to update apps, we are trying to make sure that breaking changes aren't made and that old apps will continue to work, but we haven't implemented a system for "updating" an old app. This is something that is in discussion and we will be approaching in the near future, you can see discussions around this problem in #1222.

**Comment by teamkarmix** [comment]
Thanks, I'll take a look.

**Comment by FloMiLe** [comment]
@mike12345567, thanks a lot!! You have sorted out all my problems.

Maybe just one minor thing to add: I find it a bit confusing that the "Field" field somehow filters the available columns.

<img width="253" alt="Screen Shot 2021-03-01 at 15 02 10" src="https://user-images.githubusercontent.com/13892710/109507650-3dca7800-7a9f-11eb-884f-f6007b348ebc.png">

**Comment by mike12345567** [comment]
Hi @FloMiLe glad I could help!

I'm not 100% sure what you mean on the field filtering available columns, when you reset the fields on a field group it will fetch all of the fields on the table and generate inputs for al of them. It will use the correct input based on the form dropdown as such:
![image](https://user-images.githubusercontent.com/4407001/109508202-80885200-7a97-11eb-92e1-c5a82ad75ac0.png)

Each of these different input types will only show the fields on the table that they can manipulate, so in this case a relationship picker input can only alter one of the relationships on a row. In your image you're seeing the two auto columns `Created by` and `Updated by` as these are relationship types which the relationship picker could display (in this case they cannot be edited as they are auto-columns, the input will always be disabled).

Does that answer the question? I might have misunderstood, let me know if it doesn't!

**Comment by FloMiLe** [comment]
@mike12345567, thanks again!

It indeed does make sense to filter for input type. Being a total BB beginner, I did not know that a field's type is kind of fixed and not altered on the fly according to the selected column.

In this case, I have a suggestion: How about showing the form field type in the right-hand settings menu? I would actually it instead of the field's name, which currently occurs twice (directly under "Settings" and in the input field "Name").

**Comment by mike12345567** [comment]
Hi @FloMiLe thats ok, we're still working on making all of this clear through docs and the app itself, your insights into what has been difficult and so on is very helpful! 

I agree, adding the type of component on the right would actually be very helpful, doubling up on the component name as well really isn't useful, that does seem like the ideal place to put it! I'll have a look at that and try get it in! 

Thanks again for your input, its of great help!
