### ISSUE TITLE
[BUDI-7585] Error on testing "SEND EMAIL (SMTP)" automation

### ISSUE THREAD

**Issue by ArthurLERAY** [Budibase/budibase#11952]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: handipharm

**Describe the bug**
After creating an automation to send email via SMTP, I get two errors when clicking "Finish and test automation".

The first one is `Cannot read properties of undefined (reading 'primaryDisplay')` on click and then a GET 404 on `https://handipharm.budibase.app/api/.../rows` with a message `deleted`.
After clicking, I can't go to any other tab ("Data", "Design", ...) and nothing seems to work.

**To Reproduce**
1. Go to 'Automation'
2. Create a trigger on row created
3. Create a first step to send email via SMTP
4. Fill fields "Send To" and "Send From" with an email address
5. Fill email subject with some words
6. Fill HTML Contents with some basic HTML or leave empty

**Expected behavior**
Nothing will happen. Then, when looking into the developper console, 2 errors will appear as described earlier.

**Screenshots**
  
<img width="460" alt="Capture d’écran 2023-10-02 à 17 57 05" src="https://github.com/Budibase/budibase/assets/56477022/e4c052f6-3863-4813-b321-0008ab7467e9">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5
 - Browser Google Chrome
 - Version 116.0.5845.187

<sub>[BUDI-7585](https://linear.app/budibase/issue/BUDI-7585/error-on-testing-send-email-smtp-automation)</sub>

**Comment by melohagan** [comment]
Hi @ArthurLERAY 

I am unable to recreate this. Could you please provide more information about the automation trigger please?

Is this Row Created trigger for an internal DB, or an external DB? What fields are involved, can you provide the schema?

Can you share an app export please, and/or a recording demonstrating the issue.

**Comment by FGRibreau** [comment]
- It's a row trigger from an internal DB (see the automation here: https://handipharm.budibase.app/builder/app/app_dev_handipharm_be4376b50e1a409c9c222e61e1d8a767/automation/au_11489051db9c470caa314ffb1da
- ![Sans titre](https://github.com/Budibase/budibase/assets/138050/b5ab6fc2-bee7-4e61-af68-7f4ac35dc397)
0e6a1 )

Regarding the export to what email can we send it?

**Comment by melohagan** [comment]
@FGRibreau You can send the export to support@budibase.com

**Comment by ArthurLERAY** [comment]
@melohagan I've just sent the app export to the support email address.
Let me know if you have any issue with the export

**Comment by melohagan** [comment]
> @melohagan I've just sent the app export to the support email address. Let me know if you have any issue with the export

I wasn't able to import the the app, possibly because I'm on a Mac and the export was a zip. 

I tried to reproduce as demonstrated by @FGRibreau screenshot, however I am seeing no issues. Can you make sure you are update to date with the latest **2.11.5**.

Any recordings demonstrating the bug would also be useful.

**Comment by ArthurLERAY** [comment]
I just updated our app version from 2.11.3 to 2.11.5 but it's still not working.


Demonstration: https://github.com/Budibase/budibase/assets/56477022/439189f9-75ae-4c5f-bd72-b079f2a12b7f

**Comment by melohagan** [comment]
Hey @ArthurLERAY 

I'm still unable to reproduce this. As I can't make use of your app export, could you please export your `related` table as a CSV, and provide screenshots of the column data types.

Also provide screenshots of how your relationships are configured, and I will try to replicate.

You could also try creating a new automation and see if the error occurs for it

**Comment by ArthurLERAY** [comment]
Hey @melohagan,
I tried to delete and re-create the automation and it "worked" better but I'm still unable to test.

Demo: 
https://github.com/Budibase/budibase/assets/56477022/9871a5aa-ef93-4774-b091-f24d0bd5792b

We have 2 tables:
- requests
- agencies

**Requests**
id: Number Auto ID, (required) // Display column
delivery_date: Date/Time, (required)
delivery_type: Options, (required)
lastname: Text, (required)
firstname: Text, (required)
agency: Relationship - Many rows in requests | To one row in agencies, (required)

**Agencies**
name: Text, (required) // Display column
requests: Relationship - Many rows in requests | To one row in agencies, (required) -> created by BudiBase

Is this enough informations for you to replicate ?

**Comment by melohagan** [comment]
Thanks @ArthurLERAY 

I had a go at replicating, but had no luck. I did notice however at the end of your video, this error:

![Screenshot 2023-10-04 at 10 34 23](https://github.com/Budibase/budibase/assets/101575380/36255b4b-aaa4-47b9-a83f-47fa6fb9a103)

It appears that the table within Budibase has been removed from couchdb somehow.

You could try recreating the tables (export data to a CSV first if needed and re-import).

**Comment by ArthurLERAY** [comment]
I tried to delete the **requests** table but I get an error on the DELETE request :
![Capture d’écran 2023-10-04 à 12 25 42](https://github.com/Budibase/budibase/assets/56477022/e3936983-a19c-4dce-ab95-0022e79f27ab)

Could it be because I am using this table in a form ?

Also, I noticed that when importing JSON with schema, the boolean fields are not recognized and are labeled as null

**Comment by melohagan** [comment]
> Could it be because I am using this table in a form ?

I don't think so.

Do you have any active extensions / plugins in your web browser?

**Comment by melohagan** [comment]
> I tried in an Incognito window with no extension allowed and I still can't delete the table.
> 
> Here is a recording of the error on delete : https://github.com/Budibase/budibase/assets/56477022/6e94bb01-703b-42e1-acf9-5ff518ad642d

Could you try deleting the relationship columns first, and then delete the table?

Otherwise the app itself may have got into a bad state, and you could try creating a new app.

**Comment by ArthurLERAY** [comment]
Hey,
I tried deleting the relationship column but I get a 404 deleted:
https://github.com/Budibase/budibase/assets/56477022/d9a2412c-530e-44cb-8503-90029a60c9c2

After refreshing, it appears that the row was deleted anyway.
I still can't delete the `requests` table, so it must be the app that got into a bad state.

I'll try to create a new app, create the same tables architecture and see if the automation works.
If it does, is there any way to copy design screens from an app to another ?

**Comment by melohagan** [comment]
>  is there any way to copy design screens from an app to another ?

@ArthurLERAY currently this isn't possible, however you could also try exporting the app, and importing it as a brand new app. 
When the app is imported, it should create new tables, which may help to fix the problem.

**Comment by ArthurLERAY** [comment]
Hi @melohagan,
I just tried to export the app, create a new one and import the files but it does not work.

I removed the relationship column and the automation before the export.
I have the exact same error when creating a new automation on the new app.

**Comment by melohagan** [comment]
Hey @ArthurLERAY Could you send an app export to support@budibase.com please?

**Comment by melohagan** [comment]
@ArthurLERAY I've pushed up a fix, as of version **2.11.14**, that will allow you to delete relationship columns even in the rare event that the linked table is missing.

Could you try updating now and deleting the `equipment_id` column. I believe that will resolve the automation problems you were seeing.

**Comment by melohagan** [comment]
@ArthurLERAY That error message is certainly not very helpful, but it may be a configuration issue. Are the **Send To** and **Send From** fields definitely valid email addresses?

**Comment by ArthurLERAY** [comment]
@melohagan Yes both are valid email addresses :
<img width="931" alt="Capture d’écran 2023-10-08 à 13 07 59" src="https://github.com/Budibase/budibase/assets/56477022/4326e6c1-fc2c-490d-b3d9-1fd5c9aaf2cb">

I tried with one of my own email address for the **From** field but without success

**Comment by melohagan** [comment]
Thanks @ArthurLERAY 

If you publish the app and test the automation in your published app, is it also failing? Perhaps the SMTP settings are  misconfigured?

**Comment by melohagan** [comment]
> I just tried after publishing the app but it does not work.
> 
> Am I able to edit the app SMTP settings somewhere ?

Yep, there's an email in the portal: https://docs.budibase.com/docs/email

**Comment by ArthurLERAY** [comment]
Hi @melohagan,
Works perfectly thanks a lot !
