### ISSUE TITLE
Export all rows only exports 1000 rows

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#11969]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker compose
  - Budibase Version: 2.11.9 
  - App Version: 2.11.9 

**Describe the bug**
The export rows dialog says that it will export all rows from a database when it only exports 1000 rows

**To Reproduce**
1. Create and app
2. Upload over 1000 rows of data
3. Press the export button
4. Press export on the dialog popup
5. The file export only contains 1000 rows

**Expected behavior**
Either all rows are exported or the dialog box tells you that only 1000 rows will be exported

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/97764630/c15b7a5e-74dd-43c4-a018-6b3e3d251309)

**Comment by mike12345567** [comment]
Hi @FlaminWrap - this is a limitation of the internal DB today - it can only extract 1000 rows via a filter. We cannot extend this limit - although there is some work going on towards the internal DB that will lift this limit at some point in the future - however this is a little while away still.

Going to close this issue for now as it is not possible to rectify today, but once we have completed the technology transition behind the internal DB this limit will be lifted.
