### ISSUE TITLE
[BUDI-7587] Unable to import application

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#11960]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker via hossted
  - Budibase Version: 2.11.0

**Describe the bug**
Due to issues with cloud hosted version (https://github.com/Budibase/budibase/issues/11855#) I have been trying to migrate to a self-hosted version, which I have running via hossted on AWS.
When I try to import a application which has been exported from my cloud version, the import fails with the message in console of 'Cannot import a non-text based file.'
![image](https://github.com/Budibase/budibase/assets/110813989/af7added-b081-41cb-8991-deabce4cf4e7)
I have tested importing back to a cloud tenant and it also shows this issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Export an application 
2. Create a new application and try to use the exported file to import into the application
3. View error shown in builder and console

**Expected behavior**
The application should import.
  
**App Export**
I will provide this privately is needed.

**Desktop:**
 - OS: Windows 10
 - Browser: Edge for Buisness
 - Version: 117.0.2045.43

<sub>[BUDI-7587](https://linear.app/budibase/issue/BUDI-7587/unable-to-import-application)</sub>

**Comment by andyburgessmd** [comment]
[Andrews app-export-1696339861234.tar.zip](https://github.com/Budibase/budibase/files/12793026/Andrews.app-export-1696339861234.tar.zip)
Unable to add as tar.gz so had to zip it to get it to be attached.
This a very simple application I have just created - 1 table with 1 row and 1 screen. I have tried to import this to new self hosted tenant and it fails.

**Comment by aptkingston** [comment]
I'll take a look - thanks for the export.

**Comment by aptkingston** [comment]
Does that export fail if you import it into cloud as well?

**Comment by andyburgessmd** [comment]
@aptkingston yes it fails on cloud as well

**Comment by aptkingston** [comment]
Could you email me the unzipped version, just exactly as you got it from Budibase? That test app is fine.
andrew[at]budibase.com

**Comment by andyburgessmd** [comment]
Sent, hopefully my outbound email won't block it

**Comment by aptkingston** [comment]
Looks like it might have been blocked because I didn't receive anything. Are you able to jump on discord?

**Comment by andyburgessmd** [comment]
Sent from my gmail instead

**Comment by aptkingston** [comment]
That export works fine for me, tested in both cloud and self host. I really can't think of a reason why this wouldn't work for you, especially in cloud... Do you get that same HTTP 500 with "Cannot import a non-text file" in cloud too?

**Comment by andyburgessmd** [comment]
@aptkingston I have also just sent the file to my mac and tested from that and it did work. Could this be down to the way that windows is handling the file?

**Comment by melohagan** [comment]
I tried this on cloud via a Windows laptop and could not reproduce, it worked fine.

**Comment by melohagan** [comment]
Hey @andyburgessmd 

I was able to replicate the `Cannot import a non-text based file` error. I received this when trying to import the app export as provided, i.e. with the `.tar.zip` format. This is invalid.

App exports must have the file extension `.tar.gz` to be imported into Budibase. 

I was able to import your app by extracting the files from your zip file, and running the following command:

```sh
tar -cvzf andrews.tar.gz -C Andrews .
```

<img width="190" alt="Screenshot 2023-10-04 at 10 14 35" src="https://github.com/Budibase/budibase/assets/101575380/1aa937a7-bbec-4010-bf95-fa00b839205c">

**Comment by andyburgessmd** [comment]
@melohagan the file was zipped so that it could be transferred, sending the .tar.gz was being blocked.
"Unable to add as tar.gz so had to zip it to get it to be attached."
I was trying to import the .tar.gz file

**Comment by melohagan** [comment]
> @melohagan the file was zipped so that it could be transferred, sending the .tar.gz was being blocked. "Unable to add as tar.gz so had to zip it to get it to be attached." I was trying to import the .tar.gz file

Could you please upload the `.tar.gz` file to a cloud drive and send through a download link please?

**Comment by andyburgessmd** [comment]
@melohagan 
https://drive.google.com/file/d/1d4kPM6TfAY_4r9UGmNRInUWO0lzwWSqs/view?usp=sharing

**Comment by melohagan** [comment]
Imports for me on cloud and self-hosted. Will try on Windows later on.

**Comment by melohagan** [comment]
Hey @andyburgessmd I tried importing that app export you provided on a Windows laptop, and it was fine. I'm not really sure what to suggest.

**Comment by andyburgessmd** [comment]
Thanks for testing @melohagan. I'm going to raise it with our group IT, I bet they have done something annoying like scan it and strip out something.
I'll let you know what they say if its relevant.
