### ISSUE TITLE
[BUDI-7593] External datasource formulas don't allow for relationship fields to be outputted in formula columns.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11972]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.11.8
  * App Version: 2.11.8

**Describe the bug**
When trying to display relationship fields values attached to records in an external data source nothing happens. When you select for example `{{ jobs.0.job_title }}` which does have a value for a formula column nothing appears after saving. You can output the `{{ jobs }}` but this only outputs the `primaryDisplay` and the `_id`.

**To Reproduce**

1. Import the app export
2. Use the Postgres dump schema to create the 2 tables
3. Use the insert data to add data to the tables
4. Connect your Postgres data source and fetch the tables
5. Go to the formula field in the users table, edit and try select a job field binding and save
6. Nothing appears even though there is data in that relationship field

**Expected behavior**
You should be able to access the relationship fields within a formula column. It should output and display whichever one is selected. This did work previously for external data sources but seems to not be working anymore.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/4f8cdab3-9a16-4ddb-9896-1f24199edd41/a4f2ebf3-ac7c-42e9-ba55-707080fee9f7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC80ZjhjZGFiMy05YTE2LTRkZGItOTg5Ni0xZjI0MTk5ZWRkNDEvYTRmMmViZjMtYWM3Yy00MmU5LWJhNTUtNzA3MDgwZmVlOWY3IiwiaWF0IjoxNjk4ODI3MjM2LCJleHAiOjE2OTg5MTM2MzZ9.6mRJHKm1iL6oyogLMkf3Ub6\_-uDWofIcHB7GgQ9vrCo)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/4449d86d-f00e-4945-a0a1-1a14be269463/832fa2c3-4d04-4bda-bbb2-f8401b1ed834?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC80NDQ5ZDg2ZC1mMDBlLTQ5NDUtYTBhMS0xYTE0YmUyNjk0NjMvODMyZmEyYzMtNGQwNC00YmRhLWJiYjItZjg0MDFiMWVkODM0IiwiaWF0IjoxNjk4ODI3MjM2LCJleHAiOjE2OTg5MTM2MzZ9.ZU3TEQwA6kwAhmUT0drrXahBF9UGqhx8R3SBnpgW4yY)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f8167a08-3f09-4084-8092-75e6760f0182/69a38869-931e-474b-90d6-33c42e23ad66?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9mODE2N2EwOC0zZjA5LTQwODQtODA5Mi03NWU2NzYwZjAxODIvNjlhMzg4NjktOTMxZS00NzRiLTkwZDYtMzNjNDJlMjNhZDY2IiwiaWF0IjoxNjk4ODI3MjM2LCJleHAiOjE2OTg5MTM2MzZ9.tE4WyhmwttEbLPjM_C6AHMgi_3Buma9mYkpsuI5JL84)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/8622d475-ac18-4c19-adce-9e206af6b813/32478812-d7f5-4e7f-95a9-1c90d30abf50?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC84NjIyZDQ3NS1hYzE4LTRjMTktYWRjZS05ZTIwNmFmNmI4MTMvMzI0Nzg4MTItZDdmNS00ZTdmLTk1YTktMWM5MGQzMGFiZjUwIiwiaWF0IjoxNjk4ODI3MjM2LCJleHAiOjE2OTg5MTM2MzZ9.wrHqnAfQfseKVgherfvmBv3zeeTbwHtCFtrTCnUmIQk)

**App export**
[formula regression-export-1696424095194.tar.gz](https://github.com/Budibase/budibase/files/12803523/formula.regression-export-1696424095194.tar.gz)

**Schema dump**

```
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2 (Debian 15.2-1.pgdg110+1)
-- Dumped by pg_dump version 15.4 (Debian 15.4-2.pgdg120+1)

CREATE TABLE public.jobs (
    job_id integer NOT NULL,
    job_title character varying(255) NOT NULL,
    user_id integer
);


ALTER TABLE public.jobs OWNER TO postgres;

--
-- Name: jobs_job_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.jobs_job_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.jobs_job_id_seq OWNER TO postgres;

--
-- Name: jobs_job_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.jobs_job_id_seq OWNED BY public.jobs.job_id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    username character varying(255) NOT NULL,
    gender text,
    "Pets" boolean
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_user_id_seq OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users.user_id;


--
-- Name: jobs job_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs ALTER COLUMN job_id SET DEFAULT nextval('public.jobs_job_id_seq'::regclass);


--
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (job_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: jobs jobs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--
```

**SQL insert dummy data**

```
INSERT INTO users (username, gender, pets) VALUES
    ('user1', 'Male', true),
    ('user2', 'Female', false);

INSERT INTO jobs (job_title, user_id) VALUES
    ('Job 1', 1),
    ('Job 2', 1),
    ('Job 3', 2);
```

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Brave
* Version 1.58.135

**Additional context**
No errors in the console, no network errors either.

Discussion were the issue was discovered can be found [here](https://github.com/Budibase/budibase/discussions/11967).

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7593](https://linear.app/budibase/issue/BUDI-7593/external-datasource-formulas-dont-allow-for-relationship-fields-to-be)</sub>

**Comment by ConorWebb96** [comment]
MySQL DBs are also affected.

Additional discussion showing this [here](https://github.com/Budibase/budibase/discussions/12228).

**Comment by mike12345567** [comment]
This will be fixed in the next release.
