### ISSUE TITLE
Column order in Data > Internal tables not persistent

### ISSUE THREAD

**Issue by FloMiLe** [Budibase/budibase#1197]
**Describe the bug**
In the Data view in Budibase builder, table columns can be re-arranged. However, their order is reset every time one comes back to that table.

**To Reproduce**
1. Go to Data > Internal > some table.
2. Re-arrange some columns.
3. Go to another table, and come back to the first one.

**Expected behavior**
The order of the table columns should be persistent, i.e. as it was when the table view was left.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Safari
 - Budibase Builder v0.8.3

**Comment by mike12345567** [comment]
Hi @FloMiLe - this is something we know about, currently we don't store the order of columns, this is something we have planned to solve at some point though in the near future. I'm going to change this to an enhancement as we haven't implemented this feature yet, we'll update this issue once its implemented.
