### ISSUE TITLE
budi hosting --init doesn't check for Docker with Compose plugin

### ISSUE THREAD

**Issue by IvanDrag0** [Budibase/budibase#11982]
Currently, when using the Budibase CLI and running `budi hosting --init`, the program checks to make sure that Docker and docker-compose are installed. If one of them is missing, the program errors out. Based on the `checkDockerConfigured()` function in [utils.ts](https://github.com/Budibase/budibase/blob/develop/packages/cli/src/hosting/utils.ts), it looks like the app is checking for the presence of the docker and docker-compose programs.

```
export async function checkDockerConfigured() {
  const error =
    "docker/docker-compose has not been installed, please follow instructions at: https://docs.budibase.com/docs/docker-compose"
  const docker = await lookpath("docker")
  const compose = await lookpath("docker-compose")
  if (!docker || !compose) {
    throw error
  }
}
```

However, the program doesn't check for the [Compose plugin](https://docs.docker.com/compose/install/linux/) (which is the preferred method over using docker-compose). The function should be edited to check whether the Compose plugin is being used as well.

**Comment by webtop** [comment]
Just started to set this up, and I see the error.

[paul.allsopp@office-server budibase]$ docker compose version
Docker Compose version v2.26.1
[paul.allsopp@office-server budibase]$ docker -v
Docker version 26.0.2, build 3c863ff
[paul.allsopp@office-server budibase]$ budi hosting --init
[20:51:50.639] INFO (22766): Error - docker/docker-compose has not been installed, please follow instructions at: https://docs.budibase.com/docs/docker-compose {"tenantId":"default"}
