### ISSUE TITLE
[BUDI-7609] Foreign key violation error despite the data looking good on the http request to save a row

### ISSUE THREAD

**Issue by kpturner** [Budibase/budibase#12005]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: monito.budibase.app  

**Describe the bug**
We have a simple parent table called `provider` keyed by a character field called `slug`.
There is a child table called `provider_link` which has a primary key (foreign key constraint) to `provider`.
`provider_link` also has optional foreign keys to tables called `country` and `currency`
When we use the `Save row` action to create/save rows on the `provider_link` table with the `country` and `currency` foreign keys left unpopulated, they are included in the payload with a value of `null`. However the `rows` http request returns a `Foreign key violation` error.  The "Save Row" will only work if all the foreign keys are populated, despite them being optional in the DB.

This functionality was working fine.  It seems to have stopped working for no reason. 

**To Reproduce**
You would need to use our test app to see this failing.  Details available.

**Expected behavior**
We would expect the functionality to save the row properly, or at least provide a little more insight than simply `Foreign key violation`. 

**Screenshots**
Here is the payload
<img width="750" alt="image" src="https://github.com/Budibase/budibase/assets/308646/15d337ce-9376-4328-b13e-689ef411a68c">

This is the less than useful response
![image](https://github.com/Budibase/budibase/assets/308646/8b4f4280-eac1-44fc-828b-9edef1ad58fa)

  
**App Export**
This can be emailed privately to support if need be

<sub>[BUDI-7609](https://linear.app/budibase/issue/BUDI-7609/foreign-key-violation-error-despite-the-data-looking-good-on-the-http)</sub>

**Comment by kpturner** [comment]
I hoped this would be a clue https://github.com/Budibase/budibase/discussions/11498
but setting the foreign keys to blank results in the same Foreign key violation error.

**Comment by melohagan** [comment]
Hey @kpturner 

SQL schemas for the tables involved would be useful, as well as how the relationships are defined in Budibase.
https://docs.budibase.com/docs/troubleshooting-sql

What database are you using?

**Comment by kpturner** [comment]
> Hey @kpturner 
> 
> 
> 
> SQL schemas for the tables involved would be useful, as well as how the relationships are defined in Budibase.
> 
> https://docs.budibase.com/docs/troubleshooting-sql
> 
> 
> 
> What database are you using?

PostgreSQL.

The schema has benn emailed to support on more than one occasion and has not changed. Do you need it again?

**Comment by melohagan** [comment]
Thanks @kpturner Providing the table schema when raising bugs relating to SQL is always going to be helpful, but I'm sure I can find it.

**Comment by melohagan** [comment]
Hey @kpturner Going to close this one as it does not appear to be a bug.

When trying to perform an insert statement directly against the Postgres DB I also receive the foreign key constraint violation error:

<img width="1079" alt="Screenshot 2023-11-01 at 10 02 23" src="https://github.com/Budibase/budibase/assets/101575380/3ba03aee-80db-476e-9377-c86d17af6c1d">

**Comment by kpturner** [comment]
> Hey [@kpturner](https://github.com/kpturner) Going to close this one as it does not appear to be a bug.
> 
> When trying to perform an insert statement directly against the Postgres DB I also receive the foreign key constraint violation error:
> 
> <img alt="Screenshot 2023-11-01 at 10 02 23" width="1079" src="https://private-user-images.githubusercontent.com/101575380/279640307-3ba03aee-80db-476e-9377-c86d17af6c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM0MTc3NjAsIm5iZiI6MTc0MzQxNzQ2MCwicGF0aCI6Ii8xMDE1NzUzODAvMjc5NjQwMzA3LTNiYTAzYWVlLTgwZGItNDc2ZS05Mzc3LWM4NmQxN2FmNmMxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMzMVQxMDM3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjk1YzkyNDYwNDM2YTBlNmQ5NmUwOGRmNjU0OWM5ZWVlNWQ4NTA1ODk3ZmRmYWIxN2M3YzZiYzNkMDA1YTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kkgrgrTObRl6GXOKAVSspwG6JoKsRsocjUyX7W-Vwe4">

Probably because (before trying it) you haven't actually made sure that there is a record in the `provider` foreign table with a value of `slug` in the key field (`slug`)
