### ISSUE TITLE
[BUDI-7608] Wrong sorting Date/Time values stored when using bind of Form Date Picker

### ISSUE THREAD

**Issue by SynologyUser** [Budibase/budibase#12009]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists
Same bug as  #2108 and also mentioned in  #2537 

**Hosting**
- Self
  - Method: Docker image
  - Budibase Version: version 2.10.12
 
**Describe the bug**
If I use bind in date picker {{date now "MMMM D, YYYY" "Europe/Paris"}} to set the default value, the date entry is not sorted correctly (within the other dates entered).
If I just click on the same date (so today) within the date picker, then the sorting is OK.
Both cases are recorded in the Budibase database with the same date and time.
Also very strange (maybe related to the same bug) is that a filter on the Budibase database on date ("equals value" date) will show no rows, even if these dates are present in the Budibase database.  

**To Reproduce**
See description, sorry I am no expert in this matter.

<sub>[BUDI-7608](https://linear.app/budibase/issue/BUDI-7608/wrong-sorting-datetime-values-stored-when-using-bind-of-form-date)</sub>

**Comment by ConorWebb96** [comment]
This seems to be working as intended on the latest version. @SynologyUser, could you give it a test on your end and see if it is working for you now as well. 2.11.16 is the version i've tested this on.

**Comment by SynologyUser** [comment]
Hello Conor, 

Thank you for checking.
I have installed the latest version now (2.11.33) and tested it again as requested.
The outcome was still the same as per my test with version 2.10.12.

I have done 2 tests.

A) 1 without touching the date in the date picker (so leaving it on the "Default value" = "{{date now "MMMM D, YYYY" "Europe/Paris"}}" = "October 16, 2023".
> resulting in an entry which could not be properly sorted by date (arriving after the latest date in my database = "January 30, 2024")

B) 1 with selecting the date in the date picker, so clicking on the 16th of October, resulting in the same database entry of  "October 16, 2023". (To be sure, I have clicked first on another date and clicked back on today.)
> this entry did sort correctly, after "October 9, 2023" and before "October 30,2023".

I am not sure why we get different test results but are you trying the first entry without even opening/clicking on the date picker?

According to these results, the bug still exists and has to do with how the "Default value" (text entry) is treated by your program.

For what it is worth, I am using Docker Desktop on Windows. 
I have a linux machine I could test it on as well if you really think this could have an influence, but then I need to set docker on this machine first etc (it is not supposed to be used for this purpose).

**Comment by ConorWebb96** [comment]
Hey @SynologyUser,

Can I ask what database you are using? 

The one i've tested with is the internal Budibase database. All the date related filtering seems to work. (I've supplied a gif below showing this working.) Happy to attach the app export if you'd like, so you can have a more in-depth look at everything.

![Screen Recording 2023-10-17 at 08 22 53](https://github.com/Budibase/budibase/assets/126772285/457b4b7a-89df-4d75-a3f5-134994dcc237)

Can you provide an app export replicate this issue so I can have a look at that? If you are using an external database then you'll likely need to send across your table schema as well.

Thanks in advance!

**Comment by andz-bb** [comment]
couldn't recreate, happy to reopen if more detail provided
