### ISSUE TITLE
[BUDI-7616] CONTRIBUTE.md seems to be outdated and not really working in general

### ISSUE THREAD

**Issue by j-mir-prazak** [Budibase/budibase#12028]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: develop
  - App Version: develop

**Describe the bug**
CONTRIBUTE.md contains some outdated informations and yarn build:docker:single:image does not work due to missing @budibase packages. 

DEV-SETUP-DEBIAN.md says node v14, but the yarn pull fails without node v16 and build fail without v18. 

In all cases build:docker fails while yarn pull packages and @budibase packages are missing.

**To Reproduce**
1. setup dev env as described in docs
2. clone repo
3. try to build and build image

**Expected behavior**
Being able to build single bbapps image from source

**Desktop (please complete the following information):**
 - OS: fedora 37; debian 12 (docker container)

**Additional context**
testing with yarn dev runs the server, but chrome gets stuck loading. setting the file descriptors limit does not seem to do the trick (as in DEV-SETUP-DEBIAN)

<sub>[BUDI-7616](https://linear.app/budibase/issue/BUDI-7616/contributemd-seems-to-be-outdated-and-not-really-working-in-general)</sub>

**Comment by mike12345567** [comment]
This has all been updated.
