### ISSUE TITLE
[BUDI-7619] Budibase on Azure Container Instance returns 502

### ISSUE THREAD

**Issue by tinomerl** [Budibase/budibase#12038]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Azure Container Instance
  - Budibase Version: Latest
  - App Version: Latest

**Describe the bug**
After restarting our Budibase on Azure Container Instance we suddenly get a 502 error and can't access anything of budibase. 
<img width="245" alt="image" src="https://github.com/Budibase/budibase/assets/35485536/c286c57b-f1ca-49f7-b59b-1dd27115d838">

To rule out it has something to do with our setup i tried with a completly fresh setup, [following this guide.](https://docs.budibase.com/docs/azure-container-instances) But on the fresh instance we also got a 502 and can't access even the login page. What i also found out is that after the restart the CPU Usage spiked and didn't return back to low.

<img width="1675" alt="image" src="https://github.com/Budibase/budibase/assets/35485536/bd8cee5f-5553-4d3b-b1ed-10c52c5880ac">

**To Reproduce**
1. [Follow this guide.](https://docs.budibase.com/docs/azure-container-instances) Although the steps are not completly correct anymore. In the last step, when creating the container you need to use `budibase/budibase-aas:latest` instead of `registry.hub.docker.com/budibase/budibase-aas:latest` for the `--image` flag.
2. Try to access the newly created instance.

**Expected behavior**
Access Budibase
  
**App Export**
Cannot since i cant access budibase anymore.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Happens on Chrome and Firefox

**Additional context**
Added Exported logs
[budibase-aci-logs.txt](https://github.com/Budibase/budibase/files/12872230/budibase-aci-logs.txt)

<sub>[BUDI-7619](https://linear.app/budibase/issue/BUDI-7619/budibase-on-azure-container-instance-returns-502)</sub>

**Comment by tinomerl** [comment]
Ok So just after posting this issue i gave it one last try and looked in the docker image layers over [here](https://hub.docker.com/layers/budibase/budibase-aas/latest/images/sha256-6999a23b801d011201079a3b3659eaa4b172f084183219d0b6f883b07840daee?context=explore). I gave it a shot, logged into the docker container via `az container exec` and ran `source runner.sh`. This worked and it started working again. However, this behaviour is completly new and we never had to start the runner process manually before today.

**Comment by Lassenoerre** [comment]
I have experienced the same issue since Monday.
I have been able to successfully run a fresh install of Budibase, but I have to revert back to v2.7.36 - Everything from v2.8.0 and newer will cause a 502 bad gateway on a fresh setup for me.

**Comment by tinomerl** [comment]
Since Friday restarting the Container Instance doesn't produce any 502 anymore. The CPU Usage also returned to normal.

![image](https://github.com/Budibase/budibase/assets/35485536/1de817a7-27c1-4b5e-ae0f-fbf6d039a134)

**Comment by aptkingston** [comment]
Closing as this seems to be resolved. If this happens again feel free to raise a new issue.
