### ISSUE TITLE
Deployed app Webhook trigger error: "Session not authenticated"

### ISSUE THREAD

**Issue by arladmin** [Budibase/budibase#1204]
**Describe the bug**
On triggering an automation with Webhook trigger, an error message is received as the webhook response, "Session not authenticated". The trigger works fine for localhost.

**To Reproduce**
1. Create a new automation
2. Select Trigger - Webhook
3. Add any action or just leave it like this
4. Deploy the app
5. Call the newly generated webhook
6. Response received: 
`{
    "message": "Session not authenticated",
    "status": 403
}`

**Expected behavior**
The automation should continue normally and the webhook should send a success response.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10 Pro
 - Browser [e.g. chrome, safari] Chrome 88.0.4324.182
 - Version [e.g. 22] 0.8.3

**Additional context**

**Comment by mike12345567** [comment]
Hi @arladmin thanks for reporting this, likely an issue with the permissions update in 0.8.3 - this will be an easy fix, will get a patch out for this soon!
