### ISSUE TITLE
I cannot see the option for AutoTypes for internal table creation

### ISSUE THREAD

**Issue by LenWagner** [Budibase/budibase#12063]
**Checklist**
- [ ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

**Comment by ConorWebb96** [comment]
Closing as no information was provided. In future please follow the bug template.
