### ISSUE TITLE
[BUDI-7625] I can't edit my screens

### ISSUE THREAD

**Issue by miguelet17** [Budibase/budibase#12066]
Hello 

![Captura de pantalla 2023-10-14 a las 20 45 03](https://github.com/Budibase/budibase/assets/9483801/647c8866-bd5f-48ee-a4fa-b46db2d8477f)
You can't edit anything on the screen, if I try to edit a text the server returns 500.

{
  "browser": {
    "language": "es-ES",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "platform": "MacIntel",
    "vendor": "Google Inc."
  },
  "server": {
    "budibaseVersion": "2.11.33",
    "hosting": "docker-compose",
    "nodeVersion": "v18.18.1",
    "platform": "linux",
    "cpuArch": "x64",
    "cpuCores": 2,
    "cpuInfo": "Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz",
    "totalMemory": "1.8763923645019531GB",
    "uptime": "1 day(s), 0 hour(s), 24 minute(s)"
  }
}

<sub>[BUDI-7625](https://linear.app/budibase/issue/BUDI-7625/i-cant-edit-my-screens)</sub>

**Comment by aptkingston** [comment]
Please follow the bug template. Please at least include a screenshot of the actual error. What does the server respond with when it throws a 500? You can see that in the `Respuesta` tab.

**Comment by miguelet17** [comment]
hello @aptkingston ,  the server respond -->
![Captura de pantalla 2023-10-15 a las 12 48 46](https://github.com/Budibase/budibase/assets/9483801/ffbbf965-d4d3-41cf-95be-7d67a97bba8a)

**Comment by aptkingston** [comment]
Please follow the bug template and include an app export to help us debug your issue. Thanks.
