### ISSUE TITLE
[BUDI-7628] BB freezes after dragging and dropping user column

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#12070]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
budimaster > marketing app > tasks table

**Describe the bug**
BB freezes after scrolling table, then dragging and dropping user column. See video...

**To Reproduce**
1. Scroll down the tasks table within the data section
2. Drag the user column to another location

**Screenshots / video**
https://vimeo.com/874744808/28fc7a8b65?ts=20000&share=copy

**Desktop (please complete the following information):**
Macbook/Arc.

<sub>[BUDI-7628](https://linear.app/budibase/issue/BUDI-7628/bb-freezes-after-dragging-and-dropping-user-column)</sub>

**Comment by mike12345567** [comment]
Appears to be fixed in Budi-cloud, tested in a few different environments.
