### ISSUE TITLE
[BUDI-7637] Admin/builder user only endpoint

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#12088]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.11.35
  - App Version: 2.11.35

**Describe the bug**
When a basic user is using the new user type in a create field the select is empty and the application shows a notification "Admin/Builder user only endpoint"

**To Reproduce**
1. Create an application with an internal table and add a user object to that table
2. Create a page (basic access) and add a form block to that page with create type and set the data to use the table created
3. Invite a user with basic access level and ask them to go to that application/pate

**Expected behavior**
The basic user should be able to view and select from the users in the user dropdown

**Screenshots**
![booking1](https://github.com/Budibase/budibase/assets/110813989/3c352c7d-eb29-4916-8211-91ebb02d1e9a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

<sub>[BUDI-7637](https://linear.app/budibase/issue/BUDI-7637/adminbuilder-user-only-endpoint)</sub>

**Comment by mike12345567** [comment]
Hi @andyburgessmd - this will be fixed in 2.11.41.
