### ISSUE TITLE
Allow the usage of sidecar containers in Helm chart

### ISSUE THREAD

**Issue by francoisclara** [Budibase/budibase#12087]
**Describe the feature request**
I have updated the Helm chart to be able to declare sidecar containers in the main application. The use case is to allow the usage of Cloud SQL proxy when I host BB on GCP and have to store data in a Cloud SQL database (postgresql instance). The recommandation of Google is to use Cloud SQL proxy to connect the postgres instance but to do that I need to have this proxy declared as a sidecar in the application pod.

**Comment by samwho** [comment]
Hey @francoisclara, I just merged a PR enabling the use of sidecars in our Helm chart. Search "extraContainers" on https://github.com/Budibase/budibase/tree/master/charts/budibase to see where you can use it.

I'm going to close this out, but please do feel free to reopen if you run into any problems! 🙏
