### ISSUE TITLE
1:N getting automatically converted to N:N

### ISSUE THREAD

**Issue by arladmin** [Budibase/budibase#1209]
**Describe the bug**
Unable to create a 1:N relationship type column. After creating a 1:N, it automatically gets converted to N:N and allows addition of multiple values, which is wrong.

**To Reproduce**
1. Create 2 Tables: A & B
2. Create 1:N relationship in A (1 A -> N B) , implying:1 A can connect with N Bs and each B should be able to connect only with 1 A
3. Create multiple rows in A & B
4. Try to connect multiple As in a single B, you can
5. Also, edit the relationship in both A & B, it'll show as N:N. It will also not allow you to change it

**Expected behavior**
- Table B should not be able to connect with multiple As.
- It should be possible to change a column (relationship) type.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 0.8.3

**Additional context**

**Comment by mike12345567** [comment]
Hi @arladmin - 1:N relationships are a bit confusing right now, we've got plans for the immediate future to make changes around it to clear up the language used and be more explicit about what is being created - you can see this in #1178.

For now if you wanted to create `Reps` and `Sales` where each sale could only have one rep but each rep could have many sales, you would do the following:
https://www.loom.com/share/cc6e8d31065140759656e134e9c8fff8

This is quite confusing at the minute as the table you create the 1:N relationship type from is the one that is the many, not the one, it will have a multi-select and `many to many` will be selected for its relationship type. The other table will have `one to many` selected and will only have a select, you'll notice an error will occur if you attempt to say on the many side of the relationship to a row which is already related to something else.

As I say this is definitely something we're going to target, likely with the plans discussed in #1178 - we think this will make it a lot more clear as to how the relationship is defined.
