### ISSUE TITLE
RESTful API: Query Error: Thread timeout exceeded 10000ms timeout.

### ISSUE THREAD

**Issue by dylanzan** [Budibase/budibase#12093]
Hello, I have an API interface. Due to the backend processing a large amount of data, the API response is slow, resulting in a timeout error.

May I know where should I increase this timeout duration?

![image](https://github.com/Budibase/budibase/assets/23621554/e875316d-387a-4a90-9492-9f09208967f9)

**Comment by ConorWebb96** [comment]
Hey @dylanzan,

Can you please follow the bug template. It would provide information needed in aiding with debugging this issue.

**Comment by dylanzan** [comment]
> Hey @dylanzan,
> 
> Can you please follow the bug template. It would provide information needed in aiding with debugging this issue.
> 
> If you are self-hosted this may help; [#6078 (comment)](https://github.com/Budibase/budibase/issues/6078#issuecomment-1139049852)

Thank you very much. With your guidance, I have successfully resolved this issue.
