### ISSUE TITLE
[BUDI-7638] Allow for wrapping of row content within a table instead of turnication.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12095]
**Describe the feature request**
Include a checkbox somewhere that would change the functionality of the table to allow for wrapping of a row's content instead of truncating it. This would allow for more information to be visible, possibly eliminate the need to add in side panels or other components to see the full information of a record.

<sub>[BUDI-7638](https://linear.app/budibase/issue/BUDI-7638/allow-for-wrapping-of-row-content-within-a-table-instead-of)</sub>

**Comment by aptkingston** [comment]
We're unlikely to make changes to the table component as it is soon to be deprecated, but the grid allows this by configuring row height. That allows up to 3 lines of content to be visible in every cell. Does that solve this issue? Or would you like the option of even content lines per row?
