### ISSUE TITLE
[BUDI-7649] "Clear Row Selection" from Table Block after Button Click

### ISSUE THREAD

**Issue by Doctor-N0** [Budibase/budibase#12114]
Similar to the "Clear Form" function, a "Clear Row Selection" function in the Table Block could also be helpful. The function could be added e.g. in the form of a check box "Clear Table Block Selection" under the field "Button". (see screenshot)

As discussed in the articles on Bulk selection (see [here ](https://github.com/Budibase/budibase/discussions/11055#discussioncomment-6370952) and [here](https://github.com/Budibase/budibase/discussions/12111)), this function would be quite helpful for these kind of applications.

![image](https://github.com/Budibase/budibase/assets/105864309/877315e8-6331-411c-9bf5-e660f6f6d7b1)

<sub>[BUDI-7649](https://linear.app/budibase/issue/BUDI-7649/clear-row-selection-from-table-block-after-button-click)</sub>

**Comment by melohagan** [comment]
It would be quite nice to have a **Clear Row Selection** action.
