### ISSUE TITLE
[BUDI-7651] Deleting an external Postgres data source causes builder to freeze, needs a page refresh to fix.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12122]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.11.36
  - App Version: 2.11.36

**Describe the bug**
Whenever trying to delete a Postgres data source within the builder. It freeze in the middle of the process and won't un-freeze until a manual page refresh is done.

Immediately after the delete button is clicked the data source title that was their previously changes to undefined. Not sure if this has any relevance.

**To Reproduce**
1. Go into an app create a data source connection to a Postgres database
2. After successfully fetching, delete the data source
3. See error

**Expected behavior**
Freezing shouldn't happen. Whenever a data source is deleted, a toast notification should appear outline it has successfully been deleted. This seems to be an issue related to some recent update.

**Screenshots**
<img width="631" alt="Screenshot 2023-10-20 at 07 51 04" src="https://github.com/Budibase/budibase/assets/126772285/7579ab41-d1b4-46cc-963c-a8cb77e92335">

<img width="581" alt="Screenshot 2023-10-20 at 07 51 11" src="https://github.com/Budibase/budibase/assets/126772285/037e2069-2920-4a62-b58d-87ff048b00cf">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version v1.59.120

**Additional context**
This seems to be a very recent thing e.g. within the last **few minor version increments** as this didn't happen previously.

<sub>[BUDI-7651](https://linear.app/budibase/issue/BUDI-7651/deleting-an-external-postgres-data-source-causes-builder-to-freeze)</sub>

**Comment by aptkingston** [comment]
Fix for this is already merged 👍 
https://github.com/Budibase/budibase/pull/12091
