### ISSUE TITLE
[BUDI-7650] If an external data source is added were any of the tables within don't contain primary keys it will fail to connect.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12121]
**Checklist**
- [x] I have searched Budibase discussions and Github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.11.36
  - App Version: 2.11.36

**Describe the bug**
Whenever attempting to connect to an external data source with a table that doesn't have primary keys. (Postgres) It will fail, the error shown doesn't provide a whole lot of feedback as to why. Additionally this won't create the connection, meaning you will have to close the window and ensure that your tables within that database have primary keys set.

**To Reproduce**
1. Create a new table in your Postgres data source using the sql script attached below
2. Create a new app
3. Select the Postgres data source
4. Fill in all the relevant information
5. Choose the database with the table created using the below sql
6. See the error.

**Expected behavior**
I think this check should be moved out of the connection to an external data source and instead only be done whenever the tables are being fetched and synced into Budibase. This would allow for connection, but also prevent tables without primary keys from being synced into Budibase.

**Screenshots**
<img width="634" alt="Screenshot 2023-10-20 at 07 55 19" src="https://github.com/Budibase/budibase/assets/126772285/daf0537a-e53c-4ff7-aaf9-6c5f347403db">

Issue resides in one of these files;
![Screenshot_2023-10-20_at_08 03 52](https://github.com/Budibase/budibase/assets/126772285/606350c4-2287-424b-98f2-c29377c39884)
The below screenshot seems to be the code thats causing this;
![Screenshot_2023-10-20_at_08 03 43](https://github.com/Budibase/budibase/assets/126772285/73833e9f-fd64-4ad6-befa-bd388e1cd028)
  
**Table SQL to replicate the error**
```SQL
CREATE TABLE your_table_name (
    name varchar(255),
    description text
);
```

<sub>[BUDI-7650](https://linear.app/budibase/issue/BUDI-7650/if-an-external-data-source-is-added-were-any-of-the-tables-within-dont)</sub>

**Comment by mike12345567** [comment]
Will be fixed in 2.11.40
