### ISSUE TITLE
PostgreSql Import Issue

### ISSUE THREAD

**Issue by OndreaKee** [Budibase/budibase#12159]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
When exporting a Budibase application and importing elsewhere, the PostgreSql table rows are appearing as a single column instead of in proper table format. 

**To Reproduce**

**Expected behavior**
PostgreSql table should show in proper format with rows.

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

**Comment by ConorWebb96** [comment]
Hey @OndreaKee,

Can you please follow the template. I'm going to close this for now, please provide as much information as possible. Thank you.
