### ISSUE TITLE
[BUDI-7683] There was a problem loading your grid - App users

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#12154]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.11.41
  - App Version: 2.11.41 & tested with reverted 2.11.6

**Describe the bug**
When I try to view the App users table in the data view of builder it shows the message below and no data is shown
```
There was a problem loading your grid
Cannot read properties of null (reading 'sourceId')
```
![image](https://github.com/Budibase/budibase/assets/110813989/3f0b5916-e76f-4cb5-9555-73c8485385a2)

Additionally in the front end where the a table component previously did show the application users it now shows
![image](https://github.com/Budibase/budibase/assets/110813989/2b48ba58-d024-41db-8218-53ae493dfdfe)

I think this is applicable to an application which did previously have additional fields added to the users table

**To Reproduce**
I can send you an export of the application to reproduce. Just let me know who to send it to.

**Expected behavior**
I should be able to view users in both views.

<sub>[BUDI-7683](https://linear.app/budibase/issue/BUDI-7683/there-was-a-problem-loading-your-grid-app-users)</sub>

**Comment by aptkingston** [comment]
Could you check if the error is returned by the API or not? If you check dev tools you'll be able to see if the network request fails or not. That will help us narrow down where the error is coming from.

Is this also just this one particular app or all apps? I've tested plenty of apps with and without the old users columns and they work fine, so it must be something else unique to this app.

**Comment by andyburgessmd** [comment]
Builder console shows
![image](https://github.com/Budibase/budibase/assets/110813989/ab50e109-127a-40c4-b631-c897ffd8bab6)

And the application console is 
![image](https://github.com/Budibase/budibase/assets/110813989/2a2f4c93-66a4-417c-97c2-67e34aa8bba2)

**Comment by aptkingston** [comment]
Thanks for the extra info!

**Comment by andyburgessmd** [comment]
This may be low priority to you but for me its critical being able to use an application or make any changes to it.

**Comment by aptkingston** [comment]
We're actively testing a new option that will allow you to migrate a relationship to the users table into the new "user type" column, and it's almost ready for release. By marking this low priority we're just saying that we aren't going to make any other changes to the existing user relationship codebase (which is the cause of this problem) because we've nearly got this other solution ready.

So don't worry - we aren't ignoring this issue and we're well aware that there are issues with relationships to the users table.

**Comment by andyburgessmd** [comment]
@aptkingston any eta on this?

**Comment by mike12345567** [comment]
Hi @andyburgessmd - this is currently in the process of being released - it will be available on the Cloud by end of day.

**Comment by aptkingston** [comment]
@andyburgessmd once this is released I'd encourage you to try migrating all of your user table relationships and seeing if that resolves your issue. Probably sensible to either back up your app first or do an export/import and try the migration in a new app.

**Comment by teigentler** [comment]
I also have an comparable issue (Cannot read properties of null (reading '_id'))
@andyburgessmd: Is the issue solved in your case?

**Comment by andyburgessmd** [comment]
@teigentler Nope, still waiting for the update to hopefully fix it.

**Comment by andyburgessmd** [comment]
@mike12345567 should I be seeing something to fix this yet?

**Comment by mike12345567** [comment]
> @mike12345567 should I be seeing something to fix this yet?

The previous comment I made was in reference to the release the of the user table relationship migration functionality, which is now available; we have not been able to recreate the specific scenario from this issue as of yet.

**Comment by andyburgessmd** [comment]
@mike12345567 So how do we use the 'user table relationship migration functionality'? I'm still stuck with an unusable application !!!

**Comment by mike12345567** [comment]
Hi @andyburgessmd and @teigentler - can you give it a go now and see if this has given access back to the affected tables.

**Comment by andyburgessmd** [comment]
@mike12345567 still seeing the issue when trying to view the users table running 2.13.7
![image](https://github.com/Budibase/budibase/assets/110813989/8ece9e1d-eb3e-4c15-8406-3c5ee63b80af)

**Comment by teigentler** [comment]
2.13.7 solved my issue. Thank you!

**Comment by mike12345567** [comment]
Hi @andyburgessmd - when 2.13.8 is available can you try it.

**Comment by andyburgessmd** [comment]
@mike12345567 2.13.8 has fixed it and the user table can be used again. Do we need to do something to use the 'user table relationship migration functionality' or is that what this has done?
