### ISSUE TITLE
[BUDI-7690] [BUDI-7379] Update action step removes previously set relationships if set relationships on a different relationship field.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12176]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.9.5
  * App Version: 2.9.5

**Describe the bug**
Automations with multiple relationship fields get cleared if you update a different relationship within the same table for the update action step.

**To Reproduce**

1. Go to an app
2. Create a table on a query based db e.g. MySQL, Postgres, this also happens with an internal db.
3. Create a few tables, with the main one having more than one relationship on it.
4. Create an automation that updates a row.
5. Copy the row id → \_id from a row you wish to update and paste it into the row id field of the automation.
6. Grab the row id of a different table and paste that into its related relationship field within the automation.
7. Lastly grab a row from the second table that has a relationship with the first. Paste this into its relevant place.
8. Run the test and notice that the automation only adds one of the 2 relationship values instead of both. It seems to clear the second one. If any are added before it will clear those as well on whatever one takes priority.

**Expected behavior**
Automation should preserve previously entered relationships between entries when left blank and the clear relationships checkbox hasn't been checked.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7379](https://linear.app/budibase/issue/BUDI-7379/update-action-step-removes-previously-set-relationships-if-set)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7690](https://linear.app/budibase/issue/BUDI-7690/[budi-7379]-update-action-step-removes-previously-set-relationships-if)</sub>

**Comment by Lanhild** [comment]
+1

I've seen this happen in many of my tables because of automation

**Comment by Lanhild** [comment]
Any updates about this?

It's very inconvenient

**Comment by samwho** [comment]
Hey @Lanhild, sorry for the radio silence on this. I did a little bit of digging and I think this issue got lost in the shuffle. It seems to have gotten fixed and then I added some tests for it in https://github.com/Budibase/budibase/pull/12297.

Are you still experiencing the problem on the latest version of Budibase?

**Comment by samwho** [comment]
Superb, thank you for confirming. Sorry for the confusion! Going to close this out.
