### ISSUE TITLE
[BUDI-7710] User groups do not fully support custom roles

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#12220]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.11.45

**Describe the bug**
When assigning a custom role to a user group, users of that group do not have access to any screens until you explicitly specify a user level role.

**To Reproduce**
1. Create a user group
2. Assign a user to that group
3. Create an app, and create a custom role
4. Assign the custom role to the user group
5. Try to log in as a member of the group: you will see the message 'You do not have access'
6. Directly assign the custom role to the user: you will now have the expected screen permissions.

**Expected behavior**
User groups should support custom roles.

**Screenshots**

![Screenshot 2023-10-30 at 16 18 21](https://github.com/Budibase/budibase/assets/101575380/7b8e0166-beb6-480f-898f-80c572d5392d)

Bert is a member of the Ops Managers group.

![Screenshot 2023-10-30 at 16 19 17](https://github.com/Budibase/budibase/assets/101575380/e5d2b14c-6824-49e9-86cc-ee4db7aed294)

Bert correctly appears to have the custom 'Power Plus' role.

<img width="609" alt="Screenshot 2023-10-30 at 16 19 53" src="https://github.com/Budibase/budibase/assets/101575380/60e5436a-e537-466b-9bac-69454b7098b0">

But receives this message, and has no access.

![Screenshot 2023-10-30 at 16 21 15](https://github.com/Budibase/budibase/assets/101575380/3ea00504-579f-4e6f-b620-e0910b62142b)

If I directly assign Bert to the 'Power Plus' role.

<img width="465" alt="Screenshot 2023-10-30 at 16 22 10" src="https://github.com/Budibase/budibase/assets/101575380/64248f75-9ad6-4025-b415-6f87ea9ad4cf">

He now has access.

<sub>[BUDI-7710](https://linear.app/budibase/issue/BUDI-7710/user-groups-do-not-fully-support-custom-roles)</sub>

**Comment by ConorWebb96** [comment]
Some additional screenshots of this issue replicated.
<img width="406" alt="Screenshot 2024-01-10 at 14 36 09" src="https://github.com/Budibase/budibase/assets/126772285/05d63ccb-7139-4974-9b8a-c91894116743">
<img width="443" alt="Screenshot 2024-01-10 at 14 36 19" src="https://github.com/Budibase/budibase/assets/126772285/41f41a6b-8029-4132-b1a9-1aac53c52907">
<img width="1509" alt="Screenshot 2024-01-10 at 14 36 31" src="https://github.com/Budibase/budibase/assets/126772285/7215c35f-eacd-401f-82d5-01372a567194">

**Comment by mike12345567** [comment]
Fixed in: https://github.com/Budibase/budibase/pull/13191

**Comment by ConorWebb96** [comment]
Re-opening as this issue seems to be happening again.

**Comment by loureirodnl** [comment]
Hello guys
Same is happening for us. We have an app that is supposed to work with 10+ groups (and 100+ users) that are synced with our Azure Active Directory. Do you have any workaround that we could implement ? Or is it fixed in Budibase 3 ?

**Comment by mike12345567** [comment]
Hi @loureirodnl - in Budibase 3.0 custom role RBAC has changed quite a bit with quite a few improvements - it would be worth checking if this has been fixed in latest versions.

**Comment by mike12345567** [comment]
Hi @loureirodnl - this issue should be resolved in the latest release of Budibase.
