### ISSUE TITLE
I can't change the name of the components anymore

### ISSUE THREAD

**Issue by Ttipi** [Budibase/budibase#12227]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker
  - Budibase Version: 2.11.45
  - App Version: 2.11.45

**Describe the bug**
Hello, and congratulation for Budibase. It's a wonderfull product, so easy and powerfull !

The form input made for name each component has disappeared from the page configuration web interface...

**To Reproduce**
1. Go to the edition of the design of an app
2. Click on any screen
3. Click on any page's conponent (like a container for example)
4. On the right side, in the "configuration" part of each component there should be a form to name that component. However, this input is no longer present...

**Expected behavior**
To have the possibility to name components like before

**Screenshots**
[Image](https://elmn.communaute-paysbasque.fr/index.php/s/Lf6nbC3cjqkQydn)
  
**App Export**
Not possible sorry...

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 23.10
 - Browser Chrome
 - Version 118.0.5993.117 (Build officiel) (64 bits)

**Additional context**

**Comment by poirazis** [comment]
Hey @Ttipi 
you can edit it Inline above the setting
![Screenshot 2023-10-31 at 3 35 04 PM](https://github.com/Budibase/budibase/assets/80512170/05bae052-bc84-4c4a-86ea-c9c7186e133d)

**Comment by aptkingston** [comment]
Thanks @poirazis!

**Comment by Ttipi** [comment]
oops, excuse me, I think I'm getting old... I hadn't seen the new field. Thank you again for your quick response. That's solved !
