### ISSUE TITLE
[BUDI-7719] Invite new user panel should pass the search email address into the email field of the add user page

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#12251]
**Describe the feature request**
When searching for a user by email and no user is found, you are presented with an `invite a new user` link.
Ideally clicking this link would pass the already entered email address into the email field for convenience.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e40912f6-4e23-455f-8303-262e03162837/b381b2b4-82d2-455b-af28-1254a32a41e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lNDA5MTJmNi00ZTIzLTQ1NWYtODMwMy0yNjJlMDMxNjI4MzcvYjM4MWIyYjQtODJkMi00NTViLWFmMjgtMTI1NGEzMmE0MWU5IiwiaWF0IjoxNjk4OTMxMDYzLCJleHAiOjE2OTkwMTc0NjN9.bjP6yi5g7iDqPDj8XXKMn15wwV6gBAzMvza5hQna0pM)

*No user found*

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b1795461-d64d-4909-88e5-bfba34f5e34b/ce078719-2a77-4e32-8cf7-ba60d7a5262a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9iMTc5NTQ2MS1kNjRkLTQ5MDktODhlNS1iZmJhMzRmNWUzNGIvY2UwNzg3MTktMmE3Ny00ZTMyLThjZjctYmE2MGQ3YTUyNjJhIiwiaWF0IjoxNjk4OTMxMDYzLCJleHAiOjE2OTkwMTc0NjN9.8zxzRH14PjUPrmnAh3QiJ5bj4OwF9WUXiRpzA6seBng)

*Email is blank when clicking the link, but could be populated for convenience*.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7719](https://linear.app/budibase/issue/BUDI-7719/invite-new-user-panel-should-pass-the-search-email-address-into-the)</sub>

**Comment by Leeroy28** [comment]
Fixed asap
