### ISSUE TITLE
[BUDI-7722] Relationship Picker filtering doesn't seem to be working

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12260]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.11.45
  * App Version: 2.11.45

**Describe the bug**
When using the relationship field on external db you have to do a lot of JS logic to get this working. The encoded id of the relationship fields is no longer present meaning you don't have anything which will match the value of what the relationship picker component  outputs. This means you have to do a lot of unnecessary JS logic to get the value to output in the correct format to use against the primary id of the relationship instead.

**To Reproduce**

1. Go to an app with an external db with a relationship the type doesn't matter
2. Generate a table, nested inside a form
3. Add a relationship picker component inside the form
4. Try and hook this up so it filters the data by the selected relationship
5. See that there is no encoded \_id for the relationship to match up against.
6. Proceed to do

**Expected behavior**
You should be able to hook the relationship filter up out of the box without having to do a lot of to decode, parse to array and optionally parse to number depending on what you want to do.

**Additional context**
[Discord discussion thread link](https://discord.com/channels/733030666647765003/1169353483653226586/1169353483653226586)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7722](https://linear.app/budibase/issue/BUDI-7722/relationship-filtering-doesnt-seem-to-be-working-like-it-used-to-for)</sub>

**Comment by melohagan** [comment]
The filtering as per this example for an internal DB is also broken: https://docs.budibase.com/docs/cascading-dropdown-filters

**Comment by nasilrgb** [comment]
Still not fixed this issue

**Comment by melohagan** [comment]
Hi @nasilrgb There is an open issue here: https://github.com/Budibase/budibase/issues/13893
