### ISSUE TITLE
[BUDI-7733] Error in Oracle Datasource with data type Oracle CLOB

### ISSUE THREAD

**Issue by nosc82** [Budibase/budibase#12266]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.8.30 - 2.12.7
  - App Version: 2.12.7

**Describe the bug**
1. When I connect to an existing Oracle database and fetch the tables, columns with the CLOB data type are not fetched and therefore not displayed
2. If I create a new column with the Text data type in an Oracle table via Budibase, the CLOB data type is used in the database. A new fetch of the table results in all CLOB columns no longer being displayed in Budibase.
3. If a text column is inserted via Budibase, values can be saved in it, but they will not be displayed correctly in Budibase. It comes as output for the added values [object Object]

**To Reproduce**
1. Go to 'Builder -> App -> DataSource -> Oracle'
2. Click on 'fetch tables' to an existing schema
3. Scroll down to table with CLOB-column

**Expected behavior**
1. Correct display of CLOB content
2. Correct fetching of columns whose data type is CLOB
3. For text smaller than 4000 bytes (in UTF-8 1000 char) varchar2 should be used as the data type

**Screenshots**
  
**App Export**

**Desktop (please complete the following information):**
 - OS: Linux/Windows
 - Browser Firefox
 - Version 102.14.0esr

**Additional context**

<sub>[BUDI-7733](https://linear.app/budibase/issue/BUDI-7733/error-in-oracle-datasource-with-data-type-oracle-clob)</sub>

**Comment by mcorut90** [comment]
Hello all,

Is there any progress about this issue? We' ve encountered with this problem in our self hosting platform. 

Regards,

**Comment by samwho** [comment]
Hey @nosc82, @metehancorut. I just put out a large number of fixes for our Oracle integration in 2.29.29, would you be able to update to that version and tell me if this is still a problem for you? 🙏

**Comment by nosc82** [comment]
Hey samwho, thanks for your good work. It's working now in version 2.31.1. Good job, no problems anymore.
