### ISSUE TITLE
(UX) Deployment Error Modal

### ISSUE THREAD

**Issue by Florian-Schoenherr** [Budibase/budibase#1227]
![deployment_error](https://user-images.githubusercontent.com/65456722/109413027-a6382d00-79ab-11eb-8bad-308b6898c5db.png)

1. clicking on `Failure` should open the Modal, right now you need to click the small `i`
2. The actual "error" is, that I just tried deploying without running `docker compose`, which is an obvious mistake. The Modal should either distinguish between authorization/key and "no running instance to push to" or mention both.
Any idea on how to distinguish between errors? I could only guess that there is some sort of auth step, which should spit out the auth error and if it happens somewhere before auth, it should spit out the other error.

If you want, I can make a PR for that, too 👍

**Comment by mike12345567** [comment]
Hi @Florian-Schoenherr good suggestion, we do need to improve the errors around this and make it clear when it is not currently online vs not authorised!

The modal should be updated as well, we always welcome PRs no matter the size for these sort of things! 😄

**Comment by Florian-Schoenherr** [comment]
@kevmodrome interesting, this didn't get closed by #1280
