### ISSUE TITLE
[BUDI-7734] Filtering on a relationship picker component doesn't work

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12285]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.12.11
  * App Version: 2.12.11

**Describe the bug**
When trying to add a filter to the relationship picker component. It doesn't matter what I input, nothing seems to happen. It also doesn't matter what type of filter used e.g. `Equals`, `Starts with` etc. Nothing changes. This has been tested with bindings and typed in values.

Additionally, the value of relationship select has also been tried and nothing happens.

**To Reproduce**

1. Go to an app
2. Create 2 tables with a relationship between them, doesn't matter what type.
3. Add a form with a relationship field and try to add filtering to the relationship.
4. See error, nothing you do will filter whats in the relationship.

**Expected behavior**
If the filter matches, then the values within should be filter accordingly inside the relationship picker component.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/8630af81-ad0e-457d-ae4c-c3084d7f08e8/0405f864-097f-4c15-8ce2-23fef2c06fc8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC84NjMwYWY4MS1hZDBlLTQ1N2QtYWU0Yy1jMzA4NGQ3ZjA4ZTgvMDQwNWY4NjQtMDk3Zi00YzE1LThjZTItMjNmZWYyYzA2ZmM4IiwiaWF0IjoxNjk5MjYwOTI1LCJleHAiOjE2OTkzNDczMjV9.HZzmsgZFqbpvDWAx0m-hofWyw7-IWb2T97fTxId_qGE)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/21fdce8b-97a3-47fd-99bb-bbbc304c7c53/50d3f977-8623-437b-a2ef-309d964f00a1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8yMWZkY2U4Yi05N2EzLTQ3ZmQtOTliYi1iYmJjMzA0YzdjNTMvNTBkM2Y5NzctODYyMy00MzdiLWEyZWYtMzA5ZDk2NGYwMGExIiwiaWF0IjoxNjk5MjYwOTI1LCJleHAiOjE2OTkzNDczMjV9.u_6415rQludQIpJJ087t7CIC71aRwHCI6svQu5538Fs)

**App Export**

**Additional context**
[Discussion link](https://github.com/Budibase/budibase/discussions/12250#discussioncomment-7484586)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7734](https://linear.app/budibase/issue/BUDI-7734/filtering-on-a-relationship-picker-component-doesnt-work)</sub>

**Comment by immohacker** [comment]
Hi ConorWebb96, 
thank you for change the prio but without this filter, my app is broken.
I think i revert to a an dataprovider with an option picker component, so i filter in the dataprovider but filter in relationship picker is very very nice. It makes things very very easy

I dont know which version it was 2.13.6  .213.7   2.13.8 but yesterday it would work short until i update today to latest (2.13.9).
I revert to every version list above but it would not work again.
I hope you can speed up the bug fix.
Thank you very much!
Best regards Bonkersdeluxe

**Comment by koneubauer** [comment]
Hey ConorWebb96,
any ETA on a fix for this issue? Still limiting out possibilities in creating proper forms. On v2.13.12 by now

**Comment by ConorWebb96** [comment]
Hey all,

I'll bring this up with engineering and try to get it bumped in priority.

**Comment by ConorWebb96** [comment]
Hey all,

I've got an update for you after having a chat with a few of the engineers, this has now been bumped to high probity and an engineer has been assigned to it. 

Hopefully it will be fixed swiftly.
