### ISSUE TITLE
On Change old field input

### ISSUE THREAD

**Issue by smart-account** [Budibase/budibase#12309]
If a "Save Row" action is triggered for a form text field using the "On Change" function, the old input of the field is saved. The latest field input should be available with "On Change".

**Comment by melohagan** [comment]
@smart-account Make sure you are using the `{{ Field Value }}` binding!

https://docs.budibase.com/docs/text-inputs#on-change

**Comment by smart-account** [comment]
Yes, when using the field binding it is using the old input of the field, not the updated one.
For example, if enter "test1" in a text field and an action is fired by "On Change" function it returns an empty field. After that enter "test2" in text field it returns the old state of field "test1". Would expect that "On Change" functionality should use the updated state of the fields?
