### ISSUE TITLE
Designation of a component can no longer be edited

### ISSUE THREAD

**Issue by leuedaniel** [Budibase/budibase#12349]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker single image
  - Budibase Version: 2.13.6

**Describe the bug**
When I insert a new component in the design, I cannot change the name of the component. For example, if I insert a new form, it is called "New Form" and this name can no longer be changed. The name of existing components can also no longer be changed.

**To Reproduce**
1. open an existing app
2. update the app to the new version
3. switch to the design mode
4. add a new component
5. name is assigned by the system and cannot be customized

**Expected behavior**
You can define the names of the components yourself so that the overview is not lost.

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/44936305/bc652374-c590-41eb-ab90-8e0b7ccec14d)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome
 - Version 119.0.6045.124

**Comment by aptkingston** [comment]
Hey @leuedaniel. You can now edit the name of the component directly from the label there in the side panel - just click and it's editable.

![image](https://github.com/Budibase/budibase/assets/9075550/0380ae72-ed9f-43c5-a7ff-eec70f2f7b8c)

**Comment by leuedaniel** [comment]
Thanks for the quick help :-)
