### ISSUE TITLE
[BUDI-7771] Allow a user invite to be revoked

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#12342]
**Describe the feature request**
Currently if I invite a user I am unable to invalidate their invite, which means a user can sit in the *Pending Invite* section until expiry a few days later.

As an admin, I should be able to invalidate an invite and remove a user from the pending invite list.

**Screenshots**

![Screenshot 2023-11-09 at 08 16 40](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/3f5d88f2-cbe5-427c-a5df-9efc354317f6/19899ed0-18bd-45cd-b4e5-73a6c77b19a0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8zZjVkODhmMi1jYmU1LTQyN2MtYTVkZi05ZWZjMzU0MzE3ZjYvMTk4OTllZDAtMThiZC00NWNkLWI0ZTUtNzNhNmM3N2IxOWEwIiwiaWF0IjoxNzAwODE4MjQ5LCJleHAiOjE3MDA5MDQ2NDl9.NeaypeXtnX6d_SDmCGa5g9gA1-9oko7LPbYwBWUCiUA)

![Screenshot 2023-11-09 at 08 17 01](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/9f73622d-f3c0-4e70-8a01-82f9d50ee68c/027fed5e-a02c-4d40-b3cf-946c76010af8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC85ZjczNjIyZC1mM2MwLTRlNzAtOGEwMS04MmY5ZDUwZWU2OGMvMDI3ZmVkNWUtYTAyYy00ZDQwLWIzY2YtOTQ2Yzc2MDEwYWY4IiwiaWF0IjoxNzAwODE4MjQ5LCJleHAiOjE3MDA5MDQ2NDl9.JdELEcDmuH9gx-zljfvHlhFSAW1ZVxUphNsQJAxyV2E)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7771](https://linear.app/budibase/issue/BUDI-7771/allow-a-user-invite-to-be-revoked)</sub>

**Comment by ConorWebb96** [comment]
This is a [duplicated issue ](https://github.com/Budibase/budibase/issues/11044).
