### ISSUE TITLE
Skip button in the fetch tables modal should not fetch all tables

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#12345]
**Describe the feature request**
I noticed that the `Skip` button will fetch all tables even when no tables are selected. Ideally the `Skip` button should do nothing.

Furthermore, in the datasource config modal, there is a `Back` button, but this button simply closes the modal - maybe it should be called `Cancel`?

**Screenshots**

![Screenshot 2023-11-09 at 10 34 26](https://github.com/Budibase/budibase/assets/101575380/a847e499-6c2a-44d1-a2ce-1a668e3ab878)

*Back button doesn't go to a previous step, it simply closes the modal*

![Screenshot 2023-11-09 at 10 36 01](https://github.com/Budibase/budibase/assets/101575380/5e27f320-9237-49cb-81b8-90982de9dffb)

*Skip button will fetch all tables, but should just close the modal instead.*

**Comment by ConorWebb96** [comment]
This seems to be working on the latest version now. Closing as resolved.
