### ISSUE TITLE
[ Self Hosted - 2.13.6 ] - Self Hosted Single Image installation doesnt know what version the server or the app is

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#12353]
Although i just pulled the :latest image which is 2.13.6 on docker hub, both in the server version and app version screen i get the below

![Screenshot 2023-11-09 at 4 35 56 PM](https://github.com/Budibase/budibase/assets/80512170/a292b0bc-6384-4bb9-ab55-042a4f355ff3)
![Screenshot 2023-11-09 at 4 35 32 PM](https://github.com/Budibase/budibase/assets/80512170/24be7d89-ce05-4524-99f2-b1dd1b4a755e)

**Comment by mike12345567** [comment]
Hi @poirazis it seems like the app you're looking at hasn't been updated correctly - I just created an app in the latest version and it looks correct to me:
Installation version
![image](https://github.com/Budibase/budibase/assets/4407001/f6ce66b2-faa2-4eaf-a29a-3e1ef526bae1)
App version
![image](https://github.com/Budibase/budibase/assets/4407001/dd6a2c8b-84ef-4272-8d1d-1c804e7c616c)

**Comment by poirazis** [comment]
Hey @mike12345567 
exporting and reimporting the app didnt solve it on the specific app, and also creating a brand new app does the same thing.
Could it be something wrong with my installation ?

**Comment by mike12345567** [comment]
> Hey @mike12345567 
> exporting and reimporting the app didnt solve it on the specific app, and also creating a brand new app does the same thing.
> Could it be something wrong with my installation ?
> 
> I think the issue is there is no BUDIBASE_VERSION variable defined in the .env file in the /data mount
> 
> ![Screenshot 2023-11-09 at 9 08 03 PM](https://github.com/Budibase/budibase/assets/80512170/180de4d0-64ca-47a1-968f-7c386102bef7)
> 
> 

Hmm that is odd, you dont need a BUDIBASE_VERSION specified on the .env as it is built into the image, can you try creating a brand new installation with the latest image and seeing if that works - making sure not to use the same volume.

**Comment by poirazis** [comment]
Sure, will revert

**Comment by poirazis** [comment]
yes @mike12345567 on a new intance evertryhing works fine, both the server and app version.
maybe a residue from a previous upgrade !

**Comment by mike12345567** [comment]
Ah - yes I believe this maybe something to do with the 2.12.3 image that was deleted - hopefully apps imported to the new installation should have this issue resolved! Going to close this issue for now as I don't think theres much can be done other than a new installation.
