### ISSUE TITLE
[BUDI-7772] Using an array as binding raises INCORRECT_TYPE error on automation loop

### ISSUE THREAD

**Issue by lgasteceau** [Budibase/budibase#12364]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: Docker Swarm
  * Budibase Version: 2.9.36
  * App Version: 1

**Describe the bug**
Using an array as binding raises INCORRECT_TYPE error on automation loop with external data connector.

**To Reproduce**

1. Go to automation tab, create an automation with an array as binding, and possibly other bindings if needed (see screenshot 1)
2. Add an external data connector action with looping over the array (see screenshot 2)
3. Click test
4. Enter the test data as JSON (see screenshot 3)
5. See error (see screenshot 4)

**Expected behavior**
The automation should loop over every element of the array and execute a query with the current loop value as a binding.

**Screenshots**
**Automation definition**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/dfa11779-1e30-4c7b-b01e-39f5bc41ba8b/ea9ae9cb-3a56-4b92-9f06-5369318f22a0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9kZmExMTc3OS0xZTMwLTRjN2ItYjAxZS0zOWY1YmM0MWJhOGIvZWE5YWU5Y2ItM2E1Ni00YjkyLTlmMDYtNTM2OTMxOGYyMmEwIiwiaWF0IjoxNzAwODE4Mjc3LCJleHAiOjE3MDA5MDQ2Nzd9.LejQG7izIwdXQpONL1sR4GNE_Z1akKn710Zh9scebyw)

**Loop with external data connector**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ed3cd3de-e732-4e62-bc6c-36326569f305/455e812f-f718-48ef-8cb6-b9381f1d8fbf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lZDNjZDNkZS1lNzMyLTRlNjItYmM2Yy0zNjMyNjU2OWYzMDUvNDU1ZTgxMmYtZjcxOC00OGVmLThjYjYtYjkzODFmMWQ4ZmJmIiwiaWF0IjoxNzAwODE4Mjc3LCJleHAiOjE3MDA5MDQ2Nzd9.J7u7XTHwE32CTvB4TJvm56c2tfOTsanVpcocgK9m1Ys)

**Test data**

```
{
  "fields": {
    "to_insert": [
      "2",
      "3",
      "4"
    ],
    "to_delete": [
      "5",
      "6"
    ],
    "annee": "2023",
    "RESEAU": "3100",
    "REGION": "100",
    "SECTEUR": "207"
  }
}
```

**Bug**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/110281e7-399a-4658-83e7-c850b0bc87fb/bb4f4e5b-25f1-4dcf-bcbf-4b94b0ef7464?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8xMTAyODFlNy0zOTlhLTQ2NTgtODNlNy1jODUwYjBiYzg3ZmIvYmI0ZjRlNWItMjVmMS00ZGNmLWJjYmYtNGI5NGIwZWY3NDY0IiwiaWF0IjoxNzAwODE4Mjc3LCJleHAiOjE3MDA5MDQ2Nzd9.Kj3sJ9DPvuaZD9v6CgIJjX4leykhYr1lXedzENuI3BQ)

**Desktop (please complete the following information):**

* OS Widows 10
* Browser Opera GX

**Additional context**
The external data connector is a postgreSQL custom request. This is a basic insert / delete statement.
In addition, I tried to run this same automation with a text instead of an array and it worked fine, except for when it contains only one element.
For example, I could use "1,2,3,4" instead of \["1","2","3","4"\] and the loop executes correctly.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7772](https://linear.app/budibase/issue/BUDI-7772/using-an-array-as-binding-raises-incorrect-type-error-on-automation)</sub>

**Comment by melohagan** [comment]
App export: 
[Automation bug-export.tar.gz](https://github.com/Budibase/budibase/files/13392638/Automation.bug-export.tar.gz)

**Comment by melohagan** [comment]
Noticed that the error is being thrown because `typecastForLooping` in the **automationUtils** is failing when it does:

```ts
if (typeof input.binding === "string") {
      return JSON.parse(input.binding)
    }
```

Not sure what the solution is though, as this line: https://github.com/Budibase/budibase/blob/7412fd5a5c607aad188e898d9367a13da1d07637/packages/server/src/threads/automation.ts#L290

transforms `[2,3,4]` into `"2,3,4"`

**Comment by mike12345567** [comment]
This issue should be resolved in latest release.
