### ISSUE TITLE
impossible to filter a selection field based on a relationship field

### ISSUE THREAD

**Issue by badrc** [Budibase/budibase#12374]
**Hosting**
- Self
  - Method: Docker
  - Budibase Version: 2.13.9

**Describe the bug**
Imagine I'm creating a CRM, with opportunities, companies and contacts. An opportunity is linked to an enterprise, then to contacts that belongs to this enterprise. (So 3 tables, opportunities, contacts and enterprise)
Using the form object "Relationship picker " I can't filter the contacts list using the enterprise field just filled in.
Because the field "enterprise" from the table Contacts is not even in the list

**Expected behavior**
How could I filter this contact table on the enterprise field (linked to the table enterprise) ?

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/13382499/bd0d4357-be0a-4484-9712-7b782da7ff61)
  
**App Export**
there's some private data in my app. Let me know if you need the app so I clean it before exporting it.

**Desktop (please complete the following information):**

**Additional context**

**Comment by melohagan** [comment]
Hey @badrc 

Could you please provide the SQL schemas for your tables? https://docs.budibase.com/docs/troubleshooting-sql

Furthermore, could you add additional screenshots to show how your relationships are configured within Budibase.

**Comment by badrc** [comment]
hi
data is in Budibase database, so no export schema available sorry

here's more screenshots on a simplified application I've just done

relation : 1 enterprise has many contacts 
![image](https://github.com/Budibase/budibase/assets/13382499/41ba4895-c0fd-4d72-92af-dba2305e17a3)
![image](https://github.com/Budibase/budibase/assets/13382499/57684a1e-4f1d-4c62-bc10-53144db1fb59)

then in a table view of contacts, I can't filter by Enterprise, the filed Enterprise is just not in the list
![image](https://github.com/Budibase/budibase/assets/13382499/904dd0d1-d211-4f0a-ae58-afe042a46fea)

**Comment by melohagan** [comment]
Hey @badrc 

Thanks for the screenshots and extra context!

Unfortunately this is a current limitation of the Internal Budibase DB. If you want to directly filter by relationships, you will need to use a SQL database. 
We do have plans to resolve that limitation in the future.

In the meantime, you may be able to make use of the relational data display: 

- https://docs.budibase.com/docs/fetching-data#displaying-relational-data
- https://docs.budibase.com/docs/filter-by-relationships#tutorial-filter-on-selected-relationship-picker-values

**Comment by arpadgabor** [comment]
Can this limitation be added to the Budibase UI when creating a new data provider with the Budibase DB with a big red box? Seems like a huge limitation and people often need to filter by a relational field (e.g. show "things" created by this user)
