### ISSUE TITLE
Option "Calculate" disappeared from the menu View

### ISSUE THREAD

**Issue by patricialguima** [Budibase/budibase#12378]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud

**Describe the bug**

When I create a View within Budibase, I can't see "Calculate" option anymore. It disappeared from the menu.

**Expected behaviour**

![image](https://github.com/Budibase/budibase/assets/150864805/ed63e208-a3c9-4485-9e4a-9d755f95a1c9)

**Screenshots**

![image](https://github.com/Budibase/budibase/assets/150864805/7801f0e9-b899-4eba-a06c-e2607ea94fd5)

**Obs**

I'm new here. Sorry if it doesn't make any sense.

**Comment by melohagan** [comment]
Hey @patricialguima 

This was intentionally removed as we are currently transitioning and improving our internal DB (including views) to be more powerful and flexible.

**Comment by ben-biber** [comment]
What is the Alternative? I used this for a Pie chart of my data
