### ISSUE TITLE
[BUDI-7773] Query users in automation

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#12372]
**Checklist**

* I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker
  * Budibase Version: 2.13.9
  * App Version: 2.13.9

**Describe the bug**
Since the changes to the user table its not not possible to query the users table in automation. I used this previously to query all application users and remind them to fill in timesheet weekly.

**To Reproduce**

1. Create an automation and add a query rows action
2. Try to select the users table

**Expected behavior**
You should be able to select and query the users table

**Screenshots**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/6b7bf3d2-218b-43f1-bda0-7570fa02ff09/29acad71-0ca4-4dd5-81b9-df2b7ef8d4c1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC82YjdiZjNkMi0yMThiLTQzZjEtYmRhMC03NTcwZmEwMmZmMDkvMjlhY2FkNzEtMGNhNC00ZGQ1LTgxYjktZGYyYjdlZjhkNGMxIiwiaWF0IjoxNzAwODE4MjkyLCJleHAiOjE3MDA5MDQ2OTJ9.r9cVLBVeqdMJMzj7uI-4chjpD5-P2dnEsXnTJzuE18k)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7773](https://linear.app/budibase/issue/BUDI-7773/query-users-in-automation)</sub>

**Comment by melohagan** [comment]
Fixed in version **2.13.26**
