### ISSUE TITLE
Incorrect version number for Docker Container

### ISSUE THREAD

**Issue by leuedaniel** [Budibase/budibase#12376]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.13.9

**Describe the bug**
After updating the Docker container by importing a new image, the version number in the app is no longer updated since version 2.12.7.

Display version in the application:
![image](https://github.com/Budibase/budibase/assets/44936305/181497c7-bb52-4d1f-9e64-4164d6ef3e67)

Effective version installed as Docker image:
![image](https://github.com/Budibase/budibase/assets/44936305/f5a455d2-e772-49bf-b91c-3be365c1ecd9)

**To Reproduce**
1. restart Docker container with latest image
2. log in to Budibase
3. version stops since 2.12.7
4. however, a newer image was effectively started

**Expected behavior**
The version should be recognized and displayed correctly again.

**Comment by melohagan** [comment]
Appears to be fine as of **2.13.10**

**Comment by leuedaniel** [comment]
Unfortunately, it is still wrong.

![image](https://github.com/Budibase/budibase/assets/44936305/539d0eeb-9bab-486b-8ab4-3f47aceeb181)

![image](https://github.com/Budibase/budibase/assets/44936305/d7dea581-b215-43b8-a605-642e88b1fe68)
