### ISSUE TITLE
Issues with https://account.budibase.app/auth/login

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#12381]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
NA

**Describe the bug**
I have been trying to move from cloud to self-hosted and to do that I needed to delete my account and create a new one with the same email address.
After setting up the new account with the self hosted settings I got the verification email, this did not work and when I tried to send the verification email again the alert
![image](https://github.com/Budibase/budibase/assets/110813989/bd32e216-5948-456a-904d-ac20facb2c8c)
was shown. 
I'm not sure how but it now seems to be verified and I have set a password, but when I try to login it is showing the same alert message as above.
Additionally the page is showing the "Some systems are experiencing issues" banner from your status tracking system but there are no issues showing there.
I've attached screenshot with console from that page and there are a few issues with the CSP showing as well as the error coming back from auth.

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/110813989/58ef833b-d8a7-4d19-a898-a0f9cb5b37cd)

**Comment by melohagan** [comment]
Hey @andyburgessmd 

You should be able to delete your account from the **Cloud** environment. Once you have done that, then setup a self-hosted account.

In future the near future plan types will match between cloud and self-hosted.
https://budibase.com/blog/updates/pricing-v3/
