### ISSUE TITLE
[BUDI-7762] Error saving queries with brackets () in URL

### ISSUE THREAD

**Issue by Meldiron** [Budibase/budibase#12424]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: crew1337

**Describe the bug**

REST API I want to use as datasource support filters, but it uses very specific query syntax. Following is how you do something like `LIMIT 1` in SQL:

`?queries[]=limit(1)`

* `[]` tells server that `queries` is array parameter, and there be multiple (like `?queries[]=limit(5)&queries[]=offset(10)`. It's not part of HTTP protocol as far as I am aware, but many HTTP servers accept this form. Example mentioning PHP: [https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string](https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string)
* `limit(1)` is a string value, which is then parsed by server. I believe `()` are valid symbols in value of URL parameters, as separation there is defined by `&` symbol.

Here is sample request and response from HTTPie:

![CleanShot 2023-11-22 at 21 47 51@2x](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/38fb3aa5-d17a-4762-8bce-f6e66086aa0f/318c629e-a948-4326-9b11-c5b6bb42c736?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8zOGZiM2FhNS1kMTdhLTQ3NjItOGJjZS1mNmU2NjA4NmFhMGYvMzE4YzYyOWUtYTk0OC00MzI2LTliMTEtYzViNmJiNDJjNzM2IiwiaWF0IjoxNzAwNzQ4Nzc2LCJleHAiOjE3MDA4MzUxNzZ9.-syJAXVVfc8nSvNdZvHaQhz5vxdYJ-FYMg3sGejojaQ)

Sadly, adding this to Budibase results in an error.

**To Reproduce**

1. Create REST API datasource
2. Create query
3. Write query with URL that includes parameters where value contains `(` or `)`, for example `https://google.com?q=Hello(World`
4. Click `Send`, seems to work fine
5. Click `Save`, shows error `Error saving query`

**Expected behavior**

No error, saving is successful.

**Screenshots**

![CleanShot 2023-11-22 at 21 48 21@2x](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b45ace66-f911-4ac4-b114-19673541cf6e/d120a988-ec8a-4159-99bb-9aad7f998874?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9iNDVhY2U2Ni1mOTExLTRhYzQtYjExNC0xOTY3MzU0MWNmNmUvZDEyMGE5ODgtZWM4YS00MTU5LTk5YmItOWFhZDdmOTk4ODc0IiwiaWF0IjoxNzAwNzQ4Nzc2LCJleHAiOjE3MDA4MzUxNzZ9.zQwyhyr2tt0cGPfLUhLVok5UL7oRRZpAnZxqVjdFxUY)

**App Export**

Not necessary I believe, very easy to reproduce.

**Additional context**

Open to contributing if you can point me to places ✨ Sadly, I won't be able to find the bug as I haven't contributed to Budibase yet.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7762](https://linear.app/budibase/issue/BUDI-7762/error-saving-queries-with-brackets-in-url)</sub>

**Comment by Meldiron** [comment]
In network tab I can see response from `POST /api/queries` is `{"message":"Invalid query name","status":400}`.

Name in payload seems to be `cloud_appwrite_io v1 databases main collections reminders documents?queries[]=limit(100)`

**Comment by Meldiron** [comment]
On the same note, I cannot get pagination to work because if those specific requirements for parameters.

For cursor pagination, I would need to send those two parameters:

`?queries[]=limit(5)&queries[]=offset(10)`. Can yo usee a way to do that in Budibase?

**Comment by melohagan** [comment]
Hey @Meldiron 

A couple of ideas:

1. Instead of directly using brackets in the URL, you could try using a binding instead. (https://docs.budibase.com/docs/rest-bindings)
2. Have a look at the appwrite custom datasource plugins: https://github.com/melohagan/budibase-datasource-appwrite

**Comment by Meldiron** [comment]
Hey there 👋

1. That works, thanks ❤️

2. I checked it and found the method used to list documents: `https://github.com/melohagan/budibase-datasource-appwrite-databases/blob/main/src/datasource.ts#L33` There is third parameter `queries` array, where stuff like filtering, pagination or sorting can be done. In the datasource plugin, this queries parameter is not being provided, so it doesn't help me understand how to paginate Appwrite database in Budibase.

**Comment by melohagan** [comment]
Hey @Meldiron 

I have updated the appwrite-databases connector to support queries 👍
