### ISSUE TITLE
[BUDI-7760] Relationship lost after adding a new column and add data to it

### ISSUE THREAD

**Issue by markusthiel** [Budibase/budibase#12425]
**Checklist**

* \[ x \] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker single image
  * Budibase Version: 2.13.12
  * App Version: 2.13.12

**Describe the bug**
Create a table "employee" with two columns. The first column contains a name, the second column is a relationship to another table in which a work schedule with dates can be edited. After an assignment has been made in the work schedule, the respective link, or possibly several, lands in the employee table in the relationship column. If a new column is added to the employee table and an entry is made there, the relationship assignments disappear.

**To Reproduce**

1. Go to Data
2. Create a table "employee" with a column "Name".
3. Create a second table "workschedule" with two columns "Date" and "Name" Name should be a relationship to "employee + Name"
4. Make some assignments in the table "workschedule".
5. Add a new column to "employee" like email or telephone.
6. Add an entree to someone who was previously assigned to some dates.
7. The new column in "employee" which includes the assignments gets lost, looses entrees.

**Expected behavior**
Database entrees should stay

**Screenshots**

![bug1](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/48e97755-a98c-4adb-9237-6f80f115a8ed/4f29e95b-ae08-4f75-a7fa-f1c75cdd6594?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC80OGU5Nzc1NS1hOThjLTRhZGItOTIzNy02ZjgwZjExNWE4ZWQvNGYyOWU5NWItYWUwOC00Zjc1LWE3ZmEtZjFjNzVjZGQ2NTk0IiwiaWF0IjoxNzAwNzM5ODk1LCJleHAiOjE3MDA4MjYyOTV9.Tr9j1T8xPd8hGlED-DmFR3NHjqyhuWkzIIKk7crKrvg)

![bug2](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/9258464e-9d1d-4899-b196-20a4a8016b84/859df172-9e1c-4984-89d9-24db2de2dac2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC85MjU4NDY0ZS05ZDFkLTQ4OTktYjE5Ni0yMGE0YTgwMTZiODQvODU5ZGYxNzItOWUxYy00OTg0LTg5ZDktMjRkYjJkZTJkYWMyIiwiaWF0IjoxNzAwNzM5ODk1LCJleHAiOjE3MDA4MjYyOTV9.9u1K_VDabeXLI2NaAjVmLTQElY4aGGiG5CXKhAL8B1M)

**App Export**
Is attached
[Testapp-export-1700732311254.tar.gz](https://github.com/Budibase/budibase/files/13448020/Testapp-export-1700732311254.tar.gz)

**Desktop (please complete the following information):**

* OS: Windows 11
* Browser chrome
* Version 119.0.6045.160

## **Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7760](https://linear.app/budibase/issue/BUDI-7760/relationship-lost-after-adding-a-new-column-and-add-data-to-it)</sub>

**Comment by ConorWebb96** [comment]
Hey @markusthiel,

Was there a specific relationship you used? I've just tried this on version 2.13.19. Haven't seen the behaviour you've described. Everything seems to work fine.

Your app export on the other hand it does indeed remove the relationships from the table.

Thanks for providing the export.

**Comment by ConorWebb96** [comment]
Wasn't able to replicate directly, had to use the app export provided in the issue to replicate what was being discussed in the issue.

**Comment by markusthiel** [comment]
I'm not exactly sure how to explain it. I am still new to the topic and have probably set up the simplest kind of app there is:

Two tables, which are linked via a simple relationship as shown in the following screen.

![image](https://github.com/Budibase/budibase/assets/4073474/29367998-2ac0-4261-8347-9da4f3f4f524)

This creates a new field in the People table, in which the assignments are entered. That's really all there is to it. Now, if I make changes in the People table, the assignment is lost.
