### ISSUE TITLE
[BUDI-7774] Javascript does not return false when executing script

### ISSUE THREAD

**Issue by walter-iseyon** [Budibase/budibase#12444]
**Checklist**
- [ X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: iseyon 

**Describe the bug**
I am using a piece of Javascript to validate that a specific value passed in a URL parameter is a valid UUID format. I have a function that consists of a Regex string and compare that with the URL parameter. When the parameter is in a valid format the function returns true, however when it is not in a valid format it does not return false. If I put false it quotes it will then return a value. The same issue does not occur with returning true. 

**To Reproduce**
1. Create a page with a url parameter such as /:uuid
2. Create an action on the Screen to "Show Notification" and turn off Auto Dismiss
3. Place the below javascript in the message 
4. run the screen with an empty or invalid uuid and you will not see anything
5. Run the screen with a valid uuid i.e. 5b53dee3-dd47-4841-ba15-563faf137748 and you will see that it returns true in the notification

**Expected behavior**
I expect that the Javascript should return true or false when the function executes.

**Screenshots**

  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.
[javascript_bug-export-1700847360247.tar.gz](https://github.com/Budibase/budibase/files/13461507/javascript_bug-export-1700847360247.tar.gz)

**Desktop (please complete the following information):**
 - OS: Mac Sonoma
 - Browser Safari 17.1 and Chrome 119.0.6045.159

<sub>[BUDI-7774](https://linear.app/budibase/issue/BUDI-7774/javascript-does-not-return-false-when-executing-script)</sub>

**Comment by andz-bb** [comment]
@ConorWebb96 to investigate app export

**Comment by ConorWebb96** [comment]
Hey @[**walter-iseyon**](https://github.com/walter-iseyon)**,
**
It seems pieces of your code are not quite correct or point at variables that don't exist. You aren't checking against the correct bindings for the url parameter. I don't believe i've ever seen \`\[url\]\` syntax within Budibase.

I've made a few changes to the app to get this to work. One being changing the `:uuid` to `:id`on the url, just for simplicity sake. Next i changed the returns from boolean values to the string variants `"true"` or `"false"`. Lastly I fixed the issue with referencing the const for the url variable. You can see all these changes in the exported app below.

[js bug-export-1701245554776.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/d25f3779-8692-4756-b8ca-d41fcc06849d/77e6c093-74ca-4c0e-847c-2bebf0b7eda3)


Additionally it seems to handle both cases, so aside from these changes the code would have worked.

I hope this helps.

**Comment by walter-iseyon** [comment]
@ConorWebb96 

Thanks for reviewing the code. I'm not able to download the bug export to take a look at what was done since it is on Linear and doesn't look like we have access. I was really only concerned with why the Javascript wouldn't return boolean values for both true and false. I can work around it with making them strings but thought I should point it out since it didn't make sense to me. Thanks

**Comment by ConorWebb96** [comment]
Hey @walter-iseyon,

Apologies, I'll re upload it here. [js bug-export-1701245554776.tar.gz](https://github.com/Budibase/budibase/files/13502565/js.bug-export-1701245554776.tar.gz)
