### ISSUE TITLE
[BUDI-7781] Cannot perform range filter - invalid type

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#12448]
**Checklist**

* I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker
  * Budibase Version: 2.13.17
  * App Version: **anything after 2.13.11**

**Describe the bug**
I have a form in my application which is working fine in 2.13.11 but when I have tried to update to any newer version the form does not show and console shows the error 'Uncaught (in promise) Cannot perform range filter - invalid type.'

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/888a38f5-2290-4043-8581-b9b3a621afc2/d3194da6-b978-4664-adea-7c15dc02182e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC84ODhhMzhmNS0yMjkwLTQwNDMtODU4MS1iOWIzYTYyMWFmYzIvZDMxOTRkYTYtYjk3OC00NjY0LWFkZWEtN2MxNWRjMDIxODJlIiwiaWF0IjoxNzAxMTAyMjM2LCJleHAiOjE3MDExODg2MzZ9.9lG4hR4MmcSRLROoMdIWZCJ7PAtyTfKHGfax3meW2jw)

If I revert the application to 2.13.11 it then works again.

**To Reproduce**
I'm not sure how to reproduce this. If needed I can send a export of the application to an email addresss.

**App Export**
Can provide by email.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7781](https://linear.app/budibase/issue/BUDI-7781/cannot-perform-range-filter-invalid-type)</sub>

**Comment by melohagan** [comment]
Hey @andyburgessmd 

This would be because of a recent code change I made: https://github.com/Budibase/budibase/pull/12413/files

Apologies for that. Could you provide me with the following additional context please:

- Database being used, e.g. Postgres, Internal DB, etc
- The data type of the column being filtered (text, date, number, etc)
- Screenshots of your filter drawer
- Example row data that is throwing the error when filtered

**Comment by andyburgessmd** [comment]
Hi @melohagan 
The database type is an internal db table but I don't have answers to the others.
The error is being thrown on a page that has a create form on it, there are no data providers and nothing is being filtered.
The form does have some relationship pickers, options pickers and a user field if any of them could be relevant?

**Comment by andyburgessmd** [comment]
@melohagan turns out its a headline component with some JS which works out a score from some values which are set from options pickers.
![image](https://github.com/Budibase/budibase/assets/110813989/b962ecce-55ce-4cde-9038-6ef91337d3de)
![image](https://github.com/Budibase/budibase/assets/110813989/58eaad10-c807-472a-94ce-b531864490a1)
When the score component is removed the page renders.
JS in the binding is 
`if (!$("Form.Fields.Impact") || !$("Form.Fields.Risk") || !$("Form.Fields.Priority") || !$("Form.Fields.Criticality")){
  return "";
} else {
  return "Risk score " + ((helpers.toInt(helpers.truncate($("Form.Fields.Impact"), 1)) + helpers.toInt(helpers.truncate($("Form.Fields.Risk"), 1)) + helpers.toInt(helpers.truncate($("Form.Fields.Priority"), 1)) + helpers.toInt(helpers.truncate($("Form.Fields.Criticality"), 1)))/16*100) + "%";
}`

**Comment by manwithpowers** [comment]
I'm having this same issue when updating to `2.13.14+`
I have a form field with a page number and a conditional on a button checking for the value of that field; when that conditional is set to "number", I get the `Cannot perform range filter - invalid type.` error and no data loads in the parent data provider. If I change the conditional type (for instance to 'binding') or remove it completely, the error goes away.
This works:
![Screenshot 2023-11-28 at 12 27 13](https://github.com/Budibase/budibase/assets/5508635/1d37c79a-e32a-44fb-ab27-4cb3bbab3e08)
This does not:
![Screenshot 2023-11-28 at 12 27 24](https://github.com/Budibase/budibase/assets/5508635/fb04d004-d4ad-464b-9dba-e97e5371b633)

**Comment by gmentzik** [comment]
Hi @melohagan, 
As currently I am stuck with maximum version 2.13.17 due to the change in users count and till my company decides if it will pay for extra users license i would like to ask if this bug affects only component conditionals or other cases also. Checking the source code I am not absolutely sure about it. Thank you.

**Comment by melohagan** [comment]
Hey @gmentzik from memory this did only impact components with conditional UI. Filtering data was not impacted.

**Comment by melohagan** [comment]
> > Hey @gmentzik from memory this did only impact components with conditional UI. Filtering data was not impacted.
> 
> Function runLuceneQuery in filters.ts that contains rangeMatch in question is called in following files. packages/client/src/utils/conditions.js, which I suppose is for the component conditions packages/frontend-core/src/fetch/DataFetch.js packages/server/src/integrations/googlesheets.ts
> 
> Could the other 2 cause same issue or exception is triggered only in component conditions case?

I believe it was only triggered in the component conditions. The error was thrown because the bindings in the conditions were not being interpreted within the builder, so it was trying to do a range filter on `{{ binding }}` which not a valid number or date.
