### ISSUE TITLE
[BUDI-7784] [BUG] When adding a new column to a table with views, those views are deleted

### ISSUE THREAD

**Issue by Shadowfita** [Budibase/budibase#12470]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.13.20
  - App Version: 2.13.20

**Describe the bug**
When adding a new column to a table with views, those views are deleted.

**To Reproduce**
When adding a new column to a table with views, those views are deleted.

**Expected behavior**
Views should adopt the new column and not be deleted.
 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version Version 119.0.2151.93 (Official build) (64-bit)

<sub>[BUDI-7784](https://linear.app/budibase/issue/BUDI-7784/[bug]-when-adding-a-new-column-to-a-table-with-views-those-views-are)</sub>

**Comment by mike12345567** [comment]
Fixed in https://github.com/Budibase/budibase/pull/13011
