### ISSUE TITLE
[BUDI-7789] Increase services.objectStore.storage default value to 2GB

### ISSUE THREAD

**Issue by likke812** [Budibase/budibase#12483]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: k8s
  * Budibase Version: 2.13.20
  * App Version: 2.10.1

**Describe the bug**
After we upgraded Budibase platform using K8S successfully, we can not update Budibase APP from 2.10.1 to 2.13.10 with popup error as below:
`Error updating app: [object Object]`

And there has HTTP 507 error when checking browser inspector:
`POST https://***/api/applications/app_dev_***/client/update 507 (Insufficient Storage)`
`[Builder] HTTP 507 on POST:https://***/api/applications/app_dev_***/client/update `
`Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.`

**To Reproduce**

1. Go to 'APP -> Update'
2. Click on 'Update' button and confirm the application update button again
3. See error

**Expected behavior**
Update Budibase application to 2.13.20 successfully

**Screenshots**
Error snapshot:

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/4f9934ac-448e-4baf-a66b-8604166658de/abb94806-6ef4-4c8f-8166-154a65709ae8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC80Zjk5MzRhYy00NDhlLTRiYWYtYTY2Yi04NjA0MTY2NjU4ZGUvYWJiOTQ4MDYtNmVmNC00YzhmLTgxNjYtMTU0YTY1NzA5YWU4IiwiaWF0IjoxNzAxOTM4MTYwLCJleHAiOjE3MDIwMjQ1NjB9.1mgWktJMAy8NWVvzI3zz532I6b9JLBImMBZlT1ZV1Vo)

**App Export**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Chrome and Firefox
* Version: 119 and 120

**Additional context**
The df output of all of the three DBs:

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ab92bfa2-733b-4569-94b6-f6dd1b1f6360/de5f00e8-60bc-4307-be48-85224e900e20?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hYjkyYmZhMi03MzNiLTQ1NjktOTRiNi1mNmRkMWIxZjYzNjAvZGU1ZjAwZTgtNjBiYy00MzA3LWJlNDgtODUyMjRlOTAwZTIwIiwiaWF0IjoxNzAxMzc0NzkyLCJleHAiOjE3MDE0NjExOTJ9.rbN0YTxfQrTddeK4FMCUI81EJS17t0uktWXUW8ZJ3zU)

Try to update the storage property to 200Mi and then update the deployment, but no effect. Following this post from discussion:
[https://github.com/Budibase/budibase/discussions/10559](https://github.com/Budibase/budibase/discussions/10559)

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/afa871c2-c0be-476f-84a3-bc242d0c6fbb/598ec9b0-031b-4e7e-bba3-5f82c9c8ecdb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hZmE4NzFjMi1jMGJlLTQ3NmYtODRhMy1iYzI0MmQwYzZmYmIvNTk4ZWM5YjAtMDMxYi00ZTdlLWJiYTMtNWY4MmM5YzhlY2RiIiwiaWF0IjoxNzAxMzc0NzkyLCJleHAiOjE3MDE0NjExOTJ9.1m_bblucLp1Hf8U19y_lho8gUMOlqdMOEuJSLWTeotw)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7789](https://linear.app/budibase/issue/BUDI-7789/increase-servicesobjectstorestorage-default-value-to-2gb)</sub>

**Comment by likke812** [comment]
> Hey @likke812
> 
> I think this is a MinIO issue. Could you try what was suggested here? #8038
> 
> Otherwise make sure that you have enough disk space.

I have tried to reset my Chrome browser cache or try it with different browser like Firefox or MS Edge. But still I can see the same error.

We have checked with the DB file system storage and it seems there has enough free space?

**Comment by melohagan** [comment]
Hey @likke812 We have recently updated our helm chart. Could you follow this guide and see if it helps? https://github.com/Budibase/budibase/tree/master/charts/budibase#upgrading

**Comment by likke812** [comment]
> Hey @likke812 We have recently updated our helm chart. Could you follow this guide and see if it helps? https://github.com/Budibase/budibase/tree/master/charts/budibase#upgrading

Hi @melohagan,

We have upgrade our helm chart to 3.0.1 and upgrade Budibase to the latest version - 2.13.31.

But I can still see the same HTTP 507 (Insufficient Storage) error when I tried to update APP from 2.10.1 to 2.13.31.

It seems this helm chart update is not help for my issue :-(

**Comment by melohagan** [comment]
> > Hey @likke812 We have recently updated our helm chart. Could you follow this guide and see if it helps? https://github.com/Budibase/budibase/tree/master/charts/budibase#upgrading
> 
> Hi @melohagan,
> 
> We have upgrade our helm chart to 3.0.1 and upgrade Budibase to the latest version - 2.13.31.
> 
> But I can still see the same HTTP 507 (Insufficient Storage) error when I tried to update APP from 2.10.1 to 2.13.31.
> 
> It seems this helm chart update is not help for my issue :-(

How many attachments do you have across your apps?

**Comment by likke812** [comment]
> > > Hey @likke812 We have recently updated our helm chart. Could you follow this guide and see if it helps? https://github.com/Budibase/budibase/tree/master/charts/budibase#upgrading
> > 
> > 
> > Hi @melohagan,
> > We have upgrade our helm chart to 3.0.1 and upgrade Budibase to the latest version - 2.13.31.
> > But I can still see the same HTTP 507 (Insufficient Storage) error when I tried to update APP from 2.10.1 to 2.13.31.
> > It seems this helm chart update is not help for my issue :-(
> 
> How many attachments do you have across your apps?

I am not clear about "attachments" in your question. I have two APPs in my budibase system with four users accessing to them. I don't have any plugin on my Budibase. In each APP, we have rest api queries and external MySQL database.

**Comment by melohagan** [comment]
I meant image or file attachments via the attachment column of the internal DB, but that does not appear to be the case for you.

**Comment by melohagan** [comment]
Have you searched for that error anywhere else - such as follow through this here: https://github.com/minio/minio/issues/16185

**Comment by likke812** [comment]
> Have you searched for that error anywhere else - such as follow through this here: [minio/minio#16185](https://github.com/minio/minio/issues/16185)

**Comment by melohagan** [comment]
> > > Have you searched for that error anywhere else - such as follow through this here: [minio/minio#16185](https://github.com/minio/minio/issues/16185)
> 
> Thank you @melohagan for your comments! I did searched online to see if there has some tips for this error message for Minio and I got the answer:
> 
> [minio/minio#6795](https://github.com/minio/minio/issues/6795)
> 
> From this post, I understand the object persistent storage for Minio shall be at least 1Gb free space which the minimum value is not configurable. So we increase the persistent storage mount volume /data for Minio from 1Gb to 2Gb and now it works fine for the APP updating!
> 
> ![MicrosoftTeams-image](https://private-user-images.githubusercontent.com/144492487/288548106-59affe81-3994-45c1-bdd1-b1b3d68189f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzgzNTksIm5iZiI6MTcwMTkzODA1OSwicGF0aCI6Ii8xNDQ0OTI0ODcvMjg4NTQ4MTA2LTU5YWZmZTgxLTM5OTQtNDVjMS1iZGQxLWIxYjNkNjgxODlmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwODM0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDFjMmE0OTkwYjM5ZjUyN2M3MzhkNzE2MWJlYWZjMzFlMjM1MDYyZWQ2ZTc1ODI2MDlhMDdjMTBjZDhlMGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.azNK3LF1958Sh_6f9OzQIkQLIlGm438oR_DKyq6_1JY)
> 
> BTW, I guess the upgrading document for Budibase needs to be updated for the "services.objectStore.storage" value, the default 100Mi is not enough(in our case, by default the persistent volume for Minio is 974Mb). It could be set the value to over 1Gb. https://github.com/Budibase/budibase/tree/master/charts/budibase#upgrading

Thanks very much for this suggestion! I'll update the issue title 👍

**Comment by samwho** [comment]
@likke812 thanks for the suggestion here! I just merged a PR changing that default. Going to close this out now, feel free to get back in touch if you have any other problems! 🙏
