### ISSUE TITLE
Suddenly unable to login to builder

### ISSUE THREAD

**Issue by gitguy1988** [Budibase/budibase#12506]
**Checklist**
- [*] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud
  - Tenant ID: abcconcrete
**Describe the bug**
I can no longer access the builder page.  i am redirected to the login page.  Occasionally i am able to login momentarily before a large amount of error notifications appear and i am taken back to the login page.  i have deleted my cookies and tried numerous devices and browsers.

**To Reproduce**
1. Go to login page
2. Enter credentials
3. Click on log in

**Expected behavior**
Login is successful and I am able to access my data

**Screenshots**
[Screenshot_20231205-160501](https://github.com/Budibase/budibase/assets/114008745/8eb2af7e-7cd5-47de-a788-7cca088eec30)

**Comment by gitguy1988** [comment]
Suddenly seems to be working again for now after about 3 hours of panic.   I will reopen the issue if I encounter it again.

**Comment by melohagan** [comment]
Hey @gitguy1988 @applicationuser

And engineer has dug into this issue and some tweaks to our production cloud environment have been made, that should hopefully see some improvement going forward.

Nonetheless we will continue to keep an eye out.
