### ISSUE TITLE
[BUDI-7814] Custom SQL query schema does not update when the query body changes

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#12502]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.13.28

**Describe the bug**
When I change the body of an existing SQL query, the schema does not update to reflect this.

**To Reproduce**

1. Add a read query that selects from one table
2. Run and save -> see that the schema is correctly set
3. Change the read query to select from a different table
4. Run and save -> see that the schema has not updated, even though none of the fields match

**Expected behavior**
If you change the body of a SQL query and the fields returned are different, then the schema should be updated.

**Screenshots**

![Screenshot 2023-12-05 at 12 56 23](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b8cbe431-7154-4d0f-8400-341a1b97a147/21593eac-fefe-45ba-ae20-2fa50ebd0ea2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9iOGNiZTQzMS03MTU0LTRkMGYtODQwMC0zNDFhMWI5N2ExNDcvMjE1OTNlYWMtZmVmZS00NWJhLWFlMjAtMmZhNTBlYmQwZWEyIiwiaWF0IjoxNzAxNzgxNzQ4LCJleHAiOjE3MDE4NjgxNDh9.lY2n0tM3XIWJQoEmqNsRrU8ci_0fc_BAWmuqvTlL2L8)

*Response after changing the query body*

![Screenshot 2023-12-05 at 12 56 52](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e863b833-97b1-425e-ac4c-2701c987b498/62db48a7-9371-4dab-a650-793c5c872aa5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lODYzYjgzMy05N2IxLTQyNWUtYWM0Yy0yNzAxYzk4N2I0OTgvNjJkYjQ4YTctOTM3MS00ZGFiLWE2NTAtNzkzYzVjODcyYWE1IiwiaWF0IjoxNzAxNzgxNzQ4LCJleHAiOjE3MDE4NjgxNDh9.0fcfmCPicsIaDJ80EYzjjW5fRe6pv4ruiyRPS75WFnU)

*But the old schema is still being used*

The schema will correctly update after clearing all of the existing schema fields, and running the query again.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7814](https://linear.app/budibase/issue/BUDI-7814/custom-sql-query-schema-does-not-update-when-the-query-body-changes)</sub>

**Comment by mike12345567** [comment]
Fixed as of 2.22 release.
