### ISSUE TITLE
[BUDI-7817] Budibase Builder fails to save changes to the "Styles" and "Conditions" settings of components

### ISSUE THREAD

**Issue by gitguy1988** [Budibase/budibase#12515]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: abcconcrete

**Describe the bug**
None of my components, regardless of how they are (or aren't) nested, seem to retain any changes made to the "Styles" or "Conditions" tabs of the component settings panel.  There are no notifications or alerts to imply that any modifications have failed to save.  Changes made to the "Settings" tab seem to work fine.

**To Reproduce**
1. Click "edit" for any apps on the app portal page
2. Navigate to the Design interface
3. Select any component (forms, containers, buttons, etc.)
4. Click on "Styles" or "Conditions" in the component settings panel
5. Modify any options available in "Styles" or "Conditions"
6. Click "Save" in the case of Conditions or simply change focus to a new component in the case of Styles

**Expected behavior**
Modifications made to the Conditions or Styles of my components take effect, and the Components and Styles tab interface reflects the modifications made.

**Screenshots**
  
**App Export**
[Pour Log V6-export-1701898155616.tar.gz](https://github.com/Budibase/budibase/files/13591775/Pour.Log.V6-export-1701898155616.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (also happens in Edge and Chrome)
 - Version: Budibase - 2.13.34, Firefox - 119.0.1

**Additional Context**
This behavior occurs in my other apps as well.  Could possibly be related to my issue raised in [#12506](https://github.com/Budibase/budibase/issues/12506), as the problem seemed to start after the issue seemed to resolve itself.

<sub>[BUDI-7817](https://linear.app/budibase/issue/BUDI-7817/budibase-builder-fails-to-save-changes-to-the-styles-and-conditions)</sub>

**Comment by walter-iseyon** [comment]
Can confirm that I am having the same issue. Thanks

**Comment by patricialguima** [comment]
The same thing happens to me :-(

**Comment by walter-iseyon** [comment]
I don't know if it is related or not but all of the layouts of my apps have suddenly changed as well. For example text components on a form used to have the label title above the component, now all of a sudden they are all to the left of the text box. 
<img width="540" alt="image" src="https://github.com/Budibase/budibase/assets/140833279/ea128594-fcb7-498a-aa7c-3abe95762a01">
