### ISSUE TITLE
[BUDI-7825] Conditional UI feature broken in Budibase 2.13.35

### ISSUE THREAD

**Issue by iambricegg** [Budibase/budibase#12536]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.13.35
  - App Version: 2.13.35

**Describe the bug**
The conditional UI feature to Show/Hide/Update Setting in a UI Component is broken. After configuring the feature on a UI component and press save button, nothing happened. The setting aren't save as if nothing was configured. Nothing is fired in the logs. 

**To Reproduce**
1. Select a UI component
2. Navigate to Condition Tab of the component settings 
3. Configure a Show/Hide feature
4. Click 'Save'
5. See nothing happened.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 120

<sub>[BUDI-7825](https://linear.app/budibase/issue/BUDI-7825/conditional-ui-feature-broken-in-budibase-21335)</sub>

**Comment by andz-bb** [comment]
hey @iambricegg, I believe this one was fixed in 2.13.35. We couldn't recreate it on our end today. Could you try updating your docker-compose and trying again? If you still are having problems could you let us know the component and conditions you are using please? An app export would be ideal! Thanks

**Comment by iambricegg** [comment]
The bug start to show when I was on Budibase 2.13.34 and has continued to show up despite after upgrading to Budibase 2.13.35.
But... After try again today, it's worked as expected ! I don't know why, I don't know how. The only big change I made in my app is to change the columns naming of my Budibase database.
