### ISSUE TITLE
Field of side panel can't be modified within Tableblock

### ISSUE THREAD

**Issue by sangluocun** [Budibase/budibase#12589]
**Checklist**
- [ Y] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud

**Describe the bug**
1. Create a screen with table block(internal db), enable the "Show details side panel",  the side panel for insert/update show all of field.

2. Disable one of the field, preview the screen, none of field dispaly.

**Expected behavior**
Enabled field should be display correctly

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/3936345/34625397-2588-4da1-b16b-95c3cb54a5a1)
![image](https://github.com/Budibase/budibase/assets/3936345/2838a2fb-cfa1-44e9-ab4b-62f93fb65c6c)

**Additional context**
Does it by designed?

**Comment by melohagan** [comment]
Hey @sangluocun 

I can't reproduce this one. Are you able to provide an app export please?

**Comment by sangluocun** [comment]
Thanks for reply,

I see a "update" button in cloud enviroment, click it and the issue gone.

I thought the root cause is my app designed by old version, the version
