### ISSUE TITLE
Multiple Pending invites for same user

### ISSUE THREAD

**Issue by MisterSeagull** [Budibase/budibase#12656]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Docker Compose
  - Budibase Version: 2.13.48

**Describe the bug**
Connectivity issues when sending invite to user resulted in the invite being generated multiple times and I now have multiple pending invites outstanding for a user that is currently registered.

**To Reproduce**
1. Go to Users in the top right of the Nav bar within an app
2. Click on blue Invite User button
3. Fill out email and click on invite user multiple times

**Expected behavior**
A single user invite will be sent out

**Screenshots**
![2023-12-21 13_03_09-Clipboard](https://github.com/Budibase/budibase/assets/12835264/7b8cff46-7ce5-468b-a023-de329c19a244)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox 120.0.1

**Additional context**
All four invites in the pending invite list are to the same user.

**Comment by ConorWebb96** [comment]
Hey @MisterSeagull,

This is a duplicate issue of the one created [here](https://github.com/Budibase/budibase/issues/11044). Closing for now.
