### ISSUE TITLE
Access for groups is removed

### ISSUE THREAD

**Issue by leuedaniel** [Budibase/budibase#12669]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker single image 
  - Budibase Version: 2.13.50 

**Describe the bug**
I assign access to the app as Basic to different groups within the app. The users of the corresponding groups are displayed in the app's Users table. 
![image](https://github.com/Budibase/budibase/assets/44936305/61b35584-f5ab-4f85-80ce-f1fb2f2b7294)
I unpublish the app and publish it again. The assignment to the groups disappears. If I now exit the editing mode of the app and then open it again, the users have also disappeared from the users table.
![image](https://github.com/Budibase/budibase/assets/44936305/6f168658-6ed8-4fe7-bbfb-b5badce63321)

**To Reproduce**
1. edit app
2. allow access as Basic on a group
3. check whether users of the group exist in the user table
4. unpublish app
5. publish app
6. check whether assignment for Basic still exists on group
7. quit editing the app and open it again
8. users of the groups have been removed from the user table

**Expected behavior**
If I assign a role to a group, this assignment should not be lost by unpublishing and republishing

**Comment by ConorWebb96** [comment]
Hey @leuedaniel,

Can you update to the latest version of Budibase. I wasn't able to replicate this issue.

Thanks in advance!
