### ISSUE TITLE
Cannot save REST API config when creating/modifying a REST datasource

### ISSUE THREAD

**Issue by kludd** [Budibase/budibase#12666]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: snyting.budibase.app 

**Describe the bug**
Clicking the button "Save and continue to query" for the REST API config does not save the connector config. The behaviour is very like the one described in a previous issue [BUDI-7098](https://github.com/Budibase/budibase/issues/10830)

**To Reproduce**

1. Add a new REST connector
2. Change the name and/or toggle "Reject Unauthorized"
3. Click "Save and continue to query"

The button is greyed out but nothing happens. When reloading or closing the dialogue, the changes are not saved.

**Expected behavior**
I should be able to save a REST API connector.

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/12787639/172e38b7-a445-43b6-b2ec-603eda3eb44b)
  
**App Export**
NA

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave (also Chrome and Edge)

**Additional context**
NA

**Comment by ConorWebb96** [comment]
This definitely seems to be a bug, it looks like nothing is triggering whenever clicking the button to save your changes to the config.

Nothing is fired in the network/no console errors etc.

**Comment by melohagan** [comment]
I fixed this one a while back 👍 

https://github.com/Budibase/budibase/pull/12619
