### ISSUE TITLE
Query does not return results when inside a Table

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#12739]
**Checklist**
- [ X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: raventech.budibase.app -->

**Describe the bug**
I created a button with action to execute a query.
When this query sits under a Table Block results are returned as expected.
When it is under a  TABLE, 'undefined' results are returned for the exact same query.

**To Reproduce**
Add New Data Provider
Add Table Block
Add button to query the ID of each selected row in the database.
works!

Add New Data Provider
Add Table
Add button to query the ID of each selected row in the database.
no work!

**Expected behavior**
Whats the difference between Table and Table Block.
The query is and should be independent of the data view.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 2.14.2

**Comment by melohagan** [comment]
@raventechnologiesinc 

Please provide screenshots :)

**Comment by raventechnologiesinc** [comment]
![Screenshot 2024-01-09 185110](https://github.com/Budibase/budibase/assets/156072718/d3f90e00-9caf-45a3-a244-b39c5c37e64f)
![Screenshot 2024-01-09 185159](https://github.com/Budibase/budibase/assets/156072718/899c4ff7-c7c9-4feb-9588-98dfaf6d40d8)


Notice where the NEW TABLE BLOCK is nested in the form.

As is , every thing works.  The TALLY button executes the query as expected and returns data.

--- The only reason to switch to an TABLE component is to display graphics and buttons in the columns/rows.  If I replace the New Table Block with a standard TABLE, the query returns a null/undefined (js returned).

--- The query is read/SUM only, No math or calculation are done afterward.  It does nothing that is dependent on the underlying table/block.

**Comment by melohagan** [comment]
And could you share the JavaScript as well please @raventechnologiesinc 

If you're using the selected rows binding you want to make sure it's correct.

**Comment by raventechnologiesinc** [comment]
This JS script parses the Selected rows from the TABLE or TABLE BLOCK (re-referenced when changed to different data provider)

var rows =$("New Table Block.Selected rows");
var csv= "";
for (let i = 0; i < rows.length; i++) {
x=decodeURIComponent(rows[i]);
x= x.replace('[','');
x= x.replace(']','');

  if(i == rows.length-1){
  csv=csv + x.toString();
  }else{
   csv=csv + x.toString()+',';
  }
}
return csv;


JS returns a comma delimited list of rowID  passed to Execute Query

**Comment by melohagan** [comment]
Related discussion: https://github.com/Budibase/budibase/discussions/11344#discussioncomment-8070241

**Comment by melohagan** [comment]
Hey @raventechnologiesinc 

I have tested a Table block and Table select rows and I can see that the output from the selected rows binding is identical:
![Screenshot 2024-01-10 at 09 22 40](https://github.com/Budibase/budibase/assets/101575380/cb32289f-a559-4cfb-8374-5788eab067b1)

*The order is different because the rows were selected in a different order*.

I would make sure that your bindings are definitely correct. If you share an app export I can have a closer look.

**Comment by raventechnologiesinc** [comment]
Yes it is.  Thanks for confirming.  Setup A/B experiment to confirm.
And both compnents seems to work.  It boiled down to the CSV encap in () that cause undefined query result to return.

Query param (123,124,125) passed to Table Block comes back with incorrect SUM.
Query param (123,124,125) passed to Table  comes back with undefined.

Removed (), as in the supplied JS above....it seems to work perfectly.
