### ISSUE TITLE
users' role change automatically

### ISSUE THREAD

**Issue by joeytzy** [Budibase/budibase#12734]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.8.2
  - App Version: 2.8.2

**Describe the bug**
Users' role automatically changed from ADMIN to BASIC. All admin accounts will have their role changed from ADMIN to BASIC. It does not seems to affect user accounts that already have their role set to BASIC. I have to manually change the role back to ADMIN. Initially thought the issue could be due to duplicate budibase internal roles but it seems like the duplicate role issue is just a visual issue as stated here #11666

**To Reproduce**
Does not have a step to replicate this issue since this happened automatically every few days when i open budibase.

**Expected behavior**
Admin user accounts should have their role set as ADMIN and not change to other roles such as BASIC

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/44018390/c3a70942-2afc-41ab-b237-29233e8c1187)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 120.0.6099.199

**Comment by andz-bb** [comment]
@joeytzy can you try updating your Budibase instance to the latest version and see if it still happens?

**Comment by joeytzy** [comment]
will try. it might take few days to see if it works as I have mentioned that this issue appears every few days
