### ISSUE TITLE
Table column that contains attachments should show attachment names instead of types

### ISSUE THREAD

**Issue by leonzaher** [Budibase/budibase#12733]
### Description

Table component showing Attachment type values shows file type. Is there a way to set this in current version?

Reproduction steps:

* Create BudibaseDB table that has Attachment types
* In design tab, create a Provider for the table, then add Table component that shows attachments

### Currently

![Screenshot 2024-01-08 at 19 11 12](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/d4b1918c-a05b-4712-87ac-1fb3113cba5c/2c64384c-8355-4012-b81b-fc527b15f3f0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9kNGIxOTE4Yy1hMDViLTQ3MTItODdhYy0xZmIzMTEzY2JhNWMvMmM2NDM4NGMtODM1NS00MDEyLWI4MWItZmM1MjdiMTVmM2YwIiwiaWF0IjoxNzA0Nzk5NzMzLCJleHAiOjMzMjc1MzU5NzMzfQ.O7vUMWHP3Y8n8VcRjMrMhbm113dQf6Z1sPdLYXD2t20 "=212x")

### Wanted

![Screenshot 2024-01-08 at 19 10 56](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/49fc8e91-138f-4790-a591-e82ecb0559d6/bc9f4bda-a354-422f-8a60-18e69a757a85?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC80OWZjOGU5MS0xMzhmLTQ3OTAtYTU5MS1lODJlY2IwNTU5ZDYvYmM5ZjRiZGEtYTM1NC00MjJmLThhNjAtMThlNjlhNzU3YTg1IiwiaWF0IjoxNzA0Nzk5NzMzLCJleHAiOjMzMjc1MzU5NzMzfQ.Q6quPbIvdddVk4WsozesdJDM3wpZHwxDOd1iWezGBPQ "=212x")

**Comment by melohagan** [comment]
![Screenshot 2024-01-09 at 13 55 54](https://github.com/Budibase/budibase/assets/101575380/f7629de5-942f-4c23-9bc3-620238b4ef8b)

I think there's a good reason why it is the way it is. If you have even a couple of long named attachments it will stretch the table either horizontally, or you could wrap it and then it would vertically expand. 

If you are wanting to have a screen displaying the attachment names, you may be better off building a custom view with the [Repeater](https://docs.budibase.com/docs/repeater) component.

**Comment by ConorWebb96** [comment]
Doesn't this already work, you simply have to hover over them and it will show the name.
<img width="180" alt="Screenshot 2024-01-17 at 10 48 27" src="https://github.com/Budibase/budibase/assets/126772285/7ace9296-2669-4396-babd-ea3f75b77187">
