### ISSUE TITLE
SUM Query yields different results

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#12737]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

- Cloud
  - Tenant ID: raven.budibase.app 

**Describe the bug**
I created a query in BUDIBASE, execute it with a button link to a Dataprovider

SELECT SUM(LBS) AS SUMLBS
FROM CustomerBill
WHERE id
IN {{rowArray}};    

 ===> (137304,137303,137302)   yields 22.65   (record id#)
 ===> (137302,137303,137304)   yields 17.6

**Expected behavior**

When running same query directly on MariaDB
Actual value :  12.75  9.90 , 7.70  Direct SQL to server yields correct value = 30.35

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 2.14.4

**Comment by melohagan** [comment]
Hey @raventechnologiesinc 

How many rows do you want to sum over for the internal DB?

**Comment by melohagan** [comment]
Hey @raventechnologiesinc 

Could you please include some screenshots to demonstrate the problem you are seeing.

Also please provide the SQL schema of `CustomerBill` please (https://docs.budibase.com/docs/troubleshooting-sql)

**Comment by raventechnologiesinc** [comment]
Attached are two variations of the query and result from external SQL server

![Screenshot 2024-01-09 173538](https://github.com/Budibase/budibase/assets/156072718/d87c5e04-dbef-4805-9156-45c5da3258f0)
![Screenshot 2024-01-09 173639](https://github.com/Budibase/budibase/assets/156072718/706c7e79-34bc-45cd-8198-585dd9122ebc)
![Screenshot 2024-01-09 1736310](https://github.com/Budibase/budibase/assets/156072718/449b8fb1-5603-4e47-ac2c-3d5acd7dcabb)

**Comment by melohagan** [comment]
Thank you!

> ===> (137304,137303,137302) yields 22.65 (record id#)
===> (137302,137303,137304) yields 17.6

Does it look like it's ignoring the last or first ids?

What happens if you try the binding simple as: `137304,137303,137302` (without the brackets) ?

**Comment by raventechnologiesinc** [comment]
My DB Schema
![Screenshot 2024-01-09 174310](https://github.com/Budibase/budibase/assets/156072718/2537ad05-621f-4799-a07f-89ba0e2f617c)

**Comment by raventechnologiesinc** [comment]
> Thank you!
> 
> > ===> (137304,137303,137302) yields 22.65 (record id#)
> > ===> (137302,137303,137304) yields 17.6
> 
> Does it look like it's ignoring the last or first ids?
> 
> What happens if you try the binding simple as: `137304,137303,137302` (without the brackets) ?

Amazing!

It appears to obviously ignore the FIRST data.

Without the ( ), the correct answer comes back!!

SQL Syntax is different for front and back end?

**Comment by raventechnologiesinc** [comment]
SQL query: [Copy](https://auth-db1200.hstgr.io/index.php?route=/table/sql&db=u499436164_budibase&table=CustomerBill#) Documentation


SELECT SUM(LBS) AS SUMLBS
FROM CustomerBill
WHERE id
IN 137304,137303,137302 LIMIT 0, 25
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '137304,137303,137302 LIMIT 0, 25' at line 4

**Comment by melohagan** [comment]
Awesome glad that worked! There's a bit more context from this old issue here: https://github.com/Budibase/budibase/issues/4978#issuecomment-1087380988

I think we do some escaping to protect against SQL injection, thus the brackets may be escaped if provided directly, but we do generate the brackets as needed in the backend if an IN is present!
