### ISSUE TITLE
BUDIBASE LOGIN constantly loop back without authentication errors

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#12745]
**Checklist**
- [x ] I have searched budibase discussions and github issues to check if my issue already exists

- Cloud
  - raventech.budibase.app

**Describe the bug**

I have checked status.budibase.app   All systems are UP.

I login use GOOGLE with creator account.  It loops back to the login screen.
I try using all the other 4 user accounts.  Same result and behavior.

Clear cache, nothing change.  Switched from Chrome to Edge.  Nothing

Turn on my VPN with USA address.  Can not login either.

All my web apps are still running though.

This had happen 3 time before this month around this time.
Im station and working from in Asia.  12 hours ahead of USA Central.

**Comment by mike12345567** [comment]
Hi @raventechnologiesinc - we have been experiencing an outage due to some issues with our CouchDB installation - we have updated our status page and are working on getting it resolved shortly - you should be able to follow the status of the issue here: https://status.budibase.com/
