### ISSUE TITLE
Custom CSS drawer not the correct width

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#12785]
**Checklist**

- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Cloud
  * Tenant ID: budimaster

**Describe the bug**
Custom CSS drawer not spanning the correct width.

![CleanShot 2024-01-15 at 15 22 53@2x](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/58d18e9d-dda8-4a23-a322-15d0109e955b/2a4ff0d1-c77d-412c-8aa1-24fc896ab743?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC81OGQxOGU5ZC1kZGE4LTRhMjMtYTMyMi0xNWQwMTA5ZTk1NWIvMmE0ZmYwZDEtYzc3ZC00MTJjLThhYTEtMjRmYzg5NmFiNzQzIiwiaWF0IjoxNzA1MzQxNTMxLCJleHAiOjMzMjc1OTAxNTMxfQ.tOFsFZvSptsoP23XVNSkZwWybHZ95N45_gNNTI2kNZ0)

**Comment by joebudi** [comment]
This may be the result of reducing the width of the screens panel.

**Comment by joebudi** [comment]
Hey @melohagan . Here's a video that may help:
https://vimeo.com/903603845/c4514562b0?share=copy

**Comment by melohagan** [comment]
Thanks @joebudi Andy was able to reproduce as well 👍

**Comment by melohagan** [comment]
To add to this one, the screen titles don't reveal more even when the panel is widened. 

![Screenshot 2024-01-31 at 13 17 59](https://github.com/Budibase/budibase/assets/101575380/fe805461-7eba-4079-b9bd-688ca9f41043)
*Plenty of space to show the full screen title*
