### ISSUE TITLE
The dollar character '$' should not auto-complete brackets for handlebars bindings

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#12794]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.14.8

**Describe the bug**
In handlebars I wanted to add a dollar symbol before a binding for currency purposes. I noticed that it incorrectly added brackets as if it was a JavaScript binding, i.e. `$("")`

**To Reproduce**
1. Click on the lightning icon for a binding
2. Within the `Text` tab type '$'
3. Notice that it autocompletes incorrectly to: `$("")`

**Expected behavior**
Dollar symbol should only auto-complete for JavaScript bindings.

**Screenshots**
![Screenshot 2024-01-16 at 14 15 05](https://github.com/Budibase/budibase/assets/101575380/8122c5db-9a00-4b4d-a4f2-b7dc4a5ac270)
*It should only do this in the JavaScript tab*

**Comment by ConorWebb96** [comment]
This seems to have been fixed.
