### ISSUE TITLE
You can currently select a one to one relationship type, this isn't support and won't allow you to do anything. No feedback to user to show why this isn't possible

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12797]
**Checklist**

- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.14.8
  * App Version: 2.14.8

**Describe the bug**
I believe a regression has occurred allowing you to select a one to one relationship whenever setting up your relationships. Previously there was validation that removed the one option if you had already select one as your first select. Currently you are able to select one to one, this breaks the form and doesn't allow you to proceed. Additionally there is no error outputted so the user is likely to be confused and would be stuck.

**To Reproduce**

1. Go to your data area
2. Try and setup a relationship with one to one
3. Notice the button gets grayed out but nothing happens
4. No error prompted, still able to select one to one.

**Expected behavior**
Either allow one to one relationships, or remove the option entirely whenever the first one to is selected. So users can't get into this situation.

**Screenshots**

![Screenshot 2024-01-17 at 08 22 37](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/8bc10f49-86dc-4ee3-a608-d223fb9eee6d/704cd568-75fb-4c47-9c02-92f906b2cd1e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC84YmMxMGY0OS04NmRjLTRlZTMtYTYwOC1kMjIzZmI5ZWVlNmQvNzA0Y2Q1NjgtNzVmYi00YzQ3LTljMDItOTJmOTA2YjJjZDFlIiwiaWF0IjoxNzA1NDg2ODY5LCJleHAiOjMzMjc2MDQ2ODY5fQ.0N2qHLrqlOt5f-4iLuY4mglRtoRc5lMbKRYKfE8Q9gs "=411x")

**Comment by mike12345567** [comment]
Fixed in: https://github.com/Budibase/budibase/pull/13210
