### ISSUE TITLE
Pagination fails when using a filter on a value from another table (via relationship)

### ISSUE THREAD

**Issue by maemigh** [Budibase/budibase#12806]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.14.5
  - Datasource: MySQL

**Describe the bug**
Pagination doesn't work after adding a filter based on a relationship.

Using 'table1' with a one-to-many relationship with 'table2'. When setting a table block to use 'table1' and then setting its filter on a column from 'table2', pagination stops working.

**To Reproduce**
1. Create two large tables, then create a one-to-many relationship from the first to the second
2. In the Design section, create a new table block using the first table as a datasource.
3. Create a filter which uses a column from the second table and filters out values
4. Enable pagination
5. Pagination doesn't work

**Comment by maemigh** [comment]
I don't seem to be having the problem now after deleting and re-adding a filter. I'm wondering if there is some sort of caching issue:

Steps I took if I recall correctly:
1. Load table from MySQL
2. Create data provider
3. Add Filter 'A' on a column from table
4. Go back to Data tab and add relationship to table
5. Edit data provider and add filter 'B' using value from that relationship

This is where I was and pagination didn't work. It suddenly started working again when deleting filter 'A'. And it continued working after I re-created filter 'A'.

**Comment by ConorWebb96** [comment]
Hey @maemigh,

I wasn't able to replicate this on the latest version of Budibase.

- MySQL server is running version 8.
- Budibase is 2.15.5

My tables consisted of authors and books and I had about 300 books to 75 authors and everything seemed to filter and paginate fine.

I'm going to close this issue for now as yourself and I weren't able to replicate this on either your version of Budibase or my own.

Thanks for providing all the information you did.
