### ISSUE TITLE
[ Builder ] - jsonarray columns dont apper in the fieldConfiguration property editor

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#12812]
I am not sure if this is by design, but the fieldConfiguration property editor will not show the json array and json object fields defined in a json column of an internal DB table.

![Screenshot 2024-01-18 at 7 18 24 PM](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/cfcb78ca-d568-49b8-bedc-7669bb45070e/0570acbc-359d-4dc8-b35b-ee79f9c768f2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9jZmNiNzhjYS1kNTY4LTQ5YjgtYmVkYy03NjY5YmI0NTA3MGUvMDU3MGFjYmMtMzU5ZC00ZGM4LWIzNWItZWU3OWY5Yzc2OGYyIiwiaWF0IjoxNzA2MDIxMjQ4LCJleHAiOjMzMjc2NTgxMjQ4fQ.Ifr1C-AI6igiPU7PaJcg_gSkfs1BNoWa7K1MBfvRc5U)

![Screenshot 2024-01-18 at 7 17 50 PM](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/3aa374b9-f9ec-462e-a3fa-942788920141/91ff898b-59dc-4356-b580-868b531d7b94?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8zYWEzNzRiOS1mOWVjLTQ2MmUtYTNmYS05NDI3ODg5MjAxNDEvOTFmZjg5OGItNTlkYy00MzU2LWI1ODAtODY4YjUzMWQ3Yjk0IiwiaWF0IjoxNzA2MDIxMjQ4LCJleHAiOjMzMjc2NTgxMjQ4fQ.GocWedo1PDUL37AJYzfnTpBmXODEGqOVBEjGpGJ5wf0)

**Comment by andz-bb** [comment]
@poirazis addressed this in my response to #12820
