### ISSUE TITLE
[ Builder ] - property type "field/array" doesnt list available jsonarray fields in the Form Schema

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#12820]
When you set property to type "field/array", it will not show the available json array fields in the Form Schema to bind to.

![Screenshot 2024-01-20 at 1 27 07 AM](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/0fbf4d72-b9a7-4f3b-b432-cc2978a25aa3/026d2b7b-31a8-4bfb-bf16-a60cc7ab1f98?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8wZmJmNGQ3Mi1iOWE3LTRmM2ItYjQzMi1jYzI5NzhhMjVhYTMvMDI2ZDJiN2ItMzFhOC00YmZiLWJmMTYtYTYwY2M3YWIxZjk4IiwiaWF0IjoxNzA1OTI5NTkxLCJleHAiOjMzMjc2NDg5NTkxfQ.U9Qy7s6EInOoFgF8KVzijg9c_ktuTDm-ZUQQzHA5U6c)

**Comment by andz-bb** [comment]
hey @poirazis - jsonarray is not valid as a field type in Budibase. It's used in repeaters to display JSON array data
