### ISSUE TITLE
Export with variable charset 

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#12852]
Have this issue been fixed?

I've tried every conversion using vscode and iconv...no luck to get the exported data to the charset that BB is using to display on web. Please help with any ideas

BB displays 
meta charset="utf8"

BB export  is not 1252 or true UTF-8

[datasource_plus_a20094ed6b4b4b8c9b0ad54bf1fb81eb__CustomerBill.csv](https://github.com/Budibase/budibase/files/14034210/datasource_plus_a20094ed6b4b4b8c9b0ad54bf1fb81eb__CustomerBill.csv)

MySQL export is correct  
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

[CustomerBill.csv](https://github.com/Budibase/budibase/files/14034243/CustomerBill.csv)

**Comment by ConorWebb96** [comment]
Closing as duplicate of #12853
