### ISSUE TITLE
Impossible to save basic auth for rest api

### ISSUE THREAD

**Issue by zzdpavo** [Budibase/budibase#12878]
**Hosting**
- Cloud
  - Tenant ID: bitbang

**Describe the bug**
As soon as i save a basic auth for a rest api, it disappears as soon a click on any availble link. 

**To Reproduce**
1. Create a rest api datasource
2. Go on authentication and click add authentication
3. Select Basic Auth and create your authentication then save it
4. Click on variables tab and then again on authentication
5. The authentication tab is empty

**Expected behavior**

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

**Comment by andz-bb** [comment]
@zzdpavo just to double check, does it still not save when you click the save button after the modal closes?

<img width="801" alt="image" src="https://github.com/Budibase/budibase/assets/110921612/ffa76138-6300-4ead-89b2-efd3679592e6">

I think ideally it should save on close but currently there's an extra step.

**Comment by zzdpavo** [comment]
Oh my god! i completely missed that button....

Thanks for checking
