### ISSUE TITLE
Unable to create two columns with the same name

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#1289]
**Describe the bug**
It's unclear why nothing happens when you try to create a column with the same name as an already created column. The save button is enabled, the request is sent to the database, but nothing is done with it. 

**To Reproduce**
1. Go to the data tab
2. Click on the users table
3. Click on the Create new Column button
4. Name the new column Status
5. Notice the save button is still enabled
6. Click the Save button
7. The dialog closes but no new column has been created

**Expected behavior**
The user should be notified that two columns with the same name are not allowed. So either the save button should be disabled once the name of an existing column has been entered, or after saving the data table, a notification should be shown that the column could not be created because the name is not unique.

**Desktop (please complete the following information):**
 - OS: every
 - Browser: every
 - Version: latest

**Comment by shogunpurple** [comment]
Thanks for the detailed bug report @mslourens! I've just fixed this and pushed it. It will be resolved in the next release.

**Comment by mslourens** [comment]
Wow, you are really quick! I haven't seen a bug being fixed within 5 minutes after reporting it.
