### ISSUE TITLE
Brand New User - Trying to figure out how to get all row values into a Field Group

### ISSUE THREAD

**Issue by mcancell** [Budibase/budibase#12895]
### Discussed in https://github.com/Budibase/budibase/discussions/12887

<div type='discussions-op-text'>

<sup>Originally posted by **mcancell** January 28, 2024</sup>
Hi,

New user here. I created a Data Provider, added a Options Picker, Added a Table, and finally added a Field Group. When I choose a value from the Picker, It does filter the table correctly and also DOES retrieve the value of the picked value into the corresponding field in the Field Group (e.g., Rate Name).  However, all of the other fields in the Group **never** get retrieved. 
The image below illustrated my problem. 
Why are all the other values NOT getting retrieved into the other Fields in the Group?
![Capture](https://github.com/Budibase/budibase/assets/25249301/42fee74f-a6f2-47c3-83c0-6c37c52d30d0)
 </div>

**Comment by mike12345567** [comment]
Hi @mcancell, issues is for bug reports and feature requests - discussions is the best place to look for help.

**Comment by mcancell** [comment]
Ok. I had created a discussion but no one addressed my question. I think I'm about to give up on budibase and now try another solution. Thanks.
