### ISSUE TITLE
MySQL Table names with special characters: There was a problem loading your grid

### ISSUE THREAD

**Issue by lvdon02** [Budibase/budibase#12945]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Cloud hosting
  - Budibase Version: 2.7.1
  - App Version: MySQL Community Edition version 8.3.0
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
I am trying to connect my locally hosted MySQL server to Budibase hosted in the cloud. Whenever I do so, it loads the tables and the column names correctly. However, whenever I try and enter one of the tables through the "data" tab or utilize them in the "Design" tab, it displays the following message: "There was a problem loading your grid. Table updated externally, please re-frech - The specified database does not exist. Please verify that the database name is correct". 

I do not have any issues connecting to this database over the web with something like MySQL Workbench. These tables are not being updated externally; they are copies of another database and no edits are ever made. Nothing ever changes. It says that it's connected successfully. 

**To Reproduce**
1. Go to the data tab > Sources
2. Click on MySQL and enter the credentials, click Connect
3. Select all of the tables, click Fetch Tables > Tables Fetched Successfully

**Expected behavior**
I expect to be able to see the tables connected normally. 

**Screenshots**
See attached screenshots. 
![Screenshot 2024-01-21 145845](https://github.com/Budibase/budibase/assets/158583218/3be1b695-fce9-4900-892c-15d602a51bd5)
![Screenshot 2024-01-26 145728](https://github.com/Budibase/budibase/assets/158583218/233dfdc5-874e-4025-bc4b-b307d361a00c)
![Screenshot 2024-01-26 143641](https://github.com/Budibase/budibase/assets/158583218/9eaafc61-21b6-4176-b106-342cb661def9)

**Additional context**
> We should add some validation upon table fetch to prevent invalid tables from being fetched, or we should allow for tables with special characters
> \- Mel

**Comment by melohagan** [comment]
Hey @lvdon02 

Have you tried the following:

1. delete the MySQL datasource
2. re-add and connect
3. fetch tables

**Comment by lvdon02** [comment]
> Hey @lvdon02
> 
> Have you tried the following:
> 
> 1. delete the MySQL datasource
> 2. re-add and connect
> 3. fetch tables

Yes, I have tried that multiple times. I have also tried different logins with the same permissions as well.

**Comment by lvdon02** [comment]
> I wonder could it be your table names. See the way they are `dbo.<name>`. Could you try as a test creating copies of your tables and naming them without the **dbo.** prefix, e.g. just `acceleratedcaseslog` etc

I did just that and now everything works, thank you!

**Comment by melohagan** [comment]
Great - I'll update the title of the issue. It would be nice if we added some validation to catch this

**Comment by lvdon02** [comment]
> Great - I'll update the title of the issue. It would be nice if we added some validation to catch this

Any chance that you know how to change the query timeout length in Budibase when hosted on the cloud? Every forum post that I've read regarding that has had to do with Budibase when self-hosted.

**Comment by melohagan** [comment]
> > Great - I'll update the title of the issue. It would be nice if we added some validation to catch this
> 
> Any chance that you know how to change the query timeout length in Budibase when hosted on the cloud? Every forum post that I've read regarding that has had to do with Budibase when self-hosted.

Hey @lvdon02 changing the query timeout is only available to self-hosted users via environment variables.

**Comment by ConorWebb96** [comment]
Closing as this seems to be resolved.
