### ISSUE TITLE
handleBars table clicked row binding doesn't allow you to select fields that have spaces between the words

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#12942]
**Checklist**

- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.17.2
  * App Version: 2.17.2

**Describe the bug**
When trying to pass only certain values from the clicked row binding from a table, the user is met with an error when using handleBars. This error only occurs with column names that have spaces in them, you are able to select single word columns. `Current Handlebars syntax is invalid, please check the guide [here](https://handlebarsjs.com/guide/) for more details.`

**To Reproduce**

1. Create a new app
2. Select the test data provided by Budibase
3. Create a new screen
4. Add a table block component
5. Click on this component
6. On the right hand side of the screen scroll down the `On click row` setting
7. Click the `no actions set` button add an action to update state and pass in the clicked row binding
8. Try and drill into this binding by free typing a column name you know exists and has a space
9. See error

**Expected behavior**
If the fields exist then you should be allowed to save the binding instead of switching to JS to do the exact same thing.

**Screenshots**

![Screenshot 2024-02-02 at 12 31 55](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/a93b5268-e640-4561-b635-ef0dfbeed47b/1e7f90d4-b65d-487b-8357-6484cdac32ce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hOTNiNTI2OC1lNjQwLTQ1NjEtYjYzNS1lZjBkZmJlZWQ0N2IvMWU3ZjkwZDQtYjY1ZC00ODdiLTgzNTctNjQ4NGNkYWMzMmNlIiwiaWF0IjoxNzA3MjMwNjcyLCJleHAiOjMzMjc3NzkwNjcyfQ.RMOjK4uGmr4fqvWZ2pgleSbVcxwFHaVxyVmS6A5yQ1c "=718x")

![Screenshot 2024-02-02 at 12 32 32](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b6fa77a4-3792-4171-a981-ddb561ca2f4b/557a458f-5903-4aec-8a5e-56bd795a316c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9iNmZhNzdhNC0zNzkyLTQxNzEtYTk4MS1kZGI1NjFjYTJmNGIvNTU3YTQ1OGYtNTkwMy00YWVjLThhNWUtNTZiZDc5NWEzMTZjIiwiaWF0IjoxNzA3MjMwNjcyLCJleHAiOjMzMjc3NzkwNjcyfQ.-XlNppYhm-TUqtrwSrAg3igcfUVHTB1XWkfj0VM4N7E "=895x")

**Comment by ConorWebb96** [comment]
You can get around this by pasting something like this into the an unopened input field to get around the logic `{{ Clicked row["First Name"] }}`.

However, if you go back to opening the drawer it will throw up that its invalid handlebars.
<img width="882" alt="Screenshot 2024-02-02 at 12 41 33" src="https://github.com/Budibase/budibase/assets/126772285/d601ccfc-899e-419e-8981-0d257bdc72f8">
<img width="880" alt="Screenshot 2024-02-02 at 12 41 39" src="https://github.com/Budibase/budibase/assets/126772285/43f534f4-d8b0-48f4-8a17-03b7558101ad">

**Comment by ConorWebb96** [comment]
Ignore the above it doesn't display anything whenever you paste it in to try and override it.

`row.["First Name"]` - displays nothing when tried
`row["First Name"]` - displays the entire row not the specific column within.

**Comment by aptkingston** [comment]
https://github.com/Budibase/budibase/pull/13298 for the live eval change.
