### ISSUE TITLE
Embedded TABLE Buttons all update display value to the same

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#12957]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
raventech.budibase.app -->

**Describe the bug**
I Add an button to a TABLE.
The button is labeled via JS, pulling the value from one on the columns,  (STATUS)
The  button is bind to an action .SAVE ROW  (UPDATE STATUS)

![2024-02-06-01-21-33](https://github.com/Budibase/budibase/assets/156072718/797a8b0d-0c93-4f99-b2f9-e73dabe3a5fe)

After the save row is complete.  ALL the buttons are relabeled to recent field value update.

I added a REFRESH Data Provider action, that did not help.

https://github.com/Budibase/budibase/assets/156072718/2643ce9e-d423-4cb5-95cc-1e4d0484fc92

**Comment by kasgithub8** [comment]
Hey @raventechnologiesinc, I opened a similar issue yesterday. It seems like we have the same problem: https://github.com/Budibase/budibase/issues/12956. Reverting the app should fix it for now.

**Comment by ConorWebb96** [comment]
Closing this in favour of #12956, as its a much better described issue.
