### ISSUE TITLE
Buttons in table reference wrong row

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#12956]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.17.5
  - App Version: 2.17.1 and 2.17.5

**Describe the bug**
I have multiple data providers with a table in each provider that shows different rows based on their status.
The data shown inside the table is correct but when I add a button component and use the syntax from before e.g. `{{ <TableComponent>.<Table>.<Column> }}` it references the last row in the data provider. This weirdly happens when I sort the table or switch the data provider page. The first load seems to work as excepted.

**To Reproduce**
1. Update Budibase and App to 2.17.1 or higher
2. Add Table (Data)
3. Add Data Provider
4. Add Table Component
5. Add Button inside the table
6. Reference the ID
7. Sort/refresh table OR switch data provider page 

**Expected behavior**
Reference ID of table row.

**Screenshots**
Screenshot 1: Correct behavior, freshly loaded page and provider
<img width="115" alt="BBIssue1" src="https://github.com/Budibase/budibase/assets/95284278/53ba2328-bc3b-43c0-ba36-389a95676d10">
Screenshot 2: Updated table (Sorted/refreshed table OR switched the data provider page)
![BBIssue2](https://github.com/Budibase/budibase/assets/95284278/1bd8f202-2d3f-480f-bbb8-bd380448eb06)
Screenshot 3: Bindings that worked before updates
![BBIssue3](https://github.com/Budibase/budibase/assets/95284278/4a0e4aa0-710c-47d8-a0ad-473879c40006)
  
**App Export**
Not possible because of personal information.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] (doesn't matter)
 - Browser [e.g. chrome, safari] (doesn't matter)
 - Version [e.g. 22] (doesn't matter)

**Additional context**
I've reverted the app for now. Bindings still work on 2.14.7.

**Comment by ConorWebb96** [comment]
Attaching an app export of this replicated [here](https://github.com/Budibase/budibase/files/14176779/filtering-issue-export-1707208200118.tar.gz).

1. Instructions go to the employees screen. 
2. Filter either table by `l` lower case `L` 
3. Click any of the buttons within the tables. 
4. See the error

**Comment by ConorWebb96** [comment]
Hey all, 

I've confirmed that this has been fixed with the latest release 2.17.6. The pr that fixed this can be found [here](https://github.com/Budibase/budibase/pull/12962).
