### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ianbourne** [Budibase/budibase#12966]
Currently unable to login. I login normally via google. Was working fine this morning. Now I just keep getting kicked back to the login screen.

**Comment by ianbourne** [comment]
Unable to view message from your bot

**Comment by andz-bb** [comment]
hey @ianbourne, is it still happening for you now? I was unable to replicate on my cloud instance

**Comment by ianbourne** [comment]
Yes its still happening. I see it go to the url for my instance and then goes back to the login screen.

**Comment by ianbourne** [comment]
Went to login this morning and all is resumed fine. I also previously had 3 errors appear when I logged in and those have now stopped.

**Comment by ianbourne** [comment]
Normal service resumed this morning. Thank you.
