### ISSUE TITLE
Parameter values containing comma are corrupted in API Datasource

### ISSUE THREAD

**Issue by mp-strachan** [Budibase/budibase#13038]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker Compose
  - Budibase Version: 2.17.3
  - App Version: 2.17.3

**Describe the bug**
When using a REST API source, if you add a comma separated list in a parameter, returning to the query corrupts the parameter data (`%2C` -> `%252C`)

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a REST API Data source
2. Go to the `Params` tab
3. Add a key (eg: "fields")
4. Add a CSV value (eg: "firstname, lastname")
5. Send & Save the query (this works fine with a correct endpoint. The path has correctly escaped commas (`%2C`))
7. Navigate away and return to the query
8. Go to `Params` tab -> values are no longer valid CSV (value's box and path now show `%252C`)
 *  Running the query again at this point will causes remote server to throw error as CSV is no longer valid (comma's have been replaced with `%252C`)

**Expected behaviour**
Returning to the query should preserve the correct value data

**Screenshots**
Before: 
![image](https://github.com/Budibase/budibase/assets/26296076/f0c23644-e778-4918-b47e-89fdcb274aa0)

After:
![image](https://github.com/Budibase/budibase/assets/26296076/90505910-767d-421f-b287-cb81928e2204)

**Additional context**
Current work around is to copy all data from the VALUE text box into a text editor, and find and replace `%252C` with `,`

**Comment by melohagan** [comment]
Fixed in **2.20.12**
