### ISSUE TITLE
2000 ROWS LIMT REACHED  BUT NOT BD Internal database used

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#13087]
**Checklist**

* \[ X\] I have searched budibase discussions and github issues to check if my issue already exists
* Cloud
  raventech.budibase.app -->

**Describe the bug**
We have no BD database in used
But now all our apps are locked due to 2000 ROWS LIIMT ERROR
Account is completely gone can not login

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/3f453a4b-6144-4c2b-9f73-be8409f16c4c/a1ece814-b0db-440b-a356-27a9d7385435?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8zZjQ1M2E0Yi02MTQ0LTRjMmItOWY3My1iZTg0MDlmMTZjNGMvYTFlY2U4MTQtYjBkYi00NDBiLWEzNTYtMjdhOWQ3Mzg1NDM1IiwiaWF0IjoxNzA5MDMwNDMwLCJleHAiOjMzMjc5NTkwNDMwfQ.f_Rk-tJUzr64YvvVVotvPE7g2vFZXCaLwB5fNR4OFPo)

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/a198c74d-086a-4bff-8f7c-5782b3d11a57/ecb97be1-d681-4749-adeb-2bb556bd299e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hMTk4Yzc0ZC0wODZhLTRiZmYtOGY3Yy01NzgyYjNkMTFhNTcvZWNiOTdiZTEtZDY4MS00NzQ5LWFkZWItMmJiNTU2YmQyOTllIiwiaWF0IjoxNzA5MDMwNDMwLCJleHAiOjMzMjc5NTkwNDMwfQ.8eR7xC2dnhxwBut9P2749TmK4nYr_zZudfMa6WwVlQw)

**Comment by ConorWebb96** [comment]
Hey @raventechnologiesinc,

External databases are also included in the row count. If you delete a row you can see this for yourself. There isn't any code that will "Delete an account" when the limits are hit.

When you say you couldn't use it, did you try removing some rows? I can see that there is no account related to this tenant `raventech`. 

- Any additional information you can provide would be great.
- Did you perhaps delete it when you hit this limit?

I'm going to run a test on a cloud account and see if i can recreate this.

**Comment by ConorWebb96** [comment]
Hey @raventechnologiesinc,

Couldn't replicate, all it ended up doing was tell me I was over the limit and needed to reduce rows to add more.
<img width="661" alt="Screenshot 2024-02-27 at 09 31 09" src="https://github.com/Budibase/budibase/assets/126772285/d59fe415-9b60-4525-9208-948141f1aaa1">

**Comment by raventechnologiesinc** [comment]
> There isn't any code that will "Delete an account" when the limits are hit.

Our raventech. account was locked out.
Can't login in.
Able to change password, but still can not login.
If you look at our app export we have no INTERNAL DB implemented.

We created a new BB account and import same app.
Again FREE ROWS and AUTOMATIONS are ticking up
while there is no DB or automation in place.

We need the raventech account deleted or reauthorized, so we
can add the same email userid to our app.

THERE IS NOT INTERNAL DB , to deleted any rows from!

**Comment by raventechnologiesinc** [comment]
You say there is no TENANT : raventech?

https://raventech.budibase.app/app/ship-to-vietnam#/login

their app is still published and active.
we just can't login in, because the account is unauthorised.
but it does recognize and allow us to change password.

**Comment by raventechnologiesinc** [comment]
> **Checklist**
> 
> * [ X] I have searched budibase discussions and github issues to check if my issue already exists
> * Cloud
>   raventech.budibase.app -->
> 
> **Describe the bug** We have no BD database in used But now all our apps are locked due to 2000 ROWS LIIMT ERROR Account is completely gone can not login
> 
> ![image](https://camo.githubusercontent.com/b2e1313b094f35b5156553c55ab5f7730c9613d97f41f9ad2aa519af54596975/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f37656366613239372d636337372d346664662d393131372d6661356166646238663930382f33663435336134622d363134342d346332622d396637332d6265383430396631366334632f61316563653831342d623064622d343430622d613335362d3237613964373338353433353f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a646c59325a684d6a6b334c574e6a4e7a63744e475a6b5a6930354d5445334c575a684e57466d5a4749345a6a6b774f43387a5a6a51314d324530596930324d5451304c54526a4d6d49744f5759334d7931695a5467304d446c6d4d545a6a4e474d765954466c593255344d545174596a426b596930304e4442694c57457a4e5459744d6a64684f5751334d7a67314e444d314969776961574630496a6f784e7a41354d444d774e444d774c434a6c654841694f6a4d7a4d6a63354e546b774e444d7766512e665f526b2d744a557a72363459767656566f7476504537673276465a5843614c774235664e52344f46506f)
> 
> ![image](https://camo.githubusercontent.com/3785deebb6d85788bfaadde49695f2dac1e1cecfeff451724754d9974b89095e/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f37656366613239372d636337372d346664662d393131372d6661356166646238663930382f61313938633734642d303836612d346266662d386637632d3537383262336431316135372f65636239376265312d643638312d343734392d616465622d3262623535366264323939653f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a646c59325a684d6a6b334c574e6a4e7a63744e475a6b5a6930354d5445334c575a684e57466d5a4749345a6a6b774f4339684d546b34597a63305a4330774f445a684c5452695a6d59744f475933597930314e7a6779596a4e6b4d5446684e5463765a574e694f5464695a5445745a4459344d5330304e7a51354c57466b5a5749744d6d4a694e545532596d51794f546c6c4969776961574630496a6f784e7a41354d444d774e444d774c434a6c654841694f6a4d7a4d6a63354e546b774e444d7766512e38655237784332646e687877427574395032373439546d4b346e59725f7a5a7564664d61365777566c5177)

Could you please locate the TABLE its writing thee 2000 rows to.  And you are welcome to deleted them all.  Our code does not ue INTERNAL DATABASE.

"External databases are also included in the row count. If you delete a row you can see this for yourself. There isn't any code that will "Delete an account" when the limits are hit."


We have over 60K rows in our external DB, which exceeds the 2000 row limits..Our app is still running. We add over 500 rows a day.  the 2000 row limit increase only by a few.

**Comment by ConorWebb96** [comment]
@raventechnologiesinc 

> **External databases are also included in the row count**

So you will still hit the 2k limit when using an external databases within Budibase.

Thank you for this linking the published app.

We have brought your raventech account back up can you try logging into it now?

**Comment by raventechnologiesinc** [comment]
> @raventechnologiesinc
> 
> > **External databases are also included in the row count**
> 
> So you will still hit the 2k limit when using an external databases within Budibase.
> 
> Thank you for this linking the published app.
> 
> We have brought your raventech account back up can you try logging into it now?

At what RATIO and what FORMULA is being used to deduct from the 2000 row limits?
What TABLE or ACTION does BB count as a row towards this 2000 limit.?

Does it count ever UPDATE, CREATE  row action on all external tables?

Your advertising and docs do not explicitly state this.
It only state 200O rows  of Internal Database usage.

Still Don't undertand.  Our app locks up when this 2000 limit is hit.  Even though all READ.WRITES are to extrenal DB.  Is this correct?

**Comment by ConorWebb96** [comment]
Hey @raventechnologiesinc,

I've reached out to the product team and it seems you are right. External databases SHOULD NOT be counted when using an external database.

I'll go through an clarify your bullet points in order.

1. It looks like there is an issue with how this is being handled currently, external database rows are being used in the row count.
2. The monthly reset only resets automations that have been run. (THIS ISN'T related to how many automations you have)
3. Point one answers this.
4. Point one also answers this.
5. Currently if you delete a row in your EXTERNAL MySQL table you will see the 2000 quota decrease.
6. I believe any rows that are added through Budibase count towards this limit incrementing.

I'll create a Github issue and link it after I do some more investigation. I'll close this issue as a result as the issue I make will provide better details for the engineers to fix.

Thank you for pointing this out.

**Comment by raventechnologiesinc** [comment]
Understood.

AS of now..
Whenever  a CREATE-ROW action is is called using BB it tally up the 2000 LIMIT QUOTA.
Whenever  a DELETE-ROW action is is called using BB it tally up the 2000 LIMIT QUOTA.

So if I create 2000 rows offsite
Then use BB to DELETE these row...hopethetically...my quota will decrease?

Will test.

**Comment by raventechnologiesinc** [comment]
It is confirmed!

We can now extend the life of our FREE ACCOUNT.
I created a fee rows offsite then went into the DATA TAB and manually deleted  dummy row and observed the quota decresased by that amount accordingly.

This is a very good hack.


No need to fix.  We can have free account indefinitely.
I can write an automation to delete dummy rows for our logs periodically.

**Comment by ConorWebb96** [comment]
Closing this as i've created a better issue for the engineers to fix. https://github.com/Budibase/budibase/issues/13158
