### ISSUE TITLE
UI Glitch When Adjusting Action Order in Conditionally Linked Button Groups within Forms

### ISSUE THREAD

**Issue by Stropdasman** [Budibase/budibase#13124]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> digital ocean
  - Budibase Version: v2.20.8
  - App Version: <version> v2.20.8

**Describe the bug**
This is but an example of the bug.
When a button group is added, for instance, within a form, the buttons are linked to a specific form-step. If these buttons are configured in the conditions and actions are assigned, adjusting the order of these actions causes the UI to glitch.

**To Reproduce**
1. create an app
2. add a button group
3. add condition where you add button
4. add actions to this button
5. reorder the actions to see error

**Expected behavior**
Reordering of the actions

**Screenshots**
![Bug](https://github.com/Budibase/budibase/assets/147417929/5b834525-0d25-4e3b-9db5-b62db49c715f)
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.
[test app-export-1708677247472.tar.gz](https://github.com/Budibase/budibase/files/14383187/test.app-export-1708677247472.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Versie 121.0.6167.185

**Comment by Stropdasman** [comment]
This has not been solved yet, I think

**Comment by aptkingston** [comment]
Copying my image from linear:
![image](https://github.com/Budibase/budibase/assets/9075550/1a53fcec-4bb8-4784-9ce4-6fd512bd0a34)

I was unable to reproduce this.

**Comment by Stropdasman** [comment]
Thanks for the reply. Try adding actions to a button and after that reorder the actions. This should result in some unexpected behaviour.

**Comment by aptkingston** [comment]
I've tried that, but I still can't reproduce unfortunately. My buttons have actions configured as shown:
![image](https://github.com/Budibase/budibase/assets/9075550/bd9320d9-d74a-442a-a438-6ce157394101)
![image](https://github.com/Budibase/budibase/assets/9075550/c787948b-0324-4a4b-8a6a-3294d9fff0d4)

But I can still reorder the buttons as expected:

https://github.com/Budibase/budibase/assets/9075550/e12c6332-1026-4455-be83-edcbd548af82

**Comment by Stropdasman** [comment]
Ah i see what you mean. I'm sorry if I'm not was not clear.

I was talking about reordering the actions within the button

https://github.com/Budibase/budibase/assets/147417929/c9ac1fc0-6e11-4035-97c2-edd4c181174e

Here you can see the bug. For my other app it is even more broken then this.

**Comment by Stropdasman** [comment]
https://github.com/Budibase/budibase/assets/147417929/db7773dd-bdb9-43d0-ad91-091190907fae

**Comment by aptkingston** [comment]
Thanks for the video! That makes it much clearer :)

**Comment by Stropdasman** [comment]
Is there any update regading this problem? It would be so great to be able to reorder actions and not having to remove all the actions to reorder them.
