### ISSUE TITLE
GETTING LOGGED OUT EVERY 10 sec of inactivity.

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#13122]
**Checklist**
- [ X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

ship2vietnam.budibase.app 

**Describe the bug**
I have to re login every 10 seconds
Getting FAILED REQUEST error in builder.

I am the sole creator account.
No one else is using the login.

Refreshing the builder takes me back to login.

**Comment by raventechnologiesinc** [comment]
It is not happening anymore.

We noticed that this happens usually right after an UPDATE is issued.
and around 3AM UTC+7.  This has happened 3 times, During release of updates we noticed.

**Comment by ConorWebb96** [comment]
Going to close as theres no replication steps. Plus it doesn't seem to be happening anymore.
