### ISSUE TITLE
ROW usage increasing when there are no INTERNAL DB in used

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#13123]
**Checklist**
- [ X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

ship2vietnam.budibase.app -->

**Describe the bug**
Account usage displays

Rows
144 / 2000

This stat started increasing with a new virgin account setup.
Our app do not implent any calls to any INTERNAL DB.
This mean our app will crash again 
and our account will be deleted once it hits 2000
again.

This has happened before.

Upgraded to latest version.

**Comment by raventechnologiesinc** [comment]
We monitored and showed a ROW USAGE decrease after an automation run

Rows
143 / 2000



Are automations stats tied to internal BB DB?

**Comment by raventechnologiesinc** [comment]
I have no automation implement

Automation usage shows 4

![image](https://github.com/Budibase/budibase/assets/156072718/73b1e4ff-0224-4fbd-9082-e628b18d0bc8)

![image](https://github.com/Budibase/budibase/assets/156072718/a49cf8d4-c91d-4cfd-859d-1316f0638e65)

![image](https://github.com/Budibase/budibase/assets/156072718/3a3ebd85-eee3-4d78-83e4-b868e506e30b)

**Comment by ConorWebb96** [comment]
I've answered a few of your questions #13087.

As for your automation question, this isn't tied to how many automations you have. Its related to how many times you've used an automation. You only have 200 automations that can be triggered in a month.

Hopefully this makes sense.

**Comment by raventechnologiesinc** [comment]
> You only have 200 automations that can be triggered in a month.

We explicitly delete all AUTOMATIONS to be sure.
App is running fine.  Hopefully it doesn't tick up,  Logs will show if it does.

But the question still stands.  What BB db table is receiving ROWS updates?
Our code does not reference any, nor is there a BB table ever created.

**Comment by ConorWebb96** [comment]
Closed as I've answered this already.
