### ISSUE TITLE
<title> tags empty

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#13142]
**Checklist**
I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker
  * Budibase Version: 2.20.12
  * App Version: 2.20.12

**Describe the bug**
When the application is used the page title is showing on the browser tab as the page URL and it does not show the page title. On inspection in console the html tag is empty.

**To Reproduce**

1. Create and publish an application
2. View in a broswer
3. Note the tab title and view source in inspector

**Expected behavior**
Should show the page title

**Screenshots**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/162d2013-2c01-471f-86e7-79a2cd12a5cf/a4df9a2b-453c-4eb0-ae8c-19eea44fc7c5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8xNjJkMjAxMy0yYzAxLTQ3MWYtODZlNy03OWEyY2QxMmE1Y2YvYTRkZjlhMmItNDUzYy00ZWIwLWFlOGMtMTllZWE0NGZjN2M1IiwiaWF0IjoxNzA5MTMwNzQ0LCJleHAiOjMzMjc5NjkwNzQ0fQ.dym9oGbWPXCMr6QLAasLj1D0z2wTWAKkPimVVuYdY9k)

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/229e233f-fbfd-4b2f-8115-7a9355037f0c/510f3c19-3d6c-4b84-963f-83aa761f5bac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8yMjllMjMzZi1mYmZkLTRiMmYtODExNS03YTkzNTUwMzdmMGMvNTEwZjNjMTktM2Q2Yy00Yjg0LTk2M2YtODNhYTc2MWY1YmFjIiwiaWF0IjoxNzA5MTMwNzQ0LCJleHAiOjMzMjc5NjkwNzQ0fQ.KNZ_tr9-kiDwDl5NrKLoj5GHgykglq2oJLBZj4_oZUY)

**Comment by mike12345567** [comment]
Fixed in: https://github.com/Budibase/budibase/pull/13172
