### ISSUE TITLE
[ Builder ] - Svelte warning in properties of type : "icon"

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#13154]
propety type: "icon" shows svelte warning message

![Screenshot 2024-02-28 at 9 57 23 PM](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/af17e00a-c382-4e04-b5af-3aacf806460b/5c8f25e9-2bb6-4507-b833-0546fd805c9f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hZjE3ZTAwYS1jMzgyLTRlMDQtYjVhZi0zYWFjZjgwNjQ2MGIvNWM4ZjI1ZTktMmJiNi00NTA3LWI4MzMtMDU0NmZkODA1YzlmIiwiaWF0IjoxNzA5MjAxNzgyLCJleHAiOjMzMjc5NzYxNzgyfQ.ndz57dNs1jQ0ZTNHHlqfczMUKOrT6WsLfpC1kgsIcEM)

**Comment by ConorWebb96** [comment]
Hey @poirazis,

Does this error go away after adding an icon?

**Comment by poirazis** [comment]
Nope, still there after selecting an Icon

![Screenshot 2024-02-29 at 4 52 44 PM](https://github.com/Budibase/budibase/assets/80512170/84f00661-a014-43ea-81c2-c65f4145645b)

**Comment by ConorWebb96** [comment]
Hey @poirazis, 

The above PR will fixed the issue. Going to close as it was just a stray comment that i've removed.
