### ISSUE TITLE
[ Builder - Actions ] - Navigate To - Allow disabling the "Full Screen" and "Close" options when opening a modal and add "OnClose" Event

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#13150]
For cases when we dont want the end user to be able to open the modal in full screen or close it, to force an action inside the modal and essentially use it as a popup. The use as a popup functionality could be extended by allowing to set an Event to be executed when the modal is closed so further actions can be taken.

For example OnClose -> Refesh Data Provider

**Comment by andz-bb** [comment]
good thinking @poirazis - have marked this as a duplicate of #10399
