### ISSUE TITLE
External Database rows are being counted towards the usage restriction when created within Budibase.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13158]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.20.12
  - App Version: 2.20.12

**Describe the bug**
After importing a MySQL or Postgres database I noticed that no rows were being counted in my usage area on my account. However I've I began interacting with these tables and creating new rows, I noticed that the row count seen within the usage page began to increase. This shouldn't be the case as its an external database, the counted rows should only count internal table related rows.

**To Reproduce**
1. Create a new app
2. Setup an external database e.g. Postgres or MySQL
3. Import a table with a few rows (Check the usage area within Budibase see no additional rows were added)
4. Add some rows through the Budibase UI to this table
5. See the row usage count has increased

**Expected behavior**
External database rows should be ignored in the row limit count for free tier users.

**Screenshots**
<img width="620" alt="Screenshot 2024-02-29 at 11 02 53" src="https://github.com/Budibase/budibase/assets/126772285/e5ea7e66-3968-4529-ab4f-44873d917294">
<img width="1357" alt="Screenshot 2024-02-29 at 11 03 00" src="https://github.com/Budibase/budibase/assets/126772285/7fedbaa0-db09-4be3-b416-75d5d647662e">
<img width="1354" alt="Screenshot 2024-02-29 at 11 03 09" src="https://github.com/Budibase/budibase/assets/126772285/707e58b6-c7e5-420f-9977-2656a97b6eaf">
<img width="1264" alt="Screenshot 2024-02-29 at 11 03 48" src="https://github.com/Budibase/budibase/assets/126772285/11451bff-b237-445f-9b80-c042e8aff847">
  
**App Export**
Can be re-created with any simple external db, you just need to create rows within Budibase to see the limiting in action.

**Comment by raventechnologiesinc** [comment]
Is this scheduled for fix?
Its been a month

**Comment by ConorWebb96** [comment]
Hey @raventechnologiesinc,

This hasn't been fixed. There are other bugs that are being looked at currently. This isn't an app breaking bug, therefore it is likely to be a while before an engineer gets to look into it.
