### ISSUE TITLE
On Screen Load State Changes Don't Work with current Preview Skeleton

### ISSUE THREAD

**Issue by Stropdasman** [Budibase/budibase#13171]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method>  docker compose
  - Budibase Version: <version> 2.20.13
  - App Version: <version> 2.20.13

**Describe the bug**
On Screen load doesn't change states. This only happens when refreshing the application.

**To Reproduce**
1. Add screen
2. Click on on screen load
3. Add state and show notification where the text is state
4. When loading the page, no notification is shown

**Expected behavior**
States need to be set on screen load

**App Export**
[test-export-1709285647412.tar.gz](https://github.com/Budibase/budibase/files/14459174/test-export-1709285647412.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser EDGE and Chrome

**Additional context**
Current Preview Skeleton is really slow and often pauses

**Comment by melohagan** [comment]
Fixed in latest
