### ISSUE TITLE
Problem with the MySQL table if the table name starts with "Customer"

### ISSUE THREAD

**Issue by n05331** [Budibase/budibase#13178]
**Hosting**

- Self
- Budibase Version: 2.21.0

The problem started today when I upgraded to the latest version.
If there is a MySQL table whose table name starts with "Customer" it will not work.
I have an existing table named: "Customers" and after the upgrade it stopped working.
I see the following error:
There was a problem loading your grid
Unknown column 'as.id' in 'field list'
![image](https://github.com/Budibase/budibase/assets/102161797/dec1ffa0-4386-49cc-919f-33e08c9dde0a)

I tried to create a new table with the name: "Customer" and it works.
I tried to create a new table with the name: "CustomerVV" and the same problem.
There was a problem loading your grid
Unknown column 'aVV.id' in 'field list'
![image](https://github.com/Budibase/budibase/assets/102161797/541216b0-27c8-4454-800d-365f239fdd5d)

It seems that if the table name starts with "Customer" it is automatically changed to "a" and therefore the table does not work.

**Comment by mvhaen** [comment]
I'm experiencing a similar problem, however our app was not yet updated to the latest version when it started occurring. This is our schema, we don't have a `Customers` table though.

[STR_Translations-dump.sql.zip](https://github.com/Budibase/budibase/files/14482511/STR_Translations-dump.sql.zip)

**Comment by mike12345567** [comment]
Hi @mvhaen - just to confirm, are you self hosted and this issue still occurs for you before 2.21.0?

@n05331 is there anyway you could provide a schema demonstrating the issue you're experiencing? You can retrieve it using this: https://docs.budibase.com/docs/troubleshooting-sql

If you can retrieve a schema, you can send it privately to `support@budibase.com`

**Comment by mvhaen** [comment]
@mike12345567 

I'm still running into the issue. We use the cloud offering by the way, not a local install. 

![image](https://github.com/Budibase/budibase/assets/157020/0336ecef-051e-4947-b1f0-4f103720506d)

Is it possible the fix is not yet in production?

**Comment by mvhaen** [comment]
@mike12345567 

After updating the app, I'm still running into this issue. We are using the cloud offering, not a local install bu the way.

> The app is currently using version 2.21.1.

![image](https://github.com/Budibase/budibase/assets/157020/7980b51b-4294-407f-8624-1cd36d18152c)

Is it possible that the fix was not deployed in production yet?

**Comment by n05331** [comment]
I have now upgraded to the updated version: 2.21.2
And the problem disappeared.
Thank you!

**Comment by mvhaen** [comment]
I used the schema export, yes. And the DB is MSSQL (running on azure), so it makes sense you can't create a MySQL DB from it.

**Comment by mvhaen** [comment]
For the rest this setup is not new, it's been running like this for at least 6 months without changes. The issues started appearing for us yesterday.

**Comment by dfourmanfsquared** [comment]
Still seeing errors for MS SQL on azure with the latest update, the application has been running fine for the last 2-3 months
<img width="604" alt="image" src="https://github.com/Budibase/budibase/assets/107331834/2c7ea66c-a502-469c-9b9d-955185fa793b">

**Comment by mvhaen** [comment]
Just to give you some ideas about the setup. The app manages our translation lables s and the UI on top allows someone non-technical to add translations for multiple languages. 

These are the tables involved:

![image](https://github.com/Budibase/budibase/assets/157020/e8de47fc-86c6-4534-87b3-5c7c85b6213e)

there is one relationship:

![image](https://github.com/Budibase/budibase/assets/157020/cbb4e60d-eb6f-4130-8540-f4ea5fa894a6)

The issue occurs when we edit a translation and then try to save it. Loading the records, opening the details of 1, etc. work fine.

![Screenshot 2024-03-05 at 15 29 37](https://github.com/Budibase/budibase/assets/157020/e79046a0-5802-412c-8f89-6be162a6c0fd)

**Comment by dfourmanfsquared** [comment]
This is occuring with row deletions as well: 
<img width="369" alt="image" src="https://github.com/Budibase/budibase/assets/107331834/a75e3cc3-f4e0-45dc-9c74-c426b14649fa">
