### ISSUE TITLE
DELETE ROW via builder.app does not work after update  2.21.2.

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#13199]
**Checklist**
- [ X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

ship2vietnam.budibase.app -->

**Describe the bug**
Accessing DATA in builder app
I am able to Fetch tables.
So authentication and SQL privledges are valid

Create new rows - Works
But can not delete row.

Selecting ALL Delete  - no work
Selecting 1 record to delete - No work

![image](https://github.com/Budibase/budibase/assets/156072718/ad38c06c-572d-4d34-85ea-085d61415bbc)
  
Spins indefinitely

 - Version  2.21.2

**Comment by mike12345567** [comment]
Hi @raventechnologiesinc - can you check if this still occurs on the latest version?

**Comment by raventechnologiesinc** [comment]
YES.  I updated to the latest version.
CREATING and DELETE records to External databse increases/decrease the ROW USAGE COUNT

**Comment by mike12345567** [comment]
Closing issue as resolved.
