### ISSUE TITLE
Budibase Admin Panel - UI

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1321]
https://xd.adobe.com/view/195ab5d0-d034-4d54-9285-248198bb82f8-4c09/

**Comment by joebudi** [comment]
I updated the XD doc (link in description) with the up-to-date designs for the Admin panel. I've tested the design and UX with @aptkingston and it passed with 1 minor change which has been completed and the design updated.

I am more than happy to run through the design again for whoever is building the UI.

**Comment by shogunpurple** [comment]
Closing - broken down and covered by other tasks.
