### ISSUE TITLE
Weird ��� symbols in response

### ISSUE THREAD

**Issue by Acetyld** [Budibase/budibase#13213]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method:Docker
  - Budibase Version: Newest
  - App Version: Newest

**Describe the bug**

After 208 records, on the 
��`ʊTk  莯�!�¸���ɌTЁ��駪r�j����c�E��.\\�q�觊u�j�n9����J�3$Ё��75[Sl؅��:�`b��`6��gtk�N�u�Y���,1zV��Q=���B5��xni�"�S���lV�8���?���t~hh}� R�|E�ݐ�"#;�@.���h�����B�O���\\VU!�����?2!XF?�ٙ������iɟ�      �4?!Eq�h"�<$9�ɂ�T6tdLfTn�"��ql�Ԧ�=��7��f�v��E��=��|��/�Sk�p��W�5R:|�I��Jk��R�h�Q!4�mz��+uW��r�-̋�w�;\\v��e��cI��a�hY/��e�ʞ�;�O?������8����' . "\0" . 'y��a��+oX���s���I��C$\'a����mw�h�v�k��p�F1��a4en0B.Ö��1/9�����
                                              1��ߢ~��Wn͂�W��E�ڋ�ɍ���a�p���\'�B\\� ���R�`�[��\'L�ֽ�X4A�=��od��F4|����b�F5
                                                                                                                      <����8p�-Z����C/ȏP���:�^�mxg��O#���)�td�q�WV�Ӛ=>V�yJ���l�(A�����o�EN���;O�^L�u_�l��z�����/�[}�����[�@��Vگ����B���{���m5H����W
*A���m��2QT�ඁ�!�A�"�6$g�� Y�O�U��-X5��������b����h�     M$yrxR2���nK�W
�&�&3�B���|it�G��=����?"Q��H��!�ώD���|��%�Wt[���X�L�.�
                                                      ��H�BG{�0" . '' . "\0" . '��' . "\0" . '�cq�T
                                                                                                   ' . "\0" . '' . "\0" . ''

**To Reproduce**
[
    0 => 'http://198.19.249.3:10000/api/public/v1/tables/datasource_plus_d467cf6e3d7b4f1588cb725fc905199b__contacts/rows/search'
    1 => [
        'paginate' => true
        'query' => [
            'equal' => [
                '0:trengoId' => '70777580'
            ]
        ]
    ]
    2 => [
        'Accept' => 'application/json'
        'Content-Type' => 'application/json'
        'x-budibase-api-key' => 'asd-asdasd'
        'x-budibase-app-id' => 'asdasd'
    ]
]

**Expected behavior**
Not throw these weird signs

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

**Comment by mike12345567** [comment]
Hi @Acetyld - there is not enough information in this issue to recreate the problem. We will need to know a full recreation steps for us to be able to see this for ourselves.

If you can create a small dataset that recreates this problem to share with us, it looks like you're using an SQL table of some sort, so the schema + some data to understand how this occurs, plus an app export which exhibits this problem will be required to debug it fully.

Closing for now.

**Comment by Acetyld** [comment]
After much debugging, it was the 429, but.. not the one from the DISABLE_RATE_LIMITING or API_REQ_LIMIT_PER_SEC env

But.. PROXY_RATE_LIMIT_API_PER_SECOND and PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND.

https://docs.budibase.com/docs/hosting-settings

The link here to .env
![image](https://github.com/Budibase/budibase/assets/55088242/f3de9299-201d-4521-9817-f829c5be4bbe)
Leads to
![image](https://github.com/Budibase/budibase/assets/55088242/f372882c-a9bd-43c3-92ed-c036523879b0)


Maybe having better documentation about env would be lovely (self hosting)

**Comment by mike12345567** [comment]
> API_REQ_LIMIT_PER_SEC

Hi @Acetyld - glad you got it sorted, I've updated the documentation page with information about those environment variables, and updated the dead link - thank you for pointing it out.
