### ISSUE TITLE
Self-hosting installation documentation gives 2 totally different YAML files to use.

### ISSUE THREAD

**Issue by darlingm** [Budibase/budibase#13227]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: Haven't gotten that far yet.

**Describe the bug**
I originally tried installing @budibase/cli through npm as seen at https://docs.budibase.com/docs/budibase-cli-setup.  That was giving errors connecting to redis.  I'm not sure if that's required to be installed, since it isn't mentioned on that page.  I ran across #10333 which is unrelated, but the recommendation at least for that user was to just manage the docker-compose.yaml themselves.  I'm fine going that route too.  I'd prefer not to pollute my actual installation with things including redis if they wouldn't be needed (at least outside of docker) using a different installation method.

So, I viewed:
* https://docs.budibase.com/docs/docker
* * For method 2, docker compose, it gives a sample short YAML file right on the documentation page that has a single entry under services, budibase.
* https://docs.budibase.com/docs/docker-compose
* * This page links to a long https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml which has 7 entries under services.

Which docker-compose.YAML file should be used, between the 2 totally different ones the documentation gives?

Is this just a question of having separate docker containers for things like CouchDB, Minio, Nginx, Budibase Worker & Server, versus having them all in the same container?  If so, what would you recommend for someone who is going to have them all hosted on the same device?

**To Reproduce**
N/A

**Expected behavior**
The 2 areas in the documentation explaining how to install self-hosting through docker compose shouldn't give totally conflicting advice.

**Comment by andz-bb** [comment]
hey @darlingm 

You can install Budibase either way - we have the single docker image with the short yaml file which has all of the dependencies bundled together into one image. It's probably the simplest way to get up and running if you don't specifically need fine control over specific services like Redis and Nginx. It just runs as a single container in your Docker.

The other approach is to use docker-compose and pull the images separately, running them each in their own container. If you're just looking for a simple way to spin up a Budibase instance, either way is completely fine and easy enough to manage. The docker-compose method might be more suitable or intuitive if you want to have a more custom configuration but ultimately they will both do the same thing.

If there's any way we could make this clearer in the docs let me know and I'll make some changes.
