### ISSUE TITLE
Admin Panel - SMTP Setup

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1322]
Allow user to configure SMTP credentials for their instance from the admin panel

Allow admins to invite users to the platform using their email address 

- Set up SMTP server with docker
- One click HTTPS with certbot?

**Comment by mike12345567** [comment]
Information for SMTP setup:
Allow people to create templates in the UI
Templates are saved in global db
When you send an email, it takes your data and renders it into the template
Mail is sent with nodemailer (or similar) using your SMTP credentials
Self hosted users will be directed to set up their own SMTP server through sendgrid or similar. Document this

**Comment by mike12345567** [comment]
At this point the templating system and main backend components of the SMTP have been created - there is still however some further work that is required:
1. The implementation and link up of the forgotten password and invitation flows
2. The linkage to the admin panel and creation of configuration
