### ISSUE TITLE
Errors when using button action 'navigate to' in a public form

### ISSUE THREAD

**Issue by GrietVanbillemont** [Budibase/budibase#13236]
### Discussed in https://github.com/Budibase/budibase/discussions/13206

<div type='discussions-op-text'>

<sup>Originally posted by **GrietVanbillemont** March  6, 2024</sup>
We have an issue with a button which gives an error 'session not authenticated' or 'missing'

First issue - session not authenticated
At the end of our new form, there is a button to send the completed information. There are four actions associated with this button: validate form / save row / trigger automation / navigate to. 

The first three actions succeed, but the fourth action is not performed and then the message 'session not authenticated' appears. The 'navigate to' action should take the user to a screen with a text where the registration (filling out the form) is confirmed. The page itself has 'access' 'public', so access should work for a public user. The 'navigate' action button has as destination 'screen' with the path of the specifiek screen (/bevestiging).

We have several similar apps with a similar button with four actions, where public users do get acces to the page as a fourth button action. </div>

Second issue - missing
At the end of our form, there is a button to send the completed information. There are four actions associated with this button: validate form / save row / trigger automation / navigate to. 

Last week, all four actions were working fine. Since this week, the fourth action is no longer activated (third action automations work) but there is no navigation to a next screen. Now the error 'missing' is appearing. After deleting the fourth action, the error 'missing' still appears, automations still works.

**Comment by ConorWebb96** [comment]
I'm going to close this for now as I believe this is a stray permission being set on the dataset being used in the navigated to page and not an actual bug. I've responded to the discussion. If it does indeed turn out to be a bug I'll reopen this issue.
