### ISSUE TITLE
Email Response issue with internal CouchDB

### ISSUE THREAD

**Issue by thering1975TG** [Budibase/budibase#13249]
**Checklist**
- YES -  I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self Hosted
  - Docker seperate containers, Debian 12, Arm
  - Budibase Version: 2.21.5 present in 2.19
  - App Version: <version> 2.21.5

**Describe the bug**
There is an issue with responses being included in the HTML email on Automation, Not all responses appear to be included. This may relate to but not fully sure When a column is added or moved in the DB but that could be a red herring

**To Reproduce**
1. Create a Multi Step form
2. Add various options including Options FIeld (both Radio and 
3. *Red Herring - Move a column left or right or add a column and move
4. Create HTML Email and add all the relvant - {{ trigger.row.WhichDepot }} 

**Expected behavior**
All responses to be included in email

**Screenshots**
**Database Column Affected - WhichDepot**

<img width="251" alt="database" src="https://github.com/Budibase/budibase/assets/87522339/19cef9c1-e993-4653-ab57-5d6269f75f61">

**Form Element correctly titled**

<img width="227" alt="whichform" src="https://github.com/Budibase/budibase/assets/87522339/f5555d7d-abf6-4e1d-882f-a9dfa1091b0b">

Html Element which includes this answer

`												<table class="text_block block-3" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
														<tr>
															<td class="pad">
																<div style="font-family: sans-serif">
																	<div class style="font-size: 12px; font-family: Verdana, Geneva, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
																		<p style="margin: 0; font-size: 16px; text-align: center; mso-line-height-alt: 19.2px;"><em><strong>{{ trigger.row.WhichDepot }}</strong></em></p>`

Originally WhichDepot was spelt Which Depot in the database so had additional square brackets this made no difference at all the issue affects both formats

**Email**
  
<img width="537" alt="email" src="https://github.com/Budibase/budibase/assets/87522339/89d90ed6-4474-4a59-b49b-94f25ecb74c1">

As you can see the answer is blank in the which depot row of the email, please note the row above is set up in exactly the same way as an options field and column yet that displays

It should be noted this happens in both a form submission and in the Automation Test, in the form submission the response is saved in the database correctly but not added to the email

**App Export**
Avaliable on Request

**Additional context**

**RED HERRING**
I mentioned a possible cause but that could be a red herring however the reason for that is i have found other responses are also missing with regards to Street Names. Some of these columns also could have been moved left or right in the beginning whilst organising the data  i am not 100% sure, but in a test automation email i assigned a road to each crew (there are circa 20 crews and approx 6 roads were missing.

**Comment by thering1975TG** [comment]
As a quick test i deleted this column (which was the 4th column of circa 30 in the DB)

And re-created the column with the same name and options to the end (i.e last) column of the DB

I did a form submission from the front end and the answer is shown.

So not sure whether it has been caused from the update process  (both docker and app) or my suspicion when moving the columns left or right some how causes an issue. so i guess i will have to do the same for each of the missing crew columns now

**Comment by andz-bb** [comment]
hey @thering1975TG - could you send us an app export please? If you'd rather not attach it here, you can send it to support@budibase.com and we'll have a look. Thanks!

**Comment by thering1975TG** [comment]
Hi

Apologies for delay, i will send accross the current app, and will see if i have a version of the app exported at the time i posted this and will send to the email address
