### ISSUE TITLE
Update Onboarding Flow For Single Stack 

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1325]
- Fix the forget password
- Look at OAuth providers (should be available for cognito)

https://xd.adobe.com/view/191f22da-37ce-4cac-b64f-39774d41b078-4c4c/screen/9d5c892a-9ae4-4f79-b9e1-21bf62b55dbf?fullscreen

**Comment by joebudi** [comment]
Updated designs:
https://xd.adobe.com/view/195ab5d0-d034-4d54-9285-248198bb82f8-4c09/

**Comment by joebudi** [comment]
For this release, the onboarding flow will consist of the user:
- visits website
- clicks get started, and is directed to the docs
- the user follows the docs 
_- the user sets up docker_
- the user downloads budibase cli
- use enters commands in budibase cli
- user runs budibase for the first time
- user enters admin credentials


@shogunpurple @mike12345567 are you happy with this?

**Comment by mike12345567** [comment]
> For this release, the onboarding flow will consist of the user:
> 
> * visits website
> * clicks get started, and is directed to the docs
> * the user follows the docs
>   _- the user sets up docker_
> * the user downloads budibase cli
> * use enters commands in budibase cli
> * user runs budibase for the first time
> * user enters admin credentials
> 
> @shogunpurple @mike12345567 are you happy with this?

Makes sense to me! We could also have the CLI check if docker and docker-compose are setup, if they are not it could provide details about their installation for your platform.

**Comment by shogunpurple** [comment]
@joebudi +1 looks good. Keeps it super simple as well having everything in the docs.
