### ISSUE TITLE
Handlebars in query parameters/bindings gets processed

### ISSUE THREAD

**Issue by CSLTech** [Budibase/budibase#13259]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Describe the bug**
We have an API that takes in handlebars patterns in some JSON properties. However, it seems like the backend of budibase is processing those even if they shouldn't be. This happens **IN ADDITION** the configured body format.

For example, if I have a payload that should look like:
`{"test": "{{ thisIsSomeValue }}"}`
Then what budibase sends as a REST request with a payload that looks like:
`{"test": ""}`

I also validated that it isn't simply sanitized as some static values do get processed correctly, for example:
`{"test": "{{ 'abcdef' }}"}`
Becomes
`{"test": "abcdef"}`

**To Reproduce**
1. Create a REST API datasource
2. Create a body format that includes some bindings
3. Send in Handlebars formatted data as one of those bindings
4. Bad request

**Expected behavior**
Strings should be passed as-is without further processing from the backend.

**Screenshots**

Bindings: 
![image](https://github.com/Budibase/budibase/assets/2613776/aea16caa-280e-49be-9557-0cc33d63af77)
Body:
![image](https://github.com/Budibase/budibase/assets/2613776/27c5d6c0-6a0b-4e99-ab10-e2ea3f292e64)

Sample Call:
![image](https://github.com/Budibase/budibase/assets/2613776/a1cf56ad-5f6f-4a60-9ff9-49c1445186a1)
Response from postman echo:
![image](https://github.com/Budibase/budibase/assets/2613776/3a64492f-b2a2-4ed3-bd41-acca80e08a0f)

**Additional context**
I haven't poked at the context that budibase binds there, but this could lead to security issue if anything private is in this context. An end user could easily generate REST requests with any value in this context and leak them out.

**Comment by CSLTech** [comment]
Please note that I tried escaping it, but couldn't find a good way to get the properly formatted versions output. \{{ value }} ends up as {{ _all_ value }} (For some reason) And quadruple brackets don't get processed at all and don't output a double bracket.

**Comment by CSLTech** [comment]
After a bit more poking around and dumping the context. I can confirm that I can dump sessionIds, CSRF Tokens, etc.

**Comment by mike12345567** [comment]
Hi @CSLTech - this is all intended functionality - I don't think there will be an easy way in Budibase to send Handlebars like statements - we will always process them.

They only way I can think to get around this would be to use the bindings, for example add a binding to your body of `{{ Binding.handlebars }}` then configure a binding, with a default of the HBS statement that you wish to send. This way handlebars will process in the handlebars and it shouldn't be processed again.

As for the session IDs, CSRF tokens etc these are all intended, requested features. The ability to send details about the current logged in user is very useful, a lot of people depend on this for connecting to external services using their users SSO credentials.

Going to close this issue - I don't think there is much else we can do about this as HBS statements are supposed to be processed by Budibase, and I don't think there is a nice way to escape them.

**Comment by CSLTech** [comment]
I'm sorry, but I don't see how this isn't considered a security issue and is intended behavior. I think you're misunderstanding the issue.

If an **END USER** inputs handlebars like data in an app field(not builder), then it gets processed by the backend.

**Comment by CSLTech** [comment]
@mike12345567 Just to add that this bug affect all custom queries and not only REST queries. This means that if a user were to attempt to save the value {{{.}}} in a field, it would save the context instead of the intended value.

This is also very different than the "table" behavior where those, properly do not get interpolated and the proper values get saved.

The changes from https://github.com/Budibase/budibase/pull/13280 do not break the intended behavior and still allows for all the normal binding behaviors and only fixes the unintended behavior of processing bindings in end user inputs.

**Comment by mike12345567** [comment]
Ah @CSLTech - thank you for the explanation - I now see what you mean and can recreate it. I'm not 100% sure about https://github.com/Budibase/budibase/pull/13280 as removing the enrichment can affect some paid features of Budibase - but I will take a look to see what can be done.
