### ISSUE TITLE
Adjustable Icon Sizes within Buttons

### ISSUE THREAD

**Issue by Stropdasman** [Budibase/budibase#13261]
First off, thanks for this feature [https://github.com/Budibase/budibase/pull/12624](url).

It would be great if it would be possible to resize an icon within a button.
![image](https://github.com/Budibase/budibase/assets/147417929/8dc0c0c4-7c62-455a-8d71-90f513dff6b8)
It is a small thing but I think it looks a little small and because of that weird.

edit: It would also be great if there was an option to only show an icon in a button and no text.

**Comment by ConorWebb96** [comment]
Hey @Stropdasman,

I believe the icons currently re-size based on the buttons size. So if you increase the size of the button you are using. The icons should also increase as well.

I'm not sure it would be great to allow the icons size to be changed as it would increase the button size. Making the text look small when comparing.

Hopefully this makes sense.
