### ISSUE TITLE
redis-service hardcoded on k8s helm chart template

### ISSUE THREAD

**Issue by rafaelrpinto** [Budibase/budibase#13304]
**Checklist**

- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: k8s
  * Budibase Version: Helm chart 3.0.91 (newer versions are not found by the Terraform helm provider)

**Describe the bug**
When deploying the helm chart on GKE targeting an existing Redis instance the deployment fails as it still attempts to connect to redis-service and it seems to be hardcoded on the helm chart template files.

**To Reproduce**
Deploy the helm chart targeting an existing redis instance like described on the k8s docs.

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/36b92324-5c94-49f7-9e86-18b0ff32b1a6/4f298dd5-5268-42f7-9dce-be9b12c0f05a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8zNmI5MjMyNC01Yzk0LTQ5ZjctOWU4Ni0xOGIwZmYzMmIxYTYvNGYyOThkZDUtNTI2OC00MmY3LTlkY2UtYmU5YjEyYzBmMDVhIiwiaWF0IjoxNzEwOTMxODg4LCJleHAiOjMzMjgxNDkxODg4fQ.s8PTHCWIJLn6_0p9tVfWuzdDmGr-U9f7pbcrBKtmEQg)

**Expected behavior**
Should target the redis instance instead of redis-service.

**Screenshots**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b67548ca-073b-462a-a5d9-b2666a4016cc/98bba65f-f135-4891-b19c-1a3d50e993ab?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9iNjc1NDhjYS0wNzNiLTQ2MmEtYTVkOS1iMjY2NmE0MDE2Y2MvOThiYmE2NWYtZjEzNS00ODkxLWIxOWMtMWEzZDUwZTk5M2FiIiwiaWF0IjoxNzEwOTMxODg4LCJleHAiOjMzMjgxNDkxODg4fQ.cNRdqQ2m9fNTOXetsa_x1p4SctSOkChxvmBihqgrsZI)

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/aae5d4e8-cdaa-48e3-9857-80f63138d6c9/f61f583b-0db9-4672-b66c-58e77a738569?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hYWU1ZDRlOC1jZGFhLTQ4ZTMtOTg1Ny04MGY2MzEzOGQ2YzkvZjYxZjU4M2ItMGRiOS00NjcyLWI2NmMtNThlNzdhNzM4NTY5IiwiaWF0IjoxNzEwOTMxODg4LCJleHAiOjMzMjgxNDkxODg4fQ.fJZOehuSKE2MuD3WaffNK9sNygyOzuVKp9MbrfUbFks)

**Comment by samwho** [comment]
Hey @rafaelrpinto! Sorry for the delay on getting back to you here.

Could you try `url` instead of `host`?

```yaml
  services:
    redis:
      enabled: false
      port: 6379
      url: "myrediscluster.io"
      password: "your-redis-password"
```

I made a mistake in the docs, sorry about that. I've fixed that now and this _should_ work.

Going to close this ticket out but please do feel free to reopen it if it still doesn't work!
