### ISSUE TITLE
Row bindings change to the same one when table data is ordered or page is changed 

### ISSUE THREAD

**Issue by Koyuv** [Budibase/budibase#13306]
Hello guys, 
I've found the following problem, but first I want to apologize if my report is bad. This is the first one I'm filling out.

**Checklist**
- [Yes ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image(Docker Desktop) on Windos 10 Pro
  - Budibase Version: 2.16.0

**Describe the bug**
When you change the sorting order from the column headers on a table, the bindings for all rows change to the same one. This also happens if you have pagination and move to the second page.

**Expected behavior**
The bindings should be as expected for the selected row, no matter the sorting order.

**Screenshots**
I hope this explains it better, the "open" link should open /details/client_id, but after sorting it always points to the same client_id.

![table-problem](https://github.com/Budibase/budibase/assets/163403627/39594f6e-51bb-414a-8c27-5b536223b7ca)

**App Export**
[problem test-export.tar.gz](https://github.com/Budibase/budibase/files/14664694/problem.test-export.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Version 122.0.6261.129 (Official Build) (64-bit)

**Comment by aptkingston** [comment]
Hi @Koyuv. We're currently on version 2.22.11 and this has already been fixed, so you just need to update to the latest version.
