### ISSUE TITLE
On screen load doesn't seem to be currently working as intended

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13321]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.22.5
  - App Version: 2.22.5

**Describe the bug**
When passing values via an on screen load they seem to be returning empty or not working as intended. After switching between the pages after initial load this seems to correct itself. However if navigating to a page for the first time it won't work.

**To Reproduce**
1. Import the exported app below
2. Go to the home page
3. Preview the page

**Expected behavior**
Should output the value thats present when the page loads initially.

**Screenshots**
![20240321_094305](https://github.com/Budibase/budibase/assets/126772285/bffb5145-d901-49ce-a01a-1d4148a8237a)

Console error
![CleanShot_2024-03-21_at_09 43 562x](https://github.com/Budibase/budibase/assets/126772285/c498407c-4003-4b38-ae01-82090da3a4ba)
  
**App Export**
[on screen load-export-1711014151122.tar.gz](https://github.com/Budibase/budibase/files/14693066/on.screen.load-export-1711014151122.tar.gz)

**Comment by mike12345567** [comment]
Fixed in 2.22.8.
