### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tableName')

### ISSUE THREAD

**Issue by Damienaka** [Budibase/budibase#13322]
Hello,

I've search the existing issue and could found it but no solution was provided.

We're running a self hosted docker container. App version is 2.13.15

When showing relationships in the datasource of the my app, browser hangs and it's not possible to do anything.
Application is not useable anymore cause relationships are not fetched properly.

In the console, we get this error:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tableName')

![image](https://github.com/Budibase/budibase/assets/130987784/3e7fc325-d15e-4746-b1a7-d0eaec5739b4)

Only a column in a table was added before the bug occured. No table was added, no relationships modified.
Column was removed and db fetched again but behavior does not change.
A restore of the DB from 3 days ago when the application was still working normally was done, no change, issue still occurs.

Using link: http://fs01m01budibd01.mycompany.corp/builder/assets/index-cec8c964.js:1574 leads to this code block

    class Relationships extends SvelteComponent {
        constructor(e1) {
            super(),
            init$1(this, e1, instance$6C, create_fragment$6v, safe_not_equal, {
                datasource: 0
            })
        }
    }

Please find the budibase logs for troubleshooting purposes.
[Edit - app removed]

 - OS:  MacOS Sonoma 14.3.1
 - Browser Chrome
 - Version Version 122.0.6261.128 
 
Thanks a lot!

Damien

**Comment by aptkingston** [comment]
Just to clarify - this error appears when you select the relationship tab for a datasource? Like this?
![image](https://github.com/Budibase/budibase/assets/9075550/f5ee003a-9107-4fd0-a127-ab8e014cfd2e)

**Comment by aptkingston** [comment]
I've also removed the app export from the issue - your app export was unencrypted and contains credentials to access your `infocollection` database AWS which I assume you do not want to be public. I would suggest you change the credentials for that database if this was unintentional.

**Comment by Damienaka** [comment]
Hello, yes it appears when I select this tab in the datasource, correct.
Thanks for the hint about creds included, for sure it was intentional. Just changed it.

**Comment by Damienaka** [comment]
Hey Conor,

Unfortunately I  can't, issue appeared out of the blue without us noticing it prior to adding some elements in the DB.
We "lost" all relationships while creating or updating.

I will check for an update but I'm just a power user, I'm not handling the app itself.

Regards,

Damien

**Comment by Damienaka** [comment]
Hello,

just for info, this issue was handled in this issue:
https://github.com/Budibase/budibase/issues/12044

Regards,

Damien

**Comment by Damienaka** [comment]
Hello,

I don't understand why it was closed. Issue is not solved and there was no feedback at all concerning the treatment in the previous isse.

Regards,

Damien

**Comment by ConorWebb96** [comment]
Hey @Damienaka,

This issue was closed for a few different reasons.

The main being there was no reproduction steps. We can't fix what we can't reproduce. If you manage to reproduce this issue, please share the steps with us and we will re-open this issue.

Secondly, you are 9 minor versions behind. Its likely that updating to the latest version will resolve your issue. Even if we were to fix this issue, you'd have to update. 

I hope this makes sense.
