### ISSUE TITLE
External data source - parameters not being passed to query 

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1333]
**Describe the bug**
I created an external data source, with parameters. The parameters are not being passed through to the query, but they are being sent in the client API request.

**To Reproduce**
1. Create an external datasource, and query with parameters (I'm using postgres)
2. Run Query - the default parameters get sent, but not input into query
3. Try using your query in Design, with parameters bound to for controls - same issue

**Screenshots**
https://www.loom.com/share/f1a513982a9a4140818d5b41246d4928

**Comment by shogunpurple** [comment]
This one has been fixed! Closing
