### ISSUE TITLE
JAVASCRIPT Helper parameter syntax changed 

### ISSUE THREAD

**Issue by raventechnologiesinc** [Budibase/budibase#13333]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: raventech

**Describe the bug**
const d = new Date();
var hour = d.getHours();
var minute =d. getMinutes();
var second = d.getSeconds();

var out = helpers.date($("now"), "MMDD")  + hour+minute+second;

return $("State.AGENTPREFIX") + out;

This syntax used to work.

With new update, throws JS error.

We writing a non-helper

**Comment by aptkingston** [comment]
Thanks for raising, will be fixed shortly :)

**Comment by adrinr** [comment]
This was fixed on the [2.22.11 release](https://github.com/Budibase/budibase/releases/tag/2.22.11)
