### ISSUE TITLE
Re fetching existing tables with ignore timezone toggle set, resets this back to off.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13353]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.22.12 
  - App Version: 2.22.12

**Describe the bug**
When re-fetching existing tables, toggles already turned on for `ignore timezones` gets defaulted to off and you have to re-enable again.

**To Reproduce**
1. Create a simple Postgres db with a timestamp field
2. Sync this into your Budibase app via the Postgres connector
3. Edit the timestamp field and toggle `ignore timezone` to on
4. Re-fetch the table and see that its now toggle off.

**Expected behavior**
This should remain on and should likely only get removed if a table is removed from the listing.

**Screenshots**
**Demo of whats happening**
![20240326_082032](https://github.com/Budibase/budibase/assets/126772285/49a54b36-56e8-4f55-a9fd-8771357efdd2)
  
**App Export**
```sql
CREATE TABLE example_table (
    id SERIAL PRIMARY KEY,
    timestamp_column TIMESTAMP
);
```

**Additional context**
I believe this to be a regression, as i vaguely remember this being an issue before.

**Comment by aptkingston** [comment]
Do other customisations get reverted? I would imagine that this isn't specific to the timezone toggle. We're probably just fully overwriting the table schema when you refetch.

**Comment by ConorWebb96** [comment]
Yes @aptkingston,

It seems all the toggles get reverted `Date only`, `required` etc. This only seems to happen for date related fields.

**Comment by mike12345567** [comment]
This is likely something to do with the fetching system - we usually carry over special properties/note fields that can carry special properties/customisations, date isn't currently considered one of those.
