### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Grumpypjs08** [Budibase/budibase#1336]
**Describe the bug**
When I deploy it works fine then when I click "View your deployed app" it brings me to a localhost 10000 link and I get a Site can't be reached error

**To Reproduce**
1. Go to 'the builder
2. Open the app
2. Click on deploy
3. Deploy app
4. Wait
5. View Deployed app

**Expected behavior**
To open the live link

**Desktop (please complete the following information):**
 - Winodws 10 
 - Chrome
 - IDK

**Comment by theomelo** [comment]
@Grumpypjs08, do you mind sharing a screenshot of your error and the version of your Budibase Builder?

**Comment by shogunpurple** [comment]
Will be resolved in this weeks release. Thanks!
