### ISSUE TITLE
MsSQL Tables are empty in budibase

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#13384]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.22.13
  - App Version: 2.22.13

**Describe the bug**
I just noticed that the MsSQL Tables across all our applications are empty even though the connections and queries work fine.

**To Reproduce**
1. Create application
2. Add your MsSQL server
3. Fetch tables
4. See empty tables

**Expected behavior**
Just a couple of weeks ago the tables were filled and should always have their data in the budibase app.

**Screenshots**
<img width="431" alt="image" src="https://github.com/Budibase/budibase/assets/95284278/6c2aea45-8269-4b82-b1bc-be7ab4bcff02">

  
**App Export**
Not app specific

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser every browser
 - Version 1

**Comment by andz-bb** [comment]
hey @kasgithub8, could you send your network logs for the `search` network request please? You can find them in the *Network* tab of your browser's development tools. 

<img width="1512" alt="image" src="https://github.com/Budibase/budibase/assets/110921612/61c71451-5106-4e34-acaa-c114536c4937">



It would also really help to be able to see your MS SQL table schema. Is it only this table that doesn't work for you or does it happen for all of them? Thanks

**Comment by kasgithub8** [comment]
Hi @andz-bb,

 my search doesn't look like yours at all, I can't even show you preview because it's obviously empty:
![image](https://github.com/Budibase/budibase/assets/95284278/8f532ad0-ea0a-440e-a22b-b59118232a55)

And yes, this happens to all the tables.

**Comment by andz-bb** [comment]
@kasgithub8 

could you send your table schema please? I haven't been able to replicate on my side

**Comment by kasgithub8** [comment]
@andz-bb I can send one even though they're all affected:
`CREATE TABLE [hapa] (
MAN varchar(50) NULL,
AK varchar(50) NULL,
PNR varchar(50) NULL,
Vertrag varchar(50) NULL,
Name varchar(50) NULL,
Beschreibung varchar(50) NULL,
Bezeichnung Dokument varchar(500) NULL,
Gueltig_ab date(3) NULL,
Datei varchar(50) NULL,
Gueltig_bis date(3) NULL,
RowId int(4) NOT NULL,
 CONSTRAINT [PK_hapa] PRIMARY KEY (RowId)
);`

**Comment by ConorWebb96** [comment]
Hey kasgithub8,<br><br>Does the user that you are connecting to the database with have the correct permissions to view the rows inside the table?<br><br>I haven't been able to reproduce this behaviour.

**Comment by kasgithub8** [comment]
Hi @ConorWebb96,

it seems to again. The mssql table is filled with its data again.
I don't know what caused it or fixed it, maybe a random platform update.
Thank you still!
