### ISSUE TITLE
Issue when a REST endpoint responds with status code 204 and no response body. Handle REST response cases with no body

### ISSUE THREAD

**Issue by robertof-surveypal** [Budibase/budibase#13412]
When a REST endpoint is invoked and responds successfully but without a response body Budibase throws an error:

The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Array

It's normal for example when deleting entities that the response is sent with status 204 (no content) and no response body (for example †NextJS doesn't even allow to send any response body on status 204) so this appears to be a bug on the Budibase side.

Verified on local environment with version 2.19.5 of the docker image and on a Kubernetes cluster installed using version 3.0.91 of the Helm chart.

### Discussed in [https://github.com/Budibase/budibase/discussions/13335](https://github.com/Budibase/budibase/discussions/13335)

Originally posted by **robertof-surveypal** March 22, 2024
Hello,

We are trying out Budibase at the moment (currently using the docker image in a local development environment) and everything went pretty well until we started making call to a DELETE REST endpoint that doesn't return content (and sets the status code accordingly to 204). The requests are executed successfully by the endpoint but in Budibase we see this error:

The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Array

That seems to happen every time the response body is empty. Is anyone else seeing the same issue and would there be a way to fix this?

Thanks in advance!

**Comment by mike12345567** [comment]
This issue will be fixed in the next release of Budibase.
