### ISSUE TITLE
Docs need updated for table component deprecation

### ISSUE THREAD

**Issue by MayurVirkar** [Budibase/budibase#13420]
**Checklist**
- [Y] I have searched budibase discussions and github issues to check if my issue already exists

- Self
  - Method: docker compose &  digital ocean.
  - Budibase Version: Latest
  - App Version: Latest

**Describe the bug**
https://docs.budibase.com/docs/table#configure-columns

This option is unavailable. 

**To Reproduce**
Add a table or autogenerate table from DB tables.

**Comment by aptkingston** [comment]
Thanks for pointing this out - the docs are simply referring to the old table component which we recently deprecated. With the new table component you can still configure which columns you want, and their labels, using a similar looking setting: 
![image](https://github.com/Budibase/budibase/assets/9075550/a49c3028-3f8a-477a-9b83-d0f7aaccf0e2)

**Comment by ConorWebb96** [comment]
Hey all we have updated the docs to reflect this. The Grid Block and Table Block have been remove and everything relevant has been moved into the Table component part of our docs.

This [link](https://docs.budibase.com/docs/table#configure-columns) should now redirect you to the correct area within our docs.

**Comment by MayurVirkar** [comment]
How to configure the column width and data manipulation using the new version?

**Comment by ConorWebb96** [comment]
Hey @MayurVirkar,

You can drag each column to the size you want.

**Comment by MayurVirkar** [comment]
I tried that. Didn't work.
I will check again. 
And what about data manipulation?

**Comment by aptkingston** [comment]
By data manipulation do you mean the setting on the old table that let you configure a binding for the value of each column? If so, the new way to do this is to use formula columns to create whatever sort of values you want. You can then use these values in any components, not just tables.

**Comment by MayurVirkar** [comment]
Interesting!!
Thanks!
