### ISSUE TITLE
Configurable actions on Side Panel open/close

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#13429]
Currently, clicking anywhere outside of the side-panel will close the side-panel. Side-panels are often used to contain forms that edit or update data, and clicking out of the side-panel results in the immediate loss of any unsaved changes.

In the Side Panel settings there should be an option to create actions on-open and on-close, and a toggle that allows the developer to decide if clicking out of the side-panel will close the side-panel.

Having the option to run actions on-close would give developers a chance to prompt the user to complete their form.

This feature request stems from an exploration of [Discussion #13401](https://github.com/Budibase/budibase/discussions/13401)

**Comment by thinkbig1979** [comment]
Definitely agree. If the panel closes, all unsaved data is lost. This is a UX no-no. There should definitely be an option to prevent this from happening so easily.
