### ISSUE TITLE
Clicked row action not working

### ISSUE THREAD

**Issue by mstr13** [Budibase/budibase#13422]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud

**Describe the bug**
In the Table component, if we bind the table data to a Data Provider the {{ Clicked row._id }} action doesn't work. Instead if we bind directly to the table instead of the Data Provider it works as expected. The used database is the BB built in database (couchdb).

**To Reproduce**
1. Create a new BB database table with random data (at least 2 rows).
2. Create a new screen from the data of that new table (Table with details panel).
3. Create a new Data Provider for the new table
4. Move the table component inside the Data Provider
5. Change the table component data binding to use the Data Provider
6. Preview and click on any row except the first one.
7. The side panel opens with the data from the first row instead of the data from the second row.

**Expected behavior**
The {{ Clicked row._id}} should return the right _id.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 123.0.6312.106

**Comment by aptkingston** [comment]
Hi @mstr13. We have removed that old table component that used a data provider in favour of the new table component (previously called grid block) which does not need a data provider. It still supports row click actions. Could you please update your Budibase version and use the new table component instead? If there's an issue with that one then feel free to open a new issue.
