### ISSUE TITLE
Design Overhaul

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#1342]
Tasks
- Move over the existing form components form standard-components to bbui
- Update the rest of bbui components to use Spectrum variables
- JSDoc for all the components
- Layout components that solve spacing (padding, margin)
- Move bbui into the monorepo
- Converting the current theme selector to use built-in Spectrum theme
- Wrap spectrum classes in the root builder
- Update Builder to use new components

**Comment by kevmodrome** [comment]
One way to get props for bbui and other things using just JSDoc: https://github.com/ibm/sveld

**Comment by shogunpurple** [comment]
stale bot pls
