### ISSUE TITLE
Unable to download the helm chart - Not found

### ISSUE THREAD

**Issue by yianniBantes** [Budibase/budibase#13443]
I am trying to deploy budijet to kubernetes via helm. I am following the instructions from the web, but helm is unable to download the helm chart. This is what I get: 

<code>
$ helm repo add budibase https://budibase.github.io/budibase/ 
$ helm repo update
$ helm install --create-namespace --namespace budibase budibase budibase/budibase
Error: INSTALLATION FAILED: failed to fetch https://budibase.github.io/budibase/budibase-3.0.109.tgz : 404 Not Found
</code>

**Comment by mike12345567** [comment]
Hi @yianniBantes - sorry for the issue here, if you try again this should be functioning correctly now, we've corrected the issue and the helm chart for 3.0.113 has been published.
