### ISSUE TITLE
Components and templates market

### ISSUE THREAD

**Issue by SOVLOOKUP** [Budibase/budibase#1345]
We need a community for developers to upload and share components/templates with each other.  And make some components tradable to motivate peoples to contribute.(maybe a new kind of decentralized currency)

bb should spend more time in low code components’ develop specifications rather than making more components, let the community to do this.

**Comment by shogunpurple** [comment]
@SOVLOOKUP Really interesting that you mentioned this - all of this is on our roadmap, and budibase users will have the ability to:
- Build and share templates and components
- Code against the platform

In the coming months.

What would your ideal marketplace look like? What would the perfect component/template building experience look like to you?

**Comment by SOVLOOKUP** [comment]
Awesome! Looking forward to the coming things in next. 

There are many platforms have marketplace, but their ecology is difficult to develop. But the opposite is the rapid development of those digital currency communities. I think we need attract capital to inject vitality into the community market like these digital currency communities(use NFT or make something called codecoin), only when contributors can benefit from project contributions, the ecology will get better and better.

On component development, I hope:
 - the component/template I made can not only be used in BB, but also in other code projects. They are developed and published as npm modules.
 - BB can dynamically load component/template , don’t need to rebuild to add components.
 - There are tools like [open-wc](https://github.com/open-wc/open-wc) that give me the best solution and guide me to comply with the norms without requiring me to spend extra energy.

If you think these ideas make sense, I am very happy to participate and put them into reality.
