### ISSUE TITLE
Issue in automation Collect Data / steps.n.success fails

### ISSUE THREAD

**Issue by esellier** [Budibase/budibase#13460]
The Collect Data "fails" when trying to get the result of a previous step.
The handle bar is ok I think {{ steps.6.success }}, and it runs fine in the builder when I test the automation, but fails in published app. All other previous steps before 6 are also OK.

I serialiized steps in backend log.
And there are two null values between step 5 and 6. So the steps.6 resolves to null.
So far I guess it is  probably because in step 4 there is Delete Row, inside a loop, but if the loop has no iteration (empty array) as the previous query in Step 4 returns [], so there maybe null values for the loop and another null for the delete?? (just a guess...).

see: https://discord.com/channels/733030666647765003/1227913272838328320

![Screenshot of Google Chrome at 11 Apr 2024 at 14_32_56](https://github.com/Budibase/budibase/assets/12795778/64af50c2-0bc4-468f-b8f4-f9e5d74f556f)

Serialization of steps :
[ {}, {
    "success": true,
    "result": true,
    "refValue": 14,
    "comparisonValue": 0
}, {
    "success": true,
    "result": true,
    "refValue": 83080682,
    "comparisonValue": 1
}, {
    "success": true,
    "result": true,
    "refValue": "[{\"_id\":\"ro_ta_07c7df53dc90433c99fa16cb6d7f98fc_f868970973fc49c7a168566e4ceedc72\",\"primaryDisplay\":\"83080682\"}]",
    "comparisonValue": "0"
}, {
    "rows": [],
    "success": true
}, null, null, {
    "row": {
        "tableId": "ta_81016989d5da4fe792db0b92e7e98d88",
        ...
        "_id": "ro_ta_81016989d5da4fe792db0b92e7e98d88_e3f373f6a2734ca6933ba201e455b8cb"
    },
    "response": {
        "tableId": "ta_81016989d5da4fe792db0b92e7e98d88",
        ...
    },
    "id": "ro_ta_81016989d5da4fe792db0b92e7e98d88_e3f373f6a2734ca6933ba201e455b8cb",
    "revision": "1-bcd7f204821ef1a8f24a49f265c7efc9",
    "success": true
} ];

**Comment by mike12345567** [comment]
Hi @esellier - this is likely due to the empty loop.

Have you tried renaming your steps and referencing them directly using the new step format, `{{ stepName.property }}`

**Comment by esellier** [comment]
Tried to rename steps.
The steps after the loop do not appear in the Bindings list (see screenshot).

![Screenshot of Google Chrome at 11 Apr 2024 at 14_39_40](https://github.com/Budibase/budibase/assets/12795778/8bb3cf36-ccd6-46b2-8e47-a3136d3fb82e)
![Screenshot of Google Chrome at 11 Apr 2024 at 14_38_51](https://github.com/Budibase/budibase/assets/12795778/e1d2cc8f-14ae-4b6e-af3f-b0a1074b72dd)
