### ISSUE TITLE
Explore tools for E2E testing on multiple browsers

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#1350]
Working on getting tests to pass in cypress I just realised we should probably at some point aim to use a tool that can test in multiple browsers now that we're single-stack. We're currently using cypress which doesn't support webkit.

An alternative I've played briefly with is [Playwright](https://github.com/microsoft/playwright) but there are probably other solutions out there.

Not sure what label to apply here.

**Comment by Florian-Schoenherr** [comment]
https://happo.io/ might be useful
