### ISSUE TITLE
[MSSQL] changing the default dbo schema to anything else makes the table unavailable when using the other schema to fetch the table

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13515]
**Checklist**

- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.23.6
  * App Version: 2.23.6

**Describe the bug**
When changing a MSSQL table from the default `dbo` schema to anything else. It causes the table to be unavailable and an error message `There was a problem loading your grid Invalid object name 'testtest.object Object'.` Is thrown in place of the table.

**To Reproduce**

1. Connect to a MSSQL data source
2. Create a new table
3. Switch the schema to anything but the default `dbo`
4. Connect to the same data source with the newly created schema
5. Fetch and view the table
6. See error

**Expected behavior**
The table should be able to get fetched and displayed within Budibase regardless of the schema attached to the table.

**Screenshots**
**Grid error**

![Screenshot 2024-04-18 at 09 22 04](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/3a8f7ddf-3a79-4945-bac2-35afeb439783/dbf78486-7c16-4a19-b847-44bd348a139d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8zYThmN2RkZi0zYTc5LTQ5NDUtYmFjMi0zNWFmZWI0Mzk3ODMvZGJmNzg0ODYtN2MxNi00YTE5LWI4NDctNDRiZDM0OGExMzlkIiwiaWF0IjoxNzEzNDI4Nzg2LCJleHAiOjMzMjgzOTg4Nzg2fQ.TcfWaAZQT9E44b7Qkwaue7H5mtelusofBDKMQf2cHBg "=1512x")

**Network error**

![Screenshot 2024-04-18 at 09 22 47](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/d088813f-930b-41c1-bde3-a03f4505f2e8/b8f2039b-0f4b-4f50-9449-1034ad6f2d10?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9kMDg4ODEzZi05MzBiLTQxYzEtYmRlMy1hMDNmNDUwNWYyZTgvYjhmMjAzOWItMGY0Yi00ZjUwLTk0NDktMTAzNGFkNmYyZDEwIiwiaWF0IjoxNzEzNDI4Nzg2LCJleHAiOjMzMjgzOTg4Nzg2fQ.sCpxom9Ouh3wnWkeI1XEItXTjf2lNNADsWAh0CE8stA "=738x")

**console error**

![Screenshot 2024-04-18 at 09 23 14](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/289dc711-6b17-4f8c-9b16-f028cdbc4e75/d3e813f4-39a6-4e96-8b54-6a7d6eda9ae7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8yODlkYzcxMS02YjE3LTRmOGMtOWIxNi1mMDI4Y2RiYzRlNzUvZDNlODEzZjQtMzlhNi00ZTk2LThiNTQtNmE3ZDZlZGE5YWU3IiwiaWF0IjoxNzEzNDI4Nzg2LCJleHAiOjMzMjgzOTg4Nzg2fQ.XfKhgIuhjU9Iuas-ZSZaTIwY_Kqd9NY89XRbAfkviJE "=743x")

**App Export**
**Create a table**

```sql
CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Department VARCHAR(50),
    Salary DECIMAL(10, 2)
);
```

**Change the table schema**

```sql
CREATE SCHEMA testtest; 

ALTER SCHEMA testtest TRANSFER dbo.safe_house_activity;
```

**Comment by mike12345567** [comment]
This is resolved as of 2.23.8.
