### ISSUE TITLE
Yarn setup run fail in my mac

### ISSUE THREAD

**Issue by kiner-tang** [Budibase/budibase#13537]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
<img width="891" alt="image" src="https://github.com/Budibase/budibase/assets/10286961/4d2747d2-ee01-4d97-be7d-c9104f97925f">

And the `@budibase/pro` version will be change to `latest` automatically when i run `yarn setup` or `yarn`

![image](https://github.com/Budibase/budibase/assets/10286961/d790087c-2872-48a6-a79b-1c3030a2b7ba)

**To Reproduce**

**Expected behavior**

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

**Comment by kiner-tang** [comment]
> Is the `Couldn't find package "@budibase/pro"` happening consistently? The change of the package reference to `latest` is expected, but the package `latest` should be available publicly to you: https://www.npmjs.com/package/@budibase/pro/v/latest
> 
> What happens if you run a second time `yarn`?

I get the same issue when I run `yarn` again.
<img width="845" alt="image" src="https://github.com/Budibase/budibase/assets/10286961/0c713445-5cc1-45c6-ad3f-b7efd9c52f11">

**Comment by adrinr** [comment]
Could you share what version of yarn are you using? `yarn -v`

**Comment by kiner-tang** [comment]
> Could you share what version of yarn are you using? `yarn -v`

1.22.19

**Comment by adrinr** [comment]
Could you please pull the latest master from github and check if this PR fixed it for you? https://github.com/Budibase/budibase/pull/13559

**Comment by kiner-tang** [comment]
> Could you please pull the latest master from github and check if this PR fixed it for you? #13559

Thanks, It run!!
