### ISSUE TITLE
I would like the ability to disable an automation if needed.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13532]
**Describe the feature request**
Sometimes while I'm working on an automations It would be nice to have the option to disable an automation. As i don't want it getting hit when others or myself publish the app to release other features.

**Comment by Reftek85** [comment]
I second this,
I would love to be able to disable it without having to delete it completely and having to recreate from scratch if I  want to test again.

**Comment by ConorWebb96** [comment]
Closed as completed
