### ISSUE TITLE
budi hosting --init failing

### ISSUE THREAD

**Issue by webtop** [Budibase/budibase#13535]
**Checklist**
- [ x ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.23.10
  
**Describe the bug**
Running the CLI with: hosting --init causes the error reported in #11982 

**To Reproduce**
1. Make some tea
2. Install Docker 
3. Install nodejs
4. Install the budi CLI
5. Run the CLI command

**Expected behavior**
Not sure, a compose file? This is my first time using the CLI

**Desktop (please complete the following information):**
 - OS: CentOS-Stream 9
 - Browser N/A
 - Version N/A

**Additional context**
[paul.allsopp@office-server budibase]$ docker compose version
Docker Compose version v2.26.1
[paul.allsopp@office-server budibase]$ docker -v
Docker version 26.0.2, build 3c863ff
[paul.allsopp@office-server budibase]$ budi hosting --init
[20:51:50.639] INFO (22766): Error - docker/docker-compose has not been installed, please follow instructions at: https://docs.budibase.com/docs/docker-compose {"tenantId":"default"}

Looked like this was solved in #11982 but it seems to have found its way back.

Thanks.

**Comment by mike12345567** [comment]
This will be resolved in the next release of the Budibase CLI.
