### ISSUE TITLE
It cannot pass a row id from a table contained in the data provider.

### ISSUE THREAD

**Issue by neojigi** [Budibase/budibase#13548]
my budibase version is 2.23.10 on self hosted

I have a problem with a side panel with a form block.

I set the row id setting of the formblock correctly to the key value set in the update state of the table.

Table in root --> on row click --> update state {{ Clicked row.\_id }} --> open side panel = row id pass successfully

However, if I do the same manipulation on the table under the data provider, the row id pass doesn't work and always shows the 1st id.

I would be grateful if you could let me know if there is something I am missing.

```[tasklist]
### Tasks
```

**Comment by neojigi** [comment]
Clicked row._id pass do not work within sume situation.

I've been trying for many days and in many ways, but I can't get it to work. T.T

Sometimes when I click on a row in a table, the row id pass does not work.

table is in root, it works great.

But it doesn't work when the table is in the data provider.
It is clear that row id pass does not work if the table is included in the data provider, which passes the click information.



<< My config >>
os : ubuntu 22.04
type : self hosted 2.23.12
network : behind Nginx reverse proxy with SSL

<< nginx conf's location block >>
   location / {
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header Host $http_host;
       proxy_http_version 1.1;
       proxy_pass http://192.168.0.247:10000;
   }



<< successful case A - row id pass to another screen >>

* table in root
  - on row click --> (edit screen url)/{{ Clicked.row._id }}

* (edit screen)/:id
  - data provider --> ( _id filter binding = {{ URL.id }}
    - repeater
      - form
        - ...fields --> row id pass success!!!!!



<< successful case B - row id pass to side panel's form block >>

* table in root
  - on row click
    - update state : key name with {{ Clicked row._id }}
    - Open Side Panel

* Side Panel
  - Form Block
    - Row ID = {{ State.(key name) }} --> row id pass success!!!!!



<<< but... >>>

In the above 2 success cases, ROW ID PASS do not work if the source table you are clicking on is under DATA PROVIDER.

{{ Clicked row._id }} value seems to work only when the table is at root.

**Comment by BennaceurHichem** [comment]
Same issue faced here.  ROW ID PASS do not work if the source table you are clicking on is under DATA PROVIDER.

Changing the data provider to Table will make the filters doesn't work at all as well.

**Comment by BennaceurHichem** [comment]
@neojigi do filters works properly on those 2 successful cases without need of adding data provider?

**Comment by neojigi** [comment]
In both success stories, we didn't use a data provider, so we couldn't use a dynamic filter.

Row id pass only works well when using a table that has not gone through a data provider.

This could be a bug, or it could be an internal limitation, like not being able to use values from columns that have been through a formula in a sort.

**Comment by neojigi** [comment]
I noticed an important difference.

first picture : The table componet in the sample page created via the template
next picture : The table compoent created on a page I created myself

![from template](https://github.com/Budibase/budibase/assets/167883933/542d4daa-ae03-400f-9ef0-35685b9890a4)

![i made](https://github.com/Budibase/budibase/assets/167883933/cca8a6c2-c041-405f-a104-80cb81e00e22)

The componet name is Table, which is the same for both.
Icon same too.

However, if you look at the image capturing the detailed configuration screen of table, there are differences in the elements and placement of the configuration items.

If I create a table componet from a screen I created myself, the configuration screen is never the same as the table created through the template.

In the table created through the template, the row id pass works well regardless of whether it is included in the data provider or not.

However, if you create a table from a screen that you created yourself, ROW ID PASS does not work if it is included in the DATA PROVIDER.

In addition, a table component created through a template can contain a link component.
However, a table component in a screen that you create yourself cannot contain a link component.

**Comment by neojigi** [comment]
In conclusion, it seems clear that there is a difference between the table component that is included in the template and the table component in the screen that we create ourselves.

Both the name and icon of the component are the same, but the elements in the details screen are different.

The table componet that you create yourself is different because...
  1. row id pass is not allowed when table is included in data provider
  2. link componet cannot be included inside.

The above two issues are not found in table components created via template.

**Comment by ConorWebb96** [comment]
Replicated export here

[data-provider-table-1714648165669.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/82f1d3cb-30b8-43b0-9afa-f27e50324157/f3d55520-ef15-406f-980b-a49d9b384462?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC84MmYxZDNjYi0zMGI4LTQzYjAtOWFmYS1mMjdlNTAzMjQxNTcvZjNkNTU1MjAtZWYxNS00MDZmLTk4MGItYTQ5ZDliMzg0NDYyIiwiaWF0IjoxNzE0NjQ4MzkxLCJleHAiOjMzMjg1MjA4MzkxfQ.OBsLiutF3Y9pm6bXMJiwwT-q9IvDLc15WOnsT7No7tw)
