### ISSUE TITLE
BB Table Rows Filter on Static Formula - all operators disappeared in version 2.23.12

### ISSUE THREAD

**Issue by esellier** [Budibase/budibase#13560]
It seems there was a (unwanted?) change in table rows filter...
I have a column set as a static formula, it was ok in previous versions as I could use any operator for filtering (in my case a Like operator).
But in version 2.23.12 there are no more operators presented in the Builder...

Tried to revert :

* Reverted to version 2.22.19 in App Builder (Self Hosted BD configuration).
  No Effect...
* Did change the composer yaml to force BB using 2.22.19 image
  Status: Downloaded newer image for [budibase.docker.scarf.sh/budibase/apps:2.22.19](http://budibase.docker.scarf.sh/budibase/apps:2.22.19)
  No Effect...

Solved (with still the 2.22.19 version) when I changed the table, by adding (duplication) another column (duplication of a static formula column).
Maybe an issue with the table schema?

Steps that SHOULD reproduce the issue:
A/ Setup a 2.22.19 version
B/ Create table with two numbers column, and a static formula such as
\-{{ Col1 }}-{{ Col2 }}-
C/ Create screen with a DataProvider on this table
D/ Add a filter on the static formula using Like operator
E/ Upgrade to version 2.23
F/ Check if filter is ok in the DataProvider

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/2d180b66-b458-4491-bd06-55cdd13b5338/e044ec46-256e-4f01-a5eb-c429cae7b360?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8yZDE4MGI2Ni1iNDU4LTQ0OTEtYmQwNi01NWNkZDEzYjUzMzgvZTA0NGVjNDYtMjU2ZS00ZjAxLWE1ZWItYzQyOWNhZTdiMzYwIiwiaWF0IjoxNzE0MDQ3MjAwLCJleHAiOjMzMjg0NjA3MjAwfQ.3jf8VQ0C5Kcz8W8jqhgXcuAVs-w7HfaY2DR-1zmkE6w)

**Comment by esellier** [comment]
I did try to update (again) to 2.23, and I have the issue again.
But this time, even adding or duplicating columns have no effect and the operators are still blanked.
Trying to revert to 2.22 and cross fingers... :-(

**Comment by esellier** [comment]
A simple revert to 2.22 from the App Builder did not work (operators still blank).
I had to change the docker-compose.yaml to refer to version 2.22.19, then stop the docker instance (docker compose down).
Then restarted budi with the CLI.
And then operators are back...

**Comment by mrjcgoodwin** [comment]
I'm also seeing this in the cloud version:
![image](https://github.com/Budibase/budibase/assets/6297550/2dcdd900-7222-4616-8e35-6bb787b023b6)

**Comment by ConorWebb96** [comment]
The [PR ](https://docs.budibase.com/docs/custom-datasource) for this has been linked in the issue. A new release just needs to be made. Once thats done this should be fixed with the newest/latest release. 2.24.2

**Comment by mrjcgoodwin** [comment]
> The [PR ](https://docs.budibase.com/docs/custom-datasource) for this has been linked in the issue. A new release just needs to be made. Once thats done this should be fixed with the newest/latest release. 2.24.2

Sorry - I wasn't sure if there cloud and OS versions followed the same codebase so thought I better tag it in.
