### ISSUE TITLE
Can we add localhost mysql database inside budibase?

### ISSUE THREAD

**Issue by Townieeee** [Budibase/budibase#13563]
### Discussed in https://github.com/Budibase/budibase/discussions/13388

<div type='discussions-op-text'>

<sup>Originally posted by **AryanGaur14** April  2, 2024</sup>
Error creating datasource: Unable to connect: connect ECONNREFUSED 127.0.0.1:3306 this error pops up when i try to add.</div>

**Comment by mike12345567** [comment]
Hi @Townieeee - if you're self hosting then `localhost` or `127.0.0.1` will not be available, as that points to the container/app service localhost, no the docker host. If you wish to communicate with the docker host, then you'll need to connect to your database using `host.docker.internal`. This may depend on your host operating system, you can lookup how to communicate with the docker host based on your OS/docker network configuration.

If you are trying to access a local database from the Budibase Cloud, this isn't possible - you'll need to host your database from a publicly accessible IP or URL for Budibase Cloud to be able to communicate with it.
