### ISSUE TITLE
Filter with "Return no rows" option fails to work with Is Empty / Is Not Empty operators

### ISSUE THREAD

**Issue by lfbittencourt** [Budibase/budibase#13583]
## Checklist

- [x] I have searched budibase discussions and github issues to check if my issue already exists

## Hosting
- Cloud
  - Tenant ID: lfbittencourt.budibase.app

## Describe the bug

The combination of `When filter empty: Return no rows` + a `Is empty` or `Is not empty` filter always results in an empty result set. I've tried both `Match all filters` and `Match any filter` options, but none of them worked. The only way I've found to make the filter work was to replace `When filter empty: Return no rows` with `When filter empty: Return all table rows`, which can lead to undesired results.

My understanding is that `When filter empty` relates to an empty result set, not to the filter operators being used.

## To Reproduce

1. Go to any component that supports filters
2. Add a filter with the following configuration:
   - When filter empty: `Return no rows`
   - Field: Any field
   - Operator: `Is empty` or `Is not empty`
3. Certify that the filter *should* return some rows
4. See the empty result set

## Expected behavior

The filter should return the rows that match the condition, even when the `When filter empty` option is set to `Return no rows`. My understanding is that `When filter empty` relates to an empty result set, not to the filter operators being used.

## Screenshots

Example data:

![image](https://github.com/Budibase/budibase/assets/403539/2317549f-64d9-4990-bcec-9ab2c3daef61)

With `When filter empty: Return no rows`:

![image](https://github.com/Budibase/budibase/assets/403539/6060d02b-5d33-4d81-91c0-0bd4498c28f6)

Data Provider and Table don't return any rows:

![image](https://github.com/Budibase/budibase/assets/403539/029c2fdf-befa-4577-bd62-f035f8831c97)

With `When filter empty: Return all table rows`:

![image](https://github.com/Budibase/budibase/assets/403539/2c6aa3c5-b042-45dd-9c63-e796deb2bb7e)

Data Provider and Table work fine:

![image](https://github.com/Budibase/budibase/assets/403539/e08f2556-5492-4538-9250-1d9be5533214)

## Desktop (please complete the following information):
 - OS: macOS 14.3
 - Browser: Firefox
 - Version: 125.0.3

**Comment by andz-bb** [comment]
hey @lfbittencourt, thanks for the report. Which data source are you using here?

**Comment by samwho** [comment]
Hey @lfbittencourt! Thanks for such an excellent bug report. I looked into this and this feature is indeed for deciding what happens when the _search filter itself_ is empty, not the result set. There's more info in the docs here: https://docs.budibase.com/docs/searchfilter-data#when-filter-empty.

In the process of investigating this, however, we discovered a bug that we think has caused you confusion. When you only use an "is empty" filter, the "when filter empty" toggle is erroneously having an affect on the result. This was not intended, and I have a fix for this in https://github.com/Budibase/budibase/pull/13633.

What you're wanting to do, return all rows when a search would otherwise return no rows, isn't currently something you can do with Budibase.

**Comment by lfbittencourt** [comment]
@samwho Thanks!

> What you're wanting to do, return all rows when a search would otherwise return no rows, isn't currently something you can do with Budibase.

That was my (mis)understanding of how that feature worked, but I didn't want to do that. Anyway, I think we're on the same page and you were able to find the bug I was facing.  Do you have an estimate about when this will be released?

**Comment by samwho** [comment]
@lfbittencourt ahhh I see, sorry for misunderstanding!

The change just went out in release 2.24.2. 🙂

**Comment by lfbittencourt** [comment]
@samwho Just to let you know it's working like a charm now ✨

**Comment by samwho** [comment]
@lfbittencourt super! Thanks again for such a detailed bug report, made the work on this that much easier. 🙏
