### ISSUE TITLE
New Date Picker component - dates/days incorrect

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#13598]
**Checklist**
I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.24.0
  - App Version: 2.24.0

**Describe the bug**
The updated date picker component is showing the dates matching with the wrong days of the week.

**To Reproduce**
1. Add a date picker component to a page
2. View the date picker in the builder, preview or published app
3. Compare todays date to the day of the week shown

**Expected behavior**
It's expected that the date matched the day of the week. For example 2nd May 2024 is a Thursday. 

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/110813989/5562b94c-5cec-4c9d-9b54-7706683f3209)
Screenshot shows 2nd May 2024 is a Friday. Today (Thursday) is the 2nd May.

**Comment by aptkingston** [comment]
Thanks @andyburgessmd. Deploying a fix very shortly.

**Comment by aptkingston** [comment]
That's released and fixed now 👍
