### ISSUE TITLE
Helm chart has same HPA name for automation-worker-service and app-service

### ISSUE THREAD

**Issue by op-euga** [Budibase/budibase#13602]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Describe the bug**
the helm chart uses the same name of the HPA for the app-service and the automation-worker-service. Both use "{{ include "budibase.fullname" . }}-apps"

**To Reproduce**
1. install the helm chart with both HPAs activated
2. Error: 1 error occurred:
 	* horizontalpodautoscalers.autoscaling "budibase-budibase-apps" already exists

**Expected behavior**
rename the automation-worker-hpa to a unique name so that helm chart may be deployed.

**Comment by robtec** [comment]
@op-euga Hey, I forked the repo and renamed the HPA, if you want to give it a test here - https://github.com/robtec/budibase/tree/master

**Comment by shogunpurple** [comment]
this is now fixed

**Comment by op-euga** [comment]
I tried helm chart version 3.0.126 which uses app version 2.25.0 and this worked.
I close this Ticket. 
Thank for fast fix!!!!
