### ISSUE TITLE
BudiBase invalid error when creating relation for MySQL using a relationship table

### ISSUE THREAD

**Issue by vbonachuck-sr** [Budibase/budibase#13646]
### Discussed in https://github.com/Budibase/budibase/discussions/13616

<div type='discussions-op-text'>

<sup>Originally posted by **vbonachuck-sr** May  5, 2024</sup>
Hello everyone. Hope this is a straight forward question. We thought we would try building a form with budibase to maintain the some of master the tables in our MySql db as a quick internal data maintenance solution. The database is fully normalized and there are main tables and relationship tables. 

master_material  = has all materials 
master_information = has all related information about any given material
master_material_information = has the relationship data. A given material may link to 1 or more information records

I'm getting an error in BudiBase which I cannot figure out why that is:

![image](https://github.com/Budibase/budibase/assets/158842211/943301f0-ce99-4816-a3f0-6c47181aed29)

I believe I am matching the requirements, all non-primary key fields as nullable as per screenshot below:

![image](https://github.com/Budibase/budibase/assets/158842211/9c072d5e-cf00-4f96-9559-f3e76e79f4eb)

What am I missing here?? Really appreciate any help I can get on this! </div>

**Comment by ConorWebb96** [comment]
Hey @vbonachuck-sr,

Do you have a MySQL schema/table create scripts for these tables, that I can look at? Doesn't need to include data the create scripts would be enough.

I created a small very simple sql script below that imitates binary as a primary key and everything seems to work fine.

```sql
-- Create table1
CREATE TABLE table1 (
    id BINARY(16) PRIMARY KEY,
    column1 TEXT,
    column2 INT
);

-- Create table2
CREATE TABLE table2 (
    id BINARY(16) PRIMARY KEY,
    column3 TEXT,
    column4 INT
);

-- Create the junction table
CREATE TABLE junction_table (
    table1_id BINARY(16),
    table2_id BINARY(16),
    PRIMARY KEY (table1_id, table2_id),
    FOREIGN KEY (table1_id) REFERENCES table1(id),
    FOREIGN KEY (table2_id) REFERENCES table2(id)
);

-- Insert data into table1
INSERT INTO table1 (id, column1, column2) VALUES (UNHEX('0123456789abcdef'), 'Data 1', 123);
INSERT INTO table1 (id, column1, column2) VALUES (UNHEX('fedcba9876543210'), 'Data 2', 456);

-- Insert data into table2
INSERT INTO table2 (id, column3, column4) VALUES (UNHEX('aaaa1111bbbb2222'), 'More Data 1', 789);
INSERT INTO table2 (id, column3, column4) VALUES (UNHEX('cccc3333dddd4444'), 'More Data 2', 101112);

-- Insert data into the junction table
INSERT INTO junction_table (table1_id, table2_id) VALUES (UNHEX('0123456789abcdef'), UNHEX('aaaa1111bbbb2222'));
INSERT INTO junction_table (table1_id, table2_id) VALUES (UNHEX('fedcba9876543210'), UNHEX('cccc3333dddd4444'));
```

## Screenshots in Budibase
### Junction table
<img width="1219" alt="Screenshot 2024-05-09 at 13 43 19" src="https://github.com/Budibase/budibase/assets/126772285/fb6c858c-bfb9-45be-8f28-0b5cb38f867e">

### Table 1
<img width="1219" alt="Screenshot 2024-05-09 at 13 43 39" src="https://github.com/Budibase/budibase/assets/126772285/74439c7c-ffab-473f-af62-9c075341ee53">

### Table 2
<img width="1138" alt="Screenshot 2024-05-09 at 13 44 05" src="https://github.com/Budibase/budibase/assets/126772285/8c36667d-7535-4290-bfbe-35fb593cd6f5">

### Relationship
<img width="1512" alt="Screenshot 2024-05-09 at 13 44 23" src="https://github.com/Budibase/budibase/assets/126772285/35289472-c0b7-4152-951a-a7510d0ea70d">

**Comment by ConorWebb96** [comment]
Budibase lacks support for primary keys of the Binary type. Consequently, executing automatic CRUD (Create, Update, Delete) operations isn't possible and you will receive "The values in the where clause must not be object or array," you saw before whenever attempts are made to modify or delete data.

We have no plans in the immediate future to support this as it's a bit of an edge case for data storage/indexing reasons in most RDBMS

I'll create a feature request for this and link it here. Additionally, if this functionality is crucial for your use case, you might want to consider reaching out to Budibase's [sales team](https://budibase.com/contact/) to discuss it further. They might be able to provide more insight or explore potential solutions tailored to your needs.

**Comment by vbonachuck-sr** [comment]
Hey Connor

 

Please see attached my structures. Looking at your test, it seems mine should work too… Let me know if you find anything from what I’m sending you. I’ll try to replicate your example too

 

Thanks

Vander
