### ISSUE TITLE
Add support for binary primary keys for external data sources e.g. MySQL, Postgres(BYTEA)

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13647]
**Describe the feature request**
Currently Budibase lacks support for primary keys of the Binary type. It causes lots of issues when trying to use the native CRUD functionality within Budibase.

**Screenshots**
**MySQL error thrown when editing**

![Screenshot 2024-05-09 at 14 37 30](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/d6580078-7621-423a-b9dc-d32995086434/7af50a22-ee95-45b4-9ab3-d9430b1662ef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9kNjU4MDA3OC03NjIxLTQyM2EtYjlkYy1kMzI5OTUwODY0MzQvN2FmNTBhMjItZWU5NS00NWI0LTlhYjMtZDk0MzBiMTY2MmVmIiwiaWF0IjoxNzE1NjkzOTU2LCJleHAiOjMzMjg2MjUzOTU2fQ.X9VSc82Vg6JXJKwbA6033BLVefn773mIIEmzxuKZGjA "=1250x")

**Postgres error thrown when editing BYTEA**

![Screenshot 2024-05-09 at 14 38 51](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/d4dbdf60-8f65-4dd0-a565-64ef6b287f5b/a0596651-f491-410f-92bf-aed45a5592fd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9kNGRiZGY2MC04ZjY1LTRkZDAtYTU2NS02NGVmNmIyODdmNWIvYTA1OTY2NTEtZjQ5MS00MTBmLTkyYmYtYWVkNDVhNTU5MmZkIiwiaWF0IjoxNzE1NjkzOTU2LCJleHAiOjMzMjg2MjUzOTU2fQ.W0FmLH8naQQfIigQ7FbKmtBoFwuPBDPIh_XyvFZnvXA "=1340x")

**Comment by mike12345567** [comment]
Closing this as some improved support has been added.
