### ISSUE TITLE
Navbar links never open in a new tab

### ISSUE THREAD

**Issue by mohagan9** [Budibase/budibase#13653]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: rspb.budibase.app

**Describe the bug**
Links in the navbar do not open in a new tab even when I hold down the Cmd key.
This wasn't ideal because I was filling out a form, and wanted to open a different screen in a new tab that would provide me additional information I needed to complete the form; instead I just lost my progress. 

**To Reproduce**
1. Add navigation links to the navbar
2. Hold down the Cmd key and click on a navigation link
3. The current page changed instead

**Expected behavior**
When using navigation links within a Budibase app, they should behave like hyperlinks on a webpage, i.e. when holding the Cmd key, the link should open in a new tab.≈

**Screenshots**
<img width="616" alt="Screenshot 2024-05-09 at 20 56 00" src="https://github.com/Budibase/budibase/assets/30199063/ac04bab0-3b61-4775-a72b-530c545d819f">
*Also note that initially there is no default radio option selected - a minor UI issue*

<img width="237" alt="Screenshot 2024-05-09 at 20 57 49" src="https://github.com/Budibase/budibase/assets/30199063/65b1af51-e180-485a-949a-965ca14ee5d8">

*When I am on the outings screen, I cannot open the members screen in a new tab, which is inconvenient.*

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave

**Additional context**
I could add a Link component to the Members screen to workaround this, but I don't want to! 🙈

**Comment by andz-bb** [comment]
great first issue @mohagan9! many thanks for your contribution 😊
