### ISSUE TITLE
Env var AUTOMATION_THREAD_TIMEOUT is ignored

### ISSUE THREAD

**Issue by marzzzello** [Budibase/budibase#13660]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method:  docker compose
  - Budibase Version: 
  - App Version: 2.24.2

**Describe the bug**
I have an automation that runs quite long and I increased the timeouts. For the cron job it works fine but when I click "Run test" in the automation editor it still timeouts.
I think the problem is that the env var AUTOMATION_THREAD_TIMEOUT is ignored because of missing parentheses after `||`: https://github.com/Budibase/budibase/blob/efaedbccde8adc17fb389abbd2989b26ad0257ad/packages/server/src/environment.ts#L77-L81

**To Reproduce**
1. Set AUTOMATION_THREAD_TIMEOUT to 60000 (or noticeably more than 12000)
2. Create an automation that needs noticeably longer than 12s
3. Click on `Run test`
4. Get timeout error

**Expected behavior**
No timeout

**Comment by mike12345567** [comment]
This will be fixed in 2.26.1.
