### ISSUE TITLE
user must be of type string

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#13684]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.26.1
  - App Version: 2.26.1

**Describe the bug**
This is something to do with the new user changes added recently.
I have a form with a user field which on submit saves a new row with the user and a date. When submitted it now shows the error 'user must be of type string' and does not save the new row.
![image](https://github.com/Budibase/budibase/assets/110813989/4fd297f3-3fc6-4647-8e04-aeb94d37bfd7)
I have tied to revert to 2.24.2 and it is still present.

**To Reproduce**
Steps to reproduce the behavior: This may not be reproducible when creating new - it could be linked to the change being incompatible.
1. Create a table with a user field
![image](https://github.com/Budibase/budibase/assets/110813989/54cda1f4-5c02-456f-af80-50e676a8b911)
2. Create a new form with a user component
![image](https://github.com/Budibase/budibase/assets/110813989/32585db0-1c63-4975-a291-c368b186fef7)
3. Action on the save button 
![image](https://github.com/Budibase/budibase/assets/110813989/262a74fa-be62-4be6-ad67-8e0529926186)
4. Select the user and save the new row

**Comment by mike12345567** [comment]
Hi @andyburgessmd - we have not been able to reproduce this - is it possible you could provide an app export which exhibits this behaviour?

**Comment by andyburgessmd** [comment]
Yes, but can I email it to you instead of sharing on public?

**Comment by mike12345567** [comment]
Hi @andyburgessmd - yes if you send it to support@budibase.com referencing this issue we will take a look.

**Comment by andyburgessmd** [comment]
@mike12345567 on its way now

**Comment by mike12345567** [comment]
Hi @andyburgessmd - this should be fixed in the latest release.
