### ISSUE TITLE
Builder 0.8.12 : Link behaviour of Horizontal Card differs from Vertical Card

### ISSUE THREAD

**Issue by timconsidine** [Budibase/budibase#1368]
**Describe the bug**
The Link URL property in right sidebar of vertical card works.
The Link URL property in right sidebar of horizontal card does not and produces {"message":"missing","status":404}
The Vertical card produces a link of [domain]/[app]/[route]/[doc_id]
The Horizontal card omits the <app> element so link is [domain]/[route]/[doc_id]

**To Reproduce**
1. Go to a / create a Screen
2. Add container and repeater for table and add both horizontal and vertical cards for comparison
3. In Link URL add e.g. /events/{{ New Repeater.Events._id }} in each of Horizontal Card and Vertical Card
4. Click on Link text, vertical card works, horizontal card does not

**Expected behavior**
Horizontal Card and Vertical Card should produce similar working links 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser : Opera (but it's just a badly formed link)
 - Version : 74.0.3911.218
 - Builder 0.8.12

**Additional context**

**Comment by timconsidine** [comment]
The Stacked Card suffers same problem as Horizontal Card
The generated link omits the <app> element
Only Vertical Card produces fully generated working link

**Comment by shogunpurple** [comment]
Resolved in 0.9. Thanks for reporting!
