### ISSUE TITLE
Cannot remove column from Budibase DB  

### ISSUE THREAD

**Issue by mad4me** [Budibase/budibase#13702]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists
- [X] I have tried refreshing the browser and repeat the same process
- [X] I have tried to use another browser

**Describe the bug**

When I try to remove the columns "Service Due", "Service Interval" and Age  in the table "Viaturas", I just can't, because when i try to edit the column, a blank gray container appears and  the whole site frezees (I need to press F5 to continue my work). Meanwhile in the console, there is an error message like:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at getBindings (index-1597daba.js:1577:40216)
    at Array.create_if_block_13$1 (index-1597daba.js:1578:7611)
    at Array.create_default_slot_5$X (index-1597daba.js:1579:7247)
    at create_slot (index-1597daba.js:1:1002329)
    at create_fragment$91 (index-1597daba.js:157:20741)
    at init$2 (index-1597daba.js:4:11550)
    at new Layout$n (index-1597daba.js:157:22373)
    at create_fragment$5P (index-1597daba.js:1582:725)
    at init$2 (index-1597daba.js:4:11550)
    at new CreateEditColumn (index-1597daba.js:1582:15049)
```

**Screenshots**

![image](https://github.com/Budibase/budibase/assets/54853465/36fa7b81-3e34-4505-ba84-56c5393bac18)
  
**App Export**

[Viaturas-export-1715855862854.tar.gz](https://github.com/Budibase/budibase/files/15333761/Viaturas-export-1715855862854.tar.gz)

**Desktop:**
 - OS: Windows 11 
 - Browser Google Chrome
 - Version 124.0.6367.202

**Comment by andyburgessmd** [comment]
I am also seeing this issue. It seems to affect some types. For me I cannot select edit for formula fields, also I cannot add a new field and it freezes with similar to above if I select formula type in the add dialog.
![image](https://github.com/Budibase/budibase/assets/110813989/b0e229bd-9afc-4d6e-9067-dd5861557cd6)

**Comment by ConorWebb96** [comment]
Hey all,

I believe this might be fixed on the latest version due to this pr: https://github.com/Budibase/budibase/pull/13733. can you both update and check to see if this is now fixed.

Also this seems to be a duplicate of this issue [here](https://github.com/Budibase/budibase/issues/13721).

**Comment by mad4me** [comment]
> Hey all,
> 
> I believe this might be fixed on the latest version due to this pr: #13733. can you both update and check to see if this is now fixed.
> 
> Also this seems to be a duplicate of this issue [here](https://github.com/Budibase/budibase/issues/13721).

I guess I have another problem lol
![image](https://github.com/Budibase/budibase/assets/54853465/b516d0b2-c5f9-47ed-9b7e-a27c852e16ec)

**Comment by ConorWebb96** [comment]
@mad4me what does the response look like? 

Are you able to export and re-import your app? This could fix the issue you are seeing. When I imported your app everything seemed to be working fine.

**Comment by ConorWebb96** [comment]
Apologies, I should have been more clear. I meant the body inside the response, not the headers. It should have an error message in your case.
<img width="572" alt="Screenshot 2024-05-23 at 09 29 34" src="https://github.com/Budibase/budibase/assets/126772285/e45fc6e1-2292-4467-8184-fc6965d4db2c">

**Comment by mad4me** [comment]
Oh okay sorry, im kinda new to this.

Here is the error:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Resource>/v1/update</Resource><RequestId>17D210F885673ABA</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
```

**Comment by mad4me** [comment]
Is there any information about this error? We have self-hosted, is it a problem in our side and should I create a issue?

**Comment by mad4me** [comment]
Nevermind, didnt knew what a docker was (im not the one hosting so sorry :P)

Everything is fine and working, thank you!
