### ISSUE TITLE
formula column can't create when auto column exist

### ISSUE THREAD

**Issue by neojigi** [Budibase/budibase#13723]
[[ my env ]]

{
  "browser": {
    "language": "ko-KR",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
    "platform": "Win32",
    "vendor": ""
  },
  "server": {
    "budibaseVersion": "2.26.4",
    "hosting": "docker",
    "nodeVersion": "v20.11.1",
    "platform": "linux",
    "cpuArch": "x64",
    "cpuCores": 4,
    "cpuInfo": "Intel(R) N97",
    "totalMemory": "15.371822357177734GB",
    "uptime": "7 day(s), 13 hour(s), 0 minute(s)"
  }
}

[[ using db ]]

budibase's internal db

[[ symptom ]]

I have a symptom where I cannot create a formula column with an auto column.

Regardless of the type of CREATE BY, CREATE AT, UPDATED BY, UPDATED AT, or AUTO ID, if there is only one AUTO COLUMN, there is a problem with CREATE or EDIT of FORMULA.

When I press + button for CREATE and then select FORMULA, the UI freezes as shown in the first picture. In this case, I need to enter the browser's address again to enter the site again to be able to operate.

When I press 3 dot to edit a formular column that has already been created, the UI is also stuck. (2nd photo)

![stuck-create-formula](https://github.com/Budibase/budibase/assets/167883933/ad4ee863-0e2a-43b0-b00a-95f17425ade1)
![stuck-edit-formular](https://github.com/Budibase/budibase/assets/167883933/a666e641-926a-4536-a8cf-a8bd672d678c)

Once the UI freezes, re-enter the site address to reopen the screen, then go back to the corresponding DB and delete all AUTO COLUMNS, and you should be able to create a FORMULA COLUMN.

If I do the above, there is no problem to write FORMULA COLUMN, but I need the function of AUTO COLUMN as well.

I'm concerned that the internal db I'm using is corrupted, so I tried creating another empty table and doing some manipulations on it, but it was the same symptom.

**Comment by neojigi** [comment]
my symptom is same to this link. that link is more detail.

https://github.com/Budibase/budibase/issues/13721#issue-2303694622

**Comment by ConorWebb96** [comment]
Closing as the issue you linked has been deemed as fixed. If you check and it isn't please re-open the issue.
