### ISSUE TITLE
Options-picker and mutli-select picker not closing when clickling on opened picker

### ISSUE THREAD

**Issue by pmeier123** [Budibase/budibase#13722]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud
  - Tenant ID: aachenemperors

**Describe the bug**
After updating my App from Version 2.23.12 to 2.26.4 one new bug in options-picker handling appears. I cannot close the options-picker or multi-select picker by clicking on the control itself. Was working in 2.23.12. not working anymore in 2.26.4. makes the handling of multi-select pickers very nasty because i have to click anywhere else in the form to close the picker.

**To Reproduce**
1. Go to an options picker
2. Click on options picker to enter a value
3. Try closing the picker by clicking the picker
4. Error: Picker does not get closed

**Expected behavior**
When clicking the opened picker control again, the picker should close. As working in 2.23.12

**Screenshots**

https://github.com/Budibase/budibase/assets/55078905/77ba2849-2096-46c4-9e68-50b2c39af8ba

https://github.com/Budibase/budibase/assets/55078905/bb9e3ed6-8bc4-4e55-aed5-ce928cc9556f

  
**App Export**
I can give you when neccessary.

**Desktop (please complete the following information):**
 - OS: Windows, iOS
 - Browser Chrome
 - Version 125.0.6422.61 (Offizieller Build) (64-Bit)

**Comment by pmeier123** [comment]
Just got fixed

**Comment by pmeier123** [comment]
@deanhannigan @aptkingston thanks for the quick fix!
is there a planned date for a bugfix release including this fix?

**Comment by pmeier123** [comment]
fixed in 2.27.2

**Comment by aptkingston** [comment]
Thanks for updating this yourself @pmeier123. We released last night which fixed this as you noticed :)
