### ISSUE TITLE
bbproxy               | 2024/05/21 04:43:58 [error] 26#26: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53

### ISSUE THREAD

**Issue by weizhiwang221** [Budibase/budibase#13730]
在使用docker compose 部署的时候，一直报这个错误

**Comment by ConorWebb96** [comment]
Hey @weizhiwang221,

Can you please follow the bug template. Closing as there isn't any logs etc along with the error.

**Comment by DangGwanHou** [comment]
> [BUDI-8272 bbproxy | 2024/05/21 04:43:58 [error] 26#26: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53BUDI-8272 bbproxy | 2024/05/21 04:43:58 [错误] 26#26: 解析时 recv()失败（111：连接被拒绝），解析器：127.0.0.1:53](https://linear.app/budibase/issue/BUDI-8272/bbproxy-or-20240521-044358-[error]-2626-recv-failed-111-connection)

In fact, even if you register and log in after entering this website, all you get is `Authentication Error`, so this comment does not solve this issue at all.

**Comment by DangGwanHou** [comment]
> 在使用docker compose 部署的时候，一直报这个错误

@weizhiwang221 你好，我这几天也遇到了同样的问题，经检查后，是docker-compose文件里bbproxy的环境变量RESOLVER的值错了，应该跟回bbproxy对应Dockerfile里的值，也就是127.0.0.11
希望对你有帮助
