### ISSUE TITLE
Relationships should allow you to pick the table you are building the relationship in. 

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1373]
Relationships should allow you to pick the table you are building the relationship in. This will allow for parent/child records in the same table.

_Originally posted by @lylebrown in https://github.com/Budibase/budibase/discussions/1034_

**Comment by hshifaz** [comment]
What's the budibase way work around till this is implemented?

lets say I've a TASK table and want to have SUB-TASKS. Could be 2 levels or may be 3 levels

for example:
Main Task                 -----> Level 1
->Sub Task 1            -----> Level 2
    -> SubSub Task 1 -----> Level 3
    -> SubSub Task 2

**Comment by joebudi** [comment]
Hey @hshifaz Do you have an illustration of how this would work? This may be helpful to visualise what you mean.

**Comment by hshifaz** [comment]
> Hey @hshifaz Do you have an illustration of how this would work? This may be helpful to visualise what you mean.

If we are to visualize in terms of table relationships, the following to examples should be good enough.

![one2many_many2many](https://user-images.githubusercontent.com/14042347/121732945-b3cf7980-caa7-11eb-9a18-5399f0b74146.PNG)

**Comment by Plasto13** [comment]
Main Task -----> id = 1   order = 0
->Sub Task 1 ----->id = 2 parent_id = 1  order = 0       
-> SubSub Task 1 -----> id = 3 parent_id = 2   order = 0
-> SubSub Task 2 -----> id = 4 parent_id = 2   order = 1
Main Task -----> id = 5   order = 1

database

id_____name___________parent_id______order
1____Main Task ________null or 0_________0
2____Sub Task 1___________1_____________0
3____SubSub Task 1_______2_____________0
4____SubSub Task 2_______2_____________1
5____Main Task  1______null or 0 ________1

use like nestable menu  [Nestable](https://getuikit.com/v2/docs/nestable.html)

**Comment by Shadowfita** [comment]
Bump

**Comment by nataliefoley** [comment]
Hi, is this still under consideration? Would really be helpful for creating things like role hierarchy (manager / subordinates), etc

**Comment by pmankow** [comment]
Bump. Necessary for implementing BOMs.

**Comment by reyop** [comment]
Bump

**Comment by hamzafarooq951** [comment]
Is there any update in this?

**Comment by LifeofGlen** [comment]
Bump
