### ISSUE TITLE
连接不到数据库

### ISSUE THREAD

**Issue by weizhiwang221** [Budibase/budibase#13732]
![Snipaste_2024-05-21_15-37-03](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/6e32f63d-c0c4-451a-bf54-08cc98fe35da/6cf44b23-b039-4991-bdd3-c575f239fe32?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC82ZTMyZjYzZC1jMGM0LTQ1MWEtYmY1NC0wOGNjOThmZTM1ZGEvNmNmNDRiMjMtYjAzOS00OTkxLWJkZDMtYzU3NWYyMzlmZTMyIiwiaWF0IjoxNzE2MjgyOTcxLCJleHAiOjMzMjg2ODQyOTcxfQ.e3Nkrog7r6saBN5z9SNPVDT9ju1NC2NnAHNA_Aw6du4)

**Comment by mike12345567** [comment]
Hi @weizhiwang221 - please follow the bug template when creating issues - we also kindly ask that issues are raised in english as it is easier for the development team to debug.
