### ISSUE TITLE
Table Block removed, New Table Design missing search fields

### ISSUE THREAD

**Issue by jackflack69** [Budibase/budibase#13741]
**Checklist**
- [ ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Docker Single Image 
  - Budibase Version: <2.26.2> 
  - App Version: <N/A> 

**Describe the bug**
Refer to #10288 

**To Reproduce**
Make a search table through a text field.

**Comment by aptkingston** [comment]
Hi @jackflack69. That's correct, the new table block doesn't have a setting for search fields any more. Your options are either:
- Build it yourself, which is very easy. Just add a form block above your table, then configure your table to be filtered using those form fields. This is exactly how we did it with the old table.
- Use the built in searching (hover over a column header and you'll see a search icon). This doesn't work for all types, so it depends on what you need to search.
