### ISSUE TITLE
Not able to login to Budibase cloud

### ISSUE THREAD

**Issue by rishav-propertyguru** [Budibase/budibase#13765]
### Discussed in https://github.com/Budibase/budibase/discussions/13758

<div type='discussions-op-text'>

<sup>Originally posted by **rishav-propertyguru** May 23, 2024</sup>
Hi Everyone,
I used to login to my Budibase client account using Entra SSO, and i had the password saved in a password manager.
While configuring the SSO on Budibase, i tried logging out and logging in with the new SSO.

But now i am logged out of my account, also my password it showing wrong. Reset password is showing "Password reset email sent" but i am not receiving any email.

Need urgent help on this.</div>

**Comment by mike12345567** [comment]
Closing as investigation occurring in referenced discussion.
