### ISSUE TITLE
Action - Navigate - Show as Modal

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#13777]
When the action Navigate to - Show as Modal is executed, the opened modal should ignore outside clicks to force the user to either make an action in the popup or close the popup with the close link on the top right.

An option to not show "Enter Full Screen" and "Close" links on top so at to force the user to make a choice in the popup screen, and some sizing options for the popup to make it bigger / smaller depedning on popup needs would be greatly appreciated.

I would also suggest an On Close event, similar to the Side Panel one to be able to react to what happened in the popup.

**Comment by aptkingston** [comment]
You'll be glad to hear we're currently building a generic modal component (basically the same as a side panel, but a modal) which will allow much more flexibility than the current "open screen in modal" approach!

**Comment by poirazis** [comment]
Then i shall close this request one in anticipation of the new component.

Great news @aptkingston
