### ISSUE TITLE
Cannot select option color in Data section

### ISSUE THREAD

**Issue by mohagan9** [Budibase/budibase#13781]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: rspb.budibase.app

**Describe the bug**
I am trying to select a colour for my options within a select data type, but the popover keeps closing, and the colour is not set.

**To Reproduce**
1. Add a single select column to an Internal DB table
2. Add a couple of options
3. Try to set the colour of one of the options -> see that it just closes the popover and does not set the colour.

**Expected behavior**
I should be able to set the colour of my options for a single select data type

**Screenshots**

https://github.com/Budibase/budibase/assets/30199063/39edb531-3600-4e99-bea4-6bca239cf2ed

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave

**Comment by aptkingston** [comment]
This has already been fixed and merged to master - I'll be kicking off a release very shortly to push it out :)
