### ISSUE TITLE
Iframe spam without display

### ISSUE THREAD

**Issue by mad4me** [Budibase/budibase#13799]
**Checklist**
-  [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.27.3
 
**Describe the bug**
When entering any binding configuration menu, before it loads, the cursor and the menu itself starts to lag and if we check the dev tools, its possible to see the crazy spam of `display: none;` iframes. 

As far as I know, the bug appears only in the bindings menu, and Its the most I use so it can be pretty anyoing, it loads slowly, the cursor bugs out or the menu may close by itself in the middle of the opening.

**To Reproduce**
1. Open the dev tools
2. Open any binding configuration menu
3. Iframe spam ._.

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/54853465/6942fb5a-925a-437a-b9dd-6047078e12a3)

**Desktop**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 125.0.6422.78

**Comment by aptkingston** [comment]
Thanks for spotting this. I'd actually experienced this lag myself and had never noticed that this weird iframe spam was the reason. I'll get this fixed!
