### ISSUE TITLE
The UI freezes when a table is empty and there's a button added to said table

### ISSUE THREAD

**Issue by bjornclauw** [Budibase/budibase#13797]
**Hosting**
Selfhosted docker  v2.27.4

**Describe the bug**
When I have a table that has 0 rows (either by filtering or empty) and there is a button added to this table, the whole UI freezes (in the builder and also the released app)

**Reproduce**
Create a new app with example data
Add a table, add a button to this table
Add a filter to the table that is guaranteed to not return any results

**note**  `Return all table rows when filter is empty` does not seem to function correctly in a table (returns no rows)

**Comment by Reftek85** [comment]
oh my god! I was thinking I was going crazy!

I updated my version this PM, 
on an empty table, when the table finish loading, it freeze the UI, in the builder and the App, I cannot push create customer button in my main view in the app once it is loaded empty. cannot open a side panel. it is frozen....
version 2.27.4
budibase  hosted on budibase.app cloud instance.

**Comment by aptkingston** [comment]
Thanks @bjornclauw and @Reftek85. I have a PR up to fix this which I'll get deployed ASAP.

**Comment by raventechsaigon** [comment]
I's getting usual UI FREEZES and crashes as well.  With multiple tables and dataprovider on on screen.  And yes I've encounter this behavior for an empty table.

**Comment by aptkingston** [comment]
@raventechsaigon if you have a different, reproducible scenario that causes the UI to freeze then please open another issue with more details so that we can look at it. Thanks.
