### ISSUE TITLE
Unable to load grid - Invalid Time Value

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#13802]
Issue raised as a result of discussion https://github.com/Budibase/budibase/discussions/13798 - Have offered to possible fixes/workarounds

**Checklist**
- [`Y`] I have searched budibase discussions and github issues to check if my issue already exists

Related:
- https://github.com/Budibase/budibase/issues/13552
- [Linear **BUDI-8195**](https://linear.app/budibase/issue/BUDI-8195/budibase-unable-to-load-grid-when-using-external-postgres-database)
- https://github.com/Budibase/budibase/issues/9050

**Hosting**

- Self
  - Method: Cloud
  - Budibase Version: 2.27.3
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
_"Since I update my app to version 2.27.3. I've got problems with my tables containing a timestamp type of column (using a SQLServer as datasource). I tried to revert the to the former version, but the issue still remains.
Displaying the table in the data section leads to the message "There was a problem loading your grid - Invalid time value"
The preview of the screen is also frequenly showing the message " Invalid time value"
I sure need the timetamp field in my tables for some reason. So the app is now ruined and no way out?
Any help would be appreciated."_

**Waiting for user to respond with more specifics, will update**

.
.

**To Reproduce**

**Expected behavior**

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

**Comment by raventechsaigon** [comment]
We use mySQL.  And get this error when time date value is 0000-00-00  instead of NULL.
Data field must be null and non zero
