### ISSUE TITLE
SAVE ROW will not post new record with FORM as DATASOURCE

### ISSUE THREAD

**Issue by raventechsaigon** [Budibase/budibase#13816]
**Checklist**
- [ X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud
  - Tenant ID: ship2vietnam

**Describe the bug**

All last week our app worked fine.

All the sudden to day users reported that new records could not be submitted.
WE checked and tested.  All new 'SAVE ROW' do not honor the datasource form.

We have to explicitly set each column and bind to a form field in order to CREATE.

**Comment by raventechsaigon** [comment]
We solved our own bug.

For some reason our TABLE SCHEMA in BB all fields got defaulted back to REQUIRED.
Prior to this everything worked fine. Can't explain how or who did it.  
Table Field validation and form validation are colliding.

There is no error message for form validation errors if you SAVE ROW with a form as a Datasource.

**Comment by aptkingston** [comment]
Forms do show validation for required fields, assuming you are actually validating your form with a "validate form" action.

![image](https://github.com/Budibase/budibase/assets/9075550/638d0591-2425-40fa-ad9d-909eb51fe1ef)

It sounds like this was a configuration issue, but that's good to hear that you solved your own issue.
