### ISSUE TITLE
Cannot save time value to internal DB

### ISSUE THREAD

**Issue by mohagan9** [Budibase/budibase#13839]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: rspb.budibase.app

**Describe the bug**
I cannot save time values to the internal DB.

**To Reproduce**
1. Add date/time columns to an internal Budibase DB
2. Create a form with time only fields for these date/time columns
3. Try to save data
4. See in network tab validation constraint being hit

**Expected behavior**
I should be able to save time only date/time values to the internal Budibase DB.

**Screenshots**
<img width="505" alt="Screenshot 2024-06-02 at 23 08 56" src="https://github.com/Budibase/budibase/assets/30199063/f92fc780-b4cc-45bc-b59d-a168e3200d52">

<img width="618" alt="Screenshot 2024-06-02 at 23 09 24" src="https://github.com/Budibase/budibase/assets/30199063/34f7747a-bbb3-478c-9574-40deec9d7506">

<img width="1027" alt="Screenshot 2024-06-02 at 23 11 41" src="https://github.com/Budibase/budibase/assets/30199063/1020b710-2091-47b9-8543-fb999a8b5864">

<img width="348" alt="Screenshot 2024-06-02 at 23 12 45" src="https://github.com/Budibase/budibase/assets/30199063/5032def9-4574-4b75-b045-e329ab8f703e">

<img width="321" alt="Screenshot 2024-06-02 at 23 14 31" src="https://github.com/Budibase/budibase/assets/30199063/22d71b61-8e26-49a6-90d0-627c10893616">

**Additional context**
This definitely worked fine a month ago.

**Comment by ConorWebb96** [comment]
Re-create app export here.

[date test-export-1717503810894.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/4378b494-0171-4fd1-8bfd-33671c3206f7/bc5fe38a-e2c0-4f22-a1b2-fab04fdf7c2c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC80Mzc4YjQ5NC0wMTcxLTRmZDEtOGJmZC0zMzY3MWMzMjA2ZjcvYmM1ZmUzOGEtZTJjMC00ZjIyLWExYjItZmFiMDRmZGY3YzJjIiwiaWF0IjoxNzE3NTAzOTM5LCJleHAiOjMzMjg4MDYzOTM5fQ.kfEZLeA7k4cHnPJdJ4Frd8oGjzmEXhwkdXjdhg0Lv-A)
