### ISSUE TITLE
Relationship option picker showing blank value

### ISSUE THREAD

**Issue by timtandio** [Budibase/budibase#13836]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: <tenantId>  icohs.budibase.app

**Describe the bug**
After creating the second relationship column, when trying to pick the item, it shows blank

**To Reproduce**
1. create 2 relationship column

**Screenshots**
first relationship column showing data just fine.
![image](https://github.com/Budibase/budibase/assets/166788865/5b6f255a-8346-4d71-b3e5-94df6b22d0e9)

second relationship column showing blank data to pick.
![image](https://github.com/Budibase/budibase/assets/166788865/df933d3d-0d4b-4372-9611-31e9a74834f8)

  
**App Export**
[My app-export-1717194692438.tar.gz](https://github.com/user-attachments/files/15519249/My.app-export-1717194692438.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 125.0.6422.114 (Official Build) (64-bit)

**Comment by aptkingston** [comment]
We use the primary display column as the value to show when choosing related rows. Blank values will mean you've chosen a primary display column that is empty for some rows, which I wouldn't recommend choosing.

We enforce a required restraint on the primary display column, but you're still able to change the primary display column to any column you want, including those which empty values.

Basically all you need to do is either change your primary display column into something that every row has, or add those missing values.

But there's no bug here, so I'll close this off.
