### ISSUE TITLE
BB UI lags and slows at certain times

### ISSUE THREAD

**Issue by raventechsaigon** [Budibase/budibase#13840]
**Checklist**
- [ x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud
  - Tenant ID: ship2vietnam

**Describe the bug**
everyday around 1-3 pm UTC Asia/Ho_Chi_Minh

BB crawls to a snails pace...UI and App takes forever to load and refresh..

**Comment by shogunpurple** [comment]
@raventechsaigon this isn't actionable. Please raise a new issue and follow the provided bug template. Closing
