### ISSUE TITLE
Button group action not  returning execute query result

### ISSUE THREAD

**Issue by jcyh0120** [Budibase/budibase#13855]
**Hosting**

- Self
  - Method: docker image
  - Budibase Version: 2.19.3.

**Describe the bug**
When using button group, setting action on a button with execute query not returning the result.

**To Reproduce**
1. Add a paragraph and bind the value to a state "result"
2. Add a button group
3. Click action of a button
4. Add execute query action
5. Add set state action with query result to State.result
6. Preview and test

**Expected behavior**
The paragraph should display the query result when clicking the button

When using just a single button component, everything works fine.

**Comment by ConorWebb96** [comment]
Can you include what version of Budibase you are using + hosting method please.

**Comment by ConorWebb96** [comment]
Can you update your version of Budibase? You are 1 minor version behind a lot of patches behind.

I've just checked on the latest version and this seems to work. Closing for now, if you can recreate on the latest drop a message here and this issue can be re-opened.
