### ISSUE TITLE
Glitch while editing resized number cell in Grid

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#13878]
Latest

to recreate
create an internal db table
create a number column
resize it ( make it smaller than the default )
click to add / edit record 

https://github.com/Budibase/budibase/assets/80512170/d6de0e0f-8c27-47c2-954c-c3c927c47cb3

**Comment by aptkingston** [comment]
Looks like Firefox only, and also happens with text columns! Thanks @poirazis, pushing a fix.
