### ISSUE TITLE
Poor responsiveness and high CPU load

### ISSUE THREAD

**Issue by thinkbig1979** [Budibase/budibase#13932]
### Discussed in https://github.com/Budibase/budibase/discussions/13928

<div type='discussions-op-text'>

<sup>Originally posted by **thinkbig1979** June 12, 2024</sup>
I've built a CRM in self-hosted Budibase (docker compose), 
Version: 2.28.4
Using a local Postgres DB in the stack as primary data provider.
My users are complaining - and rightly so - about poor responsiveness of the system.

Every time you go to a different page in the CRM, the the Worker and CouchDB containers max out the CPU for about 10 seconds while the page loads. The logs show tons of calls to couchDB when changing pages, even if I'm only loading a single view of a single datasource, e.g. my contacts table.
 
Looking at the logs, I cannot tell if Redis is being used at all.

Any suggestions?

**Comment by aptkingston** [comment]
Lets use the discussion for now until we verify what's going on 👍
