### ISSUE TITLE
Group and Calculate feature missing from View

### ISSUE THREAD

**Issue by timtandio** [Budibase/budibase#13935]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: <tenantId>  qis.budibase.app

**Describe the bug**
there is no option to group and calculate the view.

**To Reproduce**
1. create table (i use sample data table)
2. create view
3. see error

**Screenshots**
no group and calculate
![image](https://github.com/Budibase/budibase/assets/166788865/b47743e5-bfde-4560-8cbd-91e6b69f7723)

group and calculate view appear when we use budibase app template, for example IT Ticketing System Template here https://budibase.com/business-apps/templates/open-source-ticketing-system/
![image](https://github.com/Budibase/budibase/assets/166788865/aeb0e428-0f01-482d-967a-5c40a45eb1d6)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 125.0.6422.114 (Official Build) (64-bit)

**Comment by ConorWebb96** [comment]
Hey @timtandio,

If you are using the internal database this functionality was removed over a year ago for performance reasons. It might be coming back sometime later on this year.

If you are using an external database. You likely can write a custom query that does this for you. 

Changing this to an enhancement as its not a bug.

**Comment by timtandio** [comment]
> Hey @timtandio,
> 
> If you are using the internal database this functionality was removed over a year ago for performance reasons. It might be coming back sometime later on this year.
> 
> If you are using an external database. You likely can write a custom query that does this for you.
> 
> Changing this to an enhancement as its not a bug.

I see, thanks for clarifying. That feature is really great and helps a lot. I really hope it will be added back soon.

Cheers

**Comment by timtandio** [comment]
> Hey @timtandio,
> 
> If you are using the internal database this functionality was removed over a year ago for performance reasons. It might be coming back sometime later on this year.
> 
> If you are using an external database. You likely can write a custom query that does this for you.
> 
> Changing this to an enhancement as its not a bug.

I see, thanks for clarifying. That feature is really great and helps a lot. I really hope it will be added back soon.

Cheers
