### ISSUE TITLE
unable to select fomula in budi table

### ISSUE THREAD

**Issue by thorinas** [Budibase/budibase#13938]
Hi, 

Im unable to select Formula from the drop down list when making a table, it appers to crash the site. 
![image](https://github.com/Budibase/budibase/assets/71787922/2c59ee60-6bd2-41ad-96d0-7b4d6dd04b69)

im self hosting if that helps.

**Comment by ConorWebb96** [comment]
Hey @thorinas,

You should be able to scroll that list in the screenshot you've posted. Can you try that and see if the formula option is there?

**Comment by thorinas** [comment]
Hi yes the list scrolls. But once I click on formula the screen freezes and I need to refresh the page. Once IV refreshed the page thier is no formula coulom.

**Comment by ConorWebb96** [comment]
Can you fill out the bug template?

You're missing a lot of key information here that would be included with the bug template. E.g. app version, self-hosted or cloud etc. I'd recommend updating to the latest version as I'm unable to replicate the issue you are describing on it.

**Comment by thorinas** [comment]
Will do.
