### ISSUE TITLE
Option to add 

### ISSUE THREAD

**Issue by byebb** [Budibase/budibase#13949]
**Describe the feature request**
Add a field for the OpenAI API Key in the automations dialog.

Currently, it is very difficult to find the required field where to add the info.

**Screenshots**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5dc7c460-0dd3-4772-823c-4ecfeddcad89/f8d2ae84-2705-4f59-993a-3a5a918eba69?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC81ZGM3YzQ2MC0wZGQzLTQ3NzItODIzYy00ZWNmZWRkY2FkODkvZjhkMmFlODQtMjcwNS00ZjU5LTk5M2EtM2E1YTkxOGViYTY5IiwiaWF0IjoxNzE4NjEwMTIwLCJleHAiOjMzMjg5MTcwMTIwfQ.JYTWugP-S-YhaOmuv_TmR8jOfFERO0yXsw67VDt1Q3E)

**Comment by andz-bb** [comment]
@byebb I think it's best to keep this as a global environment variable since it's only applicable on self host and can be reused - or is there a case where you need to use more than one OpenAI API key in an app?
