### ISSUE TITLE
Session not authenticated on public permissions

### ISSUE THREAD

**Issue by micahchoo** [Budibase/budibase#13954]
**Checklist**
- [ x ]  I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
->
- Cloud
  - Tenant ID: kundapura>

**Describe the bug**
It loads some pages which have just embeds, but not the components that use the datasource queries and throws the error "(12) Session not authenticated" . I'm using google sheets as the database, and I get 
```
A resource is blocked by OpaqueResponseBlocking, please check browser console for details. faviconUrl

[Client] HTTP 403 on GET:https://kundapura.budibase.app/api/queries/query_datasource_plus_aa376a48d9634a0cbe102ebbe122eff6_c56be0df5c554837b0854a82e8b094fe
	Session not authenticated
```
on the console

I have made all the screens Public and set read access to public on the manage access modal for the app.

**Comment by ConorWebb96** [comment]
Are any of the tables you use on the screen not set to public?

You have screen access restrictions and table read/write restrictions that your roles can be applied to. Make sure these are also set to public if your screen is public.

**Comment by micahchoo** [comment]
The tables were public but the queries weren't - I changed all those and it worked! . Thanks so much for the tip!
