### ISSUE TITLE
Not able to sync to Firestore

### ISSUE THREAD

**Issue by derrickshowers** [Budibase/budibase#13950]
I'm unable to read from my Firestore database after connecting successfully. I'm receiving an error:

```
{
    "message": "function () {\n            const temp = Object.assign({}, this);\n            if (temp.credentials) {\n           ...<omitted>... } could not be cloned.",
    "status": 400
}
```

**To Reproduce**

1. Connect a new Firestore database. See it is connected successfully.
2. Create a new query - something simple like read, collection name (I also tried a collection that doesn't exist and it's successful but empty, which I would expect, so it's correctly connected to the database)
3. Tap "Run Query" to "Save"
4. See error (above)

**Expected behavior**
Error not to occur and records to be retrieved

**Screenshots**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/3512f72e-4283-4894-ab41-aa383b30251d/e97029dd-24a4-49d4-a63e-57670ff3c4f9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8zNTEyZjcyZS00MjgzLTQ4OTQtYWI0MS1hYTM4M2IzMDI1MWQvZTk3MDI5ZGQtMjRhNC00OWQ0LWE2M2UtNTc2NzBmZjNjNGY5IiwiaWF0IjoxNzE4NjEwMTEwLCJleHAiOjMzMjg5MTcwMTEwfQ.h-1RFiNS-\_6IbIyWPvdQaPL5S-twoah_JEkTXpi7MLk "=1586x")

**Comment by derrickshowers** [comment]
One quick update, this appears to only happen for collections that have references (which is most of my collections)

**Comment by STAR-173** [comment]
Hey @derrickshowers,
Was looking into the issue but wasn't able to recreate it. Can you provide some additional info about the project and some more screenshots
