### ISSUE TITLE
Request:: It would be nice to have this added when using tables.

### ISSUE THREAD

**Issue by neojigi** [Budibase/budibase#13983]
When the table component is used alone, you can choose whether you want to be able to add / edit / delete from the table itself.

However, when used in conjunction with a data provider, the above three options are no longer visible.

It would be much more usable if the above 3 options could be selected even when used with data provider!

**Comment by aptkingston** [comment]
Hey @neojigi. Just wondering why do you need to use a data provider with your table? Can you not just use your table as the data setting for the table?

**Comment by neojigi** [comment]
Oops...

I was under the impression that there was no other way to do things like filtering, binding, etc. than with a data provider.

It's only now that I've realized that when I open the table by itself, I can see the filtering options and binding within it.

Thanks for the advice :)

**Comment by aptkingston** [comment]
No problem! I think we should probably remove the data provider option, because you aren't the first person to do this. Now that the table is fully self contained and doesn't need a data provider, there really isn't a use case for hooking it up to one.

**Comment by neojigi** [comment]
p{margin-top:0;margin-bottom:0}
    


    
I looked at the table component again with your suggestion and it does what I want without the data provider!
I'm really impressed with how budibase is improving day by day.
Thank you.
Daum 메일앱에서 보냈습니다.
 

--------- 원본 메일 ---------
보낸사람:Andrew Kingston ***@***.***>
받는사람:Budibase/budibase ***@***.***>
참조:neojigi ***@***.***>,Mention ***@***.***>
날짜:Thu Jun 20 20:18:18 GMT+09:00 2024
제목:Re: [Budibase/budibase] Request:: It would be nice to have this added when using tables. (Issue #13983)


No problem! I think we should probably remove the data provider option, because you aren't the first person to do this. Now that the table is fully self contained and doesn't need a data provider, there really isn't a use case for hooking it up to one.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Budibase/budibase/issues/13983#issuecomment-2180426884",
"url": "https://github.com/Budibase/budibase/issues/13983#issuecomment-2180426884",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
