### ISSUE TITLE
Helper functions and bindings selected from the popover menu add an additional space, breaks the bindings

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13991]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.29.0
  - App Version: 2.29.0

**Describe the bug**
When adding bindings to a formula column in handleBars additional spaces are added to any bindings after using the suggestion popup. This causes the bindings to not run correctly.

**To Reproduce**
1. Go to any table
2. Create a simple formula column add 2 numbers together
3. Select your helper function (add in this case)
4. Add your select table bindings to add together
5. See issue the binding looks like: `{{  add  number1  number2 }}`

**Expected behavior**
When quickly adding the bindings + helpers additional spaces shouldn't be added and it should just work right away.

**Screenshots**
![new_recording_-_6_20_2024,_4_02_58_pm (720p)](https://github.com/Budibase/budibase/assets/126772285/fa7cfcb2-61b6-4f54-9b83-b8252bc778c9)
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Comment by mike12345567** [comment]
Fixed in: https://github.com/Budibase/budibase/pull/14018
