### ISSUE TITLE
Receiving "A column has been specified more than once in the order by list. Columns in the order by list must be unique."

### ISSUE THREAD

**Issue by wcom939** [Budibase/budibase#14002]
**Checklist**
- [X ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: dashingdanstrains

**Describe the bug**
After upgrading to the latest version reads no longer work and instead produce the error "A column has been specified more than once in the order by list. Columns in the order by list must be unique." Backend is Azure SQL

**To Reproduce**
1. Create a standard form application using Azure SQL
2. Add a table
3. attempt to modify table data or view anything

**Expected behavior**
Should work, view data, edit table data, etc.

**Screenshots**
<img width="901" alt="image" src="https://github.com/Budibase/budibase/assets/16446451/83a3366d-d680-42a6-b469-68b51ad97f5b">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest

**Additional context**

**Comment by mike12345567** [comment]
This will be resolved in the next release, fixed by: https://github.com/Budibase/budibase/pull/14008
