### ISSUE TITLE
unable to connect app (preview mode) in dev stack (next branch)

### ISSUE THREAD

**Issue by neoguet** [Budibase/budibase#1400]
**Describe the bug**
Hello,
I try to build the dev stack but when i try to connect to my app, i can't  login in preview mode.
I haven't try to deploy my app (and i don't know if it's possible in dev stack)

**To Reproduce**
1. clone repository (next branch)-> OK
2. command yarn and yarn bootstrap ->  OK
3. command yarn  build -> OK
4. command yarn dev  ->  OK
5. Launch the builder (http://localhost:10000/builder) ->OK
6. create first user ( test@test.com)  and connect to builder-> OK
7. create app and table -> OK
8. launch preview  (I see the login form) -> OK
9. fill fields with test@test.com and test -> OK
**10. click on log in button -> KO** I stay on the login form.
When i look to the dev tools I see the POST to http://localhost:10000/api/admin/auth and the response is 200 with a json : 
`{"user":{"_id":"us_7e8117eb3dea4d45a16a867b1bc3c3a9","_rev":"2-6584e6fbe9da1eca78b26ab144864dfb","email":"test@test.com","roles":{"app_4f7cbbffa9ed49ef93b27fefa9468990":"ADMIN"},"builder":{"global":true},"status":"active","roleId":"PUBLIC"}}`

**Expected behavior**
i don't know if i made a mistake but  i expected to view the home page of my app.
maybe this issue is related to the new user management of the next branch ?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser firefox
 - Version next branch

**Additional context**
sorry my English is so bad and i hope my issue is understandable

**Comment by shogunpurple** [comment]
@neoguet - the `next` branch is currently under heavy development. Especially around auth. We would not recommend trying to use the `next` branch until it is released to the community.

I will look into the issue though, and try and recreate this as it should work. This does look like a bug.

Thanks!

**Comment by neoguet** [comment]
Hi,
thanks for your response.
I know the `next` branch is under development. I will want to test this because I follow the #github channel on discord and I see you work very hard to improve budibase (users management,refactoring, UI improve, email template, ...).I think you go  in the right way and I would like contribute to the evolution on budibase. 

Today, in my job, I work with the rollbase plateform (now the name is Infinite Blue Platform). And this platform is very  powerful and customizable,  but his main fault is that not opensource. I hope to reproduce my recruiting  app in budibase and more.

At the moment, I've add in my fork a "validation format for text field" based on regex's expression. This permit to add some preset validations like email, IP, URL, ... or custom regex. This trick is based on the "constraint" present in "tables documents" like required field. But after merge to the last next branch, I could not test because authentication don't work.
And that why i wrote this issue. Obviously i can wait the next release.



 .
