### ISSUE TITLE
[ Builder ] - Property type "datasource" - Sort options alphabetically 

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#14029]
When the list of available datasources start to grow, it gets difficult to find the one you want.
I would suggest they are sorted alphabetically, and possibly adding some search to the dropdown ?

![Screenshot 2024-06-26 at 5 31 31 PM](https://github.com/Budibase/budibase/assets/80512170/b84ec287-5904-4860-a0d2-fa053231f20c)

**Comment by aptkingston** [comment]
This has been implemented thanks to @andz-bb :)
