### ISSUE TITLE
Filtering with the contains operator throws an error when using a multi user column on external data sources.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#14042]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.29.3
  - App Version: 2.29.3

**Describe the bug**
Whenever setting up a filter on an external data source e.g. Postgres and error is thrown when selecting a user to filter against. with the operator `contains`: `Cannot assign to read only property '0' of string 'us_6bab9053897744ea8444da560b7aef3d'`

**To Reproduce**
1. Add a multi user field to any external data source
2. Go to the design screen
3. Add a table component
4. Setup filtering against the new multi-user column
5. Make sure to select the contains operator
6. Select a user
7. Save the filter
8. See error

**Expected behavior**
This should work with this operator instead of throwing an error.

**Screenshots**
<img width="1512" alt="Screenshot 2024-06-28 at 11 03 52" src="https://github.com/Budibase/budibase/assets/126772285/10197195-c317-40ed-8d41-46aa661d8b02">

**Comment by ConorWebb96** [comment]
User filtering as a whole may need looked at with form fields. If I try to get users with a multi-select picker and filter on the select values of this field. All of the operators throw the same error as the one shown in the screenshot above.

Is empty + is not empty are the only ones working in the list.

<img width="1418" alt="Screenshot 2024-06-28 at 11 43 13" src="https://github.com/Budibase/budibase/assets/126772285/45af40e1-0725-4d88-8dfe-92e8213096d2">

**Comment by mike12345567** [comment]
Fixed in: https://github.com/Budibase/budibase/pull/14059, release 2.29.5
