### ISSUE TITLE
Looping in Automations - "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14066]
**Checklist**
- `[Y]` I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self & Cloud

**Describe the bug**
When passing an array to a looping-step in automations, we get the error "Cannot convert undefined or null to object". When we remove the looping function, and index the array instead, we get the desired outcome.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a table
2. Create an automation that takes an array and loops over it to write to a table
3. Run test

**Expected behaviour**
Expect looping function to loop over array from previous steps and write to the table.

**Screenshots**
Looping version simply will not run - no test results to show
![image](https://github.com/Budibase/budibase/assets/39269380/ba19f3f1-3399-49f5-98a9-4e89ee51632d)
 
 Non-looping version runs and writes the first element in the array to the table (see the variable in the create row step)
![image](https://github.com/Budibase/budibase/assets/39269380/02dd0642-446c-4dc5-840d-1eeb96fae415)

JAM Screencap: https://jam.dev/c/e39c669b-27e8-4d71-a651-40d202c8b116
Note: Test results/logs seen in the JAM are stale, leftover from the previous (successful) runthrough)

**App Export**
[Automation Looping Bug-export-1719909153191.tar.gz](https://github.com/user-attachments/files/16064706/Automation.Looping.Bug-export-1719909153191.tar.gz)

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: chrome

**Additional context**

**Comment by LMPexplorer** [comment]
Same problem here, i had an automation that was working well and i got this error while looping too since today. Even looping with simple value like "1,1,1,1" doesn't work.

**Comment by imnaveenk** [comment]
+1

**Comment by mike12345567** [comment]
Fixed in: https://github.com/Budibase/budibase/pull/14083
