### ISSUE TITLE
Unable to create documents in CouchDB datasource

### ISSUE THREAD

**Issue by g-serge** [Budibase/budibase#14079]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.29.6
  - Couchdb images versions tested : budibase/couchdb & ibmcom/couchdb3 (latest version as of 2024-07-02)

**Describe the bug**
It's not possible to create a document using CouchDB datasource with a Create query.

**To Reproduce**
1. Go to the data section of an app and add a CouchDB datasource
2. Create a new query to your CouchDB datasource
3. Select "Create" in Function dropdown
4. Add a valid JSON document inside Query text field
5. Click on "Run query" button
6. Observe error "Query Error: this.client[command] is not a function"

**Expected behavior**
The query is run and a document is created.

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/145403199/d27506d5-eaf5-41fb-bdad-001f9ee64f3f)

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox 127.0.2 (64 bits) / Chrome

**Additional context**
Clicking on "Run query" button triggers a request to "/api/queries/preview" wich fails with the following response : 
```
{"message":"this.client[command] is not a function","status":400}
``` 
The datasource is the same CouchDB server used by Budibase.

**Comment by mike12345567** [comment]
This issue will be fixed in the next release (2.29.13)
