### ISSUE TITLE
Multiple 1-many relationships between 2 tables break correct visualization

### ISSUE THREAD

**Issue by mrktt** [Budibase/budibase#14071]
Datasource is a SQL Server database
The schema is like this

tbBusiness
   - ID
   - Name

tbInvoices
  - ID
  - ...
  - IDBusinessSeller
  - IDBusinessBuyer

IDBusinessBuyer and Seller are two foreign keys pointing to the same primary keys in tbBusiness

If I define a relationships between one filed in tbInvoices and tbBusiness (which one is indifferent) the visualization in data or in views is correct, I see the display name of tbBusiness
If I add the second one both cells start to showup empy in visualizations, even if the search shows the correct list of display name.

If I copy the data of tbBusiness to tbBusiness2 and repeat the creation of relationships all works by design

**Comment by ConorWebb96** [comment]
Hey @mrktt,

Closing please fill out the bug template that includes all the relevant information we ask for. 

Thanks!
