### ISSUE TITLE
I've tried to delete a column that type: Relationship, but there is no option to do so. How do I delete an existing relationship column?

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1408]
I've tried to delete a column that type: Relationship, but there is no option to do so. How do I delete an existing relationship column?
<img width="334" alt="Budibase_Builder" src="https://user-images.githubusercontent.com/53414466/115955304-ae9c7800-a4c3-11eb-9046-988ec450101e.png">

_Originally posted by @Jake-qp in https://github.com/Budibase/budibase/discussions/1407_

**Comment by shogunpurple** [comment]
Good catch! Fixed in my branch.
