### ISSUE TITLE
Modal component closes on 'click outside', ignoring the settings

### ISSUE THREAD

**Issue by bjornclauw** [Budibase/budibase#14115]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker
  - Budibase Version: 2.29.14

**Describe the bug**
The option "ignore clicks outside" is not working for the modal component. It closes when clicked outside, regardless of the chosen setting.

![image](https://github.com/Budibase/budibase/assets/32811735/ce38ea91-cfc3-4674-a122-a4cc4e57a93c)

**Comment by ConorWebb96** [comment]
Closing this has been done and is now available on `2.29.16` +
