### ISSUE TITLE
Not being able to save form components

### ISSUE THREAD

**Issue by legaljustus** [Budibase/budibase#1412]
**Describe the bug**
When I try to save form components (I think mostly after changing form schema) the whule UI becomes unresponsive. I can't click anything, it only shows a yellow border around buttons. If i restart budibase it's fine again 

**To Reproduce**

1. Go to a form with a submit button
(1.b change the schema of the form)
2. Try to change the submit button actions / or a dynamic field
3. Can't save the actions / field and budibase freezes
  
**Expected behavior**

Save the action and close the bottom screen part

**Screenshots**

https://user-images.githubusercontent.com/83215912/116071106-ba3b9a80-a68d-11eb-9943-933154f803a7.mp4

In the video it stopped before it showed the define actions screen, normally it does show this. 

**Desktop (please complete the following information):**
 - Windows 10 Version	10.0.19041 Build 19041

**Comment by shogunpurple** [comment]
Will be resolved in this weeks release :+1:Thanks for reporting.
