### ISSUE TITLE
"Is in" filter broken

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14127]
**Checklist**
- `[Y]` I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Demonstrated on Self-host, also encountered on Cloud

**Describe the bug**
When filtering with "Is In", any more than one element in the array will break the filter and return no rows, when "return all rows if filter is empty" is set.
![image](https://github.com/Budibase/budibase/assets/39269380/f0dabb8c-ec0c-4b08-b16b-b78b6e3f9ab2)

**To Reproduce**
Steps to reproduce the behaviour:
**In the Design Tab**
- Add a data provider set to Employees
- Add a form with a multi-select picker, set to First Name
- Add a table,  set to Employees, filter on `First Name` `Is In` `binding` `{{ New Form.Fields.employees }}`
- Select a single option - table will return 1 row. 
- Select more than one option - table will return zero rows.
- Select no options - table will return all rows

**In the Data tab**
- Use sample data Employees
- Create View, add filter
- Filter on `First Name` `Is In` `value` `["Brayden", "Suzy"]`
- Alternatively `Brayden, Suzy`, `Brayden,Suzy`
![image](https://github.com/Budibase/budibase/assets/39269380/5e985251-b594-4093-998c-608a9453374f)

**Expected behavior**
Filter should display any checked names in the table below. In this example the only scenario in which no matches would be found is when no names are checked. Filter behaves as expected for a single name, but fails when multiple names are checked.

**Screenshots**
Jam Screencap - https://jam.dev/c/9fe8bec5-a30b-47c0-a8a8-dd484968666e
  
**App Export**
[Broken Filters July 9th-export-1720516438523.tar.gz](https://github.com/user-attachments/files/16141021/Broken.Filters.July.9th-export-1720516438523.tar.gz)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version Version 126.0.6478.127 (Official Build) (arm64)

**Additional context**
This issue is extracted and sanitised from a support ticket.

**Comment by mikesealey** [comment]
Issue also raised in: https://github.com/Budibase/budibase/discussions/14122

**Comment by ConorWebb96** [comment]
Fixed, merged and released [here](https://github.com/Budibase/budibase/pull/14128).
