### ISSUE TITLE
When `return all table rows` is selected the Is in filter returns nothing instead of all rows

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#14136]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.29.16
  - App Version: 2.29.16

**Describe the bug**
Data isn't returned for the `is in` filter whenever the value is empty, when the `return all table rows` is selected.

**To Reproduce**
1. Use the below app export
2. Go to the home screen
3. See currently no results are returning even though the filter value has been left blank
4. Switch to equals and save it will return results

**Expected behavior**
All records should be returned if no value is present.
  
**App Export**
[is in test-export-1720682926923.tar.gz](https://github.com/user-attachments/files/16173014/is.in.test-export-1720682926923.tar.gz)

**Comment by adrinr** [comment]
Fixed in release [2.29.18](https://github.com/Budibase/budibase/releases/tag/2.29.18)
