### ISSUE TITLE
Export attachments

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1413]
Raised via discussion: https://github.com/Budibase/budibase/discussions/1411

Would like the ability to transfer a file attachment to another platform.

Potential options
- use minio to serve the file up to various external sources - probably the simplest and most universal
- make  it possible to send file from a webhook with a multipart body (an attachment in this case) and some way to store a multi-part response back into a row

At the moment, attachments are stored as arrays. If using within automations, we would need a way to iterate the attachments, or reference items in the array e.g. `row.attachmentsColumn[0].url`

**Comment by cngi1** [comment]
I have a current project that requires sending a file.  Please add this functionality.
[https://github.com/Budibase/budibase/discussions/5511#discussion-4023028](https://github.com/Budibase/budibase/discussions/5511#discussion-4023028)

**Comment by marco-santulli** [comment]
bump
