### ISSUE TITLE
Allow text wrapping in table cell/column

### ISSUE THREAD

**Issue by IvanDrag0** [Budibase/budibase#14161]
**Describe the feature request**
Currently, when adding text to a cell in Budibase, if the column is narrower than the text, Budibase cuts off the text. Budibase should allow text wrapping of the text to allow the user to show more text than just the column width of one line.

**Comment by aptkingston** [comment]
Hi @IvanDrag0. We offer this functionality already, by letting you change the height of your rows:
![image](https://github.com/user-attachments/assets/e8d5451b-f63f-4459-9bc7-2d57953eacc3)

If you increase the height then you'll have more room to show more lines of text:
![image](https://github.com/user-attachments/assets/3c4cd262-ccaf-4f5a-8e4c-c60e6bcaa951)

**Comment by ConorWebb96** [comment]
Closing this feature request as the functionality is already in the table component.
