### ISSUE TITLE
App not responsive after placing chart

### ISSUE THREAD

**Issue by CredoSoftware** [Budibase/budibase#1417]
budibase becomes unresponsive when I place a chart on my app and choose a view to be the datasource. Funny enough, nothing happpens when i click any of budibase's links "design, data...etc."

**Comment by joebudi** [comment]
hey @credotechnologies . Could you refresh the builder - ctrl R / cmd R

**Comment by credotechnologies** [comment]
I tried it a couple of times but i still get the same result. The software only works when i delete the view completely as if the view i created is causing the unresponsive behavior

**Comment by aptkingston** [comment]
Could you open dev tools (F12) and screenshot the error in the console? Also it would help if you could screenshot your chart settings and the table showing the view you're using.

**Comment by credotechnologies** [comment]
Nothing happens when i hit F12 and unless I delete the view, I can't view the graph settings because budibase becomes non-responsive.

**Comment by aptkingston** [comment]
Alright then how about deleting the view so that you are able to delete the graph, then try setting it up again from scratch. If you do this with dev tools open already then you'll be able to see any errors if they happen again.

**Comment by aptkingston** [comment]
Assuming this is resolved via the new data provider architecture being released today. If any other issues arise please open a new issue.
