### ISSUE TITLE
Data is not showing after switching from table to view

### ISSUE THREAD

**Issue by hrusmin** [Budibase/budibase#14189]
**Hosting**

- Cloud
  - Tenant ID: test43252 

**Describe the bug**
I created a view (Non Expired Employee) from a table called Employee.
The filter is expiry Date is greater than today.
I can see data from Data tab for that view, so the filter works fine.
Then I created a form that displays that Employee table and it works fine as well.
Then I switch that table to **[Non Expired Employee] view** .
I cannot see any result after that.

**To Reproduce**
1. Go to 'Settings'
2. Under Data Select **NonExpiredEmployee** view
3. Click Preview to run the app

**Expected behavior**
Can see all records that expiry date is later than today

**Screenshots**
![NonExpiredEmployee view](https://github.com/user-attachments/assets/e9b0011a-e15d-4577-8002-d7a1868c9b43)

  
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 126.0.2592.102

**Additional context**

**Comment by andz-bb** [comment]
hey @hrusmin, could you proide an app export please?

**Comment by hrusmin** [comment]
> hey @hrusmin, could you provide an app export please?
Hi @andz-bb 
The export is 28 MB (limit is 25MB), so I used 7zip to compress it as 7z. 
Since it does not allow me to upload 7z extension, so I changed it to Zip. 
Please change it to 7z extension it again.
[HR-export-1722515438441.tar.gz.zip](https://github.com/user-attachments/files/16456419/HR-export-1722515438441.tar.gz.zip)

**Comment by hrusmin** [comment]
Thanks
