### ISSUE TITLE
QUERY_THREAD_TIMEOUT not working as intended

### ISSUE THREAD

**Issue by A3DataSolutions** [Budibase/budibase#14205]
**Checklist**
- [ x ] I have searched budibase discussions and github issues to check if my issue already exists

Similar issue here [https://github.com/Budibase/budibase/discussions/13017](https://github.com/Budibase/budibase/discussions/13017)

- Self
  - Method: Docker Compose local
  - Budibase Version: 2.29.22

When setting the QUERY_THREAD_TIMEOUT environment variable, the query still times out at 15000 ms as opposed to the set time. This occurs when using a SQL Server backend.

**To Reproduce**
1. Go to the docker compose file
2. Insert an environment variable in the app service [name QUERY_THREAD_TIMEOUT: value: 200000]
3. Run a long query

**Expected behavior**
The query does not time out.

**Screenshots**
<img width="589" alt="image" src="https://github.com/user-attachments/assets/420e0ad7-f8e3-4043-961c-f050ed82457d">

**Desktop (please complete the following information):**
Windows, Edge

**Comment by ConorWebb96** [comment]
Hey @A3DataSolutions,

After making the change did you restart your containers? I've just double checked and this seems to be working fine. Heres some screenshots of my `.env` and `docker-compose` file. I'm on version `2.29.24`, I can't see any changes from the version you are on that would have removed this functionality.

.env
<img width="278" alt="Screenshot 2024-07-24 at 10 33 43" src="https://github.com/user-attachments/assets/d6b0e99a-450d-4b7f-bbc5-a6788e8c3275">

docker-compose
<img width="722" alt="Screenshot 2024-07-24 at 10 33 59" src="https://github.com/user-attachments/assets/97e3251d-01d2-4a4e-a271-b29382ef5cd7">

<img width="726" alt="Screenshot 2024-07-24 at 10 37 28" src="https://github.com/user-attachments/assets/34d7f128-1c57-44a9-b6fa-7430d7bd77d0">

**Comment by A3DataSolutions** [comment]
> Hey @A3DataSolutions,
> 
> After making the change did you restart your containers? I've just double checked and this seems to be working fine. Heres some screenshots of my `.env` and `docker-compose` file. I'm on version `2.29.24`, I can't see any changes from the version you are on that would have removed this functionality.
> 
> .env <img alt="Screenshot 2024-07-24 at 10 33 43" width="278" src="https://private-user-images.githubusercontent.com/126772285/351661439-d6b0e99a-450d-4b7f-bbc5-a6788e8c3275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDAzMTQsIm5iZiI6MTcyMTg0MDAxNCwicGF0aCI6Ii8xMjY3NzIyODUvMzUxNjYxNDM5LWQ2YjBlOTlhLTQ1MGQtNGI3Zi1iYmM1LWE2Nzg4ZThjMzI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNjUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWRjZGQ1MmRiOTdmMmE1MDE0YWJiZDE1ZDY1YzkxZTI4M2ZmYThhOGYzMDgxZGE3NTcwN2E3ZDM0OWY4ZTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z4pSQ1INvSqakts53NYlzLstnbW35CfCzSc5xW_Ks-0">
> 
> docker-compose <img alt="Screenshot 2024-07-24 at 10 33 59" width="722" src="https://private-user-images.githubusercontent.com/126772285/351661510-97e3251d-01d2-4a4e-a271-b29382ef5cd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDAzMTQsIm5iZiI6MTcyMTg0MDAxNCwicGF0aCI6Ii8xMjY3NzIyODUvMzUxNjYxNTEwLTk3ZTMyNTFkLTAxZDItNGE0ZS1hMjcxLWIyOTM4MmVmNWNkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNjUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTdlNWRjMmI0YmMyZDMyMWIyNWE4ZGM3ODJmYmMyOWIyZmMyZTc2NjdmMWI4NzhjZTlkZWY2NjA3M2FkMzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RYAZp7jQn6V1h3t0iImy9oetilcHiOVSzNr3y4p_qwY">
> 
> <img alt="Screenshot 2024-07-24 at 10 37 28" width="726" src="https://private-user-images.githubusercontent.com/126772285/351661913-34d7f128-1c57-44a9-b6fa-7430d7bd77d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDAzMTQsIm5iZiI6MTcyMTg0MDAxNCwicGF0aCI6Ii8xMjY3NzIyODUvMzUxNjYxOTEzLTM0ZDdmMTI4LTFjNTctNDRhOS1iNmZhLTc0MzBkN2JkNzdkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNjUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDUxZjZmMmYzM2Y2MmFhNjAwYzViNjllNzNjZjA0YTdhY2FkYWM4MTMxZDQyOWYyNmFhNzhhZmJjMjljMDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UBJQIrjxJbeQz5PsKOdHO2J1VOKeIMOnCCsxLoU9hcw">

Hi Conor, 

Thanks for writing yes, I restarted and even rebuilt the containers. I even exec'd into the container and I see the environment variable. In your setup what are you using as the database?

**Comment by ConorWebb96** [comment]
I believe the database I was using was Postgres, I'm happy to try this with the same database you are using.<br><br>Are you using a standard MySQL database or MSSQL?<br><br>When you say you are using docker compose, are you using the CLI or building straight from docker-compose?

**Comment by JayP718** [comment]
> I believe the database I was using was Postgres, I'm happy to try this with the same database you are using.<br><br>Are you using a standard MySQL database or MSSQL?<br><br>When you say you are using docker compose, are you using the CLI or building straight from docker-compose?

MSSQL and building straight from docker compose

**Comment by ConorWebb96** [comment]
Hey all, so this is exclusive to MSSQL.

Replicated and there is a fix [here](https://github.com/Budibase/budibase/pull/14296) for it. Once merged the env variables should work again.

**Comment by mike12345567** [comment]
This fix has been merged and will be in the next release of Budibase.
