### ISSUE TITLE
Add SLF4J provider to Clouseau

### ISSUE THREAD

**Issue by mingfang** [Budibase/budibase#14226]
https://github.com/Budibase/budibase/blob/d432a5ee4963e8204a78aa409a6a13ac74230e46/hosting/couchdb/Dockerfile#L117

Clouseau does not ship any log providers.
As a result logging is completely disabled.

Need to add a provider such as https://mvnrepository.com/artifact/org.slf4j/slf4j-simple/1.7.32
e.g. `wget https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar`

**Comment by mike12345567** [comment]
Hi @mingfang - we are actively in the process of removing the requirement for Clouseau, so I'm going to close this as its unlikely to be added, as we work on the move to utilise SQS (our new search engine based on SQLite).

**Comment by mingfang** [comment]
Do you have a timeframe for he move the SQS?

**Comment by mike12345567** [comment]
> Do you have a timeframe for the move the SQS?

It should be within the next few weeks - you can test the functionality today with the latest `budibase/couchdb` image by setting the `SQS_SEARCH_ENABLE` environment variable on the apps/worker containers.
