### ISSUE TITLE
Javascript - not able to use Buffer.from in new version

### ISSUE THREAD

**Issue by IchthysMaranatha** [Budibase/budibase#14223]
Using self hosted docker 2.29.20
Javascript errors out in Datasource, automations and screens when using Buffer.from
In earlier versions eg 2.5.2 was able to use Buffer.from, now errors out as 'Buffer is not defined'. Have the internal node modules been disabled from being used?

**Comment by IchthysMaranatha** [comment]
I guess, this must be a result of moving to isolated-vm from vm2 https://github.com/advisories/GHSA-4g2x-vq5p-5vj6
Any workaround for needed modules?

**Comment by andz-bb** [comment]
@IchthysMaranatha I think you're right. You can maybe pull the module in using [JavaScript snippets](https://docs.budibase.com/docs/snippets) which can be resused throughout the system. Snippets is a premium feature just as a heads up!

**Comment by IchthysMaranatha** [comment]
Can needed modules be added using ivm bundles? https://github.com/Budibase/budibase/tree/7ea7fc9d3aeebd798e9fd1b8dcf586f2c8267827/packages/server/src/jsRunner/bundles

**Comment by mike12345567** [comment]
Hi @IchthysMaranatha - can you utilise `Uint8Array.from` instead of `Buffer.from` to achieve the same result? Buffer is not a part of the standard JS library, as part of the move to isolated-vm we were not able to maintain all Nodejs libraries due to the inherent risk some of them pose (https://github.com/laverdet/isolated-vm/issues/89).

Uint8Array is however part of the standard JS lib and should be available.

**Comment by IchthysMaranatha** [comment]
I was actually trying to use it for jwt decoding as with JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString())
Will I be able to use Uint8Array.from for base64 decoding somehow? 

I used a workaround with the entire base64 decoding lib script

**Comment by IchthysMaranatha** [comment]
Thank you!
On a side note, not able to build proper working docker image with newer versions. After yarn, yarn build and building the single docker image, it builds successfully but the image does not result in a running container, complains about backend-core and other modules being missing. Compared with official docker image and saw that certain modules are copied over to index.js in worker and app which is not happening with the self build steps. Could you please provide steps for a running docker build?  Thanks.

**Comment by mike12345567** [comment]
> Thank you! On a side note, not able to build proper working docker image with newer versions. After yarn, yarn build and building the single docker image, it builds successfully but the image does not result in a running container, complains about backend-core and other modules being missing. Compared with official docker image and saw that certain modules are copied over to index.js in worker and app which is not happening with the self build steps. Could you please provide steps for a running docker build? Thanks.

Hi @IchthysMaranatha - there shouldn't be any further steps beyond running `yarn build:docker:single` at the top level of the directory - i've just tested this locally and it built a functional image.

**Comment by mike12345567** [comment]
Closing this issue as will be fixed in next release.

**Comment by IchthysMaranatha** [comment]
Built again and same issue, builds successfully but does not yield running container. Was building on Oracle cloud Ampere arm, so spun up a new local ubuntu 22.04 x86 vm and built again. Again successful build but image does not run successfully, complains of missing modules. While building noticed this
 >  Lerna (powered by Nx)   No access token found
   Nx will continue running, but nothing will be written or read from the remote cache.

Is your build using some cache or some kind of mixed pro-free environment that helps it to create a working container?

Steps followed
nvm installed node 20.16
npm install -g yarn jest lerna
docker installed
git clone https://github.com/Budibase/budibase.git
cd budibase
node ./hosting/scripts/setup.js
yarn
yarn build
yarn build:docker:single

**Comment by Foorack** [comment]
Ran into this issue today trying to use `Buffer.from(str, 'base64').toString('utf-8')` in a REST API Transformer...

Temporary workaround is moving the transform logic out to a separate "JavaScript" component, which indicates the polyfill context are not the same between the two... :(
