### ISSUE TITLE
Self host docker build issue - successful but container does not work

### ISSUE THREAD

**Issue by IchthysMaranatha** [Budibase/budibase#14260]
Hi @mike12345567 
This is in continuation of build issue mentioned in https://github.com/Budibase/budibase/issues/14223
As last comment was posted after issue closure, you might not have received it, am copy pasting it here again

Built again and same issue, builds successfully but does not yield running container. Was building on Oracle cloud Ampere arm, so spun up a new local ubuntu 22.04 x86 vm and built again. Again successful build but image does not run successfully, complains of missing modules in container log. While building noticed this

Lerna (powered by Nx) No access token found
Nx will continue running, but nothing will be written or read from the remote cache.

Is your build using some cache or some kind of mixed pro-free environment that helps it to create a working container?

Steps followed
nvm installed node 20.16
npm install -g yarn jest lerna
docker installed
git clone https://github.com/Budibase/budibase.git
cd budibase
node ./hosting/scripts/setup.js
yarn
yarn build
yarn build:docker:single

**Comment by mike12345567** [comment]
Hi @IchthysMaranatha - this should be resolved in latest `master` branch.

**Comment by IchthysMaranatha** [comment]
Thank you @mike12345567
