### ISSUE TITLE
Unable to use the User Field component

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14272]
**Checklist**
- `[Y]` I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self (Docker single)
- Cloud
  - Tenant ID: miketest1.budibase.app

**Describe the bug**
Adding a User Field component to a form shows the message "Add the field" setting to start using your component but there is no "Field" setting. Adding values to each of the other settings does not enable the User Field component.

**To Reproduce**
1. Add a form component
2. add a User Field component to the form
3. Give values for each of the settings (label, placeholder, default value, help text)

**Expected behavior**
Should be able to use the User Field component as part of the form

**Screenshots**
![image](https://github.com/user-attachments/assets/ef9dc48d-18c3-4f19-9d83-3fcfe617a0c6)

  
**App Export**
[User Field-export-1722333536773.tar.gz](https://github.com/user-attachments/files/16425833/User.Field-export-1722333536773.tar.gz)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 126.0.6478.127 (Official Build) (arm64)

**Additional context**

**Comment by aMacDawg** [comment]
what was the fix here? Encountering the same issue almost 6 months later.....
