### ISSUE TITLE
Adding relationship to a new column freezes Budibase

### ISSUE THREAD

**Issue by kameshsundaram** [Budibase/budibase#1434]
I created a table for Item and a table for Location. In Item table wanted to add a column for location and insert location from location table but Budibase freezes up when I do that. All I can do is exit. The location table was imported from CSV FYI.

**Comment by shogunpurple** [comment]
I'm unable to reproduce this one with the same data structure you mentioned. Could you possibly send over the CSV you uploaded, or even a short screencast of how you were able reproduce the problem? Thanks!
