### ISSUE TITLE
The app crashed after updating to version 2.30.3. I spent time building it, but it does not work after being exported and then imported back.

### ISSUE THREAD

**Issue by timtandio** [Budibase/budibase#14375]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud
  - Tenant ID: icohs.budibase.app

**Describe the bug**
All data is missing after updating to version 2.30.3, cloud version, the app crashed, and it cannot be imported back after being exported.
Cant delete the existing app either

**To Reproduce**
1. import the app
2. see the error

**Screenshots**
![image](https://github.com/user-attachments/assets/925167f9-0d85-4ee9-9443-0b7e5f78c7e7)
![image](https://github.com/user-attachments/assets/dbea6985-b6a5-4546-a941-6fcf41f20b86)
![image](https://github.com/user-attachments/assets/9cfcb978-1906-435d-82c1-5265b9c8a627)

https://github.com/user-attachments/assets/5b0ef3f9-bc52-4348-ab30-6027bed140b1

  
**App Export**
[Forms-export-1723592409073.tar.gz](https://github.com/user-attachments/files/16606306/Forms-export-1723592409073.tar.gz)

**Comment by timtandio** [comment]
![image](https://github.com/user-attachments/assets/944014fd-3a8c-4d25-83a8-7a2fb728badf)


Request URL:
https://icohs.budibase.app/api/applications
Request Method:
POST
Status Code:
500 Internal Server Error
Remote Address:
172.67.214.212:443
Referrer Policy:
strict-origin-when-cross-origin
alt-svc:
h3=":443"; ma=86400
cf-cache-status:
DYNAMIC
cf-ray:
8b2ccb4c987b2aab-LAX
content-length:
80
content-security-policy:
default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.budibase.net https://cdn.budi.live https://js.intercomcdn.com https://widget.intercom.io https://d2l5prqdbvm3op.cloudfront.net https://us-assets.i.posthog.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://rsms.me https://maxcdn.bootstrapcdn.com; object-src 'none'; base-uri 'self'; connect-src 'self' https://*.budibase.app https://*.budibaseqa.app https://*.budibase.net https://api-iam.intercom.io https://api-iam.intercom.io https://api-ping.intercom.io https://app.posthog.com https://us.i.posthog.com wss://nexus-websocket-a.intercom.io wss://nexus-websocket-b.intercom.io https://nexus-websocket-a.intercom.io https://nexus-websocket-b.intercom.io https://uploads.intercomcdn.com https://uploads.intercomusercontent.com https://*.amazonaws.com https://*.s3.amazonaws.com https://*.s3.us-east-2.amazonaws.com https://*.s3.us-east-1.amazonaws.com https://*.s3.us-west-1.amazonaws.com https://*.s3.us-west-2.amazonaws.com https://*.s3.af-south-1.amazonaws.com https://*.s3.ap-east-1.amazonaws.com https://*.s3.ap-southeast-3.amazonaws.com https://*.s3.ap-south-1.amazonaws.com https://*.s3.ap-northeast-3.amazonaws.com https://*.s3.ap-northeast-2.amazonaws.com https://*.s3.ap-southeast-1.amazonaws.com https://*.s3.ap-southeast-2.amazonaws.com https://*.s3.ap-northeast-1.amazonaws.com https://*.s3.ca-central-1.amazonaws.com https://*.s3.cn-north-1.amazonaws.com https://*.s3.cn-northwest-1.amazonaws.com https://*.s3.eu-central-1.amazonaws.com https://*.s3.eu-west-1.amazonaws.com https://*.s3.eu-west-2.amazonaws.com https://*.s3.eu-south-1.amazonaws.com https://*.s3.eu-west-3.amazonaws.com https://*.s3.eu-north-1.amazonaws.com https://*.s3.sa-east-1.amazonaws.com https://*.s3.me-south-1.amazonaws.com https://*.s3.us-gov-east-1.amazonaws.com https://*.s3.us-gov-west-1.amazonaws.com https://api.github.com; font-src 'self' data: https://cdn.jsdelivr.net https://fonts.gstatic.com https://rsms.me https://maxcdn.bootstrapcdn.com https://js.intercomcdn.com https://fonts.intercomcdn.com; frame-src 'self' https:; img-src http: https: data: blob:; manifest-src 'self'; media-src 'self' https://js.intercomcdn.com https://cdn.budi.live; worker-src blob:;
content-type:
application/json; charset=utf-8
date:
Wed, 14 Aug 2024 00:23:10 GMT
nel:
{"success_fraction":0,"report_to":"cf-nel","max_age":604800}
priority:
u=1,i
report-to:
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=NyUQXvPtOAtKX6S3wk%2FpxzWZlda5tEKpKODCuxjy5l8MEeWxAoCfBN7TBz6Ee5B2CI%2Fj2%2BmtxsNppAQl%2Bq%2B80wgsNEarfDOYeo%2F5uzXayMvzFQz2Wg8nVSPCsqSwfEpz%2BFQgDxo%3D"}],"group":"cf-nel","max_age":604800}
server:
cloudflare
strict-transport-security:
max-age=31536000; includeSubDomains; preload
vary:
Accept-Encoding
x-budibase-tenant-id:
icohs
x-content-type-options:
nosniff
x-frame-options:
SAMEORIGIN
x-xss-protection:
1; mode=block
:authority:
icohs.budibase.app
:method:
POST
:path:
/api/applications
:scheme:
https
accept:
application/json
accept-encoding:
gzip, deflate, br, zstd
accept-language:
en-US,en;q=0.9,ja;q=0.8
content-length:
3090145
content-type:
multipart/form-data; boundary=----WebKitFormBoundaryGsE1t64gWjiviAgu
cookie:
tenantId=icohs; budibase:init=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjM1OTI1MjB9.d2fBNwlMkgZgo9OfQ1tq1IsjRvcFSEESmLAIqVRu4SM; budibase:init.sig=bpkncv6FAiOlFfOIwR6jGQgzbc4; budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c184MWJjNjQ1M2Y5MWY0ZDMxODA5ZjA2ZjMxYWI4MDM5YSIsInNlc3Npb25JZCI6Ijc0NDJhYzAxZGE4ODQzZTM5Zjg1ZGM5ZjUxMjU3ZmQ4IiwidGVuYW50SWQiOiJpY29ocyIsImlhdCI6MTcyMzU5NDkzOX0.28lgqnPxbjZR5-olxM3PSpuA3T1F6WormviqiIreB08; budibase:auth.sig=dj5cEtVlY845e4ocSYVLf5ig3Wo; ph_phc_bIjZL7oh2GEUd2vqvTBH8WvrX0fWTFQMs6H5KQxiUxU_posthog=%7B%22%24sesid%22%3A%5B1723594965910%2C%2201914e0c-2fba-7052-9a4a-01f5574ea02b%22%2C1723591307193%5D%2C%22%24client_session_props%22%3A%7B%22sessionId%22%3A%2201914e0c-2fba-7052-9a4a-01f5574ea02b%22%2C%22props%22%3A%7B%22initialPathName%22%3A%22%2Fportal%2Fupgrade%22%2C%22referringDomain%22%3A%22icohs.budibase.app%22%7D%7D%2C%22distinct_id%22%3A%22us_81bc6453f91f4d31809f06f31ab8039a%22%2C%22%24device_id%22%3A%2201903c1d-98df-7f65-94f3-170f824f744b%22%2C%22%24user_state%22%3A%22identified%22%2C%22%24active_feature_flags%22%3A%5B%5D%2C%22%24enabled_feature_flags%22%3A%7B%22PER_CREATOR_PER_USER_PRICE%22%3Afalse%2C%22PER_CREATOR_PER_USER_PRICE_ALERT%22%3Afalse%7D%2C%22%24feature_flag_payloads%22%3A%7B%7D%2C%22%24session_recording_enabled_server_side%22%3Afalse%2C%22%24session_recording_network_payload_capture%22%3A%7B%22capturePerformance%22%3Afalse%7D%2C%22%24session_recording_canvas_recording%22%3A%7B%7D%2C%22%24replay_sample_rate%22%3Anull%2C%22%24replay_minimum_duration%22%3Anull%2C%22%24autocapture_disabled_server_side%22%3Afalse%2C%22%24heatmaps_enabled_server_side%22%3Afalse%2C%22%24capture_rate_limit%22%3A%7B%22tokens%22%3A99%2C%22last%22%3A1723594939517%7D%2C%22%24initial_person_info%22%3A%7B%22r%22%3A%22https%3A%2F%2Ficohs.budibase.app%2F%22%2C%22u%22%3A%22https%3A%2F%2Faccount.budibase.app%2Fauth%2Flogin%22%7D%2C%22%24epp%22%3Atrue%2C%22%24user_id%22%3A%22us_81bc6453f91f4d31809f06f31ab8039a%22%2C%22%24stored_person_properties%22%3A%7B%7D%2C%22%24web_vitals_enabled_server_side%22%3Afalse%2C%22%24exception_capture_enabled_server_side%22%3Afalse%2C%22%24exception_capture_endpoint%22%3A%22%2Fe%2F%22%7D
origin:
https://icohs.budibase.app
priority:
u=1, i
referer:
https://icohs.budibase.app/builder/portal/apps/create
sec-ch-ua:
"Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"
sec-ch-ua-mobile:
?0
sec-ch-ua-platform:
"Windows"
sec-fetch-dest:
empty
sec-fetch-mode:
cors
sec-fetch-site:
same-origin
user-agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
x-budibase-api-version:
1
x-budibase-session-id:
cdc2eb51dddef4ff5bc8f7aa9d4077637
x-csrf-token:
6619412f-e2e9-4e7b-8919-3b7430314f5d

**Comment by mike12345567** [comment]
This issue will be resolved in the next release of Budibase.

**Comment by timtandio** [comment]
Hi @mike12345567 
thanks for your help

the update is released and i am able to import the app again, however, everytime i entered data, the data is gone.
please see below screencapture

https://github.com/user-attachments/assets/d5007a6f-32b2-46bb-ab34-be813b998a1b
