### ISSUE TITLE
Get Row _id for newly submitted form

### ISSUE THREAD

**Issue by timtandio** [Budibase/budibase#14390]
**Describe the feature request**
Hi,

I put this under discussion 3 weeks ago and no response so i am trying my luck and post it here.

I have an automation that sends an email after a form has been saved. In the email template, there is a line that says "click here to open the ticket," and the word "here" contains a hyperlink to the ticket. However, for newly saved rows, I couldn't get the unique _id, though I can easily get it for existing rows.

Is there any way I can extract the unique row _id for newly saved rows? or if its not possible, can you please add the feature?

Thank you!

Love BudiBase!

**Comment by andz-bb** [comment]
answered in #14269
