### ISSUE TITLE
Data is gone after saving it, couchDB error not found and published

### ISSUE THREAD

**Issue by timtandio** [Budibase/budibase#14397]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: icohs.budibase.app

**Describe the bug**
Thanks @mike12345567 for fixing the bug. the update is released and i am able to import the app again, however, everytime i entered data, the data is gone. and i still couldnt delete the old file
please see below screencapture

this bug is related to this post:
[https://github.com/Budibase/budibase/issues/14375](https://github.com/Budibase/budibase/issues/14375)
[https://github.com/Budibase/budibase/pull/14385](https://github.com/Budibase/budibase/pull/14385)

**To Reproduce**
1. upload the app
2. enter the data
3. save the data
4. move to another tab
5. see bug below

**Screenshots**
![image](https://github.com/user-attachments/assets/2ff8af61-4aa8-4bfb-b7f1-0a22e3b3b7ab)

https://github.com/user-attachments/assets/8181ea41-468a-43d2-8e9e-863df01b3910

  
**App Export**
[Forms-export-1723592409073.tar.gz](https://github.com/user-attachments/files/16639453/Forms-export-1723592409073.tar.gz)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome

**Comment by ConorWebb96** [comment]
Hey @timtandio,

I imported your app export and everything seems to work for me. I can see all the data in your tables. Happy to provide the export I have if yours still isn't working!

**Comment by timtandio** [comment]
Hi Conor, thank you, i am now able to see it using the latest update
