### ISSUE TITLE
Delete Screen modal shows behind builder - z-index issue

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14408]
**Checklist**
- `[Y]` I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self & Cloud

**Describe the bug**
Delete Screen Modal is partially hidden behind bindings drawer

**To Reproduce**
1. In an app with multiple screens, open the bindings drawer
2. Using the component tree, attempt to delete a screen

**Expected behaviour**
Delete screen modal should show above all else.

**Screenshots**
![image](https://github.com/user-attachments/assets/7a84888e-f40e-4dfd-835f-85e61680a0e7)

  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version  127.0.6533.89 (Official Build) (arm64)

**Additional context**

**Comment by D-Lite** [comment]
@mikesealey , I made a PR for this, I had similar issues also 🤝
