### ISSUE TITLE
"Draft" Deployments

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1441]
https://xd.adobe.com/view/7d9ab210-cf9d-4e78-aa7d-c4fe199c3a17-28c9/screen/965df262-f296-44a2-82e1-51208837f70b  

When I'm developing my app on the budibase platform, I want to be able to develop on a draft version, so that I can deploy the real app to production when I am ready to do so.

Apps should not always be “live”. The flow should be: 
- Create/Edit your app
- Creating a draft 
- Deploy your draft, which will replicate the draft to the real app

**Considerations**
When creating draft versions of applications, we may have to replicate the database to a `draft` database, and use that as the target for our app when editing. This means that we will have to discern between "real" apps and "draft" apps. 

We should not replicate data/rows from the production cluster to our drafts.

**Comment by joebudi** [comment]
Additional design focusing on the publish flow:
https://xd.adobe.com/view/827c4ee0-d78d-4226-820d-495b58e9b62d-d72f/
