### ISSUE TITLE
Side panel don't scroll all the way to the bottom in Preview

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14417]
**Checklist**
- `[Y]` I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.30.7
  - App Version: 
- Cloud
  - andz.budibase

**Describe the bug**
Using the Preview feature to view a multi-step form block in a sidepanel will cut off the end of the form. 

**To Reproduce**
1. Add a sidepanel
2. Add a multi-step-form-block to the side panel that is longer enough to require scrolling
3. add a button to open the side panel
4. preview from the builder, and preview in new tab (scroll to the bottom in both cases)
5. Pay close attention to the scroll bar - it bottoms out below the bottom edge of the preview window in both cases.

**Expected behaviour**
Should be able to scroll all the way to the bottom of the sidepanel.

**Screenshots**
[Jam Screencap](https://jam.dev/c/ecd449a7-32f3-4e25-a8e2-e51981d985d5)
  
**App Export**
[Multi Step Form Blocks in Side Panels-export-1724153442307.tar.gz](https://github.com/user-attachments/files/16675138/Multi.Step.Form.Blocks.in.Side.Panels-export-1724153442307.tar.gz)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 127.0.6533.89 (Official Build) (arm64)

**Additional context**
Additional testing shows that this isn't unique to the Multi-Step Form Block, and can be reproduced with other means. Instead of a Multi-Step Form Block, add two containers, give one of them a large height setting (2000px) and and a background color of red. Give the other a small height setting (10px) and a background colour of blue. The blue container will be out of the reach of the scrollbar.

**Comment by aptkingston** [comment]
Could you recheck this one - I can't repro and I'm hoping it may have been fixed as part of the grid layout work which has gone live in the last few days.

Seems fine for me now:
![image](https://github.com/user-attachments/assets/5fc7b329-02b4-49b4-a1cd-9a6a4a3d981c)
