### ISSUE TITLE
Basic Settings Page

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1442]
- Users need to just be able to turn off analytics.
- Set up their logo and org name
- We should support their company logo on the login page, forgot password, invite etc 

https://xd.adobe.com/view/7d9ab210-cf9d-4e78-aa7d-c4fe199c3a17-28c9/screen/207f41ed-cd49-410b-aa32-2989febf2a12

**Comment by kevmodrome** [comment]
Re-opening, still some work to do with regards to the logo
