### ISSUE TITLE
[ Custom Component / Builder ] - Define Context to nested properties in schema

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#14426]
Currently, in the case of properties of type "event" we can define a context that will be provided at runtime, so the bindings drawer works as expexted and lists the appropriate context to be selexted.

I propose to add a similar mechanism, to properties that have "nested" set to true, as these properties will be enriched by the component at runtime. For example when we have a nested prop for bacground color , that will be calculated based on the specific row in the table. This nested property could have its context expose a "activeRow" , so that property is listed in the bindings drawer for the user to select easily.

this would assume that when the component internally will enrich the prop, will provide the additionally defined context.

this change would essentially allow to nested properties context, to correctly apper in the bindings drawer.

**Comment by aptkingston** [comment]
Hey @poirazis! As `nested` settings can already reference context provided by themselves, can you not already do this? You would define a `static` context provided by your component, then any `nested` settings would be able to use it.

A quick example would look like:
```json
"foo": {
  "name": "foo",
  "settings": [
    "type": "text",
    "label": "Background color",
    "nested": true
  ],
  "context": [
    {
      "type": "static",
      "scope": "global",
      "values": [
        {
          "label": "Active row",
          "key": "activeRow",
          "type": "object"
        }
      ]
    }
  ]
}
``` 

You could also use local scope instead, if this is being provided on a per-row basis.

Not 100% sure if this solves your use case but give it a try!

**Comment by poirazis** [comment]
Hey @aptkingston and thanks !
I was trying the wrong way ( providing the context to the specific prop only ) .

Thanks again!
