### ISSUE TITLE
Issue with google sheets

### ISSUE THREAD

**Issue by TahaKazi** [Budibase/budibase#14421]
I have made a new connection to Google Sheets. Every time I submit a record, it updates in the sheet but the form throws this error Cannot read properties of undefined (reading 'tableId')

**To Reproduce**
1. Go to (https://xpertresearch.budibase.app/app/xpertresearch#/addclient)
2. Click on '..Submit..'
3. See error

**Expected behavior**
Ok notification, but error is thrown

**Screenshots**
![Screenshot 2024-08-21 102541](https://github.com/user-attachments/assets/811d6fcd-11f9-4fb7-9e66-e42373c01b70)
  
**App Export**
[redacted]

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome
 - Version 127.0.6533.120 (Official Build) (64-bit)

**Comment by traverick** [comment]
I'm having the same error.  What can I do to get an ok confirmation?

**Comment by bjornclauw** [comment]
The same problem for me when editing the sheet in the UI under the DATA section:
![image](https://github.com/user-attachments/assets/eb5b1f39-19e8-4d49-906b-28574375e9d3)

The cell in google sheets still gets updated despite the error.

**Comment by samwho** [comment]
@traverick @bjornclauw hey folks, the latest releases of Budibase should have fixes for the problems you've been seeing. I've closed this, but please do re-open it and tag me if you're still having problems. 🙏
