### ISSUE TITLE
Can't copy checkbox and relationship picker value using action with handlebar

### ISSUE THREAD

**Issue by ksstms** [Budibase/budibase#14444]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.31.1

**Describe the bug**
I'm using the "Update Field Value" action to copy the state of one checkbox to another. The second checkbox always gets checked no matter the state of the first one. This is only a problem using the handlebar notation, JS works fine. The same is true for relationship pickers.

**To Reproduce**
1. Create a form with 2 checkboxes and a button.
2. Add an on-click action to the button as shown beloow
![image](https://github.com/user-attachments/assets/d3e9c5ac-9726-478e-90b8-edaae0afd976)
3. Check how clicking the button changes the target checkbox. 

**Expected behavior**
Clicking the button should change the second checkbox state to the first one's state.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 127.0.6533.99

**Comment by andz-bb** [comment]
hey @ksstms, by default handlebars will be returning `"true"` or `"false"` as strings rather than boolean type.

If you try `{{ literal form.Fields.cb2 }}` it might return the boolean type instead.
