### ISSUE TITLE
Filter and Limit Behavior on Data Provider Produces Unexpected Results

### ISSUE THREAD

**Issue by Gtchik** [Budibase/budibase#14493]
**Checklist**
- [x] I have searched Budibase discussions and GitHub issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker single image
  - Budibase Version: 2.31.3
  - App Version: 2.31.3

**Describe the bug**
When applying both a filter and a limit on a data provider, the data returned does not reflect 10 results that meet the filter criteria. Instead, it seems to return the results that meet the filter criteria within the first 10 records fetched by the query (based on the order by clause). It appears as though the filter is being applied after the initial query is executed, rather than before.

**To Reproduce**
1. Go to the data provider configuration.
2. Apply a filter and a limit of 10 on the data.
4. Observe that the data returned does not include 10 results matching the filter criteria, but instead includes results that match the filter within the first 10 records.

**Expected behavior**
I expected the data provider to return exactly 10 results that satisfy the filter criteria, irrespective of the initial query order.

**Screenshots**
The provider using "normal" way : 
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/25a9c753-e7c1-4416-87e9-6c203e4e1474">
The provider using custom query :
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/00668624-3234-40e2-aa74-99c122f217a5">
The result with data :
<img width="628" alt="image" src="https://github.com/user-attachments/assets/1dccf676-64d8-4bc9-b59e-808d8a591058">

**Additional context**
I'm not sure if this is a bug, a feature request, or if I'm misunderstanding how this feature is supposed to work. Any clarification would be appreciated.

**Comment by mike12345567** [comment]
Hi @Gtchik - just to check, in your first screenshot of the data provider filtering you haven't picked a column to filter on, when applying this filter are you filtering on the `fk_customers_strategy_group` as you are in the custom query?

**Comment by Gtchik** [comment]
Hello,
I was pretty sure I'd tried both but actually using the fk works just fine.
Merci @mike12345567  :)
