### ISSUE TITLE
Search Component not Working Correctly

### ISSUE THREAD

**Issue by cfsdes** [Budibase/budibase#1450]
**Describe the bug**
I am setting up a search bar and placing a horizontal card inside it.

When I try to search for a word, it says it doesn't exist, even if it exists.

Searching works when I don’t search the word completely, but when I put the full word, it doesn’t work

I'm using the MacOS version

**Comment by mike12345567** [comment]
I @cfsdes is this searching from within the builder or when it is deployed?

The next version of budibase (which will be out very soon) has a completely revamped method of searching, which uses a real lucene index (like is used in elasticsearch) so issues like this should be fully solved in it.

**Comment by shogunpurple** [comment]
Addressed by search capabilities in new release
