### ISSUE TITLE
If text boxes are hidden they don't act as expected when trying to get values from them

### ISSUE THREAD

**Issue by Bornforexile** [Budibase/budibase#14524]
**Checklist**
- [X ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Local Server 
  - Budibase Version: 2.29.25
  - App Version: 2.29.25

**Describe the bug**
I have a screen of text boxes that people will use to update the values in a table in a database. I conditionally hide some of those boxes based on what information is passed to that page. The issue is that budibase seems to be treating the hidden boxes values differently than those that are always shown. THe ones that are always shown have the correct value of 0, but if they are hidden then it shows something like this 

{{ subtract [c8a0c036185c94f5ba877b5992d8c9e79].[glueFail] [c9569b94d7dc84a27bc86ae2f79768b89].[Glue Failure] }}

and it may also have to do with the subtract function interacting weird. But something is bugging out and not acting correctly.

**To Reproduce**
1. make a screen with editable text boxes.
2. Attach them to a data provider
3. Hide some of the text boxes
4. Try to write a {{subtract}} function or maybe even just retrieving the data from the hidden boxes using text and not javascript
5. values are garbled

**Expected behavior**
The values should be normal ints and not unidentified handlebar errors

**Screenshots**
The preview value when it is working correctly
![box function](https://github.com/user-attachments/assets/ccd38cd8-ead1-47b0-8cc2-6cabf093e02b)
All the containers and boxes i have
![Boxes](https://github.com/user-attachments/assets/0f770268-9c61-455b-a621-66afcbeb32fe)
![Containers](https://github.com/user-attachments/assets/1e841552-0bf9-4d0d-80a1-3f2e61496bed)
The Error Message
![error](https://github.com/user-attachments/assets/0f68511a-b4d5-40b4-a219-312b3baa3d66)
![glue](https://github.com/user-attachments/assets/13cdb669-07eb-433c-9680-742062a39e34)
The messed up values that come from hidden boxes
![messed up](https://github.com/user-attachments/assets/bfdcb2dd-c2d9-460c-ba77-1489498ee115)
![paint](https://github.com/user-attachments/assets/7ef0681f-d359-4ec8-9372-bc2cf5bbb1aa)
The missing variables in the hidden boxes
![value not showing all boxes](https://github.com/user-attachments/assets/89054d52-58ea-4d60-affd-f1775c92a91f)

  
**App Export**
[PQCDev-export-1725547254207.tar.gz](https://github.com/user-attachments/files/16895794/PQCDev-export-1725547254207.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 128.0.6613.120 (Official Build) (64-bit) 

**Additional context**
It seems as if when the boxes are hidden the VALUE binding box does no populate with the values of the hidden boxes and so it won't populate in the bindings because there's nothing there

**Comment by aptkingston** [comment]
Hey @Bornforexile. Using conditions to hide components will actually not render them at all, so that's why you can't use them. They basically stop existing. If you want to hide them visually but still use them, I'd recommend using conditions to set custom CSS and do something like `visibility: hidden` or `display: none` etc.

Your other option is use JavaScript instead of Handlebars, and check if they're null/undefined and handle that as 0 instead.
