### ISSUE TITLE
The Relationship Picker's filter(bind to another field) is not work well. 

### ISSUE THREAD

**Issue by yoyogis** [Budibase/budibase#14551]
**Describe the bug**
The Relationship Picker's filter(bind to another field) is not work well. 
I'm studying Budibase follow this guide https://docs.budibase.com/docs/cascading-dropdown-filters. In this case the "cities" can not filtered by "country". 

**To Reproduce**
1. follow the doc: https://docs.budibase.com/docs/cascading-dropdown-filters

**Comment by yoyogis** [comment]
Sorry @ConorWebb96 ， but can you explain why you closed this issue ?  The filter is not work yet, please look the snapshots bellow.
<img width="2044" alt="city-filter" src="https://github.com/user-attachments/assets/1d3b3f53-a99a-4b76-9703-2aee38fc8541">
<img width="1898" alt="city-filter2" src="https://github.com/user-attachments/assets/3ff6f6f1-1943-462c-88dc-7b19c86f76fe">

**Comment by ConorWebb96** [comment]
Hey @yoyogis,

For whatever ever reason this didn't get marked as a duplicate of https://github.com/Budibase/budibase/issues/13893.

I closed in favor of this.
