### ISSUE TITLE
Value in Oracle DB is different with SQL query result in budibase

### ISSUE THREAD

**Issue by fghhunter** [Budibase/budibase#14550]
**Checklist**
- [ V] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> docker compose
  - Budibase Version: <version> 2.29.1
  - App Version: <version> 2.29.1
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
The number field in the result of Oracle SQL query shown in left side has a very small gap against the value stored in DB. Even if use Round method to keep 2 decimal places.
![image](https://github.com/user-attachments/assets/a86683b8-f208-48d1-9786-9e57b4f3a04b)
Table component view:
![image](https://github.com/user-attachments/assets/6259994d-8ea3-44b6-a750-69978c20ac59)
DB view:
![image](https://github.com/user-attachments/assets/17a73674-fc30-4197-aebd-488e09cd8a75)

**To Reproduce**
1. Connect to Oracle DB
2. Make a query and test, result will show the gap
3. Add table component in the screen, set oracle query as data source, gap will show in the table.

**Expected behavior**
The value of sql query result should be the same with DB. 

**Screenshots**
Show above.
  
**App Export**
--

**Desktop (please complete the following information):**
 - OS:Windows10 22H2 [e.g. iOS]
 - Browser Chrome 109.0.5414.25 [e.g. chrome, safari]

**Additional context**
Budibase running on Ubuntu2404

**Comment by mike12345567** [comment]
Hi @fghhunter - sadly this is the nature of numbers in JS - when converted to decimals there is a chance of inaccuracy like this occurring - it is best in these cases to use the query transformer https://docs.budibase.com/docs/transformers to round the JS numbers to get the result set you expect/desire.
