### ISSUE TITLE
Need help, why the component plugin can not update realtime in screen during development?

### ISSUE THREAD

**Issue by yoyogis** [Budibase/budibase#14599]
### Discussed in https://github.com/Budibase/budibase/discussions/14583

<div type='discussions-op-text'>

<sup>Originally posted by **yoyogis** September 15, 2024</sup>
I'm new to Budibase. Today, I used the Budibase CLI to start a DEV environment and created a new component plugin. However, when I change the code in "/src/Component.svelte", the component in "Design/Screen" isn't updated. Only after I delete the dist directory and restart 'yarn watch', then refresh the builder page, will the component be updated.

<img width="2351" alt="image" src="https://github.com/user-attachments/assets/0086def3-3746-4fe7-b7fe-7abba5f0991d">
</div>

**Comment by mikesealey** [comment]
Hey @yoyogis - You've raised this issue as well as help discussion, so I'll close this one as it isn't a bug.
