### ISSUE TITLE
Automation - delete row not triggering

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#14595]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.32.5
  - App Version: 2.32.5

**Describe the bug**
When there is an automation which has Row Deleted as the trigger the automation does not trigger when a row is deleted.

**To Reproduce**
1. Create an app with a internal DB table
2. Create an interface where you can add and delete from the table
3. Add an automation with row deleted on that table
4. Publish the app
5. Create and delete a row
6. View automation logs

**Expected behavior**
The automation should trigger and show in the automation logs. It does neither.

**Comment by andyburgessmd** [comment]
@mikesealey I have sent the export to your support email address.

**Comment by mikesealey** [comment]
@andyburgessmd Thanks for providing your app-export. I took this on a call with some of the engineering team, who are currently working on a fix.

**Comment by andyburgessmd** [comment]
@mikesealey thanks, fixed now :)
