### ISSUE TITLE
stepsByName bindings in automations are not working

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14625]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.32.5
**and**
- Cloud
  - Tenant ID: miketest1

**Describe the bug**
When renaming steps in an automation-flow, and then using the bindings menu to fetch values from previous steps, the bindings menu uses `stepsByName[step-name-here]`, which is not defined.

**To Reproduce**
1. create an automation triggerd by an app-action
2. add 3 JS scripting steps, rename them
3. the first two should return a string of your choice
4. the third should return the first string added to the second string
5. (optional) add a step to send a discord message with the output of the third JS block

**Expected behavior**
Once the steps have been renamed - if the binding posts `stepsByName` into JS it should be a defined variable.

**Screenshots**
Steps were renamed sensibly to `JSscripting 1, 2, 3`
Using `stepsByName` returns the error `ReferenceError: JSscripting1 is not defined`
![image](https://github.com/user-attachments/assets/96996e1f-b52e-4cbc-a4ff-57be703b4b4f)

Steps were named un-sensibly, and spaces seem to cause an issue 
![image](https://github.com/user-attachments/assets/5dbb377c-99d2-45b0-96ea-9ba12e416038)

However if the steps do not get renamed, there are no issues. If I ignore the bindings and use `steps[n].value` on steps where the binding produces `stepsByName`, I can work around it.

  
**App Export**
[Venu Automations-export-1727084483833.tar.gz](https://github.com/user-attachments/files/17095437/Venu.Automations-export-1727084483833.tar.gz)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**
This issue was brought to our attention by a customer.

**Comment by mike12345567** [comment]
Binding generation fixed in latest version.
