### ISSUE TITLE
Relationships causing error in data grid on the cloud

### ISSUE THREAD

**Issue by mike-hand** [Budibase/budibase#14621]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: libsyn

**Describe the bug**
When viewing a table with a relationship in the Data section, it fails with this error:
There was a problem loading your grid
VT12001: unsupported: WITH expression in SELECT statement

**To Reproduce**
1. Go to 'Data'
2. Click on a table that has a relationship
3. Displays the error.

**Expected behavior**
Work as it did previously showing the data with the many relationship fields.  Last time I used the app was 2 weeks ago.

**Screenshots**
![image](https://github.com/user-attachments/assets/44a9a290-3c4c-458a-b2ea-d8346745be31)

**Additional context**
If you remove the relationship, you can see the normal data in the table.  Seems to a bug in the way you handle the relationship.

If you look at this tennant id, the tables show_plans and show_plans_products have the relationship.  I've remove the others so that we can update data at needed.

Thanks!

**Comment by mike12345567** [comment]
Hi @mike-hand - we have changed how we perform queries in Budibase to be more performant, making use of a CTE to execute these queries going forward. You will need to check the version of SQL database you are using and make sure that it has support for CTEs. You can find the minimum support versions for databases we support here: https://docs.budibase.com/docs/troubleshooting-sql

If you cannot upgrade your database to a version with CTE support then we recommend self-hosting a version of Budibase from before 2.31.

**Comment by mike-hand** [comment]
@mike12345567   Thank you for the update and information.
