### ISSUE TITLE
Cannot Export Data from Table w/ Custom Query

### ISSUE THREAD

**Issue by matt-harbers** [Budibase/budibase#14647]
**Hosting**
- Self
  - Method: docker compose, aws
  - Budibase Version: 2.32.8

**Describe the bug**
Cannot download a file or export data from a table populated by a custom query.  Rows are selectable, but I get the following error: "You can only export data from table datasources"

**Expected behavior**

**Screenshots**
![Screenshot from 2024-09-26 22-04-16](https://github.com/user-attachments/assets/8f232c59-ff17-44e4-a2f1-974e7b0d2b63)

**Comment by ConorWebb96** [comment]
Hey @matt-harbers,

I don't think this is a bug. The error message itself explains why it's not working for you. 

Going to close in favour of this feature request [here](https://github.com/Budibase/budibase/issues/7348).
