### ISSUE TITLE
Public API: /roles/assign POST Method Not Allowed

### ISSUE THREAD

**Issue by marzzzello** [Budibase/budibase#14643]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.32.7

**Describe the bug**

**To Reproduce**
1. run `curl -sX POST https://bb.domain.tld/api/public/v1/roles/assign -H 'x-budibase-api-key: BB_API_KEY --data '{"userIds":["USER_ID"],"role":{"roleId":"BASIC","appId":"app_67c7a780d3d346c7bad0306c1dfc571a"}}'`
2. Get error: `Method Not Allowed`

**Expected behavior**
According to `openapi.yml` POST should be the allowed method for this endpoint.

**Comment by ConorWebb96** [comment]
Hey @marzzzello,

If you look at our [documentation](https://docs.budibase.com/reference/roleassign) for the public API, you can see that this API endpoint is only for Business(Deprecated) and Enterprise tier customers.

This restriction was mainly introduced to avoid using the public API to circumvent our paid user groups feature. When you invite a user, you can assign them to user groups so they already have default access.

If you are an enterprise customer and this isn't working, please email support@budibase.com, and we will investigate this issue for you.

I will close this issue as it is likely related to not being on the correct tier.

I hope this makes sense.
