### ISSUE TITLE
MS SQL table with relationships throws "Problem loading your grid - Incorrect syntax near 'JSON"

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14686]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: microtec

**Describe the bug**
Ticket came in via support
Any MS SQL table queried fails to load with `There was a problem loading your grid Incorrect syntax near 'JSON'.` User is running MS_SQL 2012, and believes the issue came about after https://github.com/Budibase/budibase/pull/14532

**To Reproduce**
important - this issue seems to be specific to MS SQL **2012**
** Cannot upload SQL to Github, shema available on request if required **
1. Create Database with schema posted below
2. See Data Section
3. Remove relationship (using external tool)
4. Data section should load

**Expected behavior**
Data section should load regardless of relationships.

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**
Customer states: reverting to BB version _before_ the release that broke did not remedy the situation

**Comment by mike12345567** [comment]
This cannot be supported - as listed here: https://docs.budibase.com/docs/troubleshooting-sql

We cannot provide support for SQL Server 2012 in BB 2.32+ due to a lack of JSON aggregation support and CTEs.
