### ISSUE TITLE
Current user bindings compared to user field values aren't the same.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#14684]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.32.8
  - App Version: 2.32.8

**Describe the bug**
Current user bindings differ slightly from their field and single/multi-select column counterparts. The user's table value and current user bindings _id for a user looks like this `ro_ta_users_us_b25ae692d59c4410ba4f0f2a5400c555`. However, when copying the value for a single select/multi-select field and even the associated pickers. The values look like this `us_b25ae692d59c4410ba4f0f2a5400c555`.

Because of the above, you can't really do direct matching. You have to strip the text before us_ to get matching results. `ro_ta_users_`

**To Reproduce**
1. Go to any app
2. Create a new table with a single select
3. Add a user to the single select column
4. Copy the value of the field
5. Output the current user _id binding in a new screen
6. See the differences between the values

**Expected behavior**
All references of user _id bindings should follow the same format to avoid having to write code to ensure that they match.

**Screenshots**
<img width="870" alt="Screenshot 2024-10-02 at 08 10 46" src="https://github.com/user-attachments/assets/60704bc2-4e72-4052-b54c-8453d09dea1e">
<img width="863" alt="Screenshot 2024-10-02 at 08 11 08" src="https://github.com/user-attachments/assets/2bf7c088-13e7-4b02-8519-af5ab20b8e07">

**Comment by ConorWebb96** [comment]
This also extends to the user pickers and the query automation step when using the user's table.

The user pickers output the user IDs as `us_` whereas the query step on the user's table outputs _id as `ro_ta_users_` onto the front of `us_`

**Comment by shawnweeks** [comment]
Not sure why this was closed but the issue is still present in 2026.
