### ISSUE TITLE
Data Tab - Export Data feature fails

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14731]
**Checklist**

- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self (Me)
  * Method: docker single image
  * Budibase Version: 2.32.9
  * App Version:
* Cloud (Customer
  * Tenant ID: Geis - tested with Apps running versions 2.32.12 / 2.32.10 / 2.30.7

**Describe the bug**
In the Data tab, the button to export data (to csv, json, etc) fails.
When exporting to .CSV it throws an error "Export Failed".
When exporting to .JSON it exports a file that contains an empty array.
When exporting to .JSON with schema it downloads a file containing the correct schema, and an empty array where the rows should be.

**To Reproduce**

1. Create an app using the sample BB data
2. Click export
3. export to CSV - error
4. Export to .JSON - Download contains an empty array
5. Export to .JSONwithschema Download contains a schema and an empty array.

**Expected behavior**
Should export the rows of data as the requested type.

**Screenshots**
Jam Screencap holds some network errors [https://jam.dev/c/6978b9b6-7118-4d96-a21e-1ad360f8146f](https://jam.dev/c/6978b9b6-7118-4d96-a21e-1ad360f8146f)

**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Chrome
* Version 129.0.6668.70 (Official Build) (arm64)

**Additional context**
Issue submitted by CSE, raised by Geis

**Comment by shogunpurple** [comment]
This works on the latest version of Budibase - could you try again?
