### ISSUE TITLE
Relationship field appears to be filtering itself

### ISSUE THREAD

**Issue by mohagan9** [Budibase/budibase#14736]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: rspb.budibase.app

**Describe the bug**
Cannot select a new item from the relationship field. 
It looks as if it is filtering itself. 
I have no filters applied to the relationship field.
It was working maybe a week ago. 

**To Reproduce**
1. Define a many-to-many relationship (Budibase internal table)
2. Add an **update** type form block, and make sure *Search* is enabled for the relationship field
3. Try to change the relationship item - the only option available is the selected option.

**Expected behavior**
When updating an existing record, I should be able to search for and select all available options.

**Screenshots**
<img width="365" alt="Screenshot 2024-10-08 at 20 00 59" src="https://github.com/user-attachments/assets/68cc67b2-6710-429f-b7b9-89e79fb009d0">

https://github.com/user-attachments/assets/6827e864-7a81-46d6-a687-4e74b3aa3e69

**Comment by ConorWebb96** [comment]
I've attached an app export of this recreated. Can confirm its on the latest release and on the most up-to-date version of master.

Relationship columns inside the table component seem to still be working.

[filtering issue-export-1728388670418.tar.gz](https://github.com/user-attachments/files/17303401/filtering.issue-export-1728388670418.tar.gz)

**Comment by ConorWebb96** [comment]
Fixed in the latest version of Budibase.
