### ISSUE TITLE
Filtering seems to be broken for non logged in users on public screens.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#14739]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: cprem

**Describe the bug**
Filtering on data providers/table components doesn't work on public screens. It only seems to work for logged-in users. This seems to be fixed on master. 

**To Reproduce**
1. Import the below app
2. Publish the app
3. Switch to a different browser
4. Go to the published URL
5. Click on any row in the table
6. See it only gets the first record rather the correct filtered row.

**Expected behavior**
It should filter regardless of whether the user is logged in or not.

**Screenshots**
![20241009_085053](https://github.com/user-attachments/assets/d2506410-7d63-45cf-8dae-716e230cb355)
  
**App Export**
[filtering issue-export-1728460395494.tar.gz](https://github.com/user-attachments/files/17304475/filtering.issue-export-1728460395494.tar.gz)

**Comment by mike12345567** [comment]
Fix applied - issue with feature flagging in Cloud.
