### ISSUE TITLE
Dataprovide cannot filter any values since the update

### ISSUE THREAD

**Issue by robert4dt** [Budibase/budibase#14760]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
{
  "browser": {
    "language": "de",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
    "platform": "Win32",
    "vendor": "Google Inc."
  },
  "server": {
    "budibaseVersion": "2.32.15",
    "hosting": "docker-compose",
    "nodeVersion": "v20.18.0",
    "platform": "linux",
    "cpuArch": "x64",
    "cpuCores": 8,
    "cpuInfo": "Intel Xeon Processor (Skylake, IBRS)",
    "totalMemory": "30.602081298828125GB",
    "uptime": "316 day(s), 20 hour(s), 39 minute(s)"
  }
}

**Describe the bug**

**To Reproduce**
1. Add a dataprovider
2. Filter for any values
3. Add a repeater, block or anything
4. "no results found"

**Expected behavior**
The results, provided from the budibase tables

**Screenshots**
![image](https://github.com/user-attachments/assets/f9fdc7a5-1795-4d64-a112-a941f4a6ef2a)
![image](https://github.com/user-attachments/assets/8f717353-7e18-41d2-a070-488c54991243)

**Comment by robert4dt** [comment]
![version 2 23 15](https://github.com/user-attachments/assets/4cdcdead-e241-4a9f-94b1-04b7f20395db)
![version 2 17](https://github.com/user-attachments/assets/5c2362ff-f243-4d99-b88a-594e7a07ed88)

**Comment by Hertizch** [comment]
Same here. Filtering not working on 2.32.17

**Comment by knuella** [comment]
+1

**Comment by Muntliger** [comment]
+1

**Comment by ConorWebb96** [comment]
I haven't been able to replicate this behavior on the latest version of Budibase. The GIF below shows this working. This was done on the cloud, which uses the latest released version of Budibase. I've also checked locally, and it works there as well.

![20241015_090026](https://github.com/user-attachments/assets/d9466417-f9ff-4548-9d09-918bc65ac3f7)

There was an issue with the cloud, where the ability to filter on public screens wasn't working. However, this was exclusively cloud-related. The issue for this is logged [here](https://github.com/Budibase/budibase/issues/14739).

Are there any replication steps that show the error happening on the latest version of Budibase?

**Comment by robert4dt** [comment]
I recorded the complete behavior in the 2.32.17
https://scribehow.com/shared/Creating_a_New_Data_Provider_with_Repeater_Filters__wzwyj5msSr-MS_Ai5Ub16w

{
  "browser": {
    "language": "de",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
    "platform": "Win32",
    "vendor": "Google Inc."
  },
  "server": {
    "budibaseVersion": "2.32.17",
    "hosting": "docker-compose",
    "nodeVersion": "v20.18.0",
    "platform": "linux",
    "cpuArch": "x64",
    "cpuCores": 8,
    "cpuInfo": "Intel Xeon Processor (Skylake, IBRS)",
    "totalMemory": "30.602081298828125GB",
    "uptime": "321 day(s), 14 hour(s), 24 minute(s)"
  }
}

Mit freundlichen Grüßen

Robert Wall
Geschäftsführer

Tel: +49 511 999876 00

Support: +49 511 999876 20

Von: Conor Webb ***@***.***>
Gesendet: Dienstag, 15. Oktober 2024 10:06
An: Budibase/budibase ***@***.***>
Cc: Robert Wall ***@***.***>; Author ***@***.***>
Betreff: Re: [Budibase/budibase] Dataprovide cannot filter any values since the update (Issue #14760)


I haven't been able to replicate this behavior on the latest version of Budibase. The GIF below shows this working. This was done on the cloud, which uses the latest released version of Budibase. I've also checked locally, and it works there as well.

20241015_090026.gif (view on web)<https://github.com/user-attachments/assets/d9466417-f9ff-4548-9d09-918bc65ac3f7>

There was an issue with the cloud, where the ability to filter on public screens wasn't working. However, this was exclusively cloud-related. The issue for this is logged here<https://github.com/Budibase/budibase/issues/14739>.

Are there any replication steps that show the error happening on the latest version of Budibase?

**Comment by mike12345567** [comment]
Hi @robert4dt, @Muntliger, @iambricegg, @knuella and @Hertizch we've investigated this and found that there was an issue with versions 2.32.12 through to version 2.32.17 which exhibited this behaviour.

Upgrading to version 2.33 and onwards will solve this issue - which uses our new internal DB engine Structured Query Server (SQS) - if you're hosting with our docker-compose setup (not the single image) you may need to do a small migration to make sure your CouchDB image is up to date, we have a guide about this here: https://docs.budibase.com/docs/migrations.

Kubernetes and single image installations will update fine and won't require any migration.

We have also confirmed 2.32.11 is the latest version before this issue was introduced, which can be reverted to if you wish to do that instead.

Going to close this issue as it is resolved as of the latest release, if you have any questions please comment them on the issue.

**Comment by robert4dt** [comment]
Hi @mike12345567,

is there any save way to migrate to the budibase/couchdb build, without loosing all apps?
I updated budibase, now my budibase instance is gone. Then i switched the couchdb-build. Now all my apps are gone.

![image](https://github.com/user-attachments/assets/8451c8cf-c8e6-4d70-83fe-bc4c76b1f21c)


I restored the couchDb-Server from an image, so the couchdb itself does work. But i now have no working budibase instance
(the couchDB is in the local network of budibase but on a different machine). I switched from the ibm-build to the budibase-build

**Comment by mike12345567** [comment]
>  Hi @mike12345567,
> 
> is there any save way to migrate to the budibase/couchdb build, without loosing all apps?
> I updated budibase, now my budibase instance is gone. Then i switched the couchdb-build. Now all my apps are gone.
> 
> ![image](https://github.com/user-attachments/assets/8451c8cf-c8e6-4d70-83fe-bc4c76b1f21c)
> 
> 
> I restored the couchDb-Server from an image, so the couchdb itself does work. But i now have no working budibase instance
> (the couchDB is in the local network of budibase but on a different machine). I switched from the ibm-build to the budibase-build.
> 
> I alway use docker compose.

Hi @robert4dt - this should not happen, the Budibase CouchDB image is a drop in replacement for the IBM image, they should work with each other. When you say the CouchDB install is on another machine, how is this managed?
There are some extra settings which are needed now, so you need to use the new `docker-compose.yaml` - if you have customised to run CouchDB elsewhere you'll need to make sure the new ports are open and accessible as well as all the SQS configuration being correct.

**Comment by robert4dt** [comment]
it seems to me the couchDB instance uses different pathes in the base configuration. But currently i am figuring out

**Comment by robert4dt** [comment]
Couldn't fix it. I have to rollback all changes of the last 24 hours.
I don't know why the change of the image will definitly lead to the removal of all databases.

**Comment by robert4dt** [comment]
@mike12345567 
i have a different machine for couchdb.
I configured the ports to the different machine, but 
![image](https://github.com/user-attachments/assets/77719641-ddf1-45c8-9bd1-1707e6e5e647)
In the errormessage there is a different port shown, than a set in the configuration. There seems to bee an issue with the connection to the couchDB inside budibase (the portnumber is exactly 1.000 ports underneath the correct one).

**Comment by robert4dt** [comment]
Neither https://[raw.githubusercontent.com/Budibase/budibase/master/hosting/.env](https://raw.githubusercontent.com/Budibase/budibase/master/hosting/.env)
nor https://[raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml](https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml)

has specific settings for SQS configuration

**Comment by mike12345567** [comment]
> Neither https://[raw.githubusercontent.com/Budibase/budibase/master/hosting/.env](https://raw.githubusercontent.com/Budibase/budibase/master/hosting/.env) nor https://[raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml](https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml)
> 
> has specific settings for SQS configuration.
> 
> But i see now, that the port shown is part of the sqs config (according to the readme)

Ah yes - running CouchDB on a separate system using docker-compose isn't a default supported configuration - i'm not quite sure on how you will have set this up, so it might be a little difficult to support!

You will need both ports `5984` and `4984` to be opened up to your services and you will also need to set the `COUCH_DB_SQL_URL` for both app and worker services to point to your CouchDB server on port `4984`.

**Comment by robert4dt** [comment]
@mike12345567  
in https://[raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml](https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml)
this line did the trick:

      - TARGETBUILD=docker-compose

So now my existing databases are found. I were able to bind the lower port. Everything seems so work properly.


Thank you very much for your help

**Comment by mike12345567** [comment]
> @mike12345567 in https://[raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml](https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml) this line did the trick:
> 
> ```
>   - TARGETBUILD=docker-compose
> ```
> 
> So now my existing databases are found. I were able to bind the lower port. Everything seems so work properly.
> 
> Thank you very much for your help

Good to hear - thank you for noting the answer as well for anyone running a similar configuration!
