### ISSUE TITLE
MongoDB query "offset is out of range" error

### ISSUE THREAD

**Issue by injaan** [Budibase/budibase#14766]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker
  - Budibase Version: 2.32.16
  - App Version: 2.32.16
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
- Connected to MongoDB successfully
- Tried to get all records from profiles collection (collection has ~85k records)
- Error says "Query Error: The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825797"

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2024-10-11 at 11 35 29](https://github.com/user-attachments/assets/89891c20-c2da-40d0-9f83-4c4c332049a7)
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

**Comment by ConorWebb96** [comment]
Closing, please follow the bug template.
