### ISSUE TITLE
On Click actions for Containers don't work

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14767]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: miketest1

**Describe the bug**
On Click actions can be set for a container, but they never get triggered.

**To Reproduce**
1. Add a container (set a background color for ease of use)
2. Add an on click action of Show Notification (add a message)
3. Preview, and click the container

**Expected behavior**
On click actions should run when container is clicked

**Screenshots**
[Jam Screencap](https://jam.dev/c/c3d52b38-6e4b-47e2-be30-3b0d58f3dfd7)
  
**App Export**
[Click-export-1728638904067.tar.gz](https://github.com/user-attachments/files/17340753/Click-export-1728638904067.tar.gz)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Version 129.0.6668.70 (Official Build) (arm64)

**Additional context**
Issue is present in Grid and Flex layouts. Cursor does not change when hovering over a container with an on-click action set.

**Comment by aptkingston** [comment]
Just to clarify the issue only happens for grid layout containers. The parent container layout type does not matter - only the layout setting on the container itself. A flex container works as expected, but a grid container doesn't (click even support was missing from the implementation). Will push a fix now 👍
