### ISSUE TITLE
Docker-compose installation - 2.33 update requires migration

### ISSUE THREAD

**Issue by ben-biber** [Budibase/budibase#14808]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.33.0

**Describe the bug**
Budibase installation broken after migration, all apps give the error: {"message":"AppId could not be found","status":500} and all users cant log in or reset the password

**To Reproduce**
1. start migration

**Expected behavior**
migration is completed

**Comment by mike12345567** [comment]
Hi @ben-biber - docker-compose installations need to have their `docker-compose.yaml` files updated in the recent version, information about this here: https://docs.budibase.com/docs/migrations

If you use the Budibase CLI to update your installation it will perform these steps for you.

You'll need to make sure you're using the new correct version of the `budibase/couchdb` image in your installation and it has all the configuration from the latest compose file.

If you have a more custom installation I had a discussion with another user that had to walk through these steps manually here: https://docs.budibase.com/docs/migrations

**Comment by mike12345567** [comment]
Going to close out this issue as this is no further work to do.
