### ISSUE TITLE
Query Error: Failed to connect to xxxx - Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by trotec** [Budibase/budibase#1481]
**Describe the bug**
When adding a query to a MSSQL connector, it can not execute the query, resulting in the error 
`Query Error: Failed to connect to <host>:<port> - Cannot call write after a stream was destroyed`

**To Reproduce**
1. Add a database connection using **MSSQL**
2. Click on **Add Query**
3. Enter all fields and any query (any valid query will do)

**Expected behavior**
No error, and a json or schema preview with the returned results from the query. 

**Screenshots**
UI error:
![image](https://user-images.githubusercontent.com/75743827/117951516-88c10100-b314-11eb-8376-eea0db9fb2a2.png)
Errors in dev console:
![image](https://user-images.githubusercontent.com/75743827/117952045-113fa180-b315-11eb-8e73-a5c760c68584.png)

**Desktop**
 - OS: Windows 10 20H2
 - Browser: Edge
 - Version 90.0.818.56

**Comment by trotec** [comment]
@shogunpurple  Tested this in budibase 0.9.1 with the web builder, still same issue comes up.

**Comment by shogunpurple** [comment]
Hi @trotec - it seems like it could be part of the DB setup perhaps. Where are you running/hosting your MSSQL DB?

**Comment by trotec** [comment]
> Hi @trotec - it seems like it could be part of the DB setup perhaps. Where are you running/hosting your MSSQL DB?

It is running locally on a VM in the same network. Quick overview: 
 - Budibase docker host | 192.168.0.200
 - MSSQL host | 192.168.0.3
 Subnetmask for both: 255.255.192.0 
They are otherwise able to communicate, I also have a Grafana instance running on the same Docker engine which can successfully connect with the MSSQL server and databases. 

From what I see around, it might be a problem with an  `encrypt` option that should be `false`, like [here](https://www.programmersought.com/article/15786479873/). I can't be sure if that is actually the problem.

**Comment by shogunpurple** [comment]
Managed to recreate - I added the encrypt option and this should now work 👍

**Comment by trotec** [comment]
> Managed to recreate - I added the encrypt option and this should now work 👍

@shogunpurple I updated the images and I can indeed confirm that it is now working as intended. Thank you! 😁
