### ISSUE TITLE
Table setting to display large numbers with commas

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14820]
**Describe the feature request**
Create an option in the table to process number columns with commas to separate thousands.

This would likely make use of `number.toLocaleString()` but it would need to impact the display only, and not actually change the value from `number` to `string`

Currently, the workaround involves a quick formula column, but that approach isn't ideal.

**Screenshots**
![image](https://github.com/user-attachments/assets/f018b039-8ad6-452a-bcf6-3c49de61f253)

**Comment by aptkingston** [comment]
Just going to ship this as the default going forwards because I've often found myself wanting the same thing!

**Comment by mikesealey** [comment]
> Do you reckon there's ever a downside to this?

Would someone ever use a number column to store binary?

Also some European countries use a full-stop where I would use a comma, and a comma as the decimal point.

**Comment by aptkingston** [comment]
> > Do you reckon there's ever a downside to this?
> 
> Would someone ever use a number column to store binary?
> 
> Also some European countries use a full-stop where I would use a comma, and a comma as the decimal point.

Locale string is exactly for this :) it will use the correct delimiter according to whatever the user's locale says - so it will be decimal points instead of commas for Europeans for example.
