### ISSUE TITLE
Automation history pagination changes to disabled state for premium user if filter is selected

### ISSUE THREAD

**Issue by hawkinsjon** [Budibase/budibase#14870]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Digital Ocean
  - Budibase Version: 2.32.10
  - App Version: 2.32.10

**Describe the bug**
As a premium user, I should be able to view up to 30 days of my automation history. 
I'm able to do this as long as I don't touch the filtering options in the automation log area
If any of the filters are selected, the pagination arrow no longer lets me get past page 1

**Screenshots**
Notice when all filter options are showing (ALL) the pagination is accessible. 

<img width="897" alt="Screenshot 2024-10-24 at 2 42 04 PM" src="https://github.com/user-attachments/assets/e161a8c3-0923-426d-9a25-ec2f51090139">

And when even one filter options is selected, pagination is no longer accessible.

<img width="912" alt="Screenshot 2024-10-24 at 2 42 24 PM" src="https://github.com/user-attachments/assets/286c8a53-f8a6-48d7-a049-014f0e9fd5c3">

**Comment by mike12345567** [comment]
This should be fixed in the latest release (2.33.12).

**Comment by hawkinsjon** [comment]
Thanks!
