### ISSUE TITLE
Filtering on relationship fields in automations doesn't work

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#14883]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.33.2
  - App Version: 2.33.2

**Describe the bug**
Automation filtering doesn't work with relationship fields. No automation is ever found. If you apply the same filter to normal non relationship fields the triggers work as intended.

**To Reproduce**
1. Import the below MSSQL schema to a database
2. Import the attached app
3. Change your datasource settings to match your db hosting settings
4. Fetch the tables
5. Create a dummy campaign with the submitted status
6. Publish the app
7. Go to the campaigns screen
8. Click the campaign created
9. Change the status to done
10. View automation history and see no trigger was fired.

**Expected behavior**
Trigger should be fired, and automation should run.

**Screenshots**
## Automation trigger filter
<img width="1240" alt="Screenshot 2024-10-28 at 08 45 41" src="https://github.com/user-attachments/assets/4af3b21c-d7e9-4ce9-b45d-dfffe891096b">
  
**App Export**
[relationship filtering test-export-1730105125444.tar.gz](https://github.com/user-attachments/files/17539801/relationship.filtering.test-export-1730105125444.tar.gz)

**Table create scripts**
```sql
-- Create the Status table
CREATE TABLE Status (
    StatusID INT PRIMARY KEY,                 -- Unique ID for each status
    StatusDescription NVARCHAR(100) NOT NULL  -- Description of each status
);

-- Insert predefined statuses into the Status table
INSERT INTO Status (StatusID, StatusDescription) VALUES
(0, 'Campaign: Idea Submitted'),
(1, 'Campaign: Denied'),
(2, 'Campaign: Needs Work'),
(3, 'Campaign: Approved'),
(4, 'Campaign: Archived'),
(5, 'Campaign: Idea Resubmitted');

-- Create the Campaign table with a foreign key to Status
CREATE TABLE Campaign (
    CampaignID INT PRIMARY KEY IDENTITY(1,1),  -- Unique ID for each campaign
    CampaignName NVARCHAR(100) NOT NULL,       -- Name of the campaign
    StatusID INT,                              -- Foreign key to the Status table
    CreationDate DATETIME DEFAULT GETDATE(),   -- Date when the campaign is created
    LastModifiedDate DATETIME DEFAULT GETDATE(),-- Date of last modification
    FOREIGN KEY (StatusID) REFERENCES Status(StatusID)  -- Setting up the relationship
);
```

**Additional context**
The data area filtering on relationships work, this issue seems to be solely related to the automation filtering trigger.

**Comment by mike12345567** [comment]
For now we have decided that the filtering cannot support relationship fields, we've removed them from the binding options.

The best way to achieve this for the time being is to extract the values you wish to access using a JS binding or the JS scripting step instead.
