### ISSUE TITLE
_id column when working with external SQL DB has encoded id value

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#14885]
When you query a table that is an external sql table, you always get back a column "_id" ammended, but the value in that column is not the value of the id, but rather a string encoded. So , if you attemp to update / delete record using that "_id" added column, the operation will fail as that column doesnt actually exist nor the value in it represents the actual id.

This ammended column, also appears in the "field" property types, to be selected.
![Screenshot 2024-10-28 at 2 43 11 PM](https://github.com/user-attachments/assets/45f8a664-ceb6-43ec-ae3a-a1fa113acb72)

![Screenshot 2024-10-28 at 2 30 55 PM](https://github.com/user-attachments/assets/1f80c3eb-2315-48a6-846f-f66269832bc1)

Is this ammeded column necessary ?
If it is, shouldnt it be holding the same value as the id column ?

**Comment by mike12345567** [comment]
Hi @poirazis - this is intended functionality - Budibase needs the `_id` field to be completely unique, in the case of tables with composite primary keys the only real way to handle this is encoding the contents into a consistent format that we can understand. 

Having multiple formats for this can be quite tricky, so we decided that we should always encode it to follow a consistent format that we can expect no matter if the table has a composite key or not.

I'm going to close out this issue as a change in this area would be quite dangerous and this is fully intended behaviour - if it is causing a problem in the app building experience, please let us know with an enhancement request around the behaviour that it is causing issues with!
