### ISSUE TITLE
Duplicate Public Access roles, Public pages:  Session not authenticated

### ISSUE THREAD

**Issue by SimonDoll** [Budibase/budibase#14893]
**Checklist**
- [ x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.33.4
- Cloud: also affected

**Describe the bug**
The user roles of budibase tables seem messed up (Capitalized vs non-capitalized).
Depending on the app they also change:
![image](https://github.com/user-attachments/assets/4feea881-1606-4b54-b8c2-6f2b1406f6a6)
![image](https://github.com/user-attachments/assets/3785d102-abb1-4437-8e59-029ae25765c1)

It is unclear what the "right" public role is.

When accessing a public page e.g. with a form that writes to a table with public write access this causes a "Session not authenticated" error.
![image](https://github.com/user-attachments/assets/d6cc3832-b008-4aee-8d45-9cb5e6167348)

**To Reproduce**
1. Create a new app, use the visitor-check-in-form template
2. Publish the app
3. Open the app with an unauthenticated browser window
4. See error: (2) Session not authenticated

**Expected behavior**
- Only a single public role
- Always the same default user roles for all apps
- Public pages without access errors

**Screenshots**
  
**App Export**
[form_test-export-1730188668723.tar.gz](https://github.com/user-attachments/files/17553515/form_test-export-1730188668723.tar.gz)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome & firefox

**Comment by ConorWebb96** [comment]
This PR [here](https://github.com/Budibase/budibase/pull/14898) fixes this issue. It will be fixed in the next release of Budibase.

**Comment by SimonDoll** [comment]
Awesome, thanks a lot for the fast response!
Can You estimate when the fix will be available @ConorWebb96?

**Comment by ConorWebb96** [comment]
In around 20-30 minutes, if I had to guess, it might be sooner. @SimonDoll
