### ISSUE TITLE
"Error fetching user group data" on /builder/portal/users/users page

### ISSUE THREAD

**Issue by Seeung** [Budibase/budibase#14890]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: Docker Compose
  - Budibase Version: 2.33.2

**Describe the bug**
After installing not fetched users on `/builder/portal/users/users`, in "network" tab error on request `/api/global/users/accountholder`

**To Reproduce**
1. Install from Docker Compose
2. Open `/builder/portal/users/users` page

**Expected behavior**
View current users.

**Screenshots**
![img](https://github.com/user-attachments/assets/be383dfe-65ee-4e7b-9444-14020293b367)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 132.0b8 

**Additional context**
The bug does not appear if you use Docker Desktop on Windows and there is no request to `/api/global/users/accountholder`.
 - System logs: [system.log](https://github.com/user-attachments/files/17547469/system.log)

**Comment by mike12345567** [comment]
Hi @Seeung - this will be fixed in the next release of Budibase, version 2.33.6.
