### ISSUE TITLE
Improved Routing

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#149]
Right now we use straight up svelte state for routing around the app. 

https://github.com/EmilTholin/svelte-routing is a more robust alternative for this and provides nice routing capabilities. It would also clean up a decent bit of code and make everything a little more modular.

**Comment by kevmodrome** [comment]
There are number of options here that we can consider. The most popular ones are probably the svelte-routing mentioned above as well as [svelte-spa-routing](https://github.com/ItalyPaleAle/svelte-spa-router)and [Routify](https://github.com/sveltech/routify). The first ones are hash-based while Routify is file-based.

The first two ones are pretty much like react-router while Routify is more akin to how Sapper or Next works. There's support for layout files that inherit from their parents, layout resets if you don't want to use a layout, etc. as well as code-splitting and other features pretty much out of the box. The project is highly active and has a Discord server for quick questions. The documentation is a bit [sparse](https://routify-site-feb.now.sh/) at the moment but it should improve significantly over time.

From what I've seen and used I would probably go with Routify.

Regardless of what way we choose to go it would be ideal to clean up the structure of the builder.

**Comment by shogunpurple** [comment]
@kevmodrome Thanks for taking the time to type that up. Routify looks excellent and even has support for routing to modals etc which are quite heavily used in budibase. A few concerns though:

- Routify seems to be in quite active development. This may be an issue as it undergoes potentially large changes as we use it
- Do we sacrifice any functionality by using page based routing? It does seem like routify has pretty solid support for query params, props and slots etc so possibly not.

Otherwise, I think this is also a very good chance to possibly contribute back to the project if and to champion it as a routing solution for svelte apps. It seems like it would fit perfectly for our use case
