### ISSUE TITLE
Formula Colums excluded from dropdown menu in CSV Export Action

### ISSUE THREAD

**Issue by siegbertus420** [Budibase/budibase#14900]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.33.4
  - App Version: 2.33.4

**Describe the bug**
When you want to export only certain columns with the "Export Data" Action, you can't choose Formula Columns. 

**To Reproduce**
1. Create App
2. Create Budibase Table
3. Create Number Column "Factor1"
3. Create Number Column "Factor2"
4. Create Formula Column, put some JS logic inside, e.g. "return $("Factor1") * $("Factor2")"
5. Put some mock rows into the table
6. Create Screen with a Table
7. Add button
8. Add Action "Export Data" to Button
9. Try to select specific Colums
10. See that only the non-Formula-Columns Appear

**Expected behavior**
Alle Colums that are shown on the Table should also be choosable in export

**Screenshots**

<img width="1106" alt="Bildschirmfoto 2024-10-29 um 13 03 32" src="https://github.com/user-attachments/assets/7e60e9ae-0357-407d-b8b6-ddc4245774b2">

<img width="1149" alt="Bildschirmfoto 2024-10-29 um 13 04 22" src="https://github.com/user-attachments/assets/514dce11-22f4-43dc-8752-8e4bcc272a03">

  
**App Export**
[Test App-export-1730203549437.tar.gz](https://github.com/user-attachments/files/17556423/Test.App-export-1730203549437.tar.gz)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version It's definately not a Browser issue

**Comment by ConorWebb96** [comment]
@siegbertus420 What data source are you using? If you are using the internal Budibase data source, is it static or a dynamic filter?

**Comment by siegbertus420** [comment]
Internal Budibase datasource and the Formula Type is dynamic. Does that help?

**Comment by ConorWebb96** [comment]
Can you try deleting and remaking it as a static formula and see if that allows you to export it?<br><br>Dynamic formulas are re-rendered every time its loaded. Static type formulas saves the value and only updates when a row has been changed. <br><br>I think if you try a static formula it like will allow you to export the value.<br><br>Hopefully this makes sense.

**Comment by siegbertus420** [comment]
Okay, I will try that, thank you. Why would you then want to use a dynamic formula?

An BTW: you CAN export the values indeed, as long as you export ALL the colums. You just can’t choose it when you don’t want to export all of them

Am 29.10.2024 um 13:32 schrieb Conor Webb ***@***.******@***.***>>:



Can you try deleting and remaking it as a static formula and see if that allows you to export it?

Dynamic formulas are re-rendered every time its loaded. Static type formulas saves the value and only updates when a row has been changed.

I think if you try a static formula it like will allow you to export the value.

Hopefully this makes sense.

**Comment by ConorWebb96** [comment]
The main difference between these is that dynamics are generated every time a row is read. They aren't actually stored; they are just calculated when a row is seen.

Static is run and saved after amends are made.

I'm glad that this is working for you. Going to close as completed.
