### ISSUE TITLE
May Release Documentation

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1493]
For the single stack release, we need to polish up the documentation. Some key areas:

### General Housekeeping
Remove anything that is no longer relevant from the docs.

### Budibase Setup - DONE
This is the area that you will be taken to from the website. It needs to be clear and structured, showing users how to run, update and manage the platform using the CLI.

### Data Provider
This new component does not have any docs yet. We need use cases, examples and more. We also need to remove any current references to the old component data mechanism.

### Search
The new search functionality and possible operators.

### User management - DONE
- Forgot password
- Reset password

### Budibase Configuration - DONE
- SMTP config. Show how email templates work etc
- Google Auth Config
- Org config. Logo, org name etc

### Deployment, Dev Mode
- How it works
- The lock limitation

**Comment by kevmodrome** [comment]
I've made a Draft on GitBook and documented the user management page as well as the SMTP settings/email templates. Not sure how fleshed out it needs to be.

Some thoughts
- Do we delete the tutorial?
- Do we make short videos to showcase user management, etc?

**Comment by joebudi** [comment]
Yes, we delete the tutorial.
I feel videos should compliment documentation when relevant/describing a common workflow. In your case, a simple video involving adding, removing and updating users would suffice.

**Comment by shogunpurple** [comment]
I'm putting together budibase first time setup documentation. Will update when done!
