### ISSUE TITLE
Update Setting Filtering to -> "No flinters set" even when filters have been set

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14947]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud - miketest1
- AND
- Self - v3.0.0 Docker Single Image

**Describe the bug**
In an existing app that has a cards-block, "Update Setting" conditions are added to change filtering. In the app, there are 6 cases where filtering is updated, all of which have filters established, but all rows show "No filters set".

Showing no fitlers set
<img width="790" alt="image" src="https://github.com/user-attachments/assets/d0af559f-59d6-4cfb-973f-5ddb91bb5429">

When clicking into "no filters set", filters exist
<img width="773" alt="image" src="https://github.com/user-attachments/assets/e1bed9e9-25fa-4d84-bea1-1ef26a2269f4">

**To Reproduce**
Steps to reproduce the behaviour:
Unable to create a fresh app where this occurs - I believe it may be to do with the way v3 Filter Groups interact with established filters.

**Expected behavior**
Button should reflect how many filters are already set.

**Screenshots**
https://jam.dev/c/b3d99d34-1bdb-463c-a182-ea761efb61ff
  
**App Export**
App-export available on request

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**
Issue discovered in a customer's app

**Comment by aptkingston** [comment]
This is almost certainly due to the logic that is counting the filters not accounting for the old structure. It's harmless in that it shouldn't affect functionality, but is very misleading. I can take a look at it.
