### ISSUE TITLE
False error notification when saving change to parent table

### ISSUE THREAD

**Issue by emeany** [Budibase/budibase#14940]
**Checklist**

- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Cloud

**Describe the bug**
When using the 'Save Row' action to update the fields of parent record, an error message is generated (although the record appears to get updated).

The error says 'Null value not allowed for a column'.

If, I duplicate the offending postgres table, and bring it into budibase WITHOUT creating a relationship, I am able to update the record without any errors.

**To Reproduce**

1. create 2 tables, 1 parent, 1 child, and populate each with 1 row
   CREATE TABLE parenttable (
   id bigserial NOT NULL,
   oname text NULL,
   CONSTRAINT parenttable_pkey PRIMARY KEY (id)
   );

CREATE TABLE childtable (    id bigserial NOT NULL,    parentid bigint NOT NULL,    oname text NULL,    CONSTRAINT childtable_pkey PRIMARY KEY (id),    CONSTRAINT childs_parent_fk FOREIGN KEY (parentid) REFERENCES parenttable(id) );

**2. define budibase relationship:**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b73ae2a7-7243-4d69-945c-de2496ef1d32/779cace9-e52b-457b-a308-af2c93d70872?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9iNzNhZTJhNy03MjQzLTRkNjktOTQ1Yy1kZTI0OTZlZjFkMzIvNzc5Y2FjZTktZTUyYi00NTdiLWEzMDgtYWYyYzkzZDcwODcyIiwiaWF0IjoxNzMwODE5MTI0LCJleHAiOjMzMzAxMzc5MTI0fQ.aEqO21CMOSqPzR7IMs-JUMVxAh3WnJo_VKNunzXRRy0 "=328x")

**3. create an update page for 'parenttable'**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ebcbffa2-5098-4a47-9447-34bcc3eee2f7/d10a4d44-829f-4a8b-91b7-2d1f948f0147?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lYmNiZmZhMi01MDk4LTRhNDctOTQ0Ny0zNGJjYzNlZWUyZjcvZDEwYTRkNDQtODI5Zi00YThiLTkxYjctMmQxZjk0OGYwMTQ3IiwiaWF0IjoxNzMwODE5MTI0LCJleHAiOjMzMzAxMzc5MTI0fQ.4rjRSmxsa7h9yqyw-7LaJHmIgKXHys6BQb8YP6juNcc "=315x")

**4. preview in fullscreen, make an edit to the form, and attempt to save** - the error appears, but the data is saved without issue:

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/2cf21cd6-2a4f-4143-a776-6951c7d0afab/8d5bbb7f-4206-472e-b10b-dd97e9d44ac6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8yY2YyMWNkNi0yYTRmLTQxNDMtYTc3Ni02OTUxYzdkMGFmYWIvOGQ1YmJiN2YtNDIwNi00NzJlLWIxMGItZGQ5N2U5ZDQ0YWM2IiwiaWF0IjoxNzMwODE5MTI0LCJleHAiOjMzMzAxMzc5MTI0fQ.TKLlVlcuvcEPN1J2NmYMnR_IDHswXMT97gU9VifhAgM "=314x")

**5. delete the previously defined budibase relationship and again attempt to edit/save the form** - row is saved without error notification:

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/2a751ff3-29e3-4548-89f2-967ba40e598e/57e843cf-f1cc-4c1e-92fb-06b5770119bd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC8yYTc1MWZmMy0yOWUzLTQ1NDgtODlmMi05NjdiYTQwZTU5OGUvNTdlODQzY2YtZjFjYy00YzFlLTkyZmItMDZiNTc3MDExOWJkIiwiaWF0IjoxNzMwODE5MTI0LCJleHAiOjMzMzAxMzc5MTI0fQ.HVBt42ZIgESkhRAhz20Q8rziwwCEJD5T5pGoQo08sA0 "=311x")

**Expected behavior**
The record should be saved/updated without error notification.

**Comment by emeany** [comment]
Some additional info:

I am also unable to make edits to the tables directly within the data tab:
<img width="314" alt="image" src="https://github.com/user-attachments/assets/4a77d2b5-cf52-45e5-8065-27ba5e7b50a4">

I AM able to create a NEW row however, and subsequent edits to this new row DO NOT throw an error. 

The error only exists when editing records with a 'child' record.

also note that I am unable to 'break' the existing relationships from within the data tab (I receive the same error)

**Comment by emeany** [comment]
I was able to find a 500 error related to the 'child' table (interests):
<img width="880" alt="image" src="https://github.com/user-attachments/assets/7b5e426c-6966-4499-b622-5fe46445e20f">

**Comment by emeany** [comment]
Please let me know if there is any way I can assist!

**Comment by dagelf** [comment]
> Please let me know if there is any way I can assist!

Yes, you can start reading and grepping the source code, like what I am doing now.....

**Comment by adrinr** [comment]
This has been fixed in the release [3.2.15](https://github.com/Budibase/budibase/releases/tag/3.2.15)
