### ISSUE TITLE
SSO Bad Gateway with SSO "guests"

### ISSUE THREAD

**Issue by SimonDoll** [Budibase/budibase#14943]
**Hosting**
- Cloud
  - Version: 2.33.14
 
**Describe the bug**
SSO allows identity management, e.g. using Auth0.
When using "guest users" in Auth0 e.g. by connecting Microsoft Entra ID the login in Auth0 works but the redirect to budibase returns a 502 in cloudflare.

**To Reproduce**
1. setup SSO with Auth0
2. Add a connection in Auth0 to Microsoft Entra ID
3. Try login in Budibase, select Auth0, in Auth0 select Microsoft -> Login
4. Redirect to Budibase fails with 502 (ends in cloudflare)

**Expected behavior**
Login should succeed and end as logged-in user in budibase

**Screenshots**
![image](https://github.com/user-attachments/assets/4c8f3a1d-90f9-456e-b146-f4100ff8cabc)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**
Maybe the issue is related to https://github.com/Budibase/budibase/discussions/5550, since the multi-tenant SSO might cause different issuer values depending on whether Auth0 or Microsoft Entra is used for the login although both run through Auth0.

**Comment by shogunpurple** [comment]
@SimonDoll can you try again? We have fixed this in cloud

**Comment by SimonDoll** [comment]
Hey @shogunpurple,
Thanks a lot for looking into this.
Do I need to upgrade the SSO config, or can I just directly test it within the budibase cloud?

**Comment by shogunpurple** [comment]
@SimonDoll cloud will already be updated - so should just work out of the box

**Comment by tdh-claude** [comment]
@coneillpj, if you using self hosted version of Budibase, you must check NGINX parameters.
You can check this --> https://docs.budibase.com/docs/reverse-proxy
