### ISSUE TITLE
v3 AI Config issue

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#14958]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 3.0.2
  - App Version: 3.0.2

**Describe the bug**
Using a update form shows AI settings realted errors but nothing is using any AI. The errors was showing an error something like 'Error: No AI Config' so I went to settings where the /builder/portal/settings/ai was shown as default and I added a provider to see if that would fix it. Then I got the message 'Error: No config selected as default AI config',
![image](https://github.com/user-attachments/assets/f6ac9fc7-1172-4d0f-a841-60e98fb85bed)

I have tried to go back to settings to set the AI provider as default but it won't allow that and shows this message.
![image](https://github.com/user-attachments/assets/d4b4da1f-e988-4f2a-a406-0f3b02754ce6)

I've only found this on the first form I have tried after updating an app to 3.0.2 so nothing else has changed and I'm not going to continue with any others yet in case they break

**Comment by shogunpurple** [comment]
Hi @andyburgessmd - looking into this, this feature should be feature flagged and not required if there's no AI config. Must be something to do with paid tiers. Will keep you updated. Best to roll back for now if you are on the premium plan

**Comment by andyburgessmd** [comment]
@shogunpurple rolled the app back but still shows this error

**Comment by andyburgessmd** [comment]
@shogunpurple 3.0.3 has fixed it. Thanks
