### ISSUE TITLE
Mistakingly importing a plugin as an app throws and error and crashes the build locally. Doesn't affect cloud, just errors.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#14977]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 3.0.3
  - App Version: 3.0.3

**Describe the bug**
When attempting to import a tar.gz file for a plugin instead of just erroring. It completely crashes the server.

**To Reproduce**
1. Download a plugin as a tar
2. Import the plugin as an app

**Expected behavior**
It should just error out telling the user its not an app export or some other generic message.

**Screenshots**
<img width="632" alt="Screenshot_2024-11-05_at_09 54 29" src="https://github.com/user-attachments/assets/02df6ccb-188f-46a6-8a43-4ec2cb6f740a">
  
**App Export**
Import any plugin from the plugins [repository](https://github.com/Budibase/plugins)

**Comment by mike12345567** [comment]
Should be fixed on master.
