### ISSUE TITLE
Chart data not displaying as per query designed

### ISSUE THREAD

**Issue by pldmayer** [Budibase/budibase#1499]
**Describe the bug**
Chart not showing query that was designed

**To Reproduce**
1. Link to External MYSQL 5.7 Database
2. add chart to screen
3. create simple query with order by clause
4. See Chart starts at april and not Jan as per query added

**Expected behavior**
Lable on graph should represent the chart as per designed query, Label should be from Jan to Dec adn not start at April

**Screenshots**
![Screenshot 2021-05-17 194226](https://user-images.githubusercontent.com/33716628/118534806-f375a080-b749-11eb-8c45-28af70791fd2.png)
![Screenshot 2021-05-17 194145](https://user-images.githubusercontent.com/33716628/118534852-038d8000-b74a-11eb-9c2c-15d7f4e852dc.png)
![Screenshot 2021-05-17 194250](https://user-images.githubusercontent.com/33716628/118534868-08523400-b74a-11eb-831c-3b08f383c156.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**

**Comment by aptkingston** [comment]
Hi @pldmayer. Currently the charts sort data by their X axis (label column) which is usually desired for time series data, but not in all cases as you've highlighted. Our release coming out next week has huge improvements in it for searching and sorting data, which will let you sort your data however you want and have that properly reflected in charts.

**Comment by shogunpurple** [comment]
Closing as will be addressed by dataprovider updates :+1:
