### ISSUE TITLE
Automation - Cannot specify month of December in expression

### ISSUE THREAD

**Issue by f4iey** [Budibase/budibase#14993]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 3.1.3
  - App Version: 3.1.3

**Describe the bug**
Cannot specify any cron expression including the month of december in automations: the folliwing message appears: `Error: number 12 of 'months' is greater than 11`

**To Reproduce**
1. Go to Automation
2. Create an automation with cron expression
3. nter an expression which includes December, such as `0 0 16 12 *`

**Expected behavior**
12 should NOT return an error and include the month of December.

**Screenshots**
![image](https://github.com/user-attachments/assets/97e2324d-306c-4456-852f-dc7d1e8d1580)
![image](https://github.com/user-attachments/assets/6524d9dc-7abc-48df-809b-7d3eb653b245)

  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser Firefox
 - Version latest

**Comment by mike12345567** [comment]
Hi @f4iey - sorry about that - a slight difference between our validation and parsing - validation was looking for months as 0-11!
Fix will be in next release of Budibase.
