### ISSUE TITLE
Mariadb View - No way to remove / fix link to modified table column

### ISSUE THREAD

**Issue by acseven** [Budibase/budibase#15008]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 3.2.0
  - App Version: 3.2.0

**Describe the bug**
When working with MySQL/MariaDB datasources, if a View has a field that is modified directly in the database, it's not possible to fix the issue. The only possibility is to delete the view and recreate it again. 

**To Reproduce**
1. Add a view to a MySQL table using a specific column
2. Modify the column name in the MySQL table
3. See error when opening the view in budibase. 

**Expected behavior**
At least an option to remove or modify the erroneous connection instead of just removing the view.

**Screenshots**

![image](https://github.com/user-attachments/assets/1771fd3c-26f5-417d-8bae-1f56bcdc478c)

  
**App Export**

**Comment by ConorWebb96** [comment]
Hey @acseven,

What happens when you re-fetch your tables? Is this still broken after doing this?

**Comment by ConorWebb96** [comment]
Closing as there was no response and couldn't replicate.
