### ISSUE TITLE
Form component displays _id(s) instead of the display column values for related tables

### ISSUE THREAD

**Issue by otichy** [Budibase/budibase#15005]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: ffuk

**Describe the bug**
I have authors, titles and title_author tables with n:n relationship between authors and titles (via supabase/postgres). In the data tables or in the table element, the multiple records of authors on the title or multiple titles on the author are displayed correctly by the selected display column (e.g. authors.full_name and titles.title), can be added, deleted etc. But on the form element, the multiple records are displayed by the _id column. New records can be searched and added, but the old ones cannot be deleted (both in design and preview).

**To Reproduce**
Create an n:n relationship of two tables via a third one where multiple records from one table are associated with a record in the second table. Set display columns. Generate a table with edit modal form or a form. Open the form and check the field with multiple related records.

**Expected behavior**
The form should have the multiple related records displayed by the display column and it should allow the deletion of those records.

**Screenshots**
Records for titles in the authors table correctly displayed
![image](https://github.com/user-attachments/assets/fba74ccc-1b6a-4af7-9ca3-7619afe75115)

Records for titles in the authors form incorrectly displayed as _ids
![image](https://github.com/user-attachments/assets/3b514757-bfab-4002-b63c-e30463a1bb1c)

  
**App Export**
I am happy to export, but should I encrypt it?

**Comment by otichy** [comment]
Here is an export of the app, see the "test" screen "titleForm".
[ibiblio-export-1731615516518.tar.gz](https://github.com/user-attachments/files/17757328/ibiblio-export-1731615516518.tar.gz)

**Comment by aptkingston** [comment]
Thanks for the export @otichy. I've got it and can reproduce the issue. I've just deleted your comment with the export as it contains credentials to your Supabase Posgres DB.

**Comment by mike12345567** [comment]
Hi @otichy closing this issue as we believe it is related to one central problem we are tracking, we have created [this issue](https://github.com/Budibase/budibase/issues/15062) which you can use to track progress on the fix for this issue.

**Comment by otichy** [comment]
OK, brilliant. And would it help in my specific case if I changed the types of my id columns from int8 (that's the current type in supabase) to something else, e.g. int4?

**Comment by otichy** [comment]
> Hi @otichy - yes, if you remove all big int (`int8` and above) from your schema it is likely that it would work without issue.

Hi, thanks, is there any way to do this without having to rebuild everything from scratch? If I simply change the datatype (to int4) in my source db (supabase/postgres) and refetch the tables, the type stays bigint in budibase. And I can't change the type in budibase itself.

**Comment by otichy** [comment]
Unfortunately, even with the former int8 columns changed to int4 in the source PostgreSQL/supabase showing now as Number type id budibase, the original problem persists.
