### ISSUE TITLE
The CORS error when making requests to the Budibase API from the client

### ISSUE THREAD

**Issue by hypeoplestudio** [Budibase/budibase#15041]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker
  - Budibase Version:3.2.5
- Cloud
  - Tenant ID: hytest

**Describe the bug**
We want to use Budibase for backend management in our React project, but we are getting a CORS error when making requests from the client. As an alternative, we installed Budibase locally on our machine and ran it on localhost:10000, and even though we added the CORS origin settings as environment variables in the Docker Compose files, we are still encountering the CORS error.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version 1.73.89 Chromium: 131.0.6778.69 (Resmi Derleme) (arm64) Sürümü

**Comment by mike12345567** [comment]
Hi @hypeoplestudio - what API are you trying to use? There shouldn't be CORS errors if you utilise the public API - the internal API should experience CORS errors, that is intentional.

**Comment by hypeoplestudio** [comment]
> Hi @hypeoplestudio - what API are you trying to use? There shouldn't be CORS errors if you utilise the [public API](https://docs.budibase.com/docs/public-api) - the internal API should experience CORS errors, that is intentional.

Hello @mike12345567 , we encountered a CORS error when using the public API. To address this issue, we created a backend with Express.js and started using it. The requests sent from the client are routed through the API we prepared with Express.js to Budibase's public API.

**Comment by olion500** [comment]
@mike12345567 does this resolve cors error?
I updated the Budibase version 3.2.27 but still got an error.

**Comment by mike12345567** [comment]
Hi @olion500 - what API were you hitting? This only disables CORS errors if using one of the public API endpoints and connecting to it with an API key.

**Comment by olion500** [comment]
I hit the endpoint like this:
```
http://localhost:10000/api/public/v1/tables/ta_d2561c59ae37413292ae66ac1eb07cb3/rows/search
```

Is it one of the public API endpoints?
I followed the [docs about public API](https://docs.budibase.com/docs/public-api) and it requires an API key in the request header.

**Comment by mike12345567** [comment]
Hi @olion500 - that looks correct, locally if I make a request like that in Postman I'm getting the correct CORS headers as I'd expect back:

![image](https://github.com/user-attachments/assets/ecdfd549-c96a-408e-bef3-55a049143ddc)

Can you tell me what request is failing to provide the correct CORS information?

**Comment by vUdav** [comment]
I have a same problem with access to https://budibase.app/api/public/v1/ from browser.

I'm create a new project on cloud Budibase, create a new table. Make an access to this table is public. Make api instance on axios package with headers: x-budibase-api-key, x-budibase-app-id. In Postman all is good, but I catch a CORS error in any browser when I test it on my localhost Vue project.

This is my axios config
```js
// plugins/budibase.js
import axios from 'axios';

const baseDomain = import.meta.env.VITE_BUDIBASE_API_URL;
const apiKey = import.meta.env.VITE_BUDIBASE_API_KEY;
const appId = import.meta.env.VITE_BUDIBASE_APP_ID;

const baseURL = `${baseDomain}`;
const instance = axios.create({
  baseURL,
});

instance.interceptors.request.use(
  (config) => {
    config.headers['x-budibase-api-key'] = apiKey;
    config.headers['x-budibase-app-id'] = appId;

    return config;
  },

  (error) => {
    return Promise.reject(error);
  },
);

export default instance;
```

Example for send api request:
```js
import budibaseApi from '@/plugins/budibase.js';

budibaseApi.post(`tables/ta_caa2723f987c48338fca4e6cd2481b90/rows/search`, {});
```

cURL (I'm hide my api-id and api-key)
```bash
curl 'https://budibase.app/api/public/v1/tables/ta_caa2723f987c48338fca4e6cd2481b90/rows/search' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'x-budibase-app-id: *****' \
  -H 'Referer: https://localhost:5173/' \
  -H 'sec-ch-ua: "Chromium";v="135", "Not-A.Brand";v="8"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'DNT: 1' \
  -H 'Content-Type: application/json' \
  -H 'x-budibase-api-key: *****' \
  --data-raw '{}'
```

**Comment by vUdav** [comment]
Okay, today I tried to use Budibase SelfHost, installed it to my dev server and I'm get CORS error on my localhost again.

I think you need to add a special config settings for trusted domains. Because in my case I want to install Budibase on my server and I need have access from other domains (for example localhost, dev and prod). I think Budibase sefhost users should be able to decide what domains they trust for Rest API data transfer.
