### ISSUE TITLE
Values are not passed correct in the automation test screen

### ISSUE THREAD

**Issue by feurer98** [Budibase/budibase#15059]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose 
  - Budibase Version: 3.2.11.
  - App Version: 3.2.11.

**Describe the bug**
When testing the automation, the last value is displayed. However, this is not passed in the search.
With the same values but freshly entered, the search returns a row.

![image](https://github.com/user-attachments/assets/c636b04a-2542-4d76-822c-256ba42e61f4)

![image](https://github.com/user-attachments/assets/e1283917-4dc1-444c-a79d-ae7ef1822c81)

![image](https://github.com/user-attachments/assets/0ee37e2e-076e-4da0-b2a6-5455bee513cb)

**Comment by feurer98** [comment]
screen recording:

https://github.com/user-attachments/assets/90cf7f0f-9ca7-45d5-b3a8-3ab4a5c9237a

**Comment by gravyplaya** [comment]
I am also having the same issue.
