### ISSUE TITLE
Relationship-based formula display names inconsistent across linked tables

### ISSUE THREAD

**Issue by joachimBrindeau** [Budibase/budibase#15099]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists
- [X] I have tried different formulas to change format (without [], without special characters, etc.)

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: <3.2.16.>
  - App Version: <3.2.16>

**Describe the bug**
I have a formula field as display name of table A.

The formula field is calling for a relationship in table B :
`[{{ compte.0.nom }}] {{ service.0.id_interne }} : {{ description }}`

<img width="566" alt="image" src="https://github.com/user-attachments/assets/e1678162-7cf7-4016-94ee-09544d1bd110">

If I check table B, I can see complete names.

If I try to link records to table A from another table (_e.g._ table C), the display name appears incomplete. The values from linked records don't appear at all.

<img width="203" alt="image" src="https://github.com/user-attachments/assets/a0807497-d077-4082-a5ed-70c90a18efbc">

**To Reproduce**
1. Create a table A with a relationship field 1 to table B
2. Set the primary display in table A to be a formula referencing the relationship field 1
3. In table C, create a relationship field 2 to table A

**Expected behavior**
I expected the display name for records in table A everywhere in the app, to show the exact same value as when I open table A.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : Arc
 - Version : 1.70.0 (56062)

**Comment by mike12345567** [comment]
Hi @joachimBrindeau - sadly this is a limitation of Budibase today, one that would be very difficult to fix. We only enrich one level of relationships when pulling back rows, so in this case when in table C you pull back the related rows in table A, it will not have its relationships to table B.

Sadly this is not something that can be easily changed without severe performance implications for Budibase.
