### ISSUE TITLE
Change "Record" to "Model", "Index" to "View" and "Instance" to "Database" 

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#151]
We have decided that the name "record" is a confusing term. This is for 2 reasons:
- A "record" in a SQL database represents a row
- Our definition of record is more like a table schema.

"Records" will now be known as "models" inside budibase. 

The same is also true for indexes. Indexes represent "views" of data, and the terminology has been a source of confusion.

#### Tasks
- Update the docs to change records to models
- Update the docs to change indexes to views
- Update the docs to change instances to databases
- Update anywhere in the code that makes references to records to be references to models
- Update anywhere in the code that makes references to indexes to be references to views
- Update anywhere in the code that makes references to instances to be references to databases

**Comment by kevmodrome** [comment]
I'm a bit unsure what happens with the old "model" stuff, does it stay the same? I can imagine there being some confusion here

**Comment by kevmodrome** [comment]
Record -> Model should be done.

Some work done on Index to View.
