### ISSUE TITLE
Columns dont show up in data view

### ISSUE THREAD

**Issue by gravyplaya** [Budibase/budibase#15133]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Self-hosted Docker

**Describe the bug**
I have FirstName and LastName text fields in my local Budibase DB. When viewing the data on the data screen or table view the values dont show up. but when I export the DB or create a new view they do. SO I kno the data is in there. 

**To Reproduce**
1. Go to data view and view the table. FirstName and LastName columns are empty
2. Create a new view from the same data and the columns show up. 

**Expected behavior**
Columns data is populated and shows

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: latest

**Comment by mike12345567** [comment]
Hi @gravyplaya - can you confirm which version of Budibase you are self-hosting? Also did you update recently, we will need this information to help diagnose this problem.

**Comment by gravyplaya** [comment]
Version: 3.2.1
I last updated November 11th.

**Comment by mike12345567** [comment]
Hi @gravyplaya - can you try updating to latest, there has been quite a few bug fixes around this area since that release.

If that doesn't work, can you provide an app export which exhibits this behaviour? It will be very hard to replicate otherwise.

**Comment by gravyplaya** [comment]
That seems to have worked. Thanks.
