### ISSUE TITLE
Cannot read properties of undefined (reading 'schema')

### ISSUE THREAD

**Issue by JBSDS** [Budibase/budibase#15139]
Hello everyone,

I'm facing an issue since I updated Budibase: I upgraded from version 2.32.11 to the latest available version (above 3.0 ). After this update, I started encountering the following error whenever I use filters that reference "relationships" in the database :

Cannot read properties of undefined (reading 'schema').

For context, I am using MySQL as my database.

I tested a downgrade to version 2.32.11 , and everything works fine in this version. However, my goal is to move to the latest version to take advantage of the new features and improvements. 🙄

Has anyone else encountered this issue ? Or does anyone have ideas on how to diagnose/fix this problem ? Any help or guidance would be greatly appreciated ! 🙏

Thank you in advance for your feedback

```
{
  "browser": {
    "language": "fr-FR",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "platform": "Win32",
    "vendor": "Google Inc."
  },
  "server": {
    "budibaseVersion": "3.2.25",
    "hosting": "docker-compose",
    "nodeVersion": "v20.18.1",
    "platform": "linux",
    "cpuArch": "x64",
    "cpuCores": 32,
    "cpuInfo": "13th Gen Intel(R) Core(TM) i9-13900K",
    "totalMemory": "31.22834014892578GB",
    "uptime": "0 day(s), 7 hour(s), 36 minute(s)"
  }
}

```
![Capture d’écran 2024-12-08 125700](https://github.com/user-attachments/assets/9c290c49-589e-4d9a-877f-e279bace26d4)

**Comment by WoisWoi** [comment]
I'm also having this problem.

**Comment by mike12345567** [comment]
Hi @WoisWoi and @JBSDS - would it be possible to provide a schema for a database which exhibits this behaviour? You can export this using the following functionality in Budibase: https://docs.budibase.com/docs/troubleshooting-sql#sql-schema-export

**Comment by JBSDS** [comment]
Hi @mike12345567, here is the database schema.
[MySQL-dump (1).zip](https://github.com/user-attachments/files/18083675/MySQL-dump.1.zip)

**Comment by mike12345567** [comment]
Hi @JBSDS - from this schema I've been unable to find anything that demonstrates the same issue you are seeing - would it be possible for you to provide an app export which demonstrates this issue - or provide steps for the relationship and filter setup which creates this scenario?

**Comment by JBSDS** [comment]
Hi @mike12345567 , I updated to version 3.2.28 of Budibase, but I haven't noticed any difference. I'm not sure if this version was supposed to resolve the issue. 
Thank you for your help. 🙂

**Comment by mike12345567** [comment]
Hi @JBSDS - the fix has been merged but not released yet - I'll update this issue once the release goes out next week.

**Comment by JBSDS** [comment]
It works, thank you! 🙂
