### ISSUE TITLE
Nodemon server crash when importing an encrypted app

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#15187]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 3.2.28
  - App Version: 3.2.28

**Describe the bug**
This is going to get a bit meta, so bear with me... When importing an encrypted app-export that has been downloaded more than once (and is reflected in the filename `App1-export-1734343803020.enc (1).tar.gz`) the builder crashes, and server logs show an error with Nodemon `@budibase/server: [nodemon] app crashed - waiting for file changes before starting...`

**To Reproduce**
[App1-export-1734344844143.tar.gz](https://github.com/user-attachments/files/18148500/App1-export-1734344844143.tar.gz)

1. Import the above app, descriptively named "App 1"
2. View the only screen it contains in preview (or published app) and click the button to download the attached app
3. Click again to download the app _again_
4. You should now have `app1-export-[numbers]enc.tar.gz` and `app1-export-[numbers]enc.(1)tar.gz`
5. Try importing the app - password is twelvecharacters (firstly the original, then the duplicate (1))

**Expected behaviour**
Should import the app or fail gracefully

**Screenshots**
(Don't mind the incorrect password on the first import-attempt)
https://jam.dev/c/9c8349ba-ca7e-49a3-966f-129138557394

![image](https://github.com/user-attachments/assets/4c4f946a-cd1e-40ef-9055-a1d1116b2540)

  
**App Export**
[App1-export-1734344844143.tar.gz](https://github.com/user-attachments/files/18148500/App1-export-1734344844143.tar.gz) - see "Steps to Reproduce"

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**

**Comment by mike12345567** [comment]
Should be fixed on master!
