### ISSUE TITLE
Bindings generated from webhooks output as null rather than the object they are meant to reference.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#15188]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 3.2.28
  - App Version: 3.2.28

**Describe the bug**
For example, this is a generated binding `{{ trigger.parameters }}` To get the actually values you need to do something like this instead `{{ trigger.fields.body.parameters }}`

**To Reproduce**
1. Go to the automation tab
2. Click the webhook automation type
3. Setup your schema
4. Post an object to the webhook
5. Try and use the binding generated via the schema.
6. See it will return null if used.

**Expected behavior**
Clicked bindings in the automation binding drawers should work without having to change it.

**Comment by mike12345567** [comment]
Will be fixed in next release.
