### ISSUE TITLE
Users screen - text i dont understand...

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1525]
"Users are the common denominator in Budibase". This makes very little sense to me. 

![image](https://user-images.githubusercontent.com/3524181/119130735-7d668780-ba30-11eb-9579-27697f45cc07.png)

**Comment by shogunpurple** [comment]
It just means they are the most important entity in the platform. I agree though that it doesn't really add anything there though. I'll remove that sentence!
