### ISSUE TITLE
Min wiidth of a column in a table component is 80px. Is there any way to make it smaller?

### ISSUE THREAD

**Issue by neojigi** [Budibase/budibase#15259]
When I have a large number of columns and I want to display them all on one screen without scrolling left and right, I have a lot of trouble because of the width min value limitation.

I know there is a great plugin called SuperTable. But it has some bugs that make me reluctant to use it.

Is there any way to make the size of each column smaller in the main table component with css or something? (I'm a beginner in programming)

**Comment by aptkingston** [comment]
What sort of width are you trying to use? We can definitely shrink the minimum a bit.

**Comment by neojigi** [comment]
The initial width in the column settings (gear icon) of the table component does not go below 80px.

Furthermore, when I try to manually adjust the column width of the table on the preview screen or the published screen, I cannot reduce it further than the 80px.

So I thought maybe the minimum column width is set to an absolute value.

Am I doing something wrong? T.T

**Comment by aptkingston** [comment]
I've opened a PR (linked above) to shrink the minimum width from 80 to 56px. That's really the minimum before we can't even fit in the required icons any more. Hope that helps!

**Comment by neojigi** [comment]
This will be a great help! Happy New Year!

**Comment by MarceloArraes** [comment]
We need something to make everything more compact.
