### ISSUE TITLE
Newly invited user cannot update details

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1529]
**Steps**
1. Logged in as super admin, invite a new user
2. Accept invitation, and log in as new user
3. Update personal details (i.e. name)

results in an error upon `POST http://localhost:10001/api/admin/users/self`
```
message: "Invalid body - \"roles\" is required"
status: 400
```

**Comment by aptkingston** [comment]
Where did you update the personal details? Was it on the "normal user" home screen, or in the portal? Can't seem to reproduce this one.

**Comment by mjashanks** [comment]
Here: 
![image](https://user-images.githubusercontent.com/3524181/119147871-e4416c00-ba43-11eb-8d14-8478a27b2263.png)

"Update user information"

It works with my existing super admin user... just not the new user.

**Comment by mjashanks** [comment]
Wait, it just worked... i think i know why.

It works now because I added this user to an app - i.e. the user has roles now

**Comment by kevmodrome** [comment]
Sounds like we just need to add an empty roles object to the user when they're created 👍

**Comment by aptkingston** [comment]
It sounds like the user is created without any `roles` property, but whenever I create a new user they do correctly get default to `roles: {}`... Did you use the email onboarding? Maybe that makes a difference.

**Comment by kevmodrome** [comment]
This makes me think of an enhancement we might want to do - do we want to add a "Development access" toggle when the admin creates the new user?

**Comment by mike12345567** [comment]
I thought about this, in theory we could have a bunch of stuff written to redis as part of the invite, when the user accepts we pull all the details from redis and attach them to the user. However for the time being I think we can get by without this as the admin can simply update the user with the permissions they should have once they have accepted the invite.

I think this will be a lot more important once we have a full groups implementation, as admins will likely want to invite users directly into groups.

**Comment by kevmodrome** [comment]
Good point! 👍

**Comment by mike12345567** [comment]
Added a feature to set a user to a builder/admin before sending invite - for now considering this resolved.
