### ISSUE TITLE
My app does not load either inside the builder, or in full preview

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1531]
I Created a new app and added a single table, with auto generated screens.

1. Go into design - preview does not show. Console error:
![image](https://user-images.githubusercontent.com/3524181/119145651-c3781700-ba41-11eb-8571-8bc591286293.png)

2. Open preview (view Play button) - nothing shows.
Console error: 
![image](https://user-images.githubusercontent.com/3524181/119145538-a6434880-ba41-11eb-9b7d-af3020baf45b.png)

**Comment by shogunpurple** [comment]
@mjashanks I can't seem to repro this one - were you able to recreate it consistently?

**Comment by mjashanks** [comment]
Yea - I created a new app and its happening with that one too. Are we still pulling `@budibase/client` from npm? Maybe it's not published?

**Comment by shogunpurple** [comment]
If you are running the prod version from the CLI, then yeah we haven't published the latest NPM packages yet. I'm trying to repro against the most up to date code using `yarn dev`

**Comment by mjashanks** [comment]
ah right, that will be it then.
