### ISSUE TITLE
Have given app access to a user, but they dont get access

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1532]
Gave this new user ADMIN access to an app:
![image](https://user-images.githubusercontent.com/3524181/119146319-6a5cb300-ba42-11eb-85f9-fae751e0a5fe.png)

...but the user does not have access:

![image](https://user-images.githubusercontent.com/3524181/119146392-7ea0b000-ba42-11eb-874b-048b60d7a5b7.png)

Cant help thinking that it's related to #1529 which suggests that the Roles are messed up for the user.

**Comment by kevmodrome** [comment]
This should also be fixed in the latest master, builder access is turned on or off with the `Development Access` toggle
