### ISSUE TITLE
Development access toggle does nothing

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1534]
In the Users list, the `Development Access` toggle does nothing. Also - it's not clear to me whether the box is actually checked or not - it's hard to see.

The 2 look the same, so I assume its filled in. In which case, my new user has automatically got development access, without me setting it - however my new user cannot access development mode.

![image](https://user-images.githubusercontent.com/3524181/119149067-0edff480-ba45-11eb-8763-ab0a05c9da88.png)

**Comment by kevmodrome** [comment]
Fixed on latest master
