### ISSUE TITLE
When i preview my app, the wrong app is presented

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1551]
**Describe the bug**
When I preview my app, the wrong app is presented.

https://user-images.githubusercontent.com/49767913/119486701-7604ee00-bd50-11eb-850f-49b037a329d4.mov

**Comment by shogunpurple** [comment]
Try clearing cookies etc and seeing if you can reproduce - there might be an overhang from the previous versions of BB.

**Comment by shogunpurple** [comment]
Should be resolved - unable to recreate now in staging and local 👍
