### ISSUE TITLE
binding not working in automations when using CRON trigger and causes builder to crash

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1553]
**Describe the bug**
When I add a CRON trigger to an automation and subsequently add additional actions, I can not use the binding functionality within those actions, and the builder crashes.

**To Reproduce**
1. Go to automations
2. Click on CRON trigger
3. Click on send email action
4. Try to bind, and experience the errors

**Comment by shogunpurple** [comment]
Good catch - I see the issue. Will fix and push

**Comment by shogunpurple** [comment]
Should now be resolved
