### ISSUE TITLE
Getting an error when updating record which includes the one side of a one to many relationship

### ISSUE THREAD

**Issue by kahennig** [Budibase/budibase#1560]
**Describe the bug**
Hi, just getting started here with budibase. I am using the new web-editor.
I've created two tables and everything worked fine until I added a new column of type _relationship_
Now I get the following error when updating an existing record on the one side of the one to many relationship:

1:N Relationship Error: Record already linked to another.

while the log shows:

`app-service_1      | ERROR [1621978727963] (28 on aa42b11557e3): 1:N Relationship Error: Record already linked to another.
app-service_1      |     Error: 1:N Relationship Error: Record already linked to another.
app-service_1      |         at LinkController.rowSaved (/app/src/db/linkedRows/LinkController.js:226:21)
app-service_1      |         at runMicrotasks (<anonymous>)
app-service_1      |         at processTicksAndRejections (internal/process/task_queues.js:97:5)
app-service_1      |         at async Object.exports.updateLinks (/app/src/db/linkedRows/index.js:103:14)
app-service_1      |         at async Object.exports.patch (/app/src/api/controllers/row.js:100:9)
app-service_1      |         at async exports.save (/app/src/api/controllers/row.js:144:5)
app-service_1      |         at async /app/src/api/index.js:44:5
app-service_1      |         at async /app/src/api/index.js:30:5
app-service_1      |         at async /app/node_modules/koa-compress/lib/index.js:38:5
app-service_1      |         at async /app/src/app.js:48:7
app-service_1      | Trace: Error: 1:N Relationship Error: Record already linked to another.
app-service_1      |     at LinkController.rowSaved (/app/src/db/linkedRows/LinkController.js:226:21)
app-service_1      |     at runMicrotasks (<anonymous>)
app-service_1      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
app-service_1      |     at async Object.exports.updateLinks (/app/src/db/linkedRows/index.js:103:14)
app-service_1      |     at async Object.exports.patch (/app/src/api/controllers/row.js:100:9)
app-service_1      |     at async exports.save (/app/src/api/controllers/row.js:144:5)
app-service_1      |     at async /app/src/api/index.js:44:5
app-service_1      |     at async /app/src/api/index.js:30:5
app-service_1      |     at async /app/node_modules/koa-compress/lib/index.js:38:5
app-service_1      |     at async /app/src/app.js:48:7
app-service_1      |     at /app/src/api/index.js:53:15
app-service_1      |     at runMicrotasks (<anonymous>)
app-service_1      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
app-service_1      | INFO  [1621978727963] (28 on aa42b11557e3): request errored
app-service_1      |     res: {
app-service_1      |       "statusCode": 500,
app-service_1      |       "headers": {
app-service_1      |         "vary": "Accept-Encoding",
app-service_1      |         "content-type": "application/json; charset=utf-8",
app-service_1      |         "content-length": "84"
app-service_1      |       }
app-service_1      |     }
app-service_1      |     err: {
app-service_1      |       "type": "Error",
app-service_1      |       "message": "failed with status code 500",
app-service_1      |       "stack":
app-service_1      |           Error: failed with status code 500
app-service_1      |               at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:73:38)
app-service_1      |               at ServerResponse.emit (events.js:326:22)
app-service_1      |               at ServerResponse.EventEmitter.emit (domain.js:483:12)
app-service_1      |               at onFinish (_http_outgoing.js:735:10)
app-service_1      |               at onCorkedFinish (_stream_writable.js:673:5)
app-service_1      |               at afterWrite (_stream_writable.js:490:5)
app-service_1      |               at afterWriteTick (_stream_writable.js:477:10)
app-service_1      |               at processTicksAndRejections (internal/process/task_queues.js:83:21)
app-service_1      |     }
app-service_1      |     responseTime: 82
app-service_1      |     req: {
app-service_1      |       "id": 1446,
app-service_1      |       "method": "POST",
app-service_1      |       "url": "/api/ta_60853a8d9e1c4abfb4d6e316a5ec40b2/rows",
app-service_1      |       "headers": {
app-service_1      |         "host": "localhost:10000",
app-service_1      |         "content-length": "697",
app-service_1      |         "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\"",
app-service_1      |         "x-budibase-app-id": "app_dev_741723e7ec2b42619daceb77b9a25fc9",
app-service_1      |         "sec-ch-ua-mobile": "?0",
app-service_1      |         "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
app-service_1      |         "content-type": "application/json",
app-service_1      |         "accept": "*/*",
app-service_1      |         "origin": "http://localhost:10000",
app-service_1      |         "sec-fetch-site": "same-origin",
app-service_1      |         "sec-fetch-mode": "cors",
app-service_1      |         "sec-fetch-dest": "empty",
app-service_1      |         "referer": "http://localhost:10000/builder/app/app_dev_741723e7ec2b42619daceb77b9a25fc9/data/table/ta_60853a8d9e1c4abfb4d6e316a5ec40b2",
app-service_1      |         "accept-encoding": "gzip, deflate, br",
app-service_1      |         "accept-language": "es-UY,es;q=0.9,en-US;q=0.8,en;q=0.7,de-DE;q=0.6,de;q=0.5,pt-1BR;q=0.4,pt;q=0.3",1. 
app-service_1      |         "cookie": "PGADMIN_LANGUAGE=en; server-time=1609622197261; session-expiry=1609629397261; region1_configure_menu=none; region3_registry_menu=none; region4_monitor_menu=none; region5_tools_menu=none; MSG16110663656090.6251101703936099=true; MSG16110669175080.030599877315691693=true; menuPanel=visible; menuPanelType=main; MSG16110695852100.04184698578154322=true; MSG16110703941340.37450244306368174=true; MSG16110704012980.9158568296602752=true; MSG16110902590980.752925912793156=true; MSG16110904523930.5643390328205151=true; MSG16110904752100.09830839754762222=true; requestedURI=../../carbon/identity-claim-mgt/list-external-claims.jsp?externalClaimDialectURI=urn%3Aietf%3Aparams%3Ascim%3Aschemas%3Aextension%3Aenterprise%3A2.0%3AUser; JSESSIONID=2B5F04C43C3BD9901C7FCE1D7D03056B; current-breadcrumb=%2523%252Bindex.jsp*; MSG16111491698970.4107373713915645=true; connect.sid=s%3AqRSZvY23IGebygUa-qARSu5IAXsTWV3E.WtIymxrGq6jcOK%2BL0S1%2F%2Ff7%2Foj5SWDhlX3PLMT7YyTE; budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c19hZDcxZDZiOGJjYzA0MmFjYTg1YzIzMjgyMmNmYWMyYiIsImlhdCI6MTYyMTk1Mzk2MCwiZXhwIjoxNjIyMDQwMzYwfQ.YBbIHZjBK5tRsH-p8r0xaDF7jE26sj0SIDdyztSCBcs; budibase:currentapp=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImFwcF9kZXZfNzQxNzIzZTdlYzJiNDI2MTlkYWNlYjc3YjlhMjVmYzkiLCJyb2xlSWQiOiJBRE1JTiIsImlhdCI6MTYyMTk1Mzk5OCwiZXhwIjoxNjIyMDQwMzk4fQ.XEMHTcQbqiHHbNTWsE7BMHxMjrUjuGhhIeTpX4DB8K4; budibase:currentapp:local=app_dc566e3a2ecb45479003838c21d38c52",
app-service_1      |         "x-forwarded-proto": "http",
app-service_1      |         "x-request-id": "56eeb0b0-2da1-419f-aaef-be1cd5ff93f7",
app-service_1      |         "x-envoy-expected-rq-timeout-ms": "15000"
app-service_1      |       },
app-service_1      |       "remoteAddress": "::ffff:172.17.0.8",
app-service_1      |       "remotePort": 39872
app-service_1      |     }

**To Reproduce**

1. create a couple of tables 
2. add a one-many relationship between them
3. create an entry one the one side (don't associate anything on the many side - there's no thing to associate yet) 
4. create an entry on the many side (associate the entry created in 3.
5. go back to the entry created in 3 and edit it. No need to change anything. Just hit save.

Find my project in attachment
[export.zip](https://github.com/Budibase/budibase/files/6542549/export.zip)

If you try my project you can just do step 5 in the "Pacientes" table.
Edit the single entry available and hit save.

Thanks

**Comment by mike12345567** [comment]
Hi @kahennig - I had a look at this, as far as I could tell everything appeared to be working as expected, I was wondering if you could give me a bit more info around this?

I created a new app and followed these steps:
1. Created two tables and created display columns for them
2. Created a relationship between them and picked a cardinality direction (which table was the one, which was the many)
3. Created rows in each
4. Created links between rows, it appeared the one side was only able to link with one record and the many could link with many unlinked rows.

I also tried downloading your export and giving it a go in your app myself, but the export didn't appear to be valid. Is it possible your Budibase deployment is out of date or something like that?

**Comment by kahennig** [comment]
Thank you for your reply @mike12345567 I am running Budibase from the containers. The environment was sat up about two weeks ago via the docker-compose.yaml file. I just looked into docker.io and there is a very recent new version of the apps image. I'll recreate the setup from the updated images and report back.

**Comment by kahennig** [comment]
I'm back @mike12345567. 
Ok. So it worked. That is to say... it still fails in my original project even after deleting the tables and re-creating them. Fortunately I decided to try and create a new project :) and that worked. There's something broken in my original project is seems.
Thank you so much for your help.

PS: Quick question, about every how often are new images being pushed to docker.io? Just to have an idea, so I keep my environment up to date.

**Comment by mike12345567** [comment]
Hi @kahennig glad you got it sorted! 

In terms of new image updates we update fairly regularly, you can expect new images minimum once a week, likely more often!

Generally we will make a point about big releases with large feature sets via twitter, github and email - we also plan to integrate updates + notification of updates available into the builder UI to make this process a lot more seamless.

We may even consider automated updates for bug fixes, however this is still to be decided.

**Comment by kahennig** [comment]
Thanks @mike12345567. I'll stay alert to new images.

> we also plan to integrate updates + notification of updates available into the builder UI to make this process a lot more seamless.

That is a feature that _portainer_ offers and it's how I stay ontop of it's updates. Very handy feature.

Thanks again for your help.
