### ISSUE TITLE
Feature Request: Scheduled data source refresh

### ISSUE THREAD

**Issue by kevev** [Budibase/budibase#1572]
A killer feature to add would be an "Auto-Refresh Timer" field added to the data source configuration. This would allow automatic data source refreshes. This feature would allow for creation of Live Dashboards for monitoring.

**Comment by aptkingston** [comment]
Thanks for the suggestion @kevev. This could definitely make sense for applications like live dashboards and isn't hard to implement.

**Comment by joebudi** [comment]
I am converting this to a discussion, and labeling idea 👍
