### ISSUE TITLE
Google OAuth merge fails

### ISSUE THREAD

**Issue by jwillmer** [Budibase/budibase#1573]
I created a new instance of budibase and used my email `admin@example.com` to create an admin account. I then configured Google OAuth. I logged out and tested Google OAuth by selecting `Sign in with Google`. In the Google user selection I selected my email `admin@example.com`. The login worked but I only have user permissions. After logging out once more I tried to login with my user and password (not OAuth) and get `Invalid credentials`. Resetting the password via email reset link also does not work. After typing in a new password I get a `400` error.

I think the two accounts (Local and Google) are not merged properly and I can't login to my local account anymore because Budibase tries to use the Google account instead and fails.

**Comment by shogunpurple** [comment]
Thanks for the report @jwillmer - will dive into this and have a look.
