### ISSUE TITLE
Login with user, after "Force password reset" causes infinite loop

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1575]
**To Reproduce**

1. As admin user, go to another user's detail screen : `Users > Click on User`
2. Click on `Force Password Reset`
3. Copy Password
4. Open private browsingg, login with new password

Gives a blank screen, network tab has this

![image](https://user-images.githubusercontent.com/3524181/119842951-05500400-beff-11eb-8785-e458ffd7109a.png)

**Comment by shogunpurple** [comment]
Fixed in https://github.com/Budibase/budibase/pull/1574

**Comment by mjashanks** [comment]
ha that was quick

**Comment by shogunpurple** [comment]
sorry, I didn't mean to close it as well lol!

**Comment by mike12345567** [comment]
lmao sorry I found this earlier today, just didn't mention it yet - will be merged in a sec :)
