### ISSUE TITLE
Change logo in Organisation fails

### ISSUE THREAD

**Issue by timconsidine** [Budibase/budibase#1576]
**Describe the bug**
Can't change logo after initial saving

**To Reproduce**
Save logo initially
Reload page
All fine
Go to organisation / settings
Delete the logo and replace with different
Or just upload a different
Save button
Message shows : settings saved
Reload page
Original logo still showing

**Expected behavior**
New logo should appear

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux ubuntu self-hosted
 - Browser:  opera and safari
 - Version : who knows ?? doesn't show anywhere : latest from fresh docker install 26/5/21

**Additional context**

**Comment by timconsidine** [comment]
Maybe worth mentioning in passing that a custom logo has some strange sizing applied
It's fine if it's a regular e.g. 100x100 logo
But a wider logo e.g. 100x500 logo is used, it gets shrunk to fit, so it renders as 20x100
Just example sizes as concept
If there are logo size constraints, they should be announced on settings page

**Comment by shogunpurple** [comment]
@timconsidine thanks for the detailed bug report. Is this still happening on the latest version? I'm unable to recreate with images, but wondering if you are maybe getting an error when you upload yours. Could you send the contents of the dev console when this occurs?

**Comment by timconsidine** [comment]
Thank you.
I started and stopped the self-hosted Budibase server, but it didn't seem to pull down any new versions, maybe it doesn't show in terminal.
Yes, it is still happening.
The first uploaded logo still shows.
Even if I delete it, press SAVE, switch to eg Theming, switch back to Organisation, first0uploaded still shows.
So delete it, upload a new one, new one shows, press SAVE, change screen again and back, first uploaded logo still showing.

`
Refused to execute script from 'https://domain.uk/prod-budi-app-assets/app_5297d27d63944e4db195777c9264cade/budibase-client.js' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.
/api/layouts:1 Failed to load resource: the server responded with a status of 409 ()
about:srcdoc:1 Refused to execute script from 'https://domain.uk/prod-budi-app-assets/app_5297d27d63944e4db195777c9264cade/budibase-client.js' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.
`

This is the same error message I get with #1579
I think #1579  is still an open issue, so I can't do anything to design because I can't see results of anything.

**Comment by timconsidine** [comment]
If you can tell me how to make budibase-client.js executable or disable strict MIME type checking, I can try again.
Or would it be some file/directory permissions ?  root vs www-data

**Comment by shogunpurple** [comment]
@timconsidine does this one still occur given the conversation we had on https://github.com/Budibase/budibase/issues/1579?

**Comment by timconsidine** [comment]
Mostly yes still a problem
I did just successfully change from one test logo to another.
But then changing it again to a different test logo, it claims to have changed it (Grren message flash settings saved successfully).  In the Organisation screen, the new logo shows.
But it's not true : the logo at top left does not update, and switching between screen sections or reloading the page doesn't update

**Comment by timconsidine** [comment]
Further testing shows that maybe it needs a full forced screen reload (not just normal page reload)

**Comment by timconsidine** [comment]
And further testing shows that a normal page sometimes works, sometimes it needs force page reload .... but it never works without some kind of page reload.

**Comment by aptkingston** [comment]
This sounds like a browser caching issue, becuase the URL for the logo is always the same. We could maybe append a random URL parameter to the request to ensure the logo is always pulled fresh from the server. I expect this sort of behaviour will vary quite a lot between different OS's and browsers.
