### ISSUE TITLE
Required bool field errors on record save

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1580]
**Describe the bug**
When saving a record inside my app, if I do not complete a required bool field an exception is thrown and my record is not saved

**To Reproduce**
1. Create required boolean field
2. Add field to a form on Create Record
3. Preview the app
4. Create new record - don't touch the checkbox!
5. Save record

RESULT
Record validates correctly, Screen navigates back to list screen, but error banner appears. Record is not saved

EXPECTED
Actually, I'm not sure...

Is it right that a validation message should appear? If you want the checkbox the remain unchecked, then you must check and uncheck

Maybe it makes no sense for a boolean field to be required? It should default to `false` always?

Or do we need a tri-state checkbox, that has a true, false and  Nothing state?

**Comment by Fabian1410** [comment]
Its also not possible to create a row with the automation (webhook)
