### ISSUE TITLE
some issued with data in the 0.9 release 

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#1587]
Hi Guys, I am finding a lot of the data connections in automatons do not work in this new update, along with a few other things. 

1) I can not get a web hook to fire i keep getting this error
![image](https://user-images.githubusercontent.com/80058238/120003657-cf586180-bf8a-11eb-9f39-851fba1eb87f.png)

2) The trigger external database query dos not have any of my actual connections in it it is only showing old connections, 
![image](https://user-images.githubusercontent.com/80058238/120003839-f7e05b80-bf8a-11eb-9707-262606ad8b74.png)

3) When submitting a form I can not leave the date field blank without it erroring out the query, it will save internally but wont write to my PostgreSQL DB externally  
![image](https://user-images.githubusercontent.com/80058238/120004092-383fd980-bf8b-11eb-8a77-388be9843917.png)

4) There also seams to be a problem with value limits and required for example: I can not submit my form with these fields blank. 
![image](https://user-images.githubusercontent.com/80058238/120004549-c2883d80-bf8b-11eb-95bc-ae91615a75e7.png)

as you can see here I am not requiring a value for the column so I should not be stopped by a null value.  also if I hit submit in the form and it tells me i can not submit because these values cant be null, i then input the given values and submit. it will save to internal DB but it will fail the external DB query  
![image](https://user-images.githubusercontent.com/80058238/120004709-f19eaf00-bf8b-11eb-9a31-93fedf7db566.png)

5) I can not duplicate a button in the design tab I have a fair amount of things going on with the click and would like to have two buttons with just minor navigation differences. cant get it to duplicate like the other items. 
![image](https://user-images.githubusercontent.com/80058238/120005516-c072ae80-bf8c-11eb-9076-aa97c7af8b77.png)

let me know if you want more info on any of these /  cant preproduce them. 
I am running your new platform 0.9 on docker on Linux mint 20. I am using a self hosted PostgreSQL DB on the same machine.

**Comment by mike12345567** [comment]
I've looked through all of these issues:
1. this has been fixed as of latest release
2. I wasn't able to reproduce this issue in latest release
3. the new SQL system for using SQL tables like we use internal tables solves this issue
4. this has been fixed in latest release
5. I was unable to replicate this issue in latest release, there has been a lot of fixes around duplication, copy paste etc
