### ISSUE TITLE
SQL EXPRESS Database - Not connecting using Localhost but connecting by WSL adapter IP

### ISSUE THREAD

**Issue by Manishkparmar80** [Budibase/budibase#1589]
While running query to SQL EXPRESS Data Source , i am getting below mentioned error. 

![5](https://user-images.githubusercontent.com/84949590/120058714-90014200-c06a-11eb-9bb5-f29027949a8c.jpg)
![1](https://user-images.githubusercontent.com/84949590/120058716-9394c900-c06a-11eb-8235-4bf2baee533c.jpg)
![1](https://user-images.githubusercontent.com/84949590/120058806-f1291580-c06a-11eb-8856-2f868f887a33.jpg)

**Comment by Manishkparmar80** [comment]
I am running your new platform 0.9 on docker on Windows 10. I am using a self hosted latest MS SQL EXPRESS on the same machine.

**Comment by shogunpurple** [comment]
Thank you, I replied to your (duplicated) question under discussions as well.

I think your server option is wrong. localhost\\SQLEXPRESS doesn’t look like a valid host name. Try changing it to localhost

**Comment by Manishkparmar80** [comment]
I have changed server option to localhost. Now i am getting different error.
![11](https://user-images.githubusercontent.com/84949590/120078302-7b559600-c0cc-11eb-889f-1fdebbf7d9b6.jpg)
![12](https://user-images.githubusercontent.com/84949590/120078311-86102b00-c0cc-11eb-86a1-221010782b21.jpg)
![13](https://user-images.githubusercontent.com/84949590/120078316-8c060c00-c0cc-11eb-92bc-25db32db2f84.jpg)

**Comment by Manishkparmar80** [comment]
Just to update. i tried changing Localhost to WSL adapter IP and it got connected successfully !!!
**Pls. fix the bug why it is not connecting via localhost.  WSL adapter IP is dynamic so keep on changing so it is not permanent solution.** 
![21](https://user-images.githubusercontent.com/84949590/120090245-a10b8b00-c11e-11eb-85dc-98242feb2327.jpg)
![22](https://user-images.githubusercontent.com/84949590/120090258-aff23d80-c11e-11eb-9947-4740e6829a8d.jpg)

**Comment by Manishkparmar80** [comment]
This need to be kept open.

**Comment by shogunpurple** [comment]
@Manishkparmar80 is it possible that this is the issue you are having?

https://github.com/Budibase/budibase/discussions/1839

Let me know if any of that works for you.

**Comment by Manishkparmar80** [comment]
@shogunpurple yes, i wrongly reopen this issue. You can close the issue, it is already resolved. I apologies for inconvenience.

**Comment by mrjk05** [comment]
Seem to be getting this same issue when trying to connect to an RDS instance in a private VPC.
Setup:
- Budibase installed on EC2 inside private VPC
- Security Groups setup to allow connection from EC2 to RDS in same private VPC
- Connection can be established
- However when trying to fetch schema - error occurs

![Screen Shot 2021-08-04 at 4 29 02 pm](https://user-images.githubusercontent.com/9178352/128132876-f85a1e00-7983-49dc-94e7-07137ae51b28.png)

**Comment by mrjk05** [comment]
@shogunpurple ☝️ I think this needs to be reopened, unless there is anything you can help with? Cheers!

**Comment by shogunpurple** [comment]
@mrjk05 thanks for raising. Could you possibly show me the output from that failing request in the browser dev console? I'm wondering if there's a more specific error, that would help to debug what is going on. Thanks!
