### ISSUE TITLE
Blank screen when previewing app

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1592]
**Describe the bug**
When I preview my app, I am presented with a blank screen, and no app.

**To Reproduce**
1. Add data
2. Design app
3. Preview
4. See blank page

**Expected behavior**
A preview of my app should appear

**Screenshots**
![Screenshot 2021-05-30 at 15 28 55](https://user-images.githubusercontent.com/49767913/120108133-c074d900-c15b-11eb-990b-345bef5b1e1b.png)
=

**Additional context**
![Screenshot 2021-05-30 at 15 29 16](https://user-images.githubusercontent.com/49767913/120108146-cc609b00-c15b-11eb-8c29-33f704fb373f.png)
![Screenshot 2021-05-30 at 15 29 37](https://user-images.githubusercontent.com/49767913/120108157-d97d8a00-c15b-11eb-90da-194901d1c4f4.png)
![Screenshot 2021-05-30 at 15 30 16](https://user-images.githubusercontent.com/49767913/120108175-f0bc7780-c15b-11eb-96ae-d9e3a7dde214.png)

**Comment by aptkingston** [comment]
The issue there is the 404 of the budibase-client file, which I can't seem to reproduce... The URL looks correct and I thought we'd fixed that issue. There's another issue which gives you a similar screen and is caused by the server returning no subpaths when the client fetches the routes definition, and that's being investigated.

**Comment by shogunpurple** [comment]
Thanks for the detailed bug report.

I uploaded a new client lib to your app which should fix the design issue, but the actual preview is still not working as expected. Due to the fact your app just broke overnight, I think this might have had something to do with a new minIO image being pulled yesterday, which watchtower pulled automatically. I've prevented it from pulling anything but the worker + app images now, so that shouldn't happen again.

This and your other issue are manifestations of the same thing, I believe. Will keep digging into the preview issue and see if I can reproduce it.

**Comment by shogunpurple** [comment]
Ah, I actually realised the issue there with my preview was that I didn't have the right role on your app. I gave myself admin rights and your app works fully for me now. We will need to identify how that client lib got lost, but I'm almost certain it was the MinIO update that did it.

**Comment by mike12345567** [comment]
Very odd, its possibly something to do with the MinIO volume as well? I'd be shocked if an image update didn't warn of a migration requirement etc and ended up with all data being wiped, I wonder if it occurred across the entire system or if it was just one app? (since they are all in the same bucket I would expect it to affect equally)

**Comment by shogunpurple** [comment]
It looks like the entire key for Joes app was missing in MinIO when I queried it with the AWS CLI - everything else was there. All the other apps seemed to be fine. Odd indeed

**Comment by mike12345567** [comment]
hm very odd indeed! Could have been an issue during deployment, that'd be my best guess, although if it was working initially thats likely out too!

**Comment by aantn** [comment]
I'm encountering a similar issue, but don't have any interesting logs in the javascript console.
It started after I deleted the home page as I wanted to make one of my other pages the home page.

This is what the home page looks like:
![image](https://user-images.githubusercontent.com/494087/122396144-5f813980-cf80-11eb-8adb-76e3dc7fb85f.png)

If I browse to another URL which I know exists then I see the menus only:
![image](https://user-images.githubusercontent.com/494087/122396349-935c5f00-cf80-11eb-9505-e0d252dcd9a6.png)

**Comment by shogunpurple** [comment]
Hi @aantn - when you created the new page that was to be your homepage, did you set the route to `/`?

That seems like it could be the issue here.

**Comment by aantn** [comment]
@shogunpurple yes, but something seems to be fundamentally messed up. All pages are empty even in the designer

![image](https://user-images.githubusercontent.com/494087/122397503-b2a7bc00-cf81-11eb-96b6-16ab9b848257.png)

**Comment by aantn** [comment]
Attaching logs from `budibase/worker`
```
yarn run v1.22.5
$ node src/index.js
Worker running on {"address":"::","family":"IPv6","port":4003}
ERROR    [1623894871193] (29 on e954ca36a96a):
    err: {
      "type": "ForbiddenError",
      "message": "Unauthorized - no public worker access",
      "stack":
          ForbiddenError: Unauthorized - no public worker access
              at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
              at /app/src/api/index.js:61:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@budibase/auth/src/middleware/authenticated.js:63:14
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/koa-compress/lib/index.js:38:11
      "status": 403,
      "statusCode": 403,
      "expose": true
    }
    req: {
      "id": 2,
      "method": "GET",
      "url": "/api/admin/users/self",
      "headers": {
        "host": "localhost:10000",
        "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
        "x-budibase-app-id": "",
        "sec-ch-ua-mobile": "?0",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36",
        "content-type": "application/json",
        "accept": "*/*",
        "sec-fetch-site": "same-origin",
        "sec-fetch-mode": "cors",
        "sec-fetch-dest": "empty",
        "referer": "http://localhost:10000/builder",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.9,he;q=0.8",
        "cookie": "__wzd3969e67c2069ed1e20e9=1609667675|a629565905ed; __wzde5a5bb2779e548894764=1609676461|53008f4b180d; __wzd8c651fec51c1584859c4=1609676992|6a4d76446cbb; _ga=GA1.1.1393183301.1610291992; rxVisitor=1612545397583PODIN5L7UPADCPVAMHH8855J5KBA0QMM; dtCookie=v_4_srv_4_sn_53FAAA97DA80F3833548F464DF5ED0B1_perc_100000_ol_0_mul_1_app-3Aea7c4b59f27d43eb_1; dtSa=-; rxvt=1612547351030|1612545397585; dtPC=4$345550669_804h-vRPQAFUOFHFKBMMHLHFIJFFUOJTJJESMW-0e3; dtLatC=1; tilt-interface-version=; Tilt-Token=f948a50f-b169-4b21-b94b-82ebc395c8de; grafana_sess=5ff1e6952841c310; session=.eJy9UF1PwjAU_Sumz4x13QdsiYliDIiKIhCCL03Zylbp2mXt0AX577agxhcTn3xpcs_Hved0DzBpdAGPL2drLKRIKQYJoE90tLyP2_Vkvh0w_3Y2zW9AB7y8alyRlkuSgWQPaEkYN2pChBbtRW7HbipLozxSeEdrtmHUiHXd0A7YkJLxFgtSUmNbUc6ZMOKc7aj4QidEEwtymRJuAWqnn-TZt1GwdPvJnDIYrGKpbmoLFVpXKnFdXvjdXMqc00bROpVCU6FtTpc47uVD4QXDfDpGOzVTw-UgVz3i81W1eHu83jGn9dS4ba7uRqpenKs4clJzQzVrs_-005H299C754Uw6sPAj8Kwh_wgggiGRttUGdE0w0QbC4LIc2DgIDSH_SSMk8Dvwhg9g4MJXssNs433v7T9j2Z2D2bZH9sdDh_oIbx4.YIE7Aw.OT8ZRUv1kT9anZ-Enfk19bC3CrI; argocd.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjI5ODA1MjksImp0aSI6ImY5ZTRmYjRlLTExMDItNGVjMC05ODczLThlZDcxNDhhNWMyNiIsImlhdCI6MTYyMjg5NDEyOSwiaXNzIjoiYXJnb2NkIiwibmJmIjoxNjIyODk0MTI5LCJzdWIiOiJhZG1pbjpsb2dpbiJ9.Y5RtEXSeuQYPpgPQ-4CGT9_XgIYtJhi0hT9_3jdSCgA; grafana_session=05001fdb51ac2093e7c1f65ca791b648; _gid=GA1.1.1975058587.1623852852; ph_Oeq9KzIpZYaNsXIvHw5QTZWNpfiG_EOjAOpjTyAiitY_posthog=%7B%22distinct_id%22%3A%20%2217a17ad40171d3-00087d17a56d83-3373266-1fa400-17a17ad4018527%22%2C%22%24device_id%22%3A%20%2217a17ad40171d3-00087d17a56d83-3373266-1fa400-17a17ad4018527%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D",
        "x-forwarded-proto": "http",
        "x-request-id": "83b42e68-6d36-4e66-bb29-ab03429ac738",
        "x-envoy-expected-rq-timeout-ms": "15000",
        "content-length": "0"
      },
      "remoteAddress": "::ffff:172.18.0.9",
      "remotePort": 40272
    }
ERROR    [1623894886444] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623908181949] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623908186681] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623908190789] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623909851928] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623909860204] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623909861486] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623931704268] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623932257232] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
ERROR    [1623932358878] (29 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
Server Closed
Server Closed
yarn run v1.22.5
$ node src/index.js
Worker running on {"address":"::","family":"IPv6","port":4003}
ERROR    [1623934409713] (28 on e954ca36a96a): No configuration exists.
    BadRequestError: No configuration exists.
        at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
        at exports.find (/app/src/api/controllers/admin/configs.js:93:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async /app/src/api/index.js:70:5
        at async /app/node_modules/koa-compress/lib/index.js:38:5
```

**Comment by shogunpurple** [comment]
Thanks @aantn that's helpful. I'll debug this one and see if we can recreate. Thanks for the report.

**Comment by aantn** [comment]
Thanks, let me know. I've "bricked" my Budibase app for now :(

**Comment by cwrau** [comment]
I'm getting the same error;

```
err: {                                                                                    
  "type": "ForbiddenError",                                                               
  "message": "Unauthorized - no public worker access",                                    
  "stack":                                                                                
      ForbiddenError: Unauthorized - no public worker access                              
          at Object.throw (/app/node_modules/koa/lib/context.js:97:11)                    
          at /app/dist/api/index.js:106:18                                                
          at dispatch (/app/node_modules/koa-compose/index.js:42:32)                      
          at /app/node_modules/@koa/router/lib/router.js:368:16                           
          at dispatch (/app/node_modules/koa-compose/index.js:42:32)                      
          at /app/node_modules/@budibase/backend-core/src/middleware/csrf.js:45:14        
          at dispatch (/app/node_modules/koa-compose/index.js:42:32)                      
          at /app/node_modules/@koa/router/lib/router.js:368:16                           
          at dispatch (/app/node_modules/koa-compose/index.js:42:32)                      
          at /app/node_modules/@budibase/backend-core/src/context/FunctionContext.js:21:11
  "status": 403,                                                                          
  "statusCode": 403,                                                                      
  "expose": true                                                                          
```

Just on a completely new and empty installation 😕

Accessing budibase redirects me a couple of times and then I land back on the login page

The only thing I did was create the admin user 😅

**Comment by ivanvanderbyl** [comment]
I've got the same issue after a fresh install using helm on K8s.

**Comment by Pieter0313** [comment]
I'm experiencing the same issue currently. I'm on version 1.0.110

**Comment by snookie** [comment]
Same here!

Fresh install with https://github.com/Budibase/budibase/blob/master/hosting/docker-compose.yaml (and .env).

docker-compose up shows:

`
ERROR [1653315733105] (27 on 83fe6c0483bd):
    req: {
      "id": 20,
      "method": "GET",
      "url": "/api/global/self",
      "headers": {
        "host": "mensalo01",
        "connection": "close",
        "cache-control": "max-age=0",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36",
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "accept-encoding": "gzip, deflate",
        "accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
        "cookie": "budibase:init=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTMwMzM5MjZ9.l00jmv2je7VtDvSkEMTfI1x9d8MTah_qn5fN0KVReV8; budibase:init.sig=C5Q-czoPLMxSfq8tVVgSYtfNlUw; budibase:auth.sig=TtF2vr1t8BkrZmpwdKkWsShYOgw; budibase:auth=; budibase:currentapp=; budibase:returnurl=/builder"
      },
      "remoteAddress": "::ffff:172.29.0.9",
      "remotePort": 59020
    }
    err: {
      "type": "ForbiddenError",
      "message": "Unauthorized - no public worker access",
      "stack":
          ForbiddenError: Unauthorized - no public worker access
              at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
              at /app/dist/api/index.js:109:18
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@budibase/pro/dist/index.js:1:316772
              at Generator.next (<anonymous>)
              at /app/node_modules/@budibase/pro/dist/index.js:1:3817
              at new Promise (<anonymous>)
              at j (/app/node_modules/@budibase/pro/dist/index.js:1:3562)
      "status": 403,
      "statusCode": 403,
      "expose": true
    }
` 



docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019



Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:23 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
