### ISSUE TITLE
Design screen (iframe) is blank

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1593]
**Describe the bug**
I was working on building an app on Sat. It was fine, but I could not preview the app (blank screen, raised issue). On Sunday I turned on the computer, clicked the budibase tab, navigated to the design section, and the iframe/screen was blank.

**Expected behavior**
I expect the app to be presented within the iframe/screen so I can continue with the design.

**Screenshots**
![Screenshot 2021-05-30 at 15 34 52](https://user-images.githubusercontent.com/49767913/120108414-ef3f7f00-c15c-11eb-9707-ebd611c3a61c.png)
![Screenshot 2021-05-30 at 15 37 47](https://user-images.githubusercontent.com/49767913/120108431-febec800-c15c-11eb-8fe4-1dfba92502da.png)

**Additional context**
Within this app, I have over 7000 records within my internal table.
A number of components are mising.

**Comment by shogunpurple** [comment]
Closing as now resolved.
