### ISSUE TITLE
Published blank white page without generated views

### ISSUE THREAD

**Issue by hamzamu** [Budibase/budibase#1601]
**Describe the bug**
Hello, I am testing Budibase to write a snap review about it, When I publish my apps, the published views turned a blank white page.

**To Reproduce**
1. Go to "Design", create some views or use the default views.
2. Click on "Publish"
3. View the published page
4. A blank white page.

**Expected behavior**
See the generated app views.

**Screenshots**

![Screenshot from 2021-06-01 10-52-13](https://user-images.githubusercontent.com/340579/120287185-b1ab3500-c2c7-11eb-94a6-095513ac6852.png)

**Desktop (please complete the following information):**
 - OS:  Linux (Zorin) Ubuntu based
 - Browser Google Chrome
 - Version 91.0.4472.77

**Additional context**
We are interested to solve this issue to keep testing the system, as we like Budibase approach and interested to write a review about it for our readers.

**Comment by kevmodrome** [comment]
Hey! Thanks for the bug report. This is a bug that we're working on, in the meantime you can work around this by setting a role on your user manually in the Portal. Like so:

![roles](https://user-images.githubusercontent.com/534488/120290812-f97b8d80-c2c2-11eb-898f-9a84a54b3321.png)

**Comment by hamzamu** [comment]
Wow, It works, Awesome. Please let us know when will you fix the bug.

**Comment by mike12345567** [comment]
Fix is in PR #1605 will be merged and released shortly.
