### ISSUE TITLE
Create relationship - radio buttons UI bug - Firefox/Linux

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1611]
When creating a relationship: 
![image](https://user-images.githubusercontent.com/3524181/120485347-ea243f00-c3ab-11eb-943c-e1c7c4e87350.png)

on Firefox & Ubuntu

**Comment by aptkingston** [comment]
I could have sworn I fixed this already... Is your environment definitely up to date? It's fine for me on Ubuntu and Firefox now.
![image](https://user-images.githubusercontent.com/9075550/120985878-ee69a700-c773-11eb-8ab8-fd8211d1503a.png)

**Comment by aptkingston** [comment]
Looks like the control was changed to a radio group, which needs the same fix as checkboxes. The control used to be checkboxes I think.
