### ISSUE TITLE
Relationship to users not displaying in table

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1612]
I created a relationship to the user table. The relationship does not display in the row.

![image](https://user-images.githubusercontent.com/3524181/120488257-851e1880-c3ae-11eb-9a79-f569f75cd83f.png)

1. Create relationships to users table (I used "One user has many tickets")
2. Create/update rows, and set relationship
3. Press `Save Row`

**Comment by kevmodrome** [comment]
I'm seeing this issue in one of my apps again

**Comment by Mitch-Budibase** [comment]
I have replicated the above steps:

1. Create relationships to users table (I used "One user has many tickets")
2. Create/update rows, and set relationship
3. Press Save Row

I am still seeing this issue.

The relationships to the users are only sometimes displayed

**Comment by mike12345567** [comment]
No longer can replicate issue, appears to have been resolved by another un-related fix.

**Comment by gvlx** [comment]
I cannot it see them in the data list, but they are present on the record.

**Comment by mike12345567** [comment]
Hi @gvlx - I gave this another go locally (development version) and in the Cloud environment, I can see the relationships in the data view in both, I was wondering if you could give me a bit more info about your scenario?
