### ISSUE TITLE
Budibase not getting installed on Microsoft Windows Server 2016 Docker 

### ISSUE THREAD

**Issue by Manishkparmar80** [Budibase/budibase#1619]
**While installing Budibase on Microsoft Windows Server 2016 Standard Operating system Docker, i am getting following error:**

Budibase Error Version in ".\docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**My Docker & Composer version is mentioned below :** 
PS D:\BudiBase> docker-compose --version
docker-compose version 1.9.0, build 2585387

PS D:\BudiBase> docker --version
Docker version 20.10.5, build 105e9a6

**Enclosed copy of docker-compose.yaml and docker-error.log for your reference.** 
[Re__1.zip](https://github.com/Budibase/budibase/files/6590666/Re__1.zip)

**Comment by shogunpurple** [comment]
@Manishkparmar80 it is as the error says - you need to upgrade your docker-compose version to 2.0.
