### ISSUE TITLE
Unable to get past 'Create your first app'

### ISSUE THREAD

**Issue by philwakefield** [Budibase/budibase#1623]
**Describe the bug**
New install of Budibase - the pop up 'Create your first app' does not disappear after either importing an app or creating a new one. I can access the apps by URL but cannot get to the app list screen

**To Reproduce**
Steps to reproduce the behaviour:
1. New Budibase builder on Digital Ocean Docker Droplet (updated 5pm Thursday 3rd June '21)
2. Create super admin
3. Login
4. Import app (attached for ref) - may not have imported the first time but did 2nd time
[export (1).txt](https://github.com/Budibase/budibase/files/6593544/export.1.txt)
5. Create new app

**Expected behavior**
Import or new app removes popup and access list of apps

**Screenshots**
![image](https://user-images.githubusercontent.com/52033908/120693146-8e87ad80-c4a0-11eb-99cb-453e763dd81a.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/52033908/120693292-bd9e1f00-c4a0-11eb-866f-b4b18974e362.png)

**Comment by mike12345567** [comment]
Hi @philwakefield - I walked through the steps that you also followed, importing your `export (1).txt` - this did correctly create the app and the new app showed up on the screen.

I deleted this app and tried creating an app fresh which also worked.

I was wondering if there was anything else you could tell me about the steps to re-produce? Right now I've tried a few things and it seems to all work fine.

**Comment by philwakefield** [comment]
I have rebuilt the droplet and it seems to no longer be a problem. I suspect this was due to a failed import (first attempt didn't seem to work)
