### ISSUE TITLE
Issue with email templet links needs to point to an ip not local host 

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#1626]
On the email templates I can not change the IP address for the {{ inviteurl }}. I am not using a host name just keeping the app within our network. I need it to point to my machine that is on 191.168.61.6 not the localhost  
![image](https://user-images.githubusercontent.com/80058238/120721913-a1d85000-c483-11eb-8c5e-690b977f93fb.png)

when I try and go to the link which is http://localhost:1000/builder/invite?code=2f0e62ff5b0e48878b8aa3a0557e79d0 (I'm assuming the end of the URL changes with the user) I get nothing and if I change the localhost to the correct IP 
![image](https://user-images.githubusercontent.com/80058238/120722061-ee239000-c483-11eb-852b-78b5e7c78acb.png)
 I still get nothing, 
is there a way I can specify where I want the link address to pint?

**Comment by shogunpurple** [comment]
@AndrewJRamay you can update the URL that will be used in emails etc from your admin organisation page.

![Screenshot 2021-06-04 at 07 37 25](https://user-images.githubusercontent.com/11256663/120756870-b6f6c280-c507-11eb-8bfc-746f50ba18b9.png)
