### ISSUE TITLE
Installation on aarch64

### ISSUE THREAD

**Issue by manojmat29** [Budibase/budibase#1634]
Hi, there's a problem installing on Arm 64 servers such as those available on AWS and Oracle Cloud. ibmcom/couchdb3 does not support the arm arch. Error is <no matching manifest for linux/arm64/v8 in the manifest list entries>

Any workaround installing normal couchdb and changing parameters?

**Comment by manojmat29** [comment]
Tried with couchdb instead of ibmcom/couchdb3 and installation succeeds. But results in error on portal <upstream connect error or disconnect/reset before headers. reset reason: connection failure>

**Comment by mike12345567** [comment]
Hi @manojmat29 we used to make use of the standard CouchDB image, however we transitioned as of our latest update to use IBMs image to include the new 3.0 Lucene based free text search engine. This is something that the standard image is not bundled with. I expect that it is failing as we heavily utilise the search engine in our latest update.

We would love to support ARM architectures fully but haven't had time to create a custom image, this might also be an issue the IBM team could/might address as Lucene is JVM based and the lack or ARM image may simply be an oversight.

**Comment by manojmat29** [comment]
Hi, checked the container logs and it seems that the error that is usually thrown up for mismatched arch <exec user process caused: exec format error > is what is logged for worker and app. Also for ibmcom/couchdb3 if it is used instead of couchdb. So, merely getting the couchdb3 image for ARM 64 might not work.
Oracle has been really generous offering a 4 core 24 GB memory ARM 64 instance in its always free tier, so there might be an untapped market there.  Please do consider supporting ARM if feasible. Thanks.

**Comment by mike12345567** [comment]
Hi @manojmat29 - for our worker and server images I don't think it would be very difficult to support ARM since all they are is a slim Linux image with Node, should be easy enough to enable building and deployment of an ARM tagged image as well. The issue still relates back to there being no easy CouchDB 3.0 ARM image available though sadly.
