### ISSUE TITLE
Problem saving SMTP settings

### ISSUE THREAD

**Issue by timconsidine** [Budibase/budibase#1637]
**Describe the bug**
Complete the SMTP settings form
Red error flash appears  / disappears at top of page - something like :
    `Failed to save settings.  Unexpected token u in JSON at position 0`

Tried using builder accessed via domain.uk:10000 and <ip-address::10000

**Desktop (please complete the following information):**
 - OS: self-hosted Ubuntu
 - Browser : Brave
 - Version Version 1.25.68 Chromium: 91.0.4472.77

**Comment by shogunpurple** [comment]
Hi @timconsidine - so our SMTP integration will check that the connection is valid when you save the settings.

Wondering if this might be the issue here. Is your SMTP server already up and running? Which service are you using?

**Comment by timconsidine** [comment]
Yes. probably a connection issue.  
But I don't have any problems connecting to it with anything else, which throws spotlight on to Budibase.
Server is organisation's main IMAP/SMTP, which is working fine, and has been for yonks.
Tried 2 different user accounts, just in case password was wrong for one.
And 2 different formats for user (with and without domain)
Always same problem

Not willing to reset email accounts passwords "on the off-chance" (because then they have to be on 10 devices) until I know that is the problem.

The real problem here is that error message is close to useless.  
Nothing that I can use to solve the problem, and nothing that helps you to solve it.  
And I don't believe 'Failed to save settings" is correct.  Failed to connect might be true (and so didn't bother to store).  
But error message should say that.  Currently it suggests Budibase has a database connection problem, rather than a server connection issue.

Not sure how you are handling it in background, but .... just as an example .... if your connection test prior to save is telnet to server, then why not capture conversation in case of error and show in log or error message.  Then maybe we could diagnose something.

**Comment by timconsidine** [comment]
Just tested 2 separate email accounts (on same server) to ensure user/password correct.
They are.

Just tried to telnet to server : Timed out.
Which is probably what Budibase is getting.

Maybe some domain auth issue (does mail server restrict 3rd party SMTP connections)
I don't believe it does but will check their docs and maybe their support channel.

If you can clarify your connection test methodology, that might help to identify issue.

**Comment by mike12345567** [comment]
It probably would be worth while outputting more of a full error when this occurs - i'll have a look into this as the code looks like it is already supposed to append an error to the end of the message e.g. `Failed to save email settings. <actual error>`.

As for how Budibase verifies the SMTP connection we are simply verifying using the Nodemailer library - it doesn't actually describe how it verifies the connection - info about it can be found here: https://nodemailer.com/smtp/#verify-smtp-connection-configuration

**Comment by timconsidine** [comment]
I see from Nodemailer that connections with `rejectUnauthorized: false`
Are you requiring certs ?

**Comment by timconsidine** [comment]
Good news for Budibase : 
I cannot telnet from Budibase self-host server to organisation SMTP server.
I am in dialogue with their support guys

**Comment by timconsidine** [comment]
Hosting company for SMTP server have just asked a good question.
Something was bugging me about this form, but I couldn't identify what.

<img width="622" alt="Screenshot 2021-06-10 at 08 54 27" src="https://user-images.githubusercontent.com/28682881/121488076-a2fd0600-c9ca-11eb-971c-fbec39e916e8.png">

The form does not allow to specify STARTTLS or SSL/TLS.
It might be implied by the port number, but it is not specified in the form, so what's being used.

Might as well also ask/confirm : is it plain text password ?  Not CRAM-MD5, KERBEROS, NTLM etc.

**Comment by mike12345567** [comment]
This is a good point @timconsidine currently it defaults to using `STARTTLS` rather than `TLS` - I'll add something to the form to allow switching between these two.

The password is plain text, we don't currently support any other method as CRAM-MD5 is highly discouraged due to its insecure nature and nodemailer by default doesn't have support for KERBEROS or NTLM.

**Comment by timconsidine** [comment]
Thank you @mike12345567 
Yes plain text password is best.  Was just checking in case anything funny was going on in background.

**Comment by mike12345567** [comment]
Hi @timconsidine I've updated the email form and raised a PR - this includes a bit more of the configuration options we expose from our SMTP settings API in the form (in a less ambiguous way)

#1690

**Comment by timconsidine** [comment]
Thank you @mike12345567 
So good news !!
It eventually works.
Turns out not to be a bug as such.
Well not in code.  But maybe a "bug" in docs.
SMTP server hosting support respond that if using 'STARTTLS', then really port should be 587 (not 465 as per normal setup)
I think it would be really helpful the SMTP settings section to be clear that STARTTLS is being used.  Especially if that is all that is being used (but you said you might allow choice).

I haven't proved it is working by sending an email.
But the settings are saved immediately w/o timeout.
So probably time to close this.

**Comment by mike12345567** [comment]
Hi @timconsidine - as of the latest update (see PR #1690) the user is allowed to pick whether or not they are using `STARTTLS` or `SSL/TLS` hopefully this reduces confusion around this.

**Comment by ChipNowacek** [comment]
Sorry. Super new here and in many things. I just built the one-click DO container and am getting the same error. The host I'm using for SMTP only allows 465. Can you point me to the docs to update the DO-based container? Thanks much.

**Comment by shogunpurple** [comment]
@ChipNowacek if you just built the DO setup then you should be on the latest version.

Is your SMTP connection definitely valid? Budibase checks it before saving. If so, it would be helpful to see the browser developer console whenever the error occurs. Thanks!
