### ISSUE TITLE
Budibase Search DSL to SQL Conversion

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1641]
When I'm connecting my components to an opinionated datasource, I want to be able to bind queries to UI elements and search them the same way as I do with internal tables, so that I have an opinionated and consistent experience.

### DSL 
The DSL used will be one similar to that used in our current internal search built on lucene. This object will be converted into SQL for any dialect.

### Conditions of Satisfaction
- Query builder is capable of producing valid SQL for standard tables including WHERE clauses, LIMIT queries and BETWEEN queries
- JOINs to be accounted for in the context of a single element. Ie. give me the N of a 1:N relationship just by providing an ID.

**Comment by AndrewJRamay** [comment]
will this fix the problem that the external query fails when the entire form is not filled out or the date is blank ? that is a huge problem
