### ISSUE TITLE
Conditional UI - Bindings

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1644]
When using the design UI, I want to be able to control all component properties with bindings, so that I have the ability to control conditional visibility.

**Conditions** 
- Move all possible component props to handlebars to allow binding based on data

**Comment by mjashanks** [comment]
Just dropping this in here, as it's very relevant: https://github.com/Budibase/budibase/discussions/1617

**Comment by mjashanks** [comment]
Just doing some parsing of discussion #1617 

Control visibility of fields, based on other fields - Should be covered by this
 
**Limit the options for fields**
Could potentially be covered but we would need to add some extra features to the components themselves e.g.
- Date Picker needs a Min and Max value - which can be controlled conditionally
- Options picker needs overrideable options, which can be controlled conditionally
- Relationship picker needs to be filterable and the filter needs to be controlled conditionally

**Select appropriate Datasource**
Most of what is being asked for here could be achieved by allowing the filter on a datasource to be controlled conditionally, using the value in a form field. e.g.
1. Create an options picker and give it values of "Created by me", "Shared with me" and "All"
2. Apply filter to datasource, which is conditional, based on options picker

**Comment by aptkingston** [comment]
Closed via #2215.
