### ISSUE TITLE
External datasource - cannot create a query without running it first

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1650]
At the moment, Budibase forces us to run a query, before we can save it. The reasons for this are
1. To test that the query works
2. To pull back the returned schema

This makes sense for "Read" queries. However, for "Write" queries it means that we have to change data, which is not ideal.

My suggestion:
1. Remove the constraint for running the query
2. Enforce a constraint on entering a schema, which can still be auto-generated by "Run Query" or entered manually. We should also be able to check a box to say "No Schema" - allowing the user to save without a schema - i.e. when they don't care abut the response.

**Comment by shogunpurple** [comment]
Good idea - this makes total sense. Will move it into Ready to Pull 👍

**Comment by AndrewJRamay** [comment]
will this fix the problem i am having that the write query will fail if the entire form is not filled out?

**Comment by mjashanks** [comment]
@AndrewJRamay I'm looking back and think that you are referring to this: https://github.com/Budibase/budibase/discussions/1557#discussioncomment-798476

I believe that your query to the external data source was failing, due to the empty date issue: #1504

Your issue with not-required number fields looks to be fixed. I am unable to recreate this in the latest version. I created a number column, with a minimum and maximum value, which were not required. I was able to leave the field blank.

Have I understood your issues ok ?

**Comment by AndrewJRamay** [comment]
Hi @mjashanks 
yes, the issue I am having still are both related to submitting blank fields. I can save anything to the internal DB no problem however if I hit submit with either just the date blank or any of the form fields the query will fail.  

I documented it on #1606  it also looks like you are doing some major SQL redesign which would be amazing ( #1642 
 #1640   any idea when that will be done. this will be a huge thing for my app.

**Comment by mjashanks** [comment]
@AndrewJRamay your blank fields issue is now here: https://github.com/Budibase/budibase/issues/1683
