### ISSUE TITLE
DigitalOcean 1-Click Getting Started

### ISSUE THREAD

**Issue by GlennPatrickMurphy** [Budibase/budibase#1654]
**Describe the bug**
Following the Getting Started instructions on Digital Ocean 1-click. The link  https://docs.budibase.com/self-hosting/builder-settings leads to a 404. Then when I go to <your_droplet_public_ipv4>:10000 I get an access denied error

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Resource>/</Resource>
<RequestId>1686568223DBAE3C</RequestId>
<HostId>0432c1ab-6f8f-4790-8937-ada00ae0373e</HostId>
</Error>
```
**To Reproduce**
1. Go to digital ocean's 1 click marketplace
2.  Launch Budibase droplet
3. Open Get Started link
4. Go to <your_droplet_public_ipv4>:10000
5. See error

**Expected behavior**
I expect to be brought to the login screen, similar to when I run this locally on my computer

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.77

**Additional context**
Really love this app. Thanks for any guidance

**Comment by shogunpurple** [comment]
Hi @GlennPatrickMurphy - the digitalocean one click setup is currently outdated, and will be updated over the next day or two. Sorry about that. 

Please use the guide here (https://docs.budibase.com/self-hosting/hosting-methods/digitalocean) to get your droplet up and running in the meantime!
