### ISSUE TITLE
Missing store function for saving access levels for tables

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#1659]
**Describe the bug**
When changing the access level for a table, an error is thrown:
![image](https://user-images.githubusercontent.com/9075550/121137672-cee38480-c82e-11eb-9341-9be038582f03.png)

Inspecting the code, there is no save function in the permissions store. This must have been lost as part of a merge, because I can't find it anywhere.

**Comment by shogunpurple** [comment]
@aptkingston this one should be fixed on master, I pushed it yesterday 👍
