### ISSUE TITLE
Displaying Datetime with local timezone.

### ISSUE THREAD

**Issue by kahennig** [Budibase/budibase#1666]
So I tried displaying a date in the breadcrumbs and in the form title and by default it shows up in UTC
Is there a way to apply a format that will let me set the timezone to display it in?

Dates show fine in the datepicker but not in the breadcrumbs nor in the title:

![2021-06-06_00-35](https://user-images.githubusercontent.com/3522117/121196164-a1a2d080-c846-11eb-9746-bce6fe829ccf.png)

I am using this to format: {{ date Repeater.Appointments.Date "DD-MM-YYYY HH:mm a Z" }} 

is there a way to specify the timezone in the date formattin helper?

**Comment by mike12345567** [comment]
Hi @kahennig - currently the system does not support formatting with timezones, this is something we should resolve.

I'll need to look into the best approach for this, I think the nest approach will likely be to add a timezone property onto the end of the `date` helper e.g. `{{ date <prop> "DD-MM-YYYY" "GMT+1" }}`

**Comment by kahennig** [comment]
Thanks for the reply @mike12345567. 

> I think the nest approach will likely be to add a timezone property onto the end of the date helper e.g. {{ date <prop> "DD-MM-YYYY" "GMT+1" }}

that was pretty much what I was trying to see if it existed. Except I was trying "America/Montevideo". 
"GMT+3" would work for me because we've not had dailight savings time in Uruguay for some years now.
But for other users whose countries do change timezones during the summer it might be problematic, so I would think that using the "Continent/City" format might be more universal.

**Comment by mike12345567** [comment]
> Thanks for the reply @mike12345567.
> 
> > I think the nest approach will likely be to add a timezone property onto the end of the date helper e.g. {{ date  "DD-MM-YYYY" "GMT+1" }}
> 
> that was pretty much what I was trying to see if it existed. Except I was trying "America/Montevideo".
> "GMT+3" would work for me because we've not had dailight savings time in Uruguay for some years now.
> But for other users whose countries do change timezones during the summer it might be problematic, so I would think that using the "Continent/City" format might be more universal.

Sorry yes the `GMT+3` was only an example, realistically we will use the dayjs timezone system, so it'll support the full list of timezones that dayjs supports, cities and time codes.

**Comment by kahennig** [comment]
Excelent @mike12345567. What do you want me to do with this issue?
Maybe you can tag it as a feature request?
Thanks again.

**Comment by mike12345567** [comment]
Looked into this and it wasn't too complicated + also a relatively necessary feature, i've opened a PR to resolve this: #1675

**Comment by kahennig** [comment]
Great @mike12345567. I'll update and test as soon as the release is pushed to images.
Thanks for the prompt response!!!
