### ISSUE TITLE
I cannot view my app when published, when previewed, or within the design preview

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1681]
**Describe the bug**
I cannot view my app when published, when previewed, or within the design preview

**To Reproduce**
Build an app
Publish it
Use / test it
Wait 24 hours
Attempt to access the app
Witness a blank page

**Expected behavior**
The app should work

**Comment by shogunpurple** [comment]
I'll fix your app in staging here, and then we can investigate this as well.

**Comment by mike12345567** [comment]
Fixed as of PR #1691 being merged.
