### ISSUE TITLE
External data sources do not handle non-strings well

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1683]
When passing parameters into an external data source, things get hard or impossible when we need to pass in any non-strings that have the potential to be empty. E.g. numbers.

Take this example

```
insert into customers (name, email, age) 
values ('{{ name }}', '{{ email }}', {{ age }} )
```
if `age` is empty, then this fails., because the resulting query is

```
insert into customers (name, email, age) 
values ('Mike', 'mike@mike.com',  )
```

i managed to get this working by doing...

```
insert into customers (name, email, age) 
values (
'{{ name }}', 
'{{ email }}', 
{{ #if (eq age "")}} null {{ else }} {{ age }}  {{/if}} 
)
```

which is horrendous, and took me a while to figure out.

**My (vague) suggestion** 

Parameters to external datasources should not be handlebars expressions (which is also a security risk).

Parameters should be typed. E.g. the `age` parameter should be a `number`. 

We should not be able to do any dynamic string modification inside the query. Parameters should be passed in as variables/references. Any dynamic stuff should be handled by the caller.

For SQL integrations, this should mean using a parameterized query.

For queries that use JSON, I suggest exposing parameters as local variables.

**Comment by shogunpurple** [comment]
bump
