### ISSUE TITLE
Length function not working

### ISSUE THREAD

**Issue by doylegrant** [Budibase/budibase#1686]
I can't seem to get the length function to work in a formula column. Even using the example code `{{length [1, 2, 3]}}` returns 0. Seems to be the case for the `equalsLength` function as well.

**Comment by mike12345567** [comment]
Hi @doylegrant you are write that the example presented does't actually work, the reason for this is that the example is not actually valid handlebars, there is no real way to pass an array directly in the handlebars statement.

I'll update the example to not use an inline array, if you do need to use an inline array however you can do something like:
```
{{ length ( split '1, 2, 3' ',' ) }}
```

**Comment by mike12345567** [comment]
I've pushed some updates to our helpers library to fix some of the issues you were experiencing as well as updating the examples to be accurate.

I've also made it possible to handle lengths of inline arrays as this is a somewhat useful feature, the syntax appearing as: `{{ length '[1, 2, 3]' }}` - this will be available in the latest release.
