### ISSUE TITLE
Make login page respect organisation logo

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1700]
https://github.com/Budibase/budibase/discussions/1639

- Login page respects org logo instead of budibase helmet
- Allow custom welcome message on login page (configured in org settings)
- Add "Powered by budibase" to the screen on budibase apps

**Comment by mjashanks** [comment]
favicon was also requested here: https://github.com/Budibase/budibase/discussions/1578

OK if out of scope for now.

**Comment by sergey-dme** [comment]
Please make Login page customizable by admin (change logo/text)

**Comment by mike12345567** [comment]
This work has been completed, and will be part of the next release.
