### ISSUE TITLE
Improved navigation and layouts

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#1707]
Part of the improving layouts and containers involves addressing the current navigation component, and how app layouts work. Side navigation needs to be possible, and navigation should be responsive.

Requirements:
- Create new layout component which will be used for builder "layouts"
- Layouts will have a setting for either top nav or side nav
- Navigation will be responsive, and collapse to a burger menu on mobile
- Navigation will include a link to go back to the user portal rather than a log out button
- The navigation component will be removed, and the navigation settings will be part of the layout
- Links in navigation will be controlled by a setting, rather than as children of a navigation component
- The link settings should let users choose which screens they want to link to, the order or the links and add external links too

**Comment by sergey-dme** [comment]
Awesome! Just tested a few of them in new version. Would be nice to have a Logout link as url address to be able to use it in user-customized layouts with user-created headers based on empty layouts. Not everyone App creator wants user to go on the portal to logout, sometimes it unnecessary step. 
Links as child in the tree give more freedom for user, to move it, put in containers and change styles.. but in this case collapsing would not be possible.. that's the down side of child showing. Thank you
