### ISSUE TITLE
Design section screen overflow is hidden

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1708]
**Describe the bug**
When you are designing your app's UI, and the content overflows the iframe size, you are not able to scroll to see the hidden content.

**To Reproduce**
1. add lots of components/content so they are positioned off screen
2. Attempt to scroll

**Expected behavior**
You should be able to scroll

**Screenshots**
https://www.loom.com/share/527b72c346954dc5a567f3e12b046682

**Comment by aptkingston** [comment]
This has been solved and the current version does allow scrolling from the client app root. (DOM ID is `app-root`). For apps on old versions where this is an issue you can add styles to your layouts, screens or containers to allow handling overflow whatever way you'd like.
