### ISSUE TITLE
Exporting and importing app did not work

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1709]
**Describe the bug**
To update my app to use the latest features, I exported and imported it. The imported app did not have the components the original app had.

The imported app had the right screens, data, but was missing the right components for the homescreen. I believe this is because we auto-generate a home screen for every app.

**Comment by aptkingston** [comment]
Did the app just have the default "Welcome to your budibase app" homescreen? I've tested it there and can't reproduce it so I'm not sure what the problem is. I tried with custom home screens under both "basic" and "public" roles and both worked.
