### ISSUE TITLE
Unable to change role of a user in user table

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1710]
**Describe the bug**
All users are admins in staging. I wanted to change a user's role from admin to power or basic. I was presented with this feedback:

![Screenshot 2021-06-14 at 14 06 41](https://user-images.githubusercontent.com/49767913/121897030-dd8fd700-cd19-11eb-9d0c-fadae40a7970.png)

**Comment by mike12345567** [comment]
Ideally we should remove this, shouldn't actually be allowed to set the user from here, everything roles wise should be set outside the app, it should be read only here - will look into that.

**Comment by mike12345567** [comment]
Fix has been merged.
