### ISSUE TITLE
no scroll on datasource selection

### ISSUE THREAD

**Issue by pldmayer** [Budibase/budibase#1713]
![Screenshot from 2021-06-15 15-52-53](https://user-images.githubusercontent.com/33716628/122064883-c8867700-cdf1-11eb-9639-93284ec5d91f.png)
Hi in new version there is no scroll bar for data sources.

**Comment by joebudi** [comment]
Great catch @pldmayer . It's awesome to see an app with so many tables, views, and relationships!

**Comment by mslourens** [comment]
Close because this issue has been implemented and tested.
