### ISSUE TITLE
App Export Performance Issues

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1718]
In the staging environment, it takes well over 30-40 seconds to export an app with around 8000 rows.

It does seem as though the `pouchdb-replication-stream` package suffers from some performance bottlenecks, preventing us from reaching the full throughput of what should be a fairly lightweight operation.

- Test locally with a large app
- Monitor how long export takes
- Identify performance bottlenecks and fix

**Comment by sergey-dme** [comment]
Bad bot
