### ISSUE TITLE
`Not Found` error when running budibase

### ISSUE THREAD

**Issue by aantn** [Budibase/budibase#1729]
![image](https://user-images.githubusercontent.com/494087/122433952-5b184900-cf9f-11eb-8a2f-301e957c0d47.png)

How it happened:
1. I had an issue as described at https://github.com/Budibase/budibase/issues/1592
2. I decided to run budibase from scratch
3. I created a new directory and ran `budi hosting --init` in it
4. I received errors because the old budi instance was still running
5. I stopped the old budi instance
6. I received errors (see below) because several old containers still existed
7. I deleted those old containers with `docker rm`
8. I tried `budi hosting --start` but it didn't work and gave the `Not Found` error

Errors regarding old docker containers:
```
ERROR: for bbapps  Cannot create container for service app-service: Conflict. The container name "/bbapps" is already in use by container "5c7a40e521aec68c27ecc0a71415c8cb51e644297847e3d030fa17ba697d0cdd". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for app-service  Cannot create container for service app-service: Conflict. The container name "/bbapps" is already in use by container "5c7a40e521aec68c27ecc0a71415c8cb51e644297847e3d030fa17ba697d0cdd". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project.
Docker Compose is now in the Docker CLI, try `docker compose up`
```

It really doesn't seem to be my day...

**Comment by shogunpurple** [comment]
@aantn I think the error is as advertised. 

`docker container prune -a`

Should remove all old containers not currently running, if you have stopped everything.

**Comment by aantn** [comment]
@shogunpurple just tried that, but it didn't fix the issue.

**Comment by aantn** [comment]
I messed around with `docker compose` and the Docker UI on Windows until all traces of old containers were removed. That fixed the issue.

**Comment by sergey-dme** [comment]
I had the same issue yesterday (after removing budi, old container and then running "-- init"). The only thing that helped is clearing browser cache/cookies.

**Comment by shogunpurple** [comment]
@sergey-dme this happened because —init will generate a new JWT secret, so your old one stored as a cookie wasn’t valid. Good thinking on clearing them to get back up and running. We could possibly add a troubleshooting section to the docs, as that’s quite a common one we experience on the dev team as well.

**Comment by aantn** [comment]
That troubleshooting section sounds invaluable!

**Comment by shogunpurple** [comment]
https://docs.budibase.com/troubleshooting now contains a simple troubleshooting section for issues that may crop up. We will continue to add to this guide as the team comes across other potential problems. Thank you!

**Comment by aantn** [comment]
Cool, thanks

**Comment by shogunpurple** [comment]
This one seems to be docker environment related - closing.
