### ISSUE TITLE
Catch all toast/notification box for error and warning messages

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#173]
Within budibase, there is a lack of error messages and notifications as you use the UI. For alpha, we should have a "catch all" which will prompt the user to refresh when something fails.

https://getuikit.com/docs/notification

**Comment by joebudi** [comment]
Error alerts.

**Important UX**
Once a user clicks the refresh button, the page refreshes, and if the solution is solved, the error message disappears. If it is not resolved, can we alert the user to report the bug?

Dev preview:
https://xd.adobe.com/view/a6c1f01a-3e5e-4340-51f2-abf48c74a6db-d0f0/

Static images/previews
![Components level 1 – 4](https://user-images.githubusercontent.com/49767913/77904174-02ff0500-727c-11ea-918a-1fe9d91ebf23.png)
![0 02 – 1](https://user-images.githubusercontent.com/49767913/77904172-00041480-727c-11ea-807f-c2a61fd6cc6e.png)
