### ISSUE TITLE
Postgres ECONNREFUSED 127.0.0.1:5432

### ISSUE THREAD

**Issue by rishi003** [Budibase/budibase#1731]
Unable to connect to the local instance of Postgres SQL v13.1

1. Go to 'Add External Data sources'
2. Click on 'Postgres'
3. Add username, password, database.
4. Save
5. run a query
6. see error

**Expected behavior**
It should return the query results

**Screenshots**
![image](https://user-images.githubusercontent.com/58147255/122535489-acbee300-d034-11eb-98ae-0bd359df7c2c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 91.0.4472.106 

**Additional Context**
here are some logs
```

     ERROR [1624006610231] (28 on fe29cefa197f): Error: connect ECONNREFUSED 127.0.0.1:5432

Error: Error: connect ECONNREFUSED 127.0.0.1:5432

at PostgresIntegration.query (/app/src/integrations/postgres.js:79:13)

at runMicrotasks (<anonymous>)

at processTicksAndRejections (internal/process/task_queues.js:97:5)


Trace: Error: Error: connect ECONNREFUSED 127.0.0.1:5432

at PostgresIntegration.query (/app/src/integrations/postgres.js:79:13)

at runMicrotasks (<anonymous>)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at /app/src/api/index.js:54:15

at runMicrotasks (<anonymous>)

at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by shogunpurple** [comment]
@rishi003 - Can't seem to repro this one. Are you sure your database credentials are correct?

**Comment by rishi003** [comment]
@shogunpurple - Yes, I tested the same configurations with Dbeaver and they are fine and working.

**Comment by shogunpurple** [comment]
Thanks @rishi003 - I wonder if its the use of `127.0.0.1` due to running in a docker host. Try `0.0.0.0` as your DB host instead

**Comment by rishi003** [comment]
Turns out that I was trying to connect to a Postgres instance that was outside of my docker network. It worked fine when I used my machine IP instead of localhost/127.0.0.0/0.0.0.0 as they were rerouting the connection to their own network. Thanks @shogunpurple

**Comment by shogunpurple** [comment]
That’s great @rishi003 - I’ll add something to the docs about this because it’s could catch some people out. Thanks!
