### ISSUE TITLE
Log Out link for user is absent in header

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#1733]
Hello All. There is no "Log Out" link in the header in any of my app, even in new created/empty app. It showed in builder only, in app - no. I've tried almost everything `hosting --stop` then `--update` and `--start`. Also tried reinstall whole docker and installed budibase again using `cli-win.exe` for Windows (downloaded from docs.budibase.com). Nothing helped. 
Could you please advise how to get the log out link showed in layout?
I could insert **link object** in layout and fill **url** field  manually, what's the link syntax/command for logout? Thanks.

**Comment by joebudi** [comment]
Hey @sergey-dme . Thanks for raising an issue. [This PR](https://github.com/Budibase/budibase/pull/1735) will fix this by providing a button that will take the user to the portal where they can logout.

**Comment by sergey-dme** [comment]
Just build new cli.exe from the src then installed & updated. I created new test app and user with Basic rights/role - still no log out link in the app.

Log Out section/link also still missing in layouts. 

Please advise.

**Comment by shogunpurple** [comment]
@sergey-dme building a new cli.exe from source will not give you the latest features on that branch. You would need to manually build all the docker containers on your server, tag them and update your configuration. I would not advise this.

These features are not complete yet. They still need to be tested by the team before being released. We will be doing a release next week with these features (and many more), and you should be able to pull down the latest as soon as we release - thanks for your patience!

**Comment by sergey-dme** [comment]
@shogunpurple Thank you for the prompt reply and explanation. Looking forward to the next release

**Comment by sergey-dme** [comment]
@shogunpurple I done the following on new/clean computer: 
1. Enabled/Installed Win WSL2, Installed Docker (with yarn on startup), NodeJs
2. In windows CLI with Administrator rights run:
3. `npm install -g gh` 
4. `npm install -g jest`
4. `npm install -g git`
5. `git clone https://github.com/Budibase/budibase.git`
6. `npm i -g @budibase/cli`
7.  cd in budibas and run `yarn bootstrap`
8. `yarn build`
9. cd where cli.exe located and run `cli hosting --init` then 
10. `cli hosting --start` (containers appeared in docker)
11. `cli hosting --stop` then `cli hosting --update` and `cli hosting --start`

The LogOut missing link issue is present and  another one: It is unable to edit/update a table record with one-to many relationship - `1:N Relationship Error: Record already linked to another.`...

**Comment by shogunpurple** [comment]
@sergey-dme to clarify - the logout link will not be released until next week.

From your steps there, I'm not sure what exactly you are trying to do. If you have installed the CLI from NPM, you do not need pull down the source code or download `cli.exe` or install anything else.

As for the relationship issue, please raise another issue for that, with the problem and reproduction steps.

**Comment by sergey-dme** [comment]
@shogunpurple you right, building the cli wasn't needed as I use NPM to install. Sometimes I was messed with it, my experience with cli and Unix is not so good.
 As for the relationship issue - i will be preparing description and screens and create new ticket.

Sorry, but could you please tell me, what I have to do to update to the new release which is expected on next week.

`hosting --update` would work for me to receive all changes in the next release?

Thank you again for your help 🙏

**Comment by shogunpurple** [comment]
@sergey-dme no problem! Yep, you can run budi hosting --update to receive the latest updates when they are pushed.

**Comment by sergey-dme** [comment]
Dear Budibase Team, Thank you for the new improvements of frontend in v.0.9.55 . All of them is very useful and great but in the same there are still some undesirable limitations. 
Now Log Out is only accessible from a layout with pre-designed new header which is almost locked for user-customization for obvious reasons (to keep new options working, I mean collapsing). Fortunately it is still possible to use blank layouts to create almost fully customized frontend. For example, I spent hours creating , designs, using layers/containers, icons, css code on my header and more. So, it would be great if you consider the following:
- Please make possible for user to use a **url address** like  **_/builder/logout_** or something as a link to end session/logout wherever user wants
- Please make possible to set 'sticky' user-created headers. Now it only works in your pre-defined layout with the 'locked' header. Maybe a new component - Layout Header is a solution (with sticky option and which has same settings like Container)
- Please make new header shown as separate object in layout tree (as the old one)
I like how new header collapses, but unfortunately  I can't use it for now - it does not match / fit with my other existing designs. Despite of that, I can't find a way how to create new layout with new header in existing app, only if new created app.
Thank you.
