### ISSUE TITLE
NPS Forms

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1736]
*Requires Designs*

Just before I deploy an app within budibase, I will fill out an NPS score form rating the product from 0-10.

**Conditions of Satisfaction**
- Users can select a score of 1-10
- After filling out the NPS, we store a cookie on their browser or a piece of state in the DB **for that user** which means we don't show that exact user it again, but other users on the account will

**Notes**
- Original NPS Code is here https://github.com/Budibase/feedback. Move this into the main repo, because originally we planned to use it as an iframe in other products but it makes sense to just add it to the builder
- Data is stored to posthog

**Comment by joebudi** [comment]
Design doc:
https://docs.google.com/document/d/10wyQfgWG5oEqqGNCgFRS9nd0G56UYjb99P0gaa7uzDE/edit?usp=sharing
