### ISSUE TITLE
Unabe to edit/update a table row with one-to many relationship

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#1753]
It's unable to edit a row with one-to many relationship. 
I got the message: `1:N Relationship Error: Record already linked to another.
`
For Example, I created new app with two simply tables - **Documents** and **Types**. 
One Document can have only one Type. Type can have many Documents.

The relationship is shown below:

![2021-06-20_01-18-55 (2)](https://user-images.githubusercontent.com/53024832/122657098-088a8880-d169-11eb-874c-0416b710f56c.png)

The records:

![2021-06-20_01-19-22 (2)](https://user-images.githubusercontent.com/53024832/122656953-e0e6f080-d167-11eb-9a42-eeb5d7835c2e.png)

![2021-06-20_01-19-36 (2)](https://user-images.githubusercontent.com/53024832/122656959-ea705880-d167-11eb-8c66-aa313f5fa156.png)

The error messages when Im trying to edit Description field for a Type:

![2021-06-20_01-20-03](https://user-images.githubusercontent.com/53024832/122656996-2b686d00-d168-11eb-91dd-43d177261354.png)

![2021-06-20_01-17-37 (2)](https://user-images.githubusercontent.com/53024832/122657002-3c18e300-d168-11eb-893c-8a9a77c63648.png)

**Comment by Lewiscowles1986** [comment]
Is the software perhaps making the relationship non-obviously backwards? The thing you think is the one, could be the N?

Can you try adding one the other way around to see if that is it, or does the UI prevent it?

**Comment by mike12345567** [comment]
Hi @sergey-dme thank you for the report! Had a look at this, it appeared there was an issue with a row having many relationships (I expect in your case there is like auto-column relationships such as created by/updated by).

I've pushed a fix and it will be released in the next hour or so, you can update via `budi hosting --update` in the Budibase CLI.
