### ISSUE TITLE
Active Directory and LDAP Integration

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1766]
When using the budibase platform, I want to set up and authenticate with and existing Active Directory server.

- Bring up an AD server in azure
- Add some users
- Point local BB instance at server and attempt to authenticate

**Conditions of Satisfaction**
- UI to configure AD credentials from the Admin Panel
- When I log in, passport authenticates with the LDAP server, and will create a local user in the budibase DB to represent that AD user on first login
- Also identify integration points with AD groups and budibase groups. Can we map them directly?

http://www.passportjs.org/packages/passport-activedirectory/

**Comment by Rory-Powell** [comment]
See design doc here:
https://docs.google.com/document/d/1q_bzcFi2vxErfp_Lcm3sOSMQKa5RuBRswQBLfD9Dq9Y/edit#heading=h.i7oibpfqiy7b

**Comment by hillar** [comment]
please add [keycloak](https://www.keycloak.org/documentation.html)

**Comment by PClmnt** [comment]
@hillar Keycloak is supported via OIDC that was just released in v0.9.84 - https://docs.budibase.com/admin/authentication/oidc (I tested it specifically with Keycloak so I know it works). I'm putting some docs together for Keycloak and they should be published tomorrow.
