### ISSUE TITLE
Builder Development Experience. JavaScript, transformers, autocomplete

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1767]

**Comment by mjashanks** [comment]
Adding a few items in here for future reference. These are specifically around the experience of using external datasources. Just thought that I should collect them.

- Pitfalls in using parameters, read all comments: https://github.com/Budibase/budibase/discussions/1385
- Using parameters & handlebars: https://github.com/Budibase/budibase/issues/1683
- The need to Run a query before we can save it: https://github.com/Budibase/budibase/issues/1650
