### ISSUE TITLE
Budibase as Backend API

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1768]

**Comment by jben7** [comment]
Do you have news about a backend API ?

**Comment by mike12345567** [comment]
Hi @jben7 This is something that we really would like to support, but has not been added to the roadmap as of yet - because of this we can't say for sure when it will be implemented.
I'll reopen the issue as it was closed by stale bot - so that discussion around it can continue.

**Comment by dncpax** [comment]
I would be reaaally interested in this. It may be an unintended consequence but considering the ease of use of bb plus sql support, scriptable actions, 3rd party integrations, and webhooks, bb is looking like a pretty amazing api backend!

**Comment by mike12345567** [comment]
> I would be reaaally interested in this. It may be an unintended consequence but considering the ease of use of bb plus sql support, scriptable actions, 3rd party integrations, and webhooks, bb is looking like a pretty amazing api backend!

Hi @dncpax we're glad you're excited for this feature, as are we! The open API specification has been written and the first version of this will be released very soon!

**Comment by dncpax** [comment]
hey @mike12345567 . I've tested creating and consuming a backend task. Is there anyway of returning data instead of just ´{"message":"Webhook trigger fired successfully"}´?

**Comment by Topener** [comment]
@dncpax one way you could get around this is by adding your API as a data source, and triggering a POST after the automation has run. You can run an API call directly in the automation using the `external data connector`, which will trigger an API call through the Queries interface inside the REST data source.

As this is offtopic to this issue, if you have any questions around this feel free to [create a discussion.](https://github.com/Budibase/budibase/discussions/new?category=help)

**Comment by daawaan** [comment]
Hello, in relation to this issue, are there any plans to add a "datasource" for Budibase that enables the middleware to act as a proxy for an internal rest API to authenticate incoming requests? This can come in handy once adding custom components in budibase is possible and when users want to use Budibase as a BaaS instead for frameworks like Nextjs. See #5281
