### ISSUE TITLE
App becomes inactive after 24 hours of inactivity

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1773]
**Describe the bug**
I had a Budibase app open in a tab since Friday. I navigated to another screen and I received an error - Forbidden.

**To Reproduce**
1. Open an app
2. Wait 24 hours
3. Try to navigate to another screen

**Expected behavior**
I believe the app should either:
- Allow the user to navigate to another screen and continue to work
- Ask the user Sign-in - in this case, the user should be presented with a dialog box with a Sign-in CTA, rather than an error.

**Comment by shogunpurple** [comment]
Good catch. I think we need to differentiate between "Unauthorized" and "Unauthenticated", so that when your token expires it just kicks you back to the login page. I thought we actually did this, but apparently not. Will have a look at that

**Comment by mike12345567** [comment]
Resolved as of latest release.
