### ISSUE TITLE
CSV import - date datatype

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1794]
### Discussed in https://github.com/Budibase/budibase/discussions/1791

<div type='discussions-op-text'>

<sup>Originally posted by **Cinbert** June 22, 2021</sup>
I am a new user and trying to get my first app up and running. I created some test data in a csv file. I have tried a number of ways to format the date field including ISO8601 formating - 2020-09-24T13:12:04.622Z  but the table is created with no rows of data.   

There is clearly a failure somewhere but it is not being reported to me.  I only figured out that the import was failing on the date field through standard debugging steps.  My table rows only showed up after I specified the date field as a text data type.   

I have attached my small test data file.
[GIP_Tables.csv](https://github.com/Budibase/budibase/files/6690120/GIP_Tables.csv)
</div>

**Comment by mike12345567** [comment]
Resolved as of latest release.
