### ISSUE TITLE
Air gapped deployment

### ISSUE THREAD

**Issue by ifujis** [Budibase/budibase#1803]
Creating new app in air gapped deployment results in "SyntaxError: Unexpected token u in JSON at position 0".

**Comment by shogunpurple** [comment]
@ifujis we do not currently have any kind of first class support for air-gapped deployments, but this seems like a separate issue.

We are going to need a little more information. The following steps would help a lot. (Assuming you are on chrome, but the steps are fairly similar for any browser)
https://www.loom.com/share/8256c7e8503749f4b533bef285718c8e

One of your calls (the failing one) will be in red text. Sending the response of that will help the team debug.

Thanks!

**Comment by ifujis** [comment]
@shogunpurple, thank you for your reply.
Please find it here https://www.loom.com/share/86bc2c9708064457bacc35c8d18fe9cc
During app creation it tries to connect to 104.16.19.35:443.

I've also noticed it sends something via browser to posthog.budi.live despite sending analytics is off in the app settings.

**Comment by shogunpurple** [comment]
Awesome thanks - so the problem there seems to be that your reverse proxy is not able to reach the application server, and it's timing out.

Check and make sure all the docker containers are up and running: `worker` and `apps` etc. If they all are, then you might need to check your docker network is configured correctly, and all the containers can talk to each other.

As for the posthog stuff - that seems like a bug. I'm seeing the same issues. Will raise an issue for that

**Comment by ifujis** [comment]
All the components are running. I found it tries to connect to https://registry.npmjs.org and if I allow connections to registry.npmjs.org, then it works fine.

Thanks!

**Comment by shogunpurple** [comment]
Ah, that would be it. We pull the latest component libraries from NPM on app creation. Pretty cool to hear BB is running smoothly in an airgapped environment. Thanks for digging into this!
