### ISSUE TITLE
Outgoing webhook pushes empty JSON

### ISSUE THREAD

**Issue by burnoutberni** [Budibase/budibase#1809]
**Describe the bug**
When using an outgoing webhook, only `{}` gets posted to the desired URL, instead of my desired JSON.
When using a Shell script with `wget`, it works fine though.

**To Reproduce**

1. Define automation:

```
# Trigger – new row in "Postings" table (containing fields 'Titel' and 'Textvorschlag')
# Step 1 – Shell script:
wget -O- --post-data='{ "Titel": "{{ trigger.row.Titel }}", "Textvorschlag": "{{ trigger.row.Textvorschlag }}"}' \
  --header='Content-Type:application/json' \
  'https://my-url'

# Step 2 – Outgoing webhook (POST request to same URL)
# JSON body:
{ "Titel": "{{ trigger.row.Titel }}", "Textvorschlag": "{{ trigger.row.Textvorschlag }}"}
```

2. Save and test automation

```
# Received JSON on the other side
{ Titel: 'TEST', Textvorschlag: 'TEST' } # Step 1
{}                                       # Step 2
```

**Expected behavior**

```
# Received JSON on the other side
{ Titel: 'TEST', Textvorschlag: 'TEST' } # Step 1
{ Titel: 'TEST', Textvorschlag: 'TEST' } # Step 2
```

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Chromium 91
 - Version: @budibase/cli@0.9.60

**Comment by mike12345567** [comment]
Hi @burnoutberni - you're right, there did appear to be some issues, I've opened PR #1815 to solve this, will be merged and released ASAP!

**Comment by shogunpurple** [comment]
Closing as should now be fixed by https://github.com/Budibase/budibase/issues/1815
