### ISSUE TITLE
Adding new fields shifts existing table data into the wrong fields

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#181]
Video below:
https://www.loom.com/share/3f9342a014484a68a2bb5b13a8be5bed

**Comment by shogunpurple** [comment]
@joebudi can you still replicate this? I can't reproduce. I'm just hitting that issue that Mike is currently looking into where data can't be upgraded

**Comment by joebudi** [comment]
I am happy to report, this bug was squashed. Success.


<img width="1671" alt="Screenshot 2020-04-02 at 11 05 25" src="https://user-images.githubusercontent.com/49767913/78236466-ed831880-74d1-11ea-97f5-2b2c7c2d89cb.png">

**Comment by joebudi** [comment]
Issue closed
