### ISSUE TITLE
No Scrolling at Screens

### ISSUE THREAD

**Issue by PGLange** [Budibase/budibase#1817]
**Describe the bug**
When I have lots of Information on a Screen, so that the Screenheight is not enough, there is no scrolling. 
Even with  overflow: scroll; scrolling is not possible. 
I updated Budibase yesterday. Maybe this helps - before updating scrolling was possible.

**To Reproduce**
1. Create a Screen
2. Put lots of infos in
3. Scrolling won't work

**Expected behavior**
Scrolling was possible - Scrolling is needed
**Screenshots**
![error](https://user-images.githubusercontent.com/86222990/123218496-14a97980-d4cc-11eb-9652-dfaeece69186.PNG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge / Firefox
 - Version  91.0.864.54 / 89.0.2

**Comment by aptkingston** [comment]
Hi @PGLange. There were some changes in the latest release to layouts and screens, and those included different styles for handling things like overflow. You should definitely be able to fix this by adjusting the CSS though. Try setting the screen's height to `100vh` as well as using `overflow: scroll`. Some combination of height rules on the screen or the layout, and overflow rules will definitely fix this for you.

**Comment by PGLange** [comment]
Setting Screen height to 100vh worked out well!

Thank you for the fast answer! :)
