### ISSUE TITLE
I cannot change the button variant within my auto-generated table

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1822]
**Describe the bug**
I cannot change the button variant within my auto-generated table. When I select cta/secondary, nothing happens

**To Reproduce**
1. Auto-gen list screen
2. Click on the button
3. Try to change the variant

**Comment by aptkingston** [comment]
This will be fixed in the spectrum component conversion branch - it's just that the screen templates weren't updated when the button change was made, but I'll fix this on my branch.
