### ISSUE TITLE
Unable to access admin portal after authenticating a basic user

### ISSUE THREAD

**Issue by mhdaouas** [Budibase/budibase#1841]
I'm unable to access admin portal (builder interface) after authenticating with a basic user.

1. Create an admin and a basic user
2. Logout from admin and login with the basic user
3. The basic user is redirected directly to the app preview
4. There is no way to get back to admin interface (builder) since there is no user icon by default in the header (to enable the basic user to disconnect for example so we can connect with the admin). Also when I access /builder URL manually, I still get redirected to the app preview page.
 
By the way, is there a header element that we can add from design menu to allow the user to disconnect? I think this should be generated with the basic template by default. It still not clear to me how to switch from a user to another in the app preview to test the user access rights. I tried adding a button with logout action but when I click on it, it doesn't log me out (even after publishing the app).

OS: Linux Manjaro
Browser: Chrome 86.0
Budibase Version: 0.9.65

**Comment by mhdaouas** [comment]
OK I had to remove the cookies to finally get access to the authentication screen of the admin portal.

**Comment by shogunpurple** [comment]
@mhdaouas If you only have one app, then you are directly to that app as soon as you log in as a basic user. This is a good point though, I will create an issue to turn that behaviour on/off.

**Comment by shogunpurple** [comment]
@mhdaouas this one should be resolved!
