### ISSUE TITLE
Multitenancy Awareness

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1843]
#### Group Management

*Needs Designs*

### Requirements
* Admins can create new groups in a budibase installation
* Admin can assign group admins to the group
* Every group can have one or more group admins, you can set group admins at group creation time
* A group admin can add/remove people from the group. 
* A group admin can invite users outside budibase into their group. When they join, they are assigned to the group only
* Apps are still public by default, but apps that are assigned to groups are private unless you are in that group
* If you are in multiple groups, when you create an app, you can choose which groups that app is in
* **Only global builder can create totally public apps**
* Group admins can assign group roles for apps.
* Group admins can set individual user roles for apps in their group.

### Cardinality
* One group can have many admins.
* Many groups can have many users
* Many group can have many apps

### Roles Flow
* User logs into an app
* Budibase checks if they have a user role. This is the highest specificity, so user role will be used straight away if defined
* If no user role, check if there is a group role defined for the application. If, so use that.

**Comment by joebudi** [comment]
Design doc: 
https://docs.google.com/document/d/1WcfUxsyBnDpz7GXlxxXPs8ixaKTLODGF2T-uQXOxQ2E/edit?usp=sharing
