### ISSUE TITLE
Better UI Around Budibase Updates

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1852]
Right now, the budibase update UI is fairly basic in that it sends an HTTP request to watchtower, which kicks off the update process.

This request can take a very long time based on your internet connection, and envoy will frequently time out leading to confusion as to whether the update was successful or not.

**Conditions of Satisfaction**
- Allow users to turn on auto-update with watchtower
- Allow updating of client library for apps from the portal
- Tell users when their budibase version is out of date
- A more asynchronous update process, in which you can check if it's currently in progress or not.
- Show something when watchtower is down and not working correctly
- Show when an update is in progress
- Show previous updates (store in couch)

**Comment by Rory-Powell** [comment]
Some preliminary work has been started to get watchtower to write lifecycle status to disk for server / worker
https://github.com/Budibase/budibase/commit/25a737ac742a1122d7cd84d4ff671f03c4fc244a
