### ISSUE TITLE
More outgoing webhook issues

### ISSUE THREAD

**Issue by burnoutberni** [Budibase/budibase#1854]
Thanks for your work with #1815 #1809, things are definitely better now. Unfortunately, more complicated webhook actions still seem to fail.

**Describe the bug**
Now that I'm able to post data from Budibase somewhere else, I tried pushing all of the data from my test table. My table includes a column ("Bebilderung") of the type "Attachment", which is basically an array as I understand it. I don't actually need the whole attachment, I'm fine with pushing an array of URLs to the webhook recipient. Unfortunately, I'm unable to make it work.

One core issue seems to be that I have to surround handlebar items with quotes, otherwise the webhook fails silently.

```
{ 
  "Titel": "{{ trigger.row.Titel }}",
  "Textvorschlag": "{{ trigger.row.Textvorschlag }}",
  "Bebilderung": "{{ trigger.row.Bebilderung }}",
  "Deadline": "{{ trigger.row.Deadline }}"
}

# Output
{
  Titel: 'test',
  Textvorschlag: 'test',
  Bebilderung: '[object Object],[object Object]',
  Deadline: '2021-06-30T22:00:00.000Z'
}
```

As you can see, the individual attachment objects get cast to string, so they become useless. When I substitute `"{{ trigger.row.Bebilderung }}"` with `[{{ trigger.row.Bebilderung }}]`, the test automation feature returns an empty array, but when the webhook gets triggered for real, it silently fails and doesn't post.

I tried using handlebar logic to build my own array (some variations of `{{#forEach}}` and `{{arrayify}}` mainly, e.g. `"Bebilderung": "{{#forEach {{ trigger.row.Bebilderung }} }} {{ url }} {{/forEach}}"`), but I don't seem to get it to work.

Sometimes the editor shows a warning `Current Handlebars syntax is invalid, please check the guide here for more details.`, but that seems very random. Other than that there's no error messages in the editor, so you're left with hoping something comes out on the other side of the webhook and debug from there. Unfortunately, the test automation feature doesn't really help either, since the attachment type doesn't seem to be defined, so debugging has a lot of extra steps involved. This is quite frustrating, tbh.

**To Reproduce**
1. Define table with Attachment-type column
2. Create automation with outgoing webhook
3. Try defining a webhook where any attachment data is actually usable

**Expected behavior**
Webhook recipient receives attachment data (preferably array of objects).

**Comment by burnoutberni** [comment]
One more thing: It would be really nice to have an actual editor instead of a `<textarea>` to define the webhook JSON, but I understand that that's probably to much work for now. A low-hanging fruit would be to use a monospace font there to improve readability.

**Comment by burnoutberni** [comment]
Figured out how to do the things I wanna do, the key is to find the documentation of [available Handlebar handlers in Budibase](https://github.com/Budibase/handlebars-helpers) (don't think it is linked to in the docs, I think it should be added prominently [here](https://docs.budibase.com/design/binding)).

Sorry once again, I've also been asked to not spam the issues in another issue. I'll show myself to the door now ;)

**Comment by shogunpurple** [comment]
@burnoutberni great to hear you got sorted. I've added the link to the handlebars repo in the docs, as you have suggested. 

Thanks again!
