### ISSUE TITLE
BB App is in loading loop

### ISSUE THREAD

**Issue by PGLange** [Budibase/budibase#1862]
**Describe the bug**
When a user with role PUBLIC logs in and opens an application, the browser is constantly reloading. Rights are set properly in the platform and in the app.
Administrative or developer users can login and use the app. Even without the dev_ part of the url.
The bb plattform is reachable and a login is possible.
Server OS is an up-to-date Ubuntu 20.04.2 LTS

**To Reproduce**
1. Open Browser
2. point to bb app url
3. Login with a User with BASIC Role 
4. Site will load over and over again

**Expected behavior**
Show the app

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Safari / Crome / Firefox / Edge

**Additional context**

**Comment by aptkingston** [comment]
Hi @PGLange. I can confirm that I can reproduce this, and I've found the root cause. We'll get this fixed.

**Comment by aptkingston** [comment]
v0.9.71 has been released and should be generally available shortly, which fixes this.
