### ISSUE TITLE
Action (email/smtp) bindings not working

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1864]
**Describe the bug**
Adding bindings to an email/smtp action does not work.

@mike12345567 has seen a demo of this, but ultimately, when you add a binding to the SMTP email action, the contents of that binding do not appear.

![Screenshot 2021-06-28 at 13 32 52](https://user-images.githubusercontent.com/49767913/123638342-f965a380-d816-11eb-9d56-147a8e405cb8.png)

**Comment by shogunpurple** [comment]
@joebudi is this just with any binding, or which one did you use? Would be good to see your template just for repro.

**Comment by joebudi** [comment]
Hey! It's possibly the swag template in staging

**Comment by mike12345567** [comment]
I've just tested this, believe it has been resolved with all of the work that was done on automations, I can't recreate this.
