### ISSUE TITLE
Compare timestamp with now

### ISSUE THREAD

**Issue by burnoutberni** [Budibase/budibase#1865]
I'd like to build an app where I show a subset of table items to the user, depending on the timestamp in one of the columns (see screenshot below).

![Screenshot from 2021-06-28 16-21-04](https://user-images.githubusercontent.com/1640933/123652976-0d1c0480-d82d-11eb-8dbd-9ecfc74389ac.png)

Unfortunately, I can only compare with a static timestamp, but in this case I only want to show items in the future. An alternative approach would be to use queries, but I'm storing this data in the Budibase DB for now, so I can't write my own.

**Comment by aptkingston** [comment]
Hey @burnoutberni. You can do this using a binding like `{{ now }}` which will use the current date. We use Handlebars for our bindings (docs [here](https://docs.budibase.com/design/binding)).

**Comment by aptkingston** [comment]
I'm closing this off as my example above let's you do this. In future, please open a discussion if you're looking for help or advice rather than an issue. Thanks!

**Comment by burnoutberni** [comment]
Ah, thanks – regarding discussions, will do :)
