### ISSUE TITLE
Container property Transition Style missing

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#1872]
The Transition style (fly, scale, fade.. etc)  field/property missing in the builder. Unable to set the animation style for containers.

Budibase v0.9.65
Google Chrome latest
Windows 10/docker

**Comment by aptkingston** [comment]
Hi @sergey-dme. We've removed the transition property in an effort to consolidate component settings into only those settings which provide real value for the components. The transition property did not provide much value for production grade apps, and was more of a novelty. If you've got a good use case for animating your containers then please raise a discussion, but for now you won't be able to animate your containers.

**Comment by sergey-dme** [comment]
I've tried to explain 

https://github.com/Budibase/budibase/discussions/1888
