### ISSUE TITLE
Ability to change a string column type to options for a data source plus table

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#1878]
### Discussed in https://github.com/Budibase/budibase/discussions/1877

When I'm setting up a set of data source plus tables from an external data connector (e.g. a Postgres/MySQL table) I want to be able to change a string column type to options and specify the list of options for that column. This allows retaining the options functionality when using an external data source.

**Comment by AndrewJRamay** [comment]
Also, a great addition to your SQL connector would be Data validation. right now I can put text in a number field, it will cause the write to external SQL DB to fail. it would be great to be able to validate the form even in the simplest form of is this a number field or a text field

**Comment by AndrewJRamay** [comment]
Another thing would be to pull in the columns in the same order they are in my SQL DB. I have all of my columns in alphabetical order because there are a good 200 of them and it's a pain to find them when they are all mixed up.

**Comment by AndrewJRamay** [comment]
a Third thing is when switching from the internal DB schema to an external DB with the new SQL connector the fields in the form that previously where numbers are not being identified as number fields. in txt fields, you are able to select any column in the external DB. it is not until I delete the form number input and re-add it can I then select a number column it will write to in my external DB.

**Comment by shogunpurple** [comment]
Thank you for your suggestions @AndrewJRamay - I think there's actually a bug or two there. The form validation should work for any number field in your DB so think there's a potential issue there.

- Making the tables alphabetical makes sense. I've added this into my branch so you'll see that in the next release
- Will look into your bug with switching between internal/external schemas with forms. Thanks for reporting.

**Comment by AndrewJRamay** [comment]
Thank you, happy I can help.

**Comment by AndrewJRamay** [comment]
Hi, I know you guys are crazy busy, just wondering if the SQL options picker feature is in the works or still just an idea? my application is built around option selections to minimize data input errors and I can not use the new SQL connector without it.
