### ISSUE TITLE
MySQL Connector mysql2 upgrade: MySQL 8 with new pluggable auth causing error when adding as a datasource

### ISSUE THREAD

**Issue by zeryl** [Budibase/budibase#1899]
**Describe the bug**
I attempted to create a new datasource from a MySQL 8 instance, and the app cannot connect

**To Reproduce**
1. New Datasource
2. Select MySQL
3. Enter credentials and hit save
4. Attempt to fetch tables, get an error

**Expected behavior**
It connects as expected

Looking at stackoverflow, it looks like mysql npm library does not support the pluggable auth in MySQL 8.  I can downgrade, but, the proper solution is to move to a library supporting it:

Reference: https://stackoverflow.com/a/56509065

Supported Module: https://www.npmjs.com/package/mysql2

**Comment by shogunpurple** [comment]
Thanks for this one @zeryl - it looks like it would be worth it for us to upgrade to the `mysql2` library anyway, as it brings a whole host of other benefits. I've updated the title of this one to migrate that data source to the `mysql2` package, and we will get it resolved as soon as we can. 

Thanks!

**Comment by shogunpurple** [comment]
bump
