### ISSUE TITLE
Design preview shows up for a second and then disappears

### ISSUE THREAD

**Issue by vigneshvelu** [Budibase/budibase#1901]
**Describe the bug**
As I mentioned in the title, when I click on a component in design, it shows up for a second before disappearing.

This is a video of what it looks like on my screen. 

https://user-images.githubusercontent.com/24852619/124240101-08f72c00-db38-11eb-8e06-569f21bc49ba.mp4

Here is the console errors:
`TypeError: NetworkError when attempting to fetch resource.                       index.26eac5ea.js:215:1045864

Empty string passed to getElementById().                                                       230 autofill.js:252:20
`

**Desktop (please complete the following information):**
 - OS: Macos 11.4
 - Browser: Firefox Nightly
 - Version: 91.0

**Comment by aptkingston** [comment]
@vigneshvelu we're just released a new version which might help identify the issue here. Could you try updating your environment and trying again?

**Comment by Bongzy13** [comment]
Hi, I am facing the same problem with the design preview (discussed here: https://github.com/Budibase/budibase/discussions/1979)

the error might be related with a message appearing a ton of time on the webconsole: 
```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    receiveMessage about:srcdoc:51
```

**Comment by aptkingston** [comment]
@Bongzy13 can you please ensure your environment is up to date, then export and import your app again to see if that fixes the problem? We've made the updating process much easier, but it's just not released yet so for the moment you'll need to export and then import your app again to update it.

I also assume this only happens for existing apps, but doesn't happen if you create a new app?

**Comment by Bongzy13** [comment]
@aptkingston thanks for your replies. This happens also with new apps as well. I tried export/reimport but still no preview.

is `docker-compose pull` enough to make sure the environment is up to date? If yes, then I confirm it is
