### ISSUE TITLE
Can't make the Option Picker + binding with Data Provider work

### ISSUE THREAD

**Issue by poppash** [Budibase/budibase#1902]
It can't reproduce this one: https://www.youtube.com/watch?v=hmmLdeY-5d4. I.e., make the Option Picker + binding with Data Provider work.

As is show, I create a route/screen like:

```sh
Form
| Container
| - Option Picker
| Data Provider
| - Table
```

Then, I make sure to go Data Provider > Define filter and bind the Option Picker with the Data Provider. The data shows, but the Picker isn't being populated.

And ideas?

**Comment by joebudi** [comment]
Hey! 

Did you follow the following steps:
1. Connect form the table
2. Connect options picker to field
3. Click filter on your data provider - in the binding drawer, use the same field as the options picker, then 'equals' then click the lightning bolt, and choose something like '[[new.form.fields.YOURCATEGORY]] - this should be the first option - then click save, and save again. Below is a quick image of what the filter should look like.

It will look something like this
![Screenshot 2021-07-02 at 10 00 34](https://user-images.githubusercontent.com/49767913/124250026-5b2a5400-db1c-11eb-8963-2e7b3c82c36a.png)

**Comment by poppash** [comment]
Hi! Thanks for the quick reply. It look like this now:

![image](https://user-images.githubusercontent.com/12220670/124262524-743dff80-db32-11eb-961e-dd37429ddfba.png)

How do I connect the form to the table explicitly (where in the YouTube clip is it done?). I'm only aware of the requirement to bind the picker to the data provider (and did that), but might be mistaken.

Cheers,
Wessel

**Comment by joebudi** [comment]
I can jump on a call for a few minutes and check out your setup if you like?

**Comment by poppash** [comment]
That'd be great. How to easily get in touch? Is Budibase on Slack?

**Comment by joebudi** [comment]
meet.google.com/zat-qcwg-quv

**Comment by poppash** [comment]
Resolved! One has to make sure to, when creating a new table, mark the desired columns with datatype `Options`. I.e., in the case described above:

![image](https://user-images.githubusercontent.com/12220670/124280055-84f97000-db48-11eb-851f-6127723591a1.png)

Thanks @joebudi for pointing this out. Great help.
