### ISSUE TITLE
Error after starting budibase for the first time: `upstream connect error..` because some containers keep restarting

### ISSUE THREAD

**Issue by AmateurAcademic** [Budibase/budibase#1909]
**Describe the bug**
`upstream connect error or disconnect/reset before headers. reset reason: connection failure`

**To Reproduce**
1. installed the CLI
2. `budi hosting --init `
2. I modified the docker-compose file as stated in the instructions for ARM
3. `budi hosting --start `
4. Go to the internal URL with correct port (ie `http://localhost.local:1234`)

**Expected behavior**
Instead of this error there should be the screen for creating an admin user.

**Desktop (please complete the following information):**
 - OS: Raspbian  Buster (aarch64/arm64)
 - Browser: Firefox (latest)
 - Version: latest version of Budibase (I just tried it for the first time now)

**Additional context**
When I check the status of the containers I see that: 
`bbapps`, `bbworker`, and `budibase_couchdb-service_1` keep restarting. So something is wrong there.

**Comment by Rory-Powell** [comment]
Hey @AmateurAcademic, would you be able to check out the logs of the restarting containers for more details?
You should be able to list the containers with `docker ps`, select the container id and then use `docker logs <id>`

Can you confirm the URL you are accessing? It should be `http://localhost:10000/`
It might also be useful to see a screenshot of your error with the developer tools console open

**Comment by AmateurAcademic** [comment]
Hi @Rory-Powell , thanks for the swift reply! Here are those logs from the containers:

bbapps,  bbworker, budibase_couchdb-service_1:
`standard_init_linux.go:219: exec user process caused: exec format error`

And yes, the URL is correct. I run other services on the same system and they work with the same URL (different ports of course). 

If I had to take a guess, I would say despite what you write in your [documentation](https://docs.budibase.com/getting-started/budibase-cli-setup):

"If you have an ARM based CPU, you will have to make a slight update to your docker-compose.yaml . Update the couchdb-service part of your compose config with 
platform: amd64",

This architecture is not supported via your docker images. Have you or your team tested this on ARM architecture (specifically in this case aarch64)? Also out of curiosity (I am no professional docker user or anything, just enough to get my services working), why would you want to set the platform as amd64 when the platform is actually arm64? Just for the heck of it, I gave it a try with arm64, but there is no pre-made image for couchDB from this source for arm64, so that failed completely and exited your CLI.

**Comment by Rory-Powell** [comment]
Thanks for the logs! I'm not too sure on those, is that the same error across all three containers having issues? 

Apologies it looks like our documentation is slightly out of date in that regard, there's an additional step you might have to take to enable the emulation. See the details in this discussion

https://github.com/Budibase/budibase/discussions/1647#discussioncomment-923660

**Comment by AmateurAcademic** [comment]
Hi @Rory-Powell, once again thanks for the reply. I checked out [#1647 (comment)](https://github.com/Budibase/budibase/discussions/1647#discussioncomment-923660). This makes more sense. So for running on ARM, you want to enable emulation  for x86. This is really what I was missing. 

However, I thought I'd give it a try with building the images with issues on the machine itself.

* budibase_couchdb-service_1: it was a simple matter of switching in the `docker-compose.yaml` file from `ibmcom/couchdb3` to `couchdb`. This fixed that issue. Although I am not sure honestly of the difference between the two, besides the fact that `couchDB` has an image for ARM. Is there any reason not to change this?
* For the other containers, I first cloned your repo.
* bbworker: I am guessing that is located in the dockerfile here: `budibase/packages/worker`, I ran a simple `docker build .` command there to build the image.
* bbapps: I couldn't find this as a specific directory like with worker, but I am guessing(?) it is the dockerfile here `budibase/packages/server`. Same procedure as bbworker. 
* edited the `docker-compose.yaml` file, to point to the images I built. 
* ran the `budi hosting --start` command. 

The containers are now stable, however I am getting the following error reported via the browser when I go to the URL:
```
message | "ENOENT: no such file or directory, stat '/app/builder/index.html'"
```
So what did I do wrong?

Here are the logs:

bbapps: 
```
yarn run v1.22.5
$ node dist/index.js
Budibase running on {"address":"::","family":"IPv6","port":4002}
```
bbworker:
```
yarn run v1.22.5
$ node src/index.js
Worker running on {"address":"::","family":"IPv6","port":4003}
```
budibase_couchdb-service_1:
```
[info] 2021-07-04T13:49:22.361297Z nonode@nohost <0.11.0> -------- Application couch_log started on node nonode@nohost
[info] 2021-07-04T13:49:22.392724Z nonode@nohost <0.11.0> -------- Application folsom started on node nonode@nohost
[info] 2021-07-04T13:49:22.709941Z nonode@nohost <0.11.0> -------- Application couch_stats started on node nonode@nohost
[info] 2021-07-04T13:49:22.711596Z nonode@nohost <0.11.0> -------- Application khash started on node nonode@nohost
[info] 2021-07-04T13:49:22.799835Z nonode@nohost <0.11.0> -------- Application couch_event started on node nonode@nohost
[info] 2021-07-04T13:49:22.800876Z nonode@nohost <0.11.0> -------- Application hyper started on node nonode@nohost
[info] 2021-07-04T13:49:22.824249Z nonode@nohost <0.11.0> -------- Application ibrowse started on node nonode@nohost
[info] 2021-07-04T13:49:22.854307Z nonode@nohost <0.11.0> -------- Application ioq started on node nonode@nohost
[info] 2021-07-04T13:49:22.855132Z nonode@nohost <0.11.0> -------- Application mochiweb started on node nonode@nohost
[info] 2021-07-04T13:49:22.879345Z nonode@nohost <0.215.0> -------- Preflight check: Asserting Admin Account

[info] 2021-07-04T13:49:22.892548Z nonode@nohost <0.215.0> -------- Apache CouchDB 3.1.1 is starting.

[info] 2021-07-04T13:49:22.892856Z nonode@nohost <0.216.0> -------- Starting couch_sup
[notice] 2021-07-04T13:49:22.983809Z nonode@nohost <0.81.0> -------- config: [admins] HVjoeUSunEPCgLZUnAI5Home0RF0mPf2 set to -pbkdf2-b34c6b75486f70d387e4a3ac0b21feabbf16c10b,40052f5685238d56dbcb9c3326b43aaf,10 for reason nil
[info] 2021-07-04T13:49:23.189088Z nonode@nohost <0.215.0> -------- Apache CouchDB has started. Time to relax.

[info] 2021-07-04T13:49:23.212516Z nonode@nohost <0.11.0> -------- Application couch started on node nonode@nohost
[info] 2021-07-04T13:49:23.213327Z nonode@nohost <0.11.0> -------- Application ets_lru started on node nonode@nohost
[notice] 2021-07-04T13:49:23.305777Z nonode@nohost <0.249.0> -------- rexi_server : started servers
[notice] 2021-07-04T13:49:23.334857Z nonode@nohost <0.253.0> -------- rexi_buffer : started servers
[info] 2021-07-04T13:49:23.335785Z nonode@nohost <0.11.0> -------- Application rexi started on node nonode@nohost
[warning] 2021-07-04T13:49:23.599911Z nonode@nohost <0.261.0> -------- creating missing database: _nodes
[info] 2021-07-04T13:49:23.600229Z nonode@nohost <0.262.0> -------- open_result error {not_found,no_db_file} for _nodes
[warning] 2021-07-04T13:49:24.148833Z nonode@nohost <0.277.0> -------- creating missing database: _dbs
[warning] 2021-07-04T13:49:24.149184Z nonode@nohost <0.276.0> -------- creating missing database: _dbs
[info] 2021-07-04T13:49:24.149445Z nonode@nohost <0.279.0> -------- open_result error {not_found,no_db_file} for _dbs
[notice] 2021-07-04T13:49:24.286934Z nonode@nohost <0.291.0> -------- mem3_reshard_dbdoc start init()
[notice] 2021-07-04T13:49:24.332372Z nonode@nohost <0.293.0> -------- mem3_reshard start init()
[notice] 2021-07-04T13:49:24.332706Z nonode@nohost <0.294.0> -------- mem3_reshard db monitor <0.294.0> starting
[notice] 2021-07-04T13:49:24.345814Z nonode@nohost <0.293.0> -------- mem3_reshard starting reloading jobs
[notice] 2021-07-04T13:49:24.346116Z nonode@nohost <0.293.0> -------- mem3_reshard finished reloading jobs
[info] 2021-07-04T13:49:24.360355Z nonode@nohost <0.11.0> -------- Application mem3 started on node nonode@nohost
[info] 2021-07-04T13:49:24.361756Z nonode@nohost <0.11.0> -------- Application fabric started on node nonode@nohost
[info] 2021-07-04T13:49:24.876432Z nonode@nohost <0.11.0> -------- Application chttpd started on node nonode@nohost
[info] 2021-07-04T13:49:24.940922Z nonode@nohost <0.11.0> -------- Application couch_index started on node nonode@nohost
[info] 2021-07-04T13:49:24.941677Z nonode@nohost <0.11.0> -------- Application couch_mrview started on node nonode@nohost
[info] 2021-07-04T13:49:24.955393Z nonode@nohost <0.11.0> -------- Application couch_plugins started on node nonode@nohost
[notice] 2021-07-04T13:49:25.023890Z nonode@nohost <0.323.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
[error] 2021-07-04T13:49:25.024208Z nonode@nohost emulator -------- Error in process <0.324.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,96}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}

[info] 2021-07-04T13:49:25.393065Z nonode@nohost <0.11.0> -------- Application couch_replicator started on node nonode@nohost
[info] 2021-07-04T13:49:25.574001Z nonode@nohost <0.11.0> -------- Application couch_peruser started on node nonode@nohost
[info] 2021-07-04T13:49:25.782289Z nonode@nohost <0.11.0> -------- Application ddoc_cache started on node nonode@nohost
[info] 2021-07-04T13:49:25.930865Z nonode@nohost <0.11.0> -------- Application dreyfus started on node nonode@nohost
[info] 2021-07-04T13:49:26.152560Z nonode@nohost <0.11.0> -------- Application global_changes started on node nonode@nohost
[info] 2021-07-04T13:49:26.152646Z nonode@nohost <0.11.0> -------- Application jiffy started on node nonode@nohost
[info] 2021-07-04T13:49:26.271737Z nonode@nohost <0.11.0> -------- Application jwtf started on node nonode@nohost
[info] 2021-07-04T13:49:26.340906Z nonode@nohost <0.11.0> -------- Application ken started on node nonode@nohost
[info] 2021-07-04T13:49:26.398013Z nonode@nohost <0.11.0> -------- Application mango started on node nonode@nohost
[info] 2021-07-04T13:49:26.428783Z nonode@nohost <0.11.0> -------- Application setup started on node nonode@nohost
[info] 2021-07-04T13:49:26.559270Z nonode@nohost <0.11.0> -------- Application smoosh started on node nonode@nohost
[info] 2021-07-04T13:49:26.561131Z nonode@nohost <0.11.0> -------- Application snappy started on node nonode@nohost
[info] 2021-07-04T13:49:26.562925Z nonode@nohost <0.11.0> -------- Application recon started on node nonode@nohost
[error] 2021-07-04T13:49:29.598255Z nonode@nohost <0.446.0> 2da14d28dc Request to create N=3 DB but only 1 node(s)
[notice] 2021-07-04T13:49:29.835797Z nonode@nohost <0.446.0> 2da14d28dc couchdb-service:5984 172.27.0.6 HVjoeUSunEPCgLZUnAI5Home0RF0mPf2 PUT /_users 201 ok 368
[error] 2021-07-04T13:49:29.851627Z nonode@nohost <0.447.0> 637a1392e4 Request to create N=3 DB but only 1 node(s)
[notice] 2021-07-04T13:49:29.921908Z nonode@nohost <0.447.0> 637a1392e4 couchdb-service:5984 172.27.0.6 HVjoeUSunEPCgLZUnAI5Home0RF0mPf2 PUT /_replicator 201 ok 73
[notice] 2021-07-04T13:49:30.139217Z nonode@nohost <0.345.0> -------- couch_replicator_clustering : cluster stable
[notice] 2021-07-04T13:49:30.360760Z nonode@nohost <0.355.0> -------- Started replicator db changes listener <0.528.0>
[info] 2021-07-04T13:49:30.362592Z nonode@nohost <0.530.0> -------- open_result error {not_found,no_db_file} for _replicator
[notice] 2021-07-04T13:49:30.525591Z nonode@nohost <0.528.0> -------- creating replicator ddoc <<"shards/80000000-ffffffff/_replicator.1625406569">>
[notice] 2021-07-04T13:49:38.306285Z nonode@nohost <0.249.0> -------- rexi_server : cluster stable
[notice] 2021-07-04T13:49:38.309231Z nonode@nohost <0.253.0> -------- rexi_buffer : cluster stable
```

**Comment by Rory-Powell** [comment]
>Although I am not sure honestly of the difference between the two, besides the fact that couchDB has an image for ARM. Is there any reason not to change this?

See the response here: https://github.com/Budibase/budibase/discussions/1647#discussioncomment-833708

Your assumptions are spot on the for the docker images, here is the script that tags the worker and server directory 
https://github.com/Budibase/budibase/blob/2f4e85c64ec825a32ca9fc8970e63d9ce16caa8c/hosting/scripts/linux/release-to-docker-hub.sh#L12-L13

Right now the official solution is to run emulation, in the future we will look to support arm64 out of the box. 

Thank you for the detailed logs! This really helps when debugging. I'm not sure on the index not found error you are seeing, maybe @shogunpurple or @mike12345567 will have more context

**Comment by shogunpurple** [comment]
@AmateurAcademic the index problem is possibly down to the use of the couchdb image instead of ibmcom/couchdb3. The IBM image comes pre packaged with search functionality and indexing built on Apache lucene. You have to use this image to use Budibase.

Also, there's an image that is part of the docker compose configuration called couchDB-init. This script needs to run to bootstrap your couchDB instance. Has this been run?

**Comment by dopestfinancial** [comment]
@shogunpurple,  yes that script was run. 

I don't have any experience running emulation with docker, but I doubt it will be very efficient to run such emulation on a tiny raspberry pi (or is it somehow not so intense and I am over thinking it?). I guess I will just wait until your platform works on ARM. 

Thanks very much for all of the input!

**Comment by AmateurAcademic** [comment]
@shogunpurple, yes that script was run. 

I don't have any experience running emulation with docker, but I doubt it will be very efficient to run such emulation on a tiny raspberry pi (or is it somehow not so intense and I am over thinking it?). I guess I will just wait until your platform works on ARM. Is there anything I can do to help speed this along? 

Thanks very much for all of the input!
