### ISSUE TITLE
Querying Mongo

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1921]
### Discussed in https://github.com/Budibase/budibase/discussions/1886

<div type='discussions-op-text'>

<sup>Originally posted by **raghunami25** June 30, 2021</sup>
Hey There,
 I want to try querying external mongo DB, but I didn't find any documentation on it. I tried doing it by myself, but it didn't work and am not able to figure out the query. Can you please help me?

Thanks.</div>

**Comment by faroutchris** [comment]
Duplicate of #1963 :) Should probably close this too

**Comment by shogunpurple** [comment]
Thanks @faroutchris !
