### ISSUE TITLE
Can't assign other users in my app

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1922]
### Discussed in https://github.com/Budibase/budibase/discussions/1706

<div type='discussions-op-text'>

<sup>Originally posted by **hshifaz** June 12, 2021</sup>
Need help in figuring this out!

Lets consider 2 Internal tables, Users (default) and Projects. In this App, each project will have a Manager and it is a Relationship field linked to Users table.

![cant assign new users 3](https://user-images.githubusercontent.com/14042347/121782574-05870b00-cb5f-11eb-9fd1-5ebc7bdd5424.PNG)

In the Data table Project, when creating or updating a record, I can select the default user (user which was created as part of the installation of Budibase). However, other users I've created can't be assigned. The message shows "Row Saved Successfully", but as you can see on the screenshot, it is not.

![cant assign new users 1](https://user-images.githubusercontent.com/14042347/121782590-1cc5f880-cb5f-11eb-9093-42fe1d990d05.PNG)
![cant assign new users 2](https://user-images.githubusercontent.com/14042347/121782601-26e7f700-cb5f-11eb-96d8-6899fce7b8d8.png)

_**I've blur or cut out some personal info.**_

I've checked the following
1- Whether User is active
2- Gave Admin access also, changed to Public to test.

Could anyone help me figure this out, please.

Thank you in Advance.</div>

**Comment by joebudi** [comment]
FYI, I've run into this issue twice now. It's pretty essential for assigning tasks/tickets to users. It's a blocker for me now.
