### ISSUE TITLE
Default svelte prop values being ignored by the builder. Setting default value in components.json not supported.

### ISSUE THREAD

**Issue by Conor-Mack** [Budibase/budibase#193]
Svelte allows for setting default values for props whenever a component is declared:

```
  export let width = "350px"
  export let height = "auto"
```
These are getting ignored by the builder. 

`components.json` allows for setting default values for`"type": "option"` properties. It would be nice if it were possible to also set default values for non option types like so: 

```
"props": {
      "width": {"type": "string", "default": "350px"},
      ...
}
```

**Comment by Conor-Mack** [comment]
Update: builder already supports defaulting non-option type props but this doesn't appear to be working currently.

**Comment by mjashanks** [comment]
Think we got to the bottom of this. 

Conor had added a component, then set the default prop in the library. He was then expecting the value in his existing component to be set tot  the default. 

This is not the case, and shouldn't be, as an empty value can be a valid value.
