### ISSUE TITLE
Date filtering doesn't work since recent work on HBS enrichment removed date post-processing

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#1931]
As part of the recent work on optimising HBS enrichment, we removed the recursive function which used to go though context and transform date objects into ISO strings. A consequence of this is that HBS now enriches date objects with just a `toString()` meaning they get transformed into something like `Wed Jul 16 2014 12:00:00 GMT+0100 (British Summer Time)` instead of `2014-07-16T11:00:00.000Z`. 

This format is not compatible with Lucene searching, so currently doing any filtering on a `datetime` field will return 0 results.

This fix for this is simply parsing the data in data providers for any `datetime` fields and building the lucene query with ISO strings like before.

**Comment by aptkingston** [comment]
Fixed via dfc499c034eba3ed5bad0a85424df9f634539029.

**Comment by EduZeroum** [comment]
It is fixed already because i tested it and it doesnt work.

**Comment by aptkingston** [comment]
It has been merged into the `develop` branch which means it will be published alongside our next release. I have some other fixes in the works which will be going straight to `master` today, meaning they will be released today, so I will actually pull this fix in too so that it is released today.

**Comment by EduZeroum** [comment]
> It has been merged into the `develop` branch which means it will be published alongside our next release. I have some other fixes in the works which will be going straight to `master` today, meaning they will be released today, so I will actually pull this fix in too so that it is released today.

Ok, thank you.

**Comment by aptkingston** [comment]
v0.9.71 has been released and should be generally available shortly, which fixes this.

**Comment by EduZeroum** [comment]
@aptkingston I tried and the error still remains, i put the data provider to change when date is equals {{ Forma.Fields.Data I }}

**Comment by EduZeroum** [comment]
And now it doesn't load my website in preview... 
![image](https://user-images.githubusercontent.com/87012689/124749993-d5901500-df1c-11eb-81a5-97627a4510ab.png)

**Comment by aptkingston** [comment]
@EduZeroum we're still working on a way to update the version of the client library used for apps. For now, you'll need to export your app and then import it again to use the new update. Sorry I should have said that in my post earlier.
