### ISSUE TITLE
New SQL connector has a few bugs, number columns do not populate. 

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#1943]
Hi guys, 
I am still having a lot of problems with the new SQL data connector. I mentioned some of them under issue #1878. 
the biggest problem I am having is that it will not identify number columns as numbers and txt columns as text. the only number that shows up is my row id.  before if I re-added the number form it would correct this now it does not.  I'm just stuck with all text inputs which won't submit because the SQL wants a number.  

![image](https://user-images.githubusercontent.com/80058238/124788095-eed59900-defd-11eb-9b9e-a931a4669fc0.png)

**Comment by AndrewJRamay** [comment]
Hi guys, 
The New SQL data connector is kicking out my dates again. they work with MongoDB but they do not work with MYSQL. 
![image](https://user-images.githubusercontent.com/80058238/125118950-42ceb200-e0a5-11eb-8f8d-e599bf45e90f.png)
I have tried all of the date formats in MYSQL and none of them work. really hoping for a quick fix on all of the issues with the new SQL data connector.

**Comment by mike12345567** [comment]
Hi @AndrewJRamay - sorry about this, could you provide me with a list of the column types that you have tried and had issues with, so that I may try replicate the issues you're seeing?

**Comment by AndrewJRamay** [comment]
Hi @mike12345567 I have been bouncing back and forth between PostgreSQL and My SQL when switching schema from internal DB to a new external DB  both are not able to retain the number field in the forms. sometimes I can get the number form to work if I remove and re-add the form, however, most times numbers will not work in the external SQL schema. 

the big thing for dates is it works in PostgreSQL using the date format  "timestamp without time zone" however in My SQL I can not use that format, I have tried [ Date, Datetime, Timestamp, time, year] i would think timestamp would work it has the date and time in UTC however it still fails. 

lastly, the option picker function working for the external SQL DB is a huge must for me. is this something that is being worked on or just talked about at this point?

**Comment by AndrewJRamay** [comment]
I had an idea of how to get the option picker to work for the SQL connector. 
I basically had two different forms one with the SQL connection one with the internal DB connection. the internal schema controls the option picker, then I would use the add column function in the button to write what was imputed into the options picker field to the SQL connection however I just keep getting null values. cleaning this up might be a quick and easy way to make the options picker work with the SQL.   

![image](https://user-images.githubusercontent.com/80058238/125334340-1f537380-e300-11eb-92d4-1f21671cbbc5.png)

![image](https://user-images.githubusercontent.com/80058238/125334451-3db96f00-e300-11eb-9789-482b2f640020.png)

**Comment by mike12345567** [comment]
Hi @AndrewJRamay - we haven't started active development of the options picker for external data sources, but this has been discussed and will likely be implemented in the next number of weeks. It has been a request from a variety of users and I believe @shogunpurple had mentioned we would look at it for the next release.

**Comment by AndrewJRamay** [comment]
@mike12345567  thank you for the update! i look forward to testing it out!

**Comment by AndrewJRamay** [comment]
Hi @mike12345567 another thing to look at, in my tests with MySQL, BB is pulling in the primary key column then displaying it as a posable input column. this will then make the row unable to save.   
![image](https://user-images.githubusercontent.com/80058238/125361376-14113f80-e322-11eb-9306-1db76a15d191.png)

**Comment by mike12345567** [comment]
> Hi @mike12345567 another thing to look at, in my tests with MySQL, BB is pulling in the primary key column then displaying it as a posable input column. this will then make the row unable to save.
> ![image](https://user-images.githubusercontent.com/80058238/125361376-14113f80-e322-11eb-9306-1db76a15d191.png)

This issue has been fixed in our development branch, in the best version if you have a sequence/incrementing primary key it will be marked as a auto column and become read only.

**Comment by AndrewJRamay** [comment]
@mike12345567  YOUR THE MAN! Thank you!

**Comment by AndrewJRamay** [comment]
Hi, @mike12345567  just curious what is considered the next version. I would like to stay on the stable releases if I can. there have been two releases since the above conversation 9.74 & 9.75 are these not considered the next version?

**Comment by mike12345567** [comment]
Hi @AndrewJRamay - we make very minor bug fixes from time to time oh the master branch, any larger features or fixes will generally go into our development branch and then be prepared for release once they've gone through a testing cycle. These sort of releases we will make a big point about, such as tagging a new release on github.

The SQL fixes/features discussed above were part in f a larger section of work so they are currently in the QA phase on our development branch, there will be an announcement when they are launched.

**Comment by AndrewJRamay** [comment]
@mike12345567  Awesome thank you for the clarification. I appreciate all the hard work you and your team are doing!
