### ISSUE TITLE
Postgres - Query values must be an array

### ISSUE THREAD

**Issue by ChronSyn** [Budibase/budibase#1954]
**Describe the bug**
Using a `SELECT` read query against Postgres returns an error: `Query values must be an array`

**To Reproduce**
1. Create a link to a Postgres data source and fetch the schema
2. Click on 'Add Query' at the bottom
3. Select `Read` as function type and enter a query name
4. Add parameters
5. Enter SQL query in `Fields`
6. Click 'Run Query'

**Expected behavior**
I expect the query to run and return data, and to allow me to save the query for use in my designs.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91

**Additional context**
I am querying against a stored procedure (which works correctly when run via any PG SQL tool). However, even when trying to query using a normal `SELECT` query run directly against a table, I am not able to retrieve any results.

The video at https://docs.budibase.com/data/data-sources/queries shows an example, but I was not able to adapt my query following that video without the above error being returned.

Example query:
```
SELECT * FROM my_stored_procedure('{{ search_value }}');
```

`search_value` is defined as a parameter. The issue exists whether a default/fallback value is provided or even if it is empty.
Procedure here has been change to `my_stored_procedure` from the actual name of the procedure in the database.

Chrome dev console doesn't provide any info other than a 500 error, and the error message above.

**Comment by davepile** [comment]
Same issue, but regular query, not a stored procedure. Budibase downloaded and installed today via budibase cli

**Comment by shogunpurple** [comment]
Fixed in https://github.com/Budibase/budibase/pull/1982
