### ISSUE TITLE
Fonts: Ability to choose a font and change its size

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#196]
Currently, there is no way to choose a font. This limits design and is not a great experience. It is also not possible to change the font size.

**Comment by mjashanks** [comment]
I think the main issue here is the ability to add new web fonts to your app: #27 

In terms of selecting a font, this can be done easily, we need to expose the right props on components.

Theres an argument for creating a "font" prop type, which associated font control in the builder : #38

**Comment by kevmodrome** [comment]
Wouldn't one "quick" solution be to utilize Google Fonts? That way you don't have to build solution to handle it locally by uploading (I guess that needs to be done for the images anyway, though) them, you can just fetch them directly from google when the user picks one.

**Comment by mjashanks** [comment]
yea absolutely - but i think we still need some way of putting a `<link href=...` tag into the `index.html` ... there is no way of doing that right now via the builder

**Comment by joebudi** [comment]
Cool. I think utilizing Google fonts would allow us to use emojis with Noto:
https://www.google.com/get/noto/
https://www.google.com/get/noto/#emoji-zsye-color
https://www.google.com/get/noto/#emoji-zsye

**Comment by davidmabelle** [comment]
Curious why this issue is closed?  I would love to be able to import custom fonts. Not just google fonts or the default font.

**Comment by oswaldB** [comment]
Hello,

Can we reopen this issue?

Is it really impossible for you to allow at least Google Font?

Thank you

**Comment by Havock94** [comment]
I've posted a workaround in [this discussion](https://github.com/Budibase/budibase/discussions/4433#discussioncomment-2701647) if it help while waiting for an official support

https://github.com/Budibase/budibase/discussions/4433#discussioncomment-2701647

**Comment by v3ss0n** [comment]
@shogunpurple  i saw this as completed , but i didn't see anywhere to do that, how can we add custom fonts ?
