### ISSUE TITLE
OIDC/OAuth Only Admin Option

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1988]
When I'm an admin using the portal, I should have the option to force all users in my org to use the OIDC or OAuth only, so that local account logins do not fail due to lack of password.

Some organisations may not want to use local budibase auth at all.

We should provide the ability to configure "OAuth/SSO only" at the org level, which will automatically set up your login page to authenticate with SSO, rather than making users click the button in the form to sign in with it specifically.

**COS**
- Org level option to force a certain auth method
- When users log in, they will only be able to avail of the org level method.

**Notes**
- A quick and dirty way to solve this would just be to show a better error message when you try to log in with a local user, but prevention is probably better than cure.

**Comment by Rory-Powell** [comment]
Is this a duplicate of: https://github.com/Budibase/budibase/issues/1986 ?
