### ISSUE TITLE
Account for TLS in redis connection

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1993]
### Discussed in https://github.com/Budibase/budibase/discussions/1991

<div type='discussions-op-text'>

<sup>Originally posted by **hammoaj** July 14, 2021</sup>
Hi - I'm trying to implement Budibase in a cloud hosted Kubernetes environment, using the cloud providers own native Redis-as-a-service (as well as their CouchDB-as-a-service and their own S3 compatible object store).

I'm coming up with issues around connecting to the Redis service as it requires TLS and looking through the code, it seems as if the Redis connection management is still quite rudimentary. Am I missing anything here? Is there a way to connect to an external Redis service (rediss://....) without some re-coding in the Redis module?

Thanks</div>

**Comment by jg33** [comment]
Hi- I'm trying to connect to my Redis DB (DigitalOcean Managed) as a data source but I can't seem to make it work, eater cloud-hosted or self- hosted. The frontend says "Error creating datasource: Unable to connect: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details." and I'm getting a "[ioredis] Unhandled error event: Error: read ECONNRESET\n" error on the back. I suspect TLS is to blame.

When I change the REDIS_URL in the docker-compose, I get a lot of errors and cannot log in. I also see there's a redis service running in the installation. I can't seem to find any information, but it seems like budibase uses redis internally?

Is this solution for this internal Redis DB? Is there something different I need to to to use a TLS-enabled redis db as a datasource?

Thanks!
