### ISSUE TITLE
When accessing URL directly in browser client side routing is not respected

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2001]
### Discussed in https://github.com/Budibase/budibase/discussions/2000

<div type='discussions-op-text'>

<sup>Originally posted by **PGLange** July 16, 2021</sup>
Hi again,
One last question to complete my app :) (Thank you for the great support 'till now!)
I begun working with roles - the basic role for data input and correction works as it should.

But the Screens that are related to POWER User Role are not accessible. Roles are setup correctly (in BB Platform and the app), but when I log in to the app and navigate the the screen via URL, only the home URL content is shown.
- No Errors in Browsers debug console
It worked once and I don't understand why it is broken now... pls have a look at the following screenshots
BB Platform Usermanagement
![error](https://user-images.githubusercontent.com/86222990/125939357-006939f8-60c6-4471-aa81-bb696f1a7671.PNG)
User in the App
![error2](https://user-images.githubusercontent.com/86222990/125939359-ee9cda81-dea1-4337-82be-3ebaf0985ba0.PNG)
The POWER USER Screen Section
![error3](https://user-images.githubusercontent.com/86222990/125939360-b9796135-cba8-42f7-ba2b-620a935741db.PNG)
And that is displayed under the ?correct? URL
![error4](https://user-images.githubusercontent.com/86222990/125939363-5df7825c-c1be-4d5f-8eef-a980bea9a2ce.PNG)

</div>

**Comment by aptkingston** [comment]
I don't think this is a bug - the client apps use hash based routing so the correct URL for any given page is
`[app ID]#/route/to/page`.
Entering this directly into the browser does work as intended. Leaving out the `#` will fall back to rendering the `/` route.

**Comment by shogunpurple** [comment]
@aptkingston good point - it's probably a matter of docs, or sharing the correct link with the client side hash route rather than accounting for it in the app. I'll close this
