### ISSUE TITLE
Prevent user row creation from the UI

### ISSUE THREAD

**Issue by powerpro-led** [Budibase/budibase#2018]
**Describe the bug**

Hello Budibaser!

1. I created a new row [user table] from user UI, it's work as picture below, there is total 3 rows then.

![image](https://user-images.githubusercontent.com/64537609/126071861-695ed5ef-5deb-4a4d-af7e-103aa2ce9dbc.png)

2. but data UI does show the new row, as it's still 2 rows there.

![image](https://user-images.githubusercontent.com/64537609/126072010-a4a6bb2d-1eea-448b-b6d9-2c72f0375e10.png)

**Comment by shogunpurple** [comment]
Hi @powerpro-led

What you are doing here is actually not possible with budibase. Users can not be created through the UI, allowing things like custom sign up processes and user creation pages. You can find more context around this in the following discussion:

https://github.com/Budibase/budibase/discussions/1975

However, we should do something about this on our side to make it impossible to create new users from the UI. I'm going to update the name of this issue to stipulate that. Thanks for raising.
