### ISSUE TITLE
cant complete post install in docker

### ISSUE THREAD

**Issue by kaminskypavel** [Budibase/budibase#2019]
**To Reproduce**
1. install budibase on docker as [described](https://docs.budibase.com/self-hosting/hosting-methods/docker-compose)
2. access `http://localhost:4002/builder/admin`
3. can't create an admin user with 404 error

**Screenshots**
![image](https://user-images.githubusercontent.com/4253088/126073147-deb9e778-7884-42d3-912c-2352c42ba93a.png)

**Desktop (please complete the following information):**
 - OS: Tried on Win10 AND on ubuntu 20.0 , both installation were done with docker
 - Docker : 
```sh
ubuntu@ubuntu:~/Desktop/budibase$ docker --version
Docker version 20.10.7, build f0df350
```
 - Browser Chome and Firefox (latest)

**Comment by shogunpurple** [comment]
Hi @kaminskypavel - you access your local installation through the envoy proxy, which is at `localhost:10000`.

I'll add this to the docs for clarity - thank you!

**Comment by kaminskypavel** [comment]
thanks for clarifying this @shogunpurple 👍

**Comment by shogunpurple** [comment]
No problem @kaminskypavel - thanks for raising this as the docs weren't clear on that docker-compose page. I've added the following:

<img width="790" alt="Screenshot 2021-07-18 at 17 01 05" src="https://user-images.githubusercontent.com/11256663/126074089-7f09f421-9980-46f2-ab80-f58f83bcac46.png">

Enjoy using budibase!
