### ISSUE TITLE
Created By and Modified By Columns are not populated.

### ISSUE THREAD

**Issue by medouederni** [Budibase/budibase#2020]
Using Budibase  0.9.73 Docker deployment on Windows
I added a new internal table (Files) with all auto columns and the related screens.
When I add a new row, the **Created By** column is empty.
I expected that the **Created By** column will be set with the current user.

Am I missing something?

_Originally posted by @medouederni in https://github.com/Budibase/budibase/issues/1022#issuecomment-878185141_

**Comment by mjashanks** [comment]
Can confirm that this is an issue - whether creating data via the builder or via the app. Have tried a few different users.

**Comment by dashrandom** [comment]
@shogunpurple for some reason I'm still experiencing this issue despite the merge. Is it because it hasn't been pushed to a release yet?

**Comment by shogunpurple** [comment]
@dashrandom are you using an existing app? The fix above will not backfill old entries.

If this occurs when you are creating a new row, is there any errors in the browser console? 

What Budibase version are you on?

**Comment by shogunpurple** [comment]
Oh also @dashrandom did you upload your data with a CSV? We noticed an issue with this and there’s a PR up to fix it:

https://github.com/Budibase/budibase/pull/2451

**Comment by dashrandom** [comment]
@shogunpurple I'm using an existing app, but updated it to version 0.9.114 of Budibase. I'm not looking to backfill old entries, I tested with new entries but it doesn't work.

Nope, not uploading with CSV either. I created actual entries both from backend and via the app and both ways the created by and updated by do not populate. Let me know if I can provide some logs or further details.

**Comment by dashrandom** [comment]
![image](https://user-images.githubusercontent.com/9287237/130762503-0cee9b43-cccb-4092-ae89-0c06485df0e7.png)

Image for reference

**Comment by shogunpurple** [comment]
@dashrandom thanks - does the issue still occur in a new app? I'm having trouble recreating it, just trying to identify how it's happening

**Comment by dashrandom** [comment]
@shogunpurple I just tested a new app and I confirm it doesn't happen with the new app! Does this mean that the upgrade process for existing apps does not move the merge fixes?

I'm going to try exporting the bugged app and reimporting to see if it fixes it and report back.

**Comment by dashrandom** [comment]
Exporting and importing the app with the issue, the same issue is carried over. I've provided the export here for you to verify on your instance.
[export (1).txt](https://github.com/Budibase/budibase/files/7046487/export.1.txt)

**Comment by dashrandom** [comment]
@shogunpurple sorry to ask so soon but any suggestions? should I just abandon the existing app and migrate to a new one from scratch?

**Comment by shogunpurple** [comment]
@dashrandom

> I just tested a new app and I confirm it doesn't happen with the new app! Does this mean that the upgrade process for 
> existing apps does not move the merge fixes?

No, it just means that there was step missing in the original app and your data ended up in a strange state - that's why the problem carried over when you imported/exported.

The team are off today, so we haven't had a chance to look at your export just yet to debug. I will respond in due course as  we do over the next couple of days.

In the meantime - the best thing to do would be to just recreate the tables that you already have in your app, which will solve the `Created By` and `Updated By` problem, then you will just need to update the data providers in your UI to point to the new tables.
