### ISSUE TITLE
Make automation activation/deactivation more clear

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#2021]
A common issue many users have with the automation system is that its not clear that it needs to be activated for it to work in production.

The small pause and play buttons often go un-noticed, due to their size and coloration, we could probably do with some sort of warning to state that an automation hasn't been activated. We could even perhaps have the automation be activated by default as it is running within the development app, not the production app, so there isn't really any risk.

**Comment by aptkingston** [comment]
I think a spectrum toggle/slider to turn it on and off would be much clearer. Probably at the top of the automation panel.

That whole panel would really benefit from being redesigned to look like the builder design section, with dividers and different sections. We could then dedicate the top section to being the activation toggle which would make it really explicit.
