### ISSUE TITLE
Validatation for component nesting in builder

### ISSUE THREAD

**Issue by Conor-Mack** [Budibase/budibase#203]
Currently Budibase allows any component to be nested under another component. Some validation should be added to make a distinction between: 

- Components that allow any other component(s) to be nested under them e.g. a div
- Components that only allow nesting of specific components e.g checkboxgroup > checkbox
- Components that don't allow any components to be nested e.g H1

Maybe this could be defined in components.json somehow....

![image](https://user-images.githubusercontent.com/36074859/78995646-c31d0500-7b3a-11ea-8e35-7aff8418f2c9.png)

**Comment by mjashanks** [comment]
this seems to be half done...

have a look at `createProps.spec.js`  ... 

`it("should create a object without _children array, when children===false")`

so, in your `components.json`, we need to set `"children": false` for any component that should not allow children.

Also, not done, we need to disallow adding children to components where `children === false` (note that `children === undefined` should be allowed to have children)
