### ISSUE TITLE
Data Provider' Filter for Boolean type fields stopped working

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#2038]
Hi All,

v. 0.9.78

Data Provider' Filtering by Date/Time stopped working across all my apps. Returns always 0 records. 
No changes in formulas/fields/records were made. Even tried with the only Date/Time filed.

This is example where formula is using:
![Filter_Date](https://user-images.githubusercontent.com/53024832/126394199-e012fe54-16f4-4d6e-9f4c-3f95382c38ea.png)

P.S. It doesn't matter if an app is existing or re-imported.

Please solve the issue.

**Comment by aptkingston** [comment]
@sergey-dme your filter looks correct. I just tried this myself in a fresh app and it works perfectly:
![image](https://user-images.githubusercontent.com/9075550/126468630-d49daae6-4eb8-4497-96db-b2c4475eb174.png)

Your data provider is still spinning in the screenshot - is it still loading? Either it is being extremely slow or an error has happened, because it would not be spinning like that when there are 0 rows. Does it spin forever or does it stop? Is there an error in the console when you open dev tools?

**Comment by sergey-dme** [comment]
@aptkingston Actually the bug with Boolean Type field. Once I removed this condition with Boolean filed filtering It started worked again. It's not related to Date/Time field.
 
Let's recreate a behavior/issue in a new app:
 
There is just a simple Table with three columns and two records. Option1 is a Boolean type filed:
 
![image](https://user-images.githubusercontent.com/53024832/126476197-6b612fcb-ec0e-40d6-ac31-a6edf89778b8.png)
 
 
Again, the records we have (no filter used):

![image](https://user-images.githubusercontent.com/53024832/126476211-4fc7975e-61f0-402d-9cbf-e023fb04ea3f.png)

If we start using filtering for Option1 field (Boolean) it returns 0! 
It should return 1 record in this case:

![image](https://user-images.githubusercontent.com/53024832/126476320-d0a71722-e4e2-4f8e-8392-ddf54d4ed3ce.png)

**Comment by sergey-dme** [comment]
https://github.com/Budibase/budibase/discussions/2030

**Comment by aptkingston** [comment]
@sergey-dme now that this issue is linked, I'm going to close this one as it's a duplicate. You can keep track of the progress in the existing issues. Thanks for the extra detail though.

**Comment by aptkingston** [comment]
@sergey-dme I'm reopening this becaue it's actually a separate issue. I had fixed boolean filtering on data providers already, so something else must have changed here without me realising. This definitely used to work.
