### ISSUE TITLE
View filters do not handle nulls

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2042]
First described in https://github.com/Budibase/budibase/discussions/2030.

When a column value is `null` (or possibly `undefined` ?) we cannot account for this in a view filter.

To reproduce a `null` value
- Add a column of any type, when you have existing data in the table. All existing values have blank values for this column.
- Create a new row via the builder and do not enter a value for Number or Date 

### Suggested solution

- Filters should have an option for `Is not set`
- When values are not set, we should explicitly say in the rows `Not Set` rather than having a blank cell, or unchecked box. This should probably apply to both the builder and the table component within the app
- We could also set a "Value when not set" option on the column so that it can work nicely with formulas and view calculations.
- For bonus points, it would be really nice to be able to run batch updates inside the builder. This has other uses, but very much a nice-to-have if the above points are covered

**Comment by Rory-Powell** [comment]
Changes added here https://github.com/Budibase/budibase/pull/3104
