### ISSUE TITLE
Simplified Component Panel

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#206]
#### Rationale
We've had feedback from alpha customers as well as our own about the usability of the components panel. Here are some recurring themes:

- There are too many components
- Components shouldn't be divided by library
- Duplication across libraries

#### Working Solution
Joe's put together a mockup for a proposed rework of the components panel: https://app.zeplin.io/project/5e930f4143f0bd785b027207/screen/5e9310f30046c27b974038aa

This categorises components into their "usage" rather than the component library they belong to. For example, when a user selects a `Text` component, it will default to the standard component, but allow the option to select a theme, such as material or bootstrap. This will switch out that component to be the one from the corresponding library - opaque to the user.

Overall this should greatly reduce the overhead of dealing with components, making apps much easier to build.

**Comment by kevmodrome** [comment]
I've been pondering the best way to organize this, especially how it would work in a coming Routify implementation of the front-end.

I think moving the right-side panel to the frontend _layout.svelte file is the way forward here. It would probably be a good idea to split the components folder into three subcategories: common, frontend and backend as well.

The current panel lives in the `userInterface` and contains a whole lot of components that we can further divide into a `Component` and `Properties` folder.

Could the "sub-tabs" that are to be used on the Component View perhaps also be used on the Properties View? My thinking is something like sub-tabs where you have the "basic" properties and then another tab where you could stick for example layout properties. This could also be extended to further categorize properties in the future. Just an idea.
