### ISSUE TITLE
New role appears as role_<uuid>

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2062]
**Describe the bug**
When I create a new role in an app, it is listed in the `Portal > Users` section by it's id

![image](https://user-images.githubusercontent.com/3524181/126656117-353f81d0-a777-4d4e-bab9-d1a95eb9fe0e.png)

I tried publishing the app to see if it made a difference, but it did not.

**Comment by mike12345567** [comment]
Fixed in PR #2078.
