### ISSUE TITLE
Unable to create a new role without inheriting from another one

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2077]
**Describe the bug**
Creating a role without inheriting an existing role is possible in the frontend but throws a 400 Bad Request in the backend.

**To Reproduce**
1. Go to the users table
2. Click on 'Edit roles'
3. Create a role without selecting an inherited role
4. Click on save
5. A generic server error is thrown: "Error saving role"

**Expected behavior**
I expected a clear client side error message when you don't select an inherited role, since this field is required on the server side, like the name field.

**Desktop (please complete the following information):**
 - OS: Linux (Pop!_OS 21.04)
 - Browser: tested on Vivaldi, Firefox
 - Version: master branch

**Comment by mike12345567** [comment]
Hi @mslourens thanks for the report! I've raised a PR for this here: #2086

**Comment by mike12345567** [comment]
This has been merged to develop.
