### ISSUE TITLE
JS Scripting In Binding Drawer

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2089]
When I am interacting with the binding drawer, I want to be able to write JavaScript inside the binding drawer with all the available context bindings, so that I can introduce logic and dynamic functionality to my apps

**COS**
- JS bindings in design panel UI - the code needs to be executed client side
- Code in the expression will be evaluated at the same time that HBS expressions are

**Comment by mike12345567** [comment]
bump
