### ISSUE TITLE
Query Level Transformers

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2093]
When I'm using a data provider, I want to be able to use a JS transformer to map the result of queries into the shape I want, so that I can display data in the correct format in the UI.

**COS**
- Add transformer prop to data provider
- Execute the transformer server side over the data returned from the data source as part of the previews and query calls 
- Seed the initial transformer value with return data

Future View Transformers: The ability to transform output from tables - SQL, Internal etc and use them in data providers and the UI as views. Powerful for charts and data manipulation on tables.

**Comment by RobertPegu** [comment]
Hello there, any news about this feature? I really need this

**Comment by mike12345567** [comment]
Hi @RobertPegu - this feature has been developed and merged to our development branch as part of this PR #2992.

This will be release as part of our next release cycle after it has been through out QA phase.
