### ISSUE TITLE
Forms: Custom Validation

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2096]
When controlling form validation in the action binding drawer, I want to be able to add custom validation rules to the form fields, so that I can ensure data integrity when filling out forms in my apps.

*COS*
- Validation must be a boolean returning expression in either JS or regex
- Custom error messages can be added for that specific field validation
- Have some builtins

**Comment by aptkingston** [comment]
Changing the scope of this a little as we've decided to not pursue any JS related stuff this month.
Validation will be provided by a built in list of validators, or via a regex expression.
An error message will be attached to each validation rule.
Validation scope will be limited to the field's own value - you won't be able to reference the value of other fields.

We can expand this to use full JS custom validation which will be capable of referencing other fields' values from context once we have the JS binding drawer implementation done.
