### ISSUE TITLE
Logging and Debugging

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#21]
We should be able to pass the core library an abstract `log(...)` method, which outputs logs of different levels. We should then provide some basic server logger e.g. "File Logger" or "Console Logger" for development, and make sure it is pluggable. e.g. people should be able to write a "DataDog logger".

The core library should then use the logger in all sorts of places. Start with exceptions (+ we should look for places to better handle exceptions). We should think about "Debug", "Info" and "Warning" levels, and put these everywhere.

The logger implementation should be responsible for deciding what levels to log, and how (i.e. it should be responsible for reading from config what levels it should care about).

The server should also use the logger for non-core logging - i.e. any server code outside of the core library.

Additionally, the core library should attach HTTP Status codes to certain exceptions. E.g. "Record Not Found" = 404

We should also consider (as a final part ? ) logging the debug/info/warning/error messages from the front end, and sending them to the server. We would need a server endpoint e.g. `POST /my-app/api/log`. I would suggest that this enpoint require an authenticated session (i.e. not public and open), to avoid this becoming an attack vector.

**Comment by shogunpurple** [comment]
https://github.com/winstonjs/winston is the general defacto node logger for production apps, with https://github.com/expressjs/morgan middleware being really great for HTTP request/response logging etc. We could incorporate a core logging library into budibase core and use it in the other packages. @mjashanks  thoughts?

**Comment by mjashanks** [comment]
Sounds good yea. I am fairly unopinionated about the middleware. That does it.

There may be a bigger thought piece on middleware in general. I.e. It should be possible to attach whatever node/koa middleware we want to the budibase server. It we solved this, then we could just allow anyone to attach their own logging middleware (but definately explore winston as a default / recommended/supported implementation)

The main thing to crack around this is to get the `packages/core` library to spit nice logging.. curently it just throws the odd exception.
