### ISSUE TITLE
Open Screen In Modal

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2103]
When I route to another screen, I want the option to open that screen in a modal on the same page, so that I do not have to navigate back and forth.

**COS**
- Some options on the "Navigate" action to allow for the opening of a screen in a modal, including modal title and width
- Svelte SPA router needs to account for the modal opening in real apps

**Comment by Mitch-Budibase** [comment]
From testing this I am noticing an issue with nested iframes (opening a modal within an opened modal)

Explanation:

- I have a Home Screen, a second screen, and a third screen

- Home Screen has one button - opens the second screen in a modal

- Second screen has two buttons - 1 opens Home Screen in a modal, the other opens screen 3 in a modal

When I run my app, I click the button on the Home Screen and all is well (the second screen opens within a modal).
When I click either of the buttons within the second screen modal - It opens another modal but does not display anything. This second modal is slightly further down the screen than the first one.

A few other things to note:

- Clicking the full screen or close options within the second modal will close it and keep the first modal open

- Clicking outside the modals will cause both to close

I've attached a screenshot to illustrate the modal behaviour
![Screenshot 2021-08-24 at 13.35.51.png](https://images.zenhubusercontent.com/60fed9d54a973614368dfdfe/41dd3cd4-571f-4717-a61f-708c1622f6de)

**Comment by aptkingston** [comment]
As we discussed, I'll update this so that opening another screen modal inside a modal updates the URL of the first modal instead. Should be easy to do using the same technique I've used for other aspects of the modal, by broadcasting an event to the real window. Hopefuly no one ever does this cursed design, but we should definitely handle it at least.
