### ISSUE TITLE
[Feature request] Make development environment work on Windows

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2116]
It would be nice if developers working on a Windows machine could build Budibase without using WSL. 
Currently it is only possible to build the server code in WSL on Windows, because it uses unix commands like `mv`, `rm -rf` and `rmdir`, which are not recognized in Windows. There are node modules for this, like [rimraf](https://www.npmjs.com/package/rimraf) and copyfiles (which is already by in the server package).

**Comment by shogunpurple** [comment]
Good suggestion @mslourens - happy to add this in and I'll raise a PR. Thanks!

**Comment by mslourens** [comment]
`mv` is also not a native Windows command, so we need a replacement for that as well
