### ISSUE TITLE
Create Table, Relationship everything missing

### ISSUE THREAD

**Issue by gonda-dev** [Budibase/budibase#2129]
I just installed the builder app and trying to create a table or relationship all the options are missing. 

Nothing matches based on the youtube vide you have here https://www.youtube.com/watch?v=QLZOYcf_Lmk&t=81s

My screen looks totally different as you can see in below screenshot.

<img width="1390" alt="Screenshot 2021-07-27 at 4 51 28 PM" src="https://user-images.githubusercontent.com/84877705/127145690-cc248105-38f7-4ca0-b6da-dec8453140aa.png">

**Comment by joebudi** [comment]
Hey @gonda-dev 

Click the Budibase DB nav item, then click add table. Apologies for this. We are currently updating the UX and tutorials around this.
