### ISSUE TITLE
Unable to use a Date Picker to apply a greater/less than filter

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2138]
I am trying to use a filter a data provider with a date range - i.e. `MyDate between '2021-04-01' and '2021-05-01`

I do the following
1. Create a new form, of schema type "Custom"
2. Add a field group
3. Add a Date picker, manually type the field name as `fromDate`. Repeat for `toDate`
4. In the `Data Provider > Define Filters` i choose the field `fromDate`, to set the minimum of the date range

I expect there to be a `Greater Than` option, but there is not. So, I am unable to filter by date range.

**Comment by sergey-dme** [comment]
Hello. It seems similar problem as I tried to explain in https://github.com/Budibase/budibase/issues/2108
Hope it will be fixed soon

**Comment by mslourens** [comment]
@mjashanks I am not able to get your scenario reproduced. Is your form inside your data provider? The fromDate and toDate are not selectable as column in the filter, as you can see here:
![image](https://user-images.githubusercontent.com/1907152/127334952-4633cf85-0e98-4323-81a3-cc31e433378e.png)

Am I missing something?

**Comment by mjashanks** [comment]
I put my DataProvider inside the form. Therefore the DataProvider should have access to the form fields - which works. I'm just not allowed to use a `Greater Than` / `Less Than` even though it makes sense for a DatePicker

**Comment by aptkingston** [comment]
The fields in the filter dropdown belong to the schema of the data provider - so you'd need to pick a date field there. Then you'd want to compare that to the value of the form field. Here's an example I just made:
![image](https://user-images.githubusercontent.com/9075550/127567739-5fa28aab-fa03-46b6-ac63-defcee3a33f0.png)

The options that are shown for operators depend on the data provider filter field schema types, and in that example I have my data provider linked to a table which has a date field called `Date`, which works as expected. The form fields are only referenced as the comparison value, a binding, in the rightmost column.

**Comment by mjashanks** [comment]
This was user error on my part. Don't know what I was thinking, sorry to waste your time. I was convinced it was wrong :/
