### ISSUE TITLE
Update App Role: 'undefined' in Roles Option List

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#2156]
Hey all,

All roles in the Option list are showing as 'undefined':

![image](https://user-images.githubusercontent.com/53024832/127354430-3f77a10a-ff5e-428e-9548-c06983cc7110.jpeg)

Current Version: 0.9.84

**Comment by AndrewJRamay** [comment]
@shogunpurple same problem with the 0.9.84 release

**Comment by shogunpurple** [comment]
Fixed in dev, release will be out before EOD. Thanks @mslourens !
