### ISSUE TITLE
Expandable sidebar

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#2159]
### Discussed in https://github.com/Budibase/budibase/discussions/2158

<div type='discussions-op-text'>

<sup>Originally posted by **GuilhermeHirsch** July 28, 2021</sup>
Hello! It would be nice if it was possible to expand or if it had a side scroll on the left bar. This affects my experience when I have a lot of components.

![Sem título](https://user-images.githubusercontent.com/33108596/127359399-943542c3-23e9-431e-b858-5669a9a1b43a.jpg)
</div>

**Comment by gvlx** [comment]
Hi @joebudi, @shogunpurple and @mslourens:
This does not implement a resizable scrollbar, only allows its contents to scroll sideways.

class ".text.svelte-nxq66z.svelte-nxq66z"
➡️  remove `overflow: hidden;`

before:
![imagem](https://user-images.githubusercontent.com/67311/141658863-72774baa-b196-496f-8952-080d3658f613.png)

after:
![imagem](https://user-images.githubusercontent.com/67311/141658873-508aa6d9-399d-44e4-bb83-72c66ac3d55e.png)

notice the horizontal scrollbar in the bottom

**Comment by gvlx** [comment]
Note: to continue to use the element menu you also need:
class .actions.svelte-nxq66z.svelte-nxq66z
➡️ remove visibility: hidden;

**Comment by mjashanks** [comment]
Reported again: https://github.com/Budibase/budibase/discussions/3587

**Comment by kmdelucaNG** [comment]
thanks @gvlx 
Is there documentation on how/where to apply these settings?  Didn't notice any [here](https://docs.budibase.com/). We're self-hosted but I don't have much experience with admin of the install.

**Comment by gvlx** [comment]
Hi @kmdelucaNG ,

There is nothing to install, it is mostly a developer hack, which will disappear once you refresh the browser.

While hovering over the element, open the right mouse button menu and choose `Inspect`:

![imagem](https://user-images.githubusercontent.com/67311/144563856-eb1e0a3f-108a-4785-b103-018418269ab0.png)
![imagem](https://user-images.githubusercontent.com/67311/144563891-c50a937f-ccc5-485e-97bf-1238f8f1ce8a.png)

The `Developer Tools` pane/window will open and you can then untick the CSS properties for the elements (the menu icon element is the div after the element):
![imagem](https://user-images.githubusercontent.com/67311/144564188-539ffb3f-9ecc-49d8-b76c-8d8a97917ee5.png)
