### ISSUE TITLE
Builder Frontend - Page Templates

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#216]
When I create a page in budibase, I want to choose a layout template to get started with so that I can get my web app up and running faster - preventing the need to structure common layout patterns myself.

### Designs
https://app.zeplin.io/project/5e930f4143f0bd785b027207/screen/5e999c6dcc92447ae6c83cbf

**Comment by mjashanks** [comment]
when considering how we implement this underneath, we should do so in the wider context of "App Templates", "Page Templates", "Components" and "Plugins" - i.e. those that come from external sources (our theoretical "Extensions" repository)
