### ISSUE TITLE
View support in Plus Data Sources

### ISSUE THREAD

**Issue by KernOil** [Budibase/budibase#2161]
Hi Team, 
I am having trouble with using views from MySQL and editing rows in them via BB. I can create a new row with no problem, however without me including the parent table primary key I can not edit/delete rows in that view. I have no problem keeping the primary key in the view but I think it should be treated as a table and hide the key so it will not be prompted as an input. 

below is the test table with a primary key but BB handles this properly now. 
![image](https://user-images.githubusercontent.com/80058238/127399318-e3622bf5-c2b9-409b-a808-b2a2e8df6662.png)

here is a view with the exact same columns as the table but BB does not recognize the primary key (ID) 
![image](https://user-images.githubusercontent.com/80058238/127399550-8943b629-7c1f-4c91-9b3d-8f290f085b16.png)

I can submit data to the view 

![image](https://user-images.githubusercontent.com/80058238/127399783-03605c20-b173-4938-ad99-a7347c76b686.png)
![image](https://user-images.githubusercontent.com/80058238/127399812-b038a00c-3b38-4910-acf0-3db6bea1e11c.png)

but when I try and edit it will only save if the view has a primary key  in the form 
![image](https://user-images.githubusercontent.com/80058238/127400050-a4011245-3805-4ba8-88d8-dcfc2449d6bc.png)

example with no primary key 
![image](https://user-images.githubusercontent.com/80058238/127400387-8aab69eb-8937-4a81-8667-0f8ca6cd1921.png)

**Comment by AndrewJRamay** [comment]
some additional issues are described on #2196 unable to view the edit screen in deployment

**Comment by AndrewJRamay** [comment]
Update to this problem, 
I can confirm that when using a table the Details page where you can edit a line will lode and is usable. 

when using the exact same screen and switching to a view data source the window will not load in the published version. 

however, I can edit rows in the data tab of the BB builder. 
I will keep playing with this and let you know if i find out anything more.
