### ISSUE TITLE
One to Many Relation is removed on v0.9.83

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2164]
### Discussed in https://github.com/Budibase/budibase/discussions/2163

Hi,
I have upgraded budibase from v0.9.79 to v0.9.83. There is "one to many" relation feature was removed.
https://github.com/Budibase/budibase/compare/v0.9.79...v0.9.83#diff-e940c2181065c6e3b77d5dfad31e0a0bffd0df22f2ed6b4a88998d3cb0db8c47L175
The dropdown list become multi select, how to make it single selection?
Thank you

Masykur

**Comment by shogunpurple** [comment]
I've fixed this in my branch, release will be out before EOD
