### ISSUE TITLE
Error on your site

### ISSUE THREAD

**Issue by mihha** [Budibase/budibase#2166]
Hi guys,

I didn't find any other contact form on your site, so I am writing you here regarding the small issue that you have on your site

On the following page
https://www.budibase.com/product

you have wrong URL to the integration page
![image](https://user-images.githubusercontent.com/3791124/127459205-05302916-9b49-4467-94e5-5cd270601026.png)

While at it, I also tried to send an email to your support email address (found on Terms of Service page), but I got bounce email saying that support@budibase.com does not exist

![image](https://user-images.githubusercontent.com/3791124/127459471-a6e306f1-76ea-42b0-a713-05d68f266754.png)

Regards,
Igor

**Comment by joebudi** [comment]
@mihha thanks for sourcing this. I released a fix which should be live in a minute.

**Comment by mihha** [comment]
Glad I could help 😀
