### ISSUE TITLE
docker compose issues

### ISSUE THREAD

**Issue by j2l** [Budibase/budibase#2171]
**Describe the bug**
Only Budibase_couch-init and Budibase_watchtower-service are running, all the rest is rejected or failed.
# Error Logs
## CouchDB
No name found in ERL_FLAGS  -setcookie monster

No -name found in vm.args. Using couchdb@127.0.0.1

*************************************************************

ERROR: CouchDB 3.0+ will no longer run in "Admin Party"

       mode. You *MUST* specify an admin user and

       password, either via your own .ini file mapped

       into the container at /opt/couchdb/etc/local.ini

       or inside /opt/couchdb/etc/local.d, or with

       "-e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password"

       to set it via "docker run".

*************************************************************

## Proxy-service
No log line matching the '' filter

## Minio
ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials

      > Please provide correct credentials

      HINT:

        Access key length should be at least 3, and secret key length at least 8 characters

## worker-service
No log line matching the '' filter

## app-service
No log line matching the '' filter

## redis-service

*** FATAL CONFIG FILE ERROR (Redis 6.2.5) ***

Reading the configuration file, at line 2

>>> 'requirepass'

wrong number of arguments

**To Reproduce**
Tested install following https://docs.budibase.com/self-hosting/hosting-methods/docker-compose with https://github.com/Budibase/budibase/blob/master/hosting/docker-compose.yaml

**Screenshots**
![image](https://user-images.githubusercontent.com/65325/127478032-2473410a-cde0-4aef-9b82-0ec7eb2add6c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: latest

I have no idea what is the first/main issue.
Hope it helps :)

**Comment by j2l** [comment]
Wrong approach from me :smile: 
CLI way works better

**Comment by shogunpurple** [comment]
Hi @j2l - from the error messages you posted there it appears that your configuration properties are not being injected. I've just run this on a fresh server and it works.

Do you have a `hosting.properties` file or `.env` file on your server with the environment variables?
<img width="982" alt="Screenshot 2021-07-29 at 11 54 09" src="https://user-images.githubusercontent.com/11256663/127479865-48c4022d-be95-4348-ab91-fe6b583682eb.png">

If so, did you definitely run your docker environment with the following command?

`docker-compose --env-file hosting.properties up`
