### ISSUE TITLE
Unable to cancel creating new data connection

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2187]
**Describe the bug**
It is not possible to navigate away from the new database connection page, when you entered some data. You cannot cancel the screen or just navigate away. The page stays visible, all navigation is cancelled and an error message is shown saying "Unsaved changes. Please save your database configuration before leaving". If you don't want to save your configuration you cannot leave the page.

**To Reproduce**
1. Go to the data tab
2. Click on the plus button to add a new database connection
3. Enter some data
4. Click the Budibase icon to return to the portal page
5. The error message is shown and you are prevented from navigating away. 

**Expected behavior**
A warning message should be shown, giving you the opportunity to move away, and discard the changes. Or maybe a button to cancel the changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/1907152/127628241-98d3ba12-9826-4ffc-9d47-8ea67c0d999c.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Vivaldi
 - Version develop branch

**Comment by shogunpurple** [comment]
Thanks for raising @mslourens! Moved this one into our board and will have it resolved in due course.

**Comment by mslourens** [comment]
fixed by #2424
