### ISSUE TITLE
Fetch tables from database doesn't use current settings

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2188]
**Describe the bug**
On the new datasource page, clicking the 'fetch tables from database' button uses the stored configuration settings instead of the settings entered in the configuration form. Therefore you first have to click the save button after entering the configuration settings before clicking the button to fetch the tables from the database. This is not clear for the user.

**To Reproduce**
1. Go to the data tab
2. Click on plus button to create a new datasource configuration
3. Enter your datasource connection details without clicking the Save button
4. Click the 'fetch tables from database' button.
5. Note: an error occurred saying that access was denied to the server, although you entered the correct settings

**Expected behavior**
The entered configuration settings should be used to make a connection to the database. Clicking the save button should not be required for use of the page.

**Desktop (please complete the following information):**
 - OS: MacOS 11.5
 - Browser: Vivaldi
 - Version: develop branch

**Comment by shogunpurple** [comment]
@mslourens The issue with using the ones just entered in the UI without saving is that they haven't been saved to the backend, so we would have to make a few changes to send down the temporary, unsaved credentials.

I think we should possibly show a notification if you haven't saved your settings. 

What do you think?

**Comment by mslourens** [comment]
I think it's more user friendly to use the temporary unsaved credentials. Clicking the Save button saves all configurations settings. If feels weird, from a user perspective, to save all configuration settings, before finishing the configuration, as a required step in order to finish the configuration, if you can still follow my line of thought ;)
