### ISSUE TITLE
View Link breaks on edit

### ISSUE THREAD

**Issue by tobehn** [Budibase/budibase#2202]
**Describe the bug**
Changes to _View Link_ of a row break the Handlebar declaration 

**To Reproduce**
1. Go to automatically generated table
2. Click on View Link
3. Enter URL Settings
4. do a change to the handlebars declaration /test/{{ test Table.test._id }} (even a small edit like deleting "}" and inserting it again)
5. Table does not load anymore - link is broken

**Expected behavior**
I wanted to recreate a view link to a table and make the URL connection via Handlebar declaration.
On click i want the link to show the details of a row id.

**Comment by aptkingston** [comment]
@tobehn thanks for the reproduction steps! Pushing a fix soon.

**Comment by tobehn** [comment]
I still have this problem with version 0.9.90
Has the PR been merged into this version.

**Comment by aptkingston** [comment]
@tobehn I have just merged it, so a new release will be pushed very soon.
