### ISSUE TITLE
Filter does not work with repeater

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#2213]
**Describe the bug**
As a user, I would like to filter my cards which are stored within a repeater. When I attempted to filter the cards, nothing happened.

**To Reproduce**
1. Add data to internal table
2. Add data provider
3. Add a repeater
4. Add card and bind data
5. Navigate to the repeater and click the filter button
6. Add a filter

**Expected behavior**
Cards should be filtered

**Screenshots**
![Screenshot 2021-08-02 at 13 44 44](https://user-images.githubusercontent.com/49767913/127864561-fd14995e-b493-4b4b-a31e-6d0c4951ee73.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by aptkingston** [comment]
Good catch. The bug is that repeaters shouldn't have filters at all! Filtering is done on the data provider now rather than the repeater. This is just a leftover from when repeaters use to fetch data themselves.

**Comment by aptkingston** [comment]
I've pushed a fix for this straight to develop.
