### ISSUE TITLE
Add radio buttons to standard-components

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#2228]
### Discussed in https://github.com/Budibase/budibase/discussions/2226

<div type='discussions-op-text'>

<sup>Originally posted by **hardc0l2e** August  3, 2021</sup>
How can I add radio buttons in the form? like yes or no or rating 1,2,3,4,5</div>

**Comment by kevmodrome** [comment]
That's a good question. Unsure what'd be the best way here. Essentially I just look at radio group like a checkbox group where you can only pick one. We could also add a Switch component to handle the boolean case. Not sure. 🤔

**Comment by shogunpurple** [comment]
The options type seems to me that it would have much more utility. Then you can just use a checkbox for a Boolean

**Comment by aptkingston** [comment]
Lets go for `options` then. Like you say, I think we could add a switch/toggle component as another choice for boolean fields if there is any interest.
