### ISSUE TITLE
When accessing a Budibase app on mobile, it takes me to the developer portal

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#2229]
**Describe the bug**
I save Budibase app shortcuts to my mobile and when I click them, I am brought to the developer portal. When on mobiles, users should never be brought to the developer portal.

**Comment by aptkingston** [comment]
Didn't know this was supposed to function this way! I guess this is just a JS check of screen size and redirect you away to the non-developer portal if you fail a screen size check. Not sure how I feel about that, but I know the developer portal isn't mobile friendly at the moment.

**Comment by joebudi** [comment]
What is it you are not sure about?

**Comment by aptkingston** [comment]
Not sure about preventing admin access entirely just because you're on a phone. I'd rather add some sort of quick responsive design to the developer portal but I understand that's a much bigger task than just redirecting for now.
