### ISSUE TITLE
Table Row Count is not accepted

### ISSUE THREAD

**Issue by tobehn** [Budibase/budibase#2231]
**Describe the bug**
As a user i want to define the number of table rows per page in the designers table settings.

**To Reproduce**
1. Create a table (either automatically of manually)
2. Go to settings
3. change Row Count from default 8 to for example 20

**Expected behavior**
The table rows per page change to 20.

**Desktop (please complete the following information):**
 - OS: [ubuntu/elementaryOS 5.1.7]
 - Browser [Firefox]
 - Version [0.9.92]

**Comment by aptkingston** [comment]
Hi @tobehn. This isn't a bug with the table - you just need to either disable pagination of the data provider or increase the page size. On autoscreens it defaults to a limit of 8 per page, so increasing the table row count won't have any effect until you increase the amount of data being provided.

**Comment by tobehn** [comment]
ok.. sorry. Got it.

**Comment by aptkingston** [comment]
@tobehn no worries! The table row count setting controls how many rows are displayed before the table will scroll, and the data provider limit setting controls how many rows and fetched and provided at once. It's up to the components themselves (like the table) to decide how to display those rows.
