### ISSUE TITLE
Critical: Components fields not shown in Button Actions / Bindings window after update

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#2245]
Hey all, 

Just updated to 0.9.93, maybe it is not related to this particular update, but Data Providers, Repeaters, Forms fields/links are missing now in all my button actions across the app as it shown below (reverting app did not help):

<img width="1251" alt="Screenshot 2021-08-04 at 00 21 38" src="https://user-images.githubusercontent.com/53024832/128088662-ddae7daa-2096-46d1-beda-cece2fbc9e25.png">

<img width="1255" alt="Screenshot 2021-08-04 at 00 21 57" src="https://user-images.githubusercontent.com/53024832/128088692-41d96f92-53a2-44ba-b653-6e45512ade2a.png">

Even **Current.User** fields are missing, only handlebars shown

But the components Data Providers, Repeaters, Forms on their places in the builder three as before,  the forms/screens structure were not changed at all, and now the problem with all my buttons across whole app, but all forms still work as before when I test it

The structure many of my screens/form is complex (the tree has large depth due to lots of containers used) but I always organize it according to the following chain:
Data Provider -> Repeater -> Form -> Filed Group -> Button
Button is always inside a form.

This problem also with simple not complicated forms. No components fields are shown in Button actions.

**Comment by sergey-dme** [comment]
The same problem in new created test app with auto generated screen:

No components fields are shown:

<img width="1791" alt="Screenshot 2021-08-04 at 00 59 33" src="https://user-images.githubusercontent.com/53024832/128091978-da1b050f-36fc-43b7-8e8c-e1edd4653b9f.png">

**Comment by aptkingston** [comment]
Hey @sergey-dme. Looking in to this now. Don't change too much about your app, just wait for an update 👍 the bindings are still valid, they just look wrong at the moment.

**Comment by aptkingston** [comment]
Thanks for the detailed report @sergey-dme. This is fixed now and a new release will be available very soon.

**Comment by sergey-dme** [comment]
@aptkingston Yep, I assessed potential possible risks and temporary stopped making any changes in my app till new version with the fix released. Thanks for the rapid fix!
