### ISSUE TITLE
PostgreSQL/MySQL  text/varchar data types row entry automatically removes  content if starts with a number

### ISSUE THREAD

**Issue by hardc0l2e** [Budibase/budibase#2248]
When creating/updating a record/row on a PostreSQL database table, if the text start with a number, saving it will automatically remove the rest of content, just leaving the value with number only.

For example the value should be "**123 XYZ Company**" it will only save "**123**"

![20210804_01 13 48 AM-Budibase_-_Google_Chrome](https://user-images.githubusercontent.com/1472421/128058098-9fe47b05-e066-4f84-9c0b-05f9b15b40c0.png)
![20210804_01 14 06 AM-Budibase_-_Google_Chrome](https://user-images.githubusercontent.com/1472421/128058112-01738251-2c85-4c56-bffe-d3ff78c0125a.png)

_Originally posted by @hardc0l2e in https://github.com/Budibase/budibase/discussions/2238_

**Comment by hardc0l2e** [comment]
Here's a demo.
![Jn9vc6AXAW](https://user-images.githubusercontent.com/1472421/128110745-5a01ccb2-a366-46ce-94f5-f111708a2bdf.gif)

**Comment by mike12345567** [comment]
Fix has been merged, will be released soon - #2259
