### ISSUE TITLE
In kubernetes deployments using helm, In worker-service pods getting- "Unauthorized - no public worker access"

### ISSUE THREAD

**Issue by iavinas** [Budibase/budibase#2249]
**Describe the bug**
I deployed budibase in GKE using Helm. I am able to access the first-time user creation page. I am able to register. After that when the login page comes. After entering the login details I am getting the msg login successful but after that, it redirects me to the login page again.

Later I found the logs in worker pods.

```[1627646362069] (29 on worker-service-d487dfd67-lqsqm):
    err: {
      "type": "ForbiddenError",
      "message": "Unauthorized - no public worker access",
      "stack":
          ForbiddenError: Unauthorized - no public worker access
              at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
              at /app/src/api/index.js:77:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@budibase/auth/src/middleware/authenticated.js:88:14
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/@koa/router/lib/router.js:368:16
              at dispatch (/app/node_modules/koa-compose/index.js:42:32)
              at /app/node_modules/koa-compress/lib/index.js:38:11
      "status": 403,
      "statusCode": 403,
      "expose": true
    }```

Any suggestion what should I look for and fix it?

**Comment by shogunpurple** [comment]
Hi @iavinas - the helm/kubernetes branch is in progress. It has not been shipped yet. Please try to avoid checking out in progress dev branches before release.

We are still working on finishing off our k8s helm charts, and it will be done over the next few days. I am seeing the same issue in our K8S env in AWS - I believe it’s an issue with the load balancer not forwarding the correct auth information/cookies to the pods. I’ll keep you updated on the progress of Budibase K8S support. 

Did you have to make a lot of changes to the helm chart to run it on GKE?

**Comment by iavinas** [comment]
Hi @shogunpurple, Thanks for the help.
I just change a little bit when deploying on GKE. Create a new docker image for the envoy proxy to overwrite /etc/envoy/envoy.yaml. 

```
FROM envoyproxy/envoy:v1.16-latest
COPY envoy.yaml /etc/envoy/envoy.yaml
RUN chmod go+r /etc/envoy/envoy.yaml
```
