### ISSUE TITLE
Name components in your component tree

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#227]
Ahead of workflow, we need a way to give a component a user defined name in the tree. We already have `name` so it will need to be different. `identifier` might be an option - open to suggestions.

We will need UI to actually give the component a name. More than likely we will just have a modal but @joebudi if you have any other ideas a design around this would be great.

**Comment by Conor-Mack** [comment]
@shogunpurple Is this not covered by what I did [here](https://github.com/Budibase/budibase/pull/329)
