### ISSUE TITLE
Research Spike - Consolidation of Views

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2273]
Right now, views map directly to couchDB views. There are some issues here:
- This will not scale, as couchDB views are meant to be static indexes, rather than dynamic aggregations. They take up compute and disk space to keep around
- Views are limited and you cannot use them to perform BI calculations and get totally custom results

**COS**
- Keep existing view UI but update backend
- Allow users to write custom JS functions to map their data in a view for full flexiblity
- Provide premade view functions as before - SUM, AVG etc
- Provide migration path for old views

**Comment by joebudi** [comment]
Currently running into an issue where views are basically inoperable for basic chart creation.

**Comment by shogunpurple** [comment]
@joebudi can you elaborate?

**Comment by joebudi** [comment]
I have no numerical data within my table. 

I create a view, click calculation, then count, select a column (not sure it asks that), and nothing appears.

**Comment by shogunpurple** [comment]
Hm, that seems odd. I can't seem to reproduce - can I see what your table looks like? Maybe export as CSV?
