### ISSUE TITLE
Replace Envoy with NGINX

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2274]
Right now we ship an envoy proxy that sits in front of the budibase architecture.

It works well, however NGINX is a much more well known and mature solution, providing a full web server and more options for serving files etc. Providing a configurable NGINX config out of the box gives users total flexibility, as well as the ability to easily set up things like certbot for HTTPS.

**COS**
- Replace envoy.yaml with an nginx.conf and port it over
- Replace proxy service docker image with swag or standard nginx docker container
- Ensure docs are updated to reflect no longer relevant envoy links

**Comment by aptkingston** [comment]
Swag would be awesome to allow out of the box HTTPS by just configuring env variables - something we could easily configure the CLI to handle.

**Comment by mike12345567** [comment]
I think pre-configured SWAG is one of the top reasons to do it, since it'd provide so much value to self hosters.
