### ISSUE TITLE
Connecting to SQL Server

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2279]
### Discussed in https://github.com/Budibase/budibase/discussions/2223

<div type='discussions-op-text'>

<sup>Originally posted by **simulsys** August  2, 2021</sup>
Hi there,
I tried the configuration screen for SQL Server and it saved okay, but when I try to find how to attach it to a table, or form as with Postgresql or MySQL help screens my screen does not show the same commands and I get stuck. When I try to build and run a query it errors with a requests for a "Bucket" Key parameter? I have no idea what to do, so any help would be gratefully received, please?

Tally ho!
Andrew.</div>

**Comment by bloomt** [comment]
Have same issue, worked on older versions

**Comment by shogunpurple** [comment]
A fix for this has been merged and will be released in the next few minutes. Thanks!
