### ISSUE TITLE
Home screen replacement on app import

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#2298]
Hi all,

Finally I investigated (caught) home screen replacement on app import.

**Describe the bug**
After app import existing home screen replaced by empty one.

**To Reproduce**
1. Import an BB App w/ Home screen customised (not default/empty one)
2. RIGHT AFTER APP IMPORT -> Click on App Dev Preview (play icon at top right corner)
3. Your Home screen is gone - "Welcome to budibase" instead of ex.home screen

The only way to retain ex. home screen is do not click on play button right after app import.
Currently, the right way after app import - click on Design Tab. And home screen will be appeared. Then you can click on play button.

**Comment by aptkingston** [comment]
Hey @sergey-dme, thanks for looking in to this. I've seen it happen myself on a couple of occasions but I've never been able to reliably reproduce it. I tried following your steps but my home screen was still there, so there must be something else going on too. Very interesting though that these steps always make your screen disappear.

**Comment by sergey-dme** [comment]
hey @aptkingston you are right, home screen is still there, just tested it again for new app and for my "heavy" app. I don't think now that it somehow depends on user actions after app import, like I thought/described above. I was wrong something else happens with it time 2 time. For all my 7 tries of importing different apps now home screens were not replaced.

**Comment by joebudi** [comment]
This happens to me when I import a new app, and publish it straight away, **without opening the homepage in the builder preview**
