### ISSUE TITLE
ERROR on running "budi hosting --init " for M1 macbook pro 

### ISSUE THREAD

**Issue by hezhichao** [Budibase/budibase#2307]
hezhichao@hezhichaodeMBP budibase %budi hosting --init  
? This will create multiple files in current directory, should continue? Yes
Error - Error: connect ECONNREFUSED 0.0.0.0:443

which step i made wrong?

**Comment by 8debug** [comment]
> hezhichao@hezhichaodeMBP budibase %budi hosting --init ? This will create multiple files in current directory, should continue? Yes Error - Error: connect ECONNREFUSED 0.0.0.0:443
> 
> which step i made wrong?

how to solve
