### ISSUE TITLE
Unable to add External Postgres DB (Heroku extension) Hosted on AWS RDS

### ISSUE THREAD

**Issue by TairanJ** [Budibase/budibase#2308]
**Describe the bug**
I am trying to connect to an external Postgres DB hosted on AWS RDS through Heroku. It throws below error:

"Error updating datasource schema: Error: self signed certificate"

**To Reproduce**
1. Go to Data -> Sources
2. Click on Add name - select postgress
3. Add connection detail
4. Save datasource and Fetch tables
5. Error appears

**Expected behavior**
DB successfully added.

**Screenshots**
![image1](https://user-images.githubusercontent.com/54902728/128618968-6e11161c-79ee-4c59-a30f-4c3ebac9019b.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 0.9.98

**Additional context**
This seems to be similar to the issue mentioned in #1967

**Comment by TairanJ** [comment]
Furthermore, like mentioned in #1967 by spokebase, turning off "SSL" will result in the following error: no pg_hba.conf for host "...", user "...", database "...", SSL off.

**Comment by TairanJ** [comment]
After reading more about the error, it seems that the issue lies here: [https://github.com/Budibase/budibase/blob/master/packages/server/src/integrations/postgres.ts#L125](https://github.com/Budibase/budibase/blob/master/packages/server/src/integrations/postgres.ts#L125)

As the response to [this StackOverflow post](https://stackoverflow.com/questions/61097695/self-signed-certificate-error-during-query-the-heroku-hosted-postgres-database) states, the problem occurs when "ssl is set to true but no ssl configuration is provided." Possible solutions are either to "specify` rejectUnauthorized: true` to require a valid CA or `rejectUnauthorized: false` to explicitly opt out of MITM protection."

**Comment by snepote** [comment]
I'm experiencing a similar issue while trying to connect to a Postgres DB in Heroku. **Is there any update for that?**
<img width="638" alt="budibase-pgconnect-heroku" src="https://user-images.githubusercontent.com/2563348/200126957-9a6ee1c6-c7ea-42b1-9412-92d72662a13a.png">

### Error
```
Error updating datasource schema : no pg_hba.conf entry for host "XXX.XXX.XXX.XXX", user "*******************", database "*******************", no encryption
```
