### ISSUE TITLE
can't yarn setup on win10 

### ISSUE THREAD

**Issue by lewis617** [Budibase/budibase#2309]
**Describe the bug**
Throwed this error:
```
./hosting/scripts/setup.js && yarn && yarn bootstrap && yarn build && yarn dev
error Command failed with exit code 1.
```

**To Reproduce**
1. yarn setup

**Expected behavior**
work like linux or mac, don't throw error

**Screenshots**
![image](https://user-images.githubusercontent.com/11524612/128620528-29f90f9b-31ca-471a-a578-18ccdbd5f535.png)

**Desktop (please complete the following information):**
 - OS: windows 10 x64
 - Browser 

**Additional context**

**Comment by shogunpurple** [comment]
Hi @lewis617 - I'm going to need a little bit more information here.

What doe that windows error message say? It's in Chinese so I'm not sure. If you could translate that error for us then we may be able to help. Thanks

**Comment by lewis617** [comment]
@shogunpurple 
Thanks for reply. It has the same Error Code with this one:
![image](https://user-images.githubusercontent.com/11524612/129135193-0c7cb2cf-e3b2-4d40-9223-28d5b8f7b1ce.png)
