### ISSUE TITLE
Ability to use icons inside of buttons in client apps

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#2329]
**Describe the feature request**
Would love to be able to add proper Spectrum icons inside of buttons in the client apps.

**Comment by kevmodrome** [comment]
Yeah, it'd be pretty dope to update the Icon component. Possibly small enough scope that I could take a look at it at some point, we'll probably need to discuss what features, etc. we want it to have.

**Comment by sergey-dme** [comment]
Hi all, while updating the component could you please do not remove existing icons, they are also good, I used them allot in my app
