### ISSUE TITLE
Unable to update screen route

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2368]
**Describe the bug**
Changes to an existing screen route are not stored

**To Reproduce**
1. Go to the design tab
2. Click on an existing screen
3. Update the route
4. Click on another screen
5. Click on the previous screen
6. Note: the route has not been (re)stored.

**Expected behavior**
Changing the route should be stored in the database immediately, like the screen name

**Desktop (please complete the following information):**
 - OS: POP_OS 21.04
 - Browser: Vivaldi
 - Version: develop branch

**Comment by aptkingston** [comment]
Thanks @mslourens, good catch. Fixed in #2369.
