### ISSUE TITLE
Get redirected to admin login page after successful login

### ISSUE THREAD

**Issue by jpatterson-7** [Budibase/budibase#2371]
**Describe the bug**
After initial setup, I set the email and password for the Admin user. When trying to use those credentials (saved in LastPass so to not type them incorrectly, I get the green success message, but then get redirected to the login page in an infinite loop. 

**To Reproduce**
1. Go to 'http://localhost:10000/builder/auth/login?returnUrl=%252Fbuilder'
2. Type in credentials
3. Click 'Sign in to Budibase'
4. See 'Logged in Successfully' message
4. Get redirected to login page

**Expected behavior**
Log in and see portal

**Desktop (please complete the following information):**
 - OS: Mac OS - 10.15.7
 - Browser: Firefox
 - Version: 91.0

**Additional context**

**Comment by shogunpurple** [comment]
Hi @jpatterson-7 - are you getting any errors in the console? It seems like something may be throwing and kicking you back out to the login page.

**Comment by jpatterson-7** [comment]
Hey Martin, screenshot of console log below. If I can get you any other data just let me know.

<img width="942" alt="Screenshot 2021-08-16 at 21 52 23" src="https://user-images.githubusercontent.com/37450316/129628040-806459c5-95f5-4929-9e09-a5b17d2b1c1b.png">

**Comment by shogunpurple** [comment]
Thanks @jpatterson-7 - this is helpful. I thought initially there was a problem with your server but it looks like those requests are coming through as expected. This seems to be a client side issue - it would be really helpful to see the code on the top line - `index.<hash>.js:215` if you can click it there in the browser - I just set up a completely fresh budibase installation on another server and I can't seem to reproduce this. Did you set up directly using docker, or did you use the budibase CLI?

**Comment by jpatterson-7** [comment]
Appreciate the help sir, I downloaded Docker Desktop onto my Mac, but then followed the guide to install via the CLI.  I thought it might just be a Firefox issue, so I have also tried logging in on Chrome and Brave. There was a brief moment when I saw the portal page, but that was only a flash, then it was back to the login.

I've attached the index.f15ee68b.js file, 215 should be the last line

[index.f15ee68b.js.zip](https://github.com/Budibase/budibase/files/6995466/index.f15ee68b.js.zip)

**Comment by shogunpurple** [comment]
Ok thank you @jpatterson-7 - I will debug this and see if I can find what the issue is. Thank you!

**Comment by shogunpurple** [comment]
@jpatterson-7 this seems to be related to a recent commit as discussed here:
https://github.com/Budibase/budibase/issues/2374#issuecomment-899875506

Please update and let us know if you can get up and running again.

**Comment by jpatterson-7** [comment]
That's it sorted now. Portal has loaded. Cheers sir 🍺
