### ISSUE TITLE
 v0.9.105-alpha.13 deleted all of my apps please help 

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#2374]
Updating to 
v0.9.105-alpha.13 deleted all of my apps please help

**Comment by AndrewJRamay** [comment]
BB says its version 
Current Version: 0.9.106
but get hub says v0.9.105-alpha.13

**Comment by AndrewJRamay** [comment]
I get this when trying to import or make a new app 
![image](https://user-images.githubusercontent.com/80058238/129640072-736fbd8f-7ab4-4762-b669-a4a2399644f1.png)

**Comment by AndrewJRamay** [comment]
here are the errors
![image](https://user-images.githubusercontent.com/80058238/129641018-50626314-537e-47b8-82cb-d8fb9866255e.png)

**Comment by AndrewJRamay** [comment]
maybe we need the ability to role back an update

**Comment by shogunpurple** [comment]
Hi @AndrewJRamay your apps are still there, it looks like there's an issue with database authentication - we will roll back the commit that caused it and investigate. The release will be out in about 5-10 mins

**Comment by shogunpurple** [comment]
@AndrewJRamay that should be fixed now for you
