### ISSUE TITLE
Log In Loop 

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#2392]
Hi Guys my BB portal is in a login loop. it will say successfully logged in but kick me back to the log-in screen. any idea how to fix this?

![image](https://user-images.githubusercontent.com/80058238/129750550-86e4cff3-eb53-4add-825e-b1c27614b337.png)

**Comment by AndrewJRamay** [comment]
how do you recommend updating this app? i am running it in a docker container.

**Comment by shogunpurple** [comment]
@AndrewJRamay did you get this fixed? Assuming you did due to the closure
