### ISSUE TITLE
New Install / Update is only pulling MYSQL And report server.

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#2393]
Hi Guys,
@shogunpurple 
your commands you have in the code section to deploy your apps are only pulling Mariadb and reports server. I do not get any BB apps at all.
![image](https://user-images.githubusercontent.com/80058238/129756710-50473bb7-9960-4d1e-b18f-47709639a97e.png)

**Comment by shogunpurple** [comment]
@AndrewJRamay it seems you are running this in a directory where you have an existing `docker-compose.yaml` - I don't recognise `reportserverenterprise` (https://github.com/bitnami/bitnami-docker-reportserverenterprise?)

We also do not use `mariadb` - this is an environmental issue on your side. Closing
