### ISSUE TITLE
SQL Relationships do not allow for the editing of the table that holds the FK

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#2402]
Hi Guys after playing with this most of the day I believe there is a bug that is not allowing me to edit a row once it is created in the table that holds the FK. I have it documented here #2396

when I remove all of the relationships I then can use the table properly to add any SQL Relationships I can no longer edit a row in that table. I can save a new row but not edit one.

**Comment by AndrewJRamay** [comment]
to get the row to update I have to go and reselect every relationship box again. then it will save 
![image](https://user-images.githubusercontent.com/80058238/129810021-a494276f-ee43-421c-8f11-70227f1dcb83.png)

**Comment by mike12345567** [comment]
This issue has been resolved as of latest bug fixes PR.
