### ISSUE TITLE
Users are not indexed until some metadata column has been added to the table

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#2404]
### Discussed in https://github.com/Budibase/budibase/discussions/2389
It's not possible to access the rows in the Users table using the Data Provider

<div type='discussions-op-text'>

<sup>Originally posted by **erakastrati** August 17, 2021</sup>
Hi guys,

Do you know a way to add the Users table(that is generated itself from Budibase) in the development section or it is possible just from the tables part. 
I want to use the Users as Employees of my application without creating a new table named Employees?

Thanks a lot,
Era.

</div>

**Comment by aptkingston** [comment]
Can't seem to reproduce this - it works fine for me.
![image](https://user-images.githubusercontent.com/9075550/129866577-5cb29f13-308f-4ae2-9692-4d85d6dd5aed.png)

**Comment by kevmodrome** [comment]
That is odd indeed! I'm seeing this:

<img width="1779" alt="CleanShot 2021-08-18 at 10 40 14@2x" src="https://user-images.githubusercontent.com/534488/129866827-cf0f5207-da58-4026-8ab2-158dda55cafe.png">

**Comment by kevmodrome** [comment]
Is your application a new one? Maybe there's some issue with it working in old ones? 🤔

**Comment by aptkingston** [comment]
Looks like the user rows aren't indexed until some app-level metadata is created. Try adding a column to the users table in that app, and then edit a row and fill in the new column. Every row you edit and add data to should appear in the table.

**Comment by kevmodrome** [comment]
That's interesting. I'll update the title of the issue so it makes more sense.

**Comment by mike12345567** [comment]
This issue has been resolved as of latest bug fixes PR.
