### ISSUE TITLE
First login not possible

### ISSUE THREAD

**Issue by funked00** [Budibase/budibase#2406]
Hi,

after creating the admin user I cannot login. For a short time a green "Logged in successfuly" banner appears but then I'm always redirected to the login page again.

Any advise where to start debugging?

Best regards
Daniel

**Comment by kevmodrome** [comment]
Hi! 

Please make a post here if you need help: https://github.com/Budibase/budibase/discussions/categories/help

Don't forget to add any relevant data like what browser you're using, etc.
