### ISSUE TITLE
Automations: Show Data Flow

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2409]
When testing automations on the platform, I want to be able to see the data flow from one block to the other so that I can identify the inputs/outputs of each block and debug with more ease.

**COS**
- Automations restructured to run block by block
- Register automation failures and where exactly they occurred
- Allow configuration of seed data so you can test with different inputs

**Comment by mike12345567** [comment]
Feature work completed as part of @PClmnt PR and my own on automation redesign and rework.
