### ISSUE TITLE
Automations: Query Step

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2410]
When I'm setting up automations, I want to have the ability to add a "query" step, which would allow me to utilise the data provider interface to query a set of records (internal, external or relationships) and pass these records along to other steps in my automation, so that I can query the data I need based on values in my automaton blocks.

**COS**
- Add "Query rows" block definition
- Provide an identical interface to the data provider in the Design UI, including filters

![Screenshot 2021-08-18 at 15.23.57.png](https://images.zenhubusercontent.com/5fd773ddf3d67d4ceebe466b/55dfc7ba-b02d-4faf-ba82-83e395bb72c9)

More context here: https://github.com/Budibase/budibase/discussions/2024

**Comment by mike12345567** [comment]
Added in most recent PR.
