### ISSUE TITLE
Created by not present when using stringified JSON body with webhooks

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2412]
### Discussed in https://github.com/Budibase/budibase/discussions/2366

<div type='discussions-op-text'>

<sup>Originally posted by **burnoutberni** August 16, 2021</sup>
Whenever a new row is created in a Budibase table, I push the whole row to an API via the webhooks feature:

```
{
  "posting": {{ JSONstringify trigger.row }},
  …
}
```

Unfortunately the resulting JSON string does not contain the `Created By` field, but I also need this information. Is there any way to do this?</div>

**Comment by mike12345567** [comment]
Fixed in recent PRs.
