### ISSUE TITLE
Avoid zoom on accessing input field on mobile browsers

### ISSUE THREAD

**Issue by tobehn** [Budibase/budibase#2415]
**Describe the feature request**
As a User i do not want my app zoom in on accessing an input form field in a mobile browser.

I used to avoid this with font size 16px in a webapp once, though i am not aware if this is the correct and best solution

https://stackoverflow.com/questions/4472891/how-can-i-disable-zoom-on-a-mobile-web-page

**Video**

https://user-images.githubusercontent.com/40893107/129933700-476bc371-efbb-4408-95fe-2d93b99ab657.MP4

**Comment by aptkingston** [comment]
I've done some research and I'm afraid there is no proper cross-browser way to disable this Safari behaviour without having side effects. It is possible to disable it, but it will prevent normal scaling on pinch on Android devices. I recommend using a different browser if this annoys you, such as Chrome or Firefox.

Going to close this as it's out of our control. If you or someone else finds a solution to this then we can reopen, but from looking around I don't think it's possible yet (without setting all our inputs to 16px, which we won't do).

**Comment by tobehn** [comment]
iOS 14.6
Latest Firefox for iOS

@aptkingston I can totally understand you wouldn't want to set all inputs font size to 16px.

imho it's a really weired and indeed annoying behavior (especially when switching between input fields)

I definitely am interested in a solution an willing to do more research. I will let you know if I can find a proper cross-browser way.

**Comment by aptkingston** [comment]
Hey @tobehn. Yep seems like iOS is more to blame than the browser! I'd be happy to implement this if we could, but I don't think there's a way yet without prevent user zooming in some browsers.

**Comment by joebudi** [comment]
Is the issue the movement or the fact the label is cut off when zoomed?

**Comment by tobehn** [comment]
@joebudi well,.. mainly the movement. But of course in the end the whole form is cut off and not very accessible.

Without zoom movement there weren’t any cut-offs.

I would expect the screen of the same zoom level like on a fresh page load, even when I have entered a form field.

@aptkingston What font-size do you currently use in form fields? What about only doing it on smaller screens like

```
@media screen and (max-width: 767px) {
  input, select, textarea {
    font-size: 16px; !important
  }
}
```
