### ISSUE TITLE
Case insensitive filtering

### ISSUE THREAD

**Issue by MarkOSullivan94** [Budibase/budibase#2425]
**Describe the feature request**

We have added a text field above our table which is used to filter one of the columns, it would be great if there was a checkbox when setting up the filter to indicate whether or not the filter should be case sensitive or not.

This would help us avoid issues trying to filter the correct record when only some of the records in the column has been capitalised and the rest is all lower case or has only the first word capitalised

**Screenshots**

Shown below is the current filter

![Screenshot 2021-08-20 at 11 15 20](https://user-images.githubusercontent.com/6950843/130219457-d99d3e1c-d4d1-4e00-8c50-bb16bb05e4f3.png)

**Comment by aptkingston** [comment]
Hey @MarkOSullivan94. The current behaviour is that everything is case insensitive, so capitalisation shouldn't matter. Have you hit any problems where things weren't filtering properly due to casing?

**Comment by MarkOSullivan94** [comment]
Hi @apoclyps thanks for the reply. Yep, I'm having issues with all the tables but perhaps it's because I'm building those tables from a query pulling out fields from the jsonb column in the original table?

Case sensitive text

![Screenshot 2021-08-20 at 12 43 55](https://user-images.githubusercontent.com/6950843/130228318-e5861ad2-11b0-435e-a848-30792cd2dcba.png)

Not case sensitive

![Screenshot 2021-08-20 at 12 44 05](https://user-images.githubusercontent.com/6950843/130228760-8b012c3f-d905-4c69-bd47-f182db090031.png)

This is the data structure for the original table 

![Screenshot 2021-08-20 at 12 54 44](https://user-images.githubusercontent.com/6950843/130229440-07ef15aa-b51e-4496-8331-f4283859c8f5.png)

Our query for pulling out the data we need from the `data` column in the table

```
 SELECT x.id,
    x.name,
    x.size,
    x.active,
    x.causes,
    x.socials,
    x.objectives
 FROM charities c,
    LATERAL jsonb_to_record(c.data) x(id character varying(32), name text, size text, active boolean, causes text[], socials text[], objectives text);
```

We have the Table showed in the screenshots above wrapped in a Data Provider which is using this query shown in the code block above which we added to Budibase, it displays the data fine and allows us to search but only case sensitive right now.

Hope this makes sense, if any of it is unclear or you need any extra detail, let me know.

**Comment by aptkingston** [comment]
Ah sorry, the first question I should have asked was what data source you're using! Our case insensitivity only applies to our internal tables rather than external SQL tables.

Being able to specify case sensitivity for SQL queries when filtering would be a good feature request - as you noticed we just pass the values through raw at the moment, which leaves it up to the database to decide how to handle it.

**Comment by shogunpurple** [comment]
Good suggestion @MarkOSullivan94 - I'm actually thinking that case insensitive should be the default since it is with our internal tables. I can change the SQL queries in the backend to be parsed as `ILIKE` instead of `LIKE` to make the behaviour consistent?

**Comment by aptkingston** [comment]
I would be in favour of that. I think case insensitive makes more sense in general and it's definitely better to be consistent with internal tables.

**Comment by shogunpurple** [comment]
PR here: https://github.com/Budibase/budibase/pull/2426
