### ISSUE TITLE
App performance: appPackage caching

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2429]
### Discussed in https://github.com/Budibase/budibase/discussions/2348

<div type='discussions-op-text'>

<sup>Originally posted by **sergey-dme** August 12, 2021</sup>
Hey all,

Whereas BB being continuously improving and getting better and better, I am also continuously developing and improving my app, it's growing in screen number perspective, its size and functionality of course. Currently it has about 50 screens, 7 main layouts, almost empty Tables (just a few test rows/records stored), exported app file size is about 25 Mb / same size according to the Chrome' performance inspector. 

As a result, I've got quite long app loading time. When app is opening it takes **2.5 seconds** for it to be appeared/loaded, and during the loading process the only white background is showing in a browser tab, nothing else. 

I've also analyzed its performance in Chrome inspector and consider that it takes too much time to be loaded (compare to other even more complex web app and considering that my app is accessed from my local network without a long chain of different DNS or other types internet servers). In builder, app loading time is about the same.
When app is loaded it works perfectly and fast.

**I've tried to investigate it and found two main reasons leading to increasing App loading time:**

1. One of the elements of my dashboard (it's my home screen) - Device Status bar, which has 14 Data Providers inside :) - because I use them to show the status of 7 Devices (2 data providers per device) using filter and `Rows Length `with `{{#if}} `for displaying _appropriate color Device icons_ depending on the _opened issues_ and its _Priorities/Types_. Moreover, there are 13 more Data Providers in other sections of my dashboard. 
And.. all 27 Data Providers used in my dashboard are getting the data from the same Table, the only difference are Filters.
I would not deny that it is not optimized at all, but I have no other ways/solutions for this use case/task as well as the second one:

2. The UI of my app is complex but nothing unusual. I use some background wide jpg/png images (web-optimised/compressed of course), I tried to use `background-image: url("http://...") `in Custom CSS and host the images on different servers even in local network, but the bg images start blinking (known behaviour for bg images in any browser, as they should be pre-loaded that is something that is not currently possible in BB). Therefore, I ended up by using amazing base64: `background-image: url("data:image/png;base64,iVBORw0KG..` storing the images in the app screens. I know, it is usually used to handle small images, ui elements, icons etc.. but I have no choice. Thanks you for the ability to use base64 in Custom CSS anyway. Please do not remove it)

The first one (lots of data providers) has the most significant effect on app loading time. 
The second one mostly effects on app size, on the loading time - secondly in my case.

Could please advise on it, how to decrease app loading time? Thanks in advance.

`Current Version: 0.9.104`

UPD: The video showing the case:

https://user-images.githubusercontent.com/53024832/129254563-d8a2c84c-77d5-4ef9-8d31-58179698462f.mov

If I rightly understand, when app is opening - the whole app content: scripts, UI, ALL screens/pages are loaded/downloaded from the app server (as I can see in performance section of Chrome Inspector) And as for the app size, it's difficult for me to explain but I feel like there is a something unnecessary/old/already deleted still stored in my app, I don't think there is really 25MB, almost nothing heavy  there, maybe for 10-12 MB. I am unable to analyse the exported file. Sometimes I have failures when exporting/importing the app as it shown below (just an example from today):
![image](https://user-images.githubusercontent.com/53024832/129262253-79b26842-b4d7-467d-829b-ced4d8ad1802.jpeg)
But after few tries it goes away and export/import ends successfully. First time I thought the errors occurs because of the base64 in CSS and I tested it by removing all base64 images data from custom css across whole app, but it doesn't affect. Base64 works fine in BB and doesn't lead to an issue, just slightly increases the app size (depending on the image of course).</div>

**Comment by SamsonChow** [comment]
This is great to see your presentation, do u know anywhere may see more samples? I try to search around, I can't see any program is built by BB. Thx for your help!
