### ISSUE TITLE
How to send data from budibase to other service.

### ISSUE THREAD

**Issue by iavinas** [Budibase/budibase#2430]
In budibase docs it is written-
```Automations can also be used for integrating with external platforms and services, for example if you already have web services that are deeply integrated into your processes then automations can be used to receive or send data automatically between the two systems.```

But I am not able to figure out how to send whole data from a table to another service probably using the GET method. Please help me with how to do this. I am using budibase Internal CSV as data source.

**Comment by mslourens** [comment]
You can create an automation, which invokes a REST endpoint when, for example, a new row is created. You don't have access to the whole database, just the row you just created.  
These are the steps to do that:
1. Navigate to the automate tab
2. Click the Plus button next the Automations header to create a new automation
3. Give the automation a name
4. Click the Trigger button at the top
5. Select the trigger 'Row created'
6. Select a table in the Setup panel (on the right)
7. Click the action button at the top
8. Select the action 'Outgoing webhook'
9. Select a method in the Setup panel
10. Insert an endpoint in the Setup panel
11. Define the JSON body (either using the lighting button, which allows you to select the row data or some manually typed JSON string
12. (optionally) define headers, like an api-key, for the request to your api
13. Click the Save automation button
14. Toggle the live switch, so the automation is active.
15. Create a new row in the database you selected in the steps above, which will trigger the automation webhook.

**Comment by mike12345567** [comment]
Closing this issue as it is related to issue #2410 - the ability to query automation data and push it into future automation steps.

**Comment by ShinJustinHolly3317** [comment]
didn't see  this `outgoing webhook` choice on the action panel

**Comment by meadow-kun** [comment]
where did the outgoing webhook choice go?

**Comment by mike12345567** [comment]
This is a very old issue - you can use the `External Data Connector` - you can use this to run a REST query which you create from the data section.

https://docs.budibase.com/docs/rest
