### ISSUE TITLE
On detail screen, SQL Relationships don't save unless re-selected

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2435]
To Repro:
1. Create SQL datasource (ds plus)
2. Create tables with One-Many relationship, and add some data
3. Create a "detail" screen for the "Many" table. 
4. Run your app and open the detail screen
5. Change nothing, just press save

I got the following error:
```
{"message":"error: invalid input syntax for type integer: \"{\"primaryDisplay\":\"michael\",\"_id\":\"%5B9%5D\"}\"","status":400}
```

here is my request body for the save:

```
{"id":null,"name":"New Deal","customerId":9,"value":1000,"_id":"%5B2%5D","tableId":"datasource_plus_32a51e0dfccb41058080147904f898d8__deals","_rev":"rev","Customer":[{"primaryDisplay":"michael","_id":"%5B9%5D"}],"Customer_text":"michael"}
```
Note the `Customer` field - this is my relationship (the parent/"one"). It's `_id` is "%5B9%5D". 

I'm guessing that this is because
1. The foreign key is an integer
2. The supplied value is `%5B9%5D`

@AndrewJRamay reported this in https://github.com/Budibase/budibase/discussions/2396

**Comment by AndrewJRamay** [comment]
Hi, @mjashanks any chance this issue is resolved in the next feature release I hear that is coming in the next few days?

**Comment by mike12345567** [comment]
This issue has been resolved as of latest bug fixes PR.

**Comment by kengeorge2** [comment]
Kennymiles Tech
0 seconds ago
Hello, thanks for the demo, can you kindly make a video on a master detail  form, lets say like an invoice with invoice items, or requisition with request items. Would be great.
