### ISSUE TITLE
User Roles 

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#245]
Roles aka Access Levels
2 Default Roles
- Admin
- Power user
(names up for grabs)

These roles never go away
### Create Role
A Role can be created - you can choose to start with an existing role, or not
On creation, you'll just give it a name, i think

### Edit Role
When editing role, we should be able to see all permissions assigned to the role, and add/remove them.

Might be worth mentioning that it is possible to group them by type...
1. Models (read/write)
2. Views 
3. Workflows
4. General (create user, mayeb some more)

### Adding Permissions
Permissions will be added via the object your are giving access to... similar to how Drive works when sharing files/folders
1. Create/edit model - somewhere to choose which roles have access
2. Create/edit view - same
3. Create/edit workflow - same

**Comment by joebudi** [comment]
Design will be housed here:
https://xd.adobe.com/view/f3ff5ab0-93c2-43be-7173-44ab421a5e52-85ce/?fullscreen

**Comment by joebudi** [comment]
The updated design can be found here:
https://xd.adobe.com/view/55993381-d554-4328-55e6-0c8972ebbd54-23a8/?fullscreen

This will hopefully be the last update and consists of:
Tables (fields, creating a record, setup)
Views (Filtering, advanced filtering)
Users (User access levels, permissions, adding new test users)

**Comment by mjashanks** [comment]
The server stuff for this is done. 

We need to complete the properties panel (right side) before completing this task
