### ISSUE TITLE
Adding external source without type

### ISSUE THREAD

**Issue by fao9** [Budibase/budibase#2452]
**Describe the bug**
While adding external source you should choose type of data source (SQL, Mysql etc.). Is possible to avoid a choice - you can ignore type of data source. If you will create data source without type - your APP will be blocked/freezed. App won't do anything if you added invalid source data. 

**To Reproduce**
1. Go to Data>External
2. Click on plus to add new external data source
3. Fill Datasource Name - but don't click to any datasource icon
4. Click Create (blue button)
5. New data source added successful (unfortunately) - you will see added source in external sources list (without icon - just name). Now you can't delete this source or repair this step.

**Expected behavior**
You shouldn't add datasource without choosing a type - button "Create" should be disabled unit you will choose datasource type.

**Desktop (please complete the following information):**
 - OS: OSX/Windows 10
 - Browser: Chrome/Opera

**Comment by aptkingston** [comment]
Hey @fao9. This is already the behaviour - you can't create it until you pick a type. The button remains disabled. Could you clarify how you did this? On step 1 when you say go to Data > External, what do you mean by that?

Here's a screenshot showing the button is disabled if you don't pick a type:
![image](https://user-images.githubusercontent.com/9075550/130757081-c703cdd4-ab3f-4708-b700-be037e5ddb40.png)

**Comment by fao9** [comment]
![obraz_2021-08-25_105527](https://user-images.githubusercontent.com/35664902/130760567-45915637-5ef7-4197-9e0b-003285b599f8.png)

Budibase is up to date (I checked lastest version for BB panel). Instance is created from Digitalocean marketplace.

**Comment by mslourens** [comment]
The version of Budibase on DigitalOcean is 0.9.1, which is pretty old (2021-05-20), this issue has been fixed on 2021-06-28.

**Comment by fao9** [comment]
![obraz_2021-08-25_133939](https://user-images.githubusercontent.com/35664902/130784296-211cb754-1c3a-4d53-9638-d87f7b22af6c.png)
Please take a look. I was pretty sure that, im using latest version. DO image should be updated as soon as possible, propably my another bug issues were fixed too... I dont know how it's look in present version - but somewhere should be listed version of BB. Thank you for a reply :-)
