### ISSUE TITLE
One time validation in field settings

### ISSUE THREAD

**Issue by fao9** [Budibase/budibase#2453]
**Describe the bug**
If you try to design element (field / textarea) and you are using additional options with flash icon (handlebars) you can use advanced helpers and methods. Validation in this area is only one time - you made mistake in expression - will get one time information about error: "Current Handlebars syntax is invalid, please check the guide here for more details.". If you edited your handlebar expression and now everything seems to be OK - you can't add your code, save button is disabled - you have to close window, paste your edited code and save.

**To Reproduce**
1. In design section - use any element with handlebar (flash icon)
2. While you are adding expression - make mistake - you will see information about syntax
3. Repair your mistake and still you can't save your code - this is error

**Expected behavior**
Validation should work everytime when you try to save your handlebar. If handlebar is fixed after mistake, you should have option to save field without closing and opening window.

**Desktop (please complete the following information):**
 - OS: OSX/Windows10
 - Browser: Chrome/Opera

**Comment by aptkingston** [comment]
Hey @fao9. You just need to blur the text area (click outside it) to get it to run validation again. We don't run validation on every key stroke, just whenever you blur the field. Maybe this is confusing behaviour, so maybe we should look into validating it on key strokes and debouncing it or something.

Here's an error:
![image](https://user-images.githubusercontent.com/9075550/130757392-62e5c008-c229-4ca5-aa2a-66f638754b15.png)

Then when I fix the error and blur the field again:
![image](https://user-images.githubusercontent.com/9075550/130757484-ebabecdc-5581-4b24-9068-829ecd2beedf.png)

**Comment by fao9** [comment]
I tested it again and now, It seems to be OK - I dont now how it possible, yesterday it works like I wrote. I will keep eyes on it. Sorry for problems and for your time to verify. Please close this issue.

**Comment by aptkingston** [comment]
No problem! You can let us know if something happens again.
