### ISSUE TITLE
Data loop in charts

### ISSUE THREAD

**Issue by fao9** [Budibase/budibase#2454]
**Describe the bug**
While you design charts and by mistake you select wrong columns (from db) as data to show - live preview will try to load this data and your app may catch freeze. 

**To Reproduce**
1. In design module try add candlestick chart with data. You should choose column with a lot of data (100+). Your app in live preview will do everything to show you data and you will catch a freeze. It's really hard to repair because designing panel work very slowly.

**Expected behavior**
During design you shouldn't see every change in live mode. You can make some mistakes - I suggests to create additional button to update data or debug your changes in live design mode - to fill prototype with real data. 

**Desktop (please complete the following information):**
 - OS: OSX/Windows10
 - Browser: Chrome/Opera

**Comment by aptkingston** [comment]
Hey @fao9. I've tried my best to reproduce this using a table with 100 rows, and picking the wrong columns for the candlestick chart. I can't make it crash no matter what I do. How many rows is your data provider returning? If you are returning lots (1000+) then I would recommend turning off chart animation. The animation can hurt performance on slower devices.

**Comment by fao9** [comment]
I tried to reproduce this and it happend again in data around 30 rows. 

- Droplet Digital Ocean Cloud 2GB 
- PC have 12GB RAM and i5 10gen CPU.

I will try to add some example data to internal database, because I use external DB located remote so maybe problem is with DB Server. But loading data from this db works very good in another charts and elements. I will try in this week to upload more details.
