### ISSUE TITLE
No way to edit screen and screen permissions

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#2486]
**Describe the feature request**
There's currently no way to edit the screens name, url and permissions. As it is now you have to delete your whole page and re-create it. 

A workaround until this is implemented is to copy the whole screen and paste it into a new one.

**Comment by mslourens** [comment]
The name of a screen can be chaged by selecting the screen and updating the name in the General section of the PropertiesPanel:
![image](https://user-images.githubusercontent.com/1907152/131409803-205bf827-b08d-4ce7-9a99-dcaade6b7201.png)

 The access and the route can be changed in the Screen section of the PropertiesPanel:
![image](https://user-images.githubusercontent.com/1907152/131409847-c09d6c50-1674-40b3-8927-438f90f61aa8.png)
