### ISSUE TITLE
upload logourl 404

### ISSUE THREAD

**Issue by jianzhichun** [Budibase/budibase#2488]
**Describe the bug**

I am doing i18n support base on develop branch. And I found that logo-upload-url was 404 recently when I did manual testing.
![image](https://user-images.githubusercontent.com/17561654/131270666-ce391921-0072-45b5-ae44-95ed14d9536f.png)
Maybe due to this commit. 
https://github.com/Budibase/budibase/pull/2403/files#diff-eff93618308508c2b3f5fb0f787f5d9359f7f72baf146c66467fa663e31ee8a0R41
I think I have pulled the latest code for worker.
![image](https://user-images.githubusercontent.com/17561654/131270780-9610f37c-ac06-42f9-8cf2-75357c198388.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sergey-dme** [comment]
Issue confirmed.  Hmm.. It was recently fixed and working in previous or two versions ago.

**Comment by shogunpurple** [comment]
https://github.com/Budibase/budibase/issues/2495#issuecomment-908715332

This seems related. Please update your `envoy.yaml`, restart your `proxy-service` and see if the issue has been resolved.
