### ISSUE TITLE
Unable to change url for rest api

### ISSUE THREAD

**Issue by lyn444** [Budibase/budibase#2489]
**Describe the bug**

- Cannot change baseurl for REST API Data Source
- Cannot create new queries for REST API

**To Reproduce**
1. Spawn a brand new budibase docker setup with the latest version (Current Version: 0.9.116)
2. Create a new app
3. Go to Sources.
4. Create a new Rest Source
5. Try to put a different URL "google.com" in the configuration->URL field
6. Click Save - Expected to save the new URL successfully.  Actual behavior: The setting is not saved and the value reverted back to localhost
7. Go to query
8. Click add query
9. Click Run Query - Expected to see query base URL. Actual: Error saying Only absolute URLs are supported

**Screenshots**
![image](https://user-images.githubusercontent.com/2337363/131304101-569df89a-8d81-4f15-98d3-0e8a6a43d4b4.png)
![image](https://user-images.githubusercontent.com/2337363/131304161-4f72863f-68ad-469a-85f6-57400f2d1147.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser Chrome
 - Version 92.0.4515.159

**Additional context**
Fresh install

**Comment by kevmodrome** [comment]
Hi! This has been fixed and should be going out in the next release (most likely tomorrow). In the meantime, you can use the develop branch
