### ISSUE TITLE
Brought back to login page every time I login

### ISSUE THREAD

**Issue by notindi126** [Budibase/budibase#2495]
Hey, every time I log in to budibase, it immediately brings me back to the log in page. For a split second, it'll tell me I've successfully logged in then it bring me back to the log in page. I have no idea how to fix this or why it's happening, help would be very much appreciated. Thank you! :)

**Comment by mslourens** [comment]
Do you see any error messages in the browser console?

**Comment by notindi126** [comment]
> Do you see any error messages in the browser console?

nope, it just resets itself once logged in

**Comment by notindi126** [comment]
> Do you see any error messages in the browser console?

actually, I just double checked 
![image_2021-08-30_131135](https://user-images.githubusercontent.com/81588967/131399106-a11ed089-af59-4c1b-952b-ed81ef42298d.png)

**Comment by AndrewJRamay** [comment]
@notindi126 I had the same problem. I updated my bbworker and bbapps both had crashed over the weekend. for whatever reason. I run them in docker. updated and it works now.

**Comment by shogunpurple** [comment]
The problem here could be that the `envoy.yaml` reverse proxy configuration has been updated since the last release. To pull the lastest and update your proxy, you `cd` into the directory where you installed budibase and you can run the following commands:

```
wget https://raw.githubusercontent.com/Budibase/budibase/develop/hosting/envoy.yaml
docker-compose restart proxy-service
```

**Comment by AndrewJRamay** [comment]
@shogunpurple  for some reason I'm still not getting it to save. I updated envoy.yaml file and restarted it. 

![image](https://user-images.githubusercontent.com/80058238/131411205-1d4a405a-a551-4039-b4eb-0f4990e8a6eb.png)

here is the new file in the folder 
![image](https://user-images.githubusercontent.com/80058238/131411280-ac5838fb-baf2-43b0-9532-b55c3eba64ea.png)
 
anything I can try differently?

**Comment by shogunpurple** [comment]
@AndrewJRamay can you run an `ls` in that directory and show me the output?

**Comment by AndrewJRamay** [comment]
@shogunpurple 
![image](https://user-images.githubusercontent.com/80058238/131411921-1d79091e-99d7-4e9f-be97-188badb7927e.png)

**Comment by shogunpurple** [comment]
@AndrewJRamay that looks fine, no problems.

Are your worker and apps still up?

`docker ps`

**Comment by AndrewJRamay** [comment]
@shogunpurple yes all are running 
![image](https://user-images.githubusercontent.com/80058238/131415095-d3b50414-6515-4b3c-8f54-5188c6fc7af3.png)

**Comment by shogunpurple** [comment]
Thanks @AndrewJRamay - could I see your browser console when the request occurs? Is it the `self` call that is failing?

**Comment by AndrewJRamay** [comment]
@shogunpurple the update this morning to 0.9.117 did the trick thank you!
