### ISSUE TITLE
Backup attachments in export

### ISSUE THREAD

**Issue by fire** [Budibase/budibase#2500]
**Describe the feature request**
As a user of budibase, it is not expected that a backup of the app would lose the attachments.

The admin of budibase can manually go to the minio s3 datastore and copy things but there's no hooks or a process for that either. There's no clear process for putting attachments back.

**Screenshots**
Imagine a screenshot mentally of an export file that contains everything except the pdf attachments that were used for cataloguing accounting receipts which was the purpose of the database.

**Comment by mslourens** [comment]
Attachments are stored in a AWS S3 bucket. When exporting an app only the reference is stored in the txt file. After importing the backup the attachments get copied to the new app bucket. Or do you want to export/download the attachments together with the export.txt?

**Comment by fire** [comment]
> want to export/download the attachments together with the export.txt

This!

**Comment by shogunpurple** [comment]
This is a pretty nice suggestion - I feel like it should probably be optional in case you don't want to download a ton of images potentially.

**Comment by fire** [comment]
Is there any way I can prioritize this?
