### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by PGLange** [Budibase/budibase#2501]
Hi there,
when i run budi hosting --update, then a non working version of docker-compose.yaml is created.
The Error Message is: services.watchtower-service.ports contains an invalid type, it should be a number, or an object

This happens also when I load the docker-compose.yaml from https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml

Is this an already known issue? Am I the onlyone facing this? 

Have a great day, and please let me know how to get along with it, I can't update atm. I'm stuck at version 99.105. ....

.... The Variable Watchtower_Port ain't set, replacing with 6161 worked... but I had to manually edit docker-compose.yaml....
 - "${WATCHTOWER_PORT}:8080"
 changed to - 6161:8080  worked ....

**Comment by shogunpurple** [comment]
Hey @PGLange - you need to add WATCHTOWER_PORT to your .env file found where you installed budibase, then run again.

Thanks!

**Comment by PGLange** [comment]
Hey @shogunpurple 
done, but still not able to bring it up with budi hosting --start - only works with docker-compose --env-file ... .
What am I missing?

**Comment by shogunpurple** [comment]
Hey @PGLange - it looks like you still might be using the older `hosting.properties` format. Try running the following command:

`cp hosting.properties .env && budi hosting --restart`

**Comment by PGLange** [comment]
hey @shogunpurple,
this worked... is this already written in docs.budibase.com? Would be a great hint ;)

Thanks a lot!!!!
