### ISSUE TITLE
"No Access" Role / Public by default

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2503]
**COS**
- Users are assigned a PUBLIC role by default
- Don't  actually show the PUBLIC role badge, just show nothing to indicate the user has no role for an app
- Account for non-home public routes

**Comment by KernOil** [comment]
Another great feature that would be awesome! keep up the good work!

**Comment by Rory-Powell** [comment]
Potential mock ups of how this might look
![](https://cdn.discordapp.com/attachments/735083509202419778/867785747159711744/Screenshot_2021-07-22_at_16.10.05.png)

Discussed here
https://discord.com/channels/733030666647765003/735083509202419778/867772469061353472
