### ISSUE TITLE
Not able to Create mysql datasource

### ISSUE THREAD

**Issue by Amolmanorkar** [Budibase/budibase#2510]
Not able to Create MYSQL datasource Whenever trying to create mysql datasource, its getting overwrite by default saved connection properties

**To Reproduce**
1. Go to New Data source
2. Click on Mysql DB
3. Added user/Name password as root/'Password'
4. Gets overwrite by default connection properties

**Expected behavior**
It should able to save user entered properties

**Screenshots**
1. Editing my new MYSQL connections : 
![Screenshot from 2021-08-31 21-17-19](https://user-images.githubusercontent.com/9339243/131537062-f5e81350-dae1-45a1-84cd-34bb3456d862.png)

2. Clicking on save button
![Screenshot from 2021-08-31 21-17-42](https://user-images.githubusercontent.com/9339243/131537312-e602f5bd-bee8-4ac6-b076-2e343a3e9466.png)

3. Overwrite by Default values in MYSQL connections : 
![Screenshot from 2021-08-31 21-18-19](https://user-images.githubusercontent.com/9339243/131537352-62216cd1-6be4-42b8-a1c9-2e41a1eba2dd.png)

 - Ubuntu 18
 - Firefox/Chrome Both latest versions

Let me know if there's any further details needed

**Comment by chrisshaw** [comment]
The following issues shows up with PostgreSQL data sources as well.

Ubuntu 20.04
Firefox/Chrome

Looking at the `PUT` request, something odd seems to be happening on the server. The request body goes through:

```
{"_id":"datasource_plus_912c0129ccab453f86a64e337f3e465b","type":"datasource_plus","name":"Azure PostgreSQL","source":"POSTGRES","config":{"host":"host-at.postgres.database.azure.com","port":5432,"database":"portal","user":"budibase","password":"ihavebeenreplaced","ssl":true},"plus":true,"_rev":"1-0fccd1dfbc92202811ff0e6847f82b3c"}
```

But the response body is the defaults:

```
{"_id":"datasource_plus_912c0129ccab453f86a64e337f3e465b","_rev":"2-6506fbf7867fd7b2465b245a4fc4e233","type":"datasource_plus","name":"Azure PostgreSQL","source":"POSTGRES","config":{"host":"localhost","port":5432,"database":"postgres","user":"root","password":"root","ssl":false},"plus":true}
```

**Comment by mike12345567** [comment]
Hi guys,

Just to check what version of Budibase you're seeing this issue on? I've tested this on the latest August release (0.9.117) and did not encounter this issue.

**Comment by chrisshaw** [comment]
0.9.116, but I just updated to 117 and no longer see this issue!

**Comment by Amolmanorkar** [comment]
Check for updates click showing me '0.9.116' is latest one
![Screenshot from 2021-08-31 22-58-54](https://user-images.githubusercontent.com/9339243/131548793-3509d9e0-2c55-4b09-a3a8-2f6fe9bb94b9.png)

**Comment by chrisshaw** [comment]
@Amolmanorkar I had to fight it.

1. I navigated by to home by clicking the [bb] logo
2. Then clicked back to Updates.
3. I actually got an error message about a broken connection upstream.
4. I refreshed
5. Did the same thing
6. It now said 117

I believe is a separate bug to report @mike12345567

**Comment by Amolmanorkar** [comment]
tried same @chrisshaw still showing version 116 as latest version

Response : 
{"_id":"datasource_plus_40efc72740754436a9029a430abdd19c","_rev":"7-9cb41e699ef359c21cb47783426233b8","type":"datasource_plus","name":"mysqlConnection","source":"MYSQL","config":{"host":"localhost","port":3306,"user":"root","password":"root"},"plus":true}

Request : 
{"_id":"datasource_plus_40efc72740754436a9029a430abdd19c","_rev":"6-c23dee9e03fb6ff9b28527e0a08d382c","type":"datasource_plus","name":"mysqlConnection","source":"MYSQL","config":{"host":"172.16.203.155","port":3306,"user":"rootsd","password":"root"},"plus":true}

**Comment by Amolmanorkar** [comment]
it got solved with version update to 117, thanks you so much guys for all help & quick responses @chrisshaw @mike12345567
