### ISSUE TITLE
'Invalid Binding' Getting insert in the MYSQL db table

### ISSUE THREAD

**Issue by Amolmanorkar** [Budibase/budibase#2522]
'Invalid Binding' Getting insert in the MYSQL db table
when creating simple create book entry query, with set of parameters & then run a query, it adds entry in database as 'Invalid Binding'

**To Reproduce**
1. Go to create Query
2. Select Parameters with some default values
3. Run Query & check database values

**Expected behavior**
It should always fallback to default values which are defined in parameters

Screenshots
1.Creating Query & clicking on run query:
![Screenshot from 2021-09-02 13-16-51](https://user-images.githubusercontent.com/9339243/131803906-89fd09ff-817a-492a-836c-b6b4e9686518.png)

2. Checking values in db table: 
![Screenshot from 2021-09-02 13-17-16](https://user-images.githubusercontent.com/9339243/131804005-44914aea-ffff-486b-978d-0f1abec42caa.png)

 - Ubuntu Latest
 - Chrome Latest

**Comment by shogunpurple** [comment]
Thanks @Amolmanorkar we will look into this one - your configuration looks fine so it could be a bug.

**Comment by rhrish** [comment]
I found a temporary fix for this. This problem seems to occur only when the parameter name is same as the field name. Changing the parameter names fixes the issue.
