### ISSUE TITLE
Unable to create Views with the letters 'stat' in the name

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#2530]
**Describe the bug**
When you create a View and name it 'stat', the view does not populate with data.

**To Reproduce**
1. add data to a table
2. Click add view
3. Name it stat

**Expected behavior**
View should work

![Screenshot 2021-09-02 at 16 49 12](https://user-images.githubusercontent.com/49767913/131878413-03f51ab4-bc70-46bc-aee4-e86b81bb919c.png)

**Comment by mike12345567** [comment]
This issue has been resolved as of latest bug fixes PR.
