### ISSUE TITLE
Staging version of app hangs when Play button pressed

### ISSUE THREAD

**Issue by jk979** [Budibase/budibase#2532]
I have created a form with a Submit button which saves a row to the database upon being pressed. 

1. Created a simple form with a Submit button and added an Action to the button
2. Press Play button in upper right corner to view it in staging environment
3. New tab/page opens, but nothing happens (something happening in background but nothing loads, only see white space)

**Comment by mslourens** [comment]
Can you post the output of the console? 
Which version of Budibase do you use? 
What is the schema of the form (external database or internal Budibase DB)? If external, what type of connector (MySQL, MSSQL etc)?
