### ISSUE TITLE
Auto columns are always added to the end of a table when making a screen

### ISSUE THREAD

**Issue by Grayda** [Budibase/budibase#2552]
**Describe the bug**
When adding columns to a table in a screen, the auto columns always appear last, regardless of what order they're selected

**To Reproduce**

1, Make a new table called Example, with the auto columns added (Created At etc.)
2. In the table, add two new text columns, `Test` and `Demo`
3. Go to the Design tab, and bring up the `/example` screen
4. In the columns dropdown on the right hand side, change it from `All Columns` to the following columns in this order: `Demo`, `Created At`, `Test`
5. The columns will be ordered like so: `Demo`, `Test`, `Created At`,
6. Remove the `Demo` column, and re-add it
7. The columns will now be ordered like so: `Test`, `Demo`, `Created At`

**Expected behavior**
The table should show the columns in this order: `Test`, `Created At`, `Demo` (i.e. in the order the user picked them 

**Screenshots**
![Bug](https://user-images.githubusercontent.com/4891563/132207373-5bb6ef16-ad75-43ff-8378-8e13520e248c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  93.0.4577.63 (Official Build) (64-bit)

**Additional context**
Not a show-stopping bug, but something I noticed when asking #2548

**Comment by mslourens** [comment]
Auto Columns (like AutoID, CreatedBy, CreatedAt, UpdatedBy and UpdatedAt) are always added to the end of the table. It's not possible to move them.

**Comment by Grayda** [comment]
Based on https://github.com/Budibase/budibase/discussions/2548#discussioncomment-1285633 I thought it was a bug that could be fixed, but if it's not possible to fix it, then I'm not worried because it doesn't really affect me at all.

Thanks for getting back to me :)
