### ISSUE TITLE
budibase-client.js 503 Error 

### ISSUE THREAD

**Issue by christoph-noxt** [Budibase/budibase#2557]
**Describe the bug**
After creating a new app, only the following error is displayed in the Designer. The following is displayed in the console. This means that the app is not displayed. I tried it with different browsers (Chrome, Edge, Firefox) and the same error occurred. 
It is a new installation behind an Ingress. The additional NGINX rules have already been checked.
The problem also occurs with all other users.
In the Pod logs no error is shown.

**To Reproduce**
1. Go to 'new App'
2. Click on 'Design'

![budibase](https://user-images.githubusercontent.com/78072753/132229288-c4c0151f-5d45-46c5-a641-30dec87d8f91.PNG)
![budibaseerror](https://user-images.githubusercontent.com/78072753/132229291-730552ef-71db-4511-87e8-0c89681dacd5.PNG)

Thank you very much for your help!

**Comment by shogunpurple** [comment]
@christoph-noxt Thanks! This would indicate your minIO service is unreachable, and we cannot fetch the static files.

Can you post your relevant NGINX rules here so we can start there?

Are you using the default `docker-compose.yaml` and `envoy.yaml` configuration?
