### ISSUE TITLE
Unable to set organisation with existing apps created with default tenant_id

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2593]
**Describe the bug**
It is not possible to set the organisation (with multi tenancy flag enabled) after creating apps without multi tenancy enabled. 

**To Reproduce**
1. Ensure the multi tenancy flag is disabled
2. Create an app
3. Enable multi tenancy
4. Logout and back in
5. Set the organisation name
6. An error occurs in the console: `Cannot read property 'split' of null at exports.getTenantIDFromAppID (/Users/maurits.lourens/Documents/github/budibase/packages/auth/src/db/utils.js:70:23) at /Users/maurits.lourens/Documents/github/budibase/packages/auth/src/middleware/appTenancy.js:22:22`
7. The checklist endpoint also returns a 400 error, because the checklist for the created tenant could not be found

**Expected behavior**
It should be possible to set the multi tenancy flag after creating single tenancy apps

**Desktop (please complete the following information):**
 - OS: MacOS 11.5
 - Browser: Vivaldi
 - Version: develop branch

**Additional context**
The possible cause of the error described in step 6 is that the method `getTenantIDFromAppID` accepts a null as argument, but it doesn't check for a null inside the method. So if it receives a null it crashes.

**Note:** If it should not be possible to set the multi tenancy flag after creating apps without it, the app should prevent this from happening.

**Comment by mike12345567** [comment]
Hi @mslourens - good catch will get a PR for this raised.

On setting the multi-tenancy flag after apps created without it, we still need a path for migrating from no tenancy to multi-tenancy so we designed it in such a way that when the flag is enabled any existing apps are just treated as the default tenancy. This means its possible to upgrade, although not really possible to downgrade.
