### ISSUE TITLE
Props panel issues

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#261]
~~1. Layout props not working~~
~~2. Margin should come first. Also, the padding and margin boxes are wrongly labeled~~
~~3. Some of the inputs are text boxes when they shouldn't be but I guess the components for these are not yet created. Maybe we can turn these types of inputs into select fields? Example - justify~~

**Comment by Conor-Mack** [comment]
Bear in mind that the props panel isn't finished yet and whatever components are there at the minute are just placeholders 🙂 I'm going off the zeplin design for which components to build. If any changes to this could you let me know?

**Comment by joebudi** [comment]
Ahhh. I thought it was completed. I can't build a UI. You don't mind if I activate some properties?

**Comment by shogunpurple** [comment]
Some Ive seen:

- Props persisting between components
If you update a layout prop in one component, then click another, the prop seems to persist and leave `undefined`.
![Screenshot 2020-05-27 at 14 09 13](https://user-images.githubusercontent.com/11256663/83022585-a58cf780-a023-11ea-8c23-100e2ab694f9.png)

- Layout props should have the icons as they had before
- Props panel isn't scrollable

- When you select a background colour from the select, you can't undo it 
![Screenshot 2020-05-27 at 14 11 06](https://user-images.githubusercontent.com/11256663/83022754-e8e76600-a023-11ea-810f-6bf317f2df98.png)

**Comment by joebudi** [comment]
Updated issues: 

- Screenslot has no properties
- When duplicating a component from nav tree, the props are duplicated but not rendered, until you change a property

**Comment by joebudi** [comment]
There are multiple issues in one here. The props panel issue is completed. I will open a new issue for the rendering of new components and props.
