### ISSUE TITLE
Mongodb large results issue

### ISSUE THREAD

**Issue by wehde92** [Budibase/budibase#2621]
MongoDB connection querying large results doesn't work. Just running a find on a collection that has 145 results.

![image](https://user-images.githubusercontent.com/8854624/133653187-39775284-d5f1-49bf-955a-30f750cb67c5.png)

The data is just basic 3 keys and values per document. If we run it in mongosh it returns fine (just need to run "it" to loop through). 

It pulls the first item in before closing out.

![image](https://user-images.githubusercontent.com/8854624/133653806-4ed4279d-b17a-451a-9a6b-1e4b2185c774.png)

If we pull a smaller subset of data it works fine:

![image](https://user-images.githubusercontent.com/8854624/133653971-7da2b6a6-d6d8-4945-8e6f-9d218f7dd193.png)

Thanks

**Comment by wehde92** [comment]
This seems to have nothing to do with the default 20 item page limit from mongo's built in pagenation.

It seems to be a problem with returning the .toArray() call with more than 100 matching documents. Not sure if this is a memory limitation or variable. I'm able to select a subset of the data as long as the query results fit underneath 100 items.

**Comment by mslourens** [comment]
this seems to be related to #2696: the connections gets closed in the finally before all documents have be read.

**Comment by shogunpurple** [comment]
Closing as dupe of https://github.com/Budibase/budibase/issues/3022
