### ISSUE TITLE
Unable to sent trigger.row via outgoing webhook automation

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2634]
**Describe the bug**
I want to sent the whole row to an outgoing webhook using an automation. This is my automation:
![image](https://user-images.githubusercontent.com/1907152/133781242-84d6f1c7-973b-44d1-98d1-e000625064ec.png)
When I debug the request body that gets sent to the webhook, it doesn't contain the row, but the string "[Object object]"

**To Reproduce**
1. Go to the automations tab
2. Set up an outgoing automation (see picture above)
3. Save and test the automation
4. Note: The request is failing, although the endpoint is correct

**Expected behavior**
The whole row should be sent to the outgoing webhook as body, not just the string "[Object object]"

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
This piece of code breaks the outgoing webhook (taken from outgoingWebhook.js):
```javascript
try {
            // do a quick JSON parse if there is a body, to generate an error if its invalid
            if (request.body) {
                // THIS CODE HERE BREAKS, SINCE REQUEST.BODY = "[Object object]"
                JSON.parse(request.body);
            }
            const response = yield fetch(url, request);
            const { status, message } = yield getFetchResponse(response);
            return {
                httpStatus: status,
                response: message,
                success: status === 200,
            };
        }
        catch (err) {
            /* istanbul ignore next */
            return {
                success: false,
                response: err,
            };
        }
```

**Comment by mike12345567** [comment]
Thanks for raising this, I'll take a look at it!
