### ISSUE TITLE
Use Formula Field as table display column

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2643]
### Discussed in https://github.com/Budibase/budibase/discussions/2641

it's possible to set a formula field as a display column. However, Budibase will not allow us to create new rows - the error is "<Fomula field name> cannot be empty" - even when the fields that make up the formula are entered.

Either
- Formulas as display columns should not be allowed
OR
- This should work, provided the formula result is not empty

**Comment by tobehn** [comment]
Also i would like to be able to use these fields for Data Provider filtering.
Is this the same issue?
