### ISSUE TITLE
Math functions in handlebars that use arrays are broken

### ISSUE THREAD

**Issue by GlennMatthys** [Budibase/budibase#2671]
**Describe the bug**
Math functions in handlebars that use arrays always return 0 as value.

**To Reproduce**
1. Go to a number field
2. Set "Placeholder" to "{{ avg [1,2,3,4,5] }}" (without the quotes)

**Expected behavior**
Placeholder shows value "3".

**Actual behavior**
Placeholder shows value "0"

**Screenshots**
Inside editor:

![image](https://user-images.githubusercontent.com/31989842/133998406-5c79e8a1-6f06-42ba-805d-39ced42a9033.png)

Runtime:
![image](https://user-images.githubusercontent.com/31989842/133998656-8689ca4c-fe3b-44bb-971a-ddeac8f371f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004 (OS Build 19041.1237)
 - Browser: Google Chrome
 - Version: 93.0.4577.82 (Official Build) (64-bit)

**Comment by mslourens** [comment]
the example of the `avg` handlebars helper seems te be incorrect. The right way to pass arguments to the `avg` helper is: `{{avg 1 2 3 4 5}}`, without brackets or comma's.

**Comment by mslourens** [comment]
I fixed the avg helper example in PR #2672
