### ISSUE TITLE
Queries should also part of the expanded panel in the DatasourceNavigator

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2708]
**Describe the bug**
Datasources can be expanded and collapsed, but queries are not part of the expanded panel, which looks weird. I think queries belonging to datasources should be part of the expanded/collapsed panel. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1907152/134375449-13f5e8ff-ae39-4a32-a04f-0fb1ebfbd85f.png)
- getPosters is a MongoDb query and should be collapsed with the MongoDb datasource
- updateBooks is a Postgress query and should be collapsed with the Postgres datasource

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser: Vivaldi
 - Version: develop branch

**Comment by aptkingston** [comment]
Thanks @mslourens!
