### ISSUE TITLE
vehicles.csv attachment is missing

### ISSUE THREAD

**Issue by dgleba** [Budibase/budibase#2712]
**Describe the item**

This page says it has the vehicles.csv.

I don't see it.

**To Reproduce**

https://docs.budibase.com/guides/crud-app-with-budibase-db/importing-the-vehicles-table-from-a-csv

**Expected behavior**

The download link should be present.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mjashanks** [comment]
Done! Thanks for reporting.
