### ISSUE TITLE
The `search demo` download is not valid.

### ISSUE THREAD

**Issue by dgleba** [Budibase/budibase#2713]
The `search demo` download has this content:

`{"message":null,"status":403}`

https://docs.budibase.com/guides/add-search-to-a-table

![image](https://user-images.githubusercontent.com/4622715/134447368-6083d315-c4f0-4eab-b24e-c88db7433e40.png)

**Comment by mjashanks** [comment]
This works ok for me. I also tried in private browsing, in case I was logged into something. I have attached the file below for you.

[search_demo.txt](https://github.com/Budibase/budibase/files/7216584/search_demo.txt)

**Comment by dgleba** [comment]
The contents of the attached `search_demo.txt` file is:

`{"message":null,"status":403}`

Is that what it should be?

**Comment by mjashanks** [comment]
OH, i see now, Apologies @dgleba !
