### ISSUE TITLE
Cannot wrap long text

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2721]
I added a `Paragraph` component, which has some fairly long text. It does not wrap. 

I have tried 
- putting it inside a container, with the "wrap" checkbox ticked. 
- putting it inside a form, and binding to a RichText (just felt that this might support longer form). But, I couldn't work out what to bind it to (pulling this data from an API)

![image](https://user-images.githubusercontent.com/3524181/134519546-19788e07-f681-416f-a5c2-e4ef78ebb4ad.png)

I feel like the Paragraph element should automatically wrap. I would expect this. At the very least, we should have the option to do so.

**Comment by joebudi** [comment]
I think it is because the URL/link is one long string. This happens quite a lot with websites too. If you split it, it should wrap - the best solution is to use a link I suppose (which points to a note editor).

**Comment by mjashanks** [comment]
You are right - sorry, i logged this one too soon. Cheers!
