### ISSUE TITLE
Failed to save email settings. Error : Connection closed

### ISSUE THREAD

**Issue by satrioasmaraku** [Budibase/budibase#2750]
**Describe the bug**
Failed to save email settings. Error : Connection closed

**To Reproduce**
1. Go to 'Email Settings -> SMTP'
2. Click on 'SAVE'
3. See error

**Expected behavior**
Email setting success

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

![image](https://user-images.githubusercontent.com/90515555/134792338-d604d2c4-178e-4180-aaf5-2d64a82102ba.png)

**Comment by wfpaisa** [comment]
Hi guys, is there any solution?
![image](https://user-images.githubusercontent.com/1735752/155827377-ae5c4101-715e-4ad6-8779-56f7bbad73eb.png)

thanks
