### ISSUE TITLE
Inconsistencies in "Define Filters", when no comparison value is set

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2788]
When using filters on a data provider, the various operators behave differently, depending on what data source is being used.

**Like**
On a custom query, when the comparison value is not set, all results are returned
On a SQL table (used postgres), when the comparison value is not set, no results are returned
On an internal table, we don't have the option of Like (which i think is fine)

**Equals**
On a custom query and SQL Table, when the comparison value is not set, no results are returned
On an internal table, when the comparison value is not set, all results are returned (filter not applied)

Note: By "Comparison Value" I mean "Volkswagen" in the statement "Car.Make = 'Volkswagen' "

I actually prefer "when the comparison value is not set, all results are returned" - i.e. when no options is selected from the dropdown, the condition is not applied. Otherwise, we have to start using conditions to setup filters, which gets messy, quickly.

Context: https://github.com/Budibase/budibase/discussions/2778

**Comment by aptkingston** [comment]
Yea I think we should update the SQL to have the same results as lucene returns - which in this case would be returning all results if an equal expression does not have a value. Consistency is probably the most important thing like you say though, but there be differences in how the different databases themselves treat certain queries which might be outside of our control.
