### ISSUE TITLE
Attachments are not deleted when a row is deleted

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2843]
When we delete a row that has an attachment, the attachment is not removed from MinIO.

It should be. 

However - how should this work for `dev` vs `published` apps? Don't they share the same attachment?

**Comment by shogunpurple** [comment]
They do share the same bucket to avoid creating 2 and having to upload all the "dev" attachments into prod when you deploy. I would say it makes sense to:

- if you delete the row in production, it deletes the row, and also the attachment from the bucket
- if you delete the attachment row in dev, delete the row but keep the attachment, so you can revert if you need to
