### ISSUE TITLE
Self-host Budibase flow is broken

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#2850]
When I click the 'Self-host Budibase' button, it opens a modal. When I click upgrade, it opens the right page (self-hosting page in accounts), but then it redirects to the builder homepage.

Also, the flow where we want a user to try cloud then move to self-hosting is not the primary flow no more. So, the word upgrade is probably not right. I think the modal should read:

Title: Self-host Budibase
Description: Self-host Budibase for free...
CTA - Self-host Budibase

https://vimeo.com/619956829/b1f4d45758

**Comment by aptkingston** [comment]
I've updated the text, but there's some issue with redirects/auth in the hosting portal which I'm also seeing. In my case, it asks me to log in (even if I've already logged in). Attempting to go to `/portal/install` just always pushes me back to the login screen, and then always pushes me to the builder homepage after logging in as it does not store a return URL.

**Comment by Rory-Powell** [comment]
This one was raised before we hid the self host button for non-account holders. I think we are good to close this out
