### ISSUE TITLE
Date Via Action

### ISSUE THREAD

**Issue by NeloReis** [Budibase/budibase#2863]
**Describe the bug**
When adding action on submit button to fill out a DATE field with {{date now}}
the date is inserted ( think as text) but the actual date after the edit is January 1st 2021.
also the date is listed as text version when pulled from a repeater. 

**To Reproduce**
1create a DATE column on a table
2. create a form with submit button define add COLUMN,  to submit to the DATE field with {{date now}}
3. go back to the table .. on the submitted row press edit.
4. the date displayed on the edit does not match

https://user-images.githubusercontent.com/5040389/135686374-9296af71-d49b-41fc-aa51-a8d8fba09435.mov

**Comment by aptkingston** [comment]
Hey @NeloReis. I think the problem here is that `{{date now}}` is invalid syntax! It should just be `{{ now }}`. I've just tested this myself and it works perfectly.

**Comment by NeloReis** [comment]
Ok, Thank you.. I was using the syntax provided by the helpers' section.. but I'm glad I have a solution.
thank you
