### ISSUE TITLE
k8s instructions don't mention 1Gi minimum for digital ocean

### ISSUE THREAD

**Issue by fire** [Budibase/budibase#2868]
**Describe the bug**
k8s instructions don't mention 1Gi minimum for digital ocean this causes budibase to never start.

**To Reproduce**
1. Follow https://docs.budibase.com/self-hosting/hosting-methods/kubernetes

**Expected behavior**
Budibase startup as in:

![image](https://user-images.githubusercontent.com/32321/135737722-e5b78121-4763-40c1-920d-3ab3dbbe4940.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser firefox
 - Version 92.01

**Additional context**
None

**Comment by shogunpurple** [comment]
@fire what droplet are you running your K8S cluster on? 

I'm going to remove the "bug" label from this as it's more a documentation issue. I'll add it to the docs and you should scale up your droplet a bit. In general, K8S running on your droplet will consume considerable resources (depending on the K8S solution you use) so 1GB of memory is not really going to cut it for any production use

**Comment by shogunpurple** [comment]
docs updated - https://app.gitbook.com/@budibase-1/s/workspace/self-hosting/hosting-methods/kubernetes

closing

**Comment by fire** [comment]
It's one 1GB of disk btw for PVC.
