### ISSUE TITLE
Adding a field with name "type" on your model makes the field not show up

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#290]
If you create a model with a field named "type" it won't show up in your table. Most likely a name clash.

**Comment by shogunpurple** [comment]
Requires updating the `type` field in couch to `_type`

**Comment by mjashanks** [comment]
i just looked into this. I was going to update 
- `modelId` > `_modelId`
- `type` > `_typeId`

I then found out that CouchDb doe not allow this. It disallows naming of any member beginning with a `_`

So, I suggest that we just disallow creation of fields with name `type`, `modelId` AND anything beginning with `_`

I have not implemented this, as the backend is soon to be rewritten - so it should be tackled then.
