### ISSUE TITLE
spinning circle in design mode with safari not chrome

### ISSUE THREAD

**Issue by Bogey** [Budibase/budibase#2945]
### Discussed in https://github.com/Budibase/budibase/discussions/2933

<div type='discussions-op-text'>

<sup>Originally posted by **Bogey** October  8, 2021</sup>
For some weird reason Safari won't display the Screens and Layouts of the Design mode.
It only shows the spinning 'loading...' circle (see screen shot).

![2021-10-08 16 31 28](https://user-images.githubusercontent.com/866768/136576727-a62696bf-c115-47c2-b97d-f03faf951cc1.gif)
On Chrome, it works as usual.
I've disabled content blockers, emptied caches, cleared cookies and what not.
Unfortunately no working design mode on Safari.

It's Safari 15.0 on MacOS 11.6

Thx,
Eddie</div>

**Comment by Bogey** [comment]
It looks like it's been fixed 👍🏻

**Comment by jimmybrancaccio** [comment]
Can confirm it looks good on my end as well 😍

**Comment by shogunpurple** [comment]
Glad to hear it! Thanks for your patience on this one. Closing

**Comment by thegitcat** [comment]
Hi!

I am having the same problem using Firefox 96.0. I have this in error my Firefox console; Maybe it can help resolving: 

I am using docker self-hosted, no modification has been made to deployment, except secrets and password, on a clean docker host running alpine 3.X.

I have removed (whitelisted) all adblock or cookie blocker;

I have tested using Chromium Version 88.0.4324.182 (Developer Build, ungoogled-chromium) (64 bits); 

**It work fine (there is no problem accessing design)** so I guessed the problem was similar to what happened to Safari.

Budibase App version: This app is currently using version 1.0.35 which is the latest version available.

```
09:42:51,956 Uncaught (in promise) TypeError: can't convert undefined to object
    fetchRoutes http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    hI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    hI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    a http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    Ge http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    ze http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    je http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    gI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    loadBudibase http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    receiveMessage about:srcdoc:85
    EventListener.handleEvent* about:srcdoc:95
budibase-client.js:269:122378
    hI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    AsyncFunctionThrow self-hosted:699
    (Asynchrone : async)
    a http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    map self-hosted:224
    Ge http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    ze http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    je http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    gI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    loadBudibase http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    receiveMessage about:srcdoc:85
    (Asynchrone : EventListener.handleEvent)
    <anonyme> about:srcdoc:95

```
![image](https://user-images.githubusercontent.com/21105459/149163501-7368d292-c4cd-4f40-a310-89e9bc68c9e7.png)

![image](https://user-images.githubusercontent.com/21105459/149163571-58a6999a-a970-4a1f-a7f8-e93fbdeb6de0.png)

**Comment by jimmybrancaccio** [comment]
@thegitcat I would recommend opening a new issue as this was a problem specific to Safari which is now resolved and this issue is closed.

**Comment by thegitcat** [comment]
> @thegitcat I would recommend opening a new issue as this was a problem specific to Safari which is now resolved and this issue is closed.

OK; Sorry; Issued opened https://github.com/Budibase/budibase/issues/4007
