### ISSUE TITLE
Custom queries - sort by number, sorts alphabetically

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2962]
`Sort Column` applies an alphabetical sorting to numerical fields.

To Repro
1. Create a custom query against a source that has a number field - I'm using postgres, `select * from public."customers"`. My customers table has an `age` column - an `integer`
2. In design, add a `Data Provider` 
3. Set the `Sort Column` to your number field (`age`)
RESULT
filter order is alphabetical, not numerical

I believe that this is related to us not properly storing a schema for custom queries. I feel like doing so would help with a bunch of issues.

**Comment by GabrieleLabanca** [comment]
Hello, I have the same problem selecting a column explicitly casted to integer (I would be happy to check the type returned, but I don't know how).
Version 1.0.46.

**Comment by Simoon-F** [comment]
I think the settings that cannot be canceled after selection should be canceled. I just want to render directly according to the data returned by api, and I don't want any asc or desc.
