### ISSUE TITLE
Rich Text Component

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2967]
We have a `Rich Text` component. In actual fact, it's just a `Text Area` field. We'd be better off having a "Multi Line" option on a standard text field.

I get that it might be a backwards compatibility issue to just get id of it. 

I think we will eventually look into making it an actual Rich Text field. Temporarily, could we rename it "Text Area"? as "Rich Text" is incorrect

I seem to remember us going through this decision process before. Using https://quilljs.com and maybe https://ckeditor.com ? I was sure that we have formatting options on the Rich Text field at one point.

Note:
- A "read only" capability on the Rich Text Component would help with this issue https://github.com/Budibase/budibase/issues/2334f

**COS**
- The rich text component must be themeable and styleable to be in line with other budibase components
- It will save it's format as markdown to the database

**Comment by mjashanks** [comment]
When we come to do this, can we also allow the Rich text component to be used by any Text type field - i.e. not just "Long Text".

At the moment, it's not possible to use a Rich text for a `Text` field. This is a problem with SQL varchar() columns - where they could be long or short.

Maybe the solution is simply to change the type at the schema level.

**Comment by keith-ellis-sillek** [comment]
Do you have a rich text field with formatting capabilities? If not, is this in the future? Is there a new ticket specific to this capability?

**Comment by aptkingston** [comment]
@keith-ellis-sillek yes this ticket involves updating the current "rich text field" to actually be a rich text field with editing capabilities.

**Comment by keith-ellis-sillek** [comment]
@aptkingston Sweet! Is anyone actively working on this? I was going to offer to look into this. I'm a developer with 20 years experience... Mostly Java web development, so I'm experience with JavaScript. Might be a big project for a Budibase newbie, but figured if it's a ways down the roadmap, I could jump into it.

**Comment by aptkingston** [comment]
I appreciate the enthusiasm! I'm actually taking a look at this one myself at the moment, but it would be great to see you get involved if there are any other features or tickets you want to take a look at.

As for this one though, are there any particular features you'd like to see as part of the new rich text field? What's your use case for it?

**Comment by kellis5137** [comment]
Excellent!

As for particular features, I would say the following would be nice to have:
- Bold, Italics, underlines, etc
- At least a small set of fonts. Nothing too big, just enough to give the user some variety
- Be able to embed images in the document
- Ability to create hyperlinks
- Tables
- Bullet points
- Code blocks
- Read only option
- Dynamic sizing of the element
- Configure initial sizing of the element

That's personally what I would like to see?! Especially being able to embed images.

**Comment by aptkingston** [comment]
@seble-nigussie it's actually called "long form field". Not a great name I admit! You can choose whether you want plain text formatting (like a text area) or rich text formatting.

**Comment by seble-nigussie** [comment]
@aptkingston  Thank you for your quick response. I'm using web api as the data source and one thing I'm struggling with is, when I add form elements like date and the long form field I get "This Field setting is the wrong data type for this component" and the input element doesnt show. Any idea why?

**Comment by amitava82** [comment]
I'm getting same issue as @seble-nigussie
