### ISSUE TITLE
Support multi-line text for standard Text types

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2976]
Currently, there is no way to allow multi-line text for standard `Text` type columns.

The "Rich text" component only binds to "Long Form Text", even if you manually type the field name.

This is especially a problem for SQL tables, which have no concept of "Long Form Text".

IMO, in an ideal world we should have
1. The standard `Text Field` component should have a `Mult-Line` option
2. The rich text component should produce rich text (see https://github.com/Budibase/budibase/issues/2967), and also be able to bind to text columns. I.e. if it reads something that is in plain text, it should understand it but save back as rich text.

For now, we should allow the existing Rich Text component to bind to text columns (as it's currently just a `TextArea` anyway)

**Comment by aptkingston** [comment]
Some work has been done on this with the recent rich text feature:
- Text is single line plain text
- Long form text can be multi-line plain text (default) or multi-line rich text by choosing an option in the schema
- Rich / plain text can be toggled at any stage by changing the schema
- The long form text component can be manually overridden and set to be either a plain text or rich text field

I think the issue of correctly mapping SQL types to our types still exists though. I think we should be able to convert text to long form text in the data UI - I don't see a downside of allowing this.

**Comment by simon-lewis** [comment]
I can see this one is closed but wanted to see if there was any appetite to revisit / reopen this - I have some long VARCHAR fields in a legacy DB on SQL Server which I would love to present in an app as multi-line text. Makes for a better UX than making text box super long or showing truncated contents.

So ... Seeking the ability to assign a multi-line text box (optional Rich Text setting is great but not essential for my application)
