### ISSUE TITLE
Add missing settings props to relevant components

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#303]
- [X] ~~Navbar~~
- [x] Screens (link, URL etc)
- [x] Add chart type prop to data chart

**Comment by kevmodrome** [comment]
Taking this Navbar on

**Comment by kevmodrome** [comment]
I think also @Conor-Mack is working on this one for the screens

**Comment by kevmodrome** [comment]
The navbar is finished

**Comment by Conor-Mack** [comment]
This should fix the Settings 👆
