### ISSUE TITLE
App template Cancel flow not working

### ISSUE THREAD

**Issue by purplepatrick** [Budibase/budibase#3089]
When choosing an app template and deciding to abandon it, none of the cancel options (Cancel button or X in corner of window) are working. The only way to cancel out of this page is to navigate away in the menu and return.

![image](https://user-images.githubusercontent.com/5438471/137938875-238e84fa-91a9-4c1f-a3a1-e6660e276ac6.png)

**Comment by mike12345567** [comment]
Hi @purplepatrick - good catch, I discovered this today, put up a fix for it here: https://github.com/Budibase/budibase/pull/3086

will be released soon, thank you for the report!
