### ISSUE TITLE
Allow Data Provider to render Array columns

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#3173]
When I'm using a nested data provide rcomponent, I want to be able to select an array based column of the parent record as a binding for the data provider, so that I can iterate over them.

**COS**
- Allow array based bindings to be available as sources for data providers, such as attachments, and multi options
- Hard code the schemas in the bindings, because we know what they are and will not change

**Comment by aptkingston** [comment]
So I've tried this multiple different ways and it's not looking great. There is no nice way to get an array-like field to pretend to be a data provider, which is effectively what needs to be done. Implementing this as it's defined would require really badly hacking at the client library and how a lot of the internals work and is absolutely not worth it, I guarantee.

Can I clarify the use case here in case there is something better we can do. Like for attachments, would a gallery component not make more sense?

The only way this would work is if we were ok with adding another data provider layer, much like how it works for relationship columns. For example, lets say you want to iterate over the current user `pictures` (attachment field). Your tree would be:
> Pictures provider (data provider, with a source of `Current user.Pictures`)
>> Pictures repeater (repeater)
>>> Whatever component you want, bindings for `{{ Pictures repeater.Pictures.URL }}` etc are available

The extra data provider layer does not fetch any data fom the server, so doesn't slow anything down. But it's essential for managing the schema and other important state properties. The upside for this is that this will allow array like columns to be used with *any* component that uses data providers. e.g. you could render a chart with multi options data, or list attachment names and URL's in a table.

**Comment by aptkingston** [comment]
Just to be clear, at the moment there is no way to iterate over array columns even with a data provider (other than relationships). So this is still a new feature, but the part about not needing an extra data provider is the part that needs to change.

**Comment by mjashanks** [comment]
I think doing this via data provider is completely fine.

A gallery component is also good, but the other use case is when iterating a relationship that has been enriched already. I think it will be even more important when we start to handle deeper JSON objects.

Is it an easy change to also modify the data provider to also have a `[ x ]  Repeater` checkbox, that automatically iterates below it?

**Comment by aptkingston** [comment]
> 
> 
> I think doing this via data provider is completely fine.
> 
> A gallery component is also good, but the other use case is when iterating a relationship that has been enriched already. I think it will be even more important when we start to handle deeper JSON objects.
> 
> Is it an easy change to also modify the data provider to also have a `[ x ] Repeater` checkbox, that automatically iterates below it?

Modifying the data provider to also be a repeater isn't an easy change no, but could that be a block candidate? Like a "Repeater block" or "Data repeater block" or even "Data block". That would be very easy to make and basically just combine a data provider and repeater. That's a really common use case.

This new block is basically also perfect for this issue then (assuming array-like fields could be data provider source), since every "layer" of something like a JSON block would just be one component, rather than a couple data provider + repeater for every level. 

So if we made this block, and also allow array like fields to be data provider sources, then we get the overall goal here of being able to iterate over arrays with a single component. How does that sound?

**Comment by shogunpurple** [comment]
Thanks for investigating this @aptkingston - I agree and think that the blocks/array as data provider source is a good middle ground. We don't want to add even more complexity to the data provider/repeater functionality as it's so fundamental. The main goal here is that you can only perform very specific operations with array based columns right now, and this will solve that. The block will then abstract that away, which is how I think we should think about things in future - using blocks if we can to make things easier and abstract, as opposed to changing core client library logic.
