### ISSUE TITLE
Grouped condition support on filters

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3183]
I would like to be able to create more complex filter conditions in Budibase. At the moment, we can only do 

`condition1 AND condition2 AND condition3....`

I would like to be able to do..

`(condition1 OR condition2) AND condition3`

We would have to draw the line somewhere of course!

This **could** apply to
- Data provider filter (Internal tables and SQL)
- Automation query
- Validation conditions
- Conditional UI
- Dynamic filter component (not started at the time of writing)
- View filters

**Comment by mike12345567** [comment]
Implemented as part of recent work.
