### ISSUE TITLE
Action to send attachment or link to attachment

### ISSUE THREAD

**Issue by l1z4a** [Budibase/budibase#3202]
I have the need to send an attachment to another system when a form is submitted or else send a download link to an attachment when the form is submitted. Is there a way to do that directly in Budibase? If not could someone point me to documentation on how I can create a custom automation action to get attachments out of Budibase?

**Comment by mayanktiwaridotcom** [comment]
Desperately need this feature, any developer working on this ?

**Comment by shogunpurple** [comment]
@mayanktiwaridotcom please stop spamming.

This isn't scheduled on the immediate roadmap, so I can't give you a timeline. We are always happy to accept PRs or you can fork in the meantime if this is something you desperately need.

Thanks

**Comment by mayanktiwaridotcom** [comment]
@shogunpurple Sorry to bother, but Actually I found lot of posts facing same issue so just to highlight and keep the thread active I commented on All of them.

**Comment by mayanktiwaridotcom** [comment]
I am not familiar with the framework which is used thus not able to help much :(

**Comment by druggedhippo** [comment]
Automation can do it

On row updated -> query row (filter on row id) -> send email with HTML contents:

`<a href="http://localhost:10000{{steps.1.rows.0.attachment.0.url}}">Download link</a>`
