### ISSUE TITLE
Sometimes the toolbar of settings for Container hide the Component itself

### ISSUE THREAD

**Issue by cverdes** [Budibase/budibase#3207]
**Describe the bug**
Sometimes the toolbar of settings for Container hide the Component itself. This issue appear for the top container when the `Layout` field of the screen is set to `Empty Layout`.
I made a simple toy demo application, attached at the bottom of this issue, to reproduce the screenshots.

**To Reproduce**
1. Import the application file attached at the end of this issue
2. Select the `Container One` component on the component tree at the left of the screen
3. See how the toolbar hides the `Container One`

**Expected behavior**
Show the toolbar in a place without hide the component, for example below the component for this cases.

A possible general solution, and perhaps an future improvement, it could be show context popups with specific helpers related to the component the user is selecting with a right-click.
As an example of the concept, the third screenshots shows how a context menu is displayed in PowerApps when the user right-click on an image component.

**Screenshots**
On this screen it can be seen the toolbar hiding the `Container One` component:
![Screenshot from 2021-10-31 14-12-34](https://user-images.githubusercontent.com/6440942/139594964-13e3957d-5fda-4c48-809e-096e7a5e2a66.png)

On this screen it can be seen the toolbar on top of the `Container Two` component:
![Screenshot from 2021-10-31 14-12-53](https://user-images.githubusercontent.com/6440942/139595050-a8d30bb7-c86b-4663-a66a-99754a345bb0.png)

On this screen it can be seen the context menu is displayed in PowerApps when the user right-clicks on an image component:
![Screenshot from 2021-10-31 14-46-34](https://user-images.githubusercontent.com/6440942/139595756-29dff6a2-abaa-4c71-9e00-279c834d5230.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.3 LTS
- Browser: Chrome
- Version: Version 95.0.4638.69 (Official Build) (64-bit)

**Additional context**
This is the file generated when exporting the application. It could help to test the case:
📄 [test when the toolbar of a container hide the component-export-1635700970293.txt](https://github.com/Budibase/budibase/files/7449346/test.when.the.toolbar.of.a.container.hide.the.component-export-1635700970293.txt)

**Comment by melohagan** [comment]
![Screenshot 2022-08-19 at 13 22 22](https://user-images.githubusercontent.com/101575380/185617336-557f5579-51c1-4bef-b47d-f395e178cd12.png)

This has been fixed. Closing.
