### ISSUE TITLE
App is automatically removed 

### ISSUE THREAD

**Issue by c1peter** [Budibase/budibase#3210]
**Describe the bug**
Occasionally when in design mode and running the preview, the App and related tables and design components are automatically deleted.

**To Reproduce**
random behavior

**Expected behavior**
get a 404 error

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: edge Version 95.0.1020.38 (Official build) (64-bit)
 - Version: Version 95.0.1020.38 (Official build) (64-bit)

**Additional context**
--

**Comment by HyperCrowd** [comment]
I've narrowed it down a bit more.

#3278

This is an atrocity.
