### ISSUE TITLE
Checkbox tick is out of place when the checkbox size is changed

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#3216]
![CleanShot 2021-11-01 at 14 17 03](https://user-images.githubusercontent.com/49767913/139686186-542c4227-a32c-4177-ab3e-67942797d05f.png)

To recreate the issue:
Add checkbox, change size

**Comment by aptkingston** [comment]
Just a bug with spectrum itself, it's nothing that we've done ourselves. I'll include a fix for this in my next PR.
