### ISSUE TITLE
Cannot update logo in Budibase Cloud

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3234]
I am unable to update the logo on my Budibase Cloud account. It seems to save correctly, but doesn't change the logo and doesn't retain the image in `Organisation` on page refresh.

It is working ok on self-host.

`POST api/global/configs/upload/settings/logoUrl` returns a `500`, with message:

```json
{"message":"Cannot read property 'replace' of undefined","status":500}
```

**Comment by pavel-orlov** [comment]
I cannot change the logo on my self-hosted deployment v0.9.178. A while ago I changed the logo from the default "bb" and now I'm unable to change it to any different. I can only reset it to the default one but it doesn't seem to delete the custom one from the backend.

 **Behavior:**
- Deletion of the custom logo, resets the logo to default.
- Uploading any different logo, sets the logo to the initial custom logo, not the one I upload.
- Changing custom logo has no effect.

```POST api/global/configs/upload/settings/logoUrl``` returns `200`, with message:
```{"message":"File has been uploaded and url stored to config.","url":"/global/settings/logoUrl"}```

**Tried:**
- Updating `envoy.yaml` with `docker-compose restart proxy-service`
- `budi hosting --update` with yaml files update
- Restarting the host
- Making full page refresh in the browser

**Comment by Rory-Powell** [comment]
@pavel-orlov I was able to reproduce your scenario. It looks to be caused by browser caching, can you try emptying your cache?

e.g. done like this on chrome
![Screenshot 2021-11-12 at 13 29 27](https://user-images.githubusercontent.com/8755148/141474876-7313c8d4-2aa2-4aef-84d0-0ff975577f7d.png)

**Comment by pavel-orlov** [comment]
@Rory-Powell, thank you, that worked.
