### ISSUE TITLE
Forever Page Loading Chrome

### ISSUE THREAD

**Issue by abcdefabio** [Budibase/budibase#3254]
Same problem in Chrome, Design Page forever loading after update app version to 0.9.178 from 0.9.177 

 - OS: MACos Big Sur 11.6
 - Chrome Versão 95.0.4638.69
 - 
![Captura de Tela 2021-11-04 às 18 04 37](https://user-images.githubusercontent.com/8226996/140419881-4aef5810-4651-4dee-abff-257c05a6706d.png)

Budibase is the best low code open source!! Thks guys.

**Comment by cverdes** [comment]
I am experiencing the same problem. Maybe it's not a bug, but a service down on the server

**Desktop (please complete the following information)**:
-OS: Ubuntu 20.04.3 LTS
-Browser: Chrome
-Version: Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by abcdefabio** [comment]
No, because if you try the template "Job Application Tracker" then this
will work.

Fábio Vitorino



Em qui., 4 de nov. de 2021 às 18:50, Cesar Pablo Verdes <
***@***.***> escreveu:

**Comment by aptkingston** [comment]
Hey @abcdefabio and @cverdes. Silly question, but I'm guessing you've already tried refreshing the page?

If you have and it still won't load, could you check for any errors in the dev console (default key is F12). Thanks!

**Comment by abcdefabio** [comment]
Yes, I changed my browser, tried Firefox and Safari on different computers,
cleared cookies and cache, nothing worked.

My solution was.. I exported the app to a txt file and imported it into a
new app. Ready It worked! Done
Thks Guys

Fábio Vitorino



Em sex., 5 de nov. de 2021 às 04:44, Andrew Kingston <
***@***.***> escreveu:

**Comment by cverdes** [comment]
Sorry for the delay in my response, I just got home from work.

I just logged in and the problem did not occur. The application design appeared in normal times.

![image](https://user-images.githubusercontent.com/6440942/140580191-25cd3b65-0447-4e78-880c-fc1a41454286.png)

Thank you
