### ISSUE TITLE
Filter definition lacks the join option everywhere except in the view screen.

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3267]
**Describe the feature request**
The filter definition should be the same everywhere.

There are now two different filters: in view and everywhere else.

The _only_ difference is that, in the view screen, the filter definition offers the option of joining expressions with "OR" and "AND", where in all the other cases you're forced into the implicit "AND" join.

**Screenshots**
- filter definition in the data view screen:
![imagem](https://user-images.githubusercontent.com/67311/140616318-d3a8e18d-6214-4559-ba86-7a8548883efa.png)
- filter definition everywhere else in Budibase
![imagem](https://user-images.githubusercontent.com/67311/140616366-85de2783-baf0-4207-afac-25a77ccd20b5.png)

**Comment by melohagan** [comment]
Match all / match some filtering has been added. Closing!

<img width="466" alt="Screenshot 2022-10-21 at 19 36 33" src="https://user-images.githubusercontent.com/101575380/197266278-48c374fe-74a3-4b23-a867-ea4ccb88c973.png">
