### ISSUE TITLE
View should be able to choose its columns

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3268]
**Describe the feature request**
In the present version (0.9.177) a view must always carry all the source table's fields.

There should be an option to hide a column.
In that case, the option to delete a column would no longer be needed.

This allows the creation of restricted access views, where certain fields are not to be presented (to lower access roles).

**Example : hide e-mail**

**Comment by mjashanks** [comment]
Good point, I hadn't thought of this from a security perspective before - I have noted this in here: https://github.com/Budibase/budibase/discussions/2999, and linked to this issue.
