### ISSUE TITLE
Deleting a column in a view should not delete the source table's field.

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3269]
**Describe the bug**
Deleting any column in the view also deletes the same column in the source table!

**To Reproduce**
1. Go to view
2. Delete one of the columns.
3. The view no longer has that column.
3. Go to the source table
4. The column is also removed.

**Expected behavior**
Removing any column in a view has no impact in the source table.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Firefox 94.0.1
 - Version 0.9.177

**Additional context**
Implementing #3268 would solve this issue.

**Comment by melohagan** [comment]
You can no longer delete columns from a view. https://github.com/Budibase/budibase/pull/4729
Closing.
