### ISSUE TITLE
The client can accidentally send DELETE /api/applications commands

### ISSUE THREAD

**Issue by HyperCrowd** [Budibase/budibase#3278]
**Describe the bug**

A continuation of the disaster that is happening over at [#3255](https://github.com/Budibase/budibase/discussions/3255) and #3210

**To Reproduce**
1. Change the color of a background of a layer.
2. Futz around with the mouse, click and select and just generally be weird with clicking.
3. The client will send a DELETE command to /api/applications/...

**Expected behavior**

Unstable clients are never an expectation, but clients that don't accidentally send application destruction commands would be a rational expectation.  Would you like it if your flavor of Linux randomly dispatched `rm -fr /`?

**Screenshots**

Here's the client showing the `/api/client` showing `/` is empty:

![image](https://user-images.githubusercontent.com/76200774/140658462-d4bbf81e-40f7-4c46-8ef7-d64b8ac387e4.png)

Exploring the docker logs shows 409 CONFLICTS, which means edits being done to an entity that isn't there.

That's when I found it.  The client sending the DELETE command.

```{
  "id": 43,
  "method": "DELETE",
  "url": "/api/applications/app_dev_0691eacdfeb647ca9eeca3c2379b5c07",
  "headers": {
    "host": "testthething.org:443",
    "x-real-ip": "5.5.5.5",
    "x-forwarded-for": "5.5.5.6, 5.5.5.5",
    "x-forwarded-proto": "https",
    "x-nginx-proxy": "true",
    "x-forwarded-port": "443",
    "x-budibase-app-id": "app_dev_0691eacdfeb647ca9eeca3c2379b5c07",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
    "content-type": "application/json",
    "accept": "*/*",
    "sec-gpc": "1",
    "origin": "https://testthething.org",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "https://testthething.org/builder/portal/apps",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQ786J1c19lYmYyNTNjY2VmOGU0MzA4YjVjNmJiZjFlNDZjMGVmNyIsImlhdCI6MTYzNjI3NDk0NywiZXhwIjoxNjM2MzYxMzQ3fQ.IxttfQuezT_6W2RHz794ylaTz3NDy7fcGF2vgWwxZ0Y; budibase:currentapp=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImFwcF9kZXZfMDY5MWVhY2RmZWI2NDdjYTllZWNhM2MyMzc5YjVjMDciLCJyb2xlSWQiOiJBRE1JTiIsImlhdCI6MTYzNjI3NDk2MywiZXhwIjoxNjM2MzYxMzYzfQ.HyjsY_4ts84xNvTq-J1-eOs0y1TESleZiFLcdG4GBLc",
    "x-request-id": "6e47f44b-152a-47be-91e4-96d551d6b7a4",
    "x-envoy-expected-rq-timeout-ms": "15000",
    "content-length": "0"
  },
  "remoteAddress": "5.5.5.7",
  "remotePort": 56586
}
```

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Brave
 - Version: Latest

**Additional context**

I just lost hours of work because of this.  I am FURIOUS.  How is it even possible for a client to even send a command like that without SERIOUS examination of reducers, routers, and state!? I'm utterly baffled.

I'm going to dig into the CouchDB Service and see if I can collect a previous revision somehow.

**Comment by HyperCrowd** [comment]
```
curl http://budibase:budibase@localhost:10000/db/
{"error":"unauthorized","reason":"Name or password is incorrect."}
```

Any guidance on how to get access to the CouchDB so I can get revs?  Right now, the criteria in [https://github.com/Budibase/budibase/blob/master/hosting/hosting.properties](https://github.com/Budibase/budibase/blob/master/hosting/hosting.properties) is not being respected.

**Comment by HyperCrowd** [comment]
This is now an issue

#3278

**Comment by HyperCrowd** [comment]
You can now officially call Budibase a NO CODE solution since it randomly deletes all code and work you've done. 😂

**Comment by aptkingston** [comment]
Hi @HyperCrowd. I've spent a while looking in to this. I can assure you that our code does not randomly send requests to delete applications. There is exactly one place in our entire codebase that we make a "delete app" request, and that is when you are pressing the button to confirm that you definitely want to delete your app. You're welcome to look at the source code - it's line 153 in `packages/builder/src/pages/builder/portal/apps/index.svelte`.

The logs you provided are very useful, as they show the referer as being `[domain]/builder/portal/apps`. This means that this request was sent from the apps list page and not the design page like you indicated. The apps list screen, as I just described, is indeed the only place this request can be sent from. 

Your logs would indeed contain that request if you chose to delete an app, so the presence of that deletion request in your logs is totally normal. Are there any other users on your platform that might have deleted your app?

I'd also like to check if you've tried to reproduce this issue with another app or did it only occur once? "Fuzz around with the mouse" is not exactly a specific reproduction step, so I'm struggling to understand how to reproduce this.

I'd also appreciate if you could keep your comments civil - obviously we will work with you to try and recover your app and if there is a technical issue then we will absolutely fix it with top priority, but until we've worked out what happened please don't exaggerate the situation and jump to conclusions, especially with damaging statements like some of the ones I've removed.

**Comment by HyperCrowd** [comment]
> Hi @HyperCrowd. I've spent a while looking in to this. I can assure you that our code does not randomly send requests to delete applications. There is exactly one place in our entire codebase that we make a "delete app" request, and that is when you are pressing the button to confirm that you definitely want to delete your app. You're welcome to look at the source code - it's line 153 in `packages/builder/src/pages/builder/portal/apps/index.svelte`.
> 
> The logs you provided are very useful, as they show the referer as being `[domain]/builder/portal/apps`. This means that this request was sent from the apps list page and not the design page like you indicated. The apps list screen, as I just described, is indeed the only place this request can be sent from.
> 
> Your logs would indeed contain that request if you chose to delete an app, so the presence of that deletion request in your logs is totally normal. Are there any other users on your platform that might have deleted your app?
> 
> I'd also like to check if you've tried to reproduce this issue with another app or did it only occur once? "Fuzz around with the mouse" is not exactly a specific reproduction step, so I'm struggling to understand how to reproduce this.
> 
> I'd also appreciate if you could keep your comments civil - obviously we will work with you to try and recover your app and if there is a technical issue then we will absolutely fix it with top priority, but until we've worked out what happened please don't exaggerate the situation and jump to conclusions, especially with damaging statements like some of the ones I've removed.

Greetings.  Lemme get all the details you're asking for.  In the meantime, an update about the contents of CouchDB:

https://github.com/Budibase/budibase/discussions/3255#discussioncomment-1602719

**Comment by HyperCrowd** [comment]
### Update:

You are correct.  The DELETE request did come from the apps list page, as it was a request to delete a test app that I have confused with the nature of this issue.

The update here (https://github.com/Budibase/budibase/discussions/3255#discussioncomment-1602719) shows that the data is still in the CouchDB, which means the problem of the missing layout is now much more difficult to debug.

Losing multiple hours of work is unbelievably frustrating, especially when multiple people (#3210 and #3277 and https://github.com/Budibase/budibase/discussions/3255) are reporting this exact same event over the past seven days with zero traction.  If GitHub just dropped our repos suddenly, I won't blame anyone for being anything less than a shining apex of civility.  I don't think anyone can actually use this app moving forward under the circumstances of their layouts just getting randomly deindexed/removed/uncached/etc or going on in the webserver.

My harshness of tone is from the combination of previous requests of the same issue going mostly unanswered, the unreliable possibility of hours of work simply vaporizing, and an odd implied expectation that everyone who raises an issue about self-hosting ought to be a full-stack veteran with devOps experience, and if they aren't, their concerns about **pretty serious deal-breaking user experience failures get orphaned**.  For example, all four issues state that none of us know how to scientifically reproduce the issue, so asking for clearer steps to reproduce is a classic inching towards "_problem exists at all four end users, not our end_".

Here's what basic triage of the source code reveals:

* Problems about screens getting dropped arise 7 days ago, after the release of v0.9.173, which is mostly a dependency change build between alpha2 and alpha3
* During this period, [lots and lots of changes regarding underlying data sourcing has been done to make way for SQL](https://github.com/Budibase/budibase/commit/246d08c804be28b21260ef777cde74e8662e8a88#diff-1ec131a80a93234caad1821187b87ce3824b0dc312312849a0f0c9d3b96503a4).  Not that we are using SQL, but other data stores like CouchDB appear to be touching common data source code that has been altered.
* Since the app wasn't deleted (thank god) but the endpoint call to retrieve that data aren't returning it, something tells me the last 7 days of underlying datasource overhauls and coupling logic are the culprit.

Asking to get steps to reproduce when fundamental core data source code is, and all of its coupling logic is being worked on, is kinda ridiculous.  You're better off declaring the last stable version so we can use that.

Was my tone harsh?  Yes.  Has it brought us together to form a working relationship?  Yes.

**Comment by Rory-Powell** [comment]
From what I have gathered you still have access to your app, is that correct?

If so could you attach an export of your app for debugging. 

Could you show us a screenshot of your builder when viewing the affected app

**Comment by aptkingston** [comment]
@HyperCrowd so you actually have access to your app, but you just can't find your screen? Are you sure you didn't change the access role of the screen while fuzzing around with your mouse, which would filter it out? I can see from your update the snippet:
```
...
"routing": {
    "route": "/",
    "roleId": "PUBLIC"
},
...
```
Which means you've set the access role for that screen to be public. If you change your access role filter to public, does that show your screen again? You may just have visually filtered it out.
![image](https://user-images.githubusercontent.com/9075550/140703132-788a2a5b-15f2-429e-8196-d2d33f0739f7.png)

Also, for what it's worth the other issues you've mentioned here are unrelated. #3210 and #3255 both appear to be devops related issues that have resulted in the CouchDB volume not being periststed properly and wiping, causing a hard reset. #3277, as I've already replied to, is a valid bug that results from pressing the "revert" button when you haven't published your app yet and therefore don't have a version to revert to.

**Comment by mike12345567** [comment]
Removed the reference to #3277 as this is a separate issue related to the revert button that is currently being looked at.

**Comment by renelinked** [comment]
> ```
> curl http://budibase:budibase@localhost:10000/db/
> {"error":"unauthorized","reason":"Name or password is incorrect."}
> ```
> 
> Any guidance on how to get access to the CouchDB so I can get revs? Right now, the criteria in https://github.com/Budibase/budibase/blob/master/hosting/hosting.properties is not being respected.

Here's a hint: 
https://github.com/Budibase/budibase/discussions/1915

And it should even be possible to use fauxton ... 
https://github.com/Budibase/budibase/discussions/1657
