### ISSUE TITLE
Google OAuth behind proxy

### ISSUE THREAD

**Issue by jwillmer** [Budibase/budibase#3295]
I'm using the docker-compose deployment of budibase but additionally I have a reverse proxy in front which handles certificates. Budibase is reachable via `https` and the https URL is configured as the platform URL. But when setting up Google OAuth I can't set the full Budibase return URL so that Budibase is requesting a redirect to http. Google does not like that and returns `Error 400: redirect_uri_mismatch`

![image](https://user-images.githubusercontent.com/1503577/140915850-4319a045-84b0-495c-b6f4-652754e9b0c1.png)

![image](https://user-images.githubusercontent.com/1503577/140915915-0e1dd20f-92d4-4b2a-97d8-48dc26c59c39.png)

**Comment by Rory-Powell** [comment]
@jwillmer does the url configured in google for the callback use http or https? I can't see any other reason for the http redirect, given that you have access to budibase over https. The base url you use in google should match the url you visit budibase on the web

**Comment by jwillmer** [comment]
This is the config from the Google side:
![image](https://user-images.githubusercontent.com/1503577/140957788-6a1a279f-c80b-4f53-aef1-3d10e87c5a86.png)

**Comment by jwillmer** [comment]
Fyi I have another instance with the same setup working normal on version `Current Version: 0.9.119`. The only visual difference is that I see the full callback url on the old version but not on the new.

![image](https://user-images.githubusercontent.com/1503577/140960266-2d9e10f2-16e6-4e20-abe7-e9017cbf7693.png)

**Comment by Rory-Powell** [comment]
I believe the issue is due to the url being inferred by the request from the proxy to the budibase api, which is being made over http. I will prep some work to honour the platform url when it is set, in the meantime you should be able to use http in the google config instead as a workaround

**Comment by jwillmer** [comment]
Google does not support `http` callbacks: 
![image](https://user-images.githubusercontent.com/1503577/140999425-80453efa-3977-47f2-afe2-94ede6257e4f.png)

**Comment by Rory-Powell** [comment]
@jwillmer a fix has been added to this PR: https://github.com/Budibase/budibase/pull/3354
In the meantime you will be able to override the `http` callback by editing the config in the database. 

Visit http://localhost:10000/db/_utils/#database/global-db/config_google and update the `callbackURL` field to be the full https url you wish to redirect to

![Screenshot 2021-11-12 at 13 56 18](https://user-images.githubusercontent.com/8755148/141478568-937477e3-a11c-4606-88c7-4afb5da26b7e.png)

**Comment by jwillmer** [comment]
Works perfectly! Thank you :heart:
