### ISSUE TITLE
Unable to use JS scripting in automation

### ISSUE THREAD

**Issue by colomboe** [Budibase/budibase#3296]
**Describe the bug**
Trying to add some code in a JS scripting block in the automations editor like:
```js
let test = "hello world";
```

1. If I try to edit again the code I get the text `[object Object]` instead of the original JS code;
2. If I run the automation, I get as output:
```json
{
  "success": false,
  "response": "SyntaxError: Unexpected identifier"
}
```

**To Reproduce**
1. Go to the automations editor
2. Add a new `JS Scripting` step
3. Click on `Edit code` and write `let test = "hello world";`
4. Close the pop-up
4. Click again on the `Edit code` button

**Expected behavior**
See again the same code written before

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Edge
 - Version 95

**Additional context**
I'm using the Budibase cloud instance. Not tested with self-hosting.

**Comment by mike12345567** [comment]
Thanks for the report, I've raised a PR to rectify this.

**Comment by gvlx** [comment]
Hello,

I do not see that error:

![imagem](https://user-images.githubusercontent.com/67311/141453722-20a2ccaf-3ff9-41be-9c69-867b381c182d.png)

and returning to the JS box, I see the code again:

![imagem](https://user-images.githubusercontent.com/67311/141453802-4aa4db4e-ae69-4f3a-8edb-3ea6e1958b43.png)


    OS: W10
    Browser Firefox 94.0,1
    Version 0.9.185
