### ISSUE TITLE
Data loss after deleting a single table

### ISSUE THREAD

**Issue by mattiabonzi** [Budibase/budibase#3297]
Hi, 
I'm experiencing an important issue using the free online version (not self-hosted).
I was designing my tool, and after deleting a table I've got a "Server error" (I can't remember exactly what the error said, something like "Problem with syncing with production database"), and after that I've lost all my data (the whole project, not only the single table that I've deleted, an entire week of work...).

I didn't have published my tool yet, I was just designing it at the time.
And also didn't have exported it yet (it seemed useless to me before I had finished all the work).

Visiting the cached links that i have of my tool, now i'm getting a 404 response from Budibase.

What is going on? 
How can I recover my work? 
Is there any type of support that I can contact that is not the sales dep?

**Comment by shogunpurple** [comment]
Hi @mattiabonzi,

Sorry to hear you are experiencing this issue.

I can help you debug if you send the following information to support@budibase.com.

- Your tenantId - `<tenant>.budibase.app`
- Your app ID - available in the URL of your app - `https://<your-tenant>.budibase.app/builder/app/<your-app-id>`

We'll look into it for you and see how we can help resolve it. 

Thanks!

**Comment by shogunpurple** [comment]
Also just out of curiosity, you didn't happen to hit the revert button?
<img width="60" alt="Screenshot 2021-11-09 at 16 10 28" src="https://user-images.githubusercontent.com/11256663/140950265-fb8f67d6-62b9-4418-8a3d-2b2a934bed71.png">

There's a known issue with this, that will delete an unpublished app. The fix is merged but has not been released yet.

**Comment by shogunpurple** [comment]
@mattiabonzi closing this one as it was resolved over email. It would be really good for you to let us know if you hit the revert button, just for debugging purposes.

Thanks
