### ISSUE TITLE
Accessible Components

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#33]
What do we have to do to make components accessible ?

Is it simply a matter of providing the correct props on fundamental components (divs, inputs etc), and having higher level components (e.g. "Kanban") handle it themselves ?

Accessibility is one of those features that often gets left out as "Non Essential". In future that may not even be an option: https://www.bbc.co.uk/news/technology-46894463

Budibase could excell here - this is one of those features that Budibase could make really easy to get for almost free. 

Would love to innovate in this area for the good of humankind

**Comment by marblekirby** [comment]
Might have a guy that would be able to help you on this. He has done accessibility courses and stuff in the past.
