### ISSUE TITLE
Add more design settings to field groups

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3304]
**Describe the bug**
Input fields have default values for margins, padding, label size, etc, but none of these seem to be configurable.

The form group configures the placement of the labels, but there is no option to format or hide them.

The form group is a container but has almost none of its features.
For instance, the spacing between fields is not configurable.

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Firefox 94.0.1
 - Version 0.9.177

**Comment by mjashanks** [comment]
I feel like this would be better covered by global theming (future feature), whereby we provide a list of form settings that would apply to an app or all apps.

@gvlx our goal here is to keep things simple and easy to use - so there are some tradeoffs like this that we will have to make from time to time. Sometimes we will have to give up a little bit of control, for the sake of simplicity.

Global / App Level theming will likely solve most of the issues with this, whilst keeping things simple at the component level.

**Comment by gvlx** [comment]
Hi @aptkingston and @mjashanks,

I'm, sorry to bother you **again** with my remarks (sorry) , but I still fail to see the usefulness of the field group component, which seems to have only the following exclusive features:
 - `Update form field` design function;
 - label positioning.

The remaining functionalities can be found in a normal container and don't really seem to work. 

The first feature `Update form field`, should exist in the `Form` component as `Create all fields from Schema`.
Its existence is only justified because the `Form` element does not automatically expose them from its `Schema` source into the  `Field` property of its field elements. This should be flagged as a bug?

The second feature, 'label positioning', is basically a theming design placed upon its inner field components.

I would suggest, IMHO, that once the problem of dynamically finding new/removed fields is solved, you could create a new element: a 'theming' container, which sets _default_ theming values for its inner components as proposed here #3370.

**Comment by mjashanks** [comment]
@gvlx the other important role it plays is label alignment when the labels are at the side. 

![image](https://user-images.githubusercontent.com/3524181/141760048-1c20daa8-fede-43d4-9464-36f367621260.png)
