### ISSUE TITLE
Size props in the frontend builder

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#331]
The size props in the frontend building add a px to every number which makes percentages impossible.

@Conor-Mack I know you've worked with one this before dude. 👍

**Comment by Conor-Mack** [comment]
The Input components take a suffix prop which is automatically appended to whatever value the input is given. 

If you dont give it a suffix then you should be able to add whatever you want including a percentage.

Ultimately I think we'll want to create a control that allows to the user to specify what suffix (px, em, %, etc. or none) directly in the builder

**Comment by joebudi** [comment]
Can we not remove the suffix prop and let the user decide, for now?

**Comment by Conor-Mack** [comment]
Absolutely 👌

**Comment by Conor-Mack** [comment]
@joebudi this should sort it:
https://github.com/Budibase/budibase/pull/347

**Comment by shogunpurple** [comment]
Closing - appears to be resolved.
