### ISSUE TITLE
e-mail invitation from `<tenant host>.budibase.app` points to `localhost:10000`

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3310]
**Describe the bug**
In the budibase cloud app, user onboarding using e-mail sends a link to `localhost:10000` instead of the budicloud host address `<tenant host>.budibase.app`.

**To Reproduce**
1. Go to 'bb' (upper-left icon)
2. Click on 'Manage -> Users -> Add user' or `https://<tenant host>.budibase.app/builder/portal/manage/users`
3. Choose 'Email onboarding' and provide the user's e-mail.
4. Click 'Send'
5. The user will receive an invitation e-mail with a link to `http://localhost:10000/builder/invite?code=<code>&tenantId=<tenant name>`
6. Replacing `localhost:10000` with `<tenant host>.budibase.app` works.

**Expected behavior**
The link should point to `http://<tenant host>.budibase.app/builder/invite?code=<code>&tenantId=<tenant name>`

**Comment by Rory-Powell** [comment]
Thanks @gvlx

I've tried to reproduced this but I get an email with the correct link:
<img width="639" alt="Screenshot 2021-11-10 at 11 46 34" src="https://user-images.githubusercontent.com/8755148/141107813-e18b606c-a271-421d-a972-a22784d84803.png">

To rule something out, do you have custom SMTP enabled?

**Comment by Rory-Powell** [comment]
@gvlx what is the tenant id you are using in budibase cloud? I can check to see if some global settings are being overwritten

**Comment by Rory-Powell** [comment]
I see the issue, making changes to the organization config (updating name, logo etc) is creating a config with the default value. I'll get a fix prepped

**Comment by gvlx** [comment]
Thank you.

FYI, yes, I've setup a custom SMTP for this, the GoogleApps SMTP for my organization.
