### ISSUE TITLE
Builder screen in waiting after upgrade to 0.9.185 (was 0.9.183)

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3321]
**Describe the bug**
After upgrading to 0.9.183, I cannot open the builder screen, the screen is kept dark, with the spinning arch, and it never opens the design, 

I've now reverted back to 0.9.177 and the builder works again.

**Additional context**
Maybe I'll wait for the next revision?

**Comment by shogunpurple** [comment]
@gvlx are you updating your docker images in your self hosted instance manually to point to the tags on docker hub? We have not pushed the latest version of BB out to self-hosters just yet, so generally it’s best to wait until we do before upgrading manually.

Would you be able to tell us:
- your client library version on your app
- Can you see the builder preview when you create a new app?

Thanks

**Comment by ozanyolyapar** [comment]
Hey @shogunpurple, I've the same problem with 0.9.178 now. Creating a new app works, but on existing apps "screen" view doesn't get rendered.

**Comment by gvlx** [comment]
Hi, I'm using the BudiCloud.

![imagem](https://user-images.githubusercontent.com/67311/141285087-f7a3047f-be56-41ec-bc23-7de463b3c59a.png)

**Comment by gvlx** [comment]
Attaching firefox profiling (network har file and performance json file).

![imagem](https://user-images.githubusercontent.com/67311/141285622-fd471dee-1797-4e0e-aa48-07d08fd6f73e.png)
[firefox profiling.zip](https://github.com/Budibase/budibase/files/7519843/firefox.profiling.zip)

**Comment by shogunpurple** [comment]
Thanks @gvlx! 

I've had a look into this and it seems like it's a caching issue. Please try clearing your browser cache and see if that helps. If not it could be something else, but I'm unable to recreate when the cache is cleared. We are going to add a check based on version to make sure that the cache is always refreshed when new versions are released.

Thanks!

**Comment by gvlx** [comment]
Hi, still no luck.

Testing with a private window in Chrome 95.0.4638.69 show exactly the same problem.
I removed all site data are tried again, with the same results.

- Data screen lots ok (maybe a little tad slower).
- Automate screen ok (but I have no automations in my project).
- Design screen never loads.
- Apps page ok
- User page ok
- Auth page ok
- Email page ok
- Organisation, Theming and Account ok

Tried a new approach on the Design screen:
1) filtered by Access "Admin", where I had no designs;
2) loaded ok, no issues;
3) created an empty design "from scratch"
4) same issue, nothing is shown.

Created a new app "from scratch":
1) Data ok
2) Design ok
3) Test ok

Created a new app from (freshly exported old app with problems):
- works.

So maybe just a problem with _live_ data migration?

**Comment by gvlx** [comment]
NOTE: even with this error, the published application still works fine.

QUESTION: Is the published app working with the version it had when it was published?

**Comment by gvlx** [comment]
NOTE: after reverting the version, the design screen still exhibit the same behavior.
I need to refresh the browser window to have full access to the Design view.

And no, the refresh browser operation *does not work* on the new version.

**Comment by shogunpurple** [comment]
Hi @gvlx, thank you for the detailed information. So this issue seems to only be affecting the builder preview rather than the published apps, based on what you said. I still cannot seem to recreate this in cloud, on any of our tenants, on a whole host of different versions.

> QUESTION: Is the published app working with the version it had when it was published?
Yep, it will use the version of the client library that was there when the app is published.

Looking at your app metadata, it appears that the app is still on `0.9.177` after your rollback.

Could you possibly try:
- Upgrade your app to `0.9.185` using the client upgrade modal
- Send an updated HAR file with the requests that are coming through in your browser.
- Let me know what you see in the developer console, if there's any errors or warnings

**Comment by gvlx** [comment]
Abandoned app and used the last known good backup.
