### ISSUE TITLE
Getting error on connecting Mysql data source.

### ISSUE THREAD

**Issue by aamirbinabd** [Budibase/budibase#3327]
**Error statement:**
_Error saving datasource: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Team Member' at line 1_

I am adding a DB through localhost where Mysql is running on default port 3306. Budibase is running on docker. 

This DB is working as expected on multiple applications, no such error has ever been received. 

**Screenshot**
![IMG-20211111-WA0003](https://user-images.githubusercontent.com/81005721/141261286-ac206357-91fa-4bf7-a2ad-14e9406eb19a.jpg)

**Machine info:**
Ubuntu 20.04.3 LTS
Codename: focal
60GB Disk
4GB Memory

**Comment by onofalt** [comment]
Dame issue here with Mysql and mariadb

**Comment by marco-santulli** [comment]
same issue with mysql, in fact it only works if you chose sys as the databse

**Comment by aamirbinabd** [comment]
I should add that my setup is based on MySQL and MariaDB (not just MySQL), like @onofalt has mentioned.

**Comment by shogunpurple** [comment]
What version of MySQL/MariaDB are you all using?

**Comment by marco-santulli** [comment]
I have tried various versions, I get this error on all databases excluding the sys database:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/82715690/143236619-167775c1-f61f-4889-bcee-4d8fd8a77058.png">

**Comment by marco-santulli** [comment]
I think I found the reason for my bug, if the database name has upper cases, it doesn't work... hopefully it's a simple fix adding double quotes to the budibase driver
