### ISSUE TITLE
Import sql tables overwrites changes to previous imported sql tables

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#3330]
**Describe the bug**

- I import a table from postgres
- change a field type to options
- I import more tables
- the field types on my initial table are changed back to text 

**Notes**
- Add a warning to tell the user that their schemas will be overridden when you re-import
- Add a "RESET" action that models the current behaviour
- The fetch action should perform a merge of all the tables and only update schemas that haven't been changed

**Comment by mike12345567** [comment]
I've made the default of fetching SQL tables to maintain any changes you've made to the schema, meaning it'll keep numbers you've changed to boolean and it'll keep text converted to options columns - this seems a better default/more expected, also raised in #4010.

**Comment by joebudi** [comment]
@mike12345567 Wow, I wasn't expecting this. You've made my day!
