### ISSUE TITLE
Budibase DB import/export data _only_

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3335]
**Describe the feature request**
There should be an option to import and export only the data from an App.
Or to import _only_ the data from an exported App.

When importing data into an existing application, _IF_ _only_ _data_ was changed (no changes in columns, add/removed tables or views), it would be guaranteed no bindings and calculations would be broken.

Otherwise, the import operation should warn and list all the breaking changes it was about to do.

This would allow for different development branches to coexist and ensure no data loss of the published App.

**Comment by sergey-vin** [comment]
Bumping this issue. It seems that there's an option in export now, 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/1080493/219938954-ea069037-9f17-4139-b978-fda6c9ebdb1d.png">

But it generates files of the same size ~25MB (for me) with this toggle set to On or Off, and the .tgz files containing all images / attachments.

So it seems that it doesn't work.
