### ISSUE TITLE
Automation: "Create Row" and "Update Row" input dialog should follow "Define actions" design

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3345]
**Describe the feature request**
"Create Row" and "Update Row" input dialogs do not allow binding a value to fields of certain types, for instance `Options` fields.

In the `Define actions` properties in a screen design, its value can be bound.

It should be possible to choose between both possibilities.

**Example**
This column ...
![imagem](https://user-images.githubusercontent.com/67311/141457783-c66cc516-5b7a-4ff0-a8dd-af5277543a9c.png)

... has its value hard-coded in the automation, whereas the "name" field can be bound to some previous result.
![imagem](https://user-images.githubusercontent.com/67311/141457738-91d8e3d3-705e-4981-8b71-b693dd20b23f.png)

But on the `Define actions` properties in a screen design, its value can be bound :
![imagem](https://user-images.githubusercontent.com/67311/141458040-62ddf96c-4414-4944-92d9-767d8dbd279e.png)

**Comment by gvlx** [comment]
An even better example of a mechanism for setting values is found in the `Configure conditions` setup:

![imagem](https://user-images.githubusercontent.com/67311/141648487-2bed31a2-8d5b-4aae-8671-35b2fbf5d1ad.png)

In this example, it would be to be possible to only set the fields of interest (for the project) leaving the _remaining_ on their `default` values (if defined, `empty`/`null` otherwise) or, in the case of an update, on their existing values.

The only possible action would be `set` (otherwise, the field would be removed from the list), with or without a condition, with the extra possible values `default` and `empty`/`null`.



In that case, it would be advisable to have some extra helper buttons: add all fields, remove all fields.

**Comment by melohagan** [comment]
This has been solved with the `Use bindings` dropdown:

![Screenshot 2023-06-09 at 11 52 31](https://github.com/Budibase/budibase/assets/101575380/a7a0309e-0f89-44c9-af44-8cab7ce35a53)

![Screenshot 2023-06-09 at 11 53 36](https://github.com/Budibase/budibase/assets/101575380/8299a046-07ff-4b7f-af6c-0ddd2dc8d4d7)
