### ISSUE TITLE
Design screen: "Define actions" properties for option type fields can only bound values

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3346]
**Describe the bug**
This is the opposite bug for issue #3345 .

Where in the automation screen, only the list with the possible options is available, in the "Define actions", only a bound value is possible,

**Screenshots**
See #3345 examples.

**Comment by shogunpurple** [comment]
Thanks @gvlx - closing as dupe of https://github.com/Budibase/budibase/issues/3344 which we will address soon.
