### ISSUE TITLE
Duplicated element has all bindings replaced with `Invalid binding`

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3361]
**Describe the bug**
The duplicate of an element which uses some bindings (in its value, or conditions or actions), has all its bindings replaced with `Invalid binding`.

This is odd as all references would certainly still work (the duplicated element is _always placed as the next sibling of the original_).

**To Reproduce**
1. Create an element (for instance, a paragraph) and set its value using some bindings (for a data provider or form)
2. Click on 'Duplicate'
3. The bound values in the duplicate are replaced with the text `Invalid binding`.

**Expected behavior**
No changes in the bound values.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/67311/141651970-827d7789-7687-4484-86b9-7d7673c71ae1.png) 
![imagem](https://user-images.githubusercontent.com/67311/141652008-c4d96a44-3d06-4dba-90cc-64b5fd51b7bf.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Firefox 94.0.1
 - Version 0.9.185

**Additional context**
See feature request #

**Comment by gvlx** [comment]
Hi @mjashanks,

Would you mind checking this?

This bug makes the `copy` and `duplicate` feature almost useless.
I'm forced to correct all validations, behaviors, code and references each and every time I make a copy of _any_ element.

**Comment by Mitch-Budibase** [comment]
The duplicate behaviour surrounding bindings has been fixed and tested.

However, this is not the case for copy behaviour.
Copying and pasting a component with a binding will result in the copied component containing 'Invalid binding'

@aptkingston could you take a look please?

**Comment by aptkingston** [comment]
@Mitch-Budibase yep that's correct. I was specifically addressing the "Duplicate" action because when duplicating we can guarantee that all bindings are valid. This isn't the case for copying and pasting, so we still remove the bindings for those.
