### ISSUE TITLE
Sidebar scroll should keep top elements fixed

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3366]
**Describe the bug**
The sidebar's vertical scrollbars include its top elements:

![imagem](https://user-images.githubusercontent.com/67311/141659001-b1e8d972-df98-4a5e-979d-b0f6406f23a3.png)

![imagem](https://user-images.githubusercontent.com/67311/141659008-c05bec49-505a-4464-bd01-1a9441e8b9ff.png)

**Expected behavior**
The top elements should not be scrolled:

![imagem](https://user-images.githubusercontent.com/67311/141659112-23bd8e8d-81c4-4325-a2c3-7c0961c54d04.png)
 
![imagem](https://user-images.githubusercontent.com/67311/141659147-3a4d86e2-7499-4ed9-8d8b-688b5e09cb44.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Firefox 94.0.1
 - Version 0.9.185

**Comment by shogunpurple** [comment]
Hi @gvlx - we will be doing a full redesign of the sidebar experience over the next few months. I'm going to close this one in favour of https://github.com/Budibase/budibase/issues/2159
