### ISSUE TITLE
New design element: Theming container

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3370]
**Describe the feature request**
A theming container sets _default_ theming values for its inner components, but has no impact otherwise (it does not behave like a container, it has no properties of its own, e.g. a border).

Here are few settings it could define:
- for form fields: label placement (including `none`);
- for dividers: flex properties (align, grow/strech, gaps, etc.);
- for dividers: colors;
- for box elements: margin, padding, size.

The inner elements' settings take priority over this theming container values.

It could have some extra settings:
- only apply up to _x_ levels deep
- only apply to elements of _type_ [list]

It should also have an option 'reset to defaults' which would allow the inner elements to forgo any previous theming settings from the enclosing element (think of an inner form which should not follow the theming of its enclosing divider).

Properties not set are left untouched in the inner elements.

**Comment by evtnl** [comment]
- for field groups: label, border (top, bottom, left, right)
