### ISSUE TITLE
Control Rich Text Field (textarea field) height

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3375]
**Describe the feature request**
This is similar to #3374
The height of Rich Text Field (textarea field) should be controlled by the `Height` box, but that value has no effect on the field itself, only to its bounding box:

![imagem](https://user-images.githubusercontent.com/67311/141689278-3f7c1ff5-b9b2-4c79-8d78-ba3e2a670ab7.png)

The result is the same if the setting is applied to the `Custom CSS` property:
![imagem](https://user-images.githubusercontent.com/67311/141689508-25f87d18-4b21-438c-9ff1-14d6bf6590ae.png)

This is because the setting is applied to the outside div and not to the element itself, in these two cases:
![imagem](https://user-images.githubusercontent.com/67311/141689348-fd9afcbc-237f-4c9f-b2c5-b30890b88e8a.png)

Had that value been applied to the element directly, it would have worked:
![imagem](https://user-images.githubusercontent.com/67311/141689420-1a57de0e-f875-4bed-97ef-054023feb7ac.png)
![imagem](https://user-images.githubusercontent.com/67311/141689447-32988586-8578-434e-8fab-e6aabc9d76a9.png)

**Comment by mjashanks** [comment]
Similar to this: https://github.com/Budibase/budibase/issues/2967

Suggest that 
1. We have a proper rich text component
2. Give the text input a "Multi Line" options
3. Allow multi-line to be Sizeable

**Comment by aptkingston** [comment]
I've fixed this as part of my rich text PR. Long form field components properly obey the height setting now.
