### ISSUE TITLE
Table creation column ordering

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#3408]
### Discussed in https://github.com/Budibase/budibase/discussions/3097

<div type='discussions-op-text'>

<sup>Originally posted by **tluyben** October 20, 2021</sup>
I am just recently trying some things out with Budibase and I was wondering, when I create a table in the Data view, the fields jump to the end after you edit them; I know I can order them in the Design view, but you want consistent ordering in the Data view as well. Is there no way to leave them ordered as I put them in drag/drop/change some metafield 'ordering' ? 

  </div>
  
**COS**
- Table columns in data UI are draggable and can be rearranged
- This stores a `sortingOrder` key on the field in the schema in the database
- If no `sortingOrder` applied, sort columns alphabetically to prevent them moving after editing

**Comment by gvlx** [comment]
another suggestion: #3290

**Comment by adamjdavies** [comment]
Would be great to have this!

**Comment by melohagan** [comment]
Now possible with the Grid view!
