### ISSUE TITLE
New column type: "User"

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3420]
Might it be possible to create a new column of type "User", which could be applicable to Internal and SQL databases?

This would allow us to do user assignment on SQL databases. The underlying type in SQL would be `text` / `char()` and store the user `_id`.

I think that budibase apps already have a list of all users stored client-side - if so, it would not cause an extra db lookup/join.

**Comment by melohagan** [comment]
Done! https://docs.budibase.com/docs/users-1
