### ISSUE TITLE
Adding users in the portal don't grant them access to apps

### ISSUE THREAD

**Issue by hendrikjap** [Budibase/budibase#3448]
**Describe the bug**
Adding users in the portal don't grant them access to existing apps even though I grant them admin and development access.

**Expected behavior**
It should be automatically sync to existing app users table

**Desktop (please complete the following information):**
 - Version 0.9.187

**Comment by Karatalatay** [comment]
Neden ? Ben bir hata yaptığımı düşünmüyorum Hakım olanlar ? Çabam görülmüyormu.? Programlara ama Çoğu yerde Engelleme Ben naptım Arkadaşıma gittim bu sorun ;))() Ki kimsenin işinde Karışmıyorum? Evet 👍 biraz ya sağ-sol yapmayım şurada yardıma. İhtiyacı olan insanlara Yardımcı olacağım. Sizin gözetiminizde ?

**Comment by Rory-Powell** [comment]
Thanks for reporting this @ely2727 . 
The issue stems from how we are currently determining the list of apps to sync the new user to, which at the minute only considers apps that have a published counterpart. In the mean time if you publish your app you should see those new users come across and we'll get a fix in soon

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/7269
