### ISSUE TITLE
Customisable relation field display text

### ISSUE THREAD

**Issue by crudyrudy** [Budibase/budibase#3451]
Example CRM: You want to link the record of a person. The table "Person" contains the following fields:
surname, firstname, title, salutation
You have selected "surname" as the table display column in your database model.
In your database there are 12 persons with the surname "Miller".
If the relation field shows "Miller" 12 times when linking, you are lost. 
Suggestion for improvement:
**Provide an additional field for entering a formula (mustache or javascript) in the field definition when "table display column" is selected.** 
concat(lastname, ", ",title," "firstname);
displays "Miller, Dr. Peter" as distinctive select field option

BTW: A "unique" validation option for this display field would also be very comfortable!

**Comment by shogunpurple** [comment]
Hi @crudyrudy - this should be possible already by using a formula. Set up a formula field in your table:


<img width="1106" alt="Screenshot 2021-12-17 at 14 14 59" src="https://user-images.githubusercontent.com/11256663/146550036-1a50975f-68a4-4dc5-93a8-e827b5d0c3d4.png">

You can then make the formula column your primary display column, and it will be available in your dropdowns.

<img width="407" alt="Screenshot 2021-12-17 at 14 15 15" src="https://user-images.githubusercontent.com/11256663/146550072-766e3153-78df-4cd0-91e9-ee0c9556acd3.png">


<img width="705" alt="Screenshot 2021-12-17 at 14 15 54" src="https://user-images.githubusercontent.com/11256663/146550159-aa37d3c8-0445-422b-b7d0-08c59ea9a8c1.png">


Hope this helps!
