### ISSUE TITLE
Allow to change title and icon in browser

### ISSUE THREAD

**Issue by micebrain** [Budibase/budibase#3463]
**Describe the feature request**
While the app portal page can display the logo and org name, the browser always show the Budibase favicon and the html title to Budibase.
Please allow the <title> tag and favicon to changeable to use the org branding.

**Comment by burnoutberni** [comment]
This would actually be quite cool!

**Comment by burnoutberni** [comment]
Oh, just saw that this will probably be ready soon. Exciting! #4137

**Comment by Rory-Powell** [comment]
Hey @burnoutberni, the features in that PR are for configuring the application url path only, we'll look at this one separately

**Comment by burnoutberni** [comment]
Apologies, you're right. For my usecase, your PR is actually already sufficient, I just wanna have an app/HTML title that is different from the URL :)

**Comment by hmmhmmhm** [comment]
<img width="155" alt="스크린샷 2022-04-04 오전 11 55 42" src="https://user-images.githubusercontent.com/38493722/161466459-907ad6f0-97b3-4036-9481-0951dda0c36e.png">
i really hope this feature

**Comment by ajaym94** [comment]
Reopening this thread.

**Comment by alexvaut** [comment]
+1

**Comment by federicoinzirillo** [comment]
I tried putting this code in [App.Svelte](https://github.com/Budibase/budibase/blob/develop/packages/builder/src/App.svelte) 
It works, but when I reload the page, it shows "Budibase" in the browser title for a second.
MyOrg -> Budibase -> MyOrg

```
<svelte:head>
  <title>{$organisation.company}</title>
  <link rel="icon" href={$organisation.logoUrl} />
</svelte:head>
```

**Comment by mike12345567** [comment]
Implemented as part of: https://docs.budibase.com/docs/branding
