### ISSUE TITLE
Budicloud: Can't export App - "Network Error"

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3470]
**Describe the bug**
App export stops when it reaches 2MB, retrying gets a little bit farther.
It always ends with "Network Error".

The last export (two days ago) had almost 7MB.

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Firefox 94.0.1, Chrome 96.0.4664.45, Edge 96.0.1054.29
 - Version 0.9.187

**Comment by gvlx** [comment]
I've managed to export now.

Could it be a timeout issue? On my browser(s)? On your server or proxy?

Before I was reaching 200MB/s
Now I have close to 500MB/s.

**Comment by mike12345567** [comment]
Hi @gvlx - this is very likely a timeout issue, I'd expect you're probably getting a 503 back from the export - we will need to look into this, we've had issues with this before as app export size grows.

**Comment by gvlx** [comment]
Issue is still present.

If the export is not done in under 30s, it will fail.

I must be in a connection with over 500 MBps (4Gbps) to be able to export the complete app.

**Comment by gvlx** [comment]
Hi @mike12345567 ,

No, it actually ends with a "200 OK" status after ~16000ms.

**Comment by mike12345567** [comment]
Hi @gvlx - when it ends with 200 OK, does the export still fail?

**Comment by gvlx** [comment]
Yes. the 200 status is what is shown the network pane in Developer Tools, in the browser.
Tested on Chrome and Firefox.

**Comment by gvlx** [comment]
Problem continues.
Not a problem with my connections, I've just downloaded the full JDK from RedHat in a few seconds.

**Comment by gvlx** [comment]
@mike12345567 @mjashanks  no export has been possible since the 25rd of November.

Download always fails after 16s.

Anything smaller, which can be download in less than16s, will pass.

**Comment by shogunpurple** [comment]
Hey @gvlx - this appears to be a problem with a 15s timeout on our reverse proxy on our cloud platform. I've removed the timeout for app exports and deployed it to cloud. Could you try again and let me know if that is resolved for you?

Thanks!

**Comment by gvlx** [comment]
Hi @shogunpurple it now works!

Thank you.
