### ISSUE TITLE
date persistence issue

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#3474]
when saving a date field from the "table detail" pre-built screen (form), having ticked off "show time", because I am only interested in dates, the saved date is from the day before

it happens with external data sources (both mysql and postgres).

**Comment by aptkingston** [comment]
Hi @marco-santulli. A few questions which would help me look into this for you:
1. Does this only happen when you uncheck "show time"?
2. Is the saved date from the day before only when you view it in your external source (like in pgAdmin directly), or does it also look incorrect when you view it in your Budibase table?
3. What timezone are you in?

**Comment by marco-santulli** [comment]
Hi,

sorry let me give you more info:
1. it happens only when I uncheck show time.  If I show time and enter an hour, then it reports it correctly.
2. it  shows the "wrong" date from inside buibase (when I return to the list view and refresh), and also from outside connecting with different db clients;
3. I am in italy, it is: UTC/GMT +1 hour

let me know if you need any help replicating or other info that might be helpful

M

**Comment by aptkingston** [comment]
Great, thanks for info 👍

**Comment by shogunpurple** [comment]
Closing in favour of https://github.com/Budibase/budibase/issues/1504
