### ISSUE TITLE
SQL - Relationships need ability to specify where to pull data

### ISSUE THREAD

**Issue by lcslouis** [Budibase/budibase#3485]
**Describe the feature request**
In 1 of my projects I have multiple tables that are lookup tables static tables that contain a selection choice.

Depending on the field I will have my static table have columns 
ID, OptionValue, OptionName

Or they are just ID, LongTitle, ShortTitle

In the case of the First option I have to create a view in mysql so that the OptionValue is used instead of the ID field. 

the realtionships settings need the ability to designate a different column Other than the ID Primary Key.

**Comment by marco-santulli** [comment]
I would like to piggyback on this enhancement for a request.  At the moment it is not possible to specify a relationship on the same table, the UI prevents you from specifying the same table as source and target.  However it is quite normal to have father-son relationship on the same object (like contractor / subcontractor relationship).

**Comment by mike12345567** [comment]
Hi @marco-santulli - this likely needs to be a separate issue as first we need to make sure Budibase internal tables are capable of it, then we can make other data sources capable.

**Comment by marco-santulli** [comment]
Hi Mike,

see what you mean, I will create a separate one, thanks

Marco
