### ISSUE TITLE
Issues with screen creation wizard

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#3487]
Spotted a couple of issues when trying the new screen creation wizard:
- Some colours are static, so some text doesn't work in dark mode
![image](https://user-images.githubusercontent.com/9075550/142994632-086144d8-fa3f-4414-b5d3-9c4b66a08523.png)
- Once you select blank, even if you unselect it you can never select autoscreens, and vice versa
- If you select blank, then unselect and try to click autoscreens (which fails as described above), you can never click anything again
- If you select an autoscreen table, then unselect it and select blank, it will fail and also cause a console error `Uncaught TypeError: table is undefined`
- You can't choose more than one autoscreen table (was this by design? I thought we could create screens for multiple tables at once)
- If you select something, then close the modal and reopen it again, the selection is still there and hasn't been cleared
- We should probably hide the users table from the list of tables. We don't really want users to be directly edited in client apps

Most of these just seem to stem from some state issues when selecting and deselecting.

**Comment by Mitch-Budibase** [comment]
I've reviewed and verified the above points with one exception:

- If you select something, then close the modal and reopen it again, the selection is still there and hasn't been cleared

This is still the case. Will this be updated?
