### ISSUE TITLE
REST Connector V2: Authentication Tab

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#3495]
When I'm configuring a REST query in external datasources, I want to be able to add the relevant Authentication headers so that I can authenticate against my API.

**COS**
- Add "Authentication" header under the new REST UI
- Add options for HTTP Basic, OAuth1, OAuth2 and Authorization Bearer Header

**Comment by mrbarletta** [comment]
I would add 

- Allow the user to define the header name, E.g, I just found activeCampaign token is sent with Api-Token instead of Bearer.
- Allow a getToken and refresToken call previous to the REST calls.
