### ISSUE TITLE
Multi Language

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#35]
We should have a strategy on how to create multi-lingual apps.

If we could make this a first class feature of budibase - and easy to implement via the builder - it would be a feature that massively increases the marketability of our user's apps. 

E.g. when creating a `label`, `h1`, `h2` etc etc - we can choose text for "fr", "en", "de" ?

Also - we should be able to easily hide this feature for apps that only need to be a single language.

This is a feature that is sometimes tricky/messy to implement and therefore often ignored.

**Comment by marblekirby** [comment]
Does this refer to the language in the builder? 
Do we need to look at globalisation options first for the builder, such datetime localiszation, placing text into resource files and selecting the appropiate culture or looking at libraries that could translate our text?

**Comment by mjashanks** [comment]
This doe nt refer to the language in the builder.... thats a different feature.

This is about easily making the apps that you build multi lingual

**Comment by shogunpurple** [comment]
Worth building this in from the beginning and wrapping our strings with it inside elements. Something like https://www.i18next.com/ is good because it's not framework specific.

**Comment by mjashanks** [comment]
Yes would really like to do this. I think the bulk of the work in this is how to make the UI for this nice on the builder...

e.g. Say we have an `h1` component inside a screen somewhere, which has a `text` property. The builder would need to allow us to set the value of `text` for different languages, which makes a simple "string" property (i.e. a text Input), a little more complex. We then also have to listen to language settings from the web request.. think it all gets quite deep
