### ISSUE TITLE
File Upload Action

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#3501]
When I'm setting up button actions inside budibase, I want to be able to upload a file to S3/MinIO using my button action.

**COS**
- Addition of "Upload File" button action
- S3 Uploader Component
- Bindings available from the upload of the file that can be used in subsequent button actions
- S3 datasource "pre-signed" support

The upload button action allows users to choose a datasource from their datasource configuration, and add a key/bucket to upload the file to. Users must also choose a "S3 Upload Component" to get the file from from a dropdown. The MinIO option specifically should be available in self host only.

The datasource needs to have a method to fetch a presigned URL using the credentials (AWS_ACCESS_KEY/AWS_SECRET_ACCESS_KEY) configured at the datasource level.

When the file is uploaded, the S3 uploader component fetches the configuration from the backend and returns the presigned URL, and the file is then uploaded directly from the users browser to the presigned URL.

Bindings should be available for subsequent button actions, such as whether the upload succeeded, such as the URL of the newly uploaded file.

**Comment by arpadgabor** [comment]
Pretty new to Budibase and uploading files to different places (e.g. Google Drive, other API's) is something that I feel is missing. In the implementation of this issue, was it considered to implement the ability to pass a file into an HTTP request? At the moment I can only see REST calls as text/json, and sending binary would be great.
