### ISSUE TITLE
REST Connector V2: Pagination Support

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#3502]
When I'm configuring and testing the new REST connector, I want to be able to add pagination support so that I can leverage server side pagination.

**COS**
- Add "Pagination" header under the REST query configuration
- Enable support for Query Parameters, Request Body and Cursor based pagination

Budibase should support them all - and have the method used automatically in data providers.

**Query Parameters**
- (Required) Select the key of your page query parameter - it will usually be “page”, but should be configurable
- (Optional) Select the page size query parameter, to tell budibase how many to fetch

**Request body**
The same configuration as above, except the values are sent in the request body, rather than as query parameters

**Cursor based pagination**
- (Required) the name of the header or response body key that you want to use as your cursor for subsequent requests
(Required) the header or request body key you want to send the cursor under

**Comment by h888t** [comment]
hello! is there any ETA on this, or any short term work around?

**Comment by Rory-Powell** [comment]
@h888t this is now live
