### ISSUE TITLE
Navigation does not scroll

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#3505]
**Describe the bug**
When using a vertical nav that has items that extend the window, the nav does not scroll

**To Reproduce**
See: 

https://user-images.githubusercontent.com/8755148/143056908-d9b537dc-785c-47e6-ba22-f4821e6f5c13.mov

**Comment by aptkingston** [comment]
You monster with that nav! Valid bug though, will get it sorted.
