### ISSUE TITLE
Having these Errors while setuping Budibase

### ISSUE THREAD

**Issue by S4nfs** [Budibase/budibase#3506]
I've tried both the methods while upsetting the budibase but no luck.

Error while installing through CLI: Already followed [https://github.com/docker/compose/issues/4189](url)
Docker-error.log
> Budibase Error
The WATCHTOWER_PORT variable is not set. Defaulting to a blank string.
The Compose file './docker-compose.yaml' is invalid because:
services.watchtower-service.ports contains an invalid type, it should be a numb>

**Comment by shogunpurple** [comment]
Hi @S4nfs - it seems like you need to update your `hosting.properties` file.

Add  `WATCHTOWER_PORT=6161` to the bottom of your `hosting.properties` file, and `budi hosting --start` again.

**Comment by S4nfs** [comment]
It's already there. I tried the other way through `$docker-compose --env-file hosting.properties up` but it stuck up with error "The database could not be created, the file already exists"


> couch-init_1          |                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"error":"file_exists","reason":"The database could not be created, the file already exists."}
> 100    95  100    95    0     0   5472      0 --:--:-- --:--:-- --:--:--  5588
> couch-init_1          | sh: fg: line 1: No current job
> couchdb-service_1     | [notice] 2021-11-24T13:10:46.250141Z couchdb@127.0.0.1 <0.315.0> 71cd39941a couchdb-service:5984 172.18.0.6 budibase PUT /_replicator 412 ok 9

**Comment by S4nfs** [comment]
It got fixed after enabling port range but now i am facing another problem and now my builder page is showing timeout error after i reboot my server.
