### ISSUE TITLE
Calculate persistent field value based on other fields of the same record

### ISSUE THREAD

**Issue by crudyrudy** [Budibase/budibase#3507]
After saving or updating a record I want to fill a field of the same record with a persistent value calculated based on other field values of the same record. I tried to achieve this with automations but with no success. Is there a way to achieve this (even if of the incorporated fields is an object (relation field)?

**Comment by aptkingston** [comment]
Hi @crudyrudy. We have a data type exactly for this! It's called `Formula`. You can enter a Handlebars expression to calculate the value for the field, based on the the other values in the row. 

Just yesterday actually, I opened a PR to allow using JavaScript to write formulas as well, which should make that even easier. You can see that here: https://github.com/Budibase/budibase/pull/3508. It should be included in our next release, which will be coming out either the end of this week or early next week.

You can also reference relationships in `Formula` fields, so yes you can also incorporate any data from relationships.

**Comment by crudyrudy** [comment]
Hi @aptkingston!
Thank you for answer. I tried this before and it works perfectly BUT: My formula field is a concat of a text field and a relation field. This works fine inside the record and shows the correct result. But I need to use this formula field as display field to set relations from another table. And in this case the content of the relation field in my formula is left out. Do you know what I try to explain? So I thought a field type that stores the result of the formula persistently would do the trick... Any other idea how to make this work?

**Comment by gvlx** [comment]
Hi @crudyrudy,

@aptkingston, I also found that interface is inconsistent in the way fields are available in several operations.

Sometimes they appear on some filters, sometimes not.
Most of the time they are available as binding values, but not always.

It would be most valuable if they could be used in almost all ways the normal fields are, except for setting values, of course, as they should always be regarded as `read-only` fields.
