### ISSUE TITLE
Request Body not being processed when using REST API (Put/Post)

### ISSUE THREAD

**Issue by developer-uhwi** [Budibase/budibase#3509]
**Describe the bug**
I have configured a data source to post to a REST api endpoint, although I have added the params correctly it sometimes fail with missing params. I have now remove all the params except one and have manually entered the test data in the field, this action works and a new item is created but the data in the field is not passed to the query.

I have check my endpoint and it says to values were received.

**EDITED**
**I have done further checks and realize that the Request Body is not being processed. The values have to be passed instead using the query string.**

**To Reproduce**
1. Go to Query Rest API
2. Click and create a query name and use POST as the function.

**Expected behavior**
A new entry should be created, but this does not happen.

**Screenshots**
<img width="698" alt="Screenshot 2021-11-23 at 2 06 55 PM" src="https://user-images.githubusercontent.com/10439242/143088581-f621a38c-2c99-4e54-86f8-90eb83bb23e8.png">
<img width="754" alt="Screenshot 2021-11-23 at 2 07 03 PM" src="https://user-images.githubusercontent.com/10439242/143088602-7933c9cd-32fc-421a-92ca-2c7fcc2dc659.png">

**Return from Browser Console**
{
  "fields": {
    "headers": {},
    "queryString": null,
    "path": "contacts",
    "requestBody": "{\n  \"full_name\": \"{{full_name}}\",\n  \"first_name\": \"{{first_name}}\",\n  \"last_name\": \"{{last_name}}\",\n  \"external_identifier\": \"{{external_identifier}}\",\n  \"record_type_id\": {{record_type_id}}\n}"
  },
  "queryVerb": "create",
  "transformer": "return data",
  "parameters": {
    "full_name": "Jon Doe",
    "first_name": "Jon",
    "last_name": "Doe",
    "external_identifier": "TL111",
    "record_type_id": "1"
  },
  "datasourceId": "datasource_1490adf186e6417ca57a8c82437d6617"
}
**Desktop (please complete the following information):**
 - OS:  macOS Monterey version 12.0.1
 - Browser  : chrome
 - Version Version: 96.0.4664.55 (Official Build) (x86_64)

**Additional context**
It seems the request body is not being sent to the API endpoint, I have checked and the endpoint indicates no data being received.

**Comment by shogunpurple** [comment]
Hi @developer-uhwi - this is indeed a bug - I just tried it.

The problem is using non-string fields in the JSON - it works when you wrap everything in strings, but other fields are not being parsed correctly and causing an error in the JSON.

We will have a fix out for this ASAP. Thanks for reporting.

**Comment by developer-uhwi** [comment]
@shogunpurple Is it only the a non-string field problem, cause I have wrapped the {{record_type_id}} in quotes and the error remains the same. 
Looking forward to this resolution will continue designing the solution.

**Comment by developer-uhwi** [comment]
@shogunpurple I have update the post, please take a look. Request body does not work. Have to pass the values by query string.

**Comment by mike12345567** [comment]
Hi @developer-uhwi, as of the last release of Budibase (January 2022) with the new REST UI these problems have been resolved.
