### ISSUE TITLE
replace UIKit

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#352]
UIKit has caused us enough pain. Lets buck it oot.

Below is a list of dependencies. In general, if you search for `uk-` , you will find all the UIKit selectors. There are also some imports `import UIKit from "uikit"`

Notification Message
Checkbox
Text Area
Modal (+ we are using classes for header, footer and body)
Margin (uk-margin - on forms)
Form Label
Input
Select
Table
Form Controls (wrapper div around Form Control)
Alert - alert box - using uk-alert-danger for a red validation message
Toggle (https://getuikit.com/docs/toggle)
Spinner (busy indicator https://getuikit.com/docs/spinner)
Dropdown (drodown menu)
Nav (just used inside a dropdown dor some reason)
Form - using stacked and horizontal
Grid
Search Input - used in a component that is no longer needed

**Comment by shogunpurple** [comment]
Bump
