### ISSUE TITLE
CTRL-Z - UNDO

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3550]
Self-explanatory

The browser already handles the one-level undo on text boxes.

What is needed is _at least_ one-level undo on screen design (delete element, change element property, duplicate/copy/paste element, etc.).

The same for the automation design.

~~This is also needed on the data level (add/remove/change tables, columns and rows), although it could depend on the data source's features (commit/rollback).~~ Ignore data section for now aren't we?

Spec: https://budibase.atlassian.net/wiki/spaces/PROD/pages/7471114/Undo

**Tech notes**
Design section should be quite nice - it's already been refactored to have a single pipeline that all screen changes go through. Intercepting those changes and generating JSON patches which we store should allow us to achieve this. We can then rollback and reapply certain patches as required. Thinking ahead to multi user collab, not only will this technique continue to work if other users have made changes, but it will also be an excellent way of how we can live updates from other users; broadcasting patches over the network rather than full screen docs.

Automation section could be much harder. It does not have that nice flow and the code is messier. Probably needs a substantial rewrite to attempt to support this. It also may not be best suited to the patch approach since the docs are flatter. I see this as using a completely different implementation to screens.

**Designs**
- Add arrows in top right of page
- If no redo/undo available, grey out the redo/undo button
![undo](https://user-images.githubusercontent.com/11256663/191763605-18a8c5f2-7c15-4ccd-b0fb-c86bbc1ff922.png)

**Comment by adamjdavies** [comment]
This is a must needed feature. I just accidentally deleted a whole section on my page that took me an hour to set-up. Hadn't pushed to production so no way of retrieving!

**Comment by mindplay-dk** [comment]
@aptkingston amazing work! 👏 time to give Budibase another try 👍
