### ISSUE TITLE
i18n : sorting does not follow locale rules

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3551]
**Describe the bug**
Sorting data does not respect locale rules, namely accented letters.

**To Reproduce**
Use this list:
```
Castelo Branco
Coimbra
Évora
Faro
Guarda
```

In Portuguese, sorting rules ignores accents, so "É" is the same as "E" and sorting the above list should maintain this order.

For instance, this can be seen in option dropdown fields:
![imagem](https://user-images.githubusercontent.com/67311/143548411-b0fc6617-a3c6-4789-8c73-ddb2dbfc5b08.png)

**Desktop (please complete the following information):**
 - OS: W10 EN, PT locale
 - Browser Firefox 94.0.1
 - Version 0.9.187

**Additional context**
You must have a way to set language and locale for App, Layout and Page.
One you have those values set, it should be straightforward to send them to npm, so the sorting libraries handle it themselves.

Maybe the PR #2543 and #2651 could help?

**Comment by zonxin** [comment]
The reason is Lucene does not support sorting by indexer with special characters.

**Comment by gvlx** [comment]
Hi @zonxin,

I couldn't find any mention of such limitation on either the lucene or couchdb docs:
- https://docs.couchdb.org/en/stable/ddocs/views/collation.html
- https://cwiki.apache.org/confluence/display/LUCENE/IndexingOtherLanguages

There's even an indication of the possibility of using a custom sorting ordering in special cases:
- https://stackoverflow.com/questions/49360528/custom-unicode-sorting-order-for-pouchdb-couchdb-index-mango-query

Could it be a problem with the couchDB configuration or the data formatting in the database itself?

Hope this helps.

Best regards,

**Comment by zonxin** [comment]
The index key can be any validate string, but sort key can not. I doubt it is come from the parser of sort option. 
The sort option is a string with the form `fieldname<type>` or `-fieldname<type>` for descending order. Maybe couchDB does not allow special cases for simplicity.

https://docs.couchdb.org/en/latest/api/ddoc/search.html#get--db-_design-ddoc-_search-index

It seems that only `a-zA-Z_.` are allowed for sort field name.
