### ISSUE TITLE
The Budibase client library could not be loaded

### ISSUE THREAD

**Issue by dhemob** [Budibase/budibase#3570]
https://github.com/Budibase/budibase/blob/c71eab23f0e7c098da073a5765980b4b96f7fa13/packages/server/src/utilities/index.js#L54

Hi Team,

Looking for support of s3 compliant storage like [oracle etc].

Uploading is working fine , that we can see the packages and manifest in bucket.

Issue is when getting the client-library from  s3 , the URL of endpoint for s3 doesn't seem valid as we are using compliant storage from oracle.

Please review code , if needed to add support for endpoint while getting the client lib from s3.

Our setup is on Kubernetes self hosted. 

![image](https://user-images.githubusercontent.com/29512880/143788885-b7b922d1-4320-4bad-96bb-cb7206f1c04e.png)

**Comment by dhemob** [comment]
@apoclyps @kevmodrome @opensas

**Comment by aptkingston** [comment]
@dhemob please do not directly tag users in an attempt to prioritise your issue. We've seen your issue and will respond in due course.

**Comment by shogunpurple** [comment]
@dhemob could you send the response from the `budibase-client.js` call in your devtools in your browser, so that we can see the error message and debug? Thanks

**Comment by dhemob** [comment]
https://domain/prod-budi-app-assets/app_default_a781207d6d7449448ea56f67211fc376/budibase-client.js?v=0.9.187

Error : 503


Uploading and deleting to s3 bucket is working fine we are using oracle oci buckets which are s3 compatible.

Only problem while reading the bucket data [Also we made these two buckets as public as well].

Problem which is oberved is it's not calling from endpoint defined for oci bucket .

K8s config for objectStorage

objectStore:
    minio: false
    browser: false
    port: 9000
    replicaCount: 1
    accessKey: "1dasdasdasd" # AWS_ACCESS_KEY if using S3 or existing minio access key
    secretKey: "sadasdad" # AWS_SECRET_ACCESS_KEY if using S3 or existing minio secret
    region: "some region" # AWS_REGION if using S3 or existing minio secret
    url: "url for oci buckets" # only change if pointing to existing minio cluster and minio: false
    #storage: 100Mi

**Comment by Bytelegion** [comment]
Hi Team, 

Facing same issue , when using External S3 , in k8s, budibase try to call minio endpoint not the s3 service end point

**Comment by Bytelegion** [comment]
2022/05/18 15:06:59 [error] 36#36: *3522 minio-service.budibase.svc.cluster.local could not be resolved (3: Host not found), client: 10.244.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "domain", referrer: "https://domain/app/test".



K8s logs.

Instead of calling minio-endpoint , it should call the s3 endpoint

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/5636
