### ISSUE TITLE
Reusable Code/Functions

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#3571]
Hi,

I think a solution to write and execute javascript functions would really help give the extra flexibility to the platform. 

I think it could be done with "simple-ish" change: you could have a page, like the "queries" one, but without the bit that executes sql /rest. Then those functions could be invoked simply form the javascript bindings or added to the data provider.

what do you think?

M

**Comment by aptkingston** [comment]
Hey @marco-santulli. Just out of curiousity, what would you like to do in these functions? Are you thinking along the lines of common utility functions that you would like to frequently reference inside the JavaScript bindings to save time and reduce duplication?

**Comment by marco-santulli** [comment]
Hi @aptkingston I am thinking of a couple of situations:
1. common functionality as you say
2. be able to reuse the existing data providers in the design phase
3. not ideal but maybe I could use those also to generate small widgets that I need by calling them in the embeds

also, it could be simpler to use compared to the javascript in the bings no?

M

**Comment by marco-santulli** [comment]
one extra thing, it is probably due to my lack of understanding though: the binding is currently executed on the server side or client side? I am asking because if the binding is executed on the server side, and could make synchronous calls, it could be a way to also implement calls to (synchronous) API's with secrets staying on the server side.

**Comment by marco-santulli** [comment]
a function like this would also pick up on the FaaS theme :)

**Comment by Simoon-F** [comment]
Is there any result？I need it！

**Comment by melohagan** [comment]
To add to this issue, a similar problem arises when you want to re-use action sets. Ideally this feature would support that as well.
Possibly actions could also be written as code, which would solve for the problem of complex conditional action branches.

**Comment by rroblik** [comment]
Hi
Go to BB or not that is my current question !

This is to my mind a basic feature to prevent custom code duplication. That is tagged "2022 roadmap"... we are soon in 2024🤪

Is that feature will be really in a real roadmap soon ?

thanks

**Comment by CDIT-BE** [comment]
Yes reusable scripts would be great.
Ideally with a way to add parameters to the script to make it more dynamic.

In my case I have form fields with a scripted default value. I want to use the same script everywhere and pass the name of the field to the script.

**Comment by badrc** [comment]
interested as well, to avoid writing same JS function multiple times

**Comment by ecmonsen** [comment]
I would also like to have reusable JS functions available to my Actions.

**Comment by ConorWebb96** [comment]
I believe this has been solved with [snippets](https://docs.budibase.com/docs/snippets)
