### ISSUE TITLE
REST Connector V2: Query Import

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#3580]
When I'm using the new REST connector, I want to be able to import queries into a new or existing collection

COS

Import queries from 
- URL
- File
- Raw Test

The formats that can be imported
- Swagger 2.0
- ~OpenAPI 3.0~
- cURL

**Comment by itishermann** [comment]
any updates on this ?

**Comment by shogunpurple** [comment]
Hi @itishermann 

This is complete. It will be released along with the all new REST connector in the December release in a few weeks.

**Comment by Rory-Powell** [comment]
@itishermann we added support for curl and openapi 2.0 (swagger) in this pr https://github.com/Budibase/budibase/pull/3644
If you're looking to contribute then adding openapi 3.0 support that would be fantastic! It should be pretty similar to the 2.0 implementation here: 
https://github.com/Budibase/budibase/blob/develop/packages/server/src/api/controllers/query/import/sources/openapi2.ts
https://github.com/Budibase/budibase/blob/develop/packages/server/src/api/controllers/query/import/sources/tests/openapi2/openapi2.spec.js
