### ISSUE TITLE
Use presigned URLs for attachments

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#3582]
**COS**
https://docs.google.com/document/d/1JTLY7t-TiYybW9tXjB-BZDHbn96sYFWlAJg_E41J2Rk/edit#

**Comment by marco-santulli** [comment]
hi @shogunpurple how is this feature supposed to work?

**Comment by shogunpurple** [comment]
@marco-santulli we will use presigned URLs for budibase attachments against s3/MinIO so that they are only accessible by the users with the correct access levels.

**Comment by marco-santulli** [comment]
@shogunpurple what do you mean with "pre-signed"? is this a "time-boxed" token? I think the ideal would be if the attachment is fetched through budibase that checks if the URL cookie has an authenticated token no?

M

**Comment by marco-santulli** [comment]
bump

**Comment by melohagan** [comment]
Another related discussion here: https://github.com/Budibase/budibase/discussions/5624

**Comment by Bytelegion** [comment]
Hi @shogunpurple , is this resolved ? or still in waiting queue.

**Comment by aderici** [comment]
This seems to be an important one!
