### ISSUE TITLE
User Settings UI

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#359]
The settings UI will take the form of a modal and will be activated by an icon on the primary navigation panel within the builder.

Mockup below:
https://xd.adobe.com/view/9299ecce-72da-4fce-6bca-dc5532db68b5-e4a8/

**Comment by shogunpurple** [comment]
@kevmodrome I think we will need something to store a users Sendgrid API key for against the user settings for beta. Otherwise, we won't be able to use email
