### ISSUE TITLE
INT data type in MySQL not recognized as valid for options picker

### ISSUE THREAD

**Issue by lcslouis** [Budibase/budibase#3603]
**Describe the bug**
Options Picker doesn't recognize INT as valid data type. 

**To Reproduce**
Add new option picker field varchar fields are the only choice. 

**Expected behavior**
Single Integer value for a single select option. 

Option picker should have single select mode.  

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by melohagan** [comment]
Docs: 

 - https://docs.budibase.com/docs/option-picker
 - https://docs.budibase.com/docs/text
