### ISSUE TITLE
Relationships picker not choosing value

### ISSUE THREAD

**Issue by lcslouis** [Budibase/budibase#3604]
**Describe the bug**
Using mysql have a INT field on the table a relationship between it another table with the displayed name updated and shown. When adding new record the value isn't saved probably because the field is an INT. 

So the relationship picker need the ability to specify the selected value when adding a new record or row to a form that uses it. 

**To Reproduce**
Use MySQL Have a table with ID INT 
A second table that uses the first table as a lookup table. Add a relationship picker to the design page test entry error will happen or the ID value of picked relationship will be blank. 

**Expected behavior**
Selected Option value be saved when selecting 1 option only.

**Comment by mike12345567** [comment]
Hi @lcslouis - I'm wondering if you could provide a bit more info here, do you have any screenshots of this in action? Would it also be possible for you to send through the relationship configuration between the two tables?
