### ISSUE TITLE
November release - block components don't work with existing apps

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3611]
I have an existing app. If I try to use a block, nothing appears. I have upgraded my app.

Block work in new apps.

They also work if if export my app and import it again.

**Notes**
- Check that updated/new components still work in old apps

**Comment by aptkingston** [comment]
They shouldn't be listed for apps with an older version of the client library. If Budibase can't find a component definition, it shouldn't list the component as available to insert. You're obviously seeing the blocks listed whenever you're on a version of the client library that doesn't support them though, which is strange.

Did you upgrade your existing app, or is it still on a previous client library version?

**Comment by mjashanks** [comment]
Yes - i upgraded first. I was then able to add the block.

The Block appeared in the component tree, but not in the preview.

**Comment by aptkingston** [comment]
That sounds like it's the client library caching again, which I thought we had solved. Try in an incognito window, or after a ctrl+f5 hard refresh. Basically I think it's updating correctly but the iframe is not pulling in the new client library after updating.

**Comment by aptkingston** [comment]
I'm very certain this will have been caused by the S3 caching policy which we recently rectified. Going to consider this fixed because hopefully we'll never get any caching issues again.
