### ISSUE TITLE
Debug Logs Mode

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#3625]
**Original issue**
Hi,

I have a table in postgres, with 253 rows.  When I look at it inside BB where you define the data source, I only see one row. When I try to show the list of rows in the designer I also see a single row.
If I build a custom query with  SELECT * from table; I see all rows.

I can't see anyting interesting inthe log, is there a way to turn on tracing / debugging?

M

**COS**
- Have a way to turn on full debug tracing for SQL queries, CouchDB and more with an environment variable
- Add some debug logging events to the system

**Comment by mike12345567** [comment]
Hi @marco-santulli - can check that all of your tables have a primary key defined for them?

Which version of Budibase did you try this in? If not the latest, could you update and try re-fetching your tables and see if any errors pop up?

It none of this provides any fixes/more errors could you provide a rough SQL definition of the table to test and see if we can replicate?

**Comment by marco-santulli** [comment]
> 



> Hi @marco-santulli - can check that all of your tables have a primary key defined for them?
> 
> Which version of Budibase did you try this in? If not the latest, could you update and try re-fetching your tables and see if any errors pop up?
> 
> If none of this provides any fixes/more errors could you provide a rough SQL definition of the table to test and see if we can replicate?

Hi Mike,

you are the man!!! it was a missing primary key.  One question though: maybe I could have solved it myself if I had a way to increase log level or something like that and could see the SQL request / response.  Is there a way to increase debugging level somehow in BB?

thx

Marco

**Comment by mike12345567** [comment]
Hi @marco-santulli good to have solved it!

Right now there isn't a way to see logs around this that would have made the problem particularly clear, however with this particular issue we have started to add better error checking. With the latest version it won't fetch tables that don't have primary keys and it will show an error explaining why it didn't fetch said tables in the builder.

**Comment by marco-santulli** [comment]
> Hi @marco-santulli good to have solved it!
> 
> Right now there isn't a way to see logs around this that would have made the problem particularly clear, however with this particular issue we have started to add better error checking. With the latest version it won't fetch tables that don't have primary keys and it will show an error explaining why it didn't fetch said tables in the builder.

hi mike, you think there is no way to turn on logging in the layer that makes the SQL calls to show outgoing SQL and returned info?  that would help debug, thank you for the help in any case!

**Comment by shogunpurple** [comment]
I'm going to update this issue to reflect that exact need - a debug mode that can be enabled easily in self-host. We do have some various log level env variables but nothing that provides a full debug experience. It would be nice to just run with an environment variable that gets applied to all the containers.

**Comment by mike12345567** [comment]
The SQL that budibase generates is very, very complicated, due to the wide range of applications that it has to support - it could be possible to add a flag that outputs these when they are being built, but I think it might add more confusion than it detracts! However, we will have a think about it and see if there is something that could be done here to increase logging in general around these sort of issues.

**Comment by Rory-Powell** [comment]
I would actually love to see a flag for printing sql to be executed, rails does this by default in development and it's super handy

**Comment by marco-santulli** [comment]
> 

Hi Mike,

you are right, the SQL is not ideal, but I think having that output and the returned results would help people debugging autonomously, at least for the easy cases like mine here, thx

M

**Comment by marco-santulli** [comment]
bump

**Comment by mike12345567** [comment]
This is now possible with the `SQL_LOGGING_ENABLE` environment variable which can be set on app services/single images.
https://docs.budibase.com/docs/hosting-settings
