### ISSUE TITLE
Card block - Button

### ISSUE THREAD

**Issue by twilson9034** [Budibase/budibase#3629]
Using the button in the card block to define action of update state does not provide a bindable value.

**Comment by aptkingston** [comment]
Hi @twilson9034. I see what you mean - if you set a state variable using that button then the bindable value for that state value does not appear elsewhere to use. I'll get quick fix in for that.

In the meantime - even though the bindable value is not listed - if you enter a binding of  `{{ state.foo }}` where `foo` is the key you used in the update state action, then the binding will still actually work.

**Comment by twilson9034** [comment]
Thank you for the work around @aptkingston
