### ISSUE TITLE
AD broken after 1.0.2 update 

### ISSUE THREAD

**Issue by KernOil** [Budibase/budibase#3630]
![image](https://user-images.githubusercontent.com/80058238/144331860-93b9c370-59df-4045-8ba3-5e2588224676.png)

After updating to 1.0.2 I can no longer use active directory for login 

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application:

**Comment by Rory-Powell** [comment]
Hey @KernOil. There was a change to how the reply url is constructed in this release, can you check that your platform url is configured in the organisation page? It should match the url you visit budibase in the browser with

**Comment by KernOil** [comment]
I figured it out. the update reverted back to an old domain we no longer use. took a bit to even get back into BB but got it all taken care of.
