### ISSUE TITLE
after update to 1.0.2 apps are missing + unable to create an app error only absolute urls are supported

### ISSUE THREAD

**Issue by lcslouis** [Budibase/budibase#3632]
**Describe the bug**
Did a docker redepoly on stack service to 1.0.2 after update apps are missing but couchdb intact so only gone from designer.

unable to add new app getting error only absolute urls are supported 
**To Reproduce**
Using docker re deploy service
after launch unable to see apps or add new ones

**Expected behavior**
apps to still be there and able to create new ones

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser all browsers
 - Version 1.0.2

**Comment by mike12345567** [comment]
Hi @lcslouis - is there any logs from the `server` container? Or any console logs in the browser when you open the builder? Just to see if there is any more information we can work from to replicate your issue.

**Comment by lcslouis** [comment]
I have figured out what the issue was I had exposed the port for the couchdb and that messed up the service being able to be found I completely adjusted the network configuration and now it is working.
