### ISSUE TITLE
custom query parameters panel missing

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3634]
### Discussed in https://github.com/Budibase/budibase/discussions/3622

I have verified this. It's not possible to supply parameters to custom queries, from `Design`.

**Comment by aptkingston** [comment]
Found it, will PR soon.

**Comment by aptkingston** [comment]
Fix for this is now live, here's the panel showing again in a live test app:
![image](https://user-images.githubusercontent.com/9075550/144440732-923d9d88-66ff-47d1-8b8c-7a9f055e3b9f.png)
