### ISSUE TITLE
Unable to update parameters to any button actions

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3636]
I created a simple app. It only has a single button that does 

```
Update State
key: testState
value: SCREEN ONE
```
This works as expected.

However, when I try to update these values, it looks to save but does not. So, I

1. Change the values to 
```
Update State
key: testState
value: SCREEN TWO
```
2. Click save
3. Close the drawer and open again - looks to have saved ok
4. Refresh the builder
5. Open `Define Actions` again

RESULT: `Update State` has reverted to its original values.

https://user-images.githubusercontent.com/3524181/144411244-c3c518af-5429-4911-b25b-f13e19a69dda.mp4

**Comment by mjashanks** [comment]
Just tried the save with `Navigate To`. It seems like this applies to all actions - can't update the values, once assigned the first time.

**Comment by aptkingston** [comment]
I've already merged a PR that fixes this to master. We just need to release it 👍

**Comment by aptkingston** [comment]
In the meantime, if you change any other setting after changing your button actions then both with save. It's basically not recognising the button action change (but the state is updated), so by making another settings change that it does recognise, the updated state is then sent up.

**Comment by aptkingston** [comment]
Fix for this is live.

**Comment by mjashanks** [comment]
Nice work :)
