### ISSUE TITLE
App state not shared with modals

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3639]
When I set a state value, it is shared between screens, but not with modals.

Apparently, this used to work. If I set "Persist this value", then it works - but that has other effects which might be unwanted, depending on what we are using it for.

https://user-images.githubusercontent.com/3524181/144412924-00926b59-33c7-4b25-916c-52ed4a807627.mp4

**Comment by aptkingston** [comment]
It's a valid feature request though to make the state be shared with modals, so it would be fine to raise this as a new enhancement issue.
