### ISSUE TITLE
CSV upload feedback

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#3641]
**Describe the bug**
When I export data to CSV format, the columns do not match the data. This makes it impossible to export and upload the data to another app.

**To Reproduce**
1. Go to internal table, export data to CSV
2. Create new app, and upload your export CSV
3. System hangs at upload

**Expected behavior**
The export should export correctly and the import would work.

**Screenshots**
![CleanShot 2021-12-02 at 14 14 51](https://user-images.githubusercontent.com/49767913/144438953-829c282e-9bfb-4f45-a624-86832ab8aaa0.png)

![CleanShot 2021-12-02 at 14 09 41](https://user-images.githubusercontent.com/49767913/144438869-20a689a5-4a09-45ce-992c-0c4177ffbb59.png)

CSV:
[export (2).csv](https://github.com/Budibase/budibase/files/7642576/export.2.csv)

**Comment by aptkingston** [comment]
`Error transforming CSV to JSON for data import RangeError: Invalid time value` is the error that the server throws when trying to parse that CSV.
