### ISSUE TITLE
Configuring Navigations layout links 

### ISSUE THREAD

**Issue by twilson9034** [Budibase/budibase#3656]
When trying to set a condition to update links the builder locks up after clicking "configure links"

**Comment by aptkingston** [comment]
Hi @twilson9034. I've tried to reproduce this but everything works. Could you provide the exact steps that you took? Could you also check to see if there are any errors in the browser console. Thanks.

**Comment by aptkingston** [comment]
Have managed to reproduce this error now - thanks for reporting!
