### ISSUE TITLE
Pagination does not work with views

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3669]
**Describe the bug**
A `Data provider` should treat tables and their views as the same kind of object for pagination.

**To Reproduce**
1. Set a `Data provider` (or `Table block` or `Repeater block`) with a known table as source, with Pagination.
2. Data will be shown and a pagination element is present.
3. Change the `Data` source of same provider to a view of the original table
4. The pagination element is no longer present

**Expected behavior**
Pagination behavior should be the same with a table or a view.

**Desktop (please complete the following information):**
 - OS: Linux Fedora 35
 - Browser 94.0
 - Version 10.0.6

**Additional context**
In my case, the view is just a filtered table.

**Comment by pandel** [comment]
Will there be any progress in the near future in this regard? I have the same problem with the current budibase version...

**Comment by estelle-d** [comment]
Hello,

any news on that issue? I am having the same problem while I am using table to display "current user".table, the pagination is not working.

**Comment by jealouscloud** [comment]
I encountered this as well. It appears to be that Tables will paginate, but queries will not. I think this might be documented somewhere, but just wanted to share my experience.

**Comment by brett-interact** [comment]
This is still a problem, is there a workaround that I am missing?

**Comment by melohagan** [comment]
Views now support pagination 👍
