### ISSUE TITLE
[BUDI-7126] [Feature request] Scroll to the top as a button action

### ISSUE THREAD

**Issue by marchellodev** [Budibase/budibase#3671]
**Describe the feature request**
I have a long scrollable page, and a list of buttons at the bottom. It would be nice if I could indicate that the button was done executing by scroll to the top (or simply updating the page, and showing the top part), if one of the buttons was done doing it's click actions.

**Screenshots**

<sub>[BUDI-7126](https://linear.app/budibase/issue/BUDI-7126/[feature-request]-scroll-to-the-top-as-a-button-action)</sub>

**Comment by AngelCode-dev** [comment]
I'm having the same issue, I have a list of screens forms using the Open screen in modal option, when I navigate to the other screen It keeps the scroll from the last. Having control of the scroll would be awesome!

**Comment by melohagan** [comment]
Another use case <a href="https://github.com/Budibase/budibase/discussions/6202
">here</a> - scroll to top of form when next step is clicked. In this case focusing on the top element of the form step was also desired.
