### ISSUE TITLE
Validation for Date Pickers does not work correctly if more than one rule set

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#3675]
Hi All,

After the latest update validation & Custom validation for Date Pickers started working strange. 
I always have a Form validation as a first action on the button before it saving. 
So, if a date picker has wrong value or empty (depending on the rules set) previously, the red label with txt appeared below form component once value/date chosen or when button with Form Validation step pressed. Now red labels don't appear on date pickers. Only sometimes when the button pressed once again. Very strange...
So, the rules are still working (still unable to proceed to the next action/step until value match the rule) just no red labels shown. 
For other Form components it works okay.
Current version 1.0.6

Please help.

**Comment by sergey-dme** [comment]
![TestValidation](https://user-images.githubusercontent.com/53024832/145196188-6a5a2c35-e571-49b0-a231-92fd7fb27952.PNG)

I hope this will help with reproducing the issue. if leave only one condition (required), it works. With two like on the scree it does not work. no red labels with error txt

**Comment by sergey-dme** [comment]
v. 1.0.35 the issue is still persists.
Hey @aptkingston I know the team is working hard and I apologize for mentioning you, but could you please take a look at this?

**Comment by aptkingston** [comment]
Hey @sergey-dme. Thanks for your patience. I have a PR up to fix this 👍
