### ISSUE TITLE
Inviting User Produces 500 Error - Invite Fails.

### ISSUE THREAD

**Issue by Kuuchuu** [Budibase/budibase#3677]
**Describe the bug**
Attempting to invite a user gives a 500 status upon POST. Invite Fails. Basic onboarding still works, no status errors.

**To Reproduce**
1. Add user via Email Onboarding
2. Click "Add User"
3. Invite fails. Status 500 error in Dev console

**Expected behavior**
Sends invite

**Screenshots**
![image](https://user-images.githubusercontent.com/20036947/144724359-2e9189c1-d344-4687-a3cf-2f014d226b73.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Budibase Version: 0.9.187

**Comment by Rory-Powell** [comment]
Hey @Kuuchuu, would you be able to provide more details around the error by looking at the logs for these containers:
`bbworker`
```
 docker logs $(docker ps -qf "name=bbapps")
```
`bbapps`
```
 docker logs $(docker ps -qf "name=bbworker")
```
