### ISSUE TITLE
Table Component - Improvements

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3705]
The table component could do with a lot of improvements - many of which have been raised separately. 

I created this discussion to collect them all: https://github.com/Budibase/budibase/discussions/1913

I'm now raising this here as we should start to think about where it fits in our priorities.

**Comment by marco-santulli** [comment]
Hi guys,

did you manage to slot the table improvements into the roadmap? I am just asking, no pressure :)

M

**Comment by shogunpurple** [comment]
Closing as covered by the tasks in this iteration.

@marco-santulli - we are currently working on this. All of the suggestions in the discussion above will be addressed. You will see this changes in the February release, in a few weeks.

**Comment by marco-santulli** [comment]
> Closing as covered by the tasks in this iteration.
> 
> @marco-santulli - we are currently working on this. All of the suggestions in the discussion above will be addressed. You will see this changes in the February release, in a few weeks.

EXCELLENT!

**Comment by ggs331** [comment]
> Closing as covered by the tasks in this iteration.
> 
> @marco-santulli - we are currently working on this. All of the suggestions in the discussion above will be addressed. You will see this changes in the February release, in a few weeks.

Really a good news, looking forward to the Feb release.
