### ISSUE TITLE
Postgres connection pooling issues

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#3707]
Author: @Rory-Powell 

## Description
The postgres integration currently creates a new pool with each request due to how the integration object is constructed. 
See debugging details here: https://github.com/Budibase/budibase/pull/3301#discussion_r749229022

## COS
In single tenant environments the postgres datasources pools should be created outside the scope of the postgres integration. The number of connections to a database should not exceed the configured pool size. 

Investigate how this may be feasible in a cloud environment where potentially thousands of pools would have to exist. 

## Context

Author: @marco-santulli

Hi,

does budibase not use connection pooling to the database?  I got an error on the number of transactions in the log, I upped the number of transactions to 100 (note there is just one developer at the momento on it), and got this report from the DB:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/82715690/145048035-17f13d22-3e68-40a5-9596-e76ee262cb33.png">

to give context, I am running a simple query that selects one column from one table with two rows in it.  It getting called multiple times (every time a row in a table is rendered).  Maybe there is some setting to use connection pools?

M

**Comment by Rory-Powell** [comment]
Hi @marco-santulli, which database datasource are you using?

**Comment by marco-santulli** [comment]
> Hi @marco-santulli, which database datasource are you using?

sorry I should have mentioned that, it is postgres

**Comment by Rory-Powell** [comment]
Thanks marco. We do have pooling with our postgres integration but there is an issue at the moment which came up recently in this thread https://github.com/Budibase/budibase/pull/3301#discussion_r749229022

The bigger issue here seems to be that the connections aren't being released, I'll rename this issue towards getting fixes in for postgres on this

**Comment by marco-santulli** [comment]
> Thanks marco. We do have pooling with our postgres integration but there is an issue at the moment which came up recently in this thread [#3301 (comment)](https://github.com/Budibase/budibase/pull/3301#discussion_r749229022)
> 
> The bigger issue here seems to be that the connections aren't being released, I'll rename this issue towards getting fixes in for postgres on this

Hi Rory,

sorry I think that diagram was misleading, I apologize.. That is the total number of new connections requested.  Connections are getting released, look at this:
total number of active connections:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/82715690/145057344-b17e8f6d-5700-4b1d-b128-61337bc0b150.png">
 
total number of "succeeded" connections:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/82715690/145057445-1be20211-c26d-4d08-9c61-cd03f03d62ff.png">

**Comment by Rory-Powell** [comment]
Ah great thank you for the clarification, this narrows the fix down

**Comment by marco-santulli** [comment]
> Ah great thank you for the clarification, this narrows the fix down

no worries, and note that it happens because of the custom query, not because of the table.  So maybe the bug is in the queries area

M
