### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Grumpypjs08** [Budibase/budibase#3713]
**Describe the bug**
"You have an error in your SQL Sintax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-users' at line 1"

**To Reproduce**
1. Go to Data
2. Click on 'Sources
3. Enter Info

**Expected behavior**
Add my MySQL database as a data source

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Opra GX

**Comment by Rory-Powell** [comment]
Hey @Grumpypjs08
What does your connection config look like?
Here's an example working config:
<img width="512" alt="Screenshot 2021-12-07 at 22 47 51" src="https://user-images.githubusercontent.com/8755148/145117806-e79d1583-b1f1-48c7-bbda-840286107317.png">

Also what version of mysql are you running?

**Comment by Grumpypjs08** [comment]
My config:
![image](https://user-images.githubusercontent.com/47748360/145254073-7d043d20-f964-4bd5-9f6c-e4fe722e3222.jpeg)

MySQL Version: 8
