### ISSUE TITLE
Impossible to delete an invalid MySQL relationship

### ISSUE THREAD

**Issue by diogenesbrussels** [Budibase/budibase#3721]
**Describe the bug**
I'm unable to delete a budibase relationship from a deleted table.

**To Reproduce**
1. Connect a MySQL database
2. Fetch the tables
3. Create a relationship between 2 tables
4. Delete one of the tables
5. Try to delete the relationship (now named 'Cannot build name' and 'to undefined')

**Expected behavior**
We should be able to delete the relationship manually (preferred) or while fetching new tables delete old non-valid relationships.

**Screenshots**

**Desktop (please complete the following information):**
 - Self-hosted Docket
 - Firefox 94
 - Budibase 1.0.6

**Additional context**
Console output 
`Uncaught (in promise) TypeError: s is undefined
    B http://localhost:8080/builder/assets/index.9f18a315.js:442
    nX http://localhost:8080/builder/assets/vendor.470042a4.js:4
    nX http://localhost:8080/builder/assets/vendor.470042a4.js:4
    b http://localhost:8080/builder/assets/index.9f18a315.js:14
    jZ http://localhost:8080/builder/assets/vendor.470042a4.js:1
    cp http://localhost:8080/builder/assets/vendor.470042a4.js:1
    m http://localhost:8080/builder/assets/index.9f18a315.js:14
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/index.9f18a315.js:442
    m http://localhost:8080/builder/assets/index.9f18a315.js:442
    m http://localhost:8080/builder/assets/index.9f18a315.js:21
    m http://localhost:8080/builder/assets/index.9f18a315.js:21
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/index.9f18a315.js:442
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/index.9f18a315.js:1104
    m http://localhost:8080/builder/assets/index.9f18a315.js:21
    m http://localhost:8080/builder/assets/vendor.470042a4.js:6
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/index.9f18a315.js:21
    p http://localhost:8080/builder/assets/index.9f18a315.js:21
    Bx http://localhost:8080/builder/assets/vendor.470042a4.js:4
    Ku http://localhost:8080/builder/assets/vendor.470042a4.js:4
    promise callback*vp http://localhost:8080/builder/assets/vendor.470042a4.js:4
    Ex http://localhost:8080/builder/assets/vendor.470042a4.js:4
    ctx http://localhost:8080/builder/assets/vendor.470042a4.js:4
    N http://localhost:8080/builder/assets/index.9f18a315.js:1107
    q http://localhost:8080/builder/assets/index.9f18a315.js:1107
    v http://localhost:8080/builder/assets/index.9f18a315.js:1107
    cp http://localhost:8080/builder/assets/vendor.470042a4.js:1
    m http://localhost:8080/builder/assets/index.9f18a315.js:1107
    m http://localhost:8080/builder/assets/index.9f18a315.js:1104
    m http://localhost:8080/builder/assets/index.9f18a315.js:1107
    m http://localhost:8080/builder/assets/index.9f18a315.js:21
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/index.9f18a315.js:1104
    m http://localhost:8080/builder/assets/index.9f18a315.js:1107
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/index.9f18a315.js:1107
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    I8 http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/vendor.470042a4.js:4
    m http://localhost:8080/builder/assets/index.9f18a315.js:1108`

**Comment by legaljustus** [comment]
issue still seems to be present on postgres integration

**Comment by Seblor** [comment]
Same here, I just got that problem.
