### ISSUE TITLE
Only the first Bash/JS Action is executed

### ISSUE THREAD

**Issue by JMLX42** [Budibase/budibase#3722]
**Describe the bug**

When creating an Automation, if two (or more?) Bash Actions are chained, the second (and following?) actions are not executed or have the same output has the 1st one.

**To Reproduce**

1. Go to Automate
2. Create a new Automation
3. Select Row Created as a trigger
4. Add a Bash Action with the following code: `echo first`
5. Add 2nd a Bash Action with the following code: `echo second`

**Expected behavior**

The output of the 2nd Bash Action is :

```json
{
  "stdout": "second\n",
  "success": true
}
```

**Actual Behavior**

```json
{
  "stdout": "first\n",
  "success": true
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/998703/145244231-67c650b0-188a-4f76-848a-312c883618e3.png)

![image](https://user-images.githubusercontent.com/998703/145244292-4f7490df-4303-4b31-8cf5-176484d9698a.png)

**Desktop (please complete the following information):**

 - OS: Fedora 34
 - Browser: Firefox
 - Version: 94.0

**Comment by yeoldegrove** [comment]
Not only the "bash action" is affected...
I have a use case where I use chained "update row" and "external data connector" and only the "update row" action is executed.
