### ISSUE TITLE
Standard Component Designs

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#373]
Quite a few of the budibase components need redesigned before beta. Some of the main ones are: 

- Form
- Table
- Lists
- Cards
- Charts (https://github.com/Budibase/budibase/issues/362)

Post link to designs in here as completed.

Budibase styleguide is available in Zeplin for reference.

**Comment by mjashanks** [comment]
If i can just add some suggestions to this. 

### Individual Form Components

All form components should be bindable to a field. By "Bindable", i mean that
- when you add the control to the builder, you should be able to choose a "Field" to bind to. Examples of field are `context.name` (the name field on a record), or `state.SomeRandomValueSetByWorkflow` 
- when you change the value of the control, the value in the field should change
- when the field is loaded, the value in the control is set
- I dont think we should use the {{ context.field }} syntax, as this is really only for reading data, its not so great for writing

Some controls i think we **need**
- Input
- Select
- Datalink. This is for selecting a DataLink field.. it would be nice if this was a typeahead

give me a shoult if you dont know what i am on about.
