### ISSUE TITLE
OIDC integration - misleading password change

### ISSUE THREAD

**Issue by micebrain** [Budibase/budibase#3730]
**Describe the bug**
The option to change password and user profile is not linked to user that signed with OIDC.
This is misleading to user as the password change has no effect at all.

**To Reproduce**
1. Login with "Sign in with OIDC"
2. In portal select change password
3. Password form displayed and user change password successfully
4. User try to login again with new password (thinking that the password has been changed)

**Expected behavior**
Redirect to user profile of OIDC provider so that user can change user in the proper system.

**Comment by Rory-Powell** [comment]
Hey @micebrain. I haven't been able to reproduce using the steps you listed. I'm able to login / create a new user using oidc where the user will be created without a password. Then use the update password modal to set (create) a new budibase password and login using it. This is especially useful for admin users who can use the password as a backup

**Comment by Rory-Powell** [comment]
Can you check out your db to see if a password is being stored against the user?
Visit: http://localhost:10000/db/_utils/#database/global-db/_all_docs and find the `us_xxx` doc that corresponds to your user, in the document should be a hashed value under `password`

**Comment by micebrain** [comment]
Hi @Rory-Powell 
I think I use a different workflow. I didn't create the user in BB. In fact I don't how to create user in BB and link it to oidc.
Instead I have already existing users in Keycloak. I simply add the integration.
The user is able to login to BB with existing credentials in Keycloak. But then changed the password in BB portal (there wasn't any error). He then tried to login to BB with the new password, which didn't work - of course the password change is not in Keycloak. 
I know it sounds weird, normally you wouldn't change your google password in BB. But confused users do exists!

**Comment by micebrain** [comment]
And yes, I check in the DB, there is a "password" field.
I did a test again. I think I understand what happened. Here is the sequence of events:
1. Create a test user in Keycloak with credentials. 
2. Login with test user the first time in BB with Keycloak credentials - work as expected.
3. Change password in BB and logout
4. Login with OIDC again using updated password in BB - this produced an error, invalid password/user.
5. Login without OIDC but with same user name and updated password in BB and viola, I can login.

But for me this is an unexpected behaviour as it's a loophole for user to avoid using the required TOTP code. User can bypass completely the security requirements enforced in the external auth provider.

**Comment by Rory-Powell** [comment]
> In fact I don't how to create user in BB and link it to oidc

This part is automatic, as long as the configured identity provider allows the user to authenticate an account will be created in budibase upon first login. In future we'll be expanding this to allow for group sync so auth admins can further restrict who can log in to budibase. 

Using budibase to update the password for the identity provider is not something that will exist, it would be too specific to each provider to consider implementing. 

I see your concern about oidc users being able to have a backup password, this does potentially bypass sec requirements. I have created this issue to address: https://github.com/Budibase/budibase/issues/3754
