### ISSUE TITLE
tabbed-container component

### ISSUE THREAD

**Issue by samg666** [Budibase/budibase#3742]
**Describe the feature request**
In my project, I usually use a main table/repeater and many sub table/repeater to show related informations. For example, a customers page, I will have Customers table as main table, and Orders, Subscriptions, Invoices, Transactions as related sub table. When user select any of the customer, then sub tables will refresh based on selected customer id. 

A tabbed container will be really helpful, I tried many of other CRUD tools like Appsmith/Retool/Tooljet, all has the tabbed container component, I think it's a very common component for many other users. Although there's no predefined tabbed container component, currently I use a workaround which is use buttons, containers, app state and conditional show/hide to builded a tab-like container.  But a pre-build tabbed-container with tab click actions will save a lot time.

**Screenshots**
This is my tab-like conntainer builded with buttons, containers, app state and conditional show/hide.
![image](https://user-images.githubusercontent.com/29649651/145410729-c47d4a74-39d6-4c60-891d-a8d484e29767.png)

**Comment by SamirSaidani** [comment]
Any update on the tab component?

**Comment by Seblor** [comment]
I would also be interesting by such a feature.

**Comment by melohagan** [comment]
Hey guys,

One of our community members @poirazis has built this component and it works really well!
https://github.com/poirazis/bb-plugin-TabContainer

![birds](https://user-images.githubusercontent.com/101575380/205608991-e17aeeb9-270d-40ed-b9c3-8264ad99d5a0.gif)

It is a custom plugin, which you can find more about here: https://docs.budibase.com/docs/custom-plugin
