### ISSUE TITLE
Error when test integromat Automation on Row Created

### ISSUE THREAD

**Issue by satriowicaksn** [Budibase/budibase#3750]
**Describe the bug**
I'm try to create automation with scenario : after row created , trigger to integromat . I think my configuration in Integromat already correct. But when I try it in Budibase, i got error after test my automation scenario.

**To Reproduce**
1. Go to Automation
2. Create Automation 
3. Set Trigger from Row Created in table
4. Set Automation to Integromat
5. Set Webhook Url and Input Value
6. Click Finish and Test Automation
7. Add Test Data
8. Click View Response on Integromat Integration
9. Click Output

**Expected behavior**
Test Automation Success without error and Message show in my Integromat dashborad

**Screenshots**
Integromat Setup : 
![image](https://user-images.githubusercontent.com/90515555/145527305-9caf878a-d7c5-4be4-8c8c-2c7115117ef4.png)

Error Response : 
![image](https://user-images.githubusercontent.com/90515555/145527242-236847b5-f797-45a9-a828-bfaf90eebcd1.png)

**Desktop (please complete the following information):**
 - OS : Windows 10
 - Browser : Chrome
 - Version : 96.0.4664.93 (Official Build) (64-bit)

**Additional context**
Why this error happen? My Webhook Url already correct .
Thankyou.

**Comment by mslourens** [comment]
I just created a new Integromat account (which is now called [Make](https://www.make.com)), created a new webhook scenario (send the received data to an email address), copied the webhook url, entered it in a new BB Automation and tested it with some test data. The email got sent to me by Make.
