### ISSUE TITLE
Condition not met when extra space exists in the IF part

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3756]
### Discussed in https://github.com/Budibase/budibase/discussions/3753

<div type='discussions-op-text'>

<sup>Originally posted by **lxnunes** December 10, 2021</sup>
Morning!
I have noticed that when adding a _hide component_ condition, if an extra space exists in the IF clause (before of after), the condition is not enforced. In my case I was trying to hide a container if the user belongs to BASIC but with the extra space shown below, it did not work.

I have tested in my own environment, is this an expected behaviour?

![2021-12-10_09-22-13](https://user-images.githubusercontent.com/57442647/145552188-bb335fbb-7531-437b-9912-8c2c739c08a4.png)

cheers

</div>

**Comment by aptkingston** [comment]
It's expected in the sense that the strings are no longer the same, so it's working properly. We can strip whitespace around those values, but this same "issue" exists everywhere we take user input, and it would feel weird only stripping whitespace here. If we go down the route of removing it everywhere then that would be more consistent, but if anyone relies on whitespace at the moment (not saying they do, but they could) then it would be a breaking change, I don't really mind what way we go here though.
