### ISSUE TITLE
Dashboard mode for pages (seamless update of the content without reload of the page)

### ISSUE THREAD

**Issue by Coding-Muffin** [Budibase/budibase#3765]
It would be great if there was a mode for dashboards. Like constant update of the page, every second or so. 
I have an application that requires a table shown and a few key fields. Everything is possible to do in the current version. However, as it is a time-dependent dashboard with little user input - I wanted to make it seamlessly update the content every second, which turned out to be impossible.

**Comment by aptkingston** [comment]
Hey @Coding-Muffin. Yea we've thought about this before. I think the best solution would be a setting on a data provider (or on any of the blocks) to update periodically. Then you could just choose every X seconds or X minutes, and it will refresh. That way you could even configure different refresh intervals for different data if you wanted, and it also keeps things quite simple.

**Comment by Coding-Muffin** [comment]
That is what I was actually trying to do, seems to be the obvious place for it, but it's not there, so I decided to request this.

**Comment by shogunpurple** [comment]
Closing as dupe of https://github.com/Budibase/budibase/issues/3992
