### ISSUE TITLE
dates comparison in data provider "define filters" not working

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#3788]
I ha a postgres table with a "date" column.  It contains dates in the following format:

<img width="106" alt="image" src="https://user-images.githubusercontent.com/82715690/146096640-c8ec05c5-2335-486c-80c4-ad9e74094fa9.png">

I would like to only show the rows with that date being "before" today.  I think the comparison doesn't work. I even tried with a fixed date, and tried both "less than" that date and "more than" that date.  I only got two rows back for the "more than" and zero rows back for the "less than".  

on a side note: it would be good to have a filter where we just return true/false from a javascript function, then we can work around those bugs with javascript, what do you think?

M

**Comment by marco-santulli** [comment]
do you guys have any thoughts?

**Comment by marco-santulli** [comment]
bump

**Comment by aptkingston** [comment]
Hey Marco. The problem with a generic JS filter function is that we can't use that to do server side search - like we can't pass that on to SQL - so we would be limited to fetching some amount of rows and doing the searching in memory. That means there's no guarantee that you have all matching rows, and things like pagination would be impossible.

I'm going to see if I can recreate the issue here though to get it fixed 👍 I did a quick test and date filtering works fine for internal tables, so it is probably SQL specific.

Could you just share a picture of your filter? I'm just wondering if you're filtering against a value or a binding.

**Comment by aptkingston** [comment]
I'm afraid I'm unable to reproduice this - I've tried filtering on dates with the Postgres types `date`, `timestamp with time zone` and `timestamp without time zone` and they all work. What data type is your table using?

And again if you could please share your filter - I can only assume that there must be something wrong with the filter.

**Comment by marco-santulli** [comment]
Hi, sorry I didn't reply quickly, here it goes:

I am on a postgres DB on azure.  This is the column inside budi:
![image](https://user-images.githubusercontent.com/82715690/155307968-71bf2565-f3ab-43a1-97d6-a193ce8a6107.png)

this is the column type in the DB (dbeaver shot):
![image](https://user-images.githubusercontent.com/82715690/155308092-5b7a4c1e-5804-465d-b453-fb4fff962a26.png)

this is a query inside dbeaver:
![image](https://user-images.githubusercontent.com/82715690/155308140-cb02b9af-f3a0-4a3b-ac9c-7f7031d82c68.png)

this is an example filter, putting in the date using the date picker of dbeaver to avoid formulas:

![image](https://user-images.githubusercontent.com/82715690/155308204-224e4e93-14ba-4f06-ba0e-5c19898f6fd9.png)

in this case I get zero records back (the other filters are not filled in).

**Comment by shogunpurple** [comment]
Thanks @marco-santulli - will re-open. Thanks for the information. We are trying to clean up github issues at the moment, and just closing any that don't have clear reproduction steps or responses.

**Comment by melohagan** [comment]
This appears to be working:

![Screenshot 2022-08-19 at 15 54 51](https://user-images.githubusercontent.com/101575380/185646787-4fcaf852-0450-4778-8231-74322803ff16.png)

![Screenshot 2022-08-19 at 15 55 11](https://user-images.githubusercontent.com/101575380/185646883-ca18e561-0ece-48ff-a9f3-7cd3bfea845f.png)
