### ISSUE TITLE
Helm chart url 404

### ISSUE THREAD

**Issue by guemidiborhane** [Budibase/budibase#3801]
**Describe the bug**
When trying to install Budibase using the helm chart provided it results in a 404 error due to not finding the https://budibase.github.io/budibase/budibase-0.2.4.tgz file

**To Reproduce**
1. helm repo add budibase https://budibase.github.io/budibase/
2. helm repo update
3. helm install --create-namespace --namespace budibase budibase budibase/budibase

**Expected behavior**
It should install the chart and fetch all the its dependencies

**Screenshots**
![image](https://user-images.githubusercontent.com/4106935/146333070-f74d76c3-fccf-4e65-8b94-1f9efe96f4ab.png)

**Comment by shogunpurple** [comment]
Hi @guemidiborhane - 0.2.4 has been pushed and should be available through helm now.

Thanks for reporting!

**Comment by guemidiborhane** [comment]
Thank you for the quick reply. I can confirm it's been fixed
