### ISSUE TITLE
Attachments Support in Automations

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3817]
### Discussed in https://github.com/Budibase/budibase/discussions/3790

<div type='discussions-op-text'>

<sup>Originally posted by **bridei** December 15, 2021</sup>
Hello
In a Budibase app self hosting, i need to allow the users to import rows in an exisiting database, using a CSV import dialog. The CSV to import will have the same headers as the table to import
Is there any way to do it with budibase?

Thanks so much!</div>

**Comment by bpottle1** [comment]
I am interested in this ability as well. It would be a deciding factor of whether or not to use Budibase.

**Comment by mayanktiwaridotcom** [comment]
Any progress going on here ?

**Comment by matteoveglia** [comment]
Seems like there are quite a few tickets asking for this kind of functionality, any plans to implement or maybe give us built-in integrations with outside services like flatfile?

**Comment by melohagan** [comment]
Custom plugin was added to support this! https://github.com/mjashanks/budibase-csv-import

Docs for plugins: https://docs.budibase.com/docs/custom-plugin

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/5124
