### ISSUE TITLE
Duplicate a Screen + Improve copy and paste

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3818]
### Discussed in https://github.com/Budibase/budibase/discussions/3768

<div type='discussions-op-text'>

<sup>Originally posted by **lxnunes** December 12, 2021</sup>
Hi!

I found myself creating several versions of the same screen, sometimes to be used as a regular edit screen, other times as a modal or even as a read-only screen. 

I know most (if not all) of these aspects can be controlled using Conditions, but sometimes it would be easier to just duplicate a screen for testing - just like duplicating screen objects. 

Is there a way to achieve this?

Best</div>

- Ask the user to enter the URL of the new screen when you copy it.
- Preserve data bindings by generating new IDs on the new screen

**Comment by gvlx** [comment]
Copy/Paste/Duplicate a screen or layout would be useful.

**Comment by ggs331** [comment]
Copy/Paste/Duplicate a screen or layout currently works, but cannot keep the bindings. It will be really helpful if copy/past/duplicate can keep bindings, then we can easily to reuse the components.
