### ISSUE TITLE
World Map Component

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3819]
### Discussed in https://github.com/Budibase/budibase/discussions/2739

Spec: https://docs.google.com/document/d/19mkcCvPM14GLUFa8aFTQ6BMimKWjUU_-osvIFE6hz18/edit#heading=h.ovlu34ptwyud

When I'm working with location based data in budibase, I want to be able to use a map to display it, so that I can view my data based on geography.

**COS**
- LeafletJS Map
- All settings defined in the spec
- Event handlers for Marker added and marker clicked

**Needs Designs**
- Interaction when you click on a marker
- Interaction when adding a new marker
- Map marker popover design

**Comment by gvlx** [comment]
Hi @mjashanks , a few more suggestions for the data format:
- number: has to be a pair.
- text: could have a format `"<lat>,<long>[,<projection>]"` (projection could be set from the map value, the usual is "EPSG:3857" see https://gis.stackexchange.com/questions/44928/what-is-the-default-projection-in-leaflet)
- marker: coordinates (as above) + text + icon + tooltip + action (basically a button with the coordinate)
- multiples: as above (but you would need to implement a `repeated field` type).
- poligons: a multiple field of coordinates with the following extra options: `closed` (boolean) and the options from the marker.
