### ISSUE TITLE
Send Attachment through Automate

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3823]
### Discussed in https://github.com/Budibase/budibase/discussions/1689

<div type='discussions-op-text'>

<sup>Originally posted by **timchkor** June 10, 2021</sup>
Hello, 

It would be great if it's possible to send Attachment stored in Data table through 'Automate' - 'Send SMTP Email' and 'Outgoing Webhook'.

![image](https://user-images.githubusercontent.com/85532850/121471640-0010b000-c9fb-11eb-9e35-943363e7938b.png)

Thx!</div>

**Comment by mayanktiwaridotcom** [comment]
Is there any update on this ? Attachments or a public downloadable link to the attachment will be a good idea

**Comment by mike12345567** [comment]
Closing as dupe of https://github.com/Budibase/budibase/issues/3817
