### ISSUE TITLE
Enum type in PostgreSQL, MySQL, etc

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3826]
### Discussed in https://github.com/Budibase/budibase/discussions/3192

<div type='discussions-op-text'>

<sup>Originally posted by **micebrain** October 29, 2021</sup>
Hi,
I have several enums in my external Postgresql database. Is it possible for this fields with enum type to have dropdown selection instead of text in new record creation?
Also is it possible to configure certain field to have dropdown selection instead of plain text? E.g. dropdown with values like - Yes, Maybe, No. </div>

**Comment by tmaiaroto** [comment]
Or just empty so we can add a list in validation settings? I have a enum string field it forced to datetime and I can't seem to configure it in the data model or change it anywhere.

**Comment by mike12345567** [comment]
Hi @tmaiaroto - just had a look at this, could you provide a little more info around the types used in your enum? I created an example of this like:
```
CREATE TYPE person_job AS ENUM ('qa', 'programmer', 'designer');
CREATE TABLE People (
    PersonID SERIAL PRIMARY KEY,
    Job person_job
);
```

Budibase loaded the Job field as `Text` correctly, which I was then able to change to options and add the enumeration values (currently Budibase doesn't find custom types in your database). If you could provide a bit of an example of what your enum type looks like I can look into why it ended up as datetime, that seems like a very odd bug. If the type had been selected correctly you would be able to add in a list by changing the type to `Options` - however the base type has to be considered string based for Budibase to allow switching to this.

**Comment by melohagan** [comment]
Could be useful: https://stackoverflow.com/questions/9540681/list-postgres-enum-type
