### ISSUE TITLE
Access the SSO token and use in REST requests

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3827]
Spec: https://docs.google.com/document/d/1U_XY-A2vxRub0SMk7vU6at15GA1LSyz9XUyNL9mC3QQ/edit#

When I'm using the REST connector in budibase, I want to have access to the currently logged in users SSO token so that I can authenticate with my API.

**COS**
- Any SSO enabled orgs developer users will be able to use the SSO token in their REST Connector
- A dynamic variable named budibase_user_sso_token will be automatically injected into every instance of a REST API connector in budibase
- SSO providers that return a refresh token must be refreshed in the background to ensure they don’t expire

**Comment by brooth** [comment]
Budibase looked as a very good product until I saw this 😐 I expected to see that it refreshes the tokens automatically but turns out that I even cannot access id/access tokens to make requests.  Not good

**Comment by mjashanks** [comment]
Also, raised in https://github.com/Budibase/budibase/discussions/3934, it'd be useful to be able to bind to incoming request headers.

**Comment by jlangree** [comment]
Is this something that's being worked on? Are there any updates on when it might be ready? This feature would make a huge difference.

**Comment by jlangree** [comment]
@mjashanks Are there any updates on this?

**Comment by AsherDeVries** [comment]
This feature is absolutely mandatory for our company (and I assume for others as well). It's the only way to integrate with our existing api's in a safe and secure way. 

@mjashanks is this still on your roadmap?

**Comment by niggydotcom** [comment]
Another upvote for this please. Our REST API uses Azure SSO exclusively now so the project has stalled

**Comment by trialsin** [comment]
Same here! We need that too!

**Comment by mlomax** [comment]
Hi 
I'm not a coder but am trying to instruct the development of a budibase app.
It will be using REST APIs to connect to our datasource.
The REST APIS use a microsoft SSO token to authenticate - there is no option to use anything different.

I want to log on to BB using my microsoft SSO and use the returned token in my datasource 

@shogunpurple @mjashanks Is this development work what is scheduled for June as per #4139 

As this capability doesn't yet exist is there a current work around that people are using?

Many thanks
