### ISSUE TITLE
Document pretty URLs and show how to bookmark apps directly

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3828]
### Discussed in https://github.com/Budibase/budibase/discussions/2605

<div type='discussions-op-text'>

<sup>Originally posted by **bdevroey** September 14, 2021</sup>
It would be useful if you could select a default app. It opens immediately when a user logs in.</div>

**COS**
- Add documentation around pretty app URLs and how to configure them in the settings panel
- Add information to show that you can bookmark an app URL directly and bypass the portal
- Update https://github.com/Budibase/budibase/discussions/2605

**Comment by shogunpurple** [comment]
Docs here: https://docs.budibase.com/docs/link-directly-to-budibase-app
