### ISSUE TITLE
AD only log in

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3829]
### Discussed in https://github.com/Budibase/budibase/discussions/2609

<div type='discussions-op-text'>

<sup>Originally posted by **KernOil** September 15, 2021</sup>
Hi Team, 
I think a good addition to BB would be to have a toggle to eliminate the regular log-in when AD is activated to help not confuse people.  a bit more streamlined. 

![image](https://user-images.githubusercontent.com/80058238/133347066-4f0cb9ee-3abd-4aed-90f9-fb969c443698.png)
 </div>

**Comment by dewdeded** [comment]
Yep, good idea.

**Comment by shogunpurple** [comment]
Closing in favour of https://github.com/Budibase/budibase/issues/3829

**Comment by tvogt** [comment]
As a (new) Budibase user in an AD environment, I support this request. I would generalize it to an option to disable regular login irrespective of which external SSO provider is enabled.

**Comment by useronkel** [comment]
Stale or not, I support this request also.
As an enhancement:
Using the Default BB Login with user mail and password dialog, but add an option to populate this with AD and/or LDAP logins where bb is the frontend.
So all apps should access the bb default auth mechanism, regardless of underlying authentication to AD/LDAP

**Comment by JayP718** [comment]
agreed, I think there's similar issues out there as well. Seems like a highly requested feature.

**Comment by kasgithub8** [comment]
Needed!

**Comment by dewdeded** [comment]
+1

**Comment by useronkel** [comment]
+1
