### ISSUE TITLE
"=" character in parameter value is URI encoded

### ISSUE THREAD

**Issue by micebrain** [Budibase/budibase#3834]
It looks like parameter string that includes the character is encoded.

**To Reproduce**
As a test, I created a dummy API that will return the request body as is.
1. Create a parameter `var` with value `field1=abc,field2=12`
2. Use this parameter in the post request body
3. Server returns result as `field1&#x3D;abc,field2&#x3D;12`

**Expected behavior**
Server should get the parameter value as sent.i.e. `field1=abc,field2=12`

**Screenshots**
<img width="642" alt="Screenshot 2021-12-19 at 10 22 02" src="https://user-images.githubusercontent.com/7136209/146670372-9d27dc0e-de31-4358-a58b-b0c30b4b2eaf.png">
<img width="624" alt="Screenshot 2021-12-19 at 10 25 37" src="https://user-images.githubusercontent.com/7136209/146670378-52206262-290e-49dd-8474-bd9aedbc7378.png">

**Comment by hjh1004** [comment]
Hi. @micebrain and @shogunpurple!
I had the same experience about escape issue.
I solved by handlebars HTML escape.

If **_write tripe brace_** in requestBody, return original parameter value.

`{
  "keyword": "{{{var}}}"
}`


Reference
[https://handlebarsjs.com/guide/#html-escaping](url)

**Comment by mslourens** [comment]
Which version of BB did this happen? Because I can't reproduce it in the latest version:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1907152/156440091-6344ce38-6e05-47b0-b02a-b5f1a14f214c.png">

**Comment by mike12345567** [comment]
Hi @mslourens - thanks for checking this, we did in fact fix this issue throughout queries by replacing all bindings with triple brace, non-escaping bindings (in queries only) - will get this reviewed and closed.
