### ISSUE TITLE
no data returned from sql server 2016 tables

### ISSUE THREAD

**Issue by GiovanniBaldo** [Budibase/budibase#3839]
Ive installed budibase on premise with docker (budibase is version 1.0.25)
I'm connecting to a db in sql server. it connects correcly and has loaded all the tables definition.
Some tables are correctly opening and returns data. see for example: 
![image](https://user-images.githubusercontent.com/70816346/146781468-b8de0af2-4fbe-4634-8154-7f7218c7d414.png)
Some tables are correctly opening but do not display any rows
![image](https://user-images.githubusercontent.com/70816346/146781783-2262bfae-d033-42cc-a971-80a1320fdf2a.png)

**Comment by shogunpurple** [comment]
Hi @GiovanniBaldo - do the tables that are not returning data have a `PRIMARY KEY` set?

**Comment by GiovanniBaldo** [comment]
hi @shogunpurple, this is structure of one of the **not working tables**:

CREATE TABLE [dbo].[tbClienti](
	[IDCliente] [varchar](3) NOT NULL,
	[Cliente] [varchar](40) NOT NULL,
	[Project] [int] NULL,
	[Trasferito] [bit] NULL,
	[DataModifica] [datetime] NULL,
	[IDProfilo] [int] NULL,
	[RapportoChiuso] [bit] NOT NULL,
	[AddebTrasf] [bit] NOT NULL,
	[NonFatturare] [bit] NOT NULL,
 CONSTRAINT [aaaaatbClienti_PK] PRIMARY KEY NONCLUSTERED 
(
	[IDCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

and this is the structure of one of **working tables**:
CREATE TABLE [dbo].[tbValute](
	[IDValuta] [int] IDENTITY(1,1) NOT NULL,
	[SiglaValuta] [varchar](5) NOT NULL,
	[DescValuta] [varchar](30) NOT NULL,
	[NDecVis] [int] NOT NULL,
	[IsEuro] [bit] NOT NULL,
 CONSTRAINT [PK_tbValute] PRIMARY KEY NONCLUSTERED 
(
	[IDValuta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

At a first look I tought it can be a problem with the name of the constraint for the primary key (its a bit strange on the tbClienti table). But some working tables have the same strange name for the constraint so probably thats not the problem!

**Comment by KevMyst** [comment]
I have the same problem.  
In my opinion, budibase does not support any schema other than dbo. Tables with a different schema do not load data.

**Comment by mike12345567** [comment]
This should be resolved in the latest release of Budibase.
