### ISSUE TITLE
Export data does not follow charset encoding

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3844]
**Describe the bug**
Data export does not follow UTF-8 charset.

**To Reproduce**
1. Create a new test app.
2. Import `UTF-8` csv file [concelhos_AML.csv](https://github.com/Budibase/budibase/files/7753598/concelhos_AML.csv) to a new table.
![imagem](https://user-images.githubusercontent.com/67311/146919196-47bc9072-64f6-443e-8172-1f20a3cfa61a.png)

3. Export table data as CSV.
4. Check the new file (you'll find it was actually encoded as `ISO8859-1`)
![imagem](https://user-images.githubusercontent.com/67311/146919359-2b8740c3-1334-40af-a9ab-1df105ee5d14.png)
![imagem](https://user-images.githubusercontent.com/67311/146920373-7439296c-959d-4d8b-b0ff-26e696e0072b.png)
![imagem](https://user-images.githubusercontent.com/67311/146920460-63b74f41-dec7-4321-9c23-d887080a5fb0.png)

**Expected behavior**
The resulting export should be encoded in `UTF-8`.

**Screenshots**
it should be noted that the app clearly states that is going to transfer an UTF-8 encoded file:

![imagem](https://user-images.githubusercontent.com/67311/146920544-74db3f43-7fdf-4493-8ac9-0dd944d7b147.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Firefox 95.0.2
 - Version 1.0.25

**Comment by gvlx** [comment]
Hi, @mjashanks , @shogunpurple , any chance on reviewing this issue in the next days?

Thank you.

**Comment by xnohat** [comment]
Hi,

This issues still doesn't fix in newest version.
In my case, I cannot find correct charset encoding of csv exported file
[export (4).csv](https://github.com/Budibase/budibase/files/8547628/export.4.csv)

any update on this issue ?

**Comment by thomaskamalakis** [comment]
Would be nice to fix this!

**Comment by MSrubar** [comment]
Hi

I need exported data with correct UTF-8 encoding too. It's very important because exported data with Czech letters has damaged format.

Thanks
Marty.

**Comment by aricooperdavis** [comment]
@shodunpurple I don't think this has been completed, so it shouldn't have been closed. This is the second issue I've come across that you've inaccurately closed as completed - is there something going wrong with an automated tool that's closing these issues?

**Comment by shogunpurple** [comment]
@aricooperdavis has it not? This PR was merged which should have solved the problem. https://github.com/Budibase/budibase/pull/7146 

You could try raising a bug report and sharing your CSV - that would be helpful.

**Comment by aricooperdavis** [comment]
Ah, sorry, I hadn't spotted that merge - I'll submit a new bug report for the issue! 👍 

The other issue that has been closed without being completed is #5995

**Comment by raventechsaigon** [comment]
Will this bug ever be fix?  
Is there a work around anyone know?
