### ISSUE TITLE
Backend Builder Bugs

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#386]
- [x] 1. When I complete the create a new record form, it doesn't show in the table

- [x] 2. When adding a new field, I have to refresh for it to show in the table

- [x] The save buttons remain greyed out - could be a styling issue

- [x] 4. When creating a new record, date fields are not saving

- [x] 5. Create new record - cannot set data links field~~

- [x] 6. True/False [boolean] - when you add a boolean field, and when adding a new record, you must select the checkbox then uncheck it before proceeding. 
- [x] 7. (from mike) Routing is inconsistent with frontend. ON the frontend, each screen and component gets its own path. Models on the backend should get their own path (currently routed by instance, which is no longer relevant)
- [x] (from mike) When saving a field (whether create or update), "required" is not being saved 
https://www.loom.com/share/8dc8fbc00bb6418aafe284714b684e01
- [x]  When you create a new web app, the previous web apps table name is in the new web apps table name text box
![Screenshot 2020-07-09 at 09 18 37](https://user-images.githubusercontent.com/49767913/87015433-52cb6180-c1c5-11ea-88aa-7eac3462866d.png)

**Comment by joebudi** [comment]
- [ ] remove upload csv button

**Comment by mjashanks** [comment]
Hvae logged the remaining bugs seperately
