### ISSUE TITLE
Add "IN" and "NOT IN" conditions in data filter

### ISSUE THREAD

**Issue by micebrain** [Budibase/budibase#3863]
**Describe the feature request**
Current filter does not allow the "in" condition and for some queries it is difficult to emulate with the existing available conditions.
e.g.  in SQL a statement like `select something from table where type in ('warning', 'error')`

**Screenshots**

<img width="514" alt="Screenshot 2021-12-22 at 21 10 11" src="https://user-images.githubusercontent.com/7136209/147150406-1c8a3e53-78d9-45a5-9aed-d3d49b8e708e.png">

**Comment by melohagan** [comment]
This would be pretty handy. Same goes for Automation Conditions.
