### ISSUE TITLE
Frontend Builder Bugs

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#387]
- [x] 1. bottom-margin is overridden by margin "all sides" , same with padding (the other side specific values are not overridden)

- [x] 2. Sytles (design tab) are not being applied to the master screen (i.e. just the Root element - "Master Screen")
- [x] 3. Fonts that dont work (Windows). Inter, Open Sans, Playfair, Roboto Mono
- [x] 4. Some font weights dont work - I assume because the installed font doesnt support these weights.
- [x] 5. Typography > Font Color ... 2 color pickers appear
- [x] 6. Single Color picker has 2 coloured sliders, 2 transparency sliders & 2 Hex inputs
- [x] 7. OptionSelect menu gets clipped by its container. Should be able to break out of it.
- [x] (from mike) List Component - Has a border around it, which is impossible to remove or style
- [x] (from mike) Form - Should be able to edit (or remove) title
- [x] (from mike) Right Margin - cannot select none, 8 or 4, as it's out of the screen
- [x] (from mike) Form. All controls are text inputs.. i had. Boolean, Link and Date field. None display the relevant control - [Joe] Boolean and selects are done. Dates are not, which I think is fine for now. 
- [x] (from mike) Design panel - only one category at a time should be open - when one opens, another should close
- [x] (from mike) Screenslot - when on master screen, screenslot is displayed as "content". It looks naf.
- [x] (from mike) Working on frontend... navigate to backend (just to check a field name)... navigate back - i lost my place... its annoying
- [x] (from mike) Binding to link in a list, used the expression {{ context.Company.name }} the context does have a Company field (i checked the casing), and Company does have a "name" field
- [x] (from mike) String interpolation does not work properly... i tried to set the url of a link to /product/{{context._id}} ... it just printed "/product/{{context._id}}" 
- [x] (from mike) wheny ou click on a screen, we get `undefined` n the url. This causes an issue if we refresh
- [x] adding multiple children to a list does not behave as expected - the list should act like a single container. workaroiund is to add a Container, and then children to the container

**Comment by joebudi** [comment]
- [ ] Joe - table shows model number

**Comment by mjashanks** [comment]
@joebudi do you have any designs done for Deleting a screen ?

**Comment by joebudi** [comment]
It would be cool if it had the same edit icon and  dropdown as the components

**Comment by joebudi** [comment]
It would also require a "are you sure you want to delete this" modal

**Comment by mjashanks** [comment]
Have transferred remaining items to individual issues
