### ISSUE TITLE
improve error messages

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#3906]
Hi,

I tried to deploy an app with an automation where I must have used a chron mask that budibase doesn't like.  It is: 0 0 7 ? * * *

when I try to publish I get an "error 500 back", but looking in the log I see the real reason is in the trace, it might be good to show the trace in the error message in the web app?

Trace: { message: 'Deployment Failed: Invalid cron expression' }
    at /app/dist/api/index.js:69:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by shogunpurple** [comment]
Thanks @marco-santulli - this is something we will be looking at this month. Improved error messages, tooltips and generally more insighti nto what is happening in the builder. Is there anywhere else that you think error messaging could be improved?

**Comment by marco-santulli** [comment]
Hi Shogun,

thank you.  I can't think of one at the moment, I think messages are generally very good.  

I think the most important features lacking in BB at the moment are:
1. customizeable tables:
-- at least be able to change column names and define content type so currencies, dates etc are shown properly
-- possibility to give column name to columns added automatically when you drop a prompt or button into the table
I think in general you can find some good ideas on how to do this in appsmith.  Or be able to use repeaters, but have some sort of "grid layout" available to put data in a good looking table.
2. direct access to data from javascript.  Like you can access a data provider in a javascript binding, make access to all default data providers from js available
3. be able to map a url directly to a javascript function.

I think these three would give a very good boost to the power of the tool

thx

M

**Comment by JayP718** [comment]
bump
