### ISSUE TITLE
MS SQL Server connector not working correctly with MSSQL v2012

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3928]
### Discussed in https://github.com/Budibase/budibase/discussions/3883

```
 ERROR [1640887454758] (30 on b3d416c9bd8e): RequestError: Invalid usage of the option next in the FETCH statement.
bbapps                |     Error: RequestError: Invalid usage of the option next in the FETCH statement.
bbapps                |         at /app/dist/integrations/microsoftSqlServer.js:85:23
...
```

I believe that Knex does not support some fairly recent versions of MS SQL Server: https://github.com/knex/knex/issues/1527. Some comments in there mention that error happens with v2017. 

We need to work out
1. Which versions of SQL Server do we currently support?
2. Which versions do we intend to support?

The maintainers of Knex have made it clear that they are happy to accept contributions to support earlier versions. If we want to support these versions we should look into contributing to Knex, since it's such a great project.

**Comment by mike12345567** [comment]
Currently we test against the latest image from the Microsoft MCR (https://mcr.microsoft.com/v2/mssql/server/tags/list) - this should be MS SQL 2019. As of right now this is the only version we've tested extensively against - it would be easy enough for us to run tests against older versions and check what changes we'd need to make to support it.

Right now the big issue seems to be around pagination (`OFFSET`) in older versions, which we might be able to fix by detecting the version of MS SQL in use and recording the version against the datasource, allowing us to adjust our pagination efforts depending on version. The bigger issue here is we'd need to make a decision about what versions we want to test (and support) for MS-SQL and realistically other DBs as well.

**Comment by datdamnzotz** [comment]
Confirmed - same error on Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)
```
ERROR [1643643870316] (29 on a6305281b83f): RequestError: Invalid usage of the option next in the FETCH statement.
    Error: RequestError: Invalid usage of the option next in the FETCH statement.
        at /app/dist/integrations/microsoftSqlServer.js:85:23
```
I tried changing SQL Db compatibility modes as well (from 2012 up to 2016)
![image](https://user-images.githubusercontent.com/3913859/151826239-7d7f57b5-a14c-4783-b246-6b0b928caa12.png)

Same error

**Comment by pbjorklund** [comment]
Same with Azure Sql Server

**Comment by pbjorklund** [comment]
Still getting this error with azure sql server

```
bbapps                | ERROR [1665657962771] (29 on 2a81b9e095ca): RequestError: Invalid usage of the option next in the FETCH statement.
bbapps                |     Error: RequestError: Invalid usage of the option next in the FETCH statement.
bbapps                |         at /app/dist/integrations/microsoftSqlServer.js:85:23                                                                 bbapps                |         at Generator.throw (<anonymous>)
bbapps                |         at rejected (/app/dist/integrations/microsoftSqlServer.js:6:65)
bbapps                |         at runMicrotasks (<anonymous>)
bbapps                |         at processTicksAndRejections (internal/process/task_queues.js:95:5)                                                   bbapps                | Trace: Error: RequestError: Invalid usage of the option next in the FETCH statement.                                          bbapps                |     at /app/dist/integrations/microsoftSqlServer.js:85:23                                                                     bbapps                |     at Generator.throw (<anonymous>)                                                                                          bbapps                |     at rejected (/app/dist/integrations/microsoftSqlServer.js:6:65)
bbapps                |     at runMicrotasks (<anonymous>)
bbapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
bbapps                |   expose: true,
bbapps                |   statusCode: 400,
bbapps                |   status: 400
bbapps                | }
bbapps                |     at /app/dist/api/index.js:69:21
bbapps                |     at Generator.throw (<anonymous>)
bbapps                |     at rejected (/app/dist/api/index.js:6:65)
bbapps                |     at runMicrotasks (<anonymous>)
bbapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by pbjorklund** [comment]
Seems the image used by the mentioned docker compose installs v 1.0.46. Seems.. old? :)
