### ISSUE TITLE
Helm chart - CouchDB performance issues

### ISSUE THREAD

**Issue by felixmoldovan** [Budibase/budibase#3930]
First, what a nice find! Congrats on the work and continuous improvement!
I have spent a few days using the features on a Kubernetes deployment based on your helm chart. Budibase works but there is an impression of slowness/lag on the CouchDB. This is definitely more apparent when compared with the cli/docker-compose deployment on an identical infrastructure.
One lead is that an exposed ingress on the CouchDB service will stall on Fauxton and throw several "you are not an administrator" errors.
Again, this does not happen on the docker-compose instance where Fauxton as well as the app are snappy and responsive.

I appreciate any lead in troubleshooting this.
Also, any plans to align the helm chart with the docker-compose release?

I break the ice on this from the mobile. I am available to provide more details and logs/configs if of interest.

Thanks, Felix

**Comment by felixmoldovan** [comment]
After further poking around, the answer is /_cluster_setup -d '{"action": "finish_cluster"}'
Welcome to close or take onboard as an action to be specified in NOTES or automated.

**Comment by shogunpurple** [comment]
Hey @felixmoldovan - thanks very much for investigating this. Is this just on startup, when the couchdb instances are starting up, or does this slowness continue once everything is configured?

**Comment by felixmoldovan** [comment]
No slowness noticed after the cluster is finished. Thanks

**Comment by shogunpurple** [comment]
All good, thanks for that! I'll close this one out 👍
