### ISSUE TITLE
Ability to translate the interface

### ISSUE THREAD

**Issue by KevMyst** [Budibase/budibase#3950]
Hi, it would be nice to be able to translate the interface and to be able to select the language by the user.
You can make a table with languages and place translations for elements there, eg Page Number.

**Comment by matanAlltra** [comment]
I would love to see that feature

**Comment by neoguet** [comment]
Hi,
I 'm very interesting to this feature. I think this feature is especially useful for end users who are not always familiar with English language.
I think developers can initially have only English in the builder
Today, I can rewrite labels, buttons, column headers and other things but all built-in labels/texts are still in english.

**Comment by DarkDare** [comment]
Yes, it would be nice for a wider use. I can help translating to french.

**Comment by Keksik-tyan** [comment]
This feature is very much needed.

**Comment by oswaldB** [comment]
Guys, please us how we can help you to translate things? 

All the login related pages are in English and I need them in French as well. Where can I translate them?

**Comment by and7eh** [comment]
This would be great.! I could help with spanish translation.

**Comment by vaclaff** [comment]
I think that ability to do translation using i18n standard is very important and in fact crucial for worldwide implementation in SME segment...

Please consider adding this feature ASAP.

**Comment by tom-90** [comment]
I would love to see this feature as well, especially for the components that get shown to tne end-users. The language of the builder is not that big of a problem for us right now.

**Comment by KevMyst** [comment]
I can help translating to polish. 
Is there any possibility to translate the interface at the moment?

**Comment by pandel** [comment]
+1!
Please add a possibility to translate the end-user components. Or, at least, please give us a hint which files to translate...

**Comment by delixfe** [comment]
Same here. Builder can stay English, but we have to provide all apps / forms in 4 languages.

**Comment by vaclaff** [comment]
While it doesn't solve all the hassle, I probably managed to find a way to translate notification messages like "Row saved" or "Automation triggered". At least if you're using the self-hosted variant.

You just need to update one file:

> budibase-develop/packages/client/src/utils/buttonActions.js

Inside the file, you'll immediately notice that these notification strings are hard-coded, like this:

`notificationStore.actions.success("Row saved")`
`notificationStore.actions.success("Automation triggered")`
`notificationStore.actions.success("Query executed successfully")`

You just need to find all of these, change the strings and you're good to go.

**Comment by pandel** [comment]
Many thanks! But you are not really good to go if you need to provide multiple languages at the same time in your app... really don't understand why these strings are hard-coded...

**Comment by yarin-zhang** [comment]
I tried budibase for the first time today and had a very good experience.

The only problem for me is that the language of the user-facing interface cannot be modified... Although I can localize it by editing the content on the page.

However, places like the buttonActions alert, the prompt text in Filters, etc. can't change the languae, may cause a lot of confusion for customers.

I hope budibase will take this point of localization into account.

**Comment by airbenich** [comment]
+1

**Comment by JayP718** [comment]
Hi all, 

While it doesn't solve all the issues, Budibase has added a new action in the latest update which allows for customized alerts

**Comment by funkyferdy** [comment]
+1 For Translations. I'm playing with buddibase for some days now and so far I LOVE IT. Exactly what i need. My end users at the end, needs a German Interface...in 90% of the cases im renaming the same generated stuff. There are many generic things here.

Save = Speichern
Delete = Löschen
Edit = Bearbeiten
New = Neu

Would help allready a lot :)

As Swiss guy i have a lot of experience regarding Multi-Language, because in Switzerland eveything needs to be mutlilingual, we have usualy German, French, Italian and English interfaces by default. I dont care much about the Builder, but the generated apps would be great to be able to localise in a efficient way.

**Comment by oldwired** [comment]
I could see having a table with all the strings somewhere in the Builder/Backend. There we users can translate the strings we need to translate. You could even enforce a max length there to avoid overflows in the UI.

**Comment by shumpeiKishi** [comment]
+1. I'd like to ask a question to someone familiar with Node.js app translation. Does this require whole app architecture change or can we small start by, for example, adding translation capability to component names?

**Comment by alcompstudio** [comment]
Still relevant - I need translations into Russian, Ukrainian.

**Comment by bambalaus** [comment]
This is marked as "completed". Does it mean that these capabilities (front-end localisation) are now available?

**Comment by Den4ik1992** [comment]
No as far as I know you cannot translate to Budibase in other languages.

**Comment by Flashpok** [comment]
> 

I use selft-hosted Budibase in Docker. I don't find the "buttonActions.js". Can you help me to find it ? Thank you.  

+1 for translation !

**Comment by TechInterMezzo** [comment]
@shogunpurple Could you please state a reason for closing this issue as completed?

**Comment by florianb** [comment]
A localization PR has been opened - not sure if it covers a full translation though: https://github.com/Budibase/budibase/pull/10532
