### ISSUE TITLE
Set user password flow

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#396]
At the moment, we can create and update a user.

When you create a user, you set their password. This means that the administrator has to create inital passwords... which is not right.

There is some thought to be done around what we actually want to support here.... here are some scenarios for consideration

1. Developer create user from builder - type password
As now, create new users from builder, and allow setting of password - a useful scenario for dev

2. Developer creates user from hosting platform - do not type password
User gets an email, with a unique link. They can set their own from here password

3. App Admin user creates user from App - no password
User gets sent an email, with link

4. App Admin resets users password
User gets sent an email with link

5. User sets their own password
User gets sent an email with link

Note that most of the above require an email address.... we are not currently storing

**Comment by HugoLd** [comment]
I've started working on it with PR #473

**Comment by HugoLd** [comment]
Storing email : OK
Send minimal email with sendGrid: OK
