### ISSUE TITLE
Log Out Action does not work

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3968]
I have reproduced the issue below. It actually seems that `Log out` does not work at all. When this action is triggered, I get redirected to the App portal and can continue working as normal (logged in).

### Discussed in https://github.com/Budibase/budibase/discussions/3967

<div type='discussions-op-text'>

<sup>Originally posted by **micebrain** January  7, 2022</sup>
Hi,

I have a public page with a button that navigate to a second page that required permission and this works perfectly fine and I can see that after login it gets redirected to the return url.
On this second page, I have a button to logout and I see that it redirects back to `/builder/app/login`. I would like to have it redirect back to the app public page.
I tried setting a `Navigate to` action this in the button action, but it doesn't seems to work. Is there a way around this?

<img width="576" alt="Screenshot 2022-01-07 at 14 47 46" src="https://user-images.githubusercontent.com/7136209/148556054-e9ca4662-181f-4d99-bda9-9eb95a206933.png">

Thanks!

 </div>

**COS**
- Make call to worker to log out
- Don't redirect
- Add property to logout action for URL you want to navigate to

**Comment by aptkingston** [comment]
Yea the log out action was implemented way back when we had custom login screens. I think I had said about removing it before because I don't think the apps should be concerned at all with auth. Do you think there's value in keeping it?

**Comment by Klience** [comment]
Hi!

This functionality was crucial when I pitched a potential HR app to many clients.

If I remember correct, I could just drop a link to let's say an HR manager, they would enter their pre-set credentials and access the app without installing budibase.

This made it useful to use it on any device without budibase running. The link to app access with the right login/pass and permissions was enough.

I don't know whether that's still the case or much changed with cloud access, but that was something that many potential clients valued.

IMO if it's not difficult to keep and maintain, there's 100% some value in it.

**Comment by Sbleck** [comment]
Hello,

`Yea the log out action was implemented way back when we had custom login screens. I think I had said about removing it before because I don't think the apps should be concerned at all with auth. Do you think there's value in keeping it?`

I think that could not only be useful to quit the app, but also close all database connections should be considered, of course too.

Rgds
