### ISSUE TITLE
No  Pagination when Data in Data Provider as a SQL Query

### ISSUE THREAD

**Issue by KevMyst** [Budibase/budibase#3974]
No  Pagination when Data in Data Provider as a SQL Query.

![image](https://user-images.githubusercontent.com/6716949/148593711-eafa73b9-884d-4ced-b339-a667379b8183.png)

**Comment by aptkingston** [comment]
Hi @KevMyst. Yes this is correct - if you write a custom query then you will need to handle everything yourself. If you're using Postgres or MySQL then I would highly recommend integrating your database with Budibase and letting us handle queries for you - which will let you use our built in pagination. 
https://docs.budibase.com/building-apps/data/tables/postgresql-mysql-and-sql-server

**Comment by KevMyst** [comment]
Hi @aptkingston. Unfortunately, I can't use the "integrating database with Budibase" because I need to change columns type, e.g. datetime to date and add calculated columns from other related tables. Is it possible using tables and not SQL queries?

**Comment by David-Nahorniak** [comment]
I would also appreciate the ability to turn on multiple pages when using SQL queries.
I'm starting to worry about the performance of the application, as I will be displaying >5000 records on one page.

**Comment by melohagan** [comment]
For anyone interested, I've created a workaround here: https://github.com/Budibase/budibase/discussions/7313#discussioncomment-3430353
