### ISSUE TITLE
[BUDI-7802] Auto refresh data provider on an interval 

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3992]
Set up a data provider to auto-refresh on an interval.

This has been asked for a few times before and I know that we want to do this. It seems that it's got lost along the way. https://github.com/Budibase/budibase/issues/2427 was closed because we did the manual refresh part of it.

<sub>[BUDI-7802](https://linear.app/budibase/issue/BUDI-7802/auto-refresh-data-provider-on-an-interval)</sub>

**Comment by dumblob** [comment]
I'm highly interested in **fully** automated refreshing initiated by **any** change to data on the server. Imagine something like push notifications.

My goal is to integrate BB with [Grist](https://www.getgrist.com/ ) (probably as ["custom widget"](https://support.getgrist.com/widget-custom/ ) in the Grist's terminology as if integrated upside down - BB as frontend and Grist as a data source, it'd scratch most of the Grist's advantages). Note Grist is "live/reactive by default" in its widgets (uses a web socket or alike in the background).

Just to cross-reference another potentially related BB discussion: https://github.com/Budibase/budibase/discussions/1609 .

**Comment by mjashanks** [comment]
Also requested here: https://github.com/Budibase/budibase/discussions/5011

**Comment by Valdri** [comment]
I am also very interested in this feature but unfortunately, I have not seen it on the budibase roadmap.

**Comment by Valdri** [comment]
My current workaround is to use the chrome [addon](https://getautoclicker.com/) to click hidden refresh button at intervals.

**Comment by MichalisDBA** [comment]
Any chance getting this feature with latest budibase versions?

**Comment by cstasius** [comment]
Interested as well

**Comment by 4nsix** [comment]
+1 needed this feature

**Comment by MichalisDBA** [comment]
Is it released with the new version 2 now?

**Comment by tristndev** [comment]
+1 this seems like a relatively simple but essential and needed feature that is a show stopper for some of our applications.

**Comment by mahxds** [comment]
missing this feature too... specially when modal screens open, and change values, main page needs to be updated

**Comment by ErielCruz** [comment]
Interested in this too

**Comment by MartinPicc** [comment]
Here is a budibase plugin to define a time interval and execute a set of actions every x seconds (including refreshing data provider):
https://github.com/MartinPicc/budibase-interval-plugin
Disclaimer: I'm the author of this plugin, let me know if you have any feedback

**Comment by hci-ikahera** [comment]
Any update related to this feature?
Thank you.

**Comment by Lanhild** [comment]
Still relevant.

**Comment by lastcron** [comment]
Definetely needed in order to refresh dashboards every x mintues

**Comment by pmendl** [comment]
+1 Either allow access to windows and location (fast-but-dirty solution) or make some Action like refresh dataprovider, reload form grid etc. available. I have all ready for our monitoring screen, except it does not actualize...

**Comment by Lanhild** [comment]
@melohagan has this issue been closed because this feature will not be implemented or because the team tracks it internally?

**Comment by melohagan** [comment]
@Lanhild No - accidentally closed!

**Comment by ConorWebb96** [comment]
Closing as this has been completed
