### ISSUE TITLE
Update State does not work when used inside a Card 

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3993]
When I use update state from a `Card` or `Card Block`, the state value is not listed in the available binding propertis.

Steps:
1. Add a `Card Block`
2. Add a card button, and make it's actions `Update State`
3. Elsewhere in your screen, try to use your state variable 

RESULT: it's not listed in the Binding drawer

I've also tried to bind to it by typing the name in javascript `return $("State.card_state");` - it does not work either.

**Comment by aptkingston** [comment]
I'm guessing this is using the prod version? I believe I've already fixed this on develop, but we haven't done a release in a while.

**Comment by aptkingston** [comment]
Cloud has been updated with a version that includes this fix, so closing this off.
