### ISSUE TITLE
Design access using Firefox 96.0

### ISSUE THREAD

**Issue by thegitcat** [Budibase/budibase#4007]
**Describe the bug**
Accessing to the design using Firefox result in infinite loading

**To Reproduce**
1. Go to 'app -> design'

**Expected behavior**
Infinite loading

**Screenshots**

```
09:42:51,956 Uncaught (in promise) TypeError: can't convert undefined to object
    fetchRoutes http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    hI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    hI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    a http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    Ge http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    ze http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    je http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    gI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    loadBudibase http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    receiveMessage about:srcdoc:85
    EventListener.handleEvent* about:srcdoc:95
budibase-client.js:269:122378
    hI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    AsyncFunctionThrow self-hosted:699
    (Asynchrone : async)
    a http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    map self-hosted:224
    Ge http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    ze http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    je http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:1
    gI http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    loadBudibase http://10.0.10.16:10000/prod-budi-app-assets/app_04efcb51729f4d7d8efeb795e2f416de/budibase-client.js?v=1.0.35:269
    receiveMessage about:srcdoc:85
    (Asynchrone : EventListener.handleEvent)
    <anonyme> about:srcdoc:95

```
![image](https://user-images.githubusercontent.com/21105459/149163501-7368d292-c4cd-4f40-a310-89e9bc68c9e7.png)

![image](https://user-images.githubusercontent.com/21105459/149163571-58a6999a-a970-4a1f-a7f8-e93fbdeb6de0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 96.0
 - Version Budibase 1.0.3.5

**Additional context**

Hi!

I am having the same problem using Firefox 96.0. I have this in error my Firefox console; Maybe it can help resolving: 

I am using docker self-hosted, no modification has been made to deployment, except secrets and password, on a clean docker host running alpine 3.X.

I have removed (whitelisted) all adblock or cookie blocker;

I have tested using Chromium Version 88.0.4324.182 (Developer Build, ungoogled-chromium) (64 bits); 

**It work fine (there is no problem accessing design)** so I guessed the problem was similar to what happened to Safari.

Budibase App version: This app is currently using version 1.0.35 which is the latest version available.

**Comment by aptkingston** [comment]
Hey @thegitcat. That error is actually nothing to do with your browser - it's because somehow the route definitions for your app are malformed. I'm not sure how that can happen, but I will add in some checks to ensure that this specific scenario doesn't cause the client to crash. The fix will be included in our next release.

**Comment by thegitcat** [comment]
> Hey @thegitcat. That error is actually nothing to do with your browser - it's because somehow the route definitions for your app are malformed. I'm not sure how that can happen, but I will add in some checks to ensure that this specific scenario doesn't cause the client to crash. The fix will be included in our next release.

Thanks! FYI, here is exactly what I did from start:

1. run using docker-compose after changed secret;
2. create super admin using Firefox on default route;
3. Create app from template "Marketing"
4. Naming "Demo-Marketing";
5. system warn me not to use hyphen in app name;
6. rename to "DemoMarketing"
7. access the Design then got the infinite loop;
8. Tried again on Chromium, no infinite loop.

Thanks!

**Comment by aptkingston** [comment]
Hey @thegitcat. We identified that the reason for this is the change Mozilla added to Firefox 96.0 which adds a default `SameSite=lax` attribute to cookies, which prevents cookies being sent from our dev preview (it's an iframe, so a third party site technically). The error in your screenshot is throw by the client which made me think it was nothing to do with the browser, but the reason the client throws it is that the browser has stopped our cookie from being sent!

We've pushed a fix for this to master and will release soon. Thanks for reporting it!

**Comment by thegitcat** [comment]
No problems, thanks to you guys(and probably girls) for the amazing work.

**Comment by shogunpurple** [comment]
Hey folks - so even despite our push to master, this still seemed to be an issue. I've just discovered that this is a bug in firefox. Our problems were with the new samesite cookie policy that mozilla shipped, but it was a bug - chrome has had the same (correct) samesite behaviour since February 2020. Our `.budibase.app` domain for cookies isn't actually a cross domain request - so firefox was treating it differently to chrome even though they are now meant to be the same behaviour. See this support issue under mozilla.

https://support.mozilla.org/en-US/questions/1365797

They've rolled it back in the latest versions of firefox. Updating your firefox should resolve the issue. I'm going to close this for now - because when they roll out firefox 97, the correct behaviour should exist, and this will not be a problem.
