### ISSUE TITLE
Editing Records / Tables Within Web Apps

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#401]
I feel it is important the user can edit/view/delete records within tables, within their web apps.

**Comment by mjashanks** [comment]
I have partly addressed this by adding a new `RecordDetail` component.

1. Create a new screen, with url that looks like `/products/:id` ... i.e. has an `id` at the end
2. Add the RecordDetail to your new screen
3. Add child components to `RecordDetail`
4. Now somewhere else in your app, you will probably already have a `List` component, that lists through the models that you want to edit. In your list, put a link with url `/products/{{ context._id}} ` ... which will navigate to your new screen

The components underneath `RecordDetail` should be able to access the records properties using the `{{ context.FieldName }}` syntax.

Now, we need Form components (Inputs, Select) that are able to edit the values of {{ context }}  - which we dont currently have
