### ISSUE TITLE
no error message when saving a form to postgres which violates constraints

### ISSUE THREAD

**Issue by rburgst** [Budibase/budibase#4049]
**Describe the bug**
When trying to use an auto generated form for a postgres table which has non-null constraints I get no error message on the client but it simply redirects to the list view.

**To Reproduce**
1. import postgres database with a table such as
```sql
-- auto-generated definition
create table customer
(
    customer_id                 integer  not null
        constraint tbl_cm_customer_pk
            primary key,
    firstname                   varchar(50),
    lastname                    varchar(50),
    person_type                 smallint not null
);
```
2. let budibase auto generate a screen
3. run it via the play button
4. enter some data and dont fill out `person_type`
5. click Save

**Expected behavior**
I would expect the user to stay on the edit screen and get some error message. Instead I am routed to the list screen and get a brief "error" toast. 
The entered info is unfortunately gone at this point. 

I have not found a way to only navigate when saving succeeded

**Screenshots**

![SCR-20220115-lmt](https://user-images.githubusercontent.com/22971/149625545-62a00e26-01f9-4ee4-803d-7ec09c84cc1f.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser firefox

**Additional context**
Budibase 1.0.35

**Comment by melohagan** [comment]
Better error messages have been added:

![Screenshot 2023-12-01 at 16 29 27](https://github.com/Budibase/budibase/assets/101575380/59fe0420-36ae-4237-a257-bb0a339012e2)
