### ISSUE TITLE
SQL Server Load Data - Table schema other than dbo

### ISSUE THREAD

**Issue by KevMyst** [Budibase/budibase#4051]
In my opinion, budibase does not support any schema other than dbo. Tables with a different schema do not load data.

![image](https://user-images.githubusercontent.com/6716949/149638068-0dadd9bc-8ed2-43be-99b1-d04371ca93ca.png)

![image](https://user-images.githubusercontent.com/6716949/149638074-ba8b19ac-26ef-4b9e-8be5-d2e6069cd210.png)

![image](https://user-images.githubusercontent.com/6716949/149638153-e444c875-65f5-4e53-b526-fefedbc8dca5.png)

_Originally posted by @KevMyst in https://github.com/Budibase/budibase/issues/3839#issuecomment-1013755756_

**Comment by GiovanniBaldo** [comment]
In my case thats not the problem. All my tables are in dbo schema

**Comment by KevMyst** [comment]
> In my case thats not the problem. All my tables are in dbo schema

The problem arises if the database to which you want to connect the table has a different schema and it cannot be changed to dbo.

**Comment by mike12345567** [comment]
In the latest release of Budibase you can now select a different table schema as part of the datasource configuration.
