### ISSUE TITLE
Multi-select picker - cannot set default value

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4067]
I am trying to set a default value on the multi-select picker, but cannot.

I have tried to set it to

```javascript
return ["Value1"];
```

`Value1` is a valid option.

When I do this, I see the console error

```
uncaught (in promise) TypeError: e.forEach is not a function
    at budibase-client.js?v=1.0.39:1:617582
```

Originally raised here: https://github.com/Budibase/budibase/discussions/4048

**Comment by bastiaanterhorst** [comment]
@aptkingston I looked at this just now, but missed that you had assigned this to yourself. I hope you hadn't spent too much time on it yet, and that my solution is acceptable!

**Comment by aptkingston** [comment]
@bastiaanterhorst no problem at all! The changes I made were almost identical to yours, so I'm very happy to get your PR merged in and add you as a contributor. Thanks again!

**Comment by bastiaanterhorst** [comment]
This issue is resolved and can be closed.

**Comment by shogunpurple** [comment]
Thanks @bastiaanterhorst!
