### ISSUE TITLE
Workflow Builder Improvements

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#407]
Please add to this list as you see fit,

- [ ] Currently, there is an action to "Set UI State". We should also be able to set a value in current `{{context}}` . Should this be an option on the existing action ?

- [ ] I was trying to create a button that set a timestamp. I.e. set date value to Now. This is probably a very specific example of some arbitrarty programatic action. I suggest we create a Code block, until we know what the common use cases are, which seems impossible to know right now

- [ ] If I create a heading, bound to a value on state `{{ state.SomePath }}`, and then update that path with a workflow action, the component does not update. However, if i nav to a different screen, then back to this one, the Heading text updates. This would suggest that the Heading is not subscribed to the store - i.e. it only getes its new value when the screen is rerendered

**Comment by shogunpurple** [comment]
The context of workflow needs a bit of work in general:

- Context items are stored on their blockID as the workflow executes, but this isn't obvious to the user. We need a little dropdown or some sort of UI to show them the available values
- Can't test workflows yet
- Need a fairly rigorous test of all the ones we currently have
