### ISSUE TITLE
Automation JS steps returning wrong values

### ISSUE THREAD

**Issue by funkymule** [Budibase/budibase#4078]
I have an automation with several JS steps. The first one shows the correct output, but further down in the automation, the later JS steps are returning the value of the **_first_** JS step instead.

Am I coming up against a bug in Budibase or am I completely misunderstanding things?

I have exported an application that demonstrates the problem. It can be downloaded from this gist:
https://gist.github.com/funkymule/287e73df43c9e35072c66d4fab7a0bac

**Comment by mike12345567** [comment]
Hi @funkymule - just to check, what version of Budibase did you experience this on? This should be fixed in the latest release that went out a few days ago: https://github.com/Budibase/budibase/pull/3998

**Comment by funkymule** [comment]
I will have our client update their servers and check again. Thank you.
