### ISSUE TITLE
Backend Improvements

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#412]
### Backend  - Things we need to be able to do at some stage

Below is a list of this, in priority order (IMO), which I think we will need at some stage. Note that most of these will require work in the builder, and work in components, that make use of the features

1. Dates. Currently dates are just strings. These should be real dates, in order to allow proper ordering, and other handling

2. Calculated fields (formulas)

3. Perform Rollups on tables - Have the server rollup this data, so entire datasets do not have to be returned (only aggregated data). Grouping should be supported. I think that this is necessary to properly support charting. E.g. say we have 4 charts on a page... doe we want to load 4 full datasets, and perform the grouping etc on the client side ?

4. Define a default value, or a function to get a default value (e.g. Date > now). This is noticeable now - when we create a record, with a checkbox, the checkbox is uncheck, but the value is null. The record wont save. We could solve this by always defaulting to false - and same idea with a select. But I think a better solution wwould be to all setting of a default value.

5. Primary key concept. Tables need this concept to allow efficient lookups of linked records, and to know how to display a linked record, inside a table/card etc.

6. Datalinks - store linked data inline ("primary key" only? Or Declare list of fields to be inlined ?). At the moment, if we want to display the linked record, we need to look it up seperately. This will be unacceptable going forward, when displaying tables with linked columns and lots of data. This means updating linked records when their primary key changes

7. Filter, Sort, Map. Static views and/or On the fly filters / queries. Ability to filter, sort and map data in some way.

8. Custom Validation Rules. We have some basics at the moment.

9. Server Paginated data. 

10. String - multiple select - e.g. like tags

11. Data link - linke to single item (currently multiple only) - this could be a ui change only

**Comment by joebudi** [comment]
- [ ] create record form does not contain the inputs from bbui
