### ISSUE TITLE
Importing an app doesn

### ISSUE THREAD

**Issue by msztenke** [Budibase/budibase#4125]
**Describe the bug**
After exporting an app to the export.txt file from one BB instance, it doesn't get imported to another from that file. In fact only the name given on importing dialog appears but nothing else is there. No data, no screens, nothing.

**To Reproduce**
1. Have an app using BB built-in DB
2. Click Export apps in the main screen and save the export file locally
3. Move to another BB instance and select Import app in the main screen
4. Select the previously exported file, give app the name
5. Get a dialog box to select the type of the DB
6. After dismissing it, nothing is available in the app

**Expected behavior**
All tables, data, screens, etc. should be exactly the same as in the original BB instance

**Comment by aptkingston** [comment]
Hi @msztenke. Can I just confirm that you tried to export *all* your apps (which is what "export apps" does), and then tried to import all your apps using the "import app" button (which only imports a single app)?

The functionality for exporting all your apps is designed to be used for migrating to a self hosted environment. During the setup process you'll be able to use that export to set up your new environment to include all the apps and settings that you have in the cloud version.

If you just want to export and import a single app, please select the "export app" option from the context menu beside each app name. This will export just that one app, which you can then import using the "import app" button that you have already tried to use.

**Comment by msztenke** [comment]
Hi Andrew, thanks for the response. I did exactly as you wrote. I didn't know there's a difference between the exports and imports. Exporting from a context menu and importing into another instance works as expected.

What might be an UX comment is that Export apps and Import app buttons that don't actually work together are located side by side on the main screen. This is what confused me.

**Comment by aptkingston** [comment]
Yep I totally agree - whenever I was thinking about your issue the same thought occurred to me as well. I think the "Export Apps" button should be in a different location, because it should be something that is rarely done. Thanks for the feedback and I'll discuss with the team and I'm sure we'll make a change!
