### ISSUE TITLE
Form Fields no longer work as data provider bindings

### ISSUE THREAD

**Issue by Gomeyy** [Budibase/budibase#4126]
**Describe the bug**
I can no longer use a form field as a data provider binding after updating to 1.0.44, they also don't show up as options when using handlebars when setting a binding.

**To Reproduce**
1. Create a form with any field
2. Create a data provider in that form
3. Try to use that field as a binding in the data provider

**Expected behavior**
Being able to use form variables in data provider bindings

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97.0.4692.71

**Additional context**

**Comment by sergey-dme** [comment]
I guess this is why a tab with my app completely freezes after update to 1.0.44, it happens on some pages with similar structure and even complicated tree (lots and data providers. repeaters and forms inside of each other). I rolled back to v1.0.35

**Comment by Gomeyy** [comment]
@mike12345567 Using a form field as a query binding not a filter 
![image](https://user-images.githubusercontent.com/22477051/150364645-a022217b-a1c7-4a0a-9f4f-1228a75a604c.png)
This is what I see when using a data provider, no bindable values 
![image](https://user-images.githubusercontent.com/22477051/150364804-629860de-065e-4c42-a4bf-afd13c8dc11d.png)
When using a headline at the same position in the hierarchy is acts as I would expect
![image](https://user-images.githubusercontent.com/22477051/150365345-c127e28b-6fe2-458f-ada8-7d438c13be42.png)

**Comment by mike12345567** [comment]
Thanks @Gomeyy - I can see that happening as well - will get a fix out for it.

**Comment by mike12345567** [comment]
Hi @Gomeyy - I've triggered `v1.0.45` to release which should resolve your issue.

@sergey-dme - if possible could you check if it resolves your issue as well? If not it'd be good to try and diagnose what went wrong in your app too.

**Comment by Gomeyy** [comment]
@mike12345567 Okay, so the bindable values are appearing now for data providers.

But now when running a rest query on the design tab any bindings assigned for that rest query become empty?

I have a company binding on one of my rest queries and when I run it from the data tab, it uses the default value and runs fine.
![image](https://user-images.githubusercontent.com/22477051/150395433-450dcd78-2353-4be4-a379-f21278bbad49.png)

When I run the same query from a data provider/table block it doesn't use the default value, or any value I attempt to assign and seems to be running the query with that binding as an empty string.
![image](https://user-images.githubusercontent.com/22477051/150395837-00423419-d672-4e90-9c02-5c1568cf8e86.png)

**Comment by mike12345567** [comment]
Hi @Gomeyy - i've been trying to re-create to not much success, can you try a few things for me:

1. If you create a new app, add a REST datasource and then try it does the same problem occur?
2. Just to check, have you updated your app client library version? You'll see a little blue refresh icon in the top right if you haven't.
![image](https://user-images.githubusercontent.com/4407001/150401008-18d41c6c-6fce-4e7c-b95c-1e871f9ac944.png)

**Comment by Gomeyy** [comment]
@mike12345567 Okay, so it seemed to be the second one, I had the blue refresh icon. Clicking that and updating to 1.0.45 fixed the previous issue but upon updating, assigning a data provider as the data value of another data provider causes it to perpetually load
![image](https://user-images.githubusercontent.com/22477051/150406154-17eaa16e-9eed-43d7-836d-f1e6871329a8.png)
![image](https://user-images.githubusercontent.com/22477051/150406222-bb4aabac-a811-46e5-aeb5-053179aff329.png)
![image](https://user-images.githubusercontent.com/22477051/150406317-67665b3d-2c6c-46c1-a191-fef04ea6f39b.png)

![image](https://user-images.githubusercontent.com/22477051/150405390-609a4f6c-80ad-4f80-804e-98b31926c4a3.png)

**Comment by aptkingston** [comment]
@Gomeyy my PR (https://github.com/Budibase/budibase/pull/4086) to fix that issue (#4069) was just merged half an hour ago, but to our `develop` branch, so it won't be shipped until our next release which should be about 10 days away.

**Comment by Gomeyy** [comment]
@aptkingston Great! Sorry I missed the develop branch, thanks for the info.

**Comment by aptkingston** [comment]
No worries! We've actually decided to pull this fix into master as part of this PR (https://github.com/Budibase/budibase/pull/4134), so we'll actually get it live very soon 👍
