### ISSUE TITLE
Critical: App completely freezes and browser tab gets unresponsive

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#4132]
Hey all, 

App completely freezes, crashes and browser tab gets unresponsive if `{{ now }}` is used as Default value in Date Pickers (Create New row Forms). I rolled back to 1.0.35. 

Please close this issue if you consider that it will be fixed by PR https://github.com/Budibase/budibase/pull/4033

Thank you.
v. 1.0.44
v. 1.0.45

**Comment by sergey-dme** [comment]
The test app. Try to fill txt filed if date picker in the form has` {{ now }}` as default value.. 

<img width="663" alt="Screenshot 2022-01-20 at 22 06 29" src="https://user-images.githubusercontent.com/53024832/150405446-4de5b779-214e-417e-8960-d9ae6b15c2df.png">

**Comment by aptkingston** [comment]
Looking at it now Sergey 👍

**Comment by sergey-dme** [comment]
Hey @aptkingston Thank you for fast response. It took whole day for me to find the crash cause). Hope it will be fixed soon

**Comment by aptkingston** [comment]
Have included a fix in https://github.com/Budibase/budibase/pull/4134 which we will be publishing live very soon 👍 
Appreciate your effort in finding the exact cause of the crash, it really helped!
