### ISSUE TITLE
Default values for Option Pickers do not work correctly (being ignored)

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#4136]
Hello again,

I have a Form which is a filter for Data Provider/Table. There is a regular Option Picker (not multi), like a Status filed with values "Open, Closed, Reserved, etc.." The Option Picker has default value "Open". When I open a page with this form - it's okay, value "Open" is shown in Picker, but Data Provider filter just ignores it (returns all rows with Open, Closed, etc..) until I select any other option and then again "Open". The same story across entire app.

It works in 1.0.35 but does not work in 1.0.44-46
Im still on 1.0.35. 

Thanks.

**Comment by aptkingston** [comment]
Thanks Sergey, will get this fixed.
