### ISSUE TITLE
"Continue If" step, for button actions

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4143]
We've recently added the ability to use values from previous button actions steps.. .e.g. ``{{ Action 1.Saved Row._id }}`

It would now make sense to add a "Continue If" step, that allows us to exit the flow under certain conditions.

**Comment by aptkingston** [comment]
Nice idea! Would be pretty easy too. Basically just a one line config of:
`Only continue if / don't continue if` - `HBS or JS binding` - `equals / not equals` - `HBS or JS binding`
And then you'd be able to use the outputs of any previous steps in either of those bindings, as well as all the other normal bindings.

**Comment by yliang725** [comment]
Hi, is there any alternative solution to exit the button action flow under certain conditions currently? Such as receiving errors or failed messages from the validation.

Thank you

**Comment by aptkingston** [comment]
Hey @yliang725. Currently if a "validate form" action fails or any sort of API call (save row, execute query etc) fails, then the flow will exit. It only continues if everything is successful.
