### ISSUE TITLE
Define default access for new users

### ISSUE THREAD

**Issue by burnoutberni** [Budibase/budibase#4160]
Previous to #2975, all new users were automatically added to all apps, which might not be perfect from a security perspective, but in my case pretty useful:

* My Budibase is set up with OIDC. On log in, unregistered users are automatically created.
* I have a public app with a form. Parts of the form (name/email) are autocompleted if the user is logged on.
* Previously, a new OIDC user would sign in, be automatically added to all apps including this one. OIDC supplies name/email, autocomplete works without further interaction.
* Now, I have to add users to the app manually. This can't happen beforehand, because the user doesn't exist yet.

Probably there's a few ways to solve this, but it would really be great to define default app roles for new users.

**Comment by robinWongM** [comment]
Same here. Also notice that there is a column called "group" in user table, but I can't create groups or assign groups to users. Is there any workaround to enable access for users to apps without adding them one-by-one?

**Comment by nishantnaagnihotri** [comment]
Hi @shogunpurple 

This is something that will really help in scalability of the apps that we configure on Budibase.
It is infeasible to give access of the app to each user one by one when users are signing up by google sso.

Is there any workaround available to give users access to an app by default?

**Comment by jat255** [comment]
@shogunpurple what was the reason for closing this? If using SSO in an organization beyond a few users, manually adding 100s of email addresses is not really a feasible approach, as @nishantnaagnihotri mentioned.

**Comment by shogunpurple** [comment]
https://docs.budibase.com/docs/user-groups#individual-roles-and-group-roles is the way to do this, but right now has no integration with SSO.

**Comment by nutgood** [comment]
This is important for us too.
