### ISSUE TITLE
OIDC login loses returnUrl

### ISSUE THREAD

**Issue by burnoutberni** [Budibase/budibase#4161]
Usually, when users are redirected to the login page, the last app state is retain by the `returnUrl` parameter (e.g. https://budi.base/builder/auth/login?returnUrl=%2Fapp%2Fbudi-test

This is not true for OIDC users.

**To Reproduce**
1. Go to an app (not logged in) and move to a restricted site
2. After redirect press "Log in with OIDC" button
3. Log in with OIDC
4. Returns to `/builder` instead of restricted site

**Expected behavior**
Should keep state and bring users back to `returnUrl`

**Comment by Rory-Powell** [comment]
Hey @burnoutberni , we've got fixes for this one coming soon that were introduced here https://github.com/Budibase/budibase/pull/4022
