### ISSUE TITLE
REST Api - cannot Save Query until I "Send"

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4167]
The `Save Query` button only appears once I press send. This is very annoying when making small changes to a query....

1. When I open an existing query and start editing it, the "Save Query" button is not visible anywhere, so it's not obvious what I should do.
2. For small changes it's often not necessary to "Send" before I save
3. POST and PUT requests cause updates - I should be able to save my query without updating my data.

- Only force save when there is no schema
- Allow saving whenever afterwards

**Comment by Rory-Powell** [comment]
+1. Do you think the ability to save without send should be present on all HTTP methods?

**Comment by mjashanks** [comment]
I think so. One of the benefits of Sending, is that your schema gets created automatically. So we might need to warn about that.

But yes, I think it should be available on all HTTP methods if possible.
