### ISSUE TITLE
Editing issues with on-screen text editor

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#4177]
**Describe the bug**
When I double-click a paragraph component, add my content, click away from the paragraph component, the content disappears. When I attempt to paste the content into the paragraph component, HTML is displayed.

https://cln.sh/DbAdZh

**Comment by aptkingston** [comment]
Found the issue 👍 it's from an old optimisation that isn't needed any more after my latest performance improvements, and now it's actually causing issues instead. I'll get a PR up to remove up and get it into master tomorrow.

**Comment by aptkingston** [comment]
Fix for this is included in `frontend-core` which will hopefully be merged soon :+1:
