### ISSUE TITLE
Table Configuration Drawer: Cell Configuration (UI)

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4200]
When working with the table component in budibase, I want to be able to control the display of my cells in my table, so that I can control the display of cells based on my data and bindings.

**COS**
  - Allow users to format cell values using a handlebars expression
  - Allow users to edit column styling properties - width, text align, height, background-color, text color, font-weight and font-family. This should be bindable to a handlebars expression.

**Comment by aidenmitchell** [comment]
Why was this closed? I'd like this feature, but I don't see it implemented.

**Comment by aptkingston** [comment]
@aidenmitchell column configuration changed from being a dropdown to being a full drawer. You can choose, label and reorder your columns here:
![image](https://user-images.githubusercontent.com/9075550/160021828-be222242-8296-4dcc-afe5-2efcae6db9f6.png)

Clicking on the settings icon for a column opens another settings drawer to control format, size and colors:
![image](https://user-images.githubusercontent.com/9075550/160021936-724ec6e2-555f-490b-8d7d-f681f730982c.png)

**Comment by aidenmitchell** [comment]
@aptkingston Great, thanks. It seems that this doesn't allow for JS or Handlebars expressions, as mentioned in the original issue. Is that on the way?

**Comment by aptkingston** [comment]
No problem! It does indeed allow for JS or Handlebars - you just need to click the lightning bolt icon in the value field shown above to open the data binding editor. The lightning bolt is a symbol used everywhere in the platform for creating JS or Handlebars bindings.

**Comment by aidenmitchell** [comment]
Could you send a screenshot? In the above screenshot, there’s no lightning bolt for text or background colour.

**Comment by aptkingston** [comment]
That's correct, the colours are just colour pickers. The value is the only field that supports expressions. Adding bindings for colours though might be a nice way of offering conditional colours - like red if the value is less than a threshold, green if above the threshold - since that would be easy to write as a JS expression.
