### ISSUE TITLE
Formula Field returns number, budibase treats it as a string

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4203]
https://github.com/Budibase/budibase/discussions/4190

1. Create a new formula, which calculates a number ... e.g. `return $("amount") * $("vat");`
2. In design, sum the formula column

Summation results in a concatenation, not addition.

**Comment by aptkingston** [comment]
I believe I've already made a change which will fix this as of https://github.com/Budibase/budibase/pull/4086, but I'll double check. Hopefully this is already fixed and will be in the next release.

**Comment by aptkingston** [comment]
Yep just tested and confirmed that it has indeed already been fixed! All JS binding outputs are real types now instead of just always strings. Closing this one off.
