### ISSUE TITLE
Postgres SQL Queries : Cannot use different access levels for different queries

### ISSUE THREAD

**Issue by superbolt-x** [Budibase/budibase#4205]
Hi!
Am trying to create multiple views/queries per access level - for example one for Public and one with more sensitive fields for Basic, but as I change the access level dropdown of one Postgres SQL query to Public, all the other queries defined before automatically switch to Public. Is this the intended behavior? Or one should be able to create multiple views with different access levels?

**To Reproduce**
1. Connect a Postgres DB
2. Create a new Query and choose 'Public' as Access Level for the query
3. Save the query above
4. Create a new query and choose 'Basic' for this one instead
5. Save the query above and refresh
6. Now both the queries have Basic access levels - the one with public access view has the permission overwritten

**Expected behavior**
Creating multiple postgres queries with different access levels

**Desktop (please complete the following information):**
 - OS: Docker-compose on EC2 AMI Linux
 - Browser : Brave

**Comment by mike12345567** [comment]
Hi @superbolt-x - i've looked into this, it appears there is a visual glitch where the correct role is not being loaded in the frontend - if you select one from the dropdown that will be the one the server uses. We'll get a fix out soon to make sure the frontend always displays the role that the query currently is using.

**Comment by superbolt-x** [comment]
Oh Ok! Thanks so much for the quick response!!
