### ISSUE TITLE
Unpublishing app reverts icon changes

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#4236]
**Steps to reproduce**
- Set icon and colour
- Publish
- Set icon and colour differently
- Unpublish
- Icon and colour are reverted

The icon changes should be persisted in dev and prod app dbs

**Screenshots**

https://user-images.githubusercontent.com/8755148/151554257-46fe1acb-229c-4e6c-a91a-ad0a6a3715fa.mov

**Comment by deanhannigan** [comment]
I could't reproduce the issue on staging, production or my local environment. App icon configuration remains in place when apps are unpublished.
