### ISSUE TITLE
Bindings are not available when using as custom API paramters

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4243]
Originally reported here: https://github.com/Budibase/budibase/discussions/4138

This is a bug that I previously could not reproduce. I have now stumbled upon it by accident, so the app export is below.

The issue
1. In the builder, go into the Home screen and choose the "Repo Provider" (this is a Repeater Block, but I find the same issue with a data provider)
2. It's linked to a REST query called "Get Repo". I want to pass a parameter to the query, from the Text Field, using the cog icon.

I find that the bindings from the form are not available when trying to bind the query parameter. In fact **no** bindings are available.

 The binding works ok with "Define Filters", on the same component.

[GitHub to Table-export-1643385551544.txt](https://github.com/Budibase/budibase/files/7960078/GitHub.to.Table-export-1643385551544.txt)

**Comment by mjashanks** [comment]
Update. 
1. The issue above, I experience in cloud
2. Imported this app into my localhost Budibase, on `v1.0.46` - this issue did not occur
3. I reimported the same app into Cloud (new app), and the issue happened again.

So, it seems to be a difference between these 2 versions.

**Comment by shogunpurple** [comment]
Deployed the latest there to cloud as it sounds like it may have been fixed since last release - will try and recreate now

**Comment by aptkingston** [comment]
Yep can confirm this fix is live and works now in the latest deployed version.
