### ISSUE TITLE
Old app data appearing in new app

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#425]
I created a new web app. Add tables and records. Clicked frontend, and it showed me the frontend of another web app. I then clicked backend and my new data was gone and data from an old app was there.

I went back to the welcome screen, and my new app was there. Clicked it, and the new data is still there. Clicked frontend and everything seems to be running fine.

Not sure if this has happened to anyone else but felt the need to flag this.

**Comment by joebudi** [comment]
I believe this issue was resolved with recent changes - is that right @shogunpurple ? I've not had any experience of this issue in the last 24hrs.

**Comment by shogunpurple** [comment]
@joebudi yep, I can't seem to reproduce. Looks like it's resolved.
