### ISSUE TITLE
Rows are not displayed when there are multiple relationships between 2 PostgreSQL tables

### ISSUE THREAD

**Issue by lhtrieu87** [Budibase/budibase#4255]
**Describe the bug**
Rows are not displayed when there are multiple relationships between 2 PostgreSQL tables.

**To Reproduce**
1. Use Budibase Cloud
2. Use PostgreSQL as the data source for all below steps
3. Create a users table (id, first_name, last_name)
4. Populate some data into the users table
5. Create a billings table (id, creator_id, billed_user_id) with both creator_id and billed_user_id being the foreign key relationships to the users table
6. Create a new row for the billings table
7. The newly created billings row is **NOT** displayed in both Budibase data builder and deployed view

**Expected behavior**
The newly created billings row should be displayed in both Budibase data builder and deployed view.  

**Screenshots**
Rows in PostgreSQL:
![Screenshot from 2022-01-30 10-58-41](https://user-images.githubusercontent.com/2397432/151685002-1a75ef8b-d5d8-48f4-8ee8-ea232924b0a9.png)

No rows in Budibase data builder:
![Screenshot from 2022-01-30 10-59-38](https://user-images.githubusercontent.com/2397432/151685030-69230dff-e4ff-4b41-8286-d98fbc92f715.png)

No rows in the deployed version:
![Screenshot from 2022-01-30 11-00-01](https://user-images.githubusercontent.com/2397432/151685035-1d8c2520-4378-47ce-bff2-1beb81230497.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 97.0.4692.99 (Official Build) (64-bit)

**Additional context**
- Use Budibase Cloud
- Use PostgreSQL version 14 on Google Cloud

**Comment by maxschrems** [comment]
Maybe related: 

* Cannot define a second relationship between two tables in postgresql - "save" button is not clickable.

![Unbenannt-2](https://user-images.githubusercontent.com/7262828/152132549-01865daf-b328-40a6-b9b2-ff2f42d885db.png)
