### ISSUE TITLE
when using `{{ context ... }} ` urls get encoded

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#427]
Mustache automatically sanitizes stuff inside `{{ ... }}` . This causes us a problem, when we have a databse field that contains a url.

You can disable this by using 3 curlys `{{{ ... }}}` . However - reccomending this to our users would be dangerous. It would allow their end users to send unsanitized input... e.g. script injection

**Comment by shogunpurple** [comment]
This is something that we will paper over with UI. If you select a "URL" field from the dropdown, it will insert the `{{{context.urlValue}}}` into the template

**Comment by mjashanks** [comment]
This is still a problem when using the Embed component.

Using 3 curlys inside the Embed field, allows the end user of the app to inject a script tag
