### ISSUE TITLE
Accept user invite page shows Budibase logo instead of org logo

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4290]
Accept user invite page shows Budibase logo instead of org logo

https://github.com/Budibase/budibase/discussions/3233#discussioncomment-2092942

**Comment by shogunpurple** [comment]
hi @imskr - of course, and thank you!

The file that you will need to update is here: `budibase/packages/builder/src/pages/builder/invite/index.svelte`

You can get set up by following https://github.com/Budibase/budibase/blob/develop/.github/CONTRIBUTING.md.

Let us know if you have any questions or need any guidance.

**Comment by R2bEEaton** [comment]
This is still listed in Good First Issues.
