### ISSUE TITLE
Deleting a exported app records deletes attachments in the non exported app

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#4293]
**Describe the bug**
If you export an app and then import it on the same server it was exported from then delete the rows that had an attachment. It will delete the attachment from the original app.

**To Reproduce**
1. Create a new app and create a budibase DB
2. Create a text column and an attachment column
3. Create a couple of rows with attachments
4. Export the app
5. Import the app and call it a different name
6. Delete the rows that you created earlier
7. When trying to access the attachment from the main app you will be greeted with an error page saying invalid key

**Expected behavior**
When deleting rows from exported app it will not affect the attachments from the main app

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97.0.4692.99
 - BudiBase Version 1.0.46

**Comment by shogunpurple** [comment]
Closing in favour of https://github.com/Budibase/budibase/issues/3378
