### ISSUE TITLE
Please add host.docker.internal information on documentation page to make requests to host machine.

### ISSUE THREAD

**Issue by yashbhatt** [Budibase/budibase#4339]
Could someone please add information about making requests / connecting to the local machine using REST api.

I could not connect my small local express api to REST datasource.

Tried :

127.0.0.1
localhost
0.0.0.0
192.168... (local IP)
172.17.0.1 (docker IP)

Eventually had to use : 

**host.docker.internal**/products

adding this to rest documentation would save a lot of time 

**Found it here** : 
https://github.com/Budibase/budibase/discussions/1839

**Comment by melohagan** [comment]
Note added to the docs: https://docs.budibase.com/docs/rest-queries#api-endpoint-url
