### ISSUE TITLE
Design Selection sometimes covering the Object

### ISSUE THREAD

**Issue by NanoClass** [Budibase/budibase#4349]
STEP TO REPRODUCE:

If you create a button on the top of the layout

![image](https://user-images.githubusercontent.com/37381079/152667546-8886cf4b-ae65-476d-882b-9d9a9194ef73.png)

and then select the button to edit it,
The Design modal will cover the button

![image](https://user-images.githubusercontent.com/37381079/152667533-799d2d0f-b8f1-4ce8-8fce-2eff5fa0a26f.png)

Maybe you can implement some "Drag" feature for the Modal.
So we can move the modal somewhere else.

Desktop (please complete the following information):

OS: any
Browser any
Version any

**Comment by aptkingston** [comment]
Thanks for reporting @NanoClass! We can hopefully detect when this is happening and show the bar underneath the component instead.
