### ISSUE TITLE
MongoDB w/ a self-signed certificate

### ISSUE THREAD

**Issue by davext** [Budibase/budibase#4351]
**Describe the bug**
Trying to connect to a Mongo Database with a self-signed certificate, results in the following error:
```
{
    "message": "failed to connect to server [mongo.ondigitalocean.com:27017] on first connect [Error: self signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at TLSSocket._finishInit (_tls_wrap.js:937:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {\n  name: 'MongoNetworkError'\n}]",
    "status": 400
}
```

**To Reproduce**
1. Add the self-signed MongoDB using the `mongodb+srv://` link
2. Click on add query and fill out the query with any query
3. Click run query

**Expected behavior**
Either accept the path of the certificate, or accept the certificate’s contents, and pass the certificate to the connector on the backend.

Metabase had the same issue a while ago, and this is what it looks like now: https://user-images.githubusercontent.com/1447303/84531524-0b94a280-ace5-11ea-8056-4a106a9ac22b.png

**Screenshots**

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Additional context**

**Comment by satanch** [comment]
Bumping this. Any news?
