### ISSUE TITLE
"Parameter format not correct" on win10

### ISSUE THREAD

**Issue by lewis617** [Budibase/budibase#4353]
**Describe the bug**
after run `yarn setup`, it throw this error:
```
lerna ERR! yarn run build exited 1 in '@budibase/server'
lerna ERR! yarn run build stdout:
$ rimraf dist/ && tsc && mv dist/src/* dist/ && rmdir dist/src/ && yarn posd
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about thisand.

lerna ERR! yarn run build stderr:
Parameter format not correct - "src".
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@budibase/server'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit iately.
error Command failed with exit code 1.

```

**To Reproduce**
run `yarn setup`

**Expected behavior**
no error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10

**Additional context**

**Comment by daawaan** [comment]
i tried this but unfortunately, `mv` isn't recognized in windows. tried using `move` but i still can't get it to work

**Comment by daawaan** [comment]
Thanks @mike12345567, I raised an issue by the way regarding running budibase in debian through WSL. I'd be glad if the team can check [#4996](https://github.com/Budibase/budibase/issues/4996)

**Comment by mike12345567** [comment]
Going to close this issue and continue discussion around development setup on Windows in issue #4996.
