### ISSUE TITLE
Revision History and Version Control

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4360]
## Description
The ability for users to roll back their application to a particular point in time.

## Spec
https://budibase.atlassian.net/wiki/spaces/PROD/pages/13631524/App+Backups

## Teams and Stakeholders
- Firestorm team

## Workflow
- [x]  Spec Created and pasted above
- [x]  Product Review
- [ ]  Designs created
- [x]  Individual Tasks created and assigned to Epic

**Comment by AntonAndreevichMoroz** [comment]
I would like to see this functionality in the form of integration with Git. To be able to specify the repository. And each developer would have their own login and password for push notifications. then the commits will be structured and you can see who ruled what.

**Comment by v3ss0n** [comment]
This one is quite necessary when we want to work with a team.
Currently it is locking each other , 
I think there should be configuration for Manual Locking , now i cannot show to my team because it is locking eac other

**Comment by mlucero-wine** [comment]
@shogunpurple  How does one use this feature?
