### ISSUE TITLE
Barcode/QR Scanner Component

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4379]
Spec: https://budibase.atlassian.net/wiki/spaces/PROD/pages/12615691/QR+Barcode+Scanner

When I'm creating new rows in budibase, I want to be able to use the camera on my device to scan a QR code or barcode, and insert the encoded information into a string type field in the form.

**COS**
- Add barcode scanner component to any input requiring a QR code to be scanned 
- Add barcode/QR type to form inputs section

Designs:
https://www.figma.com/file/NNLgDGmQxM96b5i0OKwkax/QR-%2F-barcode-scanner?node-id=0%3A1

**Comment by Grayda** [comment]
Don't know if you're planning to use a webcam for this (like a QR code scanner), or if it's just a field that would validate barcodes fed in via a USB barcode scanner or something, but if it's webcam based, could that component be split up to also handle taking photos and uploading them, like an Attachment field?

I'm building a video game collection tracker, and it'd be nice to be able to take a photo and upload it in-app, without having to take a photo via my phone or webcam, save it to my PC, then attach it.

**Comment by mike12345567** [comment]
Thoughts on this mentioned in: #4671.

**Comment by nev-21** [comment]
Great, it is a necessary component!

**Comment by artisleilands** [comment]
As you are involving the phone camera already (right?), could you also consider the possibility to add a photo as an attachment? I.e. to enable taking photos directly from the BB app.

**Comment by kasgithub8** [comment]
Are there any updates on this?
