### ISSUE TITLE
Signature Component

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4380]

**Comment by hotemetoot** [comment]
Same, this is one of the few features that prevents me from switching projects from Knack to Coda

**Comment by rafikApp** [comment]
We need a signature component

**Comment by Terrik** [comment]
Signature component is a must! Its only thing preventing me from switching over.

**Comment by vkDV** [comment]
Signatures would give the APPs a new level when using it as a reporting tool for service-employees, which have to take a signature from the currently visited customer. 

The functionality could also be used for a drawing-board on which the user can mark some special mock-ups of a delivered service (f. e.).

**Comment by MrApe** [comment]
+1 for this!

**Comment by rafikApp** [comment]
+1 for this

**Comment by melohagan** [comment]
There's a signature custom component here! https://github.com/FlaminWrap/budibase-signature-component

**Comment by GeisGit** [comment]
+1 for this...This would help us so much!

**Comment by ConorWebb96** [comment]
Closing as completed https://docs.budibase.com/docs/signature-field
