### ISSUE TITLE
n8n.io integration

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4400]
### Discussed in https://github.com/Budibase/budibase/discussions/2566

<div type='discussions-op-text'>

<sup>Originally posted by **physx2494** September  8, 2021</sup>
This is a continuation of the [now locked suggestion](https://github.com/Budibase/budibase/discussions/891#discussioncomment-381459) thread about the n8n.io integration. I couldn't find it mentioned here in Ideas, so made a feature request just to highlight and document it further.</div>

We should explore the idea of making this its own datasource so that there's a better integration with automations and you don't have to continually create queries to the same source.

**Comment by Elliot-Construct** [comment]
I did some testing around and the outgoing integromat webhook works with n8n webhooks.

**Comment by Elliot-Construct** [comment]
This isn't necessary because if you use the zapier automation tool and link it to the n8n webhooks element it works just the same. Therefore the easiest fix would be to rename the zapier automation tool to Zapier/N8n

**Comment by marco-santulli** [comment]
> 

sounds good thx

**Comment by shogunpurple** [comment]
https://github.com/melohagan/budibase-datasource-n8n-workflow

**Comment by satoshinotdead** [comment]
> https://github.com/melohagan/budibase-datasource-n8n-workflow

Thanks! I tried that integration but I don't know how to query data from N8N. I'm looking for sending a webhook from budibase (after changes) and I probably missing an important point here.
