### ISSUE TITLE
Supabase Integration

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4402]

**Comment by maeno14** [comment]
It would be awesome!

**Comment by MentalGear** [comment]
Can't this be done by linking to supabase's regular Postgres URL ?

**Comment by shogunpurple** [comment]
@MentalGear it can - this ticket was really just a placeholder to add a thin wrapper around that and make it easier to integrate with the supabase API if it’s something users are interested in.

**Comment by MentalGear** [comment]
> integrate with the supabase API if it’s something users are interested in.

Based on the upvotes, I'd figure it's def something users are interested in! :)
I am currently trying to figure out how to get supabase integrated into budibase myself.

**Comment by maeno14** [comment]
i would love to have this

**Comment by oldwired** [comment]
A wrapper to make it a bit easier would be great. 
Also Auth-Integration would be useful.

**Comment by MentalGear** [comment]
Yes, alone the functionality to have relations (fk) auto-imported and keep tables in sync would be great.

**Comment by gaa23** [comment]
While standard postgres works with supabase, I think a dedicated integration would include a lot more of their functionality.

If I am a no-code app planning for the future, I'm building a close partnership with Supabase.

**Comment by melohagan** [comment]
There is a basic Supabase datasource plugin here if anyone is interested: https://github.com/melohagan/budibase-datasource-supabase
