### ISSUE TITLE
Delete all screens underneath a route

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4406]
### Discussed in https://github.com/Budibase/budibase/discussions/4396

<div type='discussions-op-text'>

<sup>Originally posted by **hertilizer** February  8, 2022</sup>
Instead of having to manualle delete every subscreen of a route, there should be a way to delete multiple screens at once. For instance, instead of deleting "/person/:id", "/person/new/row", & "/person/", there should be a way to delete them all at once under the tab "/person" or their should be a way of selecting multiple screens and choosing to delete all.  </div>

**Comment by kasgithub8** [comment]
And copy + paste multiple screens at once!

**Comment by shogunpurple** [comment]
Addressed in https://github.com/Budibase/budibase/pull/4821
