### ISSUE TITLE
Budibase CLI hosting --init returns 404 not found

### ISSUE THREAD

**Issue by rogermyung** [Budibase/budibase#4419]
**Describe the bug**
When running the budibase CLI commands from https://docs.budibase.com/self-hosting/self-host/budibase-cli-setup#running-budibase, the error "404 not found" is returned.

**To Reproduce**
1. Download the budibase cli
2. Run budi hosting --init
**Expected behavior**
I expected the message 

> # Feel free to configure your port
> ? Please enter the port on which you want your installation to run:  10000
> 
> Configuration has been written successfully - please check .env file for more details.

**Desktop (please complete the following information):**
 - OS: linux
 
**Additional context**
I get the same error in the docker-compose instructions: https://docs.budibase.com/self-hosting/hosting-methods/docker-compose#setting-up-budibase when trying to download hosting.properties from https://raw.githubusercontent.com/Budibase/budibase/master/hosting/hosting.properties

**Comment by mike12345567** [comment]
Hi @rogermyung - thanks for raising this, we're currently transitioning away from Envoy to NGINX, during the migration some files had been removed that were needed for the Envoy installation, you can try again now and it'll work!

**Comment by svanschooten** [comment]
I installed and setup budi today, but am also getting 404 response, apparently the redirect rule in your nginx proxy is omitting the port. The redirect based on the message in the logs `http://localhost:1000` -> `http://localhost/builder/`
