### ISSUE TITLE
Need to update the documentation at Self Hosting > Hosting Methods > Docker Compose to remove reference to envoy.yaml

### ISSUE THREAD

**Issue by sudipmandal** [Budibase/budibase#4423]
**Describe the bug**
The documentation at [https://docs.budibase.com/self-hosting/hosting-methods/docker-compose](https://docs.budibase.com/self-hosting/hosting-methods/docker-compose) still mentions using envoy.yaml file which points to a non-existent url.

After the change from using envoy.yaml to nginx, this documentation needs to be updated for users trying to self host using docker-compose.

Following the current documentation does not work anymore.

**To Reproduce**
1. Go to 'https://docs.budibase.com/self-hosting/hosting-methods/docker-compose'
2. Click on 'envoy.yaml'
3. See error

**Expected behavior**
Documentation should not have broken links and should work

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Additional context**
Not a bug, its a documentation issue

**Comment by shogunpurple** [comment]
Thanks @sudipmandal - this was on a change request but hadn't been merged. It's merged now and the docs are updated - thanks!

**Comment by sudipmandal** [comment]
Thanks @shogunpurple!

Similar to docker-compose is there any documentation/discussion around getting this to work with Portainer?
Simply using the docker-compose.yaml file and the env file as a stack does not seem to be working on Portainer.
