### ISSUE TITLE
REST query modified by budibase without any notice

### ISSUE THREAD

**Issue by KacperKlys** [Budibase/budibase#4428]
**Describe the bug**
After saving REST query and going to the `Design` tab the same query is being modified (missing half of the variables).

**To Reproduce**
1. Go to `Data`
2. Click on `Add query` 
3. Configure query with bindings and parameters - see first screenshot
4. Send it and save after successful running
5. Go to `Design` tab
6. Come back to `Data` tab and to saved query
7. It occurs that query has been modified and it's not working anymore - see second screenshot (`value` label is missing and one square bracket)

**Expected behavior**
I would expect that the query won't be modified by budibase without any error messages? Is there something wrong with the query syntax?

**Screenshots**
How it looks like when I'm saving query:
![image](https://user-images.githubusercontent.com/45046413/153581399-c169249a-cab4-4978-8d15-6d6f9b1e2126.png)

How it looks like when I come back to the query tab:
![image](https://user-images.githubusercontent.com/45046413/153581563-e6ad885b-a525-4313-94f5-7e33ebdc9954.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.03 LTS (GNU/Linux 5.4.0-99-generic x86_64)
 - Browser: chrome Version 94.0.4606.81 (Official Build) (64-bit)
 - Version: 1.0.46

**Additional context**

**Comment by melohagan** [comment]
Looks fine in the latest version.
