### ISSUE TITLE
bbproxy - host not found in upstream

### ISSUE THREAD

**Issue by mihha** [Budibase/budibase#4429]
**Describe the bug**
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/02/11 11:50:22 [emerg] 1#1: host not found in upstream "app-service.budibase.svc.cluster.local" in /etc/nginx/nginx.conf:47
nginx: [emerg] host not found in upstream "app-service.budibase.svc.cluster.local" in /etc/nginx/nginx.conf:47

**To Reproduce**
1. budi hosting --start
2. check bbproxy log

**Expected behavior**
Well, I guess, bbproxy should start 

**Desktop (please complete the following information):**
Not related to the desktop

**Comment by mike12345567** [comment]
Hi @mihha - we are looking into the issue, for now if you update your images directly with docker rather than the CLI (`docker pull`) then it should start ok.

**Comment by mike12345567** [comment]
Hi @mihha - the latest version of the Budibase CLI should resolve this issue, if you download it from the [release](https://github.com/Budibase/budibase/releases/tag/v1.0.59).

**Comment by mihha** [comment]
Thank you for such a prompt reaction
