### ISSUE TITLE
Builder and app stop loading in Safari after update to v1.0.62

### ISSUE THREAD

**Issue by micebrain** [Budibase/budibase#4452]
I updated my builder to the current version 1.0.62 and noticed that the app is not loading in Safari (v15.3)

Upon checking the browser console, I see the following error message:

<img width="452" alt="Screenshot 2022-02-12 at 21 25 28" src="https://user-images.githubusercontent.com/7136209/153727321-a002384e-e0c6-4113-ba8f-e53c2a682c9c.png">

I am also not able to load previously published application (still in old version).

The app do however loads in Chrome.

**Comment by micebrain** [comment]
I found similar issues with other apps. So think is related to the fact that Safari does not support look behind regex.

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by aptkingston** [comment]
> I found similar issues with other apps. So think is related to the fact that Safari does not support look behind regex.
> 
> https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

Yea you're right, that looks like the issue. We haven't added this to the source ourselves, but we're trying to identify which dependency has added this.

**Comment by micebrain** [comment]
Maybe this has more info, I found that the console shows more info when I tried to load a published app 

<img width="1268" alt="Screenshot 2022-02-14 at 17 21 32" src="https://user-images.githubusercontent.com/7136209/153903546-eb4e8098-18d5-4c62-8e76-33f9fb812ab2.png">

**Comment by aptkingston** [comment]
Thanks a lot @micebrain! Have a PR up to (hopefully) fix this: https://github.com/Budibase/budibase/pull/4482.
We're just testing if it works or not.

**Comment by micebrain** [comment]
Just updated to v1.0.65 and it works :)
