### ISSUE TITLE
Apache reverse proxy instead of NGNIX

### ISSUE THREAD

**Issue by mihha** [Budibase/budibase#4453]
**Describe the feature request**
For various reasons, I can't use Ngnix as a reverse proxy in my environment. It would be great if you could provide Apache server reverse proxy configuration

So far I tried the following, which is not working 

```
ProxyPreserveHost On
ProxyPass / http://localhost:15000/
ProxyPassReverse / http://localhost:15000/
```

With this, when I access https://budi.domain.tld, browser redirect to http://localhost/builder

I am missing something in my Apache configuration, but can't figure out what exactly

I have similar reverse proxy configuration for various different services on the same server, and they are working correctly, so this is not an issue with the Apache setup

**Comment by mihha** [comment]
I have figured it out, so you might want to put this also in the official documentation

Correct and working Apache reverse proxy configuration is the following

```
ProxyPreserveHost On
ProxyPass / http://localhost:15000/
ProxyPassReverse / http://localhost:15000/

<Proxy *>
    allow from all
</Proxy>
```

**Comment by kmagumise** [comment]
Hi @mihha 

I new to Budi and reverse proxies.

I am attempting to do the same, but I keep getting No matching DirectoryIndex error

`<VirtualHost xxx.xxx.xxx.xxx:443>
	ServerName recruit.xxx.xxx
	ServerAdmin webmaster@recruit.xxx.xxx
	SSLProxyEngine On

	ProxyPreserveHost On
	ProxyPass / http://localhost:10000/
	ProxyPassReverse / http://localhost:10000/

	<Proxy *>
		allow from all
	</Proxy>

	CustomLog /usr/local/apache/domlogs/recruit.xxx.xxx.bytes bytes
	CustomLog /usr/local/apache/domlogs/recruit.xxx.xxx.log combined
	ErrorLog /usr/local/apache/domlogs/recruit.xxx.xxx.error.log

</VirtualHost>`
