### ISSUE TITLE
can not delete first app in cloud or self hosted

### ISSUE THREAD

**Issue by gerhardmpl** [Budibase/budibase#4469]
**Describe the bug**
It is not possible to delete the first app using the cloud (app version 1.0.57) or self hosted (app version 1.0.62) budibase

**To Reproduce**
1. create an app (e.g. "MyFirstApp") starting with an empty instance of budibase (adding a table for the app in the process)
2. goto the "My apps" list (showing only the "MyFirstApp") and click on the ellipsis (three dots for more options) icon
3. depending on the lock status the menu only shows "release lock" or "export" when already released but not more options
4. create another app (e.g. "MySecondApp", again adding a table while doing so)
5. click on the ellipsis icon of the second app and you can choose from the full menue: release lock, export, edit, delete, edit icon

**Expected behavior**
The full menue shoud be available even for the first (single) app to delete every app if needed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox
 - Version: 97

**Comment by gerhardmpl** [comment]
**Update**
Need to investigate this issue more since it is working from another device. So maybe more a client side issue and not a bug. Closing the bug for now.

**Comment by gerhardmpl** [comment]
**Cause**
The issue was related to the browser zoom level, in which the top most apps ellipsis opens to the bottom but is only partly shown (one line). Changing the zoom level gave either room enough to fully display or made the menu open to the top.

**Comment by MentalGear** [comment]
The problem still persist. If there's only 1 app, the menu doesn't contain a Delete entry.

**Comment by mrkking** [comment]
^ un-publish app first then delete
