### ISSUE TITLE
Access to slack

### ISSUE THREAD

**Issue by HugoLd** [Budibase/budibase#449]
@mjashanks @joebudi @shogunpurple 
Hi, i saw a slack link in the doc but couldn't access to it.
I don't know if it's a mistake or a reserved access to teammates
It could be great to have a community channel on slack or discord to talk to contributors or even users

**Comment by shogunpurple** [comment]
@HugoLd hi there! We now have a discord channel for collaborators. The invite link has been added to the README.

**Comment by HugoLd** [comment]
@shogunpurple it seems that you added the number of connected members widget but not the invite link

**Comment by joebudi** [comment]
Hey

The following link should work.

https://discord.gg/YX2g7y

The link will expire in 24hrs.

Soeak soon, 

Joe

**Comment by mjashanks** [comment]
I added a permanent discord link to the Readme: https://github.com/Budibase/budibase/commit/856d0102178decb39ce0d1dca7ac1d6b4b07da47
