### ISSUE TITLE
budibase/proxy container not working correctly with port other than 80

### ISSUE THREAD

**Issue by nobodyshome** [Budibase/budibase#4521]
**Describe the bug**
budibase/proxy container (Nginx) is losing/not using the port supplied in the .env (MAIN_PORT)

**To Reproduce**
1. Launch the docker compose stack
2. Set "budibase/proxy" to use anything other than port 80 as the external port, eg (default in .env: 10000)
3. Connect to "http://ip:10000/"
4. Redirects you to: "http://ip/builder" dropping the port

**Expected behavior**
The port is maintained for every redirect/route and the page loads

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 98.0.4758.102 (Official Build) (64-bit)

**Comment by Grayda** [comment]
Did you find a good solution for this? I'm using the Budibase Portainer app template and straight out of the box it's doing this. I've only self-hosted Budibase once before (about a year or so ago) and remember having to edit proxy files manually, which I'd rather not do.
