### ISSUE TITLE
Error inviting user but the user is emailed with an invite anyway

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#4522]
**Describe the bug**
When inviting a user to Budibase you sometimes get a "Error inviting user" error message. But the user gets the invitation email but cannot sign up.

**To Reproduce**
1. Setup SMTP
2. Go to Users
3. Click on Add user
4. Fill out their email address
5. Click Add user
6. "Error inviting user" appears

**Expected behavior**
The user does not receive the email if there is an error.

**Additional context**
If you create the user through basic on boarding, the user can reset their password and then gain access.

**Comment by ChristKe** [comment]
I got the same error **"Error inviting user"** but the user gets the invitation email. 
The link from the invitation email works but when i accept the invite, get another error **" Error accepting invitation"**. 
The Users table doesn't get new row.

**Comment by mike12345567** [comment]
Hi guys, this issue should be resolved as of our release yesterday.
