### ISSUE TITLE
Rich text editor buttons are not visable

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#4530]
**Describe the bug**

<img width="1890" alt="CleanShot 2022-02-16 at 15 39 55@2x" src="https://user-images.githubusercontent.com/49767913/154300384-1d18184f-7b99-4805-a79d-22147e7aa72a.png">

**Comment by joebudi** [comment]
This app is published and can be accessed:
https://bb.budibase.app/app/notesapp#/notes/new/row

**Comment by shogunpurple** [comment]
Ah - looks like an issue with our CSP in our proxy again. I can push an updated proxy image that should fix it

**Comment by shogunpurple** [comment]
Fixed - try now 👍

**Comment by joebudi** [comment]
Working! Cheers!
