### ISSUE TITLE
Lightning bolt panel does not update value in settings

### ISSUE THREAD

**Issue by jeestirlingdev** [Budibase/budibase#4538]
**Describe the bug**
I am using the cloud hosted .budibase.app with a MySQL backend. In the Design screens whenever I click the lightning bolt, update the handlebars code and click save the original value in the Settings panel remains unchanged.

This happens in all contexts where the lightning bolt panel is available

I cannot see any errors in the browser console

**Screenshots**
animated screenshot showing the handlebars token remaining unchanged in settings after being updated in the lightning panel
![lightningpanelupdateattempt](https://user-images.githubusercontent.com/7762979/154380773-f8ffd75d-e2da-46b5-a1e0-6cc32f28c426.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 98 and Firefox 97

**Additional context

**

**Comment by dannyshin76** [comment]
Exactly same with my issue, I'll delete mine (https://github.com/Budibase/budibase/issues/4537)

**Comment by Topener** [comment]
Hi @jeestirlingdev and @dannyshin76. Thanks for reporting this issue.

We're able to reproduce on our end, it looks like a recent change caused this issue. We're trying to push out a fix as soon as we can! Until then we recommend copying the handlebars directly into the field in the sidebar so you can at least use this functionality until it is fixed.
