### ISSUE TITLE
Cannot create a save button on the :id screen

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#4539]
**Describe the bug**
Cannot create a save button on the :id screen. When selecting the save row option in the define actions section, the browser page freezes with an error appearing in the console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an app
2. Create a BB db and table and add some columns
3. Create an auto generated screen for the table 
4. Navigate to design
5. Select the table:id view
6. Create a new button
7. Click Define actions
8. Select Save row
9. An error appears in the console and the page freezes and you have to refresh the page to regain functionality.

**Expected behavior**
When selecting the save row option the correct options appear that will allow you to save the row

**Screenshots**
![image](https://user-images.githubusercontent.com/97764630/154386564-33dbca2f-28a2-43ec-a87e-412973b80aed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - 98.0.4758.80
 - Budibase Version: 1.0.67

**Additional context**
Existing / Auto created save buttons work fine. Only new ones created manually are affected. Also copying and pasting an existing save button works.

**Comment by aptkingston** [comment]
Thanks for reporting @FlaminWrap. Have a fix pushed and will release shortly.

**Comment by FlaminWrap** [comment]
Thank you. This is working as expected after updating to 1.0.68.
