### ISSUE TITLE
Export App Without Rows

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4552]
**COS**
- Allow export of apps without row records
- Use filtered couchDB replication to achieve this
- This should be configurable on the app export as either a toggle or separate modal

**Comment by dougwettlaufer** [comment]
This feature would be really helpful for us. We'd like to build out an app in stage and then export just the app so it can be imported into our production instance. Grafana does something similar where you export the dashboard and it parameterizes the datasources. That way when you import it somewhere else it prompts you to fill in the datasources it needs with what you have set up.

**Comment by geertvanheusden** [comment]
It seems that this useful feature is not yet part of the self hosted version. Will it be integrated there as well?
