### ISSUE TITLE
Cannot edit Handlebar or Javascript value settings

### ISSUE THREAD

**Issue by Kuuchuu** [Budibase/budibase#4556]
**Describe the bug**
I am no longer able to make any changes to any text fields that make use of Handlebars or Javascript Functions. Changes are not saved.

**To Reproduce**
1. Select element
2. Click on 'lightning bolt symbol
3. Edit Bindings
4. Save changes
5. No changes take

**Expected behavior**
Changes should save

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux solus 5.14.21-210.current SMP PREEMPT Sun Dec 5 21:23:09 UTC 2021 x86_64 GNU/Linux
 - Browser: Brave
 - App Version: 1.0.67

**Comment by mike12345567** [comment]
Hi @Kuuchuu we've released a new version to fix this - 1.0.68 was released earlier today to address this issue.

**Comment by Kuuchuu** [comment]
@mike12345567 Awesome, thanks! I'll pull it now and give it a try!

**Comment by Kuuchuu** [comment]
It's working for me now, thanks!
