### ISSUE TITLE
Element Tree Visibility Issues

### ISSUE THREAD

**Issue by Kuuchuu** [Budibase/budibase#4557]
**Describe the bug**
I am unable to see most of the elements inside of the Element Tree, as they are nested too deep. Any way we can get a horizontal scroll bar for the Element Tree once it gets too large?

**To Reproduce**
1. Nest too many elements...

**Expected behavior**
Once nested elements go beyond the width of the tree, a scroll bar should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/20036947/154570963-ad5a098b-ddb8-4000-9e08-f0f8bf7ed465.png)

**Desktop (please complete the following information):**
 - OS: Linux solus 5.14.21-210.current SMP PREEMPT Sun Dec 5 21:23:09 UTC 2021 x86_64 GNU/Linux
 - Browser: Brave
 - App Version: 1.0.68

**Comment by Kuuchuu** [comment]
I am still majorly affected by this issue. I can no longer click on the 3 option dots on some of my elements, preventing me from duplicating elements. This seems like a relatively important issue to fix, unless I am just obviously using the software incorrectly. A horizontal scrollbar would fix this issue.
![image](https://user-images.githubusercontent.com/20036947/157113191-131a7b66-897e-4bf2-b7db-73752253167e.png)

**Comment by Kuuchuu** [comment]
I've found there is a horizontal scrollbar, unsure if it was recently added, but the tree still does not function/display correctly once they reach a certain depth, one that expands past the width of the Element Tree panel.
![image](https://user-images.githubusercontent.com/20036947/158854869-8109da59-3ee6-4309-bbea-5848a64c5f7d.png)

**Comment by joebudi** [comment]
@Kuuchuu I do apologize. This has been an issue we've been wanting to fix for a while. We plan on updating the design UI/UX over the next few weeks. We were hoping to include a fix for this then but I'm not sure we can wait that long. I will chat with our designer/team over the next few days and we'll see if we can agree on a quick fix that we can hopefully deploy sooner than we originally planned.

**Comment by aptkingston** [comment]
Just a quick update to say we haven't forgotten about this - here's what we're thinking of as a solution!
https://user-images.githubusercontent.com/9075550/159046276-eb4176e8-3458-4869-8024-f2f97f421c6d.mp4

**Comment by joebudi** [comment]
This is great @aptkingston and miles better than the quick solution I had in my head. Super job!

**Comment by Kuuchuu** [comment]
Thank you @aptkingston and @joebudi 
I truly appreciate it!
