### ISSUE TITLE
[BUDI-7805] DayJS Support in JS Scripting

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4564]
As a user, when I am writing JS scripts inside budibase i want to have access to dayJS methods so I can perform logic on date objects.

**COS**
- Expose dayJS API in JS Scripting drawer
- Provide docs to show that it is available

**Notes**
We already use some elements of dayJS in our binding system, but it is not exposed.

<sub>[BUDI-7805](https://linear.app/budibase/issue/BUDI-7805/dayjs-support-in-js-scripting)</sub>

**Comment by andreipopovici** [comment]
Here's some recent activity.

I, too, would like to be able to use dayJS functions other than `format()` or `duration()`, specifically `startOf()` and `endOf()`.

Perhaps a `module.exports.dayJS` in https://github.com/Budibase/budibase/blob/v2.2.20/packages/string-templates/src/helpers/date.js ?
