### ISSUE TITLE
Public pages show 'Session not authenticated' when the user is not logged in into console.

### ISSUE THREAD

**Issue by Coding-Muffin** [Budibase/budibase#4582]
**Describe the bug**
Public pages show 'Session not authenticated' when the user is not logged in into console. even if the page is public. 

**To Reproduce**
Steps to reproduce the behaviour:
1. open private window
2. open app (the result that people use)
3. see the error on top

**Expected behaviour**
should allow to see public pages

**Comment by PhilDonaus** [comment]
I am currently having this issue as well. 
![image](https://user-images.githubusercontent.com/20375520/155829204-cf74a4b9-e529-487a-81b1-94e6265a0b24.png)

**Comment by aptkingston** [comment]
You'll see this error if you're trying to read or write data to a datasource that you don't have access to. In Budibase you can control the access levels for each individual table or query. This is independent from the screen roles, which just control what screens users can see.

For internal tables, you can control access using the "Manage access" option above the table. You'll need to set read or write (or both) to public depending on what you want public users to be able to do.

![image](https://user-images.githubusercontent.com/9075550/156021865-95bb0cdd-0511-4804-b23d-a7861fe86292.png)

**Comment by gunar** [comment]
Thank you @aptkingston! This worked.

I think this issue can be closed now.
