### ISSUE TITLE
Latest version of helm chart install on AKS failed...

### ISSUE THREAD

**Issue by Naboo2604** [Budibase/budibase#4583]
**Describe the bug**
Install the latest version of budibase on AKS failed with error: 

> Error: INSTALLATION FAILED: template: budibase/templates/worker-service-deployment.yaml:115:27: executing "budibase/templates/worker-service-deployment.yaml" at <.Values.globals.google.clientId>: nil pointer evaluating interface {}.clientId

Installation a few weeks ago was successful without problems - must be a problem in the latest release (google.clientId?)

**To Reproduce**
1. helm uninstall budibase --namespace budibase
2. helm repo update
3. helm install --create-namespace --namespace budibase budibase/budibase
4. Error: INSTALLATION FAILED: template: budibase/templates/worker-service-deployment.yaml:115:27: executing "budibase/templates/worker-service-deployment.yaml" at <.Values.globals.google.clientId>: nil pointer evaluating interface {}.clientId

**Desktop (please complete the following information):**
 - Azure Kubernetes Service - v1.21.7

**Additional context**
i see changes 10 days ago in worker-service-deployment.yaml - maybe that prevents installation on AKS?

**Comment by astrospective** [comment]
just hit this with a fresh k3s install, so not specific to AKS

**Comment by Janikio** [comment]
Yes. I had the same issue yesterday on my Kubernetes cluster.

**Comment by shogunpurple** [comment]
Hi, 

This one should now be resolved in the latest version of the helm chart - there were some values missing that were added. Please try pulling the latest and deploying again!

**Comment by Naboo2604** [comment]
Hi,

after `helm repo update` - the installation was now successful.

many thanks for your fast help!
