### ISSUE TITLE
REST Import Error

### ISSUE THREAD

**Issue by h888t** [Budibase/budibase#4586]
When importing an OpenAPI v3 file, or SwaggerUI v2 file, I get the following error;

index.bb7bb6ed.js:1 [Builder] HTTP 500 on POST:http://127.0.0.1:10000/api/queries/import
	Cannot read property 'getInfo' of undefined

Are there any directions on how to potentially resolve this?

**Comment by egimbernat** [comment]
I'm facing this also

**Comment by shogunpurple** [comment]
Closing in favour of https://github.com/Budibase/budibase/issues/4745
