### ISSUE TITLE
Screen Freeze/Infinite Loop When setting Default Date JavaScript binding

### ISSUE THREAD

**Issue by conorw** [Budibase/budibase#4589]
**Describe the bug**
When trying to set the default date on a DateTime control using JavaScript, the design screen freezes (unresponsive, cpu increasing). 

**To Reproduce**
1. Go to design screen
2. Add DateTime form field
3. Set Default Date binding to JavaScript
4. Add JavaScript of "return new Date();"

**Expected behavior**
The default date should default to today's date

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, latest

**Additional context**
BB Hosted v1.0.68
Only remedy is to delete entire screen or revert project to the previous version.

**Comment by aptkingston** [comment]
Hey @conorw. I know why this is happening - because dates are accuracte to the millisecond, every time a new date is created it is different, which can cause an endless loop of what we call "binding enrichment". I'll have to try and think how we can get around this.

For now, if you just round your date to the nearest second then this issue won't happen:
```js
return new Date(Math.floor(Date.now() / 1000) * 1000)
```

**Comment by conorw** [comment]
thanks @aptkingston, makes sense. cheers for the quick response.

**Comment by superbolt-x** [comment]
Hi! Same issue here

Browser: Brave (Chromium)
BB V : 1.0.73
OS : AWS AMI EC2 Linux with docker-compose

I guess I have to recreate the screen from a backup manually right? Is there any other way like using the BB API to change the default date to the formula above?

**Comment by aptkingston** [comment]
Hey @superbolt-x. Yea that's a good point - if the screen is locked then there isn't an easy way to delete the component. I'm going to see if I can get a quick patch in that would actually fix this issue - then all you would need to do is update your app to the latest version.

**Comment by thehowl** [comment]
@aptkingston hey there, just had this issue while trying to play around budibase the first time... it's still happening? tested on latest docker containers and firefox.

**Comment by aptkingston** [comment]
Hey @thehowl. Our next release is targetted to go out on Monday and will fix this once and for all. The changes in #5010 should prevent this ever happening.
