### ISSUE TITLE
Embed Iframe blocked due to Policy directive: "frame-src 'self' 

### ISSUE THREAD

**Issue by mrbarletta** [Budibase/budibase#4594]
**Describe the bug**
IFrames are not shown due to Policy directive: "frame-src 'self'

Also, the chat embedded on the cloud version, also shows this behavior, I wanted to answer the "Would you recommend to a colleague" and got the very same error. (picture attached.

**To Reproduce**
1. Go to design
2. Click on EMbed, return an iframe from the javascript editor.
3. Preview

**Expected behavior**
Render the Iframe

**Screenshots**
![image](https://user-images.githubusercontent.com/2429244/154885839-9b7a30d5-342f-4b8d-95a3-e72ac050d533.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome 98
 - Version 1.0.68 Cloud

**Additional context**

**Comment by shogunpurple** [comment]
Thanks @mrbarletta - we recently added a content security policy to the platform to increase security. This is a valid point - the embed/iframe component is not useful if we use `self` for iframes. We will update the policy to allow this to work as expected.

**Comment by sergey-dme** [comment]
Similar problem with using external bg images in Custom CSS :( 
it works fine in v1.0.35 but not in latest/newer one.

**Comment by mrbarletta** [comment]
@shogunpurple how could I help? 
From what you say looks like an easy fix/rollback and for many apps this is quite a bummer!

**Comment by mrbarletta** [comment]
Linking related issues #4745 #4748

**Comment by shogunpurple** [comment]
Hi @mrbarletta - I'll get the CSP updated for this today - sorry for the delay!

The ones for the other issues should be resolved now also.
