### ISSUE TITLE
Use template from website is broken

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4606]
When I try to use a template directly from https://budibase.com/templates  it does not work:

![image](https://user-images.githubusercontent.com/3524181/154984361-2d439ffe-95eb-41cf-8b21-bee47629beb9.png)

I am already logged into my tenant. In dev tools , the call to `POST /api/applications` fails with

`{"message":"unexpected response Forbidden","status":400}`

**Comment by shogunpurple** [comment]
Seems like this is only happening on the [Vacation Request Form Template](https://budibase.com/forms/templates/vacation-request-form-template/)

Might be a misconfiguration on that side - will have a look!

**Comment by berief** [comment]
Hello, were you able to solve the problem already. We would be really grateful.  Greetings from Germany!

**Comment by mslourens** [comment]
fixed in PR https://github.com/Budibase/templates/pull/33
