### ISSUE TITLE
Set Default Date - Cannot Change from default value

### ISSUE THREAD

**Issue by conorw** [Budibase/budibase#4609]
**Describe the bug**
When you set a default date for a datetime picker, you cannot change the initial value

**To Reproduce**
1. Add a form. Custom data type
2. Add a date picker
3. Set the default date using handlebars or JS
4. Attempt to click on date control to change the date

See video below
https://crvideos.bonjoro.com/r/260d122f-1013-4370-bb2c-74550688aba6

**Expected behavior**
Date picker should change value

**Screenshots**
https://crvideos.bonjoro.com/r/260d122f-1013-4370-bb2c-74550688aba6

**Desktop (please complete the following information):**
Windows 11, Chrome Latest
BB Latest

**Additional context**

**Comment by aptkingston** [comment]
Thanks for raising this @conorw, I'll get it fixed. In the meantime, if you quickly double click on the same date it will work!
