### ISSUE TITLE
REST - SSL Self-Signed Cert error bypass

### ISSUE THREAD

**Issue by Gamechiefx** [Budibase/budibase#4615]
I am in an environment where a requirement to perform API calls with Self-signed certs. 

![image](https://user-images.githubusercontent.com/14176836/155029890-1625d047-79e5-44fa-ae6a-a800478446e6.png)

I am looking to bypass this error in budibase

**Comment by b509** [comment]
Hi @Gamechiefx were you able to circumvent it or import your self-signed cert somewhere as trusted?

**Comment by FocusDesigner** [comment]
I'm also struggling to make budibase accept self signed certificates. Is there a solution for this already?

I tried to add `NODE_EXTRA_CA_CERTS: /app/cacert.crt` in my docker compose with the cert in place based on this thread 
[https://github.com/Budibase/budibase/discussions/3917](https://github.com/Budibase/budibase/discussions/3917) but this doesn't seem to have an affect. Still get this Error

**Comment by dwesthuis** [comment]
Please help, same problem here:

Query Error: request to https://xx.xx.xx.xx:xxxx/xxxxxxx? failed, reason: self signed certificate

**Comment by Gamechiefx** [comment]
Sorry to resurrect this but I'm still having the same issue.
