### ISSUE TITLE
Doesn't recognize correct data types while fetching MS SQL tables

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#4652]
**When fetching Microsoft SQL Server tables it always recognizes text data type.**
This is a big problem for us, we work with a lot of "bit"-columns (which should be Boolean in BudiBase) and with number columns (money, decimal, float), which should at least be recognized as a number.

**Comment by dewdeded** [comment]
I second this issue. We see the same problem.

**Comment by mike12345567** [comment]
These data types are now recognised for MS-SQL tables in the latest release of Budibase.
