### ISSUE TITLE
Automations allows me to run test, with an invalid setup

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4659]
I originally reported this: https://github.com/Budibase/budibase/issues/4658, but discovered the cause.

In my `Query Rows` step, I had not completed the setup. I did not set the `limit`, `sort column` or `sort order` values. So , when I ran the test, no rows were returned.

Once I set these values, the rows were returned.

I should not be allowed to run the test with an invalid setup. I think we should also be more clear when the setup is invalid - this trips me up quite a lot as it disables adding a new step.

**Comment by melohagan** [comment]
I don't think this is a problem anymore, as the limit value is defaulted and I was able to receive rows back without setting any of those.

I've got a PR out to display the default limit value, which should help to clarify for users in this scenario: https://github.com/Budibase/budibase/discussions/5685
