### ISSUE TITLE
REST Query Params with "=" in them get truncated at first "="

### ISSUE THREAD

**Issue by Zebble** [Budibase/budibase#4667]
**Describe the bug**
When a Query is added for a REST data source, and a parameter is added with a value that has an "=" in it, the query will work on first try but after saving and going back into the query, the value is truncated to the first "="

**To Reproduce**
1. Go to the REST datasource.
2. Click on '+ Add Query'
3. Add your query URL
4. Add a param.  Enter a key name. (eg. 'conditions')
5. Enter a value:  eg.  board/name="Service" and summary like "The system %"
6. Save it.
7. Send it and it works.
8. Exit out of the query screen and then go back into it.
9. The "value" for the key is now truncated.  eg.  board/name

**Expected behavior**
Value should retain the full value, even if it contains "="

On version 0.11.3 of Budibase

**Comment by dubbya** [comment]
Can confirm, seeing same issue

**Comment by aptkingston** [comment]
I've added a PR to support this, but please make sure that whatever REST API you are hitting is able to parse this query.

**Comment by Zebble** [comment]
Thanks @aptkingston !  I had confirmed the REST API call we were using worked previously.  FYI, the software we're making REST calls to is called ConnectWise Manage.  [https://www.connectwise.com/platform/business-management/manage](url)
