### ISSUE TITLE
Read QR code(s)

### ISSUE THREAD

**Issue by skotzko** [Budibase/budibase#4671]
I want to be able to rapidly scan in a QR code and extract the data encoded in it. 

In my use case, the QR code contains metadata about an object that would be laborious and error-prone to have the user enter manually.

Can see this in 2 use cases:
1. Standalone: scan QR codes, extract data, map it directly into fields in Budibase DB, submit data
2. Part of larger flow (my case): my user needs to scan in 2-4 QR codes at a time—for each one, the data extract/map/submit flow should happen—and then manually enter in a bunch of their observations about the objects that are tagged with the QR codes.

**Comment by mike12345567** [comment]
Hi @skotzko - I've linked this issue to the main issue around this #4379 - going to close this issue as it is a repeat.
