### ISSUE TITLE
Local builder after update still has issue #4538

### ISSUE THREAD

**Issue by dannyshin76** [Budibase/budibase#4675]
I see the lightning bolt panel problem (https://github.com/Budibase/budibase/issues/4538) has been fixed on cloud version.
However, I keep experiencing the same problem on the local installation even if I do update.

![image](https://user-images.githubusercontent.com/93232582/155442369-fa21b8c1-30d3-44bf-811a-469960c8bc9b.png)

Is the fix still not available for local builder? Please advise.

**Comment by shogunpurple** [comment]
This should be resolved with the release from a few days ago. Can you confirm that your watchtower instance is running, and possibly try a manual update through either the budibase CLI or docker-compose?

**Comment by sergey-dme** [comment]
I have the same issue. 
Updated through the budibase CLI  `cli-win hosting --update`

**Comment by dannyshin76** [comment]
Manually redeployed to solve the issue. Got the bug fix right.
