### ISSUE TITLE
Theme slider

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#4694]
**Describe the feature request**
Add a slider to the side navigation to choose your Budibase theme

**Prototype**
[Idea prototype](https://xd.adobe.com/view/2fecdda7-2cd8-470d-8dc3-85406e352f0e-7abf/)

**Mock up**

![image](https://user-images.githubusercontent.com/99655473/155708593-df02a826-87a8-4703-935a-8f47535c346d.png)

**Comment by shogunpurple** [comment]
Closing as dupe of new Theme Panel
