### ISSUE TITLE
Signup Process UX

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#470]
We need a smooth, understandble signup process. This is the most likely time for  someone to drop off.

This needs some thought. Also bear in mind that eventually we will probably want to allow login via the builder (thus skip the copy/paste API key bit)... i.e. Keep in mind what improvements we can make for minimal effort

Here is some feedback from one of our beta users

> When clicking the first next button in the create a new account screen, is the account created?
> 
> Sign-up button text should be more descriptive
> 
> What part of building a web app do you find most difficult? Coding should be an option.
> 
> Reduce the number of questions - who are they and what are they trying to build.
> 
> On the download success screen, be more explicit. Always be obvious and descriptive. The text is wrong and includes a link which goes nowhere.

**Comment by joebudi** [comment]
In addition to the above, the 'happy for us to track you' screen does not work, has a broken link, and we now have a better idea of how to communicate this type of screen. I feel we should delete this, along with 'what part of building a web app do you find most difficult?'

**Comment by joebudi** [comment]
@kevmodrome as I previously commented:

_When a user signs up, we ask multiple questions that we don’t record and are pretty pointless (at the moment). We also have a download screen, where the user clicks download, it takes them to the hosting platform.
I feel, it would easier and quicker if the signup process was: User provides email, password, clicks signup > is taken to the hosting platform, where they can download BB.

I think we should remove them for now. This will temp solve a lot of the above issues.

**Comment by joebudi** [comment]
@kevmodrome ... @victoriasloan is looking at the API UX. I will remove the API action from this issue, and create a new one that focuses only on the API UX.
