### ISSUE TITLE
Clicking the pencil icon on a column while in a view can cause a soft lock.

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#4723]
**Describe the bug**
If you click the pencil icon while in a view it can cause it soft lock and you have to refresh the page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a BBDB table
2. Create a column
3. Create a row with any data
4. Create a view
5. Navigate away from the view (e.g. back to the table you created in step 1 or refresh the page)
6. Navigate back to the view you created in step 4
7. Press the pencil icon on any column
8. Error below should appear in browser console

**Expected behaviour**
The edit column menu works like it does on the table screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/97764630/155903457-183f1cb5-cb80-475c-b71b-7d912dd4b593.png)

**Additional context**
It does not happen with views that you have just created and have not navigated away from.
Budibase version: 1.0.73

**Comment by aptkingston** [comment]
Thanks for reporting @FlaminWrap. I'm seeing this too 👍
