### ISSUE TITLE
bbproxy - host not found in resolver

### ISSUE THREAD

**Issue by amit-techsur** [Budibase/budibase#4728]
**Describe the bug**
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/02/28 03:58:53 [emerg] 1#1: host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/nginx.conf:22
nginx: [emerg] host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/nginx.conf:22
```
**To Reproduce**
1. deploy budibase in k8s with cluster different than "cluster.local"
2. Check proxy log

**Expected behavior**
Proxy should start

**Additional context**
cluster.local is hardcoded in ngnix.conf.  It doesn't use service.dns value to resolve host.

**Comment by 0cwa** [comment]
According to [stackoverflow](https://stackoverflow.com/questions/71773485/budibase-helm-deployment-host-not-found-in-resolver-kube-dns-kube-system-svc-c)  you can circumvent this bug by "creating a kube-dns service with the same spec as the coredns one". How would one do that?

**Comment by riimak** [comment]
I had the same issue so I've downloaded the chart locally and added to the proxy-service-deployment.yaml the following:

`        command: ["/bin/bash", "-c"]
        args: 
          - 
            /bin/sed -i 's/kube-dns/coredns/g' /etc/nginx/nginx.conf
            && /bin/sed -i 's/cluster.local/{{ .Values.services.dns }}/g' /etc/nginx/nginx.conf
            && nginx -g 'daemon off;'
`

In our clusters we use coredns, you can omit this line if you are using kube-dns or update the snippet with your DNS resolver.

Hope this helps.

**Comment by scheibling** [comment]
This seems to occur on two conditions:

1. Using another localdomain than cluster.local
2. The kube-dns service not being called kube-dns (like with RKE2 where it's called rke2-coredns-rke2-coredns.kube-system.cluster.local)

In the second instance, you can resolve this by setting up the following service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: "kube-dns"
spec:
  type: ExternalName
  externalName: "rke2-coredns-rke2-coredns.kube-system.svc.cluster.local"
```

Apply this to the namespace kube-system. This is basically a CNAME record for the dns service, telling it to forward kube-dns to whatever your local DNS is called.

This won't help with the non-standard localdomain though, but in case anyone stumbles upon this with the second issue this resolved it for me.

**Comment by osso-rkuper** [comment]
If you are using CoreDNS you can actually change the resolver value to use CoreDNS:
```
services:
  proxy:
    resolver: coredns.kube-system.svc.cluster.local
```
I believe this should also fix issue #5306

**Comment by shogunpurple** [comment]
Hi folks - this is now controllable through the `RESOLVER` environment variable that you can set in your `values.yaml`. I've updated the docs here with how you can configure this in your `values.yaml`.

https://docs.budibase.com/docs/kubernetes-k8s#nginx-proxy

**Comment by erSitzt** [comment]
@shogunpurple  is your answer still valid ? i did not find anything related to resolver in the values.yaml or the docs
