### ISSUE TITLE
Improve Handlebars/JS UI for bindings in REST Connector Dynamic Variables

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4736]
I have verified the below discussion. I cannot seem to get dynamic variables to work. See video below - happy to have my errors highlighted. 

My setup
1. Running a local api
2. Create query that runs a `get`, which returns a body like `{ "key" : "1234" }`
3. Assign `key` to dynamic variable called `key` like `key : {{ data.key }}`
4. Create a second query that runs `post /verify`, with a body of `{ "key" : "{{ key }}" }`

The query fails, with no useful error. It does not even reach my API

If I remove run `post /verify`, with a body of `{ "key" : "1234" }` - i.e. without the binding, it works.

https://user-images.githubusercontent.com/3524181/156016090-6e94dbc3-a69d-4233-91e6-aece0ac7b2d8.mp4

### Discussed in https://github.com/Budibase/budibase/discussions/4719

<div type='discussions-op-text'>

<sup>Originally posted by **kdavis5** February 26, 2022</sup>
Hello,

I have read the documentation and believe I am following it properly but cannot seem to get this to work. Please advise if I am missing something. 

I am using a Cisco ACI APIC as a data source. It requires an authentication POST with username/Password and returns a cookie in the set-cookie field (I assume pretty standard). 

1. I send a query to authenticate. I get a 200 response and I create a dynamic variable from the returned set-cookie field. 
6. I name that "cookieACI"
7. I make a second query in the same data source with an added header, key=Cookie, and value={{cookieACI}}
8. I get an error "Error running query"

IF, I paste the cookie value from the first query directly into the second queries header value..... it works. I am testing and reviewing what Postman is doing and trying to replicate here.

IF, i add [ ] within my variable like this {{cookieACI[]}} - I do not get the error, query sends but of course the response is a 400 level. 

I am a noob with development so I hopefully am missing something small. 

Also, is there a way to force run the authentication query before other queries to ensure authentication takes place? Still reading and getting acquainted. 

Any help is greatly appreciated!</div>

**Comment by Rory-Powell** [comment]
I think the binding should be
```hbs
{{ data.0.[key] }}
```
Can verify by using the `Create dynamic variable` from the schema response.

**Comment by mjashanks** [comment]
I'm getting the same issue

https://user-images.githubusercontent.com/3524181/165501869-b3803996-8bbf-41f9-8120-3580805ebb71.mp4

**Comment by Edwin-Joe** [comment]
Is it resolved? why is this closed?

**Comment by lakicv** [comment]
> Hi @Edwin-Joe yes this was resolved - the issue was that you need to save your REST query after creating dynamic variables for them to be usable.

It does not seem to be fixed. Shouldnt the dynamic variables appear in the bindable values when using handlebars for header values?

**Comment by mike12345567** [comment]
Hi @lakicv - you just first configure your bindings, as well as static/dynamic variables before you can use them. If you use a handlebars value in a header, it will not exist until you've configured in somewhere, either through bindings:
![image](https://user-images.githubusercontent.com/4407001/187931690-9611d465-3648-4a89-a8de-c1ba738b2c85.png)

Or through a variable:
![image](https://user-images.githubusercontent.com/4407001/187931825-82f42ce5-271d-4a31-8796-64b0a0c33a5e.png)

**Comment by lakicv** [comment]
hey @mike12345567
I did configure the dynamic variable but it only appears in the handlebars for the query in which it was created. The variable is not available in other queries.

I thought that that should be possible or am I wrong?

**Comment by mike12345567** [comment]
Hi @lakicv - you should be able to use it once you have saved the query - it won't appear in the list anywhere (this is something we are working on) but if you reference it in another query it will work.
E.g. you can see based on the dynamic variable I saved within a different query I can send it in the body here:
![image](https://user-images.githubusercontent.com/4407001/187934765-7d5a9330-4b3e-408b-9065-29f64fb70441.png)
On the webhook I get: 
![image](https://user-images.githubusercontent.com/4407001/187934827-bc3d04de-98a7-42e1-bbad-d00b9483e5c1.png)
