### ISSUE TITLE
Form > Select appears selected but the value does not save

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#477]
1. add a form to your web app, that has a select field (a "string" with "Categories")
2. Open your app, and navigate to screen with form on it
3. DO NOT CHANGE the select (i.e. it appears to be selected)
4. Save
Result: the record saves with an undefined value for the select field.

Simplist solution for now, is to add a blank option as the first option in the dropdown.... so it appears as nothing is selected (which is the truth)

**Comment by joebudi** [comment]
@mjashanks is this done?

**Comment by mjashanks** [comment]
Yes
