### ISSUE TITLE
Firefox asking to save MySQL port/password

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4772]
See below. Had a quick google - this seems to be relevant: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

### Discussed in https://github.com/Budibase/budibase/discussions/4753

<div type='discussions-op-text'>

<sup>Originally posted by **diogenesbrussels** March  1, 2022</sup>
Hello,

I got this strange situation with Firefox:
- I'm logging in as administrator on a self-hosted Budibase instance.
- I open an application to modify it.
- I want to edit a table in a MySQL connection.
- The Firefox password save prompt appears to keep the username: 3306 and the database password.
![mysql firefox save password](https://user-images.githubusercontent.com/91942877/156162400-4c45a709-6c9f-454b-b858-c0bc405ca0d3.png)

Firefox 97.0.1
Budibase 1.0.73

This is not a problem for me but if I allow one of my "less technical" colleagues to change something he might be disturbed.</div>

**Comment by melohagan** [comment]
I had a look the suggestion and a number of related StackOverflow posts but nothing worked. 
I think the general gist is that the user and the browser should be in control of whether or not a password field should be saved, and not the developer. 

One idea I had is that you could have the username & password for a datasource be hidden fields in the form. 
Then you could have a button that opens a credentials modal that includes the password field. Clicking save passes the password field value through to the hidden text field on the form.

Is it worth it?
