### ISSUE TITLE
Cannot reuse one binding in the same SQL Query

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4779]
### Discussed in https://github.com/Budibase/budibase/discussions/4768

I have reproduced like so...

1. Add a custom query...

(this is a very contrived example - but have a look at the discussion to see a real example)

```sql
select *, '{{name}}' as Name, '{{name}}' as Name2 from customers;
```

In the results section, I can see that this returns:

```json
{
  "id": 22,
  "name": "{{name}}",
  "email": null,
  "age": null,
  "dateOfBirth": "2022-02-03T00:00:00.000Z",
  "jobDone": null,
  "personJson": null,
  "uuid": "a8bb354b-2791-4292-9da8-69f0332989cd",
  "name2": "{{name}}"
}
```

now, if I change my SQL to

```sql
select *, '{{name}}' as Name from customers;
```

it returns

```json
{
  "id": 22,
  "name": "michael",
  "email": null,
  "age": null,
  "dateOfBirth": "2022-02-03T00:00:00.000Z",
  "jobDone": null,
  "personJson": null,
  "uuid": "a8bb354b-2791-4292-9da8-69f0332989cd"
}
```

**Comment by mike12345567** [comment]
This issue will be resolved in our upcoming 1.0.80 release, which should be released in the next day or two.
