### ISSUE TITLE
Inviting user email field error & incorrect label

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#4790]
### Problem

1. On the option to invite a basic user, the label says `Username` when it should say `Email address`

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/ea1ce519-16d5-46b9-b460-fcd768cdbe9b)

2. We currently show an error for an invalid email before the user tries to submit an invalid email on both user invite options. It's not a major issue but just not a nice UX.

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/0eefea6a-da2e-4208-a006-a1b8a51a9400)

### Solution

Fix the label
Don't show this error until the user submits an invalid email

**Comment by mslourens** [comment]
The onboarding label will be changed in PR #4639
