### ISSUE TITLE
Column defaults to sorting values as text

### ISSUE THREAD

**Issue by Kuuchuu** [Budibase/budibase#4804]
**Describe the bug**
Users are unable to sort a table based on its "Count" column, as it sorts it like it is text rather than a number. Screenshot of issue provided.

**To Reproduce**
1. Add data to table element.
2. Click on the "Count" column to sort

**Expected behavior**
Should sort based on numerical order rather than alphabetical.

**Screenshots**
![image](https://user-images.githubusercontent.com/20036947/156901521-6e912b69-e13c-4372-be9c-a66ab8bb550a.png)

**Desktop (please complete the following information):**
 - OS: Linux solus 5.14.21-210.current SMP PREEMPT Sun Dec 5 21:23:09 UTC 2021 x86_64 GNU/Linux
 - Browser: Brave
 - Version: 1.0.73

**Comment by mslourens** [comment]
I tried to reproduce your issue, both with an internal Budibase table, MySQL and Postgres, but without any luck. The order of all tables are correct. Is the data type of your `count` column a Number? Which type of data source did you use?

**Comment by Kuuchuu** [comment]
@mslourens I am using a REST API data source, connected to NocoDB. The value in NocoDB is stored as a number. Every attempt I've made using a JavaScript transformer to recognize the count column as a number data type has not worked, Budibase has always shown all columns as data type text for me, on all of my data sources.
This is from the current data source I'm working with:
![image](https://user-images.githubusercontent.com/20036947/157113733-8ae60ae5-dd29-4b68-af80-3283f4d24d75.png)
This is from another REST API data source that I am using: 
![image](https://user-images.githubusercontent.com/20036947/157114427-9b5dcc7d-e3c6-4f5a-b873-1902d91503f3.png)
I've never had the scheme state anything other than text.
My latest JavaScript transformer attempt to get the value recognized as a number:
```
count = count.map(function(obj) {
    return {Item: obj.Item, Count: parseInt(obj.Count)};
});
return count.reverse()
```
I can post the entire transformer if needed.
Thanks for taking a look into my issue, I appreciate it.

**Comment by mslourens** [comment]
you don't have to use a transformer, you can simply select Number from the schema dropdown for the number fields. After you selected all the correct field values, you should click Save again. This will update the schema, and will let you order by number as you would expect. 
As a test I just created a simple API, which I then added to Budibase. After adding the query I defined the schema like so:
![image](https://user-images.githubusercontent.com/1907152/157133401-2c227088-4625-429f-858a-8aa5334644e6.png)

After creating a screen with a table using my query as a data source, I can order the permissionId column correctly:
![image](https://user-images.githubusercontent.com/1907152/157133632-bf396454-9558-449b-8a98-96b405657333.png)

**Comment by Kuuchuu** [comment]
@mslourens Sorry about that, I swear I've changed that before and it just reset itself back to text. No luck though. I made that change and it still sorts it in the table like it is text when I click on the column name.

**Comment by estiller** [comment]
Hi, I tried using Budibase and encountered the same issue. It works fine with SQL data sources, but when I try to add a REST data source, the table sorts numeric columns in alphabetical order.

I ensured that my API was actually returning numbers, and I set the appropriate column to a `Number` type in the schema. Still no luck. When I look at the data preview in the Data screen, it sorts by numbers just fine. But when I show the column in a UI data table, the column sort is done alphabetically. No matter what I did, I just couldn't resolve this behaviour.

The same issue is described in https://github.com/Budibase/budibase/discussions/5757.

Are there any possible workarounds for this?

**Comment by melohagan** [comment]
Hey @estiller 

I have found a workaround, as well as more precise reproduction steps:

1. Add a Data Provider with REST query (that returns a number via the Number type selected in the query schema)
2. Add a table
3. See that the sorting is alphabetical
4. In the Data Provider set the *Sort Column* to the number field of your query
5. Refresh the page
6. Sorting is now numeric

**Comment by froster12** [comment]
I am having this problem with MySQL, using a table block. Even though it sorts properly when the user clicks on the table heading, the parameters - Sort Column + Sort Order - do not work. It sorts text fields correctly but not numbers.

Also, I am noticing that it looks like there's a problem saving the MySQL query schema.
