### ISSUE TITLE
S3 New Form Upload Field - Cannot Connect my S3 Source

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4814]
### Discussed in https://github.com/Budibase/budibase/discussions/4515

<div type='discussions-op-text'>

<sup>Originally posted by **superbolt-x** February 15, 2022</sup>
Hi!

I connected and tested my S3 source using s3.us-east-1.amazonaws.com as endpoint and worked. But then not sure when I use an S3 upload form field component how to select that source, the option "S3 Datasource" is empty. Tried also with a DP with the S3 query but nothing

How should I proceed? [Self Hosted on AWS EC2 - BB v1.0.62]

Thanks so much!</div>

**Comment by daawaan** [comment]
Hello @shogunpurple, this issue persists in the latest version, the S3 datasource remains empty even when an S3 datasource has already been added in the application and when the site has been refreshed

**Comment by sergey-vin** [comment]
this was answered in https://github.com/Budibase/budibase/discussions/5481#discussioncomment-2592309
