### ISSUE TITLE
server running in dev mode  can not use Svelte-Dev

### ISSUE THREAD

**Issue by zhengtulymGh** [Budibase/budibase#4825]
**Describe the bug**
I run server in dev mode, and can access http://localhost:10000/builder in booswer, but cant not use Svelte-Dev

![image](https://user-images.githubusercontent.com/13768025/157039185-4ea15522-cac8-4dff-96a5-836f0e1c4e60.png)

**Comment by mslourens** [comment]
Did you try refreshing the page with the Svelte dev-tools tab open? It should work, I use it all the time:

<img width="1765" alt="image" src="https://user-images.githubusercontent.com/1907152/157054305-dc7e0bcd-420c-45cc-a8e4-d2fea0d63729.png">

**Comment by zhengtulymGh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来件已收到，我会尽快回复您。。。。

**Comment by zhengtulymGh** [comment]
Maybe it's because I run the server by  ```docker-compose up``` [https://docs.budibase.com/self-hosting/hosting-methods/docker-compose](url). However, I can't acess  http://localhost:10000/builder in booswer by running ```yarn setup```, I can only  acess http://localhost:3001/builder/ with 404 error of http://localhost:3001/api/global/users/self  request。
