### ISSUE TITLE
App becomes unusable when S3 upload field is not in a Form

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#4829]
**Describe the bug**
When a S3 File Upload Field is added to a screen outside a Form, the app becomes unusable. Every click fails, nothing is happening or responding to user input. In the console you'll see this error: 
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'props')
    at Object.$$self.$$.update (FormFieldSelect.svelte:15:19)
    at init (index.mjs:1802:8)
    at new FormFieldSelect (FormFieldSelect.svelte:23:39)
```

**To Reproduce**
1. Go to the Design tab
2. Create a new screen
3. Add a S3 File Upload Field to the screen
4. Nothing happens, the app doesn't respond to any clicks, restarting the app does not help either. 

**Expected behavior**
If a field should be added to the form field, but it isn't, it should mention it (which it does in the preview) and the user should be able to add a form and move the form field inside it (or remove the form field, add a form and create a new form field inside it).

**Screenshots**
<img width="1764" alt="image" src="https://user-images.githubusercontent.com/1907152/157057932-f32b4e67-ab54-42c8-a713-f00c7cffa405.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1
 - Browser: Vivaldi
 - Version: develop branch

**Comment by aptkingston** [comment]
That's a weird one @mslourens - that's being thrown because your `currentAsset` is undefined, which is nothing to do with the S3 upload component. I tried reproducing this too and it doesn't cause any errors. If you refresh your page does that still happen?

**Comment by mslourens** [comment]
Yes, I have to remove the component from the screen to continue working with the app.

**Comment by aptkingston** [comment]
Very strange. I'll push a fix which will stop this from happening, but I still don't know how `currentAsset` was ever undefined.

**Comment by melohagan** [comment]
Could not reproduce, appears to be fixed. Closing.
