### ISSUE TITLE
Changing the route of a screen in the settings panel deletes a screen

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#4840]
**Describe the bug**
Currently only one screen is allowed per route - if you attempt to create a screen on a route that is already in use an error will be shown and it will not be possible to create the screen. However if you adjust the screen route from within the settings panel it will allow overwriting an existing screen. The behaviour here is a little inconsistent, sometimes it deletes the screen currently on the route, sometimes it deletes the screen that you were trying to move to the route.

*NOTE* this behaviour can also occur when updating a screens role, if the role you are changing the screen to already has the route in use in it then the same issue will occur.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a screen on route `/`
2. Create a screen on route `/other`
3. Go to the settings panel of the screen on `/other`
4. Change the route to `/`
5. See that one of the screens has been deleted

**Expected behaviour**
Shouldn't have allowed the operation, should have showed an error in some way.

**Screenshots**
Adjusting the route here:
![image](https://user-images.githubusercontent.com/4407001/157230476-558df76c-276d-4ea3-8db5-f02fdf404dd0.png)

**Comment by aptkingston** [comment]
The same thing happens if you adjust the role for the current screen to a role which already has that same route - one will be removed.
