### ISSUE TITLE
Disable login with email

### ISSUE THREAD

**Issue by emrahcetiner** [Budibase/budibase#4859]
I've read through all the documentation, but couldn't see any information about disabling email login. 

I want to disable login with email so users can only log in with Google/OpenID.

**COS**
- Add option to tenant auth settings to turn off email login by default. Show this option in business tier only.
- Lock this down on the backend when the setting is on, to prevent SSO logins at all. Add this code to pro repo.
- If there are password users in the instance when the setting is turned on, prevent them logging in after this is turned on
- Hide the email login UI from the screen when the setting is on
- In cloud, the users must go to the `tenant.budibase.app` URL for this to take effect, as we need to know who the tenant is. For self host this is not as relevant.

**Comment by JayP718** [comment]
+1

**Comment by jonathanfinley** [comment]
+1

**Comment by marian001** [comment]
+1

Until this is done, how can I edit the login screen to comment out the email-login section?

**Comment by itsthisjustin** [comment]
This seems like a major oversight imo. What's the point of offering SSO if the users can simply get around it by resetting a password for their account?

**Comment by mp-strachan** [comment]
+1

**Comment by alexvaut** [comment]
+1

**Comment by nicotriballier** [comment]
+1

**Comment by nicotriballier** [comment]
+1

**Comment by nicotriballier** [comment]
+1

**Comment by melohagan** [comment]
This can be done with the Enforced SSO feature! https://docs.budibase.com/docs/enforced-sso
