### ISSUE TITLE
multi-page tables not printable

### ISSUE THREAD

**Issue by yeoldegrove** [Budibase/budibase#4870]
**Describe the bug**
When having a table with many entries (that do not fit on a single page), they cannot be printed as **no new page is created**.
In print view (`ctrl+p`), budibase seems only to be able to render a single page. The page is not wrapped.
This seems also to be true for other design elements, not only tables.

In general, the print view is not very optimized.
It can be worked around a lot by, e.g. hiding elements like the headers via a "print view button".
But not wrapping/creating any new pages is a major issue here.

**To Reproduce**
1. create a simple page with a table
2. fill table with enough rows to not fit on a single page

**Expected behavior**
Budibase should be able to render multiple pages in print view and wrap pages.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chromium/firefox
 - Version: 97/96

**Additional context**
Tested with latest docker containers `v1.0.82`

**Comment by yeoldegrove** [comment]
@shogunpurple When will this be released?

**Comment by aptkingston** [comment]
The next release is due to go out on Monday.
