### ISSUE TITLE
"fiiltering" for "Contains" on a "Data Provider" is not possible

### ISSUE THREAD

**Issue by yeoldegrove** [Budibase/budibase#4886]
**Describe the bug**
"fiiltering" for "Contains" on a "Data Provider" is not possible.
Other options might as well be missing.

**To Reproduce**
1. Add a "Data Provider" Block
2. Click on "Define Filters"
3. Try to add a "Contains" condition

**Expected behavior**
Filtering by "Contains" should be possible.
This is e.g. possible when creating a "Filter" on a view.

**Screenshots**
![image](https://user-images.githubusercontent.com/8668070/157723628-689d9873-d7c8-4939-b1b5-d1b4ebf1674c.png)
vs.
![image](https://user-images.githubusercontent.com/8668070/157723870-399d84e4-ea79-49f8-875a-9451968c9e1f.png)

**Comment by aptkingston** [comment]
Hi @yeoldegrove. The filtering options available to views are different than what are available to data providers, as views are built on top of our internal database, while data providers need to support all possible datasources. We won't be able to add "contains" here, but hopefully either "like" or "starts with" are suitable replacements.
