### ISSUE TITLE
Filtering by Budibase DB Relationship is not available

### ISSUE THREAD

**Issue by mattdeloach** [Budibase/budibase#4887]
Any Budibase DB relationship columns are not available in filters for automation flows or UI data source components

Reproduction:
1. Create 2 Budibase DB tables with at least 1 row of test data 
2. Create a relationship column and select the other Budibase DB ( use any of the three relationship options )
3. Create a row and select a row in the alternate Budibase dB to establish a relationship -> save column
4. In the design tab, create a new Data Provider component and select one of the Budibase DB's
5. Click Define filters -> Add filter
The relationship column created is not available for selection in the Column dropdown list

** Same result when using the automation Query Rows filter **

Expected behavior would be to be able to filter results based on contents of Relationship column - at least Is empty / Is not empty

I am looking to have a Database of services and be able to link those services to another Database of clients, then be able to filter a list of clients based on a service being related or not

Thank you!

**Comment by mike12345567** [comment]
Hi @mattdeloach - this is currently a limitation of the internal DB. You can get around this by using the "Static Formula" field, which allows you to select information from related rows and create a filterable column from them. The static formulas will be re-enriched each time one of the related rows is updated, so it should stay in sync.

The other option is to make use of a SQL datasource, like Postgres or MySQL, as these are relational databases filtering on relational data is built in.

Closing this issue as support for relationship full filtering on Budibase DB tables is not something we can support at this time.

**Comment by mattdeloach** [comment]
@mike12345567 thank you very much, the static formula type seems to be keeping in sync with updates and is accessible via filters in the instances I've been using. I appreciate the workaround
