### ISSUE TITLE
Bindings not passed correctly to MSSQL Stored Procedure in 1.0.82

### ISSUE THREAD

**Issue by mcerwin** [Budibase/budibase#4890]
**Describe the bug**

When executing an MS SQL query that executes a stored procedure and passing binding values as parameters, the query fails.  This worked prior to version 1.0.82

**To Reproduce**

Execute an Update Query against MS SQL that passes binding values to a stored procedure via handelbars:

**Example Query:**

Exec sp_VXS_UpdateShipDate @InvoiceID = {{ InvoiceID }} , @NewShipDate = {{ NewShipDate }}

**SQL Trace Results**:

exec sp_executesql @statement=N'Exec sp_VXS_UpdateShipDate @InvoiceID = (@p0) , @NewShipDate = ''(@p1)''',@params=N'@p0 nvarchar(8), @p1 nvarchar(9)',@p0=N'22000341',@p1=N'2-28-2022'

I believe the issue is the parens that budibase adds to the query surrounding the parameters during the execution process.  These are inserted automatically by the app and there is no way to compensate in the query.     

Working:
@InvoiceID = @p0

Not Working:
@InvoiceID = (@p0)

**Comment by mike12345567** [comment]
Hi @mcerwin thanks for the report, this will be fixed by PR #4888.

**Comment by mike12345567** [comment]
This issue has been resolved as of the latest release.
