### ISSUE TITLE
Selecting a row in a table with Allow row selection enabled using a REST API data source appears to select all rows

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#4895]
**Describe the bug**
Selecting a row in a table with Allow row selection enabled using a REST API data source appears to select all rows. You also cannot parse the row for data as it is undefined.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a REST API data source
2. Add a query
3. The query should be set a GET `https://gorest.co.in/public/v2/users` (This is a public REST API with dummy data)
4. Send query
5. Save query
6. Create a Screen
7. Add the REST API data source as a data provider component on the screen
8. Create a table component underneath the REST API data provider component
9. You should see data appear in the table
10. Press the play icon at the top right of the page
11. Navigate to the screen you created
12. Click on a table row
13. All table rows are now selected while saying 1 row selected

**Expected behaviour**
Each table row is able to be selected.

**Screenshots**
REST API query
![image](https://user-images.githubusercontent.com/97764630/158058175-8d3d4054-8544-48ee-8a75-d135b1db88f8.png)
Screen layout
![image](https://user-images.githubusercontent.com/97764630/158058030-8785252b-7fa2-49c0-8007-73d497b24426.png)
Table setting
![image](https://user-images.githubusercontent.com/97764630/158058120-27808437-6cf5-4f42-ab8a-03fdd11a435a.png)
Table before selecting a row
![image](https://user-images.githubusercontent.com/97764630/158058093-eb009fe9-3f13-4112-899c-b0c062825296.png)
Table after selecting a row
![image](https://user-images.githubusercontent.com/97764630/158058103-98b559db-0b1c-4616-a634-0901f6211379.png)

**Additional context**
BB version 1.0.82
This only happens with REST API data sources.

**Comment by aptkingston** [comment]
I'm going to close this one off as we've already deployed some changes to prevent row selection being used for custom queries, or non SQL datasources like REST. This feature was designed to target internal tables and SQL tables, so this issue was a symptom of us not properly preventing row selection being used for other datasources.

Row selection for custom queries could be raised as a separate feature request if that functionality is required.
