### ISSUE TITLE
Exporting to CSV using the published applications exports a JSON file with a CSV extension

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#4902]
**Describe the bug**
Exporting to CSV using the published applications exports a JSON file with a CSV extension. This makes it hard to read in Excel.

**To Reproduce**
1. Create a table with a few columns
2. Add some data to the table
3. Create a screen
4. Create a data provider on the screen that is linked to the table created in step 1
5. Create a Table
6. Make sure Allow row selection is ticked or the export button will not work
7. Make a button and make sure it is underneath the data provider
8. Call the button Export to CSV
9. Click the define actions button while the button is selected
10. Click Add an action
11. Select Export Data
12. Select the table created in step 5
13. Export as = CSV
14. Publish the app
15. Open the published app
16. Press the button created in step 8
17. A CSV file will be prompted to be downloaded
18. The file will contain JSON data

**Expected behavior**
A CSV file is prompted to be downloaded in a comma delimited format.

**Screenshots**
Table
![image](https://user-images.githubusercontent.com/97764630/158194328-1ff48178-04b7-45ed-93e0-3174adb14d53.png)
Design view
![image](https://user-images.githubusercontent.com/97764630/158194450-6868d835-8f4e-4f9f-bb36-20ea12077ec6.png)
Button Actions
![image](https://user-images.githubusercontent.com/97764630/158194519-9590bcdc-84f4-4b12-9e48-661a8fd60ee9.png)
CSV file produced
[export.csv](https://github.com/Budibase/budibase/files/8245791/export.csv)

**Additional context**
BB version: 1.0.82
If you change the button to create a JSON file it is exactly the same, just the file extension changes.

**Comment by FlaminWrap** [comment]
Fixed in 1.0.90

**Comment by yagobski** [comment]
How to make select all select others rows in other page not only displayed page (pagination).

**Comment by mr-falken** [comment]
> How to make select all select others rows in other page not only displayed page (pagination).

This is something that is blocking us as well: having thousands of rows in a paginated and filtered table, selecting all rows for every single page is not possible.
