### ISSUE TITLE
Self Hosted 1.0.86 - BB Worker Container and Redis Connection Error

### ISSUE THREAD

**Issue by lollococce** [Budibase/budibase#4904]
**Describe the bug**
Both upgrading self hosted to the 1.0.86 or relaunching BB from that new release get stuck due to some BB worker failure in connecting with Redis.
Hi!
Tried to upgrade my self hosted on AWS EC2 from 1.0.73 to 1.0.86 with the update button on the admin view and got locked out of Budibase - all log in requests were returing in a 502 Time out. Created a new AWS EC2 and git clone 1.0.86 release - but after trying to update organization data on the new Budibase the same Redis error happened with the BB Worker

BB Worker container : "Redis connection failed - ReplyError: NOAUTH Authentication required."

**Comment by lollococce** [comment]
Thank you for the quick reply!!

**Comment by mike12345567** [comment]
Hi @lollococce 1.0.87 has been released with a fix for this.

**Comment by mike12345567** [comment]
Hi @lollococce - what URL are you using to access Redis? As can you give me an idea of the format of your `REDIS_URL` environment variable?

**Comment by mike12345567** [comment]
Hi @lollococce - that is an identical setup to what I'm using - that is very odd.

Just to check, can you confirm that the Updates page within the Budibase Builder does show 1.0.87 as below:
![image](https://user-images.githubusercontent.com/4407001/158237141-f90d53ce-f89e-4365-b694-cd9e2fd11242.png)

And also check that all of the instances have been restarted fully.

I would recommend deleting one of the two files `hosting.properties` or `.env`, we've deprecated the `hosting.properties` file in preference of using the default `.env` now. In 1.0.86 the issue could be resolved by changing the `REDIS_URL` to `redis://default:${REDIS_PASSWORD}@redis-service:6379` for the server and worker and then restarting the instances - that could be worth a try as well to see if the old version is still in use.

**Comment by lollococce** [comment]
Hey!
I was unable to log in because of that error from the BB worker (log in was giving back 502 time out errors) so I could not check the version from the UI

I had to stop and recreate the containers (restart was not enough) with the link you suggested (redis://default:${REDIS_PASSWORD}@redis-service:6379) and worked!
I am now logged in again and seeing version 1.0.85 on the UI!

Just used the Update button from the UI and looks like it's now 1.0.87 and working! Thanks!!

But the link on docker-compose remained the same - not sure what the UI update button does exactly, a git pull?

I mean I can leave the REDIS_URL like that if it works - but trying now to restart docker with the new REDIS_URL

**Comment by mike12345567** [comment]
Hi @lollococce - the easiest way to keep your Budibase install up to date is to use the Budibase CLI, you can install it via NPM/Yarn ([package](https://www.npmjs.com/package/@budibase/cli)) or you can get it as a pre-built binary from the latest [release](https://github.com/Budibase/budibase/releases).

With it you can run it in your compose directory using the command `<BB CLI> hosting --update` and it'll update you to the latest version.

The update button in the UI uses watchtower to make sure the images are correctly up to date, making sure to update the correct images. You can do it with a `docker pull budibase/apps && docker pull budibase/worker && docker pull budibase/proxy && docker-compose stop && docker-compose start` but utilising the CLI makes sure you're always getting the correct images and restarting safely.

**Comment by Bogey** [comment]
I followed the suggestions but I still get "Redis connection failed - undefined". I'm running Budibase via Docker.

**Comment by mike12345567** [comment]
Hi @Bogey - which version of Budibase are you currently running? Also can you check on the state of your Redis docker container?

**Comment by Bogey** [comment]
> Hi @Bogey - which version of Budibase are you currently running? Also can you check on the state of your Redis docker container?

Hi Mike, I pulled the latest images budibase.docker.scarf.sh/budibase/apps and budibase.docker.scarf.sh/budibase/worker
And Redis: 
```
1:C 15 Mar 2022 21:40:57.878 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 15 Mar 2022 21:40:57.878 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 15 Mar 2022 21:40:57.878 # Configuration loaded
1:M 15 Mar 2022 21:40:57.878 * monotonic clock: POSIX clock_gettime
1:M 15 Mar 2022 21:40:57.879 * Running mode=standalone, port=6379.
1:M 15 Mar 2022 21:40:57.879 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 15 Mar 2022 21:40:57.879 # Server initialized
1:M 15 Mar 2022 21:40:57.879 * Loading RDB produced by version 6.2.6
1:M 15 Mar 2022 21:40:57.879 * RDB age 2028 seconds
1:M 15 Mar 2022 21:40:57.879 * RDB memory usage when created 0.77 Mb
1:M 15 Mar 2022 21:40:57.879 # Done loading RDB, keys loaded: 5, keys expired: 0.
1:M 15 Mar 2022 21:40:57.879 * DB loaded from disk: 0.000 seconds
1:M 15 Mar 2022 21:40:57.879 * Ready to accept connections

```

**Comment by mike12345567** [comment]
Hi @Bogey - can you try updating using the Budibase CLI? Just to confirm the update has gone through successfully.

**Comment by Bogey** [comment]
Sorry @mike12345567 , I don't have npm. Budibase runs on Docker on a Synology. I use docker-compose with plain-vanilla docker-compose and .env files. I deleted the Docker images and pulled the new ones but the problem stays. Budibase cannot connect to Redis.

**Comment by mike12345567** [comment]
Hi @Bogey - you can try the update using the pre-built CLI utilities found in the [release](https://github.com/Budibase/budibase/releases/tag/v1.0.90).

You can do something like `wget https://github.com/Budibase/budibase/releases/download/v1.0.90/cli-linux` and `chmod +x cli-linux` then run `./cli-linux hosting --update` in the directory.

**Comment by Bogey** [comment]
My apologies for waisting your time @mike12345567 , in order to install cli-linux I discovered that Docker had assigned a different network to budibase... so when I made the changes to the firewall, it all worked. ☺️

**Comment by mike12345567** [comment]
Hi @Bogey - no wasted time at all, glad you were able to get it fixed!
