### ISSUE TITLE
make Authentication (SSO) required for apps

### ISSUE THREAD

**Issue by timomayer** [Budibase/budibase#4909]
**Describe the feature request**
As a budibase user who has connceted budibase with SSO (keycloak) i want t be able to build apps in budibase which are only accessible for SSO authorized users and where i am able to use the user specific infomration in the app (userId, email, name)

Usecase: 
- Welcome a user in my budibase app with "Hello {username}"
- Store form data with the {userId} keycloak id of the respective user

**Comment by melohagan** [comment]
https://docs.budibase.com/docs/enforced-sso
