### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by CosmasSC128** [Budibase/budibase#4926]
**Describe the bug**

I cannot add more than 1.1 Mb attachments, while budibase docs say it should be up to 20Mb upload possible.

**To Reproduce**

Drag and drop a 1.1Mb or larger file, or multiple files adding up to more than 1.1Mb into the attachment uploader widget.

**Expected behavior**

Files under 20Mb should be added and uploadable.

**Screenshots**
![Screenshot 2022-03-16 at 15 56 34](https://user-images.githubusercontent.com/93920520/158633133-a17604ae-6065-4cd3-9e3d-9b5c341c91cf.png)
![Screenshot 2022-03-16 at 15 56 37](https://user-images.githubusercontent.com/93920520/158633150-68d42b0c-7aa9-424b-a6c6-9f0f47e29c5a.png)

**Desktop (please complete the following information):**
 - OS: iOS - Catalina - 10.15.7
 - Browser Chrome
 - Version 99.0.4844.74 (Official Build) (x86_64)

**Comment by devops2k10** [comment]
use this on Nginx conf file
client_max_body_size 200M;
