### ISSUE TITLE
500 internal server error on some save operations

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#4938]
It is very difficult to give context, I have an action on a button, that calls a query. Since build 82 (I am now on 90), when I hit the button and confirm the popup message, the action is completed correctly (i.e. the query is executed), but then we get a popin saying:

![image](https://user-images.githubusercontent.com/82715690/158794958-512fcb04-a7cc-428a-8247-d464ed8f6b40.png)

I can see two cases:
1. Nothing strange in the logs, I also see I got this in the debugger:
![image](https://user-images.githubusercontent.com/82715690/158797659-4b2b2e73-20d4-48f7-b325-31be1c6e9175.png)

and see this in the console:
![image](https://user-images.githubusercontent.com/82715690/158798483-e94a1a8b-8899-41e6-8d51-abd418e686e7.png)

2. Another case, Intermittently, the data source returned an actual error 500. 
I see this in the debugger:
![image](https://user-images.githubusercontent.com/82715690/158799925-946721b6-c213-48ba-b701-79993f880fd2.png)
and this in the console:

![image](https://user-images.githubusercontent.com/82715690/158800173-15eefb41-3a03-4321-8c6b-82ebb9dc572e.png)

And in that case I find something in the logs:  I see the following error, but can't really understand the reason.

```
ERROR [1647513707208] (29 on a9b84fd41504): Datasource is not configured fully.
    req: {
      "id": 617,
      "method": "GET",
      "url": "/api/tables/datasource_plus_eb43710b9fdc4763b7ae4b673a95d729",
      "headers": {
        "connection": "upgrade",
        "x-real-ip": "REDACTED",
        "x-forwarded-for": "REDACTED",
        "host": "app-service:4002",
        "x-forwarded-proto": "http",
        "accept": "application/json",
        "x-budibase-app-id": "app_dev_9a80ae06fbad41f280954678a909e215",
        "x-csrf-token": "823512b0-e47e-4826-b86c-ecf49cad204d",
        "x-budibase-api-version": "1",
        "x-budibase-type": "client",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.3
6",
        "referer": "http://REDACTED/app_dev_9a80ae06fbad41f280954678a909e215",
        "accept-encoding": "gzip, deflate",
        "accept-language": "it,en-US;q=0.9,en;q=0.8",
        "cookie": "budibase:auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c19jNjAyY2UyMmE2ODU0ODlkOWUzNzU0MWQyNzJkOGZhOCIsIn
Nlc3Npb25JZCI6ImU4MjdlZmEwMTBlMDQ2NzRiMjc4NWUyMTg1MTI2NzA0IiwidGVuYW50SWQiOiJkZWZhdWx0IiwiaWF0IjoxNjQ3NDU1Mjk5fQ.pTes8abXdgyEmTAC_1qa6Mq
UZexTTNRjrJ1iWWJwoMc; budibase:auth.sig=nP3TU0gmZBCU-OQM16Bo_opBesY; budibase:currentapp=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZC
I6ImFwcF9kZXZfOWE4MGFlMDZmYmFkNDFmMjgwOTU0Njc4YTkwOWUyMTUiLCJpYXQiOjE2NDc1MDMzMDN9.hrVmAGn7P6XdKDsntRPrHqYpNhgXOSm3keC-MjkEC8o; budibase
:init=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDc1MDMzMDN9.4E2c8wvGutvYBZMR7SsAUsPYuHt9uB8pKUcxnb5hopM; budibase:init.sig=dIYtC
DWMIUwvpaWMxBR5V4-xrT4"
      },
      "remoteAddress": "::ffff:REDACTED",
      "remotePort": 36066
    }
Trace: Datasource is not configured fully.
    at /app/dist/api/index.js:69:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO  [1647513707209] (29 on a9b84fd41504): request errored
    res: {
      "statusCode": 500,
      "headers": {
        "vary": "Accept-Encoding",
        "content-type": "application/json; charset=utf-8",
        "content-length": "14"
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:77:38)
              at ServerResponse.emit (events.js:412:35)
              at ServerResponse.emit (domain.js:475:12)
              at ServerResponse.emitted (/app/node_modules/emitter-listener/listener.js:134:21)
              at onFinish (_http_outgoing.js:792:10)
              at callback (internal/streams/writable.js:513:21)
              at afterWrite (internal/streams/writable.js:466:5)
              at afterWriteTick (internal/streams/writable.js:453:10)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
    }
```

**Comment by mike12345567** [comment]
Hi @marco-santulli - I can see its a datasource plus table, what SQL database are you using this with? I'd assume its something to do with the `Datasource is not configured fully` - but I'd need to know what datasource to attempt to diagnose, thanks!

**Comment by marco-santulli** [comment]
Hi Mike,

it is a postgres DS, this is the setup, keep in mind this error popped up with build 82 it wasn't there before.

![image](https://user-images.githubusercontent.com/82715690/158994403-d60eacc5-855c-470b-8684-bc86bdbd990f.png)


M

**Comment by bwint** [comment]
Hi!
I'm experiencing the same behaviour trying to execute an update query as a button action.
I'm using an MS SQL Server Database.

When I try the query from query editor it works fine and the data get changed in the db. 
But when the button action executes I get a similar error to described above.

**Comment by mike12345567** [comment]
Hi @marco-santulli and @bwint - thanks for the info, I was able to re-create will get a fix out for it.

**Comment by marco-santulli** [comment]
top man thx!

Marco

**Comment by aptkingston** [comment]
Fix is here https://github.com/Budibase/budibase/pull/4951 :+1:

**Comment by bwint** [comment]
Wow that was fast, thanks a lot!
Is there a timeline when the fix will be included in the official docker container?

**Comment by marco-santulli** [comment]
@aptkingston sorry for bugging, do you know when the fix will be released?

**Comment by aptkingston** [comment]
Hey @marco-santulli, I didn't realise we hadn't released it for self-hosters. It's currently deployed to the cloud environment only. I'm running a self-host release right now, so it should be available very soon!

**Comment by marco-santulli** [comment]
@aptkingston you are the man thank you very much
