### ISSUE TITLE
Visting published app in tenant1 while logged into tenant2 produces 404

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#4947]
**Describe the bug**
Create and publish app in tenant1
Log out
Log in to tenant2
Visit url of app in tenant1
See: 
![Screenshot 2022-03-18 at 12 04 28](https://user-images.githubusercontent.com/8755148/158999929-9755aae2-cb34-4373-9bac-6e93a55becd8.png)

**Comment by Mitch-Budibase** [comment]
Testing steps:

login to t1.budipreprod.live
publish -> t1.budipreprod.live/app/123
logout
login to t2.budipreprod.live
go to  t1.budipreprod.live/app/123
go back to t2.budipreprod.live

After following the above steps, I am logged out of t2.budipreprod.live

No 404 error being thrown, but rather the user is always logged out instead.

**Comment by Mitch-Budibase** [comment]
Further testing highlighted the issue I was seeing was related to permissions.

All good on my end, setting this to Done
