### ISSUE TITLE
Enforce SSO

### ISSUE THREAD

**Issue by pavel-orlov** [Budibase/budibase#4957]
**Describe the feature request**

- Add an option to enforce SSO for a selected authentication provider and redirect unauthenticated requests to the provider automatically bypassing login page, logout redirects to the login page `/builder/auth/login`.
- Optionality disable the use of internal authentication and password change/reset option for users.
- SSO authentication from the login page `/builder/auth/login` in the same browser tab. Currently it creates a new tab from the login page.

**Comment by shogunpurple** [comment]
Closing as dupe of https://github.com/Budibase/budibase/issues/4859
