### ISSUE TITLE
Navigating to newly duplicated row via Navigate To doesn't work properly

### ISSUE THREAD

**Issue by Grayda** [Budibase/budibase#4962]
**Describe the bug**
When using the "Duplicate Row" action on a button, `{{ Action 1.Duplicated row._id }}` doesn't get updated when you click it more than once

**To Reproduce**
1. Create two tables, `Items` and `Templates`. Add a text field called `Title` to each
2. Create a row in the `Templates` table with the title `Test 1`
3. Generate screens for the two tables
4. On `/templates`, add a button to the Templates Table
5. Define these actions for the button: `Duplicate Row` (Data Source = `Templates Table`, Duplicate To Table = `Items`), and `Navigate To` (Screen = `/items/{{ Action 1.Duplicated row._id }}`, Open Screen in Model = Ticked)
6. Run or publish the app. Go to the templates screen and click the button next to "Test 1".
7. Note that the row in the modal is "Test 1". Change the title of the row from "Test 1" to "Hello" and save it
8. Close the modal using the "X Close" link in the top right-hand corner
9. Click the button next to "Test 1" again
10. **You will be taken to "Hello", instead of "Test 1"**
11. Go to the `/items` screen and note that the row has been successfully duplicated (both "Hello" and "Test 1" will be there), but `{{ Action 1.Duplicated row._id }}` didn't get updated, so you were redirected to the existing "Hello" row, instead of the newly duplicated "Test 1" row

**Expected behavior**
The row displayed in the modal should be the newly duplicated row, each and every time the button is clicked. Right now the `_id` only gets updated once for each button, and you have to refresh the page to clear out the remembered `_id` before you will be taken to the correct page.

I assume this doesn't happen if "Open Screen in Modal" is unticked because it's a full page reload, not just a modal.

**Screenshots**
![budibase_issue](https://user-images.githubusercontent.com/4891563/159123872-89a65b5d-a60a-4acf-baef-4830cf26769b.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64 bit)
 - Browser Chrome
 - Version 99.0.4844.51 (Official Build) (64-bit)

**Additional context**
This bug applies to each individual button, and only until you reload the page. To confirm this:

1. Create a second row in the `Templates` table called "Test 2"
2. Click on the button next to "Test 1" and call the row "Hello 1"
3. Click on the button next to "Test 2". It'll take you to "Test 2" (NOT "Hello 1"). Call the second row "Hello 2"
4. Click on the button next to "Test 1". You'll be taken to "Hello 1" (NOT to "Test 1")
5. Click on the button next to "Test 2". You'll be taken to "Hello 2" (NOT to "Test 2")
6. Refresh the page. Click the first button again. You'll be taken to "Test 1"

**Comment by aptkingston** [comment]
Appreciate the detailed reproduction steps @Grayda - I can reproduce this perfectly so will get a fix out.
