### ISSUE TITLE
Cannot import App

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#5000]
**Describe the bug**
"Error creating app" when importing an app I had just exported.

**To Reproduce**
1. Go to 'Welcome to Budibase'
2. Click on '... Export App' from your existing app and save it to a file.
3. Click on 'Import App' and choose the file you've just saved and set a new new for the app and path

**Expected behavior**
A new clone of the existing app, with a new path and a new name.

**Screenshots**
![2022-03-22_11-55](https://user-images.githubusercontent.com/67311/159476615-f2438511-3c7b-4efa-9717-42977c0738e3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser Firefox 98.0.1
 - Version current

**Additional context**
Console log shows: 
> [Builder] HTTP 400 on POST:https://ciaud.budibase.app/api/applications
>	You have exceeded your usage quota of 4000 rows.

Note: my exported app has 340 lines and 11 MB.

**Comment by shogunpurple** [comment]
Hi @gvlx - it seems like your usage quota was at over 8000 rows, possibly due to previous applications. We had an issue with this a few months ago that has since been resolved. I've reset your quota. Please have another go and let us know if that works for you!

**Comment by gvlx** [comment]
Hello @shogunpurple,

It failed again.

There was already a new app (maybe you created it)?

So I removed it and imported again the latest export.
Exactly the same error.

Maybe the platform is not releasing the resources fast enough?

I'll try again in a hour.

**Comment by Rory-Powell** [comment]
Hi @gvlx 

I've ran a migration to sync your row and app counts with our usage quotas:

<img width="542" alt="Screenshot 2022-03-23 at 10 49 34" src="https://user-images.githubusercontent.com/8755148/159682865-4be6438a-0513-41e0-af00-89e15a345279.png">

I believe the app creation should succeed on an import here but the follow up error is throw when the rows are being imported, this would explain the new app you mentioned above. 

You will continue to see this error until your row count is below 4000, which currently is sitting at 12270. As martin explained we had some problems in the past that allowed the row count to get this high.

**Comment by gvlx** [comment]
Hi,

This row count is a limitation of the account, a problem with the existing application or its export file?

How can it be solved?
The existing app is currently on version 1.0.93 but it was on 1.0.28 before (which could also be the version of the exported file).

Best regards,

**Comment by shogunpurple** [comment]
Hi @gvlx - row limits of 4000 are the maximum in the budibase free plan. Users will be able to upgrade their budibase subscription to pay for more rows, but this does not exist yet - it will be shipped in a few weeks. Until then you will have to stay within your row limit. I can bump your limit up further for a while, but bear in mind that you will pay for these extra rows in future.

Thanks!

**Comment by gvlx** [comment]
How can a check those limits (per app, table, design, assets)?

**Comment by Rory-Powell** [comment]
Currently they aren't exposed, in the coming weeks we will have this UI available that shows the current usage:
<img width="732" alt="Screenshot 2022-03-23 at 12 04 29" src="https://user-images.githubusercontent.com/8755148/159695049-15abe67a-4330-4c03-846a-a503c7816a41.png">

**Comment by gvlx** [comment]
@Rory-Powell please check #5036 .

**Comment by Rory-Powell** [comment]
And perhaps to answer your question more accurately, the definition of the limits today can be seen on the pricing page on our website
https://budibase.com/pricing/
