### ISSUE TITLE
Infinite redirect when logging in directly via App URL

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#5004]
Open up an incognito tab and browse directly to an App URL: `https://domain.budibase.app/app/AppName` - then login.

Infinite redirect loop:

https://user-images.githubusercontent.com/3524181/159492373-cec94867-98b8-4ba7-9fd3-4cb596894173.mp4

**Comment by aptkingston** [comment]
I've tried to reproduce this but I can't seem to.

If I have screens that my user can access, then I get correctly pushed to the requested screen.
If I don't have any screens available for the user I'm loggin in as, I correctly get served the permission error:
![image](https://user-images.githubusercontent.com/9075550/159545068-87f29fb4-96b1-4cf9-8d78-eaae58a252ce.png)

What role are you logging in as, and does that user have access to any screens? In particular do they have access to the exact route you're requesting?

**Comment by mjashanks** [comment]
Ah sorry, I hadn't assigned access to the user at the admin portal level.

Minor issue then - still weird tho.

Worked once I assigned access.

**Comment by aptkingston** [comment]
Ah nice - that's what causes it! Can reproduce now so will have a look.
