### ISSUE TITLE
Date Picker default value of {{ now }} doesn't allow value to be changed.

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5008]
**Describe the bug**
Whenever `{{ now }}` is used as the default value of a date picker, the date cannot be changed in the UI.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add new form with Date Picker
2. Set default value to `{{ now }}`
3. Run the app, you cannot change the date (unless you spam click). 

**Expected behavior**
You should be able to change the default date when using `{{ now }}`

----
There is also another bug when using JavaScript `return Date.now();` as the default value of a date picker.

In that case the entire builder hangs, and you cannot interact with the designer at all. You have to delete the app.

**Comment by aptkingston** [comment]
About `{{ now }}` - could you check you're running the latest version? I definitely fixed this, and I just checked and it works fine now on 1.0.93.

You're right about using `return Date.now()` though - any value which is different every single execution will cause problems like this, if used inside forms. Using `Math.random()` would do the same thing.
