### ISSUE TITLE
New Screen Addition UI

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5015]
As a user creating a new screen, I want to be able to determine between creating a blank screen, and creating several CRUD screens.

Spec: https://docs.google.com/document/d/1QLCLczXlAZkQ14hWDrgZiP4skgbiM6SaU8YfDj_QZ50/edit#heading=h.cwqflae0tq9n

**COS**
- Split blank screen and auto generated screens into 2 sections
- Always show the autogenerated screens option
- Disable the autogenerated screens option when there is no data source
- Show a list of data sources under the autogenerated section 

#### CRUD Screens
- When you click a datasource, you can then choose a table under that datasource and generate CRUD screens from it.

**Events**
- `budibase:changed_role_on_screen_creation` - indicate whether people change the role when they create a screen, or we should remove that and just let them change it after
- `Screen Created` - add a "datasource" field to indicate if the CRUD screens have been generated from a particular datasource

**Designs**
Walkthrough - https://www.loom.com/share/62256da462bb456f99f889edf00e985f
XD - https://xd.adobe.com/view/76a3927f-aae5-4944-8686-c5b8872ac013-23f0/?fullscreen

**Comment by deanhannigan** [comment]
@shogunpurple Is there any preference on the contents of the "datasource" column? 

The below shows examples in posthog of either the string name or the type of the source being used.
![Screenshot 2022-04-08 at 11 15 13](https://user-images.githubusercontent.com/5913006/162418452-70b15b69-9d0d-4850-97e4-136155684249.png)

**Comment by shogunpurple** [comment]
@deanhannigan - yep, we should just use the name of the datasource itself, given you could have a few of the same type.
