### ISSUE TITLE
UI Redesign: Component Tree V2

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5023]
Spec: https://docs.google.com/document/d/1HvUlXDMuBH8qalFP9-j153uhf0-QZ72bSVy53iT81pU/edit#

### COS
- Add icons to components in tree
- Scroll to component in preview when clicked
- Highlight child components as block when the parent is selected to indicate the "sub tree"

XD - https://xd.adobe.com/view/9319d3eb-35a9-4604-ac5f-003b456a48d6-c64a/

#### Highlight newly added components in tree and preview
- Scroll to the new component when it gets added to show where it went
- Highlight the component on the component tree for a few seconds 
- Highlight the component on the preview for a few seconds

XD - https://xd.adobe.com/view/a5692c5f-d305-4bf7-a721-9e8e260c0402-f03a/

#### Improve Drag and Drop
- Don't move components around as you drag
- Use a green line like the builder preview to indicate drop target
- Highlight parent with green border when dropping as a child into a parent element

XD - https://xd.adobe.com/view/4a53f920-4dd5-4f4b-8dd8-ed3739741ec6-1f00/

#### Improve dropdown chevrons
- remove the chevron arrow from elements that can’t be expanded.
- Reveal the chevron arrow only on hover for parent elements that can be expanded
- Expand the component when user clicks

XD - https://xd.adobe.com/view/f66935ab-9b85-4502-91ea-8369f8e89eb4-a33a/

**Comment by michalfita** [comment]
🙏🏼 When? When? When?

Lack of visual indication of elements on the tree is a real trouble ATM.

Suggestion: Add hoover tooltip with the exact component type displayed, and maybe the data model linked with for forms.

**Comment by shogunpurple** [comment]
@michalfita - we are redesigining our entire design UI over the coming 2 months - but obviously given that its such a big change we are going to test it with a smaller group of users, behind feature flags etc before rolling it out to everyone. We will post in the community forum on discussions to gather interest in the budibase insiders program.

You will be glad to know however that we will be shipping some updates in the next release (going out on Monday) which will make using the component tree much easier and solve the scrolling/visibility problems.

**Comment by michalfita** [comment]
@shogunpurple Great news. Now I'm completely lost when I start building screens without visual indication.
