### ISSUE TITLE
UI Redesign: Side Nav

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5024]
Spec: https://docs.google.com/document/d/1RCVdDO99UhZZHJ3Nyi6UNXRhbUIEWxFAelYc75RkWYc/edit#

**COS**
Add sections with icons for:
- Screens (Default)
- Components
- Theme
- Navigation 
- Theme (As a temporary measure to help existing users move over to new version)

**Designs**

- Add tooltips on hover
- Screens is selected by default
- Switching tab in the side nav doesn't affect the preview
- Other ways to navigate to these tabs
 - User clicks navigation on preview - Open navigation tab
 - User clicks on a component in the preview - Open component tab

XD - https://xd.adobe.com/view/65c4cbc6-1c9c-4300-abc9-5321f7bbee7b-3097/

**Comment by aptkingston** [comment]
Bumping the estimate of this up to 5 as we need to account for a completely new routing structure which requires a large amount of refactoring.
