### ISSUE TITLE
UI Redesign: Screen Config Panel

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5025]
Spec: https://docs.google.com/document/d/1RCVdDO99UhZZHJ3Nyi6UNXRhbUIEWxFAelYc75RkWYc/edit#

**COS**
- Add an "all screens" filter to the role dropdown (This does not have any affect other than filtering the screen panel)
  - All screens
  - Admin level access
  - Power level access
  - Basic level access
  - Public level access
- Represent roles with colour scheme (see designs)
- Show the roles URL in the middle of the screen above the preview, along with its role. 
- Remove the concept of Screen Names
- Show the home screen with a home icon
- Update role setting on right hand side to incorporate new role colour indicators
- Add some text to the role to make it more descriptive (eg. Open up to admin/power/basic users)
- Replace "Route" label on right hand "URL path"
- Remove styling settings from right hand side, as they are now available in the top level screen component in the component tree
- Add "View Components" button to the right hand tree to open up the components tree for that screen
- Add CTA plus button at top of panel to add a new screen
- Prevent users from setting a home screen to "/" 
- Allow users to access screens by clicking the access role displayed above the preview
- Add "More" icon in the screen setting panel to show options for delete and duplicate

XD - https://xd.adobe.com/view/aa4972e0-82ef-4855-92cd-5fc8c04e0cdc-ff1a/

#### Setting home screen
- Add a checkbox to set the selected screen as the home screen. Note that this is role based - when you are on the admin role for example, it will set the home screen to be the home screen for admins
- Clicking the checkbox will open a confirmation modal
- If you have a home screen set, it overrides the existing one
- Once the user confirms the home screen, it will update the icons on the screen menu, above the preview and in the header of the screen settings

XD - https://xd.adobe.com/view/07a66dcb-515b-4cd9-8da1-6c453c5752bd-52f5/

**Comment by melohagan** [comment]
The *All screens* filter will be great. Just got caught out by the filter defaulting to Basic; thought there was something wrong with the templates!

**Comment by aptkingston** [comment]
> The _All screens_ filter will be great. Just got caught out by the filter defaulting to Basic; thought there was something wrong with the templates!

It is indeed great, I'm enjoying it very much in my local version!

![image](https://user-images.githubusercontent.com/9075550/165746213-63e9f3b4-10c3-437c-abb3-95206f62986c.png)
