### ISSUE TITLE
Documentation article "Create a child record from the parent" is missing

### ISSUE THREAD

**Issue by tmdoit** [Budibase/budibase#5031]
**Describe the bug**
The link to https://docs.budibase.com/guides/create-a-child-record-from-the-parent is broken. Where can I read about it?

**Comment by joebudi** [comment]
Hey! I was wondering, where did you find this link? It's very, very old.

**Comment by tmdoit** [comment]
Hi :)
I found it in google, I typed "create related record Budibase" so it could be not relevant, I hit multiple times to 404 but didn't forget from where, in the future I will be more conscious and let you know.

Can you help me with the subject?
Where can I find example or doc about how to create child record from the parent?
In case of "Customer can have multiple addresses" the user journey should look like:
1.  Open screen "Customers"
2. Add customer
3. Fill customer data
4. Select customer address
5. Save

Extended scenario
4.1 Create customer address
4.1.A System opens popup or redirects to the Addresses screen
4.1.B User fills address data
4.1.C User saves address
4.1.D In case of popup - popup disappears, created address is selected; in case of redirect - customer selects created address

From the UI perspective, there could be also table with customer addresses in "Customer" screen, where she can add, update and delete address.
