### ISSUE TITLE
Error - TypeError: this.breakLines(...).flat is not a function

### ISSUE THREAD

**Issue by AnthonyZheng** [Budibase/budibase#5032]
I download the cli-macos, run "chmod +x cli-macos" and then "mv cli-macos budi",
and "budi  hosting --init",the cmd show me the message "**Error - TypeError: this.breakLines(...).flat is not a function**"

Also I try to install it use "**npm i -g @budibase/cli**", after that , I run "budi  hosting --init",the cmd show me the same message.

Did I use the unspported Node version or OS ?

My MacOS version is Catalina [10.15.6]
node version is 10.9.0
npm version is 6.4.1

**Comment by mike12345567** [comment]
Hi @AnthonyZheng - we currently require and support all releases which Node supports themselves - you can find these [here](https://nodejs.org/en/about/releases/) - I believe for the CLI we support Node 11+ but we test from Node 12+.

**Comment by AnthonyZheng** [comment]
I update my node version and then I run "budi hosting --init", the cmd report me another error:
"Error - Error: connect ECONNREFUSED 0.0.0.0:443"

**Comment by 8debug** [comment]
> 

Is it resolved please?

**Comment by 8debug** [comment]
> I update my node version and then I run "budi hosting --init", the cmd report me another error: "Error - Error: connect ECONNREFUSED 0.0.0.0:443"

Is it resolved please?
