### ISSUE TITLE
Email verify not received

### ISSUE THREAD

**Issue by mielune** [Budibase/budibase#5042]
**Describe the bug**
After souscription, the verification email is not received even if I try the "resend button".
I signin with my company email address, you can MP me if you need more details.
After 2-3 hours, no email anymore.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/8350742/159742679-351f2ada-7da3-4d88-9380-70380bf9be41.png">

**Comment by shogunpurple** [comment]
Hi @mielune - is it possible your corporate email policy is blocking the email? Are you working behind your company network?

**Comment by mielune** [comment]
Hi Martin,

Our emails are managed by outlook online in Azure.
My prof e-mail is ***@***.***

I retried today the resend process, still no email received.

Best regards

Laurent / mielune

**Comment by melohagan** [comment]
Hi @mielune Is this still an issue with the latest version of Budibase? 

If it is, would you be able to provide reproduction steps please? Is there any further information on your environment you could provide, e.g. Self-host or cloud, tenant id, etc?

**Comment by mielune** [comment]
Hi @melohagan 😃 

I tried today and it work now (v1.2.20), thank you for all the job the BB team do 💪
