### ISSUE TITLE
App Id is invalid/not found after update of budibase version

### ISSUE THREAD

**Issue by ajay-nagarajan** [Budibase/budibase#5060]
**Describe the bug**
There were 2 apps created on budibase which was working well. it was built on the version 1.0.86. On March 22, we restarted our servers and it updated to the latest version of budibase 1.0.90 after which we now see this error while trying to open the app. 

<img width="473" alt="Screenshot 2022-03-22 at 5 57 19 PM" src="https://user-images.githubusercontent.com/10414636/159454993-be68cc90-5319-4870-a472-4d0c4a9cf75f.png">

On further inspection, it seems like the component/definitions api returns an error with status code 404. 
Could anyone please help with this?

**Comment by shogunpurple** [comment]
Hi @ajay-nagarajan - would you be able to go into the network tab in the browser, and paste the response from the call to  component/definitions? That way we can help a lot more with debugging. Thank you!

**Comment by ajay-nagarajan** [comment]
hey @shogunpurple ! sorry i thought i had provided this already. 
i got this response 
<img width="1214" alt="Screenshot 2022-03-29 at 10 43 51 AM" src="https://user-images.githubusercontent.com/10414636/160522421-12dab8cc-64d5-4003-9dc7-0f6bd2e7e6ff.png">

`{"message":"The specified key does not exist.","status":404}` from the components api.

**Comment by shogunpurple** [comment]
Hi @ajay-nagarajan - thanks for sharing the error. Are you just using the standard docker compose setup with budibase? Or has it been changed in any way - using S3 instead of MinIO, or pointing to an existing MinIO?

Also just to check - if you export your app in the portal, and import it, does the new app work as expected?

**Comment by ajay-nagarajan** [comment]
So we have hosted the app with our own setup  [deployed containers as separate services on AWS ECS, each service behind its own load balancer]. We do use MinIO, the same image provided in the docker compose file. 

Regarding your second question, an export and import does work fine, but that causes a change  in the URL of the generated form [because of the new app Id] and that behaviour is undesirable for us.

**Comment by shogunpurple** [comment]
@ajay-nagarajan - as a quick fix, you can change the URL of the new app in the app settings panel to be the same as the old one to avoid conflict.
<img width="399" alt="Screenshot 2022-03-31 at 13 41 03" src="https://user-images.githubusercontent.com/11256663/161056940-97a3b77e-a142-46d2-a070-b72643d6adeb.png">

As for your setup, it does not seem like we've updated anything relevant there between 1.0.86 and now that is relevant to this issue you are seeing with minio, I feel like this could be an environmental issue in your ECS setup - are all the task definitions up to date with all the relevant environment variables?

It appears the `manifest.json` file is missing from MinIO under your app ID. When you look at the MinIO browser, is it missing?

**Comment by themantalope** [comment]
Discovered that in my case it was because I was out of disk space! The browser console showed the error in case anyone else runs into this.
