### ISSUE TITLE
Add a $ to column configuration value, removes the value

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#5063]
**Describe the bug**
When configuring a table's columns, and I add a $ before {{Value}}, the value disappears within the column.

https://cln.sh/rhIOP8

**Comment by aptkingston** [comment]
Just updating to say that this only affects the block, and it breaks if you use any additional value, not just a dollar sign.

**Comment by aptkingston** [comment]
In develop so should be deployed to staging shortly :+1:
