### ISSUE TITLE
Component requests: Fixing multiple loading indicators out of sync

### ISSUE THREAD

**Issue by daawaan4U** [Budibase/budibase#5085]
**Describe the feature request**

Currently, multiple data providers are used when querying from different views. However, this results in multiple loading indicators popping out and loading out of sync and can cause unnecessary rerenders of the layout of the components. As a quick fix, a component can be provided in order to group multiple data providers with only one loading indicator that will wait for all data providers to successfully finish first fetching before loading every component at once.

In the long run, I think an animated skeleton loading component for every existing component (all including tables, cards, charts, paragraphs, input fields, etc.) would provide a better end-user experience in case the initial height and width can be estimated.

**Screenshots**

https://user-images.githubusercontent.com/53972232/160054135-a664319b-88e2-4bda-8bab-aa14cc6f7f6a.mp4

**Comment by joebudi** [comment]
I must say @daawaan your app looks awesome!

**Comment by melohagan** [comment]
Skeleton loading has been added! Closing.

**Comment by Den4ik1992** [comment]
> Skeleton loading has been added! Closing.

How i can select the Skeleton loading Style ?
The Spinner looks very ugly.

 
![2023-05-10 08_48_45-Window](https://github.com/Budibase/budibase/assets/82113641/c4aa11f9-730b-4ee1-a47a-2ca97da9807a)
