### ISSUE TITLE
Frontend - State Management

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#51]
Screens created in the front end need connected to data.

E.g. we may have a "Customer List" - a table which displays all customers. 

- Customers are loaded from the API `/api/myapp/list/customers` .
- This returns an array of customers, which is stored in memory in your app

We need a way of pointing the table, to that data stored in memory.

There are already mechanisms underneath for "binding" the components to the data. However, there is no easy way to get an overview of what data is being stored & how it is named etc.

**Comment by mjashanks** [comment]
Was using the events screen, and noticed something thats missing. The parameters need to be bindable to state...

![image](https://user-images.githubusercontent.com/3524181/74639794-70d8ec80-5166-11ea-9d03-75651e850d80.png)

**Comment by mjashanks** [comment]
Another issue with this...

The current state cascader only allows you to read existing values from state.

We need to be able to write to state from in here... e.g. binding the value of an input...

![image](https://user-images.githubusercontent.com/3524181/74735460-a6ee9d00-5248-11ea-90f2-1d5ba0f9536c.png)

The input value needs to be setting some value in state.

We could achieve this via and input `onChange` event... but this seems like alot of work, and would also require te abililty to bind event parameters (as above)

**Comment by mjashanks** [comment]
.... in addition to the above comment....

I actually think we need the option of free typing into state... 

one of the binding sources is "Context", which is a value passed in from the `code` section....

```
function (render, store) {
  for(let customer of store.customers) {
    render( { customer } ) 
  }
}
```

in the above example, { customer } is passed in to the rendered component as it's "Context"

At this point in time, the state cascader is not parsing this javscript to understand what the members of `context` are... and i dont think it will be all that easy to do so

**Comment by shogunpurple** [comment]
We will need to discuss how direct bindings will work in Budibase from certain components (inputs etc). An event parameter aware `onChange` from the current UI is the simplest solution IMO rather than adding anything to the component panel. 

As for context -  I suggest we do the text input binding to context for now in a modal thats opened from the component properties panel. Freeform text is easy to implement but we can't do this for alpha - it's just going to be a nasty user experience and very hard for us to add validation for

**Comment by mjashanks** [comment]
yea - so long as we can bind to context & store in some way, im not bothered on how right now... just need to be able to do it.

So - you're saying use a modal for the context binding... but is there freeform text inside the modal ? e.g. How do we bind to `context.surname` (without knowing whats inside context at this point)

Also - i'm not clear on the event parameters bindings... are we ok with allowing bindings there ?
