### ISSUE TITLE
[BUG] Time picker very inconsistent behavior.

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [Budibase/budibase#5102]
**Describe the bug**

The date picker is very inconsistent when used just to pick time.
In the video attached is possible to see values constantly disappearing and reseting (the value actualy gets written in the field, just the UI goes blank)
The AM/PM button needs several pressings to actualy change. An option to set 24 hours mode would be nice.

**To Reproduce**

1. Add a date picker and set it to "time only"
2. Try to pick a time

**Expected behavior**

The picker should not reset the value and the value should not disappear from the UI.

**Screenshots**

screenshot of the widget config:
![image](https://user-images.githubusercontent.com/47254894/160189108-4770ae1b-61eb-45a4-9291-36c95202fdcc.png)

Video attached

**Desktop (please complete the following information):**
 - OS: docker-compose in Fedora 35
 - Browser used Firefox in Windows 10
 - Version 1.0.90

**Additional context**

Video of the problem:
https://user-images.githubusercontent.com/47254894/160188583-1893ce48-dffa-4785-a3be-ab42b2ad6acd.mp4

**Comment by yeoldegrove** [comment]
I can confirm that the time picker also does not load "default values" defined via a javascript funtion on a firefox 96 on linux.
On chromium 97 this is working fine by the way.

**Comment by sergey-dme** [comment]
Hey all, 

In my case, when binding `{{ now }}` is set as Default value it's unable to change the date in UI - picker always jumps to the current Date, but when I set JS `return Date.now() ` instead, as @aptkingston showed, it crashes everything, even builder freezes and after the change when I close frozen tab and re-open the app in builder mode then navigate to this screen it freezes again, fortunately I was able to I revert changes back and restored my app

**Comment by aptkingston** [comment]
Hi @sergey-dme. All this will be fixed in the next release coming out soon - both Handlebars like `{{ now }}` and JS expressions will be fine and not cause any issues.
