### ISSUE TITLE
Ability to filter/compare multiple values in a table

### ISSUE THREAD

**Issue by aidenmitchell** [Budibase/budibase#5106]
**Describe the feature request**
I'd like a table view that filters the "Stock" number to less than or equal to another value in that row.

**Screenshots**
![image](https://user-images.githubusercontent.com/30846409/160213018-4c423272-9eed-48c5-80e3-c459e1ad01f5.png)
Have a lightning bolt icon, or a dropdown of other columns, so that we can compare two table values.

**Comment by daawaan** [comment]
@aidenmitchell alternatively, you can add a `Formula` column that will compare the `Stock` to another column and return the result of that condition. You can then filter in the view using the `Formula` column you added
