### ISSUE TITLE
Issue with installing in Kubernetes 

### ISSUE THREAD

**Issue by maximru** [Budibase/budibase#5107]
I'm trying to reinstall budibase in kubernetes cluster (tried both AKS and EKS) after deleting previously installed version via namespace deletion and I'm getting the following error:

Error: INSTALLATION FAILED: failed to create resource: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://budibase-ingress-nginx-controller-admission.budibase.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "budibase-ingress-nginx-controller-admission" 

I do see resources created in the namespace, but cannot access site with 404 response from nginx and I cannot see anything registered in helm.

I'm not sure if this issue exists during initial install.

**To Reproduce**
1. Delete namespace of existing budibase installation in kubernetes 
2. Update helm repo
3. Try to install budibase using helm following instructions

**Comment by shogunpurple** [comment]
Hi @maximru - there was a bug in previous versions of the NGINX ingress controller that prevented you deleting the `validatingwebhook`. Try the following command, then delete again.

`kubectl delete -A ValidatingWebhookConfiguration budibase-ingress-nginx-admission`

Thanks!

**Comment by maximru** [comment]
That worked. Thanks a lot @shogunpurple !!!

Closing the bug.
