### ISSUE TITLE
gke install with helm fails with budibase-ingress-nginx-controller-admission not found error. 

### ISSUE THREAD

**Issue by bayeslearner** [Budibase/budibase#5108]
**Describe the bug**
A standard helm installation with ingress-nginx (in ns ingress-nginx) already installed would fail.  But it may be something else. 

**To Reproduce**

```
$ helm install --create-namespace  --namespace budibase budibase budibase/budibase --set ingress.nginx=false 

W0326 02:21:42.197739  394036 warnings.go:70] spec.template.spec.containers[0].env[13].name: duplicate name "LOG_LEVEL"
Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://budibase-ingress-nginx-controller-admission.budibase.svc:443/networking/v1/ingresses?timeout=10s": service "budibase-ingress-nginx-controller-admission" not found

```

```

$ kubectl get validatingwebhookconfigurations
NAME                                                              WEBHOOKS   AGE
budibase-ingress-nginx-admission                                  1          71m
cert-manager-webhook                                              1          16d
flowcontrol-guardrails.config.common-webhooks.networking.gke.io   1          16d
ingress-nginx-admission                                           1          25m
nodelimit.config.common-webhooks.networking.gke.io                1          16d
validation-webhook.snapshot.storage.k8s.io                        1          16d

```
$ kubectl describe validatingwebhookconfigurations.admissionregistration.k8s.io budibase-ingress-nginx-admission 
Name:         budibase-ingress-nginx-admission
Namespace:    
Labels:       app.kubernetes.io/component=admission-webhook
              app.kubernetes.io/instance=budibase
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=ingress-nginx
              app.kubernetes.io/version=1.1.0
              helm.sh/chart=ingress-nginx-4.0.13
Annotations:  <none>
API Version:  admissionregistration.k8s.io/v1
Kind:         ValidatingWebhookConfiguration
Metadata:
  Creation Timestamp:  2022-03-26T05:16:54Z
  Generation:          2
  Managed Fields:
    API Version:  admissionregistration.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:app.kubernetes.io/version:
          f:helm.sh/chart:
      f:webhooks:
        .:
        k:{"name":"validate.nginx.ingress.kubernetes.io"}:
          .:
          f:admissionReviewVersions:
          f:clientConfig:
            .:
            f:service:
              .:
              f:name:
              f:namespace:
              f:path:
              f:port:
          f:failurePolicy:
          f:matchPolicy:
          f:name:
          f:namespaceSelector:
          f:objectSelector:
          f:rules:
          f:sideEffects:
          f:timeoutSeconds:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-03-26T05:16:54Z
    API Version:  admissionregistration.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:webhooks:
        k:{"name":"validate.nginx.ingress.kubernetes.io"}:
          f:clientConfig:
            f:caBundle:
    Manager:         kube-webhook-certgen
    Operation:       Update
    Time:            2022-03-26T05:21:50Z
  Resource Version:  9742364
  UID:               ab1444f6-2d6e-4dba-88f7-481395fe624f
Webhooks:
  Admission Review Versions:
    v1
  Client Config:
    Ca Bundle:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkVENDQVJ5Z0F3SUJBZ0lSQU9uOUY1SlZiUHB4YmwrUTRSRWxxMTB3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FYm1sc01UQWdGdzB5TWpBek1qWXdOVEUyTlRCYUdBOHlNVEl5TURNd01qQTFNVFkxTUZvdwpEekVOTUFzR0ExVUVDaE1FYm1sc01UQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJK2ZXVm1FClA0UGtyNGlBUHNNVG5qZXdnVWlucjREVUpqbWxpblZVZGlPL2dsdFJ6ckljdWQwZjEyUS93QWNFaUZxSmpPb3MKckpQK0VraEJFeE02UGYyalZ6QlZNQTRHQTFVZER3RUIvd1FFQXdJQ0JEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRgpCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUNTh6YWFpcXBIdXJLQ2lXQWZ2eUdOCkYwM2k2VEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFMZXE0aVN3SDhYczVIcmJYcW5KbGhLbDZHMS9wV3J3TVEKdkFRbFdUR2NLUUlnSFdZZURFTlI2M0FabnFVUjN1QkJTRWI3SEJrUEE0WFBmSVB0bGhWd1BrND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    Service:
      Name:        budibase-ingress-nginx-controller-admission
      Namespace:   budibase
      Path:        /networking/v1/ingresses
      Port:        443
  Failure Policy:  Fail
  Match Policy:    Equivalent
  Name:            validate.nginx.ingress.kubernetes.io
  Namespace Selector:
  Object Selector:
  Rules:
    API Groups:
      networking.k8s.io
    API Versions:
      v1
    Operations:
      CREATE
      UPDATE
    Resources:
      ingresses
    Scope:          *
  Side Effects:     None
  Timeout Seconds:  10
Events:             <none>
```

```

**Comment by shogunpurple** [comment]
Hi @bayeslearner - I'll try to recreate this with a fresh k8s cluster - are you trying to turn NGINX/ingress off so you can use your own ingress?

**Comment by bayeslearner** [comment]
yes, I already installed ingress-nginx separattely.

**Comment by shogunpurple** [comment]
Thankd @bayeslearner - I see the issue. You need to set `ingress.enabled` to `false` as well in your chart, and the ingress won't be created.

**Comment by bayeslearner** [comment]
Actually, I did. I got the same error.

**Comment by shogunpurple** [comment]
Thanks @bayeslearner - it seems like you may be encountering this one that another user saw.

https://github.com/Budibase/budibase/issues/5107#issuecomment-1079917681

Please try running the command I suggested in that issue and let me know if that works for you!
