### ISSUE TITLE
Get rid of events panel

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#511]
https://github.com/Budibase/budibase/issues/486

- create onclick component prop panel/modal for setting up handlers

The onclick component modal will allow you to set up navigation to another screen, or trigger a workflow.

**Comment by mjashanks** [comment]
We discussed that #488 would be enough to cover scenarios where we want an input control to update a single field on a record.

i.e. In the builder UI, we are presented with a list of fields in the current "Context" e.g. Fields from the model, choosen in the parent list.

This approach should work for that particular scenario. However, it does not cover the following example use cases
- Click a "Close" button to update the record's "Status" to "Closed"
- On check changed, update the ToDo item to "completed" (OK as above), and also set the "Completed Date" to now (Not OK)
- Custom form. My "Customer" table has 20 fields. I want an inline "Quick Create" form, with "Forname" and "Surname" fields, and a "Create" button. 

I feel like we could do a better job of covering all these scenarios by implementing the following
1. An "Update Record" event action. This would allow you to choose a record in context, and supply values for any field in this record (listed out for the user). For each field, you make use binding expressions.
2. A "Create Record" action - basically the same behaviour as No.1
3. An "Update Field" action. Again - similar functionality to 1 & 2, except more simple... a quicker way of updating a single field

The control described in No.1 is essentially a control for building JSON requests. I think it would also eventually cover another scenario, which we havent really thought of..... "Trigger Workflow"...

We had discussed that workflows should be Backend only. However, if we want to manually trigger a workflow, we are going to need to send some data to it, in the form of a JSON object. We therefor need to ability to build a JSON request, from application state (i.e. inputs or data on the screen)

Here is a quick mockup of the "Update Record" action / request builder...

![Stories - Request Builder](https://user-images.githubusercontent.com/3524181/89914764-636c5e80-dbed-11ea-858f-3582e772f5ca.jpg)

**Comment by mjashanks** [comment]
Further to the above, we agreed that it would be best to rework the events panel, to make it more fit for purpose.

Below is an initial mockup
![Stories - New frame](https://user-images.githubusercontent.com/3524181/91280827-3f795300-e77f-11ea-86b2-a840ff9e0201.jpg)

Features/Intention of the above
- The list on the left, lists out the actions that happen when this evnt fires. They will happen in the order listed
- The dropdown in the top left is to add a new action to the bottom of the list
- The actions in the list must be reorderable, by some mechanism (D&D / up-down arrows ?).
- Must be able to remove actions from the list
- Mockup shows the panel as a Popover, but can be a modal

## Available Actions

### Update Record

Updates a record with the given values...

Users chooses
1. A Table to update , from a Select
2. A record `_id` to update *from binding
3. Fields to update. Fields will be selectable based on the chosen table. Their value will be a *binding expression (see spreadsheety think in above mockup)

* the binding expressions will look like `{{ Input 1 }}` or `{{ Customer List.data.Surname }}`, and will be constructed using the exisintg binding interface

### Create Record

Creates a new record with the given values...

This is the same as **Update Record**, except that an `_id` does not need to be supplied

### Navigate to

Navigates to another screen within the app (i.e. external urls not required, for ease)

User Chooses
1. A Screen (by name) from a Select

### Trigger Workflow

**This can be left until last, as it may also require some workflow changes**

Triggers a certain workflow

User Chooses
1. A workflow, from a Select
2. Data to supply to the workflow. This probably needs a little more thought, but will probably look like the field selection in  **Update Record**... i.e. a spreadsheet/grid like entry.
