### ISSUE TITLE
[BUDI-6867] Automations don't support attachment fields

### ISSUE THREAD

**Issue by Havock94** [Budibase/budibase#5124]
**Describe the bug**
I'm looking for a way to remove N files from a record on button click.

**To Reproduce**
1. Have a table with a file column
2. Create a button and set a click action linked to an automation
3. Configure the automation to "Update row"
4. File fields are not shown in the setup

**Expected behavior**
I expected to find file fields in the automation setup so I can set them to null (remove the uploaded file)

**Additional context**
Maybe I approached this the wrong way, maybe there's another way to remove all files from a field on a button click (without removing each of them individually) but I haven't found out how!

Thank you

<sub>[BUDI-6867](https://linear.app/budibase/issue/BUDI-6867/cannot-remove-files-on-button-click)</sub>

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/12328
