### ISSUE TITLE
Sign in not working

### ISSUE THREAD

**Issue by jwillmer** [Budibase/budibase#5126]
We run version `1.0.46` of budibase in docker with a SSO configuration. Today I tried to update with latest images but was unable to sign in (via regular or SSO). I always get a green banner with "authentication/login successful" but I don't get redirected. I replaced the `budibase/apps:latest` image with the old one and the setup works without any problem (using the new `budibase/proxy`). I don't know what has changed maybe there is a upgrade procedure I'm not aware of?

**Comment by jwillmer** [comment]
Also encountered the new window issue as described in this issue - maybe related?: https://github.com/Budibase/budibase/issues/4957

**Comment by shogunpurple** [comment]
Hi @jwillmer - sorry to hear you are having some issues. Would you be able to get the logs of the `worker` so we could see what is going on? 

`docker-compose logs worker-service`

Thanks!

**Comment by jwillmer** [comment]
@shogunpurple can't reproduce it any more. After switching back to the latest build to get the log output it works. Maybe some migrations required a restart of the containers. Anyway, closing since I can't reproduce it anymore - thx for the quick reply.
