### ISSUE TITLE
App Creation Wizard

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#514]
When a user creates an app in the builder for the first time:

- They will be presented with a "wizard" asking them to enter their API key
- They will be asked to enter their app name
- They will be asked to create a single user for their app
- The app is then created

#### Designs
https://www.figma.com/file/X9x7UiiJNX6BdJkwgYiGc0/Forms?node-id=248%3A0

**Comment by kevmodrome** [comment]
Done in PR #523
