### ISSUE TITLE
Custom SQL limit & offset params issue

### ISSUE THREAD

**Issue by ggs331** [Budibase/budibase#5149]
Hello,

I have just upgraded to 1.0.90, then many of my page got error `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''6' OFFSET '0'' at line 1` due to I am using custom SQL with limit and offset for pagination. 

Custom SQL with `limit` and `offset` params will got error, but it works if I use a number instead
![image](https://user-images.githubusercontent.com/29649651/160531004-78a6729a-58e7-445f-b23a-1d4dc6dca038.png)

It works if use  `limit` and `offset` number.
![image](https://user-images.githubusercontent.com/29649651/160531208-855f6eab-7321-43c3-9641-d5b44b81e5ee.png)

It seems Budibase is doing SQL syntax verification, and somehow it found the syntax was wrong.

**Comment by mslourens** [comment]
I looked into this issue and what I found is that offset and limit are converted to string, which is not a valid type. If you convert those values to number, then the query runs fine.

**Comment by ggs331** [comment]
> 

I can convert limit and offset to number on design panel, but it seems no way to convert those default values. And many of my queries has limit and offset, it's a lot work to convert all manually. Hope this bug will be fix very soon. Thank you.
