### ISSUE TITLE
Link visibility in Navigation Layout based on user-role

### ISSUE THREAD

**Issue by serelsnauw** [Budibase/budibase#5150]
Hi guys,

It would be great if the navigational links (in Navigation Layout) could have the option to show or hide based on the user-role (power- or basic-access, or other conditions).

There are now some links in the menu that not every user has access to, so it would be best if these links are not presented to the basic-user.

If anybody has an idea how to deal with this in the current version, would be great. Otherwise, it would be a (simple but great) feature.

Grtz Serel.

**Comment by aptkingston** [comment]
Hey @serelsnauw. We actually have plans to implement this over the next 2 months as we do a large update to the design UI. For now you can do this using conditional UI, but you'll just need to create a new condition for each user role and pick which links you would like selected.

If you make new conditions anf check `{{ Current User.roleId }}` then you can achieve this. For example, here is how to do choose new links to show for admin users:
![image](https://user-images.githubusercontent.com/9075550/160588767-f646d284-1e4f-4176-a56e-ae9c55dd32b0.png)

**Comment by aptkingston** [comment]
Thanks @serelsnauw, glad to hear so! Going to close this issue off as we already have this scoped as part of our new work.
