### ISSUE TITLE
Unpublishing app as a non-admin produces 500 error

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#5155]
**Describe the feature request**
Due to `Unable to remove app role - Admin user only endpoint.`
This caused by the server -> worker request to remove the app role from existing users

Suggested fix: 
- This service to service call should use the internal api key only, rather than relying on the current users headers

Investigate:
- Is it possible to remove the header forwarding completely, or are there places where we require the user context being sent through. Potentially around the public api and users

**Comment by melohagan** [comment]
I was able to successfully unpublish as app as a developer. Closing.
