### ISSUE TITLE
Allow disabling sorting options in options pickers

### ISSUE THREAD

**Issue by Upgreydd** [Budibase/budibase#5160]
**Describe the bug**
Options Picker limit and doesn't respect Data Provider settings

**To Reproduce**
1. Define data provider with 200 records, set sort by column A
2. Inside data provider add form
3. in form define Options Picker, select Options source: Data Provider, select provider from point 1, set display column to B, value column to C

**Expected behavior**
200 records to select, sorted by column A with label from column B and value of column C

**Current behavior**
50 records sorted by column B (label/display column)

**Comment by aptkingston** [comment]
Hi @Upgreydd. I've just tested this and it will correctly show all the rows that your data provider has. Are you sure your data provider is actually pulling back 100 rows? You can use the `Data Provider. Rows Length` binding to double check this if you aren't sure.

In my case, here's a data provider with 100 rows and all 100 options in the picker:
![image](https://user-images.githubusercontent.com/9075550/160657630-5d479005-2099-4c5a-a365-31a84f4980f5.png)

As for sorting, you can't actually manually control it. The picker will alphabetically sort all options by their labels.

**Comment by Upgreydd** [comment]
@aptkingston sorry man, you're right about number of records (my rest limit) but sort options doesn't apply.

**Comment by aptkingston** [comment]
Yes like I said, you can't control sorting of options - the options picker automatically sorts options alphabetically, because otherwise. I can leave this open as a feature request to add a setting to disable the sorting, so it would respect whatever order of rows your data provider has.
