### ISSUE TITLE
New Backend UI Design - Frontend

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#517]
The new backend UI must be in place in order for us to create the custom views functionality.

@joebudi could you add the designs for the new backend?

https://xd.adobe.com/view/76cd2b03-4e33-4bab-84d3-d5a1cdddb9c8-239e/

**Comment by joebudi** [comment]
https://xd.adobe.com/view/76cd2b03-4e33-4bab-84d3-d5a1cdddb9c8-239e/
