### ISSUE TITLE
Change locale of DatePicker

### ISSUE THREAD

**Issue by yeraydeveloper** [Budibase/budibase#5173]
**Describe the feature request**
Is not possible to change the locale of all the dates and datepickers? 
I'm from spain and I'm unable to change the first day of the week to Monday and change the month names
It would be nice to add a option to select the locale and timezone for Dates.

Thanks in advance

**Comment by melohagan** [comment]
Hey @yeraydeveloper 

I've created a custom date picker that supports locale! https://github.com/melohagan/budibase-component-kasper-date-picker

If you have further requests feel free to raise them on that repo. The current library being used within Budibase as the core date picker does not easily support locale.
