### ISSUE TITLE
Columns do not show for REST Data Provider Filters

### ISSUE THREAD

**Issue by Kuuchuu** [Budibase/budibase#5180]
**Describe the bug**
I haven't been able to modify filters for my apps since I believe around v1.0.73, I am currently on v1.0.99. Same issue as #4948 columns do not show, but it was closed 9 days ago. Sorry if this isn't the proper way to inquire about the fix, feel free to close if that's the case.

**To Reproduce**
1. Add a REST data source
2. Add a Data Provider to the app
3. Attempt to modify filters.

**Expected behavior**
Ability to add filters.

**Screenshots**
![image](https://user-images.githubusercontent.com/20036947/160865012-4b157eb4-a300-4994-a64a-5552e9dee846.png)

**Desktop:**
 - OS: Solus Linux
 - Browser: Brave

**Additional context**
Filters that were in place before the broken version was installed seem to still work, but I cannot make any modifications to it.

**Comment by mike12345567** [comment]
Hi @Kuuchuu - we haven't release the changes from #4948 yet, they will be released on Monday all being well - the issue should be resolved then.

**Comment by Kuuchuu** [comment]
@mike12345567 All good, sorry about the duplicate issue. I appreciate your help and work on Budibase! Thanks for the eta
