### ISSUE TITLE
custom sql datetime type parameters issue

### ISSUE THREAD

**Issue by ggs331** [Budibase/budibase#5187]
Hello,

I have just upgraded to v1.0.101 and found some of my apps with MySQL query `DATAE BETWEEN '{{DateFrom}}' AND '{{DateTo}}'` just didn't work. After checked the MySQL query logs, I found that the datatime params passing to the custom SQL is something like `BETWEEN concat('', 2022, '') AND concat('', 2022, '')`, the correct value should be something like `BETWEEN 2022-03-01T00:00:00.000Z AND 2022-03-31T00:00:00.000Z`

### This is my custom MySQL query string
![image](https://user-images.githubusercontent.com/29649651/160976694-7b274471-de6a-4d2a-b130-f2cbc85d32e5.png)

### This is what I got from MySQL query logs
![image](https://user-images.githubusercontent.com/29649651/160977052-42b3ece6-4b8b-4cd9-906d-190686b985b8.png)

**Comment by Rory-Powell** [comment]
Hi @ggs331. Version `1.0.101` is actually not released yet, it is currently going through QA. Would you be able to verify this is an issue on the latest supported version `1.0.99`? This should help us narrow down a fix

**Comment by Rory-Powell** [comment]
For you version, did you update your compose manually to get to `101`?

**Comment by mike12345567** [comment]
Hi @ggs331 - can you try your query without the string characters around the bindings, there has been some changes to how queries are handled by Budibase.

Can you try something like `DATAE BETWEEN {{DateFrom}} AND {{DateTo}}`

**Comment by ggs331** [comment]
> Hi @ggs331. Version 1.0.101 is actually not released yet, it is currently going through QA. Would you be able to verify this is an issue on the latest supported version 1.0.99? This should help us narrow down a fix

@Rory-Powell 
As I met the bug #5149, so I tried to manually update my compose file to get the latest `101` and found bug #5149 has been fixed on `101`. Unfortunately  I met this new issue. 


> Hi @ggs331 - can you try your query without the string characters around the bindings, there has been some changes to how queries are handled by Budibase.
>Can you try something like DATAE BETWEEN {{DateFrom}} AND {{DateTo}}

@mike12345567 
As your suggestion, I have tried change my query from `BillDate BETWEEN '{{DateFrom}}' AND '{{DateTo}}' ` to `BillDate BETWEEN {{DateFrom}} AND {{DateTo}}`, still not work. On MySQL query log, if I set single quote for date `2022-02-01` then got `concat('', 2022, '')`, if without single quote then got `2022`.

**Comment by ggs331** [comment]
> Hi @ggs331 - we will soon be releasing #5215 which should solve your issue, you will still need to remove single quotes around dates however for this to work correctly.

Hi @mike12345567  - I have just manually upgraded to `1.0.106`, YES, then date time parameters can be correctly passed to MySQL without single quotes. 

However, I found another issue is about the number parameters. 

### When passing a `number` value to MySQL query, the MySQL got something like a `datetime`
![image](https://user-images.githubusercontent.com/29649651/162114852-69d319f1-9e66-45a1-b0d0-a7dfeb69a2a1.png)

### Below is what I got from MySQL query log, the `number` seem being converted to `datetime`
`2022-04-07T03:32:37.556216Z	165337 Query	SELECT COUNT(*) TotalNo, (sum(if((BillCurrency = 'USD'),((BillAmount * '2001-06-05 00:00:00.000')),0)) + sum(if((BillCurrency = 'HKD'),((BillAmount * '2000-08-01 00:00:00.000')),0)) + sum(if((BillCurrency = 'CNY'),(BillAmount),0))) AS BillCNYMRC
FROM view_bills
WHERE BillStatus='已支付' AND BillType='Invoice' AND RelCustomerID<>'' AND BillDate BETWEEN '2022-02-01 00:00:00.000' AND concat('', '2022-02-28 00:00:00.000', '')`
