### ISSUE TITLE
Column list is empty in "Define Filters" for Data Provider with PostgreSQL data

### ISSUE THREAD

**Issue by lsoica** [Budibase/budibase#5200]
**Describe the bug**
I have a PostgreSQL query in the Data section that returns 5 columns.
I have a Data Provider with the PostgreSQL query result as its data

When I select "Define Filters" on the data provider, the "Column" dropdown is empty

**Expected behavior**
The dropdown should display the 5 columns that are return by the PostgreSQL query.

**Screenshots**
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1623282/161203278-4eea666d-fe3a-4e08-a98a-aa7e2705a90c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave

**Comment by aptkingston** [comment]
Hey @lsoica. Thanks for reporting! We've actually already fixed this one, and it'll be included in our next release going out on Monday.

Fixed in https://github.com/Budibase/budibase/pull/4953 for reference.
