### ISSUE TITLE
Setting MANY relations removes displayed rows from parent table and multiselect dropdown

### ISSUE THREAD

**Issue by afurkimJET** [Budibase/budibase#5204]
**Describe the bug**
When setting multiple "MANY" relations from a parent table to child tables, the number of entries shown in the parent table and in the multiselect dropdown is greatly reduced for no apparent reason (the parent_child_mapping table has entries for all parent_row/child_row relations). 

Using MySQL as the configured datasource.

Tables: `PARENT_TABLE` > `PARENT_CHILD_MAPPING_TABLE`  (id, parent_id, child_id) > `CHILD_TABLE`

**Expected behavior**
All relations entries are shown in the respective budibase tables as well as in the multiselect dropdown menus.

**Desktop (please complete the following information):**
 - OS: Mac OS (running docker-compose)
 - Browser [chrome]
 - Version [latest docker-compose]

Thanks in advance!

**Comment by AurelienLyUp** [comment]
I have the same problem as you when you more than 2 "many-to-many" relations on a same id.

**Comment by afurkimJET** [comment]
Anybody have an idea on this? Very frustrating as everything else works like a charm

**Comment by melohagan** [comment]
Hi @afurkimJET 

Is this the issue you are describing here?

<img width="903" alt="Screenshot 2022-04-15 at 14 24 32" src="https://user-images.githubusercontent.com/101575380/163576099-c978b10d-28e8-489e-a2fe-7534c4a3469b.png">

So three parents each mapped to three unique PARENT_CHILD_MAPPING_TABLE rows, but the multiselect dropdown does not show the mappings for all parents?

**Comment by melohagan** [comment]
Closing because the issue is stale and has no reproduction steps.
