### ISSUE TITLE
Update State does not trigger before Save Row action

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5212]
**Describe the bug**
If I have update state as my first action, I cannot use the new updated state in my second 'Save Row' action

**To Reproduce**
1. Add a button with update action to setup a state that is an array with 3 elements. Have a paragraph to show the length of this state array.
2. Add another button with action > Update State > Set Value (Elements) > JavaScript binding that returns an array of two elements.
3. Add a second binding: Save Row. Return the state array to a column in a table. Save your actions.
4. Run the app. Click the first button to setup 3 elements in the state array.
5. Click the second button to replace the state with a 2 element array.
6. The data table will save 3 elements, whereas the paragraph will update to show the new state of 2 elements.

**Expected behavior**
If I have update state as my first action, then the second action 'Save Row' should use the updated state from Action 1. Or there could be a new action state type for passing and transforming data along an action chain.  

**Screenshots**
| Create 3 Button | Replace With 2 Button |
| ----- | ----- |
| ![Screenshot 2022-04-01 at 14 56 11](https://user-images.githubusercontent.com/101575380/161277980-c4d13aa1-0c89-40c0-a9d6-ebfe5781a8b8.png) *return [1, 2, 3]* | ![Screenshot 2022-04-01 at 14 56 52](https://user-images.githubusercontent.com/101575380/161278092-108a500d-4c06-46ff-86c7-a55fbe8e4f84.png) *return [1, 2]* ![Screenshot 2022-04-01 at 14 57 19](https://user-images.githubusercontent.com/101575380/161278185-a3a111f0-6532-4aa4-b792-0c92c2bee7fd.png) |

**Paragraph**
![Screenshot 2022-04-01 at 15 00 38](https://user-images.githubusercontent.com/101575380/161278791-391c3960-e3ab-4623-83c5-7fad08a57060.png)

**Step 1 - Click Create 3**
![Screenshot 2022-04-01 at 15 00 07](https://user-images.githubusercontent.com/101575380/161278709-047fdb0c-e257-4411-8140-668ed1a1c17b.png)

**Step 2 - Click Replace With 2**
| State | Table |
| ----- | ----- |
| ![Screenshot 2022-04-01 at 15 01 12](https://user-images.githubusercontent.com/101575380/161278896-8a20ddba-55c1-4f88-beae-3bc0b13fee03.png) | ![Screenshot 2022-04-01 at 15 01 54](https://user-images.githubusercontent.com/101575380/161279015-6dd160e7-8082-4a3f-9518-036d3c9afffd.png) |

Here is the app export for trying out:  
[update_state_bug-export-1648821863345.txt](https://github.com/Budibase/budibase/files/8398353/update_state_bug-export-1648821863345.txt)

**Comment by aptkingston** [comment]
Had written a long post about why this is impossible, then realised I can do it really easily because global state is an edge case haha. So I have this changed and will PR soon, but initial post is below for reference.

> Had a look into this. This is actually very difficult to change. Button actions do only get enriched at the moment before execution, but they assume that the only additional enrichments are things like previous step outputs and action parameters, not "normal" data context like state. It's hard to explain exactly why we can't do this, but it's basically that the entire button action chain gets the same base context to enrich from and can't access a newer one at the moment of enrichment.

> This doesn't break anything though does it, because if you're setting a value into state, then you also have available the same data you need to just use the same expression again in the save row action. Just a little duplication but everything works fine, so you can still get around this limitation.
