### ISSUE TITLE
Text fields created in Postgres break if 'Fetch Tables' is used

### ISSUE THREAD

**Issue by sudpuzzer** [Budibase/budibase#5219]
**Describe the bug**
When creating columns in Budibase on an external Postgres 13.6 database, a normal text column (not long form text) is created in Postgres with the TEXT type. If the Fetch Tables button is used on the data source configuration page, Budibase reads the TEXT column in as a Long Form Text field, and it is not possible to change it back to a normal text field. This breaks any forms and field groups that are expecting a the text field type.

**To Reproduce**
1. Create a new column in a Postgres table in the Budibase table editor.
2. Select the 'Text' type.
3. Use the 'Fetch Tables' button in the data source configuration page for PostgresSQL
4. Verify that the newly created column is now a 'Long Form Text' type, and it is not possible to change.

**Expected behavior**
The normal text type should be created in Postgres as a VARCHAR column, which Budibase correctly identifies as the normal text type.

**Screenshots**
Create column:
![image](https://user-images.githubusercontent.com/10662820/161323922-5a9f17a0-d362-4e64-b139-72b07011ce20.png)

Verify TEXT type:
![image](https://user-images.githubusercontent.com/10662820/161323975-4e0dde64-6779-4636-a995-07723c34a7aa.png)

Fetch tables:
![image](https://user-images.githubusercontent.com/10662820/161324000-6692dee4-6d44-4801-b9ab-98ec44a89af0.png)

Column is now Long Form Text:
![image](https://user-images.githubusercontent.com/10662820/161324030-659e1c8b-0607-4790-945a-70c0fd6f1fc7.png)

Change column to varchar(255) in database:
![image](https://user-images.githubusercontent.com/10662820/161324100-b8957563-120c-4c49-a6c2-1f4b547db29c.png)

Fetch tables again, column back to text:
![image](https://user-images.githubusercontent.com/10662820/161324168-432bc2a1-722c-4d51-a149-26c87214f77a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.84
 - PostgresSQL: 13.6
 - Budibase: 1.0.98

**Additional context**
Specifying a max length for the does not make a difference either, when the Fetch Tables button is used, the Max Length value is discarded and behaves as above. A text field with a Max Length should certainly be created as a VARCHAR(255) in the PostgresSQL database.

**Comment by mike12345567** [comment]
Hi @sudpuzzer - I can add an option so that the `TEXT` type can switch between long form text and text types in Budibase, I'll make the default text as well as I feel that is probably going to be more useful anyway - will get this fix out in a hotfix at some point next week.
