### ISSUE TITLE
Yarn cache inflates docker image size

### ISSUE THREAD

**Issue by qubidt** [Budibase/budibase#5233]
**Describe the feature request**
The docker image's size is inflated because of the yarn packages. For the `RUN yarn` step I'm seeing 1.7GB and 802MB for the apps and server image, respectively. From my apps image, over half the size of the image (~1GB) is used by `/usr/local/share/.cache`. Could I suggest cleaning this directory from the final image? Perhaps using a multi-stage build? 

`/app/node_modules` would still be quite beefy, not sure if there's anything you could do about that, but it save over half of the current disk and bandwidth usage

**Screenshots**
```
root@budibase-app:/app# du -h -x / | sort -h | tail
118M    /opt
817M    /app/node_modules
874M    /app
1015M   /usr/local/share
1015M   /usr/local/share/.cache
1015M   /usr/local/share/.cache/yarn
1015M   /usr/local/share/.cache/yarn/v6
1.2G    /usr
1.2G    /usr/local
2.2G    /
```

**Comment by mike12345567** [comment]
Hi @qubidt - thanks for raising this issue, we've actually recognised some of these issues and plan to address them as part of https://github.com/Budibase/budibase/pull/5209 and #5202 - try and minimise the size of the images.

**Comment by qubidt** [comment]
Thank you, those issues do address my concerns re: image size. I'll leave closing this issue as a duplicate up to your discretion.
