### ISSUE TITLE
Masked input

### ISSUE THREAD

**Issue by vidz1979** [Budibase/budibase#5241]
**Describe the feature request**
When input different types of information like phone numbers, id numbers and dates, it's a good practice to format the input as it is typed by the user. It would be awesome if Budibase could provide masked inputs out of the box.

**Screenshots**
[Some methods to creating mask using Javascript, with examples.](https://css-tricks.com/input-masking/#aa-estelle-weyls-input-masking)

**Comment by melohagan** [comment]
Hey @vidz1979 

I've created a Mask input custom plugin which may be of use to you: https://github.com/melohagan/budibase-component-nikita-input-mask

There is also a custom date-picker component that supports masking built in as well: https://github.com/melohagan/budibase-component-kasper-date-picker

If you need something more custom, you can check out the custom plugins docs here! https://docs.budibase.com/docs/custom-component
