### ISSUE TITLE
Query Binding Interpolation Bug in Local Environment

### ISSUE THREAD

**Issue by crisisdice** [Budibase/budibase#5242]
### Discussed in https://github.com/Budibase/budibase/discussions/5236

<div type='discussions-op-text'>

<sup>Originally posted by **crisisdice** April  4, 2022</sup>
Hello,

we have successfully set up Buidbase on our staging cluster, and working on apps here has thus far been a great experience. Now, we would like to leverage the power of custom REST queries to hit our own endpoints. To do so, I am running the budibase docker image locally and have imported the app from staging.

Now to the problem: basic queries from the app to the local postgres instance are working, but all queries involving bindings are failing. I have been working this morning on trying to isolate why this is the case. I have attempted various postgres/budibase version numbers (i.e. the same setup on staging, where the query bindings work), and I cannot figure out why this would work there but fail locally. Any help would be appreciated!

Cheers</div>

Update: Building v1.0.82 from source (the same version we have on staging) and testing locally fixes the problem, which means somewhere between this and the version used in the docker image a SQL generation bug must have slipped in.

**Comment by crisisdice** [comment]
In particular, the change that occured between these two versions `6dd09b6b4f3fd8cf9ff376d3d32cc690443016e6` and `66b565b0712acc5a3df988b8e0108a90f0d094c8` is this function:

```
+    getStringConcat(parts: string[]): string {
+      return parts.join(" || ")
+    }
+
```

in `packages/server/src/integrations/postgres.ts`, which partially explains the following error message:
```
{"message":"error: invalid input syntax for type integer: \" || $1 || \"","status":400}
```
 I am not super familiar with the code base but I will try and figure out a fix.

**Comment by crisisdice** [comment]
For reference, here is the [mustache](https://github.com/Budibase/budibase/files/8411417/mustache.txt) and [generated](https://github.com/Budibase/budibase/files/8411406/generated.txt) sql.

**Comment by mike12345567** [comment]
Hi @crisisdice - I can see this issue, thank you for the clear reproduction steps and the base query - made my life a lot easier! Will get a fix out soon.
