### ISSUE TITLE
Error Fetch View Data when use template Car Rental Admin Panel

### ISSUE THREAD

**Issue by mikewin** [Budibase/budibase#5244]
**Describe the bug**
When use template Car Rental Admin Panel, Select any view etc. Age Avg, report Error Fetch View Data, console log:
@budibase/server: ERROR [1649126394213] (16096 on home-office): The _stats function requires that map values be numbers or arrays of numbers, not 'null'
@budibase/server:     invalid_value: The _stats function requires that map values be numbers or arrays of numbers, not 'null'
@budibase/server:         at Object.throw (F:\work\test\synthesis\visual\budibase\packages\server\node_modules\koa\lib\context.js:97:11)
@budibase/server:         at F:\work\test\synthesis\visual\budibase\packages\server\src\api\controllers\row\index.js:68:14
@budibase/server:         at Generator.throw (<anonymous>)
@budibase/server:         at rejected (F:\work\test\synthesis\visual\budibase\packages\server\src\api\controllers\row\index.js:6:65)
@budibase/server:         at runMicrotasks (<anonymous>)
@budibase/server:         at processTicksAndRejections (node:internal/process/task_queues:96:5)

**To Reproduce**
1. use template 'Car Rental Admin Panel'
2. Click on sidebar 'Age Avg'
3. See error

**Screenshots**
![20220405104748](https://user-images.githubusercontent.com/6510502/161669159-40b5d4ab-45fc-4253-944d-c06d1fc16142.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [1.0.104 , 1.0.103]

**Comment by Bogey** [comment]
I have this error too (I'm on MacOS 12.3.1 with Safari).
Clicking on Mileaage Avg results in the same error. Also running the app and then selecting a different menu item.
The result is that the complete database seems to be wiped.

**Comment by melohagan** [comment]
Looks fixed!
![Screenshot 2022-08-23 at 17 00 55](https://user-images.githubusercontent.com/101575380/186206244-f90d47aa-bffe-44be-a51f-d70f85eafc66.png)

Closing.
