### ISSUE TITLE
Intermittent errors while retrieving data from PostgreSQL data source with JS

### ISSUE THREAD

**Issue by lsoica** [Budibase/budibase#5245]
**Describe the bug**
Occasionally, stat cards report JS errors and lists have empty data when using Postgres as a data source.

For the same dataset, this one fails:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/1623282/161695888-2e7a52f8-cc00-418f-baf1-45d589f9642d.png">

and then, by simply refreshing the page, this one is successful:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/1623282/161695929-6aa29b4b-e814-4751-8cd9-138fb57d3726.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave

**Comment by melohagan** [comment]
Hi @lsoica 

Have you found this to be a persisting issue? 

The JS error could be from trying to access a property of an undefined object, if for some reason the data is not coming back from the DB. 
You could use null propagation to handle that: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

I wasn't able to reproduce this myself. Are you working with a large data table?

**Comment by lsoica** [comment]
Hm, ok , forgot to update this one. Found out that this is not a PG related issue. It's because the rate limit hardcoded in the nginx config.

**Comment by melohagan** [comment]
Thanks for getting back @lsoica, I'm going to close this issue. If you are having any other issues feel free to raise a new request!
