### ISSUE TITLE
Automation - Bash scripting - timeout 1 second

### ISSUE THREAD

**Issue by Upgreydd** [Budibase/budibase#5248]
### Discussed in https://github.com/Budibase/budibase/discussions/5246

<div type='discussions-op-text'>

<sup>Originally posted by **Upgreydd** April  5, 2022</sup>
Hey.
I have a question - is there an option to change some timeout for script?
I've added binary which I need to use to `app-service` container and I can confirm existance of binary with:
```
ls -la /path/to/binary
```
binary have `+x` but when I try to execute `/path/to/binary` in automation with `Bash Scripting` I'm getting:
```
{
  "stdout": "spawnSync /bin/sh ETIMEDOUT",
  "success": false
}
```
Execution time is limited to 1 second </div>

**Comment by shogunpurple** [comment]
Hi @Upgreydd - it's actually 500ms at the moment. If you are running self hosted, what we could do is:
- Add an environment variable for bash timeouts
- Make it configurable

Would that work for you?

**Comment by Upgreydd** [comment]
> Hi @Upgreydd - it's actually 500ms at the moment. If you are running self hosted, what we could do is:
> 
> * Add an environment variable for bash timeouts
> * Make it configurable
> 
> Would that work for you?

Would be great - I have now script which is running ~ 1 minute when doing external requests to other servers and It's not able to finish due to timeouts - I think timeouf should be possible to set even to some high value like 30 or 60 minutes for bash runs.

**Comment by Upgreydd** [comment]
@shogunpurple https://github.com/Budibase/budibase/pull/5257 can you check this please?

**Comment by Upgreydd** [comment]
Fixed in https://github.com/Budibase/budibase/pull/5267
