### ISSUE TITLE
App preview failed to load

### ISSUE THREAD

**Issue by duyan11110** [Budibase/budibase#5282]
Hi,

Here's error detail:
![image](https://user-images.githubusercontent.com/10897328/162144339-5f90c7e5-bddc-4842-ae75-e9f1a45c0b6c.png)
![image](https://user-images.githubusercontent.com/10897328/162144399-7eeb143b-fe4a-4485-89be-5983fe055f7c.png)

I deployed Budibase version 1.0.108 on Docker for Window. Docker version 20.10.13, build a224086. 
Pls help me how to fix it.

**Comment by aptkingston** [comment]
Hi @duyan11110. I think your Budibase installation is fine - but what verison is your browser? I can see lots of layout issues in your screenshots, for example:
![image](https://user-images.githubusercontent.com/9075550/162149777-cd0af5fa-8734-4fb8-8021-a15621a31639.png)

Which would suggest that the flex `gap` property is not supported, which means you must be using a version of chrome that is nearly 2 years out of date (chrome 83). Could you confirm what version your browser is? If it is indeed chrome 83 I would strongly suggest updating it, not just for Budibase compatibility but mostly for essential security updates.
