### ISSUE TITLE
Global Media Management: Allow the user to store images to be used in the screens

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5285]
### Discussed in https://github.com/Budibase/budibase/discussions/5278

<div type='discussions-op-text'>

<sup>Originally posted by **willi-piske** April  7, 2022</sup>

In cases when you want to show a custom image, icon or illustration it would be much more straightforward and performant to upload the image file to the budibase's minio instance or to the database as an attachment and be able to load it into an image component rather than having to upload it to an external service and provide the URL to the image component.

---
Current workarounds:
1. saving the image file in the internal database as an attachment;
2. placing an image component inside a data provider and;
3. using handlebars to provide the attachment url to the image component.
---
It would be good to have an _assets_ tab in the budibase admin page where one can save files and then allowing the user to provide an URL or browsing and picking an asset from the image component settings tab.

</div>

#Designs

https://www.figma.com/file/CmpNdqPaUdgO8D1Lltocfx/Asset-management?node-id=0%3A1

**Comment by cantonsen** [comment]
I like this idea. Perhaps one could make folders (groups) of assets, that can be made available on a per app basis as well.

**Comment by shogunpurple** [comment]
Converting to epic

**Comment by MGAUSSAKKODIS** [comment]
so, is it now supported?
