### ISSUE TITLE
Allow users to choose 24-Hour time in Date Picker

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5287]
**Describe the feature request**
As a user, I want to be able to select 24-Hour time within a date-picker. 
Possibly add another checkbox in the designer `[] 24-Hour Time`

**Screenshots**
![Screenshot 2022-04-07 at 10 28 34](https://user-images.githubusercontent.com/101575380/162167937-6b97d9f3-d970-46b3-b3e7-2b1234fd1ce5.png)
![Screenshot 2022-04-07 at 10 28 53](https://user-images.githubusercontent.com/101575380/162168009-b53ff397-5018-414a-90c4-13ad8e1da289.png) << Allow the users to select 24-Hour time (no AM/PM)

---

In general, it would also be good to have more date formatting options for the date-picker value.

**Comment by Teico88** [comment]
I would love to see this in the near future.

**Comment by cantonsen** [comment]
I hope this can be fixed soon. It cannot be that difficult for the developers.....

**Comment by melohagan** [comment]
Done!
![Screenshot 2022-09-12 at 09 41 06](https://user-images.githubusercontent.com/101575380/189610226-2181fb0b-f558-4a49-a6e8-22beefca437f.png)

**Comment by ecxs** [comment]
How can I display a DateTime Field in Table view with Time only?
