### ISSUE TITLE
Tablet Or Mobile Phones - Virtual Keyboard Disappears - Unable to use input fields (Galaxy Tab, Galaxy A8, S9, Pixel) - Chrome 

### ISSUE THREAD

**Issue by conorw** [Budibase/budibase#5292]
**Describe the bug**
Using a tablet (Samsung Galaxy Tab A, Samsung Internet Browser latest version) if you click on an input field the virtual keyboard appears but the field loses focus.
Any attempt to then type in the field will cause the virtual keyboard to disappear.

**To Reproduce**
1. Use the Samsung internet browser (or chrome browser) to navigate to a budibase app with input fields
2. Tap on the input field
3. try to type using the virtual keyboard

**Expected behavior**
The field should retain focus and the keyboard input appear in the field

**Screenshots**

**Desktop (please complete the following information):**
Samsun Galaxy Tab A 
- Samsung Internet Browser
 - Version. Latest

https://user-images.githubusercontent.com/3536589/162190091-48ac6525-9e48-42c6-a5d3-1509b5b144f9.mp4

**Additional context**

**Comment by conorw** [comment]
Also replicated on Samsung phone (Galaxy A8, Samsung browser & Chrome browser)
![image](https://user-images.githubusercontent.com/3536589/162194795-a942a8dd-a212-4733-9cee-d8511b65328e.png)

**Comment by conorw** [comment]
also replicated on Galaxy S9, Google Pixel 4, both Chrome

**Comment by melohagan** [comment]
Appears to be fixed. Tested on AOSP with Samsung web browser.
