### ISSUE TITLE
[charts] Install fails on EKS Fargate with EFS persistence

### ISSUE THREAD

**Issue by greg-mcnamara** [Budibase/budibase#5293]
**Describe the bug**
I'm trying to deploy budibase on AWS EKS (Kubernetes) Fargate using the helm charts. Fargate requires EFS for volumes and dynamic volume creation/claims are not possible. On the first install attempt I noticed some persistent volumes/claims were dynamically created, but could not bind (as explained above). For the second install attempt I pre-created the volumes/claims manually, but the install failed with a message:

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim "minio-data" in namespace "budibase" exists and cannot be imported into the current release`

Can I install budibase with existing PVCs? I guess if I was reinstalling and the PVCs had been retained, the install would also fail?

**To Reproduce**
1. Attempt to install on Fargate, fails silently due to unbound PVCs (pods remain in state "Pending")
2. Manually create PVCs on EFS and try to install again, fails with error about existing PVCs.

**Expected behavior**
The install would recognize existing PVCs and not try to recreate them.

**Comment by MarcusSorealheis** [comment]
@greg-mcnamara I apologize for getting to this one so late. I recognize this error. Is this still an issue for you?

To provide more streamlined assistance and/or bug resolution, could provide the commands you used and the corresponding output? Also, if you modified the helm chart, please share that as well. I'll take a look at this one if it is still an issue for you. I'll also attempt to reproduce with the information I have thus far.
