### ISSUE TITLE
Tablet - Date Input Field - Missing Year Dropdown in Popup

### ISSUE THREAD

**Issue by conorw** [Budibase/budibase#5295]
**Describe the bug**
When using a browser on a tablet, the date field does not show the year dropdown

**To Reproduce**
1. Use a tablet browser to click on a date input field
2. The popup will not allow you to select a year

**Expected behavior**
The year should be selectable

**Screenshots**

https://user-images.githubusercontent.com/3536589/162190417-6a1c368e-f5bd-46ec-88e5-4e98720b2674.mp4

**Desktop (please complete the following information):**
 - Samsung Galaxy Tab A, Samsung Internet Browser, Latest Version

**Comment by shogunpurple** [comment]
@conorw - just before going any further with this, do these same issues occur on chrome/firefox on your tablet? If this is a samsung browser specific issue, it reduces the severity of it significantly.

**Comment by conorw** [comment]
hey @shogunpurple, for this issue, I believe it is related to their font size on the tablet.
I can check with the client, but I'm pretty sure it would affect all browsers on this particular tablet.

**Comment by conorw** [comment]
@shogunpurple using browserstack I was able to reproduce this on a Samsung Galaxy S8 v12, using the Samsung browser but NOT using chrome.

To reproduce, to go the browser settings on Samsung internet and increase the text scaling.
The reason I am unable to replicate with chrome is that the text scaling options seem to have no effect on the text size in the budibase app.
![image](https://user-images.githubusercontent.com/3536589/162193567-b83c55b8-6f7e-46ce-bfaf-820a08d4e63e.png)

**Comment by conorw** [comment]
in the meantime, I've advised the client to dial down the text scaling on their browser

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/11894
