### ISSUE TITLE
Builder freezes completely when an empty "App action" automation trigger confronts "Trigger automation" action.

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#5300]
**Describe the bug**
Builder freezes completely when a "Trigger automation" action is defined on any of the elements after an empty automation with an "App action" trigger was created.

**To Reproduce**
1. Go to 'Automations > Create Automation'
2. Select "App action" trigger. Leave it like this without any further configuration.
3. Go to anywhere in the builder and click on any element.
4. Click "Define actions > Add action" on the element.
5. Select "Trigger automation".
6. Everything freezes, but hover animations work. After reload (F5), you see that there's no action defined on the element. Everything unfreezes.
7. Repeat steps 4 - 5 and everything freezes again.

**Expected behavior**
No freeze or whatever behaviour you think there should be.

**Desktop (please complete the following information):**
 - OS: Windows 10, v.21H2, OS Build 19043.1586
 - Browser: Chrome
 - Version: 1.0.108

Maybe the problem is in the lack of any configuration after the "App action" trigger is selected?

UPD-1: To quickly test further automation setup, if after the "App action" trigger a "Do this - Backend Log" action is chosen, the "Trigger automation" action on the element doesn't trigger any freezes.

**Comment by Klience** [comment]
> Please do not tag team members directly.

Got it.

**Comment by aptkingston** [comment]
Thank you. I've found the issue and added a fix to a pending pull request.
