### ISSUE TITLE
Documentation for Delete Row: What is Row Rev?

### ISSUE THREAD

**Issue by cfepdan** [Budibase/budibase#5326]
I auto-generated a CRUD screen for a table in my MySQL database.

When looking at the actions performed by the "Delete" button,   the source of Row ID is intuitively `{{ Repeater.contacts._id }}`

The source of Row Rev is less intuitive... `{{ [c691d93a5f02f486c900fa198e3736633].[_rev] }}`

Displaying this in a paragraph reveals that this in fact contains the string "rev"

I have not found Row Rev referenced in the docs for actions... https://docs.budibase.com/docs/actions

What's it mean?

**Comment by melohagan** [comment]
Hi @cfepdan @poirazis 

The Row Rev is a CouchDB (budibase internal DB) specific feature. 
It is used to prevent users from deleting a record that has very recently been updated.

I have a PR out to remove this option, which will improve consistency between SQL and internal deletes, and also reduce user error.
