### ISSUE TITLE
Internal Error - Datasource is not configured fully on a page displaying REST data

### ISSUE THREAD

**Issue by oboudry** [Budibase/budibase#5339]
**Describe the bug**
While reproducing the example provided in the documentation for transfomers https://docs.budibase.com/docs/transformers, I managed to create the REST request with the appropriate transformer. Create a basic page and cards showing the brewery data that is used as an example. But when displaying it, also the content is there and all looks fine, a big ugly red button showing "Internal Error" pops up. 

Server error log can be found in following Gist
https://gist.github.com/oboudry/4ac60ef884cfa271541ac63b98a26606 

Error message is "Datasource is not configured fully" so I suspect it could be due to the fact that my datasource only implements the GET functionality, as it's a REST request with only that option set. But for the use case here I don't see a need for more.

**To Reproduce**
1. Create a new app with a REST datasource.
2. Follow the steps in https://docs.budibase.com/docs/transformers, I put my transformer code here: https://gist.github.com/oboudry/c01769ad77f8574759a3985d2115f41e
3. Create a blank page and add a cards block using the REST query, and map fields (name = state, description = count, image = flags)
4. All looks good but the big red "Internal Server Error" button

**Expected behavior**
No internal server error.

**Screenshots**
![Budibase_REST_Transformer_ERR500](https://user-images.githubusercontent.com/2891956/162619197-72eeaee5-7db6-4fe6-b52a-b1f394570673.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 2004
 - Browser Firefox
 - Version 98.0.2

**Additional context**

**Comment by that-one-tom** [comment]
+1, trying out budibase for the first time today and building a simple frontend for some REST data. No params/headers/auth need to be set. I am getting this error despite the REST API responding as expected and budibase processing and rendering its data.

Running latest version via docker using the docker compose file provided [here](https://docs.budibase.com/docs/docker-compose).
