### ISSUE TITLE
Allow for ILIKE search of an ANY or ALL array of multiple values so that OR can be used

### ISSUE THREAD

**Issue by bamboowonder** [Budibase/budibase#5352]
Hi there,

It would be a fantastic time saver, if we could just use the new Dynamic search everywhere instead of hand building search.

For that to be possible, we need to be able to ILIKE search using OR.

For Postgres, this is possible by using an ANY/ALL array.   (which interestingly, the pg planner breaks many queries down to this format anyway)

for a single line case-insensitive CONTAINs that allows for multiple values that use OR
UI:    field -> contains -> value1,value2
DB:   WHERE field ILIKE ANY('{%value1%,%value2%}')

and the opposite for a single line NOT
UI:    field -> doesn't contains -> value1,value2
DB:   WHERE field NOT ILIKE ALL('{%value1%,%value2%}')

I'd so appreciate this, and I think your other users would too!

Thank you,

**Comment by mike12345567** [comment]
Hi @bamboowonder - just to confirm, you'd like to be able to do this on the internal, Budibase tables, or would you like this specifically for SQL based tables?

**Comment by bamboowonder** [comment]
This is for external postgres primarily.  Though I imagine we'd use internal table for adhoc apps, but much less so.
