### ISSUE TITLE
"User does not have permission" when Automations/Trigger run by user with Basic Role

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#5359]
Hey all,

I have some trigger automations in button actions (send email and create row in another table). 
They work only in Power or Admin roles.
When user with Basic role press that button /trigger returns error:

```
{message: "User does not have permission", status: 403}
message: "User does not have permission"
status: 403
```
Seems it's a bug
I checked access for table, it allows Basic to write
Please help

**Comment by shogunpurple** [comment]
This one should now be fixed!
