### ISSUE TITLE
Dynamic filter with custom column labels

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5366]
### Discussed in https://github.com/Budibase/budibase/discussions/5358

<div type='discussions-op-text'>

<sup>Originally posted by **gerhardmpl** April 12, 2022</sup>
Allowing the use of configurable labels instead of default column names will increase user experience (like the _config columns_ feature for tables, maybe even using them for dynamic filter).</div>

**Comment by EuanRW** [comment]
This would be a great feature, any idea of when this will be added?
