### ISSUE TITLE
Cannot set role from Admin to No Access 

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5367]
**Describe the bug**
Related to this discussion: https://github.com/Budibase/budibase/discussions/5361
I am trying to configure roles for a dev user, to remove access to some apps. Whenever I select **No Access** a toast pops up with success, but the role does not change from *Admin*. I can change the role to *Power* or *Basic*.

**To Reproduce**
1. Add a new development access user
2. Go to Configure roles for this new user
3. Select an app, and select Role: No Access
4. Green "Role Updated" toast appears, but the role in the table remains *Admin*

**Expected behavior**
As an admin user, I should be able to restrict the access of dev users for any number of apps.

**Comment by sohail-hussain** [comment]
just ran into same bug - is the only workaround

1. export application
2. delete application
3. re-import the application
?

**Comment by aptkingston** [comment]
I think this is because if the user has the development priviledge then they implicitly have access to all apps and you can't revoke it. Developers can edit all apps.

You can unset admin as long as they aren't a developer so I don't think this is a bug, but just by design.

**Comment by melohagan** [comment]
I see, that makes sense. Maybe remove the 'No Access' option from the dropdown (or disable it) for users that have developer set.
