### ISSUE TITLE
Error message: "worker call timed out!" Status 400

### ISSUE THREAD

**Issue by CovantaDataManagement** [Budibase/budibase#5374]
**Describe the bug**
We are getting a weird message at the top of our Budibase forms when we are making API calls to save records.  There are no errors on our side and everything saves and processes properly.  The message is not stopping anything from working and seems to be more of a nuisance than anything else but it freaks out our end users.

**To Reproduce**
When we click the Save Action button on our Daily Operations form there are a series of actions which include:
I have attached screenshots of the actions setup.  The issue seems to occur just before the last Navigate to step

**Expected behavior**
There should be no 400 status message

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrime
 - Version 1.0.46

**Additional context**

**Comment by mike12345567** [comment]
Hi @CovantaDataManagement - I don't think the screenshot you mentioned has attached, it would be great if you could provide a bit more information about the configuration that causes it, as well as the version if Budibase you're using if you're self-hosted.

**Comment by CovantaDataManagement** [comment]
The attachment would not upload so I emailed to Michael Shanks along with the logs.  If you provide your email, I will send to you as well.  I am at clink@covanta.com

**Comment by mike12345567** [comment]
Hi @CovantaDataManagement - thanks I've had a look at the screenshots now, from the sound of the error I believe one of the API endpoints is being slow to respond, by default now Budibase gives queries 10 seconds to respond before throwing an error, you could try opening this up to something very large, like 300 seconds to see if the API endpoint is being slow - if the issue persists then we'll need to look into why Budibase is missing the API response.

To increase the timeout you can set the `QUERY_THREAD_TIMEOUT` environment variable on your `app-service`, e.g. `QUERY_THREAD_TIMEOUT=300000` for 300 seconds (set in milliseconds).

**Comment by mike12345567** [comment]
Hi @CovantaDataManagement - a few questions in that case:
1. What did you up the threshold to? Did you get the same error in the same amount of time or did it take significantly longer for the error to occur?
2. Which version of Budibase is this based on?
3. If you make the REST API call from within the builder data section (through the actual query configuration section itself) do you get the same error or does it preview correctly?

**Comment by CovantaDataManagement** [comment]
We are on 1.0.046 I think.  It seemed to take longer.  The wierd thing is that all our API calls are functioning well.  It seems to happen before the navigate to as opposed to everything else.  The API calls through the builder and using curl respond quickly.  I copy pasted the threshold in your comments

**Comment by CovantaDataManagement** [comment]
This error was being caused by a slow running SQL server backend.
