### ISSUE TITLE
Allow assignment of field values, on change of other inputs

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#5392]
Recently, we changed the way `Default Value` works, so that it only executes once - on load.

Whilst this was the correct decision, and fits better with the term "Default Value", it was a breaking change.

Previously, people were using `Default Value` to trigger updates on other fields. I have recommended this method many times. Discussions have been raised about this already.

So, I am proposing to fill this gap with the following changes.

### 1. Add "Define Actions" for  `On Change` of all form inputs  

This is something that has been requested many times, and is a useful feature in it's own right. For example, people want to trigger `Execute Query` on change of a dropdown.

### 2. Extend the `Update State` action to allow assignment of form fields

![image](https://user-images.githubusercontent.com/3524181/163145387-979ab08b-b47b-4b01-a698-d51ef24d159d.png)

- In the "Type", add a "Set Form Field"
- The "Key" dropdown would then be populated with all available form fields

We could also implement this as a separate action.

### SUMMARY

So, the overall flow to update a text input, based on a select input:
1. Add a "Define Action" for "On Change" of the Select
2. Add and "Update State" action
3. Set the `Form.Fields.MyTextColumn` to whatever value we defined

I think this makes sense overall, and is how I would normally approach this problem as a programmer anyway.

**Comment by dubbya** [comment]
Theres also oninput to capture text field changes without losing focus.

**Comment by aptkingston** [comment]
> @mjashanks @aptkingston Can this issue be closed - is there anything else that needs done?

Yep this can be closed off!
