### ISSUE TITLE
Cron Trigger which created row does not trigger Row Created Trigger

### ISSUE THREAD

**Issue by theobouwman** [Budibase/budibase#5396]
**Describe the bug**
I have an automation (A) which will run every minute. In that automation I create a row.
The other automation (B) is triggered when a new row in the same table is created.

When I create a record myself automation B is triggered.

But, when automation A creates a record the automation is not triggered. 

Is this intended behaviour?

**Comment by melohagan** [comment]
In my opinion, this should be the intended behaviour. 

Automated actions shouldn't trigger automations because of the risk of infinite loops, and unexpected data loss.
