### ISSUE TITLE
Auto-detect SQL enumeration types when building schemas

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5401]
**Describe the bug**
I have a pretty simple table in mysql schema as below 

`CREATE TABLE `oc_patients` (
  `id` int NOT NULL AUTO_INCREMENT,
  `FirstName` varchar(100) DEFAULT NULL,
  `LastName` varchar(100) DEFAULT NULL,
  `Gender` enum('Male','Female') DEFAULT NULL,
  `DOB` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)`

Now i connect budibase to mysql and fetch tables, all good.
When i try to "create row" on the above table, the ENUM field Gender, is shown as a text box and not as an Options Dropdown.

I am running the latest budibase version with docker.

**Comment by mike12345567** [comment]
Hi @poirazis this is not currently a supported feature of Budibase - at some point in the future we may introduce the ability for Budibase to automatically detect enumerations, but for now you can set it manually by editing a column:
![image](https://user-images.githubusercontent.com/4407001/163217722-082fcc5e-6bbb-4aa8-90e3-9c97e7d113c6.png)

Once you switch to options type you can fill in a list of enumeration options.

**Comment by poirazis** [comment]
Thank you !

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/3826
