### ISSUE TITLE
Blocks V2

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5403]
## Description
The blocks V2 project aims to provide much more power and flexibility around blocks, such as avoiding lock in, and make blocks a core concept of budibase through allowing users to interact with them in more sophisticated ways.

## Spec
https://budibase.atlassian.net/wiki/spaces/PROD/pages/98041865/Blocks+V2

## Teams and Stakeholders
- avalanche team

## Workflow
- [x]  Spec Created and pasted above
- [x]  Product Review
- [x]  Designs created
- [x]  Individual Tasks created and assigned to Epic

**Comment by davidjeba** [comment]
can you update description? just curious on what it is?
