### ISSUE TITLE
Automation - Row Created Bug

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#5412]
***Describe the bug***
Automation works in test but not in actual app.

***To Reproduce***
**What you need:**
1. Table
2. Automation -> *When this happens* = "row created in Table" *Do this* = "Send email"

**Steps to reproduce the behavior:**
1. Test run automation works
1. Create row in table (actual site)
2. Automation doesn't work

***Expected behavior***
It should send out emails when row created.

**Comment by melohagan** [comment]
Hi @kasgithub8 Just to confirm, it is not working in your published app?
