### ISSUE TITLE
Always working "Go back" button 😄 

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#5420]
**Describe the feature request**
So a common problem for me was that there was no real "back" button.
There is the option to "Navigate to" a screen but that's useless most of the time.
With this simple JavaScript it directs you to the link before.
The second line directs you to the website "http://example.com" if this, f.e., was the first link you opened

**Screenshots**
*JavaScript:*
```
window.history.back();
    window. Location = "http://example.com";
```

**Comment by sergey-dme** [comment]
This feature is needed and would be really useful.
COS: For example, a have a screen with a form and link to this screen is accessible from few different  places in my app, I want if I close that screen after form submission "Navigate to" then it goes to a previous place in my app from where that screen was opened. 
Currently I solved this by using my binding in url like` /somedoc/:id/:urlback` and then I use handlebars "if", "is" in url address of button action Navigate to

**Comment by melohagan** [comment]
@sergey-dme Would it be easier to use App State to keep track of the previous screen? Then you could simply do Navigate To `{{ State.PreviousScreenPath }}`

**Comment by sergey-dme** [comment]
> @sergey-dme Would it be easier to use App State to keep track of the previous screen? Then you could simply do Navigate To `{{ State.PreviousScreenPath }}`

Hey @melohagan yes, that's another good solution but it would working only for a buttons/icons, idk how to use it (set value) with tables, where I have a link row

**Comment by melohagan** [comment]
@sergey-dme Good point about the linked rows. As they're not actions, there'd be no way to update the state.
