### ISSUE TITLE
unable to reach internet with proxy

### ISSUE THREAD

**Issue by StarZeus** [Budibase/budibase#5422]
I have a self-hosted budibase setup running behind a corporate proxy and we need to integrate with okta ODIC. As the open ID "Config URL" is hosted in aws (outside our private network). As backend-core/src/middleware/passport/oidc.js is using "node-fetch" to get the config file it does not use any proxy setting to connect to the internet and authentication fails.

Also app templates are not loading since the template manifest and the templates are hosted on aws, they are not accessible without proxy configuration.

We need a way to configure proxy for budibase/worker and budibase/apps.

**Comment by shogunpurple** [comment]
I believe this one was resolved in your PR @StarZeus - is that correct?
