### ISSUE TITLE
Budibase builder not working

### ISSUE THREAD

**Issue by gerhardmpl** [Budibase/budibase#5462]
**Describe the bug**
When logging in to Budibase at https://account.budibase.app/auth/login, opening an existing app in the builder results in error messages (see #5460)

**To Reproduce**
1. Go to https://account.budibase.app/auth/login
2. Login to your account
3. Open an existing app or try to create a new one
4. See error messages

**Expected behavior**
Apps can be opened or created

**Screenshots**
![grafik](https://user-images.githubusercontent.com/40722408/163729758-abaa2a51-a711-4628-89e1-64a8dcb090fb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser  Chrome 100.0.4896.127 or Firefox 99.0.1

**Additional context**

**Comment by shogunpurple** [comment]
Hi @gerhardmpl - sorry just seeing this. Is this still occurring for you? We restarted one of our nodes there, which seems to have solved some issues. Thanks!

**Comment by gerhardmpl** [comment]
Hi @shogunpurple - no problem and all good now. Thanks for the swift reaction. Have a great long weekend.
