### ISSUE TITLE
"Error publishing app" when trying to publish

### ISSUE THREAD

**Issue by raziele** [Budibase/budibase#5463]
While trying to update my app, I fail to publish the app to production, getting the following messages:
"Error publishing app"
"Fail to sync production and dev databases"

Seems like the reply is 504 (?)

Trying to publish using the "Publish" button

![image](https://user-images.githubusercontent.com/2432693/163730151-2fe7a7d4-9612-45fa-b483-cd35689f110e.png)
![image](https://user-images.githubusercontent.com/2432693/163730405-b6f7fd17-d8ff-4f2e-80ad-7f4f642625a2.png)

Environment info:
 - OS: macOS
 - Browser: Chrome
 - Version: 100 (Intel)

Additional context:
I've been trying to publish multiple times along the day - all got the same result.
Also tried downgrading Budibase from latest version - issue still persisted

**Comment by shogunpurple** [comment]
Hey @raziele - sorry just seeing this. Is this still occurring for you? We restarted one of our nodes there, which seems to have solved some issues. Thanks!

**Comment by raziele** [comment]
@shogunpurple thanks for the prompt response.
Yes, it seems to work, I am able to publish now. 
Thank you! this product is awesome ☺️
