### ISSUE TITLE
API Too many requests, please try again later

### ISSUE THREAD

**Issue by mattiason** [Budibase/budibase#5469]
**Describe the bug**

**To Reproduce**
1. I tried to add about 160 items via API Post with a delay of about 500 ms per item with is well within the limit of 10 per soned via API. I have both tried on your hosted environment and on our own hosted 

**Expected behavior**
Be able to add via API Post 
**Screenshots**
<img width="827" alt="image" src="https://user-images.githubusercontent.com/45860668/163824950-2ec7e595-afc8-449e-bbb9-5fa3dc0d3dd3.png">

I have tried both via postman and via the API Reference tool

**Comment by melohagan** [comment]
Is it definitely 10 per second, and not 10 per minute? 

https://developers.support.clio.com/hc/en-us/articles/360023272714-What-Are-The-Rate-Limit-Headers-Returned-After-Each-API-Call-#:~:text=X%2DRateLimit%2DLimit%3A%20The,now.

**Comment by smitsialis** [comment]
I am also having this issue.  It seems to be tied to the current user.  If I use a token from a different user it works (have not pushed more than 100 records).  Is there a way to reset this for the user having issues (workaround)?  I tried restarting the docker and even upgraded it and still get "too many request" for that user, even for a single GET.  Running v 1.1.21.
