### ISSUE TITLE
Deleting the only condition on an element does not actually delete the condition.

### ISSUE THREAD

**Issue by cfepdan** [Budibase/budibase#5473]
I can create a condition, like a show/hide condition, for an element. However, when I change my mind and delete the condition, the condition disappears but still has the original effect.

**To Reproduce**
1. Add a paragraph to a blank screen.
2. Configure conditions -> Add condition -> Hide component if 1 equals value 1
3. Click "Save"

Deselecting the paragraph will result in its disappearance.

4. Now click on the paragraph in the nav panel.
5. Configure conditions
6. Click the "X" to delete the condition.
7. Click "Save"

Deselecting the paragraph continues to result in its disappearance.

**Expected behavior**
Deleting a condition should render the condition ineffective. In the example above, the paragraph would be visible once deselected.

**Comment by aptkingston** [comment]
Hey @cfepdan. The condition does actually get removed, but the change just isn't reflected in the previewimmediately. If you refresh your page (or change page, then go back to your initial page) you'll notice that it has indeed been removed.

There still is a small bug here that the change is not reflected visually immediately, but the condition has indeed been removed from the component.

**Comment by cfepdan** [comment]
Ah. I hadn't tried that. Thank you!
