### ISSUE TITLE
"Service Unavailable", Random queries completely failing

### ISSUE THREAD

**Issue by Kuuchuu** [Budibase/budibase#5474]
**Describe the bug**
At the moment our main app is mostly unusable for the intended users. I personally noticed all other apps started failing to load randomly maybe a day or two ago.
When an app attempts to query data for use, the queries seem to be failing at random (or possibly it's just page elements failing to load?).
The only error I've seen so far is when loading the app's page "Service Unavailable" appears at the top.
Our data source is NocoDB using a REST API. All test queries outside of Budibase work fine every time. Queries work every time inside the Data Source configuration page.
The queries have not changed since I added them around v1.0.60, or whenever I started using Budibase. Budibase is currently the latest public version, v1.0.110. The app is also on the latest version.
The queries all worked fine until maybe a week or so ago. Logs appear to be normal, but I can provide whatever logs may be useful.

**Screenshots**
![image](https://user-images.githubusercontent.com/20036947/163924921-da0709b7-de76-49d8-8d81-944849958e46.png)
![image](https://user-images.githubusercontent.com/20036947/163924009-a4a1544e-4250-41b9-a6f7-39ac0337a009.png)
![image](https://user-images.githubusercontent.com/20036947/163923869-a573cc07-9838-4d5c-a379-619830002e62.png)
![image](https://user-images.githubusercontent.com/20036947/163926073-f8d05176-e5f8-40ed-a3f1-7ec9114ee715.png)

**Desktop (please complete the following information):**
 - OS: Solus/Windows/iOS/Ubuntu
 - Browser: Brave/Chrome/Edge/Safari/LibreWolf/Firefox

**Additional context**
Exporting the app and importing does not fix the issue.
I am unable to downgrade to a version earlier than the latest, as several of our apps were remade from old/outdated imports on the latest.

**Comment by aptkingston** [comment]
Hi @Kuuchuu. `Service Unavailable` (HTTP 503) is an interesting error, and I wonder if it originates from the Budibase backend or from further upstream. Could you check your browsers dev tools network tab when these errors happen? It would be helpful to see which API calls are erroring and whether the 503 status code is coming from us or the external datasource.

**Comment by Kuuchuu** [comment]
@aptkingston
Here is a pastebin of my DevTools console upon loading the main home page/app: https://pastebin.com/BgQZnrKD

**Comment by Kuuchuu** [comment]
Sorry @aptkingston , just realized you said Network Tab. Here is a copy of everything in the Network Tab:
[b.d.com-Network.har.txt](https://github.com/Budibase/budibase/files/8514894/b.d.com-Network.har.txt)

**Comment by melohagan** [comment]
@Kuuchuu I'm closing this issue as it is both stale and does not have reproduction steps.

If you find the issue persists in the latest version of Budibase, please feel free to raise the issue again including the reproduction steps.
