### ISSUE TITLE
App Preview Failed To Load

### ISSUE THREAD

**Issue by kjc12345** [Budibase/budibase#5478]
Not Self-Hosted, hosted via Budibase

**Describe the bug**
When on the 'Design' tab building any app, the error message 'App Preview Failed to Load, An Unknown Error Occurred'  is displayed on the screen, meaning the screens cannot be designed. 
This is through my company laptop and was wondering if there are any blockers in place that may be on a company firewall or VPN that may be blocking this. 
I have raised a ticket with my IT department but then are unable to find out what they have in place that mat be blocking this.
I have used multiple browsers, whilst both connected and disconnected to the VPN.

**To Reproduce**
1. Go to 'Design'

**Expected behavior**
To be able to design the screens

**Screenshots**
See below.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge, Chrome

**Additional context**
On my company laptop.
[
![image](https://user-images.githubusercontent.com/103994641/163968215-125d55b8-8a18-4565-a847-cba0f1d80d9f.png)
](url)

**Comment by aptkingston** [comment]
Can you please open your browser dev tools and see if there are any errors or failing network requests? This is usually caused by a network request failing (or being blocked) or a browser extension.

**Comment by kjc12345** [comment]
@aptkingston Thanks for replying. I have include a screenshot of the console and error. 

![image](https://user-images.githubusercontent.com/103994641/163975349-64b5e9b7-50ec-4e63-98c4-2403c7da79ea.png)

**Comment by aptkingston** [comment]
@kjc12345 thanks for the screenshot. That confirms that the reason your app won't load is that something is blocking the request to load our `budibase-client.js`, which is our code for running client apps. This might be some sort of security policy on your laptop or in your browser, but I can't really help you more than explain that this is the issue.

If you go to the network tab or hover over `budibase-client.js` it should show you the full URL that it is trying to load. Please make sure that nothing is blocking a request to that domain.

**Comment by Bytelegion** [comment]
Same case happen with my instance, when i am trying to load budibase client lib file from s3
