### ISSUE TITLE
Table block: Open in modal should have the close action on save

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#5480]
When using the table block (open in modal checked), the modal should close when a user clicks Save on the record (within the modal).

https://vimeo.com/700749046/803ffc28a7

**Comment by aptkingston** [comment]
The screen that opens is chosen by the user, so the table block can't control what happens in a button click on another screen. If you want to open in a modal, it's up to the user to ensure the modal is closed again whenever they perform some action on whatever screen they pick.

We could set up autoscreens to do this by default, if we updated the autoscreens to also use the table block (they use the normal table at the moment still).

**Comment by joebudi** [comment]
Cheers @aptkingston

**Comment by shogunpurple** [comment]
No longer relevant with side panel
