### ISSUE TITLE
Allow budibase object store bucket names to be configurable through environment variables

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5487]
### Discussed in https://github.com/Budibase/budibase/discussions/5430

<div type='discussions-op-text'>

<sup>Originally posted by **dougwettlaufer** April 14, 2022</sup>
In the helm chart, under `objectStore` I see references to `region` and `AWS_ACCESS_KEY` but I'm a little lost on setting the bucket. From the looks of things it seems like the bucket names are hardcoded in utils.js

```js
exports.ObjectStoreBuckets = {
  BACKUPS: "backups",
  APPS: "prod-budi-app-assets",
  TEMPLATES: "templates",
  GLOBAL: "global",
  GLOBAL_CLOUD: "prod-budi-tenant-uploads",
}
```

Since a bucket in S3 must be globally unique this won't work. Please excuse my lack of JS knowledge but from grepping through the code it doesn't seem like there's a way to override the bucket name or add a unique prefix. Can someone please confirm that's the case?</div>

**Comment by MartinPicc** [comment]
I tried using newly created ENV variables to set custom names for buckets, without success.

I'm using docker compose install, here is what I did:
- In `.env` file, I have defined `APPS_BUCKET_NAME` to a value different from the default (default value is `prod-budi-app-assets`)
- then I start the stack and create a new app
- when I browse the APPS_BUCKET_NAME bucket, I can see the subpath `app_<appid>` for the newly created app with `budibase-client.js` file inside
- however, when I open my app and then go to the "Design" tab, I see the error "App preview failed to load":
![image](https://user-images.githubusercontent.com/35298861/194719250-02c7fe1a-cc2d-491f-98e6-e119a45bf40f.png)
and if I open the console of my browser, I have HTTP 403 Forbidden error for the following request: `GET https://fra1.digitaloceanspaces.com/prod-budi-app-assets/app_5047077b270842688fc618119725067d/budibase-client.js?v=2.0.3`

It tries to download the file from the bucket `prod-budi-app-assets`, despite the env variable `APPS_BUCKET_NAME` having a different value. So it seems that this bucket name (and maybe others) is still hard-coded somewhere in the code, hence it tries to download the file from the wrong bucket. Especially I found this suspect line: https://github.com/Budibase/budibase/blob/270836b30ef08c89f172c0394ed712fc2e28d439/packages/server/src/constants/index.js#L177

NB: you will note that my bucket host is a digitalocean spaces, which is unusual but as soon as I set the `APPS_BUCKET_NAME` to its default value, it works fine with this configuration
