### ISSUE TITLE
Text Field Labels

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#5488]
Hey,
I have a simple "CSS/Design" Problem.
I can't change the size of the Text Field Labels nor can I insert
a line break Handlebars & JavaScript.

Sincerely, 
K

**Comment by shogunpurple** [comment]
@kasgithub8 Sorry, I have no idea what you are asking for here. Please use the bug issue template that we provide to tell us more about your issue. You have deleted the entire issue template and written this instead, which makes it difficult for the team to help given the vague description. 

Closing this - please open a new and more detailed issue.

Thank you.
