### ISSUE TITLE
Field from Relationship Unavailable with Budibase defined relationship between SQL tables

### ISSUE THREAD

**Issue by zimmra** [Budibase/budibase#5495]
## **Hosting**

- Self
  - Method: <method>docker compose
  - Budibase Version: <version>1.0.110
  - Database: MS SQL (also confirmed on PG SQL)

## **Describe the bug**
When attempting to use a field from a related table, the object is only populated with `primaryDisplay` and `_id`. 

 ***I believe budibase is either is improperly loading the related object, or the formula helpers are incorrectly recommending these fields as being available as a relationship/in the formula***

## **To Reproduce**
1. Create 2 MSSQL Tables, with an ID column for use as key and additional columns to reference 
2. Create Relationship with ID as key 
3. Create new 'Formula' column on one table
4. Try to use a formula to reference the related table (e.g. `{{ fromtable.0.examplecolumn }}`
5. previous step yields no results, but `{{ fromtable }}` has `primaryDisplay` and `_id` as the only fields in the object

## **Expected behavior**
For the value from related table `examplecolumn` to be displayed. 

## **Screenshots**
> ### Formula Helpers indicating these fields can be used
>>![image](https://user-images.githubusercontent.com/28514085/164147439-f5b6e492-ec2f-46c9-a274-35baacb7b1af.png)

**Additional context**
Info on my table structure below:

>#### Table: TimeSheets
>>primary key: Id
Created Relationship Column: TimeSheetEntries
Desired Related Columns: TimeSheetEntries.StartTime, TimeSheetEntries.EndTime, etc

>#### Table: TimeSheetEntries
>>primary key: Id (_does not equal TimeSheets.Id_)
bb relationship foreign key: TimeSheetID (_does equal TimeSheets.Id_)
Created Relationship Column: TimeSheets

From discussion #5494

**Comment by zimmra** [comment]
For what it's worth, I have since recreated this scenario with PGSQL, so it is not limited to just MSSQL

**Comment by zimmra** [comment]
@mike12345567, I spun up a second stack running branch v1.0.117 and I am able to properly reference related table columns!

Do you guys prefer for these issues to stay open until it's in the production release or should I go ahead and close this?

**Comment by zimmra** [comment]
I may have spoken a bit too quickly

Worked fine at a glance, but started getting some errors when flipping through the tables pages (this was thrown once I got to page 9)

```
ERROR [1650653771214] (29 on 4933b8f7488a): Cannot convert undefined or null to object
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at ExternalRequest.squashRelationshipColumns (/app/dist/api/controllers/row/ExternalRequest.js:284:40)
        at /app/dist/api/controllers/row/ExternalRequest.js:358:95
        at Array.map (<anonymous>)
        at ExternalRequest.outputProcessing (/app/dist/api/controllers/row/ExternalRequest.js:358:77)
        at ExternalRequest.<anonymous> (/app/dist/api/controllers/row/ExternalRequest.js:613:37)
        at Generator.next (<anonymous>)
        at fulfilled (/app/dist/api/controllers/row/ExternalRequest.js:5:58)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
Trace: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ExternalRequest.squashRelationshipColumns (/app/dist/api/controllers/row/ExternalRequest.js:284:40)
    at /app/dist/api/controllers/row/ExternalRequest.js:358:95
    at Array.map (<anonymous>)
    at ExternalRequest.outputProcessing (/app/dist/api/controllers/row/ExternalRequest.js:358:77)
    at ExternalRequest.<anonymous> (/app/dist/api/controllers/row/ExternalRequest.js:613:37)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/api/controllers/row/ExternalRequest.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  expose: true,
  statusCode: 400,
  status: 400
}
```

**Comment by mike12345567** [comment]
Hi @zimmra - thanks for giving this a test I've pushed a fix for it. Generally we wait to close an issue until QA has given it a test and confirmed that it is working as expected, then we release it (in the case of hotfixes) and close the issue.

**Comment by zimmra** [comment]
Discovered this present elsewhere in my test environment **_(running v1.0.132)_**
When using a binding in the builder, referencing the column that was made with the relationship produces the same results.
For example:
In Design > Screens > Cards Block >Try to use a binding that uses the created column from the relationship that was previously made

It will display the `primaryDisplay` and `_id` options only

The fix you previously pushed seems to have resolved/works as intended when the same binding is used in the Data section, when adding a Function column to a table
@mike12345567 

![image](https://user-images.githubusercontent.com/28514085/166125909-9b67d3ec-5ba4-4c7d-9bd9-3f89c930f4a8.png)
![image](https://user-images.githubusercontent.com/28514085/166125913-6c35114c-8704-4af0-bc9c-68a9494cd60c.png)

**Comment by mike12345567** [comment]
Hi @zimmra - this is expected functionality in the frontend, for now we don't return the full relationships from the UI. To get the full relationships you use another data provider, which retrieves the relational data. We do this to avoid a recursive relationship issue, although this may change in the future.

We have docs on this here: https://docs.budibase.com/docs/fetching-data#displaying-relational-data
