### ISSUE TITLE
JS Scripting Automation Action: JavaScript Bindings not working

### ISSUE THREAD

**Issue by Topener** [Budibase/budibase#5505]
**Describe the bug**
The JS Scripting automation action does currently not support JS bindings but instead requires the outdated bindings through handlebars.

Right now, this is not possible, but it should be.

```js
const cars = $("steps.2.rows");
```

This trows an error: 

```json
{
  "success": false,
  "response": "ReferenceError: $ is not defined"
}
```

Currently, the only way to get data is directly interfacing through handlebars

**Expected behaviour**
JavaScript bindings should be available like also with any field with bindings

**Comment by xnohat** [comment]
JS Scripting can access JS Bindings through 
```
const cars = steps[1].rows
```

**Comment by dalyd14** [comment]
Can you also reference the current loop item. `{{ loop.currentItem }}` does not appear to be working for me. It is resulting in a `SyntaxError: Unexpected token`

**Comment by egutierrez-ar** [comment]
I would like to bring this issue up, as I found it confusing that the prompt from the intrface encourages you to use the `$("variable")` syntax when one should be using `variable` directly

![image](https://github.com/Budibase/budibase/assets/70960423/cb70ab84-e5df-4d7a-9317-4daee9f81032)

In fact, the documentation also makes use of the correct `variable` syntax but is not properly communicated in the user interface
