### ISSUE TITLE
Error: Error constructing OIDC authentication strategy

### ISSUE THREAD

**Issue by wangzhendong-c** [Budibase/budibase#5506]
I deploy with Docker，
I used keycloak authentication, but bbwork reported the error ‘Error constructing OIDC authentication strategy’
Config URL Configuration is' http://localhost:8011/auth/realms/master/.well-known/openid-configuration '
keyclaok  Valid Redirect URIs  is ' http://localhost:10000/api/admin/auth/oidc/callback'

**Comment by imcheck** [comment]
I think you need to change `localhost` to each your keycloak, budibase url.

**Comment by wangzhendong-c** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。
