### ISSUE TITLE
Configurable proxy ratelimit

### ISSUE THREAD

**Issue by lsoica** [Budibase/budibase#5517]
Currently the proxy nginx ratelimit is hardcoded to 20r/s
https://github.com/Budibase/budibase/blob/develop/hosting/nginx.prod.conf.hbs#L12

For a page with 14 charts where each chart gets its data from a PostgreSQL query, I often get "Error while executing JS" in the browser as a consequence of a 503 received from the proxy. Increasing the ratelimit in the nginx config fixes the issue. But I can only manually do that inside the container, and that's an ephemeral change.

**Comment by daawaan** [comment]
Hey @lsoica, have you tried changing the official proxy service running the `budibase/proxy` image in the production `docker-compose.yaml` with a customized proxy service directly running the `nginx` image then mounting a customized nginx configuration?

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/6028
