### ISSUE TITLE
Show which columns are Formula Type

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5523]
**Describe the feature request**
It would be nice to see which columns in a data view table are using formulas. I had created some formula columns a while back and I couldn't remember which ones they were. 
Does any consideration need to be made for *Static* versus *Dynamic* formulas?

**Screenshots**
This is a formula column, but there's no way to tell looking at it:
<img width="118" alt="Screenshot 2022-04-21 at 17 25 49" src="https://user-images.githubusercontent.com/101575380/164507002-094f4545-1165-477d-a11a-47bf4769bce2.png">

Suggestion from @AndyWhann - add icon to column label
![image](https://user-images.githubusercontent.com/101575380/164506731-102b5ebc-4b4f-4430-980f-7d34793ff738.png)

**Comment by jaysoni-ash42** [comment]
@melohagan  is this issue still active? can i work on this issue?

**Comment by melohagan** [comment]
Hey @jaysoni-ash42 

This one has been recently addressed with the new Grid view!

Thanks!

![Screenshot 2023-05-25 at 10 57 19](https://github.com/Budibase/budibase/assets/101575380/765ccbed-e7e3-4065-aaa4-f6e191ded666)
