### ISSUE TITLE
filter table block with "like" or "start with" condition on a text field

### ISSUE THREAD

**Issue by neoguet** [Budibase/budibase#5549]
**Hosting**
- Self
  - Method:  docker compose
  - Budibase Version:  1.0.110
  - App Version:1.0.110  with internal database

**Describe the bug**.
Hello, I try to make search form with table block. I I follow the doc (well I think)  but when I define a filter with "like" or "start with" on a text field, it seems not work but with an option picker it's work.
![image](https://user-images.githubusercontent.com/4342594/164812731-49caba6a-297c-48be-860c-326ab8ca9fc0.png)

**To Reproduce**
[test filter-export-1650667196348.txt](https://github.com/Budibase/budibase/files/8544652/test.filter-export-1650667196348.txt)

I don't understand what is wrong
thanks

**Comment by bjornclauw** [comment]
Hi,

`Like` is also not working for me. (read somewhere this is a limitation when working with budibase databases)
`Starts with` should work.
I tried your app, changed `Like` TO `Starts with` and it didn't work.

Seems you found a bug >> Filter does not update when you save (it shows your new condition in the editor but does not apply the correct condition in your app)

Workaround for you: 
- delete your first rule (for title)
- re-add it like so (if you need to change it, you have to delete it and re-add it)
![image](https://user-images.githubusercontent.com/32811735/164888913-37e7d908-a5e3-4eea-8a35-5c6e766a71b6.png)

after this your your app is working on my docker install (1.0.110)

**Comment by neoguet** [comment]
thanks @bjornclauw .
If I delete the filter for title and then  I re-add it  with `start with` condition it's work.
But when I change condition for `like` it doesn't work. perhaps a limitation ? 
And to finish, If a re-change the condition for `starts with` it doesn't work anymore.
I've tested with the version  1.0.131
