### ISSUE TITLE
Text editor on mobile

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#5555]
Unable to move to a new line using the text editor on mobile unless I add a space or special character at the end.

Chrome on mobile.

**Comment by aptkingston** [comment]
When you say text editor do you mean an input field, the long form field with normal formatting or the long form field with rich text formatting?

**Comment by joebudi** [comment]
Rich text editor.

**Comment by deanhannigan** [comment]
This seems to be an inherent flaw in the underlying Codemirror dep used in EasyMDE itself.
You can can see the issue isolated in it's own right  https://codemirror.net/5/demo/placeholder.html

In Chrome on Mobile the behaviour, in general, is very odd. It won't let you have a newline after the last piece of content and when you start to delete, it will sometimes start adding in elements it already removed.

https://user-images.githubusercontent.com/5913006/193292758-97cb2399-1bb0-4002-b4fa-f6e67c89af0b.mov

**Comment by aptkingston** [comment]
Awaiting upstream fix.
