### ISSUE TITLE
Improved filtering

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#5585]
**Describe the feature request**
On Youtube, someone asked:
> Quick question (which is a deal breaker for me), If I had a list of videos (for example), can I add tags to them. (480p, catvid, etc), and then search. Is the search limited to one field, or can I do 'name like XXX' with the tags X,Y ? Do you support tagging and search based on the tags along with other fields?

My answer:

> Hi. If you have a list of tags, you can use the dynamic filter component to solve your query: https://docs.budibase.com/docs/adding-a-search-field#3-using-a-table-and-dynamic-filter---the-filtersearch-hybrid-approach

I attempted to provide alternative solutions specifically for custom tags, but when testing BB I couldn't:
- filter by relationship(sep tags table)
- filter by json field type

I imagine this will be popular (filter by tags, categories, etc), and is something we should support IMO. Apologies if we already support this and I wasted your time. @melohagan and I could not find a solution.

I actually think a tags field type might be nice - it would marry up with the on-change event nicely.

**Comment by HeronCS** [comment]
We're migrating away from budibase for this sole reason of not being able to filter by relationships.

**Comment by melohagan** [comment]
![Screenshot 2022-07-15 at 11 36 51](https://user-images.githubusercontent.com/101575380/179207225-b5d147dc-01fc-4d9d-acd4-464283b2eb5f.png)

I noticed you can add a json array to the Dynamic Filter, but I'm assuming this is a bug.

The new release has added the 'Is in' filter but this is the inverse of what's needed here. The code should hopefully be reusable though, at least for the filter by json array type. 

One 'Is in' Many 👍 **Done**
Many 'Contains' One 🤌 **Needed**

**Comment by Grayda** [comment]
+1 for this, as I just discovered that if I create a Dynamic Filter component in Design, it won't let me filter by my relationship field. I was hoping to use a one-to-many relationship as a tags field, then filter the table to show all rows that have Tag 1 AND Tag 2 (or Tag 1 OR Tag 2, or whatever) 

Some additional thoughts on this: When I was building apps with Laravel Nova, I was using a third party tags package. It had a few different modes, including:

 * No new tags could be added. If the tag was not in the list, you couldn't add it. You could either click into the field to pick a tag, or start to type one, and just press comma to confirm
 * New tags could be added by just typing them in, but they wouldn't get saved anywhere, so if you wanted to use that tag again, you'd need to retype it every time.
 * New tags could be added by just typing them in, and the results would get saved to a table you had set up so you could use them again later.

And the list of tags was either grabbed from a table, or hard-coded as an array 

So what'd be most useful for me, is being able to have a pre-defined list of tags from somewhere, whether that's a table, or a textbox, one tag per line, plus the ability to filter a table by one or more tags
