### ISSUE TITLE
Views - cancel calculation

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#560]
When creating a view, using a filter, and then a calculation, I am unable to cancel/remove the calculation.

**Comment by shogunpurple** [comment]
You have to set the field and the calculation to empty in the select elements. We probably need a nicer way to do this.

**Comment by joebudi** [comment]
Ahh, cheers. Yes, we need a nicer way to do it 👍

**Comment by shogunpurple** [comment]
@joebudi how does a simple "clear" button sound for now at the bottom of this popover? This would be in the same place that the "Add Filter" button is on the filter popover

**Comment by joebudi** [comment]
Sounds good dude @shogunpurple
