### ISSUE TITLE
Save button in binding drawer doesn't update when HBS expression is fixed

### ISSUE THREAD

**Issue by PClmnt** [Budibase/budibase#5605]
Another minor UI bug in Bindings:

- Open the Bindings drawer
- Enter an invalid Handlebars expression
- Click Save -> Error message shows and Save button is disabled
- Fix the Handlebars expression
- The Save button is still disabled

You can get the Save button to re-enable by clicking on the search bar on the left, or toggling between JavaScript tab back to Handlebars.
It would be nicer if typing the fix into the textbox immediately made the button enabled.

**Comment by aptkingston** [comment]
It's just blurring the field isn't it? So clicking anywhere outside the editor should trigger the validation again.

**Comment by melohagan** [comment]
This has been replaced with a new bug: https://github.com/Budibase/budibase/issues/8329
