### ISSUE TITLE
Texts with "A-1-1" structure is automatically converted into date type in MySQL data source

### ISSUE THREAD

**Issue by apsonandtesla** [Budibase/budibase#5612]
**Describe the bug**
Texts with "A-1-1" (alphabetic-number-number) structure is automatically converted into date time type when writing to a text field in MySQL data source.

**To Reproduce**
1. Create a data table in MySQL with a text column (varchar).
2. Use the MySQL data table created in _**Step 1**_ to Budibase as a data source.
3. Add a row in Budibase Data View with the text field set to "A-1-1".
4. You can see that the "A-1-1" has been converted to "2001-01-01 00:00:00.000" in Budibase record (as well as the record in MySQL database).

**Expected behavior**
The text "A-1-1" entered in text field should never be converted into date time type, it should remains "A-1-1" instead.

**Screenshots**

![Enter "A-1-1" to the text field](https://user-images.githubusercontent.com/42469315/165517645-db28762d-afca-4fdd-81ae-2e65de2176de.png)

![The "A-1-1" is converted to a date time type](https://user-images.githubusercontent.com/42469315/165517617-50d5c304-ba67-45e6-97de-b14c0b261d07.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 99.0.1

**Additional Information**
If you are using a Budibase DB data source, the behaviors are correct.

**Comment by melohagan** [comment]
@mike12345567 I think this is related as well: https://github.com/Budibase/budibase/discussions/5639

**Comment by mike12345567** [comment]
Hi @melohagan - thanks yes I solved for that as part of the issue thanks for referencing it!
