### ISSUE TITLE
Can't figure out how to do a delete request using the mongoDB connector

### ISSUE THREAD

**Issue by Laestry** [Budibase/budibase#5613]
I'm using your hosted version, I've succesfully connected to mongoDB and can display everything that I need. The problem is that I can't delete something

These are the querries I've tried
{ "_id" : "{{id}}" } this one seems to work but return a delte count of 0, and the Id I'm using is 100% in the default input the same.
{ "_id" : ObjectId("{{id}}") } this one returns a mistake

**Screenshots**
![image](https://user-images.githubusercontent.com/49237501/165537000-89aeac1e-85d6-42d0-93cb-82baa7e76f41.png)
![image](https://user-images.githubusercontent.com/49237501/165537026-2af44786-7a66-44af-81bd-21a34d3e25bd.png)
![image](https://user-images.githubusercontent.com/49237501/165537107-9eb2d96a-b061-4f31-b4da-ad42efc86131.png)
![image](https://user-images.githubusercontent.com/49237501/165537148-4479dd6f-e8a4-48ee-8a56-f765e6a314d4.png)

**Comment by melohagan** [comment]
This is now fixed and merged into master, alongside some other query fixes.

If you want to use ObjectId it takes the form: `"_id": "ObjectId('{{id}}')"`

**Comment by Laestry** [comment]
Thanks! We're currently using appsmith but willing to give budibase a try again!
