### ISSUE TITLE
Container Background Color - Cannot tell which option is transparent

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5628]
**Describe the bug**
It is impossible to differentiate between white and transparent in the color picker. In addition, when you select transparent coloring. 
I also sometimes get an error (but still changes the color).

**To Reproduce**
1. Add a container, and set the background color
2. See that it is hard to see which option is transparent
3. Click on the transparent option. Sometimes an error message is shown

**Expected behavior**
It should be clear to the user which option is transparent.
Also, when you select a gradient, the color circle is still shown. More of a UX thing, but maybe make this look disabled?

**Screenshots**
![Screenshot 2022-04-28 at 09 44 54](https://user-images.githubusercontent.com/101575380/165714075-dac8a61f-3cea-48e8-98c8-1795a613f2cc.png)
*Looks white, but is transparent in this case*

![Screenshot 2022-04-28 at 09 45 31](https://user-images.githubusercontent.com/101575380/165714185-0fea238f-7ed6-46e7-9dd9-3167b80f1041.png)
*Error on selecting transparent. Sometimes.*

**Comment by aptkingston** [comment]
None of those options are transparent actually. Transparent is when you don't have a background colour selected - which is the crosshatch thing 
![image](https://user-images.githubusercontent.com/9075550/165741986-00786e69-a75f-4833-8cb5-3d08b2756cb9.png)
To go back to transparent you just hit the X to clear the field. If you pick the colour that matches the page background then it looks transparent, but it's just the same colour.

**Comment by aptkingston** [comment]
When you get that error is it just a 409 document update conflict?

**Comment by melohagan** [comment]
Ah okay that makes sense. 
I wouldn't have thought to do that because the *Hex, RGB, HSL* text field doesn't populate with a value. To me it looks like the X is just for that field, but I'll add that into the docs and close this issue.

The error may simply have been a self hosting blip. Been getting a few on/off today for various things.

**Comment by aptkingston** [comment]
Yea that's a fair point - it's not obvious that the X applies to everything.
