### ISSUE TITLE
[BUDI-7783] Defining existing relationship between keys of the same table not possible. Allow a table to join to itself.

### ISSUE THREAD

**Issue by pkoetter** [Budibase/budibase#5635]
**Hosting**

* Self
  * Budibase Version: 1.0.35
  * Datasource PSQL

**Describe the bug**
Define a relationship between two keys of the same table an error is displayed: "From/to/through tables must be different".

**To Reproduce**

1. Go to a PSQL table in Budibase
2. Click on 'Define existing relationship'
3. Choose Relationship Type 'One'
4. In 'Select to Table" choose the same PSQL table
5. See error

**Expected behavior**
A relationship between two keys of the same table should be possible as PSQL supports it and it is used to portray tree like data structures. (eg. the company Meta is parent of the company WhatsApp and the company Facebook)

**Desktop (please complete the following information):**

* OS: macOS 12.3.1
* Browser: Safari
* Version: 15.4

**Screenshot**

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/908da5b4-14af-4e11-bc78-0fa4ac53a798/736933ea-5d70-4235-9273-02ebcda344d6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC85MDhkYTViNC0xNGFmLTRlMTEtYmM3OC0wZmE0YWM1M2E3OTgvNzM2OTMzZWEtNWQ3MC00MjM1LTkyNzMtMDJlYmNkYTM0NGQ2IiwiaWF0IjoxNzAxMjg0NjU2LCJleHAiOjE3MDEzNzEwNTZ9.0ir2V-UOJxHzDE21w56GpMI9JLTIXnVrZWaMWhSSWE0)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7783](https://linear.app/budibase/issue/BUDI-7783/defining-existing-relationship-between-keys-of-the-same-table-not)</sub>

**Comment by aptkingston** [comment]
Changing from a bug to a feature request as the limitation is clearly displayed when you try to do this.

**Comment by derekmoeller** [comment]
Adding to this issue - self-referencing tables are a necessary part of a lot of hierarchical information, such as:

- Org charts - who reports to whom
- Task dependencies - can't do project management without it
- Most scheduling systems - where planning capacity is a function of sequential actions which need to refer to predecessors. This could be anything from staff resource planning, truck routes, or production schedules.

**Comment by karol-depka** [comment]
> * Task dependencies - can't do project management without it

Good examples!

Adding to this (my use case): categories with sub(sub)categories.

**Comment by karol-depka** [comment]
Any plans to support this?
Is there a technical/performance/etc. limitation which prevents this? 
Or just a change in UI/UX?

**Comment by zigenis** [comment]
Dropping in to say that I'd also really like this feature to be available. I'm using it to relate one task to a preceding one. Currently using a custom SQL query to fill in the gap, but I have a feeling it's not very performant.

**Comment by karol-depka** [comment]
Closed as not planned? 
A bit more comment maybe?

**Comment by pmankow** [comment]
This is the Achilles heel of this otherwise great tool.
