### ISSUE TITLE
Enable support for external MinIO with K8S 

### ISSUE THREAD

**Issue by hit2hat** [Budibase/budibase#5636]
**Hosting**
- Self
  - Method: k8s
  - Budibase Version: 1.0.110

**Describe the bug**
Proxy container can't return files from non build-in s3 (default minio settings from official helm chart). Proxy can't connect to not existing address and fall with 502 error. For example I'll use loading of Logotype.

**To Reproduce**
1. Set settings in `values.yaml` for custom s3 (1 screenshot) and deploy chart
2. Go to 'Settings' -> 'Organization'
3. Select file in 'Logo' form
4. Scroll down to button 'Save' and press it
5. See that logo in left corner is damaged file (2 screenshot)
6. See in logs, that proxy try to connect to default minio url (3 screenshot)

**Expected behavior**
Logo in left corner is image

**Screenshots**
<img width="365" alt="image" src="https://user-images.githubusercontent.com/42957391/165773169-a0274cf9-4db3-4aa3-b54a-ee063d915d34.png">
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/42957391/165772575-3e6e45f6-378e-42a4-95da-02da48e171ce.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/42957391/165772725-4494a57a-87ae-4965-a9ae-e27f6c7154ed.png">

**My opinion**
I think that root of trouble was in this https://github.com/Budibase/budibase/blob/e79a90fbe175ed2088531626b8a0a1b7dd8d672e/scripts/proxy/generateProxyConfig.js#L43

p.s. sorry for my bad english

**Comment by Rory-Powell** [comment]
hi @hit2hat, thanks for raising this. This is something we will need to look at, there is some defaulting occurring when resolving the object store url where we are incorrect using the path regardless of the configured minio url e.g. 
https://github.com/Budibase/budibase/blob/develop/packages/worker/src/api/controllers/global/configs.js#L220

**Comment by ctellechea2001** [comment]
@Rory-Powell. We have the same issue. 

![image](https://user-images.githubusercontent.com/45426180/171180879-0268f83b-8ca0-4951-ad82-4b92d9ef9652.png)

2022/05/31 12:59:57 [error] 32#32: *98 **minio-service.budibase.svc.cluster.local could not be resolved (3: Host not found),** client: 192.168.244.195, server: _, request: "GET /prod-budi-app-assets/app_46875b4dc81546e78dd1eb08a984deba/budibase-client.js?v=1.0.187 HTTP/1.1"

 Could you describe how can we resolve that? What is the value that is necessary for EXTERNAL_OBJECT_STORE use S3?

![image](https://user-images.githubusercontent.com/45426180/171181259-fb2a4375-dd40-421e-915d-18d6011f9164.png)
