### ISSUE TITLE
Automate,  Drawer not overlaying properly

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#5649]
Env: PreProduction

Steps to reproduce: 

1. Create an app, using Budibase BD
2. Add 1 column, and 1 row
3. Click automate and select Row created, add test data

Short video : https://www.loom.com/share/2dc61a1c562f4372b398f5d4a16525c1

expected result: The drawer should pop up and overlay properly.
actual result: The drawer not overlaying properly

**Comment by shogunpurple** [comment]
Looks like https://github.com/Budibase/budibase/pull/5652 addresses this one, closing
