### ISSUE TITLE
Embed budibase into existing web app 

### ISSUE THREAD

**Issue by eliliam** [Budibase/budibase#5659]
**Describe the feature request**
Having a way to embed budibase into an existing internal web app, such as a React site, and share authentication state would be amazing. I am looking for a way to embed a budibase app that just contains tables and a few charts into an existing React web app. This web app has authentication already, so having some way to pass that authentication information to budibase is a must, since having the user log in twice(once in our app, and then once again in the embedded budibase app) is not an option.  

**Screenshots**
Budibase inside internal portal tool:
![budibase_in_react](https://user-images.githubusercontent.com/14301439/165985596-4b2c00fe-91f8-4f7e-82ea-867fd06bdbbc.jpeg)

**Comment by wooparadog** [comment]
also trying to find a solution. 

I've tried putting them under the same top domain, still cant get it to work

**Comment by switchupcb** [comment]
Not stale: https://github.com/Budibase/budibase/discussions/9792
