### ISSUE TITLE
Container Element - option for background Image and Overlay

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5667]
**Describe the feature request**
..or allow Background Image to hold children elements. :) 

**Screenshots**

**Comment by n0rthwood** [comment]
you can add container custom css like this 
`background-image: url("paper.gif");`
or 
`background-image: url(data:image/jpeg;base64,/9j/4ROIRXh.....);`
to add background image

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/7972
