### ISSUE TITLE
Form Steps freeze Builder in V.1.0.132

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5669]
**Hosting**

- Self
  - Method: Self, Docker, Mac Silicon
  - Budibase Version: 1.0.132

**Describe the bug**
Add a new blank screen
Add a form
Add a form Step.
Builder Preview window no longer responds and the Preview doesn't t get rendered.
Navigating to another screen also stops working.
( Also opening an existing screen with a form and multiple steps causes the same freeze on the preview panel)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSX Monterey
 - Browser Safari
 - Version Latest

**Additional context**

**Comment by Rory-Powell** [comment]
Hi @poirazis, thanks for raising this. `1.0.132` is not yet a publicly supported version, the current `latest` tag is `1.0.110`. Can you try with this version?

**Comment by poirazis** [comment]
With 110 works fine. 

Just wanted to give you guys a heads up with 132 and 133 ( problem persists ) during your testing

**Comment by Rory-Powell** [comment]
very much appreciated @poirazis, thanks for the heads up here!

**Comment by poirazis** [comment]
happy to help @Rory-Powell . Also have a look at application Export in .133. It seems to be broken.

**Comment by poirazis** [comment]
Hwy @Rory-Powell , @mike12345567 i think i spotted another one, again in .133

if you try to set a filter on a table column that contains a space you get an error (both in design and runtime).

<img width="1101" alt="Screenshot 2022-05-03 at 6 14 30 PM" src="https://user-images.githubusercontent.com/80512170/166482560-7532b9c9-a317-4705-95ad-c3248b638c07.png">

**Comment by mike12345567** [comment]
Hi @poirazis - thanks for the report, I'm unable to replicate this, could you give me a bit more instruction/a walk-through of what you did to create the error scenario?

I've done as follows:
![image](https://user-images.githubusercontent.com/4407001/166484961-7f10e24e-8e15-4b9e-8103-6cac19d9c6ba.png)

Table has column `space name`, I've created a form, created a text field and then created a filter in the data provider for the `space name` column equalling that of the text field value from the form.

**Comment by poirazis** [comment]
Hey @mike12345567 
it seems to happen only when the condition is "Like" not "Equals".
Delete your Filter and recreate the filter with the condition "Like"

Another thing while trying to recreate this, is that updating the type of the filter from Equals to Like doesn't take effect.
You have to remove the filter, save, and recreate.

**Comment by mike12345567** [comment]
Hi @poirazis - I've tried to re-create both issues, for me I can't find any issue with changing a filter, changing the condition without deleting/saving the filter drawer seems to work fine for me and the like condition appears to work as expected as well.

![image](https://user-images.githubusercontent.com/4407001/166671965-e2ffd6d0-f730-4af3-b292-dbc16f9ebcf9.png)

**Comment by mike12345567** [comment]
Hi @poirazis - thanks for that, I was able to replicate based off of that, I'll get a fix added as well.

**Comment by poirazis** [comment]
way to go @mike12345567 !

Since we are in a bug hunting spree here, let me give you another one :)

The duplicate Element button on the element's toolbar no longer works in v.141

<img width="540" alt="Screenshot 2022-05-04 at 6 40 14 PM" src="https://user-images.githubusercontent.com/80512170/166718847-686eff99-32e8-418d-9d7c-8b0019bf7094.png">
