### ISSUE TITLE
Text Field refresh automatically Data Provider/Table after any click outside text box

### ISSUE THREAD

**Issue by nyxdata** [Budibase/budibase#5674]
I've created a simple app that retrieve email from first name/last name/company name.

To do so, I've created a form containing 3 text fields and a data provider containing a button and a table:

- Form 1
     - Text field 1: First Name
     - Text field 2: Last Name
     - Text field 3: Company Name
     - Data Provider 1: Linked to rest API that send the 3 text fields to an AWS endpoint
         - Validation button 1: action: refresh data provider
         - Table 1: containing the response of my API
         
Each time I change anything in the text boxes and click outside the box (another field, or anywhere), Budibase refreshes Table 1 (and call my API inducing performance and cost issues)

Thank you

**Comment by melohagan** [comment]
This is open as a discussion: https://github.com/Budibase/budibase/discussions/5675
Closing.
