### ISSUE TITLE
Chart Components 

### ISSUE THREAD

**Issue by Conor-Mack** [Budibase/budibase#569]
At the time of writing, the charts that I would consider completed are the Bar, Donut, Grouped Bar and Line Charts (line chart x labels don't seem to work, I am currently reviewing this).

All other charts (located within `packages\standard-components\src\Chart`) have only been partially completed and will need some work. 

At the minute separate components exist for these that include the props and prop bindings for the charts. All charts have also been registered in `components.json`.

**Comment by joebudi** [comment]
Bugs I have experienced whilst using the charts:

Line chart:
- Line Curve prop does not seem to work
- Height and width - only 1 valued is accepted
- X Axis Format - does not work (must select custom)
- X Axis Custom Format - does not work
- X Ticks and Y ticks should be a select component with the following options: empty option, 2, 4, 6, 8, 10

Groupedbar chart:
- It might be better to swap the name label with the group label - this makes more sense to me.
- Y ticks should be a select component with the following options: empty option, 2, 4, 6, 8, 10

Donut chart:
- Internal and external radius do not work without a [width and height prop](https://britecharts.github.io/britecharts/tutorial-donut.html ) - 
- Legend width should be a select option with values 200, 400, 600, 800

Bar chart:
- X-Axis label requires additional margin
- Missing britecharts color palette

For all charts:
When you select a dropdown, the checkboxes continue to show - possible z-index issue.
Width/height options should be options within a select component - 400, 600, 800, 1200, 1600
Change the name of the Britecharts color palette to something else - Rainbow or something
