### ISSUE TITLE
Table doesn't respect values modiffied by handlebars for date type

### ISSUE THREAD

**Issue by Upgreydd** [Budibase/budibase#5700]
**Hosting**
- Self
  - Method: docker-compose
  - Budibase Version: 1.0.138 - tested in few versions
  - App Version: 1.0.138

**Describe the bug**
If you use datetime field in data and you configure columns in table, the column is marked as `datetime` and it always requires a value in datetime format to parse it always to the same format. You can't transform the content of a column to a custom format - for example to date.
If I use `{{ date value 'dddd' }}` I'll get an invalid date cause the column require a date format.
If I use `{{ date value 'YYYY-MM-DD' }}` which should show up as `1986-11-24` I'll receive `November 24 1986, 00:00`.
![image](https://user-images.githubusercontent.com/579481/166677212-9f90fee2-98b7-4c01-a441-e31bc5f528f9.png)

**Comment by aptkingston** [comment]
Hey @Upgreydd. Yep I know why this is - the table cell itself is doing additional parsing and treating the value as the default date format. We need to disable any additional table cell formatting whenever a custom value is in use.

**Comment by Upgreydd** [comment]
Hey @aptkingston. Thanks, I've found where it's in code but can't find a way how to detect if value is `modiffied` by handlebars to add one more if in statement:
```
  $: isTimeOnly = !isNaN(time) || schema?.timeOnly
  $: isDateOnly = schema?.dateOnly
  $: format = isTimeOnly
    ? "HH:mm:ss"
    : isDateOnly
    ? "MMMM D YYYY"
    : "MMMM D YYYY, HH:mm"
```
I guess it should be like this
```
  $: isTimeOnly = !isNaN(time) || schema?.timeOnly
  $: isDateOnly = schema?.dateOnly
  $: isCustomFormat = ............
  $: format = isTimeOnly
    ? "HH:mm:ss"
    : isDateOnly
    ? "MMMM D YYYY"
    : isCustomFormat
    ? value
    : "MMMM D YYYY, HH:mm"
```

**Comment by Upgreydd** [comment]
@aptkingston same apply for boolean. Can't do:
`{{#eq value 'true' }}Male{{ else }}Female{{ /eq }}` - it always render as checkbox

**Comment by aptkingston** [comment]
Yep there will be a few types that do this. A temporary solution would be making a new formula column in your table, since that is just text.

**Comment by Upgreydd** [comment]
@aptkingston I'd love to but it's impossible with postgres :/

**Comment by melohagan** [comment]
This appears to be fixed! Closing.

![Screenshot 2022-10-27 at 10 29 42](https://user-images.githubusercontent.com/101575380/198247931-58ea45ec-f7d8-4a4c-940b-69874ae49a91.png)

![Screenshot 2022-10-27 at 10 29 58](https://user-images.githubusercontent.com/101575380/198247972-87991cf1-3b9a-4f2b-b88c-787f4c729b3d.png)

![Screenshot 2022-10-27 at 10 30 09](https://user-images.githubusercontent.com/101575380/198248019-c9f11cb4-f3e0-46f4-8079-34435e84975c.png)
