### ISSUE TITLE
Formula column is inaccurate when picking day from date column

### ISSUE THREAD

**Issue by Pieter0313** [Budibase/budibase#5704]
I added a column which shows the day number based off of the date column using a formula, but it's one day off:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/52565351/166704286-e8412851-538a-4fc7-9dc2-351caac51c74.png">

This is what the formula looks like:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/52565351/166704566-61ab66f7-f716-41d1-b7ab-2c452e42824f.png">

It looks like it shows the day accurately when the date reaches 2AM, everything between 12 AM and 2AM shows the previous day number.

**Comment by Upgreydd** [comment]
@Pieter0313 isn't that related to your application timezone? try to convert timezone with handlebar: `{{ date Betaaldatum "D" "Europe/Berlin" }}` for example - for me it looks like a timezone issue.

**Comment by Pieter0313** [comment]
Oh right that was the issue, oops
