### ISSUE TITLE
JavaScript Binding - Bindable value does not inject at cursor position

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5710]
**Hosting**
- Self
  - Method:  docker compose
  - Budibase Version: v1.0.108
  - App Version: v1.0.108

**Describe the bug**
I want to insert a binding at the cursor position (see gif).

**To Reproduce**
1. Type a for loop
2. Inject array as binding
3. Value gets inserted at the end of the JavaScript block

**Expected behavior**
As a user, I should be able to inject bindings at the position of the cursor when using JavaScript.

**Screenshots**
![javascript_cursor](https://user-images.githubusercontent.com/101575380/166724858-0abbb4fd-702d-4089-b9b9-c80825e1c0c9.gif)

**Comment by aptkingston** [comment]
Yea I remember the cursor thing being a pain. I think I abandoned it because the shortcut method (press ctrl+space) does insert it in the correct cursor position - and once you discover the shortcut you never go back! But would still be worth fixing this at some point.

**Comment by melohagan** [comment]
That is really nice! I've added a green info card to the docs: https://docs.budibase.com/docs/javascript#using-javascript-code-in-bindings

I think then a nice compromise would be to make that list searchable on type, similar to how VSCode and other IDEs do it for folders:
<img width="327" alt="Screenshot 2022-05-04 at 22 42 35" src="https://user-images.githubusercontent.com/101575380/166830580-0119c48e-42eb-4552-a8ef-ea5dc9d889ec.png">

There's no search bar, you just start typing and it'll automatically start filtering down the list, because you can have quite a number of bindings.

**Comment by melohagan** [comment]
This will be improved with the new bindings work. Closing.
