### ISSUE TITLE
v1.0.141 - multi step form doesn't render steps other than STEP1 in `Design` preview

### ISSUE THREAD

**Issue by Upgreydd** [Budibase/budibase#5713]
**Describe the bug**
BEFORE: When going to elements in STEP X in multi-step form - a preview for editing purposes shows up
NOW: No matter which step you're editing it still shows STEP 1

**To Reproduce**
1. Go to Design
2. Create a multi-step form
3. Voila

**Expected behavior**
Step X shows the form for the selected step

**Comment by kellis5137** [comment]
Do we have an ETA on when this fix will be released?
