### ISSUE TITLE
Repeater misbehaves inside Data Provider not yet assigned to a data source in v.1.0.141

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5716]
Self hosting tag v  1.0.141 / MacOSX Monterey 

How to recreate

New Blank Screen
New Data Provider - Do not assign a data source
New Repeater 
New Header Element inside Repeater -> You will see that neither the header not any other elements inside the repeater appear.

It seems to also happen, when you DO assign a data source to the Data Provider, but that data source has no rows ( empty table )

**Comment by aptkingston** [comment]
Hey @poirazis. This is correct behaviour - when the repeater has nothing to repeat over it won't show anything, and instead show a message saying "no rows found". You can customise what fallback text you want displayed when you have no rows to show with the "empty text" setting.

**Comment by poirazis** [comment]
hey @aptkingston 
sorry to nudge again, but i think there is an issue.

in design mode, Data Provider not assigned or assigned source has 0 rows, the Builder App Preview goes like this.
The arrangement of the elements is like i described above.


<img width="392" alt="Screenshot 2022-05-05 at 12 36 35 PM" src="https://user-images.githubusercontent.com/80512170/166898346-cd1d4afb-4b72-4340-af17-33863687c40a.png">

<img width="1220" alt="Screenshot 2022-05-05 at 12 36 28 PM" src="https://user-images.githubusercontent.com/80512170/166898355-1e070030-3522-47e2-a7a0-6f75511d9b4a.png">

**Comment by aptkingston** [comment]
Have you added some custom styles to your repeater? The content is just stretched way outside the component for some reason.
It should look like this: 
![image](https://user-images.githubusercontent.com/9075550/166903278-2ed6ded2-6b89-498b-8833-8acbcee5015a.png)

I've never seen it look like yours before! Do you have custom CSS on the repeater or other components on that screen which could cause this?

**Comment by poirazis** [comment]
Nope, nothing custom, just a blank screen, empty / unconnected Data Provider / Repeater / Headline.


After some playing around i found the below ..

When i change alignment anything but stretched, it works
<img width="1154" alt="Screenshot 2022-05-05 at 2 02 06 PM" src="https://user-images.githubusercontent.com/80512170/166910590-fb9fcf64-cc4a-4f13-8949-252af570dafc.png">

When i set it back to streched, it messes up again.
<img width="771" alt="Screenshot 2022-05-05 at 2 00 19 PM" src="https://user-images.githubusercontent.com/80512170/166910719-a98cde56-afae-41c7-a9a8-362ff6cd5b28.png">

**Comment by aptkingston** [comment]
Very strange. I can't understand why that would happen. What browser (and version) are you using?

**Comment by poirazis** [comment]
I am on latest Safari in Monterey.
