### ISSUE TITLE
Data picker issue

### ISSUE THREAD

**Issue by EduardoZeroum** [Budibase/budibase#5727]
The date picker after the condition "Update Setting , Disabled , IF: {{State.Edit}} Equals Binding "Yes", dont let me use the date picker but if i open the full screen the date picker is able to use , and i saw in the browser console and the placeholder disable doesnt disappear, this error only occurs in date picker , in text fields, etc... don't.

**To Reproduce**
1. Use the template Client Contact List'
2. Put a datapicker in /clients/:id and disable it
3. Copy the condition of other components
4. Click on edit button
5. Try to use the data picker again
6. See error

**Expected behavior**
I expect to use the data picker because it is no more disabled...

 - OS: Linux UBNT
 - Browser: Microsoft Edge/Google Chrome
 - Version 1.0.110

**Comment by Rory-Powell** [comment]
Hi @EduardoZeroum. I haven't been able to reproduce. The only scenario this occurred for me was when I set the `Field` setting of the New Date Picker to be one of the auto generated columns (created at, updated at). 

Can you check that you are doing the following:
- Add a new Date/Time column to `Clients` table e.g. `New Date` 
- Add a new Date Picker component nested under the existing Field Group
- Select `New Date` as the field to assign the component

e.g.
<img width="1436" alt="Screenshot 2022-05-05 at 12 26 32" src="https://user-images.githubusercontent.com/8755148/166913941-3408fead-639a-4499-8441-967d011bed29.png">

**Comment by EduardoZeroum** [comment]
Hello, @Rory-Powell thank you for the reply but it didn't solve my issue , uploaded a video on streamable of the error in order to be easier to understand.

https://streamable.com/9kgvsv

Thank you in advance,
Eduardo Silveira.

**Comment by shogunpurple** [comment]
Fixed in https://github.com/Budibase/budibase/pull/5797
