### ISSUE TITLE
Cannot create new account

### ISSUE THREAD

**Issue by ChristopherPeterFrank** [Budibase/budibase#5732]
Hello,

Trying to create a new account to test the out the platform.  When I click on the verification email I get a "error creating tenant" message.  Please assist
![Capture](https://user-images.githubusercontent.com/12631947/166998823-d1d6372b-b369-411c-b982-e11a0b7da88c.JPG)
.

**Comment by Rory-Powell** [comment]
Hi @ChristopherPeterFrank, to diagnose, what domain name did you choose when signing up? Thanks

**Comment by ChristopherPeterFrank** [comment]
Thanks for the prompt reply.  I tried "retailapp" and my colleague Dayle tried "denningers" and "denninger" using his email account and received the same error message.

**Comment by Rory-Powell** [comment]
Thanks for highlighting this @ChristopherPeterFrank. Working on a fix for this.

**Comment by Rory-Powell** [comment]
@ChristopherPeterFrank you should be able to resend the activation email and try again

**Comment by ChristopherPeterFrank** [comment]
Hi Rory,

I'm confirming that it now works.  Thank you for the prompt support.




Christopher
