### ISSUE TITLE
Tooltips !

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5743]
**Describe the feature request**
The ability to define popup Tooltips for the various Elements, especially the  Icon Element.

**Screenshots**

**Comment by melohagan** [comment]
Also include an option to add tooltips for form fields: https://github.com/Budibase/budibase/discussions/7852

**Comment by marian001** [comment]
+1

**Comment by melohagan** [comment]
Hey @marian001

@andz-bb Has added a really nice Tooltip plugin: https://github.com/andz-bb/budibase-component-tooltip

Plugins docs: https://docs.budibase.com/docs/custom-plugin
