### ISSUE TITLE
[Builder] - Select Enclosing / Parent Element 

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5746]
When designing complicated screens with large hierarchies of elements, especially nested Containers, it would be really useful to have the capability with a keyboard shortcut and / or the elements toolbar to select its enclosing element. Select Parent, which if you feel pressing will go all the way up to the screen.

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/12358
