### ISSUE TITLE
Possible bug with relationships

### ISSUE THREAD

**Issue by weixingp** [Budibase/budibase#5753]
**Hosting**

- Self
  - Method: Docker compose 
  - Budibase Version: 1.0.99 
  - App Version: 1.0.99 
  - DB: MariaDB 8.0
 
**Describe the bug**
After adding 2 or more relationships to a table, it no longer displays all the data rows. Using the table as data provider does not work as well, i.e only returning 1 row from the table.

**To Reproduce**
1. Using MariaDB / MySQL (not tested with other DB)
2. Create a table, and add around 10 rows of data.
3. Create two other tables, making foreign key reference to the table created in step 2
4. Import the tables in Budibase, adding one-one relationships
5. Only 1 row is displayed.

**Expected behavior**
All the rows returned as usual.

**Screenshots**
Screenshot: after adding several one-to-one relationships on a table. More than 1 location in this table originally.
![image](https://user-images.githubusercontent.com/72912936/167168182-a2357b3f-cf46-4a1a-85fe-b7a9e805bd5e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 100

**Comment by jgeis** [comment]
I'm having the same issue, but for me no data shows, it says "Now let's add a row" implying there is no data there.  If I remove the foreign key relationship in Budibase, all the rows display again.  

MariaDB 10.5.15
Budibase 1.0.166, but it happened in 1.0.158 as well
Chrome, 101.0.4951.54 (Official Build) (x86_64)

**Comment by melohagan** [comment]
Hi @weixingp 

This may be the correct behaviour. 
It would help to see the tables involved, the keys involved, and screenshots of the 'Define Relationship' modal.

I think the confusion here is that **Relation type** of *One* means *One->Many*
Where the first table is the one, and the second table is the many.

So if you are selecting the table with 10 rows as the foreign table, then only one row would be displayed in one of the two 'other' tables.
