### ISSUE TITLE
Query timeout with ArangoDB

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5782]
### Discussed in https://github.com/Budibase/budibase/discussions/5756

<div type='discussions-op-text'>

<sup>Originally posted by **jackgray** May  6, 2022</sup>
Hi everyone. I guess I didn't do deep enough investigation before designing my solution architecture, because I based it on the fact that Budibase claims to support ArangoDB, but now that I am at the actual integration stage, I can't seem to find a single instance of anyone on the web using them together, much less any documentation for it...

I have both services successfully running independently on docker, and can access their endpoints and connect the Arango one as a Budibase backend without any error. However I am not sure how to create a query or access the data through Budibase in any way. 

I try using the straightforward AQL query of " FOR item in <collection_name> RETURN item" and receive a timeout error. When working against the native Arango web interface or python API, the query takes only a second, so it seems unlikely that it simply needs more time. I trust the budibase developers to include a reasonable timeout setting in the default compose settings. I will try increasing, but am banking on that being a dead end. 

What is the support status of the ArangoDB integration, and does anyone know of it being used successfully?

Thanks!</div>

**Comment by tolgaulas** [comment]
This may be related to #8029

**Comment by melohagan** [comment]
Thanks for the reproduction steps @tolgaulas ! Closing this issue in favour of yours
