### ISSUE TITLE
App name does not change in the nav bar.

### ISSUE THREAD

**Issue by tbox98** [Budibase/budibase#5789]
Hi. I changed the name of the application, but the title bar is still displaying the original one. I suppose that is a bug to fix.

**Comment by aptkingston** [comment]
Hey @tbox98. This isn't a bug - we just use your app name when you create your app as the initial page title, but you can change this yourself in your layout settings. We don't reset your page titles when you change your app name.

You can change your title for each layout using the following setting:
![image](https://user-images.githubusercontent.com/9075550/167584584-00af17e0-4ae0-4d96-bd64-266c8d501564.png)
