### ISSUE TITLE
Mixed data in enrich request

### ISSUE THREAD

**Issue by Yaroslav-QA** [Budibase/budibase#5790]
**Hosting**

- Cloud
  - Tenant ID: crs.budibase.app

**Describe the bug**

On the client side, I get a Documents table with empty rows:
![image](https://user-images.githubusercontent.com/57775897/167482280-ed408b8a-91fb-487b-8929-b78c4d7a2e5d.png)

When trying to get data about documents of a specific project, mixed data is received. The Documents array contains mixed data from the Users table and data from the Documents table:
![image](https://user-images.githubusercontent.com/57775897/167479738-2dddaa2b-1490-439a-8c7a-72e02cb8b944.png)

The Users array returns data from the Documents table:
![image](https://user-images.githubusercontent.com/57775897/167480513-7149d63e-b3d5-4470-8f29-34b12e80a7b7.png)

**To Reproduce**
DB type is Budibase DB.

The database has related tables Projects and Documents. 
![image](https://user-images.githubusercontent.com/57775897/167477328-6d8aabf7-72fa-416e-a87b-5578694537ab.png)

The client side uses the following structure:
![image](https://user-images.githubusercontent.com/57775897/167482010-b0925e39-0393-4080-8369-4df561922064.png)

**Expected behavior**
The data should not be mixed. Users data should be in the Users array, and projects data should come in the Projects array.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Chrome 
 - Version 101.0.4951.54 (Official Build) (x86_64)

**Comment by melohagan** [comment]
Hi @Yaroslav-QA 

I tried to recreate this, but failed. The bug may have since been fixed.

If you are still experiencing this bug on the latest version of budibase, would it be possible for you to email your app export to support@budibase.com ?
