### ISSUE TITLE
Can't read existing PostgreSQL schema

### ISSUE THREAD

**Issue by andy47** [Budibase/budibase#5792]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.149

**Describe the bug**
I'm trying to add an existing PostgreSQL database to my first app in Budibase. 
I'm running from the docker compose template in the documentation, registered my user and created my first application.
When I add the data source - that I can access through other tools so I know the database is fine - I get an error message when pressing the 'Save and fetch tables' button;

![Screen Shot 2022-05-10 at 2 57 03 pm](https://user-images.githubusercontent.com/782758/167557273-035de08c-9b03-481e-bead-cf0a363b27bb.png)

If I save the connection without fetching tables it will save in my app. But if I then open the data source and press the 'Fetch tables' button I get an error message;

![Screen Shot 2022-05-10 at 3 50 45 pm](https://user-images.githubusercontent.com/782758/167557499-35f8b8ae-4e00-4832-9f15-ccf9e9a2aa80.png)

**To Reproduce**
1. Go to data source in my app
2. Click on 'Fetch tables'
3. See error

**Expected behavior**
Something to do with reading my existing table structures into the data source

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 12.3.1 on Apple Silicon
 - Browser Firefox
 - Version 100

**Additional context**
I've tried to connect to a PostgreSQL database running on the same machine and another one on a Linux server. Same errors for both databases.

**Comment by Upgreydd** [comment]
Can confirm bug

**Comment by shogunpurple** [comment]
This one is now resolved and released. Thanks for reporting!
