### ISSUE TITLE
120 seconds timeout when bb container has no internet access

### ISSUE THREAD

**Issue by rooso** [Budibase/budibase#5798]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.150

**Describe the bug**
When the budibase container does not have access to the internet, the start screen has an timeout about 120 seconds before a user is able to create an app: "Error loading apps and templates".

After the first app is created, the timeout is gone but the error persists.

Issue seems to be known, but not properly fixed:
https://github.com/Budibase/budibase/discussions/2997

**To Reproduce**
1. Deploy on budibase on Docker behind a corperate proxy
2. Login to budibase
3. See error "Error loading apps and templates"

**Expected behavior**
Option 1: Allow user to choose if templates should be loaded using an environment var
Option 2: Do not load templates if there is no internet access (timeout after a few seconds) at first login

**Screenshots**
Screen after login:
![image](https://user-images.githubusercontent.com/51026046/167620835-4f770b2e-22d0-47b2-907c-5b7b096a9145.png)

Screen 120 seconds after login:
![image](https://user-images.githubusercontent.com/51026046/167620853-26349521-655f-4953-887c-4839a05651c5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge Chromium

**Comment by shogunpurple** [comment]
Closing in favour of https://github.com/Budibase/budibase/issues/3164

**Comment by rooso** [comment]
Nope, just deployed it to an kubernetes cluster with internet access.

**Comment by xingyang-007** [comment]
when start docker budibase container, i have passed HTTP_PROXY into it, 
but this error still showed, anyone know why ? 
it should have detected proxy setting and got network access.

**Comment by xingyang-007** [comment]
have found answer from here: https://github.com/Budibase/budibase/discussions/8926, 
just set below env solved the problem.
GLOBAL_AGENT_NO_PROXY: "budibase,minio,nginx,postgres,localhost"
GLOBAL_AGENT_HTTP_PROXY: http://xxx
GLOBAL_AGENT_HTTPS_PROXY: http://xxx
