### ISSUE TITLE
Unable to save columns in Data tab

### ISSUE THREAD

**Issue by aidenmitchell** [Budibase/budibase#5805]
**Hosting**
- Cloud
  - Tenant ID: bspit

**Describe the bug**
I am unable to save any columns in the Data tab without an error, `Error saving column`.
This seems to prevent my JS formula column from calculating.

**To Reproduce**
Honestly not sure, I was just creating columns and it started happening.

**Expected behavior**
No error and JS calculates as expected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: 1.37.116 Chromium: 100.0.4896.127

**Additional context**
Console error:
`[Builder] HTTP 400 on POST:https://bspit.budibase.app/api/tables
	Invalid sort field: <<>>`

**Comment by shogunpurple** [comment]
Is this still happening @aidenmitchell?
