### ISSUE TITLE
"ExpressionAttributesValues must not be empty" Error when you try to sign up. 

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#5813]
ENV production

Video: https://www.loom.com/share/165f1066478f46608d35589d1cab07c4

 
ExpressionAttributesValues must not be empty Error when you try to sign up. 
My local storage holds my UserData and it looks like it's causing this error. 

**To Reproduce**
1. Go to https://budibase.com/eula/ 
2. Scroll all the way down and click get Started for free

Video: https://www.loom.com/share/165f1066478f46608d35589d1cab07c4

![Screenshot 2022-05-11 at 13.09.17.png](https://images.zenhubusercontent.com/623866329f3f8e7223d95e00/1c860acd-a617-4384-9e0a-64e6e3caeaaa)

**Comment by Rory-Powell** [comment]
Thanks for raising this @MihailHadzhiev2022, we've seen this a couple of times around previously failed registrations. We should address this once and for all by reworking the local storage mechanism. Created https://github.com/Budibase/budibase/issues/5814
