### ISSUE TITLE
text field on change action value reference issue

### ISSUE THREAD

**Issue by ggs331** [Budibase/budibase#5816]
Hello,

I am running on v1.0.150, the new version introduced a great feature `On Change` action for text field, option picker and more. 

Here I found an issue of the text field, when the text field `On Change` action reference to the text field itself something like `{{ Form1.Fields.Keyword }}`, the value being fetched is not the `Changed` value, but the value before the change. 

In my use case, I have a text field named `Keyword` for searching, and I've added `On Change` action `Navigate To` > `/services/list/q={{ Form1.Fields.Keyword }}`(I would like to store the search keyword on the URL), everytime the value on the URL is the previous value, but not the changed value. 

![image](https://user-images.githubusercontent.com/29649651/167829556-ad7be871-87cc-4101-9922-1d8e3ffdc6df.png)

**Comment by melohagan** [comment]
Hi @ggs331 

You need to use the Field Value binding: https://docs.budibase.com/docs/actions#on-change

**Comment by aptkingston** [comment]
Following on from Mel's answer - to give you an example, the "Navigate To" URL should be `/services/list/q={{ Field Value }}`. That binding contains the new field value, rather than the old field value.
