### ISSUE TITLE
Bug: Cannot use long auto generated passphrase from my password manager

### ISSUE THREAD

**Issue by samal-rasmussen** [Budibase/budibase#5822]
**Describe the bug**
When trying to make a Budibase user I got my password manager to generate a long random passphrase and copy pasted that as my Budibase password, but then I faced this error message:

> Password invalid. Minimum eight characters, at least one lower and uppercase letter, one number and one special character

This is a misguided rule that actually *lowers* the entropy of the password, because it *decreases* the set of possible characters in the password by mandating specific characters as opposed to allowing any characters.

See the [NIST guidelines](https://doi.org/10.6028%2FNIST.SP.800-63b):

> Despite widespread frustration with the use of passwords from both a usability and security standpoint, they remain a very widely used form of authentication [Persistence]. Humans, however, have only a limited ability to memorize complex, arbitrary secrets, so they often choose passwords that can be easily guessed. To address the resultant security concerns, online services have introduced rules in an effort to increase the complexity of these memorized secrets. The most notable form of these is composition rules, which require the user to choose passwords constructed using a mix of character types, such as at least one digit, uppercase letter, and symbol. However, analyses of breached password databases reveal that the benefit of such rules is not nearly as significant as initially thought [Policies], although the impact on usability and memorability is severe.
...
As noted above, composition rules are commonly used in an attempt to increase the difficulty of guessing user-chosen passwords. Research has shown, however, that users respond in very predictable ways to the requirements imposed by composition rules [Policies]. For example, a user that might have chosen “password” as their password would be relatively likely to choose “Password1” if required to include an uppercase letter and a number, or “Password1!” if a symbol is also required.
Users also express frustration when attempts to create complex passwords are rejected by online services. Many services reject passwords with spaces and various special characters. In some cases, the special characters that are not accepted might be an effort to avoid attacks like SQL injection that depend on those characters. But a properly hashed password would not be sent intact to a database in any case, so such precautions are unnecessary. Users should also be able to include space characters to allow the use of phrases. Spaces themselves, however, add little to the complexity of passwords and may introduce usability issues (e.g., the undetected use of two spaces rather than one), so it may be beneficial to remove repeated spaces in typed passwords prior to verification.
Users’ password choices are very predictable, so attackers are likely to guess passwords that have been successful in the past. These include dictionary words and passwords from previous breaches, such as the “Password1!” example above. For this reason, it is recommended that passwords chosen by users be compared against a “black list” of unacceptable passwords. This list should include passwords from previous breach corpuses, dictionary words, and specific words (such as the name of the service itself) that users are likely to choose. Since user choice of passwords will also be governed by a minimum length requirement, this dictionary need only include entries meeting that requirement.
Highly complex memorized secrets introduce a new potential vulnerability: they are less likely to be memorable, and it is more likely that they will be written down or stored electronically in an unsafe manner. While these practices are not necessarily vulnerable, statistically some methods of recording such secrets will be. This is an additional motivation not to require excessively long or complex memorized secrets.
...
Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets.

So to sum up password rules other than length are considered outdated and backwards. They decrease security and usability.

**To Reproduce**
1. Try to create a new budibase user
2. Enter a password over 8 chars length

**Expected behavior**
It should accept the password

**Comment by aptkingston** [comment]
I didn't actually know we did this. I completely agree with you and am fully in support of removing any restrictions other than length!

**Comment by samal-rasmussen** [comment]
The one other password rule other than length that makes sense is a blacklist of the passwords from known password leak databases: https://haveibeenpwned.com/Passwords

**Comment by Rory-Powell** [comment]
We've updated the account signup process to no longer require specific rules, apart from a minimum of 8 characters
