### ISSUE TITLE
[Builder / Core] - Enable an inline editor (TinyMCE / Quill / Other) for text fiels

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5823]
It would be most useful if we could create fields (log text fields) with formatting capabilities. Much like the toolbar right above where i am writing this now.

**Comment by shogunpurple** [comment]
@poirazis you can do this with the long form text field, that comes with a full markdown editor built in!

https://docs.budibase.com/docs/long-form-field

**Comment by poirazis** [comment]
hey @shogunpurple thanks!

i dont know why it skipped my mind given the fact i already built forms using that.
this suggestion hasnt been my finest moment :)
