### ISSUE TITLE
Date Picker form field not responsive

### ISSUE THREAD

**Issue by leonardo-pieraccioli** [Budibase/budibase#5824]
**Describe the bug**
The Date Picker form field is not responsive

**Expected behavior**
It should stretch and expand as the other fields

**Screenshots**
![PC view](https://user-images.githubusercontent.com/67798721/167847501-724b68da-ea0f-40f0-9033-e8b49d32f5db.png)

![Responsive](https://user-images.githubusercontent.com/67798721/167847536-315aaabb-98c8-44bb-a3e1-cbdc470ebdea.png)

**Desktop (please complete the following information):**
 - OS: OS 
 - Browser: chrome
 - Version: 101.0.4951.54

**Comment by melohagan** [comment]
Hi @leonardo-pieraccioli 

I can't reproduce this. Could you share your component tree or app export please?
