### ISSUE TITLE
Cloning/Editing Entry

### ISSUE THREAD

**Issue by PaulMcF1987** [Budibase/budibase#5830]
I posted the question in the community discussion - https://github.com/Budibase/budibase/discussions/5828

However, I think I might have found the answer...

The problem seems to be, When the `Field Groups` are set, it seems to automatically either set the entries as Long Text or Number

There are a lot of fields in my form so I tried changing all of the Long Text fields to Text Fields... However in the Text Entry settings, when I type the column name, it tells me `The field you are setting is the wrong data type for this component`

The Datatype was set to text... I then changed it to TinyText to see if this made a difference but no joy.

I decided to give BudiBase a try to see if it would make things easier but Ill be honest, it has proven to be a nightmare since the get go

**Comment by mike12345567** [comment]
Hi @PaulMcF1987 - sorry I don't quite understand you issue, could you provide some replication steps as to how you found this issue?

Are you using an external datasource, and if so which one, also if you could provide some information about the schema of your table that would be great.

Budibase automatically determines what fields to use based on the column type, its possible there is a mismatch with some SQL column type.
