### ISSUE TITLE
Button or icon action ignored in linked table row

### ISSUE THREAD

**Issue by rourke** [Budibase/budibase#5837]
**Hosting**

- Self
  - Method: docker
  - Budibase Version: 1.0.150

**Describe the bug**
The action of a button or an icon inside the table row, that allows rows to be linked, will be ignored. In my case I want a table row to be linked to `/item/:id` and separate buttons or icons in each row for `/item/edit/:id` and `/item/delete/:id`. When I click the buttons I go to `/item/:id`.

**To Reproduce**
1. Create a data provider (not sure if this step is required)
2. Insert a table showing the data, and allow table rows to be linked (in a modal in my case)
3. Add a button or icon with a different link action than the table row link
4. Notice how the button or icon action is ignored. Instead it will always open the link from the linked row

**Expected behavior**
Buttons and icons should always have priority over a linked table row.

**Screenshots**
Structure example
![image](https://user-images.githubusercontent.com/2820753/167942150-1faf2c7a-7b31-4dbe-9d23-0d8a72ff8ac8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Browser: Chrome
 - Version: 101.0.4951.54

**Comment by Rory-Powell** [comment]
Hi @rourke 

Could you try updating to the latest version first? It should be `1.0.154`

I wasn't able to reproduce, here's an example where I've used two additional ways to link to another screen using a `Link` and `Button` component to link to a different screen other than the default `View` button

https://user-images.githubusercontent.com/8755148/168092802-2e7034ab-7405-48f6-b7ba-11dbe3921456.mov

To test if there is a problem with your install you could import the export:
[5837-export-1652363917782.txt](https://github.com/Budibase/budibase/files/8679747/5837-export-1652363917782.txt)
Then visit the home page and give it a go yourself

**Comment by rourke** [comment]
I've updated to `1.0.154` and imported your project. It behaves as in your video, but the key here is _linked table rows_. To reproduce you can enable row linking to for example `/directory/:id`. Now every button or link click opens both the row link and the button link.

In my case I run everything in a modal. If you enable `Open screen in modal` for the linked row and the View and New buttons you see my original problem description: the buttons are ignored.

**Comment by rourke** [comment]
Thank you for your investigation. I will apply the workaround for now.

**Comment by melohagan** [comment]
This appears to be fixed. Tested in **v1.4**

![Screenshot 2022-09-23 at 08 35 29](https://user-images.githubusercontent.com/101575380/191912219-d704902d-09b6-453b-9652-b41a0b17a21e.png)

![bug](https://user-images.githubusercontent.com/101575380/191912374-39684f9f-551d-4a65-81dd-3aae58be4539.gif)
