### ISSUE TITLE
Unable to save modifications in REST query

### ISSUE THREAD

**Issue by bjornclauw** [Budibase/budibase#5838]
**Hosting**
docker 1.0.154

**Describe the bug**
When editing existing query's unable to save (most of the time)

**To Reproduce**
1. Go to existing query
2. Add a binding or parameter (save button stays greyed out)

![Schermafbeelding 2022-05-12 001610](https://user-images.githubusercontent.com/32811735/167957207-7d70a7a4-4c5a-4f99-82c9-0363a914c24a.jpg)

//
1. Go to existing query
2. Edit the body
4. first time you edit, you can save (after you click outside of the textfield)
5. After first save, the button stays greyed out (you have to refresh the page)

![Schermafbeelding 2022-05-12 001807](https://user-images.githubusercontent.com/32811735/167957233-78ca2b60-536b-4aa4-9e80-9d8e3082a8e3.jpg)

![Schermafbeelding 2022-05-12 002156](https://user-images.githubusercontent.com/32811735/167957245-49c7ae47-8137-4428-a1ca-9e569c876b23.jpg)

temporary workaround: 
- add your binding
- add empty header after making changes -> push the save button
- reload page, delete empty header -> push the save button -> reload page

**Comment by Rory-Powell** [comment]
Thanks for raising this @bjornclauw 
We'll have a fix out shortly
