### ISSUE TITLE
regression: multi-page tables not printable

### ISSUE THREAD

**Issue by yeoldegrove** [Budibase/budibase#5842]
**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: [v1.0.154](https://github.com/Budibase/budibase/releases/tag/v1.0.154)

**Describe the bug**
#4870 and https://github.com/Budibase/budibase/pull/4872 added support to print multi-page tables.
This works fine for me in  [v1.0.110](https://github.com/Budibase/budibase/releases/tag/v1.0.110) but is broken after an update to  [v1.0.154](https://github.com/Budibase/budibase/releases/tag/v1.0.154).
Pages are cropped again...

**To Reproduce**
1. open print dialog an a page with multi-line tables

**Expected behavior**
I can print multi-line tables.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chromium 101, firefox 96

**Comment by aptkingston** [comment]
Thanks for reporting @yeoldegrove :+1: We don't have a test for this so we missed it. I've opened a PR to fix this again.

**Comment by Rory-Powell** [comment]
Deployed in `1.0.158`
