### ISSUE TITLE
Error Fetch Google Sheet Tables

### ISSUE THREAD

**Issue by nicolopozzato** [Budibase/budibase#5854]
**Hosting**

- Self
  - Method: docker-compose
  - Budibase Version: 1.0.154

**Describe the bug**
I have setup the Google Auth, I also add the Drive and Sheet API to the google application on the google console.
If you add a Google Sheet in an app and then autenticate it's manage well and i don't get error (i don't have enabled the google autentication on my budibase Auth section (user authenticate with their budibase account).

I'm using a Google Workspace account (i'm an admin of our organization so i create the google project on the correct console), the google sheet is in a shared drives and i have the google sheet url, i put that in the google sheet url (i also try with only the id and with different urls, it seems ok, but when i save that and click "Fetch tables" I get this error:
`Error updating datasource schema`

**To Reproduce**
1. Setup google authentication
2. Add a Google Sheet on a project
3. Try to Fetch the tables
4. See error `Error updating datasource schema`

**Expected behavior**
I'm exepting to import the table and mantain the correlation between budibase and that google sheet like appsmith.

**Comment by shogunpurple** [comment]
Hi @nicolopozzato - would you be able to show the logs for your `app-service` or `worker-service` to see what the actual error message being thrown is?

`docker-compose logs worker-service`
`docker-compose logs app-service`

Then click "Fetch tables".

This discussion may also be of use:
https://github.com/Budibase/budibase/discussions/4471#discussioncomment-2612132
