### ISSUE TITLE
Postgres: 504 Gateway Timeout - Incorrect Host value

### ISSUE THREAD

**Issue by Mitch-Budibase** [Budibase/budibase#5860]
This is occurring across all environments.

Reproduction steps:

1. Create app
2. Add data source
3. Select Postgres
4. Click save and fetch tables (without changing any configuration)
5. Wait 2 minutes
6. 504 Error is thrown, empty error modal shown

Attempting to save and fetch tables with an incorrect host causes a 504 gateway time-out. We also see an empty error modal appear at the top of the screen.

With the likes of Oracle and MySQL, attempting to save and fetch tables with an incorrect configuration throws a 500 error. This was previously the case with Postgres. 

Having the correct Host, with the rest of the configuration being incorrect, will throw the 500 error that we seen before and see with Oracle and MySQL.

It takes 2 minutes each time for the request to fail. The save and fetch tables button spins during this time.
My expectation is that the behaviour should be the same as Oracle and MySQL. I have an automation test affected by this issue. The workaround could be to update the test to expect a 504 (coupled with a 2 minute wait for the timeout to occur). 

I've attached a screenshot below:

![Screenshot 2022-05-12 at 19.13.28.png](https://images.zenhubusercontent.com/60fed9d54a973614368dfdfe/dae62f87-584d-47ce-8297-f0fd240e510d)

**Comment by melohagan** [comment]
Appears to be fixed! Closing.

**Comment by mendoncart** [comment]
Hello!
I'm having the exact same problem on version 2.10.10
![image](https://github.com/Budibase/budibase/assets/62950083/4a46111c-0d43-44ee-98f4-5c3d8cf20800)

Is there any way to solve this, or increase the time?
