### ISSUE TITLE
Budibase DB Table Column sort not working properly

### ISSUE THREAD

**Issue by Kanary159357** [Budibase/budibase#5865]
**Hosting**

- Cloud
I'm using 1.0.156  version of Cloud Budibase

**Describe the bug**

I'm using Budibase DB to make example data and tried to save timestamp value with Number Column

I found that when even column with type Number are sorted unexpectedly

As shown in the picture, the sort is not working properly. I think there are some wrong sorting logic

Below 958181100, there are some values bigger than 958181100.... and also they are not sorted.

I wonder whether it is budibase db 's problem or problem of budibase table it self.

Also, Text Type Columns are not working properly with date-time format. 

It's hard to say that it's a string comparison order....

**Expected behavior**

It should sort by value properly

**Screenshots**

Number

<img width="166" alt="image" src="https://user-images.githubusercontent.com/69702813/168215217-a678d493-ea7a-406b-8257-71650956b017.png">

Text

<img width="175" alt="image" src="https://user-images.githubusercontent.com/69702813/168219755-fb027491-47ce-4402-b221-0907c32b9f27.png">

**Desktop (please complete the following information):**
 - OS: 2021 Macbook pro M1 Montrery
 - Browser Chrome
 - Version [100.0.4896.127 (arm64)]

**Comment by simonedelmann** [comment]
Hello! Is there any progress on this one? I encountered the same / a similar issue:

In the image below I sorted some items by its Auto ID. I cannot figure out any logic behind the sorting.

I also have a numeric field in this table, which I manually filled with some increasing numbers (1-25): Not only they are sorted strangely in two increasing blocks (6, 9, 10, 11, 12, 14, 15, 18, […], 1, 2, 3, 4, 5, 7, 8, 13 […]), I can also sometimes move them from one block to the other by simply clicking Edit->Save row without touching any data.

(Side note: I didn‘t confirm this yet, but I had the impression the sorting was correct for the first ~10 items and it got messed up when pagination got used.)

Furthermore I can confirm, the same strange sorting also applies when using a table block in design section. (It is also starting with 6, 9, 10…)

I am using Budibase 1.2.47 (selfhosted via docker-compose) and Budibase DB for this table.

![IMG_0322](https://user-images.githubusercontent.com/2821076/187007819-e6d1c8ae-afdf-4bfe-8c4f-c336b3fc0c99.jpeg)
