### ISSUE TITLE
Error upgrading from v1.0.110 to v1.0.156

### ISSUE THREAD

**Issue by martino-zito** [Budibase/budibase#5866]
hi, i've just upgraded the container version from v1.0.110 to v1.0.156 on a kubernetes cluster.

The installation has been done some months ago with budibase helm chart version 0.28.

Can you please help me to understand this error?

<img width="1363" alt="Screenshot 2022-05-13 at 08 14 43" src="https://user-images.githubusercontent.com/1997948/168222946-6f681b95-fcff-47a9-86c6-e8289ec6a120.png">

**Comment by Rory-Powell** [comment]
Hi @martino-zito , I've been able to re-create this by shutting down my couchdb container prior to startup. Looks like your db pods might not be running

**Comment by martino-zito** [comment]
No no are running. i've never stopped them. Just restarted budibase app and worker.
<img width="1151" alt="Screenshot 2022-05-13 at 10 27 45" src="https://user-images.githubusercontent.com/1997948/168243496-7e484da3-98e1-43fa-8c18-a1ae1166ea27.png">
<img width="1363" alt="Screenshot 2022-05-13 at 10 28 14" src="https://user-images.githubusercontent.com/1997948/168243535-85c788cf-a347-4b3d-9655-9f1af23db8fc.png">

**Comment by Rory-Powell** [comment]
then I think the issue is related to the very first log line, there's a 401 indicating that budibase isn't using the correct credentials for the database. To check what the username and password are you can inspect the `x-couchdb` secret, then you could attach a shell to the app-service / worker-service and grep for `COUCH_DB_USER` and `COUCH_DB_PASSWORD` to make sure they match. If they do then we can look further into this

**Comment by martino-zito** [comment]
can u explain how to do "To check what the username and password are you can inspect the x-couchdb secret" this ?

**Comment by martino-zito** [comment]
Done i think

<img width="824" alt="Screenshot 2022-05-13 at 17 21 03" src="https://user-images.githubusercontent.com/1997948/168315629-32f4768f-f375-460d-8479-aeca942d81a6.png">

<img width="729" alt="Screenshot 2022-05-13 at 17 21 21" src="https://user-images.githubusercontent.com/1997948/168315669-3fb69d6f-9a2a-4cff-b067-56afa9a51728.png">

**Comment by mike12345567** [comment]
Hi @martino-zito - your images included secrets from your CouchDB cluster, I removed them as you shouldn't present these publicly - you may want to change them.

**Comment by martino-zito** [comment]
nop its a test cluster and is not publically available

**Comment by mike12345567** [comment]
Just to check @martino-zito - have you updated your Helm chart itself, there was some changes to it two weeks ago, if you're still using the helm chart from v1.0.110 you may run into some issues.

Helm chart here: https://github.com/Budibase/budibase/tree/develop/charts/budibase

**Comment by martino-zito** [comment]
https://budibase.github.io/budibase/ this is the url of the chart. is it right?

**Comment by mike12345567** [comment]
Hi @martino-zito yes that is the right location, `0.2.9` is the latest version, I just noticed your CouchDB cluster appears to still be using the CouchDB chart `3.3.4` based on the labels in the picture, when the helm chart specifies that `3.6.1` should be used, perhaps it hasn't upgraded successfully, have you performed `helm upgrade -n budibase budibase budibase/budibase` as per the [docs](https://docs.budibase.com/docs/kubernetes-k8s)?

**Comment by martino-zito** [comment]
a simple upgrade is not enough to upgrade couchdb image version because it is fixed in values.

**Comment by martino-zito** [comment]
i've restarted app and worker right now. and now is using v1.0.158 (the latest) and the problem has gone. the couch db version is still 3.3.4

**Comment by shogunpurple** [comment]
Thanks @martino-zito for debugging with the team. I think the issue with couch versions was a red herring - what seemed to have happened is that your design doc was missing, and after the restart of services (or possibly even couch) your design doc was created again, the migrations were run and your platform now works. This is good to know for future reference, if it ever crops up in the community again, so thanks for the detail.
