### ISSUE TITLE
New AutoID Column and Identifiers not applied to Existing Data

### ISSUE THREAD

**Issue by Elliot-Construct** [Budibase/budibase#5874]
Hey Budis

When I add an **AutoID** column to an existing data structure it _doesn't_ apply automatic ID numbers to existing data within the table.

I feel like this is a data classification issue in the Automatic Identification Column creation process. Since all current data remains unidentifiable in relation to that field and all future data gets incremented from 1 onwards, thus creating non-continuous identifiers.

How can we fix this and does everybody else agree that this is a data handling issue?

- [ ] Workaround?
(Could we maybe export the data to another database and create a script to import the data to the database thus creating the autonumbering?)
- [ ] how can this be fixed 
(perhaps with a chronological datestamp script that takes the oldest entries and applies the numbering from there as part of the AutoID column creation process)

Cheers
Elliot.

**Comment by Elliot-Construct** [comment]
Bump

**Comment by mike12345567** [comment]
Hi @Elliot-Construct - sadly this is just a design feature of all the auto column types, for now this is unlikely to change as we don't have a bulk update mechanism that could go through a very large quantity of data and update auto columns that are usually added at row creation.

Ideally the best route for now is to export all of the data and add it to a new table with the auto column already setup.
