### ISSUE TITLE
Authentication config for REST API not getting saved

### ISSUE THREAD

**Issue by mathewhealthi** [Budibase/budibase#5900]
On the cloud version of Budibase, while configuring a REST API data source, when an authentication config is created and added, upon refreshing the app, the  authentication config is no longer available and hence cannot be selected in the REST API query.

**Comment by Rory-Powell** [comment]
Hi @mathewhealthi, just to confirm this isn't a UX issue, have you scrolled to the top of the datasource and clicked `Save` after adding the authentication config?

**Comment by mathewhealthi** [comment]
> Hi @mathewhealthi, just to confirm this isn't a UX issue, have you scrolled to the top of the datasource and clicked `Save` after adding the authentication config?

Aah this works. Apologies. It would disappear when I went into a query without saving the entire source it seems. Thanks for the response!

**Comment by Rory-Powell** [comment]
No problem! It's a valid point, it's not immediately clear that a save is needed especially as the save button is out of view
