### ISSUE TITLE
Sorting alphabetically where it should not

### ISSUE THREAD

**Issue by GabrieleLabanca** [Budibase/budibase#5903]
**Hosting**
- Self
  - Budibase Version: 1.0.46

**Describe the bug**
Numeric fields from SQL query are not sorted properly (apparently, they are treated as strings).

**To Reproduce**
1. create SQL query 
2. create data source setting the first column of the query as sorting field
3. show data in a table (same with a histogram)
4. the wrong sorting happens as in figure

**Expected behavior**
I expect the numeric values to be sorted numerically and not alphabetically. 

**Screenshots**
![Screenshot 2022-05-16 at 11 15 03](https://user-images.githubusercontent.com/6714239/168560248-1ec7909e-34f3-44a9-b522-ae73b814220c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 100.0.4896.127

**Additional context**
Probably related to: https://github.com/Budibase/budibase/issues/4804#issue-1160458588 and https://github.com/Budibase/budibase/issues/5865#issue-1234749629

**Comment by melohagan** [comment]
Tested the latest version with SQL Server, MySQL and Postgres. Appears to be sorting numerically as it should.
