### ISSUE TITLE
External Data Connector does not handle arrays

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5912]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: v1.0.145
  - App Version: v1.0.145

**Describe the bug**
The external data connector does not return an array from response. It returns an object with the indices as the keys.

**To Reproduce**
1. Create an automation with Do This: External Data Connector
2. Use a simple REST query that returns an array of values
3. Run test
4. The EDC returns an object not an array

**Expected behavior**
The external data connector should be able to return an array output.

**Screenshots**
![Screenshot 2022-05-16 at 16 55 33](https://user-images.githubusercontent.com/101575380/168634212-6af0b77d-a8b8-498e-a019-e38f98e94e33.png)

![Screenshot 2022-05-16 at 16 56 30](https://user-images.githubusercontent.com/101575380/168634400-3e3a20af-0019-45f7-8ab6-441c33c7f607.png)

**Desktop (please complete the following information):**
 - macOS

**Comment by Shadowfita** [comment]
I am also experiencing this issue.
