### ISSUE TITLE
Enable Cacheable Queries

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5917]
### Discussed in https://github.com/Budibase/budibase/discussions/5885

<div type='discussions-op-text'>

<sup>Originally posted by **mattiason** May 13, 2022</sup>
Would it be possible to store the latest query from e.g a rest API until a new request is made? The main reason is that sometimes you would like to use some data e.g a list in a drop down and it becomes relatively slow sometimes when all the time needing to call the api. Therefore it would be nice to be able to store the last query inside the app without the need of adding it to a table.</div>

As a user, I want to be able to set a queries results as cachable with an expiry, so that I can fetch it again within the cache limit and improve performance.

**COS**
- Add cache option to data provider query option
- Add TTL to caching option

**Comment by NLKNguyen** [comment]
Up voted! Also, when Budibase supports PWA (#5668), having cache options on the client-side for offline browsing is even more powerful.

**Comment by matteoveglia** [comment]
+1 for this, I have a rarely updated data source which is part of a landing page and it takes 4.7s avg to load regardless of if i'm using the internal db or my own

**Comment by christophsanz** [comment]
+1

**Comment by mjashanks** [comment]
This can be achieved using the 

On Screen Load action, which should

Exceute REST request

Save the response to state - i.e. Update State actions
