### ISSUE TITLE
Budibase apps don't work in safari

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#593]
Budibase apps only seem to run in chrome and FF. When running in safari:

![Screenshot 2020-09-10 at 15 30 28](https://user-images.githubusercontent.com/11256663/92745778-8fa90580-f37a-11ea-901b-5316e5966688.png)

The 500 error is strange because it doesn't even hit the server - it looks like the requests are being cancelled somehow.

**Comment by mjashanks** [comment]
Possible that its a cookie policy.... we set `httpOnly: false` - which we really would like to avoid i think

**Comment by Benoitv98** [comment]
> Possible that its a cookie policy.... we set `httpOnly: false` - which we really would like to avoid i think

Hey  @mjashanks, 
I'm new to GitHub and also new to this awesome developing software. 
I encountered the same problem when I wanted to deploy my application and open it on the browser Safari. 
Now I was wondering, is there a possibility to solve this problem so that it could run on Safari? 
thank you for your answer! 

Kind regards, 
Benoît

**Comment by mjashanks** [comment]
Hi @Benoitv98.

This is currently a bug with Safari on iOS. I will reopen this ticket, and we will look at it as soon as possible - thanks for letting us know!

**Comment by shogunpurple** [comment]
Additional info - This actually only happens with cloud hosted apps. Seems to be an issue with how HTTPS certificates are set up in our AWS environment. Will investigate

**Comment by shogunpurple** [comment]
The issue we are seeing with iOS devices is described here - https://developer.apple.com/forums/thread/655074?page=2

Ever since iOS 14, underscores are not supported in wildcard domains on iOS. According to the actual internet standard RFC about domains, underscores should actually not be valid in domain names, but that's a separate issue.

The easiest way to solve this is to update app IDs to be separated by hyphens instead of underscores.

I do not want to do this now before 0.8. A few reasons:
- Its potentially a breaking change for old apps
- It only affects iOS users viewing apps in our cloud platform
- It's fairly high risk to change since it underpins almost everything in BB

I'll move this one out to backlog, and get it addressed after we've rolled out 0.8.

**Comment by shogunpurple** [comment]
No longer relevant on latest release
