### ISSUE TITLE
Rest API (verify certificate = false)

### ISSUE THREAD

**Issue by therapac** [Budibase/budibase#5930]
**Describe the feature request**
I am looking to bypass this error (Screenshots) in budibase.
Is it possible to add a checkbox with a function (verify certificate = false).

**Screenshots**
![image](https://user-images.githubusercontent.com/55585899/168795261-f6df2ed4-3388-498b-aa8e-0d6ad91c5de0.png)

**Comment by serhii-bielozorov** [comment]
As a workaround, you can set the environment variable NODE_TLS_REJECT_UNAUTHORIZED: '0', it helped me on docker-compose deployment.
