### ISSUE TITLE
The form steps not shown in the form designer on click

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5935]
### Discussed in https://github.com/Budibase/budibase/discussions/5921

<div type='discussions-op-text'>

<sup>Originally posted by **Harshtone** May 17, 2022</sup>
Hi,
I was working with the Form Steps, I only see the first step of the form in the Designer being updated. if i click on the other steps the designer still stays at the first step . so its been little difficult for me to design other steps without preview it. in the designer . please let me know if others facing this problem as well. thanks 
![Screenshot (19)](https://user-images.githubusercontent.com/55141711/168749173-45137552-d1bd-4bcb-b2ff-453cee448a59.png)
 </div>

**Comment by aptkingston** [comment]
This has already been fixed - they just need to update their app to the latest version.
