### ISSUE TITLE
Options picker/Multi-select picker with "add option" as first or last option

### ISSUE THREAD

**Issue by Upgreydd** [Budibase/budibase#5940]
Let's say I have table roles in schema:
- Department (varchar)
- Team (varchar)
- Role (varchar)

Now I'd like to be able to create records with an option to select already created Departments/Teams if they exist so I'm adding:
- DataProvider for roles
- Options picker with selection and value for Department
- Options picker with selection and value for Team
- Options picker with selection and value for Role

OK Now I can select between existing values from other records, but I'm not able to add a new option to the above lists. In such case, I need to use inputs and any typo will destroy the hierarchy in Department -> Team -> Role

**Comment by aricooperdavis** [comment]
I would like to see support for this added too :)
