### ISSUE TITLE
Public form show "Session not authenticated" when user try to upload an attachment

### ISSUE THREAD

**Issue by HMXHIU** [Budibase/budibase#5945]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.158

**Describe the bug**
Public form show "Session not authenticated" when user try to upload an attachment.

**To Reproduce**
1. Create new app
2. Add a form and attachment component
3. Set both the read and write table permission to public
4. Publish app
5. Open app in incognito and try to upload any file.

**Expected behavior**
User are able to upload attachment in public form without sign-in

**Screenshots**
<img width="1467" alt="Screenshot 2022-05-18 at 11 01 35" src="https://user-images.githubusercontent.com/9115894/168949961-00cd3c30-babb-4b5d-8c97-336dd2793cce.png">

**Additional context**
The `id` in upload URL was `undefined`

**Comment by raziele** [comment]
Additional context:
- doesn't work with Safari for IOS, Safari for macOS, Chrome for IOS, Chrome for macOS.
- works with Edge for macOS

**Comment by HMXHIU** [comment]
Updates:

Turns out it was due to the setting of schema in form component. It will work if I set the form schema to follow a public table schema but does not work for all other options. Maybe there is something wrong with the authentication check for schema when user are not signed in.

<img width="482" alt="Screenshot 2022-05-26 at 11 46 48" src="https://user-images.githubusercontent.com/9115894/170412503-d87bfb0c-1dc3-4fd1-a21a-c23f80c2ebb4.png">

**Comment by mayanktiwaridotcom** [comment]
Hi Guys,

Facing the same issue, in my case schema is custom, as the form fields i am storing in different table and attachment in budibase db table. So the form schema is custom and I am using 2 steps to save form:
1. fields in mysql db
2. attachment in budibase db.

Is there any immediate fix or workaround for this ?

**Comment by charlfields** [comment]
> Updates:
> 
> Turns out it was due to the setting of schema in form component. It will work if I set the form schema to follow a public table schema but does not work for all other options. Maybe there is something wrong with the authentication check for schema when user are not signed in.
> 
> <img alt="Screenshot 2022-05-26 at 11 46 48" width="482" src="https://user-images.githubusercontent.com/9115894/170412503-d87bfb0c-1dc3-4fd1-a21a-c23f80c2ebb4.png">

@HMXHIU This resolved the problem than you so much!

I would recommend @mayanktiwaridotcom to make all the tables public like this case https://github.com/Budibase/budibase/issues/4582#issuecomment-1054444261 including the tables on the MySQL database.

**Comment by melohagan** [comment]
Thanks for the extra info guys!

I've added a section to the docs to explain this: https://docs.budibase.com/docs/attachments#manage-access
