### ISSUE TITLE
[BUDI-6756] Text formatting icons missing (rich text support / markdown)

### ISSUE THREAD

**Issue by chooimail** [Budibase/budibase#5947]
**Hosting**

- Self
  - Method: Docker
  - Budibase Version: 1.0.145

**Describe the bug**
Column type = Long form text
Formatting with rich text support (markdown) = Enabled
### Problem = The formatting buttons/icons go missing or become invisible

--------------------
**To Reproduce**
- This is weird, because I didn't do anything except start the Docker container, log into Budibase, Create column, then create row.
- Also, it is affecting previous existing tables, or columns rather... that have the formatting **Enabled**

PS.
I can live without the extra formatting, but would be nice to use it if available

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari] : Chrome, Edge

![markdown problem](https://user-images.githubusercontent.com/77225894/168974089-85640be8-53fe-4e33-9e25-5649c3d3d19e.png)

<sub>[BUDI-6756](https://linear.app/budibase/issue/BUDI-6756/text-formatting-icons-missing-rich-text-support-markdown)</sub>

**Comment by melohagan** [comment]
Could not recreate in **v1.4**. Closing.

![Screenshot 2022-09-23 at 11 33 20](https://user-images.githubusercontent.com/101575380/191942717-64a11b6d-ef2a-412c-bdc4-2d73c114bec3.png)

**Comment by melohagan** [comment]
Re-opening because I am now able to see this issue!

**Comment by melohagan** [comment]
This bug was introduced in **2.3.0** by the use of the font-awesome packages: https://github.com/Budibase/budibase/pull/9371/files#diff-a549d2657aa3ea787f685c405385a2c352488058096cb3c4d68a4ab82bf3bf50

I tried a couple of things, but I wasn't able to figure out a workaround without removing the packages.

**Comment by kerk1v** [comment]
Hello, 

I see the same bug in 2.3.20

<img width="375" alt="Screenshot 2023-03-05 at 12 45 10" src="https://user-images.githubusercontent.com/16302524/222958495-83c6d220-3041-4290-bc7e-9feeb5b91554.png">
