### ISSUE TITLE
Google Sheets integration cannot auth on self-hosted setup. Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by cfepdan** [Budibase/budibase#5967]
**Hosting**
- Self
  - Method: Docker single image on Azure.
  -- Set up with Google auth to log in to Budibase, FWIW.
  -- Platform URL correctly set to our domain
  - Budibase Version: 1.0.14

**Describe the bug**
When I try to add a Google Sheet as a data source, I click "Sign in with Google" and receive a redirect_uri_mismatch error.

![image](https://user-images.githubusercontent.com/28074021/169089146-4861b973-07ac-4ea8-b578-261d235b6e48.png)

**Comment by mike12345567** [comment]
Hi @cfepdan - just to mention, currently there is no supported single docker image installation of Budibase - the dockerfile that we've started working on is extremely experimental and still requires quite a bit of work.

**Comment by Rory-Powell** [comment]
@cfepdan this might be asking an obvious question but have you whitelisted the additional redirect url in your GCP account?
Note that the url path is slightly different from the normal google login endpoint

**Comment by cfepdan** [comment]
I appreciate your obvious question. No. I had not. And now that I have, we are good to go.

So, this issue can either be a request to add this to the documentation, or it can be closed. Thanks!
