### ISSUE TITLE
Icon Standard Component

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#598]
We need a way to add icons to budibase apps.

https://remixicon.com is what we use for the builder, and probably makes the most sense here.

**Notes**
- Add remix icon CSS to standard components
- Add an icon component to standard components

- Allow it to be configurable through the settings panel or the left hand side as separate components. @joebudi might have a preference here

**Comment by joebudi** [comment]
Ola.

We need a large icon set. Bootstraps new icon set is great and growing fast:
https://icons.getbootstrap.com/

and then there's font awesome and material.

All 3 packs are pretty extensive.

IMO, I'd prefer font awesome or Bootstrap. Font awesome has a lot, but most of the best are paid.

I'm not sure about the installation process which will play a huge part in the decision.

**Comment by Conor-Mack** [comment]
Nice, bootstrap icons look really slick.

@shogunpurple whats your thoughts on this?

**Comment by shogunpurple** [comment]
@Conor-Mack hard to beat font-awesome in terms of adoption and ease of installation through a single CSS file.

The question is how do we use the icon component? 
- Do you click it on the left and you get a whole bunch of individual icon components?
- Do you select `Icon` from the left panel and change the icon in the settings panel?

Whatever one we choose, the user needs to be able to preview the icons before selecting them. We can't just give them a big list of classnames

**Comment by Conor-Mack** [comment]
@shogunpurple we could probably render a preview of the icon next to the class name / icon name within an OptionSelect component. 

Similar to how we preview fonts in typography design panel
