### ISSUE TITLE
User Groups: User Groups Tab

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5985]
When I'm on the portal, I want to be able to access the "User Groups" tab so that I can manage the members and permissions of my teams.

**Spec**
https://docs.google.com/document/d/1M_J4VFMI4GDyen_AfaLiYKR1MIbucM26WlkHpbesvGg/edit#heading=h.l6m9u5gc64j4

**COS**
- Add teams tab
- Add upgrade button for free users

- User Group UI
- UI for creating a new User Group (name, icon, colour)
- Group management UI (adding/removing members)
- List of apps the Group has been assigned to

**Designs**

Figjam - https://www.figma.com/file/QfMIrA5JV4nYOze62DTWl4/User-management?node-id=0%3A1

**Comment by MihailHadzhiev2022** [comment]
![Screenshot 2022-08-01 at 13.54.37.png](https://images.zenhubusercontent.com/623866329f3f8e7223d95e00/f4e12be8-e049-4c1d-b3cf-13dd294ae75d)

**Comment by MihailHadzhiev2022** [comment]
I created 3 user groups and deleted two of them, I tried to create a second one again and I got this error message.

**Comment by MihailHadzhiev2022** [comment]
Bug-2 :   Add users not working as expected https://www.loom.com/share/e640d66df3f3477bafece4c284a925bf

**Comment by MihailHadzhiev2022** [comment]
bug-3 ![Screenshot 2022-08-01 at 14.08.18.png](https://images.zenhubusercontent.com/623866329f3f8e7223d95e00/3b14098c-d387-4c1b-bfa9-8a949cda502c)

**Comment by MihailHadzhiev2022** [comment]
Can we change the error message with "Licensed Developers of 5 has been exceeded. To upgrade, visit https://account.budirelease.live/portal/upgrade" 
![Screenshot 2022-08-01 at 16.17.22.png](https://images.zenhubusercontent.com/623866329f3f8e7223d95e00/fc126e57-c30f-4134-bc88-079352333136)

**Comment by Rory-Powell** [comment]
Looks like the groups tab isn't loading where there are no groups present:
![Screenshot 2022-07-27 at 17.12.27.png](https://images.zenhubusercontent.com/60d9d62f3f2380536d5a5bf2/25fc7e95-48f5-4926-8034-9904929547e8)

**Comment by Rory-Powell** [comment]
Remove previous no access comment, issue was related to new `USER_GROUPS` feature flag not being present
