### ISSUE TITLE
Request Edit Control

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5989]
When I can see that another user is developing an app, I want to be able to request the app lock so that I can develop on the app.

**Spec**
https://docs.google.com/document/d/1ptRAGHn6axyXoEujhySFMUs6ku0jXmkJ14u1-5i5v3w/edit#heading=h.2co4ty69g1x0

**COS**
- Allow user to request control of a locked app from app overview panel
- Notify user with lock that you have requested access and give them option to deny or allow
- Timeout lock after 20 seconds if no choice picked, and automatically release
- Notify the lock requesting user of the lock holding users choice

**Questions**
- Should we re-add the CTAs to view/edit app on the app list?

**Designs**

Figjam - https://www.figma.com/file/rpdJ0jJYp1QbhGGKQyvD6l/Removing-app-lock?node-id=0%3A1

**Comment by melohagan** [comment]
This is no longer needed. https://docs.budibase.com/docs/multi-dev-collaboration
