### ISSUE TITLE
Deployment Data - History, Errors

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#599]
Right now, we just allow a user to click deploy and wait for their app to be deployed.

We need a way to track a history of deployments and their statuses. 

This helps us see how many times a user deploys, as well as tracking error metrics, number of files etc.

It would be useful to have these analytics for debugging and potential product features in the future.

**Comment by joebudi** [comment]
I would add, the success link needs to be redesigned - it can be hard to see.

**Comment by shogunpurple** [comment]
This is now stored locally on our users machines. Closing this one
