### ISSUE TITLE
Current Date and Date Operations

### ISSUE THREAD

**Issue by Hajelarohit** [Budibase/budibase#5991]
**Describe the feature request**
I have dates in my database and I want to do few operations, filters to see if anything is overdue. for example, a document was to be provided by 5/01/2022. Since today's date is 5/19/2022, it is overdue and I want to get notified. 

**Screenshots**
I have an end date in one of my databases. I want to create a filter to view overdue items
![image](https://user-images.githubusercontent.com/104535363/169441698-cc357e61-21ec-4a5d-9d1c-b9bdad66d4cc.png)

searching for date in filter gives me following options
![image](https://user-images.githubusercontent.com/104535363/169441898-26c49193-2fe4-4e5d-a2c6-db183b9cf3ed.png)

![image](https://user-images.githubusercontent.com/104535363/169441924-f9e96022-4259-4395-aa59-b46bb67f41fc.png)

I want to do operations such as the "end date" is less than "today's date" or "end date" is more than "30 Days" away

The filter should also give me an "OR" option. Current Filter only works as "AND" and must meet all conditions.

**Comment by Hajelarohit** [comment]
The Date Range also doesn't fulfill the requirement. The Data Range limits the search to last 1 year. What if want to search a record from 3 years ago? 

I also can't do operations on date such as due date is (date selected + 30 days)

**Comment by mike12345567** [comment]
Hi @Hajelarohit for any date manipulation you'll need to use the JavaScript bindings, you can then use JS date manipulation, for example, you could do something like:
```js
const date = new Date($("New Form.Fields.date"))
date.setDate(date.getDate() + 30)
return date
```

To generate a date which is 30 days past a date selected in a form.
