### ISSUE TITLE
[BUDI-6904] Dynamic Filter - CONTAINS Option

### ISSUE THREAD

**Issue by Hajelarohit** [Budibase/budibase#5995]
**Describe the feature request**
Current Dynamic Filter doesn't have the capability to search partial strings. 
**Screenshots**
My Data contains multiple first and last names of Vendor Managers. 
![image](https://user-images.githubusercontent.com/104535363/169449580-56a487fb-85b9-487e-abc5-af5c3feb1249.png)

The filter should be able to search with only first name of last name or even partial strings. I tried Like, but it doesn't work for this.
![image](https://user-images.githubusercontent.com/104535363/169449373-c4e94c38-35c7-44b5-8b6c-be374adf7e4e.png)

<sub>[BUDI-6904](https://linear.app/budibase/issue/BUDI-6904/dynamic-filter-contains-option)</sub>

**Comment by JeroenvdBurg** [comment]
Definitly a +1 for this enhancement. FYI: If you use a SQL or Postgres connection the Like operator is behaving as a Contains query.

`
 if (this.client === SqlClients.POSTGRES) {
          query = query[fnc](key, "ilike", ``%${value}%``)
`

**Comment by JeroenvdBurg** [comment]
@mike12345567 any thoughts on this one ?

**Comment by aricooperdavis** [comment]
I don't think this should have been marked as completed - the referenced issue is for multi-select types only, not string types as this issue raises.

**Comment by aricooperdavis** [comment]
@shogunpurple I'm still not seeing a `contains` option for filtering string type fields in 2.3.0. Can you confirm that this has been completed for `string` type fields, not just multiselect?

**Comment by jeanole** [comment]
would be highly appreciated!!
