### ISSUE TITLE
Weird behavior around query bindings with negative number

### ISSUE THREAD

**Issue by dannyshin76** [Budibase/budibase#5996]
(1.0.105-alpha.8, on-premise. If this is not reproduced, it may be my local issue)

**Describe the bug**
![image](https://user-images.githubusercontent.com/93232582/169449117-01b1b7a6-8589-4d70-a418-d20277e11299.png)

**To Reproduce**
With mysql query, put a negative number into the binding.

**Expected behavior**
Negative numbers should be passed as-is, but they are being converted into some weird date value. So practically the binding becomes useless within the query.

**Desktop (please complete the following information):**
(Not relevant)

**Additional context**

**Comment by mike12345567** [comment]
Hi @dannyshin76 - this issue has been resolved as of two weeks ago, I believe you are on quite an old development version of Budibase, the current version is `v1.0.166`.

Issue resolved as part of: https://github.com/Budibase/budibase/issues/5612 (this encompassed a few related issues).
