### ISSUE TITLE
Automation -> Query Rows does not apply the filter at all

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#6013]
Hi,

In a self hosted environment i have 2 internal tables like parent and child. I did not create a typical relationship between them, instead i'm saving parents auto id into child. 

I have a need of deleting children when parent row is deleted. Firstly is there a recommended way of achieving this? 

I have tried an automation, whenever a row is deleted from parent, query related child rows and delete them in a loop. 

The problem is, "filter" is not applied in query rows block. even though it is properly entered and value is properly populating for filter criteria. 

This caused all my rows to get deleted instead of only filtered ones. 

Can you check this bug? I believe it is a serious one,

Best regards,

**Comment by PClmnt** [comment]
Hi @aderici. Sorry that you're having issues with this! Can you give a little more information about what the filter in your Query Rows step looks like?

**Comment by aderici** [comment]
Hey thanks for the quick response, very happy to see that, let me share some screenshots : 


This is the general look, Order is the parent object Sample is the child object : 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/6830693/169623096-bd6c28ec-7b57-4c71-804d-61553a99dfb9.png">

This is my filter for querying samples table : 

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/6830693/169623123-864453b9-227c-4add-868c-fb3347eb53b7.png">

And this is the JS code : 

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/6830693/169623165-7c5a7584-cc62-44aa-9d61-57908559142f.png">

**Comment by aderici** [comment]
Also my version number : 
<img width="195" alt="image" src="https://user-images.githubusercontent.com/6830693/169623236-97c69cad-76bf-4f9e-92db-a25336421c2d.png">

**Comment by PClmnt** [comment]
So I had a quick look at this and tried to reproduce. I _think_ the problem is that `Auto ID` doesn't actually come back as the response from the `Delete Row` automation. It will just return the `tableId` and the user added columns. Auto columns aren't returned. So this meant the rows weren't filtered. 

Could you potentially use your own ID column as an identifier instead of the `Auto ID` column?

**Comment by aderici** [comment]
If you want to use an auto increment it would again become an auto column right?

Do you think it is the right behavior to let all data pass unfiltered if one side of the equation is undefined? rather throw an error and dont pass anything i guess. Otherwise you'd let people see unauthorized data or the whole table deleted like my case.

I'll simply state the requirement so you can guide me for the solution. How can you relate 2 tables so that once a parent row is deleted all children would be deleted as well

**Comment by aderici** [comment]
While i'm still interested in the suggested way, i ended up collecting _id s of child rows and sending them to an app triggered automation as comma separated text, when the delete button is pressed for parent.

**Comment by PClmnt** [comment]
@aderici Glad you found a work-around. Just to keep you in the loop I'm actively looking into the original issue. Will keep this issue updated.

**Comment by aderici** [comment]
Thanks @PClmnt today i have noticed a similar behavior in data source filters when i was working for a design of a page.

I had a form (parent info) and a table (child rows) on a page. 

I had a filter on child data source to display only children that belongs to that specific parent. When i have removed the "parent id" from table columns (because doesnt make sense to display from a UX perspective), it suddenly started displaying all children of all parents. 

I'd expect it to display nothing as the filter condition would never have a truthy outcome. 

I think this might be something to consider, that if some part of filter is not available it should let none pass instead of all
