### ISSUE TITLE
bug: Top-level object must be a mapping

### ISSUE THREAD

**Issue by 8debug** [Budibase/budibase#6017]
When I execute `budi hosting --start` as per the documentation，The following exception occurs：

![image](https://user-images.githubusercontent.com/3394927/169691336-0fc8ab8f-a313-4970-b65b-26926356255e.png)
![image](https://user-images.githubusercontent.com/3394927/169691436-4b3abf29-0f2a-4a02-88b7-cd0bdb1eee3d.png)

# The file content of docker-error.log is `Budibase Error Top-level object must be a mapping` and I found **docker-compose.yaml** file size is 0

**Comment by shogunpurple** [comment]
Seems like some folks on SO are having the same issue - could you try this?

https://stackoverflow.com/questions/46550348/docker-stack-deploy-error-about-top-level-object-mappings

**Comment by default-student** [comment]
Still an issue
