### ISSUE TITLE
MySQL: support primary foreign keys 

### ISSUE THREAD

**Issue by palsivertsen** [Budibase/budibase#6029]
**Hosting**

- Self
  - Method: docker compose (testing locally)
  - Budibase Version: 1.0.169
  - App Version: N/A
- Cloud
  - Tenant ID: N/A

**Describe the bug**
I have two tables, "a" and "b", with a one to one relationship where table "b" has a foreign key ("a_id") that references the primary key in table "a". While defining this relationship the foreign key is missing as an option from the dropdown menu.

![image](https://user-images.githubusercontent.com/11890143/169812665-581d9bb6-a7a0-42ed-94d4-9c8b1255cefa.png)

**To Reproduce**
1. Setup a MySQL 5.6 instance with the following tables:
```
CREATE TABLE `a` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `b` (
  `a_id` bigint(20) NOT NULL,
  `additional_field_1` varchar(50) DEFAULT NULL,
  `additional_field_2` int(11) DEFAULT NULL,
  PRIMARY KEY (`a_id`),
  CONSTRAINT `b_ibfk_1` FOREIGN KEY (`a_id`) REFERENCES `a` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
2. Add the database as a datasource in Budibase
3. Select "Define relationship" under "Relationships"
4. Select table "a" as from table
5. Select "id" column as Primary key
6. Select table "b" as to table
7. Open drop down menu for foreign key and see that the column "a_id" is missing

**Expected behavior**
I should be able to see and select any column from "b" table as foreign key.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Google Chrome Version 101.0.4951.64 (Official Build) (64-bit)

**Comment by palsivertsen** [comment]
Issue seems to be related to the fact that `b.a_id` is both a primary and foreign key at the same time.

**Comment by palsivertsen** [comment]
This is still an issue in version `1.0.195`

**Comment by palsivertsen** [comment]
Still an issue in `1.2.52`

**Comment by palsivertsen** [comment]
I suspect the `b.a_id` column is filtered out from the view since it's both a primary and foreign key.

**Comment by palsivertsen** [comment]
I can confirm this happens because `b.a_id` is both a primary and foreign key. I was able to get this working using the following schema:
```
CREATE TABLE `a` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `b` (
  `id` bigint(20) NOT NULL,
  `a_id` bigint(20) NOT NULL,
  `additional_field_1` varchar(50) DEFAULT NULL,
  `additional_field_2` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `a_id` (`a_id`),
  CONSTRAINT `b_ibfk_1` FOREIGN KEY (`a_id`) REFERENCES `a` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

@melohagan Any chance to get a fix on this for an upcoming version?

**Comment by melohagan** [comment]
Hey @palsivertsen 

The reason we currently don't allow for primary keys to double up as foreign keys is integral to how Budibase handles relationships at the moment. 
I've changed this from a bug to an enhancement, because this may involve a new approach to how relationships are handled.

**Comment by palsivertsen** [comment]
I see. Thanks for following up :laughing:
