### ISSUE TITLE
When I migrated the system successfully deployed from the external network to the internal network, some pages opened very slowly or even failed.

### ISSUE THREAD

**Issue by 8debug** [Budibase/budibase#6038]
When I migrated the system that was successfully deployed on the external network to the internal network, some pages opened very slowly or even failed. I see in the console of Chrome browser that some static resources need to be connected to the Internet to be loaded. Would you like to consider changing the reference method of these static resources to local references?

**Comment by mike12345567** [comment]
Hi @8debug I believe you are talking about this: https://github.com/Budibase/budibase/issues/3164 - the ability to run a Budibase self hosted system off of a network which does not have an internet connection, or has a slow internet connection, serving all required assets from the local system.

This is planned work but currently has not been given a set date on the roadmap.

Closing this issue as #3164 has more details on this.
