### ISSUE TITLE
[ ] around number returned by URL binding

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6045]
### Discussed in https://github.com/Budibase/budibase/discussions/6041

<div type='discussions-op-text'>

<sup>Originally posted by **timmehrees** May 24, 2022</sup>
Hi All,

I'm using the URL.id binding a fair bit when changing screens, saving data, etc etc. I've noticed that sometimes the URL comes up with /screenname/8 and other times /screenname/[8]

Weirdly, on some screens [8] returns the right record, on others, it doesn't. 

It seems that any of the automatically generated screens work with [8]. 

My current screen I am getting the "id" from has the ID in a form field (returned by an options menu). Is there a way to strip the [ ] from the returned value using handlebars or JS? (I'm not overly familiar with either, and have learnt a lot in the last 2 weeks of working on Budibase).

Thanks.</div>

I am also seeing this for autogenerated screen from external datasources (both MySQL and PostreSQL). 
In my case the URLs are encoded: 

![Screenshot 2022-05-24 at 14 23 16](https://user-images.githubusercontent.com/101575380/170045543-66f8da9f-11ee-4b98-be1c-567e50bf6075.png)

but replacing that with `3` also works fine.

**Comment by aptkingston** [comment]
I think this is because with SQL tables we generate an internal ID for the rows which is an array (as there may be multiple composite keys). This is then URL encoded when used in the URL. It should probably always be encoded, so maybe there are some places that we update the URL but don't encode it properly.
