### ISSUE TITLE
Calendar widget

### ISSUE THREAD

**Issue by PaulMcF1987** [Budibase/budibase#6053]
I was wondering if there was any plans to add a calendar widget/element.

Time keeping/scheduling are important elements for any business.

For example, I work in transport, having a table view helps me see the jobs but having a calendar view to easily see everything that is on for the day/week/month makes things a lot easier.

It would also allow me and others to manage meeting schedules etc all from the one app without the need to have multiple different apps

I feel a calendar widget would help give budibase the ability to create a one size fits all app

**Comment by PaulMcF1987** [comment]
Should I assume that there are no plans to introduce this?

**Comment by FabioKido** [comment]
> Should I assume that there are no plans to introduce this?

You did it?
