### ISSUE TITLE
User Profile UI Updates

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#6055]
**COS**
- Update the user profile screen to show the User Groups they are in and apps they have permission to view

**Designs**
https://xd.adobe.com/view/7132ee2a-8723-47cd-93c5-29e195449921-2461/

**Comment by MihailHadzhiev2022** [comment]
"Add all users"  is not working as expected
https://www.loom.com/share/e640d66df3f3477bafece4c284a925bf
