### ISSUE TITLE
Allow Filtering By User Group in App List

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#6056]
When I'm in the app list on the budibase app portal, I want to be able to filter the apps by the user groups that have access to them, so that I can filter down to apps that are more relevant to me.

**Example**
- Open app list
- Filter by marketing group
- Show only apps that the marketing group has been **directly** assigned access to. 

**COS**
- Add option to filter by user group (pro only)
- Once clicked, allow user to select user group
- Click on user group to filter

**Comment by NEOLPAR** [comment]
This part is done, it will go with user group PR
