### ISSUE TITLE
Invalid table column names

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#606]
It looks like there are some column names which are reserved for internal use by PouchDB which silently fail if you try to use them. However, they then show up under the schema for that particular model.

So far the illegal ones I've found are `type`, `_id` and `_rev`.

We should probably stop the user from using reserved names so that these don't get in to schemas.

To reproduce:

1. Create a column called `type`
2. Notice it submits but then doesn't actually get added to the table
3. Create a new workflow
4. Choose "Save record" action or anything else that uses a model schema
5. Notice that `type` is listed there and can be used

**Comment by mjashanks** [comment]
illegal ones are...
- Anything starting with a `_`
- type
- modelId

**Comment by aptkingston** [comment]
Great thanks for clarifying. Reckon it would probably be good to both reject these in the API and also do some front end validation so users know that they're illegal, even if `type` is the only one I can actually see people using. I actually tried to use `type` myself which is why I noticed this in the first place.
