### ISSUE TITLE
CRON automation continues after deletion

### ISSUE THREAD

**Issue by colingourlay** [Budibase/budibase#6073]
**Hosting**
- Self
  - Method: digital ocean
  - Budibase Version: 1.0.184
  - App Version: N/A

**Describe the bug**
I created a new app for the purposes of trying out the CRON automation trigger. I set up an hourly CRON which would send me an (empty) email. Once I did a test run (successfully receiving email), and waited til the next hour (successfully receiving email), I deleted the automation l, then deleted the app. However, I now still receive emails every hour, and there’s no way to stop them. 
A full server restart does not fix the issue.

**Comment by aptkingston** [comment]
I've tested this flow myself and the automation does stop triggering for me.
Just to clarify, was your flow:
- Delete automation
- Unpublish app
- Delete app

That's the exact flow that I've just tested and the automation does stop, so I'm wondering if your flow was any different to that.
