### ISSUE TITLE
Autogenerated Screens not functional for postgres tables not in public schema

### ISSUE THREAD

**Issue by C-HKH-Herbst** [Budibase/budibase#6083]
**Hosting**
- Cloud
  - Tenant ID: eatplanted

**Describe the bug**
As outlined in the title, the otherwise very useful autogenerate feature does not produce functional screens for postgres datasources not using public schema.

Replacing the autogenerated datasources with custom queries leads to tables and forms being displayed correctly, insert/updates however do not work.

Attempting to use the New Row page save button yields "error: relation "yadayada" does not exist". It seems like the autogenerated screens do not adapt the insert/update queries to the schema specified in the datasource setup.

**To Reproduce**
1. Connect to any postgres database with tables in non-public schema
2. Point the datasource to that schema
3. Autogenerate screen for any table in said schema
4. Autogenerated screen is not functional, as described above

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 99

**Additional context**

**Comment by NEOLPAR** [comment]
Unfortunately, we have not been able to reproduce the bug. If you can still recreate this, could you please provide a few more details such as: 
1. table schema
2. further reproduction steps

And please re-open this issue to make us aware of the new reproduction steps.
Thanks!
