### ISSUE TITLE
Attachments cause row not to be displayed in a table.

### ISSUE THREAD

**Issue by magickaito** [Budibase/budibase#6085]
**Hosting**

- Cloud
  - Tenant ID: tplus

**Describe the bug**
My app is stuck in an error state. For any tables, rows with image attachments will be hidden. 
I noticed this issue was raised before but closed without a fix: https://github.com/Budibase/budibase/issues/2892

**To Reproduce**
Unfortunately I cannot reproduce this in a new app, but it is happening in my existing app. 
So to reproduce, I stripped down my app to a bare minimum, removed all tables, all automation, all screen, I can still see the problem. You can simply import this minimal app to see the problem:

1. Create new app and import the attached text file. 
2. Check out the "Debug" table. You will only see 1 row. 
3. Click export to CSV, you will see 3 rows exported in csv. 2 hidden rows with image attachments.
4. Add new rows with image attachment, they will be hidden
5. Add new rows without image attachment, they will show up properly
6. Create new table, and it will be the same. 

[Debug Attachment Row-export-1653646675008.txt](https://github.com/Budibase/budibase/files/8785936/Debug.Attachment.Row-export-1653646675008.txt)

**Expected behavior**
Table rows with image attachment should be showing 

**Screenshots**
![Screenshot 2022-05-27 at 6 25 13 PM](https://user-images.githubusercontent.com/1195573/170682360-68eeb5fd-36ff-4ac6-87fd-547825606fe6.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.3.1
 - Browser: Chrome
 - Version: Version 101.0.4951.64 (Official Build) (x86_64)

**Comment by melohagan** [comment]
Hey @magickaito 

Apologies for the late response, but this is actually an issue with couchdb conflicts in that app export!

Please follow this guide: https://github.com/Budibase/budibase/discussions/7777#discussioncomment-3732390

You may also need to open the port on the couchdb service in the docker-compose file: 
<img width="239" alt="Screenshot 2022-10-28 at 08 42 46" src="https://user-images.githubusercontent.com/101575380/198532185-0d8f8e13-2f2c-42a7-a304-de8a49e1c700.png">

![Screenshot 2022-10-28 at 08 43 31](https://user-images.githubusercontent.com/101575380/198532350-87270f38-da74-4d83-97fb-d49e1696e8a8.png)

**Rows with attachments are now appearing**
![Screenshot 2022-10-28 at 08 44 13](https://user-images.githubusercontent.com/101575380/198532493-aac1dfab-71d4-4d49-85df-afc17f69162a.png)
