### ISSUE TITLE
REST API  Nested Pagination Params

### ISSUE THREAD

**Issue by Kanary159357** [Budibase/budibase#6105]
**Describe the feature request**
A clear and concise description of what the feature request.

I have rest query that contains pagination params like this
```
{ id: "",
  data : "",
  page:{
    next_token: "asfasfasfasfasf"
    limit  : 10
  }
}
```

Currently, Budibase just append the property to request body, so I could not use pagination with Budibase REST API Query..

I hope if I allocated page.limit, page.next_token to Request cursor parameter name,Request limit parameter name, It automatically wrap this as object

Metadata, or page informations often format of object, so it would be great...
 
<img width="991" alt="image" src="https://user-images.githubusercontent.com/69702813/170905727-18ccdc94-aba0-4d99-a4e7-a23e9f27c2b0.png">

**Comment by melohagan** [comment]
This had been fixed: https://github.com/Budibase/budibase/issues/5066

If the issue persists, I'd need to see both the request and response bodies, as well as the transformer.
In addition, it is not clear in the issue what is being requested.
