### ISSUE TITLE
Filter an internal table's view

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6108]
### Discussed in https://github.com/Budibase/budibase/discussions/6104

<div type='discussions-op-text'>

<sup>Originally posted by **pierreminik** May 30, 2022</sup>
Hi,

I have a table where a column is an option type with three possible values, along with some meta data fields.
I need a display a Pie Chart that shows the distribution of those values, and I need some filters that allow exploring how these three values are distributed in combination of the meta data fields.

## Data

I've created a view on the table that calculates a count on the option type column and enabled `Group by` on the values. I now correctly see how the three values are distributed.

## Design

In the design, I've added the table's view as a data provider and the pie chart is shown as expected.

Now I'd like to add a filter button which filter's the original table and shows the view's calculation results. I'm only allowed to filter the view.

![Screenshot 2022-05-29 at 23 15 23](https://user-images.githubusercontent.com/614588/170900670-e422ceac-0324-4521-9e63-8f5ef7daf5dd.png)

Is this possible somehow?</div>

So from my understanding, you can filter the data that goes into a view, but there's no way to pass in a binding. If you could pass a binding into the filter view then this would be possible?

![Screenshot 2022-05-30 at 11 03 27](https://user-images.githubusercontent.com/101575380/170969269-65804eb7-e41b-4de5-b9b4-08a81c669190.png)

**Comment by andyburgessmd** [comment]
I'd find this feature really useful too. I'd be happy if the filter could be applied within the data layer. I have a view that has a count and group on the date field of the table but I would like to filter to only see the dates that are more than todays date. There is a date selector on the filter but there is no way to dynamically set it, i.e. use handlebars of JS to set the date as today.
