### ISSUE TITLE
Need to duplicate empty form field / form group on button click in budibase

### ISSUE THREAD

**Issue by gauravpay3ds** [Budibase/budibase#6110]
Hi Budis,

I am trying to  duplicate the existing form field in the next row on button click.
But not able to get the clue . can some help on this ?

something like this 
![image](https://user-images.githubusercontent.com/106397756/170982195-1300fcca-ab4a-4132-8c63-f8d99a17e971.png)

 
user click on the add row and above complete row should get cloned/duplicate added so user can add the value.
Also delete button should get delete the row.

is it possible in budibase?

**Comment by melohagan** [comment]
Requested here as well: https://github.com/Budibase/budibase/issues/5658
