### ISSUE TITLE
Cannot export db data as CSV or JSON 

### ISSUE THREAD

**Issue by purplepatrick** [Budibase/budibase#6112]
**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
selecting db row and pressing export and format will generate an error "Unable to export csv/json data"

**To Reproduce**
1. Go to db
2. Click on row checkbox and select export and select format
4. "Unable to export csv/json data"

**Expected behavior**
Export working

**Screenshots**
https://tinyurl.com/2okatd9l

**Desktop (please complete the following information):**
<html>
<body>

Vivaldi | 5.2.2623.48 (Stable channel) (64-bit)
-- | --
Revision | 80d94afbd301a973f33b94e8c76a22a33ed078c7
OS | Windows 10 Version 21H1 (Build 19043.1706)
JavaScript | V8 10.0.139.17
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.162 Safari/537.36

</body>
</html>

**Additional context**

**Comment by aptkingston** [comment]
Looks like this might also be fixed by https://app.zenhub.com/workspaces/budibase-product-5fd773eeaec59f001117ad65/issues/budibase/budibase/6354,
 assuming this is also an external SQL DB.

**Comment by purplepatrick** [comment]
It's still happening. 
- Self-hosted
- PostgreSQL

**Comment by aptkingston** [comment]
Hi @purplepatrick. The fix was merged but it hasn't been deployed yet - it will be included in the next release.

**Comment by purplepatrick** [comment]
Ah, sorry. Didn't see that. Thanks!
