### ISSUE TITLE
Filtering of Data

### ISSUE THREAD

**Issue by PaulMcF1987** [Budibase/budibase#6119]
I am trying to filter data shown in a table.

I have tried multiple different approached but with no joy.

I have 5 job statuses - `Job Not Completed` `Completed` `Archived` `Sourcing` `Quoted` 

I am trying to display data on the table which has `no job number` and can be have only statuses `Job Not Completed` or `Completed`.

I tried filtering
`JobNumber is Empty`
`JobStatus Not Equals Quoted`
`JobStatus Not Equals Archived`
`JobStatus Not Equals Sourcing`
![image](https://user-images.githubusercontent.com/75368133/171051555-ecfaf1a4-e09f-4bae-8c54-43cbf4ab2c37.png)

As you can see from the picture below it gives me an `Archived` entry
![image](https://user-images.githubusercontent.com/75368133/171051631-a59283af-f729-44eb-9b81-c1e6dfdcd792.png)

I also tried filtering
`JobNumber is Empty`
`JobStatus  Equals Job Not completed`
`JobStatus  Equals Completed`

![image](https://user-images.githubusercontent.com/75368133/171051777-23005bcc-0ecc-4140-8bae-efcc19365bcc.png)

But this time the table only returns `Job Not Completed` entries

![image](https://user-images.githubusercontent.com/75368133/171051879-2b8b0d22-c4ba-4cc9-b7e4-a87ce41e3c6b.png)

I have tried multiple different filters including, filtering via the data provider and using `table block` and adding another layer of filtering, still with no joy.

I used an SQL query
`SELECT * FROM JobRecord
WHERE JobNumber is null AND JobStatus != 'Archived' AND JobStatus != 'Sourcing' AND JobStatus != 'Quoted'`

This gives me the results I am looking for, however when I view the record some of the information is missing as it does not show any of the `relationship` columns

Is there something obvious that I am missing? Or is there an error somewhere?

I feel as though the filters should offer conditions as the filter states ``Results are filtered to only those which match **all** of the following constraints.
Is there a way to add in `AND` `OR` statements without a query? as if I use a Query I will end up again in the position where relationship columns are not shown

**Comment by shogunpurple** [comment]
Hi @PaulMcF1987 - this one is a manifestation of this bug: 

https://github.com/Budibase/budibase/issues/2585

Due to how filters are stored, filters on the same key override each other. We do plan to resolve this one but it requires quite a bit of restructuring as to how filtering works, so it hasn't been done yet. I can't give you an exact timeline but it will be over the next month or two.

**Comment by shogunpurple** [comment]
Closing in favour of https://github.com/Budibase/budibase/issues/2585

**Comment by PaulMcF1987** [comment]
@shogunpurple is there a current work around?

**Comment by krissydt2** [comment]
I am experiencing the same issue... it has been about 2 months since this was first posted, so is there a timeline on when this issue will be resolved?
