### ISSUE TITLE
Document Update Conflict - Internal DB - Static Formulas

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#6124]
I have 2 tables with a relationship in between and static formulas in both. I'll call them parent and child. 

Having a static formula field on child makes saving parent rows impossible. Always errors with update conflict. Same behavior in data tab and my app itself. 

Converting the formula field on child to a dynamic one removes the problem but i need it to be static. 

Is this a bug? Any ideas on how can i make it work? 

Using latest version as of today,

**Comment by aderici** [comment]
More diagnostic info : the problem only occurs when child table has 2 static formula fields and only happens when you try to update a parent row. If you change one of the static formulas to dynamic, leaving only one static formula column problem goes away

**Comment by yeoldegrove** [comment]
I have the very same issue as @aderici described. As soon as I get rid of the multiple static formulas columns, the update conflict is gone.
