### ISSUE TITLE
Pushing / Publishing applications from Local Dev to Live BB Server

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6131]
I have a local installation on my laptop for development purposes. 
A cool feature would be the ability to "Publish" my application to a Live BB installation / Cloud , instead of export / import.

**Comment by aderici** [comment]
Also automatically switching database / api details along the way (or getting them from environment variables automatically)

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/9126
