### ISSUE TITLE
global-info > tenants is prone to 409 conflicts 

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#6134]
**Hosting**
- cloud

**Describe the bug**
When concurrent accounts are created or deleted there is the possibility for the `tenants` document to receive conflicts. 

**To Reproduce**
- Create two accounts at the same time
- Delete two accounts at the same time
- Create and delete an account at the same time 

**Expected behavior**
- No errors

**Additional context**
The suggested fix here would be to use a document per tenant, and introduce a view for querying across all tenants similar to how users are queried by email. This introduces a nice place to store tenant wide information in future, e.g. the globally unique tenant id which is currently stored in the settings document

**Comment by mike12345567** [comment]
This issue cropped up during the conversion of the worker tests, as all creation of users happening nearly simultaneously - for some reason this wasn't an issue with PouchDB but is with real CouchDB (likely timing related). For now we have added a `env.isTest` wrap to the tenancy functionality as it doesn't affect testing until this issue can be rectified overall.
