### ISSUE TITLE
App options menu is tiny on CHrome

### ISSUE THREAD

**Issue by gondilon** [Budibase/budibase#6139]
**Hosting**

- Self
  - Method: docker compose
  - Budibase Version:  1.0.184
  - App Version: 1.0.184

**Describe the bug**
When there are three apps, the middle app's options menu does not display correctly. It displays very tiny where only one option is visible.
The menus display correctly on Firefox, so this appears to be Chrome specific.

**To Reproduce**
1. Create 3 apps
2. Click on '...' next to the middle app.

**Expected behavior**
Options menu should display the same as other apps.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: chrome
 - Version 101.0.4951.67

**Comment by mslourens** [comment]
Could you add a screenshot, because I don't see the issue:
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/1907152/171874442-b5526a4b-35d4-4f74-a8d9-d0fdec932842.png">
