### ISSUE TITLE
long form field wrapping issue

### ISSUE THREAD

**Issue by samg666** [Budibase/budibase#6150]
Hello,

I just found that if I input multiple line text on the `long form field`, the value stored on MySQL will be something like `line1\nline2\nline3`, but when I read from the MySQL and bind to the `long form field`, it will not convert to `\n` as new line, but all show as single line plaint text `line1\nline2\nline3`. I have tried change the `long form field` formatting to `Auto/Plain text/Rich text`, all shows the same  single line plaint text. Is this a bug, or something I was doing wrong?

### The text I have input on the `long form field`
![image](https://user-images.githubusercontent.com/29649651/171326946-3b2e410b-b1cb-464c-957b-fffa6b2794c7.png)

### The text read from MySQL
![image](https://user-images.githubusercontent.com/29649651/171326996-186877a5-8e73-40f5-9bb4-212e9414f083.png)

**Comment by ggs331** [comment]
@melohagan Can you help to take a look on this issue?

**Comment by ggs331** [comment]
Thank you @melohagan , hope this issue can be fixed soon.

**Comment by melohagan** [comment]
Okay, I've had a closer look at this. I do not believe there is a bug here.

Tested on version 1.0.198, and using MySQL.

**SQL**: `UPDATE sys.Costs SET cost_varchar = 'line1\nline2' WHERE idCosts = 11;`
**Result**:
<img width="224" alt="Screenshot 2022-06-08 at 16 18 45" src="https://user-images.githubusercontent.com/101575380/172654114-b03f1292-29a1-4888-9773-a2cc2fa4dd93.png">
![Screenshot 2022-06-08 at 16 19 46](https://user-images.githubusercontent.com/101575380/172654334-9804158b-e27e-463e-8c23-3f6381e55e3d.png)
![Screenshot 2022-06-08 at 16 20 26](https://user-images.githubusercontent.com/101575380/172654491-5c7ef9cb-e069-4416-91a2-9da599579c00.png)

In your case, if you are seeing `line1\nline2\nline3` in your SQL table, that means you've not saved the newline character. Instead you have saved the escaped version, e.g.
<img width="217" alt="Screenshot 2022-06-08 at 16 22 27" src="https://user-images.githubusercontent.com/101575380/172654989-9a7b4680-812c-4dd2-95ba-b9fbe533de5c.png">
![Screenshot 2022-06-08 at 16 22 56](https://user-images.githubusercontent.com/101575380/172655118-0ca9bc93-e10e-4803-9226-5b673a4f96d9.png)

**This is correct behaviour.**

The phrase "\n" is not markdown. With this said, it appears that markdown for adding a newline such as `<br />` `\` and `&nbsp;` is not working. In my opinion this is the bug.

**Comment by ggs331** [comment]
@melohagan I have just find something on this issue, if I use `Save Row` action to update MySQL, the wrapping works just fine, I can see the MySQL logs is somthing like` insert into tbl_logs (LogDetail) values ('LINE1\nLINE2\nLINE3')`, but if I use `Execute Query` action, what I saw on the MySQL query logs is something like ` insert into tbl_logs (LogDetail) values (concat('', 'LINE1\\nLINE2\\nLINE3', ''))`, the Budibase has added additional slash `\` which make the wrapping not working when binding back to the long form text field.

**Comment by melohagan** [comment]
Brilliant catch @ggs331 - this should definitely be made to be consistent.

**Comment by ggs331** [comment]
I have just use the wordaround is use Javascript to replace `\\n` with `\n` when binding back to the `Long Form Field`, the code is something like `return $("Repeater.FetchServiceDetails.Remark").replaceAll('\\n', '\n')`, then the wrapping can correctly show on the  `Long Form Field`.

@melohagan Please kindly let me know when this issue has been fixed. Thanks.

**Comment by v3ss0n** [comment]
Any update on this? this totally ruin nocode aspect , since i always need to write javascript for any form bindings ,
