### ISSUE TITLE
Table displaying key columns

### ISSUE THREAD

**Issue by hardc0l2e** [Budibase/budibase#6151]
Is is possible to display the key column from another table to look like a normal column? without the gray box on white text?
![image](https://user-images.githubusercontent.com/1472421/171330306-62daddaf-24e6-46de-b360-ca63a70bca88.png)

**Comment by melohagan** [comment]
Hey @hardc0l2e 

Just happened to stumble upon this issue.

You can do this by adding in a [Formula](https://docs.budibase.com/docs/formula) column like so:


![Screenshot 2023-02-15 at 14 57 22](https://user-images.githubusercontent.com/101575380/219063689-c956e199-b91f-4097-8f9f-a8b4d81a9f1f.png)

![Screenshot 2023-02-15 at 14 57 34](https://user-images.githubusercontent.com/101575380/219063744-535c8b71-c73f-4a00-a7ea-39cf04b2c4e5.png)

In the **Design** section, `Add all columns`. And click the `x` to remove the relationship column.

![Screenshot 2023-02-15 at 14 59 00](https://user-images.githubusercontent.com/101575380/219064150-d85701d3-3904-4fb9-9919-df7fdf4631f8.png)
