### ISSUE TITLE
Budibase DB - Users is loading and nothing is happening

### ISSUE THREAD

**Issue by ctellechea2001** [Budibase/budibase#6168]
Dears,
          We implemented the budibase in Kubernetes based on your chart. (
https://github.com/Budibase/budibase/tree/77d7a5ed70d84bd4171038af37d5abbc7310fc52/charts/budibase)

We have a specific issue related to the Section Budibase DB - Users. When you clic on that hangs loading and after a few minutes the message "Now let's add a row" is showing. In a local enviroment in docker in this part is showing a user.

Could you help us?

Thanks!!

![image](https://user-images.githubusercontent.com/45426180/171493455-a1473981-30b1-423d-886a-59d147af8b4a.png)

After 3 minutes!!

![image](https://user-images.githubusercontent.com/45426180/171493245-d73fd736-0a25-47e5-8461-b3a679e1b393.png)

**Comment by little-liang** [comment]
i have a same problem

**Comment by shogunpurple** [comment]
Hi @ctellechea2001 and @little-liang, 

When you say "based on our chart", do you mean that you edited the chart before deploying? What changes did you make?

Also useful would be to know:
- Which kubernetes provider you are using (EKS, K3S, etc)
- which kubernetes version you are using

In that case I should be able to reproduce the issue. I am unable to reproduce this in any of my existing K8S environments, with the latest helm chart deployed from scratch. 

Thanks!

**Comment by ctellechea2001** [comment]
@shogunpurple How are you?? It is the lastest chart.

do you mean that you edited the chart before deploying? **No, it is the same chart with default configurations and values.**

    Which kubernetes provider you are using (EKS, K3S, etc): **EKS**
    which kubernetes version you are using: **1.20**

We can help you with the following information that happens in the error time.

![imagen](https://user-images.githubusercontent.com/45426180/172161855-0ef63336-da81-4253-b1d6-472c80eabfe4.png)

![imagen](https://user-images.githubusercontent.com/45426180/172163883-7255b7f4-7abb-4f70-a43f-7eb619bf01df.png)

**Comment by shogunpurple** [comment]
@ctellechea2001 please don't tag maintainers directly and poke for updates - we reply to discussions as soon as we can. There's no update yet - I will need to run this on a K8S cluster to mirror yours, as I cannot seem to reproduce.  Thanks

**Comment by ctellechea2001** [comment]
sorry, Thanks for your help!!

**Comment by infnada** [comment]
Same issue here (EKS 1.21). We've detected errors in the couchdb pods as soon as we navigate to the users page.

main couchdb container:
![image](https://user-images.githubusercontent.com/6633771/173045343-c261784d-0247-4c29-81e8-b7f8785212d6.png)

couseau container:
![image](https://user-images.githubusercontent.com/6633771/173045593-1b903359-2a00-458a-bb4c-364faca15018.png)

**Comment by thomasbergernz** [comment]
I'm interested in more details on how to "downgrade version of couchdb"!

**Comment by Rory-Powell** [comment]
Hi @thomasbergernz , in the above case this was achieved by changing the value here in the kubernetes charts
https://github.com/Budibase/budibase/pull/5651/files#diff-490204f647f3d37fa99f47934ee498517894b136f3adedb785be697bdb1c043bR218

For docker-compose installations the `couchdb-service` image would instead be changed to:
 ` image: ibmcom/couchdb3:3.1.0`
https://github.com/Budibase/budibase/blob/master/hosting/docker-compose.yaml
