### ISSUE TITLE
Field Value updated from Relationship Picker onChange - strange encoding

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6194]
### Discussed in https://github.com/Budibase/budibase/discussions/6176

<div type='discussions-op-text'>

<sup>Originally posted by **mmalessa80** June  2, 2022</sup>
In a form I have one relationship picker for the one side on a one-many and another picker for the many side on a many-many. I added a set value action on another field under the onChange event in an attempt to get the ID field, however the actual value that is entered into the field contains additional characters besides just the ID.

The underlined parts in the respective fields that get filled in are the IDs in this case, but as can be seen by the screen shot there are additional characters.

![image](https://user-images.githubusercontent.com/106758851/171692924-1ba2524b-6787-4ab2-a41d-0ead310d52e8.png)
</div>

**Comment by aptkingston** [comment]
That looks like full unicode encoding.

- `%5B` and `%5D` are the encoded values for `[` and `]`
- `&#x27;` is the unicode value for an apostrophe (a.k.a single quotes)

So for example `%5B&#x27;4339458d&#x27;%5D` is just `['4339458d']` encoded. The value `['4339458d']` is how we represent IDs for rows pulled from SQL tables. That full array value should never make its way to the SQL table though, as it's an internal Budibase concept only. 

I worry that what has happened here is that the internal Budibase row ID (these array values) have been used in an external query or automation and have actually been saved into the external SQL table. In doing so, it looks like they've gone through full unicode encoding.

**Comment by melohagan** [comment]
Re-opening as there was another related discussion here: https://github.com/Budibase/budibase/discussions/7687

In this case the user was having issues with the default value. You should be able to provide numbers and Budibase should do the encoding if needed.

**Comment by hydroxy** [comment]
I too am looking for a solution to this. I am trying to save the row ID for the previous action (  {{ Action 2.Saved row._id }}  )
![image](https://user-images.githubusercontent.com/6318064/193602305-11f19b96-2cf1-4bb0-8c59-cac560abe553.png)

However whenever I output it to my database it comes out not as the row number but instead as something like this, %5B2158%5D. I have figured out that this is the URI encoding for the string [2158]

![image](https://user-images.githubusercontent.com/6318064/193602603-d4ad4f63-534e-4840-8e3a-1b7d8509015e.png)

Is there an easy way to just output the integer 2158, I've tried to use handlebars URI decoding but I am new at chaining handlebars commands so I have not had any luck.  Any help is appreciated.

**Comment by aptkingston** [comment]
@hydroxy the `_id` property coming back from that response is the Budibase internal ID for referencing your row - you shouldn't need to ever use this manually, and you definitely don't want to insert this into your SQL table. Can you reference the ID from the saved row response based on whatever your actual ID column name is?

**Comment by hydroxy** [comment]
I am looking to create a row in the process table it's ID will be processID, then create another row in processFertilize table. The process table will be super-table and processFertilize will be sub-table.

What would be the best way to do that? I am using a mySQL database to store the information also.

**Comment by melohagan** [comment]
Related encoding issue here, but with execute query: https://github.com/Budibase/budibase/discussions/8087

**Comment by hydroxy** [comment]
Excellent, that resolved it for me. I was trying with the javascript but couldn't quite get the exact syntax right. Much appreciated :)

**Comment by aptkingston** [comment]
The solution here is just to use whatever your ID columns are. If you want the `processID` to save in the `processFertilize` table, then use `Action 1.Saved row.processID`, not our internal `_id` column. There should never be a need to save the Budibase `_id` column anywhere, so there should never be a need to need to decode it. It's only for our internal reference.

Unless I'm missing something here, there is no work to be done. Maybe we just need to update the docs to make it more clear to not use our `_id` column. We could potentially just not generate the `_id` bindings for rows in SQL databases, which would hopefully discourage people from using it.

**Comment by shogunpurple** [comment]
We've added a fetch row action that should help to address this issue - it will be available in the next release in 2 weeks. Thanks!

**Comment by dipak1116** [comment]
@melohagan  how I can bind the field values of form by selecting option picker value
