### ISSUE TITLE
The selected Multi Select is not cleaned if in form 2 "Multi Select"

### ISSUE THREAD

**Issue by Pasha49** [Budibase/budibase#6196]
**Hosting**

- Self
  - Method: cloud
  - Budibase Version:  1.0.105 
- Cloud
  - https://hiveonfw.budibase.app/app/testbug

**Describe the bug**
The selected Multi Select is not cleaned if in form 2 "Multi Select"

**To Reproduce**
1. Add multiselect from base
2. Add multiselect from custom
3. Add Headline for check checkbox value (`{{ New Form.Fields.multiselect }}`)
4. Publish
5. Select 2 flags
6. Remove the selection from 2 flags

**Expected behavior**
The flags must be removed, the value should be cleaned.
But the value is not cleaned

**Screenshots**
![Peek 2022-06-06 18-13](https://user-images.githubusercontent.com/17119725/172190468-229ffca1-2378-45e1-92c7-022c2efab681.gif)
![2022-06-06_18-15](https://user-images.githubusercontent.com/17119725/172190445-314d40e4-6e03-4d9b-b370-e9401194b950.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 101

**Comment by GRSARVESH** [comment]
Did you find a fix for it?
