### ISSUE TITLE
Support deployment via podman

### ISSUE THREAD

**Issue by er2** [Budibase/budibase#6200]
**Hosting**
Locally on Arch Linux with Podman compose

**Describe the bug**
I followed these instructions: https://docs.budibase.com/docs/docker-compose and used the two files mentioned without any edits.

**To Reproduce**
1. Download `docker-compose.yaml` and `.env` to a new empty directory
2. In that directory run `podman-compose up`
3. Wait a bit for it to look like it's done setting up
4. Visit localhost:10000
5. See nice looking 502 error page, nothing of note in browser dev tools console

**Expected behavior**
See start page

**Desktop (please complete the following information):**
 - OS: Arch Linux `5.18.1-arch1-1`
 - Browser: firefox
 - podman version: 4.1.0
 - podman-composer version  1.0.3

**Additional context**
stdout and stderr attached. Comes from running it a second time after doing `podman-compose down` and `up` again.
[err.log](https://github.com/Budibase/budibase/files/8846394/err.log)

**Comment by aptkingston** [comment]
Looking at the logs, it looks very much like it's a podman specific issue. DNS resolution is failing when attempting to reach the localhost loopback resolver on `127.0.0.11:53`. I haven't used podman myself, but I would guess that its network setup is slightly different and does not expose a localhost loopback resolver the same way that docker does.

We don't officially support running via podman so we can't consider this a bug - but I'll leave it open as a feature request to support running via podman.

**Comment by aptkingston** [comment]
You could try updating `scripts/proxy/generateProxyConfig.js` and updating the `resolver` property of the `compose` config, then running a `yarn run build:docker:proxy` to build a custom proxy image with whatever resolver podman supports. I appreciate it's a few extra steps, but if you'd like to get up and running with podman quickly then that might be best option.

**Comment by jonnymccullagh** [comment]
Just responding to this issue now as we have been able to test running the latest budibase image using podman. Tested on Debian 11 and AlmaLinux. After installing podman (apt install podman || dnf install podman) 

```
mkdir -p ~/budibasedata
podman run -p 7764:80 -v ~/budibasedata:/data -e INTERNAL_API_KEY=abcd123 -e JWT_SECRET=abcd321 -e MINIO_ROOT_USER=miniouser -e MINIO_ROOT_PASSWORD=Install@123 -e REDIS_PASSWORD=abcd1212 -e COUCHDB_USER=couchuser -e COUCHDB_PASSWORD=Install@123 --name budibase -d docker.io/budibase/budibase:latest
```

For building the image from the Dockerfile this was also successfully tested with podman as described [here](https://github.com/Budibase/budibase/tree/develop/hosting/single)

@er2 are you ok for us to resolve this issue?

**Comment by er2** [comment]
That works brilliantly, thanks!
