### ISSUE TITLE
Field options missing when using query as form schema

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6238]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.198
  - App Version: 1.0.198

**Describe the bug**
When using a MySQL query as a form schema, the form field is missing dropdown options.

**To Reproduce**
1. Add a simple MySQL query that returns text fields in the schema
2. Add a form with that query as the schema
3. Add a Text Field -> There are no options in the dropdown.

**Expected behavior**
External DB queries should be usable as form schemas.

**Screenshots**
![Screenshot 2022-06-08 at 15 52 49](https://user-images.githubusercontent.com/101575380/172648043-4a2f2d5a-9cbd-4a83-be72-b9d9c3097b1c.png)

![Screenshot 2022-06-08 at 15 53 04](https://user-images.githubusercontent.com/101575380/172648116-7acb5535-c823-489a-9988-33baec3ad40a.png)

![Screenshot 2022-06-08 at 15 53 29](https://user-images.githubusercontent.com/101575380/172648219-d76d544d-5e1a-4c69-a6cc-6c0e81f6a1b0.png)

**Additional context**
Discussed here: https://github.com/Budibase/budibase/discussions/6197#discussioncomment-2900848

**Comment by aptkingston** [comment]
Think this was discussed recently... but basically this isn't a bug but by design. Using a custom query as a form will make the parameters available as field bindings, rather than the schema. This is because there's no point in using the schema as fields in a form, because you can't do anything with them - whereas the parameters are the values that can actually be submitted and used.

There's probably a use case for making a type of form called "read only" which would allow you to use the schema bindings just so that you could display the result of a custom query in a form, if someone needed to do that.

**Comment by JayP718** [comment]
@aptkingston I might not be fully understanding but I think it might be a good idea to clarify this in the documentation. The documentation states "Forms have a Schema setting which is optional. The schema for a form can be a table, view, relationship, query or "custom", this confused us a bit but perhaps we were interpreting it the wrong way.

**Comment by aptkingston** [comment]
Hey @JayP718. Yea you're right - we should clarify that better in the docs. Custom queries are handled differently than everything else so we need to reflect that.

**Comment by melohagan** [comment]
I've added a sentence to the docs: https://docs.budibase.com/docs/forms#form-schema

I think it may be worth removing the option to select REST queries as a form schema altogether.
It's a weigh up between how useful being able to select the query bindings as field names is versus user confusion.

**Comment by melohagan** [comment]
Related discussion: https://github.com/Budibase/budibase/discussions/7492

**Comment by melohagan** [comment]
Related discussion: https://github.com/Budibase/budibase/discussions/9720

**Comment by tavrez** [comment]
Sorry but I got confused reading all the answer and related issues. So I can't populate a form when I'm using custom queries in anyway? If no then how can I create a basic update query?

**Comment by tavrez** [comment]
To update my previous comment, I've used a data provider, a repeater inside that, and a form inside that repeater with custom Schema, the fields inside the form won't get prepopulated even when I manualy specify their Field, which is documented, but weird. I think it should be able to iterate over fields returned by repeater and prefill all the form values, isn't that possible?

I also did something funny which made it work, I created a table inside budibase built-in db with the fields being same as the fields in my custom query but without any data in it, and I used that as the schema of my form, and fields get prefilled :D

**Comment by aptkingston** [comment]
> To update my previous comment, I've used a data provider, a repeater inside that, and a form inside that repeater with custom Schema, the fields inside the form won't get prepopulated even when I manualy specify their Field, which is documented, but weird. I think it should be able to iterate over fields returned by repeater and prefill all the form values, isn't that possible? Or maybe when we select custom as schema, we should be able to select fields in a dialog or something like that(specifying the fields in custom schema mode)
> 
> I also did something funny which made it work, I created a table inside budibase built-in db with the fields being same as the fields in my custom query but without any data in it, and I used that as the schema of my form, and fields get prefilled :D

You can do this - but you just need to bind your form fields to your query params, as they are the only things that accept input values. You can use default values if you want to pre-populate your fields with values from your query results.
