### ISSUE TITLE
Cards - Make full component clickable 

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#6244]
When using cards, I expect the full card to be clickable when I have added a link. In adobe spectrum it also suggests that the full card is clickable.

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/88fdcaf5-53c6-4eb2-bbdc-aef3cc8fadb3)

**Comment by Shadowfita** [comment]
Yes please.
