### ISSUE TITLE
Break line for Label in Forms

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6249]
### Discussed in https://github.com/Budibase/budibase/discussions/6245

<div type='discussions-op-text'>

<sup>Originally posted by **kasgithub8** June  9, 2022</sup>
Hey,

is there any way to insert a break line for labels in forms?
Problem is if you have some words that need to be in the label, 
it doesn't look good because its just stretching every other form with it.

Thanks!

PS: \n & br don't work</div>

**For Example**
![Screenshot 2022-06-09 at 11 49 21](https://user-images.githubusercontent.com/101575380/172830031-6c730f51-e060-453e-bf05-e4f35cf946b5.png)

I was able to use an embed to style this, but there should probably be some automatic wrapping or easier way to handle this.

**Comment by marian001** [comment]
+1
