### ISSUE TITLE
Allow collapsing currently opened screen on designers left menu

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#6259]
As screens get complex, there are a lot of components and left menu gets quite messy. System does not allow users to collapse the mess because currently open screen cannot be collapsed now. This is extremely annoying because i would collapse current screen, find the other screen i'd like to go next and click to open id. Would be nice to have this is possibe or is there another way to browse through screens today

**Comment by aptkingston** [comment]
Hey @aderici. We've actually redesigned a lot of the design interface, and we're currently beta testing it. It will solve this issue and make everything much easier to use. You can see some pictures in the PR: https://github.com/Budibase/budibase/pull/6046.

It will be released over the next couple of months. I'll close this issue off as we aren't going to make any significant design changes to the current interface, but the new interface should definitely solve your problem.
