### ISSUE TITLE
HELP PLEASE. I MIGRATED AZURACAST FROM ANSIBLE TO DOCKER

### ISSUE THREAD

**Issue by JCBP1974** [Budibase/budibase#6276]
Please help!

I migrated my Azuracast account from Ansible to Docker but now I can no longer access it with the server link.
What I can do?

**Comment by JCBP1974** [comment]
Please help me. 
I can not access using ip link. 
I tried typing: 
./docker,sh azuracast:account:set-administrator [email address]

But appear this message:

-bash: ./docker,sh: No such file or directory

**Comment by mike12345567** [comment]
Hi @JCBP1974 - I'm closing this issue as I don't see how this relates to Budibase, if this does relate then please provide us with more information about what we can do to help with Budibase as we have nothing to do with Azuracast.
