### ISSUE TITLE
csv export table/view doesn't include relationship columns

### ISSUE THREAD

**Issue by HeronCS** [Budibase/budibase#6279]
**Hosting**
- Cloud
  - Tenant ID: I'd rather not disclose

**Describe the bug**
csv export table/view doesn't include relationship columns

**To Reproduce**
csv export any table/view with a relationship column

**Expected behavior**
to have all data included in csv export

**Comment by Shadowfita** [comment]
Bump. Primary display column of relationship would be ideal.

**Comment by NEOLPAR** [comment]
Unfortunately, I wasn't unable to replicate this issue. However, I fixed an issue where it wasn't possible to export a table from a datasource different than budibase in cloud mode.

If you could still experience this issue, could you please give us more details to replicate it? Thanks!
