### ISSUE TITLE
Default value of zero '0' for number field returns empty

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6284]
### Discussed in https://github.com/Budibase/budibase/discussions/6272

<div type='discussions-op-text'>

<sup>Originally posted by **thomaskamalakis** June 10, 2022</sup>
It seems that you can not set a default value equal to zero

So `return 1` works but `return 0` just leaves an empty value on the form field.</div>

---

`return 0` should display zero for a form field - at least the Number field anyway.

**Comment by Shadowfita** [comment]
What a coincidence, I've just noticed this issue! Haha.

**Comment by melohagan** [comment]
This appears to be fixed!

![Screenshot 2022-10-17 at 08 37 33](https://user-images.githubusercontent.com/101575380/196116795-ebc78ba0-c911-43f3-8c9a-8ae68c888c04.png)
![Screenshot 2022-10-17 at 08 37 49](https://user-images.githubusercontent.com/101575380/196116860-89f4d9f8-e9a9-427d-a641-3bbd5d85a125.png)

**Comment by NicolasFabre81** [comment]
Hello @melohagan , you show it works with the 1 but... problem was with the 0 and it remains.

**Comment by melohagan** [comment]
![Screenshot 2024-02-08 at 13 41 00](https://github.com/Budibase/budibase/assets/101575380/1bef06e7-d523-488a-b5e2-14028c40c353)

Lastest version...
