### ISSUE TITLE
Set Size ( Width / Height ) of an Element via Conditional UI

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6293]
Currently, you can set the Size to Grow / Shrink only
If we could set the width via conditional UI we could create nice Progress Bars for Multi Step Forms ( plus any other utilization )
I have currently implemented a progress bar via Show/Hide Conditionals on as many containers as steps.
This would be majorly simplified if I could set the Width property.

Keep on rocking!

**Comment by melohagan** [comment]
You can do this now with [Custom CSS bindings](https://docs.budibase.com/docs/custom-css#bindings)
