### ISSUE TITLE
Conditional UI is not working with Form Steps {{ Form.Current Step }}

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6295]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.196
  - App Version: 1.0.196

**Describe the bug**
Containers with backgrounds (gradient or just solid color) do not show on condition within app.

**To Reproduce**
1. Add a form with form steps
2. Add a container within the form, with three nested child containers
3. For each child container, set a background
4. For each child container, set a condition: `Show component IF {{ Form.Current Step }} 'More than' Number  1 | 2 | 3
5. See that for the Form Builder the behavior is correct
6. See that in the app itself, there are no containers with backgrounds regardless of which Form Step.

**Expected behavior**
The behaviour seen in the builder should replicate in the app. Conditional UI on Form Step bindings should work with containers.
In addition, the 'More than' is misleading. From the builder the behaviour is really **>=**

**Screenshots**
![formstep_conditional](https://user-images.githubusercontent.com/101575380/173371446-1c0523a7-0986-4f0b-9be0-8246c49fc625.gif)

**Comment by aptkingston** [comment]
It will depend on the parent contain settings - you can set the parent container to be a row and vertically stretch all children, which will have the desired effect here. It's just if you top/center/bottom align things and then add no children and add no height then it will be squished.

This would be more obvious too if there wasn't the placeholder component rendered for empty containers. But if the placeholder wasn't rendered, you could end up with a 0px sized container which is invisible and I think that would cause even more issues withg design haha.

**Comment by melohagan** [comment]
That makes sense. I think this case is unlikely to come up for users as well, because 99.9% of the time they'll be adding content to the container or setting a custom height anyway.
Just happened to catch me off guard in a test case and I jumped to the wrong conclusion.
