### ISSUE TITLE
Exists In / Doesn't Exist In Validation Rules for Form Fields

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6298]
A neat feature would be to have the option to add the Exists In / Doesn't Exist In Validation Rule to input fields.
This should Validate the input value against a list of value, static or dynamic (Data Provider Column)

<img width="1131" alt="Screenshot 2022-06-13 at 7 17 22 PM" src="https://user-images.githubusercontent.com/80512170/173399148-d6f6dd57-4fbc-41fe-ba0d-807ef17f573a.png">

**Comment by melohagan** [comment]
Hey @poirazis 

If you need to make sure that a value is within a set, could you not use an Options or Multi-select picker field? 
What's the use-case here?
