### ISSUE TITLE
App created from template cannot be viewed by basic user

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6308]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.199
  - App Version: 1.0.199
 
Also happening on cloud (bb.budibase.app) 

**Describe the bug**
Whenever I create an app from any template (Car Rental Admin Panel, Client Contact List, Invoice Approval Software) it cannot be viewed by a basic user

**To Reproduce**
1. Create app from template
2. Add non-dev, non-admin basic user
3. Add roles to the basic user - basic for the newly created app
4. Log in as the basic user - You do not have any apps

OR as an admin user, click **Close developer mode** after creating an app from template

**Expected behavior**
Basic users should be able to see apps created from templates.

**Screenshots**
![Screenshot 2022-06-14 at 15 37 54](https://user-images.githubusercontent.com/101575380/173604754-6430ff89-ec8e-4b0e-8e8b-86744e323982.png)

![Screenshot 2022-06-14 at 15 38 20](https://user-images.githubusercontent.com/101575380/173604852-88a8fb1a-e7b2-4f7e-9903-8fe8b7140e78.png)

**Comment by deanhannigan** [comment]
Hi @melohagan, thanks for the thorough steps! Could I ask you to confirm if the new template applications that you created had been published? Only published applications will appear in the list for basic users.
I ran through your steps and my basic user can see only published

**Comment by melohagan** [comment]
@deanhannigan Ah that's probably all it was then! I should add that into the docs then - closing!
