### ISSUE TITLE
Automation Looping handlebar cannot access to Column name have whitespace (ex: Auto ID)

### ISSUE THREAD

**Issue by xnohat** [Budibase/budibase#6318]
**Hosting**

- Self
  - Method: docker compose 
  - Budibase Version: 1.0.199 
  - App Version: 1.0.199 

**Describe the bug**
Automation Looping handlebar {{ loop.currentItem }} cannot access to Column Name have whitespace (ex: Auto ID)

Column Name without Whitespace

<img width="938" alt="image" src="https://user-images.githubusercontent.com/4613808/173654670-b25351ea-f0ff-428a-afae-dd9c7e66616f.png">

Column Name with Whitespace

<img width="949" alt="image" src="https://user-images.githubusercontent.com/4613808/173649508-beafc1f9-d1b9-4229-8eae-b3b2d64227e4.png">

**To Reproduce**
1. Create Automation
2. Create Query Rows block
3. Create Create New Rows block
4. Add Looping at Create New Rows block and bind steps.1.rows to loop
5. Setting create new row with data from {{ loop.currentItem._id }} and {{ loop.currentItem.Auto ID }} to compare return values

**Expected behavior**
get data from any columns

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome

**Comment by melohagan** [comment]
Hi @xnohat 

If you want to access a column that has whitespace in automation, you can do so as follows:
![Screenshot 2022-06-20 at 09 32 03](https://user-images.githubusercontent.com/101575380/174559872-be517403-5b6f-40e7-82c1-b441beb144ee.png)

I have also previously added this issue, so I'm going to close this one in favour of: https://github.com/Budibase/budibase/issues/5715
