### ISSUE TITLE
Validate the overall form, write freehand javascript

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#6322]
I have custom rules to validate a text entry field and i'm not sure if there's a way to apply it right now. Can i have a script box to write my custom javascript and return my custom error messages for validation? 

Forexample, what is the best way to implement "text field must contain 5 syllables" type of validation today*

**Comment by melohagan** [comment]
Hey @aderici 

Late reply, but you can do this by using the trick of returning the field value back to itself!

1. Configure validation on your text field
![Screenshot 2023-02-02 at 13 23 18](https://user-images.githubusercontent.com/101575380/216336594-5be0265a-2075-4f81-9715-22665a26005f.png)

2. Binding:
```js
function meetsCustomRequirement() {
	//TODO - implement
	return true
}
return meetsCustomRequirement() ? $("New Form.Fields.First Name") : false;
```
