### ISSUE TITLE
UI redesign: Allow user to select access for each nav link

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#6331]
In our current builder, users can create different layouts to create multiple navs so you can hide and show links depending on their permissions. 

With the new re-design and removing multiple layouts, we are effectively removing the ability to hide links from lower permission users. 

##Suggestion

Add conditions dropdown to each nav link so the user can choose the level of access required to view the link. 

This way they can have 1 navigation with conditional links. 

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/50cd0b86-693b-4a2d-a950-fa33b810da12)

**Comment by arladmin** [comment]
Hi. 
I find myself in the need for exactly this feature: Conditional Navigation links based on the user's access-level.
I've been unable to find any workaround for it so far.

Is the image shown above an upcoming UI? 
If yes, by when is this feature expected to be released?

Thanks.
