### ISSUE TITLE
CORS error in S3 File Upload - Non eu region

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6332]
### Discussed in https://github.com/Budibase/budibase/discussions/6324

<div type='discussions-op-text'>

<sup>Originally posted by **czarnndz** June 15, 2022</sup>
Budibase Cloud 1.0.199 

I'm trying to use a S3 File Upload component in Form, but I'm getting CORS error

![image](https://user-images.githubusercontent.com/7936586/173729642-3e208e1e-a268-4c3c-951a-1df7633854ff.png)

I set S3 Source without Endpoint, also I tried with and without Región but I saw that Request always use eu-west-1, maybe that could be the error idk.
![image](https://user-images.githubusercontent.com/7936586/173729751-3feb3cac-287c-43d8-bf80-9e7f25f3afaf.png)

This are the config I'm using
![image](https://user-images.githubusercontent.com/7936586/173730511-b15fbb20-f6e9-4f67-aa18-96a6028903d6.png)

And I'm using the "Upload File to S3" Action in "On change" event
![image](https://user-images.githubusercontent.com/7936586/173730642-96226f28-3e86-4b37-8ef2-238b84b7a24f.png)

The AWS User I'm using has administrator policy,
Below is the CORS bucket configuration in S3 I'm using

`[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT",
            "POST",
            "DELETE",
            "GET"
        ],
        "AllowedOrigins": [
            "https://hic.budibase.app"
        ],
        "ExposeHeaders": []
    },
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT",
            "POST",
            "DELETE",
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]`

Hope that someone can help me with this.

Thanks and Regards
</div>

**Comment by legaljustus** [comment]
Thanks for fixing this! 

I unfortunately still have the same problem on 1.2.52 with my bucket in eu-central-1
