### ISSUE TITLE
Can't change oidc callback url.

### ISSUE THREAD

**Issue by imcheck** [Budibase/budibase#6333]
**Hosting**

- Self
  - Method: k8s 
  - Budibase Version: 1.0.199 
  - App Version: 1.0.200 

**Describe the bug**
During setup oidc authentication method, the `Callback URL` input field is blocked with `readonly` option.
Let me know how to be able to edit the callback url.

**Expected behavior**
I want to edit the callback URL with my idp provider.

**Screenshots**
<img width="933" alt="image" src="https://user-images.githubusercontent.com/13193410/173821489-e4d7d554-1598-4a20-a459-073a0f5ad2ef.png">
<img width="841" alt="image" src="https://user-images.githubusercontent.com/13193410/173821612-b078786c-c433-4e7b-ae00-4483743ec05f.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by Rory-Powell** [comment]
Hey @imcheck, this is by design. If you mouse over the `Callback URL` field label there are instructions on how to change this, by updating the platform URL in organisation settings

**Comment by imcheck** [comment]
Thanks you @Rory-Powell ! It's resolved.
