### ISSUE TITLE
Drawer UI improvements (Bindings, Actions, Conditions) - Save button

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#6340]
At the moment we have a `cancel` and a `save` button for our drawers. 

Problem 1 is that the Save button is always active even when changes have not been made.

Problem 2 is that I see is that when you hit cancel, you don't get a warning saying you are going to scrap the work that you just did.

My expectation when working on a Budibase app is that my changes are going to be applied straight away but not published - like how they are in the settings panel. 

Even though the bindings, actions and conditions are in a separate UI, I still expect these changes to be saved and shouldn't require me to manually save.

## Suggestion

Rather than updating the save button and adding a warning modal. I think we could remove the cancel button and change save to `done`. 

This button will still act the same as save but there is now no way for a user to lose their work and any changes they have made that they don't want can be reversed in the UI itself. 

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/6fdd2db9-20ec-412f-841f-df228edcdeab)

**Comment by ConorWebb96** [comment]
Closing, its been done
