### ISSUE TITLE
'Table Pagination' disappears at the published site

### ISSUE THREAD

**Issue by TEAM-MAPA-DEV-REPO** [Budibase/budibase#6349]
**Hosting**

- Self
  - Method: <method> docker compose
  - Budibase Version: <version> 1.0.199
  - App Version: <version> client 1.0.200-alpha.3

**Describe the bug**
Table pagination works on Edit (Dev) mode, but after publishing, on published site, the table pagination disappears. We're using REST-API pagination

**Expected behavior**
Same pagination component should appear on both Edit, Published mode

**Screenshots**
Edit Mode
![image](https://user-images.githubusercontent.com/87367027/174042832-33203a85-fb1a-433c-a1db-53e2db50e6a8.png)

Published Site
![image](https://user-images.githubusercontent.com/87367027/174042538-3eae88f0-9487-4006-9f18-771b10d4b827.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Browser Chrome, Edge
 - Version 102.0.1245.30 (Official build) (x86_64) - Edge

**Comment by ladislavstefan** [comment]
We have a similar issue. REST API paging works well on dev mode but it stops working after publishing. Pagination is visible but inactive. 

There is a notice in the data provider  `Pagination is only available for data stored in tables.`. What's the correct pagination usage for REST API resources?

Budibase version: 1.0.217

**Comment by ladislavstefan** [comment]
Any update on this?
Tested again on the latest build 1.2.4. The same behavior - pagination component is inactive in published version while it is working in preview mode.

![image](https://user-images.githubusercontent.com/97522096/182540577-d5d1e6a3-54cc-4939-8015-f965db990611.png)

**Comment by aptkingston** [comment]
I've confirmed this issue is fixed. REST API pagination works as expected in both the preview and published apps.

Here's an example of a published app with functional REST API pagination using a test API:
![image](https://user-images.githubusercontent.com/9075550/234513713-459defd0-25e1-4577-8003-904264a4eca4.png)
