### ISSUE TITLE
handlebars.js - Week Year Number not supported.

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6369]
### Discussed in https://github.com/Budibase/budibase/discussions/6368

<div type='discussions-op-text'>

<sup>Originally posted by **insomniacj93** June 17, 2022</sup>
Hello there, dear friends!

I'm looking for help with the handlebars, I'm trying to generate a unique ID for every entry. I'm retrieving data from the user input and one thing i really wanted to do is get the current week number (the number of the current week that the ID is being generated "1-52").

This is what my handlebars.js looks like atm:

{{ Form.Fields.product_id }}{{ date now "YYMMDD" }}{{ random 10 99 }}{{ "PT" }} 

=Output:      "PRODUCT22061799PT"       (current date = 22-06-17)

I like how it looks so far, but my intention is to ditch the "MM" and the "DD" and replace them with just the Week Year. I found some documentation online about the handlebars.js and they reference Week Year as "GG" but such acronym isnt recognized in the budibase handlebars compiler.

ExpectedResult:         "PRODUCT225299PT"        (22 = Year / 52 = Week Year)

myref: https://docs.celigo.com/hc/en-us/articles/360045564992-Handlebar-expressions-for-date-and-time-format-codes

Any help on how to resolve this issue?

Very appreciated!!</div>

----

It appears that `Year, month, and day tokens` work, but `Week year, week, and weekday tokens` do not.
https://momentjs.com/docs/#/parsing/string-format/

Is there any reason we can't support ISO week date?

**Comment by adamjdavies** [comment]
Access to Week Year would be really useful for me too!
