### ISSUE TITLE
Apps update from Dev server

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Budibase/budibase#6403]
how can i transfer app updates to another server?  For example, we have a production environment server and a development environment.  How to transfer applications?  if you do export and import, then how to save the user base with accesses?  If we import a new version as a new application, do we need to re-add users and give them roles in the application?  Is there some kind of app update mechanism?

**Comment by vicam001** [comment]
Hi!! This is a very good point. Additionally I ha observed than when exporting/importing an app, in the target server it does not have the navigation links, nor the images ( even though they have been added by adding a public kink to the files stored publicly online.

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/9126
