### ISSUE TITLE
Bindings - Add suggestions/autocomplete menu

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#6422]
All IDE's have auto complete / suggestion menus that appear as the user types. This saves the user time and also prevents mistakes from happening. 

We currently have a menu for bindable values were the user can click the objects to add them to their handlebars or JS. We also have a keyboard shortcut `CTRL + Space` to reveal all the bindable values when using JS.

## Suggestion

When the user types `{{` or `$` and begins to type we should open a menu that filters the results which allows them to easily add values without the use of their mouse. 

This will have give a slightly more polished feel to our bindings drawer as it's a basic expectation of developers when coding in a IDE. 

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/5cfa8e48-0392-442c-bea2-65e0e5f2447f)

**Comment by jibe-b** [comment]
+1
