### ISSUE TITLE
Update public api range filter's format

### ISSUE THREAD

**Issue by brocococonut** [Budibase/budibase#6434]
https://github.com/Budibase/budibase/blob/9c8e25526e0abd96bc85156f7040e837555e2fdb/packages/server/specs/openapi.json#L2156-L2165

The above is either incorrect or obsolete. As I found and documented while investigating the `oneOf` filter (https://github.com/Budibase/budibase/discussions/6419#discussioncomment-3003074), the seemingly correct way that it should be used is:
```javascript
const query ={
  range: {
    [key]: {
      low: 1,
      high: 2,
    }
  }
}
```

**Comment by mike12345567** [comment]
This issue should include specifying the `oneOf` operation isn't available on Budibase DB, it is only an option for SQL based databases.
