### ISSUE TITLE
If no rows would be returned by a Date Range component, the builder is not happy

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6490]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.206
  - App Version: 1.0.206

**Describe the bug**
Whenever the Data Range would return no rows, the Client returns 400: Failed to send request, which continues in an infinite loop of retries (see animation).

**To Reproduce**
1. Create a form with Date Range for a Data Provider. Date field = some date field (I was using Created At)
2. Set the default range to something you know wont return any rows.
3. Watch the builder continuously refresh until you change the default range to return rows. The app also does something similar.

**Expected behavior**
If no rows would be returned by a Data Range component, then this should be handled gracefully.

**Screenshots**
![daterangebug](https://user-images.githubusercontent.com/101575380/176225699-35d95345-6a39-4891-88c2-109bd5537d65.gif)

**Comment by melohagan** [comment]
Hey @deanhannigan 
I had actually raised an issue for that as well! https://github.com/Budibase/budibase/issues/6491

That makes sense about the Repeater causing the loop. I wonder if it's possible to handle that more gracefully - not quite sure what the best approach would be.

**Comment by aptkingston** [comment]
Can we close this one off then? There's a PR up for moving the date range picker to the data category https://github.com/Budibase/budibase/pull/6622#pullrequestreview-1041566437.
