### ISSUE TITLE
Error publishing app - status 500 when using CRON Trigger

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6501]
### Discussed in https://github.com/Budibase/budibase/discussions/6459

<div type='discussions-op-text'>

<sup>Originally posted by **applicationuser** June 24, 2022</sup>
Error publishing app 

![image](https://user-images.githubusercontent.com/42922833/175696707-eb47d60c-683e-416f-825f-08224356ac30.png)
</div>

https://github.com/Budibase/budibase/discussions/6459#discussioncomment-3042440

**Comment by mike12345567** [comment]
I have been unable to recreate this issue in the latest releases, might be worth re-testing.

**Comment by melohagan** [comment]
Some further information here: https://github.com/Budibase/budibase/discussions/6459#discussioncomment-3154616

I'll test it out when I get a chance.

**Comment by mike12345567** [comment]
@melohagan - I was able to recreate, have added a fix for it.
