### ISSUE TITLE
Typo in page “OIDC integration with Budibase"

### ISSUE THREAD

**Issue by tylermneher** [Budibase/budibase#6506]
There is a trailing extra bullet point at the bottom of the page [OIDC integration with Budibase](https://budibase.com/integration/oidc/) in the list of SSO implementations. The raw url for the page im referencing is `https://budibase.com/integration/oidc/ ` and i’ve included a screenshot.

![buildbase-screenshot](https://user-images.githubusercontent.com/59175568/175799192-04f10656-a3c9-46eb-b5b6-0beb7a5c73ea.JPEG)

__Originally posted by @tylermneher in https://github.com/Budibase/website/issues/86__

**Comment by mslourens** [comment]
see PR https://github.com/Budibase/website/pull/88
