### ISSUE TITLE
Big List of Bugs

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#651]
- [ ] New App > Create User - HIDE PASSWORD

- [ ] Errors not handled well - sometimes app freezes

**Comment by shogunpurple** [comment]
Great list, thanks for putting this together.

```
Create new Row > Attachments > Upload (or drop into) does not work
Uncaught (in promise) TypeError: processedFiles is not iterable
processFileList Dropzone.svelte:45
(windows + FireFox or Chrome)
```

As mentioned in the PR, file upload only works in electron due to permissions. Are all of these bugs happening in dev mode on the browser? If they aren't happening in electron they probably shouldn't be here.

**Comment by mjashanks** [comment]
Most of them were foudn on Beta calls.... a few i added today from browser testing. I will re-check

**Comment by aptkingston** [comment]
Great to have these written up. I've closed off a few that are fixed as part of the backend UI updates for linked records and I'll continue to fix these where I can.

**Comment by mjashanks** [comment]
Closing this - separated into areas #660 #659 #658 #656 #657
