### ISSUE TITLE
Cannot close modal on save

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6521]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.214
  - App Version: 1.0.214

**Describe the bug**
I cannot close a modal on save row. 

**To Reproduce**
1. Add a Home screen with a Card with a link URL and *open link in modal*
2. Note I had to use `/tickets/{{ Repeater.Tickets._id }}`. The 'magic' linking did not work when selecting `/tickets/:id` from the dropdown.
3. In the tickets id screen, add a Save button with save row and **Navigate To** `/` i.e. home.
4. The modal does not close - you have to click the close button.

I also tried a table instead of Repeater/Card. In this case the 'magic' linking worked i.e. `/tickets/:id` but the modal issue was still the same.

**Expected behavior**
I should be able to close the modal with an action.

**Screenshots**
![Screenshot 2022-07-01 at 14 47 10](https://user-images.githubusercontent.com/101575380/176907176-af217f50-fdbb-4cc5-98df-303947072b0d.png)

<img width="1478" alt="Screenshot 2022-07-01 at 14 47 50" src="https://user-images.githubusercontent.com/101575380/176907276-b86662aa-32f7-47e8-9d47-bd7da6fe0270.png">

<img width="1478" alt="Screenshot 2022-07-01 at 14 48 15" src="https://user-images.githubusercontent.com/101575380/176907364-0a692001-2edc-4258-b62c-27913e70eaa2.png">

**Comment by aptkingston** [comment]
Hey @melohagan. The `Close Screen Modal` action is designed for this! Just use that in your save button action chain if you would like the screen modal to close.

**Comment by melohagan** [comment]
Ah brilliant! Probably should have known that! 😄 

It's not in the docs, so I can add it in there at least - closing.
