### ISSUE TITLE
Navigation bar not showing after detaching layout

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#6524]
**Hosting**

- Cloud
  - joe.budibase.app

**Describe the bug**
_This occurred when testing the new design UI_
I opened an old app in editor mode. This old app had a custom layout (full-width image above screen slot).
When I opened the design section, the image was not there. I then decoupled the layout, and the custom layout disappeared.
After this, I went to the navigation section and selected the left, then top nav options. Both did not work. I decoupled the old layout from all screens and tried again but it still didn't work. I've attached a video below:

https://vimeo.com/726090828/18975bffe1

**Comment by shogunpurple** [comment]
Solved in latest
