### ISSUE TITLE
Error updating number of attachments via arrow buttons

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#6530]
**Hosting**
- Cloud, app version 1.0.214

**Describe the bug**
Error updating No. of attachments in the "Attachment" form block.

**To Reproduce**
1. Add a form block
2. Add a field group
3. Add an attachment block
4. Click on arrow buttons rapidly (up or down)
5. See errors pop off

**Expected behavior**
No error OR a clearer error message?

**Screenshots**
![Attachment prop update error](https://user-images.githubusercontent.com/94982318/177011274-e4d7cc85-c1a5-470a-8e43-cc19fd70c004.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome Version 103.0.5060.66 (Official Build) (64-bit)

**Additional context**
_When clicked slowly error is not shown._ I guess it's a limitation to number of updates per second or something.

Pretty sure that was intended, but the error message could be clearer. As at first I thought that it was not working at all.

**Comment by shogunpurple** [comment]
Should be resolved in latest
