### ISSUE TITLE
'Data source' apps list disappears with the up and down slider is moved downwards .. refresh brings the list back  

### ISSUE THREAD

**Issue by mapprentals** [Budibase/budibase#6533]
**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mslourens** [comment]
Please fill in the details of the template, otherwise we cannot reproduce and fix the issue
