### ISSUE TITLE
Update edit user modal within app to make builder aware of read only properties

### ISSUE THREAD

**Issue by mapprentals** [Budibase/budibase#6534]
![image_2022-07-03_115442051](https://user-images.githubusercontent.com/108612479/177036349-01fa4ff9-d86d-4be4-8f4f-7ed05fa80273.png)
**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mike12345567** [comment]
Hi @mapprentals - this is maybe a documentation issue, you can't edit these attributes of the user from within the app, this information can only be edited from the portal, in the global user structure - as shown below:
![image](https://user-images.githubusercontent.com/4407001/177320294-eb6be2cf-761b-47e0-ae13-76ac2b3747d2.png)

We can't adjust this information from within the app, if you add another column to the user metadata table within an app it can be edited in the modal, but the `Email`, `First Name`, `Last Name` and `Role` are all read only properties from within an app.
