### ISSUE TITLE
DateTime Picker enhancements 

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6541]
We are often faced with a situation where the user needs to pick the Year only.

For example, when inputting credit card expiration, which is usually Month / Year.

A nice feature of the picker would be to have the options to show only Years with a specified range (i.s CurrentYear - CurrentYear + 10 ). Or just show a list of Months. 

Another case scenario would be when the user needs to enter the Year of Birth, and not the whole date.

I think these are pretty common use cases, and adding these options to the DateTime picker is worth it.

Have a blessed day.

**Comment by melohagan** [comment]
Hey @poirazis 

You could use options pickers for Months/Years, or alternatively a Text Field with some regex validation?

**Comment by poirazis** [comment]
Yeap, that's how I do it now, but I thought this could be a functionality of the component itself.

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/7961
