### ISSUE TITLE
Add Conditions to Row Selection

### ISSUE THREAD

**Issue by insomniacj93** [Budibase/budibase#6542]
Hello there,

I've been working with budibase for about 1 month now and I've got a little suggestion.

What comes to row selecting in data tables, there aren't many options for someone who wishes to select and use the data.
The selection seems kind of pointless if we cannot bulk transfer the data from tb1 to tb2 or have a condition for the user where he can only select 1 row at a time (avoiding bulk selection errors).

So my request is, if possible, the bulk transfer since it would be a great feature to have, otherwise the condition on row selection like allowing only 1 row to be selected at once (greying out the rest) I think it would be very useful to select the rows from the table which I want to transfer over.

**Comment by HeronCS** [comment]
Drop an `Element > Link` into (underneath) a table: [like so](https://gyazo.com/836a9b63a356d8613b85c427e4875186)

**Comment by melohagan** [comment]
This may be useful to you as well: https://github.com/Budibase/budibase/discussions/8759#discussioncomment-4207094
