### ISSUE TITLE
Dynamic filters don't allow filtering on SQL relationship columns

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#6550]
**Describe the bug**
Currently it is possible to filter by SQL relationship columns on tables with static filters defined through the `Define filters` option of a data provider. This should also be possible for dynamic filters which are built within published apps, using the `Dynamic filter` component.

**To Reproduce**
1. Add an SQL table with relationship columns
2. Create a screen with a data provider, a dynamic filter and a table
3. View the app, try to add a dynamic filter for one of the relationship columns
4. The options will not be available within the opened modal

**Expected behavior**
The dynamic filter component should detect the relationship columns and provide them as filterable options.

**Comment by Nicoautoxp** [comment]
Hi, 
I'm having this exact issue described here. I see that is marked as completed but it still doesn't work. Could someone point me in the right direction?
Regards, 
Nicolas
