### ISSUE TITLE
Webhook's domain is not correct

### ISSUE THREAD

**Issue by jason-wangting** [Budibase/budibase#6555]
**Describe the bug**
I am new for BB. When I use Webhook trigger, I follow  the guide to send `POST` to the URL shown in the below pic.
![image](https://user-images.githubusercontent.com/67987666/177240244-64fbb68d-354a-4df1-b2f3-2d440cd8c84b.png)
The url is `http://localhost:10000/api/webhooks/schema/app_dev_10a6e5fe6f1447faad60b92a4de776e3/wh_ae9462fa56a94e7686386774731de967`.
As you can see, the domain is `http://localhost:10000`. When I send `POST` to the `10000`, it always response `Invalid Request`.

Then I change the url to `http://localhost:4001`(4001 is the port for server), it turns to be correct. I donot know why the `10000` is not usable.

**Comment by shogunpurple** [comment]
Hi @jason-wangting - could you provide a reproducible app export, so we can debug? Thank you
