### ISSUE TITLE
Adding or Excisting automation

### ISSUE THREAD

**Issue by danielbolt** [Budibase/budibase#6564]
**Hosting**
- Self
  - Method: Docker
  - Budibase Version: 1.0.206
  - App Version:  1.0.206

**Describe the bug**
I'm able to build an automation within the 'Automate' screen. Even the tests passes. When going back to the 'Design' screen of my app and changes the 'Actions' of a button, and choose 'Trigger Automation' the select button of 'Use an existing automation' is greyed out.

Also adding a new automation 'Create a new automation' via the 'Trigger Automation' screen, the automation is added to the 'Automate' screen, but can't be edited.

![image](https://user-images.githubusercontent.com/60649319/177402262-e913a9b4-0245-45a3-8e97-da3396818b1a.png)

![image](https://user-images.githubusercontent.com/60649319/177402381-8c692d59-a913-4398-9a4d-412e7d399095.png)

![image](https://user-images.githubusercontent.com/60649319/177402470-9e8ddc5e-8cc6-44e1-9e97-cf9966b6270a.png)

**Comment by mslourens** [comment]
You can only manually trigger an automation if you have an automation using the App Action trigger. Other automations cannot be manually triggered by a button. 
I just tried creating a new automation in the Trigger automation step and could edit it afterwards. What do you see in the console of your browser?

**Comment by danielbolt** [comment]
> 

I've build an automation which will be triggered by a new row creation. The automation will duplicate the row in another table. On which moment will the automation be active?

When adding a new automation via the 'Trigger automation step' i only get a blank screen in the console. I can't edit the automation flow. This is visable in screen shot 3 in my previous post. The 'Copy' automation gives a blank screen.

**Comment by mike12345567** [comment]
Hi @danielbolt - simply publishing the app with an automation that has a trigger of "Row creation" will make it work. In development we don't trigger automations as the test functionality can be used instead.

You can read about automations in our documentation: https://docs.budibase.com/docs/automation-steps

**Comment by danielbolt** [comment]
> Hi @danielbolt - simply publishing the app with an automation that has a trigger of "Row creation" will make it work. In development we don't trigger automations as the test functionality can be used instead.
> 
> You can read about automations in our documentation: https://docs.budibase.com/docs/automation-steps

Thanks Mike!

I will test this!
