### ISSUE TITLE
Frontend Bugs

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#657]
- [x] add a button, then delete it - the builder throws an error and crashes

- [x] Screen - Description and Route should not be bindable

- [x] CSS Heirarchy

1. Created a container
2. Added a heading
3. Clicked on container and changed the font color for :hover ... this did not apply the hover prop to the heading... though it does work for a paragraph

- [x] Create new screen. We have the option to choose a "Layout Component". We should hide this.

- [x] Duplicate component - The component and all its children keep its original name - it should get an incremented number .. "Input 2"

- [ ] Should not be able to change the Home screen URL, or remove the screen (must always be a home page)

**Comment by aptkingston** [comment]
Fixed a couple of different crashes when I was working on the frontend over the past couple of days, so that button issue is now resolved.
