### ISSUE TITLE
Backend Bugs

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#658]
- [x] Add 2 Attachment Columns. When i upload to the Second one, it adds the attachment to the first

- [x] View filter does not work for true/false columns - IN PROGRESS - MS

- [x] View > Calculate, we are allowed to choose "Statistics" a single valued dropdown. I suggest that this should not be a dropdown until we have other options in here. It's an unecessary click

- [x] If I create a table, without a Number type column, it is impossible to get a count of records, or a "max date", etc

- [x] Created a table with NO required columns. Got an error message, listing all fields as required fields

**Comment by mike12345567** [comment]
- [ ] Deleting a view will attempt to make a query to the view after it has been successfully deleted, causing it to 404
