### ISSUE TITLE
bbapps High ram usage

### ISSUE THREAD

**Issue by Valdri** [Budibase/budibase#6580]
**Hosting**

- Self
  - Method: docker compose 
  - Budibase Version: 1.0.214 

**Describe the bug**
The bbapps container consumes all available RAM over time and then when it is almost 100% it releases it and the cycle continues.

**Screenshots**
![1](https://user-images.githubusercontent.com/13934649/177565779-def2bd4b-d651-4094-85c9-276bf582233f.png)

**Comment by maiducan** [comment]
i have the same issue

https://github.com/Budibase/budibase/discussions/6577

**Comment by Rory-Powell** [comment]
Hi @Valdri @maiducan , thank for raising this. We've found the source of the issue (a memory leak) which we are currently fixing. I'll leave an update here and in the other issue when the fix is released.

**Comment by maiducan** [comment]
> Hi @Valdri @maiducan , thank for raising this. We've found the source of the issue (a memory leak) which we are currently fixing. I'll leave an update here and in the other issue when the fix is released.

Hello Rory, are there any updates regarding fix and release? Just to know if it is going to be within days or weeks? Thanks a lot!

**Comment by kunalgupta711** [comment]
> Hi @Valdri @maiducan , thank for raising this. We've found the source of the issue (a memory leak) which we are currently fixing. I'll leave an update here and in the other issue when the fix is released.

Hi@Rory-Powell ,

Requesting you to please share the ETA for the fix .
It will help us manage in better way.

Thanks in advance!

**Comment by mike12345567** [comment]
Hi everyone, realise this is a painful issue, we're currently working on a fix, we hope to have it out at some point next week.

**Comment by maiducan** [comment]
Hello, any updates please? :))

**Comment by mike12345567** [comment]
Hi @maiducan - I should have tagged the PR for this, but the latest versions of Budibase should have this problem resolved.

We have a plan to remove the offending library which should make sure this never happens again, but for now we've applied some fixes to make sure the library is getting cleared down correctly again.

**Comment by v3ss0n** [comment]
I am still having performance issues. Is there any easy way to grab memory usage of each contaienrs? searching in htop is a pain for containers.

**Comment by mike12345567** [comment]
Hi @v3ss0n - you can run `docker stats` to see the state of your containers and their memory usage.
