### ISSUE TITLE
Cannot add Section component to Form component

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6585]
**Hosting**
- Cloud
  - Tenant ID: bb
  - App Version: 1.0.218

**Describe the bug**
Cannot add Section to Form directly, but can add the section to the screen and then drag it into the form component.

**To Reproduce**
1. Have a screen with a Form
2. Click the form, then click Layout -> Section (section is disabled)
3. Click the screen, then click Layout -> Section to add the section
4. You can now drag the section into your Form

**Expected behavior**
I should be able to add a Section directly into a Form?

**Comment by aptkingston** [comment]
Sections can only be top level components - you can't add them inside any other component. I think we should remove sections entirely, but that's a different conversation haha.
