### ISSUE TITLE
Component Bugs

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#659]
* [x] Card component - Link Color and Hover Color should be a colour picker
* [x] Radio input is useless as we cannot group them together

* [x] Select component is useless, as we cannot add options
* [x] Navigation component - cannot add padding
* [x] Link component - Needs a URL or it will crash the builder
* [x] Icon component - crashes when any option is changed
* [x] Add a Login component to the screen - crash

* [x] Form - Date fields defaults to "undefined" (it actually displays this)
* [x] Link component - if i want the url to be /customer/{{ List.Customer._id }} - then i need to type the binding expression in myself - because it is a dropdown of screens, there is no binding icon
* [x] Stacked list - I added a Stacked list inside a List - before setting the Table on the list. The builder crashed. A reload of the builder failed, as it reloaded with the stackedlist selected, and thrw the same error. I had to change the url
* [x] Stacked List - the "Destination Url" does not display a dropdown of screens. However - if it did, it would be less usable as I would have to type the binding expression myself anyway, to get the ID

**Comment by kevmodrome** [comment]
Just double checking, this one: 

> Card component - Link Color and Hover Color should be a colour picker

Is not relevant anymore, correct?

**Comment by kevmodrome** [comment]
Can't reproduce the stacked list issue. @mjashanks can you elaborate on how to get the error? 🙏

**Comment by mjashanks** [comment]
@kevmodrome 
> Can't reproduce the stacked list issue. @mjashanks can you elaborate on how to get the error? 🙏

Retested, and cannot reproduce - this one is old, will assume that it is fixed

**Comment by kevmodrome** [comment]
Cool! Thanks!
