### ISSUE TITLE
Re-add no navigation option

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#6607]
I think it would be helpful to re-add the 'no navigation option'. It's my most popular choice when building internal tools.
<img width="303" alt="CleanShot 2022-07-08 at 09 02 19@2x" src="https://user-images.githubusercontent.com/49767913/177946461-3f312a17-3f76-4855-8a07-abd3270a10a2.png">

**Comment by kasgithub8** [comment]
Isn't that just the Empty Layout? Or am I thinking wrong here?

**Comment by aptkingston** [comment]
With the new UI you choose which screens you would like navigation on by using the "Show navigation" setting in the screens setting panel.
![image](https://user-images.githubusercontent.com/9075550/178722377-74069b59-0d5f-42ea-8c64-d5462e360f7f.png)
You can just turn it off for any screens where you don't want navigation.
