### ISSUE TITLE
User disappeared from management area and I am now receiving an error

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#6608]
When accessing the users tab, I received an error + my user was not there.
<img width="1798" alt="CleanShot 2022-07-08 at 09 15 33@2x" src="https://user-images.githubusercontent.com/49767913/177948671-b354f590-e28f-43e6-875f-9f3267546e68.png">

**Comment by shogunpurple** [comment]
@joebudi this is because the new backend hasn’t been deployed when using the new UI - when we roll this out for real. It will work 👍 you can get round it in the meantime by rolling back to the old UI

**Comment by joebudi** [comment]
Cheers. The new UI is awesome

**Comment by joebudi** [comment]
Cheers. The new UI is awesome
