### ISSUE TITLE
Saving attachments using "On Change" action does not save the attachment

### ISSUE THREAD

**Issue by esprssoo** [Budibase/budibase#6616]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.0.218

**Describe the bug**
Trying to immediately save an uploaded attachment using the "On Change" action on the Attachment field does not save the attachment to the table, but creates an empty row. Saving the row using a button works as expected.

**To Reproduce**
1. Create a table `Attachments` with a column `Attachment`.
2. In any screen create a simple form for the `Attachments` table, and add the `Attachment` field
3. Add a new "Save Row" inside "On Change" actions with data source `New Form` and table `Attachments`. Click save.
4. Now upload any attachment using the form. A new row will be created but it will be empty.

**Expected behavior**
I was expecting the attachment to be saved in the table when I uploaded the attachment.

**Screenshots**
Here's how the form was created
![image](https://user-images.githubusercontent.com/20658439/177991456-54427c5f-dc86-46f2-a28d-177f3024f2f5.png)
Here is the resulting table
![image](https://user-images.githubusercontent.com/20658439/177991628-8a5065b9-1cd7-4a24-84ed-3b4cca9a347f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 102

**Comment by esprssoo** [comment]
Experimenting further, I found out that when clearing the attachment form field using the X button also triggers the On Change event. Weirdly, it creates a new row with the previously uploaded attachments saved in the `Attachment` column!

**Comment by melohagan** [comment]
Hey @esprssoo 

What's your use-case for this? Why not simply have an `upload` button?
