### ISSUE TITLE
on change action with execute Query wrong value

### ISSUE THREAD

**Issue by Dominic-Wagner** [Budibase/budibase#6632]
**Hosting**

- Self
  - Method:  docker compose 
  - Budibase Version: 1.0.214 
  - App Version: 1.0.214 

**Describe the bug**
on change event is submitting the previous value when execute query is triggered, even if the previous value is not valid due to validation.

**To Reproduce**
1. following app structure:
![image](https://user-images.githubusercontent.com/43470807/178138228-7153b4eb-c9ed-4846-8efc-9af795af043e.png)
2. setup on change action
![image](https://user-images.githubusercontent.com/43470807/178138217-28144210-2563-42c4-aa89-7f261f6f21ba.png)
3. setup validation
![image](https://user-images.githubusercontent.com/43470807/178138559-7da5c4cf-2933-4fc4-8628-40d813688d87.png)

3. change value to something wrong -> execute query is not performed due to invalid form
![image](https://user-images.githubusercontent.com/43470807/178138271-713da39c-a98f-43d0-958a-f184da7b1f8f.png)
5. change to something valid
![image](https://user-images.githubusercontent.com/43470807/178138293-a92c08e5-51f5-4d88-83b6-312af80d498d.png)
6. execute query gets executed with previous invalid value
![image](https://user-images.githubusercontent.com/43470807/178138316-b9b2d4fe-6dd9-46f3-b86f-c0b790d85237.png)
8. trigger on change a second time time to submit correct value
![image](https://user-images.githubusercontent.com/43470807/178138332-9c449d91-c48b-43fd-a056-a267f0585006.png)

**Expected behavior**
execute Query with the current value

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 103.0.5060.114

**Additional context**
I also tried it without execute query. When using save row, the api is called two times directly, first with old, then with new value.

**Comment by Dominic-Wagner** [comment]
With execute query, {{ Field Value }} needs to be used

**Comment by diedder** [comment]
Hi @Dominic-Wagner,
could you please explain the solution? I'm having the same issue wirh die previous value. I want to use the value of this {{ Form Question.Fields.Sort }} field in my binding for the query.
Thank you!

**Comment by aptkingston** [comment]
> Hi @Dominic-Wagner, could you please explain the solution? I'm having the same issue wirh die previous value. I want to use the value of this {{ Form Question.Fields.Sort }} field in my binding for the query. Thank you!

Hi @diedder. When using an "on change" action for a form field, the `{{ Form.Fields.Foo }}` binding will contain the previous value, before the change. There is another binding `{{ Field Value }}` which containers the new value. It's the first option in the list:
![image](https://user-images.githubusercontent.com/9075550/182389729-3f5a1a0f-d3d7-4d28-bf64-ee241e1f83a3.png)
