### ISSUE TITLE
Unable to revert back to the old builder

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#6649]
**Hosting**
- Self
  - Method: separate local nodejs processes
  - Budibase Version: develop branch

**Describe the bug**
It is not possible to revert back to the old builder. Clicking the button will only reload the builder, but still in the new layout

**To Reproduce**
1. Go to the beta tab
2. Click on 'revert back to the old builder'
3. Notice: the app refreshes, but remains in the new layout

**Expected behavior**
The app refreshes in the old layout

**Screenshots**
https://user-images.githubusercontent.com/1907152/178348244-55e16ac8-2ea2-40f0-b992-b18fa658bc0b.mp4

**Desktop (please complete the following information):**
 - OS: PopOS 22.04
 - Browser: Firefox
 - Version: develop branch

**Comment by aptkingston** [comment]
Hey @mslourens. If you were running this in dev mode (which it sounds like from your setup) then you will always only be served the current client library version that's on your filesystem. App versions/updates (including toggling the beta branch) won't have any effect when running the dev scripts - they only work in production installs.

**Comment by mslourens** [comment]
Ah, then I'll close this issue. Thanks for the explanation. 
I thought it was just a feature flag, but it's actually a replacement of part of the code.
