### ISSUE TITLE
Budibase does not show all the SQL records.

### ISSUE THREAD

**Issue by danielbolt** [Budibase/budibase#6653]
Hosting

Self
Method: Docker
Budibase Version: 1.1.2
App Version: 1.1.2

Budibase does not show all the records within SQL tables. This is a huge problem.

Example:

Records in SQL management studio:

![image](https://user-images.githubusercontent.com/60649319/178424935-8c97ec92-4d4b-4b91-a466-dbea4c0cc79e.png)

Records in Budibase:

![image](https://user-images.githubusercontent.com/60649319/178424987-14ac658d-c2cd-4459-bb71-b6c5cc9790c4.png)

This problem excists for several SQL tables. All the SQL tables are added and designed withijn Budibase.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Comment by melohagan** [comment]
Hi @danielbolt 

Can you have a look at the console and network tabs (Fn+F12 on Chrome). Do you see any error messages in there?
