### ISSUE TITLE
This screen uses a custom layout, which is deprecated

### ISSUE THREAD

**Issue by danielbolt** [Budibase/budibase#6654]
Hosting

Self
Method: Docker
Budibase Version: 1.1.2
App Version: 1.1.2

After updating to the next version of budibase, my apps are showing this message:

![image](https://user-images.githubusercontent.com/60649319/178426422-095c2e7d-b717-4690-a989-2d1bdddcf6db.png)

When i hit 'Detach custom layout' the whole screen is deleted.

Alle the screens are generated bu Budibase CRUD.

**Comment by mpilnan** [comment]
Hi @danielbolt , I had the same issue just now. For me, the problem was that the individual apps were not actually on version 1.1.2.

Had to go to *Apps* menu in the Builder, go to *Manage* menu of the individual apps and *Update* the apps created before today's release.

I went to create a similar issue, and just then realized that Budibase version and App version were two different things 😄

**Comment by danielbolt** [comment]
> Hi @danielbolt , I had the same issue just now. For me, the problem was that the individual apps were not actually on version 1.1.2.
> 
> Had to go to _Apps_ menu in the Builder, go to _Manage_ menu of the individual apps and _Update_ the apps created before today's release.
> 
> I went to create a similar issue, and just then realized that Budibase version and App version were two different things 😄

Thnkas,

But the app is on the latest version.....

**Comment by aptkingston** [comment]
Hi @danielbolt. As @mpilnan mentioned, your app needs to be on the latest version to take advantage of these new features. It's a bug on our part that you're able to do the "detach" action while not being on an app version that supports detached screens. We're pushing an update today which will make app updates more visible, by adding back the update icon into the top bar of the builder. They're currently quite hidden inside the settings tab of the overview section.

While these screens "disappear" when detaching them using an older app version - rest assured that no harm is done. Once you update your app to the latest version they will still be there and work perfectly.

Thanks @mpilnan for the quick reply and solution.

**Comment by Elliot-Construct** [comment]
Yeah @danielbolt, and unfortunately if you used screens to make custom menus for different roles this feature is now depreciated. 
The bottom line is.. the users have outlined that they prefer ease of use over customization options. Hopefully new options open up soon. 
#6790
