### ISSUE TITLE
Dcoument update conflict

### ISSUE THREAD

**Issue by danielbolt** [Budibase/budibase#6655]
Hosting

Self
Method: Docker
Budibase Version: 1.1.2
App Version: 1.1.2

![image](https://user-images.githubusercontent.com/60649319/178428253-37d290f5-0ce4-4f5a-b9a6-f63c03a35607.png)

**Comment by shogunpurple** [comment]
@danielbolt could you create a new issue and follow the bug template please, to detail reproduction steps and tell us a little more about the issue you are having. This is not actionable - closing
