### ISSUE TITLE
New menu items are not displayed when app is published

### ISSUE THREAD

**Issue by danielbolt** [Budibase/budibase#6656]
Hosting

Self
Method: Docker
Budibase Version: 1.1.2
App Version: 1.1.2

When adding new menu items, these menu items are not displayed within the published app.

![image](https://user-images.githubusercontent.com/60649319/178428513-a4cee43a-c4f3-4d50-8d9b-459c1f01a88d.png)

Published app:

![image](https://user-images.githubusercontent.com/60649319/178428666-48b83528-c774-4d95-bf99-f37970472eb6.png)

**Comment by aptkingston** [comment]
Hey @danielbolt. The new navigation settings only take effect for screens *not* using old custom layouts. The warning boxes in the design section should show you this. If you detach your screens from custom layouts then the new navigation settings will work as expected.
