### ISSUE TITLE
Background outside the Screen Slot no longer changeable.

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6657]
Up to v.1.0.218 we could set the navigation background Gradient, and it would apply to the area outside the screen slot.
With the new version v.1.1.2 this ability is gone.
<img width="414" alt="Screenshot 2022-07-12 at 10 47 46 AM" src="https://user-images.githubusercontent.com/80512170/178437915-353eb841-2fa1-413f-b823-df575843857c.png">
<img width="420" alt="Screenshot 2022-07-12 at 10 47 17 AM" src="https://user-images.githubusercontent.com/80512170/178437944-e7a3ee26-7e71-407b-882d-fb49a397d2fc.png">

**Comment by sergey-dme** [comment]
The same. My app ruined now by this new version :( I always used custom layouts with lots of important custom elements.. and precisely tuned by custom CSS and embed
Gonna stay on v.1.0.218 forever as no other option for keeping my app UI I can see now

**Comment by joebudi** [comment]
Hey @poirazis . I am not sure if this answers your questions, but, you could add a gradient to the background color input:
![CleanShot 2022-07-12 at 11 45 40](https://user-images.githubusercontent.com/49767913/178473085-3b54810d-1c68-4eb9-b39a-87744fc82b46.png)

For ref:
```
background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 35%, rgba(0,212,255,1) 100%);
```

**Comment by poirazis** [comment]
Hey @joebudi 
I am talking about the space around the Screen Slot, not the background of the navigation bar. That area , around the Screen Slot that appears grey in my first screenshot.

**Comment by joebudi** [comment]
hey @poirazis . Ah yes, I've told the engineering team about this. When max-width is set, it should space the full width of the screen. I'll keep this issue open and one of our engineers will take a look at it.
