### ISSUE TITLE
Nested Links in Navigation Menu

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6659]
While building complex applications, having all the Menu / Navigation Links as Level 1 is very cumbersome. We are often faced with the scenario where we need to nest navigation links as Menu / Submenu

**Comment by Elliot-Construct** [comment]
This also may be offset by role specific menus
See #6790 for info

**Comment by Elliot-Construct** [comment]
not stale still very relevent

**Comment by darkzone** [comment]
still relevant

**Comment by seandlg** [comment]
Check out [this](https://github.com/poirazis/bb-plugin-TabContainer) :-)

**Comment by scmsystm** [comment]
> Check out [this Tabs layout](https://github.com/poirazis/bb-plugin-TabContainer), which may pose a viable alternative :-)

Tabs layout are nice for < 5 contents, tab navigation does not scroll on phone view.
We still need nested links inside native budibase navigation 👍

**Comment by jkirkpatrick** [comment]
not stale issue, please fix bot

**Comment by alican92** [comment]
Defiantly not a stale issue, this would be VERY helpful in instances where a single Budibase APP has multiple pages that need to be grouped.

**Comment by rafalpawlik1981** [comment]
Hi, is there any progress about this topic?

**Comment by techthrasher** [comment]
This functionality is key to making complex applications.

**Comment by ConorWebb96** [comment]
This is now complete, closing this issue. 🤝
