### ISSUE TITLE
Document update conflict

### ISSUE THREAD

**Issue by PaulMcF1987** [Budibase/budibase#6670]
Im not sure that is causing it or even how to check what the error is but I noticed that on multiple occasions today, when I tried accessing pages of my app, only part of it loaded and I got an error 

![image](https://user-images.githubusercontent.com/75368133/178551228-855b70f2-10a7-46df-a781-b15a54ac96a6.png)

Is this a known error? what is the best way to debug the issue?

I have noticed in recent days that the app has been getting slower. It started with relationship drop-down, when I select the drop-down it takes a few minutes for it to populate but it does eventually get there. Now I am getting the above error

It seems to happen more on pages which use custom queries (at least from what I have noticed)

![image](https://user-images.githubusercontent.com/75368133/178551922-eb6955bf-89ab-4df8-8b8d-3092ad412fe0.png)

After refreshing the page:

![image](https://user-images.githubusercontent.com/75368133/178552270-c26a2173-7676-417e-9676-3286d1988c7f.png)

Excuse the markings, Id rather not share live business info

after a further refresh I get:

![image](https://user-images.githubusercontent.com/75368133/178556710-06261d1e-0df0-4739-911c-558b05ab3fff.png)

The bottom pic is with the new/updated version, the rest are with the previous version. 

Incase it makes a difference, I am using an External MYSQL DB.

**Comment by PaulMcF1987** [comment]
The problem is getting worse and is now happening with relationship dropdows

![image](https://user-images.githubusercontent.com/75368133/178713710-c2ee6c75-a434-41d6-88a9-d7f1be4e54f7.png)

I am scared that the app will soon be unusable

**Comment by cfepdan** [comment]
We are seeing these 400 errors, too, on our dashboard, which pulls from ~5 external APIs.
@aderici 

![image](https://user-images.githubusercontent.com/28074021/180578452-b412a6f2-b8da-459d-9e89-352496789a69.png)

**Comment by diogenesbrussels** [comment]
Hey,

I also encounter errors from time to time with requests (dev and published app):

message | "Document update conflict."
status | 400

Here on a MySQL read request
![image](https://user-images.githubusercontent.com/91942877/181011463-0bde64dc-a511-4e85-b2dd-76cfa3d1b36a.png)

Here on a search request (stat card)
![image](https://user-images.githubusercontent.com/91942877/181013367-9413748b-a7fc-45d7-8846-e779b9f8a728.png)

If I resend the request via the dev tools, it doesn't seem to get an error.
App v. 1.1.21

**Comment by shogunpurple** [comment]
We've pushed some fixes that should considerably help with this. Closing for now
