### ISSUE TITLE
Link table rows do not go to the linked screen

### ISSUE THREAD

**Issue by pr1malc0de** [Budibase/budibase#6679]
**Hosting**

- Self
  - Method: k8's
  - Budibase Version: 1.0.218
  - App Version: <version> 
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
Link table rows doesnt go to the defined link screen

**To Reproduce**
1. Create SQL data source and table tick link table rows and define another screen
2. Click on sql table row

**Expected behavior**
A modal opens with screen selected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: minikube running on ubuntu

**Additional context**

**Comment by aptkingston** [comment]
@pr1malc0de could you provide more information or screenshots? I have tested this and it works fine:

![image](https://user-images.githubusercontent.com/9075550/178714306-1ab15e6a-2500-48d1-9d4a-8a3b6335cd7c.png)
![image](https://user-images.githubusercontent.com/9075550/178714335-b35d38c3-c0e8-4ad3-9848-3ec34127be50.png)

Please make sure that:
- You have configured the correct settings
- You have created a details screen wih an `:id` parameter (or are using autogenerated screens)
- Your details screen works and you have verified this, if you created the details screen from scratch yourself
