### ISSUE TITLE
Form component success / failure messages (and current pop-ups).

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#6695]
**Describe the feature request**
It would be great to be able to customize "Success" or "Failure" messages when submitting a form.

Right now a pop-up shows **on the top edge** of the page saying "Row Saved" or "Bad Request".

We should be able to customize the message or optionally get rid of the pop-up on top of the page. As it's (a) shown out of the form component which makes it counter-intuitive and (b) has unclear messages like "Row Saved" and "Bad Request" which are for internal/dev use that public users should not be able to see when filling out a form.

P.S. I believe it's possible to create a "Success" message close to the "Submit" button by using conditional UI and visible/not visible? But we still can't get rid of the pop-up if we want to.

**Comment by melohagan** [comment]
> But we still can't get rid of the pop-up if we want to.

This has been solved with this checkbox setting.

![Screenshot 2023-12-06 at 15 28 13](https://github.com/Budibase/budibase/assets/101575380/1b49e88f-55c0-4a41-95e3-17ea783b0eda)
