### ISSUE TITLE
Problems with rootless docker

### ISSUE THREAD

**Issue by guidot** [Budibase/budibase#6698]
**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 1.0.218
  - OS: Debian 11

**Describe the bug**
It seems as if budibase is not working fully in a rootless docker environment, which I consider a security issue in a broader sense, since docker should not run as root.
While budibase seems to work normally I experience the following problems:

- Watchtower looks for the socket in the wrong place. See also #6582.
  I assume that's why the Web-UI update says `Your budibase installation is up to date.` even though the June update is out.
- The budi CLI doesn't recognize the running instance. 

**To Reproduce**

##### For the watchtower problem:
1. Install docker from their repos and set it to rootless mode according to their [docs](https://docs.docker.com/engine/security/rootless/).
2. Have the following lines in your user's `.bash_profile`: 
```
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock.
```

3. In docker-compose.yaml change the reference to the docker socket to the one in the environment variable `DOCKER_HOST` (I hardcoded the User ID):
```
  watchtower-service:
    [...]
    volumes:
      - /run/user/998/docker.sock:/run/user/998/docker.sock
```

The error console shows
`level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"`

##### For the budi CLI problem:
1. Install budi CLI according to the offical docs
2. Change into your budibase directory.
3. Enter `budi hosting --status`.
`Error - docker/docker-compose has not been installed, please follow instructions at: https://docs.budibase.com/docs/docker-compose
`

**Expected behavior**

- Watchtower recognizes the correct socket
- Web-UI informs me of the update
- Budi CLI recognizes the running docker instance

**Comment by aptkingston** [comment]
You can use the single image if you want rootless docker support.
