### ISSUE TITLE
Linked Records Frontend UI

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#670]
There are quite a few different components which need to be updated to support linked records in the standard components library.

- [x] Create multiselect component in BBUI so that it can be used in the builder and client apps
- [x] Add linked record selection to `DataForm`
- [x] Add linked record count to `DataTable`
- [x] When binding to a field which is a linked record, display the count rather than the actual value

**Optional**
Ideally when inside a record detail view we should expose any linked record fields as data sources. That would mean you could add a `List` inside a `RecordDetailView` and choose the source as `Student.classes`  for example, and then add nested components to see details about their linked records. This is quite complicated and the codebase for all this is very slow to work on with fresh eyes so leaving this to last as I would rather merge this in ASAP than keep it open for another few days until this part could be worked out.

**Comment by aptkingston** [comment]
Going to leave that "optional" part alone for now - it warrants a proper discussion around CRUD for tables and the current implementation is sufficient to display linked record counts in the UI. The linked records branch has been open long enough so lets merge it as it is, and the further work of displaying actual linked records as a data source can be implemented as a new feature branch.

**Comment by joebudi** [comment]
You deserve a medal for this work. Great job AK

**Comment by aptkingston** [comment]
Cheers @joebudi! Pulled in BBUI form components too, so here's a real app where you can create a student and pick their classes, and looks a bit fresher overall. Took way longer for these frontend changes than it should have, but most of it was getting my head round how the frontend and client libraries work since I hadn't looked at it before.

![dataforms](https://user-images.githubusercontent.com/9075550/95238126-f813c700-0800-11eb-9d38-53902f29624a.PNG)

**Comment by joebudi** [comment]
Looks great. Clean cut. Very Budibase. Love it.

**Comment by shogunpurple** [comment]
Amazing work @aptkingston and great shout on leaving the record detail view out for now. The record detail view as well as any other components of a similar ilk need to be looked at from a UX perspective so that they are super simple to use for any user. They will also need to be linked record aware on top of that - another fairly substantial piece of work. We will revisit that whole area as its own project soon after the beta launch.
