### ISSUE TITLE
Remove user table as an option for automation triggers and create row action

### ISSUE THREAD

**Issue by Elliot-Construct** [Budibase/budibase#6702]
When I set an automation on the User table, it doesn't trigger when you activate a user on an application.

Any thoughts?

**Comment by mike12345567** [comment]
Hi @Elliot-Construct - this isn't really a supported path for automations, realistically we need to hide the users table as an option for automation row created/deleted triggers. The users table is quite different to other tables under the hood and doesn't really play very well with automations, other than being read, or updating custom columns on an existing user row.
