### ISSUE TITLE
No longer able to trigger automations from Public screens (Session not authenticated)

### ISSUE THREAD

**Issue by bmcbride** [Budibase/budibase#6709]
**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 1.1.4
  - App Version: 1.1.4

**Describe the bug**
I have a Public form that triggers an email automation when submitted. After upgrading from version 1.0.196 to 1.1.4 the automation no longer runs and a "Session not authenticated" warning is displayed. 

**To Reproduce**
1. Create a Public screen with a button to trigger an automation.
2. Try triggering an automation while logged out of Budibase.

**Expected behavior**
Previously automations could be triggered from Public screens.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 103.0.5060.53

**Comment by bmcbride** [comment]
I was able to reproduce the `Session not authenticated` error in my hosted Budibase account on version 1.1.7. Is it no longer possible to trigger automations from Public screens or is this a regression? Thanks!

**Comment by bmcbride** [comment]
@mike12345567 thanks for working on addressing this! Any idea when these fixes might make it into a release? Thanks again, much appreciated!

**Comment by mike12345567** [comment]
Hi @bmcbride - this should be released early next week, with the change you'll need to configure your app actions as public, you can see an example of this done in the PR!

**Comment by bmcbride** [comment]
Sounds good. Thanks again and have a great weekend.
