### ISSUE TITLE
Selected form step not showing

### ISSUE THREAD

**Issue by laromana** [Budibase/budibase#6729]
**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 1.1.4

**Describe the bug**
Selected form step not showing in the design area unless page is refresh.

**To Reproduce**
1. Go to design
2. Select screen
3. Open component panel
4. Select form>from step number
5. Select different step number

**Expected behavior**
Selected form step to show within the design are

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by aptkingston** [comment]
Hi @laromana. Could you check if you're seeing any errors in your browser console when this behaviour happens? Probably something that looks like:
![image](https://user-images.githubusercontent.com/9075550/179224525-8e86064b-f5ea-4060-aa65-0cdc8a6bdee0.png)

**Comment by laromana** [comment]
Yes I am getting the error below:

![budibase_error](https://user-images.githubusercontent.com/79430611/179230045-4578dd40-b8ac-4233-8191-adf586e3c5b2.JPG)

192.168.1.196/:1 Unchecked runtime.lastError: The message port closed before a response was received.
budibase-client.js?v=1.1.4:243 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'scrollMargin')
    at budibase-client.js?v=1.1.4:243:303415
    at e.$$.update (budibase-client.js?v=1.1.4:243:303493)
    at _e (budibase-client.js?v=1.1.4:1:6391)
    at Le (budibase-client.js?v=1.1.4:1:6141)
(anonymous) @ budibase-client.js?v=1.1.4:243
e.$$.update @ budibase-client.js?v=1.1.4:243
_e @ budibase-client.js?v=1.1.4:1
Le @ budibase-client.js?v=1.1.4:1
Promise.then (async)
we @ budibase-client.js?v=1.1.4:1
(anonymous) @ budibase-client.js?v=1.1.4:1
(anonymous) @ budibase-client.js?v=1.1.4:1
(anonymous) @ budibase-client.js?v=1.1.4:243
i @ budibase-client.js?v=1.1.4:1
set @ budibase-client.js?v=1.1.4:243
window.loadBudibase @ budibase-client.js?v=1.1.4:243
receiveMessage @ VM985 about:srcdoc:86
postMessage (async)
I @ index.91ff43ed.js:904
r.$$.update @ index.91ff43ed.js:904
Zz @ vendor.7f11b0ca.js:4
V9 @ vendor.7f11b0ca.js:4
Promise.then (async)
hv @ vendor.7f11b0ca.js:4
Qz @ vendor.7f11b0ca.js:4
(anonymous) @ vendor.7f11b0ca.js:4
(anonymous) @ index.91ff43ed.js:919
f @ vendor.7f11b0ca.js:4
Oz @ vendor.7f11b0ca.js:1
T @ index.91ff43ed.js:749
d @ index.91ff43ed.js:749
(anonymous) @ vendor.7f11b0ca.js:1

**Comment by aptkingston** [comment]
Thanks, I've fixed the issue in the PR referenced above. We'll get the fixed pushed soon :+1:
