### ISSUE TITLE
Custom error message in custom validation rules not working.

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#6736]
**Hosting**
- Cloud
  - Version 1.1.7.

**Describe the bug**
When setting custom validation rules custom error message cannot be changes.

For example, for email field "Must match regex" always has "Invalid email" error message when email address doesn't match regex pattern. Despite 

**To Reproduce**
1. Create a database "Email" column.
2. Add a component within Form that writes to the "Email" column.
3. Add custom validation rules to "Email" component "Must match regex".
4. Enter regex email validation rules
5. Customize error message
6. Go see error message when invalid email is entered -- It's always "Invalid email".

**Expected behavior**
Error message should be customizable.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - Browser Chrome
 - Version 103.0.5060.114, 64 bit

**Comment by Klience** [comment]
Hi @shogunpurple -- noticed you added sev3 label a few day ago. That problem was fixed AFAIK. I have no problem setting up custom validation error messages anymore. Including with the regex example above.

**Comment by shogunpurple** [comment]
Thanks for letting us know @Klience!
