### ISSUE TITLE
bbproxy container fail to start with IPV6 disabled

### ISSUE THREAD

**Issue by lolcabanon** [Budibase/budibase#6752]
**Hosting**

- Self
  - Method: npm @budibase/cli && docker compose up 
  - Budibase Version: 1.1.4 
  - Docker Version : 20.10.17-1
  - Docker Compose Version : 2.6.1-1

**Describe the bug**
bbproxy container fail to start. When running `budi hosting --status` or `docker stats` the container is in `restarting` state.

Error mesage :

```
$ docker start -i bbproxy
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: ipv6 not available
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/07/16 09:20:44 [emerg] 1#1: socket() [::]:10000 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:10000 failed (97: Address family not supported by protocol)
```

**To Reproduce**
1. Install `node`, `npm`, `docker`, `docker-compose` then `@budibase/cli`.
2. `mkdir budibase && cd budibase`
3. `budi hosting --init`
4. `budi hosting --start`
5. All the other containers start successfully, but `bbproxy` keep restarting.

**Expected behavior**
All the containers would launch and budibase would be accessible at http://localhost:10000.

**System**
- OS: Manjaro Linux x86_64
- Host: 81BD Lenovo ideapad 720S-14IKB
- Kernel: 5.15.53-1-MANJARO
- Packages: 2225 (pacman), 46 (flatpak)
- Shell: bash 5.1.16
- DE: Plasma 5.24.6
- Terminal: konsole
- CPU: Intel i7-8550U (8) @ 1.800GHz

**Additional context**

**IPV6 is willingly deactivated on my PC since my VPN does not support it.**

Installing _budibase_ worked well with _Docker Desktop_ (same machine, same config, literally an hour before), but for Arch (Manjaro) there is only a manual installer (manual updates also) and I prefer to use _docker CLI_ since it is much more lightweight. I first installed _budibase_ trough _Docker Desktop_, and it went all good, then I uninstalled _Docker Desktop_ and tried to reinstall it with _docker CLI_ but got the error message.

I **fixed it** by copying an empty file in place of /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh (`$ docker container cp 10-listen-on-ipv6-by-default.sh bbproxy:/docker-entrypoint.d`) and commenting the line `# listen  [::]:10000 default_server;` in `nginx.conf` (`$ docker container cp nginx.conf bbproxy:/etc/nginx`).

Now budibase is running well on my local machine with docker CLI. :)

**Disclaimer**
Not sure if this has to do with a script related to budibase or to nginx, or is specific to my config. Since I noticed a different behaviour with Docker Desktop than the CLI tool, and that I found an easy (not reliable for long time I guess) fix, I thought I should share it with you.

**Comment by jonnymccullagh** [comment]
I was able to replicate this bug on a Linux box with IPv6 enabled. 
In the nginx/proxy container the scripts under /docker-entrypoint.d are numbered so they run with `/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh` running first and removing any mention of IPv6. Afterwards `20-envsubst-on-templates.sh` runs and puts an `nginx.conf` in place that contains an IPv6 line. So the IPv6 config line is not removed.

To rectify that I have modified the [Dockerfile](https://github.com/Budibase/budibase/blob/master/hosting/proxy/Dockerfile) to delete the file `10-listen-on-ipv6-by-default.sh` and replace it with `80-listen-on-ipv6-by-default.sh`([source](https://github.com/Budibase/budibase/blob/master/hosting/proxy/80-listen-on-ipv6-by-default.sh)). With the `80` at the start of the file name it runs after the envsubst script and so acts to remove any IPv6 lines in the config files.

I tested the new image on a Linux box rebooting with IPv6 on and off.  

Please pull the 'latest' (SHA 4ed89e90c16c) image from [dockerhub](https://hub.docker.com/r/budibase/proxy) to get this change.

**Comment by lolcabanon** [comment]
Awesome, thanks!
