### ISSUE TITLE
Docker Single Image Not Working

### ISSUE THREAD

**Issue by Elliot-Construct** [Budibase/budibase#6753]
**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: <version> 
  - App Version: latest
  
**Describe the bug**

New single image doesn't provision and results in "502 Bad Gateway" error when attempting to load using browser.

Docker Logs output the following on a reoccuring loop:
```
[notice] 2022-07-16T11:02:03.322584Z couchdb@127.0.0.1 <0.3956.0> 6005c0d865 localhost:5984 127.0.0.1 1c1eb47f8f6c431b9d35c7d8a0ba4038 GET /global-db/ 200 ok 3
[notice] 2022-07-16T11:02:03.340529Z couchdb@127.0.0.1 <0.3957.0> 7f92d746c2 localhost:5984 127.0.0.1 1c1eb47f8f6c431b9d35c7d8a0ba4038 GET /global-db/migrations? 404 ok 1
[notice] 2022-07-16T11:02:08.156713Z couchdb@127.0.0.1 <0.4021.0> d47eed24b3 localhost:5984 127.0.0.1 1c1eb47f8f6c431b9d35c7d8a0ba4038 GET /global-db/ 200 ok 2
[notice] 2022-07-16T11:02:08.172512Z couchdb@127.0.0.1 <0.4022.0> 37956cabfd localhost:5984 127.0.0.1 1c1eb47f8f6c431b9d35c7d8a0ba4038 GET /global-db/migrations? 404 ok 1
[notice] 2022-07-16T11:02:13.419675Z couchdb@127.0.0.1 <0.4074.0> 70cb805608 localhost:5984 127.0.0.1 1c1eb47f8f6c431b9d35c7d8a0ba4038 GET /global-db/ 200 ok 2
[notice] 2022-07-16T11:02:13.434517Z couchdb@127.0.0.1 <0.4075.0> 3e054d4aef localhost:5984 127.0.0.1 1c1eb47f8f6c431b9d35c7d8a0ba4038 GET /global-db/migrations? 404 ok 1
[notice] 2022-07-16T11:02:13.801095Z couchdb@127.0.0.1 <0.4076.0> ba2dd4e75f localhost:5984 127.0.0.1 undefined GET / 200 ok 0
```
`Last output | ERROR: Budibase is not running ERROR: Budibase backend is not running Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe. Warning: AUTH failed ERROR: Redis is down`

**To Reproduce**
```
docker run -d -t \
  --name=budibase\
  -p 8931:80 \
  -v /home/budibase/data:/data \
  --restart unless-stopped \
  budibase/budibase:latest
```

**Expected behavior**
Budibase to spin up and be provisioned correctly.

**Desktop (please complete the following information):**
 - Ubuntu running docker; browsed on windows running Firefox.

**Comment by kunduarnab** [comment]
Same issue on my M1 MAC

**Comment by eyegeegeewhy** [comment]
having the same issue, trying to run the single image on unraid (x86)

**Comment by aptkingston** [comment]
Our latest image is available and should fix this - could you try pulling and running it again?

**Comment by mike12345567** [comment]
Hi @eyegeegeewhy - what happens when you try to use the container in the browser? From the look of the logs there is nothing wrong, but I don't see any attempt to access the builder.

It should be available on `http://localhost:<port you've bound>/builder`

**Comment by eyegeegeewhy** [comment]
this works for me

**Comment by mike12345567** [comment]
Hi @eyegeegeewhy - sounds good, happy solution was found!

Going to close this issue as I believe the underlying issue has been resolved, if a new issue is found can open a separate issue.
