### ISSUE TITLE
webhook response always 200

### ISSUE THREAD

**Issue by nev-21** [Budibase/budibase#6761]
**Hosting**

- Self
  - Method: docker
  - Budibase Version: 1.1.4

**Describe the bug**
Webhook trigger (called with wrong data type) return 200 result. My Webhook need a field of type number. I have sent a string without numbers and the automation log show an error but the response of the webhook call is 200.

**To Reproduce**
1. Create a webhook. 
2. Setup the webhook sending a json with a number field.
3. Add an automation step "Create row"
4. Select a table that has a number field
5. Run the test with alphabetic character on the field, and it will show an error on create row.
6. Call the trigger from outside (exampler postman) with the field populated with alphabetic char, it will return 200.
7. Check the automation log, it has the error of the webhook trigger.

**Expected behavior**
The webhook trigger call, should return error (maybe 400 or 500)

**Screenshots**
![image](https://user-images.githubusercontent.com/89469783/179374349-efe503e2-3528-474f-a19e-c9e72954191c.png)

![image](https://user-images.githubusercontent.com/89469783/179374403-e9f3d205-d241-439c-be94-2c9dc0fe664b.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 103

**Comment by mike12345567** [comment]
Hi @nev-21 - this is a feature of how the webhooks work currently, there is no way to synchronously await the response of the automation (as it could be very long running) so the webhook simply triggers it and responds immediately.

In the future we might add a way to track the automation that you triggered by returning an automation run ID from the webhook call, but this is quite a big feature that will need spec'd separately to this feature.

If we did await the automation results in the webhook, then its highly likely you could run into timeout issues in the automation system is busy, or if you have a long delay in the automation itself.

**Comment by nev-21** [comment]
ok, thanks for the explanation @mike12345567 that makes sense for webhooks. An error should be returned only when the webhook didn't trigger correctly or other infrastructure things.
