### ISSUE TITLE
"Check for Update" - Ask for confirmation before appplying Update

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6774]
When you click on Check For Updates, if an Update is found, the user should be asked for Confirmation before applying the update.

Another way would be for the system to check for updates in the background, and when a new update exists alert the user with a bubble on the main menu and give him the option to apply the update.

<img width="643" alt="Screenshot 2022-07-18 at 12 40 44 PM" src="https://user-images.githubusercontent.com/80512170/179485361-98c6c48f-0c11-43c5-8145-ab28107873e5.png">

**Comment by saksham-jain** [comment]
Hey, @shogunpurple if this issue is not taken up can I take it?
Also please share the details of what flow is expected?

**Comment by shogunpurple** [comment]
Hi @saksham-jain - of course, thank you very much for the offer to contribute.

Here's a brief spec detailing how the feature should look:

**Conditions of Satisfaction (COS)**
- When the update button is clicked in the update UI, present the user with a modal
- If the user confirms the operation, continue the update as normal
- If they cancel, close the modal

You can see some examples of how to use our `Modal` component here in the codebase:
`budibase/packages/bbui/src/Modal/Modal.svench`

**The Modal**
- The modal should read "Are you sure you want to update your budibase installation?"
- There should be 2 buttons - `Confirm` and `Cancel`. (These should come as default in the `Modal/ModalContent` components.

Please let me know if you have any issues or questions.

**Comment by saksham-jain** [comment]
Thanks, @shogunpurple understood. You can assign this to me, I will create the PR soon.

**Comment by aditya-shelke99** [comment]
Can I work on this ?
