### ISSUE TITLE
Bindings issue with MongoDB

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6778]
### Discussed in https://github.com/Budibase/budibase/discussions/6771

<div type='discussions-op-text'>

<sup>Originally posted by **cyl1234567** July 18, 2022</sup>
Hi, Every one

I can run a MongoDB update directly. But when I use bindings, the system always toast a query error.
("ID" is a field in numeric format)

Is this a bug or am I missing a specific escape character?

app version: 1.1.7

screen shot:
- query directly
  - <img width="527" alt="image" src="https://user-images.githubusercontent.com/109498463/179445455-7bf5ee52-2fa1-4e37-9677-f4e3234753f6.png">
- use bindings
  - <img width="522" alt="image" src="https://user-images.githubusercontent.com/109498463/179445831-bae8d99a-e4a6-4d8d-b526-1d6a0920cf95.png">
  - <img width="321" alt="image" src="https://user-images.githubusercontent.com/109498463/179446305-e37ab1c4-975d-4144-b83c-5c166a8ffb1b.png">

</div>

Replicated for **updateOne**

**Comment by melohagan** [comment]
I think this is actually an issue with the bindings.

![bindings_cleared](https://user-images.githubusercontent.com/101575380/179492678-b5523fcd-99bc-457a-9742-623caa4515a1.gif)

![Screenshot 2022-07-18 at 11 25 48](https://user-images.githubusercontent.com/101575380/179492766-83b88ade-1482-4bc5-a705-eaec4d9b99f1.png)

**Comment by deanhannigan** [comment]
In the second example  the binding needs to be changed from

`{  "id" : { "$eq" : {{ id }} }` to 
`{  "id" : { "$eq" : "{{ id }}" }`

The binding expressions must be added a strings to any query body.

The bug here was related to a UI change that caused the value field to clear.

**Comment by cyl1234567** [comment]
> In the second example the binding needs to be changed from
> 
> `{ "id" : { "$eq" : {{ id }} }` to `{ "id" : { "$eq" : "{{ id }}" }`
> 
> The binding expressions must be added a strings to any query body.
> 
> The bug here was related to a UI change that caused the value field to clear.

Hi @deanhannigan,

"id" is a numeric field in the second example.
Is it possible to use binding expressions without double quote? otherwise, I thinks the update can't match any document.

mongo db document:
```
{
	"_id" : ObjectId("62d54a93aaee5e087b5a90d5"),
	"id" : 11,
	"create_date" : {
		"$date" : 1658145427141
	},
        "track": false
}
```

**Comment by deanhannigan** [comment]
Hi @cyl1234567! Apologies, I misunderstood the issue here.  It is possible to add your binding without quotes and it should resolve to the appropriate type in the request. 

Also, I've raised a PR to fix the UI issue outlined by @melohagan.

**Comment by cyl1234567** [comment]
Hi @deanhannigan,

Thanks for the clarification.

**Comment by cyl1234567** [comment]
It's works fine on v1.1.21. 

<img width="156" alt="image" src="https://user-images.githubusercontent.com/109498463/180678364-c22f2e77-2a94-486d-a36e-f965f7a7a666.png">

<img width="506" alt="image" src="https://user-images.githubusercontent.com/109498463/180678296-74d88ae1-9307-405a-b930-6c4a6bbce44b.png">

**Comment by melohagan** [comment]
This issue also popped up in discussions: https://github.com/Budibase/budibase/discussions/6874

The Date and Number type fields do not seem to be working correctly within forms.
