### ISSUE TITLE
Allow customising links for exact roles

### ISSUE THREAD

**Issue by Elliot-Construct** [Budibase/budibase#6790]
The new design layout links do not allow you to have different links for different users.

I have a few set to basic; and a few set to power... and if you are a power user you just see all of them! This is a bug and needs addressing

**Comment by aptkingston** [comment]
Hey @Elliot-Construct. This is the way the links are supposed to work - the role is the minimum required role to view links, not the exact role. Notice the placeholder is named "Minimum role":
<img width="848" alt="image" src="https://user-images.githubusercontent.com/9075550/179549438-ea964ead-c8f1-4ff9-b4a2-89ab1f159578.png">

For example:
- Admins can view any links
- Power can view power, basic, public
- Basic can view basic, public
- Public can view public

Choosing no role is the same as choosing "Public", in that anyone can see the links.

If you're after a feature where only one type of role (and no others) can see a certain link then I can update this ticket to be a feature request for that. Is that what you would like?

**Comment by Elliot-Construct** [comment]
It's a feature we had and now no longer have due to the new system. Please can you fix this.

**Comment by aptkingston** [comment]
We've never had this feature - unless you mean using conditional UI on layouts to overwrite the links setting for each role. The new design makes it extremely fast and easy to solve most use cases - you can see additional, higher privilege pages if you have a higher role.

If you have a use case where you want a completely different set of links for users of different roles, you might be better to just disable the built in navigation completely and make your own (it's pretty simple - just a container and some links). You can very easily use conditional UI to show a certain set of links for a certain role, just like you used to do on the old design.

If we get other feedback that more people want this then we can consider adding a way to do this in the UI, but based on the feedback we had previously, the new system is exactly what was asked for. That's not to discredit your use case of course - which is why we can leave this open as a request and see if there is more demand for it.

**Comment by Elliot-Construct** [comment]
@mjashanks What's your take on this?

**Comment by Elliot-Construct** [comment]
It's lazy from the perspective of the end user. Because they won't have to create links for ALL of the roles manually. therefore it's a fix that reduces the features in favour of being lazy and having a quicker outcome.
If you perceived it as a direct insult to the contributors of this project then you are mistaken.

Furthermore... This is a feature that has been removed [possibly, as you say, by popular opinion?] but you shouldn't be removing features and then tell me that they haven't been removed or that they never existed. You are accusing me of being wrong or fabricating features which in turn is an insult to me.

**Comment by shogunpurple** [comment]
@Elliot-Construct - "being lazy and having a quicker outcome" is false and to be honest totally misplaced. A quicker outcome is the exact reason it was built in that fashion. It's not lazy to do work that isn't necessary for 90% of use cases - in fact it's inefficient to do so. As an open source project, we are always welcome to PRs and contributions, and you are always welcome to stay on an older version, or fork the repo and perform updates as you wish.

You were never accused of being wrong - in fact in the sentence directly after it was caveated by saying that custom layouts were the way to do this in previous versions.

Solutions have been offered - you can get rid of the navigation, and use a completely custom screen to build the same functionality - in fact, we even provided tools to allow you to do this more easily using your existing custom layouts and copy and paste.

I can also assure you @mjashanks, myself and the rest of the team were behind the decision to simplify and speed up budibase development as much as possible, as was much of our community.

This behaviour isn't helping anyone. We are always open to feedback - it's what drives the product and we appreciate all of it. What we are not open to is being dictated to and spoken to in that manner. Please stop changing the title, I'll have to lock the discussion on this issue to contributors if this childish behaviour continues.

**Comment by Elliot-Construct** [comment]
- A simple checkbox that changes it from minimum role to equals role shouldn't be too much to ask. Especially considering you are excluding a minority of developers that according to your own estimates reach a huge 10% of use cases! Which is a large minority group.

> A quicker outcome is the exact reason it was built in that fashion.
How is what you just said any different from what I said? I said it had been changed to favour a quicker outcome and less effort.
>You were never accused of being wrong - in fact in the sentence directly after it was caveated by saying that custom layouts were the way to do this in previous versions.

This statement is hereby proven false by this specific comment; thank you for yet again accusing me of being wrong in a comment. 

>We've never had this feature - unless you mean using conditional UI on layouts to overwrite the links setting for each role. The new design makes it extremely fast and easy to solve most use cases - you can see additional, higher privilege pages if you have a higher role.

Furthermore I was the person who wrote that caveat that you referred to in order to outline why your colleague was incorrectly suggesting that I was wrong in my statement

> Solutions have been offered - you can get rid of the navigation, and use a completely custom screen to build the same functionality - in fact, we even provided tools to allow you to do this more easily using your existing custom layouts and copy and paste.

This may be true however it's a temporary solution that radically reduces the design elements (You can't sticky header a container.) So it's a poor solution compared to previous features. and as for your tools.. I assume you are referring to the copy layout tool? That has absolutely no place in this discussion and is wholly irrelevant because I can't copy the links of the layout; therefore it's not worth mentioning [albeit a cool and useful tool for other use cases.]

>Please stop changing the title
The title was changed by your colleague to "reflect the scope of work required to deliver the feature you are requesting"; I agreed with his specific concern here and only changed the title further to further quantify the scope as well as the purpose

I am looking for a solution for all parties here, a solution that requires the minimum amount of contributor effort and you two  have called me out for being incorrect when I'm not and accused me of insulting people when I haven't

I request you return the title to what it previously was and stop being negative towards somebody who's trying to help you make Budibase better.

**Comment by Elliot-Construct** [comment]
@shogunpurple bump

> I request you return the title to what it previously was so the "10%" minority might find this issue more easily.

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/10645
