### ISSUE TITLE
Single Image healthcheck fails if REDIS_PASSWORD is not set

### ISSUE THREAD

**Issue by alphafalcon** [Budibase/budibase#6795]
**Hosting**
- Self
  - Method:  docker single image

**Describe the bug**
When environment vars are not set in the compose file or on the docker command line, the healthcheck script fails because the REDIS_PASSWORD variable is not set in the script.

in a swarm environment this leads to constantly restarting the container.

Adding the snippet
`if [ -f "/data/.env" ]; then
    export $(cat /data/.env | xargs)
fi`
from the runner.sh script at the beginning of healthcheck.sh loads the variables and fixes this.

**Comment by mike12345567** [comment]
Hi @alphafalcon - this issue should be resolved in the latest versions of the single image.
