### ISSUE TITLE
Enabling a search column on a date field greys out the search box

### ISSUE THREAD

**Issue by aidenmitchell** [Budibase/budibase#6833]
**Hosting**
- Cloud
  - Tenant ID: bspit

**Describe the bug**
Enabling a search column on a date field greys out the search box, rendering it unusable.

**To Reproduce**
1. Create a DB with dates in it
2. Create a table with data from the DB, and add a search column on the date field.

**Expected behavior**
Search box is not greyed out.

**Screenshots**
![image](https://user-images.githubusercontent.com/30846409/180094516-80db44c0-d95f-44e5-9580-79a974217071.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 103.0.5060.114 (Official Build) (arm64)

**Comment by aidenmitchell** [comment]
@aptkingston When will this be pushed out to the cloud tenants? Thank you!

**Comment by shogunpurple** [comment]
@aidenmitchell The release goes out on monday :)
