### ISSUE TITLE
Duplicating many form steps causes the design view to freeze and an error to appear in the browser console

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#6835]
**Hosting**

- Self
  - Method: BudiCLI
  - Budibase Version: 1.1.17 
  - App Version: 1.1.17 
 
**Describe the bug**
Duplicating many form steps causes the design view to freeze and an error to appear in the browser console.

**To Reproduce**
1. Create a form
2. Add a form step
3. Add a headline and paragraph in the form step
4. Rename form step to something else
5. Duplicate it five or six times
6. Set each duplicate as its own step
7. The error should appear in the console

**Expected behavior**
For this not to happen

**Screenshots**
![image](https://user-images.githubusercontent.com/97764630/180100433-f3a16f40-43cb-436a-b56b-d34d36930b21.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103.0.5060.114

**Additional context**
Exported app test app
[Test-export-1658360102562.txt](https://github.com/Budibase/budibase/files/9155043/Test-export-1658360102562.txt)

**Comment by aptkingston** [comment]
This should be fixed by the PR I just merged today https://github.com/Budibase/budibase/pull/6735
Will probably get deployed soon :+1:
