### ISSUE TITLE
Cannot drop on the root "Screen" component

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6842]
**Hosting**
- Cloud
  - Tenant ID: bb.budibase.app

**Describe the bug**
Whenever I drag a form into a container, I cannot drag the form out of the container.
This also applies to two containers, etc.

**To Reproduce**
1. Add new screen
2. Add form component
3. Add container component to screen
4. Drag the form into the container
5. Try to drag the form component into the screen. It wont allow you.

**Expected behavior**
I should be able to unnest a form (or any other component) from a container. 

**Screenshots**
![container-bug](https://user-images.githubusercontent.com/101575380/180236011-801b601e-476d-4ddd-8607-cfb0ba9c8a4f.gif)

**Comment by aptkingston** [comment]
What browser and OS are you on? This works as expected for me. Might be specific to some environment.

**Comment by aptkingston** [comment]
Ah I see what it is - hover slightly further down, like around where the line is, and it works. It does nothing if you hover higher like on top of the word "Screen". I'll have a look!
