### ISSUE TITLE
MacOS setup failing with following error

### ISSUE THREAD

**Issue by saksham-jain** [Budibase/budibase#6843]
`➜  budibase-self git:(develop) ✗ node -v
v18.6.0
➜  budibase-self git:(develop) ✗ docker -v
Docker version 20.10.14, build a224086
➜  budibase-self git:(develop) ✗ docker-compose -v
docker-compose version 1.29.2, build 5becea4c
➜  budibase-self git:(develop) ✗ yarn -v
1.22.19
➜  budibase-self git:(develop) ✗ jest --version
28.1.3
➜  budibase-self git:(develop) ✗ lerna --version
5.1.8
➜  budibase-self git:(develop) ✗ yarn setup
yarn run v1.22.19
$ node ./hosting/scripts/setup.js && yarn && yarn bootstrap && yarn build && yarn dev
Docker installed - continuing.
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
$ lerna bootstrap && lerna link && ./scripts/link-dependencies.sh
lerna notice cli v3.14.1
lerna info Bootstrapping 10 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 10 packages
lerna notice cli v3.14.1
lerna info Symlinking packages and binaries
Linking backend-core
warning There's already a package called "@budibase/backend-core" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
/Users/saksham/Desktop/self/budibase-self
Linking string-templates
warning There's already a package called "@budibase/string-templates" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
/Users/saksham/Desktop/self/budibase-self
Linking types
warning There's already a package called "@budibase/types" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
/Users/saksham/Desktop/self/budibase-self
Linking bbui
warning There's already a package called "@budibase/bbui" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
/Users/saksham/Desktop/self/budibase-self
$ lerna run build
lerna notice cli v3.14.1
lerna info Executing command in 9 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@budibase/types' in 5.0s:
$ rimraf dist/
$ tsc -p tsconfig.build.json
lerna info run Ran npm script 'build' in '@budibase/string-templates' in 22.7s:
$ tsc && rollup -c
lerna info run Ran npm script 'build' in '@budibase/backend-core' in 24.9s:
$ rimraf dist/
$ tsc -p tsconfig.build.json
lerna info run Ran npm script 'build' in '@budibase/worker' in 16.6s:
$ rimraf dist/
$ tsc -p tsconfig.build.json
$ copyfiles -u 1 src/**/*.hbs dist/
lerna info run Ran npm script 'build' in '@budibase/bbui' in 34.5s:
$ rollup -c
lerna info run Ran npm script 'build' in '@budibase/cli' in 72.9s:
$ rm -rf prebuilds 2> /dev/null && cp -r node_modules/leveldown/prebuilds prebuilds
$ yarn prebuild && renamer --find .node --replace .fake 'prebuilds/**' && pkg . --out-path build && yarn postbuild
$ rm -rf prebuilds 2> /dev/null && cp -r node_modules/leveldown/prebuilds prebuilds
✔︎ prebuilds/android-arm/node.napi.armv7.node → prebuilds/android-arm/node.napi.armv7.fake
✔︎ prebuilds/android-arm64/node.napi.armv8.node → prebuilds/android-arm64/node.napi.armv8.fake
✔︎ prebuilds/darwin-x64/node.napi.node → prebuilds/darwin-x64/node.napi.fake
✔︎ prebuilds/linux-arm/node.napi.armv6.node → prebuilds/linux-arm/node.napi.armv6.fake
✔︎ prebuilds/linux-arm/node.napi.armv7.node → prebuilds/linux-arm/node.napi.armv7.fake
✔︎ prebuilds/linux-arm64/node.napi.armv8.node → prebuilds/linux-arm64/node.napi.armv8.fake
✔︎ prebuilds/linux-x64/node.napi.glibc.node → prebuilds/linux-x64/node.napi.glibc.fake
✔︎ prebuilds/linux-x64/node.napi.musl.node → prebuilds/linux-x64/node.napi.musl.fake
✔︎ prebuilds/win32-ia32/node.napi.node → prebuilds/win32-ia32/node.napi.fake
✔︎ prebuilds/win32-x64/node.napi.node → prebuilds/win32-x64/node.napi.fake

Rename complete: 10 of 19 files renamed.

> pkg@5.7.0
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/leveldown/prebuilds
  %2: path-to-executable/prebuilds
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/leveldown/prebuilds
  %2: path-to-executable/prebuilds
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: ../backend-core/node_modules/leveldown/prebuilds
  %2: path-to-executable/prebuilds
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: ../backend-core/node_modules/leveldown/prebuilds
  %2: path-to-executable/prebuilds
$ rm -rf prebuilds 2> /dev/null
$ rm -rf prebuilds 2> /dev/null
lerna info run Ran npm script 'build' in '@budibase/client' in 51.3s:
$ rollup -c
lerna ERR! yarn run build exited 127 in '@budibase/builder'
lerna ERR! yarn run build stdout:
$ routify -b && vite build --emptyOutDir
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
/bin/sh: routify: command not found
error Command failed with exit code 127.

lerna ERR! yarn run build exited 127 in '@budibase/builder'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by melohagan** [comment]
Hey @saksham-jain 

Are you at the root directory when you're running `yarn setup` ?

Try this:

- `yarn nuke`
- `yarn clean`
- `yarn bootstrap`
- `yarn dev`

**Comment by saksham-jain** [comment]
When I ran `yarn nuke ` it failed with following error-

➜  budibase-self git:(develop) ✗ yarn nuke
yarn run v1.22.19
$ yarn run nuke:packages && yarn run nuke:docker
$ yarn run restore
$ yarn run clean && yarn run bootstrap && yarn run build
$ lerna clean
lerna notice cli v3.14.1
lerna info Removing the following directories:
lerna info clean packages/backend-core/node_modules
lerna info clean packages/bbui/node_modules
lerna info clean packages/builder/node_modules
lerna info clean packages/cli/node_modules
lerna info clean packages/client/node_modules
lerna info clean packages/frontend-core/node_modules
lerna info clean packages/server/node_modules
lerna info clean packages/string-templates/node_modules
lerna info clean packages/types/node_modules
lerna info clean packages/worker/node_modules
? Proceed? Yes
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/backend-core/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/bbui/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/builder/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/cli/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/client/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/frontend-core/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/server/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/string-templates/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/types/node_modules
lerna info clean removing /Users/saksham/Desktop/self/budibase-self/packages/worker/node_modules
lerna success clean finished
$ lerna bootstrap && lerna link && ./scripts/link-dependencies.sh
lerna notice cli v3.14.1
lerna info Bootstrapping 10 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna WARN EREPLACE_EXIST @budibase/backend-core is already installed for @budibase/server. Replacing with symlink...
lerna WARN EREPLACE_EXIST @budibase/types is already installed for @budibase/server. Replacing with symlink...
lerna WARN EREPLACE_EXIST @budibase/backend-core is already installed for @budibase/worker. Replacing with symlink...
lerna WARN EREPLACE_EXIST @budibase/types is already installed for @budibase/worker. Replacing with symlink...
lerna success Bootstrapped 10 packages
lerna notice cli v3.14.1
lerna info Symlinking packages and binaries
Linking backend-core
warning There's already a package called "@budibase/backend-core" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
/Users/saksham/Desktop/self/budibase-self
Linking string-templates
warning There's already a package called "@budibase/string-templates" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
/Users/saksham/Desktop/self/budibase-self
Linking types
warning There's already a package called "@budibase/types" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
/Users/saksham/Desktop/self/budibase-self
Linking bbui
warning There's already a package called "@budibase/bbui" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
/Users/saksham/Desktop/self/budibase-self
$ lerna run build
lerna notice cli v3.14.1
lerna info Executing command in 9 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@budibase/types' in 5.5s:
$ rimraf dist/
$ tsc -p tsconfig.build.json
lerna ERR! yarn run build exited 1 in '@budibase/backend-core'
lerna ERR! yarn run build stdout:
$ rimraf dist/
$ tsc -p tsconfig.build.json
error TS2688: Cannot find type definition file for 'jest'.
  The file is in the program because:
    Entry point of type library 'jest' specified in compilerOptions
src/cache/writethrough.ts(29,7): error TS4078: Parameter 'db' of exported function has or is using private name 'PouchDB'.
src/cache/writethrough.ts(67,31): error TS4078: Parameter 'db' of exported function has or is using private name 'PouchDB'.
src/cache/writethrough.ts(80,7): error TS4078: Parameter 'db' of exported function has or is using private name 'PouchDB'.
src/cache/writethrough.ts(98,7): error TS4031: Public property 'db' of exported class has or is using private name 'PouchDB'.
src/cache/writethrough.ts(102,9): error TS4063: Parameter 'db' of constructor from exported class has or is using private name 'PouchDB'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@budibase/backend-core'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
