### ISSUE TITLE
The ability to add other apps' databases as a datasource

### ISSUE THREAD

**Issue by Elliot-Construct** [Budibase/budibase#6854]
I think it would completely change the game if it were possible to select other apps' Budibase db's as a selectable data source.

This would allow inter-app operability and I can't imagine it would be too hard to achieve.

**Comment by mike12345567** [comment]
Hi @Elliot-Construct - sadly this is not the easiest thing to implement, generally cross database communicate is frowned upon when using CouchDB as it means that any single API request could be making requests to multiple shards, it makes some tasks a bit harder to reason about.

We do have a plan for this however, a larger feature that has been discussed and is something we have on our roadmap, although I can't say exactly when it will be released: https://github.com/Budibase/budibase/issues/4359

A global datasource would be built at the portal level in Budibase, then could be accessed in every single app, this could be a Postgres table, a snowflake query, REST request or even an internal CouchDB table. Building it this way would give us more control over how apps access data outside their database.

Going to close this issue as the global datasources is the way we plan to approach this problem, we think it will be a really killer feature but there is quite a bit to it, making it work in a great way is really important to us.

For now you can use an external datasource like say Postgres, and then just duplicate the datasource within the apps, this is frustrating but its a workaround for the time being!
