### ISSUE TITLE
Replace "+" with action buttons for components and screens

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#6861]
To make it clear when you are adding a screen or a component we want to add clearly labelled buttons to each of the panels

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/f69da6ce-c2f5-4759-95fe-52ebf9f54879)  

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/f13f1da1-a10d-411b-ae27-d3bc5cdfc291)

**Comment by joebudi** [comment]
Hey! Just a heads up, we follow Spectrum's pattern for text within buttons:
https://spectrum.adobe.com/page/button/#Use-sentence-case
