### ISSUE TITLE
Ability to be more front end as well making use of the auth0 via a wordpress setup for hosting sellers

### ISSUE THREAD

**Issue by ThunderM16** [Budibase/budibase#6871]
**Describe the feature request**
So more or less the idea is allowing front end 
+ custom domains 
+ dns management 
+ File Manager to manage files internally more easily
+ 
And a little more integration regarding hosting, I've used https://bubble.io and tbh its a pain edit this design this that this and blah blah blah I'm not a hard coder by trade so thus hinders some things and I need to figure out a new strategy to perform the action which is normally something I can figure out but with all said and done when I stumbled upon Budibase I was honestly amazed, its a nice and clean platform allowing massive db integration and can be used for a lot more if there were a few more features even offered more tailored to hosting providers as once tools for hosting providers is incorporated much much more can be designed via budibase

**Comment by jonnymccullagh** [comment]
Hi @ThunderM16 
There are several features listed in your request:
- auth0 integration is documented [here](https://docs.budibase.com/docs/sso-with-auth0)
- Wordpress: adding a wordpress plugin that can integrate with the Budibase API certainly sounds like an interesting idea. I will close this ticket and create a new ticket to track that feature. 
- Custom domains: this will likely be a pro feature for those who do not want to self-host
- File Manager: A file manager for the S3/minio storage is something I will raise with the team to see if it is possible

**Comment by Rory-Powell** [comment]
@ThunderM16 could you raise separate issues for these requests as @jonnymccullagh mentioned
