### ISSUE TITLE
Action "Execute Query" should have the option NOT to be asynchronous

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6872]
When you use a button Action event to execute a Query, that query should not be executed in ASYNC mode as further actions (like setting an App.State as discussed here #6808 may depend on the result.

**Comment by chiptech-mitchell** [comment]
I am also encountering this issue, I hope this will be worked on soon

https://github.com/Budibase/budibase/discussions/8833

**Comment by ecxs** [comment]
probably also issue https://github.com/Budibase/budibase/discussions/9328#discussioncomment-4755941

**Comment by Rory-Powell** [comment]
@poirazis just to confirm, the intention here is to fire a query, not wait for the result, and proceed with other actions immediately?

**Comment by poirazis** [comment]
hey @Rory-Powell 
exactly the opposite :) the need was that the next action ( validate Form in my case ) shouldn't run before the Execute Query has returned as the validation was depended on the output of the query.

So the need was to make an Execute Query Action to be synchronous.

**Comment by Rory-Powell** [comment]
This is actually the case today. As an example:
https://user-images.githubusercontent.com/8755148/231448990-df051fad-335e-4c7a-87fa-d5f3b5d9fe7b.mov

query, followed by update state
![image](https://user-images.githubusercontent.com/8755148/231449026-970c7a03-2dda-4b07-b331-bcee0370d374.png)

referencing the query result
![image](https://user-images.githubusercontent.com/8755148/231449038-7d6bff0c-ddb0-4ae8-b888-8810994510be.png)

Closing for now. If this is still an issue for you could you raise a bug with an export that shows the behaviour, thanks!
