### ISSUE TITLE
DigitalOcean Rest Query SSL Error - Allow self-signed certificates

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6885]
### Discussed in https://github.com/Budibase/budibase/discussions/6849

<div type='discussions-op-text'>

<sup>Originally posted by **jkatsabanissp** July 21, 2022</sup>
Hello,

Fiddling with Budibase on a DO droplet and attempting to connect to a REST API. The endpoint requires ignoring invalid or self-signed certificate errors similar to -k or -insecure in CURL. </div>

----

Given I am hosting Budibase with DigitalOcean
Then I want to be able to make a REST call with SSL turned off.

**Comment by Rory-Powell** [comment]
The `rejectUnauthorized` option at the rest datasource level should now support this
