### ISSUE TITLE
Update screens list (access indicator) 

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#6886]
# Problem

Access is not clear. The colours are not memorable and the indicator looks like a notification indicator and feels out of place.

# Solution

- Update the colours 
 - Admin - Red
 - Power - Amber
 - Basic - Green
 - Public - Blue
 - Custom - Black

- Update the access to a rounded square positioned on the right
- Move the home icon to the right
- Remove the screen icon to make the home icon more obvious
- Make the quick screen switcher above the preview quiet, bold and auto width.

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/daacbc44-1a41-4e24-a934-a892e0778cb9)

**Comment by joebudi** [comment]
This looks awesome @AndyWhann
