### ISSUE TITLE
Add binding for option picker search box

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6889]
### Discussed in https://github.com/Budibase/budibase/discussions/6878

<div type='discussions-op-text'>

<sup>Originally posted by **colonyshipforsale** July 25, 2022</sup>
Hello all,

is it possible to use the option picker to also add an entry if autocomplete did not yield a result?

Below you can see part of an "add Row" form where the user has to populate several fields and should reuse existing values wherever possible, but add also values, if none where found. Similar to how "tagging" usually works whereas a tag is added if none where found ..?

Worded differently ...

As an "option picker" user i would like to not only autocomplete existing values found within a column (budibase db) (see below) like eg. "doctor" BUT if not found, the same input field that is used for searching, should add a value like eg. "doctor who".

Please let me know if it's possible with reasonable effort? Any help/hint is appreciated, many thanks!

![option picker search and add options](https://user-images.githubusercontent.com/73785468/180738735-a630e1fa-7412-4545-8849-b684ef174359.jpg)
</div>

----

Could this be opened up by adding a binding for the option pickers search box?

**Comment by aptkingston** [comment]
This isn't possible with our internal database as the options must be within a specific set, so we shouldn't allow adding custom options via an options picker. I understand when using custom datasource this is a valid thing to do, so we either need to enable this dynamically based on the datasource (harder) or add a checkbox to allow this as a setting for option fields (easier). If you enabled it for internal DBs you'll just be hit by an error, so it's fine to allow it to be checked always.

**Comment by melohagan** [comment]
I hadn't added it to the body of the feature (which I've done now) but I was thinking more of having a binding for the search box, and then it'd be up to the user to build out the functionality described with the data provider option picker source.

But if it's doable another way that's good too!

**Comment by abdennor** [comment]
@melohagan hello what you're proposing is very interesting, i'm new to Budibase and im trying to acheive the same thing from option picker just like googleSheet UX in advanced table the issue lie in the missing value of search term typed when activating the autocomplet feature which is great, im trying to use custom javascript to grap the search value but it seem long to do as @aptkingston said before its better to use checkbox option to chose between select or insert im looking forward to see what you've could accomplish

**Comment by kasgithub8** [comment]
Is this still a feature thats being added to budibase?

**Comment by melohagan** [comment]
Hey @kasgithub8 

There's no immediate plans to work on this, however it could be a good candidate for a custom component: https://docs.budibase.com/docs/custom-component#example-custom-form-field-component
