### ISSUE TITLE
Ability to Choose The Correct SCreen Resolution of App in Low resolution Device.

### ISSUE THREAD

**Issue by Jivayu** [Budibase/budibase#6891]
Its A great Platform , i found Some days ago. while on working on it, i found too disturbance with the resolution of app.
some pc's are from low resolution so i cant do abt my lap screen reso but what i did is  "zoom in" so my browser show all app element in proper position. 

![budibase1](https://user-images.githubusercontent.com/9782164/180944574-ac859c4c-ef2a-4f5c-9f30-f2fedd01c045.jpg)
![budibase2](https://user-images.githubusercontent.com/9782164/180944593-33370725-e35f-45eb-b432-1decfbbd3d22.jpg)

App Resolutions are not too Precise Device ..

**Comment by Rory-Powell** [comment]
@Jivayu can you clarify the issue you're experiencing here?
