### ISSUE TITLE
Bind List component to a table with all types of column

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#690]
False boolean does not pull through. 
Relationships result in an "undefined relation row(s)"
![Screenshot 2020-10-12 at 10 48 50](https://user-images.githubusercontent.com/49767913/95732310-86140580-0c78-11eb-8a8b-456a57c03bb4.png)

**Comment by aptkingston** [comment]
Are you up to date from master @joebudi? I fixed this issue on Friday I think it was.

**Comment by joebudi** [comment]
I am not!

**Comment by aptkingston** [comment]
Close this one off sure if pulling from master fixes it 👍

**Comment by joebudi** [comment]
Does it fix the boolean issue too? :-)

**Comment by aptkingston** [comment]
Didn't spot that one, my bad! Looks like a classic case of bad falsiness checking. I'll fix that too.

**Comment by aptkingston** [comment]
This is fixed now.
