### ISSUE TITLE
Automation doesn't work outside of tests

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#6900]
**Describe the bug**
1 table with lots of different fields, during the Test Automation I have 0 problems.
When I'm creating a new row on the frontend it doesn't work and it throws me an automation error.

**To Reproduce**
1. Create "Row Created" Automation on Table
2. then add "Update Row"
3. add "trigger.row.[<Table Fields>]
4. Test Automation (which works perfectly fine)
5. Create a new row on the frontend
6. Automation Error:
![image](https://user-images.githubusercontent.com/95284278/181031201-10661082-6014-438f-962e-00ee54432c1d.png)

**Additional context**
I need to update a empty column per automation which doesn't work

**Comment by mike12345567** [comment]
Hi @kasgithub8 - I'm a little confused by what you mean with the step 3, `trigger.row.[]` as this looks like invalid syntax, could you please provide a screenshot of your update row configuration?

**Comment by kasgithub8** [comment]
_could you please provide a screenshot of your update row configuration?_

This works for the tests
![image](https://user-images.githubusercontent.com/95284278/181179256-de6f01f0-55b3-4d2e-9e24-16605f9219d7.png)

**Comment by mike12345567** [comment]
Hi @kasgithub8 - i've tried a few different ways to replicate this and haven't been able to, if you can provide a minimalist app exhibiting the behaviour that would really help in getting the problem resolved.

I tried the following:
1. Created a new app
2. Adding a table to it with a text column
3. Created an automation, with a `Row created` trigger and an `Update row` action, looking as such:
![image](https://user-images.githubusercontent.com/4407001/181303899-e9881e4b-b9ef-49c5-96fb-52ddc632dca5.png)
4. Add auto screens for table
5. Publish the app
6. Open auto-screen to create a row
7. Refresh page to see changes automation made to row, appears as such:
![image](https://user-images.githubusercontent.com/4407001/181304079-651bc85d-02cd-47d8-bd1e-12bcf471f921.png)

If you can provide full steps to create the problem from scratch, or provide an app export that exhibits the problem that would help with the issue.

**Comment by kasgithub8** [comment]
Nvm, your approach opened my eyes and i fixed it myself. Thanks!
