### ISSUE TITLE
Ejectable Blocks

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#6903]
When I'm using block components within the builder, I want to be able to eject them back into their original composition of components.

**COS**
- Add Eject button in block settlngs
- This button will expand the block out into its original tree
- Preserve settings and children on ejection - there cannot be loss of data as part of this operation

**Comment by poirazis** [comment]
Reset instead of Eject ?

**Comment by mike12345567** [comment]
Hi @poirazis - by eject we mean the ability to break a block up into the underlying components, e.g. Convert a table block into a data provider, table, search components etc. The idea being that a user might want to use a block initially, then convert to components for more granular control.

**Comment by poirazis** [comment]
Hey @aptkingston , this seems like halfway composite components functionality! :)

**Comment by aptkingston** [comment]
@poirazis it is! This is sort of the other side to what we call "custom blocks". This lets you break down blocks into components, and soon we hope to let users create their own blocks from groups of components too.
