### ISSUE TITLE
Ensure bindings work inside list component

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#691]
Attached images do not pull through.
![Screenshot 2020-10-12 at 10 52 36](https://user-images.githubusercontent.com/49767913/95732726-0c304c00-0c79-11eb-990d-16966a5b9093.png)

**Comment by aptkingston** [comment]
I fixed this on my recent PR - previously lots off different characters (notably forward slashes in the case of URL's) were being changed to the string "undefined". This should work now.
