### ISSUE TITLE
bb-warn: Ignoring conflict in write-through cache

### ISSUE THREAD

**Issue by yeoldegrove** [Budibase/budibase#6910]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.1.25
  - App Version: 1.1.25

**Describe the bug**
This warning message is in the logs (counts every minute):
```
bb-warn: Ignoring conflict in write-through cache
```
No further explanation is given on what exactly is wrong and how to fix it.

**To Reproduce**
Run `docker-compose logs`.

**Expected behavior**
Some more context about what exactly is wrong or how to fix it is given.

**Comment by mike12345567** [comment]
Hi @yeoldegrove - this is a warning that we've added to help the development team with debugging, but it is not an error scenario. You can safely ignore warnings, as they will only really come in use if you are experiencing an issue in the builder etc.
