### ISSUE TITLE
Data provider presenting ORA-00972: identifier is too long

### ISSUE THREAD

**Issue by willer007** [Budibase/budibase#6927]
**Hosting**
- Self
  - Method: Docker Compose
  - Budibase Version: 1.1.21

- Datasource
   - Oracle 11g 

**Describe the bug**
Tables which are used on others systems are presenting: ORA-00972: identifier is too long error when used as data provider, whe cannot change the tables because they are used as entities by multiple microservices

**To Reproduce**
1. Navigate to Data
2. Add a Oracle datasource
3. Navigate to Design
4. Create a Screen
5. Create a Data Provider
6. Select a table from oracle datasource with a column name size 27

**Expected behavior**
Sucessfull data fetch on the Data Provider 

**Screenshots**
![image](https://user-images.githubusercontent.com/39967705/181280403-9e067486-991d-4185-8385-81b83d417b70.png)

The table bellow have 20k rows
![image](https://user-images.githubusercontent.com/39967705/181281282-da8c2e37-0e5b-4320-9d4d-ad8afa54d5ba.png)

**Comment by aptkingston** [comment]
Closing as this issue looks unique to your environment.
