### ISSUE TITLE
Create a table with no columns or data... [test case]

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#694]
Create a table with no columns or data, add a bindable frontend component and hit preview app. Go back and add columns + data and see if it works.

After adding columns and data, I previewed the app and got the following error:
{"message":"ENOENT: no such file or directory, stat '/Users/joe/.budibase/ab654652add1478499ece7582947dbc6/public/main/index.html'","status":404}

**Comment by mike12345567** [comment]
I think this is resolved now, I haven't been able to re-create anything related to this test case.
