### ISSUE TITLE
[Test case] Deploy app, make some frontend updates, deploy again. Are they reflected?

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#695]
This worked when creating a new app, but not when using a template.

![Screenshot 2020-10-12 at 13 09 34](https://user-images.githubusercontent.com/49767913/95744961-2e7f9500-0c8c-11eb-95c4-0ad2d4d29ca7.png)

**Comment by shogunpurple** [comment]
@joebudi the current template is broken since the id changes - let's revisit this when we make a new template
