### ISSUE TITLE
Bindings V2: Binding Input V2

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#6962]
Spec: https://budibase.atlassian.net/wiki/spaces/PROD/pages/52101121/Bindings+V2

Replace the existing lightning bolt binding input with a much more intelligent autocomplete.

**COS**
- Provide toggles between HBS and JS
- Provides autocomplete with **only bindings and types** (the ones that currently exist in the search menu in the drawer)
- Provides further information/description of each binding as you cycle through the options
- Add to automations, design and data connectors UI
- Popout brings up the original bindings drawer, for more control over longer bindings
- Nest the bindings under their respective parent in the bindings list in drawer. Eg. `My Data Provider` and children such as `.Rows`

**Comment by deanhannigan** [comment]
Following up on this, I've added my notes from the CodeMirror spike here: https://budibase.atlassian.net/wiki/spaces/PROD/pages/81264641/CodeMirror+-+Autocomplete+Spike
