### ISSUE TITLE
Add padding settings to form and field group

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#6978]
**Describe the feature request**
The form and field group component allow the user to configure margin but not padding. When designed the create and update screen that's presented in a modal, padding is needed to control the width.

Without padding
<img width="1905" alt="CleanShot 2022-07-29 at 11 23 53@2x" src="https://user-images.githubusercontent.com/49767913/181739694-22a6e913-893f-4241-aec8-1722247dc93e.png">

With padding
<img width="1907" alt="CleanShot 2022-07-29 at 11 24 18@2x" src="https://user-images.githubusercontent.com/49767913/181739748-f880f144-9020-4dd4-8157-d981e4ff918e.png">

**Comment by melohagan** [comment]
This will be possible with the side panels. 
Adding margin will affectively add padding:

![Screenshot 2022-12-05 at 15 30 09](https://user-images.githubusercontent.com/101575380/205676392-42da43c2-9ef2-415e-b010-f14754e1faff.png)

Closing.
