### ISSUE TITLE
Delete images from image uploads

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#699]
There is no way to delete images from a column in a table. If there is a way, it is not obvious.

https://www.loom.com/share/b6e44a480ec646aca1d38301fe531efa

**Comment by kevmodrome** [comment]
What do you guys think about having a small "X" button on each image directly in the list that shows on the table? That would work well for the grid as well for deleting images

**Comment by kevmodrome** [comment]
Something like this: https://cln.sh/bwuYYI

**Comment by joebudi** [comment]
Nice. A white X with a circle, black background :-)

**Comment by shogunpurple** [comment]
@kevmodrome are you currently working on this?

**Comment by kevmodrome** [comment]
No, I didn't think it was supposed to be worked on this week, can get started on it tomorrow.
