### ISSUE TITLE
Bindings V2: Show full JS API in autocomplete

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#6992]
When I'm using the JavaScript binding input experience, I want to have autocomplete for all the standard JS keywords and functions, including arrays, objects and other primitives.

Additional context here;
https://codemirror.net/examples/autocompletion/

**COS**
- Dropdown of full context aware JS API when interacting with binding inputs, as well as their types

**Comment by arpadgabor** [comment]
Hello. Has there been any development in this direction? Not sure about CodeMirror, but with Monaco there's a way to add JSON objects as context for intellisense to work seamlessly. If there's interest in this direction, I'd be willing to lend a hand as I managed to get this working nicely for n8n to get autocomplete for the output of previous nodes.
