### ISSUE TITLE
"Single" record type initialise 

### ISSUE THREAD

**Issue by ghost** [Budibase/budibase#7]
We can create a "single" record.... i.e. one that is not part of a collection. A single record in the heirarchy is identified by the property `isSingle:true` and `type:"record"`

Currently, a single record is never being initialised. There are 2 places where this should happen
1. If the single record is on the root level, is should be initialised in appInitialise/initialiseData.js
2. If it is a child of another record, it should be initialised when a record of that type is created.

**Comment by mjashanks** [comment]
Completed in [Commit 8cad5e7](https://github.com/Budibase/budibase/commit/8cad5e72fef0f10148c764574f789ce357315d25)
