### ISSUE TITLE
[test case] Backend Pagination with a large amount of data

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#701]
Uploaded 1000 records and pagination failed

![Screenshot 2020-10-12 at 15 21 07](https://user-images.githubusercontent.com/49767913/95757108-99d26280-0c9e-11eb-84e5-1ada9051ef0f.png)

**Comment by aptkingston** [comment]
I'll quickly fix this on my branch that I'm about to PR.

**Comment by aptkingston** [comment]
@joebudi you happy with the blue or should I go back to the subtle grey?

![Capture](https://user-images.githubusercontent.com/9075550/95761618-7b6f6580-0ca4-11eb-920c-7dc85e4c4132.PNG)

**Comment by joebudi** [comment]
> @joebudi you happy with the blue or should I go back to the subtle grey?
> 
> ![Capture](https://user-images.githubusercontent.com/9075550/95761618-7b6f6580-0ca4-11eb-920c-7dc85e4c4132.PNG)
> 
> (Ignore the fact the numbers don't make sense there, it's just faked for testing)

Blue is nice - good shout. Anything 'selected/active' should be blue

**Comment by aptkingston** [comment]
![snakes](https://user-images.githubusercontent.com/9075550/95856155-7c120580-0d51-11eb-8a6d-ca0a0764f509.PNG)

Merged in earlier, so closing off now.
