### ISSUE TITLE
Multiselect - Default value unable to deselect

### ISSUE THREAD

**Issue by eyduh** [Budibase/budibase#7025]
**Hosting**
- Self
  - Method: docker-compose
  - Budibase Version: 1.1.21
  - App Version: 1.1.21

**Describe the bug**
I have set up a form where one field is a multi-select with a many-to-many relationship to another table. If I set a default value, I am unable to deselect it. If I were to try I end up selecting it twice.

**To Reproduce**
1. Set up a Two tables
2. Make a column in one of them with a many-to-many relationship to the other table
3. Make a multi-select form field, select the appropriate field.
4. Set Default value to something that is in the table
5. When publishing or previewing the app the default value will be selected, but it will be possible to select it again. It will not be possible to deselect the value.

**Expected behavior**
 The selection should be able to be deselected, and it should also not be possible to select the same value twice.

**Screenshots**
Default value correctly filled in when opening up preview, however, it is not selected in the drop down list:  
![Skärmavbild 2022-08-01 kl  18 14 14](https://user-images.githubusercontent.com/29815625/182196004-610bfc8f-459c-4519-b299-b9911e66c980.png)

It is possible to select it again instead of deselecting it:
![Skärmavbild 2022-08-01 kl  18 14 03](https://user-images.githubusercontent.com/29815625/182196490-663fa029-9713-4f29-8945-a59e6062957e.png)

**App Export**
app: [Stockmotion 2022-export-1659370930368.txt](https://github.com/Budibase/budibase/files/9235616/Stockmotion.2022-export-1659370930368.txt)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina / Alpine Linux
 - Browser Chrome / Firefox

**Additional context**
I have only tried this with a Budibase DB, I will be making similar apps in postgres over the next year so will try it out with postgres as well.

**Comment by deanhannigan** [comment]
Hi @eyduh, thanks for getting in touch. The relationship picker requires row ids to properly link an entry from the database into the picker. 

For this scenario, you can wrap your relationship picker with a datasource pointing to the `språk` table. 

With the datasource selected, you can also add in a filter to specifically target the values you wish to have as default. I have also included `Alabama` in the filter as this solution can potentially allow several defaults.
![Screenshot 2022-08-09 at 10 02 05](https://user-images.githubusercontent.com/5913006/183609492-187b34b0-3e82-49ba-a46a-a41d479ba870.png)

Nest the `Språk - Tal` field inside the new datasource.
![Screenshot 2022-08-09 at 10 04 45](https://user-images.githubusercontent.com/5913006/183609979-314336e3-5116-4039-9032-cd92d473715b.png)

With `Språk - Tal` selected, click on the lightning icon next to the `Default` field. Clear the previous value and open the javascript tab. The following code will retrieve the appropriate row ids to initialise the field. "Alabama" is included in the defaults array to demonstrate that several could be defined if needed.

```
//Any defaults you want to retrieve
const defaults = ["svenska", "Alabama"];

//Store the result rows
const result = $("dataLookup.Rows").filter(entry => {
	return defaults.indexOf(entry.value) > -1
})

//Parse the results into comma-separated row ids
const result_ids = result.reduce((acc, entry) => {
	acc.push(entry._id);
	return acc;
},[])

return result_ids.length ? result_ids.join(",") : null;
```

The updated version of the application is attached :
[Stockmotion.2022-updated-export-1660036305580.txt](https://github.com/Budibase/budibase/files/9289021/Stockmotion.2022-updated-export-1660036305580.txt)
 
Let me know if you run into any issues

**Comment by eyduh** [comment]
Right! Thanks! 

I had a look at the tables again after your helpful answer and tried a few things out:

There's no need to wrap the relationship picker in another data source, as long as I use the Row "UUID" from the Auto Columns - nor adding extra JS. ( Adding this does add extra function that can be helpful though. )

I used the copy row ID button ( ![Skärmavbild 2022-08-09 kl  14 17 53](https://user-images.githubusercontent.com/29815625/183645005-16912f22-bdaf-4d2d-84d7-17047c65ce9a.png) ) for swedish in the language table:
![Skärmavbild 2022-08-09 kl  14 12 49](https://user-images.githubusercontent.com/29815625/183644781-cfb89e31-3d2b-4048-b8fb-9b1201d64c83.png)
![Skärmavbild 2022-08-09 kl  14 24 19](https://user-images.githubusercontent.com/29815625/183646158-5d6a8472-970f-437f-ad54-658937498406.png)

Then added it to the default value both in the Multi-select wrapped in another data source and in the one not wrapped:
![Skärmavbild 2022-08-09 kl  14 15 01](https://user-images.githubusercontent.com/29815625/183645574-a44c0a85-01a3-4280-9ca6-d8f0af92b293.png)

It will then show up as the Default value in both Multi-Select picker, and it will be possible to deselect it.
![Skärmavbild 2022-08-09 kl  14 21 06](https://user-images.githubusercontent.com/29815625/183648112-503ffd3d-8dcb-4ded-a115-b6054c61556f.png)
![Skärmavbild 2022-08-09 kl  14 29 27](https://user-images.githubusercontent.com/29815625/183648314-1318d5ba-b3df-4aff-840c-e3f98b59e2f6.png)

Cheers!
