### ISSUE TITLE
Unable to edit app. Encountering errors everywhere. 

### ISSUE THREAD

**Issue by adamjdavies** [Budibase/budibase#7046]
**Hosting**
- Cloud
  - Tenant ID: tern.budibase.app
  - App ID: app_tern_64947965bb6644849c305366aa9d9cc6

**Describe the bug**
I'm having major issues with the platform at the moment. I keep getting errors all over when trying to edit data, the design, and automations. Additionally, each time I refresh the page I keep getting logged-out of the platform. I've also noticed that when navigating back to the account admin panel, I am being logged-out of the platform.

**To Reproduce**
Try to change anything in the app. An error will then appear. 

**Screenshots**
An example of the errors I'm getting when editing automations.  
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/64409787/182403836-29cbedda-759e-459b-ab0d-920eae595537.png">

**App Export**
[Receiving portal-export-1659451815249.txt](https://github.com/Budibase/budibase/files/9243260/Receiving.portal-export-1659451815249.txt)

**Desktop (please complete the following information):**
 - OS: macOS Monteray v12.5
 - Browser: Chrome
 - Version 103.0.5060.134

**Comment by shogunpurple** [comment]
Hi @adamjdavies - we just did a release, so there's a good chance that this was due to the platform updating live, which may have caused some interruption. Are you still experiencing issues?

**Comment by adamjdavies** [comment]
Hi @shogunpurple - I think that may have been it. I've just updated to v1.2.4 and everything seems to be working now. Thanks for the speedy response.
