### ISSUE TITLE
Error getting user groups

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#7050]
version 1.2.4, running through cli, the "users" screen wont allow me to click on a user to edit its details. It makes a request to api/roles endpoint and gets a 500 with this message : 

{
  "message": "Missing/invalid DB name",
  "status": 500
}

any way to fix this?

**Comment by aderici** [comment]
magically started working, in the meanwhile what i did was, i created my first app, and i logged in through an openid provider

**Comment by aptkingston** [comment]
Hey @aderici. As you noticed - the fix is creating at least one app. I have done a real fix for this issue though which will be deployed soon, and thanks for reporting :+1:
