### ISSUE TITLE
[Kubernetes Hosting] Unable to access CouchDB embedded Fauxton client

### ISSUE THREAD

**Issue by jmlaurenti** [Budibase/budibase#7058]
**Hosting**
- Self
  - Method: k8s
  - Budibase Version: 1.2.4

**Describe the bug**
When trying to access CouchDB admin using url :  "[budibase host]/db/_utils/#", I have a 502 error Bad Gateway instead of being asked credentials

**To Reproduce**
1. Have a kubernetes hosted budibase instance : <budibase host>
2. Access [budibase host]/db/_utils/#
4. See error 502:Bad Gateway

**Expected behavior**
The Fauxton login page should be displayed.

**Additional context**
- NB : Everything is working fine on a Docker hosted image
- Proxy-Service pod logs in Kubernetes are the following :
    [notice] 45#45: *113 "^/db/(.*)$" matches "/db/_admin", client: 10.12.5.79, server: _, request: "GET /db/_admin HTTP/1.1", host: "budibase.xxx.com"
    [notice] 45#45: *113 rewritten data: "/_admin", args: "", client: 10.12.5.79, server: _, request: "GET /db/_admin HTTP/1.1", host: "budibase.xxx.com"
    ***[error] 45#45: *113 budibase-prod-svc-couchdb could not be resolved (3: Host not found), client: 10.12.5.79, server: _, request: "GET /db/_admin HTTP/1.1", host: "budibase.xxx.com**"**

After some investigation, there is a reference to budibase-release-svc-couchdb in (https://github.com/Budibase/budibase/tree/develop/scripts/proxy)/generateProxyConfig.js 
Strangely, it's the only element not following the pattern with suffix ".budibase.svc.cluster.local"

const Configs = {
  prod: {
    apps: "app-service.budibase.svc.cluster.local",
    worker: "worker-service.budibase.svc.cluster.local",
    minio: "minio-service.budibase.svc.cluster.local",
    **couchdb: "budibase-prod-svc-couchdb",**
    resolver: "kube-dns.kube-system.svc.cluster.local"
  },
  preprod: {
    apps: "app-service.budibase.svc.cluster.local",
    worker: "worker-service.budibase.svc.cluster.local",
    minio: "minio-service.budibase.svc.cluster.local",
    **couchdb: "budibase-preprod-svc-couchdb",**
    resolver: "kube-dns.kube-system.svc.cluster.local"
  },
  release: {
    apps: "app-service.budibase.svc.cluster.local",
    worker: "worker-service.budibase.svc.cluster.local",
    minio: "minio-service.budibase.svc.cluster.local",
    **couchdb: "budibase-release-svc-couchdb",**
    resolver: "kube-dns.kube-system.svc.cluster.local"
  },
  compose: {
    apps: "app-service",
    worker: "worker-service",
    minio: "minio-service",
    couchdb: "couchdb-service",
    watchtower: "watchtower-service",
    resolver: "127.0.0.11"
  },
}

Hope it helps :-)
Have a great day, and kudos for the hard work !
JML

**Comment by shogunpurple** [comment]
@jmlaurenti we do not expose fauxton over NGINX in the kubernetes setup, as it is generally used for production configurations and exposing the management UI is a security risk.

The safest way for you to access fauxton, is to run a port forward to one of your couchDB nodes to your local machine. You can do this as follows:

```
kubectl port-forward <couchdb-pod-name> 5984:5984 -n budibase
```
You can then access this in your browser on `localhost:5984/_utils`.

If you want to know your credentials, they are stored in kubernetes secrets. You can find out how to access these here, in the documentation:
https://docs.budibase.com/docs/kubernetes-k8s#secrets-management

Thanks!

**Comment by jmlaurenti** [comment]
Understood ! 
Thanks for your reply, I will use your solution...
Maybe it should simply be added to the documentation page related to K8s deployment ?

Thanks again.
JML
