### ISSUE TITLE
Kubernetes: Allow deployment to custom namespace

### ISSUE THREAD

**Issue by panos--** [Budibase/budibase#7062]
**Describe the feature request**

Currently on Kubernetes Budibase can only be installed into a namespace called _budibase_. It would be nice if the installation would support any namespace. This would for example allow to run staging and production deployments in different namespaces on the same cluster, so that updates can be applied to and tested in the staging deployment without affecting the production deployment in any way.

The only thing that prevents this is the proxy service that has hard-coded upstream URLs in its config which reference the namespace name.

When changing those upstream URLs accordingly (in our case using a forked Helm chart and an initContainer that manipulates the static config) Budibase runs fine in namespaces named other than _budibase_.

**Comment by shogunpurple** [comment]
This should now be addressed with your PR - thanks @panos--!
