### ISSUE TITLE
Authentication Problems

### ISSUE THREAD

**Issue by Franosa** [Budibase/budibase#7071]
**Hosting**
- Cloud
  - Tenant ID: chesschristian

**Describe the bug**
I am forced to re authenticate several times per day. I can be working on an app and all of the sudden I get an error message about not being able to load components, then the page will refresh and ask for me to login again. 

**Expected behavior**
I should not have to authenticate several times in an active session

**Desktop:**
 - OS: macOS 12.5 M1
 - Browser: Chrome and Safari
 - Version 104.0.5112.79 and Version 15.6 (17613.3.9.1.5)

**Comment by mike12345567** [comment]
Hi @Franosa - we've released some fixes to the Cloud which should have fixed this issue, can you let me know if you're still experiencing it? If not we can close this issue.

**Comment by Franosa** [comment]
It looks like the update has fixed the issue.
