### ISSUE TITLE
Live search over table

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#7092]
### Discussed in https://github.com/Budibase/budibase/discussions/7032

<div type='discussions-op-text'>

<sup>Originally posted by **Pulsdesign** August  1, 2022</sup>
Hi there,
Is there a possibility to search a table with live results. Like typing in 3 letters and all matches will appear and not to have press enter or type the exact search-term in?
</div>

**Comment by kasgithub8** [comment]
Same thing would be great with numbers f.e. for the Auto ID.

**Comment by sergioponguta** [comment]
Any update on this, or any workaround?

**Comment by melohagan** [comment]
Hey @kasgithub8 @sergioponguta 

You can now use the Type Ahead plugin! https://github.com/ConorWebb96/bb-type-ahead

More on custom plugins here: https://docs.budibase.com/docs/custom-plugin
