### ISSUE TITLE
Error updating component property

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#7097]
**Hosting**
- Cloud v.1.2.10

**Describe the bug**
Error updating component's property

**To Reproduce**
1. Add a paragraph
2. Try change the text
3. An error pop us from the bottom of the screen saying "Error updating component property"

**Expected behavior**
No error when updating component's properties.

It should have changed from default placeholder to ">".

**Screenshots**
![error updating component prop](https://user-images.githubusercontent.com/94982318/182920902-3641db91-2667-4ddc-b81c-315d01a9201c.png)
  
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 103.0.5060.134 (Official Build) (64-bit)

**Other context**
I have two applications opened. One is template-based done by Budibase, the other one is on the screenshots to which I copy functionality from the template (as a way of learning the builder).

_**Can redirects between browser tabs cause this issue?**_

**Comment by Klience** [comment]
Same problem with button actions. Tried to add 3 actions to a button: validate form, save row, navigate to a screen. Got the same error, without any actions added.

![error updating component prop 2](https://user-images.githubusercontent.com/94982318/182923749-704b3fd0-8fe1-460f-b693-324b9b89247c.png)

**Comment by aptkingston** [comment]
This must have been caused by a temporary server issue with our cloud environment (HTTP 503 in screenshot), and it is definitely not reproducable any more.
