### ISSUE TITLE
Contributor guidelines do not work as stated in docs

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#71]
see comment: https://github.com/Budibase/budibase/pull/69#issuecomment-579574544 ... reports:

Anyway, the issue I was trying to address is that the contributor guidelines don't work as-is. Specifically the yarn bootstrap command (which the package.json defines as lerna bootstrap) gives this error...

```
yarn bootstrap
yarn run v1.21.1
$ lerna bootstrap
'lerna' is not recognized as an internal or external command

```

**Comment by shogunpurple** [comment]
You have to run ‘yarn’ first to install NPM dependencies before running any ‘yarn’ commands.

**Comment by shogunpurple** [comment]
Docs updated. Closing
