### ISSUE TITLE
Budibase Users Logged Out Automatically

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#7104]
**Describe the bug**
All of our users seem to be logged out since yesterday.

**To Reproduce**
Don't know the origin of this bug

**Expected behavior**
We have a safety screen for people without permissions for this app. Since yesterday, every person is landing on that

**Comment by kasgithub8** [comment]
https://github.com/Budibase/budibase/discussions/7085

**Comment by mike12345567** [comment]
Hi @kasgithub8 - just to confirm, this is occurring on a self hosted system or is this occurring in our Cloud platform?

**Comment by kasgithub8** [comment]
> Hi @kasgithub8 - just to confirm, this is occurring on a self hosted system or is this occurring in our Cloud platform?

Hey @mike12345567, we're hosting it on our own docker.

**Comment by mike12345567** [comment]
Hi @kasgithub8 - can you provide a little more information, such as what version of Budibase you are running, as well as how you are hosting it, e.g. is it docker-compose, docker single image etc - the more info you can provide the easier it will be to diagnose!
