### ISSUE TITLE
[BUDI-7003] Data update error with mssql, data type datetime2 and value '9999-12-31 23:59:59.9999999'

### ISSUE THREAD

**Issue by B-z-F** [Budibase/budibase#7109]
There seems to be a problem with update records with data type datetime2 and value '9999-12-31 23:59:59.9999999' (Microsoft SQL Server).

Sample table, where is field [ValidFrom] which has default value:
```sql
...
[TestTableID] [int] IDENTITY(1,1) NOT NULL,
[Name] [varchar](255) NOT NULL,
[ValidFrom] [datetime2](7) NOT NULL,
...
...
ALTER TABLE [dbo].[TestTable] ADD  DEFAULT ('9999-12-31 23:59:59.9999999') FOR [ValidFrom]
...
```
In Budibase I can create new records (just [Name], without data entry into [ValidFrom] (default is used)) and save them.
Strange is that it shows "January 1 10000, 00:59" - no matter if I changed Ignore timezone or not.

But when I update record (again only [Name]) and try to save them, then there is error:
```
RequestError: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 4 ("@p1"): The supplied value is not a valid instance of data type datetime. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.
```
If I change [ValidFrom] to December 31 9999, 12:59, then save works.

But I need to work with value '9999-12-31 23:59:59.9999999' (it is required by SYSTEM_VERSIONING).

<sub>[BUDI-7003](https://linear.app/budibase/issue/BUDI-7003/data-update-error-with-mssql-data-type-datetime2-and-value-9999-12-31)</sub>

**Comment by andz-bb** [comment]
![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/703a5939-fd21-4cc2-9a04-49b09370e66f/e1408308-e4ab-4d72-bd12-8ac966d15e2b)

recreated the edit issue in 2.6.23

here's my script for creating the table with the default date.

```
CREATE TABLE [dbo].[TestTable]
(
    [TestTableID] [int] IDENTITY(1,1) NOT NULL,
    [Name] [varchar](255) NOT NULL,
    [ValidFrom] [datetime2](7) NOT NULL CONSTRAINT DF_TestTable_ValidFrom DEFAULT ('9999-12-31 23:59:59.9999999'),
    CONSTRAINT PK_TestTable PRIMARY KEY CLUSTERED 
    (
        [TestTableID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

**Comment by aptkingston** [comment]
Resolved with recent changes to the date picker.
