### ISSUE TITLE
Cannot import into main Users table.

### ISSUE THREAD

**Issue by alscheuring** [Budibase/budibase#7119]
**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 1.2.4
  - App Version: 1.2.4

**Describe the bug**
I get error messages when I try to import a CSV into the main users. table. "Error, please check the following emails: <csv contents after>"

**To Reproduce**
1. Manage -> Users
2. Click on Import Users
3. Select CSV file (attached in this post)
4. Error occurs.

**Expected behavior**
System parses csv file and give the ok to proceed

**Screenshots**
Attached.
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: OSX 12.4
 - Browser Chrome 
 - Version 103.0.5060.134 (Official Build) (x86_64)

.
![Screen Shot 2022-08-05 at 11 40 38 AM](https://user-images.githubusercontent.com/223471/183113935-6d8ad33d-f46a-442c-a4da-61cbebcb63ce.png)
![Screen Shot 2022-08-05 at 11 40 11 AM](https://user-images.githubusercontent.com/223471/183113938-e20bc482-ef08-4d69-a728-d0b114db7853.png)
![Screen Shot 2022-08-05 at 11 40 08 AM](https://user-images.githubusercontent.com/223471/183113940-1953200c-a0e7-41ef-938f-534b95b79d4b.png)
[fake-email-import.csv](https://github.com/Budibase/budibase/files/9270023/fake-email-import.csv)

**Comment by mauricedcastro** [comment]
Imports appear to work on 1.3.12 if the file consists of email addresses separated by \r characters. The file must NOT end in a \r. ie. 

a@example.org\rb@example.org works (works.csv)  [works.csv](https://github.com/Budibase/budibase/files/9561685/works.csv)

but 

a@example.org\rb@example.org\r does not work (fails.csv) [fails.csv](https://github.com/Budibase/budibase/files/9561684/fails.csv)

Also adding additional comma separated fields appears to cause the import to fail (fails2.csv) [fails2.csv](https://github.com/Budibase/budibase/files/9561692/fails2.csv)
