### ISSUE TITLE
SSL rejectUnauthorized for REST API

### ISSUE THREAD

**Issue by adamkingsbury** [Budibase/budibase#7123]
**Describe the feature request**
Hi, I would like to request that you add rejectUnauthorized functionality to the REST Api integration in a similar fashion to how you have implemented for PostgreSQL and MYSQL integrations. 

I would like the ability to integrate Web services on my self hosted platform that utilise self signed certs for https comms.

**Comment by FocusDesigner** [comment]
plus 1

would be awesome to have this feature as most of my REST APIs use self signed certificates and I am not able to connect as described here already

[https://github.com/Budibase/budibase/issues/4615](https://github.com/Budibase/budibase/issues/4615)

If anyone has a temporary solution to fix this, would be super helpful. Thanks

**Comment by dwesthuis** [comment]
Please help, same problem here:

Query Error: request to https://xx.xx.xx.xx:xxxx/xxxxxxx? failed, reason: self signed certificate

**Comment by adamkingsbury** [comment]
I've submitted a pull request to resolve this issue.....first time I've attempted so we'll see how it goes:
/pull/7716
