### ISSUE TITLE
Grid no longer displaying

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#713]
Grid component no longer displays 

https://www.loom.com/share/7dd2b34b6e024d8dbb6918ef0c72de22

**Comment by joebudi** [comment]
Ahhhh @kevmodrome i didn't know we had to set a height. Maybe we should default to a height?

**Comment by kevmodrome** [comment]
I thought I set a default, let me double check and see if I did something wrong

**Comment by joebudi** [comment]
P.s loving the editable and pagination options

**Comment by kevmodrome** [comment]
The height option seems completely borked for me, I'll investigate. Not sure what happened to it.

**Comment by aptkingston** [comment]
@joebudi check the grid component itself - is the table prop correct or is it "Deals"? The template pages created when you create a table always put it to a "Deals" table for me which needs changed.

**Comment by joebudi** [comment]
It works now, after setting the height

**Comment by shogunpurple** [comment]
I'm noticing this one too off master - the problem for me was the lack of a default height, so the grid was rendering with 0 height. The grid is there

**Comment by kevmodrome** [comment]
It's odd, i'm trying to set default values but it's not getting put in there correctly for some reason, I have to change it from the current default (500) to something else to get it to update. No clue why that is

**Comment by kevmodrome** [comment]
https://cln.sh/UYBMTl

**Comment by joebudi** [comment]
I think we have consistency issues around units. Some parts of the builder, you have to add px - 500px, and some you do not. IMO, we should have this as a datalist component with defined heights and an open input. I prefer adding the px, as it adds a little more context.

**Comment by kevmodrome** [comment]
I found the issue, the good old components.json and temporaryPanelStructure.js (very temporary, this file 😆) weren't in sync.

**Comment by joebudi** [comment]
I feel the temppanel... is heading towards the realm of UIKit

**Comment by kevmodrome** [comment]
fixed
