### ISSUE TITLE
When trying to test an automation with an app action the screen freezes and an error appears in the console.

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#7147]
**Hosting**
- Self
  - Method: Docker compose
  - Budibase Version: 1.2.9
  - App Version: 1.2.9

**Describe the bug**
When trying to test an automation with an app action the screen freezes and an error appears in the console.

**To Reproduce**
1. Create an automation and use App action
2. Create your automation
3. Click finish and test automation
4. The error will appear in the browser console

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/97764630/183422889-8e79a1f2-b659-4e7d-9863-145aee03e770.png)
  
**App Export**
[BulkUpdateApp-export-1659963249625.txt](https://github.com/Budibase/budibase/files/9281802/BulkUpdateApp-export-1659963249625.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 103.0.5060.114

**Comment by PClmnt** [comment]
Hi @FlaminWrap, sorry you're having issues. Could you provide some more information about what your App Action step looks like? i.e what test data are you using. And what does the rest of your Automation look like?

**Comment by FlaminWrap** [comment]
Hi @PClmnt 

The automation queries the valid field for not equals yes in the bulk update table. The automation then goes into a loop to update the records and change the value to Yes

The the automation would be triggered through a button in the app. I didn't know what method of automation to choose when first starting as I didn't want it to trigger under any other circumstances, so I chose app action.

Here is a screenshot of the full automation.
![buditest](https://user-images.githubusercontent.com/97764630/183608182-654a82b3-28a3-4a10-a19d-323000d55649.png)

**Comment by PClmnt** [comment]
Hi @FlaminWrap, I pulled down your app and there appears to be an bug with the testing of an App Action automatio, that if you haven't added a field to the app action, that you'll get that error. I will edit this issue title and fix the problem shortly, but in the meantime, you can just click `Add field` and enter any value whatsoever (it doesn't matter what it is, it won't be used within your automation) and the automation should complete successfully, it did for me anyway! Thank you for bringing this to our attention!

**Comment by shogunpurple** [comment]
@FlaminWrap this one should be resolved on the latest versions
