### ISSUE TITLE
Manage-users, After force reset user password, User is not sent directly to login page

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#7149]
User is not sent directly to login page, the builder flash for a second with an error message.

31st second of the this video : https://www.loom.com/share/3b329f96fed6446b9461698d338afac4 

Steps:

1. Create an user and click the 3 dots, force user password. 
2. Login with the user and temporary password 
3. Set a new password and click login 

Expected result: User is send directly to login page
Actual result : The builder flashes for a second and then redirect to login page

**Comment by deanhannigan** [comment]
Hi @MihailHadzhiev2022, 

I couldn't reproduce this locally or on the current cloud release. After resetting my test users password, they are successfully redirected back to the login screen.

**Comment by MihailHadzhiev2022** [comment]
Yes, you are right, it looks like it was fixed. You could close it.
