### ISSUE TITLE
Apps that have an avaiable update show an Icon / Alert in the Apps List Portal

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#7150]
It should be visible from the portal, if an application has an available update and the possibility to update multiple apps at once.
think of the case you have 20 or more internal apps, and budibase updates.
you would need to go to each up individually to see if there is an update available and apply it.

suggested feature, would show an update alert ( Notification Icon maybe ) before the app icon and name in the portal, that would be ON (yellow) if the App can be updated. A checkbox should also appear, to allow you to Tick this App and then "Apply Update to Selected Apps" button / link.

**Comment by shogunpurple** [comment]
Thanks @poirazis - we have one here for this https://github.com/Budibase/budibase/issues/6663

Really like your suggestions, we will take these into account when we build the feature!

Will add your comments into that one and close this one for now.
