### ISSUE TITLE
Action to Update Element Settings

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#7158]
What we currently need to do to achieve above behavior is user the Update State Action to set an App.State then set Conditional UI so the Element can adapt itself. 

Now another, more straight forward way could be to have an Action "Update Element" in which we would be able to Set changeable properties of any Element on the Screen.  

Example, you can expand a collapse a container, increase the limit on a data provider and fetch more records, change a Form from Create to Update etc

Example 2, on screen load you have two actions. Continue if {{ Device.Mobile }} == true and Update Element Settings. Using the Second Action, you can completely customize your screen for mobile.

Just an idea!

**Comment by melohagan** [comment]
Closing as duplicate of: https://github.com/Budibase/budibase/issues/7979
