### ISSUE TITLE
Automatic App Provisioning

### ISSUE THREAD

**Issue by Elliot-Construct** [Budibase/budibase#7178]
The ability to already provision users to an application in the ADD USER. Or the ability to all normal users automatically to an app. Otherwise... right now there is no welcome zone for the new user :-)

**Comment by kasgithub8** [comment]
Hey @Elliot-Construct,

I don't know if you have heard by now but this is a pro feature which could be released in 1 or 2 weeks.
Check this out: [https://github.com/Budibase/budibase/issues/7269](url)

**Comment by Elliot-Construct** [comment]
#7219
