### ISSUE TITLE
Allow updating parent window location when closing screen modal

### ISSUE THREAD

**Issue by JayP718** [Budibase/budibase#7184]
Hosting

Self
Method: Docker-Compose
Budibase Version: 1.128
App Version: Self-Hosted
Describe the bug
When you open a modal screen and use an action on the modal screen to navigate to another screen it opens the screen within the modal. We tried to put a close modal step  ahead of the navigate to step but unfortunately that doesn't work.

Not sure if this is expected behavior but hoping a work around exists.

**Comment by aptkingston** [comment]
Hey @JayP718. I'm afraid you can't do this currently. You can change the location of the modal itself, but you can't change the location of the parent window from within the modal.

Normally when you use a modal screen you would expect for the modal to close and still be on the same screen though. If you don't plan to back to the original screen, you might be better not using a modal at all, which would solve this problem.

It's possible to add this as a feature though, so I'll leave this issue open and convert it to a feature request.

**Comment by JayP718** [comment]
Hi @aptkingston,

Thanks all good! We were able to do a work around using the open javascript function.

JP
