### ISSUE TITLE
I am getting errors when deleting multiple screens

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#7192]
**Hosting**
Cloud

**Describe the bug**
Budibase is throwing errors when I delete screens. Within this case, there were 7/8 screens I was deleting in a row.

https://share.cleanshot.com/EbwDYd

**Comment by aptkingston** [comment]
Usually whenever you get into a bad state like this (e.g. if you get a 409 error), you'll continue to get them until you do a refresh. I've done a lot of work recently to try and reduce them but maybe there's a specific bug here with deleting screens. I'll have a look.
