### ISSUE TITLE
Deleting User from Main Users Table Does Not Delete App User Row

### ISSUE THREAD

**Issue by pbarmak** [Budibase/budibase#7220]
If I create a user in the main, system-wide Users portal table, then assign that user to an app, the system creates a row in the app's Users budibasedb table. I can then add custom columns to the apps's Users table and update that user row as usual. That works.

If I then delete the user from the system-wide Users table in the portal, it deletes that main user, but it does not delete the user row from each of the apps Users tables. 

Since the apps' Users tables are somehow tied to the system-wide one, I cannot clean up the specific app's User table. It won't let me delete a row there. I can't even update any custom columns in that table (it gives me a "Document update conflict." error).

I think, when a main user is deleted, the system needs to either a) delete all apps' Users table rows for that user or b) unlink the user and allow us to manually delete an orphaned user row from the app Users table.

In the meantime, anyone know how I can clean up the app's Users table without destroying my app?

**Comment by aderici** [comment]
Within your app you can use delete row action in a button and delete an apps user row. I'm not sure if this is supported behavior but it does delete

**Comment by pbarmak** [comment]
@aderici That's interesting, I'll try it, thank you. Though that maybe is concerning, if we can delete a row from the Users table via a button action while we can't from the actual Data interface. But it's good to know, thanks for pointing it out.

**Comment by mlomax** [comment]
> 
We have this problem too.
The lack of cleanup also seems to have an effect on re-adding a user.

I was having issues with SSO so deleted a user from the main screen so I could run a test by re-adding. 
The email was deleted from the user portal but when I come to re-add it I get a reason of "unavailable" and the email isn't added.

On checking Budi hasn't deleted the user from the app-user tables, although it has set to inactive. But I think this is why I can't re-add the email.

**Comment by michal-81** [comment]
Having the same issue. Are they any plans to fix this?
