### ISSUE TITLE
New user generated password screen styling breaks when user email is too long

### ISSUE THREAD

**Issue by andz-bb** [Budibase/budibase#7222]
**Hosting**
- Self
  - Method: docker-compose
  - Budibase Version: 1.2.26
  - App Version: 1.2.26

**Describe the bug**
When generating a password for a new user, if the email is over a certain length it is truncated in the field in the dialog. The truncated email is still too wide for the field though so the elements spill over the boundaries of the dialog.

**To Reproduce**

- Go to Users and add a new one with a long email 
- Select generate password when prompted
- The _Accounts created_ screen shows the email and password

For emails around 21 characters and above in length it starts to stretch beyond the natural width of the field.

**Expected behavior**
The email address is truncated sooner to fit the width of the dialog, or the dialog is wider to fit the longer email.

**Screenshots**
With a short email, all is fine:
<img width="672" alt="short email" src="https://user-images.githubusercontent.com/110921612/184093518-9df6ad1d-3f97-413e-a134-976f9931a137.png">

with ~21-27 characters it shows the full email but the field stretches beyond the width it should be for that dialog
<img width="510" alt="medium long email" src="https://user-images.githubusercontent.com/110921612/184099638-fe0f61f1-33c5-4a93-af2e-cdbeaf35d3e4.png">

The long email (28+ characters) is truncated but the truncated version is still too wide:
<img width="546" alt="really long email" src="https://user-images.githubusercontent.com/110921612/184093568-6cec9655-8fc9-4fc2-a56a-92f6d534054c.png">

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Browser: Chrome
 - Version 104

**Comment by PClmnt** [comment]
Fixed by Rory in: https://github.com/Budibase/budibase/pull/7478

**Comment by Rory-Powell** [comment]
Re-opening - still an issue for longer email addresses

**Comment by deanhannigan** [comment]
Hey @Rory-Powell, I just ran through this on the app site and it appears to be neatly truncating the emails without the overspill.

![Screenshot 2022-10-28 at 12 01 21](https://user-images.githubusercontent.com/5913006/198572235-4531f640-829c-4a68-9511-059958b5067a.png)
