### ISSUE TITLE
budibase/proxy fails to start with IPv6 disabled on node

### ISSUE THREAD

**Issue by mrmurb** [Budibase/budibase#7240]
**Hosting**

- Self
  - Method: k8s 
  - Budibase Version: 1.0.214 
 
**Describe the bug**
Proxy fails to start if IPv6 is disabled on node since nginx tries to bind on v6 address.
[hosting/nginx.prod.conf.hbs#L44](https://github.com/Budibase/budibase/blob/develop/hosting/nginx.prod.conf.hbs#L44)

**To Reproduce**
1. Disable IPv6 on nodes.
2. Deploy Budibase helm chart.
3. See error

**Expected behavior**
Proxy to start without trying to bind on v6 address.

**Additional context**
I am using Kube-router which does not support dual-stack networking. So there are no workarounds availalable except building a new container image with a different nginx config.

**Comment by tharwan** [comment]
We have the same problem, the on prem k8s cluster does not support ipv6 so we can not install budibase. Any workarounds would be highly welcome.

**Comment by jonnymccullagh** [comment]
I was able to replicate this bug on a Linux box with IPv6 enabled. 
In the nginx/proxy container the scripts under /docker-entrypoint.d are numbered so they run with `/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh` running first and removing any mention of IPv6. Afterwards `20-envsubst-on-templates.sh` runs and puts an `nginx.conf` in place that contains an IPv6 line. So the IPv6 config line is not removed.

To rectify that I have modified the [Dockerfile](https://github.com/Budibase/budibase/blob/master/hosting/proxy/Dockerfile) to delete the file `10-listen-on-ipv6-by-default.sh` and replace it with `80-listen-on-ipv6-by-default.sh`([source](https://github.com/Budibase/budibase/blob/master/hosting/proxy/80-listen-on-ipv6-by-default.sh)). With the `80` at the start of the file name it runs after the envsubst script and so acts to remove any IPv6 lines in the config files.

I tested the new image on a Linux box rebooting with IPv6 on and off.  

Please pull the 'latest' (SHA 4ed89e90c16c) image from [dockerhub](https://hub.docker.com/r/budibase/proxy) to get this change.
