### ISSUE TITLE
Cannot log into previewed app (inconsistent)

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#725]
I was able to preview one of my apps. I am running the builder in the browser.

However, i created a new on, then opened preview. I could not log in:

![image](https://user-images.githubusercontent.com/3524181/96105923-80196100-0ed2-11eb-896f-4d9369731565.png)

**Comment by mjashanks** [comment]
Update: if preview my app, and clear ALL my cookies - `builder:token` and `budibase:token`, then i cannot even load the login screen.

![image](https://user-images.githubusercontent.com/3524181/96106306-f9b14f00-0ed2-11eb-9835-c903ff5dc508.png)

**Comment by mjashanks** [comment]
Still not working for me:
1. Pull from master
2. Clear down apps
3. `yarn bootstrap`
4. `yarn build`
5. server > `yarn build:electron`
6. Run electron build
7. Create new app & some tables
8 Preview

![image](https://user-images.githubusercontent.com/3524181/96249736-89273280-0fa5-11eb-9126-1b7f2b698b4f.png)

**Comment by mjashanks** [comment]
Had a look at this (my last screenshot).

The issues is that the appId is not being detected properly on the server. See below.

When serving the component library, the "referrer" header is `assets/budibase-client.js`, which does not have an appId in its url (assumed by the `authenticated` middleware). See debug console in screenshot below.

I am not sure where else we would get the appId from at this point :/

![image](https://user-images.githubusercontent.com/3524181/96352887-fbd80100-10be-11eb-965d-3d9a274d8e81.png)

**Comment by mjashanks** [comment]
@shogunpurple have you fixed this anywhere? Do you want me to look at it?

**Comment by shogunpurple** [comment]
@mjashanks sorry missed your comment there yesterday. I'm not sure we can rely on the Referer header in certain browsers - this particular issue also seems to be windows related as I can't seem to reproduce. I think we might have to just set the appID in the token at a point when we know for certain that it's there. I'll look into it

**Comment by mjashanks** [comment]
quick fix: https://github.com/Budibase/budibase/tree/auth-fix

**Comment by shogunpurple** [comment]
Nice one - that will solve it for now for windows. I'll still work on getting something a bit longer term here.
