### ISSUE TITLE
Make "Created by" "Updated by" columns one sided

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#7254]
It just unnecessarily bloats User table query and is unnecessary in my opinion. Created by Updated by information is only needed in the Application table.

To be more precise : 

Let's say i have a table called "Support Tickets". With every single ticket, i need to see who created it. But i don't need to see 10000 tickets when i query users table. So is it possible to have those auto columns but not have the corresponding fields in users table?

**Comment by melohagan** [comment]
It's needed for this: https://docs.budibase.com/docs/fetching-data#display-user-specific-data
