### ISSUE TITLE
OneLogin OIDC integration failing

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#7267]
**Hosting**
- Cloud
  - Tenant ID: https://mistraldata.budibase.app

**Description**
When the OneLogin OIDC integration has been configured and enabled according to the instructions 
And a user tries to login via the 'Sign In with OneLogin' button on the /auth/login page
Then the browser redirects round and shows a {"message":"Unauthorized","status":403} error message and the url shows the error 'error=invalid_scope&error_description=some%20of%20requested%20scopes%20are%20not%20whitelisted'

**To Reproduce**
1. Configure an OIDC connection to OneLogin
2. Click on 'Sign In with OneLogin'

**Expected behavior**
The user should be preseneted with the OneLogin authentication (if not logged in) and returned to the redirect url set with a valid OIDC JWT.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 104

**Comment by aderici** [comment]
This is probably because of the "offline_access" scope requested by budibase. Onelogin does not allow this on auth code or implicit flows.

I think you should review how you are refreshing the access token for the user. offline access scope is for the cases where you need to access users resources when the user is not using the app (when they are sleeping). I think there is another method to refresh when the user is actively using the app

**Comment by andyburgessmd** [comment]
I see the https://github.com/Budibase/budibase/pull/7349 feature has been merged to develop. Do you have any eta on when it might make it to prod/live?

**Comment by Rory-Powell** [comment]
hey @andyburgessmd! Those changes will become live in the next week or two, pending or QA cycle.

**Comment by mlomax** [comment]
@deanhannigan we were very excited that you'd added scope. It hasn't worked for us though and we get 
![image](https://user-images.githubusercontent.com/105858177/189922930-5f276d51-cd3b-48bd-896d-d9274a8de0b3.png)
 We can log on with Azure SSO when just using the default openid scope but not when putting our bespoke one in. Is there anything we can help on with the testing? thanks Mary

**Comment by aderici** [comment]
@mlomax Hi, unfortunately that 403 error is a bit generic and you can get more descriptive error message about what's wrong by logging into the inspect window or the pm2 logs in the docker container if self hosting. For microsoft, which scope are you looking to get access to? Some scopes require "admin consent" so a regular user won't be able to login before an active directory admin logs in first.

**Comment by mlomax** [comment]
![image](https://user-images.githubusercontent.com/105858177/190381013-71316e57-cc32-44cc-833c-5ec05bff29f5.png)
@deanhannigan @niggydotcom 
I think the callback isn't working.
In an incognito window, I log in using Azure and it takes me to the microsoft login.
It then returns to this web address
https://pitest.budibase.app/api/global/auth/pitest/oidc/callback?code=....&session_state=.....
where .... are a lot of letters and numbers.
if i delete everything after the question mark I can get into the budi database fine.
Mary

**Comment by deanhannigan** [comment]
Hi @mlomax, I was just able to reproduce this on the same system. This seems to be a general issue and I'll update you when I have more information.

**Comment by mlomax** [comment]
@deanhannigan thanks - if you need us for testing just give me a shout Mary

**Comment by deanhannigan** [comment]
Hi @mlomax, upon further testing, the issue I ran into was unrelated and caused by my user being registered in another tenancy in the cloud.

From the logs for your login attempts on Thursday, it appears that there is an issue with the Azure configuration in your tenant.

`status: 401 data: {"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience." ....`

- Have you been able to verify that this particular user can log in outside Budibase via Insomnia?
- Did this user email exist in the builder before you attempted to log in with Azure?
- Could you confirm that you were able to access [https://pitest.budibase.app/builder]( https://pitest.budibase.app/builder) having removed the URL parameters? Were you logged in as the OAuth User and able to use the builder?

**Comment by mlomax** [comment]
Hi @deanhannigan 
It's my user and it works fine to get the token back via insomnia

Using a different login I've deleted my user from the builder and removed all scopes except openid. I can then login as me using Azure and Budi adds me to the user table.

As soon as I go back in to the builder and add the custom scope I get the 403 error and that extremely long callback URL

If I delete the URL parameters then I can get into the builder but the token isn't being accepted by my datasource.

I have two queries on the same REST source. They are identical apart from the token they use
- one uses the insomnia token which I've pasted in as a parameter.
- one tries to use the OAuth token but this fails both as a parameter or as an authentification config

I can't now see the budi OAuth token as something has changed. If you remember I could send it as a parameter to niggy.com and get back the jwt that I could then decode. It now just sends back {{ [user].[oauth2].[accessToken]}} so I can't even identify which bit of the token doesn't match insomnia anymore :(

Very happy to jump on a teams call. Mary

**Comment by aderici** [comment]
Just wanted to share that for azure ad oidc you shouldnt use "common" discovery endpoint. As far as i know budibase doesnt support microsoft multi tenant login.

Your discovery url should include your tenant id.

https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration

If you dont know the tenant id for your company, you can visit whatismytenantid.com and enter the domain name of your company that is also used in your email addresses

**Comment by fan-wen** [comment]
> https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration

THIS IS SOOOOOOOO FXXKING HELPFUL for the 403 Unauthorized error. Also discussed in https://github.com/Budibase/budibase/issues/11146
https://github.com/Budibase/budibase/discussions/4065
