### ISSUE TITLE
App access - set default apps

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#7269]
### Discussed in https://github.com/Budibase/budibase/discussions/7180

<div type='discussions-op-text'>

<sup>Originally posted by **andyburgessmd** August  9, 2022</sup>
It would be useful if you could set which apps that all users can have access to so that when you add a new user they will have access to that app straight away.</div>

Maybe have a setting in the access tab to allow apps to be exposed to all users:
![Screenshot 2022-08-15 at 10 37 14](https://user-images.githubusercontent.com/101575380/184612659-1700938d-51ca-48b2-8643-6c551dcc78e2.png)

**Comment by aptkingston** [comment]
This is what groups are for - the idea is that you can assign users to groups while inviting them, which will immediately give them access to the apps accessable by those groups. We aren't likely to make any more changes to this in the near future as groups are a pro feature and being able to make apps available to everyone by default would be shooting ourselves in the foot a bit.

I think groups should be live in a week or two, but as a pro feature.

**Comment by Elliot-Construct** [comment]
Will this remain a pro feature?

**Comment by shogunpurple** [comment]
@Elliot-Construct yes, it will be pro on self host also

**Comment by Elliot-Construct** [comment]
How much is pro?
How do we purchase pro?

**Comment by melohagan** [comment]
@Elliot-Construct Pricing can be found here: https://budibase.com/pricing/
