### ISSUE TITLE
Redis URL syntax not parsed correctly

### ISSUE THREAD

**Issue by noseshimself** [Budibase/budibase#7285]
**Hosting**
- Self
  - Method: Docker
  - Budibase Version: Docker-tag 1.2.40

**Describe the bug**
Neither the valid redis URL ``redis://redis:6379&db=8`` nor ``redis://redis:6379/8`` are accepted as REDIS_URL

see https://www.iana.org/assignments/uri-schemes/prov/redis

**To Reproduce**
Configure a Redis URL as stated above in docker-compose.yml

**Expected behavior**
I expect the application to start and use the specified Redis database. It doe not make sense to have multiple instances of redis running.

**Comment by shogunpurple** [comment]
Hi @noseshimself, we are afraid this one can't be supported in budibase - we use different databases within redis, so we aren't able to allow query parameters to select specific databases. It has to be the top level redis URL to be compatible with budibase.

Apologies!
