### ISSUE TITLE
Automations don't work anymore.

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#7304]
**Describe the bug**
I just noticed that none of my "Create row" Automations work anymore.
Last Automations in the History was 50 minutes ago.

**Comment by melohagan** [comment]
Hey @kasgithub8 Could you provide some additional details please?

Is this cloud for example? What is your tenant id?

**Comment by kasgithub8** [comment]
Oh and, the Test Automations work but only the tests.

**Comment by kasgithub8** [comment]
@melohagan, and suddenly they work again. Hopefully this bug won't appear for our users. 😞
