### ISSUE TITLE
Auto ID conflict between dev and production / automations

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#7311]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.2.36

**Describe the bug**
When two users save a row to the internal Budibase DB, there can be duplicate Auto IDs when one of the users is on the dev environment, and the other is on the published app. 

**To Reproduce**
1. Create an app with a Budibase DB table
2. Add two users to the app access
3. Add a screen with a form that saves a row to the table
4. Publish the app and open the published app link
5. In an incognito tab, open the dev app preview
6. Save the row for both users
7. Within the builder, you can see that two rows have been saved, however both have an Auto ID of 1

**Expected behavior**
If a row is saved in dev and prod at the same time, there should not be a conflict in Auto IDs.

**Screenshots**
![Screenshot 2022-08-16 at 15 48 07](https://user-images.githubusercontent.com/101575380/184909536-d092c812-30ba-4296-986f-2d4658dc9e63.png)

<img width="385" alt="Screenshot 2022-08-16 at 15 48 31" src="https://user-images.githubusercontent.com/101575380/184909610-afde3327-d12d-4199-9395-bc0964121454.png">

![Screenshot 2022-08-16 at 15 48 51](https://user-images.githubusercontent.com/101575380/184909703-f2f86fe2-7f5e-48e0-80f1-fdaf0cfe0f20.png)

**Comment by melohagan** [comment]
To further add to this, it appears it may also be an issue with automations: https://github.com/Budibase/budibase/discussions/9269#discussioncomment-4797710

**Comment by kasgithub8** [comment]
Hi @melohagan,

I ran into this problem today. 2 normal users created a row each in a time span of 5 hours and they had the same Auto ID.

**Comment by melohagan** [comment]
> Hi @melohagan,
> 
> I ran into this problem today. 2 normal users created a row each in a time span of 5 hours and they had the same Auto ID.

Hey @kasgithub8 

Does your app have any automations that save or update rows in that table?

**Comment by melohagan** [comment]
> @melohagan yes. One of my automations updates rows. Is that the problem?

It looks to be the case, as indicated by another user.

**Comment by kasgithub8** [comment]
@melohagan I think a cool addition/change would be a "Update row" in automations for specified fields and not every single one.
