### ISSUE TITLE
Enable accessing previous action results in page load actions

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#7338]
I need to execute a query and based on the response returned, navigate to another url or perform other actions.

On page load actions i can not see the bindings like Action2.response. Is this intended behavior or a bug?

**Comment by Rory-Powell** [comment]
Hi @aderici, thanks for raising this. Currently accessing the result of the query is supported in button actions only. I'm going to mark this issue as an enhancement to enable it, then you should be able to access `{{Action 1.Query result }}` in future actions to achieve your goal. Example of how this is achieved in button actions: https://github.com/Budibase/budibase/discussions/6808

**Comment by aderici** [comment]
Oh wow is this feature implemented now?

**Comment by aptkingston** [comment]
It is! It's merged to master, but just hasn't been deployed yet. This feature was already implemented for things like button actions, but it was just a bug preventing the bindings being shown for the "on load" screen setting.

**Comment by aderici** [comment]
I'm compiling my single image docker for this project so i may be able to use it before deployment. Thank you for the fast response! Where is the buymeacoffee link?

**Comment by aptkingston** [comment]
No problem at all. You're very kind but a github star and kind words like this are all we need for now!
