### ISSUE TITLE
cant update field value for relationshippicker in a form

### ISSUE THREAD

**Issue by hmily3913** [Budibase/budibase#7354]
use database :mysql
data tables:column 
product: id, name, default_unit_id
unit: id, name
product_price: id, product_id, unit_id, price
3table key field is 'id'

Design  form : add product_price
field:
1. product  : relationship product.name
2.unit : relationship unit.name

when i change product field ,i want set unit field.

I add product field action like this:
actiontype : update field value
field: unit
try value :(table unit has row id=1,name='BOX')
1. javascript     ---- return [1];   ---------field unit show 'null'
2. javascript     ---- return ['BOX'];  ---------field unit show 'null'

**Comment by shogunpurple** [comment]
Hi @hmily3913 - not sure what is actionable here. Could you please use the issue template here to provide more details:

https://github.com/Budibase/budibase/issues/new?assignees=&labels=bug&template=bug_report.md&title=
