### ISSUE TITLE
Autocomplete in Binding Selection Drop Down

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#7358]
Improve speed by adding auto completion / search to the binding select drop-down.

<img width="363" alt="Screenshot 2022-08-19 at 3 29 45 PM" src="https://user-images.githubusercontent.com/80512170/185618726-be09c68d-7683-425b-aa70-94bd5fa4e4c4.png">

**Comment by evtnl** [comment]
Same for all dropdown selects (e.g. when adding fields in table widget)

**Comment by aptkingston** [comment]
Hey @poirazis. Great suggestion and we're already working on this - you can keep track here: https://github.com/Budibase/budibase/issues/6962.
