### ISSUE TITLE
When creating first column on table, it should be required by default

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#736]
When we create the first column of a table, we default the "Use as table display column" to true. I think we should also make this required.

In fact - should the "Primary Display Column" **always** be required ?

![image](https://user-images.githubusercontent.com/3524181/96248773-fc2fa980-0fa3-11eb-90c6-b003275d3467.png)

**Comment by aptkingston** [comment]
It should be requirued - I've had to write various edge cases to deal with it potentially not being there, but yea it doesn't make sense to have your main display column be optional.
