### ISSUE TITLE
menu  / navigation block widget in designer

### ISSUE THREAD

**Issue by evtnl** [Budibase/budibase#7365]
**Describe the feature request**
Often you need more links / menu's than the main menu.
Of course you can add panels and change layout to multi column and add a menu in te new space manually.
It would be a lot faster to have a menu component with placement option (top (sticky option), bottom (sticky option), left, or right) per screen, especially if you can create several menus and select one of them on each screen.

**Comment by aptkingston** [comment]
Just in case you hadn't seen it, you can choose the position (top or left) and make it sticky (top only) in the navigation settings:
![image](https://user-images.githubusercontent.com/9075550/185643390-9b77a36a-d135-4af9-ac66-ff4fd625e2c3.png)

In the next few months we'll be doing some work to enable custom components and custom blocks which should make it really quick to make a custom nav (or more than one) and use them as desired in different screens.

**Comment by evtnl** [comment]
Yes I have seen it, but this is for the main navigation menu. 
I'm looking for a menu per screen, e.g. below the main navigation. So I'm looking out to the custom components!
