### ISSUE TITLE
add overall custom CSS

### ISSUE THREAD

**Issue by evtnl** [Budibase/budibase#7366]
**Describe the feature request**
In many widgets a custom CSS option is provided. 
An overall (per app, or per screen) custom CSS block would be nice to have

**Comment by melohagan** [comment]
Hey @evtnl 

Have you had a look at this at all? https://docs.budibase.com/docs/custom-css#global-styling

**Comment by evtnl** [comment]
Thanks! exactly what i was looking for per screen.
Per app would be nice to have, to change / vreate a theme for the whole app.

**Comment by pbarmak** [comment]
Any update on this request? It would be great to have a per-app global style option.
