### ISSUE TITLE
Unable to use calculation view with list or graph component

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#738]
Steps
1. Create calculation view (i'm using statistics)
2. Add list component (same with graphs)
3. Set datasource to your view

RESULT: Network Error: 400

![image](https://user-images.githubusercontent.com/3524181/96266444-900e6f00-0fbe-11eb-898c-89b827044fb1.png)

**Comment by shogunpurple** [comment]
I've found the issue with this - will put a PR up soon with some other stuff
