### ISSUE TITLE
New Record > clicking save twice creates 2 rows

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#739]
We should 

1. modify the Button component so that it will not execute a handler until the first handler has finished
1. the SaveRow handler should update `_id` and `_rev` of the stored row, so that a second click will cause an update

**Comment by mike12345567** [comment]
I think this applies in a few places, the same can be done for tables and so on, we likely need to debounce our buttons a little bit or something like that.

**Comment by mjashanks** [comment]
Stops multiple records being created - but this is still a bug... I have almost got a good fix for it, but probably too risky right now...
https://github.com/mjashanks/budibase/tree/client_update_state_on_save_record

Have added the `|once` for now
