### ISSUE TITLE
Simple loop in button actions and page load actions

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#7392]
Sometimes you just want to process multiple records at the same time. Like a table-like editor where your data should be saved into multiple records. Or you need to select multiple rows in a table and process them. In those cases i really desparately need to be able to loop. Handing it to an automation does not solve the problem because they run asynchronously, user can't see the result of their action when they are taken back to list view because automation didnt finish running yet.

**Comment by Rory-Powell** [comment]
Will be implemented by: https://github.com/Budibase/budibase/issues/9890
