### ISSUE TITLE
Table URL prop doesnt have access to the "Row Detail" url

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#740]
When I add a table, and try to set the Table URL prop, the "Row Detail" URL is not available (which is the only one i need).

This is because the Table does not know it is in the "Context" of a particular backend table. Ask me for more info...

![image](https://user-images.githubusercontent.com/3524181/96271819-407f7180-0fc5-11eb-8b1c-74be2a0de03e.png)

**Comment by aptkingston** [comment]
This is sorted in my PR! There's a new component which **only** list detail page URL's instead of exluding them.
