### ISSUE TITLE
Update table data via csv import

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#7400]
### Discussed in https://github.com/Budibase/budibase/discussions/7353

<div type='discussions-op-text'>

<sup>Originally posted by **yewkay** August 19, 2022</sup>
It seems that there is only an import function in the database CSV import function. At the moment I didn't find a function within budibase to update a table with existing data using csv. Importing a csv into a table with data will repeat the data. 

I would like to propose a way of matching the data to be updated eg: using a user-defined column as the ID, so each row item in that column will be matched and all the other columns will be updated with the new CSV being imported.

Additional suggestions to build on the import function:
- it could also contain mapping of columns, eg: DB columns A, B, C.. etc are matched to CSV's Columns E,F,G
- Additional columns that are not matched in the CSV can have the option to either ignore or create a new column 
</div>

**Comment by stellarfinn** [comment]
@melohagan  Has this been abandoned?

**Comment by melohagan** [comment]
![Screenshot 2023-09-20 at 15 44 59](https://github.com/Budibase/budibase/assets/101575380/5493ddbf-44c7-4953-bfde-11d307199a9b)

Hey @stellarfinn 

This has already been released for the internal Budibase DB!

It was skipped for external databases because there would have been many implementations to do, and you can write your own update queries for external datasources.
