### ISSUE TITLE
Remove localstorage from account-portal: Registration form - Error: Invalid body - "tenantName" must be a string

### ISSUE THREAD

**Issue by otamxfcz** [Budibase/budibase#7402]
Registration form.

Steps to reproduce the behaviour:
1. Go to https://account.budibase.app/register
2. Fill in the email address and continue
3. On the next page fill in the name and password and click continue
4. Where there is a choice of how to host it click cloud (not self-hosted)
5. Do not fill in any data on this page
6. Click back to get to the page with the hosting choices
7. Click on the self-hosted option
8. It throws invalid body exception

Expected behaviour:
8. It should send me a verification email and allow me to continue in the process

![image](https://user-images.githubusercontent.com/20321524/185939447-7bed87f9-25c7-4d3f-9534-635b1c647643.png)
  

 - OS: Windows 11
 - Browser Google Chrome
 - Version 104.0.5112.82 (Official Build) (64-bit)

**Comment by aptkingston** [comment]
This has been fixed. We no longer use localstorage.
