### ISSUE TITLE
Can't open attachments anymore

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#7410]
**Hosting**
- Self
  - Method: docker
  - Budibase Version: 1.2.36
  - App Version: 1.2.36

**Describe the bug**
We have a table with contracts and these contracts have attachments like a PDF.
Since yesterday we get a an error.

**Expected behavior**
Download/Open PDF.

**Screenshots**
![Error](https://user-images.githubusercontent.com/95284278/186091373-71540140-dbfd-4687-826f-e1f29fe8db69.png)

**Comment by kasgithub8** [comment]
**Update**

**Hosting**
- Self
  - Method: docker
  - Budibase Version: 1.2.47
  - App Version: 1.2.47

**Describe the bug**
We have a table with contracts and these contracts have attachments like a PDF.
Since today we can download the files but they are basically non existent.

**Expected behavior**
Download/Open PDF.

**Screenshots**
![image](https://user-images.githubusercontent.com/95284278/186092313-52eba8fb-3c3f-4ea6-817b-dd0fdcd4db81.png)

**Comment by shogunpurple** [comment]
Hi @kasgithub8 - are you using the packaged budibase MinIO in your installation, or are your using another provider, such as amazon s3 etc?

**Comment by kasgithub8** [comment]
> Hi @kasgithub8 - are you using the packaged budibase MinIO in your installation, or are your using another provider, such as amazon s3 etc?

Hi @shogunpurple,

I think we are using the packaged one.

**Comment by kasgithub8** [comment]
@shogunpurple & my automations are out again.

**Comment by kasgithub8** [comment]
Any updates?

**Comment by kasgithub8** [comment]
Update:

Files that got attached last week seem corrupted and can't be reached.
Though If our users create rows with new attachments, they are reachable.
We really need the attachments because they're important.
