### ISSUE TITLE
Drag and drop indicator does not go away 

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#7412]
The drag and drop indicator does not go away after dragging and dropping.
https://vimeo.com/742168849/dbc1dc8553

A refresh solves the problem.

- Chrome
- Mac
- Cloud

**Comment by aptkingston** [comment]
Was this the first time you've seen this? We haven't made any changes to this in a long time so I'm wondering if it's a browser update or something. In this video it looks like you have already "dropped". Can you easily reproduce it by dragging anything or is it some specific component that causes it? Could you also check devtools when it happens in case the client is crashing and just causing it to freeze?
