### ISSUE TITLE
Postgres CRUD - Array Types (error: malformed array literal)

### ISSUE THREAD

**Issue by bgregory-pmc** [Budibase/budibase#7463]
**Hosting**
- Cloud
  - Tenant ID: peoplesmortgage

**Describe the bug**
Postgres requires array literals to match the format `{"Item","Item2","Item3"}`. (Exclude quotes for integer/decimal arrays)

When utilizing one of the auto-generated CRUD screens for a database table, update forms in specific will have issues with Postgres array literals. The form will not populate with the curly braces necessary to denote proper Postgres syntax for an array literal, resulting in an error upon saving: `error: malformed array literal: "first_item"`.

It does seem to properly add quotes although they're absent in the form field, it just needs to wrap the whole thing in curly braces if they're missing.

**To Reproduce**
Consider the following (simplified) PostgreSQL table:
```
CREATE TABLE
  public.employee (
    id serial NOT NULL,
    states_with_license text [] NULL,
  );
```

1. Connect to a Postgres database, and create a new screen using the basic CRUD template. Populate data if necessary.
2. Choose a table that has an array data type. (`states_with_license` in example above).
3. Preview/run the app. View an existing record on the `employee` table, ensure that record has data populated for field `states_with_license`.
4. Without making any edits on the update form, click "Save"
5. See the error: `error: malformed array literal: "first_item"`

**Expected behavior**
It would be great if Budibase could wrap curly braces around the arrays in form fields to avoid this error (preferably in a way that hides it from the user, since it's syntax that shouldn't ever really need to be modified).

**Desktop**
 - OS: Pop_OS 22.04
 - Browser: Chromium
 - Version: 104.0.5112.79

(This occurred with my colleagues on Windows 10 machines as well, Chrome)

**Additional context**
It'll work if you manually add the curly braces before saving. Some custom JavaScript could easily format the field properly, but my expectation is for the basic CRUD operations to work out-of-the-box without developer intervention.

Thank you!

**Comment by milad2golnia** [comment]
We have same problem here too.
Budibase doesn't support postgres arrays and we are receiving errors upon update.
