### ISSUE TITLE
"Favourite" Apps

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#7472]
When Im on the app list page, I want to be able to star/favourite my applications for easier access.

**COS**
- Allow users to star or favourite an application from the app list menu
- Have a way to filter down to only favourited apps
- Favourites should only be stored against a user, not the entire instance.

**Comment by andz-bb** [comment]
not sure if this would be in scope here (I can log separately if not) but if we're working on the app screen could we preserve the user's `Sort by x` selection? I often use `Sort by recently updated` but every time I come back to the Apps screen it reverts back to `Sort by name`.

**Comment by aptkingston** [comment]
> not sure if this would be in scope here (I can log separately if not) but if we're working on the app screen could we preserve the user's `Sort by x` selection? I often use `Sort by recently updated` but every time I come back to the Apps screen it reverts back to `Sort by name`.

Both of these will just be stored in global user metadata so I think it's reasonable to include persisting their sorting method in this ticket too. Both go towards improving the app filtering experience.
