### ISSUE TITLE
Failed to connect to MongoDB server

### ISSUE THREAD

**Issue by yasinormin** [Budibase/budibase#7483]
Hi
I'am trying to connect my app to MongoDB server but got this error. 
I'am sure that mongodb server is running on localhost:27017 or 127.0.0.1:27017 because Mongo Compass connected to MongoDB server and everything works fine. But when I want to setup db for my app and setting ConnectionString to "mongodb://127.0.0.1:27017" I got this error when I try to do a query.

`Query Error: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:130:17) { name: 'MongoNetworkError' }]`

Just to mention that every container in docker is running except "couch-init_1" and has STATUS of "exited(2)"

os: windows 10 enterprise ltsc
mongodb v6.0.1

**Comment by yasinormin** [comment]
After trying different databases and having the same error, finally I found that I needed to replace "localhost" with "host.docker.internal" in ConnectionString. 

"mongodb://localhost:27017" to "mongodb://host.docker.internal:27017"

**Comment by bardic** [comment]
@yasinormin where did you find this information? This solved my answer but without your comment I have no idea how I would have known this.

**Comment by yasinormin** [comment]
@bardic, I was trying to search anything related to DB connection on localhost in docker, find couples of pages like [this](https://www.howtogeek.com/devops/how-to-connect-to-localhost-within-a-docker-container/) or [this](https://forums.docker.com/t/how-to-reach-localhost-on-host-from-docker-container/113321), finally with trial and error, problem solved!
