### ISSUE TITLE
Import CSV Data into Table Failure

### ISSUE THREAD

**Issue by kyletd** [Budibase/budibase#7489]
When i upload a csv into a table on a self hosted instance of budibase, The import is successful, but it does not appear in the table. If i export to csv from the same table and open the file, you can see all the data that was previously imported. Is there something i'm missing or doing incorrectly.

**Comment by theonlyhamish** [comment]
Im having the same issue, would be good to see a solution

**Comment by melohagan** [comment]
Closing as there are no labels, and no reproduction steps, screenshots, etc have been given.
