### ISSUE TITLE
cron automation continues after deletion or changing time

### ISSUE THREAD

**Issue by yeoldegrove** [Budibase/budibase#7494]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.2.47

**Describe the bug**
This somewhat similar as #6073.
I noticed that an old deleted cron trigger still creates some files on my fileshare.
The automation is long deleted in the automation tab but an export of my app still includes it!
My automation tab currently lists 3 cron triggers, but the export includes 21 ...

It may be hard to analyze what went wrong as this app is running for quite some time now and was updated many many times. What really would help me is some kind of API-call or DB-query to get rid of these old cron triggers.

**Comment by yeoldegrove** [comment]
I had a deeper look at the couchdb side of things.
Are there supposed to be that many conflicts?

![image](https://user-images.githubusercontent.com/8668070/188312931-4e2676fa-b18a-47e9-81e7-6480e11d953d.png)

#1646 is also still happening to me. I cannot delete certain automatons unless I delete their conflicts in couchdb.
Maybe it is related?

**Comment by yeoldegrove** [comment]
@shogunpurple Is there any easy way to redact the data in the export?

The app itself is "8 month old" but was updated many times over it's lifetime and now is up2date in regards of the budibase version.

I deleted all conflicts two days ago and most of my issues related to automations seem to be solved now.

But... In the `app_metadata` new "minimal conflics" still pop up. e.g.:
![image](https://user-images.githubusercontent.com/8668070/188667510-35fba482-7ea1-46ab-8588-a129eda3dc34.png)

**Comment by shogunpurple** [comment]
@yeoldegrove there isn't an easy way to do it - you can export without rows (the data in the tables) and see if that issue still occurs. But if it's all working on the latest version and this hasn't cropped up again, I'm inclined to believe that this might have been a bug that has since been fixed.
