### ISSUE TITLE
navigation bar doesn't update in published site

### ISSUE THREAD

**Issue by GabrieleLabanca** [Budibase/budibase#7509]
**Hosting**
- Self
  - Method: k8s
  - App Version:  1.1.17

**Describe the bug**
While I could add the link for a new page in the "design" page, when published it doesn't show in the app.

**To Reproduce**
1. The app was using a deprecated layout for the bar.
2. Detach the layout from the navigation bar.
3. Add the link -> visible in the design
4. Publish

**Expected behavior**
The navigation bar should look the same as in the developing view. 

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by shogunpurple** [comment]
Hi @GabrieleLabanca - could you send an app export of your app here so we can verify? Thanks
