### ISSUE TITLE
Dates from a MySQL Database are Incorrect

### ISSUE THREAD

**Issue by validlogin** [Budibase/budibase#7531]
**Hosting**

- Self
  - Method: Docker Compose, Ubuntu Server
  - Budibase Version: 1.2.52
  - App Version: 1.2.52

**Describe the bug**
When a date field is used as a column in a row, the dates will be displayed incorrectly. All the dates are one day behind their actual value. (Please note that all dates are random test data and not actual birthdates from a true data source.)
![image](https://user-images.githubusercontent.com/63905362/187643105-de54bf61-0f84-42c6-a67d-a71c4156a3f1.png)

The same issue applies when viewing the data from the Data view inside the builder:
![image](https://user-images.githubusercontent.com/63905362/187643357-18c9509e-c752-4bb9-a200-782281a6dba5.png)

However, when viewing the data directly from the MySQL database, the dates are correct (not shifted one day back):
![image](https://user-images.githubusercontent.com/63905362/187643668-6fffcdf1-d01a-4b3a-9ebe-da14212a11d9.png)

Even more interestingly, when using a repeater to display the date, the date shows up correctly:
![image](https://user-images.githubusercontent.com/63905362/187644531-bb72f364-d034-4aa2-b50e-1de4919e242f.png)
While the Data page and Row shows this date as 2022-8-28.

**To Reproduce**
Add a MySQL database to Budibase
Create a new row with a form and date picker.
View the database in the data view or as in a row.

**Expected behavior**
The date should not be shown as one day prior, but should remain the same as the initial selection.

**Screenshots**
See above.
  
**App Export**
N/A

**Desktop (please complete the following information):**
Appears to apply to all browsers and OS'es.

**Additional context**
This may be a timezone related issue. It seems to be related to issue #5553, as the data we are is DATE only. However, Budibase imports this as Date/Time and adds a 00:00:00 timestamp to the data, possibly causing the day prior to be shown instead.

This also may be related to issue #5548, in this issue a timestamp is also appended to the data.

**Comment by validlogin** [comment]
Appears to be very closely related to issue #6227

**Comment by aptkingston** [comment]
Hi @validlogin. Assuming the underlying type in your database does not have timezones (i.e. it is not a `timestampz`), then you should just enable "Ignore timezones" in your field schema to ensure that Budibase does not consider your values to be stored in UTC and in need of conversion.

Enabling this option will make Budibase show the data exactly as it is stored inside the table.

You can enable it for your column at the bottom of the schema settings:
![image](https://user-images.githubusercontent.com/9075550/187851072-49b02c31-0a3c-4b1f-8122-a5fa14bd6b09.png)

**Comment by validlogin** [comment]
@aptkingston That seems to have fixed it! Funny thing was that I tried it but didn't notice that it fixed the issue because I fetched the tables after changing this option and it didn't persist. Thank you!
