### ISSUE TITLE
Users, Adding a new user, if you copy the email with empty space in front or back, and paste it, an error message is displayed "Please enter a valid email" 

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#7534]
1. Navigate to https://test.budirelease.live/builder/portal/apps
2. Click "Users" 
3. Add Users 
4. Paste the email mihail@budibase.com with empty space on the back 

Expected result: I should be able to add the user and Add user button should be active
Actual result: Error message is displayed " Please enter a valid email" 
![Screenshot 2022-08-31 at 13 38 32](https://user-images.githubusercontent.com/102024164/187660498-cac5a700-4368-4f14-b5c0-17fa9a824483.png)

**Comment by aptkingston** [comment]
This happens if you just type it too (not just pasting) - we just don't trim whitespace and it flags any whitespace as invalid. So we just need to trim the values entered here.

**Comment by PClmnt** [comment]
This appears to be fixed now.
