### ISSUE TITLE
REST API connector - common headers do not save

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#7538]
**Hosting**
Cloud

**Describe the bug**
When I add a header to the rest datasource (at the datasource level, not the query level) - the header value does not save

**To Reproduce**
1. Create a new REST datasource
2. Add a header with a key and a value
3. Click save
4. Navigate away from the REST datasource
5. Navigate back to the REST datasource

Header key and value should be saved - the **value** is not saved

![image](https://user-images.githubusercontent.com/3524181/187682904-3fb11b40-636b-467f-ab22-fd86f8b828fb.png)

**Comment by PClmnt** [comment]
Seems to be fixed now.
