### ISSUE TITLE
Continue Actions if Execute Query Results Fail

### ISSUE THREAD

**Issue by JayP718** [Budibase/budibase#7548]
Currently if the execute query action fails all actions after it do not run. I'm am assuming this is expected behavior which is why I'm raising this as a feature requests.

In my use case I am running an execute query action to run a stored procedure. That stored procedure raises an error which shows up in Budibase nicely. 

However, I still want to conduct some actions after the "query" fails. I want to go back to a certain form step and set some states.

I feel like if actions continued it would only enable more flexibility and customization since the developer can still chose to stop all further actions if required. Just an idea.

**Comment by melohagan** [comment]
Hey @JayP718 

I think you could use a **Continue If** action for this.
![Screenshot 2022-12-09 at 14 48 13](https://user-images.githubusercontent.com/101575380/206728109-74f0964d-98c2-468b-a2e9-8fb716d420ee.png)
