### ISSUE TITLE
Alphabetically Ordered Automation List

### ISSUE THREAD

**Issue by R2bEEaton** [Budibase/budibase#7565]
**Describe the feature request**
The automation list is currently ordered by the internal ID of the automation, making finding automations pretty annoying. You also cannot use your own naming scheme to group related automations as the naming is ignored for sorting.

**Screenshots**
This problem is exacerbated as number of automations increases:
![image](https://user-images.githubusercontent.com/34921506/187889951-8bcf55b1-a21c-4d98-960c-864addcf6b6b.png)

**Comment by poirazis** [comment]
Also a grouping mechanism would be good ( various parts of BB ).
Like grouping tables / queries in the DataSource, grouping Automations and an incremental Search.

Say you have 100 Automations, to able to split them into groups ( Invoicing, AutoSocialMediaPosting etc ) so you can navigate better. 

just an idea!

**Comment by R2bEEaton** [comment]
Totally. I feel Automations need a pretty big overhaul in general. Here are some more ideas I compiled recently: #7553.

**Comment by ConorWebb96** [comment]
Going to close this as this is done.

Will open a separate feature request for categorising and grouping automations. Will link back to your comments.
