### ISSUE TITLE
Can't access public part of app

### ISSUE THREAD

**Issue by fredhp** [Budibase/budibase#7598]
Test URL: 
https://budibase.relt.com.br/app/adpecs-avaliacao-de-desempenho#/assinatura/o_ta_9c07e285afcc4bbeab5e85eb27925c16_16c725de3a4542d69712edc66145a99d

Errors:
![image](https://user-images.githubusercontent.com/382703/188228767-3633cb86-f463-4175-9bcb-27df12e906b6.png)

Version 1.3.1, using docker, already run "cli-linux hosting --update"

**Comment by Klience** [comment]
@fredhp I had the same issue yesterday. The 1.3.2 update fixed that for me.

You still have 1.3.1 version as far as I can tell. Judging from the screenshot you posted.

Try updating the app to 1.3.2 and re-publish it.

P.S. You can see the reference to #7593 issue.

**Comment by shogunpurple** [comment]
This hasn’t been rolled out to self host - I’ll kick off that job now, and you should be able to update your installation and the issue would be resolved. Closing this one

**Comment by fredhp** [comment]
Guys, problem solved! Thanks
