### ISSUE TITLE
Can't build single container image for the latest master branch (v1.3.4)

### ISSUE THREAD

**Issue by taoyuan** [Budibase/budibase#7603]
Can not build the single container image for the latest master branch (v1.3.4). It will throws error below when building: 

```
Cannot find module '@shopify/jest-koa-mocks' or its corresponding type declarations.
```

Just run `yarn build:docker:single` or run `Deploy Budibase Single Container Image to DockerHub` action in github actions. You will see the error.

**Comment by aderici** [comment]
Facing the same issue here! please help! also happens on development branch

**Comment by aderici** [comment]
did you also just change couchdb persist folder from couch to couchdb? Upgraders won't be happy

**Comment by taoyuan** [comment]
No, I just keep the default settings. 

However, when upgrading, I encountered that the design UI could not be displayed, any project (original or new) always kept loading, but the preview was fine.

After I restarted the database related docker services, it worked. 

When I was about to try the single docker image, I encountered the situation described in this issue.

**Comment by aderici** [comment]
That comment was for the budibase team. I believe the persisted files folder name changed for couchdb so it didnt automatically pick up my old files, i had to change local persisted folders name to get it to work. 

I could run the single docker by adding "yarn add @shopify/jest-koa-mocks" to dockerfile just before worker build command.

I have also faced the same issue that builder can not display pages, unable to develop anything. I tried restarting the docker container, no luck. do you remember what exactly you restarted?

**Comment by taoyuan** [comment]
Run `yarn dev:stack:down` and `yarn dev:stack:up` in `packages/server` to re-up docker services. After that, restart budibase apps. Good luck.

**Comment by jonnymccullagh** [comment]
> That comment was for the budibase team. I believe the persisted files folder name changed for couchdb so it didnt automatically pick up my old files, i had to change local persisted folders name to get it to work.

That is on me. I will revert that after Mike addresses the build issue

**Comment by aderici** [comment]
@mike12345567 thanks for the fix. Have you seen #7630 ? Even if you do build the app, can not view screens as a developer. /preview endpoint keeps returning 403

**Comment by taoyuan** [comment]
@mike12345567 Still can't build the single container image. The same error throws.

**Comment by Rory-Powell** [comment]
@taoyuan we're working on a change now that should resolve the issue

**Comment by geertvanheusden** [comment]
Would it be possible to have an automated build setup for this Single container image in Github Actions and let it automatically push to the Docker Hub? That would be really great and helpful. 😊

**Comment by Rory-Powell** [comment]
@geertvanheusden we do have this in place, we will push the single image build at the end of each development iteration

**Comment by Rory-Powell** [comment]
The single image should now be able to be built from master

The latest version `1.3.11` has been released to docker hub: 
https://hub.docker.com/layers/budibase/budibase/v1.3.11/images/sha256-9e25a0be84733f467ab3731b07a7bff90770e4be8625575f4f07eda41ed19cb1?context=explore

**Comment by geertvanheusden** [comment]
> > That comment was for the budibase team. I believe the persisted files folder name changed for couchdb so it didnt automatically pick up my old files, i had to change local persisted folders name to get it to work.
> 
> That is on me. I will revert that after Mike addresses the build issue

Correct me if I am wrong but I don't think this change is reverted in the 1.3.11 build?

**Comment by jonnymccullagh** [comment]
Not yet I needed to be able to build to test it. Working on that now.

**Comment by jonnymccullagh** [comment]
I believe the data directories should be reverted now. Still working around the Microsoft-isms of the Azure App Service. They have an environment variable named PORT that they already pass through to all containers with a default setting of 80 so that messes things up a little.
