### ISSUE TITLE
Let us disable hard-coded notifications (due to new custom notifications)

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#7604]
**Describe the feature request**
With custom notifications that were introduced recently, we should be able to disable the built-in native notifications. These have internal "Row Saved" or "Bad Request" messages that are non-informative for users. By users I mean people who use the app, not those who build the app with Budibase.

E.g., a public user can access a submission form. When submitted, they should see the custom "Thank you" notification, not "Row Saved". As they don't have access to any rows or database.

These also stack above custom notifications cluttering the space.

**Screenshots**
![notifications](https://user-images.githubusercontent.com/94982318/188267084-e159d4cf-5f90-4c44-934e-ba605f8b35e9.png)

**Comment by JayP718** [comment]
+1 I have about 5 queries that run consecutively causing 5 notifications appear at once. So happy to hear custom notifications have been enabled :)

**Comment by Klience** [comment]
@JayP718 -- I have 2 "save row" actions that save data to two tables - job applications and resume database. This fires off two "Row saved" notifications that a public applicant sees. With a custom notification it shows 3 of them.

Didn't realize that apps can actually have use cases with more queries. 5 notifications stack up in a huge column I believe :D

**Comment by aptkingston** [comment]
Good suggestion and easy to implement! We can add a checkbox setting to any action that currently has a forced notification allowing it to be disabled. It makes sense to allow this since we've added the custom notififcation action, like you said.

**Comment by JayP718** [comment]
Hey @aptkingston,

Do you know if this is on the horizon? Right now the 5 alerts are really throwing off our users during UAT. I know you all have a lot on your plate, so if it's a simple change maybe I can take a stab on it?

**Comment by hawkinsjon** [comment]
+1 I'm running into the same issue and would love to disable or change color/label of the default notifications.

**Comment by luigiPinnaAevo** [comment]
Great, it would be a very useful improvement.

**Comment by rose111data** [comment]
+1 on this

**Comment by luigiPinnaAevo** [comment]
Great! Thank you @FlaminWrap !!

**Comment by Rory-Powell** [comment]
Implemented in above pr
