### ISSUE TITLE
Options Picker

### ISSUE THREAD

**Issue by touchsky2018** [Budibase/budibase#7614]
I want to set the default value of Options picker
but not work even I set a fix value, show null in page

another problem, can set the option picker with no blank option.

**Comment by melohagan** [comment]
Hi @touchsky2018 

The default value you are trying to set - is it present within the list of options?

**Comment by touchsky2018** [comment]
of course. the default value is in the list of options.
<img width="316" alt="20220905204125" src="https://user-images.githubusercontent.com/43028495/188451940-62edb7f1-45f2-45ad-8074-6232ea5a6a59.png">
@melohagan

**Comment by aptkingston** [comment]
The default value needs to be the "value" field instead of the "label" field - in case you have different fields for "value" and "label" in the options picker.

**Comment by shogunpurple** [comment]
@touchsky2018 did you get this one resolved?

**Comment by touchsky2018** [comment]
the "value" field is same with "label" field.  @aptkingston 

![图片1](https://user-images.githubusercontent.com/43028495/188654511-802e10ed-827f-42dc-983e-78ff26ed00ca.png)

**Comment by touchsky2018** [comment]
> 

not resolved

**Comment by aptkingston** [comment]
@touchsky2018 is this field inside a form that is inheriting data? The default value is only used if no existing value exists. Could you try renaming your options picker to something that definitely does not exist in your data?

**Comment by touchsky2018** [comment]
I don't know what's your meaning.  @aptkingston 
the default value is one of the options of options picker.
If set default value, the page should show the default value. but show the "null"

**Comment by aptkingston** [comment]
@touchsky2018 if you go to the settings for the form that this field is in - is it a "Create" form or an "Update" form?

**Comment by touchsky2018** [comment]
yes, "Update" form
Is there any relationship between default value of options picker and the create/update form.
Still show null when I set default value with create  @aptkingston

**Comment by AlejandroFNadal** [comment]
I am having the same bug right now.  The default value does not work. My form is of the update type @touchsky2018 @aptkingston
![image](https://user-images.githubusercontent.com/32724827/206130141-e81ba509-61ba-47ab-89b5-53342cdf8f2d.png)

@melohagan should I create a new bug report or we could reopen this one? My bug is exactly the same

**Comment by AlejandroFNadal** [comment]
> @touchsky2018 is this field inside a form that is inheriting data? The default value is only used if no existing value exists. Could you try renaming your options picker to something that definitely does not exist in your data?

![image](https://user-images.githubusercontent.com/32724827/206131731-c8593a04-f752-4132-bf67-49556b7e31ff.png)

I have tried that too, just in case, it doesnt work as well.

**Comment by melohagan** [comment]
> I am having the same bug right now. The default value does not work. My form is of the update type @touchsky2018 @aptkingston ![image](https://user-images.githubusercontent.com/32724827/206130141-e81ba509-61ba-47ab-89b5-53342cdf8f2d.png)
> 
> @melohagan should I create a new bug report or we could reopen this one? My bug is exactly the same

Hey @AlejandroFNadal 

Could you raise another bug report with the reproduction steps please. I couldn't remember why I'd closed this one, but I think it was just because the description in the OP was unclear.

**Comment by melohagan** [comment]
Possibly related to this: https://github.com/Budibase/budibase/issues/8948

**Comment by aptkingston** [comment]
Looking at both examples here, I wonder if this is something to do with the type of the value column. @AlejandroFNadal is the value column some sort of number type or a string type in your DB? 

If it's a number, could you try this for me:
- Open the binding drawer (lightning bolt icon) for the default value
- Switch to JavaScript
- Enter `return 453`

Let me know if that changes anything!

**Comment by AlejandroFNadal** [comment]
> Looking at both examples here, I wonder if this is something to do with the type of the value column. @AlejandroFNadal is the value column some sort of number type or a string type in your DB?
> 
> If it's a number, could you try this for me:
> 
>     * Open the binding drawer (lightning bolt icon) for the default value
> 
>     * Switch to JavaScript
> 
>     * Enter `return 453`
> 
>     * Press save
> 
> 
> Let me know if that changes anything!

It works using javascript! The value column is just a normal mysql INT, it is the primary key of the table
I will refrain from creating a new bug report until @aptkingston responds, because he seems to have an idea about what is happening and perhaps the bug report is unnecesary or I can describe it better after an explanation from him.

![image](https://user-images.githubusercontent.com/32724827/206140421-173a1825-868c-4336-80a9-b92bcba7e3bb.png)

A screenshot from the explain command on the table. The source of the DP is a query executed over the table, not the table itself:

`SELECT ID_Mitarbeiter, CONCAT(Surname, ' ', Name) as fullname from mitarbeiter ORDER BY Currently_hired DESC, Surname;`

Thanks a lot to both @melohagan and @aptkingston  for your prompt responses <3
