### ISSUE TITLE
handlebars  ellipsis is not work

### ISSUE THREAD

**Issue by touchsky2018** [Budibase/budibase#7617]
handlebars  ellipsis is not work

{{ ellipsis  "adfasdfasdfasf" 7 }}      return  ""
{{ ellipsis  "adfasdfasdfasf", 7 }}     syntax error

**Comment by melohagan** [comment]
Hey @touchsky2018 

Please provide reproduction steps as well as a detailed description of the problem.

**Comment by mike12345567** [comment]
Hi @touchsky2018 - going to close this issue until better reproduction steps can be provided as in the latest versions of Budibase this appears to work in the core library (tests passing) and works in the design/data/automation sections.

![image](https://user-images.githubusercontent.com/4407001/188861326-b8b0597b-eecb-4343-984b-2f951b55930d.png)
