### ISSUE TITLE
OIDC users are not signed up automatically

### ISSUE THREAD

**Issue by yigitkeremoktay** [Budibase/budibase#7621]
Hey there,

I installed budibase via docker and setup OIDC using keycloak. Now the issue is, when sign in with a user that does not exist, I get this output on my browser:
`{"message":{"error":"not_found","reason":"missing","status":404,"name":"not_found","message":"missing","stack":"Error\n    at generateErrorFromResponse (/app/node_modules/pouchdb/lib/index.js:694:18)\n    at /app/node_modules/pouchdb/lib/index.js:6816:19\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","docId":"us_ade1a7fa-3d10-44bf-9d71-a68090948ebd"},"status":403}`
Signing with an already existing user is fine.

Version is 1.3.4

**Comment by yigitkeremoktay** [comment]
Also, when I add a custom image for the provider, when saving the settings, the page errors out saying `Error saving auth settings` and the alt text is of the img element is displayed instead.

**Comment by Rory-Powell** [comment]
Hi @yigitkeremoktay, thanks for raising this. The logic around user saving was updated in the previous release which caused this issue for you. A fix will be released shortly. Follow: https://github.com/Budibase/budibase/pull/7624

**Comment by yigitkeremoktay** [comment]
Thanks very much, looking forward to a new version soon

**Comment by Rory-Powell** [comment]
Hi @yigitkeremoktay, this has been released to self host in version `1.3.6`. I've created a separate issue for the logos not loading / saving correctly https://github.com/Budibase/budibase/issues/7639
