### ISSUE TITLE
Select Picker (checkboxes) doesn't work

### ISSUE THREAD

**Issue by Maxiwork** [Budibase/budibase#7668]
Select Picker (checkboxes) doesn't work when changing the values of it.

I have already 3 selected, when I remove one of them or all of them, it's not taken in account and when i'm sending to POST, it's like nothing change.

https://www.loom.com/share/940e0d74c69944d2a1e21a7ae23aa6dc

**Comment by melohagan** [comment]
Hey @Maxiwork 

Are you able to share the app export?

**Comment by pandel** [comment]
@melohagan 
I have the same problem. Is it helpful if you get more than one example? I can export, too...

**Comment by melohagan** [comment]
Definitely @pandel that would be very helpful 😄

**Comment by pandel** [comment]
> Definitely @pandel that would be very helpful 😄

@melohagan 
I just sent an example regarding two issues to the support. See email subject :-)

**Comment by pandel** [comment]
@melohagan 
I rearranged the whole component tree the way Andrew did here: https://github.com/Budibase/budibase/discussions/6548#discussioncomment-3568511

And this did the trick! Now selection works again with my JS and, additionally, the problem with "the last checkbox being selected, too" has gone away.

<img width="258" alt="Bildschirmfoto 2022-09-07 um 14 14 41" src="https://user-images.githubusercontent.com/12460002/188875837-3648a5c7-5478-4513-a715-c97d063c8b5b.png">
