### ISSUE TITLE
Version apps for Cloudfront caching

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#767]
Currently we invalidate the Cloudfront cache during deployment, instead it would be a good idea to version our apps with the intention of clearing out older version of apps over time.

Info on this can be found [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#Invalidation_Expiration).

**Comment by shogunpurple** [comment]
No longer necessary
