### ISSUE TITLE
Data provider filter breaking if changed and reverted

### ISSUE THREAD

**Issue by adamjdavies** [Budibase/budibase#7675]
Hello all

I'm having some issues with when editing filters on my data providers. My data is being fed into the app from an Airtable base and uses the Airtable connecter to do this. 

On the page, I have a data provider set up with two filters:

1. The first filters the data based on what is entered in my 'search bar'
2. The second filters the data based on a condition - e.g. if a field in my airtable base equals  **1** then return that row. 

Right now, the filters are working correctly. If I edit or delete this second filter and then revert it back to its original set-up, no data is being returned at all. Please see the video below for reference. 

https://user-images.githubusercontent.com/64409787/188873283-0c0f1866-0acd-4ffe-8554-010be7edddc3.mp4

I originally discovered this when trying to set-up a new filter on the same data provider but based on another field. This also was failing to work. 

I've checked my airtable queries and they all seem to look good, so I'm a bit perplexed with what is happening. I also reverted my app back to a previous version (currently running on 1.3.11) but that didn't work either. A bit frustrating as I can't get it to work!

Any ideas?

Thanks, 
Adam

**Comment by aptkingston** [comment]
Hey @adamjdavies. This sounds like the same issue I recently fixed in https://github.com/Budibase/budibase/pull/7729. Could you check and see if it's fixed? Just update to the latest version first if you're self hosted.

**Comment by adamjdavies** [comment]
Hi @aptkingston. That seems to have done it. I was also struggling to set up a new search filter on another page and I was pulling my hair out trying to make it work. This update has also fixed that too! 

Thank you so much!
