### ISSUE TITLE
API REST Queries: URI param encoding

### ISSUE THREAD

**Issue by MentalGear** [Budibase/budibase#7683]
**Describe the feature request**
When using the Query UI, it would be great if the input would be automatically URI component converted, if there are special characters in the input.
This would make it much easier to scan the parameter values in the UI and change them.

**Screenshots**
<img width="971" alt="Screenshot 2022-09-07 at 18 12 09" src="https://user-images.githubusercontent.com/2837147/188928294-361e0164-6197-4632-8c3c-1d09a8a8ad8f.png">

**Comment by MentalGear** [comment]
Instead of having to write it like this:

<img width="964" alt="Screenshot 2022-09-07 at 18 15 24" src="https://user-images.githubusercontent.com/2837147/188928493-f9f4099e-cfe4-4071-b5ac-c79ab39607ba.png">

**Comment by MentalGear** [comment]
PS: Happy to submit a PR if someone can point me where I can find the relevant files in the src.

**Comment by mike12345567** [comment]
Hi @MentalGear - thanks for the suggestion - I think this is more of a bug than a feature - it really should do this already! I've made a change on one of my bug squashing branches.

**Comment by MentalGear** [comment]
Thx for the quick reply, Mike!
I'm also experiencing a bug on 1.3.2: when trying to save a modification to the query, the green save toast is displayed, yet no changes are saved on reload. Is this already known ?

**Comment by mike12345567** [comment]
Hi @MentalGear - this is likely due to trying to modify the parameters through the URL, rather than one of the options in the Params tab. Some changes to the URL currently will not be reflected in the saved query - I've made a change on my branch so that changes to the URL will update parameters correctly.

**Comment by FocusDesigner** [comment]
I'm not sure if this is related, but I have this problem the other way around. 

If I use a binding as variable for the params the handlebars are getting encoded in the url as well. 
This way the variable isn't translated correctly, which leads to an error in the request.
According to this guide [https://docs.budibase.com/docs/rest-bindings](https://docs.budibase.com/docs/rest-bindings) that shouldn't be the case, or am I missing something?

**Comment by charlesDannerSpg** [comment]
Hi @mike12345567 I am also facing similar problem to @FocusDesigner, where the bindings are encoded into the url.

**Comment by mike12345567** [comment]
Hi guys, I'll get a fix out for this today.

**Comment by danielband** [comment]
@mike12345567 idk if related or separate issue. The encoding seems to work fine at first, but after navigating to the design paneland, then back to Data the character '%' gets encoded. So '@' becomes %2540 int the url.
