### ISSUE TITLE
display local timezone datetimes with handlebars from UTC in datetime

### ISSUE THREAD

**Issue by pbrink231** [Budibase/budibase#7713]
**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 1.2.36
  - App Version: 1.2.36

**Describe the bug**
I have a MySql database with Datetime fields.  This is a new table used only with budibase.  I am saving the rows through budibase which are being saved as UTC date times in the database.

I am trying to display this datetime in a textfield from a query.  the field is set as a datetime field inside the query schema.
date in database = "2022-09-09 19:34:22"
{{ mydatefield }} = "2022-09-09 19:34:22"
{{ date mydatefield "YYYY-MM-DD hh:mm A" }} = "2022-09-09 07:34 PM"
{{ date mydatefield "YYYY-MM-DD hh:mm A" "UTC" }} = "2022-09-09 11:34 PM"
{{ date mydatefield "YYYY-MM-DD hh:mm A" "UTC-05:00" }} = {{ date [c73ddb96fd23a4485a8d1a4cd25f37e94].[approval_date] "YYYY-MM-DD hh:mm A" "UTC-05:00" }}

I have used "UTC-5", "America/New_York" and nothing seems to show the date correctly.

What I want is:
{{ date mydatefield "YYYY-MM-DD hh:mm A" "UTC-05:00" }} = "2022-09-09 3:34 PM"
or
{{ date mydatefield "YYYY-MM-DD hh:mm A" }} = "2022-09-09 3:34 PM"

It is thinking this is the local time instead of thinking it is UTC time which is how budibase stores it.  It seems like tables are managing this timezone conversion for columns.  Not sure what I am missing.

**Comment by pbrink231** [comment]
Looked into this more.
I guess what I need is a way to use dayjs library in the javascript module.
Currently the {{ date }} helper uses new Date(value) to parse the dates which is wrong.
mysql connector uses dayjs(value) to parse the date string.

I think it would be good to have a helper to use dayjs to parse a date string that can be fed into the date helper.

![image](https://user-images.githubusercontent.com/8224560/189448608-1c7116cb-22df-44c3-8639-ebb9a09c1a2f.png)

**Comment by melohagan** [comment]
Hey @pbrink231 

It's not clear what's being asked here. 

If it's still an issue, please fill out the bug template, with reproduction steps and screenshots.

**Comment by andreipopovici** [comment]
@melohagan I think the ask is the same as in https://github.com/Budibase/budibase/issues/4564: access to dayJS within Javascript bindings. 🙏

Commenting just to show there are multiple related requests, no need to reopen this particular issue.

**Comment by melohagan** [comment]
Thanks @andreipopovici !
