### ISSUE TITLE
Endless loading design section in any browser

### ISSUE THREAD

**Issue by mralesssss** [Budibase/budibase#7718]
Hi everyone,

I just self hosted Budibase using docker on my Windows. The data and automation section works well. But when I go to Design i get an endless loading page. I think it was also mentioned in #3248.  I tried with different browers (Chrome, Firefow, Edge) but its always the same. Hope you can help me. Thank  you!

Best regards

**Comment by aptkingston** [comment]
Hi @mralesssss. #3248 is a very old issue that was solved a long time ago. If you are using the single docker image then there is currently a problem which we are aware of, but a fixed image has not been pushed yet. You can either wait for the new image to be published, or deploy the stack of individual images with [docker compose](https://docs.budibase.com/docs/docker-compose) instead.

Closing in favour of #7630 which describes this in more detail.

**Comment by mralesssss** [comment]
Thank you! I think i will wait for the fixed image. Do you know when it will be published? (approximately) @aptkingston

**Comment by aptkingston** [comment]
Should be out on Monday!
