### ISSUE TITLE
Design loading - 403 Forbidden

### ISSUE THREAD

**Issue by cstasius** [Budibase/budibase#7723]
Hosting

Self
Method: docker single image
Budibase Version: 1.3.11

Describe the bug
Design Page keeps loading. Error appear for any app (new, template etc.) Development tools in browser show 403 Forbidden error.

Screenshots
see discussion below

### Discussed in https://github.com/Budibase/budibase/discussions/7696

<div type='discussions-op-text'>

<sup>Originally posted by **lukasrst** September  8, 2022</sup>
Hi,
I just installed Budibase via Docker on a Linux Server and the Design Page is loading endless.
The browser developer tools show the error "403 Forbidden".

This error happens with completely fresh apps as well as with templates. Tested Chrome, Chromium, Firefox and Edge with allowed Cookie Setting.

![image](https://user-images.githubusercontent.com/58342398/189082908-ec47d346-d7d3-4ef2-82df-2c928d7b92ab.png)
![image](https://user-images.githubusercontent.com/58342398/189083895-3116c65f-0eb7-4860-a60d-8b8a84320955.png)

Thanks for your help!</div>

**Comment by pigmej** [comment]
I have the same problem. The same setup method seems. Something is odd, as it was working previously.

**Comment by yarin-zhang** [comment]
I have the same problem, my version is 1.3.15 and I installed it via Docker too.

And everything works fine with version 1.2.9 that I installed via Docker on another machine.

**Comment by yarin-zhang** [comment]
![image](https://user-images.githubusercontent.com/58888890/189821750-2dc6d1f6-c301-48f8-b608-737c926ebacb.png)

I found this notice when I login Budibase.

**Comment by aptkingston** [comment]
Hey. The latest single image (v1.3.15) includes a fix for this. Please update to this version and the app preview issue will be solved :+1:.

**Comment by aptkingston** [comment]
> 

This looks like something different @yarin-zhang. Please open a separate issue if this keeps happening.

**Comment by yarin-zhang** [comment]
> Hey. The latest single image (v1.3.15) includes a fix for this. Please update to this version and the app preview issue will be solved 👍.

Thanks for your prompt reply. But I just did a Docker deployment today, and I'm using v1.3.15.

![image](https://user-images.githubusercontent.com/58888890/189847979-a27e8d3f-4171-42d4-a6db-37ebddcf5060.png)

![image](https://user-images.githubusercontent.com/58888890/189848667-edfa8b06-0c23-44a9-9dd0-75cfc096b972.png)

![image](https://user-images.githubusercontent.com/58888890/189848834-be0a4efa-2647-4006-8221-22d9e4260526.png)

**Comment by aptkingston** [comment]
@yarin-zhang could you open a new issue for this and include these same screenshots? I can see from your network log that you do not have the same isssue (you are not getting a 403 on the `/preview` endpoint which is what this issue is about).

When you open the issue could you also please fill out the template with information about your browser, and check for any errors in the browser console. Thanks!
