### ISSUE TITLE
Prevent users from deleting their own user account through public API

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#7732]
ENV  = Test Env https://test.budi.live/

1. Create an user with API 
2. Update the same user with API (remove the email in the body before you send the call)
3. Navigate to https://test.budi.live/ Users 

**Expected behavior** 
Not allow to update an user with API, without an email 
![Screenshot 2022-09-12 at 11 26 36](https://user-images.githubusercontent.com/102024164/189608355-4fc1ee8c-839f-43d2-a325-cf791d5b39f7.png)

**Comment by shogunpurple** [comment]
The API should be allowed to perform potentially destructive actions - so this is ok and users just have to be careful if they have admin rights. Although will update the title of this to prevent users from deleting themselves.

**Comment by melohagan** [comment]
In this scenario the user hadn't actually deleted the admin user, but they had set their role to power, which completely locked them out of Budibase.

Maybe we can't account for that, but I'll leave it here for reference: https://github.com/Budibase/budibase/discussions/8689

**Comment by aptkingston** [comment]
Yea you can't update yourself from the UI at all, so I feel like we should mirror that functionality in the API. Definitely shouldn't be able to update your own role.
