### ISSUE TITLE
sshd  setup on aas image not compatible with azure

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#7745]
Azure appservice not only requires openssh to be installed, but also requires a specific username and password to be set. 

Azure appservice containers are not exposed to the outer world. They are isolated and it is required that it has a pre defined user pass for ssh. It is by no means a security risk but a required setup. 

See following suggested code for getting it ready for azure : 

```
# - - -

# Install OpenSSH and set the password for root to "Docker!". In this example, "apk add" is the install instruction for an Alpine Linux-based image.
RUN apt-get -y install openssh-server \
     && echo "root:Docker!" | chpasswd

# Copy the sshd_config file to the /etc/ssh/ directory
COPY sshd_config /etc/ssh/

# Copy and configure the ssh_setup file
RUN mkdir -p /tmp
COPY ssh_setup.sh /tmp
RUN chmod +x /tmp/ssh_setup.sh \
    && (sleep 1;/tmp/ssh_setup.sh 2>&1 > /dev/null)

# - - -
```

**Comment by jonnymccullagh** [comment]
This is already added to branch: `jonny/ssh-for-aas` 
I will merge when I finish testing.
