### ISSUE TITLE
Deleting selected row of table - remains selected after deletion

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#7760]
### Discussed in https://github.com/Budibase/budibase/discussions/7707

<div type='discussions-op-text'>

<sup>Originally posted by **eyduh** September  9, 2022</sup>
Hi,

I have a simple table view of a form and would like to allow users to download a CSV of the entire table, as well as make some simple editing of the rows such as deleting duplicate entries. 

Exporting works fine, but if I delete a row I think it stays selected somehow and interferes with other operations:

I set up a table like so:
![image](https://user-images.githubusercontent.com/29815625/189352702-f16001f4-7b06-4132-9cb7-50c6baa8610d.png)

and the delete button like so:
![image](https://user-images.githubusercontent.com/29815625/189352971-a3e88f9a-dfac-4a6f-85fd-937ba152c427.png)

if I go into the exported app and delete a row and then try to delete another row I get `missing` in red:

https://user-images.githubusercontent.com/29815625/189354941-2e483084-f608-4921-b448-c82ec4898076.mp4

when I reload the page and try to delete the same row that gave me "missing" it works fine.
</div>

---

I was able to confirm this - the row stays selected (i.e. an item in the Selected rows binding value) even after deletion.

**Comment by amit-meshram** [comment]
@melohagan Is this issue resolved?

**Comment by melohagan** [comment]
> @melohagan Is this issue resolved?

Not yet - I had looked at it, but it wasn't quite right.

**Comment by melohagan** [comment]
Appears to be fixed
