### ISSUE TITLE
Add icon button to allow component tree to expand / collapse

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#7763]
**Describe the feature request**
As a user I would like to click a toggle button to expand or collapse all of the components in my component tree.

Related discussions:
 - https://github.com/Budibase/budibase/discussions/7673
 - https://github.com/Budibase/budibase/discussions/7761

**Comment by ConorWebb96** [comment]
Not a button, but you can drag the component tree now to increase of decrease its size. Closing as it has been resolved.
