### ISSUE TITLE
Unable to install helm chart

### ISSUE THREAD

**Issue by tharwan** [Budibase/budibase#7778]
Hi, 

I am trying to install the budibase helm chart on our cluster. 

ChartVersion 0.2.11          
AppVersion 1.0.214

I get the following error message: 
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "budibase": current value is "ingress-nginx"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "budibase": current value is "ingress-controller"

Our cluster already has nginx ingress and I would like budibase to be hosted behind a subpath.

**Comment by AiCaptain** [comment]
> Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata;

Are you installing it in the namespace `budibase`? Maybe there is a problem with the permissions ... 
 
> Our cluster already has nginx ingress and I would like budibase to be hosted behind a subpath.

Do you mean nginx ingress **controller**? Try to set `ingress.nginx` to `false`. AFAIK the subpath must be set under the `hosts` section in your values.yaml.

**Comment by tharwan** [comment]
Yes the namespace was budibase with sufficient permission. Setting nginx to false made no difference.

**Comment by AiCaptain** [comment]
We also use an existing ingress controller (in our case it's a kong). The overwritten ingress configuration looks like
```
ingress:
  enabled: true
  nginx: false
  annotations: 
    kubernetes.io/ingress.class: kong
```
followed by some kong specific annotations. 

I think most important is to set `ingress.nginx` to `false` to prevent that helm installs the nginx ingress controller subchart (again). The flag is only used in the chart.yaml. The annotations `meta.helm.sh/release-name` and `meta.helm.sh/release-namespace` are annotations of the deployment. In your case it seems, that this is the problem: a second deployment of the nginx ingress controller. 

If you set `nginx` to `false` after a first try with `true` maybe there are some artifacts left in the namespace.

I know, this is not a solution for you, but I hope it helps you getting closer to the problem and a solution.

Cheers
André

**Comment by tharwan** [comment]
Alright, maybe I just clean up and restart the process.

**Comment by tharwan** [comment]
deleting and recreating the namespace did solve the problem.
