### ISSUE TITLE
The Multitenancy-Flag is ignored

### ISSUE THREAD

**Issue by AiCaptain** [Budibase/budibase#7787]
**Hosting**
- Self
  - Method: k8s on nutanix and azure clusters
  - Budibase Version: 1.3.11 / 1.3.15 (probably all versions > 1.2.52)

**Describe the bug**
I tried to update our selfhosted budibase from version 1.2.52 to an 1.3.X (starting from 1.3.11 and gone backwards down all official releases 1.3.X release) and since a couple of days also the 1.3.15. After a `helm install` the first screen that appears is the  `builder/auth/org` screen, which I did not expect because I did not changed `globals.multiTenancy: "0"`

Analyzing the network traffic in browser I saw the response for `api/system/environment`:
```
{"multiTenancy":true,"cloud":false,"accountPortalUrl":"","isDev":false}
```
Dived deeper into the problem I opened a shell into the container in the worker-pod, installed a curl and checked the env var `MULTI_TENANCY` vs the output of the rest call on the container and I was very surprised by the result:

```
/app # echo "$MULTI_TENANCY"
 0
/app # curl localhost:4003/api/system/environment
  {"multiTenancy":true,"cloud":false,"accountPortalUrl":"","isDev":false}
/app # 
```

What's going wrong?

**To Reproduce**
1. install budibase (>v1.2.52) via helm chart in a k8s cluster
2. open URL of deployment in browser with development tools
3. open a shell in worker-pod
4. enter commands as described above

**Expected behavior**
The multitenancy flag of the response of `/api/system/environment` should be false if globals.multiTenancy is set to "0" in the values.yaml of the helm chart.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by shogunpurple** [comment]
Hi @AiCaptain - multitenancy is not supported in self hosted envs and will be a pro feature in future.
