### ISSUE TITLE
CSV Import doesn't account for Nordic Charset

### ISSUE THREAD

**Issue by HvetemelGibson** [Budibase/budibase#780]
Budibase discriminates us from the nordic countries. 

![image](https://user-images.githubusercontent.com/65621428/97173411-cacb9080-1790-11eb-88c7-cad96568e3f1.png)

ÆØÅ won't import correct from csv :smile:

**Comment by shogunpurple** [comment]
Hey @HvetemelGibson, thanks for taking the time to raise an issue. I updated the name of the issue to be more descriptive for the team. We will look into this and should have it solved fairly soon. Thanks again 👍

**Comment by kevmodrome** [comment]
This has now been fixed in #940

**Comment by kevmodrome** [comment]
Woops! This should have been closed when the release goes live :)
