### ISSUE TITLE
Adding a form field should automatically add a parent form component if needed

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#7800]
**Describe the feature request**
It would be nice that IF the screen has no form components in it, that adding a form field, such as Options Picker, would automatically add a parent form.

In addition, if there is only one Form component on the screen, then new form field components should automatically be added into the only form component. 

**Screenshots**
![Screenshot 2022-09-16 at 11 24 58](https://user-images.githubusercontent.com/101575380/190618576-2064969e-4af3-4e10-87c2-882066cd4364.png)
*In this scenario the form component may as well be added as a parent because there was no existing form in the screen.*

**Comment by shogunpurple** [comment]
This is done
