### ISSUE TITLE
Can not unlock the Edit button

### ISSUE THREAD

**Issue by sangdth** [Budibase/budibase#7806]
**Hosting**

- Cloud
  - Tenant ID: `lakihelppi` 

**Describe the bug**
Can not edit the app name

**To Reproduce**
1. Go to `portal/apps`
3. Click on `Manage`
4. Release the lock.
5. Click on `Settings` tab
6. `Edit` button still disabled.

**Expected behavior**
After release the lock, it should allow to modify app name.

**Screenshots**
<img width="914" alt="Screenshot 2022-09-16 at 16 24 01" src="https://user-images.githubusercontent.com/1083478/190656391-698b2d84-ca1c-4d64-bd58-ba308379181e.png">

**App Export**
The app is currently using version 1.3.15.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Browser Chrome
 - Version 105

**Comment by aptkingston** [comment]
Hey @sangdth. You'll need to unpublish your app before you can change the name or URL - that's why it's disabled at the minute.

**Comment by sangdth** [comment]
@aptkingston it's correct! It works now. Sorry for false alarm.
