### ISSUE TITLE
Query Bindings on Data provider not appearing

### ISSUE THREAD

**Issue by dkaiping** [Budibase/budibase#7811]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.3.20
  - App Version: 1.3.20

**Describe the bug**
When trying to set a binding on a data provider, in the bindings area, only the "Binding Name" and "Default" fields show.  There's no Bindings Input as shown in the documentation.

Query Bindings as observed in my data provider

![image](https://user-images.githubusercontent.com/7794557/190690086-b7b96d1d-c332-44b3-98ce-b920f4287d8c.png)

Query Bindings as observed in the documentation

![image](https://user-images.githubusercontent.com/7794557/190690171-703c69dc-86f8-47ac-9f32-e1520f7420c9.png)

Note the different where the field name and default value are Read Only in the documentation with the binding expression being the last box vs in the current version there's only 2 input boxes (that are actually editable, which seems like it should be Read Only as well)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: ?

**Comment by chadgriff** [comment]
I am experiencing the same issue myself after updating to 1.3.20. My app is working normally  in my production env which is at 1.3.15.

**Comment by mike12345567** [comment]
Hi @dkaiping and @chadgriff - this issue should be fixed in version 1.3.21.

**Comment by dkaiping** [comment]
I've validated it works.  Thank you for the quick response.
