### ISSUE TITLE
Remove Multi Tenancy

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#783]
- One database per app
- Removal of client database

This will more than likely break current users apps

**Comment by shogunpurple** [comment]
### High level
- One database per app
- Get rid of client DB
- AppId -> instanceId. There will be only one ID used to identify an application

### Current Budibase Initialisation and App Creation Flow

 **Initialisation (when you open the electron app for the first time)**
 - Create a new client DB
```javascript
exports.create = async clientId => {
  const dbId = exports.name(clientId)
  const db = new CouchDB(dbId)
  await db.put({
    _id: "_design/client",
    views: {
      by_type: {
        map: `function(doc) {
            emit([doc.type], doc._id)
          }`,
      },
    },
  })
  return db
}
- ClientID is set as an environment variable on your local server for future
```

**App Creation - (Every time you create an app from the builder)**
 - POST to `/applications`
 - client ID is parsed from request body
  - Generates an appID
   - maps the appId to the clientId in the `client_app_lookup` table
  ```javascript
  const appId = generateAppID()
  // insert an appId -> clientId lookup
  const masterDb = new CouchDB("client_app_lookup")

  await masterDb.put({
    _id: appId,
    clientId,
  })

  const db = new CouchDB(ClientDb.name(clientId))
```

- Creates an app, containing a `userInstanceMap` for mapping users directly to the correct instances
- App Information gets written into **CLIENT DB**
- We will need to store this app data as either metadata or its own document in the **instance** DB. See the following to see what our current app data contains.

 ```javascript
  const newApplication = {
    _id: appId,
    type: "app",
    instances: [],
    userInstanceMap: {},
    version: packageJson.version,
    componentLibraries: ["@budibase/standard-components"],
    name: ctx.request.body.name,
    template: ctx.request.body.template,
  }```

- new **instance** DB is created
        - We then push the new instance into the application documents `instances` array, so the client db knows which instances of an app exist.

**App Package Creation (This happens after the DB stuff, and is mainly for creating static files and frontend things for budibase apps)**
- Create <appId> folder at `~/.budibase` and put screens, pages etc into it, all generated from templates that get interpolated with your app data
- download the relevant NPM modules for the component libraries and write them to disk

**Your app is now ready.**

### Proposed Setup
    - Remove all mention of appId. There should only ever be a single reference to an app and that's its instance ID
    - remove client database, userInstanceMap and storing app metadata in the client DB
    - Update auth, so with builder you can preview any instance, but with actual apps you must have an instance token for each app to log in. This means you can be logged into many apps
- Try deploying a "legacy" app to see if it still works. (testing backwards compatibility)

**Comment by mike12345567** [comment]
Most of this work was completed with the merge of the `feature/remove-multitenancy` branch, there is however still a small amount of still outstanding work around it.

This pertains to the `userInstanceMap` and the way that authentication is handled, this still needs to be updated.
This should be minor but I felt it best to do the majority of the multi-tenancy update and then do the auth update after that was finished and working, rather than cramming too much into a single PR.
