### ISSUE TITLE
[Builder] Screen Selection - Scroll into view

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#7832]
When inside the builder, we usually go from one screen to another , wither from the screen panel list, or the screen selection drop down.

Would it be possible, the screen selection dropdown to scroll into view the screen that is selected ?
It doesn't seem much, but it would greatly speed up switching from one screen to another as we are usually working on neighboring screens / routes.

For example, it should scroll into view as shown below when opening instead of going though all the list every time.

<img width="459" alt="Screenshot 2022-09-18 at 6 29 25 PM" src="https://user-images.githubusercontent.com/80512170/190915215-80fa4022-0d7c-4e09-8d42-14a6c9876edb.png">

**Comment by shogunpurple** [comment]
Thanks for the suggestion @poirazis! This is a nice idea - we will try and get this one pushed in an update in the near future. Also I just want to thank you for your feedback items and correct labeling of issues - they are always well thought out, and broken up into smaller, actionable pieces of work. 🙏
