### ISSUE TITLE
Ability to bind values of more than just components above

### ISSUE THREAD

**Issue by martkaczmarek** [Budibase/budibase#7833]
I think it would be very beneficial to be able to reference any component on the page, not only the ones that are above in the tree. 
There should be at least some unique component ID that we can bind to, regardless of where it is.
I do realize it would result in quite a bunch of nulls since some components could be non-existent at the time of execution, but let us (app creators) deal with these. 
For repeating components (such as under repeater), there could be parent-children structure (such as repeaterID[0], repeaterID[1], repeaterID.first() etc.)

Also, as mentioned in #7831 , it would be useful to reference from the component to itself's attributes (maybe through "this" keyword).

**Comment by Rory-Powell** [comment]
This may be implemented as a part of global bindings - closing as duplicate
