### ISSUE TITLE
URL variables not showing up for REST datasource bindings

### ISSUE THREAD

**Issue by dominikjannis** [Budibase/budibase#7834]
When defining a screen route containing an url variable like

"/groups/:group"

upon configuring a corresponding data provider with a REST datasource, i cannot select the URL.group binding in the query bindings. Is this intended behaviour?

I am running version 1.3.20

**Comment by deanhannigan** [comment]
Hi @dominikjannis,

I just ran through this scenario on the cloud site and was unable to reproduce the issue. 

- I added a binding called `sampleBinding` to a rest query in my system and gave it a default value.
- On the parameters for my Rest query, I added a new entry called `testParam` and set it to `{{ Binding.sampleBinding }}`
- In the designer I added a new page with the path `/param/:someparam`
- I added a new data provider using my Rest query and could see the option `URL.someparam` listed in the UI.
![Screenshot 2022-09-21 at 11 14 11](https://user-images.githubusercontent.com/5913006/191479354-968fb613-ca7e-42df-8160-0e361cfc4201.png)
- Navigating to `/param/replaceDefault123` in my app successfully binds `replaceDefault123` onto my rest requests e.g. ?`testParam=1234567` changes to `?testParam=replaceDefault123`

Do the steps used above adequately outline the behaviour you are expecting to see?

Could you run through the configuration of your Rest request in more detail?

**Comment by dominikjannis** [comment]
Sure!
My instance is self hosted, here is the config of the query in the data tab:
<img width="1092" alt="Bildschirmfoto 2022-09-25 um 13 37 17" src="https://user-images.githubusercontent.com/58996158/192141490-0b2ee07a-5239-4fdc-bb1f-837f07ed45c7.png">
this is how i configured the screen:
<img width="1117" alt="Bildschirmfoto 2022-09-25 um 13 37 51" src="https://user-images.githubusercontent.com/58996158/192141546-8d47ff46-9026-491e-9ed5-0496a0297f62.png">
and here the URL.group param i expected is missing:
<img width="1178" alt="Bildschirmfoto 2022-09-25 um 13 38 24" src="https://user-images.githubusercontent.com/58996158/192141605-b2c8de27-c156-469f-9480-35f412cfa13e.png">

Maybe i misunterstood how these bindings are supposed to be used?
