### ISSUE TITLE
Dev Environment: Mac OS X Error: (110: Connection timed out) while connecting to upstream, client

### ISSUE THREAD

**Issue by JayP718** [Budibase/budibase#7835]
Feel free to move this to discussion if it is more appropriate.

I'm trying to start the dev environment on a Mac running Mojave. I've followed the instructions found [here](https://github.com/Budibase/budibase/blob/058ae96e0f4c15f15bf89a8d57fdfbf31c5c6dda/docs/DEV-SETUP-MACOSX.md).

Environment 
OS: Mojave
Docker: 3.1.0
Node: v16.14.2

Yarn dev runs without errors. However, when I try to access the builder I get the following.

"502
Houston we have a problem!
Bad gateway. Please try again later." error page.

When looking at the logs within the nginx container I see this error
[error] 433#433: *7 connect() failed (110: Connection timed out) while connecting to upstream, client: 172.20.0.1

I've tried increasing some of the timeout times within nginx.conf with no success. 

All containers are running. @budibase/worker: Redis connection failed - Error: connect ECONNREFUSED 127.0.0.1:6379 This also appears at times.

Any idea what might be causing this? Please let me know if any further info I can provide.

Thanks,

JP

**Comment by shogunpurple** [comment]
Hi @JayP718,

Did you uncomment the CouchDB line to emulate amd64 in `docker-compose.dev.yaml`?

What does your docker setup look like when you run the dev command? Is redis, couch, NGINX etc all running?

**Comment by JayP718** [comment]
Hi,

Thanks @aptkingston  for chiming in, So I have an intel mac but I did try it and still no luck. All containers seem to be running healthy.

Here are the logs for them

Redis 
1:C 20 Sep 2022 00:50:41.391 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 20 Sep 2022 00:50:41.391 # Redis version=7.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 20 Sep 2022 00:50:41.391 # Configuration loaded
1:M 20 Sep 2022 00:50:41.394 * monotonic clock: POSIX clock_gettime
1:M 20 Sep 2022 00:50:41.431 * Running mode=standalone, port=6379.
1:M 20 Sep 2022 00:50:41.433 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 20 Sep 2022 00:50:41.434 # Server initialized
1:M 20 Sep 2022 00:50:41.436 * Loading RDB produced by version 7.0.4
1:M 20 Sep 2022 00:50:41.436 * RDB age 3109 seconds
1:M 20 Sep 2022 00:50:41.436 * RDB memory usage when created 1.27 Mb
1:M 20 Sep 2022 00:50:41.436 * Done loading RDB, keys loaded: 2, keys expired: 0.
1:M 20 Sep 2022 00:50:41.436 * DB loaded from disk: 0.000 seconds
1:M 20 Sep 2022 00:50:41.436 * Ready to accept connections

Couch DB

[info] 2022-09-20T00:50:53.301353Z couchdb@127.0.0.1 <0.341.0> -------- Apache CouchDB has started on http://any:5984/
[notice] 2022-09-20T00:50:54.627353Z couchdb@127.0.0.1 <0.431.0> -------- All system databases exist.
[notice] 2022-09-20T00:50:56.161598Z couchdb@127.0.0.1 <0.501.0> 75812bbe67 couchdb-service:5984 172.21.0.5 budibase PUT /_users 412 ok 95
[notice] 2022-09-20T00:50:56.185196Z couchdb@127.0.0.1 <0.502.0> 1b2bb5078c couchdb-service:5984 172.21.0.5 budibase PUT /_replicator 412 ok 2
[notice] 2022-09-20T00:50:58.552510Z couchdb@127.0.0.1 <0.388.0> -------- couch_replicator_clustering : cluster stable
[notice] 2022-09-20T00:50:58.557073Z couchdb@127.0.0.1 <0.415.0> -------- Started replicator db changes listener <0.541.0>
[info] 2022-09-20T00:50:58.558167Z couchdb@127.0.0.1 <0.543.0> -------- open_result error {not_found,no_db_file} for _replicator
[notice] 2022-09-20T00:51:07.426253Z couchdb@127.0.0.1 <0.298.0> -------- rexi_server : cluster stable
[notice] 2022-09-20T00:51:07.426372Z couchdb@127.0.0.1 <0.302.0> -------- rexi_buffer : cluster stable
[notice] 2022-09-20T00:51:48.460651Z couchdb@127.0.0.1 <0.941.0> dc500d9ae3 localhost:4005 172.21.0.1 budibase GET /global-db/ 200 ok 17
[notice] 2022-09-20T00:51:48.475072Z couchdb@127.0.0.1 <0.942.0> 840a9b2ac4 localhost:4005 172.21.0.1 budibase GET /global-db/migrations? 200 ok 1
[notice] 2022-09-20T00:51:48.487458Z couchdb@127.0.0.1 <0.943.0> 17f0569864 localhost:4005 172.21.0.1 budibase GET /global-db/ 200 ok 2
[notice] 2022-09-20T00:51:48.493901Z couchdb@127.0.0.1 <0.944.0> cc9269b45a localhost:4005 172.21.0.1 budibase GET /global-db/migrations? 200 ok 1
[notice] 2022-09-20T00:51:48.527786Z couchdb@127.0.0.1 <0.945.0> e94a26e0fc localhost:4005 172.21.0.1 budibase GET /_all_dbs 200 ok 26
[notice] 2022-09-20T00:51:48.540788Z couchdb@127.0.0.1 <0.946.0> e9778bd9da localhost:4005 172.21.0.1 budibase GET /_all_dbs 200 ok 4
[notice] 2022-09-20T00:51:48.548334Z couchdb@127.0.0.1 <0.947.0> 92cd5bb53f localhost:4005 172.21.0.1 budibase GET /global-db/ 200 ok 1
[notice] 2022-09-20T00:51:48.554417Z couchdb@127.0.0.1 <0.948.0> 345524312b localhost:4005 172.21.0.1 budibase GET /global-db/migrations? 200 ok 1
[notice] 2022-09-20T00:51:48.569150Z couchdb@127.0.0.1 <0.949.0> 4cf590e5c8 localhost:4005 172.21.0.1 budibase GET /global-info/ 200 ok 8
[notice] 2022-09-20T00:51:48.575446Z couchdb@127.0.0.1 <0.950.0> 42ce385630 localhost:4005 172.21.0.1 budibase GET /global-info/migrations? 200 ok 1
[notice] 2022-09-20T00:51:48.591293Z couchdb@127.0.0.1 <0.951.0> caa4d7d926 localhost:4005 172.21.0.1 budibase GET /global-info/ 200 ok 1
[notice] 2022-09-20T00:51:48.597677Z couchdb@127.0.0.1 <0.952.0> c2a6774fff localhost:4005 172.21.0.1 budibase GET /global-info/install? 200 ok 1
[notice] 2022-09-20T00:51:48.612039Z couchdb@127.0.0.1 <0.953.0> afdfa0d2cd localhost:4005 172.21.0.1 budibase GET /global-info/ 200 ok 2
[notice] 2022-09-20T00:51:48.672389Z couchdb@127.0.0.1 <0.954.0> 575a74983e localhost:4005 172.21.0.1 budibase PUT /global-info/install 201 ok 53
[notice] 2022-09-20T00:51:48.694879Z couchdb@127.0.0.1 <0.955.0> 85fcaa6a2c localhost:4005 172.21.0.1 budibase GET /_all_dbs 200 ok 4


MINIO


License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2022-09-17T00-09-45Z (go1.18.6 linux/amd64) 

Status:         1 Online, 0 Offline.

**Comment by JayP718** [comment]
These are my docker networks
8c1a858fb7ad   bridge            bridge    local
05906d72e07b   host              host      local
922e30eaef87   hosting_default   bridge    local
c40c5f0a2747   none              null      local

**Comment by shogunpurple** [comment]
Hi @JayP718 - sorry for the late reply on this one, did you manage to get up and running? Please try running on the latest version, and using node 14 as thats the version most of the team are on.

**Comment by JayP718** [comment]
Hi @shogunpurple,

No worries, this error gave me an excuse to buy an M1 Mac :)

However, I'm also having trouble on the M1 Mac now it just hangs on -

lerna info Bootstrapping 11 packages
lerna info Installing external dependencies
⸨         ░░░░░░░░░⸩ ⠸ install dependencies: verb actions 11 actions, concurrence

I'm on node v14.20.1
macOS Monterey
Docker version 20.10.18, build b40c2f6b5d
npm-8.19.2

I tried yarn nuke, yarn clean with no success.

**Comment by shogunpurple** [comment]
@JayP718 great choice 👌 

Are you by any chance on a company VPN or some kind of "different" network environment? It seems odd that the install part would hang otherwise.

**Comment by JayP718** [comment]
I've tried three different networks company, personal hotspot, and a normal wifi set up.

**Comment by JayP718** [comment]
I've lined up all the version with what is found in the guide with the exception of docker-compose. Still no luck :(

**Comment by JayP718** [comment]
@shogunpurple never mind I got it up and running. Not sure what change worked as I was fiddling with a ton of things but a restart might have been the trick. Thanks again.
