### ISSUE TITLE
Data Provider Paging missbehaving 

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#7843]
How to recreate.

MySQL DB
New Screen
Insert Data Provider link to members table, set Filter to group_id = State.group_id
Paginate True
Limit 10
(set accordingly so there are more than one page for each group_id)

Insert Button 1
Insert Button 2

Button 1 -> Set State group_id = 1
Button 2 -> Set State group_id = 2

Now, Press Button 1. 
The Data Provider gets filtered, navigate to page 2

Now Press Button 2.
The Data Provider refreshes, and shows the SECOND page of the result set ( kept from previous step ) despite the Navigation label showing page 1.

**Comment by melohagan** [comment]
Hey @poirazis 

I wasn't able to recreate this. Would you be able to confirm the issue still exists on the latest version of Budibase please?

**Comment by poirazis** [comment]
Will test and revert @melohagan !
