### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by HMXHIU** [Budibase/budibase#7862]
**Hosting**
- Self
  - Method: ecs
  - Budibase Version: 1.2.52

**Describe the bug**
Page loading is extremely slow and CPU usage is over 100% at all time.

**Screenshots**
![Screenshot 2022-09-20 at 10 02 07](https://user-images.githubusercontent.com/9115894/191399851-418fdd0c-5eeb-44f1-ba76-3cc27092e1c2.png)
<img width="829" alt="Screenshot 2022-09-21 at 09 52 14" src="https://user-images.githubusercontent.com/9115894/191399884-906d492e-955d-4420-aa22-a5f1022b03a9.png">
<img width="518" alt="Screenshot 2022-09-21 at 10 22 41" src="https://user-images.githubusercontent.com/9115894/191399948-827bafbe-eebe-4fba-b64b-a052ad07c79a.png">

**Additional context**
- CPU allocation: 2048

**Comment by HMXHIU** [comment]
And this does happen when Budibase first started. Seems like there is something occur and causes the redis event_handler to stuck in infinite loop. 

<img width="645" alt="Screenshot 2022-09-26 at 17 58 31" src="https://user-images.githubusercontent.com/9115894/192248646-fe797ea4-8c68-46a5-a004-13d39255bcfc.png">

**Comment by HMXHIU** [comment]
Updated to v2.0.6 but it still does not solve the problem

**Comment by HMXHIU** [comment]
I managed to dump the cpu headshot and seems like it is trying to reconnect into something 
<img width="1607" alt="Screenshot 2022-10-03 at 12 16 00" src="https://user-images.githubusercontent.com/9115894/193500842-09bf4ded-0e8f-46ca-be96-9603d4a82194.png">

**Comment by shogunpurple** [comment]
Looks like this is a problem connecting to redis. Do you have elasticache running and the correct environment variables to point to it?

**Comment by HMXHIU** [comment]
The budibase is connected to a elasticache which is shared with my other applications. My other applications is working fine, only the budibase having issues reconnecting to it. Is there any guide for setting the correct environment for budibase?

**Comment by HMXHIU** [comment]
My intermediate solution is to start budibase using pm2 and set to force restart whenever budibase use more than 1G of ram.  Budibase is able to reestablish connection to redis every time after pm2 restart, so I assume the elasticache is working fine.
