### ISSUE TITLE
`budi` command errors with `Cannot find module '@budibase/string-templates'`

### ISSUE THREAD

**Issue by andreasbhansen** [Budibase/budibase#7884]
**Hosting**
- Self
  - Method: docker compose
  - Node: v16.13.2 (is this too old?)
  - Budibase Version: CLI v1.4.5 (globally installed)
  - App Version: Installed v1.4.3 (found via Portal -> Settings -> Update)

**Describe the bug**
I wanted to try the pre-v2.0 custom component feature, so I went through the [Docker Compose](https://docs.budibase.com/docs/docker-compose) setup tutorial as described on the [Budibase CLI setup](https://docs.budibase.com/docs/budibase-cli-setup) page, then completed the CLI setup. Having installed the Docker stuff and with all services up and running, I attempt to run `budi plugins --init component` but all things related to the `budi` command will immediately fail with:
```
Error - Failed to run CLI command - please report with the following message:
Error - Error: Cannot find module '@budibase/string-templates'
Require stack:
- /Users/andreas/.nvm/versions/node/v16.13.2/lib/node_modules/@budibase/cli/src/plugins/skeleton.js
- /Users/andreas/.nvm/versions/node/v16.13.2/lib/node_modules/@budibase/cli/src/plugins/index.js
- /Users/andreas/.nvm/versions/node/v16.13.2/lib/node_modules/@budibase/cli/src/options.js
- /Users/andreas/.nvm/versions/node/v16.13.2/lib/node_modules/@budibase/cli/src/index.js
```

**To Reproduce**
1. Follow [Docker Compose](https://docs.budibase.com/docs/docker-compose) and [Budibase CLI setup](https://docs.budibase.com/docs/budibase-cli-setup).
2. Ensure that all services are running and can be accessed via http://127.0.0.1:10000/builder
3. Attempt to execute the `budi` command in terminal
4. See error ^

**Expected behavior**
Being able to run `budi plugins --init component` successfully without errors.

**Screenshots**
Nothing else to show than the error stack above. 

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1
 - Browser: Chrome
 - Version: 105.0.5195.102 (Official Build) (x86_64)

**Comment by mike12345567** [comment]
Hi @andreasbhansen - thanks for the issue, this will be fixed in the next release, there was a minor issue and some of the dependencies weren't listed in the CLI package, this will be fixed promptly!

**Comment by andreasbhansen** [comment]
Super! Thanks, Michael.

**Comment by andreasbhansen** [comment]
Latest release (1.4.7) fixed the issue, I can now use the `budi` command 👍
