### ISSUE TITLE
Kubernetes setup with 1.2.52 non working when using Helm Chart

### ISSUE THREAD

**Issue by pigmej** [Budibase/budibase#7898]
**Hosting**

- Self
  - Method: k8s with helm chart <method> 
  - Budibase Version: 1.2.52 <version> 

**Describe the bug**
For a few days now I'm trying to get budibase working on k8s while installing it with Helm chart. There were multiple problems with it:
* had to downgrade budibase to 1.2.52
* had to downgrade couchdb to 3.1.0 

But essentially now no matter what I do the result is:
```
│ couchdb {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.e ││ couchdb
```

And that makes budibase unusable, as nothing can be viewed from even template apps.

**To Reproduce**
1. Install budibase on k8s with Helm chart
2. Setup anything from template apps
3. Nothing will be visible as the outcome in the app itself.

**Expected behavior**
App should work

**Screenshots**
  
**App Export**
Any from template

**Desktop (please complete the following information):**
Does not matter

**Additional context**

**Comment by pigmej** [comment]
In the same time I'm not sure if not existence of _users is that's a reason for breakage or it's just some noise.

**Comment by AiCaptain** [comment]
Hi Pigmej,

I wrote a shell script to create the users db in couch db, we got the same error everytime we start a new instance of budibase in our clusters (prerequisite: your kube context points to the right cluster): 

```
COUCHDB_PASSWORD=$(kubectl -n budibase get secret budibase-couchdb -o jsonpath="{.data.adminPassword}" | base64 --decode)
kubectl port-forward -n budibase pod/budibase-couchdb-0 5984:5984 &
sleep 2
curl -X PUT http://admin:$COUCHDB_PASSWORD@localhost:5984/_users
pkill kubectl -9
```
Hope that helps ...

Cheers, André

**Comment by muscovitebob** [comment]
This is still the case with the latest helm chart with the latest image values. How do I install budibase without hitting this?
