### ISSUE TITLE
Budibase slowly grinds to a halt on design section

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#7903]
**Hosting**
- Cloud
- Tenant ID: repro'd on both `bb.budibase.app` and `bbdemo.budibase.app`

**Describe the bug**
When I start using the design section for an extended period, it gets slower and slower. Over the course of 5-10 minutes it grinds to halt and becomes totally unusable. 

A page refresh temporarily fixes

**To Reproduce**
1. Go to the design section
2. Open your dev tools, watch the network tab
3. Look out for a call to `/socket/client/?EIO=4&transport=polling&t=xxxx`

The call times out after a minute. Eventually, I have lots of failed and lots of pending requests. After a few minutes, I am unable to add / delete / update components.

**Screenshots**
![image](https://user-images.githubusercontent.com/3524181/191762084-d86ea9a5-86d5-4efa-89b7-39e60dc639b0.png)

 **Desktop:**
 - OS: Ubuntu
 - Browser: Chromium
 - Version: 105.0.5195.102

**Additional context**
My app is a very simple app - the standard generated screens.

**Comment by aptkingston** [comment]
These are requests from the websocket library - the polling indicates that the socket is not connecting properly (which is an issue - it should be and it does in self host so this looks like an env issue) so it's attempting to poll for changes, but this shouldn't cause any sort of slowdown of the browser.

**Comment by shogunpurple** [comment]
Fix: https://github.com/Budibase/budibase/pull/7907

**Comment by shogunpurple** [comment]
Should now be resolved!

**Comment by maiducan** [comment]
My design section is still very lagging and slow after the newest update :/
