### ISSUE TITLE
Custom role - Navigation links

### ISSUE THREAD

**Issue by applicationuser** [Budibase/budibase#7917]
### Discussed in https://github.com/Budibase/budibase/discussions/7849

<div type='discussions-op-text'>

<sup>Originally posted by **applicationuser** September 19, 2022</sup>
Hello ,

Need help with navigation link setup with custom roles.

anything i missed or setup incorrectly? Please help

Here is my setup

Custom role: Regional inherits Basic Role
 
![image](https://user-images.githubusercontent.com/42922833/191123951-fdc4ba85-502d-487c-bbb2-650b2b16b48a.png)

Navigation links - configured Minimum role to access link as Basic.

![image](https://user-images.githubusercontent.com/42922833/191124175-fccf0433-b32f-4794-a8a0-11d78a203031.png)

user setup with app access set to custom role: Regional
![image](https://user-images.githubusercontent.com/42922833/191125168-4599dcf8-ff3c-4a6a-b3f3-dbf0c8066a79.png)

Published app and logged in with user defined at role: Regional 
Navigation links not displayed on Home page 

![image](https://user-images.githubusercontent.com/42922833/191125562-851f7cc5-c228-4839-8365-618f5ef3a180.png)

another issue, with the dev mode preview there is no option to view screen as custom role user 
![image](https://user-images.githubusercontent.com/42922833/191124299-8d35c8b6-12dc-4e71-9f68-0c7dac8a5b66.png)
</div>

**Comment by insomniacj93** [comment]
Same issue here, I wanted to set partitions of the program to be only used by a certain role but also have the lower roles such basic accessable to the higher roles created.

**Comment by melohagan** [comment]
Thank you for raising this issue @applicationuser 

I was able to replicate it. If you set the navigation link role to **Regional** it will work as expected, but I understand that the *Basic* role should work as well because the Regional role is higher.

**Comment by aptkingston** [comment]
This is unfortunately just a limitation of custom roles. We don't really have a proper hierarchy of where custom roles fall, and this is a symptom of that. I can only recommend sticking to the built-in roles to ensure everything works as expected.

**Comment by JayP718** [comment]
Having similar issues are visibility of navigation links using custom roles

**Comment by mp-strachan** [comment]
> This is unfortunately just a limitation of custom roles. We don't really have a proper hierarchy of where custom roles fall, and this is a symptom of that. I can only recommend sticking to the built-in roles to ensure everything works as expected.

Could a potential solution be a multi select drop down when configuring a nav link, rather than a single role with inheritance?

That way, if you wanted a link to be shown to BASIC and a few custom roles, simply select all the roles that link is visible to.

A tiny bit more work when setting up a link, but potentially a lot more flexible?

**Comment by melohagan** [comment]
This one appears to be fixed for published apps, but not for the preview yet:

<img width="199" alt="Screenshot 2023-10-13 at 10 58 20" src="https://github.com/Budibase/budibase/assets/101575380/347521b8-6436-458b-b0c6-b813f0babc76">

**Comment by mike12345567** [comment]
This should be fixed in the next version of Budibase.
