### ISSUE TITLE
True SPA - Role based screens

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#793]

**Comment by kevmodrome** [comment]
I fired off some questions at Jake to see how hard converting this into an SPA would be using Routify.

Routify uses a routes object (reference below). Normally it generates this object from the file system but I have a sneaking suspicion that we probably want to generate this ourselves. It also imports all the different components from the different files in your src/pages folder but in our case we probably just want to create a `Screen.svelte` component and pass that in everywhere, passing in all the relevant props (screen ID, etc) that are needed.

Here's how a small part of the routify-template example looks like: 
```js
//buildRoutes
import { buildClientTree } from "@roxi/routify/runtime/buildRoutes"

//tree
export const _tree = {
  "name": "root",
  "root": true,
  "ownMeta": {},
  "children": [
    {
      "isDir": true,
      "ext": "",
      "children": [
        {
          "isFile": true,
          "isDir": true,
          "ext": "svelte",
          "children": [
            {
              "isFile": true,
              "ext": "svelte",
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "prerender": true
              },
              "path": "/example/api/:showId",
              "id": "_example_api__showId",
              "component": () => import('../src/pages/example/api/[showId].svelte').then(m => m.default)
            },
            {
              "isFile": true,
              "ext": "svelte",
              "isIndex": true,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "prerender": true
              },
              "path": "/example/api/index",
              "id": "_example_api_index",
              "component": () => import('../src/pages/example/api/index.svelte').then(m => m.default)
            }
          ],
          "isLayout": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "prerender": true
          },
          "path": "/example/api",
          "id": "_example_api__layout",
          "component": () => import('../src/pages/example/api/_layout.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "ext": "svelte",
          "isIndex": true,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "prerender": true
          },
          "path": "/example/index",
          "id": "_example_index",
          "component": () => import('../src/pages/example/index.svelte').then(m => m.default)
        }
      ],
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "prerender": true
      },
      "path": "/example"
    },
    {
      "isFile": true,
      "ext": "svelte",
      "isPage": true,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "prerender": true
      },
      "path": "/index",
      "id": "_index",
      "component": () => import('../src/pages/index.svelte').then(m => m.default)
    }
  ],
  "meta": {
    "recursive": true,
    "prerender": true
  },
  "path": "/"
}

export const { tree, routes } = buildClientTree(_tree)
```

Usage in our apps would be just

```js
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "../.routify/routes";
</script>

<style  global>
  @import "../assets/global.css";
</style>

<Router {routes} />
```

**Comment by shogunpurple** [comment]
@kevmodrome this is great information - our pages + screens tree doesn't actually look all that different to that setup.

I think file based is the way to go for our routing - whether that be routify or hand written. This way, as we construct budibase apps, it would work something like this:
- Create a file directory structure on disk filled with .svelte files that we interpolate with data using mustache/handlebars
- On preview, bundle this svelte app into a real app

The only issue with this is the preview mode - we can't rebundle every time someone changes a prop - we will need to do some kind of HMR or dev mode reloading (snowpack?) when someone is doing things in the builder

**Comment by kevmodrome** [comment]
Ah! I figured getting around the bundling/compile part would be an issue when in the builder. I wonder if we can just straight up make a routify-template and customise it a bit and ship that for our apps? I'll check what the HMR status is on the Routify front.

**Comment by shogunpurple** [comment]
Just adding some context around this before we have a proper design meeting.

#### Rationale
When I want to prevent access to certain screens in my budibase application, I want to lock down certain screens to particular roles, or show a different screen based on role so that I can create different experiences for different user levels in my application.

#### Background
Right now, budibase is made up of the concept of **pages** and **screens**.

Pages are exactly that - HTML pages or their own single page application. By default, budibase contains 2 pages - **main** and **unauthenticated**. When the user first lands on a budibase application, the server checks whether or not they are logged in, and serves them the correct "app" - main or unauthenticated. The reason for this setup was due to multitenancy support; allowing a multitenant application to have one login screen shared between tenants, but different app instances based on the tenant that the user logging in belongs to. As a result of https://github.com/Budibase/budibase/projects/10, multitenancy is no longer a first class citizen of budibase and we are following the database-per-user model recommended by CouchDB. 

This means that budibase applications now have the opportunity to become fully fledged, single page applications, where screens are the main representation of a route. Routes or screens would be locked down to particular users, and many screens can be created for a single route, based on user role. How would some of the current unauthenticated pages look in this new, single page, role based world?
- The login screen itself should become a page, and be locked down to "logged in" users (logged in users should be a role itself too). 
- A hypothetical signup page would be accessible to any user.

This setup provides some real benefits to the users of budibase applications and hits a few high level product initiatives that have both been recommended and asked for by our users. Bear in mind some of them might require some updates to the current access level implementation.

- Conditonal UI. Different experiences for different users
- Role based access control
- Public data such as dashboards, landing pages, sign up pages and more
- Significant performance improvements

#### Current Technical Implementation
The 2 pages have different folders under `~/.budibase/<appId>/public`, each with different HTML pages and also 2 different `clientFrontendDefinition.json` files to represent their frontend tree consumed by the client library. When a user hits the initial page of their app, they will be served either application based on their authentication status.
