### ISSUE TITLE
Stripe Checkout Plugin

### ISSUE THREAD

**Issue by rpmcoding** [Budibase/budibase#7937]
It would be amazing if you or someone else is able to create a plugin for Stripe Checkout.

**Comment by melohagan** [comment]
Here you go! https://github.com/melohagan/budibase-datasource-stripe-checkout

**Comment by rpmcoding** [comment]
@melohagan fantastic thanks.  In what format should we add parameters to the parameters textarea under fields on the plugin page please?

**Comment by rpmcoding** [comment]
@melohagan sorry, yes create.

Am referring to this textarea.

![crud](https://user-images.githubusercontent.com/59533498/192570276-33594c23-7583-4f8f-921f-2ecd142a38f3.png)

**Comment by melohagan** [comment]
Official docs here: https://stripe.com/docs/api/checkout/sessions/create?lang=node
Select Node.js from the dropdown:
![Screenshot 2022-09-27 at 16 38 38](https://user-images.githubusercontent.com/101575380/192571590-a3993c1e-e969-4dab-a5e6-c0d5e9882806.png)

**Comment by melohagan** [comment]
Well looking at the docs it's not labelled as required. I think it's only conditionally required, and you may be able to pass other parameters instead.

**Comment by rpmcoding** [comment]
@melohagan  It is required unfortunately, removing it gives error:- "Query Error: The `line_items` parameter is required in payment mode."

I appreciate it is an array of objects, but if this is to be a true no-code platform, the array of objects and json should be generated in the background from the simple text inputs fields. 

As general feedback, I love budibase, it is great.  The only part that is a limitation is dealing with the data via the JavaScript for the transformer, json and accessing data via data.data[0].something.somethine etc etc.  

It all really needs to be point and click to be truly no code.

Please do take this is genuine constructive feedback aimed to help improve the product even more and not criticism by any means :)

**Comment by melohagan** [comment]
100% @rpmcoding Really appreciate the feedback! There's a number of tweaks we need to make to the datasources in general, so as always it's a matter of priority and what we can get done!
