### ISSUE TITLE
Error creating app doesn't resolve itself

### ISSUE THREAD

**Issue by GllsBe** [Budibase/budibase#7951]
**Hosting**
- Cloud
  - Tenant ID: werco

**Describe the bug**
The app creation failed when trying to create a new app from the templates. The message "Creating your Budibase app from your selected template..." is shown in the overview for +24 hours and the list with other apps have disappeared. (opening any other tab as "users" and then returning to the "apps" tab does resolve the missing list, but the initial message is still shown below that list.) The error message "Error creating app" also appears on every load.

**To Reproduce**
1. Go to ['builder/portal/apps'](https://werco.budibase.app/builder/portal/apps)
2. See error and disappeared list

**Expected behavior**
When the app creation failed the process of creating the app should be halted so no (error)messages appear.
When loading the budipress apps portal all apps should be visible.

**Screenshots**
See comments

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (64-bit)
 - Browser Firefox 104.0.2 (64-bit)

**Comment by GllsBe** [comment]
1. Initially we get the page without the list but with the app creation messages.

![Screenshot 2022-09-24 at 08-48-54 Budibase](https://user-images.githubusercontent.com/18401063/192084314-e89c03da-c0c6-4619-8196-a51c7764404f.png)

2. When opening another tab and returning to the app tab, we get the full list and the app creation messages.

![Screenshot 2022-09-24 at 08-49-07 Budibase](https://user-images.githubusercontent.com/18401063/192084365-d7ed4bed-e81d-477e-af04-1cf47dede966.png)

**Comment by shogunpurple** [comment]
This one has been resolved
