### ISSUE TITLE
Custom component development causes `UsageLimitError: Licensed Plugins of 10 has been exceeded`

### ISSUE THREAD

**Issue by andreasbhansen** [Budibase/budibase#7952]
**Hosting**
- Self
  - Method: docker compose
  - Node: v16.13.2 
  - Budibase Version: CLI v1.4.7 (globally installed)
  - App Version: Installed v1.4.7

**Describe the bug**
I'm working on a custom component using `yarn watch` and the live-reload feature. After a few saves and live-reloads, the component in the builder is no longer updated with the latest code changes. In the Docker `bbapps` logs window, I see the following error:

```
Importing plugin: /plugins/budi-datatable/dist/budi-datatable-1.0.0.tar.gz

Error updating usage quotas for plugins UsageLimitError: Licensed Plugins of 10 has been exceeded
at /app/node_modules/@budibase/pro/dist/index.js:1:14818
at Generator.next (<anonymous>)
at r (/app/node_modules/@budibase/pro/dist/index.js:1:2449)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'usage_limit_exceeded',
  type: 'license_error',
  status: 400,
  limitName: 'Plugins'
}

Failed to import plugin: Licensed Plugins of 10 has been exceeded
```

It doesn't matter if I'm working with a template or a project made from scratch, the error is the same.
I only have this one custom plugin/component, and it is the only component on the Budibase Portal's Plugin page.

**To Reproduce**
1. Setup everything related to Docker and Budibase CLI.
2. Create a new custom component and drag it into an app's designer/builder view.
3. Make sure to have `yarn watch` running. 
4. Do an unknown amount of saves to the component, which at some point triggered the above error for me, and I can no longer visually see changes to the custom component I'm working on.

**Expected behavior**
Having the custom component live-reload as expected, and not see the licensing errors described above. 

**Screenshots**
Nothing else to show than the error stack above. 

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1
 - Browser: Chrome
 - Version: 105.0.5195.102 (Official Build) (x86_64)

**Comment by mike12345567** [comment]
Hi @andreasbhansen this issue should have been resolved with the recent releases of Budibase.
