### ISSUE TITLE
Date format specification in datepicker form field

### ISSUE THREAD

**Issue by agruenberg** [Budibase/budibase#7958]
Currently it seems not to be possible to set a desired date format for the datepicker form field.
You can modify the desired format in the table eg. `{{#if Value}} {{ date Value "DD.MM.YYYY" }} {{/if}}` and the date will be formatted into this format, but within the form the date field will show the date still in the wrong format.
A format string input field for date fields would be very helpful.

**Comment by melohagan** [comment]
Hey @agruenberg 

You can set the date format with this custom date picker plugin! https://github.com/melohagan/budibase-component-kasper-date-picker
