### ISSUE TITLE
Offer year and date without the entire date-time combination

### ISSUE THREAD

**Issue by wolftune** [Budibase/budibase#7961]
There are many cases where just the year or year+month or just full date matter. Having to enter the time is extraneous noise.

**Comment by wolftune** [comment]
FWIW, I was comparing tools like Baserow and NocoDB, and some of those have this already. NocoDB has separate options for year, date, and date+time.

**Comment by melohagan** [comment]
Hey @wolftune 

I've created a custom date picker that allows for this: https://github.com/melohagan/budibase-component-kasper-date-picker

![image](https://user-images.githubusercontent.com/101575380/195886688-2331a0e7-32a2-49b2-9723-2987b68c082c.png)

**Comment by wolftune** [comment]
Nice, I'm a little confused though. Is this just for forms, like just front-end? The DB setup is still full date+time for the data?

**Comment by melohagan** [comment]
It is for forms only. If you use a format that only includes a date using that picker, then it will set the time part of the date to `00:00:00`.

If you want the internal DB to support both date and date/time data types, then that'd be a separate issue but there shouldn't be much need for it if you can zero out the time.
