### ISSUE TITLE
The name in data-view "Options" should be changed and should respect ordering

### ISSUE THREAD

**Issue by wolftune** [Budibase/budibase#7962]
First, "options" is not a clear name for single-choice. There's nothing in the name "options" that distinguishes it from "multi-select". It should be renamed "single-select".

It's also odd that multi-select respect the order for options. "Options" should respect the order as well and not just use alphabetic order.

Example: "Beginner, Intermediate, Advanced" in alphabetic becomes "Advanced, Beginner, Intermediate" and obviously this isn't appropriate for multi-select.

**Comment by wolftune** [comment]
geez, stale just two months later? and no attention to this obvious bug?

**Comment by aptkingston** [comment]
@wolftune you can simply disable alphabetic sorting using the setting on the options field:
![image](https://user-images.githubusercontent.com/9075550/206136380-3781875e-db91-4424-a316-b57fe7be6354.png)

**Comment by aptkingston** [comment]
Ah, my bad - I didn't realise you meant within the data section. That's fair feedback then - we should probably disable alphabetical sorting everywhere within the data section, but especially with any sort of custom query since custom sorting might have been specified within the query.

**Comment by wolftune** [comment]
Yeah, only after my recent comment, I realized that it could have been obvious about data because the concern about the *name* "options" is irrelevant for design (front-end users don't see the name). It's a poor name for people working with the data directly.

**Comment by wolftune** [comment]
Seems there was support for doing this… not sure if it's actually stale

**Comment by Rory-Powell** [comment]
With the updates for the grid UI in the data section we no longer automatically sort options fields
