### ISSUE TITLE
Row Explorer Block

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#8008]
### Row Explorer Block
The record detail block is a block that contains 2 panels. 

It allows you to see a searchable list of records (shown as spectrum cards), and select one from the list. When you select one from the list, all of the fields are displayed inside the detail view on the right, in a clean format. 

**Props**
- Data (table/datasource etc)
- Search field
- Preview fields
- Thumbnail field (string or attachment field)

Use spectrum cards for the list and have their values here as bindable props:
![Screenshot 2022-10-17 at 15.14.45.png](https://images.zenhubusercontent.com/5fd773ddf3d67d4ceebe466b/eda4f68f-1319-48a1-a2dd-f6a93ceb133a)

The thumbnail field allows you to show an image inside your detail view.

**Comment by aptkingston** [comment]
![image](https://user-images.githubusercontent.com/9075550/196389189-475eae28-90cd-4f9e-aa01-4b66b120788d.png)
 Rough idea of how this might look.

**Comment by joebudi** [comment]
@shogunpurple, what does the link URL do here?

**Comment by shogunpurple** [comment]
@joebudi this is just an example from the cards block, it won't be necessary in this case, since clicking on one of the cards just shows it in the row explorer.
