### ISSUE TITLE
filter out columns in internal table views

### ISSUE THREAD

**Issue by yeoldegrove** [Budibase/budibase#8012]
**Describe the feature request**
It would be great if one could filter out certain columns in a view created on an internal budibase table.
It would be even better if one could assign access permissions on a per column basis instead on the whole table.

**Comment by mike12345567** [comment]
This will be addressed as part of a larger rework.

**Comment by saz33m1** [comment]
@mike12345567 I am able to filter out columns in a new view. However, it doesn't work if a column is marked as "REQUIRED". Thoughts?
