### ISSUE TITLE
slow perf when moving to v 1.4.3 ?

### ISSUE THREAD

**Issue by nschaeff2000** [Budibase/budibase#8019]
**Hosting**

- Self
  - Method: docker
  - Budibase Version: 1.4.3
  - App Version: 
- Cloud
  - Tenant ID: 

When upgrading an application from to 1.3.11 to 1.4.3, I face strong perf concerns : preview takes long time to load (beginning with a blank page for more than one minute). Every page change takes also 20 to 30 seconds to load.
In Design mode, filling in a paragraph (for instance) takes one minute to appear
Going back to v 1.3.11 solves the issue
The app uses internal couch DB as well as MySQL Tables and Queries (MySQL server is local to the budibase server)

Regards

**Comment by nschaeff2000** [comment]
Hi @mike12345567 
Yes I did, I found that perf issue were still there if there are different versions of app in the single budibase install
When all the app get in the same version, the perf issues seem to disepear
Thanks !

**Comment by mike12345567** [comment]
Hi @nschaeff2000 - I think this problem has been resolved as of a recent version of Budibase - there were some performance issues which have now been solved. You'll need to update each of your apps client libraries - if an app needs an update you'll see something like this in the top right of the builder:
![image](https://user-images.githubusercontent.com/4407001/193595399-6f7818f7-f10c-42d3-8c1d-7e5e35d5cb61.png)

Going to close this issue as I believe the technical reason for the performance slowdown as been resolved in the latest version of Budibase.
