### ISSUE TITLE
Data Table - the new table is behaving weird with attachments

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#803]
In some cases, attachments are cropped. In other cases, they are not, and the text is not aligned.

![Screenshot 2020-10-28 at 21 04 18](https://user-images.githubusercontent.com/49767913/97496639-26e50f00-1961-11eb-93b0-b0b91d2a6e57.png)

https://www.loom.com/share/476a257570b140e8a018fa0c1ffd4e33

**Comment by shogunpurple** [comment]
Should now be resolved with the above PR
