### ISSUE TITLE
Public accessible app - navigation menu is missing

### ISSUE THREAD

**Issue by hheedfeld** [Budibase/budibase#8031]
### Discussed in https://github.com/Budibase/budibase/discussions/7922

<div type='discussions-op-text'>

<sup>Originally posted by **hheedfeld** September 23, 2022</sup>
Hi,

I've created a public accessible app, which is working very well, but I'm not able to make the navigation menu visible for unauthenticated users. What am I missing?

Thank for any hints,
Henning</div>

**Comment by melohagan** [comment]
![Screenshot 2022-10-03 at 14 40 39](https://user-images.githubusercontent.com/101575380/193592020-27fe7eb0-2d07-410d-a644-f1056d28d9d6.png)

![Screenshot 2022-10-03 at 14 41 06](https://user-images.githubusercontent.com/101575380/193592118-9c782dc9-f759-4a78-9ba7-54da805d75fe.png)

**Incognito**
![Screenshot 2022-10-03 at 14 41 41](https://user-images.githubusercontent.com/101575380/193592268-0e99ec8c-56d6-48fd-8556-531b763327e0.png)

**Authenticated**
![Screenshot 2022-10-03 at 14 42 23](https://user-images.githubusercontent.com/101575380/193592422-7374a037-c11e-440f-b187-15954ed2110b.png)

**Comment by hheedfeld** [comment]
@shogunpurple Should it be fixed in 2.0.26 already?

cheers,
Henning

**Comment by melohagan** [comment]
Hey @hheedfeld This was closed by accident. In future could you please add reproduction steps and screenshots (I've provided this time).
