### ISSUE TITLE
User creation always says successful even when user could not be added

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#8033]
**Hosting**
- Cloud
  - Tenant ID: all

**Describe the bug**
- The users response includes `successful` and `unsuccessful` users. 
- Previously an unsuccessful users modal would be shown when some users could not be added. 
- For email invite this modal is never shown
- For password invite this modal is shown however the success notification still fires

This is particularly misleading as users will be waiting for emails that will never arrive. 

**To Reproduce**
- See video

**Screenshots**

https://user-images.githubusercontent.com/8755148/192964074-58d06e9b-0819-447a-af4c-f5227b6a797d.mov

**Comment by melohagan** [comment]
Introduced in version **2.0.3**

**Comment by melohagan** [comment]
I think this was maybe just a bad merge: https://github.com/Budibase/budibase/commits/39a3a478b7dd9f6ff7be9ef403220c3439244995?before=39a3a478b7dd9f6ff7be9ef403220c3439244995+35&branch=39a3a478b7dd9f6ff7be9ef403220c3439244995&path%5B%5D=packages&path%5B%5D=builder&path%5B%5D=src&path%5B%5D=pages&path%5B%5D=builder&path%5B%5D=portal&path%5B%5D=manage&path%5B%5D=users&path%5B%5D=index.svelte&qualified_name=39a3a478b7dd9f6ff7be9ef403220c3439244995

On the 1st of September the `InvitedModal` was being used. 
Then after the merge on the 16th of September, the `InvitedModal` was no longer being used. 

Might just need to be cherry-picked back in.

**Comment by MihailHadzhiev2022** [comment]
I'll move this ticket to Done since it's fixed on develop, and close it when it's on production.
