### ISSUE TITLE
Failed to add plugin: Failed to import plugin: "schema.extra" is not allowed

### ISSUE THREAD

**Issue by Cityjohn** [Budibase/budibase#8041]
**Hosting**
- Self hosted latest community edition on Synology Docker.

**Describe the bug**
Getting Failed to add plugin: Failed to import plugin: "schema.extra" is not allowed" Error when attempting to save Stripe Subscriptions plugin by using Github URL.

**To Reproduce**
1. Go to plugins
2. Press add plugin
3. Press Github
4. Input URL: https://github.com/melohagan/budibase-datasource-stripe-subscriptions.git
5. Error

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome

**Comment by mike12345567** [comment]
Hi @Cityjohn - I cannot replicate this, what version of Budibase are you actually on?

**Comment by melohagan** [comment]
This was fixed: https://github.com/Budibase/budibase/pull/7857

Verified to be working in master. Closing.

**Comment by Cityjohn** [comment]
Excuse me for the delay please.

I have version 1.4.7.

The problem resolved itself after updating Chrome browser and clearing the cache.
