### ISSUE TITLE
Custom field in user cannot be updated

### ISSUE THREAD

**Issue by reichert** [Budibase/budibase#8043]
**Hosting**
- Self
  - Method: docker-compose
  - Budibase Version: 2.0.6

**Describe the bug**
In an app, if I create a new custom field in the User table and try to update that value I receive an error message: document update conflict.

**To Reproduce**
1. Create a custom field in the Users table of a given app
2. Click on edit any user (yourself or other) as admin
3. try to edit the field
4. Save
5. You will see the error
![image](https://user-images.githubusercontent.com/1287032/193050452-cad3a31f-4961-41f5-b17d-98088226e82b.png)

**Expected behavior**
- Have the user column updated

**Comment by dominik-bsr** [comment]
Related: https://github.com/Budibase/budibase/discussions/8081

**Comment by validlogin** [comment]
Here is the error I am getting from the console when trying to update a user and receive this error, maybe it could be helpful in shedding some light at the situation:

`ERROR [1665218212850] (30 on 575fea6ec3a6): Document update conflict.
bbapps                |     Error
bbapps                |         at generateErrorFromResponse (/app/node_modules/pouchdb/lib/index.js:694:18)
bbapps                |         at /app/node_modules/pouchdb/lib/index.js:6816:19
bbapps                |         at runMicrotasks (<anonymous>)
bbapps                |         at processTicksAndRejections (internal/process/task_queues.js:95:5)
bbapps                | Trace: Error
bbapps                |     at generateErrorFromResponse (/app/node_modules/pouchdb/lib/index.js:694:18)
bbapps                |     at /app/node_modules/pouchdb/lib/index.js:6816:19
bbapps                |     at runMicrotasks (<anonymous>)
bbapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
bbapps                |   message: 'Document update conflict.',
bbapps                |   error: 'conflict',
bbapps                |   reason: 'Document update conflict.',
bbapps                |   docId: 'ro_ta_users_us_0633739477ad4659a21d496d5f81241a'
bbapps                | }
bbapps                |     at /app/dist/api/index.js:74:21
bbapps                |     at Generator.throw (<anonymous>)
bbapps                |     at rejected (/app/dist/api/index.js:6:65)
bbapps                |     at runMicrotasks (<anonymous>)
bbapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
bbapps                | INFO  [1665218212870] (30 on 575fea6ec3a6): request completed
bbapps                |     res: {
bbapps                |       "statusCode": 400,
bbapps                |       "headers": {
bbapps                |         "vary": "Accept-Encoding",
bbapps                |         "content-type": "application/json; charset=utf-8",
bbapps                |         "content-length": "52"
bbapps                |       }
bbapps                |     }
`

Unfortunately my app is mostly useless without being able to manually update user fields :(

**Comment by marian001** [comment]
I have also tried the following to update custom field in User table:

- using Save Row action
- using automation with Update Row

Both failed.

**Comment by validlogin** [comment]
> Hi folks, this has been fixed in `v2.0.29`

Awesome! Do you know when 2.0.29 will be released?:)

**Comment by shogunpurple** [comment]
@validlogin it's released

**Comment by reichert** [comment]
Thanks @melohagan @Rory-Powell
I'm happy to contribute!

Regards.

**Comment by Zero2XIII** [comment]
HI,

This is still happening for me, exactly as reported by OP.
My version is 2.0.3 and when I click on update (Since it does not say 2.0.3**0**) it says it is up to date, yet still have this error.
Column in user table is a Boolean field - to opt into getting system generated emails.

**Comment by pbenfe64** [comment]
I'm still having same problem on 2.0.31. Any suggestion ?

**Comment by Leeroy28** [comment]
No thank you for the update Sent from my iPhoneOn Oct 16, 2022, at 3:23 AM, pbenfe64 ***@***.***> wrote:﻿
I'm still having same problem on 2.0.31. Any suggestion ?

**Comment by pbenfe64** [comment]
> No thank you for the update Sent from my iPhoneOn Oct 16, 2022, at 3:23 AM, pbenfe64 ***@***.***> wrote:﻿ I'm still having same problem on 2.0.31. Any suggestion ? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Excuse me sir, can you just tell me if you think it's normal to have the same problem even if I am running 2.0.31 ? Maybe I am missing something in updating the realse ?

**Comment by validlogin** [comment]
> I'm still having same problem on 2.0.31. Any suggestion ?

Have you updated your app in Budibase as well?

**Comment by pbenfe64** [comment]
> > I'm still having same problem on 2.0.31. Any suggestion ?
> 
> Have you updated your app in Budibase as well?

It's ok now, it was my mistake
