### ISSUE TITLE
Lab day plugin bugs + improvements

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#8053]
Opening this for visibility as I work through some of these changes. Feel free to add any aditional feedback that anyone else has!

Bugs:
- [x] Custom components don't work with generated bindings for things like field settings or action inputs
- [x] `fetchRow` in the internal API is currently broken (frontend implementation, the actual endpoint is fine)
- [x] `table` setting type is broken

Improvements:
- [ ] BBUI could be bundled better so that individual components could be imported, e.g. `Import Button from "@budibase/bbui/button"`, without needing to bundle the entirety of BBUI
- [x] Use the plugin friendly name (rather than the component name) for names of new plugin components, e.g. `New Custom Component` instead of `New custom-component`
- [x] Use a separate rollup config when developing plugings (when watch mode is active) which adds inline sourcemaps and disables terser, for easier debugging
- [x] Show `Plugin X reloaded` notification
- [ ] Document use of `"type": "event"` + usage with actions / bindings
- [x] Notify builder from client when plugins are hot reloaded, so the builder can fetch component definitions again (cheap hack to basically get hot reloading of component settings)
- [x] Ensure only one instance of the websocket can be constructed

PR here: https://github.com/Budibase/budibase/pull/8054

**Comment by melohagan** [comment]
Something I came across today with the latest Budibase CLI and master branch was the need to include all four CRUD methods for the datasource plugin to import.
Ideally I shouldn't need to provide all of these.
