### ISSUE TITLE
public query result contains too much information

### ISSUE THREAD

**Issue by yeoldegrove** [Budibase/budibase#8056]
**Hosting**
- Self
  - Method:  docker compose
  - Budibase Version: 2.0.4

**Describe the bug**
I have the challenge of displaying information from a private table on a public screen. The table cannot be public, as it would allow anyone to query all rows via the API or carelessly built screens. The use case would be displaying a row to a user that can also be edited later. As a bonus, everything should be authenticated by some kind of shared secret.

So I came up with this approach:
 - run a custom public query inside the data provider in the public screen (instead of using the private table directly)
 - the custom public query than queries the budibase API (using/hiding x-budibase-api-key header from the user) for the row information
   - parameters (passed via url) will be:
     - `id` of the row
     - `uuid` shared secret stored in column - a random uuidv4 generated on row creation -> the parameter will be send to a user (e.g. by mail)
   - query will only return a result if `uuid` supplied via url parameter matches the `uuid` entry in the row
 - additionally the query result is filtered by `id` and `uuid` in the data provider

My approach seems to work, but has a glitch. The query also returns an `extra.raw` field which contains all the row information even if the `uuid` check does not match.
Not sure if this really is a bug or some kind of feature that I don't understand yet.
All feedback is welcome, also maybe different approaches for my use case.

**To Reproduce**
- look at screenshots for detailed information
- import attached app export
  - test scenario based on "Client Contact List" template.

**Expected behavior**
`extra.raw` field is not returned or can be disabled (in query settings).

**Screenshots**

custom query:
![image](https://user-images.githubusercontent.com/8668070/193242369-94ab98f0-374f-46b3-881a-c67bd2885ebf.png)

positive result (uuids match) in browser:
![image](https://user-images.githubusercontent.com/8668070/193243987-9ea42228-c798-48bc-a793-096099ef9247.png)

negative result (uuids do not match) in browser:
![image](https://user-images.githubusercontent.com/8668070/193242698-63cdd598-bc75-45a6-842e-07d7746e70fc.png)

negative query result details (emtpy `data` but "too much information" in `extra.raw`:
![image](https://user-images.githubusercontent.com/8668070/193242823-036cbc81-47e9-4697-8031-21d9cf551f8c.png)

  
**App Export**
https://justpaste.it/8tkd4

**Comment by mike12345567** [comment]
Hi @yeoldegrove - I've adjusted the main query execution endpoint so that it doesn't return the raw query anymore - the raw query is only returned by the preview endpoint which can only be called from development apps by builders. This will be part of the next release.
