### ISSUE TITLE
API Testing: App Publish Workflow

### ISSUE THREAD

**Issue by Mitch-Budibase** [Budibase/budibase#8069]
COS:

- Review the current Cypress tests associated with the App Publish Workflow and replace them with API testing, where applicable
- It may not be possible to replace all of the Cypress tests with effective API testing. If so, create a list of what is and is not covered.
- Add more API tests for the App Publish Workflow (if applicable), beyond what the current Cypress suite covers. 

[Link to the App Publish Workflow test file (on Github)](https://github.com/Budibase/budibase/blob/develop/packages/builder/cypress/integration/appPublishWorkflow.spec.js)

**Comment by Pedro-Revez-Silva** [comment]
This flow is tested within the API tests, but all the verifications done on the FE with Cypress can't be done with them. I.E showing the published apps URL to the user.

**Comment by Mitch-Budibase** [comment]
All good Pedro! - We can get those other scenarios covered with E2E testing
