### ISSUE TITLE
Lab day - Cloud job websocket server integration

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#808]
The Cloud job system is essentially as feature complete as need be, but there are some things that would be needed if we wanted to release it into the wild:

1. Any decisions around whether or not it should have any database access, in this case we could discuss the API key, should the endpoints allow anything etc.
1. Infrastructure of it, where are we going to run it, what load balancer behind it so on.

**Comment by shogunpurple** [comment]
We could probably just run this as another ECS task in it's own cluster - I'd imagine it might need to be scaled out over time. ALB supports websockets so we should be fine there. We also have some CDK templates that can be used for spinning up a new service. 

As for database access - this service will need to be run in the public subnet to allow ws connections over the internet, so it will more than likely need to be API key aware to some degree

**Comment by mike12345567** [comment]
Yeah I was thinking running it as an ECS task would be the easiest way to get it out there, just didn't want to put it up unless we were going to use it.

What do you think it would need to be aware of the API key for out of interest? Just to stop any websocket connections from being opened? My main thinking was that each websocket only allows interactions that particular websocket has configured, therefore if you connect via websocket you can't actually do anything other than mark some webhooks as created etc.

**Comment by shogunpurple** [comment]
I guess it probably isn't a huge deal actually - given that the other client would need to know the URL and even if they did there's not a lot of damage being done. Might be easier to just keep things simple then!

**Comment by mike12345567** [comment]
Yeah, my thinking is that the only real danger is if another client somehow knows another users webhook ID/app ID, however I don't see how that information could get out into the wild, to some extent they are in and of themselves their own API keys - my thinking on this is:
1. Needing the API to create the websocket connection adds no security, it simply means the micro-service now needs Dynamo access which makes it more of a risk.
2. Having the API key checked on schema/trigger calls means that the user now needs the service they are using to be able to set the headers with an API key, adds more complexity to the use case.

Currently when the app is actually in production the user will need to specify the API key and instance in the same manner that any programmatic API call requires, but I think for testing/local builder work its not necessary.

**Comment by shogunpurple** [comment]
Yep it certainly has a very low chance of anything catastrophic happening. This service can become a go between for general internet/local builder pushes as well

**Comment by mike12345567** [comment]
Yeah thats my thinking too, given its lack of access to anything it can't do very much which is the nice thing about it being totally separated and keeps the experience simple for the user.

My thinking in the way I desired the external service was that if we want to do something which requires access to external resources etc then the builder should pass up the keys required to make the call when it is needed and then keys are old held ephermally while the transaction occurs, e.g. if we need to do something in Dynamo for any reason then the builder should pass up the API key with the particular message that is destined for Dynamo at that time, securing each message payload individually.

Yeap, I don't think we should let anything into our API without an API key being generated, so webhooks fall under the overall hood of that still - we'll just need to write docs about how to use the API/webhooks in production.
