### ISSUE TITLE
Unable to delete / disable a user

### ISSUE THREAD

**Issue by alain-sole** [Budibase/budibase#810]
Can create user and password + auth level
Can change auth level from admin to power user but no way to 
- disable a user or delete it?
- modify its password?

**Comment by mjashanks** [comment]
Hi @alain-sole. 

You're right - at the moment, there is no way to do these things. However, we are addressing this over the next 1-2 months. Keep an eye on these issues:

[Users as a table](https://github.com/Budibase/budibase/issues/790) - Should address better general management of users

[Create and Manage Access Levels in Builder UI](https://github.com/Budibase/budibase/issues/782) - Should allow you to create custom auth levels

Another one we will need to address at some point will be the signup & forgot password flow. 

If you could follow these issues, then come and give your feedback on them when complete, that would be really helpful for us :)

**Comment by shogunpurple** [comment]
Closing due to deletion of users available in next release
