### ISSUE TITLE
Oracle integration script makes build fail

### ISSUE THREAD

**Issue by KevinHamonApp** [Budibase/budibase#8101]
**Hosting**
Dev environnement on my local machine (Windows 11, Node 14.20). Installed as described in `CONTRIBUTING.md`

**Describe the bug**
I try to build Docker images, running `yarn build:docker:selfhost` from the root project. It announces 2 packages to build in.
The worker builds correctly. However, the docker build from the server fails. The error describe a problem with the file `server/scripts/integrations/oracle/instantclient/linux/x86-64/install.sh`. It seems that line ends `\r` are causing script to fail. 

**To Reproduce**
1. Clone Develop
2. Install the dev environnment as described on `CONTRIBUTING.md`
3. Launch  `yarn build:docker:selfhost` from the root project

**Expected behavior**
Builds correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/74555017/193569763-8bd4265e-9cca-4f09-9a12-74e56f435e72.png)

  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I converted the format of this file to exclude all '\r', and it worked properly.

**Comment by mike12345567** [comment]
Hi @KevinHamonApp - currently the development experience is relatively limited/un-maintained on Windows - currently there are no maintainers working on Windows.

I've also had a look at it doesn't appear the `install.sh` contains `\r` on both my Linux/Windows system - I expect this is something to do with the cloning process of the repo.

**Comment by KevinHamonApp** [comment]
Thanks @mike12345567 for your answer. It was indeed problems linked to my Windows. 
I tried all on Linux VM and the development experience seems much better.
