### ISSUE TITLE
Budibase App Corrupted? :(

### ISSUE THREAD

**Issue by JayP718** [Budibase/budibase#8107]
Hosting

Docker
Self Hosted
Linux

Version: 2.0.12

Hi,

I've got a published app which is still live. However, when I try to access it within the builder I get the following error

![image](https://user-images.githubusercontent.com/42209052/193637965-b745e2f5-1624-43ee-aea8-9968b99c16fe.png)

The error which appears is "404 Not Found" in the request "appPackage". 

When looking at the logs in the docker container I see the following.

Trace: {
  error: 'not_found',
  reason: 'missing',
  status: 404,
  name: 'not_found',
  message: 'missing',
  stack: 'Error\n' +
    '    at generateErrorFromResponse (/app/node_modules/pouchdb/lib/index.js:694:18)\n' +
    '    at /app/node_modules/pouchdb/lib/index.js:6816:19\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
  docId: 'app_metadata'
}
    at /app/dist/api/index.js:74:21
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/api/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO  [1664817066364] (30 on f7fc12e22927): request completed

Is there anyway to recover the app so it can be edited. It does seem to still exists since it's still live. Any help is greatly appreciated!!

JP

**Comment by shogunpurple** [comment]
Hi @JayP718 - what steps were you taking before you got up to this point?

It seems like the actual dev app database is not accessible. The reason you can still access the production one is because it's all stored in a separate database and is segregated from the dev app.

If it appears as though the dev database is completely broken, what you could do is run a replication of the production database back to the dev one.

Go to fauxton - `http://<your-server-ip>/db/_utils` and log in using the CouchDB credentials found in your docker-compose file.

Go to `http://<your-server-ip>/db/_utils/#/replication/_create`, where you will see this screen.

![Screenshot 2022-10-03 at 18 39 21](https://user-images.githubusercontent.com/11256663/193642900-a5b4f574-64aa-41ee-b61c-7fae92a4ef58.png)

Set up as following, replacing your appIds with the real appID of your app, and the corresponding `_dev` app ID. Don't forget to enter the auth creds for each (same as your couchDB credentials above)

![Screenshot 2022-10-03 at 18 40 09](https://user-images.githubusercontent.com/11256663/193643064-49683157-644e-4cba-879c-b9568c61b545.png)

Run the replication, and your dev database should hopefully be accessible again.

**Comment by JayP718** [comment]
@shogunpurple Thanks so much for the prompt response, happy to hear it still exists somewhere.

Another developer and I were doing several things within Budibase. I was deleting an unrelated app. They were working on modifying the app which is corrupted. Not sure exactly what action they were taking.


Unfortunately the state for the replication is retrying, it seemed like it tried but did not succeed. Does this look right ?


![image](https://user-images.githubusercontent.com/42209052/193651645-f7628f5a-43c2-4850-81bc-594a62243774.png)

**Comment by shogunpurple** [comment]
Hi @JayP718 hmm, that doesn't seem right. It seems to me as though the app was deleted somehow.

The replication must have failed here - are there any error messages in fauxton there detailing what happened?

Also, when you try to open the app, what error messages do you get from the response in the browser console?

**Comment by JayP718** [comment]
Hi,

That's really strange... I did delete another app with a completely different name (I know since I had to confirm the name before deleting).

Unfortunately the fauxton errors seem very vague unless I'm looking at the wrong place. The production database does seem to exists as seen below. Also the live app is running without fault at the moment.

![image](https://user-images.githubusercontent.com/42209052/193692338-134d745a-d01d-4cb9-9485-a362d88c4320.png)


The errors in the console are the following

![image](https://user-images.githubusercontent.com/42209052/193692732-c3a7c931-382a-412f-910f-ee471d25658c.png)

![image](https://user-images.githubusercontent.com/42209052/193692769-9f186a25-7c7d-46b9-bcc8-81c567ace21b.png)


Thanks again for your help.

**Comment by shogunpurple** [comment]
@JayP718 if you export your (dev) app from the builder UI, and import it again, does it work? If so, we may be able to run a replication between the new dev app and the old dev app and that should hopefully resolve it.

It's quite hard to know exactly what has happened here without looking at the DB.

**Comment by JayP718** [comment]
Unfortunately it has now disappeared from the list of apps however, when it was there it did not let me go to the manage app screen to export the app.

It's very very strange. I'm going to try to replicate.

One thing I noticed is that the dev database still exists albeit a lot smaller and with one less doc. Not sure if this means anything just thought I'd bring it to your attention.

If there's any other tips you might have please let me know.


![image](https://user-images.githubusercontent.com/42209052/193695413-c818df66-d287-4a4a-8137-45a62cc4c479.png)

**Comment by shogunpurple** [comment]
@JayP718 do you know which doc is missing? By any chance is it the `app_metadata` document? Or does that exist in the dev app?

**Comment by JayP718** [comment]
Yep exactly, the app_metadata seems to be missing.

**Comment by shogunpurple** [comment]
Ok, can you try re-adding the `app_metadata` document from your production app to your dev app? You will also need to update the `appId` key in your `app_metadata` to match the one from your dev app.

**Comment by JayP718** [comment]
Ah I thought that was going to be it but unfortunately I get document update conflict when I try to save. I also tried to change both the appid and instance _id. Tried just one then both. Both give me document update conflict

![image](https://user-images.githubusercontent.com/42209052/193697385-9125b49f-1ed9-4d3f-b8e7-afab6e596a42.png)

**Comment by shogunpurple** [comment]
@JayP718 try removing the `_rev` field in that document and saving again.

**Comment by JayP718** [comment]
That worked!! Thank you so much, you are a lifesaver!

**Comment by shogunpurple** [comment]
@JayP718 excellent! Now, not to lecture, but please take backups. 😄 

We will be releasing a feature this iteration on the paid plans to allow you to automatically back up and restore budibase applications - so every time you publish, a snapshot of your app is taken, along with scheduling capabilities where you can control how often your apps get automatically backed up. It would have solved todays problem with one click!

Glad everything is back in working order.

**Comment by JayP718** [comment]
> @JayP718 excellent! Now, not to lecture, but please take backups. 😄 
> 
> 
> 
> We will be releasing a feature this iteration on the paid plans to allow you to automatically back up and restore budibase applications - so every time you publish, a snapshot of your app is taken, along with scheduling capabilities where you can control how often your apps get automatically backed up. It would have solved todays problem with one click!
> 
> 
> 
> Glad everything is back in working order.

Fair point 😄 

Thanks again, looking forward to it
