### ISSUE TITLE
In Data Tab of Webapp Designer Drag Issue

### ISSUE THREAD

**Issue by Ayoxii** [Budibase/budibase#811]
I added a column to the end, and when I did so the app still thought that the original first column (now the second) was still the first. It doesn't cause any devastating issues in the app.

**Comment by mike12345567** [comment]
Hi @Ayoxii thanks very much for the report! We will get that sorted!

**Comment by shogunpurple** [comment]
Will be resolved by https://github.com/Budibase/budibase/pull/812
