### ISSUE TITLE
Keyboard focus and key press event action

### ISSUE THREAD

**Issue by jgngo** [Budibase/budibase#8119]
**Allow keyboard oriented apps**

I am trying to build an app that uses a hardware barcode scanner. The barcode scanner can be configured to emit a keypress event after a successful scan, typically the "enter" key or a "tab" key. So a typical use case for the screen to collect barcodes is:

1. On screen enter, place the input focus on the barcode field
2. In the barcode field, when an "enter" is received, perform an action, which is either move to the next field or to submit the form, clear the form and go back to step 1

In javascript:

```
// Execute a function when the user presses a key on the keyboard
input.addEventListener("keypress", function(event) {
  // If the user presses the "Enter" key on the keyboard
  if (event.key === "Enter") {
    // Cancel the default action, if needed
    event.preventDefault();
    // Trigger the button element with a click
    document.getElementById("myBtn").click();
  }
});
```

**Comment by melohagan** [comment]
Hey @jgngo 

Is this a custom component that you're building? https://docs.budibase.com/docs/custom-component
