### ISSUE TITLE
Data Provider User Created-By

### ISSUE THREAD

**Issue by morphace** [Budibase/budibase#8131]
**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.0.12

**Describe the bug**
I'm trying to limit records in a Data Provider by user that has created the record, as described here: https://docs.budibase.com/docs/fetching-data
However the Data drop down of the Data Provider only contains Tables, not the relationships as described.

I'm using BudibaseDB as the database.

**Comment by melohagan** [comment]
I'm also seeing this as early as **v1.0.15**.

**Comment by morphace** [comment]
Ah, intersting @melohagan - thanks for the feedback. Maybe there's an alternative approach to implement this?

**Comment by morphace** [comment]
I also tried to implement a filter on the Data Provider that would filter the Created By column by the Current User, but the Created By column is not provided as filter column.
