### ISSUE TITLE
MySQL Data Source doesn't handle zero values in timestamp fields

### ISSUE THREAD

**Issue by borzoj** [Budibase/budibase#8134]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.0.3

**Describe the bug**
If I hava a MySQL table with a timestamp column, and a row in that table with the value `0000-00-00 00:00:00` in the timestamp column, it's not possible to load the data from that table into a budibase app.

**To Reproduce**
1. Create a table with a timestamp column and insert a zero value into it:
```
CREATE TABLE `zero_timestamp` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `zero_timestamp` VALUES (1, '0000-00-00 00:00:00');
```
3. In Data configure a database connection and fetch tables.
4. Scroll down to the list of tables, and click on zero_time
5. The table view will be shown but the rows won't load. A red message will appear: "Invalid time value"
6. In docker logs this error is logged:
```
bbapps                | ERROR [1664962509266] (31 on a798dd41d474): Invalid time value
bbapps                |     RangeError: Invalid time value
bbapps                |         at Date.toISOString (<anonymous>)
bbapps                |         at exports.processDates (/app/dist/utilities/rowProcessor/utils.js:74:47)
bbapps                |         at ExternalRequest.outputProcessing (/app/dist/api/controllers/row/ExternalRequest.js:363:54)
bbapps                |         at ExternalRequest.<anonymous> (/app/dist/api/controllers/row/ExternalRequest.js:620:37)
bbapps                |         at Generator.next (<anonymous>)
bbapps                |         at fulfilled (/app/dist/api/controllers/row/ExternalRequest.js:5:58)
bbapps                |         at runMicrotasks (<anonymous>)
bbapps                |         at processTicksAndRejections (internal/process/task_queues.js:95:5)
bbapps                | Trace: RangeError: Invalid time value
bbapps                |     at Date.toISOString (<anonymous>)
bbapps                |     at exports.processDates (/app/dist/utilities/rowProcessor/utils.js:74:47)
bbapps                |     at ExternalRequest.outputProcessing (/app/dist/api/controllers/row/ExternalRequest.js:363:54)
bbapps                |     at ExternalRequest.<anonymous> (/app/dist/api/controllers/row/ExternalRequest.js:620:37)
bbapps                |     at Generator.next (<anonymous>)
bbapps                |     at fulfilled (/app/dist/api/controllers/row/ExternalRequest.js:5:58)
bbapps                |     at runMicrotasks (<anonymous>)
bbapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
bbapps                |   expose: true,
bbapps                |   statusCode: 400,
bbapps                |   status: 400
bbapps                | }
bbapps                |     at /app/dist/api/index.js:74:21
bbapps                |     at Generator.throw (<anonymous>)
bbapps                |     at rejected (/app/dist/api/index.js:6:65)
bbapps                |     at runMicrotasks (<anonymous>)
bbapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
7. This will also happen in any view where the table data is shown, for example if you want to create a Table in Design showing the data from the table.

**Expected behavior**
Table rows are shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/6280685/194030266-c5e059c4-77b9-4b0b-8069-9d1ef7062d9e.png)
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: chrome
 - Version: 105.0.5195.125

**Additional context**

**Comment by melohagan** [comment]
Hey @borzoj 

Is that definitely a valid timestamp. I'm trying to save that into my MySQL table and it's not allowed:

> Error Code: 1292. Incorrect datetime value: '0000-00-00 00:00:00' for column 'orderDate' at row 1


<img width="229" alt="Screenshot 2022-10-10 at 16 30 43" src="https://user-images.githubusercontent.com/101575380/194902543-0a77b9c9-7dd4-40a6-b43e-8b10dedec45b.png">
