### ISSUE TITLE
Possible Missing description in Budibase Docs

### ISSUE THREAD

**Issue by insomniacj93** [Budibase/budibase#8159]
Hello, While browsing through the budibase docs i ran into this: 

link: https://docs.budibase.com/docs/user-roles

![print21](https://user-images.githubusercontent.com/107686004/194307723-4243c853-4a39-41de-825a-101f7a3e3701.png)

Power Role has no Description, is it supposed to be this way? Anyway if it is, sorry to bother!

**Comment by melohagan** [comment]
Updated the docs! https://docs.budibase.com/docs/user-roles#adding-custom-roles
