### ISSUE TITLE
Delete button shown for in-built roles

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8163]
**Hosting**
- Cloud
  - Tenant ID: bb.budibase.app

**Describe the bug**
I cannot delete user roles - might be a permissions thing but the error is not clear.

**To Reproduce**
1. Go to users table in app
2. Edit roles
3. Select Power
4. Click delete
5. See error

**Expected behavior**
I should be able to delete user roles, or be provided with a meaningful error message if not.

**Screenshots**
![Screenshot 2022-10-06 at 16 24 23](https://user-images.githubusercontent.com/101575380/194353653-931190cf-a5d2-4590-b969-d8596f1da389.png)

![Screenshot 2022-10-06 at 16 23 33](https://user-images.githubusercontent.com/101575380/194353436-8544041f-0b73-4542-9596-1f8029fb9fcf.png)

**Comment by mike12345567** [comment]
Currently its not possible to delete the in-built roles like `Power` - if it is an inbuilt role we should hide the delete button.
