### ISSUE TITLE
Data section, Filter, Match any of the following filters, doesn't work

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#8173]
**Describe the bug**
When I tried to select Match any of the following filters, it doesn't work

**To Reproduce**
1. Data section
2. Add a filter
3. Select "Match any of the following filters", and click Save
4. Go back to filters. 

**Expected behavior**
Match any of the following filters is saved

https://www.loom.com/share/2332332a738c4bacb87ae75e6f9872e3

**Comment by HVStechnik** [comment]
I encountered a similar bug in version 2.0.24:
The "Match any of the following filters" option in the data provider component obviously does not link the where clauses with OR, but with AND. It should concatinate them with AND.
I'm using an external mysql database.

**Comment by Chukwu3meka** [comment]
Kindly assign me to this bug

**Comment by PaulERayburn** [comment]
I am also having this exact issue. Select "Match any of the following filters" in the database filter options and the default match all is applied and no results are found. Then when re-open the filter tool you can see it is defauted to match all.

**Comment by PaulERayburn** [comment]
Here's a video as well.  Sorry audio not on but you should get the idea.

https://user-images.githubusercontent.com/117835153/204563885-34e1e4ec-79f6-484c-b161-11224e2919d3.mp4

Also in fixing this would it be possible to propose a saved filter option so we can turn on and off a set of predefined filters?

**Comment by Chukwu3meka** [comment]
@PaulERayburn Thanks for sharing more bug details

**Comment by MihailHadzhiev2022** [comment]
Fixed
