### ISSUE TITLE
Importing App in Self-Hosted environment

### ISSUE THREAD

**Issue by lsbicyclic** [Budibase/budibase#8186]
Hi,
I am new here.
I started Budibase in the free hosted plan.
I wanted to import my app in a self-hosted environment wich is running.
But this does not work (created app with import option creates empty and asks for data source creation).
I am probably missing something ....

**Comment by shogunpurple** [comment]
Hi @lsbicyclic - please use the issue template and create a new issue with your budibase version, error you are seeing and an app export if possible, so we can reproduce. I am successfully able to import apps from a cloud account to a self hosted account after a test there. Closing this one for now as there isn't enough information. Thank you

https://github.com/Budibase/budibase/issues/new?assignees=&labels=bug&template=bug_report.md&title=
