### ISSUE TITLE
Data section, After deleting few of my rows on page 2, all other rows disappeared. 

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#8190]
**Bug 1:** 
You could check the bug on production, app - "Bird"
After I deleted few of my rows on page two, all other rows disappeared, I have to refresh to bring them back again. 

Video : https://www.loom.com/share/ee3288d3ed9748089de99cacb53fb807

**Bug 2:** 
![Screenshot 2022-10-10 at 9 42 12](https://user-images.githubusercontent.com/102024164/194813260-76b3b8da-1072-4527-96ed-a4ee75b7eb6f.png)

Settings bar, delete button doesn't work.

**Comment by shogunpurple** [comment]
The problem here is deleting the rows in the second page, so there are none left in that page. We need to refresh the pagination state on row deletion to ensure this does not occur.
