### ISSUE TITLE
[BUDI-7082] Send meeting invite via automation email SMTP

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8198]
**Describe the feature request**
As a user I would like to send email meeting invites.

Related discussion: https://github.com/Budibase/budibase/discussions/7980
Related SO post: https://stackoverflow.com/questions/24323452/how-to-send-a-meeting-request-correctly-with-nodemailer

<sub>[BUDI-7082](https://linear.app/budibase/issue/BUDI-7082/send-meeting-invite-via-automation-email-smtp)</sub>

**Comment by andyburgessmd** [comment]
Hopefully this will reopen the FR as I think this would be really useful to have.
