### ISSUE TITLE
Attachment Issues in deployed apps

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#820]
**Describe the bug**
Attachments do not show in deployed apps and the dropzone to upload attachments is also broken.

**When viewing attachments**
Attachments show as broken images in the browser. It appears that the images are not being uploaded to cloudfront correctly on deploy.

**When uploading attachments**
When uploading an attachment in **any dropzone**, calls to https://app_896df54e157a43659a164dcfdbe848bb.app.budi.live/api/attachments/upload for example respond with the following 400 request:

```
{"message":"The conditional request failed","status":400}
```

**To Reproduce**

1. Build a local app with attachments in one of your tables
1. Deploy the app
1. Try to interact with attachments in the deployed app. View them in the grid, or try to create a new row 
1. Notice that attachments show as broken images in the table

**Expected behavior**
Users should be able to view and upload attachments in their deployed applications

**Screenshots**
![Screenshot from 2020-11-04 21-40-51](https://user-images.githubusercontent.com/11256663/98170765-7b026d00-1ee6-11eb-98e8-5ccec695ffa6.png)

**Desktop (please complete the following information):**

* Budibase Builder version v3.0.1
* Ubuntu 18.04.5 LTS 

**Additional context**

**Comment by kevmodrome** [comment]
If anyone picks this up before I get back to it it looks like there might be an issue with file paths and/or jimp. Seeing issues both in the builder and in preview apps.
