### ISSUE TITLE
Application Assigning Users

### ISSUE THREAD

**Issue by insomniacj93** [Budibase/budibase#8206]
While Managing roles I've noticed a bug.
If I add more than 9 or 10 users, forcing the second page to appear.
I got a bug that wont let me assign any other users if I'm in Page 1, Only when i move to Page 2 the search box will allow me to type.

1. Enter 'Manage' Application,
2. Assign atleast 9 or 10 users (making sure it is enough to generate Page 2),
3. Refresh the Page,
4. Again, inside Assign Users, if page is 1, Try Assign New user,
5. If unsuccessful, move to Page 2 and try again.

My current version is 1.2.36, not sure if it's fixed in 2.0, but just letting you guys know!
If it's been fixed, my apologies!

**Comment by mike12345567** [comment]
Closing as duplicate - working on other issue.
