### ISSUE TITLE
TypeError when trying to select Relationship in Data Provider

### ISSUE THREAD

**Issue by m0k13** [Budibase/budibase#8220]
**Hosting**
- Self
  - Method: <method> docker compose
  - Budibase Version: <version> 2.0.26
  - App Version: <version> 2.0.24

**Describe the bug**
I am trying to show a table with items that have a relationship to the current user. When I select any options in the 'Relationship', I get the error: '**Cannot read property 'tableId' of undefined**'.
All tables are internal BB-Data-Sources.

**Screenshots**
<img width="1890" alt="Bildschirmfoto 2022-10-11 um 18 02 41" src="https://user-images.githubusercontent.com/45663017/195144329-7755ee98-0ba9-4a88-a8d2-44dba1f6b8f0.png">

**App Export**
[export.txt](https://github.com/Budibase/budibase/files/9757917/export.txt)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version 106

**Additional context**
Docker Logs for the error:
`bbapps                | ERROR [1665504932018] (32 on 9bc710f9929d): Cannot read property 'tableId' of undefined`
`bbapps                |     TypeError: Cannot read property 'tableId' of undefined`
`bbapps                |         at /app/dist/api/controllers/row/internal.js:397:18`
`bbapps                |         at Generator.next (<anonymous>)`
`bbapps                |         at fulfilled (/app/dist/api/controllers/row/internal.js:5:58)`
`bbapps                |         at runMicrotasks (<anonymous>)`
`bbapps                |         at processTicksAndRejections (internal/process/task_queues.js:95:5)`
`bbapps                | Trace: TypeError: Cannot read property 'tableId' of undefined`
`bbapps                |     at /app/dist/api/controllers/row/internal.js:397:18`
`bbapps                |     at Generator.next (<anonymous>)`
`bbapps                |     at fulfilled (/app/dist/api/controllers/row/internal.js:5:58)`
`bbapps                |     at runMicrotasks (<anonymous>)`
`bbapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {`
`bbapps                |   expose: true,`
`bbapps                |   statusCode: 400,`
`bbapps                |   status: 400`
`bbapps                | }`
`bbapps                |     at /app/dist/api/index.js:74:21`
`bbapps                |     at Generator.throw (<anonymous>)`
`bapps                |     at rejected (/app/dist/api/index.js:6:65)`
`bapps                |     at runMicrotasks (<anonymous>)`
`bapps                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by melohagan** [comment]
Hey @m0k13 

I am unable to recreate this using your app export or my own app. Could you try updating to the latest Budibase version please?

If you're still having issues, try removing the relationship column from the Users table and re-adding it, or possibly exporting your app and re-importing it under a new name.
