### ISSUE TITLE
Add support for OpenShift in Helm Charts

### ISSUE THREAD

**Issue by lfvjimisola** [Budibase/budibase#8229]
**Describe the feature request**

OpenShift is a more restrictive with privileges than standard k8s.

The proxy-service uses the default service account and we would like to use a custom one to setup special permissions (this is required to make it run in OpenShift).

**Comment by ka11f** [comment]
I'll add to this:
OpenShift got quite restrictive default permissions, the default service account can only run containers in a specific predefined uid range for each namespace. OpenShift adds a user (ex id 1000000) and run the container as that user. We are able to override this by setting a custom service account, but the helm chart does not support this for these two containers:
- worker-service
- proxy-service
A possible solution would be to make these two containers also use the budibase service account that gets created when enabling serviceAccount creation in the values.yaml file.

Another big problem running this helm chart in OpenShift is that in the proxy-service NGINX configuration, the DNS server is hardcoded to: kube-dns.kube-system.svc.cluster.local, OpenShift use another at the following address: dns-default.openshift-dns.svc.cluster.local.
This is not currently possible to override in the helm chart and the NGINX template is included in the proxy-service container, a possible solution would be to include the template as a configmap and allow users to override it in the values.yaml file.

Another problem that is not OpenShift related is that the NGINX configuration in the proxy-service assumes that everything is running in a namespace called budibase, again this could be solved by using a configmap as mentioned above.

**Comment by shogunpurple** [comment]
Hi @lfvjimisola, 

Thanks for this, this is a great starting point for us to make the helm chart better by addressing some of these issues.

This is excellent feedback @ka11f detailing what exactly the problem is here - it seems like there's a few addressable things here, some of which aren't openshift specific.
- Enable custom service accounts for `worker` and `proxy`
- Provide much more config over the NGINX setup using environment variables (we've started some work on this here: https://github.com/Budibase/budibase/pull/7413) 
- allow users to run in whatever namespace they like

If we were to address these ones, would this solve the problems you are having?

**Comment by lfvjimisola** [comment]
@shogunpurple For clarity, @ka11f and I are colleagues.

**Comment by shogunpurple** [comment]
> allow users to run in whatever namespace they like

**Comment by shogunpurple** [comment]
@lfvjimisola Ah, that makes sense! 

I was referring to the hardcoded namespace when I wrote this:
> allow users to run in whatever namespace they like

**Comment by lfvjimisola** [comment]
Sorry. I missed that. Time to call it a day :)

**Comment by ka11f** [comment]
> Hi @lfvjimisola,
> 
> Thanks for this, this is a great starting point for us to make the helm chart better by addressing some of these issues.
> 
> This is excellent feedback @ka11f detailing what exactly the problem is here - it seems like there's a few addressable things here, some of which aren't openshift specific.
> 
>     * Enable custom service accounts for `worker` and `proxy`
> 
>     * Provide much more config over the NGINX setup using environment variables (we've started some work on this here: [Allow proxy upstream URLs to be configured at runtime #7413](https://github.com/Budibase/budibase/pull/7413))
> 
>     * allow users to run in whatever namespace they like
> 
> 
> If we were to address these ones, would this solve the problems you are having?

Found more as I was working on getting this to run:
- We need to be able to add proxy environment variables as described [here ](https://docs.budibase.com/docs/running-budibase-behind-company-proxy), we are running this behind a company proxy.
- Ability to set a service account for app-service deployment.

Looking at the changelog for https://github.com/Budibase/budibase/pull/7413:
Seems like we will only be able to change the last part of the resolver, we need to be able to change the whole thing.

Finally, when we are running the "latest" version of Budibase, we are hit by https://github.com/Budibase/budibase/discussions/7699 and as a result, we had to downgrade to "v1.2.52", which works for us.

That is everything I think at the moment, thanks.

**Comment by shogunpurple** [comment]
These should now be addressed!
