### ISSUE TITLE
Javascript issue with component named with "()" characters

### ISSUE THREAD

**Issue by nunopoco** [Budibase/budibase#8254]
**Hosting**
- Self
  - Method: digital ocean
  - Budibase Version: 2.0.30

**The bug**
When setting a paragraph with a Javascript function that cycles through the selected rows of a table component named "Owners (individuals)", it outputs an error. I tried attributing the rows array into a constant and then doing the cycling but the same happens.
Changing the name to remove the "()" characters fixed it.
Was running on the previous version.

**Comment by melohagan** [comment]
Hey @nunopoco 

Could you please fill out the bug template, including the detailed reproduction steps and screenshots!
