### ISSUE TITLE
Backup fails

### ISSUE THREAD

**Issue by alscheuring** [Budibase/budibase#8262]
**Hosting**

- Self
  - Method: docker
  - Budibase Version: 2.0.3
  - App Version: NA

**Describe the bug**
Running budi backups according to the instructions ends in an out of memory error.

**Screenshots**
  
![Screen Shot 2022-10-14 at 8 28 27 AM](https://user-images.githubusercontent.com/223471/195847113-3642da14-32f1-41ff-b119-8dcd0e7579a8.png)

**Additional context**
Tried upgrading from 2GB to 4GB and got the same error. Is there a recommended minimum RAM amount?

**Comment by melohagan** [comment]
Hey @alscheuring 

This is probably to do with your Node environment: https://www.makeuseof.com/javascript-heap-out-of-memory-error-fix/

**Comment by alscheuring** [comment]
Unfortunately this didn't work for me.

**Comment by AlejandroFNadal** [comment]
I am having the exact same problem
```
{
  "browser": {
    "language": "en-US",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "platform": "Linux x86_64",
    "vendor": ""
  },
  "server": {
    "budibaseVersion": "3.4.16",
    "hosting": "docker-compose",
    "nodeVersion": "v20.18.3",
    "platform": "linux",
    "cpuArch": "x64",
    "cpuCores": 2,
    "cpuInfo": "Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz",
    "totalMemory": "7.755077362060547GB",
    "uptime": "41 day(s), 5 hour(s), 44 minute(s)"
  }
}
```

If I run the command with NODE_OPTIONS="--max-old-space-size=7000" (and command here) then it works, but between couch and minio I have total have a gigabyte of data and it should not require 7 to make a backup. Something weird is going on.

Would you consider reopening the issue @melohagan ?

**Comment by AlejandroFNadal** [comment]
@melohagan Thanks for such a prompt response. One detail I forgot to mention, the excesive consumption seems to be only in the couchdb export part of the backup, and not during the s3 export

**Comment by melohagan** [comment]
You're welcome @AlejandroFNadal - thank you for reporting!

**Comment by mikesealey** [comment]
@AlejandroFNadal are you still having this issue? Please ensure your CLI is the latest version with

```
budi -V
```

and run

```
npm update -g @budibase/cli 
```

and then

```
docker compose down
```

```
docker compose pull
```

```
docker compuse up
```
