### ISSUE TITLE
App Access, when we have 8+ users already with access to an app and add 2 more, I have to refresh the page to get all users

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#8263]
Bug related to ticket : 
https://app.zenhub.com/workspaces/budibase-product-5fd773eeaec59f001117ad65/issues/budibase/budibase/8208
 
**Bug 1:** 

When I have 8 users with access to an app, and I add additional user1 and user2, two other users disappears from the table, and I have to refresh the page to get all users back again.

**Bug 2:** Overview: 8 users assigned (this number never changed) 

https://www.loom.com/share/17426c165fc84ccca85be64b2627ad49

**Comment by StefanoBg2022** [comment]
This is nice . :)

**Comment by StefanoBg2022** [comment]
Well done!
