### ISSUE TITLE
Custom queries: If column name is same in two joined tables, only one field is returned

### ISSUE THREAD

**Issue by HVStechnik** [Budibase/budibase#8264]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.0.24

**Describe the bug**
I'm using a custom query on an external mysql db to join two tables. Both tables contain a column "name". 
Wenn I select all columns of both tables with `Select * FROM table1 JOIN table2 ON table1.a = table2.b` budibase returns one `name` column only. I think that the second column is overwritten, while retrieving. 

**Expected behavior**
All columns should be returned. If a column name exists twice, number them automatically with name1, name2, name3, ...

**Work around**
You can request `Select table1.name as name1, table2.name as name2 FROM table1 JOIN table2 ON table1.a = table2.b`. This works but get's quite messy quickly.

**Comment by shogunpurple** [comment]
This is not something that is supported - ambiguous field names need to be aliased in queries. Closing
