### ISSUE TITLE
App action automations do not trigger the animation that is used to move between automations

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#8276]
**Hosting**

- Self
  - Method: Docker Compose
  - Budibase Version: 2.0.31
  - App Version: 2.0.31
 
**Describe the bug**
Moving between two app action automations does not trigger the animation that is used to move between automations. Moving between other types of automations works fine.
 
**To Reproduce**
1. Create two app action automations with at least one step
2. Create a non app action automation
3. Click on one of the app action automations
4. Click on the other one
5. The automation has changed but the animation did not trigger

**Expected behavior**
The animation triggers.

**Screenshots**
Animation is not triggered
![budi1](https://user-images.githubusercontent.com/97764630/196063412-e13a41e6-c838-440c-b0a9-695990126a33.gif)
Other strange behaviours 
![budi3](https://user-images.githubusercontent.com/97764630/196063409-07ca6172-652c-43c6-9f7c-d90039d63fec.gif)
![budi2](https://user-images.githubusercontent.com/97764630/196063414-503c2ac8-1b6f-4ebb-870a-ee07a386bf2d.gif)

to help explain your problem.
  
**App Export**
[Test-export-1665962090712.txt](https://github.com/Budibase/budibase/files/9795907/Test-export-1665962090712.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 103.0.2

**Additional context**
Other strange things can happen if you add or make a change in the app action automation and click on another automation while the field is active (not sure if this is a separate bug and does not happen if you delete a field)

**Comment by aptkingston** [comment]
Fixed.
