### ISSUE TITLE
Data Provider Filter Not Working - DateTime 

### ISSUE THREAD

**Issue by 23brewert** [Budibase/budibase#8277]
**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 1.3.15

**Describe the bug**
When I try to filter a data provider by seeing if a date time value is blank the filter flat out doesn't work and if I change the filter type to "matches any of the following" zero results show up.

**To Reproduce**
1. Create a table named tasks and add a title field and and a end_time *datetime value*
2. Make a data provider in the design tab and reference that tasks table
3. Click "Define Filters"
4. Add a filter that says end_time is blank
5. create a new task record with a set end time
6. Observe that the record still showes up

**Expected behavior**
The filter is supposed to not include items that do not meet the filter rules.

**Screenshots**
https://gyazo.com/6fe1a4eadf499b02629f2c0d832fe4cd
  
**App Export**
Available Upon Request.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 106.0.5249.103

**Comment by aptkingston** [comment]
Hey @23brewert. Thanks for the video. I can see that there seems to be an issue only when using `Match any` with an `Is empty` filter. I had originally typed out a reply saying this works fine, but I was using `Match all`. In the meantime, you can use `Match all` which does properly filter empty values.

Original reply for reference:
Here's my table with one text column and one date column. You can see I have 2 rows - one with an empty date and one with a date:
![image](https://user-images.githubusercontent.com/9075550/196115061-9b7abdf1-05ce-488e-9e07-e6543a2857e1.png)

If I configure my filter to only show empty dates it works:
![image](https://user-images.githubusercontent.com/9075550/196115251-38c3cbc2-9b63-436f-ab4b-fca5a8d33dcf.png)
![image](https://user-images.githubusercontent.com/9075550/196115280-8c616c88-8e11-4aaa-b356-bcf200a47741.png)

If I configure my filter to only show non-empty dates it works:
![image](https://user-images.githubusercontent.com/9075550/196115366-77f41c81-4172-4a3f-8360-d58beee7aa8d.png)
![image](https://user-images.githubusercontent.com/9075550/196115403-744ef757-3047-4762-a74f-57f3e3674e8c.png)

**Comment by 23brewert** [comment]
> Hey @23brewert. Thanks for the video. I can see that there seems to be an issue only when using `Match any` with an `Is empty` filter. I had originally typed out a reply saying this works fine, but I was using `Match all`. In the meantime, you can use `Match all` which does properly filter empty values.
> 
> Original reply for reference: Here's my table with one text column and one date column. You can see I have 2 rows - one with an empty date and one with a date: ![image](https://user-images.githubusercontent.com/9075550/196115061-9b7abdf1-05ce-488e-9e07-e6543a2857e1.png)
> 
> If I configure my filter to only show empty dates it works: ![image](https://user-images.githubusercontent.com/9075550/196115251-38c3cbc2-9b63-436f-ab4b-fca5a8d33dcf.png) ![image](https://user-images.githubusercontent.com/9075550/196115280-8c616c88-8e11-4aaa-b356-bcf200a47741.png)
> 
> If I configure my filter to only show non-empty dates it works: ![image](https://user-images.githubusercontent.com/9075550/196115366-77f41c81-4172-4a3f-8360-d58beee7aa8d.png) ![image](https://user-images.githubusercontent.com/9075550/196115403-744ef757-3047-4762-a74f-57f3e3674e8c.png)

My point is that the date is blank filter doesnt work at all.
Here is a better video: https://gyazo.com/6d11604dc439d639609b2fb90bfdaf34

**Comment by melohagan** [comment]
This appears to be resolved:

<img width="1021" alt="Screenshot 2022-11-18 at 13 55 27" src="https://user-images.githubusercontent.com/101575380/202721051-a7549821-46b3-4057-8d4f-9d01d194aeb1.png">

<img width="620" alt="Screenshot 2022-11-18 at 13 55 46" src="https://user-images.githubusercontent.com/101575380/202721123-8a9949ab-731d-48c1-9532-8ceafa0a6e82.png">
