### ISSUE TITLE
Handlebars incorrect syntax validation message

### ISSUE THREAD

**Issue by diogenesbrussels** [Budibase/budibase#8329]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.0.3
  - App Version: 2.0.3

**Describe the bug**
It is almost impossible to see the error message when handlebars syntax is detected as invalid and the value reverts back to its previous value without any other warning.

**To Reproduce**
1. Open properties of a component (e.g. option picker)
2. Click on the thunder icon next to the field
3. Fill in a correct handlebars expression
4. Click on Save
5. Click again on the same thunder icon
6. Fill in an invalid handlebars expression
7. Click on Save
8. The validation message is shown but at the same time the panel slides down and the value is reverted to the previous one

**Expected behavior**
The validation error message is displayed and the Save action is stopped. This gives me an opportunity to read the message, correct the expression and click Save again.

**Screenshots**
![image](https://user-images.githubusercontent.com/91942877/196705592-aabf5f9d-0793-4698-b3e1-937d9a88cc85.png)

**Additional context**

**Comment by diogenesbrussels** [comment]
Yes, the drawer closes instantly and the error message is not displayed until the Save button is clicked which leaves just enough time for the drawer to come down to see it. Validation of the expression occurs when the button is clicked, not when it is edited as I see it.

**Comment by aptkingston** [comment]
Investigate moving to a debounced on change handler.
