### ISSUE TITLE
Relationship data in automation

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#8333]
**Hosting**
- Self
  - Method: <docker compose> 
  - Budibase Version: <2.0.30> 
  - App Version: <2.0.30> 
  
**Describe the bug**
I can't insert relationship columns in my automations.

**To Reproduce**
1. Automations
2. Update Row
3. insert {{ trigger.row.Client.0.ClientCompany }}
4. Field stays empty after automation

**Expected behavior**
Last week this line worked, it should fill in the ClientCompany

**Screenshots**
![Screenshot 2022-10-18 093108](https://user-images.githubusercontent.com/95284278/196885416-d6d96543-e21a-4a39-bd37-de78ce675108.png)

**Desktop**
 - Browser: Chrome

**Additional context**
Like I said, it worked last week after updating from 2.0.2? something.

**Comment by melohagan** [comment]
Hey @kasgithub8 

I tested something similar recently and it worked fine: https://github.com/Budibase/budibase/issues/7750

Just to double check could you make sure you are up-to-date with version **2.0.33** please, and try again.

Also your reproduction steps should really outline the tables involved, and include an app export if possible.

**Comment by kasgithub8** [comment]
Hey @melohagan,

 I'm gonna update it to 2.0.33 but we really need some kind of indicator when updates are available.
Especially the updates that you can only do inside the docker.

**Comment by melohagan** [comment]
Hey @kasgithub8 

You can get notified of a self-hosted release by clicking the watch dropdown on the repo:
![Screenshot 2022-10-21 at 09 19 32](https://user-images.githubusercontent.com/101575380/197148338-cc0ccdc6-c59f-476e-aea2-04d612c1e89a.png)

Select custom, and tick **Releases**
![Screenshot 2022-10-21 at 09 20 09](https://user-images.githubusercontent.com/101575380/197148466-7ddeca13-b9cd-4cb3-8fe9-6f07b332ad80.png)
