### ISSUE TITLE
External datasource fails when filtering with _id

### ISSUE THREAD

**Issue by gmentzik** [Budibase/budibase#8334]
**Hosting**
- Self
  - Method:  docker compose
  - Budibase Version: 2.0.32
  - Mysql version 8.0.30 , 8.0.32 (both dockerized and stand alone tested)

**Describe the bug**
Data provider connected with Mysql datasource table cannot filter by _id and generates error "
Unknown column '{mysqltablename}._id' in 'where clause'", when trying to load page with and  _id  at the url bar at the following cases:
- After modifying filters at auto generated page provider filter 
- Creating a new provider and filter by _id. 
The only way you can filter by _id is creating an auto generate page and using the provider generated taking care not touching  "Define filters".

**To Reproduce**
1. Install a clean budibase 
2. Install mysql 8.0.  Both stand alone at host and dockerized version included as service in budibase docker compose were tested)
3. Create database and user for budibase to connect with. Create a simple table eg "testtable" with an int AI PK 'tid' column and a text column as value.
4. At budibase create a new app , at mysql datasource and autogenerate pages for "testtable".
5. Duplicate the testtable/:id page to something like testtable2/:id
6. Check preview of application and use view button at testtable page to go to testtable/:id. Change url to testtable2/:id. Now both should work.
7. At editor testtable2/:id page try the following scenarios that should all fail:
- Add a 2nd filter to provider.
- Delete/Modify 1st filter save and modify again to _id.
- Delete auto generated provider and add new with _id filter.

**Expected behavior**
Filter by _id should always work if auto generated Mysql table provider's filters are modified or new user added data Mysql table provider with _id filter is added.

**Screenshots**
![image](https://user-images.githubusercontent.com/65217733/196893800-103341b5-4731-45f3-9733-2402560674ce.png)
  

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 (Ubuntu) , CentOS 7.8
 - Browser Chrome, Firefox

**Comment by melohagan** [comment]
As a note, the screen duplication is not required to reproduce. Ejecting the form block and adding a second filter to the data provider will cause an issue on the original `/:id` screen.

**Comment by melohagan** [comment]
@gmentzik The work around at the moment is to change the filter from `_id` to `product_id` or whatever your primary key is named within your MySQL table:

*This will break*
![Screenshot 2022-11-10 at 17 07 25](https://user-images.githubusercontent.com/101575380/201160709-7dca503a-f675-4755-be1b-d2c1a7b62ae6.png)

*This will fix*
![Screenshot 2022-11-10 at 17 07 51](https://user-images.githubusercontent.com/101575380/201160804-9566d3b6-9d25-45c0-9d89-7597e3a93608.png)

**Comment by gmentzik** [comment]
Hi @melohagan,

Thank you for confirming the issue. Currently I am using filtering with the table's primary key as you suggest. But I think since this is a core functionality that provides abstraction to primary key column of mysql table it is good to be fixed. Now if I decide to change the column name of primary key I must go through the application to change that everywhere whereas if you used _id this would not be needed i suppose.

**Comment by phaethon** [comment]
Hello! I stumbled against the same issue using external PostgreSQL. I suggest changing title of the issue to reflect that this relates to multiple (or any?) external databases.

**Comment by melohagan** [comment]
Introduced in version **v1.2.2**

**Comment by phaethon** [comment]
@melohagan Do I understand it correctly that the idea of the fix which was merged is to hide _id field from the available fields for filter? At least this is only change I could see with on 2.1.42 using PostgreSQL
