### ISSUE TITLE
Budibase CLI does not print version

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#8335]
**Hosting**
 Selfhosting

**Describe the bug**
The command budi --version prints the help of the command but no version. I am following the budibase cli install tutorial

**To Reproduce**
1. Install budi according to: https://docs.budibase.com/docs/budibase-cli-setup
2. Run budi --version

**Expected behavior**
To show a version

**Screenshots**
![image](https://user-images.githubusercontent.com/32724827/196902641-4fa45c4c-7d7d-48d2-b6f1-e73719a28092.png)
  

**Desktop (please complete the following information):**
 - OS: Debian 11

**Comment by MarcusSorealheis** [comment]
Can this issue be closed?

**Comment by mike12345567** [comment]
Hi @MarcusSorealheis - we close issues once we've put them through our QA team, and then pushed them in a release (today hopefully).
