### ISSUE TITLE
Users, Role, App user, If you have an user with "app user role", and change it quick to "developer role", and back to "app user role" you get an error message.

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#8342]
https://www.loom.com/share/3b181e14813a4bcda557ffae58d0327d

**Comment by aptkingston** [comment]
Looks like it's just the server being extremely slow, so you're sending up another save request before the first request has completed. We could disable fields while saving (but that would be ugly), but it would be better if the server just responded fast enough that this couldn't happen!
