### ISSUE TITLE
Form button loses its 'pill shape' when set to large

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#8343]
As the title suggests, the form button loses its pill shape when the form size is set to large.

<img width="1235" alt="CleanShot 2022-10-21 at 10 04 06@2x" src="https://user-images.githubusercontent.com/49767913/197158577-0d0f97ce-e987-4888-a58a-b96bdb1a06a5.png">

**Comment by Chukwu3meka** [comment]
@joebudi  What are the steps to reproduce?

**Comment by aptkingston** [comment]
This is due to
