### ISSUE TITLE
I can't select the data source in the table/card block

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#8348]
I'm using test.budi.live.

When I try to add a block (card or table) to my home screen, I can't select the data source.

Video:
https://vimeo.com/762591439/1ab81d8996

I tried refreshing multiple times, but the problem persisted.

**Comment by melohagan** [comment]
@andz-bb Saw this earlier as well.

**Comment by joebudi** [comment]
@melohagan is this working for you now? It seems to be working for me.

**Comment by shogunpurple** [comment]
Fix here: https://github.com/Budibase/budibase/pull/8355

**Comment by aptkingston** [comment]
Fixed and deployed in test env.
