### ISSUE TITLE
Budibase cloud: "Error initialising app: Not Found" on all apps

### ISSUE THREAD

**Issue by skoch-inform** [Budibase/budibase#8350]
**Hosting**
  - Tenant ID: inform

**Describe the bug**
Applications are not accessible anymore.
- Cannot open existing apps: Receiving "Error initialising app: Not Found"

**To Reproduce**
1. Login via OICD, access "Apps" dashboard on the administrative panel 
2. Click on '"Edit" on existing app
4. See error "Error initialising app: Not Found"

**Expected behavior**
Show the BudibaseBuilder for the app

**Screenshots**
![image](https://user-images.githubusercontent.com/115981217/197183040-5914012b-4bea-4aab-a2ba-fe158c74a065.png)
  
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 106.0.5249.119 

**Additional context**
- Every applications (Total of 4) have the problem
- Creating new Templates result in having a new app, but cannot edit
- Applications are in the state"Locked by  you". Unlocking works, but after clicking edit, it result in the same errormessage ("Error initialising app: Not Found")
- Exporting using "Export apps" is working, but it imports as a single app that has the same issues

**Comment by skoch-inform** [comment]
Remark:
On a secondary regular account, I can see the same behaviour. (https://storylike.budibase.app/)

**Comment by shogunpurple** [comment]
Hi @skoch-inform - I'm seeing this one too - we will resolve it as a matter of priority and keep this thread updated.

**Comment by shogunpurple** [comment]
Hi @skoch-inform - this one should now be resolved. Thanks for reporting!
