### ISSUE TITLE
download file through "execute query" action of a click event of a button

### ISSUE THREAD

**Issue by reichert** [Budibase/budibase#8356]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.0.31
  - App Version: 2.0.31

**Describe the bug**
Hi guys,
I'm not sure if this is a bug but let me explain:
- I've put in the click of a button an action that triggers a REST datasource. This REST service returns a file to download.
- The file is correctly generated and has all the required headers but since it is proxied in backend, it seams that the content-type is not forwarded to the frontend in order to allow browser to download the file.
- Any recomendation about how to achive the result of send this file to the browser to be downloaded without saving it anywhere else (like s3)?

**To Reproduce**
1. Create a button
2. Add the action "Execute Query" to the click event of the button
3. Configure an endpoint that return a file
4. the file is not dowloaded by the browser

**Expected behavior**
- The content type should be treated and budibase backend should forward the file to the browser to be downloaded

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome

**Comment by ConorWebb96** [comment]
I believe this has been resolved with the new https://docs.budibase.com/docs/data-actions#download-file. You can download either via directing to the file or providing the url to the file.
