### ISSUE TITLE
SQL Server Handlebars are now Global?

### ISSUE THREAD

**Issue by kerbersystems** [Budibase/budibase#8369]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.0.33
  - App Version: 2.0.33

**Describe the bug**
When handlebars are created in a na individual custom query, it will be populated to every other custom query under the same SQL Server.

**Comment by kerbersystems** [comment]
It looks like a page refresh brings the right bindings. Could this be a browser issue?

**Comment by gmentzik** [comment]
Have same behavior with Mysql. It started happening in on of most recent updates. Binding part does not refresh when you select another query. You have to refresh the whole page.

**Comment by skoch-inform** [comment]
I can confirm this also for the dynamob data configuration.

**Comment by melohagan** [comment]
Hey @kerbersystems 

Thanks for drawing attention to potential bug, but could you please fill out the bug template. 
Provide detailed reproduction steps and screenshots please!

**Comment by kerbersystems** [comment]
@melohagan 

**Hosting**
Self
Method: docker compose
Budibase Version: 2.0.33
App Version: 2.0.33

**Describe the bug**
When handlebars are created in a na individual custom query, it will be populated to every other custom query under the same SQL Server.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to a specific APP. (it effects all of my APPS)
2. Click on 'Data' > 'SQL Server'
3. Which ever Custom Query is clicked on first, the 'Bindings' section will follow to every other custom query page. 
4. Binding are corrected after a refresh of the page

**Expected behavior**
On each query the bindings are correct for that query.

**Screenshots**

-First query clicked on will set the bindings.
![image](https://user-images.githubusercontent.com/96125948/199340018-826a3afb-406e-44fb-b42f-dd194658d55b.png)

-Every other query after will have the same bindings showing
![image](https://user-images.githubusercontent.com/96125948/199340203-9acb6387-8adc-4e33-b8a1-ac7642a9032a.png)

-Upon refresh, bindings are correct
![image](https://user-images.githubusercontent.com/96125948/199340279-3bb63902-ba16-4ab9-8439-e080f2413e62.png)

**Comment by melohagan** [comment]
Bug introduced in **v1.3.20**
