### ISSUE TITLE
Auto list screen problem

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#838]
**Describe the bug**
When a list screen is auto-created, and the grid component replaced, the preview continues to show the original grid component. Also, on deploy, none of the list components show.

**To Reproduce**
1. Create a table with data
2. Delete the grid component in your auto-created list screen
3. Add new repeater component with a card component
4. Bind data to the component
5. Preview app
6. Deploy app 

**Expected behavior**
The new component should be shown in preview mode and all list components should be viewable in deploy mode.

**Screenshots**
https://www.loom.com/share/adcf5d53a15949fe9cb19ae452b0cb80

**Desktop (please complete the following information):**
 - Mac, chrome

When deployed and the data components are not there, I get the following errors in the console:
I am getting the following errors:

```
api/tables/ta_95e5713e292c4d979fb8afabae1b3ab6:1 Failed to load resource: the server responded with a status of 403 ()
componentlibrary?library=@budibase/standard-components&appId=app_8c7c31f826b84b4c871d8f191a718dce:366 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at componentlibrary?library=@budibase/standard-components&appId=app_8c7c31f826b84b4c871d8f191a718dce:366
```

**Comment by shogunpurple** [comment]
Discord seems to be having a sad at the moment, so couldn't reply to you on there. Will have a look into this one. Cheers @joebudi
