### ISSUE TITLE
Improve appPackage security

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8381]
### Discussed in https://github.com/Budibase/budibase/discussions/8266

<div type='discussions-op-text'>

<sup>Originally posted by **FCMHUB** October 14, 2022</sup>
First of all, congratulations on this great tool.

I have a security-related question.
Is there any reason why the appPackage file has some back-end-related information sent to the browser? 
For instance, looking at the appPackage file we can see the datasources with their related queries exposed to the front end.

That brings me some thoughts.

- If this info is somehow used by the client, couldn't a man-in-the-middle attack change that file and grant some undesired database access?

Or

- If the info is not used by the client, shouldn't it be kept only on the back end?

Thanks in advance,</div>

**Comment by shogunpurple** [comment]
Credentials do not come back to the client in our datasources and are only stored on the backend - so this one should be resolved.
