### ISSUE TITLE
[BUDI-6818] Array type missing from query schema selector

### ISSUE THREAD

**Issue by andz-bb** [Budibase/budibase#8389]
**Hosting**

- Self
  - Method: dev stack with MySQL db
  - Budibase Version: 2.0.30-alpha.16
  - App Version: 2.0.30-alpha.16

**Describe the bug**
When running a query on an external datasource there is no proper support for array type columns. The server returns the type as "array" but the type select component doesn't have that as a possible value so it shows as null in the front end.

**To Reproduce**
1. Create a Multi-select column or another array type in an external datasource
2. Create a query in the datasource that pulls that array column back
3. Check the query schema - the array column type will be null

**Expected behavior**
Include an option for Array in the query schema column type options

**Screenshots**
![SCR-20221025-fpl](https://user-images.githubusercontent.com/110921612/197748669-a575a5d9-64ab-4f57-86ec-beb0999cc16c.png)

In my case I'm running MySQL so this is a JSON type column:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/110921612/197750076-2204d6a4-b05e-47fe-b398-99a9c916d410.png">

when previewing the query, the server correctly returns the column type as "array":
![SCR-20221025-fof](https://user-images.githubusercontent.com/110921612/197750504-87ba2aab-edaf-4807-a591-98a7024a10e6.png)

but that type from the response isn't properly supported in the front end
![SCR-20221025-foz](https://user-images.githubusercontent.com/110921612/197750187-f014fcca-6340-4768-8197-87f0bd8fa01d.png)

we need a value for array here:
![SCR-20221025-fp5](https://user-images.githubusercontent.com/110921612/197750334-5da9bac4-03bb-45f2-8178-96cf5db7f4ee.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Browser: Chrome
 - Version: 106

**Additional context**
Raised from discussion #8304 

<sub>[BUDI-6818](https://linear.app/budibase/issue/BUDI-6818/array-type-missing-from-query-schema-selector)</sub>

**Comment by aptkingston** [comment]
I think the bug here is that we're trying to handle that column type at all - I don't think we support JSON/array types in external DBs, so we should just be ignoring it when pulling it in.

It would probably be a reasonable large enhancement to add support for them. It would also depend heavily on which type of database you're connecting to. Our JSON column only works with internal tables, but we also can't assume that all JSON columns in external DBs are arrays (since an object is valid JSON).

@deanhannigan was looking at some of this stuff recently so I'll let him chip in.

**Comment by andz-bb** [comment]
> I think the bug here is that we're trying to handle that column type at all - I don't think we support JSON/array types in external DBs, so we should just be ignoring it when pulling it in.
> 
> It would probably be a reasonably large enhancement to add support for them. It would also depend heavily on which type of database you're connecting to. Our JSON column only works with internal tables, but we also can't assume that all JSON columns in external DBs are arrays (since an object is valid JSON).
> 
> @deanhannigan was looking at some of this stuff recently so I'll let him chip in.

thanks @aptkingston - is it a problem that BB can create JSON columns in external DBs for multi-selects if those values aren't properly supported after that point?

**Comment by aptkingston** [comment]
> > I think the bug here is that we're trying to handle that column type at all - I don't think we support JSON/array types in external DBs, so we should just be ignoring it when pulling it in.
> > It would probably be a reasonably large enhancement to add support for them. It would also depend heavily on which type of database you're connecting to. Our JSON column only works with internal tables, but we also can't assume that all JSON columns in external DBs are arrays (since an object is valid JSON).
> > @deanhannigan was looking at some of this stuff recently so I'll let him chip in.
> 
> thanks @aptkingston - is it a problem that BB can create JSON columns in external DBs for multi-selects if those values aren't properly supported after that point?

Definitely a problem if it works in one direction and not the other! Although that's tricky because we can create JSON fields for multi-selects and we know those are arrays, but we can't assume all JSON fields are arrays again on import... So I'm not sure if we can standardise that without removing JSON support entirely from external DBs, or fully supporting JSON in external DBs and allowing mapping them to either arrays or our internal JSON type.

**Comment by deanhannigan** [comment]
Hi @aptkingston @andz-bb, I did have a look into JSON field support for external fields and found that most of the functionality to read/edit JSON fields was supported. I specifically looked at MySQL and PostgreSQL.

There are however, a number of issues when it comes to filtering and sorting as these options are not supported in the external DBs at all. As @aptkingston points out, a lot of UI work/testing would need to be done to filter out these options and unsupported actions from the builder.

In this instance, the label for the array type is simply missing. The array column will still be accessible/visible in the builder. Whether or not the field type should be supported, I think remains to be discussed.

**Comment by shogunpurple** [comment]
Related - likely to solve this: https://github.com/Budibase/budibase/issues/3382

**Comment by melohagan** [comment]
This also impacts REST API responses that have array properties: https://ptb.discord.com/channels/733030666647765003/1091358878777741382

**Comment by 23brewert** [comment]
Same issue
