### ISSUE TITLE
Bug: chart title doesn't get light text when a dark theme is selected.

### ISSUE THREAD

**Issue by TimVee** [Budibase/budibase#8403]
**Hosting**
- Cloud

**Describe the bug**
The title text for charts isn't light when a theme with a dark background is selected, making it hard to read to illegible.

**To Reproduce**
1. Go to the builder
2. Click on the theme button: the button with the brush icon on the left
3. Select a dark theme
4. Set up a bar chart with data
5. Give the bar chart a title

**Expected behavior**
Text on a dark background should be light.

**Screenshots**
![msedge_kSXZncaKs9](https://user-images.githubusercontent.com/70507163/198016927-20a4e8e9-2ee8-4a9d-8e0b-3f9dc1428c59.png) 
![msedge_Sa7QvpupaN](https://user-images.githubusercontent.com/70507163/198016986-e48ae16e-b4da-4da7-86e2-3fc515c64106.png)

**Desktop:**
 - OS: Windows
 - Browser: Edge
 - Version: 106

**Comment by melohagan** [comment]
Will be fixed as part of this commit in the upcoming release! https://github.com/Budibase/budibase/pull/8374
