### ISSUE TITLE
Budibase shows the wrong app

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#848]
**Describe the bug**
When working IN the builder, clicking between data and design, Budibase shows the data of one and the UI of another.

**To Reproduce**
1. It all went wrong when I added the candlestick chart

**Expected behavior**
The builder, and preview should show the app which the user is working on.

**Screenshots**
https://www.loom.com/share/d172b4d3b835489b8110063ceaafcce0

**Desktop (please complete the following information):**
 - Mac

**Additional context**

**Comment by aptkingston** [comment]
Not sure what went wrong with the app, but I can at least guarantee that clicking the candlestick chart didn't cause it haha. We've seen issues with wrong previews before which is usually down to somehow using the wrong app ID / wrong cookies.

But are you saying the data and design tabs are for different apps there? Not just the preview, but like it's showing the list of screens for one app and list of tables for another?

**Comment by joebudi** [comment]
That's correct. When in the design section, the screens changed to a previous app. I then clicked into the data section and it was still the data for the new app.
