### ISSUE TITLE
"You can't place a Form here" when editing

### ISSUE THREAD

**Issue by sergey-vin** [Budibase/budibase#8484]
**Hosting**
- Cloud, tried on 2 different tenants/accounts

**Describe the bug**
Every time I'm trying to duplicate a field or insert a new component, it gives me the following issue:
"You can't place a Form here"

I've tried updating to the app latest version (2.x) - didn't help.

**To Reproduce**
1. Go to 'Design', Pick any screen.
2. Click on a field within an existing hierarchy of field components
3. Click on ... -> Duplicate

Also, tried to recreate the page by copy-pasting the whole screen content into a brand new screen - same error.

Also, tried deleting (not duplicating) an existing field - saw a spinning wheel, never ending.

Seems that no modification of old apps is allowed - only creating new screens is allowed, which is quite bad.

**Expected behavior**
A field to be duplicated.

**Screenshots**
![image](https://user-images.githubusercontent.com/1080493/199474957-43c2564a-ba77-4143-b7ad-c906c5ab7337.png)

![image](https://user-images.githubusercontent.com/1080493/199475411-3be896f6-c912-4877-95ca-63e8366b34c2.png)

**Comment by melohagan** [comment]
Hey @sergey-vin 

I'm struggling to reproduce this bug. Could you flesh out the detail in the reproduction steps further please and include screenshots or a screen-recording of the steps.

I'm having no issue with duplicating or inserting form fields.

**Comment by sergey-vin** [comment]
https://user-images.githubusercontent.com/1080493/199574798-69bfb16c-4313-43a4-8e28-2afe2f754c7c.mov

**Comment by mike12345567** [comment]
Hi @sergey-vin - I'm going to close this issue as #8478 is exactly the same issue - there is a problem with apps that have components in places that they aren't supposed to be (forms within forms, or sections somewhere deep in the tree) - we're looking into allowing continued development with a warning for these components!

**Comment by sergey-vin** [comment]
@mike12345567 , disallowing such nested forms is not the right way of addressing the issue.
Such nested components is the only way of getting around the limitations of the platform on accessing linked data from 2 different data sources.
