### ISSUE TITLE
Cannot select options in multi-select picker when field type is 'Select'

### ISSUE THREAD

**Issue by adamjdavies** [Budibase/budibase#8490]
**Hosting**
- Cloud
  - Tenant ID: tern
  
**Describe the bug**
Unable to select any options in a multi-select field when the field Type is set to **Select**. However, I am able to select options if the field type is set to "Checkbox". 

**To Reproduce**
1. Create a form with a multi-select picker
2. For the multi-select picker set **Type** as **Checkboxes** and add a custom **Option source**.
3. Try to select an option.

**Expected behavior**
I should be able to select multiple options in the multi-select picker.

**Screenshots**
![Screen Recording 2022-11-02 at 12 21 16](https://user-images.githubusercontent.com/64409787/199489381-68453e35-0731-4324-823d-bcc14410eedf.gif)

  
**App Export**

**Desktop (please complete the following information):**
 - OS: macOS Monteray v12.6
 - Browser: Chrome Version 107.0.5304.87 (Official Build) (arm64)

**Additional context**
This is affecting a live client of mine. Have also had another issue today (#8483) but I don't think these are related.

**Comment by adamjdavies** [comment]
I'm also unable to put in a temporary fix by switching the field type to **Checkboxes** due to the same issue I reported earlier (#8483). When I try to update the multi-select field picker on some pages, I'm getting the error **Error updating component prop**.

**Comment by adamkingsbury** [comment]
It also looks like this is currently affecting relationship pickers

**Comment by melohagan** [comment]
Fixed in latest release!

**Comment by adamjdavies** [comment]
Thank you!
