### ISSUE TITLE
Autogenerated ejected form block crashes app

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8493]
**Hosting**
- Cloud
  - Tenant ID: bb.budibase.app

**Describe the bug**
Ejecting a form block and selecting the Form component causes the app to enter a broken state.

**To Reproduce**
1. Create auto-generated screens from a table (either internal or external SQL)
2. Select the `/new/row` screen
3. Eject the form block
4. Click on the form component
5. The app crashes, and the console shows: `TypeError: value?.match is not a function at extractLiteralHandlebarsID`
6. Refresh the page - **the screen is still unworkable**

**Expected behavior**
Ejecting a form block should not crash the app for auto-generated screens.

**Screenshots**
![Screenshot 2022-11-02 at 17 22 38](https://user-images.githubusercontent.com/101575380/199558432-2a34a946-1d09-426d-a680-02a7f69d75ae.png)

![Screenshot 2022-11-02 at 17 23 18](https://user-images.githubusercontent.com/101575380/199558552-16eb3941-0c46-4044-9707-47adb8f3e615.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by Ghrehh** [comment]
Merged this directly into master like you asked Mel https://github.com/Budibase/budibase/pull/8489

**Comment by melohagan** [comment]
That looks fixed now, thanks @Ghrehh ! Closing.
