### ISSUE TITLE
Cannot add S3 data source

### ISSUE THREAD

**Issue by rpmcoding** [Budibase/budibase#8510]
Self hosted.  Latest version.

I fill out the form when trying to add S3 as a datasource, however the "save and continue to query" button remains disabled so I cannot proceed.

**Comment by melohagan** [comment]
This actually applies to all datasources. I think it was introduced in **v2.1.11** from this file here: https://github.com/Budibase/budibase/commit/0d786426d5d3f1fe6efe383ee31b223f3b8ad8f7

@mike12345567 That fix of yours went into develop - it'll need merged into master?

**Comment by rpmcoding** [comment]
@mike12345567 @melohagan thanks for fixing.  However, when I go to update budibase, it says I am on 

Current version
2.1.9

Which seems ahead of v2.1.14 you released earlier somehow?

And the underlying data connection issue persists for me.

**Comment by mike12345567** [comment]
Hi @rpmcoding - 2.1.9 is 5 versions behind 2.1.14 - make sure to use the CLI to update your installation https://docs.budibase.com/recipes - this is the recommended method.

**Comment by rpmcoding** [comment]
@mike12345567 sorry yes you are  right. Why doesn't it update from the ui?

**Comment by mike12345567** [comment]
Hi @rpmcoding - the UI update utilises watchtower, which we've found to be flaky. In future it may be removed, as it only really works for docker-compose, and it works quite poorly. The CLI is always the safest way to update your installation.

Going to close this issue as I believe it is resolved!
