### ISSUE TITLE
Cannot save REST Configuration

### ISSUE THREAD

**Issue by kerbersystems** [Budibase/budibase#8511]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: <2.1.8>

**Describe the bug**
The 'Save' button on the rest configuration page is constantly greyed out, even after a config change. This means that no configurations can be changed.

**To Reproduce**
1. Go to 'Data'
2. Click on 'REST-2' (or any rest source)
3. Attempt to make a change
4. Unable to save

**Expected behavior**
That I can save the REST configuration 

**Screenshots**
Shown is me trying to make a change. I refreshed the page to show that no configurations changes are saved. Save button is never clickable. 

![Recording 2022-11-03 at 11 27 31](https://user-images.githubusercontent.com/96125948/199763371-13a91d75-2fa5-40fc-8554-0956e4c6ec11.gif)

  
**App Export**
[NIMO-export-1667489104988.tar.gz](https://github.com/Budibase/budibase/files/9930579/NIMO-export-1667489104988.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10/11, Mac OS
 - Browser Edge, Chrome, Safari

**Comment by mike12345567** [comment]
Hi @kerbersystems - this should be fixed in the latest release of Budibase 2.1.13. It is the same issue as: https://github.com/Budibase/budibase/issues/8465

**Comment by kerbersystems** [comment]
@mike12345567 Thank you so much. You guys are amazing!
