### ISSUE TITLE
Save Query button: Show why it is disabled

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#8523]
**Describe the feature request**
When creating a new query, if the name is not written, the Save Button is disabled. This makes sense, but perhaps it would be better if the button was enabled but a little red message was shown saying "The query has no name". 
Perhaps unnecessary, but it has happened to me that I got frustrated because I could not save the query and I didn't know why until I started checking everything and saw that the name field was empty. 

![image](https://user-images.githubusercontent.com/32724827/200532033-123f4688-bcd1-42e2-b2e9-c40c8b7bb48b.png)

**Comment by MistaZidane** [comment]
@AlejandroFNadal  Please can you send a screenshot so I could figure out the button in question? Thanks

**Comment by AlejandroFNadal** [comment]
> @AlejandroFNadal Please can you send a screenshot so I could figure out the button in question? Thanks

@MistaZidane thanks for the reply, I edited the issue report adding a screenshot

**Comment by MistaZidane** [comment]
@AlejandroFNadal  I have got it working now. There is a problem when the function is set read. 
[https://github.com/Budibase/budibase/pull/8602](https://github.com/Budibase/budibase/pull/8602)

**Comment by AlejandroFNadal** [comment]
Great, thanks :-D !

**Comment by aptkingston** [comment]
This will be addressed as part of upcoming work on the data section.
