### ISSUE TITLE
Allow "Only One Click" for the buttons 

### ISSUE THREAD

**Issue by JEQ7** [Budibase/budibase#8525]
there is no way to restrict the button clicks to only one single click!

**Comment by melohagan** [comment]
Hey @JEQ7 

I'm not sure what you mean. Are you looking to disable a button after it has been clicked?

**Comment by JEQ7** [comment]
I create app that send some requests if the user click the button 2 time it will send 2 request and I want to restrict it to one click only

**Comment by melohagan** [comment]
Hey @JEQ7 

This is possible at the moment by using [App state](https://docs.budibase.com/docs/app-state) and [Conditional UI](https://docs.budibase.com/docs/conditions)

### Step 1: Define actions -> Update State on click
<img width="1045" alt="Screenshot 2022-11-04 at 21 54 43" src="https://user-images.githubusercontent.com/101575380/200080733-ed24bc25-28b2-49ac-a2e7-67449302099d.png">

### Step 2: Configure conditions (at the bottom of the buttons settings panel)
<img width="1045" alt="Screenshot 2022-11-04 at 21 56 08" src="https://user-images.githubusercontent.com/101575380/200080912-7bd13510-41a7-4764-a238-5606790710ad.png">

#### Result
![disable_button](https://user-images.githubusercontent.com/101575380/200081085-58c58f3c-364f-40d9-9484-447237346994.gif)
