### ISSUE TITLE
bb-alert: No JWT Secret supplied, cannot configure JWT strategy

### ISSUE THREAD

**Issue by richardji7** [Budibase/budibase#8531]
**Hosting**

- Self
  - Method: <npm> 
  - Budibase Version: <2.1.15> 
  - App Version: <version> 

**Describe the bug**
After install it via:
$npm i -g @budibase/cli
I am getting error when trying to initialize
$budi hosting --init
bb-alert: No JWT Secret supplied, cannot configure JWT strategy 
Error - docker/docker-compose has not been installed, please follow instructions at: https://docs.budibase.com/docs/docker-compose

**To Reproduce**
1.  Install node.js 18.12.1
2.  Install budibase through: npm i -g @budibase/cli
3.  Try to init budibase:  budi hosting --init

**Expected behavior**

**Screenshots**
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

**Comment by agiient** [comment]
I am getting the same error.

**Comment by melohagan** [comment]
Hey @richardji7 

What do you seen when you run `docker-compose --version` ?

**Comment by richardji7** [comment]
I don't have docker installed.  Is that required?  I thought only node.js is required for non-docker use.

**Comment by melohagan** [comment]
Hey @richardji7 

As the error states:
> Error - docker/docker-compose has not been installed, please follow instructions at: https://docs.budibase.com/docs/docker-compose

You do need to install docker-compose. The Budibase CLI is basically a convenience wrapper on top of docker-compose.

More in the docs here! https://docs.budibase.com/docs/budibase-cli-setup#prerequisites

Closing.
