### ISSUE TITLE
Invalid body - App name must be letters, numbers and spaces only

### ISSUE THREAD

**Issue by jonnymccullagh** [Budibase/budibase#8533]
**Hosting**
- Cloud 

**Describe the bug**

**To Reproduce**
1. Log in to budibase.app
2. Go to [https://budibase.com/portals/templates/agency-client-portal-template/](https://budibase.com/portals/templates/agency-client-portal-template/)
3. Click on 'Use this template'
4. Redirected back to budibase.app
5. Error message: Error creating app

**Expected behavior**
App should be created in the same way as if staying within budibase.app and choosing 'User template' on the apps page.  

**Screenshots**
<img width="633" alt="image" src="https://user-images.githubusercontent.com/5209315/200119472-31d458ca-d5a2-42a6-ac11-db8084a03b13.png">

**Additional context**
Console shows:
```
POSThttps://redacted.budibase.app/api/applications
[HTTP/2 400 Bad Request 92ms]

[Builder] HTTP 400 on POST:https://redacted.budibase.app/api/applications
	Invalid body - App name must be letters, numbers and spaces only [index.059fe3d7.js:1:978](https://redacted.budibase.app/builder/assets/index.059fe3d7.js)
```

**Comment by shogunpurple** [comment]
This one is now working again - thanks for raising @jonnymccullagh!
