### ISSUE TITLE
Unable to select a date using date picker

### ISSUE THREAD

**Issue by michal-81** [Budibase/budibase#8548]
**Hosting**

- Self
  - Method: docker compose 
  - App Version: 2.1.8 

**Describe the bug**
I am not able to select any date except today's date using date picker. The problem occurs on 'Data'/'Design' tabs both for new and existing rows.

**To Reproduce**
1. Go to Data tab and select table with Date/Time column.
2. Click on Create row
3. Try to select any date for Date/Time column

**Expected behavior**
The selected date should appear for the field value

**Screenshots**
![Screenshot 2022-11-06 at 21-50-59 Budibase](https://user-images.githubusercontent.com/114871390/200196602-792d0fb4-6944-4404-8188-1ac6a0685715.png)

![Screenshot 2022-11-06 at 21-52-09 Olimp - built with Budibase](https://user-images.githubusercontent.com/114871390/200196633-35f863ce-e71c-4bfc-8a2e-f35bbdef6d0a.png)
  
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 106

**Additional context**
I think it might have broken after one of the recent updates because it was working before. Does anyone has the same issue?

**Comment by melohagan** [comment]
Hey @michal-81 

This has been fixed in the latest version **v2.1.15**. Please upgrade. 

https://github.com/Budibase/budibase/issues/8487

**Comment by michal-81** [comment]
Thank you @melohagan
After the upgrade it's working.
