### ISSUE TITLE
Perform action on cancel of confirmation dialog

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8561]
**Describe the feature request**
When performing an **Execute Query** or **Save Row** action you can specify a requirement of confirmation.

As a user, I would like to perform an action if cancel is pressed, so that I can clear a loading state.

E.g.
1. Update State (*isLoading = true*)
2. Execute Query (*require confirmation*) IF CANCEL -> *isLoading = false*
3. Update State (*isLoading = false*)

**Screenshots**
![image](https://user-images.githubusercontent.com/101575380/200347257-fd43fd1b-ac7c-421a-82df-cbc3a0a45a23.png)

**Comment by melohagan** [comment]
Another related issue here: https://github.com/Budibase/budibase/issues/7762

**Comment by aptkingston** [comment]
Sync automations is where you should handle branching, so while we may look at something like this it won't be in the short term.
