### ISSUE TITLE
MongoDB Aggregate Queries not listed as Data Provider source

### ISSUE THREAD

**Issue by dan-burt** [Budibase/budibase#8565]
**Hosting**

- Cloud
  - Tenant ID: https://redswitch.budibase.app

**Describe the bug**
MongoDB Aggregate functions, once Saved (created) cannot be selected as a Data Provider source

**To Reproduce**
1. Inside an active App, select the "Data" tab (at top of the page)
2. In the left-hand "Sources", select the green `MongoDB` list item
3. When right-hand pane loads, click the `Add Query` button
4. Fill in the fields, as needed. This will depend upon the backend datasource.
5. Click the "Run Query" button to test for execution. This should return data (documents) from the DB
6. Click the "Save Query" button
7. Go to the "Design" tab (at top of the page)
8. Click "Add Component" button
9. Select "Data Provider" in right-hand list
10. With the new Data Provider selected, select the Data drop-down list. It should be listed under "Queries", but does not on my usage.

**Expected behavior**
The "Run Query" button returns results, so the syntax is correct and data is available.
I expect this query source to be listed as the Data source for a Design Component

**App Export**
I can attach, but is a 10MB file

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.1
 - Browser: Safari
 - Version: 16.1

**Additional context**

**Comment by melohagan** [comment]
Hey @dan-burt 

I followed the reproduction steps but I can't reproduce the bug. It would be helpful if you could provide the app export please

**Comment by dan-burt** [comment]
[App1-export-1667836688969.tar.zip](https://github.com/Budibase/budibase/files/9960121/App1-export-1667836688969.tar.zip)

As requested. Think I did this correct, from within my "App1" settings.
