### ISSUE TITLE
align field to right and left?

### ISSUE THREAD

**Issue by agaitan026** [Budibase/budibase#8570]
any way to align some fields to the left, and other to the right? or always its like all scrolling down? 
thank you

**Comment by kasgithub8** [comment]
@agaitan026 you could try out the component "Section" set it to "Two columns" and put 2 containers inside the section.

**Comment by agaitan026** [comment]
yes i tried that but then how i add just one form to both containers? i dont want two forms blocks

**Comment by agaitan026** [comment]
got it thank you
