### ISSUE TITLE
Error initializing app: Not Found

### ISSUE THREAD

**Issue by tbankstemp** [Budibase/budibase#8571]
**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.1.15, 2.1.14, 2.1.13, 2.1.11, 2.0.37, 2.0.30
  - App Version: <version> 

**Describe the bug**
Tried to create, add templates, and import a previously exported app. When clicking on an app, or after importing an app and then clicking on it. I get what's in the screenshot below. Tried creating multiple new apps, adding multiple templates, and get the same results across all above listed versions. Two of my previously exported apps were on versions 2.0.30 and 2.0.37 and were working perfectly. I also noticed once I create a new app, I would get logged out and once re-logging back in, either the app wouldn't be listed in the Apps section, or when clicking on it, the errors show up on screen(screenshot). I've read through most of the other issues mentioning "Error initializing app: Not Found".  [#8351](https://github.com/Budibase/budibase/issues/8351) and [#8350](https://github.com/Budibase/budibase/issues/8350) seam to be similar to my issue. 

![Screenshot at 2022-11-04 11-41-58](https://user-images.githubusercontent.com/9778528/200022754-59e463f9-2716-406e-992b-faf5562f1aba.png)

**To Reproduce**
1. Go to 'Apps'
2. Click on 'Start from scratch' or 'Import app'
3. Click on 'the newly created app'

**Expected behavior**
Expect the App to open and ability to start designing.
  
**Desktop (please complete the following information):**
 - OS: [Linux Debian 11, bullseye]
 - Browser [Firefox, Chrome, and Chromium]
 - Version [Multiple]

**Additional context**
Tried multiple browsers, multiple versions on Budibase, even blew away one of my Linux boxes and started fresh and issues persists. 
I thought that there could be the possibility of a specific update to the Linux system that could have caused an issue with Docker and rebuilt on an image I had when I initially started testing Budibase(2.0.30) and am still having the same issues.

Any help would be greatly appreciated. 
Thanks.

**Comment by melohagan** [comment]
Hey @tbankstemp 

Maybe there is an issue with your couchdb instance. You could try wiping your docker volumes to get a clean slate.

Otherwise, you could try following this guide incase there's a conflict in your couchdb database: https://github.com/Budibase/budibase/discussions/7777#discussioncomment-3732390

**Comment by tbankstemp** [comment]
Thanks for the reply @melohagan, 

I've wiped my volumes, and also tried this on a completely fresh system with no updates and a fresh install of Docker. On the original system I blew away all volumes before posting this report. 

This is my docker string I'm using... ( I also wiped the local "budibase_data" folder as well as removing that from the below command altogether). 

`docker run -it --name budibase -p 10000:80 -v $(pwd)/budibase_data:/data -e INTERNAL_API_KEY=budibase -e JWT_SECRET=budibase -e MINIO_ROOT_USER=budibase -e MINIO_ROOT_PASSWORD=budibase -e REDIS_PASSWORD=budibase -e COUCHDB_USER=budibase -e COUCHDB_PASSWORD=budibase -e MINIO_BROWSER=on budibase/budibase:latest`

All this to say, I'm not understanding what has happened, got a fresh system, trying with multiple versions of basically everything(budibase, browsers, OSes, Docker and I still get the same results. Also no conflicts in couchdb that I can see.

**Comment by tbankstemp** [comment]
Okay, so I'm an idiot. I changed the 

> MINIO_ACCESS_KEY  to MINIO_ROOT_USER
and 
> MINIO_SECRET_KEY to MINIO_ROOT_PASSWORD

After changing that back, everything is working...sorry for the trouble, and thank you for your help.  I guess I should re-read the Docs next time.

**Comment by tbankstemp** [comment]
No problem at all. I should have listed the docker command to begin with. Thanks again!
