### ISSUE TITLE
MySQL config: pressing enter adds SSL entry instead of saving

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8580]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.15
  - App Version: 2.1.15

**Describe the bug**
When adding a new MySQL datasource, when you press the enter key on any field, it adds a row to the SSL setting rather than the expected functionality of `Save and fetch tables`

**To Reproduce**
1. Add a new MySQL datasource
2. Type into the 'Host' field
3. Press enter
4. See that an entry has been added under the SSL config, which is unexpected.

**Expected behavior**
When I press enter on the MySQL config, it should trigger the `Save and fetch tables`

**Screenshots**
*Type in a host*
![Screenshot 2022-11-08 at 10 29 48](https://user-images.githubusercontent.com/101575380/200541393-cdf2d455-8572-4ffa-98c9-38d35eeb5858.png)

*This happens when you press the enter key*
![Screenshot 2022-11-08 at 10 30 16](https://user-images.githubusercontent.com/101575380/200541501-c5a98d28-f032-42a5-a321-d1bceb51c780.png)

**Comment by aptkingston** [comment]
Fixed with new data onboarding changes.
