### ISSUE TITLE
Ejecting a date picker from a form has the wrong initial 'Show time' setting

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8585]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.15
  - App Version: 2.1.15

**Describe the bug**
Ejecting a date picker from a form has the setting 'Show time' ticked, but the time doesn't actually show. You have to untick and tick the setting again to get the time to show.

**To Reproduce**
1. Create a table with a Date/Time field
2. Create auto-generated screens
3. In the edit screen, see that the date-picker has no time
4. Eject the form block
5. The date field has 'Show time' ticked, but see that no time is shown
6. Untick/tick to get the setting to apply.

**Expected behavior**
When I eject a form block, the date picker settings should match what they were in the form block.

**Screenshots**
*Ejected form field has 'Show time' ticked but no time included*
![Screenshot 2022-11-08 at 11 10 03](https://user-images.githubusercontent.com/101575380/200549481-0b2bcbce-3d2e-4a7e-8b1f-0ad7e932b78a.png)

*Toggle the 'Show time' setting. Time is now shown*
![Screenshot 2022-11-08 at 11 10 47](https://user-images.githubusercontent.com/101575380/200549599-4826b200-67a2-4ec9-a330-8bd8a8798e10.png)

**Comment by aptkingston** [comment]
This is actually just a bug with the date time field itself - the component has a default value of false for showing time, but the manifest defines a default value of true. I'll push that change to the form block fixes branch anyway since hopefully it'll get merged soon.
