### ISSUE TITLE
Export app - 504 Gateway timeout

### ISSUE THREAD

**Issue by maiducan** [Budibase/budibase#8589]
Hello,

i cannot export my app from budibase portal (self-hosted), my app is large (more than 50MB) and it exceeds the timeout during export even though i increased the limit in nginx. So it must be somewhere inside of the budibase. Its always 2 minutes.

**Comment by maiducan** [comment]
@mike12345567 Hello Mike, thank you for your fast reaction. However it is still not doing the trick for me. I have updated to the newest version and tried to export, and there is still 2 minutes threshold. :/ Could you please look at it once again? Thank you alot!

**Comment by marian001** [comment]
Although different, it may be related..   I can't export even small app from self-hosted portal. I'm getting error 502 Bad gateway.

**Comment by maiducan** [comment]
yes its related .. i have the same issue now, it immediately through 502 after clicking export app  :/ .. @mike12345567

**Comment by maiducan** [comment]
@mike12345567 

1. I am using docker-compose / Budi CLI
2. I am udpating via budibase UI

**Comment by mike12345567** [comment]
Hi @maiducan - updating through the UI can be quite flaky - its something we're probably going to remove in the future as it doesn't work particularly well. Can you please try updating using the Budibase CLI, using the `budi hosting --update` command.

**Comment by mike12345567** [comment]
Hi @maiducan - do you know what version this started happening at? I'm currently testing an installation based on docker-compose, running 2.1.24 and I cannot replicate it at all.

**Comment by mike12345567** [comment]
Hi @marian001 - I'm not 100% sure what image is used on Digital Ocean at the minute, but if it is docker single image, or docker-compose based you can still use the CLI to update it.

**Comment by maiducan** [comment]
For me it started at version 2.1.21 or 24, after you made changes in those nginx config files

**Comment by marian001** [comment]
BTW, I'm running my instance with HTTPS and on own domain. I tried accessing the portal through HTTP on the IP address and port 10000, but the export is still failing.

**Comment by mike12345567** [comment]
Hi guys - I've played around with this, tried upgrading through a few versions etc - but I'm still unable to replicate. Perhaps there is something you can find in your logs that would help explain the issue - or if you can see if it happens with all apps, vs a small set of apps (does it happen with newly created apps, or only with older apps, or is it just a total installation problem).

**Comment by maiducan** [comment]
I have two separate servers, each one has unique app (very big one > 50mb, and the second is tiny) .. And this occurs on both servers.

**Comment by marian001** [comment]
@mike12345567 where can we find logs to look into?

I have two apps running on one server..  one app is about 35 MV (latest tar.gz export with all data 10.11.2022; app txt exports before were less than 2 MB) and is no older than 2 months. The other is in early development with basically no data and is just a couple weeks old.

Is there any other (free) way to backup apps or the whole portal?

**Comment by mike12345567** [comment]
Hi @maiducan - does it still occur with new apps? Are there any logs you can provide, or even an older example of an app which exhibits this behaviour? 

Also - can you try just downgrading your `proxy-service` to a version before my changes, e.g. v2.1.20 (https://hub.docker.com/layers/budibase/proxy/v2.1.20/images/sha256-0eed22ccce35d8d70bfc4cbb92cc4acd973c572bc435bc53d9b5a86c18781483?context=explore).

You can specify the version on the image in your docker-compose file, by updating the image of the `proxy-service` to `image: budibase/proxy:v2.1.20`.

Hi @marian001 - you can backup your whole platform using the CLI: https://docs.budibase.com/docs/backups

**Comment by maiducan** [comment]
Yes it occurs even with a newly created "empty" app.
Do you think the downgrade will help? There is still that issue with timeout ..

**Comment by mike12345567** [comment]
@maiducan - it is more to try and determine what is happening - for me the timeout issue is resolved and I cannot re-create the 502 issue - just want to see if its something to do with the proxy image or if something else is happening.

**Comment by marian001** [comment]
502 error is immediate..

**Comment by maiducan** [comment]
Downgrade of proxy worked on the smaller app ..
The bigger one is in production, I will try it at night probably.

**Comment by maiducan** [comment]
I have tried the downgrade on bigger app. 502 is not occuring, but the timeout is still there. And even though the error appears, the export process does not stop in the background and consumes the resources (100%) for a few minutes, so i have to restart the bbaps container.

**Comment by mike12345567** [comment]
Hi @maiducan - just for confirmation - would it be possible for you to try adding a fresh install of Budibase to your system running on another port? Without some logs or something to go off of - I'm finding very difficult to know how to rectify this issue - it appears to be an installation issue as I cannot re-create it with any of my existing installations/new installations.

The consuming 100% resources and crashing the container sounds like something is going very wrong - I've never seen behaviour like this before - if you have any older exports of the app you'd be willing to share you could send them to me privately, michael.drury@budibase.com - it might help me to replicate the issue you're seeing.

**Comment by marian001** [comment]
This is what I found in my logs from the moment when I tried to export an app:

`[34mcouchdb-service_1     |[0m [notice] 2022-11-14T11:57:02.261879Z couchdb@127.0.0.1 <0.29373.1> 72d259a770 couchdb-service:5984 172.18.0.8 def7e19e-e35d-4c01-9569-dd1a0754781e GET /global-db/ 200 ok 1
[34mcouchdb-service_1     |[0m [notice] 2022-11-14T11:57:02.266303Z couchdb@127.0.0.1 <0.29374.1> 10c16114e9 couchdb-service:5984 172.18.0.8 def7e19e-e35d-4c01-9569-dd1a0754781e GET /global-db/_design/database/_view/by_api_key?key=%22d90a4732d42xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxef38af5566d17%22 200 ok 1
[34mcouchdb-service_1     |[0m [notice] 2022-11-14T11:57:02.281798Z couchdb@127.0.0.1 <0.29375.1> e96b3dca56 couchdb-service:5984 172.18.0.2 def7e19e-e35d-4c01-9569-dd1a0754781e GET /global-db/ 200 ok 2
[34mcouchdb-service_1     |[0m [notice] 2022-11-14T11:57:02.285371Z couchdb@127.0.0.1 <0.29376.1> f9db392f48 couchdb-service:5984 172.18.0.2 def7e19e-e35d-4c01-9569-dd1a0754781e GET /global-db/_design/database/_view/by_api_key?key=%22d90a4732d42xxxxxxxxxxxxxxxxxxxxxxxxxf38af5566d17%22 200 ok 1
[34mcouchdb-service_1     |[0m [notice] 2022-11-14T11:57:02.290336Z couchdb@127.0.0.1 <0.29377.1> 40f009ac62 couchdb-service:5984 172.18.0.2 def7e19e-e35d-4c01-9569-dd1a0754781e GET /global-db/ 200 ok 1
[34mcouchdb-service_1     |[0m [notice] 2022-11-14T11:57:02.295077Z couchdb@127.0.0.1 <0.29378.1> 904a0c2494 couchdb-service:5984 172.18.0.2 def7e19e-e35d-4c01-9569-dd1a0754781e GET /global-db/_all_docs?include_docs=true&startkey=%22us_%22&endkey=%22us_%EF%BF%B0%22 200 ok 3`

..so not much..  I haven't seen any 502 error in the whole log

**Comment by mahxds** [comment]
im having same issue , i cant export currently my app getting 502

**Comment by mahxds** [comment]
also can confirm proxy version 2.1.6 works finde. Downgrade worked fine for me

**Comment by maiducan** [comment]
There is another semi-related issue - full platform backup up via budi cli is also failing. Due to the bigger size of the app and minio attachements, the export fails on RAM capacity. I have 8GB and when it reaches max capacity, the process of budi backup is killed. So right now i cannot export app neither do full platform backup :/

**Comment by diogenesbrussels** [comment]
I also get a 502 when exporting apps: in self-hosted, updated via CLI from 2.0.37 to 2.1.24.
This doesn't seems to be related to the size of the app or the needed ressources.
