### ISSUE TITLE
Hidden fields not included in database insert

### ISSUE THREAD

**Issue by jefft4** [Budibase/budibase#8595]
**Hosting**
- Cloud

** Issue **
I have a create form which needs to write a new UUID value to a SQL Server uniqueidentifier column on the table. I've been able - thanks to someone else's solution (why is uuidv4() not build in?) to create the UUID value in the default code for the field and if the field is visible on screen, the new record inserts as expected.

However, if I hide the field - no-one is interested in an ugly long uuid - then the form save action fails, reporting that the uniqueidentifier column cannot be null.

This is either an issue with the default value code not being executed for hidden fields, or with the database column bindings 'forgetting' hidden fields.  I'm not sure which; will try to add something to expose the value of the field by another route and update this post when I confirm.

**Expected behaviour**
Field default values should work and field values should bind to their data source columns, regardless of whether the field is visible or not.

**Comment by melohagan** [comment]
Hey @jefft4 

Could you please fill out the bug template. Include numbered reproduction steps, screenshots and if possible an app export.
