### ISSUE TITLE
Use json for db.txt in export

### ISSUE THREAD

**Issue by B-z-F** [Budibase/budibase#8618]
**Describe the feature request**
It would be useful if json was used for the db.txt file in the export. If many screens are used, the quickest way to localize e.g. button labels is to export the file, bulk edit the db.txt and import as a new application.
If json could be used instead of txt, it would be faster and clearer (now when reformatting the db.txt file, the import as a new application fails).

**Comment by mike12345567** [comment]
Hi @B-z-F - the app export can't really be JSON based as this is a CouchDB/PouchDB feature that we are not in control of. It includes a lot of data about revisioning, tombstoning of apps etc. 

Right now its best to look at Budibase exports as a read-only file, updating/formatting the file in anyway can cause issues with the import which will be very hard to fix.
