### ISSUE TITLE
UI hangs when tables are swiftly changed

### ISSUE THREAD

**Issue by digiajay** [Budibase/budibase#862]
As you can see below that UI has hung when I swiftly change between the table options and I have to close and reopen the budibase to get it fixed.

![de0e3245-a5fc-4537-9e8e-2a8f0e8e40db](https://user-images.githubusercontent.com/6551395/99156111-58c2d900-26b6-11eb-938f-970c801f5c3f.gif)

**Comment by shogunpurple** [comment]
Thanks @digiajay, this has been resolved and the fix will be in the next release.
