### ISSUE TITLE
Lot of screens list added

### ISSUE THREAD

**Issue by digiajay** [Budibase/budibase#863]
I was following the tutorial to build the CRM app and when I refreshed the BudiBase, I got to see a lot of Home Screens.. I am not sure at what point it started generating so many screens... I refreshed, closed, and opened the BB app, still, issue persists.. When I deleted the screen, all Home screens gone.

![2fe83ca6-7642-427e-ae0d-f2f69fae56ea](https://user-images.githubusercontent.com/6551395/99156728-3d0e0180-26bb-11eb-9b4f-da8091d2ef82.gif)

**Comment by kevmodrome** [comment]
This has already been fixed and will be in the next release :)
