### ISSUE TITLE
Missing attachments, after export and import app, wrong attachment's path

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#8637]
https://www.loom.com/share/f1054b9c42024f5fa0f6c90210670dcd
Env : bb.budibase 

Cheeks: :) so its just a bug where cloud attachments get converted into [newAppId]/[newAppId] when it should just be [newAppId], like the old app ID prefix is replaced with a double prefix of the new app ID

**Comment by MistaZidane** [comment]
@MihailHadzhiev2022 I will look it up. Thanks
