### ISSUE TITLE
App updated to latest version, but still it showing to update but to the previous version

### ISSUE THREAD

**Issue by smad-bro** [Budibase/budibase#8641]
**Hosting**

- Self
  - Method: Docker Single Image
  - Budibase Version: 2.1.24 
  - App Version: 2.1.24

**Describe the bug**
I have updated the budibase app and then when I opened one of my apps in the top right corner the update notification popped up. Then I clicked on it. Then it shows that you are running 2.1.24 update it to the latest  2.1.21. Please check the screenshot that I attached.
I self-hosted this on the Microsoft Azure platform.

**Screenshots**
![Screenshot (194)](https://user-images.githubusercontent.com/67038642/201307333-d4567cb7-352c-4b04-b422-df9eab015666.png)
  

**Desktop:**
 - OS: Windows
 - Browser: Chrome

**Comment by melohagan** [comment]
Hey @smad-bro 

Just incase, could you ensure that the browser cache has been cleared. 

Also can you pull down the latest single image.

**Comment by smad-bro** [comment]
I clicked on cancel, and it never appeared again.
