### ISSUE TITLE
Backslash converted to double Backslash when set as default value

### ISSUE THREAD

**Issue by koneubauer** [Budibase/budibase#8642]
**Hosting**
- Self
  - Method: docker-compose
  - Budibase Version: 2.1.24
  - App Version: 2.1.24

**Describe the bug**
I want to have a single backslash as the default value for my textfield. When i use the Budibase-DevTools, the default value is two backslashes. It's the same for other component types like Options Picker.

**To Reproduce**
1. Create any component type which supports a default value
2. set a single backslash as the default value
3. in the preview, open DevTools and select the component

**Expected behavior**
Should be a single backslash

**Desktop:**
 - OS: W10
 - Browser Edge 107.0.1418.35

**Comment by aptkingston** [comment]
Devtools escapes values before showing them, so this is just a slight display issue that we probably won't be addressing.
