### ISSUE TITLE
Error when connecting Keycloak

### ISSUE THREAD

**Issue by PaulKolbe** [Budibase/budibase#8645]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.0.33

**Describe the bug**
I tried to connect Keycloak to Budibase and followed the steps in the Budibase-Documentation. When I try to login with OIDC I land on a page showing the following error: 
`{"message":"Error constructing OIDC authentication configuration","status":500}`

**Things I have already checked**
1. The Config URL works
2. The Client ID is correct
3. The Client Secret ist correct
4. I copied the Redirect URI from budibase to keycloak

**Screenshots**
![image](https://user-images.githubusercontent.com/44832086/201318574-0c4e334f-2c94-4494-9848-9fc1a5383d02.png)
Error message
![image](https://user-images.githubusercontent.com/44832086/201318795-fabafd90-eb2a-4bbd-a0c1-9b5ecf515ac9.png)
Settings in Budibase
![image](https://user-images.githubusercontent.com/44832086/201319076-a7c30b8e-b1a9-4d7b-8d1e-29d54ccbd359.png)
Settings in Keycloak

**Desktop**
 - OS: Windows
 - Browser: chrome

**Comment by thomas-schuster** [comment]
Any updates on that? We do have a similar setup and end up with the same error.

Software versions used by us:
Budibase 2.1.42
Keycloak 16.1.1 and a second setup tested with 20.0.1

**Comment by wuyh03** [comment]
replace the localhost with real IP (within the redirect url) might fix the issue, but will meet another issue .


{"message":"Error constructing OIDC authentication configuration - TypeError: Cannot destructure property 'clientID' of 'enrichedConfig' as it is undefined.","status":500}

**Comment by Notespeak** [comment]
Facing a similar problem described in https://github.com/Budibase/budibase/issues/7527#issuecomment-1396090680 .

**Comment by m1212e** [comment]
Did you find a solution to this?

**Comment by melohagan** [comment]
I don't think you can use localhost for OAuth flows. Also if it's docker, would it not need to be **host.docker.internal** ?

Going to close as stale.
