### ISSUE TITLE
SMTP SSL routines:ssl3_get_record: wrong version number

### ISSUE THREAD

**Issue by feurer98** [Budibase/budibase#8649]
**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 2.1.24

**Describe the bug**

**To Reproduce**
1. Setup:  sudo docker run -d -t -p 10010:80 -v /volume1/docker/budibase3:/data budibase/budibase:latest
2. creat admin
3. login
4. import app
5. reminde to setup mail
6. Fill in settings
7. save
8. View error message

The installation is only 10 minutes old.

**Screenshots**
![image](https://user-images.githubusercontent.com/45851500/201331931-43329d81-9e07-48bf-91ab-9cd3db8aa0d5.png)

**Comment by Rory-Powell** [comment]
Hi @feurer98 . This appears to be an issue with your SMTP providers handling of SSL. You may need to reach out to the provider for support in this specific case.
