### ISSUE TITLE
Chart data/label options run off the screen

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#865]
**Describe the bug**
Chart data/label options run off the screen

**To Reproduce**

1. Add data to your table (make the column title reasonable long)
1. Add a chart to your screen
1. Click the data label option

**Expected behavior**
The popover position itself more to the left so there's enough room to show the options in their entirety 

**Screenshots**
![Screenshot 2020-11-17 at 14 45 33](https://user-images.githubusercontent.com/49767913/99404781-f18a6c00-28e3-11eb-994c-4d092b427ca7.png)

**Comment by zulqarnain4** [comment]
Quite a Bug!
