### ISSUE TITLE
Add delete option on published apps

### ISSUE THREAD

**Issue by AndyWhann** [Budibase/budibase#8650]
#Problem

There is no way to educate the user that in order to delete a published app, they have to unpublish it first.

#Solution

Leave the option available but instead of opening the delete modal, open a new modal that asks if they want to unpublish their app in order to delete.

After they unpublish then open the confirm deletion modal.

![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/4ea07e2c-b3e8-4095-bbe6-b331a8204bd6)

**Comment by shogunpurple** [comment]
Always find myself wanting this one. Would be a really nice addition
