### ISSUE TITLE
Create chart with unknown number of data columns

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8652]
### Discussed in https://github.com/Budibase/budibase/discussions/8442

<div type='discussions-op-text'>

<sup>Originally posted by **that-one-tom** October 29, 2022</sup>
Hi all, the [documentation ](https://docs.budibase.com/docs/chart#many-data-columns) mentions

> If you do not know ahead of time how many labels or data columns you will be displaying, then you will need to use JavaScript to loop over your API data.

I am working on a screen where users can pick which data series they want to compare in a line chart. The transformation in the data provider can handle this just fine (and returns one label column + 1...n data columns with changing names), but I can't get the line chart to work with this setup.
</div>

**Comment by HilaryTorn** [comment]
We need this too! We did a custom chart instead, but it makes configuration more awkward.

**Comment by aptkingston** [comment]
Sorry we aren't likely to support this.
