### ISSUE TITLE
Budibase bug: api call edit freezes UI

### ISSUE THREAD

**Issue by nunopoco** [Budibase/budibase#8655]
**Hosting**
- Self
  - Method: digital ocean
  - Budibase Version: 2.1.18

**Describe the bug**
Editing an API call freezes the UI, even though other calls work properly.

**To Reproduce**
1. Use my app export and click on the data tab;
2. Click on SMS API;
3. Click on "Enviar SMS de Reserva";
4. Try and click back to anywhere else.

**Expected behavior**
Expected to open the api call configuration screen.

**Screenshots**
[video walkthrough](https://nuno.dubb.com/v/80aYcG)
  
**App Export**
[Processos-export-1668186671336.tar.gz](https://github.com/Budibase/budibase/files/9992210/Processos-export-1668186671336.tar.gz)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Chrome
 - Version: 107.0.5304.106

**Comment by melohagan** [comment]
Will be fixed in the next release - apologies for the delay.
