### ISSUE TITLE
Custom Component can't bind on change value

### ISSUE THREAD

**Issue by ppipee** [Budibase/budibase#8683]
Latest Budibase Version
Both Self Hosted and Online

https://github.com/ppipee/csv-import

I create  a plugin component and pass a value to the onChange event and I try to access `Field Value` but it returns undefined. I've tried to using your component to investigate my error code, but `Field Value` is still undefined. 

or Plugin component can't bind value to the onChange event?

**Comment by melohagan** [comment]
Hey @ppipee 

Make sure that you have it configured correctly. Docs added here: https://docs.budibase.com/docs/custom-component#on-change-event
