### ISSUE TITLE
"Your Apps Error: [object. Object]" after crash from adding Column to table

### ISSUE THREAD

**Issue by Lumikinos** [Budibase/budibase#871]
**Describe the bug**
Adding column of type "option" to an imported table with existing data resulted in BudiBase crash and "Your Apps...
Error: [object Object]" upon re-launch. 

**To Reproduce**
1. Created table from csv, not all columns contained data
2. Table imported successfully 
3. Add column of type "option" and enter option names
4. click save
5. tables disappeared from side view, app unresponsive
6. Upon re-launch, "your apps" only displays Error: [object Object]

**Expected behavior**
Add column with option fields available to pick 

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Version Budibase Version 0.3.8

**Comment by shogunpurple** [comment]
Thank you for the details bug report @Lumikinos. The team will look into this one ASAP.

**Comment by shogunpurple** [comment]
This one should be resolved in the next release. Closing
