### ISSUE TITLE
Not possible to configure CA for MySQL via UI

### ISSUE THREAD

**Issue by palsivertsen** [Budibase/budibase#8713]
**Hosting**
- Cloud
  - Tenant ID: N/A

**Describe the bug**
When adding a MySQL data source it's not possible to set the `ca` parameter since the input does not allow new lines (`\n`).

**To Reproduce**
1. Go to add datasource for any app
2. Select MySQL
3. Click 'Add' under 'SSL'
4. Try to put a newline in the `value` field

**Expected behavior**
The `value` input field should accept text with newlines so that we can provide a certificate in pem format

**Screenshots**
![image](https://user-images.githubusercontent.com/11890143/202486440-b0968acc-66ab-4d38-bbea-93eff4a49810.png)
  
**App Export**
N/A

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Google Chrome
 - Version 107.0.5304.87 (Official Build) (64-bit)

**Additional context**

**Comment by melohagan** [comment]
Hey @palsivertsen 

Just to clarify, when you provide a database, what error do you get when trying to connect with that ca cert?

**Comment by palsivertsen** [comment]
I can't remember the exact error message, but it's related to certificate parsing. The `ca` field used by the underlying library expects a string in PEM format, which heavily depends upon linefeeds (`\n`). When pasting in a PEM encoded certificate in the text box, then all the line feeds gets stripped.

Example:
```
-----BEGIN CERTIFICATE-----
MIIFaDCCBFCgAwIBAgISESHkvZFwK9Qz0KsXD3x8p44aMA0GCSqGSIb3DQEBCwUA
VQQDDBcqLmF3cy10ZXN0LnByb2dyZXNzLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAMGPTyynn77hqcYnjWsMwOZDzdhVFY93s2OJntMbuKTHn39B
bml6YXRpb252YWxzaGEyZzIuY3JsMIGgBggrBgEFBQcBAQSBkzCBkDBNBggrBgEF
BQcwAoZBaHR0cDovL3NlY3VyZS5nbG9iYWxzaWduLmNvbS9jYWNlcnQvZ3Nvcmdh
bml6YXRpb252YWxzaGEyZzJyMS5jcnQwPwYIKwYBBQUHMAGGM2h0dHA6Ly9vY3Nw
lffygD5IymCSuuDim4qB/9bh7oi37heJ4ObpBIzroPUOthbG4gv/5blW3Dc=
-----END CERTIFICATE-----
```
Becomes this in stead:
```
-----BEGIN CERTIFICATE-----MIIFaDCCBFCgAwIBAgISESHkvZFwK9Qz0KsXD3x8p44aMA0GCSqGSIb3DQEBCwUAVQQDDBcqLmF3cy10ZXN0LnByb2dyZXNzLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMGPTyynn77hqcYnjWsMwOZDzdhVFY93s2OJntMbuKTHn39Bbml6YXRpb252YWxzaGEyZzIuY3JsMIGgBggrBgEFBQcBAQSBkzCBkDBNBggrBgEFBQcwAoZBaHR0cDovL3NlY3VyZS5nbG9iYWxzaWduLmNvbS9jYWNlcnQvZ3Nvcmdhbml6YXRpb252YWxzaGEyZzJyMS5jcnQwPwYIKwYBBQUHMAGGM2h0dHA6Ly9vY3NwlffygD5IymCSuuDim4qB/9bh7oi37heJ4ObpBIzroPUOthbG4gv/5blW3Dc=-----END CERTIFICATE-----
```

As a workaround I ended up recoding the API call from my browser and ran it through cURL with a corrected json. Worked like a charm.

---
Some context:  
I found [this answer](https://github.com/Budibase/budibase/discussions/4306#discussioncomment-2102854) in a similar issue linking to [this doc](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) which documents the available fields. Hope this helps.

**Comment by melohagan** [comment]
Can we copy the same box and code from Postgres? 

<img width="531" alt="Screenshot 2022-11-23 at 17 57 49" src="https://user-images.githubusercontent.com/101575380/203616648-97ff706a-0712-48c0-9a8d-ab4a15eee21d.png">

**Comment by palsivertsen** [comment]
Just a heads up: there are some other fields that accepts PEM encoding as well (cert, key, crl). Maybe they should be added as well? Or maybe allow the user to supply the json object?

**Comment by melohagan** [comment]
I'm going to close this one, because I don't think `ca` is an option. From the docs only `cert` and `key` are mentioned.
