### ISSUE TITLE
User created by oidc(Azure) cannot be deleted from Budibase DB user table.

### ISSUE THREAD

**Issue by kzkondo** [Budibase/budibase#8721]
**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 

**Describe the bug**
User created by oidc(Azure) cannot be deleted from Budibase DB user table.

**Screenshots**
![apps_users](https://user-images.githubusercontent.com/93172658/202596087-883cd9fe-540d-4698-af94-f14732bb80f5.png)
oidc (Azure) user that cannot be deleted.

![users_pages](https://user-images.githubusercontent.com/93172658/202595179-cd7952ca-ff3b-4d7a-85c5-63e253f29fa4.png)
Remains even if deleted from the user screen.

![access_page](https://user-images.githubusercontent.com/93172658/202595423-6587722c-4416-4834-8e88-578b164305e4.png)
It remains even if the user is deleted from the App Access screen.
  
**Desktop (please complete the following information):**
 - OS: [MacOS 12.6.1]
 - Browser [chrome, safari]
 - Version [107.0.5304.110]

**Comment by melohagan** [comment]
Hey @kzkondo 

We stepped through this one and have determined that it is not a bug. When you remove a user that has previously logged into an app, the user is kept in the users table as a log.
You can see in your screenshot that the status of the user was set to *inactive* to indicate that the user has been deleted from user management. 

For example Budibase internal tables have auto columns that keep track of which user created and updated a row. If the user was deleted from the users table, then this history would be lost.
![Screenshot 2022-12-07 at 17 30 49](https://user-images.githubusercontent.com/101575380/206249668-5833db63-5372-4656-969c-dcf2aabecf05.png)

Closing.
