### ISSUE TITLE
Discrepancy between default image size unit in builder and preview

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8750]
### Discussed in https://github.com/Budibase/budibase/discussions/8745

<div type='discussions-op-text'>

<sup>Originally posted by **ecxs** November 21, 2022</sup>
Hi there,

I've set an image to be a certain size, which show fine in design mode, but keeps expanding in preview and published version.

App version 2.1.26 with Chrome Version 107.0.5304.110 (Official Build) (arm64)
![Screenshot 2022-11-21 at 12 19 33](https://user-images.githubusercontent.com/4005405/203038152-692b975b-9d04-44c1-aaff-dd0b493c3c64.png)
![Screenshot 2022-11-21 at 12 19 44](https://user-images.githubusercontent.com/4005405/203038172-c160f440-7b29-41e5-9120-9ac53237a5ba.png)
</div>

This is fixed by using `25px` instead of `25`, but it is a little confusing that the default size unit is not the same between the builder and the preview.

**Comment by aptkingston** [comment]
A unit is always expected - I'm not sure why the behaviour is inconsistent.

**Comment by melohagan** [comment]
It definitely does appear to treat the width and height as pixels in the builder for some reason.

**Comment by aptkingston** [comment]
This has been fixed.
