### ISSUE TITLE
Sending one mail on an update

### ISSUE THREAD

**Issue by Autoradiowecker** [Budibase/budibase#8753]
**Hosting**
- Self
  - Method: Docker Container Native
  
**Describe the bug**
We have a Emailing Process where we want to sent one Mail after a specific edit. 
Emails get sent multiple Times. Because when the row updated Event with conditions we cant set a state like email already sent.

either we dont update the Row and send additional Mails on evry Further Update
or we use update Row and multiply the entry

**To Reproduce**
1. Go to Automations
2. Create New with row updated
3. Create Mail Event
4. Create Update Row
5. now on a valid update you sent one mail and multiply the row

**Expected behavior**
Sending a Mail with using the Row Updated Event and updating the row.

**Comment by kasgithub8** [comment]
Why don't u:

option 1: trigger another (emailing) automation inside Budibase or outside (n8n?)
option 2: why dont u trigger your email automation not based on the row updated event rather on an app action

?

To Budibase devs: is it issue really true or should his desired behaviour work?

**Comment by mike12345567** [comment]
The correct solution to this would be to use a condition in your automation like so: https://docs.budibase.com/docs/conditions-1

To stop the automation before sending email if the condition isn't met.

Closing as this isn't an issue with the platform.
