### ISSUE TITLE
Default value of text field doesn't change when inside data provider

### ISSUE THREAD

**Issue by koneubauer** [Budibase/budibase#8763]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.24
  - App Version: 2.1.24

**Describe the bug**
I have a hidden textfield inside a repeater inside a data provider. The data provider uses a query and passes the value of another textfield to the query. The result of this query/data provider is set as the default value of the hidden textfield. When changing the content of the plain textfield, the content in the hidden textfield stays unchanged. When putting a table inside the data provider it displays the correct value. This used to work in version 1. Eversince updating to version 2, this functionality doenst work anymore.

**Expected behavior**
The value of the hidden field should change according to the result of the data provider when changing the input field

**Desktop:**
 - OS: W10
 - Browser Edge 107.0.1418.52

**Comment by melohagan** [comment]
Hey @koneubauer 

Default value in version 2 only loads on initial page load. It is no longer 'dynamic'. 

If you want to update a form field you must use the **Update Field Value** action: https://docs.budibase.com/docs/actions#update-field-value
