### ISSUE TITLE
Google SSO callback changed?

### ISSUE THREAD

**Issue by palsivertsen** [Budibase/budibase#8765]
**Hosting**
- Cloud

**Describe the bug**
I've configured callback URL for Google SSO to `<budibase-domain>/api/admin/auth/google/callback` according to the docs. This morning when trying to log in I get an error because the callback URL is now `https://<budibase-domain>/api/global/auth/<my-company>/google/callback`. Is this expected?

**Expected behavior**
Callback URL to stay the same.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Google Chrome
 - Version 107.0.5304.110 (Official Build) (64-bit)

**Comment by shogunpurple** [comment]
Hey @palsivertsen - this is due to our new URL structure for google callbacks. It seems that you have an override in your callback URL, so you will need to update your config to that described in the docs - https://docs.budibase.com/docs/sso-with-google

Closing this for now.
