### ISSUE TITLE
Dragging a button out of a table can cause the page to error and require a page refresh

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8767]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.31
  - App Version: 2.1.31

**Describe the bug**
Moving a button out of a table component and dragging it around can crash the builder page.

**To Reproduce**
1. Add a Data provider with a nested table
2. Click on the table and add a button into the table
3. Drag the button out of the table to the top of the data provider
4. Drag the button from the top of the data provider to the bottom (below the table)
5. Observe crash. Need to refresh page.

**Expected behavior**
Moving a button out of a table and dragging it around should not crash the builder.

**Screenshots**
<img width="1450" alt="Screenshot 2022-11-22 at 13 47 01" src="https://user-images.githubusercontent.com/101575380/203329883-28502333-b190-413c-88f8-c20347fc407d.png">

**Comment by aptkingston** [comment]
I had intermittently seen this issue myself but it seemed hard to reproduce and it's an internal svelte error being thrown which makes things nearly impossible to debug.

I've had another look, and (while I'm completely guessing here) I think that it's something to do with the fact that we don't key table rows, so something is going wrong when the number of table columns reduces and svelte unmounts things. I tried remounting the entire BBUI table component when the number of columns changes and this does appear to fix the issue, so I'll go with that fix.
