### ISSUE TITLE
Budibase CLI memory usage improvements for large backup procedures

### ISSUE THREAD

**Issue by maiducan** [Budibase/budibase#8770]
Hello, I cannot backup my full environment with budi backup command due to the fact, that my container (couchdb - 2.5GB) is a little bigger and the backup process exceeds the RAM limit (using all of the 12GB) and then crashes. 

- Self hosted, using Budi CLI / docker compose
- 12GB of RAM

Is there a possibility to update the command so that it utilise the memory more efficiently? Thank you

**Comment by mike12345567** [comment]
Hi @maiducan - sadly its very difficult to make this more memory efficient easily, however you could try adding the `--max-old-space-size` when running the CLI, by default Node can only use 1.5GB of memory, you could set this to say 5GB with `--max-old-space-size=5120` and try this again.

**Comment by mike12345567** [comment]
@maiducan - I see, I'll convert this issue into an enhancement request, i'm not sure what we can do to improve this - for now I would recommend looking into direct CouchDB replication as this will be much more performant in larger deployments.
