### ISSUE TITLE
Table component displays Invalid Date for dates formatted with handlebars Date helper

### ISSUE THREAD

**Issue by michal-81** [Budibase/budibase#8775]
**Hosting**

- Self
  - Method: docker compose
  - App Version: 2.1.28

**Describe the bug**
Date columns in table component are not formatted properly when configured using conditions.

**To Reproduce**
1. Add data provider with a table containing datetime column
2. Click on 'Configure columns' button and add a datetime column. 
3. Click on the gear icon for that column and set the Value to {{ date Value "DD-MM-YYYY" }} and save the changes.
4. The dates are displayed and formatted correctly
5. Add a button to the screen that when clicked stores some value in an App state.
6. Click on 'Configure conditions' button for the table component. 
7. Choose 'Update settings' -> 'Columns' to 'configure columns' and use value stored in step 5 as a condition for new column layout.
8. Repeat step 2 and 3 for that condition.
9. Click on the button to trigger the condition.
10. 'Invalid Date' is displayed for the date column.
 
**Expected behavior**
The dates should be displayed correctly whether or not the condition is used.

**Screenshots**
I created a gif file to show the problem
  
![firefox_iZ2PsUXgLG](https://user-images.githubusercontent.com/114871390/203439921-103d7e65-57f7-4949-a58f-77e660eb6a55.gif)

**Comment by melohagan** [comment]
App export that reproduces the issue: 
[Invalid Date-export-1669203110088.tar.gz](https://github.com/Budibase/budibase/files/10075021/Invalid.Date-export-1669203110088.tar.gz)

**Comment by michal-81** [comment]
Hi @melohagan,
do you know when this bug might be resolved? 
I have tried to come up with some workaround but the problem is that when I tested it with a JavaScript expression like this  `return typeof $("Value");` the returned field value is undefined.
