### ISSUE TITLE
Update Field Value action does use the correct value

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#8776]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.31
  - App Version: 2.1.31

**Describe the bug**

**To Reproduce**
1. Create two date fields and one number field, call them Date1, Date2 and Duration
2. Create a form
3. Add a field update action to Date1 and Date2 to update Duration
```
var start = new Date($("Form.Fields.Date1"));
var end = new Date($("Form.Fields.Date2"));
var hours = Math.abs(start - end) / 36e5;

return hours
```
4. Publish the form
5. Go to the published app and change the end date
6. The duration is always wrong as it is always the previous value

**Expected behavior**
The duration field represents the current value of the two date fields

**Screenshots**
![update](https://user-images.githubusercontent.com/97764630/203449849-8de8a116-187a-4cad-9aa3-e23b9e148cdd.gif)
  
**App Export**
[UpdateFieldTest-export-1669164139247.tar.gz](https://github.com/Budibase/budibase/files/10072158/UpdateFieldTest-export-1669164139247.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 107.0.1418.52

**Additional context**

**Comment by melohagan** [comment]
Hi @FlaminWrap 

This is not a bug. You need to use the `Field value` binding to get the current binding of the field.

<img width="692" alt="Screenshot 2022-11-23 at 14 44 19" src="https://user-images.githubusercontent.com/101575380/203575434-a3d78bda-d688-4e54-9355-bb04b2919093.png">
