### ISSUE TITLE
MySQL BigInt Primary Key

### ISSUE THREAD

**Issue by andr-04** [Budibase/budibase#8781]
**Hosting**
- Self
  - Method: <method> docker single image
  - Budibase Version: <version> 2.1.28

**Describe the bug**
MySQL as a data source distorts BigInt datatype because of int53 problem of JavaScript. I've found the distortion comes from a backend (for example, https://portal/api/***/search entrypoint returns the wrong data). There are only 2 options for a column type of BigInt field: Number and Boolean.

**To Reproduce**
1. Create MySQL database.
2. Create the table for the MySQL database.
3. Create a field with the type BigInt(20).
4. Add a record with the value 12345678901234567890.
5. Create Budibase application.
6. Attach MySQL database as a datasource to the Budibase application.
7. See 12345678901234567000 instead of 12345678901234567890.

**Expected behavior**
The safest way is to use strings for BigInt values.

**Desktop:**
 - OS: macOS 13.0
 - Browser: Chrome 107.0.5304.110 (arm64)

**Comment by melohagan** [comment]
There is also this other bug to take into consideration: https://github.com/Budibase/budibase/issues/6000

Users wanted the ability to establish relationships between integer columns and big integer columns. 
If the type of big integer was treated as a string, then it may not allow you to select the columns of different types when creating the relationship.

**Comment by andr-04** [comment]
It looks like the problem with BigInt is still here. I try to use a "Repeater block" component with a filter by BigInt field and was stuck with the problem that no rows found in some cases. Is it the problem with the "Repeater block" component or with something else?

@melohagan can you check it, please?

**Comment by melohagan** [comment]
Hey @andr-04 

I've checked the latest version **v2.6.9** and I can't find any issues myself. If you can reproduce a specific problem please feel free to raise another bug issue!

**Comment by andr-04** [comment]
@melohagan, #10703. Just now I checked it on v2.6.11, and it's the same.

**Comment by melohagan** [comment]
Hey @andr-04 Could you provide the schema for your MySQL table (the CREATE SQL script) as well as a video recording demonstrating the problem please?
