### ISSUE TITLE
Authentication with AD/LDAP

### ISSUE THREAD

**Issue by useronkel** [Budibase/budibase#8782]
I am new to bb, but already do have a request ;-)
I started to build some apps (which went really easy), but get stucked when it comes to authentication to a LDAP/AD.
Am I blind or are there no simple auth mechanisms to LDAP/AD?

In many companies there is no Google accounting neither an IDMS (FreeIPA or similar) or OID.
Most companies only have some kind of Windows-$erver or a similar authentication stack with OpenLDAP.

As an enhancement request:
Using the Default BB Login with user mail and password dialog, but add an option to populate this with AD and/or LDAP logins where bb is the frontend. Some settings to access the LDAP/AD and then add listed users to bb with a simple click.
Password check and credentials against the LDAP/AD and all would be fine.
So all apps should access the bb default auth mechanism, regardless of underlying authentication to AD/LDAP.

**Comment by yuppox** [comment]
I would also like to see LDAP integration. Many people use LDAP without OpenID or Google.

**Comment by useronkel** [comment]
> Maybe run OpenID server in your LAN that checks LDAP/AD against your domain controller? Or use Azure AD. :-)

Why should I? :-)
It doesn't make any sense for a small group of people (but too much to create a login for every user) to use an OpenID-Server for authentication with bb when a ldap-Server is quite enough to handle authentication against Windows AD.
It sounds like: Create a low-code app to use with bb
Doesn't make any sense ;-)
And bb is running only inside, no public access ever allowed, no external connections. No security risks :-)
We have a bunch of other applications (self programmed), which handles it's authentication with ldap. It's a term of user experience. Too much information isn't good, keep it simple and clean :-)
It's only an enhancement request ;-)
