### ISSUE TITLE
Duplicated add binding button

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#8784]
**Hosting**

- Self
  - Method: <method>  docker compose
  - Budibase Version: <version> 2.1.31
  - App Version: <version> 
  - 
**Describe the bug**
Two buttons to add bindings are shown when creating a new query button. One of them does not do anything

**To Reproduce**
1. Go to a MySQL database in the Data Tab
2. Go to "Create Query"
3. Observe duplicated buttons 

**Expected behavior**
I expect one button to show to add bindings instead of two.

**Screenshots**
![image](https://user-images.githubusercontent.com/32724827/203552737-fe3d3483-f1c1-4546-af06-bcf4d16ed519.png)

  
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 107.0

**Additional context**
It doesn't cause any real problem. Just a weird unexpected behavior

**Comment by melohagan** [comment]
The pill shaped button also doesn't appear to do anything

**Comment by AlejandroFNadal** [comment]
I can confirm as fixed in version 2.2.1
