### ISSUE TITLE
Automation new row not triggered

### ISSUE THREAD

**Issue by RickxZen** [Budibase/budibase#8785]
**Hosting**

- Self
  - Method: docker-compose
  - Budibase Version: 2.1.31
  - App Version: 2.1.31

**Describe the bug**
Automation is not started. 

I have an automation that fires a query to an external system if a row is created in a MS SQL database:
![afbeelding](https://user-images.githubusercontent.com/48241736/203581088-ff94d2c2-cf46-471e-aa45-2744e28cb85c.png)

The App is published.

I create new rows with an insert command which has an autogenerated Id column, but the automation does not get triggered. However manually entering the data through the GUI also doesn't work/trigger the automation. The inserted row is visible in the data explorer from Budibase:
![afbeelding](https://user-images.githubusercontent.com/48241736/203583418-5ebdd741-70fe-425b-ab9a-37253036cd0d.png)
![afbeelding](https://user-images.githubusercontent.com/48241736/203583641-bd717d1b-69ef-4b66-8fb2-cc401639dba4.png)

The weird thing is that when testing the automation it works. 
![afbeelding](https://user-images.githubusercontent.com/48241736/203581996-6a5113e9-6fcb-4dcd-8eea-387a8fd1d84e.png)

However if I change the row created trigger to a Budibase DB table, it works:
![afbeelding](https://user-images.githubusercontent.com/48241736/203584535-1d42041a-826d-4246-8cb2-b74cd884eef9.png)

**To Reproduce**
1. Row gets inserted into MS SQL datasource.
2. Automation does not get triggered.

**Expected behavior**
1. Row gets inserted into MS SQL datasource.
2. Automation gets triggered.
3. Query gets executed.

**Screenshots**
See above.
  
**App Export**
There is some confidential information so if export is really needed, export can be provided after removing some information.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version 107.0

**Additional context**
Other automations do work, these are webhook triggered automations with query/create row actions. 

For some reason the create row does not get triggered.

**Comment by RickxZen** [comment]
Hi Michael thanks for your quick response. The app is published like I mentioned in the post. However your second paragraph explains it all why my automation isn’t triggered since it’s an external MS SQL database and that it does work with the Budibase DB table.Guess I thought it was possible since I could select the MS SQL table from the created row trigger.Verstuurd vanaf mijn iPhoneOp 23 nov. 2022 om 16:56 heeft Michael Drury ***@***.***> het volgende geschreven:﻿
Hi @RickxZen - your app/automation needs to be published for your automation to be triggered, if your app is only in development we don't trigger automations.
Also - it should be noted that any rows added to your MS-SQL table outside of Budibase will not trigger automations. Right now we don't have a good way to detect this for all of our external datasources, so it isn't an option.

**Comment by mike12345567** [comment]
Hi @RickxZen - no problem - sadly this is something that we can't support right now, we'll update the documentation to state that for external databases the trigger only applies when the row is created through Budibase!
