### ISSUE TITLE
Builder wiped itself when adding charts and previewing

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#879]
**Describe the bug**
I added a CSV with 1000 records. I created a view, made a calculation, and used the group feature. I then created an area chart in the design section. I used the new view as my data source. There were issues with the chart not displaying so I deleted the app, and tried again. This time, I turned off 'animate' in the chart. The chart worked wonderfully. So, I tried to preview it. I got a 404 message in the browser. I went back to the builder, refreshed, and it was frozen. So, I deleted the app. And then, when I went back to the welcome screen, I got the error: [object object] - see screenshots below. I have tried to create a new app, and the builder is asking me for my API key :-(. My other apps are gone.

**Expected behavior**
Animate should be off by default, not an option at all, or only an option for small amounts of data.
I should be able to preview the app.

**Screenshots**
![Screenshot 2020-11-25 at 10 13 45](https://user-images.githubusercontent.com/49767913/100213846-1051b980-2f07-11eb-9e5d-7738488274a1.png)
![Screenshot 2020-11-25 at 10 18 24](https://user-images.githubusercontent.com/49767913/100214246-8fdf8880-2f07-11eb-8f48-d006858279fc.png)

**Desktop (please complete the following information):**

* Mac

**Comment by shogunpurple** [comment]
Thanks @joebudi. Will look into the underlying issue that causes this.

One thing of note is when you said you lost all your apps. The problem here is that when one breaks completely, the call to get all the app information fails and you lose them all. [This PR](https://github.com/Budibase/budibase/pull/872) solves that, so that will stop you losing everything if this happened again.

**Comment by shogunpurple** [comment]
@joebudi I can no longer reproduce. Have you seen this happen again?

**Comment by joebudi** [comment]
No, it's not happened since.
