### ISSUE TITLE
Published app date is not updated

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#8792]
**Hosting**
- Self
  - Method:  docker compose in Linux Debian 11
  - Budibase Version: Version: 2.1.31

**Describe the bug**
The last published date from any app is not updated

**To Reproduce**
1. Create an app
2. Publish it
3. Wait for some time (perhaps a day)
4. Publish it again with new content
5. Check the dashboard
6. The published date still says 1 day ago

**Expected behavior**
I excpect the "Last published date" in the dashboard from an app to be updated every time an app is published

**Screenshots**
![image](https://user-images.githubusercontent.com/32724827/203750613-c52b80ca-d000-4d49-b318-00bf8593f8de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 107.0

**Additional context**
This bug was originally published at: #7613
I was asked to republish it (I was not the original published but I also have this bug) because it did not followed the expected templating.

**Comment by AlejandroFNadal** [comment]
![image](https://user-images.githubusercontent.com/32724827/203773846-f0dc188f-bc67-46f0-9b7d-d5c20c004259.png)
It is also shown incorrectly in the top right side of the designer

**Comment by AlejandroFNadal** [comment]
Writing here just to "unstale" the issue :-)

**Comment by Rory-Powell** [comment]
This will be fixed in the June release (05/07/23)
