### ISSUE TITLE
Import/Export Data: Make CSV delimiter configurable

### ISSUE THREAD

**Issue by oldwired** [Budibase/budibase#8799]
**Describe the feature request**
Please make the CSV delimiter configurable. At the moment it is always `,`, but the delimiter excel expects depends on the localization settings. For languages like german Excel expects `;` when just using the open dialog/doubleclicking it.

**Comment by melohagan** [comment]
As an additional improvement to the **Export data** action, I would like to see the column selector match the column selector from the **Data** section.

![Screenshot 2024-01-30 at 09 48 13](https://github.com/Budibase/budibase/assets/101575380/88a036ab-1000-4b39-8161-0d7f4571488f)

*This should become this:*

![Screenshot 2024-01-30 at 09 48 47](https://github.com/Budibase/budibase/assets/101575380/5e10c01b-e480-4ddf-a5c3-4875fb6d670c)

**Comment by melohagan** [comment]
https://docs.budibase.com/docs/data-actions#configure-delimiter
