### ISSUE TITLE
Export Data: Make CSV filenames less cryptic

### ISSUE THREAD

**Issue by oldwired** [Budibase/budibase#8800]
**Describe the feature request**
Please make the filename for the csv file less cryptic. At the moment a) something very cryptic, that's scaring end users and b) always the same, for the same datasource. So only the browser appends (n) when downloading.

You could either get rid of some parts and append a timestamp, or you could make it fully configurable.

**Screenshots**
<img width="310" alt="image" src="https://user-images.githubusercontent.com/9700404/203797897-cdcd97a4-1c72-4b76-8993-9520d4107d9e.png">

**Comment by aptkingston** [comment]
Exports are just called `export.csv` now. No more scared users!
