### ISSUE TITLE
Multi-select Picker: Checkbox Type: Default value does not work when values are integers. 

### ISSUE THREAD

**Issue by UweBear** [Budibase/budibase#8802]
**Hosting**
- Self
  - Method: docker compose (budi hosting)
  - Budibase Version: 2.1.31
  - App Version: 2.1.31

**Describe the bug**
I use a Multi-select Picker with a custom source define as "Mon"=1, "Tue"=2,...
The data provider pull a table from Postgesql with a field define as integer array.
As Default value I just return the array from the database. 
Works fine with the type Select:
![image](https://user-images.githubusercontent.com/118995068/203824436-1a4504e3-e848-4912-b15b-4a0878582979.png)

But does not work with type Checkboxes:
 
![image](https://user-images.githubusercontent.com/118995068/203824653-916bf617-e358-49e7-9416-55a8eeeb1230.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser safari

**Comment by melohagan** [comment]
Hey @UweBear 

This is specific to the string parsing of the default values. E.g. if you use the JavaScript binding for the default value `return [1,2]` that will work with checkboxes.

It's when you use the handlebars: `1,2` that it doesn't.

**Comment by UweBear** [comment]
My JavaScript function for the Default value is:

let days = $("Repeater.Emp_hours.days");
if (days) {
	return days;
}
return null;

I checked, "days" is an array. So I do already return an array.

**Comment by UweBear** [comment]
I found out that the issue are the custom defined data source for the selection.
I changed it to a Data Provider and it is working now.

**Comment by deanhannigan** [comment]
Hi @UweBear I've been looking into this issue and can't seem to replicate the behaviour you are seeing.

What is the explicit Postgres type of the field you are trying to work with? Also, just to confirm, did the field already exist before the database was imported? Or was this field created explicitly as a `Multi-select` in Budibase?

The default value for `Multi-select` fields can handle either strings or integers e.g. `[1,'2',3]` will be rendered by the field correctly. When the field is persisted to the DB, it will take the form of a JSON array of strings.

Would it be possible to get an export of the application?

**Comment by UweBear** [comment]
I am using a PostgreSQL integer array, data type integer[].
The filed already existed in the table when I used "Fetch tables" to pull the tables into Budibase. It gets converted into Text in Budibase.

I could try to make a mini app to show it.

**Comment by UweBear** [comment]
For now I fixed it with turning the array of integers into a array of strings at the Default value

return days.map(d => d.toString());

and turn it back into an array of integers in the save action

$("Form.Fields.formdays").map(d => parseInt(d))

**Comment by deanhannigan** [comment]
Hi @UweBear, glad you managed to find a solution that worked for you. I'm closing this issue now as your solution is the only way to approach this scenario for the moment. Any further issues, let me know.
