### ISSUE TITLE
Error toast persists

### ISSUE THREAD

**Issue by chiptech-mitchell** [Budibase/budibase#8805]
**Describe the bug**

**To Reproduce**
When creating a new data source and providing incorrect configuration settings and to save and fetch tables an error toast is shown. If you continue to hit the save and fetch tables button repeatably with still incorrect configuration settings an additional toast is displayed each time.

**Expected behavior**
Error toast is dismissed after a certain period of time.

**Screenshots**
![image](https://user-images.githubusercontent.com/109489679/203881357-a988fc56-8c10-4148-8145-cf755d70ea96.png)
  
**App Export**
This shouldn't be specific to my application

**Additional context**
I don't imagine this is specific to the create data source dialog but I haven't been able produce additional examples

**Comment by aptkingston** [comment]
Hey @chiptech-mitchell. This is by design - errors do not automatically dismiss so that you can read them and copy/paste the error text if needed. Normal notifications get automatically dismissed, just not errors.

**Comment by chiptech-mitchell** [comment]
Fair enough
