### ISSUE TITLE
User Groups Issues: Editing, Naming, Large user list

### ISSUE THREAD

**Issue by Mitch-Budibase** [Budibase/budibase#8819]
There are some issues around User Groups for having a large list of users, having groups with the same name, and group naming limitations.

**Repro steps for large list of users:**
1. Import a large list of users (100) and add them to a user group
2. Navigate to the user group and click into it
3. Scroll to the bottom of the group
**Issues from this**
- There is no pagination
- There is no filtering for finding specific users within a group
- The bottom of the screen gets cut off

**Repro steps for editing a group:**
1. Create two user groups
2. Edit the name of the user groups so they are the same
**Issues from this**
- User groups can have the same name (there should probably be a limitation to prevent groups having the same name)
- Additionally, multiple user groups can have the same colour/image (this is less important)

**Repro Steps for user group naming:**
1. Create a user group
2. Edit the name and replace with empty spacing - This is accepted but it is not possible to create a group the same way
3. Edit the name and include a large number of characters (e.g. 250)
4. Navigate to user groups page - The user groups list is skewed from view due to the long name
**Issues from this**
- It is not possible to create a list with empty space for the name, but it is possible to edit the name to only have empty spacing
- Having a user group with a long name affects the user group page and user groups sections visually. We need a max character limit. Actions on the user groups section are not possible due to a long name.

I have attached some supporting screenshots and videos

https://images.zenhubusercontent.com/190729906/4e168d02-ab6c-406d-8b53-a977b85dc8e5/screen_recording_2022_11_24_at_17_18_07.mov

![image.png](https://images.zenhubusercontent.com/60fed9d54a973614368dfdfe/33c476df-6512-407c-a4c0-a466f564e7fa)

![image.png](https://images.zenhubusercontent.com/60fed9d54a973614368dfdfe/e3bbb066-b26e-4b50-8b47-499f7969b66f)

**Comment by melohagan** [comment]
Fixed!
