### ISSUE TITLE
MySQL Fetch Tables causes error due to views

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#8840]
**Hosting**
- Self
  - Method: docker compose, 
  - Budibase Version: 2.1.38

**Describe the bug**
When trying to run the "Fetch tables" option in Budibase for a MySQL table, I get the following error:
```
Error fetching tables
No primary key constraint found for the following table: **Something**
```
The "Something" is actually the name of a view in MySQL. I am happy that Budibase considers a View as a Table, that is very useful, because it would allow me to use paging with a view. But Views do not have primary key constraints, so I am a bit lost.

**To Reproduce**
1. Create an app
2. Add a MySQL database
3. Create a Table and a View
4. Try to import

**Expected behavior**
I would expect either the View to be ignored (sad but still good I guess) or the View to be considered a table without any issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/32724827/204282365-daa04836-62a7-4200-ba33-07d3cb5a2930.png)
  
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version 107

I have found https://github.com/Budibase/budibase/discussions/3650

**Comment by melohagan** [comment]
Hey @AlejandroFNadal 

You can fetch specific tables, so you can list your tables without importing the views.

![Screenshot 2022-11-28 at 13 45 46](https://user-images.githubusercontent.com/101575380/204292937-f57f110f-567f-4c06-bb0c-c311db302af3.png)

Press **Skip table fetch**

Then click **Fetch** under the datasource config and type in your table names that you want to import.

![Screenshot 2022-11-28 at 13 46 16](https://user-images.githubusercontent.com/101575380/204293056-0e2680bf-24cb-4846-9aea-ed6da2aaf827.png)

External DB views are currently not supported: https://github.com/Budibase/budibase/issues/6216
I'm going to close this issue as a duplicate.

**Comment by AlejandroFNadal** [comment]
Sorry for the duplicate, my bad
