### ISSUE TITLE
Backup with CLI cannot access to CouchDB

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#8854]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.38

**Describe the bug**
While attempting to run the backup using:
`sudo budi backup --export testfile --env .env_backup`

I get the following error:

`Error - FetchError: request to http://admin:8pNy63cIrIbiq1LnI9EWWfrPGOm3WvnM@localhost/db/_all_dbs failed, reason: connect ECONNREFUSED ::1:80`

The .env_backup is the following:
(I am not showing here the real passwords, of course)
```
COUCH_DB_URL=http://admin:passcouch@localhost/db/
MINIO_URL=http://localhost:4004
MAIN_PORT=80
MINIO_ACCESS_KEY=accesskeyminio
MINIO_SECRET_KEY=secretkeyminio
```
The docker-compose.yaml is the following:
```version: "3"

# optional ports are specified throughout for more advanced use cases.

services:
  app-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/apps
    container_name: bbapps
    environment:
      SELF_HOSTED: 1
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      WORKER_URL: http://worker-service:4003
      MINIO_URL: http://minio-service:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      BUDIBASE_ENVIRONMENT: ${BUDIBASE_ENVIRONMENT}
      PORT: 4002
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      ENABLE_ANALYTICS: "true"
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BB_ADMIN_USER_EMAIL: ${BB_ADMIN_USER_EMAIL}
      BB_ADMIN_USER_PASSWORD: ${BB_ADMIN_USER_PASSWORD}
      PLUGINS_DIR: ${PLUGINS_DIR}
    depends_on:
      - worker-service
      - redis-service
#    volumes:
#      - /some/path/to/plugins:/plugins

  worker-service:
    restart: unless-stopped
    image: budibase.docker.scarf.sh/budibase/worker
    container_name: bbworker
    environment:
      SELF_HOSTED: 1
      PORT: 4003
      CLUSTER_PORT: ${MAIN_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_URL: http://minio-service:9000
      APPS_URL: http://app-service:4002
      COUCH_DB_USERNAME: ${COUCH_DB_USER}
      COUCH_DB_PASSWORD: ${COUCH_DB_PASSWORD}
      COUCH_DB_URL: http://${COUCH_DB_USER}:${COUCH_DB_PASSWORD}@couchdb-service:5984
      SENTRY_DSN: https://a34ae347621946bf8acded18e5b7d4b8@o420233.ingest.sentry.io/5338131
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_URL: redis-service:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-service
      - minio-service
      - couch-init

  minio-service:
    restart: unless-stopped
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER: "off"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  proxy-service:
    restart: unless-stopped
    ports:
      - "${MAIN_PORT}:10000"
    container_name: bbproxy
    image: budibase/proxy
    environment:
      - PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND=10
      - PROXY_RATE_LIMIT_API_PER_SECOND=20
    depends_on:
      - minio-service
      - worker-service
      - app-service
      - couchdb-service

  couchdb-service:
    restart: unless-stopped
    image: ibmcom/couchdb3
    ports:
      - "${COUCH_DB_PORT}:5984"
    environment:
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
      - COUCHDB_USER=${COUCH_DB_USER}
    volumes:
      - couchdb3_data:/opt/couchdb/data

  couch-init:
    image: curlimages/curl
    environment:
      PUT_CALL: "curl -u ${COUCH_DB_USER}:${COUCH_DB_PASSWORD} -X PUT couchdb-service:5984"
    depends_on:
      - couchdb-service
    command: ["sh","-c","sleep 10 && $${PUT_CALL}/_users && $${PUT_CALL}/_replicator; fg;"]

  redis-service:
    restart: unless-stopped
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  watchtower-service:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update bbapps bbworker bbproxy
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=budibase
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  couchdb3_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
```

**To Reproduce**
Attempt to generate a backup with the cli

**Expected behavior**
Expect backup to run

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 107

**Additional context**

I have attempted to access the CouchDB over the browser and it works with the user and password. If I try to access directly over the browser to localhost/db/_all_dbs I get an error message saying: you are not a server admin, but that makes sense, as I am not logged in. If I log in first and then attempt that, then it works.

I also don't know why the .env file autogenerated by the cli tool has one port for COUCH_DB (4004) and then it uses 5984 directly in some parts of the docker-compose. I guess one port is to communicate between dockers and the other is the actual port that will be accessible from outside the set of dockers, but I am not sure of this. I have attempted to change these values for them to be the same, without luck.

I have also attempted to change the proxy service port to 80 (the main service is running in port 80), as by default it is 10000. This causes the system to not work. I did this because by default budibase works in port 10000.

I hope someone can orient me on what is going on, I am at a bit of a loss at this moment.

**Comment by mike12345567** [comment]
Hi @AlejandroFNadal can you try updating the `COUCH_DB_URL` in your `.env` file to be `http://user:pass@localhost:<COUCH_DB_PORT>` rather than using the proxy? See if that works going directly to CouchDB using the exposed port.

**Comment by AlejandroFNadal** [comment]
An extra thing that might result useful:

For some reason, the port 39739 is open:
```PORT      STATE SERVICE
22/tcp    open  ssh
53/tcp    open  domain
80/tcp    open  http
4005/tcp  open  pxc-pin
39739/tcp open  unknown```

```sudo lsof -i -P -n | grep 39739
container   443    root   13u  IPv4  12710      0t0  TCP 127.0.0.1:39739 (LISTEN)```

Is this normal? I have tried to set up that port as well in the couchdb url but it also doesnt work.

**Comment by mike12345567** [comment]
Hi @AlejandroFNadal - just to confirm, on all of those ports you are able to access the DB through Fauxton in the browser? Via `http://localhost:<port>/_utils/#`.

You do not want to remove the proxy service, but using a port assigned directly to the CouchDB service allows the CLI to directly communicate - but this doesn't appear to be the issue.

What version of the CLI are you using also? This could be an issue with an older version of the CLI perhaps.

The source code for the CLI can be found here: https://github.com/Budibase/budibase/tree/develop/packages/cli

The ephemeral port `39739` being open is fine, that is likely used by the MinIO browser.

**Comment by AlejandroFNadal** [comment]
Thanks for your fast reply :-D
> Hi @AlejandroFNadal - just to confirm, on all of those ports you are able to access the DB through Fauxton in the browser? Via `http://localhost:<port>/_utils/#`.

The only one of those that triggers a login is localhost:4005/_utils. The others give me an "Access denied" or "Unable to connect"
> 
> You do not want to remove the proxy service, but using a port assigned directly to the CouchDB service allows the CLI to directly communicate - but this doesn't appear to be the issue.
> 
> What version of the CLI are you using also? This could be an issue with an older version of the CLI perhaps.

My version of the CLI is 2.1.38
> The source code for the CLI can be found here: https://github.com/Budibase/budibase/tree/develop/packages/cli

Thanks <3
> The ephemeral port `39739` being open is fine, that is likely used by the MinIO browser.

Oh, okay, that is good to know

**Comment by mike12345567** [comment]
Hi @AlejandroFNadal - based on that information, I would assume that utilising a `.env` file with the CLI like:
```
COUCH_DB_URL=http://<USER>:<PASSWORD>@localhost:4005
MINIO_URL=http://localhost:4004
MAIN_PORT=80
MINIO_ACCESS_KEY=accesskeyminio
MINIO_SECRET_KEY=secretkeyminio
```

should work - what response do you get from doing this? If you're able to login to Fauxton on `localhost:4005/_utils` then Budi CLI should be able to access it with the same credentials.

**Comment by AlejandroFNadal** [comment]
Hi @mike12345567 , the response I get from that is:

`Error - FetchError: request to http://<USER>:<PASSWORD>@localhost:4005/_all_dbs failed, reason: connect ECONNREFUSED ::1:4005`

where <USER> and <PASSWORD> are the values that do work over Fauxton. I am running the command locally, could this be a firewall issue even if it is in localhost?

I have run a nmap check from another server to the server where budibase is running, and it reports the following:

PORT     STATE SERVICE
4005/tcp open  pxc-pin

I havent been able to find what pxc-pin is, but it is in the IANA list of what this port usually is.

Any ideas on how to continue my search on this topic?

**Comment by mike12345567** [comment]
At this point I am unsure how to continue looking into this, if a curl works to the URL `http://<USER>:<PASSWORD>@localhost:4005/_all_dbs` but the CLI fails, there must be some sort of network issue - perhaps you could try replacing `localhost` with say `127.0.0.1` - maybe its a resolution issue with curl isn't experiencing?

**Comment by AlejandroFNadal** [comment]
@mike12345567 thanks a lot, replacing localhost with 127.0.0.1 worked
I started trying with an empty node console, using node-fetch as the cli uses, and it works with 127.0.0.1 and it doesnt with localhost, so I guess it cannot resolve localhost :(

Perhaps this would be a neat addition to the backup guide, something like " if you are having this problem, try using..." . But maybe it is quite obvious and I just didn't think of trying it out.

Sadly, the backup still doesnt run completely. It fails on the Minio/S3 part. I have changed localhost to 127.0.0.1 in the MINIO_URL, with no success. 

An interesting detail that I have just tried out: pinging localhost in the server, sends the pings to :::1 instead of using 127.0.0.1 . From what I gather, :::1 is the IPv6 equivalent of 127.0.0.1

About the multiple interfaces, not really. It has a loopback interface, a ethernet interface, and then all others created by the dockers of the docker-compose. We are not running anything else in this server, just budibase. The databases (not the budibase ones, but the ones that contain the data we manage with budibase) are run in a different server. 

I will try to solve by myself the Minio part and if I have no results, I might write here again to ask for help.
Thanks a lot, once again, for your help so far

**Comment by mike12345567** [comment]
Ah - interesting, this sounds to me like an issue with IPv6 in that case - I'll have a play around and see if I can re-create in an IPv6 environment - if I can I'll create a specific issue targeting that as its likely to affect more in the CLI than just the backup process.

It sounds to me like a general IPv6 issue - the MinIO issue is likely cropping up from it as well - it should be accessible via the proxy - its possible the proxy isn't working exactly as expected - docker-compose and its host bindings can be a little funny in IPv6 environments.

I'll close out this issue for now - as in general IPv6 support is spotty across some of the tools Budibase utilises, I'll see if there are any specific issues that can be raised on the back of that.

**Comment by AlejandroFNadal** [comment]
@mike12345567 Hey Mike, how are you doing?
Regarding this problem, every time I run an update of budibase, the docker-compose.yaml gets broken again and I cannot run updates :-(

**Comment by mike12345567** [comment]
Hi @AlejandroFNadal - the update will replace the `docker-compose.yaml` - but your CLI version may be out of date, it may be updating it with an older version of the `docker-compose.yaml` - you can run `budi --version` to find out your CLI version (if no version is shown it is a very old version).

If there is an issue with the latest version of the CLI I would suggest opening an issue with specific instructions about what is occurring, e.g. if you've made any changes to your `docker-compose.yaml` and what the state is before and after (hiding any secrets).
