### ISSUE TITLE
BigInt interpretation problem

### ISSUE THREAD

**Issue by andr-04** [Budibase/budibase#8872]
**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.1.28

**Describe the bug**
All numbers are processed with `parseFloat` which is not safe for big integers (greater than int53). Big Integers should be left as strings. To determine does the number is big or not `Number.isSafeInteger` should be used.

**Comment by melohagan** [comment]
It does seem to be the case looking here: https://github.com/Budibase/budibase/blob/178fd100af09ac1bc8b8395db52c629c572dc4bb/packages/server/src/integrations/utils.ts

It should be a matter of moving `bigint: FieldTypes.NUMBER,` into the **SQL_STRING_TYPE_MAP** and changing the type to string.

That may also fix the other bug you raised: https://github.com/Budibase/budibase/issues/8781

Going to close this one as a duplicate, as I believe they can be done together.
