### ISSUE TITLE
Refactor data section routing

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#8878]
In order to finish work on the command palette feature, we first need to refactor the data section to properly sync the URL with state. This has been done in the design section already by way of a new `syncURLToState` helper.

**Comment by melohagan** [comment]
Just to add to this one, I pulled down the data-routing-refactor branch, but I'm still seeing a little issue; not sure if it is related or not.

1. Click on design tab
2. Add component -> Container
3. Click on the data tab
4. See that it does not navigate to data.
5. Click on design and back to data to get it to navigate.

![tabs_bug](https://user-images.githubusercontent.com/101575380/212673932-275dfb9f-ca9e-4256-a7c0-58c06896e88f.gif)
