### ISSUE TITLE
Portal redesign

### ISSUE THREAD

**Issue by aptkingston** [Budibase/budibase#8879]
There wasn't an existing issue for this so thought I should create one. We're hopefully going to implement this in December, or at least finish it the current implementation and gather more feedback

Link to new designs:
https://www.figma.com/file/T57nnTekuyKgZhxdBCbgGM/Portal-re-design?node-id=0%3A1

This is probably over 50% completed on a lab day branch of mine already (`cheeks-lab-day-portal-redesign`).

**Comment by MihailHadzhiev2022** [comment]
![Screenshot 2023-01-19 at 11.46.18.png](https://images.zenhubusercontent.com/623866329f3f8e7223d95e00/288ff699-59bc-4063-8b61-ebda05b35b60)
