### ISSUE TITLE
Data provider with a form relationship as a source does not work

### ISSUE THREAD

**Issue by phaethon** [Budibase/budibase#8910]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.42
  - App Version: 2.1.42

**Describe the bug**
Using Form relationships as a datasource for a Data Provider results in spinning wheel and does not load relationships.
This is for both the internal Budibase DB and external SQL DBs.

**To Reproduce**
1. Create a table with a relationship
2. Create the auto-generated screens
3. In the edit details `/:id` screen, add a Data Provider nested inside the Form.
4. Set the new Data Providers datasource to: `Form.Fields.<Relationship-Field-Name>`
5. See that the relational data does not load, and a permanent spinner appears.

**Expected behavior**
I should not be able to select a Form relationship field as a datasource.

**Screenshots**
![Screenshot 2022-12-07 at 10 43 38](https://user-images.githubusercontent.com/101575380/206158258-9703a441-5427-4e44-939e-22b6e06343ab.png)

**App Export**
[Form Relationships-export-1670409500798.tar.gz](https://github.com/Budibase/budibase/files/10175226/Form.Relationships-export-1670409500798.tar.gz)

**Additional context**
In a recent bit of work I did, I had filtered out the form relationship options. It may be a matter of doing the same for the main `DataSourceSelect`: https://github.com/Budibase/budibase/pull/8897
```js
$: links = bindings
    .filter(x => x.fieldSchema?.type === "link" && x.category === "Repeater")
```

**Comment by phaethon** [comment]
![image](https://user-images.githubusercontent.com/1088890/205318742-aa3b4d4e-71c3-41ac-80b6-26c78a3074c2.png)

**Comment by phaethon** [comment]
![image](https://user-images.githubusercontent.com/1088890/205318902-d4864411-fca3-41b1-b259-738a6360a494.png)

**Comment by melohagan** [comment]
> I cannot use filter by _id as the database is PosgreSQL and _id field is not available in filter.

You would just replace **_id** with the primary key field instead.

**Comment by phaethon** [comment]
This issue primarily is about form with relationship as a data source. Currently, it seems to be a bug that I can choose it as a data source for data provider, but neither component is drawn, nor any error is shown. If it is not possible to use form with relationship directly as data source, then why is it shown in the list of data sources? If you cannot recreate "rotation circle" from my description, I can send an export of application.

And, yes, I have, also, tried to recreate Owners/Pets/Appointments example. No, it does not work for me as described (I did fix error on data provider replacing null with id in Owners provider data filter, which is not covered by documentation). If you have a demo app that I could import and see how it works, I would be grateful.

**Comment by melohagan** [comment]
Hey @phaethon 

Thanks for the extra info, I was able to reproduce the issue. I have updated your OP to include the reproduction steps, screenshots, app exports, etc.
In future could you please do this as it makes it a lot easier for the dev team to understand and fix the bug, and bug reports that do not follow the template may be closed.
