### ISSUE TITLE
Why has MARGIN/PADDING fixed values?

### ISSUE THREAD

**Issue by UweBear** [Budibase/budibase#8925]
**Describe the feature request**
I want to be able to enter any value for the MARGIN input at all components.

**Screenshots**
![image](https://user-images.githubusercontent.com/118995068/205498613-be423173-95f1-4455-8fae-24480fcc9158.png)

**Comment by aptkingston** [comment]
Hey @UweBear. These are sensible presets to make it easy to keep consistency across your app. If you want custom values, you can always use custom CSS to enter any margin/padding values you want.

**Comment by UweBear** [comment]
Thank you @aptkingston for the explanation and hint.
