### ISSUE TITLE
Invalid date using handlebars for column format in data table on iPhone

### ISSUE THREAD

**Issue by phaethon** [Budibase/budibase#8929]
Using budibase 2.1.28 on Google Cloud Run with PostgreSQL as data source.

I have a table with datetime column (timestamp column in the database) and a screen with data provider and table. For formatting of the date value I used handlebars `{{ date value 'DD/MM/YYYY' }}` under Configure columns for specific column. It does work correctly on my computer and on Android phone. On iPhone (both Chrome and Safari browsers) column becomes 'Invalid Date'.

Expected: Handlebars for date formatting should work on iPhone.

**Comment by melohagan** [comment]
Hey @phaethon 

What is the locale of your iPhone? Is it different to that of your computer and Android phone?

**Comment by phaethon** [comment]
iPhone (the one showing Invalid date) has Region: Germany, English as interface language.
Trying to set various regional settings for Win10 (including Germany, Latvia, US) - it was working correctly.

Workaround, which works on all platforms, was to use Javascript instead of handlebars:
```
let d = $("Value").toString();
return d.slice(8,10) + '/' + d.slice(5,7) + '/' + d.slice(0,4);
```

**Comment by melohagan** [comment]
Thanks @phaethon that extra info is useful.

**Comment by melohagan** [comment]
Hey @phaethon 

Can you please provide the version of iOS that you are using, screenshots, and ideally an app export.

I've just tested on an iOS 16 simulator and see no issues:
![Screenshot 2022-12-06 at 15 24 35](https://user-images.githubusercontent.com/101575380/205952713-3debe16b-dbf9-41aa-9980-7fdd8746d9ab.png)

**Comment by phaethon** [comment]
iPhone SE, iOS 15.5. Cannot immediately access to create a screenshot, but generally instead of date it says "Invalid date"

**Comment by phaethon** [comment]
In case it may make a difference - underlying database field is timestamp without time zone.
