### ISSUE TITLE
Add external datasource CockroachDB serverless

### ISSUE THREAD

**Issue by s1223** [Budibase/budibase#8938]
https://www.cockroachlabs.com/

**Comment by vincenewton** [comment]
I am fully supportive of CockroachDB's serverless database. It has the potential to greatly improve our database management and cost effectiveness.

**Comment by braydennjinu** [comment]
The idea of using CockroachDB as a serverless database is excellent and I support it wholeheartedly.

**Comment by hazzenut23** [comment]
CockroachDB is a great choice as a serverless database, I fully endorse this idea.

**Comment by Rory-Powell** [comment]
Have you tried using the postgres connector for cockroach? The documentation states it is compliant. Alternatively you can have a look at using a custom datasource plugin https://docs.budibase.com/docs/custom-datasource
