### ISSUE TITLE
Enforce `illegalChildren` for apps + component error highlighting

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#8941]
We previously merged a PR that enforced which components can be added as children of others. We want to prevent the validation from occurring on old apps, but enforce it for new apps.

**COS**
- Only enforce nesting/children rules in all applications
- Highlight components that are nested illegally
- Allow users to delete them
- Prevent the bricking of apps with broken nesting

**Comment by ConorWebb96** [comment]
Closing as this was fixed a while ago.
