### ISSUE TITLE
Components: Cannot Edit Component Name

### ISSUE THREAD

**Issue by Mitch-Budibase** [Budibase/budibase#8946]
There is a problem with changing the name of a component after adding it

Reproduction steps:
1. Create app
2. Add any component to a screen
3. Attempt to change the name of the component - Error occurs
4. Repeat above steps for several other components - Error occurs for each component name change

The error is :

> Error updating component prop

Here is a screenshot showing the error:
![Screenshot 2022-12-06 at 12.44.25.png](https://images.zenhubusercontent.com/60fed9d54a973614368dfdfe/e0f8f68f-ac01-45a0-81b2-8f18d27af799)

Here is a loom video for additional context:
https://www.loom.com/share/5cf1448de8604dcd9373338688f8575a

**Comment by aptkingston** [comment]
This sometimes happen when you get into a bad state, and then it happens continuously - but if you refresh it will be gone.
