### ISSUE TITLE
Table Filtering Issues

### ISSUE THREAD

**Issue by Mitch-Budibase** [Budibase/budibase#8947]
There are a few issues associated with internal table filtering:
1. More than
2. Less than
3. Match any of the following filters

Repro steps:
1. Create app
2. Add table
3. Populate table (e.g. Dogs, with name, age, and breed)
4. Add More than filter to the table for age
**- The selected number is included in the more than filter**
**- e.g. If i select more than age of 5, dogs with an age of 5 still appear**
5. Remove previous filter
6. Add less than filter
**- The selected number is included in the less than filter**
**- e.g. If i select less than age of 5, dogs with an age of 5 still appear**
7. Add another filtering (2 total)
8. Set behaviour to 'Match any of the following filters'
9. Save and review filtered table - **The filter has not worked correctly, not all results are shown**
10. Click filter option to open modal - **The behaviour option has changed to 'Match all of the following filters'**

**Comment by aptkingston** [comment]
In terms of less than and more than - this is correct. The actual behaviour is "more than or equal to" and "less than or equal to". We can update the labels, but can't update the functionality.

As for the match any - I believe that doesn't work at all in the data section like you've noticed, so I think we just need to remove that as an option.

**Comment by Mitch-Budibase** [comment]
Thanks for looking into this Cheeks! I'd say it would be worthwhile to update the labels for the more than and less than options, just to remove any potential confusion.
