### ISSUE TITLE
Very long screen names cause side panel to be unaccessible

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8950]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.42
  - App Version: 2.1.42

**Describe the bug**
Given a very long screen name (which could occur if using a lot of URL variables for example), the screen details panel is not visible - it is pushed out of sight!

**To Reproduce**
1. Add a screen with a very long name
2. See that you cannot edit screen details - importantly you can't shorten the name!

**Expected behavior**
If a screen name is too long, it should use an ellipsis and a max width.

**Screenshots**
![Screenshot 2022-12-06 at 14 32 11](https://user-images.githubusercontent.com/101575380/205939574-18d99c23-3dee-419d-8b4a-5c918f4cb295.png)

**Comment by shogunpurple** [comment]
Nope all good, I’d only started it!
