### ISSUE TITLE
Budibase DB View Filtering Problem with Multiselect Column Type

### ISSUE THREAD

**Issue by punkshift** [Budibase/budibase#8964]
- Cloud
  - Tenant ID: dakidlat

**Describe the bug**
The wanted filter doesn't work. Filter is Where ORDER TYPE Is Equal Samples

**To Reproduce**
1. Click Create View from Budibase DB.
2. Click Filter.
3. Set filter to ORDER TYPE, Equals, Samples (or anything)
4. Click Save
5. No result

**Expected behavior**
Result should show entries with the correct Order Type.

**Screenshots**
![image](https://user-images.githubusercontent.com/120009866/206142255-07b6c5b6-1640-4aef-b3bc-24e13414cb47.png)
![image](https://user-images.githubusercontent.com/120009866/206142316-a4055968-98ce-40ec-a6e2-ec1228a5d202.png)

  
**App Export**
[PhoebeCakes-export-1670405747218.tar.gz](https://github.com/Budibase/budibase/files/10174717/PhoebeCakes-export-1670405747218.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version 1.46.134 Chromium 108.0.5359.94

**Additional context**

**Comment by aptkingston** [comment]
We're doing a large update to views and this work will be included as part of that.
