### ISSUE TITLE
S3 File Upload with public access

### ISSUE THREAD

**Issue by czarnndz** [Budibase/budibase#8975]
**Describe the feature request**
Hi, I'm doing a public form where public user can upload their resume, but I'm can not figure out how can I set the S3 File Upload component as public, because right now I'm getting "Error uploading file: Session not authenticated" when the component try to upload to S3 bucket.

**Screenshots**

![image](https://user-images.githubusercontent.com/7936586/206307271-54bf20bc-d504-45d8-8a39-3972bea10828.png)

The DS don't have a section to allow write action as public
![image](https://user-images.githubusercontent.com/7936586/206307474-05f6e1f9-e59a-49fd-a816-baf6955c15cd.png)

Thanks and regards

**Comment by rohangaikwad** [comment]
Facing the same issue. Any solution to this problem?

**Comment by jasonford1** [comment]
I am facing the same issue. Any ideas?
![Screenshot 2023-09-26 at 1 18 21 PM](https://github.com/Budibase/budibase/assets/41327322/c413a298-ce5e-4387-aa35-f51da51740f1)

**Comment by jasonford1** [comment]
We also want to use Budibase for when customers need to take a photo of any damage or broken aspects of their bike that they would like a service quote on. S3 public upload is critical for that functionality and without it we are dead in the water and I will need to look at moving to a different platform.

**Comment by melohagan** [comment]
Hey @jasonford1 @czarnndz 

While we could open up the S3 Upload to public sessions, there is a security concern for our users as a whole. 

Ideally we want users to be authenticated before uploading files to S3 buckets, therefore I'm going to close this issue.
