### ISSUE TITLE
MySQL relationships should have a dropdown to choose the column to show

### ISSUE THREAD

**Issue by froster12** [Budibase/budibase#8984]
**Describe the feature request**
Budibase does not reliably show the expected data in relationships with a MySQL database. I have had a lot of trouble trying to get it to work and this makes the relationships useless. I also don't think the _From table column_ field is necessary.

What the system really needs is the simple ability to choose which column to show in the relationship. The screenshot shows an example where I have a table of `courses` and `signups`. Each course has a `title`, `id`, and other columns. Each signup row has a reference to the appropriate course using `course_id`. For the new column in `signups`, I want to show the `title` of the course.

**Screenshots**
![example](https://user-images.githubusercontent.com/120126599/206536076-d0351452-cf85-4eb3-aa08-3936b55e4937.png)

**Comment by melohagan** [comment]
Hey @froster12 

I think you may mis-understand how display columns work. 

The `To table column` is the name of the relationship column, but you can choose any other column as the display value for the relationship:
https://docs.budibase.com/docs/budibasedb#selecting-the-display-column

**Comment by froster12** [comment]
Thank you @melohagan .

That option is not easy to find but I see it now.
