### ISSUE TITLE
All ids - replace with folder list items

### ISSUE THREAD

**Issue by ghost** [Budibase/budibase#9]
Currently, we keep a record of all available records in a collection, in an "allids" file. This is just a list of all record ids in that collection (which can be sharded).

Since implementing this, I had to add a `datastore.getFolderContents(path)` method - which lists all items in a "folder". 

We should now get rid of the "allids" mechanism. 

Instead, we should be able to recursively call `getFolderContents` to iterate through all records.

No public api should change. So, all tests should still pass, except ones that refer to the "allids" files (or shard files) directly.

This new method should respect all existing sharding rules.

**Comment by mjashanks** [comment]
https://github.com/Budibase/budibase/commit/8d438082e32a154e2db9912a807d4cdb1e3729ff
