### ISSUE TITLE
Improve error messages when failing to import plugins

### ISSUE THREAD

**Issue by antonioleo89** [Budibase/budibase#9008]
**Hosting**

- Self
  - Method: <method> docker compose with budibase cli
  - Budibase Version: 2.1.42
  - App Version: N/A

**Describe the bug**
Useless error when trying to install a custom plugin

**To Reproduce**
1. Go to Plugins
2. Upload a custom plugin
3. See error

**Expected behavior**
A clear error of the plugin to help the dev to troubleshoot.

**Screenshots**
<img width="745" alt="image" src="https://user-images.githubusercontent.com/17302331/206916743-d077ea02-3efa-4c26-9123-f2d2305b17f9.png">
  
**App Export**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Chrome
 - Version: 108

**Additional context**
The BE error on the container is the following:
```
2022-12-11 17:43:07 Trace: BadRequestError: Failed to import plugin: JS invalid: Cannot read property 'indexOf' of undefined
2022-12-11 17:43:07     at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
2022-12-11 17:43:07     at /app/dist/api/controllers/plugin/index.js:59:22
2022-12-11 17:43:07     at Generator.throw (<anonymous>)
2022-12-11 17:43:07     at rejected (/app/dist/api/controllers/plugin/index.js:6:65)
2022-12-11 17:43:07     at runMicrotasks (<anonymous>)
2022-12-11 17:43:07     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-12-11 17:43:07     at /app/dist/api/index.js:74:21
2022-12-11 17:43:07     at Generator.throw (<anonymous>)
2022-12-11 17:43:07     at rejected (/app/dist/api/index.js:6:65)
2022-12-11 17:43:07     at runMicrotasks (<anonymous>)
2022-12-11 17:43:07     at processTicksAndRejections (internal/process/task_queues.js:95:5)`
```

**Comment by antonioleo89** [comment]
Hi @aptkingston  thanks for the feedback. The fact is that my JS code is fine. I think is a matter of module installation since I am trying to create a IBM DB2 connector. Without importing the db2 object the installation seems fine.

```
import { IntegrationBase, SqlQuery } from "@budibase/types"

// @ts-ignore
import ibmdb from "ibm_db2" // this object is breaking the installation

interface Db2Config {
  host: string
  port: number
  user: string
  password: string
  database: string
}

class CustomIntegration implements IntegrationBase {
  private readonly config: Db2Config
  private readonly db: any

  constructor(config: Db2Config) {
    this.config = config
    this.db = ibmdb.open( 'DATABASE=' + this.config.database + 
    ';HOSTNAME=' + this.config.host +
    ';UID=' + this.config.user + 
    ';PWD=' + this.config.password+ 
    ';PORT=' + this.config.port + 
    ';PROTOCOL=TCPIP');
  }

  async create(query: { collection: string, body: string }) {
    return await this.db.create(query.collection, JSON.parse(query.body))
  }

  async read(query: { collection: string }) {
    return await this.db.select(query.collection)
  }
  async update(query: { collection: string, body: string }) {
    return await this.db.update(query.collection, JSON.parse(query.body))
  }

  async change(query: { collection: string, body: string }) {
    return await this.db.change(query.collection, JSON.parse(query.body))
  }

  async modify(query: { collection: string, body: string }) {
    return await this.db.modify(query.collection, JSON.parse(query.body))
  }

  async delete(query: { collection: string }) {
    return await this.db.delete(query.collection)
  }

  async advancedQuery(query: SqlQuery) {
    //return await this.db.query(query.sql)
    return await this.db.then(
      (connection: any) => {
          connection.beginTransaction(function (err: any) {
              connection.query(query.sql).then( (data: any) => {
                return data;
              })
          })        
      }, (err: any) => {
          console.log(err)
      }
    );
  }
}

export default CustomIntegration
```

**Comment by aptkingston** [comment]
Hey @antonioleo89. From having a quick look at that package I think I can see why - we unfortunately can't support plugins that depend on binaries. `ibm_db2` appears to depend on binaries which are pulled down upon installation, but we're unable to bundle binaries into our JS.

If there was an easy way to detect this then that would be a nice enhancement, so that we could at least provide a useful warning saying that a certain dependency can't be used.

**Comment by antonioleo89** [comment]
Hi @aptkingston, thanks for the feedback. If not through plugins, is it possible to create a new datasource using modules needing binaries customising the core? Or I can give up on having Db2 working with budibase?

**Comment by aptkingston** [comment]
You could certainly use it by forking the repo and adding it as a regular datasource! By doing that you can install whatever packages you need as normal. You could even upstream it as a PR if you felt inclined - we've accepted community contributions for datasources before (ArrangoDB comes to mind).
