### ISSUE TITLE
couch returned 400 - users table

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#9029]
### Discussed in https://github.com/Budibase/budibase/discussions/9016

<div type='discussions-op-text'>

<sup>Originally posted by **applicationuser** December 12, 2022</sup>
Hi,

Error when navigating screen in published app and table design access.

Table page not showing data rows.  Table has data before publishing app and new rows added in published app.

Budibase Cloud
App Version : 2.2.1

published app error on navigated to screen
![image](https://user-images.githubusercontent.com/42922833/207116729-fc9f3d0d-b62f-4307-ae46-8efeece61e8d.png)

![image](https://user-images.githubusercontent.com/42922833/207116775-b2f4641e-fa1a-4cda-83be-ab5b72e356f6.png)

Error when table accessed
![image](https://user-images.githubusercontent.com/42922833/207118336-9797cdda-92e1-4ba1-85f1-ad8cf872ce81.png)

</div>

**Comment by mike12345567** [comment]
Hi @andyburgessmd - would it be possible for you to provide an export of an app which is exhibiting this behaviour?

**Comment by andyburgessmd** [comment]
@mike12345567 I've just emailed it to you using the address from your github profile. Hope that's ok?

**Comment by shogunpurple** [comment]
Hi folks - the latest change has now been deployed to budibase cloud and self host. We will close the issue out here if everyone is back up and running. Apologies for the service interruption.
