### ISSUE TITLE
Time data type returns "Invalid time value" on Postgres

### ISSUE THREAD

**Issue by windowsdeveloperwannabe** [Budibase/budibase#9050]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.3
  - App Version: -
- Cloud
  - Tenant ID: -

**Describe the bug**
Trying to view a table that uses a `time` data type column and a row using the column returns error "Invalid time value".

**To Reproduce**
- Create table using `time` or `timetz` data type
```
CREATE TABLE time_test_table (
	id INT PRIMARY KEY,
	daily_at TIME
);

INSERT INTO time_test_table (id, daily_at) VALUES (1, '13:55');

CREATE TABLE timetz_test_table (
	id INT PRIMARY KEY,
	daily_at TIMETZ
);

INSERT INTO timetz_test_table (id, daily_at) VALUES (1, '13:55');
```
- In Budibase add data provider for Postgres
- Try to view the table

**Expected behavior**
Displaying the table without error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 108

**Comment by melohagan** [comment]
Hey @windowsdeveloperwannabe 

Thanks for raising this. If you edit the columns and tick `Ignore time zones` and refresh the page, then that will sort it.

With that said, it would be nice if we were able to check on table fetch if this should be checked by default when there's no timezone present.

![Screenshot 2022-12-15 at 16 18 52](https://user-images.githubusercontent.com/101575380/207912884-bbe91cd1-7b76-4209-bdaf-8210ca49af18.png)

![Screenshot 2022-12-15 at 16 19 08](https://user-images.githubusercontent.com/101575380/207912937-eef63d91-f0cb-4107-a43b-b2a14ca17e47.png)

**Comment by xtrojak** [comment]
@melohagan I'm having the same problem.
I have basically the same setup, expect running version `2.13.10` on MacOS.

However, when I try to display the table containing column with type `time [ without time zone ]` (as described [here](https://www.postgresql.org/docs/current/datatype-datetime.html)) it does not even show me the column names, so I can't really apply the approach you proposed. Any other workarounds?

![image](https://github.com/Budibase/budibase/assets/15349569/40256918-27fa-415c-a203-dffb1d83f3d9)

**Comment by Shadowfita** [comment]
I am getting this error message when trying to import a csv file into a budibase db table with ISO timestamps.

**Comment by melohagan** [comment]
Hey @Shadowfita 

Could you provide the CSV with some sample data that doesn't work and I can try to reproduce

**Comment by Shadowfita** [comment]
@melohagan  I've just realised I was running a fairly old version of budibase. I think it's safe to assume this isn't an issue anymore. I will confirm later today.

**Comment by Shadowfita** [comment]
@melohagan Scratch that, now trying to import REST query results into table, date string is: 20221201T080000Z, getting "Must be a valid date". I've also tried importing csv with similar datetimes into a table on the latest budibase version and it's unable to validate the column.

![image](https://github.com/Budibase/budibase/assets/11067520/a9cf2b0d-d506-4bb5-8506-a00c230b152c)

![image](https://github.com/Budibase/budibase/assets/11067520/0770c4e8-d864-42eb-b22b-685bc42f4ad3)

**Comment by Shadowfita** [comment]
Hey @melohagan , apologies, there are no line breaks, just a formatting issue I had with the code block.

**Comment by melohagan** [comment]
Hey @Shadowfita 

Not seeing this issue with the data provided:

![Screenshot 2023-12-01 at 09 14 02](https://github.com/Budibase/budibase/assets/101575380/4af5dd76-3ed0-4449-a2d6-1b857a466034)

<img width="312" alt="Screenshot 2023-12-01 at 09 17 17" src="https://github.com/Budibase/budibase/assets/101575380/9fdea6de-fc50-4dd7-97bf-bf0e0accc4cc">

**Comment by melohagan** [comment]
Feel free to provide your SQL schema and I can try to more accurately reproduce
