### ISSUE TITLE
[BUDI-7104] Bindable Inputs in builder require onblur to be fired before appearing in binding drawer

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#9060]
**Hosting**
- Cloud
  - Tenant ID: `bb`

**Describe the bug**
When you enter a binding in the app builder settings on the right hand side into a bindable input, then click the lightning bolt, the value is not shown in the handlebars binding drawer straight away. 

I'm aware that this works when the `onBlur` handler is triggered, but I think it makes sense to trigger the update handler when the lightning bolt is clicked, so that the value is appended there. Minor, but potentially a little confusing.

**To Reproduce**
1. Go to design
2. Create a paragraph component 
3. Go to the text setting and type something 
4. Click the lightning bolt binding button

**Expected behavior**
- Text from input is in handlebars input

**Screenshots**
https://user-images.githubusercontent.com/11256663/207894561-259cfd80-9c41-431f-8e5d-df447bfc27da.mov

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0.1 - M1 chip
 - Browser Chrome
 - Version  108.0.5359.98 (Official Build) (arm64)

<sub>[BUDI-7104](https://linear.app/budibase/issue/BUDI-7104/bindable-inputs-in-builder-require-onblur-to-be-fired-before-appearing)</sub>

**Comment by aptkingston** [comment]
Yea makes sense. This is actually a race condition, so in self host it generally manages to save in time and the new value is displayed, but not in cloud of course.

**Comment by shogunpurple** [comment]
l

**Comment by aptkingston** [comment]
Not sure there's anything we can do with this one. We definitely can't use an onchange event here because it would spam the API, so we do need to rely on a blur. Increasing cloud speed is one of the only things we can do.
