### ISSUE TITLE
Skeleton loader a little sluggish, increasing the time before the user can interact with the page

### ISSUE THREAD

**Issue by hawkinsjon** [Budibase/budibase#9064]
**Hosting**
- Self
  - Method: digital ocean
  - Budibase Version: 2.2.3
  - App Version: 2.2.3

I think the point of the skeleton loader addition was to help show a single loading animation until all of the queries of a given view are completed. 

The way the skeleton loader is set up now, I see some queries speed past the animation, the data fully renders, and then a short moment later the skeleton animation takes over masking all items that had previously rendered, then when the final queries complete, the page is fully rendered.

My feeling after flipping around to a few query heavy pages is that the skeleton loader is being a little greedy and slowing down the speed in which the page is finally rendered and useable for the user.

As a comparison I reverted my app from 2.2.3 back to 2.1.42, refreshed the page and I get snappy "feeling" page loads again.

I'm guessing for a lot of budibase users, this Skelton loader feature will be just fine as it is now. For those with greater queries per page, especially if those queries are from different sources or APIs, I think this experience as it sits now is not good enough. Feels a little clunky. 

If there's a way to tweak or disable this feature and revert back to the old set up which seemed to be an individual spinner per area querying data, that would be great. Maybe in the setting per app?

**Comment by melohagan** [comment]
Hey @hawkinsjon 

I'm not seeing any particular issue myself:
![add_comp](https://user-images.githubusercontent.com/101575380/208111758-7ff9cb58-a3e5-4e41-98ac-c723b4910a9c.gif)

If there's a particular problem you want to showcase, a recording would be very helpful. 

As a bug there really needs to be reproduction steps, otherwise it may be best to raise feedback in either the GitHub discussions, or in our discord channel: https://discord.gg/zPH2EYKQ

I believe that you may have created this thread in Discord? `Skeleton Loader feels slow`

**Comment by hawkinsjon** [comment]
Sure thing, here's two clips, one on version 2.1.42 and the next on version 2.2.3 where you can see the experience a bit.


https://user-images.githubusercontent.com/3512179/208146207-07f14917-72c7-429a-9112-7515a3111ded.mov


https://user-images.githubusercontent.com/3512179/208146220-dc21c55f-cd7f-44cf-a20e-5ffa8e934b9a.mov

**Comment by melohagan** [comment]
Thanks for that @hawkinsjon I can see the visual issue! 

I think seeing your component tree, i.e. the composition of your Data providers and repeaters would also be useful. 

In addition, what are your datasources? Are you using REST APIs, SQL Databases, the Internal DBs or a mix of these?

**Comment by hawkinsjon** [comment]
![screen-shot](https://user-images.githubusercontent.com/3512179/208249567-bdd5baab-b6ca-4dbe-8c22-237fc0c11113.jpg)

No worries, @melohagan. I tried to collapse the component tree to focus on the data providers. I renamed them to make it more obvious in the screenshot what each connector is doing. 

Overall...

1. Postgres data provider + repeater displaying a table lightly filtered table with a few thousand rows
2. Mysql data provider running a query with 9 self-joins from a dataset of about 30,000 rows 
3. Similar query to #2

**Comment by melohagan** [comment]
Hey @hawkinsjon 

Thanks very much for that, I'll see what I can do on my end to reproduce.

Just out of curiosity, do you need to have two MySQL queries? Is it possible to combine them into one?

**Comment by hawkinsjon** [comment]
Thanks @melohagan! 

Regarding the two mysql queries, you are correct, they can be merged into one. Just a little tech debt.

**Comment by melohagan** [comment]
Hey @gmentzik If you check the network tab in your browser, do you find that **2.2.9** is making more queries than **2.1.42** ? 
https://github.com/Budibase/budibase/issues/9143

**Comment by gmentzik** [comment]
> Hey @gmentzik If you check the network tab in your browser, do you find that **2.2.9** is making more queries than **2.1.42** ? #9143

Yes indeed. I have a provider/form in repeater page that gives back the following results:
2.1.42 : Fetch/XHR / All Requests : 47/59
2.2.9   : Fetch/XHR / All Requests : 130/142

I tried to increase max connections in Mysql to 200 still is very slow and occasionally unresponsive.

**Comment by melohagan** [comment]
> > Hey @gmentzik If you check the network tab in your browser, do you find that **2.2.9** is making more queries than **2.1.42** ? #9143
> 
> Yes indeed. I have a provider/form in repeater page that gives back the following results: 2.1.42 : Fetch/XHR / All Requests : 47/59 2.2.9 : Fetch/XHR / All Requests : 130/142
> 
> I tried to increase max connections in Mysql to 200 still is very slow and occasionally unresponsive.

Thank you for providing this information. The dev team is looking into this now.
