### ISSUE TITLE
Table clipping options picker

### ISSUE THREAD

**Issue by LauridsJMikkelsen** [Budibase/budibase#9080]
**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.2.3

**Describe the bug**
My goal is to have a options pickers as table columns in a table component, as I the users wants to be able to edit data directly in the table, and not having to open a modal or another page. The issue is that when i add a options picker component inside of a table component the popover window gets clipped by the table.  You can still scroll inside the table component, but this is just not very pretty.
![image](https://user-images.githubusercontent.com/108740098/208178734-e4b0b2b6-1bfc-48b5-a9af-50b1aedc6443.png)

I've tried adding padding, changing sizes and different nestings of the components as well as bit of custom CSS. 

**To Reproduce**
1. Add a Form component to screen
2. Add Data provider inside Form component (or vice versa) and add data source
3. Add Table component inside Data Provider
4. Add Options Picker component inside of Table Component
5. Add options to the picker, preview app and try opening one of the pickers in the bottom of the table

**Expected behavior**
What i would love to be able to do is to add different pickers inside of a table to be able to view and interact with the data directly in a table view. 

**Screenshots**

![image](https://user-images.githubusercontent.com/108740098/208180172-223cf34b-0e84-4bdb-8e19-4fb397e06f5f.png)

  
**App Export**
[Test-export-1671221296253.tar.gz](https://github.com/Budibase/budibase/files/10248675/Test-export-1671221296253.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Edge
 - Version: 108.0.1462.46

** Server:**
 - Windows Server 2022

**Comment by melohagan** [comment]
Hey @LauridsJMikkelsen 

Have you considered using the new side panels? They are a setting of the table block: https://docs.budibase.com/docs/table-block#on-row-click

**Comment by LauridsJMikkelsen** [comment]
Hey @melohagan 

No I haven't tried out the side panel, but I will take a look at it as an alternative solution.

Although, that doesn't address my main requirement of being able to edit data inline, and not having to rely on side panels, modals or page links. Is this something that can be done? By adding option pickers, date pickers etc to the table component or some other way?

Also, is there a fix for the expanding the size table or something, that prevents the drop-down/popover menu from being clipped?

Thanks for the reply

**Comment by kasgithub8** [comment]
> Although, that doesn't address my main requirement of being able to edit data inline, and not having to rely on side panels, modals or page links. Is this something that can be done? By adding option pickers, date pickers etc to the table component or some other way?

Hi @LauridsJMikkelsen,

it works with Number-Fields I can't see why it wouldn't work with option pickers.
