### ISSUE TITLE
Email binding values from 'Base format' template are not shown if email is sent by automation.

### ISSUE THREAD

**Issue by michal-81** [Budibase/budibase#9092]
**Hosting**
- Self
  - Method: docker
  - App Version: 2.2.3

**Describe the bug**
Email template bindings like platformUrl, company, currentYear etc. are not shown if email is sent by automation

**To Reproduce**
1. Go to your app settings and set some 'Org. name' and 'Platform URL'
2. Create automation that sends an email to the user.
3. Send the email using automation.
4. Check the email and notice that values for platformUrl, company (in the header), currentYear (in the footer) are missing.

**Expected behavior**
Common email binding values should be displayed when automation is used to send email

**Additional context**
I have tested built in 'User invitation' and  'Password recovery' templates and they are working fine i.e. 'Org. name',  'Platform URL' and current year are displayed so the problem is only when using custom template in automation.

**Comment by yingenpass** [comment]
Unfortunately I have the same Problem with the same hosting setup.
