### ISSUE TITLE
Internal DB: Cannot Create Column

### ISSUE THREAD

**Issue by Mitch-Budibase** [Budibase/budibase#9095]
It is impossible to create a column for an internal DB table.

Steps to repro: 
1. Log in
2. Create a new app
3. Click Budibase DB as source
4. Click 'Create new table'
5. Click 'Create column'

Here is a loom video highlighting the issue
https://www.loom.com/share/a7136390867648128b2c35f2156a4754

After clicking create column, the page seems to freeze up - it is not possible to navigate anywhere or perform any action. A refresh will give the user control again but clicking create column will cause the freeze up again.

**Comment by aptkingston** [comment]
Fix this on develop and it's live on the release env - feel free to check again.

**Comment by Mitch-Budibase** [comment]
Thanks Cheeks! I have verified that it is working as expected
