### ISSUE TITLE
Empty string passed to getElementById()

### ISSUE THREAD

**Issue by diogenesbrussels** [Budibase/budibase#9096]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.3
  - App Version: 2.2.3

**Describe the bug**
When using Firefox I have a large number of errors: Empty string passed to getElementById() in the console log when loading a screen containing a form.

**To Reproduce**
1. Use Firefox
2. Go to a screen with a form
3. Check the browser console
4. See warnings

**Expected behavior**
No warnings :)

**Screenshots**
![image](https://user-images.githubusercontent.com/91942877/208413446-d8974cf7-2c1e-49c5-8e6d-f739dece73e3.png)
![image](https://user-images.githubusercontent.com/91942877/208413594-f8cab726-79b7-4958-ab0a-75fd101d0a0c.png)

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Firefox
 - Version 108

**Additional context**
Maybe it's a bug with Firefox or Chrome not displaying these warnings?

**Comment by diogenesbrussels** [comment]
Hey @aptkingston 
Thanks for the information, I'll try to look into it further if I can offer you a solution.
Is it possible to disable the minification/grouping of the js assets by a flag or env variable? 
I was unable to set up the development environment on my machine running W11 and I don't think I'll be able to set up a unix environment soon.

**Comment by Rory-Powell** [comment]
Hi @diogenesbrussels . We're not planning to make any changes to our build process at present.
