### ISSUE TITLE
Default value no longer being set on Navigate To action. Causes problems with filtering in version 2.2.3

### ISSUE THREAD

**Issue by ShivrajJoshi1996** [Budibase/budibase#9104]
Hosting

Internal Budibase Hosting

  - App Version: 2.2.3

**Describe the bug**
Filtering the table using the data from other table is not working.

**To Reproduce**
1. Create two internal tables with one to many relations. 
2. Use the value of relationship column to new column (so that we can use the new column for filtering )
3. On screen 1 click on table row and navigate to other screen
4. On screen 2 show the selected/clicked information on top. (like column value). Take data provider>new repeater>text field to show the value in text field. For data provider, specify the condition as below " Screenshot for Meta data"
5. Based on meta data, provide filtering to table 2. As per "Screenshot to filter below table"

**Expected behavior**
I should be able to filter screen 2 table based on text field which provide data from table 1.

**Screenshots**
1.
![Table 1](https://user-images.githubusercontent.com/121036387/208453775-545b8943-b1cf-414b-8897-6f3f73dbc6f1.png)

2.
![Table 2](https://user-images.githubusercontent.com/121036387/208453800-3fa895fd-a8a2-4b8a-af05-dfd4806a0986.png)

3.
![Screenshot 1 navigate](https://user-images.githubusercontent.com/121036387/208453822-70d525dd-56a8-4b10-8d9c-a799baa95fbb.png)

4.
![Screenshot for Meta data](https://user-images.githubusercontent.com/121036387/208453852-e9aeca02-1c56-44a2-bb5d-6fe787f94712.png)

5.
![Screenshot to filter below table](https://user-images.githubusercontent.com/121036387/208453880-54792095-8aa8-4a91-9b7a-7c43921725aa.png)

  
**Additional context**
For earlier version filtering was achieved using above steps, but since the last update filtering is not possible.

**Comment by melohagan** [comment]
Hey @ShivrajJoshi1996 

I can't reproduce any issue here - I don't think I understand what you're trying to do in steps 4 and 5. 

What data type is the NEW_RELATION field, and why do you need it?

**Comment by ShivrajJoshi1996** [comment]
Hi @melohagan 

Thanks for your replay. let me give you little briefing on each screenshot that I have added.

On 1 and 2 screenshot: 
I created two tables as both table are interdependent means one best practice is having multiple strategy so its 1:Many relationship. Here you will see on both tables we have relationship columns highlighted with grey background .

I need this columns as I have to filter data on other screen which I will mention on screenshot4. 

I can't use relationship column directly for filtering as I don't see it inside repeater so I have to create copy of this column so that I can actually use it during filtering. Thats what New_Relation_1 column is doing.

Screenshot 3: 
This is just to navigate to next screen.

Screenshot 4: 
It is basically on screen 2 where I actually wanted to filter the data from last screen say screen 1.  The filter condition what you are seeing here is basically limiting data through URL._id of previous screen (say I have selected 1 row on screen 1, so only record associated with that row is presented here)

Here inside a form I used data provider with table 1 (Best practice) and inside that data provider I used repeater so that I can get the column name from Table 1 and using this column name for a text field.(on screenshot 5, it will use to filter a table)

Screenshot 5:  
This is also on screen 2 and this is table which will be filtering based on Screenshot 4's condition.
So here New_Relation_1 of table 2 is basically holding the relation data of table 1 i.e.name of best practice (See screenshot 1 and 2).

Now I am checking whether New_Relation_1 is equals to text field  (basically from screenshot 4) if it is true then data should filter with that best practice name else false.


This is basically what the screenshots are about. Let me know if you need more details on this.

**Comment by melohagan** [comment]
Hey @ShivrajJoshi1996 

I think I'll need an app export for this one. I've followed through the steps as best I can, but I cannot reproduce any issue with the filtering:

![bug](https://user-images.githubusercontent.com/101575380/208901258-e47698ee-981e-4697-9b71-2769207e2efb.gif)

This is version **2.2.9**

**Comment by ShivrajJoshi1996** [comment]
Hi @melohagan 

Thank you for your quick response. Yes you are doing correct thing, only small thing is there which is:

As you see you are filtering data based on text field which is correct but earlier it was filtering based on placeholder and default value assigned to it, I was not giving any input in the text box to filter data but now I need to give the input. Which I can't do due to the requirement of the project.

So I need text box to capture the default value assigned to it and filter the data based on it without giving any input in the text box (like above in you UI) as it was doing earlier or let me know if there is any other options I can try. for your information I have tried all of Budibase's components but nothing work as I wants it to work.


 If you need an export will provide it as well but you already replicated the thing.

**Comment by ShivrajJoshi1996** [comment]
Hi @melohagan

If you need any more details here is the attached export.
[Demo-export-1671628386602.tar.gz](https://github.com/Budibase/budibase/files/10277926/Demo-export-1671628386602.tar.gz)

**Comment by ShivrajJoshi1996** [comment]
Ohh Yes @melohagan Thanks, hoping for early solution on this.

**Comment by ShivrajJoshi1996** [comment]
Hi @melohagan Next week we have a demo, so can you please fix the issue ASAP and keep me posted.

Thanks.

**Comment by melohagan** [comment]
Hey @ShivrajJoshi1996 

We normally offer prioritisation like this on our enterprise plan, aside from that, we won't be able to fix this within the next week.

However, I believe that I have a workaround that may suffice for your demo. 

1. Rename your second (detail) screen to have two URL variables, e.g. `/detail/:id/:relation`
2. In the first screen, set **Navigate To**: `/detail/{{ New Table.Selected rows }}/{{ Clicked row.Name }}` (In your case Name is Best Practices Name)
3. For the default value of your text field, use the following JavaScript binding: `return $("New Repeater.Best Practices.Name") || $("URL.relation");`
4. In the second Data Provider, use the filter JavaScript binding: `return $("New Form.Fields.Name") || $("URL.relation");`

Here is the app export that you can have a look at: 
[FilterTest-export-1671634644020.tar.gz](https://github.com/Budibase/budibase/files/10278720/FilterTest-export-1671634644020.tar.gz)

**Result**
![bug](https://user-images.githubusercontent.com/101575380/208935078-de4779ed-a546-4093-bdfe-0219f3fff2cf.gif)

**Comment by ShivrajJoshi1996** [comment]
Hi @melohagan Thanks, it works.
