### ISSUE TITLE
The application freezes when trying to edit a table row and causes memory leak.

### ISSUE THREAD

**Issue by michal-81** [Budibase/budibase#9106]
**Hosting**

- Self
  - Method:  docker compose,
  - App Version: 2.2.3

**Describe the bug**

I have a table with edit link that loads the form with selected table row data.
When I click the link the application becomes unresponsive, refresh button in the browser flickers and I have also noticed gradual memory consumption of the browser.
To stop it I have to kill web browser in task manager ( closing the browser tab with Budibase app is not enough ).
I created this functionality good few months ago and it was working fine until recently. 
The URL that loads the form looks like this
`/reservation/edit/{{ reservations Table.reservations._id }}`

Now I can't use the app. Sometimes the edit form loads OK but more often than not it just hangs.
I created animated GIF to show the problem.

**Screenshots**

  
![Taskmgr_Lydh6hTlrZ](https://user-images.githubusercontent.com/114871390/208473995-936e6259-a5d2-4ad4-9d59-6836acd60e61.gif)

**Additional context**
I tested in on Windows (Edge, Firefox) and Linux (Firefox) but the problem is the same. I have also tried to clear page cookies but it didn't help either.

**Comment by melohagan** [comment]
Related discussion: https://github.com/Budibase/budibase/discussions/9114
