### ISSUE TITLE
Table values are truncated even with plenty of space left

### ISSUE THREAD

**Issue by ttben** [Budibase/budibase#9108]
Hi!

Text values in table are truncated, even if plenty of space is available
![image](https://user-images.githubusercontent.com/6167712/208479484-5d3c3c5f-4d4c-4c92-87dd-0afea75e01d4.png)

As the content of this particular column is critical to the app, and that the side panel is not a word-around as it suffers the same issue (btw, how can I opt for opening a modal instead a of the side panel?), the app is barely usable for me now...

A discussion from 1 year ago addressed the [exact same question (3588)](https://github.com/Budibase/budibase/discussions/3588), which lead to  [an issue (3705)](https://github.com/Budibase/budibase/issues/3705 ) that is now closed and the data truncation should no longer be an issue (https://github.com/Budibase/budibase/issues/3705#issuecomment-1031875901) as far as I understand.

But as the whole table component was re-designed, maybe I misunderstood.
Can you help me on this? :)  Thanks !

----
Infos 

- Budibase self-hosted
- Version 2.2.3

**Comment by aptkingston** [comment]
Hey @ttben. If you have columns that you need to be particularly wide then you can configure that yourself.

To do that:
- Select "Configure Columns" in the table component
![image](https://user-images.githubusercontent.com/9075550/208627570-bf5741b4-a9c0-4574-b4da-fc6d17a8206e.png)
- Choose which columns you want to include
![image](https://user-images.githubusercontent.com/9075550/208627634-d50e0b29-23a2-4739-80dc-64655cf57f9e.png)
- Press the settings icon beside the column you want to make wider
![image](https://user-images.githubusercontent.com/9075550/208627698-5c781936-695b-488f-8bef-25acd9a1979a.png)
- Enter whatever you like for the width
![image](https://user-images.githubusercontent.com/9075550/208627753-18ee2f04-2a6e-4152-a88a-c15c48eaf9e4.png)
- Press save twice to close both drawers

Hope that helps!

**Comment by ttben** [comment]
Thank you for your quick answer!

Actually, I have set each col-width, but let the last one width on "auto" ,  thinking that "it would take all the remaining width available"
It does behave that way, i dont know if it is normal or not.

Anyway, following your advice I set a fixed  width, and  now the col is larger

Thank you!

**Comment by aptkingston** [comment]
No problem. Sorry yea I should have mentioned that - setting `auto` won't make it take up the available space, but it will make sure that your value never is truncated. So it will take up as much width as required to show the full value :+1:
