### ISSUE TITLE
[BUDI-6816] Don't include relationship ID columns for auto-generated SQL screens

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9111]
**Describe the feature request**
When you create an auto-generated screen for a SQL datasource that has relationships, it includes the ID columns in the side panel form.
You would probably never want these, thus you're going to have to always eject the table block which isn't ideal.

**Screenshots**
![Screenshot 2022-12-19 at 17 48 01](https://user-images.githubusercontent.com/101575380/208488150-c948ba7b-30a5-47f5-acb2-6fdec5f47842.png)
*I don't want staff_id because I have the staffs field for the relationship. Forces me to eject the table block.*

<sub>[BUDI-6816](https://linear.app/budibase/issue/BUDI-6816/dont-include-relationship-id-columns-for-auto-generated-sql-screens)</sub>

**Comment by shogunpurple** [comment]
Should be resolved by the form block updates happening this iteration where you can show and hide the columns of your choosing

**Comment by melohagan** [comment]
Re-opening this one because I was going through this scenario with @doingandlearning and the ID fields can cause issues when creating a new row when you are selecting relationships in the pickers, but not entering numbers into the ID fields.

**Comment by melohagan** [comment]
Appears to be fixed @shogunpurple !
