### ISSUE TITLE
[BUDI-7184] MongoDB "In" Query

### ISSUE THREAD

**Issue by JayP718** [Budibase/budibase#9119]
### Discussed in https://github.com/Budibase/budibase/discussions/9091

<div type='discussions-op-text'>

<sup>Originally posted by **JayP718** December 18, 2022</sup>
Hi,

So I think this may be a bug but I'll start here.

I'm trying to return a few documents from a collection using the "in" operator.

{"_id":{"$in":["ObjectId('639f3e8d46447d7af2d312f4')"]}}

I've tried several variations of the statement above. I am able to use the "in" operator with other fields. I'm just unable to use the in operator for the ID. Is this a bug or just something I'm doing wrong?

Best,

J</div>

<sub>[BUDI-7184](https://linear.app/budibase/issue/BUDI-7184/mongodb-in-query)</sub>

**Comment by littlediobolic** [comment]
I am running into this issue as well. I can't use the following query:

```json
{
	"_id": { "$in": {{ids}} }
},
{
	"$set": {
		"datesAttended": {{date}}
	}
}
```

with the following Bindings:

```
ids = ["ObjectId('63be2abfcda690ca16b33a14')"]
date = "test date"
```

**Comment by littlediobolic** [comment]
This seems to be a problem with requiring `ObjectID` to be escaped in quotes. The mongo shell does not match anything with the above query either, only when removing the quotes from the ObjectID does it actually update. This restrictions would need to be removed for it to work

I could be mistaken however...
