### ISSUE TITLE
Public API: Allow import of full application

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9126]
### Discussed in https://github.com/Budibase/budibase/discussions/9051

<div type='discussions-op-text'>

<sup>Originally posted by **CheshireNine** December 15, 2022</sup>
**Question**
Is it possible to import full application ( exported JSON blob text file) to Budibase via some Public Budibase API?

I can't find any existing Public API for this purpose:
_POST /api/public/v1/applications_ budibase endpoint allows to create only BLANK application with given name and url.

**Why I need this**
Our developers work on their local Budibase environments. After feature is done we want to store the application and then import this app version on several sandbox/preprod Budibase environments on release date. So we are trying to setup CI/CD process to 
1. unpublish/delete existing version of the application from Budibase environment
2. import new version of application (stored in git as exported JSON blob text file) to the same environment and publish it.

Right now we can do it only manually via Budibase UI, but it is inconvenient process as we need to do it on multiple environments.
I will be thankful for any advice and workarounds.
</div>

**Comment by geertvanheusden** [comment]
Would the option to upgrade an existing app also be part of this Public API call?
As this would be really helpful to migrate your application to a new version instead of going through the changes manually.

**Comment by atticuss-sra** [comment]
Hi @shogunpurple & @melohagan. Given the `premium-enterprise` label, is it safe to assume that this feature has been added but is not available to free users? I'm investigating using Budibase atop short-lived, ephemeral infra but with applications that need to persist across deployments.
