### ISSUE TITLE
[ Client Package - FieldGroup Component ] - Context should be converted to a readable Store

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#9128]
Currently, the FieldGroup component, exposes an object in its context an object
`  setContext("field-group", { labelPosition }) `

I think, this should have been a readable Store so child elements can subscribe to receive updates.
I understand this might require some rewiring of the existing Form Components, but i think in the long run it will be worth it.

**Comment by Rory-Powell** [comment]
@poirazis for this change, we're unlikely to dedicate time to make this refactor, but would be happy to accept a pull request introducing the change requested.
