### ISSUE TITLE
I can't delete my admin screen, error 404

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#9149]
https://www.loom.com/share/7878d03e5e8c4d108667b330eddb4f42
Reported by QA wolf

Note: It is inconsistent for me.. 

Steps to reproduce: 

1. Add test app
2. Navigate to Design tab
3. Add screens of different access levels, use names with spaces:  "this screen is admin", "this screen is power", "this screen is public" 
4. Try to delete the Admin screen

Expected result: Admin screen is deleted
Actual result: Error 404 when I try to delete the screen

**Comment by aptkingston** [comment]
I've tried to reproduce this myself and I can't I'm afraid. Until we get reproduction steps that always work then I'm not sure we can action this. It's likely 409 conflicts due to doing too many actions too quickly.
