### ISSUE TITLE
Table Level Roles (Public Data)

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#915]
When I create a table in budibase, I want to optionally assign a role to it, so that only users of that role or above can perform the relevant read/write actions against the table.

- Tables are assigned to admin by default
- Tables can be made public by removing the role from them altogether
- When a user tries to perform an operation on something they do not have access to, they should be notified

This will require UI work to configure table roles and backend work on the middleware side to allow certain users to perform certain operations

**Comment by joebudi** [comment]
Approvals are an important aspect of table-level roles. Here is a very popular and important use case:

Manage has to approve X (contract hours, time off, support tickets, leads)

Workflow:

An employee submits a form
Manager receives submitted form and has to approve or disapprove
User gets notified re decision

**Comment by mjashanks** [comment]
> Tables can be made public by removing the role from them altogether

In addition to this, can just make sure that there is some sort of warning/indication that public means that the data is completely open.

Also, there is a possibility that #951 could affect the design for this. E.g. will we want query-level access rights? I feel like we **may** end up in a situation where "Read access to the Contacts table" will not make sense.

We should maybe consider #951 first.

**Comment by joebudi** [comment]
https://miro.com/welcomeonboard/JpNjY2n3xPnxcPB43bYtohmpBkMPavaV2X9v23RALxRxyAOZxCza0WTVBWmE7qvI

Above is a very quick and dirty mockup of how I expect this to work. It's a start.

**Comment by shogunpurple** [comment]
Really like that mockup @joebudi - clean and simple way to control access to particular tables. We would have to account for the unauthorised situation in all the different components though - so possibly a dialog or central component showing your error message is a good middle ground; it would be shown when we get a specific error back from the backend when accessing data.

We will have more complex access control on tables in future, where you may prevent a certain user or something from accessing a table, but we've overcome that kind of thing in the past by expanding the popover out into its own modal.

@mjashanks - are you thinking that we should be doing something more granular? Eg. You can restrict access to particular columns (or even rows) on a table, rather than setting permissions on the whole table

**Comment by mjashanks** [comment]
That's not what I was thinking. It's related to a suggestion that I have for #951. It also takes into account access control for external data connectors (queries).

I will do a proper writeup of my suggestion for #951 as soon as I can.
