### ISSUE TITLE
Automation update row removes relationship

### ISSUE THREAD

**Issue by m7kael** [Budibase/budibase#9161]
- Self
  - Method: digital ocean, PostgreSQL database
  - Budibase Version: 2.2.9
  - App Version: 2.2.9

**Describe the bug**
When using automations to update rows I run into the same problem frequently. I am working on a simple stock management app and have a "products" table and a "productsEvents" table for keeping track of stock in PostgreSql. The "products" table has a number field for stock and the "productsEvents" table have a number field for qty. I use static values to be able to search for products that are in stock. I then have a automation that is triggered when a row is created in "productsEvents", that queries all productsEvents rows that are related to the products and sums the qty field, it then updates the products stock field to the calculated value. The problem is if I leave the relationship field emty when updating the product it deletes the relationship and the product has no events related. 

I have also noticed that the same applies if i have a option field in the "products" table it deletes the value if I have it empty. 

**To Reproduce**
1. Create a "products" table and a "productsEvents" table and create a one to many relationship. Create a "stock" number field in "products" and a "qty" number field in "productsEvents" table.
2. Create an automation that is triggered on row creation in "productsEvents" table, query productsEvents related to the same product, sum "qty" field and update the "stock" field in the products table.
3. Check data and relationship between "products" and "productsEvents" is removed

**Expected behavior**
I would like the update row step to only update the fields that are filled and not to remove relationships. The question is then how to handle when you do want to empty a field or remove a relationship?  

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 16.2

**Comment by melohagan** [comment]
Not quite the same issue, but a related issue. From the automation history:

**TRIGGER OUTPUT**
```json
{
  "fields": {
    "tags ": [
      {
        "_id": "ro_ta_b289aab2670e407cbba7b40ddb186ad6_0df0603d9b2a4667bd858bc50217e595",
        "primaryDisplay": "Fantasy"
      }
    ],
    "movie_id": "ro_ta_04be775a673942e58723c4528dc6881b_8dd2d5882b314b3a9d90bba6255e8b44"
  }
}
```

**UPDATE ROW OUTPUT** (shortened for readability)
```json
{
  "row": {
    "_id": "ro_ta_04be775a673942e58723c4528dc6881b_8dd2d5882b314b3a9d90bba6255e8b44",
    "Year": 2001,
    "Title": "Lord of the Rings",
    "tableId": "ta_04be775a673942e58723c4528dc6881b",
    "Auto ID": 1,
    "type": "row",
    "Tags": [
      {
        "_id": "ro_ta_b289aab2670e407cbba7b40ddb186ad6_0df0603d9b2a4667bd858bc50217e595",
        "Name": "Fantasy",
        "tableId": "ta_b289aab2670e407cbba7b40ddb186ad6",
        "Auto ID": 1,
        "type": "row",
      },
      {
        "_id": "ro_ta_b289aab2670e407cbba7b40ddb186ad6_992874a8cd5d411687c10a2ee6776d2c",
        "Name": "Action",
        "tableId": "ta_b289aab2670e407cbba7b40ddb186ad6",
        "Auto ID": 2,
        "type": "row",
      }
    ],
  },
  "response": "Movies updated successfully.",
  "id": "ro_ta_04be775a673942e58723c4528dc6881b_8dd2d5882b314b3a9d90bba6255e8b44",
  "success": true
}
```

For some reason it is adding both relationships despite using the `{{ trigger.fields.tags }}` binding:

<img width="511" alt="Screenshot 2023-01-27 at 21 16 49" src="https://user-images.githubusercontent.com/101575380/215202334-28f77ebc-3c24-4b31-ad88-d38a46899915.png">

<img width="511" alt="Screenshot 2023-01-27 at 21 16 27" src="https://user-images.githubusercontent.com/101575380/215202284-2a77c396-0ac0-4173-912c-ee20a802b5b2.png">
