### ISSUE TITLE
Image URL Regex Error

### ISSUE THREAD

**Issue by matteoveglia** [Budibase/budibase#9162]
**Hosting**
- Cloud
  - Tenant ID: vfxbase

**Describe the bug**
I'm trying to use simple regex on a form field to validate an image url, essentially any http or https url that ends with jpg/jpeg/png.
For some reason I just can't work out the expression seems to be failing.

This is the url I'm testing against:
https://xl.movieposterdb.com/14_12/2014/816692/xl_816692_b871049b.jpg
I've used other urls, I'm also messed with the url in the form but it just won't hit.

And this is the regex:
/https?:\/\/.+\.(png|jpeg|jpg)$/

**To Reproduce**
1. Make a Text Field form input
2. Set the validation to Match given Regex = /https?:\/\/.+\.(png|jpeg|jpg)$/
3. Try the field with an image url, any http or https url ending in jpeg/jpg/png

**Expected behavior**
An accepted input

**Screenshots**
![image](https://user-images.githubusercontent.com/1258632/209421211-643c9e79-b422-43fe-ba73-7a2cc1d98fa1.png)
  
**App Export**
[vendorBase-export-1671856329902.tar.gz](https://github.com/Budibase/budibase/files/10297992/vendorBase-export-1671856329902.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 108

**Comment by aptkingston** [comment]
Hey @matteoveglia. You just need to remove the slashes around the expression - it expects just the contents of the regex.
If you just enter `https?://.+.(png|jpeg|jpg)$` then it will work. We should document that somewhere if we don't already as that's a very easy mistake to make.

As an aside, I'd also recommend escaping the forward slashes in your expression, and you also need to escape the literal full-stop character before your extensions, so I would define the regex as `https?:\/\/.+\.(png|jpeg|jpg)$`.

Thanks for following the issue template, providing a detailed description and providing an app export by the way!

**Comment by matteoveglia** [comment]
Sooo fun fact! If you don't put regex into a code block in an Issue then it strips out some slashes, this is what I posted with those slashes you suggested all intact
<img width="944" alt="image" src="https://user-images.githubusercontent.com/1258632/209479623-f3f42aa5-263e-4123-adf6-d0c4b1d1d54c.png">

Either way thank you very much for the info on removing the opening and closing slashes, removing those worked!
