### ISSUE TITLE
Incorrect <Style> Tag Generation & Uncaught TypeError

### ISSUE THREAD

**Issue by matteoveglia** [Budibase/budibase#9169]
**Hosting**
- Cloud
  - Tenant ID: vfxbase

**Describe the bug**
Hi,

Bit of a strange one which might be multiple issues but I'm not sure, they all feel related.

So I have an options picker, it all works just fine, I pass it a list of projects and the user can pick from them. Picking one pushes it to the app state which is then used by the rest of the app; that all works just fine.

However, I have some placeholder text for when there's no selection, "Select a Project" which is put in there using the following handlebars code on the Placeholder field:
`{{#if State.projectSelected}}
  {{State.projectSelected}}
{{else}}
  Select a Project
{{/if}}`
_Note, in the app export I just put straight text of 'Select a Project' in there to check if the code was the issue._

This code works, on refresh the code displays the project in State or "Select a Project", however, strangely for some reason as you'll see in the attached video if I open the picker then that placeholder reformats the box strangely and is constantly loading (but not loading). 
Additionally, every time I open and close the picker a new empty <style> tag is made in the page Header.

There's also a strange Uncaught TypeError which eventually comes up, sometimes it's an error about a missed promise (seems random), I've put a screenshot in for that too.

Lastly, I feel like this is related too but for some reason the Made with Budibase logo is offset too, even stranger how if I turn off alignment in DevTools it then aligns... I've added a video for that.

**To Reproduce**
1. Load the app, on the home page click "Select a Project" at the bottom
2. On the project selection page, pick any project, just go with 1 I guess
3. Click the now clickable "Test Project 1" at the top, this will take you to the project overview page
4. On this page you'll now see an option picker on top right, this is there to allow for hot switching of projects without going back home every time.
5. Click the options picker and you should see all the issues described

**Expected behavior**
No <style> creation, Budibase logo aligned correctly and an options picker which allows me to change the placeholder without strange behavior 

**Screenshots**
[Video.webm](https://user-images.githubusercontent.com/1258632/209753868-6c7bba18-5159-4e1f-abf6-56ba324bd1f1.webm)
![image](https://user-images.githubusercontent.com/1258632/209755323-285707d1-4c5e-4940-a309-cc62b3efea20.png)
[Video2.webm](https://user-images.githubusercontent.com/1258632/209755482-1f65ebdf-2ab7-4363-b706-59efda4421c9.webm)

**App Export**
[vendorBase-export-1672197728687.tar.gz](https://github.com/Budibase/budibase/files/10311881/vendorBase-export-1672197728687.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 108

**Comment by melohagan** [comment]
Hey @matteoveglia 

I wasn't able to recreate the issue you were describing. Are you still seeing this issue?

I also noticed you are using this custom plugin: https://github.com/poirazis/bb-component-SuperTabs

Cool to see it in action, but just be aware that there is the possibility of custom components having bugs - not that I am saying that this is definitely the case here!
