### ISSUE TITLE
 execute script 'yarn setup' is so slow

### ISSUE THREAD

**Issue by caizhisheng** [Budibase/budibase#9174]
when i git clone code from https://github.com/Budibase/budibase.git  then i execute script ‘yarn setup’ and found very slow.

Node: 14.20.1
Yarn: 1.22.19
Lerna: 5.1.4

How can I solve it? 
thanks forevery

![image](https://user-images.githubusercontent.com/13362401/209891569-82383ecf-0dc8-43d7-95fb-4e7591864bd9.png)

**Comment by melohagan** [comment]
Hey @caizhisheng 

`yarn setup` only needs to be run once on your first go. 

After doing the `yarn setup` initially, you can simply do a `yarn bootstrap` going forward which is much faster.
