### ISSUE TITLE
Migrating Budibase app and all data to another server - Blank page "Not found"

### ISSUE THREAD

**Issue by maiducan** [Budibase/budibase#9242]
Hello, I want to duplicate my budibase app to another server.

BUDI CLI is not working for me due to the size of the volumes (it basically crasshes in the middle of the process) 
So a copied entire docker folder /var/lib/docker to a new machine. Altogether with docker-compose.yml and .env
And started it using budi hosting --start based on the setting, all containers loaded but i got blank page "Not found" when I access the web.

However i.e. Minio web is working .. So it must be some problem in app container

Any tips? Thanks guys, budibase is the best!

**Comment by shogunpurple** [comment]
You've already raised a discussion here https://github.com/Budibase/budibase/discussions/8574#discussioncomment-4597554

Closing this as a dupe
