### ISSUE TITLE
Content Security Policy directive "media-src 'self'

### ISSUE THREAD

**Issue by JayP718** [Budibase/budibase#9252]
Cloud Version
Version 2.29
https://a3datasolutionsllc.budibase.app/builder/app/app_a3datasolutionsllc_f86cf3da9ace4c12bb9ee76ae0b3e30f/

I've built a custom plugin based off of shogunpurple's https://github.com/shogunpurple/budibase-component-microphone.

All I'm trying to do is play audio from an attachment.

Unfortunately although it works on locally hosted Budibase platforms but due to CSP in the cloud version I get the following error and am not able to replay the audio. 

Also raised it here 
https://github.com/shogunpurple/budibase-component-microphone/issues/2

![](https://user-images.githubusercontent.com/42209052/210647135-2e5877cf-c284-4050-8079-012cc31a9717.png)

Not sure if anything can be done to fix this but I thought I'd raise

**Comment by shogunpurple** [comment]
See comment https://github.com/Budibase/budibase/pull/8158#discussion_r1063808249
