### ISSUE TITLE
Adding a missing component plugin does not immediately update the app screens 

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9260]
**Hosting**
- Cloud
  - Tenant ID: plugins.budibase.app

**Describe the bug**
When importing an app that uses custom plugins into a new environment, you have to import the necessary plugins.
The screens do not immediately update to begin showing again. You have to add another instance of the same plugin to reload the existing one.

**To Reproduce**
1. In a new environment import the app export with custom components (see below)
2. Go to the Design section and see that the custom components have not loaded
3. Go the plugins section of the portal and import the needed components from Github (see links below)
4. Go to the Design section of the app and see that the component plugins have still not reloaded
5. Add a plugin of the same type. Now see both plugins load. 

**Expected behavior**
Upon importing custom component plugins, existing apps should reload the components without having to insert another component.

**Screenshots**
*Header Image is missing*
![Screenshot 2023-01-06 at 11 01 46](https://user-images.githubusercontent.com/101575380/210999639-5bca37bb-4c33-41db-a248-db86bc050f6b.png)

*Add another header image, the existing one will now reload*
![Screenshot 2023-01-06 at 11 02 22](https://user-images.githubusercontent.com/101575380/210999733-c01ade5a-a26a-4076-bf37-8e58de057d39.png)

**App Export**
[Hugo Plugin Submission-export-1673001481044.tar.gz](https://github.com/Budibase/budibase/files/10359622/Hugo.Plugin.Submission-export-1673001481044.tar.gz)

**Additional context**
Plugin Github URLs used:
 - https://github.com/poirazis/bb-plugin-Stepper
 - https://github.com/joebudi/budibase-component-gradient-header

**Comment by mike12345567** [comment]
The `app_metadata` document for an app DB contains a list of plugins that are used, when an app is imported a new app metadata document is generated, we need to copy over the list of plugins used from the old app metadata when importing apps.

**Comment by cgtms** [comment]
This issue is still present on 2.32.17.
