### ISSUE TITLE
Test Performance of encryption/decryption of environment variables

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#9261]
**COS**
- Understand the added latency to query requests for those using the new environment variables functionality
- Brute force a bunch of queries together using a load testing solution
- If required look at solutions to make encryption more efficient or some kind of intermediary hot storage for secrets that can be read at high throughput

**Comment by mike12345567** [comment]
Performance tested - decryption does add a small performance drop, but a simple solution was found using an LRU-cache (https://www.npmjs.com/package/lru-cache) and CouchDB's revision system to cache in memory the decrypted secrets, only caching the new decrypted secrets if a change occurs (or the instance is restarted).
