### ISSUE TITLE
Timeout on custom SQL Server query

### ISSUE THREAD

**Issue by JaCoB1123** [Budibase/budibase#9266]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.9
  - App Version: 2.2.9

**Describe the bug**
When running a long running custom Query I get the error
`RequestError: Timeout: Request failed to complete in 15000ms`.

I tried setting the env-var QUERY_THREAD_TIMEOUT to 120000, but that didn't change anything.

In my current case the query is really long-running, as it's a database cleanup thing. It will probably run for about 10 minutes.

**To Reproduce**
1. Have a SQL Server Datasource
2. Add a long running custom query 
3. Execute said query from a button

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 108

**Comment by melohagan** [comment]
Hey @JaCoB1123 

If the query would take 10 minutes, it should probably be executed asynchronously. 

Would it be possible for you to execute this within a stored procedure? 

You could also try running this via the **External Data Connector** in an automation, although it may possibly timeout as well.

If the environment variable does not take effect, you may also need to adjust timeout settings in your nginx config.
