### ISSUE TITLE
Query Import: docs don't mention OpenAPI/Swagger v3 support

### ISSUE THREAD

**Issue by davidrans** [Budibase/budibase#9267]
**Describe the bug**
The docs say that OpenAPI 2 query import is supported, but don't mention OpenAPI 3 support.

**To Reproduce**
1. Check out the Query Import docs: https://docs.budibase.com/docs/rest-query-import#import-formats

**Expected behavior**
It looks like OpenAPI v3 is supported as of https://github.com/Budibase/budibase/pull/4773, so I think the docs just need to be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/806152/211117978-bfe1a92d-c8b0-449e-bf57-b8534c42fd54.png)

**Comment by mike12345567** [comment]
Hi @davidrans - I have updated the documentation to include OpenAPI 3.0 support.
