### ISSUE TITLE
Data grid Editor scales down page in background on mobile phones tested in Google Chrome

### ISSUE THREAD

**Issue by milosFromSerbia** [Budibase/budibase#929]
**Describe the bug**
Data grid Editor scales down page in background on Mobile Phones tested in Google Chrome
**To Reproduce**
Test data grid editor on mobile phone sizes in browser

**Expected behavior**
Page in background need to scale to fit screen

**Screenshots**
https://pasteboard.co/JFgmb1Y.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**

**Comment by joebudi** [comment]
Hi @milosFromSerbia 

Thanks for creating the issue. It will be resolved very soon. It relates to:
#846

**Comment by shogunpurple** [comment]
@joebudi is this one now solved since https://github.com/Budibase/budibase/issues/846 is?

**Comment by joebudi** [comment]
It should be. There are still issues around fix widths. I believe the container around the data components in auto screens has a fixed width or it could be the screenshot.
