### ISSUE TITLE
Add histogram plot

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9294]
### Discussed in https://github.com/Budibase/budibase/discussions/9276

<div type='discussions-op-text'>

<sup>Originally posted by **Murali-001** January  9, 2023</sup>
I need histogram plot for my data.</div>

This should be doable with the Apex Charts library used in Budibase.

**Comment by lcorcodilos** [comment]
Hi all,

It seems like this made it into v2.9.25. I upgraded my docker image to this version but don't seem to have the Histogram accessible as either a component or an option in a Chart Block. Is there a trick I'm missing? Can anyone confirm they're able to use the feature in the latest release?

Thanks!

**Comment by melohagan** [comment]
Added a page to the docs: https://docs.budibase.com/docs/histogram-chart
