### ISSUE TITLE
Filtering cascading table widgets choosing multiple lines

### ISSUE THREAD

**Issue by Bitello** [Budibase/budibase#9301]
### Discussed in https://github.com/Budibase/budibase/discussions/9033

Hi!

I've been digging around the forum and it's been really interesting as I've been able to figure out how to properly use some features.

In my previous discussion I learned how to filter cascading tables (Thanks to @andz-bb).

But now I need to choose multiple rows from a table and the tables below must be filtered according to the selected rows.

I researched a lot, tried several alternatives, but I couldn't. My knowledge is in-depth in TSql, but not in javascript...

Anyway... could anyone guide me on how I should proceed to perform this type of filtering?

Grateful!

**Comment by mike12345567** [comment]
Hi @Bitello - for help on matters like this we recommend utilising Github discussions or Discord.
