### ISSUE TITLE
[Firestore] [Update Query] Query Error: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.

### ISSUE THREAD

**Issue by s1223** [Budibase/budibase#9305]
**Hosting**

- Self
  - Method: docker single image, docker compose
  - Budibase Version: 2.2.9
  - App Version: 2.2.9

**Describe the bug**
when i try to update firebase data, i get error 'Query Error: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.'

I have followed the tutorial https://docs.budibase.com/docs/firestore#update-query but I get an error (can be seen in the image below)

**To Reproduce**
1. Click the data tab above
2. add source from firestore
3. complete the Configuration
4. create an update query
5. Fill in the Config details (see image below)
6. Fill in the Fields details (see image below)
7. Click run query
8. error

**Screenshots**
![image](https://user-images.githubusercontent.com/8839594/211747127-4d701f17-72cd-4036-906c-1a17c1c079b7.png)
![image](https://user-images.githubusercontent.com/8839594/211747383-3ba33a02-9d80-414a-9ffe-98c870b34f0b.png)
![image](https://user-images.githubusercontent.com/8839594/211748791-ec489b0e-d247-4aec-a725-ede66c2dab7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome
 - Version 108.0.5359.125

**Comment by melohagan** [comment]
Hey @s1223 

You are simply missing a comma in your JSON!

Should be along the lines of:

```json
{
  "no_whatsapp": "890",
  "id": "123"
}
```
