### ISSUE TITLE
[Custom Components] - Component Schema should be a Component property

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#9310]
Feature : 
instead of providing an external Schema definition for a custom component, i propose the schema is defined in an internal component field. Lets assume, that every component must have a _builderScema, that exposes the exact same JSON as now defined in an external file. 

The reasoning : 
1. The component can now change / adapt its builder schema and show / hide properties. show different "options" in select inputs depending on internal state etc. 
2. The component becomes self contained and atomic.
3. Possibly the Component would also be able register Custom Property Types

**Comment by mike12345567** [comment]
Hi @poirazis - just to note, changing the schema on the fly would not be possible - the reason we used a separate JSON file was to make sure that the schema could not change/update once it has been loaded.

This is an overall limitation of the Budibase component system right now, component properties cannot change once the component has been loaded into the builder.

**Comment by poirazis** [comment]
Hey @mike12345567 
what if we were to introduce / extend a certain Property Type ( similar to type = field ) that can populate its options dynamically ?

`
{
  "type" : "select",
  "key": "selectedItem",
  "label" : "Form Steps",
  "options" : "itemsArray"
  ...
}
`

in the Forms / FormSteps combo, the Form would keep an array of its child steps and the user would be able to select from that

**Comment by mike12345567** [comment]
Hi @poirazis - in theory this could be supported - but right now the builder simply will not refresh/update component schemas once they have been loaded initially. So any changes to them would just be ignored, I'm not 100% sure on the complexities of changing this - but it would require some fairly core changes to the builder!
