### ISSUE TITLE
Navigation Menu Displaying all Links for All Users with Custom Roles

### ISSUE THREAD

**Issue by JayP718** [Budibase/budibase#9343]
Self Hosted
Linux
Latest Version

I have several custom roles in my application. I am trying to configure the links within the navigation bar to only display for certain roles. It doesn't modify the visibility regardless of what I have in the roles column within the navigation bar settings.

1. Create Custom Roles
2. Create Links within Navigation Bar only available to the custom roles.
3. Test

**Comment by shogunpurple** [comment]
Please use the bug template @JayP718 and provide an app export with a reproduction - closing this for now until we have a better issue - thanks!
