### ISSUE TITLE
Clicking Add component button should re-focus add component panel

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9349]
## Checklist
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.16

**Describe the bug**
In the builder, if the add component side panel loses focus, you cannot re-focus by either clicking add component or pressing Ctrl+Enter again.

**To Reproduce**
1. Click `Add component` (or use the key-board shortcut)
2. See that the side panel search bar is auto-focused
3. Click an empty space on the left hand-side
4. See that the side panel has lost focus.
5. You cannot re-add the focus with `Add component` action. Instead you must click into the search box.

**Expected behavior**
If I lose focus on the component side panel, I should be able to use the `Add component` action to regain focus.

**Comment by aptkingston** [comment]
We focus the field using an onmount handler here, so its not possible to refocus the field if it's already mounted I'm afraid.
