### ISSUE TITLE
Portal App List - App Icon UX fixes

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#9350]
Just when using the budi admin account I realised that there's a few little issues with updating the icons on the menu.

You cannot update an icon by just clicking it in the app list. (Below)
![Screenshot 2023-01-16 at 09.49.51.png](https://images.zenhubusercontent.com/5fd773ddf3d67d4ceebe466b/41f71af7-18cb-4ad4-9e83-0145045a5e47)
You must open the app in "Manage" to change the icon, we should allow it directly from the portal.

When you close "developer mode" - the icons are not used for apps, we fall back to the gradients, which is inconsistent. This app user app list should show the icons instead of the gradients.

![Screenshot 2023-01-16 at 09.50.33.png](https://images.zenhubusercontent.com/5fd773ddf3d67d4ceebe466b/9940e13a-cedd-4ad1-8a88-c46379d625d5)

**Comment by mike12345567** [comment]
Closing this as we are making changes to icons.
