### ISSUE TITLE
Cannot immediately navigate to Data section after adding component in Design

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9358]
## Checklist
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.15
  - App Version: 2.2.15

**Describe the bug**
UI glitch when clicking on Data section tab after adding component.

**To Reproduce**
1. Click on design tab
2. Add component -> Container
3. Click on the data tab
4. See that it does not navigate to data.
5. Click on design and back to data to get it to navigate.

**Expected behavior**
I should be able to navigate to a different section of the Budibase app after adding a component.

**Screenshots**
![tabs_bug](https://user-images.githubusercontent.com/101575380/212673932-275dfb9f-ca9e-4256-a7c0-58c06896e88f.gif)

**Comment by aptkingston** [comment]
Just to clarify that it's any immediate navigation outside of the design page (i.e. the same happens with automations) indicating that the problem is in the design section routing. Also it seems to be just one bad click - after the first click everything works as intended. So clicking twice on data for example works.

**Comment by melohagan** [comment]
> Just to clarify that it's any immediate navigation outside of the design page (i.e. the same happens with automations) indicating that the problem is in the design section routing. Also it seems to be just one bad click - after the first click everything works as intended. So clicking twice on data for example works.

Is this issue related or just a coincidence that it also requires the two clicks: https://github.com/Budibase/budibase/issues/8560
