### ISSUE TITLE
[BUD-3241] Link to plugins repo from plugins tab

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#9382]
**COS**
- Add a link to the plugins tab in the portal to make the plugins repo more discoverable
- Also update empty state to hide table

<sub>[BUD-3241](https://linear.app/budibase/issue/BUD-3241/link-to-plugins-repo-from-plugins-tab)</sub>

Empty state
![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/fe168c74-00c3-4b6a-8280-41d161aec208)

Plugins added
![image.png](https://images.zenhubusercontent.com/620a72941dd7bc25ac548dc4/2a20f9ea-4adf-4f98-84b8-790151ab195c)

**Comment by ConorWebb96** [comment]
Closing as completed
