### ISSUE TITLE
Ejecting a block removes filter 

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9385]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: bb.budibase.app

**Describe the bug**
Whenever I define a filter in a table block and eject the block, the filter is removed and I have to re-add it.

**To Reproduce**
1. Add a table block for the sample data
2. Define filters, for example: 'First Name' *Equals* *Binding* `{{ Current User.firstName }}`
3. Save that filter
4. Eject the table block
5. Click define filters of the Data Provider. The filter is there but the binding value/expression is missing and must be re-added.

**Expected behavior**
When I eject a block, my filter bindings should be persisted.

**Screenshots**
![Screenshot 2023-01-19 at 11 15 55](https://user-images.githubusercontent.com/101575380/213428655-42ffab49-5af4-4671-adb3-1f803fa19ed8.png)
*Table block filter*

![Screenshot 2023-01-19 at 11 17 31](https://user-images.githubusercontent.com/101575380/213428988-dd9919df-60b2-4674-9803-3fe3042858b5.png)
*Filter binding value/expression now gone from Data provider after ejection*

**Comment by aptkingston** [comment]
`filter` just needs marked as `nested` in the manifest - I'll add it.
