### ISSUE TITLE
Dynamic filter - selecting fields from relationship table

### ISSUE THREAD

**Issue by phaethon** [Budibase/budibase#9389]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists. There is #6550, but it seems to be obsolete as filtering by relationship fields is working

**Hosting**
- Self
  - Method: Google Cloud Run
  - Budibase Version: 2.1.42

**Describe the bug**
When I add a Dynamic filter for a data provider with a table with relationships (using PostgreSQL as the data source), I can filter by fields from relationship table. For Dynamic filter component there is a property Allowed Filter Fields. If I select any of those fields, then relationship fields disappear from the Dynamic filter. I cannot select relationship fields from Allowed Filter Fields component. Thus it is either all fields (with relationship fields) or selected fields from direct data source without relationship fields.

**To Reproduce**
1. Create 2 tables with a relationship between them in PostgreSQL
2. Create a screen with Data provider (and set source to a table), Dynamic filter (set provider to added provider, Table (set source to data provider)
3. Open Allowed Filter Fields property to see that relationship fields are not there.
4. Open Preview and see that relationship fields are visible
5. Open Allowed Filter Fields property and select any field(s)
6. Open Preview and see that relationship fields are not visible

**Expected behavior**
It should be possible to select relationship fields as part of Allowed Filter Fields of Dynamic filter.

**Comment by Nicoautoxp** [comment]
Hi, 
I'm having the exact issue that is being described here. I see that it is marked as closed but i can't seem to find way to do the dynamic filtering. Could someone point me in the right direction?
Regards, 
Nicolas
