### ISSUE TITLE
Switching between roles makes screens disappear

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#939]
**Describe the bug**
When I use the "Filter by Role" dropdown, in design, screens disappear unexpectedly

**To Reproduce**

1. Set role to Basic
RESULT 1: lots of screens appear
2. Select a component
3. Set role to Admin
RESULT 2: No screens are listed
4. Filter screens by basic again
RESULT 3: No Screens are listed

**Expected behavior**
RESULT 1: As expected
RESULT 2: Expected all the basic screens to be listed, as Admin has access to these
RESULT 3: Expected ll the basic screens to reappear

**Screenshots**
https://www.loom.com/share/62667003ac3a4dc1886ad34dea46ad39

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: electron
 - Version: 4.2

**Comment by joebudi** [comment]
I actually quite liked the fact the screens resided with their specific role. The separation was clearer.

**Comment by aptkingston** [comment]
Have fixed this in https://github.com/Budibase/budibase/pull/943 👍
