### ISSUE TITLE
If you create a view with / in the name you navigate to the design screen

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#9398]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.2.19
  - App Version: 2.2.19

**Describe the bug**
If you create a view with `/` in the name you navigate to the design screen

**To Reproduce**
1. Create a new view
2. Name the view `Apples / Oranges` or something using `/`
3. Click on the view you have just created
4. You will be sent to the design screen

**Expected behavior**
I stay on the data section and get to customise the view or `/` is not allowed in views

**Screenshots**
![budiview](https://user-images.githubusercontent.com/97764630/213694563-2d40ec4a-30d0-4369-979b-db6a1f4620cf.gif)

**App Export**
[View Test-export-1674217433334.tar.gz](https://github.com/Budibase/budibase/files/10466228/View.Test-export-1674217433334.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 109.0.1518.55

**Additional context**
You also cannot delete the view unless you rename it to something without `/`. If you click the view after you will navigate to the design screen.

**Comment by melohagan** [comment]
Fixed!
