### ISSUE TITLE
Table row button click

### ISSUE THREAD

**Issue by arpit-ma** [Budibase/budibase#9399]
Hello 
How would I make it so I can redirect the user when the click on a **row button** in the table, I essentially want it so that they click on the row button and it brings up the view page for that row.
@joebudi

**Comment by kasgithub8** [comment]
Hey @arpit-ma,

it's really simple.
![image](https://user-images.githubusercontent.com/95284278/213704924-066dc540-43bd-4e1c-8b42-2d0bc8a8ee09.png)

**Comment by arpit-ma** [comment]
**but it is showing invalid syntax** 

![Screenshot 2023-01-21 at 9 04 31 AM](https://user-images.githubusercontent.com/86701463/213841802-dde8a7f7-f661-479d-9a93-a2d91cbe1d28.png)

**Comment by melohagan** [comment]
Hey @arpit-ma 

Is that binding within the **Navigate To** action?

Possibly try this expression: `/{{ Clicked row[Auto ID] }}`

Note the extra space and removal of the '.'

**Comment by arpit-ma** [comment]
yaa i got it thanks a lot,
i have one more question can you help me with this also
like this is my database (i have attached the screenshot)
i want to make a bar chart only for cold data according to dates,
like i want to display Date and Cold count value in bar chart

**Comment by kasgithub8** [comment]
@arpit-ma No screenshot attached tho.
