### ISSUE TITLE
User Invites with Pre-loaded Roles

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#9403]
When I invite a user to the budibase platform who does not currently exist, I want their invite to be pre-filled with a role on a specific app, so that when they accept, they will automatically have access to the app I specified.

**COS**
- Users who are invited from the referral modal for a specific role on an app will have that role assigned when they accept the invitation
- Pending invites can have their roles updated from the user referral modal until the user accepts

If groups and user search endpoints need changed to allow a configurable page size, that work should be included in this ticket too.

**Comment by ConorWebb96** [comment]
I believe that this has been done.

<img width="1240" alt="Screenshot 2024-01-08 at 08 33 48" src="https://github.com/Budibase/budibase/assets/126772285/febf6f52-a518-4cf7-8f2c-ab8d2c9f55d0">
<img width="817" alt="Screenshot 2024-01-08 at 08 34 38" src="https://github.com/Budibase/budibase/assets/126772285/d0b6ddf6-a049-44a9-b0f5-671e82e574ac">
<img width="878" alt="Screenshot 2024-01-08 at 08 34 46" src="https://github.com/Budibase/budibase/assets/126772285/0fc721a1-0e87-45c0-94c8-b7ca3a4a0422">
