### ISSUE TITLE
Screen freezes when filtering by date.

### ISSUE THREAD

**Issue by kzkondo** [Budibase/budibase#9406]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.19
  - Postgres 15.1

**Describe the bug**
Screen freezes when filtering by date.

**To Reproduce**
1. Create a data provider.
2. Press Define Filter.
3. Press Add Filter and select Column.
4. For the column, select the date type of the relation destination.

**Screenshots**

https://user-images.githubusercontent.com/93172658/213859321-ddfcc932-2d83-44fc-93b9-7bc577076894.mov

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.2
 - Browser chrom
 - Version 109.0.5414.87

**Comment by melohagan** [comment]
Hey @kzkondo 

Could you provide your Postgres table schemas please?  For tables **groups** and **kouji**

**Comment by kzkondo** [comment]
Hi! @melohagan Thanks for your cooperation!
Table schema is public.
The relationship between kouji and groups is one-to-one.
groups.id is the primary key and is connected to kouji.group_id.

**Comment by melohagan** [comment]
Re-opening because it's still an issue for custom SQL queries:

![Screenshot 2023-02-20 at 10 20 04](https://user-images.githubusercontent.com/101575380/220078213-45d193e2-8286-4dd5-adec-ab99edfca715.png)
