### ISSUE TITLE
When column name in relationship is 'XToZ', the relationship type changes

### ISSUE THREAD

**Issue by ttben** [Budibase/budibase#9408]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists
I have  to admit that I  had  a lot of difficulties to find what to look for... I may have missed an issue on  this

**Hosting**
- Self
  - Method:  k8s, 
  - Budibase Version: 2.2.15

**Describe the bug**
When defining the `To column name` in a relationship, if the specified name contains the `To` keyword followed by a table name, the type of the relationship is affected.

**How to Reproduce**
I have three MySQL tables: `sources`, `clients` and `consumption`. A consumption targets a single source, and a source may be consumed multiple times and a consumption targets a single client and a client may be part on multiple consumptions.

I imported the tables and  defined a `One` relationship, from `sources(id)` to ` consumption(source)`  and I  named the `from` column `consummedBy` and the `to` column `pluggedToSources`.
I created a second `One` relationship, from `client(id)` to ` consumption(client)`  and I  named the `from` column `isWiredTo` and the `to` column `isConsumedBy`.

I autogenerated a screen and I was surprised by the result:  _**in the edit pane, I can select only one client from the dropdown (which is expected) but can select multiple sources for a single consumption!**_

After struggling, re-importing, checking if I didn't  tick a box, I renamed the `to` column of the `sources -> consumption` from `pluggedToSources` to `pluggedSources` and :boom: problem solved.

I failed to see in the doc that the name carries a semantic value or if it is an actual bug.

**Comment by melohagan** [comment]
Hey @ttben 

Could you provide some screenshots please?
