### ISSUE TITLE
Auto Selection of Form Fields

### ISSUE THREAD

**Issue by kerbersystems** [Budibase/budibase#9413]
**Describe the feature request**
It would be nice to have a form field auto-selected after a step change or reload. Fro example, a text field would automatically have the cursor selected to allow for immediate typing. This is very useful for scanning of barcodes or numbers as the user would not have to click into the field to enter a value.

**Comment by kerbersystems** [comment]
I believe this could be added using the is-keyboardFocused class attribute.

**Comment by shogunpurple** [comment]
Dupe of https://github.com/Budibase/budibase/issues/9699
