### ISSUE TITLE
Form Builder

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#945]
When I am creating budibase apps, I want to be able to generate a form from a table or query, as well as to be able to create completely custom forms, so that I can retrieve data input from my users and perform actions with it.

#### Features
- Forms will have a context, with some information about the form (validity etc)
- Feedback on failed form validation
- Wide form and standard form will be replaced with a single FormBuilder component

#### Form builder
- User creates form builder component
- User binds form builder component datasource in the settings panel (query, table), or chooses a "custom" form
- If table, fetch the schema and render inputs for it in the component nav
- if query, fetch the parameters and render inputs for them in the component nav
- You can then reorder and change the order of fields as well as properties within them from the nav

Input components inside a form builder context will have different properties in settings panel than standard input components.

#### Validation
Users need to be able to add validation to a form field inside a form builder context. Based on complexity this can be through premade validations (email, regex etc) or even a javascript expression to validate the form fields. (or both) Eg.
```
value => value.length === 5 && {{ !formContext.error }}
```

**Comment by mjashanks** [comment]
Expanding on the above with my thoughts, and linking up to some other issues.

**Form context**
I'm not sure what we mean by this.

**Total control over form component**

- Should be able to remove fields on the form - logged as #789
- Should be able to add fields to the form. This should be minimal effort. E.g.  

a) Add Select Field
b) Pick "Status" field from the list. (Status is an options type)
RESULT: A select, with a label

- Should be able to change the order of fields on the form.
- Should be able to layout fields inside the form. Related to #956  E.g. 

Title: _____    First Name: ________     Last Name________ 
Email: ___________
Phone: __________

**Feedback on failed form validation** - depends on #967

**An additional requirement** - should be able to prefill fields from URL parameters already logged as #955

**Comment by mjashanks** [comment]
Just pointing out - if the Form has a data source, then this may eliminate the need for the "NewRow" and "RowDetail" components:
- NewRow creates a JSON object with the schema of the selected data source, and make it available to all it's children, for binding.
- RowDetail fetches the row, and makes it available to the children.

If this becomes the role of the form, then we don't need these components. They are currently used as the root element for New Row and Row Detail screen templates

**Comment by aptkingston** [comment]
> Just pointing out - if the Form has a data source, then this may eliminate the need for the "NewRow" and "RowDetail" components:
> 
> * NewRow creates a JSON object with the schema of the selected data source, and make it available to all it's children, for binding.
> * RowDetail fetches the row, and makes it available to the children.
> 
> If this becomes the role of the form, then we don't need these components. They are currently used as the root element for New Row and Row Detail screen templates

Good point. NewRow won't be needed since it can just be replaced by a Form with a datasource of the correct table, but RowDetail will still exist pretty much as it is today - providing a datasource which the Form will use.
