### ISSUE TITLE
Multiple clicks on form submit button fires multiple duplicated actions

### ISSUE THREAD

**Issue by stearm** [Budibase/budibase#9450]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.22
 
**Describe the bug**
Action button is not disabled when the action is fired: if I click multiple times on a button that insert a record into a table, I'll find multiple rows in it. I can't figure out how to do that.

**To Reproduce**
See attached video. Create an autogenerated screen, select an example table and the try to add rows clicking multiple time on the form submit button.

**Expected behavior**
Button should be disabled

**Screenshots**
![Screenshot 2023-01-26 at 12 09 05](https://user-images.githubusercontent.com/14802795/214822743-fd8282cf-8b32-49be-a705-2fb6f773574b.png)

https://user-images.githubusercontent.com/14802795/214822732-a6cf42ef-5648-4aec-9086-d2bb9c127a59.mov

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.2 (Monterey)
 - Chrome
 - Version 109.0.5414.87

**Comment by melohagan** [comment]
Fixed!
