### ISSUE TITLE
[BUDI-6449] Filter Data Provider (with 2 criteria) based on view -> no results

### ISSUE THREAD

**Issue by serelsnauw** [Budibase/budibase#9473]
Hi guys,

When I filter a Data Provider with a table-view as source ("match any filter", with 2 criteria)  I get no rows found.
When I change the source of the data provider to the original table (in stead of the table-view), I get the desired results.

As I change the filter to 1 criteria (with the table-view as data provider source) I'll get results. So the problem exists when I use the table-view (tested with some filters, or no filters at all) as a source for my data provider, and use 2 criteria as a filter for that data provider.
I need this kind of filtering to get records with a "open" status, and filter these rows based upon the location(s) from the current user (a relation-column in the user row).
So the table-view filters the "open" records, and the data-source in the screen filters the location matching the current user locations.

 ----------------
**Hosting** As well Cloud hosted (at budibase.app) as own Docker single image
- Self
  - Method: docker single image
  - Budibase Version: 2.2.22
- Cloud (budibase.app)

**Expected behavior**
Getting rows matching the view-filters, as well the data-source filters

**Desktop (please complete the following information):**
 - OS: Kubuntu Linux 20.04
 - Browser: Firefox 109.0 | Chromium 109.0.5414.119

Hope this info covers the information needed, else i would be happy to provide some more detailed information / screenshots etc.

Grtz Serel.

<sub>[BUDI-6449](https://linear.app/budibase/issue/BUDI-6449/filter-data-provider-with-2-criteria-based-on-view-no-results)</sub>

**Comment by aptkingston** [comment]
Views don't support the "match any" feature. We're doing a lot of work on views in the upcoming months and this will be included as part of that work.
