### ISSUE TITLE
Developer(role) users are not able to invite users. 

### ISSUE THREAD

**Issue by MihailHadzhiev2022** [Budibase/budibase#9474]
As a developer user I should be able to invite new users. 

**To Reproduce**
1. Sign in to Budibase as a developer User

Expected result: Developer user should see "Users", and should be able to add new Users
Actual result: Users is missing 
![Screenshot 2023-01-30 at 12 06 18](https://user-images.githubusercontent.com/102024164/215447683-7efe192f-1de3-40f3-b200-521bdac9020b.png)

**Comment by aptkingston** [comment]
Just clarifying that this isn't a bug, but by design. In the new portal design developers have read-only access to the users page. If we want to let developers add users to the platform then that's a new feature.

**Comment by mike12345567** [comment]
This has been updated as part of the update to allow builders to invite users from within the app building experience.
