### ISSUE TITLE
Deep links into app from EMails not working

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#9476]
Hosting: On-premise, 9 Docker container deployments with Budi-CLI tool, Version: 2.2.22

We use automations to email Budibase users about changes in the app, especially row updates.

We generate links like: https://budibase.our-org.com/app/example-app/#/194

We see a behavior especially at users using multiple Budibase, that use that link. They are logged out of Budibase even though they were previously logged in. What happens is and very undesired behavior, they see the public pages of the app, then click and on login and get redirected to the normal Budibase login page and after login they are redirect to the standard user app page, for example: https://budibase.our-org.com/builder/apps . The desired behavior is that they get linked to URL above, deep in the selected app and the per mail notified data row.

We get a lot of customer complaints about that.

We think a similar requests are: https://github.com/Budibase/budibase/issues/6798 , https://github.com/Budibase/budibase/issues/4161 and https://github.com/Budibase/budibase/pull/4022

Please look at this request.

**Comment by shogunpurple** [comment]
@kasgithub8 please raise a better issue, and fill out the issue template. You haven't provided steps, a reproduction or anything at all here. Closing

**Comment by dewdeded** [comment]
Ok, I will do that.
