### ISSUE TITLE
[BUDI-6443] API REST Queries: Optional or Nullify Param if not available

### ISSUE THREAD

**Issue by diegoarda** [Budibase/budibase#9486]
Describe the feature request
An option to omit API query parameters altogether if they are not set or are bind to null.

Use case
Sometimes, certain parameter values are optional or not available yet, but budibase sends them anyhow which makes some APIs return errors if a parameter contains a non-usable or empty value.

Even sending the binding's default value in this case won't help, since the API will return an error, as for some parameters default values don't make sense.

Example
An API endpoint that returns all applications by default:
https://myapi.com/applications

And the same api, when a filter is applied, add query param with the search
https://myapi.com/applications?search=name

The endpoint doesn't admit empty values for the queryparam search. If it's informed, it expect a reported value.

<sub>[BUDI-6443](https://linear.app/budibase/issue/BUDI-6443/api-rest-queries-optional-or-nullify-param-if-not-available)</sub>

**Comment by shogunpurple** [comment]
Please fill out the bug issue template with a fresh reproduction to help us debug - closing for now. Thanks
