### ISSUE TITLE
[BUDI-6448] Duplicate user accounts in database as a result as readding previously deleted account

### ISSUE THREAD

**Issue by accesstechnology-mike** [Budibase/budibase#9496]
**Hosting**
- Self
  - Method: docker
  - Budibase Version: 2.2.19

**Describe the bug**
Duplicate user accounts present, after adding user who was previously deleted.

![image](https://user-images.githubusercontent.com/55278705/215838794-be7cd910-b23b-45b3-828e-3d9c4c7253f8.png)
![image](https://user-images.githubusercontent.com/55278705/215839055-31cec1e2-54e7-4b91-8df9-7c8b143aa998.png)
![image](https://user-images.githubusercontent.com/55278705/215839194-47acdc99-3be9-4453-afa1-f7e595142385.png)

**To Reproduce**
1. Add a user
2. Remove user. System displays no records of users in BB internal database
3. Add user again
4. User appears twice in 

**Expected behavior**
User is removed when deleted, so that is not replicated when added again. 

<sub>[BUDI-6448](https://linear.app/budibase/issue/BUDI-6448/duplicate-user-accounts-in-database-as-a-result-as-readding-previously)</sub>

**Comment by mike12345567** [comment]
Hi @accesstechnology-mike - closing this issue as we have https://github.com/Budibase/budibase/issues/10216 where we will be tracking the work to update the sync system.
