### ISSUE TITLE
UX - Not obvious that we have to click on "PAGE" to get back to the page properties

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#95]
See below... when we are viewing a screen, and want to get back to Page, it is not obvious that we must click "PAGE" ... its doesnt look like a link and it has no `:hover` style change.

In general, its just a bit confusing that we have the page dropdown at the top, that selects the page.... and then this other "PAGE" text which feels a bit random

![image](https://user-images.githubusercontent.com/3524181/74341042-fe02f680-4d9e-11ea-9c26-94cb2c0540e6.png)

maybe worth considering alongside #93

**Comment by joebudi** [comment]
@mjashanks what about this:
https://xd.adobe.com/view/c518ff96-8a82-418e-6f37-ca39bf169c91-b329/?fullscreen

**Comment by shogunpurple** [comment]
Looks like this one has been done.
