### ISSUE TITLE
App state binding does not work as expected

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9502]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.23

**Describe the bug**
Following through this tutorial: https://docs.budibase.com/docs/tag#removing-tags

There is this **Update State** action:
![image](https://user-images.githubusercontent.com/101575380/216049074-b130d2ca-d73c-4cfe-bfd8-e5e1551d79f0.png)

With this JavaScript binding:
```js
let removedTags = $("State.RemovedTags") || {};
removedTags[$("Tags Repeater block.Tags._id")+$("Repeater.Movies._id")] = true;
return removedTags;
```
*I also tried* `let removedTags = $("State.RemovedTags") ? { ...$("State.RemovedTags") } : {};` *just incase, but same issue*.

I would expect the `removedTags` to append a field, and not be a brand new object:
![fast_close](https://user-images.githubusercontent.com/101575380/216051210-878b0e3a-7d78-4045-9efc-426368ae877b.gif)

**To Reproduce**
1. Follow through the tutorial (or you can use the app export provided below).
2. Preview the app and see that two actions cannot be removed.
3. Click `Define actions` of the Tag component
4. In **Update State**, edit the JS binding. Remove the `$("State.RemovedTags")` reference and re-add it via the bindings helper menu. Click `Save`.
5. Preview the app again. Both tags can now be removed, despite the binding code being identical.

**Expected behavior**
It appears to me that because I am setting the **RemovedTags** state variable at the same time as trying to reference it, the actions are saved without the binding mapping. 
The save button should figure out if a state variable is being created, and make sure any references are pointing to that state variable. 
  
**App Export**
[Tag tutorial-export-1675255767246.tar.gz](https://github.com/Budibase/budibase/files/10557237/Tag.tutorial-export-1675255767246.tar.gz)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by melohagan** [comment]
@aptkingston The reason that worked for you was because the state variable was already created at that point. I have a PR out for the bug fix, which includes a GIF that should hopefully highlight the problem more clearly!

**Comment by aptkingston** [comment]
The state variable is undefined actually initially (here's a video to show):

https://user-images.githubusercontent.com/9075550/216089104-a03fe254-296b-4d14-b095-2a047f07c7be.mp4

But I'll check out this PR!
