### ISSUE TITLE
Make Internal Database Tables Dynamically Searchable

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#951]
- Mark table fields as searchable
- Use these searchable fields in a couch index

### Marking fields as searchable
A user should have the ability to mark columns in a table as "searchable" or "indexable". This will: 
- Add that key to a couch search index
- Allow those searchable fields to be used in the query component
- Columns will be marked as searchable in the settings modal for the column, and on column creation

### Design Section
- User can use the same UI as external data sources to bind dynamic values from the frontend to searchable fields, allowing you to query those fields dynamically and even change your mango query
- For each argument to the query, we should allow default values if the argument is null/empty

**Comment by mjashanks** [comment]
You should first note that everything I say below is a look into the future of where I think this can go to - not necessarily everything that we must do now. We must consider some of the uses I mention below **now**, as they could be fundamental to the architecture.

I will start with the external data sources, as I believe that the separation between the database configuration and it’s queries is correct.

I will add to this, by saying that in the future we are likely to have multiple “Types” of query:
- “List” - returns a collection of rows. 
- “Update” - updates one or more rows.
- “Find” - returns a single row.
- “Delete” - is a possibility, but probably falls under “update” (?)

![image](https://user-images.githubusercontent.com/3524181/103639404-39258f80-4f46-11eb-96c5-b01df196ecba.png)

So, my suggestion is to mirror this format with Budibase internal tables.

![image](https://user-images.githubusercontent.com/3524181/103639605-7ab63a80-4f46-11eb-8dd3-c0289ac84d17.png)

So, when the “Deals” table is created, we automatically get 3 default “Queries”
- All Deals. Unfiltered list of deals
- Save Deal. A query that accepts all deal columns as parameters
- Get Deal. Accepts an Id parameter, and returns a single record.

Reasons for this suggestion

**Consistency**
Internal tables are now consistent in behaviour, with external data sources. The queries are where you get your data.

This is actually how Airtable does this - when using Airtable, you are always looking at a view.

**Security Control**
When applying access levels rules, we only have to apply them to these queries. This is simple and gives us more granular control over data.

Examples
1. We could create a query called “My Deals”. We could then set up the system to only allow Basic users to see “My Deals”.
2. We could create a query called “Approve deal”, which accepts an ID, and updates the deal’s status to “Approved”. This means that we could allow certain user levels to Approve the deal, without giving them full access to update the deal details.
3. We could create a query that only returns certain columns. This would allow us to restrict the visibility of columns to certain access levels.

**Setting Default column values**
We could modify the default “Update Deal” query, to 
automatically set some column values
don’t allow these column values to be set by user input

The obvious example is timestamping. A timestamp could always be set on row creation, and never be settable by the user.

**Record Level Security**
A very common ask, is to able to set up a structure like:

“Projects” (parent table) have “Issues” (child table) 
I want Bob only to have access to Issues that belong to the “Brexit Project”.

I know that we are a long way of this. However, the above table/query structure would allow us to create a query called “Issues for Project”, that accepts a “Project ID” as a parameter. 

There is more to solving this problem than this, but it is a good start.

**Comment by shogunpurple** [comment]
Great write up - a good bit to think about here. My thoughts:

### External Data Sources
Totally agree there should be query types. It means you can filter out a bunch of queries where they don't make sense. Ie. UPDATE queries as datasource in a grid etc.

For dynamic queries here, I think we should extract values from both the **frontend and the backend**. For example, you might have a query like this:

```
select * from {{ serverside.someSecretValue }} where name = '{{ someUiComponent.value }}'
```

This would require us to inject the client context into the query and possibly pass it to the backend, allowing for totally dynamic query capabilities. I'm experimenting with this kind of stuff in the work I'm doing at the moment for https://github.com/Budibase/budibase/issues/886.

### Internal Queries
Due to the restrictions on views in couch, it would be hard to provide a completely dynamic query against an internal table without rebuilding the index. However I can see a lot of merit in a separate "query view" which lets you play around with some query syntax and read data out of your already indexed fields in the DB using mango.

### Security
A lot of people have asked for complicated IAM, but the way security has been designed, we can hopefully do a lot of that through middleware. Ie. on every operation, check if you are allowed. This would apply to values at any level - table, record etc
