### ISSUE TITLE
Many to Many random constraint failures

### ISSUE THREAD

**Issue by royaljeffr** [Budibase/budibase#9512]
I am receiving random errors when checking and unchecking a Dropdown box that pulls from a join table.  Here is my Postgres schema.

```
CREATE TABLE IF NOT EXISTS public.titles
(
    title character varying COLLATE pg_catalog."default",
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 112 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT titles_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.titles_attributes
(
    type character varying(50) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 396 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT titles_attributes_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.titles_attributes_join
  (
        title_id integer NOT NULL DEFAULT,
        title_attribute_id integer NOT NULL DEFAULT,
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 4061 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        CONSTRAINT uq_title_attribute_ids UNIQUE (title_id, title_attribute_id)
        INCLUDE(title_id, title_attribute_id)
)
```

And then in Budibase I have this for my JOIN
![image](https://user-images.githubusercontent.com/49763873/216198850-a7530aa6-29d1-4463-b93a-a9154fbb7da4.png)

Then when I go to the Autogenerated screen and change the values from the picklist I get error message - error: duplicate key value violates unique constraint "uq_title_attribute_ids".  I can verify at the database level there no duplicates.  And when I get that message it usually deletes all the record associated with that title.
![image](https://user-images.githubusercontent.com/49763873/216199657-0fb16b4a-53d1-4118-a0d5-360d3e7d0f3e.png)

**Comment by melohagan** [comment]
Hey @royaljeffr 

The next release which will be within the next week or so, will improve the relationship modal.

In this case the validation should have prevented you from saving without setting foreign keys.
