### ISSUE TITLE
Budi Day Bug List

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#952]
- [x] **Boolean fields do not work in "Define Actions" panel. Type error**
- [x] **Rename true/false to Boolean**
- [x] **Save row automation does not run on update**
- [x]  **Saving a user with the same email address is allowed**
- [x]  **Using dots in a column name causes the column to not be displayed**
- [x] **Editing a row via AG grid view will make a request api/undefined/rows/undefined PATCH request**
- [x] **Editing things inline strips newlines, even if you were using the binding interface with newlines before**

**Comment by shogunpurple** [comment]
bump

**Comment by kevmodrome** [comment]
I'll sort out the AG grid undefined thing

**Comment by aptkingston** [comment]
Boolean fields do work in the actions drawer now thanks to the handlebars `literal` helper - eg `{{ literal true }}` is a boolean true rather than a string true, so I'll check that off

**Comment by kevmodrome** [comment]
I can't reproduce the AG Grid issue. Checking that one off.

**Comment by aptkingston** [comment]
> I can't reproduce the AG Grid issue. Checking that one off.

Yea I think I actually fixed this a couple of weeks ago. I added some better validation to the client API so that it wouldn't fire off requests with invalid params.

**Comment by kevmodrome** [comment]
Awesome. I'm taking a look at the one where rows don't show up when using dots in column names.

**Comment by aptkingston** [comment]
Nice. I'm updating the client components to preserve white space.

**Comment by aptkingston** [comment]
Have fixed the component whitespace, and also fixed the validation when creating users with duplciate emails. I'll PR from a bug fixing branch soon.
