### ISSUE TITLE
Ability to mark relationships as 1:N

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#953]
Ability to mark relationships as 1:N in the UI and validate that only one element is added. Only allow one option in multi select.

- Add schema validation for it on the backend
- Option for it on the frontend
- Client side search/autocomplete on relationship dropdowns. When using a multi select in a form or other elements that allow you to assign relationships, a 1:N relationship will only allow you to choose one option.

**Comment by doughnet** [comment]
Wanted to se on the status of this integration.

Will this also resolve how relationships are displayed??

**Comment by shogunpurple** [comment]
Hi @doughnet  - we should have this one finished in the coming week. Thank you for your patience.

**Comment by shogunpurple** [comment]
We discussed this one internally and have decided that the following is the best approach: 

- Rename the repeater to become a more all encompassing data provider component. This is due to the fact we cannot recursively fetch constant children of every single transitive relationship. This means users will have to use that component to bind to a relationship, even if it only has one element. We can provide help and docs around this to make it more obvious
- Ensure the form builder shows a select instead of multi select for 1:1 relationships
- Enable the ability to set a relationship to 1:N, 1:1 in the data section of the builder

**Comment by doughnet** [comment]
Awesome! Can't wait.
