### ISSUE TITLE
bb-alert: No JWT Secret supplied, cannot configure JWT strategy

### ISSUE THREAD

**Issue by switchupcb** [Budibase/budibase#9537]
**Hosting**
- Self
  - Method: https://docs.budibase.com/docs/budibase-cli-setup
  - Budibase Version: 2.2.26

**Describe the bug**
Every time the `budi` command is run, this alert appears.

**To Reproduce**
Node: v18.14.0
Docker: version 23.0.0, build e92dd87
`docker compose`: Docker Compose version v2.3.3
`docker-compose`: docker-compose version 1.29.2, build unknown

**Expected behavior**
No alert upon running after installing `docker-compose` (v1) as specified in https://github.com/Budibase/budibase/issues/8531.

**Comment by switchupcb** [comment]
Using `budi hosting --init` fixes the problem.

**Comment by shogunpurple** [comment]
@switchupcb did you run `budi hosting --init` first like in the docs?

**Comment by switchupcb** [comment]
I typed `budi` after `npm install -g ...` and it started showing the alert.

**Comment by mike12345567** [comment]
Hi @switchupcb - this is resolved in latest versions of CLI.
