### ISSUE TITLE
Option Picker layout in side panel

### ISSUE THREAD

**Issue by gyoung41** [Budibase/budibase#9552]
**Hosting**

- Self
  - Method: docker compose 
  - Budibase Version: 2.2.19
  
**Describe the bug**
When adding option picker component to a side panel (generated from auto create screen) the option picker does not display in the same width to the other fields when located in the Field Group component. Appears to place the drop down selection in the same column as the label. 

**To Reproduce**
1. create a screen using the auto approach from a database table (where side panel auto created for editing record)
2. Add option picker component to the side panel within the Field Group component used to edit the record selected.
3. Leave width to Auto or set a width
4. Option Picker selection does not span across the width and is forced into the label column width

**Expected behavior**
Expect to see the selection aligned vertically to use the width of other field inputs on the side panel

**Screenshots**
![image](https://user-images.githubusercontent.com/76951140/217066547-92689bcd-3a27-4938-b968-f58a545322b0.png)

  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome or Edge

**Comment by joeshajan** [comment]
I would like to fix this issue. Can someone assign this to me?

**Comment by aptkingston** [comment]
Hey @gyoung41. I'm unable to reproduce this. If you add an options picker inside a field group it will correctly display itself:
![image](https://user-images.githubusercontent.com/9075550/217191975-585596c0-c05c-47f1-a202-65dd94ece088.png)

Setting any sort of width style has no effect when your field group is using left-aligned labels.

Could I see a screenshot of your component tree? This would only happen if you had nested some other component inside your field group that was not a form field, for example:
- Field Group
  - Container
    - Options Picker

**Comment by gyoung41** [comment]
Hi - here is the screenshot of the options picker in the field group:

![image](https://user-images.githubusercontent.com/76951140/217205204-6bf60958-a692-4d3e-990f-e4344b62c8dd.png)

and here is a duplicate of this screen with the Options Picker outside the field group at the bottom of the side screen:

![image](https://user-images.githubusercontent.com/76951140/217205519-dfabe10d-24c7-433c-b8d9-2f16b98a73b9.png)

Here are the two component trees:
Inside Field Group: 
![image](https://user-images.githubusercontent.com/76951140/217205747-450f8423-3487-4910-b59c-498cc3043d1a.png)

Outside Field Group:
![image](https://user-images.githubusercontent.com/76951140/217205892-3d598286-a881-44ec-907b-6553e8f08854.png)

Hope this helps

**Comment by aptkingston** [comment]
This is because of the data provider that's wrapping the options picker - nothing should be directly inside a `FieldGroup` component other than actual fields. You can fix this in a few ways, but the easiest is probably just moving the `CurrencyData` data provider up so that it wraps the entire `FieldGroup` component.

Other solutions include:
- Change the field group to use labels above the fields, instead of left
- Put the new options picker outside the field group

**Comment by gyoung41** [comment]
okay  got it. We had moved it down and that made it work but we had not tried holding it above the FieldGroup. We are very new to Budibase and only just getting to grips with the component tree - so thanks for taking the time to explain.
