### ISSUE TITLE
[BUDI-6437] Export to csv from PostgreSQL table fails

### ISSUE THREAD

**Issue by megatron757** [Budibase/budibase#9553]
**Hosting**
- Cloud
  - Tenant ID: ankr.budibase.app
  - App version: 2.3.0

**Describe the bug**
Attempting to export data as a csv from a PostgreSQL table produces error "tableName is not defined" and "there was an error exporting the data"

**To Reproduce**
1. Add data provider > Change Data dropdown to psql table
2. Add table component, point at data provider > Allow row selection on table
3. Add button
4. Define action for Export Data 
5. Table: table created in step 2
6. Export as CSV
7. Export columns: All columns

**Expected behavior**
I expect to cilck the button and a csv file with table data downloads in my browser

**Screenshots**
![Screen Shot 2023-02-06 at 1 54 15 PM](https://user-images.githubusercontent.com/106602832/217071895-81fa4b15-d687-4318-8828-5c14bdab7669.png)
![Screen Shot 2023-02-06 at 1 51 16 PM](https://user-images.githubusercontent.com/106602832/217071896-f89b23fd-645c-4b48-b836-ff60b967b63f.png)
![Screen Shot 2023-02-06 at 1 51 32 PM](https://user-images.githubusercontent.com/106602832/217071898-dbc8da1d-96ad-4cad-9180-c09dd0b9c1de.png)
![Screen Shot 2023-02-06 at 1 50 57 PM](https://user-images.githubusercontent.com/106602832/217071903-71cd4089-16fc-4ad1-8cad-bd59d36ba065.png)
![Screen Shot 2023-02-06 at 2 21 24 PM](https://user-images.githubusercontent.com/106602832/217076795-b9006f0b-fe21-41a2-a20e-25bd53e4c738.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 109.0.5414.119 (Official Build) (arm64)

**Additional context**
This appears to indicate that the button is correctly grabbing table information to export: 
DevTools > Export button > Bindings > Category > Selected rows: 
`{"tableId":"datasource_plus_0b7cbc90637b4440869c7fc40140b6d7__employees","selectedRows":["%5B60132%5D"]}`

The Export to CSV functionality was working correctly recently - no changes that I am aware of. This issue persists with all PostgreSQL tables connected to the budibase instance. Other actions such as saving a row on the PostgreSQL table work correctly.

<sub>[BUDI-6437](https://linear.app/budibase/issue/BUDI-6437/export-to-csv-from-postgresql-table-fails)</sub>

**Comment by shogunpurple** [comment]
First of all thank you for filling out such a detailed and solid issue. I've been able to reproduce this - we will aim to get a fix out for it ASAP.

**Comment by melohagan** [comment]
This has been fixed as of **2.3.6**.
