### ISSUE TITLE
[BUDI-6435] Numberfield accepting characters in firefox

### ISSUE THREAD

**Issue by SuperKebabie** [Budibase/budibase#9555]
**Checklist**
- [check ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> 
  - Budibase Version: <version> 
  - App Version: <version> 

**Describe the bug**
While viewing the application (in preview or publish mode) in firefox Numberfield inputs accept character inputs. Upon saving the form does not return any issies and returns the saved succesfully notification. However it does NOT save these inputs. I tested it in chrome and here you are not allowed to input character values in a numberfield so i think it's a firefox only bug.

**To Reproduce**
1. Go to firefox
2. Click on "Add screen"
3. Generate a screen with numberfield inputs
4. Preview or publish app
5. Input a number value with text Example: "12 m"
7. See error

**Expected behavior**
I either expect not being able to fill in text values at all or upon saving getting a return that Numberfield x contains unsupported values
[TIL HQ Civil Infrastructure-export-1675758150080.tar.gz](https://github.com/Budibase/budibase/files/10672939/TIL.HQ.Civil.Infrastructure-export-1675758150080.tar.gz)

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/31392845/217189997-a9a062f8-0a4f-46b3-a2a7-1cecfbc0628f.png)
![afbeelding](https://user-images.githubusercontent.com/31392845/217190147-051acee6-e474-4926-b811-b56b34b3bd93.png)
No values
![afbeelding](https://user-images.githubusercontent.com/31392845/217190208-00c4a400-e0ff-480e-b106-8a1137abcf88.png)

  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser Firefox
 - Version 109

<sub>[BUDI-6435](https://linear.app/budibase/issue/BUDI-6435/numberfield-accepting-characters-in-firefox)</sub>

**Comment by aptkingston** [comment]
Hey @SuperKebabie. This is correct behaviour for Firefox - they allow characters to be typed in `number` inputs but it does not actually affect the value saved.

Here's the upstream bug from Mozilla's own bug tracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1398528

Rest assured that the value saved does not contain any characters - it's just a visual thing.

**Comment by SuperKebabie** [comment]
Thanks for your help! Yup, it's just a bit annoying.. Sadly we'll just have to deal with it for the time being!!

**Comment by aptkingston** [comment]
Yep I totally agree! Hoping they change it at some stage, but the issue has been open for 6 years so who knows.
