### ISSUE TITLE
[BUDI-6556] [BUDI-6436] 2.2.15 - 2.3.0 MySQL (Can't alter table columns) 

### ISSUE THREAD

**Issue by insomniacj93** [Budibase/budibase#9557]
After the Update ( not sure which ) I'm no longer able to alter data types and such in the budibase backend.

The issue appeared when i tried to change the Text datatype to Long Form text, but when selecting any other type of data, it simply won't select it. Even if i add a limit of characters, it won't save.

I've tried fetching the tables again many times.

The issue prevails and seems like something that happened before.

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/df4327c8-9fec-415f-b70f-02aac2a075b2/6345c25b-9bf3-460d-b2e9-314457f8e3c1)

MySQL
Budibase 2.2.15 - 2.3.0
Docker-Desktop 4.16.3
OS - Windows 11

Best, Insomniac.

<sub>[BUDI-6436](https://linear.app/budibase/issue/BUDI-6436/2215-230-mysql-cant-alter-table-columns)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6436](https://linear.app/budibase/issue/BUDI-6436/2215-230-mysql-cant-alter-table-columns)</sub>

**Comment by insomniacj93** [comment]
Workaround:

I deleted the column and created a new one with the same name but with Long Form Text.

This issue I'm having applies to not only MySQL, but also budibase db apparently.

Not sure what might have caused it, but I cannot edit columns.

**Comment by insomniacj93** [comment]
Could be related to same issue:
https://github.com/Budibase/budibase/issues/9602#issue-1577025984

**Comment by mike12345567** [comment]
Hi @insomniacj93 - I've tried re-creating this on the latest version (2.3.12 released yesterday) and it appears to be resolved, can you confirm this?

**Comment by insomniacj93** [comment]
@mike12345567 Sorry for the late reply mike!

I confirm it is working, just updated to the newest version 2.3.16!

Thank you very much!
