### ISSUE TITLE
[BUDI-6440] After updating from 2.2.23 to 2.3.0, I can no longer access from my smartphone

### ISSUE THREAD

**Issue by kzkondo** [Budibase/budibase#9558]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.3.0

**Describe the bug**
After updating from 2.2.23 to 2.3.0, I can no longer access from my smartphone.
Strictly speaking, I can access it, but the login screen is not displayed on a black screen.  

**Desktop (please complete the following information):**
 - OS: iOS 16.3
 - Browser chrome, safari
 - Version chrome 109.0.5414.112, safari latest

<sub>[BUDI-6440](https://linear.app/budibase/issue/BUDI-6440/after-updating-from-2223-to-230-i-can-no-longer-access-from-my)</sub>

**Comment by aptkingston** [comment]
Hey @kzkondo. I think this is probably due to the regex issue that was fixed here: https://github.com/Budibase/budibase/pull/9548. That fix has been pushed to cloud but it hasn't be released for self hosters yet. Expect it to go out soon :+1:

**Comment by kzkondo** [comment]
Hi! @aptkingston Thank you for your reply. Looking forward to the release.

**Comment by shogunpurple** [comment]
Will kick off the release now!

**Comment by kzkondo** [comment]
@aptkingston Is it also uploaded to docker hub?

**Comment by AlejandroFNadal** [comment]
@shogunpurple Hi, quick question. Pressing on the "Check for updates" button in the budi interface and running "budi hosting update" in the terminal, are equivalent?
