### ISSUE TITLE
Custom CSS Input

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#958]
- Custom CSS box at the bottom of the design panel for a component

**Comment by otavio99** [comment]
Hi, I've been trying to add a custom styling though the custom css for a label of a form, but no matter what css I use, nothing happens. I tried looking for documentation or tutorials on the matter but so far, I found these:
- https://github.com/Budibase/budibase/discussions/3079
- https://github.com/Budibase/budibase/discussions/2391
- https://github.com/Budibase/budibase/discussions/4331

They more or less give an idea of how to do it, but its not very insightful. I'd like to know more how to set custom css on the components and have a documentation for it if possible
