### ISSUE TITLE
[BUDI-6467] [BUDI-6468] A table block properties is missing the "Define Action" buttons

### ISSUE THREAD

**Issue by lukuser** [Budibase/budibase#9590]
* Self
  * Method: docker compose
  * Budibase Version: 2.2.19

**Describe the bug**
A table block properties is missing the "Define Action" buttons for the button or the row click.

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/783773eb-a45f-4f9f-b770-e776024d9651/40ee7336-c065-4a2d-ae2e-e6db6190b619)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/b1845c73-93a7-4ab7-9003-bd9d6276d8c2/86fb0e19-f15b-478a-84c1-fa6e99658046)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f5d01bcc-a1ce-4bc1-9ee5-c87dcb454211/72f06ced-c384-4cdf-b2e5-1ea496123008)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6467](https://linear.app/budibase/issue/BUDI-6467/a-table-block-properties-is-missing-the-define-action-buttons)</sub>

**Comment by lukuser** [comment]
Update: I created a new tableblock and the buttons are there. The old table block was there when the version was 2.1.42 and the project was exported/reimported a few times. The tableblock must have "lost" it's "Define action" buttons during an update or an import. I now find some other tables and tableblocks in my app missing the buttons, but not all.

**Comment by aptkingston** [comment]
Hey @lukuser. Can you try changing the "on click" setting to the other option, then changing it back? e.g. click "show side panel", then change it back to "run actions". I have a feeling that will fix it.

Your settings will still be there - it's just not showing them.
