### ISSUE TITLE
[BUDI-6518] Redis query command doesn't accept spaced values 

### ISSUE THREAD

**Issue by SemanticInheritance** [Budibase/budibase#9622]
**To Reproduce**
1. Go to 'Redis add query'
2. Function: 'redis command'
3. Query: (SET myKey Keyvalue) but SET myKey "Key spaced value" doesn't
     + When sending the query the values keeps beign split by space
     + Tried using ', `, \ to escape the spaces doesn't work
     + Tried having the value as a binding also fails
This is a problem since i want to work with other redis data types but can't have a custom command with a value containing spaces

Tried the following
```
SET myKey "spaced phrase"
Serverside: "set" "myKey" "\"spaced" "phrase\"""

SET myKey `spaced phrase`
Serverside: "set" "myKey" "`spaced" "phrase`""

SET myKey \spaced phrase\
Serverside: "set" "myKey" "\\spaced" "phrase\\""
```
Any way to stop budibase from splitting the command and allow raw execution on some parts with query?

**Comment by melohagan** [comment]
You can use the 'CREATE' query in this case:

![Screenshot 2023-11-09 at 15 23 33](https://github.com/Budibase/budibase/assets/101575380/085e6bc2-d4db-45bc-abe2-d66424d7666b)

![Screenshot 2023-11-09 at 15 23 06](https://github.com/Budibase/budibase/assets/101575380/bb42f602-fc8e-45ff-9330-e68787e6174b)
