### ISSUE TITLE
[BUDI-6520] Cannot see which Datasource was selected for a Data provider 

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9623]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.3.0
  - App Version: 2.3.0

**Describe the bug**
When the value of the *Data* property in a Data provider is long, you cannot tell what the datasource is. When you expand the drop-down, no option is selected.

**To Reproduce**
1. Add a data provider and select a long datasource, such as a relationship source.
2. See that the name is cut-off, and no option is ticked in the drop-down.

**Expected behavior**
A data provider datasource should have a tick beside it once selected.

**Screenshots**
![Screenshot 2023-02-09 at 11 43 07](https://user-images.githubusercontent.com/101575380/217803564-31a580c7-875f-4503-be67-dafe0c9044e1.png)
*Source cut-off*.

![Screenshot 2023-02-09 at 11 43 37](https://user-images.githubusercontent.com/101575380/217803673-9848c7a9-bd89-44db-9745-4824fdfa4b08.png)
*No tick. Which one was selected?*

**Comment by Rory-Powell** [comment]
The designs for this have been updated and will be implemented shortly
