### ISSUE TITLE
[BUDI-6521] Skeleton loading breaks format of components 

### ISSUE THREAD

**Issue by kerbersystems** [Budibase/budibase#9625]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method:  docker compose
  - Budibase Version: 2.2.22
  - App Version: 2.2.22

**Describe the bug**
When waiting for elements to load on the page inside of a Section, the UI bugs out and the format is lost.

**To Reproduce**
1. watch the gif

**Expected behavior**
For the right-hand section to stay within it's bounds and not reformat the page.

**Screenshots**
![Recording 2023-02-09 at 08 54 26](https://user-images.githubusercontent.com/96125948/217831964-b5cc1322-6194-4755-bdb7-b373af0c4cc3.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge, Chrome

**Comment by melohagan** [comment]
Just to add to this one, notice how the `Save` button is stretched:
![save_stretch](https://user-images.githubusercontent.com/101575380/217865605-626c5c37-5004-4487-832f-a17b7bbcec9b.gif)

**Comment by kerbersystems** [comment]
A way that i've helped my screen is I set all the elements that format incorrectly to be hidden while the data loads.

**Comment by mike12345567** [comment]
The skeleton loader has been reverted - this issue should be resolved in latest version.
