### ISSUE TITLE
[BUDI-6524] OpenID Connect isn't working with ADFS 

### ISSUE THREAD

**Issue by mwllgr** [Budibase/budibase#9628]
Hello,

I'm trying to use an ADFS server for OpenID Connect. However, everytime I enter username/password and get redirected properly, Budibase only responds with this JSON content:

```json
{"message":"Unauthorized","status":403}
```

- Config URL: `https://<adfs-server>/adfs/.well-known/openid-configuration`
- Scopes: `openid, profile, email`

I selected the claims `openid`, `email` and `profile` on the ADFS server in the management console too. Checked logs on the ADFS server, look good so far. Can't find any logs for Budibase in the container, stdout only contains the nginx access logs.
Anyone here who successfully used AD FS/Active Directory to log in to Budibase?
Also, can roles/groups from the OIDC token be synced with Budibase or similar?

Thanks!

**Comment by illoyd** [comment]
@mwllgr check the redirected URL; it may contain additional error messages which are not reflected in the body payload.

In my particular instance I see additional information that Budibase does not support PKCE or PAR, hence if your ADFS requires those it will fail.

**Comment by mwllgr** [comment]
Thanks for the hint - will take a look.

**Comment by mwllgr** [comment]
Can't work on this issue as I don't work at the company anymore. Guess it was an error on my side.
