### ISSUE TITLE
[BUDI-6545] Many to many relationship broken?  

### ISSUE THREAD

**Issue by MaxBernstetter** [Budibase/budibase#9654]
Budibase 2.3.5 (self-hosted)
I have 3 tables in a psql- datasource

* managers (pk mail -> text)
* positions (pk id -> integer)
* relation_manager_position
* 
  * managermail (text)
* 
  * positionid (integer)

I want to define a many to many relationship but  cannot do so

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/dd47cc21-84a3-4bfc-8e91-1cbfdebfaac5/7ab564a6-7fe7-4b9e-acd9-fe63d43f5509)

<sub>[BUDI-6545](https://linear.app/budibase/issue/BUDI-6545/many-to-many-relationship-broken)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6545](https://linear.app/budibase/issue/BUDI-6545/many-to-many-relationship-broken)</sub>

**Comment by oscargws** [comment]
Having trouble with the same issue here, following

**Comment by shogunpurple** [comment]
This one should now be resolved. Closing
