### ISSUE TITLE
[BUDI-7071] Improve User invite email errors

### ISSUE THREAD

**Issue by anthonydibi** [Budibase/budibase#9657]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Cloud
  - Tenant ID: mdt4950 

**Describe the bug**
When I try to add a user to my application by either email or simple invite, it says that there was a problem inviting users, with the reason being "unavailable"

**To Reproduce**
1. Go to users tab in Budibase home
2. Click "Add users"
3. Enter email address, give role (I have tried all roles)
4. Click add users
5. Click send email invites, then continue
6. Error occurs: unavailable user

**Expected behavior**
I expected a confirmation stating that an email invite was sent to the invited user.

**Screenshots**
![image](https://user-images.githubusercontent.com/57297382/218228655-60b5bb55-2f92-4156-b171-00ce053d4478.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120

<sub>[BUDI-6550](https://linear.app/budibase/issue/BUDI-6550/cannot-add-user-to-app-with-free-plan)</sub>

<sub>[BUDI-7071](https://linear.app/budibase/issue/BUDI-7071/improve-user-invite-email-errors)</sub>

**Comment by shogunpurple** [comment]
Hi @anthonydibi - I can't seem to reproduce this. Could you show any errors in the browser console?

**Comment by anthonydibi** [comment]
![image](https://user-images.githubusercontent.com/57297382/218235990-8b2d83b8-ef20-48c5-993d-557190003e30.png)
I've also noticed that this only happens when I use an active e-mail - if I use an e-mail that doesn't exist then it gives a success message.

**Comment by kpturner** [comment]
This happens to me for some email addresses and not others.   I tried to adding 5 users by email invite and four were successful and one says "Unavailable" - and it always says "Unavailable" every time I try to add it.  So there is clearly some check going on behind the scenes that produces this issue.

**Comment by melohagan** [comment]
Hey @anthonydibi @kpturner 

For your information, this *Unavailable* message displays when the email is already being used by a user in another tenant. 

To further add to this one, when inviting a user that already exists through the Users side panel, an error is thrown due to a null-pointer on the email address:

![Screenshot 2023-06-01 at 11 20 03](https://github.com/Budibase/budibase/assets/101575380/4993717c-7667-4363-96bd-4f28118e0da0)

Ideally a clearer message should be shown, and no error thrown.

**Comment by kpturner** [comment]
> Hey @anthonydibi @kpturner
> 
> For your information, this _Unavailable_ message displays when the email is already being used by a user in another tenant.
> 
> To further add to this one, when inviting a user that already exists through the Users side panel, an error is thrown due to a null-pointer on the email address:
> 
> ![Screenshot 2023-06-01 at 11 20 03](https://user-images.githubusercontent.com/101575380/242565675-4993717c-7667-4363-96bd-4f28118e0da0.png)
> 
> Ideally a clearer message should be shown, and no error thrown.

I can't imagine that the email addresses I was trying to add are already being used by a user in another tenant.  One of the addresses is owned by a user who has never previously heard of Budibase.
