### ISSUE TITLE
Docker Single Image Does Not Work with v2.3.10-v2.3.12

### ISSUE THREAD

**Issue by pinwaven** [Budibase/budibase#9674]
**Checklist**
- [ x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Creating docker single image from source
  - Budibase Version: 2.3.10-2.3.12
 
**Describe the bug**
After creating docker single image with command "yarn build:image:single", an image is created, however, when accessing budibase from the image, it results in a 502 error. For information only, docker single image from version v2.2.9 src was running OK.

**Comment by mike12345567** [comment]
Hi @pinwaven - I've tried this locally and was able to build locally and ran into no issues - we also already provide an image which is pre-built as part of our CI, docs around its usage here: https://docs.budibase.com/docs/docker

You should ideally be using the full build command `build:docker:single` which will make sure your environment is fully setup for the build, I'm going to close this issue as it cannot be replicated - likely an environmental issue.
