### ISSUE TITLE
[BUDI-6603] Long column names leads to narrow inputs in the autogenerated side panel

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#9681]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
bb tenant

**Describe the bug**

**To Reproduce**
1. Go to Persona psychographic survey app in bb tenant 

**Expected behavior**
The content should wrap?

**Screenshots**
Shared in product chat.
  

<sub>[BUDI-6603](https://linear.app/budibase/issue/BUDI-6603/long-column-names-leads-to-narrow-inputs-in-the-autogenerated-side)</sub>

**Comment by shogunpurple** [comment]
This will be solved by the new form block updates where you can move the position of the labels, closing as will be solved in next iteration.
