### ISSUE TITLE
[BUDI-6573] Data provider rows binding with ternary statement does not work

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9692]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.3.12
  * App Version: 2.3.12

**Describe the bug**
I can bind a value to: `$("New Data Provider.Rows")?.[0]?.["First Name"]`

But I cannot bind a value to: `return $("New Data Provider.Rows")?.[0]?.["First Name"] === "Brayden" ? "Brayden" : "Not loaded";`

In this case 'Not loaded' is returned when I expect 'Brayden'.

**To Reproduce**

1. Add a Form for the sample data Employees table
2. Add a Data provider for the Employees table
3. Set the default value of a text field to: `$("New Data Provider.Rows")?.[0]?.["First Name"]`

   See that it works
4. Set the default value to: `return $("New Data Provider.Rows")?.[0]?.["First Name"] === "Brayden" ? "Brayden" : "Not loaded";`

   See that it incorrectly displayed 'Not loaded'.

**Expected behavior**
Ternary statements in JavaScript bindings should trigger when Data provider rows are loaded, to match non-ternary statements.

**Screenshots**

![Screenshot 2023-02-14 at 15.21.35.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f389a8d3-3d06-4946-b080-a364b9b63663/8842602c-5af6-4182-8440-f21aa1a47e4a)

Default value without ternary.

![Screenshot 2023-02-14 at 15.22.36.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/464cc512-6468-4e9f-a06b-d8e0d78aa334/568fdd5a-a1f2-4196-9949-933b35f114e8)

Default value with ternary. Should be Brayden.

**App Export**

[My first app-export-1676388187810.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/7b26c2b6-d933-46ea-b06b-8bdb3b197ad5/f5afb381-12e5-4207-9fbe-56f34022faed)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6573](https://linear.app/budibase/issue/BUDI-6573/data-provider-rows-binding-with-ternary-statement-does-not-work)</sub>

**Comment by aptkingston** [comment]
This was caused by skeleton loaders, which have now been removed. So this is fixed.
