### ISSUE TITLE
Automation: Update Row: boolean fields have only On/Off toggle, but need to have On/Off/Don't change

### ISSUE THREAD

**Issue by sergey-vin** [Budibase/budibase#9697]
**Hosting**
- Cloud

**Describe the bug**
When creating automation step "Update Row" for tables with Boolean fields - there's only 2 options, but should be 3.
![image](https://user-images.githubusercontent.com/1080493/218971580-dba8018c-7198-4bca-99a7-83f35b615479.png)

Now it's not clear what the "off" does - does it set the value to "False", or it doesn't change the value.

**Comment by shogunpurple** [comment]
@sergey-vin please raise a better issue and fill in the bug template. Closing for now until we have better reproduction
