### ISSUE TITLE
[BUDI-6601] Bug in automation Looping on Update row block : k.steps is undefined

### ISSUE THREAD

**Issue by KevinHamonApp** [Budibase/budibase#9703]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.3.10
  - App Version: 2.3.10

**Describe the bug**
I have an automation with those blocks : 
* query block, querying rows in a base
* update row block, with a loop on the rows queried 
The test automation keep running forever, and I observe a log in console :  k.steps is undefined (see attached picture for full error)

Then, I tried other automations to isolate the problem. 
If I delete the loop statement, all works well. 
If I change the Update Row block for a Backend log block, with a loop statement, all works well. 

It just seems that something does not work between Update Row block and loop statement.
Am I missing something ? 

**To Reproduce**
1. Go to Automate
2. Make a query block, query rows of a budibase base
3. add an Update Row Block
4. Add a loop condition on precedent Query Rows block
5. Test automation
6. Observe in console

**Expected behavior**
I would expect the automate do this update row action X times. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74555017/219073432-526643c8-7ed2-4732-bc1f-e0bca4ac36a8.png)
  
**App Export**
[Alter Gaia-export-1676475350250.tar.gz](https://github.com/Budibase/budibase/files/10744685/Alter.Gaia-export-1676475350250.tar.gz)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser Firefox

<sub>[BUDI-6601](https://linear.app/budibase/issue/BUDI-6601/bug-in-automation-looping-on-update-row-block-ksteps-is-undefined)</sub>

**Comment by andz-bb** [comment]
I was unable to recreate this with a fresh app/DB but I could recreate whenever importing the app attached in the bug report on latest master. In this case a problem with the schema is causing the Update Row automation step to crash out and error. Specifically the two date columns *Date* and *Collecte* in the table *Passage* had Ignore time zones set to null in the column configuration. I'm not sure how this happened but I saw [a similar issue very recently](https://github.com/Budibase/budibase/discussions/9744#discussioncomment-5056424) where the Formula Type was unset on several formula columns in a table. This caused an Update Row step to crash in the same way.

It now works fine whenever I update the problematic columns and remove/re-add the bad automation step.

I don't know how the schema has got broken like this, it may be historic bad data or there may be a bug that causes these cases. We should definitely handle these cases better in the automation either way - currently when the automation errors you just get an infinite spinner and an unhelpful error in the network response. The only way to proceed is to refresh the page.

![image.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/a3245ab1-f458-4d28-9beb-8d0d5716a87e/686da575-d6b0-46d5-bd13-29245b33abb6)

Above is where the code is failing. `hbsString` is null
