### ISSUE TITLE
[BUDI-6600] Error from building Docker Single

### ISSUE THREAD

**Issue by pinwaven** [Budibase/budibase#9722]
**Checklist**
- [ x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Cloud ECS Virtual Machine with Ubuntu 22.04LTS
  - Budibase Version: 2.3.16

**Describe the bug**
Building Docker Single image resulted in error. Created a new Ubuntu Virtual Machine, installed NodeJS v16, Yarn, Jest.

**To Reproduce**
1. Created a new Ubuntu 22.04 Virtual Machine, installed NodeJS v16, Yarn, Jest.
2. git clone the budibase repository
3.  ran yarn, then ran "yarn bootstrap"
4. yarn build:docker:single
5. See error
src/tests/utilities/TestConfiguration.ts(159,34): error TS2339: Property 'tenant' does not exist on type 'typeof import("/app/node_modules/@budibase/backend-core/tests/utilities/structures/index")'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c node /pinVersions.js && yarn && yarn build && /cleanup.sh' returned a non-zero code: 2
error Command failed with exit code 2.
<img width="1735" alt="image" src="https://user-images.githubusercontent.com/12550765/219573402-7a72ae98-20a2-4ec7-a8fd-0d0b95d6609a.png">

<sub>[BUDI-6600](https://linear.app/budibase/issue/BUDI-6600/error-from-building-docker-single)</sub>

**Comment by mike12345567** [comment]
Hi @pinwaven - can you try running the following:
```
yarn setup
yarn build:docker:single
```

**Comment by pinwaven** [comment]
Hi @mike12345567 
Yes, I tried multiple combinations, including "Running Yarn Setup first, then yarn build:docker:single", the results were the same. If you have a combinations of linux version,Node version etc that would work, i will try to following the working setup.

**Comment by pinwaven** [comment]
Hi @mike12345567 
I can confirm the docker single building process completes ok with 2.3.18-alpha.12

**Comment by mike12345567** [comment]
Hi @pinwaven - if thats the case then the latest version (due to be released today) will solve your issues, going to close this issue as it will be resolved in the release version very soon.
