### ISSUE TITLE
[BUDI-6599] Unable to add and remove many<->many relationships simultaneously

### ISSUE THREAD

**Issue by Darojax** [Budibase/budibase#9727]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.3.12
  - Database Version: MariaDB 10.10.3

**Describe the bug**
I have two tables 'personnel' and 'groups' which are in a Many<->Many relationship. The relationship itself works fine and the relationship has been entered properly in the Budibase 'Define relationship' section. Using the backend Data management, clicking on a 'personnel' row and using the dropdown menu for 'groups' it IS possible to add one or more relationships, and it IS possible to remove one or more relationships. HOWEVER, it is NOT possible to add and remove relationships simultaneously, attempting this will result in the attempted change not being made. 

**To Reproduce**
1. Open the backend Data management section.
2. Click on a personnel row.
3. Use the dropdown menu for 'groups'.
4. Add a new group while removing another group.
5. Observe that the attempted change is not saved. 
6. This however works: Attempt to add a new group OR remove another group.
7. Change is saved.

**Expected behavior**
Adding and Removing a relationship at the same time should save the change.

**Screenshots**
![MjHSiNF](https://user-images.githubusercontent.com/110496226/219652165-b4f0ff06-cc71-4cef-b320-2b1e2f7d10ce.png)
  
**App Export**
[Recruit Status-export-1676636327524.tar.gz](https://github.com/Budibase/budibase/files/10766595/Recruit.Status-export-1676636327524.tar.gz)

**Desktop (please complete the following information):**
 - OS: WIndows 11 Pro
 - Browser: Chrome
 - Version 110.0.5481.104 (Official Build) (64-bit)

**Additional context**
Thanks for a great product

<sub>[BUDI-6599](https://linear.app/budibase/issue/BUDI-6599/unable-to-add-and-remove-many-many-relationships-simultaneously)</sub>

**Comment by Darojax** [comment]
Actually to add to this, there are additional issues. If one personnel row has multiple relationships to the groups table, if you deselect one of them and try to save it can actually remove a different relationship, not the one you removed. Seems something is not right here.

**Comment by Darojax** [comment]
I'm sorry, I just need to verify if you do not plan to fix this bug in the future?

**Comment by shogunpurple** [comment]
@mitch did you try this with mariaDB? The user emailed me to say they were still experiencing this one
