### ISSUE TITLE
[BUDI-6595] Export from Cloud, import to Self-hosted doesn't load the pictures / attachments.

### ISSUE THREAD

**Issue by sergey-vin** [Budibase/budibase#9739]
**Hosting**
- Cloud

**Describe the bug**
Export from Cloud, import to Self-hosted doesn't load the pictures / attachments.

**To Reproduce**
1. Create an app
2. Create a BB table with Attachment column
3. Upload some pictures there
4. Export the app with data (don't set "Exclude rows")
5. Import to self-hosted version
6. Open Data section, observe the error: files are somewhat uploaded - they are present as data entries but content is broken
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1080493/219939963-729c3f0e-407d-4954-9d73-a7aeea16d39b.png">
7. Try replacing one of them with a picture (re-upload it), and observe that it works: 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/1080493/219940037-83860734-7f3a-4316-ae1a-20e31095a1ef.png">

This means that self-hosted storage works well, but the import fails.

**Expected behavior**
To see the pictures from the dump file, not broken, in self-host version right after the import.

<sub>[BUDI-6595](https://linear.app/budibase/issue/BUDI-6595/export-from-cloud-import-to-self-hosted-doesnt-load-the-pictures)</sub>

**Comment by mike12345567** [comment]
Hi @sergey-vin - this should be resolved as of the latest release.
