### ISSUE TITLE
[BUDI-6611] Tooltip in binding window is being cut off

### ISSUE THREAD

**Issue by mp-strachan** [Budibase/budibase#9741]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker-compose
  - Budibase Version: 2.3.16
  - App Version: <version> 

**Describe the bug**
When using helpers from the binding window, the lowest helpers have their tool tips cut off

**To Reproduce**
1. Add a button component to a screen
2. Add a onClick action
3. Add a action that requires a binding (eg: notification)
4. Add a binding
5. Click "Helpers"
6. Scroll to the bottom of the list - the tooltips for the last few items render outside the window frame

**Expected behavior**
Lowest tooltips should render within the frame

**Screenshots**
![image](https://user-images.githubusercontent.com/26296076/220020928-ceba0124-407b-4074-a950-d1d64a9bbe9d.png)

<sub>[BUDI-6611](https://linear.app/budibase/issue/BUDI-6611/tooltip-in-binding-window-is-being-cut-off)</sub>

**Comment by aptkingston** [comment]
This is fixed.
