### ISSUE TITLE
[BUDI-6700] Automation's Filter -> "Is in" doesn't retrieve all rows

### ISSUE THREAD

**Issue by sergey-vin** [Budibase/budibase#9762]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists
  https://github.com/Budibase/budibase/issues?q=is%3Aissue+is%3Aopen+filter+automation

**Hosting**

* Cloud

**Describe the bug**
Querying rows with a filter in Automation returns not all rows.

**To Reproduce**

1. Create new app, import from a template "Professional Directory Template"
2. In "Data", edit "Directory" table to remove some values from some fields  (city and zip of IDs=1 and 2), remember the state of the DB (I'm changing data to make sure I look at the right app - that's handy if you have several app / several tabs opened)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/2695dc71-4776-43e5-9553-d5abd2f2f4f7/303898bd-83d8-4fa8-b2c1-1d4d93dfa6a1)

1. Create an automation to query all rows
2. Run it and see the results in sorted format:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/30f20c1b-52f1-4039-8bf1-1e0242456b2a/669cda29-9096-41c4-8c9d-4824201ffba8)

1. See that at least IDs 1, 2 and 3 are present

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/fc4a6ecb-41ce-4e81-9243-80a9344f32e4/f6089365-80a1-4b8e-85ed-a4c1b65af82e)

1. Create an automation to query only rows 1, 2 and 3

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ac04fe65-7771-43d4-b1f2-0ab76dd0af35/24dcb44d-77c6-466a-b743-3e6f6dd37899)

1. Run it and see that only 2 & 3 but not 1 were returned:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/f7dd368c-568f-4788-a323-9f3bd60ae60c/0e898fd6-cea3-4a7e-bc99-9bc450473f6c)

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/31300b86-33ac-42b5-909d-ffd5ce510709/8ed6fb17-ca69-40d4-808d-e49ad6d2cecd)

**Expected behavior**
Should have returned 1,2,3

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6700](https://linear.app/budibase/issue/BUDI-6700/automations-filter-is-in-doesnt-retrieve-all-rows)</sub>

**Comment by melohagan** [comment]
Hey @sergey-vin 

I think you just need to use remove the square brackets from your value in the filter. Could you try:

*Auto ID* **Is in** Value: `1,2,3`

If that doesn't work you could try a JavaScript binding like so:

```js
return [1, 2, 3];
```
