### ISSUE TITLE
[BUDI-6699] Automation's "Update Row" Action does not allow to save rows with "Off" / "False" value of a Boolean field

### ISSUE THREAD

**Issue by sergey-vin** [Budibase/budibase#9764]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists
https://github.com/Budibase/budibase/issues?q=is%3Aissue+is%3Aopen+update+row+automation

**Hosting**
- Cloud

**Describe the bug**
In Update Row action there's only a toggle with 2 values for boolean fields:
- "Off" leaves the value unchanged.
- "On" sets it to true.
- There's no way to set it to "False".

(Note: That's a more detailed description of https://github.com/Budibase/budibase/issues/9697)

**To Reproduce**
1. Create new app, import from a template "Professional Directory Template"
2. In "Data", add a boolean field to a "Directory" table 
<img width="390" alt="image" src="https://user-images.githubusercontent.com/1080493/220314531-9cf31cc8-c2cd-45f9-813f-22b41c8656dd.png">

3. In "Data", edit "Directory" table to set/remove some values from some fields  (`isTerminated`, `City` and `Zip` of IDs=1, 2, 3)
4. Remember the state of the DB 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/1080493/220314930-8775bd12-6a68-4df2-bbce-3c1b00f5e0ef.png">
5. Create an automation to query all rows and change only `Address`, see that it's not clear what will happen with "isTerminated" (will it be all marked as "false", or kept as is?)
6. Run it
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1080493/220328624-140549cb-b0c9-4c6d-8d8c-7dc3a5ebe96b.png">

7. Observe the DB - address was changed, but `isterminated` - not
<img width="704" alt="image" src="https://user-images.githubusercontent.com/1080493/220328221-eb520f17-e436-413e-8903-912d00c4b0a0.png">

8. Toggle `IsTerminted` to "On" / "True", re-run automation
<img width="549" alt="image" src="https://user-images.githubusercontent.com/1080493/220328841-9447e459-ba92-446e-8f9b-52b01936e81a.png">

9. Observe that `IsTermintated` was set to True in the DB
<img width="657" alt="image" src="https://user-images.githubusercontent.com/1080493/220328995-a6672cc5-f15e-4e95-a2d9-b466803aad07.png">

**Expected behavior**
To be able to set boolean values to "False", and have a more clear UX that doesn't confuse. Maybe have 3 options there, to clearly state "set to false" vs "don't change"

<sub>[BUDI-6699](https://linear.app/budibase/issue/BUDI-6699/automations-update-row-action-does-not-allow-to-save-rows-with-off)</sub>

**Comment by melohagan** [comment]
JavaScript is making this a nightmare because I can't tell if the value is actually **false** or if it was previously cast to **false** because it was *falsey*.

**Comment by shogunpurple** [comment]
Nope, this should be firestorm - updated

**Comment by melohagan** [comment]
There are now three states:

- *Choose an option* (Leave value unchanged)
- True
- False
