### ISSUE TITLE
Self Hosted Login Customization - Testimonials removal

### ISSUE THREAD

**Issue by PaulFederato** [Budibase/budibase#9770]
**Describe the feature request**
- We would like to be able to have better white labeling of the Login page for Self Hosted deployments.
  - Specifically the ability to drop the Testimonials on the right.
  - We would also like to be able to change the `Log in to Budibase` to `Log in to <org name>`

**Screenshots**
![image](https://user-images.githubusercontent.com/111723903/220471735-ed078de4-ac49-46b7-9ca2-8f97fcd8365d.png)

**Other Details**
- Budibase version 2.3.16
- Self Hosted via Kubernetes Helm chart version: 2.3.16

**Comment by shogunpurple** [comment]
This has been implemented - https://docs.budibase.com/docs/branding

**Comment by PaulFederato** [comment]
@shogunpurple You all are awesome, thank you very much!
