### ISSUE TITLE
[BUDI-6698] Budibase CLI: RC0 when failed

### ISSUE THREAD

**Issue by martingasseriml** [Budibase/budibase#9772]
**Checklist**
- [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Budibase running as docker-compose stack

**Describe the bug**
budi backup with budibase/CLI returns rc 0 even when backups fail

**To Reproduce**
1.shutdown docker-compose  -> No running budibase
2. Start budi backup with `/var/lib/nvm/versions/node/v18.13.0/bin/budi backups --export --env /opt/iml_budibase/.env`
3. See error

```
bb-alert: No JWT Secret supplied, cannot configure JWT strategy 
Error - FetchError: request to http://budiuser:budipassword@localhost:10000/db/_all_dbs failed, reason: connect ECONNREFUSED 127.0.0.1:10000
```
4. check error code

```
usert@budibase:prod budibase# echo $?
0
```

**Expected behavior**
Errorcode <> 0

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Version Budibase CLI latest (2.3.17) 

<sub>[BUDI-6698](https://linear.app/budibase/issue/BUDI-6698/budibase-cli-rc0-when-failed)</sub>

**Comment by mike12345567** [comment]
Issue resolved.
