### ISSUE TITLE
[BUDI-6630] Table export CSV action includes headers for all columns instead of selected ones

### ISSUE THREAD

**Issue by andz-bb** [Budibase/budibase#9776]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.3.17
  * App Version: 2.3.17

**Describe the bug**
When choosing specific columns to export from a table, the headers for the unselected columns are still included along with empty strings for each of them. 

**To Reproduce**

1. Create a table
2. Create a button with an Export Data action
3. Select the table and specific columns to export
4. Click the export button to download the file and see unselected column headers in the CSV

**Expected behaviour**

A CSV file should be generated with headers and data for only the selected columns.

**Screenshots**

![Screenshot 2023-02-22 at 15.58.12.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/bc41a412-4d26-49c5-9c87-7c4931bfc23f/465fb6fb-0b41-4692-9166-730864420aba)

![Screenshot 2023-02-22 at 15.49.45.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/38be666e-7d19-4314-b78c-28f43d1bed86/ca27500f-5404-41bc-b8e2-371be32b72d6)

**Additional context**

raised by community member here: [https://github.com/Budibase/budibase/discussions/9773](https://github.com/Budibase/budibase/discussions/9773)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6630](https://linear.app/budibase/issue/BUDI-6630/table-export-csv-action-includes-headers-for-all-columns-instead-of)</sub>

**Comment by zedascouves** [comment]
Just to say that I also have this issue. Is there a way to upvote a bug, so there's a way to know if it's affecting many people?

**Comment by andyburgessmd** [comment]
I also have this issue and would upvote
