### ISSUE TITLE
Unable to read from Bindings for REST Headers

### ISSUE THREAD

**Issue by samexsam** [Budibase/budibase#9786]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.3.16
  - App Version: 2.3.16

**Describe the bug**
Headers in REST query is unable to read from Bindings value. Value will be undefined during "execute query" steps under a button's "Define Action". The same value can be read if you select `Show Notification` under `Define Action`

**To Reproduce**
1. Go to `Data tab`
2. Select Budibase DB > User > Create Column > add new columns with custom value
3. Select REST > Add query > Select Headers tab > select Current User > select the new custom value created in step 2
4. Go to `Design tab `
5. Create a button > Define Action > select Execute Query > Select REST API created in step 3

**Expected behavior**
Execture Query Action should read value from Bindings

**Screenshots**
![image](https://user-images.githubusercontent.com/4414288/220931790-cd0c018f-3813-45ad-9676-b62b4d4c7527.png)

**Comment by melohagan** [comment]
Hey @samexsam 

This is not a bug. You need to pass the `{{ Current User.key }}` from the **Design** section through to your REST Connector.

I.e. in your REST connector you would have in the Bindings tab:
![Screenshot 2023-02-24 at 11 41 34](https://user-images.githubusercontent.com/101575380/221170740-ad5a460e-d119-47bf-bb6d-35af658815af.png)

Params tab:
![Screenshot 2023-02-24 at 11 42 00](https://user-images.githubusercontent.com/101575380/221170821-553c4416-edab-4150-9184-2ff234f80f07.png)

And finally in your Design section:
![Screenshot 2023-02-24 at 11 43 54](https://user-images.githubusercontent.com/101575380/221171140-b77f80f3-0800-41e0-99d8-4c98117bb018.png)

There's an example here for [Custom queries](https://docs.budibase.com/docs/custom-queries#tutorial-posting-form-data-to-a-custom-query) but the process is similar.
