### ISSUE TITLE
[BUDI-6635] Calculated columns lost on "fetch tables" in SQL

### ISSUE THREAD

**Issue by lukuser** [Budibase/budibase#9788]
Version 2.2.19

Using SQL database, the "fetch tables" erases all calculated, formula-based javascript columns, even though the tables containing those columns have not changed at the source db.

<sub>[BUDI-6635](https://linear.app/budibase/issue/BUDI-6635/calculated-columns-lost-on-fetch-tables-in-sql)</sub>

**Comment by shogunpurple** [comment]
Hi, please fill out a better issue using the issue template. Closing for now
