### ISSUE TITLE
Built-in Users table empty

### ISSUE THREAD

**Issue by galenvssysadmin** [Budibase/budibase#9808]
The built-in 'Users' table for one of the Budibase apps is currently showing an empty table:

![Screen Shot 2023-02-25 at 12 45 10](https://user-images.githubusercontent.com/102808173/221371706-cc7c49f1-cbbe-4540-b015-199e4ea9b5e1.png)

This is strange because in the 'Access' settings for the app I can see that a list of users for the app is assigned:
![Screen Shot 2023-02-25 at 12 46 30](https://user-images.githubusercontent.com/102808173/221371780-76c12789-f761-4041-9b03-7a420deda15f.png)

When I bring up the Chrome console, I get these errors:
![Screen Shot 2023-02-25 at 12 49 48](https://user-images.githubusercontent.com/102808173/221371921-d5710200-5b99-46f8-89b9-eb737ba478e5.png)

- This is only happening with one app; the 'Users' table shows all the users in other apps.
- I did not add any custom columns to the 'Users' table

This is happening on a self-hosted Docker image of Budibase.

This first occurred on version **2.2.2**, however I updated to **2.3.15** and still have the same issue.

**Comment by melohagan** [comment]
Hey @galenvssysadmin 

What happens if you publish the app, leave the builder, and then re-edit the app. Do the users show then?

Users are only pulled into the Users table for published apps.

**Comment by galenvssysadmin** [comment]
The app was already published, but thanks to your tip I just cloned the app and published the clone. The Users database started functioning again (for the cloned app).
