### ISSUE TITLE
[BUDI-6647] NumRecords field for airtable is ignored

### ISSUE THREAD

**Issue by helena-pa** [Budibase/budibase#9813]
**Hosting**
- Self
  - Budibase Version: 2.3.16

**Describe the bug**
NumRecords field for airtable is ignored whether you fill it in or not.

**To Reproduce**
1. Go to 'Data' and create a _Read_ query for Airtable for a table with more than 100 rows (and less than 1000).
2. Set NumRecords to `1000` (or leave it blank)
3. In the _Transformer_ section set `return data.length;`
4. Test the query : the resut is `100` (or `10` if the _NumRecords_ was left blank).

**Expected behavior**
According to the documentation : "The _NumRecords_ field is an optional field, by default all data will be returned, but if you want to limit the results you could enter a number here.".
So the result query should be the number of rows of the selected table.

**Screenshots**
With NumRecords to `1000` :
![image](https://user-images.githubusercontent.com/117634672/221528678-a8115b26-c25d-4db6-bcef-112a91fe3c4d.png)

With NumRecords left blank : 
![image](https://user-images.githubusercontent.com/117634672/221528883-d0ce0363-16d3-440b-a445-410aca6e4113.png)

<sub>[BUDI-6647](https://linear.app/budibase/issue/BUDI-6647/numrecords-field-for-airtable-is-ignored)</sub>

**Comment by ryszardwhee** [comment]
Thank you for reporting this issue.
We would like to use Budibase at our company but without fixing this bug we can't use it with our airtable database.

Do have an estimated time when this bug will be fixed?

**Comment by helena-pa** [comment]
> Thank you for reporting this issue. We would like to use Budibase at our company but without fixing this bug we can't use it with our airtable database.

I've checked [the Airtable documentation](https://airtable.com/developers/web/api/list-records) since then and I'm not sure it's possible to get more than 100 records at once. But if so, it means that as long as paging and the "Get record" call are not supported, the Airtable datasource is unusable for tables with more than 100 records (and that the Budibase documentation needs to be fixed).
In the meantime, I worked around the problem by further filtering my views to keep less than 100 records or by [calling the Airtable API directly](https://docs.budibase.com/docs/rest).

**Comment by ryszardwhee** [comment]
Airtable has client sdk to fetch all the records.

Example code how it works:

```
const Airtable = require("airtable");

export type ResponseData = {
  id: string;
  fields: {} | any;
}[];

type Props = {
  tableName: string;
  view?: string;
  maxRecords?: number;
  filterFormula?: string;
  sort?: [{ field: string; direction: string }];
};

function getTableRecords({
  tableName = "",
  view = "Grid view",
  maxRecords = 30,
  filterFormula = "",
  sort = [{ field: "createdAt", direction: "desc" }]
}: Props) {
  try {
    const base = new Airtable({ apiKey: process.env.AIRTABLE_API_KEY }).base(
      process.env.AIRTABLE_BASE_ID
    );
    return base(tableName)
      .select({
        maxRecords,
        view,
        sort,
        filterByFormula: filterFormula
      })
      .all();
  } catch (error) {
    throw new Error(`Error getting table records in ${tableName}: ${error.message}`);
  }
}
```
