### ISSUE TITLE
[BUDI-6694] Options Picker with lots of options goes off screen if at the bottom of form

### ISSUE THREAD

**Issue by keith-ellis-sillek** [Budibase/budibase#9819]
**Checklist**
- [X ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker-compose 
  - Budibase Version: 2.3.16 

**Describe the bug**
If you have a options picker close to the bottom of the browser window, you changes direction of the drop-down up so that it can stay on the screen. This is expected. However, with mine with a lot of options, the options scrolls goes off the top of the screen.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://drive.google.com/drive/folders/1n85zVXUWQWGPS2tl62RFM2hkxlpyX9Wk?usp=sharing
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**

**Additional context**

<sub>[BUDI-6694](https://linear.app/budibase/issue/BUDI-6694/options-picker-with-lots-of-options-goes-off-screen-if-at-the-bottom)</sub>

**Comment by keith-ellis-sillek** [comment]
It wouldn't let up upload screenshots for some reason, but here's a google drive folder with screenshots and a video

https://drive.google.com/drive/folders/1n85zVXUWQWGPS2tl62RFM2hkxlpyX9Wk?usp=sharing

**Comment by melohagan** [comment]
Hey @keith-ellis-sillek 

One thing you could do is add an embed component with the following:

```css
<style>
.spectrum-Popover {
  max-height: 100px !important;
}
</style>
```

Set the **max-height** to show the maximum number of options that you want.

**Comment by keith-ellis-sillek** [comment]
Thank you for getting back so quickly, btw!

**Comment by melohagan** [comment]
You're welcome @keith-ellis-sillek 

Try adding in this line: 

```css
<style>
.spectrum-Popover {
  top: -400% !important;
  max-height: 100px !important;
}
</style>
```

This is taken from this discord thread: https://ptb.discord.com/channels/733030666647765003/1070089914718371971
