### ISSUE TITLE
MSsql connector does not retrieve any tables when it is not relerring to the default MSSQL instance

### ISSUE THREAD

**Issue by rschnell** [Budibase/budibase#9820]
### Discussed in https://github.com/Budibase/budibase/discussions/9809

<div type='discussions-op-text'>

<sup>Originally posted by **rschnell** February 26, 2023</sup>
Using a cloud based sql server external to the self hosted Budi base on windows.pc/docker

confirmed the remote database connection is working from the windows pc

the connection details in budibase match eg a successful connection from sql management studio and on saving the connection in budibase there is no error - success message.

fetch all tables and fetch named tables do no work. There is no error and no message, just no tables are retrieved.

also just confirmed same behaviour from Budi cloud to this external database.

ideas?</div>

**Comment by melohagan** [comment]
Could you please follow the bug template, providing reproduction steps and screenshots. 

Closing for now!

**Comment by rschnell** [comment]
Actually this is easy to replicate. In the sql connection parameter settings for mssql you need to set the server/host name. This is the server ip (or url) where the mssql instance resides. However if the instance is not the default and is a named sql instance the name should become servername\instance name and not just servername. But this does not work and no tables can be retrieved. So to test you need a named sql instance and the default (internally called MSSQL). A database in the named instance is not recognized. Copy it to the default instance and it is recognized.
