### ISSUE TITLE
[BUDI-6693] Starting up: Brave and other Chrome based browsers keep loading

### ISSUE THREAD

**Issue by ile** [Budibase/budibase#9830]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: Latest git clone (Feb 28, 2023)
  - Docker: 20.10.5
  - Docker-Compose: 1.29.2
  - Node: v14.20.1
  - Yarn: 1.22.19
  - Lerna: 5.1.4

**Describe the bug**
When starting up (yarn dev), and going to url http://127.0.0.1:10000/builder/admin, some assets can't get loaded, they just keep being "Pending". 

When using Chromium, the first load usually works, but if I refresh (F5), the same thing happens. With Brave, even the first load keeps Pending.

**To Reproduce**
1. Follow installation https://github.com/Budibase/budibase/blob/66f74dfbc3a65af830641c269a999eb252c9b298/docs/DEV-SETUP-DEBIAN.md
2. Install
3. Go to the url

**Expected behavior**
Page should load

**Screenshots**
![image](https://user-images.githubusercontent.com/433707/222023742-aaecaaa8-5b99-491c-bc7e-6dcb492b4d4c.png)
  
**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser: Brave, Chromium
 - Version: latest

**Additional context**
Firefox works every time.

<sub>[BUDI-6693](https://linear.app/budibase/issue/BUDI-6693/starting-up-brave-and-other-chrome-based-browsers-keep-loading)</sub>

**Comment by ile** [comment]
The same issue seems to affect other urls after creating the super user.

![image](https://user-images.githubusercontent.com/433707/222025505-4145aeb8-2436-48b3-810b-9c2afafd4120.png)

**Comment by ile** [comment]
If I exit that browser window and load the url again, I get something, but not everything has loaded correctly (images). 
![image](https://user-images.githubusercontent.com/433707/222025710-758b2b95-fe96-4997-9387-8bef6346fdd8.png)

`docker ps` looks like this:

![image](https://user-images.githubusercontent.com/433707/222025777-27c2d447-0c9b-46e6-ad50-6bd594bbc955.png)

**Comment by aptkingston** [comment]
Hey @ile. This is just because our dev server (vite) in Chrome is trying to request more file descriptors than your system allows. I'll add this tweak to the docs, but all you need to do (on debian based distros) is add `* - nofile 65536` to the file `/etc/security/limits.conf` and reboot.
