### ISSUE TITLE
[BUDI-6651] Deleting a data provider with nested parent container will prevent component being added to screen initially

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9838]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.3.16
  * App Version: 2.3.16

**Describe the bug**
When deleting a data provider in use within the Design section it can prevent you adding any other component.

You can then delete the data provider, but you cannot add any components until you refresh the page, or use the `Add component` button from the middle of the screen.

**To Reproduce**

1. Create a Budibase table with a column.
2. Add a Data provider and nest a table.
3. Click on the Table to select it, but delete the parent Data provider
4. Click Add component button **in the top left**
5. See that there's no components to add
6. Click the `Add component` **in the centre of the screen (below Your screen is empty)**. You will now see the component list

**Expected behavior**
Clicking any `Add component` button should allow you to add a component even when a selected container has been deleted.

**Screenshots**

![Screenshot 2023-03-01 at 14.06.13.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/0e65736f-5053-4723-9b95-fdbac3e1b66e/cad36890-d6c4-4134-b781-79bb68c2b8f2)

![Screenshot 2023-03-01 at 14.07.16.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/5b0eb122-f955-47ea-9bc6-271da313b932/08283b49-d542-4b7b-b1d2-53a77d401354)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6651](https://linear.app/budibase/issue/BUDI-6651/deleting-a-data-provider-with-nested-parent-container-will-prevent)</sub>

**Comment by aptkingston** [comment]
Could you try to repro this to see if it's still an issue? I've tried but it works.

**Comment by melohagan** [comment]
Appears to be fixed! Closing.
