### ISSUE TITLE
Tinyint values are interpreted as bool by default

### ISSUE THREAD

**Issue by AlejandroFNadal** [Budibase/budibase#9839]
**Checklist**
- [X ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.3.16.

**Describe the bug**
When a MySQL table with field of type "tinyint unsigned" is imported, it is interpreted as a boolean value and I haven't been able to create a table that shows me the value as a number.

**To Reproduce**
1. Create a table with a tinyint field in mysql, add a few values
2. Import table

**Expected behavior**
I would expect that if any of the values are not 0s or 1, I would want the value to be displayed as a integer.

**Screenshots**
Example of values
![image](https://user-images.githubusercontent.com/32724827/222164743-43694f5b-2d1a-4548-bde0-9b8b1b72e2b6.png)
Example of how it is shown
![image](https://user-images.githubusercontent.com/32724827/222165424-c3c06032-d8ec-42c1-94bd-48deaa991fff.png)

**Desktop (please complete the following information):**
 - OS: Linux Debian 12
 - Browser: Firefox
 - Version: 102.8.0

**Additional context**
I guess this is because boolean values in MySQL are represented as numbers and not as an actual boolean value, right? Is this solvable?

Thanks a lot for your time

**Comment by AlejandroFNadal** [comment]
Omg, I am sorry, this does have a solution. You can change the interpreted type in the column table.

**Comment by ArnoldHueteG** [comment]
I have still this issue please open it again.

**Comment by kenshub** [comment]
I have the same issue.

Budibase 3.13.15 self hosted
MySQL DB
Data type: tinyint unsigned
We are storing numeric values between 1-9
Budibase is showing as Boolean, and is uneditable as shown in EvanGllt screenshot.
