### ISSUE TITLE
[BUDI-6659] F5 OIDC: Invalid authorization request state

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9846]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.3.16
  * App Version: 2.3.16

**Describe the bug**
I am using F5 OIDC server to communication with our internal AD and allow SSO authentication.

Here is a snapshot of an auth failed request flow:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/15d4a469-7a11-4b64-b5fd-323d0501113d/54cb6673-66cd-41d9-8606-b17cb354f5a8)

It looks like that the url encoding is missing somewhere so that the special characters contained in the state GET header is not correctly decoded by budibase-worker.

When a correct login is achieved, no special character appear in the state header so the authentication payload is correctly validated by the budibase-worker:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/070dec72-6126-44a8-8c35-94090f8be91a/1f7e1c1a-4784-4b9d-b051-1b1fe4905cbe)

**Additional context**

From this discussion: [https://github.com/Budibase/budibase/discussions/9831](https://github.com/Budibase/budibase/discussions/9831)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6659](https://linear.app/budibase/issue/BUDI-6659/f5-oidc-invalid-authorization-request-state)</sub>

**Comment by mielune** [comment]
Having the same issue working with Gravitee.io OIDC provider.
