### ISSUE TITLE
[BUDI-6692] Creating and assigning custom roles breaks all access to Budibase

### ISSUE THREAD

**Issue by galenvssysadmin** [Budibase/budibase#9860]
**Checklist**
- [✓] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 2.3.15 
  - App Version: 2.3.15 

**Describe the bug**
Whenever I create a custom role within an app, then assign it to a particular user, that user's access to the entire Budibase instance, including any apps therein, is broken.

**To Reproduce**

1. Edit any app, and create a custom role. In this case, this is a custom 'Super' role I created:

<img width="395" alt="Screen Shot 2023-03-02 at 06 54 18" src="https://user-images.githubusercontent.com/102808173/222421701-0ffb5339-db38-4e03-a9df-a6f5a5069f91.png">

2. Assign this role to a user:
<img width="849" alt="Screen Shot 2023-03-02 at 06 56 11" src="https://user-images.githubusercontent.com/102808173/222422223-03df19b5-015d-4e67-9d86-8a7332845bfc.png">

3. When this user tries to access the Budibase instance (e.g. the app portal), or any apps directly, they see this:
<img width="348" alt="Screen Shot 2023-03-02 at 06 58 57" src="https://user-images.githubusercontent.com/102808173/222422894-4a811727-124b-4b7c-b4ce-2351ce745b53.png">

A "Not Found" message.

If I revert this user's access back to any of the default roles (i.e. Basic, Power, Admin), their access is restored.

<sub>[BUDI-6692](https://linear.app/budibase/issue/BUDI-6692/creating-and-assigning-custom-roles-breaks-all-access-to-budibase)</sub>

**Comment by mike12345567** [comment]
Hi @galenvssysadmin - I've attempted to re-create this in V2.4.3 and the issue appears to be resolved - could you re-test this in the latest version of Budibase and check if you're still experiencing this issue?

**Comment by galenvssysadmin** [comment]
> Hi @galenvssysadmin - I've attempted to re-create this in V2.4.3 and the issue appears to be resolved - could you re-test this in the latest version of Budibase and check if you're still experiencing this issue?

Yes, once I updated to 2.4.2 the issue is resolved, thanks.
