### ISSUE TITLE
Allow Budi CLI to use docker subcommand, compose instead of outdated docker-compose

### ISSUE THREAD

**Issue by dnk8n** [Budibase/budibase#9871]
**Describe the feature request**
Modern Docker instructions now bundle compose as a docker subcommand. I tried to workaround the problem by `alias docker-compose="docker compose"` but it did not have the desired effect.

**Comment by mike12345567** [comment]
Hi @dnk8n - for this you can follow support for this feature here: https://github.com/PDMLab/docker-compose/pull/228
