### ISSUE TITLE
[BUDI-6691] URL variables lead to 502 bad gateways with google sheets

### ISSUE THREAD

**Issue by caseyatMission** [Budibase/budibase#9878]
**Checklist**
- [ x ] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: missioncloud

**Describe the bug**

When using URL parameters to try to open detailed views of google sheets, as in the example from the docs here, https://docs.budibase.com/docs/url-parameters, current behavior will 502 bad gateway in Preview while taking you to a valid URL in production. In preview, everything after budibase.app/ is stripped (hash identifier, tenant name, etc.), leading me to URLs like missioncloud.budibase.app/38.

I know there's a current issue related to filtering Google sheets data in #8557 so I wanted to flag this for visibility in case it helps the solve.

**To Reproduce**

1. Run the app as a Preview. 502 Bad Gateway will occur when clicking the button to trigger URL navigation, as outlined in the docs example.
2. Run in production. Button takes you to a valid URL, though the data is not filtering correctly.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2
 - Browser Chrome 110

**Production:**
<img width="940" alt="Screenshot 2023-03-03 at 11 59 44 AM" src="https://user-images.githubusercontent.com/124637427/222815069-eddf85e1-75cc-4cb4-b7d0-4acbd66f6677.png">
**Preview:**
<img width="853" alt="Screenshot 2023-03-03 at 11 58 32 AM" src="https://user-images.githubusercontent.com/124637427/222814908-21e48cc1-4de9-4cb3-866c-353f62b71f2f.png">

<sub>[BUDI-6691](https://linear.app/budibase/issue/BUDI-6691/url-variables-lead-to-502-bad-gateways-with-google-sheets)</sub>

**Comment by shogunpurple** [comment]
Hi @caseyatMission - can you try this again? Does it still occur? We've shipped some fixes recently for google sheets that should help solve this one.

**Comment by caseyatMission** [comment]
😞  Still occurring, @shogunpurple. 502 bad gateway still occurs in preview, URL is still stripped of hash and tenancy and takes me to URLs like missioncloud.budibase.app/38.

No change to behavior in production either—record repeater remains unfiltered no matter which id passed.

**Comment by mike12345567** [comment]
Hi @caseyatMission - we're currently working on a fix for the filtering - can be tracked here: https://github.com/Budibase/budibase/pull/9886

We'll look into the separate issue with URL variables causing bad gateway errors.

**Comment by adrinr** [comment]
Hello @caseyatMission. I had been looking at the error but we cannot reproduce it. Could you please provide an example spreadsheet and the destination you did set up?
<img width="824" alt="image" src="https://user-images.githubusercontent.com/15987277/224023640-21d66312-49de-4e93-81d0-a457ec498291.png">

Could you please clarify as well where are you triggering the action from? Is on the table-row click, or in a button?

It would be ideal if you could export an app reproducing this issue

**Comment by caseyatMission** [comment]
Hey, @adrinr. So from your screen shot it looks like you're trying to pass the URL differently than how it is outlined in the documentation?

I get this behavior currently from a button embedded into each table row, following the docs example at https://docs.budibase.com/docs/url-parameters, and have the button action set to Navigate To {{ New Table.WorkSearch._id }}, rather than the way you've set it up there, with /{{ Clicked row.id }}.

<img width="1074" alt="Screenshot 2023-03-09 at 8 53 32 AM" src="https://user-images.githubusercontent.com/124637427/224098441-30c1e90a-64c7-4834-8557-b1cbf6a7358b.png">

{{ New Table.WorkSearch._id }} is what autofills when selecting the table's id from the lightning bolt menu and reflects the correct table name, my custom query for that table's data, along with the _id, which is present in the schema when I run the query to double-check. 

After updating this morning to the latest point release, this request now times out in a 504 bad gateway in Preview, though I can see the URL is still stripped of the tenancy and hash. In Production, I get a working URL that looks like this https://missioncloud.budibase.app/app/24#/:id, though the data continues not to be filtered correctly.

Happy to export an example with non-sensitive data, but first maybe you could provide some clarity about whether or not the docs example is out of date?

**Comment by adrinr** [comment]
I see, @caseyatMission. I thought you were setting a row click action instead of a custom button, for this I pasted a slightly different configuration. Anyhow, the issue is the same.
You are having an issue because you missed the initial `/`, so you are redirected to the wrong URL. If you replace the destination with `/{{ New Table.WorkSearch._id }}` should get fixed.

Let me know if there if you are having further problems.
