### ISSUE TITLE
Record Level Roles

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#990]
As a user, I want to be able to prevent certain users from accessing particular records, so that they cannot access them when hitting the API directly.

We need a way to only allow a user to see rows for their direct relationship.

**For example, if you have a project table and an issues table:**
- Projects have a relationship to issues
- Users are assigned to a project
- We set a "relationship" permission on the table for that user role, meaning when a user queries that table, they can only ever see records in their relationship to that table
- When a user queries for "Projects", they will only see projects they have a relationship with

**Comment by Bytelegion** [comment]
Hi @shogunpurple , looks like it's resolved. Do we need to implement specific rules to simulate this on API level.
