### ISSUE TITLE
[BUDI-6681] New users side panel showing users not linked to account

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#9907]
In Cloud hosted version

Noticed the new user panel in the top of admin this morning and clicked into it. The user list shows a number of pending invites of users that are not associated with the account and are not pending invites.

![bb-bug](https://user-images.githubusercontent.com/110813989/223380481-f68ea337-8d81-4589-982d-d2ead9903643.png)

<sub>[BUDI-6681](https://linear.app/budibase/issue/BUDI-6681/new-users-side-panel-showing-users-not-linked-to-account)</sub>

**Comment by shogunpurple** [comment]
Thanks for reporting @andyburgessmd - this should now be resolved!
