### ISSUE TITLE
[BUDI-6719] Prevent premature closure of imported users modal

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#9956]
Remove the ability to click off this modal aside from clicking the done button. Its very easy to click off and not be able to see the passwords that have been generated. (There isn't a way to get back to this modal so the generated passwords are lost.)

![Screenshot_2023-03-09_at_10.24.25.png](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/ec068482-d65e-467e-b62b-0f557f1a575d/fab6dd4a-40ab-47ae-9ebc-6ddef2626baa)

Preventing the closure of this as much as possible would be a big help, as it would limit the steps that come afterwards if you close this screen prematurely.

* Deleting users and re-importing
* Going through the users and password resetting them individually.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6719](https://linear.app/budibase/issue/BUDI-6719/prevent-premature-closure-of-imported-users-modal)</sub>

**Comment by draqist** [comment]
I'd like to check this out
