### ISSUE TITLE
[BUDI-6721] Can't add Adminusers to App

### ISSUE THREAD

**Issue by koneubauer** [Budibase/budibase#9959]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.3.19

**Describe the bug**
I created a new app. I can't add the Admin-Users to the User List in the App. I need to do this to try out the app from a user perspective.

**Expected behavior**
Usually, I would have all the Admin-Users in the App-User list automatically.

**Desktop:**
 - OS: W10 22H2
 - Browser: Edge
 - Version: 110.0.1587.63

<sub>[BUDI-6721](https://linear.app/budibase/issue/BUDI-6721/cant-add-aminusers-to-app)</sub>

**Comment by aptkingston** [comment]
Hi @koneubauer. All admin uses already have access to all apps, so you don't need to add them manually. You can easily verify this by opening the user access side panel in the builder, and you will see all admin users are listed:
![image](https://user-images.githubusercontent.com/9075550/224699336-cbfe7833-71ef-4387-8821-9d9df6898814.png)

Notice that anyone with "admin" or "developer" roles already gets full admin access to all apps.

This is further explained if you open the dropdown:
![image](https://user-images.githubusercontent.com/9075550/224699482-7d5a1c7e-4f2b-40f9-a956-b3e2531d8891.png)
