### ISSUE TITLE
[BUDI-6722] Can't update Budibase users after ugrading to 2.4.2

### ISSUE THREAD

**Issue by galenvssysadmin** [Budibase/budibase#9966]
**Checklist**
- [✓] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 2.4.2
  - App Version: 2.4.2

**Describe the bug**
After updating to 2.4.2, I am unable to update a user's role, either at the budibase level, or at the individual app level.

**To Reproduce**

1. At the Budibase admin portal, go to the Users tab and select any user.
2. Try to change their role (e.g. from App User → Developer).

I get this error message:
![image](https://user-images.githubusercontent.com/102808173/224081225-06c3604e-836e-4ceb-b42c-94aab26f35de.png)

The same behaviour happens if I try to assign a user to a particular app or update their role within that app:
![image](https://user-images.githubusercontent.com/102808173/224081613-4d2b0392-efbc-4a69-ba73-c713686729b8.png)

<sub>[BUDI-6722](https://linear.app/budibase/issue/BUDI-6722/cant-update-budibase-users-after-ugrading-to-242)</sub>

**Comment by andz-bb** [comment]
I can recreate on andz cloud tenant on 2.4.11. Unable to change user role in the users tab. Response is `{"message":"User exists already","status":400}`

**Comment by shogunpurple** [comment]
Cheers @andz-bb - I've raised this one to sev1 as it's on the critical path. We will get a fix out for this today

**Comment by mike12345567** [comment]
Hi @galenvssysadmin - we've released a new version of the single image - if you can try updating to this and letting us know if this solves the issue for you.

**Comment by galenvssysadmin** [comment]
Updated to the latest docker image (v2.4.14) and the issue has been fixed. Thank you!
