### ISSUE TITLE
[BUDI-6743] Option picker not displaying properly.

### ISSUE THREAD

**Issue by kzkondo** [Budibase/budibase#9993]
**Checklist**
- [✔️] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.4.4

**Describe the bug**
Option picker not displaying properly.

**To Reproduce**
After updating from 2.4.15 to 2.4.4, the value set in the option picker placeholder is no longer reflected.
The default [choose an option] will remain.

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.3
 - Browser chrome, safari
 - Version latest

<sub>[BUDI-6743](https://linear.app/budibase/issue/BUDI-6743/option-picker-not-displaying-properly)</sub>

**Comment by aptkingston** [comment]
Yea this looks like a regression and I know where it's from. Will get a fix out soon.

**Comment by kzkondo** [comment]
Hi! @shogunpurple I am always grateful for your help.
